### ISSUE TITLE
Hello, world! 

### ISSUE THREAD

**Issue by edaik** [amzn/selling-partner-api-docs#1]
Welcome to the Selling Partner API (SP-API) docs repo! We're excited to share information about our upcoming new suite of API functionality with developers serving Amazon's selling partners.

To get started, please make sure to watch the repo for notifications as we make announcements via GitHub issues.

Also, we'd love to engage our community for feedback, feature requests, and questions/issues. Please feel free to log an issue and our support engineering team will respond/tag appropriately.

Thank you!
-Evan, PM for Selling Partner API developer experience

**Comment by dominickmalzone** [comment]
Awesome! Thanks @edaik 🎉

**Comment by keithbrink** [comment]
Curious if you have plans for a PHP SDK? I'm maintaining a Laravel PHP MWS package, and plan to do the same for the Selling Partner API. If you don't have any short-term plans for a PHP SDK then I will roll one of those as well.

**Comment by diego-vieira** [comment]
@keithbrink you should be able to generate PHP code using swagger-codegen. From what I'ver heard Amazon doesn't like PHP 😅

**Comment by charliecode** [comment]
> Curious if you have plans for a PHP SDK? I'm maintaining a Laravel PHP MWS package, and plan to do the same for the Selling Partner API. If you don't have any short-term plans for a PHP SDK then I will roll one of those as well.

Looks like you're in luck. Check out below link, PHP is one of the 3 currently available libraries. Wonder if they plan on adding more, Node would be great!

https://developer.amazonservices.com/tools

**Comment by weitzhandler** [comment]
Do you need to register a seller account and pay the $39 monthly fee to be able to develop with the SP-API?

I used to have a Seller account that was terminated. Now I don't want to sell but rather to develop apps utilizing the SP-API.

I wasn't sure where else I could post this, as the Seller forums are locked.

**Comment by seanevan** [comment]
Hi @weitzhandler,

Yes, a Professional Seller Account is required to be able to develop with SP-API.

Best regards,
Sean

**Comment by weitzhandler** [comment]
OMG. That's nonsense.
You should enable developing against a sandbox or dummy seller account for developers. Why would a developer have to pay $45 to try out this API? So unfair.
Anyway, I guess it is what it is, and appreciate your response.

**Comment by seanevan** [comment]
Hi @weitzhandler,

We are definitely aware of the need for a Professional Seller Account being a point of friction, and are evaluating options to address this. Thanks for the direct feedback, it helps us remain focused on such matters.

Best regards,
Sean

**Comment by GriceTurrble** [comment]
Agreed that requiring a seller account to develop software is really an unnecessary barrier to entry. I've been working on middleware for MWS connectivity for some time without being able to directly test features, relying on community members who themselves are working with sellers (plus there's no sandbox, so they have to test on live data!).

Would greatly appreciate the ability to access a test environment without needing a seller account to do so.

**Comment by seanevan** [comment]
Hi @GriceTurrble,

The lack of a sandbox is definitely a commonly-voiced pain point with MWS. I hope you'll be pleased to hear then that SP-API does include a sandbox. Currently the sandbox provides static responses. We are planning how best to support dynamic responses, so would welcome your input on the API sections/operations/scenarios that you find most critical when developing.

Thanks,
Sean
