### ISSUE TITLE
Process to get access to PII is a black box

### ISSUE THREAD

**Issue by intellifox-hq** [amzn/selling-partner-api-docs#100]
Hello there,

We've been using MWS for the past year without Personally identifiable information (PII) access.
While registering for the new access to SP-API, we went through the process to comply with every requirements detailed in the documentation and asked to get access to the PII for a specific purpose (invoice generation for French sellers).

The first answer was:

> Thank you for completing your Amazon Selling Partner API (SP-API) Developer Profile.
> You have indicated that you require Restricted roles to build an application that will be publicly available for sellers.We have determined that you currently do not qualify for this access. We apologize for any inconvenience this causes.
> You have been granted access to the SP-API roles you requested, excluding any Restricted roles.

Then we sent:

> Thank you very much for your answer and for the granted access to the SP-API for the unrestricted roles.
> Could you elaborate on the points that prevented us from being allowed to access the restricted roles ? We tried to follow the guidelines as precisely as possible and would appreciate your guidance on this.

Which was met by a:

> Thank you for your response. While we appreciate the additional information you have provided, this decision is final. We apologize for any inconvenience this causes.

What additional step can we take to alleviate this issue?

Thanks for you help

**Comment by parvathm** [comment]
Hi @intellifox-hq Can you please provide us the case id, we will check it further.

Thanks,
Parvathm , 
 Selling Partner API Developer Support

**Comment by intellifox-hq** [comment]
Hi @parvathm thank you for your answer.

Here is the case id: 6476206472 (note: this is for EU marketplaces)

Have a good day

**Comment by intellifox-hq** [comment]
Hi @parvathm 

I received this response:

> At this time, we are not approving the use of PII for new applications or updates for added functionality on an existing application. We apologize for any inconvenience this causes.

This gives an unfair advantage to my competitors.
Applications like our own that currently don't have PII access, simply cannot in any way get this PII access?

I must say I didn't anticipate this. Neither did our customers.
