### ISSUE TITLE
GB_VOEC in DeemedResellerCategory of getOrderItems API

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#1000]
As per the [docs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#deemedresellercategory) below are two enums expected in **DeemedResellerCategory** key for **getOrderItems** API.

<img width="1040" alt="Screenshot 2021-07-07 at 6 56 09 PM" src="https://user-images.githubusercontent.com/28811774/124767199-3a676180-df55-11eb-9f73-6cb9e289b9c4.png">

 But getting a new enum (**GB_VOEC**) in response for **UK marketplace** in some orders, Which is not included in docs!! 

**Is that added newly or an issue ?**

```
"DeemedResellerCategory": "GB_VOEC"
```

**Comment by avvarga** [comment]
Hi @Nilanth,

This looks like something we need to get additional details so we can research internally, therefore we will need to work with you via a support case to resolve this issue. 

Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation and post the Case ID here so we can pick it up.

Thanks,
Alejandro C
Selling Partner API Developer Support

**Comment by diegocvazquez** [comment]
@avvarga 

The current ordersV0.json model (https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json ) does not include the enumeration GB_VOEC in DeemedResellerCategory. As this value is included  in the json payload payload for UK orders so the desarializacion of the payload in "/orders/v0/orders/{orderId}/orderItems" will fail if the value in included. I will post this also in https://github.com/amzn/selling-partner-api-models/issues

Reards,

**Comment by diegocvazquez** [comment]
@avvarga 

The DeemedResellerCategoryEnum for GB_VOEC is not documented nor in swagger.
https://github.com/amzn/selling-partner-api-models/issues/146

There is a merge request from @xbaha fixing this issue, the value GB_VOEC  is already in the payload of "/orders/v0/orders/{orderId}/orderItems  

regards

**Comment by magik092** [comment]
@avvarga Our customers from time to time process an order with the value GB_VOEC in the DeemedResellerCategory field which blocks the import of orders into the sales management system. Is there a planned fix for the models to have this value listed in the JSON file?

**Comment by jadanah** [comment]
Please can this be merged https://github.com/amzn/selling-partner-api-models/pull/265
