### ISSUE TITLE
Report error    /feeds/2020-09-04/documents

### ISSUE THREAD

**Issue by yao657355700** [amzn/selling-partner-api-docs#1003]
POST
/feeds/2020-09-04/documents

content-type:application/x-www-form-urlencoded; charset=utf-8
host:sellingpartnerapi-eu.amazon.com
user-agent:My (Language=PHP/7.1.16;)
x-amz-date:20210707T095648Z

content-type;host;user-agent;x-amz-date
1fc8d63a192e5485606a3c7241233f568b29d2011c33526cb8502570075694d2

text ： {"body":{"contentType":"text/tab-separated-values;charset=UTF-8"}}

Error：
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]

**Comment by mukulcap** [comment]
@yao657355700 kindly mention how you fix this.

**Comment by yao657355700** [comment]
> @yao657355700 kindly mention how you fix this.

I set the Content-Type in the header to application/json;charset=UTF-8.
Then update the last content {"body":{"contentType":"text/tab-separated-values;charset=UTF-8"}} to {"body":{"contentType":"application/x- www-form-urlencoded;charset=UTF-8"}}
It succeeded

**Comment by mukulcap** [comment]
Thanks @yao657355700
