### ISSUE TITLE
Getting Error in Generating AWS4 Signature in SP-API in PHP

### ISSUE THREAD

**Issue by sanket-shipway** [amzn/selling-partner-api-docs#1005]
when i try to hash the canonical string then it is not matched 
$canonical_hash = "POST 
/shipping/v2/shipments/rates 
content-type:application/json 
host:sellingpartnerapi-eu.amazon.com 
x-amz-access-token:Atza|IwEBIC5IzzJp-eozsEVszq3vFlQRwE7GM8IcKYdhAHb9sFKionUr5a4xZMUR8Xd3Rkw51srzJKLt7G-nMGIbkAkzfanXDcmY7zwR1OeNZWz-uta4Pp6rGi6O7cbdIcRNiQnUfV4z4yCS9XYONQJKl4scDoAyfYhT1Rm2ZaPXTLzihRWX5BlkyUMlVfEO5qH4S0tHzmt6DUR3x8XP1130zBqNQ2iLNDtGfH7VDlh0kI-thNDzRJBLMphH_jjVtHr1gBD1Gs41P11rHal1osKZHEOyYTZaUsnRlq7qJrdkcOx0RkXSuBzj-VuJDZ368Lha47BcsNujMhp_RzCdqhPKCrjmqZ-7 
x-amz-content-sha256:beaead3198f7da1e70d03ab969765e0821b24fc913697e929e726aeaebf0eba3 
x-amz-date:20210708T173743Z 
content-type;host;x-amz-access-token;x-amz-content-sha256;x-amz-date 
1a8d32ece2659397117f2b1c66dfd1e1fc99908cacead80bb2145b4d95c77d66";

$canonical_hashed =  hash('sha256', $canonical_hash);
//$canonical_hashed = "a95dd17b921b59a597df53b3096725e418b257e90b70d5989ba2d6384f1d5937";
$stringToSign = "AWS4-HMAC-SHA256 20210708T171811Z 20210708/eu-west-1/execute-api/aws4_request ".$canonical_hashed;

but when i try to hit the request then it return as 
The String-to-Sign should have been 'AWS4-HMAC-SHA256 20210708T173743Z 20210708/eu-west-1/execute-api/aws4_request b53b152424d579e694aed4d8d4ba42d439e645c52667b0134438c9ba87bd9eef'

Note: when i try to pass this "b53b152424d579e694aed4d8d4ba42d439e645c52667b0134438c9ba87bd9eef" as a $canonical_hashed then it successfully validate the request.

**Comment by sanket-shipway** [comment]
can any one help on this?

**Comment by teddy-codes** [comment]
Use the signer provided by AWS. I know that this is a thing in go, but I am unsure about PHP.

**Comment by sanket-shipway** [comment]
@teddy-codes any idea about in python

**Comment by parvathm** [comment]
Hi @sanket-shipway,

Can you please let us know if you are following all the steps to create the canonical request as given in [this](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)? 
If you are still receiving same error please open a [support case](https://sellercentral.amazon.com/gp/mws/contactus.html?) so we can help you by checking complete request and the way you are creating canonical request. 

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by sanket-shipway** [comment]
Hi @parvathm ,

I already go through the steps for creating canonical request and that is also correct which is verified by the API response. but the signature is not matched.

**Comment by rugved1991** [comment]
Hi @sanket-shipway,

Check out the new Selling Partner API on AWS QuickStart for a quick setup of SP APIs using Python Lambda.
https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

Feel free to open issues or provide feedback on the issues page of the QuickStart.

Thanks,
Rugved
Solutions Architect, SP API.
