### ISSUE TITLE
Our app's restirected data access request case Pending Amazon Action since long time

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#1010]
Hi,
We are waiting since long time for Amazon review of our case and still get no reply.
Our developer team waiting for this and we loss time for that.
Can you please review our case?
CASE ID: 8488857661
Thanks

**Comment by hkncnr07** [comment]
Hi,
Can you please review our app case and approve that please?
Thanks

**Comment by jchavest13** [comment]
Hi @hkncnr07,

I've created an internal request to expedite the vetting of your case. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by hkncnr07** [comment]
> Hi @hkncnr07,
> 
> I've created an internal request to expedite the vetting of your case. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed.
> 
> Regards,
> Julian
> Developer Registration Specialist, SP-API

Hi,

Thanks for your answer.
You wrote my cas will be expedited but still not replied.
Can you please help us?

Thanks
