### ISSUE TITLE
PII missing, even if PII roles are enabled!

### ISSUE THREAD

**Issue by marconline** [amzn/selling-partner-api-docs#1011]
Hello, we requested and were given the PII access privilege on SP-API for our application, but we do still face issues in your response as follows.

This is what I tried:

1. converting an old MWS token to a new SP-API one: **call successful**
2. with that token, I tried calling the reports/2020-09-04/schedules with reportType = GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE: **call successful, no schedules returned (correct)**
3. with that same token, I tried calling the same endpoint with reportType = GET_ORDER_REPORT_DATA_SHIPPING: **I get an unauthorized error** (why?!)
4. even if into SP-API docs is stated differently, I thought this might be related to RDT (i.e. maybe that is a restricted operation), so I moved to a different call
5. with the same token, I tried calling the orders/v0/orders/408-2364174-6084300: **call successful, order is returned correctly**
6. now I tried calling the orders/v0/orders/408-2364174-6084300/address twice. First time, using the same token and getting (correctly) a Forbidden error. Second time, getting a fresh RDT and using it. As I got before having officially access to PII, by doing that I get a 200 OK answer, but with an incomplete response. I miss Name and Address field. Here is what I get:
`{"payload":{"AmazonOrderId":"408-2364174-6084300","ShippingAddress":{"StateOrRegion":"Rieti","PostalCode":"02032","City":"Passo Corese (RI)","CountryCode":"IT","Name":""}}}`
7. then I thought that this might be related to the convert process of the old MWS token to the new SP-API one, so I tried removing authorization from that Seller Account (A14U1GTHP2GO2K) and re-authenticating through the App Store. During the flow I saw all the permissions requested (screenshot below) but now all of my requests (even the "getOrder" one) doesn't work.

![image](https://user-images.githubusercontent.com/14978905/125081685-9271a580-e0c6-11eb-9131-f65a91052f98.png)

My opinion is that there is some issue with the fact that we have two Developer IDs for the same region (EU) and that our currently main one is different from the one that we used during all of these years (for the reason you know). So, to summarize:
converted tokens from MWS to SP-API partially work, but no PII is returned
new tokens generated from either App Store flow or Website flow don't work at all. I guess that this is related to the fact that our main developer Id is the "wrong" one (ie. 963727762970) instead of the "correct" one (ie. 971580489273)
My assumption comes out from the fact that, after I tried to connect using the two flows, I've seen two developer connected.

![image](https://user-images.githubusercontent.com/14978905/125081740-9f8e9480-e0c6-11eb-9800-07f400ecf965.png)

After I exchanged the old MWS token (the one connected to 971...) for a new SP-API token, the app disappeared.

![image](https://user-images.githubusercontent.com/14978905/125081784-afa67400-e0c6-11eb-8c99-6f5460f23530.png)

What should I try further?

Thanks for your support.
Marco

**Comment by tspicer** [comment]
@marconline any progress on this? We currently have an MWS app approved for PII. I recall seeing docs that said converting to hybrid would retain the PII access for SP-API. Based on your issue, that might be incorrect. We are currently testing a draft SP-API app and are blocked for any RDT Reporting API work. Before converting our MWS app, I would want to make sure SP-API will inherit the PII permissions else we are going around in circles.

**Comment by marconline** [comment]
@tspicer, we too have a MWS app approved for PII and I can confirm that, even if we passed to a Hybrid app, we still can access PII using MWS. I can confirm that we CANNOT access PII using SP-API, but this might be related to a mix of Developer Ids that we have, since Amazon - without any prior notice - deleted our original developer account. It simply disappeared. 

What you should check is:
a) that your developer profile on the Seller Central's developer page is enabled for ALL the roles, if not then you will have to request them. I can confirm that we have all of them enabled
b) that your app is enabled for ALL the roles. I didn't get this "two layer" of checkboxes (developer + app), but  I guess this is to provide less roles to your application, in case you need them. I can confirm that we have all of the enabled on our unique app

If this is your situation, that I guess that this might work, but I cannot guarantee!
Good luck and let me know, if you can.

Marco

**Comment by tspicer** [comment]
@marconline thanks for the reply.  This is good feedback. Out of curiosity, are you working across NA and EU regions?

**Comment by marconline** [comment]
@tspicer , we have both developer ids. Currently we have 2 dev ids for EU, 1 dev id for NA e 1 dev id for FE regions.

**Comment by tspicer** [comment]
@marconline , we have an MWS app for EU and one for NA.  Did you have to apply twice for NA and EU?

**Comment by marconline** [comment]
@tspicer : you mean that you have 2 Dev Ids? Or are you referring to two distinct apps? In any case, you will just need to apply once (a new set of SP-API keys will work for all the regions).

**Comment by tspicer** [comment]
@marconline in the past we had an NA account and another EU account for our MWS apps. We had to apply for PII separately for NA and then EU.  Are you saying that an SP-API resident in our NA account will now work across all regions/markets? I was still under the impression we had to create a distinct app under each region (or a market in that region).

**Comment by AleemFeng** [comment]
Hi,could tell me how to request  PII access privilege for applicaiton?
