### ISSUE TITLE
SP API Connection Issue

### ISSUE THREAD

**Issue by jatinthapar1910** [amzn/selling-partner-api-docs#1012]
I am trying to link an account with a developer app having SP API in place. 

While authorizing the seller with SP API I getting the following error for Amazon Callback to get accessToken and refreshToken:

`{"messageCode":"INVALID_INPUT","errorMessage":"Invalid input from dependency:MarketplaceApplicationPermissionsService","messageProperties":{"MarketplaceApplicationPermissionsService":"The permission has MWS role but no configured MWS AccountId for authorization for application : <APP ID HERE>"}}`

**Comment by ferrants** [comment]
I am experiencing this issue as well
