### ISSUE TITLE
Release date of 2021-06-30 version of Reports/Feeds API

### ISSUE THREAD

**Issue by bpyzikvc** [amzn/selling-partner-api-docs#1013]
I saw that the most recent release date is July 14th, is this still the case?

**Comment by psyklopz** [comment]
@bpyzikvc - I've spent the last few hours trying to find an answer to this, nothing in Amazon's forums or anywhere else.

The SP-API responds to requests with the new version, to create a file document.   But once you go to upload something it reports an error that the data is unencrypted and should be.

If you hear anything, would you mind updating this issue and I'll do the same?

**Comment by gokigoks** [comment]
@psyklopz Hi, does that mean the create feed endpoint has not been working all along?

**Comment by bpyzikvc** [comment]
@gokigoks The feeds api version 2020-09-04 has been working. Same with the reports api of the same version. 

We are waiting for the 2021-06-30 version of both because they eliminated the requirement of encryption. This would make my life much easier but I don't know for sure when it'll be released. July 14th is the most recent release date I have seen online.

**Comment by bpyzikvc** [comment]
@psyklopz @gokigoks Just wanted to let you know I confirmed the 2021-06-30 version has been released for both feeds and reports. Good luck with your development!

**Comment by psyklopz** [comment]
I'm still having trouble, it's giving me a SignatureDoesNotMatch error, despite the content being unsigned.  This is the identical behavior I was having two weeks back, leading me to wonder if it's actually ready for real use?

Have you had any luck, and if you have, do mind quickly explaining what you're doing to formulate the upload request?
At the moment, I'm just posting the content to the URL which was returned back from the CreateFeedDocumentSpecification request.

**Comment by gokigoks** [comment]
@psyklopz Try setting the request method as PUT instead of POST. I believe this was my issue originally as well.

**Comment by psyklopz** [comment]
@gokigoks - That's it!  You saved me a LOT of time!  I can't find anywhere in the Amazon documentation (short of one code sample in the Feeds API Use Case), where they mention that it's an upload by PUT, not POST.

For those who come after, here's a link to the best documentation I can find.
Or **if anyone from Amazon is listening**, this seems like an easy trap to fall into.  Perhaps make the docs more clear?
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md#workflow-for-submitting-a-feed
