### ISSUE TITLE
[BUG] GET /catalog/v0/categories Operation: listCatalogCategories

### ISSUE THREAD

**Issue by jmichaelterenin** [amzn/selling-partner-api-docs#1016]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
I'm expecting to see the parent-child category list associated with an asin (or sku), but I just get an 'Access Denied'.
I'm performing the request very similar to how the getCatalogItem operation is called:

/catalog/2020-12-01/items/B00C9TEOWU
marketplaceIds=ATVPDKIKX0DER&includedData=images%2Csummaries%2CproductTypes%2CsalesRanks&locale=en_US

/catalog/2020-12-01/categories
marketplaceId=ATVPDKIKX0DER&asin=B00C9TEOWU

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#get-catalogv0categories

Is this an expected result? Is this operating? Is there a better way to access product categories?

**Comment by jlevers** [comment]
@ShivikaK @parvathm could you please confirm whether or not the newer version of the Catalog API (v2020-12-01) has been published yet?

More generally, it would be very helpful if you could avoid adding models to the main branch of the `amzn/selling-partner-api-models` repository if those endpoints can't actually be called yet. I ran into this issue with the new versions of the Reports and Feeds APIs as well (see #925).

**Comment by parvathm** [comment]
Hi @jmichaelterenin,

Please check FAQs [here ](https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs) for troubleshooting access denied issues. If you are not able to find the solution, please open a support case with Request id , time stamp and application id details so we can investigate further.

Hi @jlevers ,
As per this [announcement](https://github.com/amzn/selling-partner-api-docs/issues/568) catalogItems_2020_12-01 is available.
Thank you for your feedback about avoiding adding models to main branch when the endpoints are not accessible, For Feeds and Reports it is a preview to help smooth migration planning. We understand your concern and will consider your feedback for future previews.

Thanks,
parvathm
Selling Partner API Developer Support.
