### ISSUE TITLE
Feed upload 403 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by gokigoks** [amzn/selling-partner-api-docs#1017]
I am writing a script for submitting a feed using SP-API. I am able to create a feedDocument but I am running into an issue when uploading the feed file. The error coming back is 403 forbidden error SignatureDoesNotMatch. 

I believe I am doing it correctly as I am passing the same contentType headers (createFeedDocument request and upload to s3 request) and following the encryption from the createFeedDocument response (decode iv & key -> encrypt file contents). Also, the content type is 'text/tab-separated-values; charset=UTF-8'. I'm encoding the file by opening it in a variable then encoding the var to utf8, then apply the encryption(aes-256-cbc). 

Please let me know if I missed a step. 

Side Note: 
I believe it would be best to include the request for uploading the feed document to the documentation as the steps are quite complex and the error does not really give much info.

**Comment by xiaowang123** [comment]
hi, have you resloved it?

**Comment by gokigoks** [comment]
@xiaowang123 Yes. My issue was on uploading the feed file to the s3 URL returned by CreateFeedDocument (It was returning the error in my original post). 

My fix was to stop using the Guzzle library and just use curl similar to this [post](https://github.com/clousale/amazon-sp-api-php/issues/61)
