### ISSUE TITLE
InvalidInput for getSmallAndLightFeePreview OR any POST request

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#102]
Hello,
I'm trying to use the getSmallAndLightFeePreview method with PostMan <a href='https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-small-and-light-api/fbaSmallandLight.md#post-fbasmallandlightv1feepreviews'> Documentation </a>,
data: {"items": {"asin": "XXXXXXXXXX", "price": {"currencyCode": "EUR", "amount": 10}} , "marketplaceIds": "A13V1IB3VIYZZH"},
but each time I get the Invalid Input error with no other informations, is the request malformed ?

**Comment by ShivikaK** [comment]
Hello @FexusZ 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @FexusZ 

As we haven't heard back from you, we are closing this issue. Please feel free to reach out to us if you still require further assistance with this.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
