### ISSUE TITLE
Trouble registering application for Amazon SP-API

### ISSUE THREAD

**Issue by ykuni-software-developer** [amzn/selling-partner-api-docs#1020]
Our developer profile was approved for Amazon SP-API. Based on what I have understood on the documentation, the next step that we need to follow is to register our application. We tried filling up the form with the client but there is no section that requires the IAM ARN role. From what we understood in the form, it also expects us that we have a ready application ready to deploy. But we have no application developed yet, we just want to connect to the Amazon SP-API first so we could build and test our application from the available endpoints.

I'm very confused about how to move forward with this and how to resolve this issue. What's your advice on this?

**Comment by ShivikaK** [comment]
Hello @ykuni-software-developer 

Thank you for raising this issue.

After your developer profile is approved, you should be able to see an option to "Add an application client" on the same Developer console page. Clicking on this button will direct you to app registration form where you need to fill out the form and provide details such as IAM ARN, Oauth URIs and what roles you want to add to your app. 

Once you save and exit the form, you should see an application client listed in the Dev console page with App ID and IAM ARN info next to it along with a link to view your LWA credentials required to make a valid request to SP API.

Please let me know if you still face any issues or have any further questions/concerns.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ykuni-software-developer** [comment]
Thank you for your reply. I went to the developer console page and when I clicked on the "Add New App" button there's a dropdown list if it's an android or mobile web (Please see the screenshot attached). 
![image](https://user-images.githubusercontent.com/78894093/125403104-b6472b00-e3e7-11eb-8e05-8f8ac4c5a7ca.png)

I've selected mobile web since I assumed it would lead me to register an SP-API application. I've initially filled out the form and haven't submitted it yet since there's no input information about the IAM ARN role which was specified on the docs. Am I on the right site or webpage?

**Comment by ShivikaK** [comment]
Hello,

Thank you for sharing the screenshot but it does not appear to be Seller Central's Developer Central page.

You need to login to Seller Central account and navigate to App & Services > Develop Apps page.

Can you confirm when you say your developer profile was approved, which developer profile are you referring to? 

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ykuni-software-developer** [comment]
We have submitted an application to register as a developer to access the Amazon Selling Partner API (SP-API). We have received an email that our application as a developer was approved.

**Comment by ShivikaK** [comment]
Hello @ykuni-software-developer 

Please refer to below documentation and follow the steps provided to create your SP API application.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-application

The screenshot shared previously is not the correct portal for App registration as that refers to Amazon developer Portal and not Seller Central's Developer Portal. Please navigate to correct portal to create a new SP API application.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by yao657355700** [comment]
> 你好@ykuni-software-developer
> 
> 请参考以下文档并按照提供的步骤创建您的 SP API 应用程序。
> 
> [https://github.com/amzn/ sell-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-application](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-application)
> 
> 之前分享的屏幕截图不是应用程序注册的正确门户，因为它指的是亚马逊开发者门户，而不是卖家中心的开发者门户。请导航到正确的门户以创建新的 SP API 应用程序。
> 
> 谢谢，
> Shivika Khare
> 销售合作伙伴 API 开发人员支持

Hello there,
Does the application client have to be released before it can be used?
Has been in the draft state, can I authorize other sales accounts to use it?

**Comment by jchavest13** [comment]
Hi @ykuni-software-developer ,

Can you please provide your most recent Developer Registration case ID, so I can make sure your Developer Registration was successfully completed?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by ykuni-software-developer** [comment]
Hi @jchavest13,
Our case # is CASE 8187158301

**Comment by jchavest13** [comment]
Hi @ykuni-software-developer ,

Upon review, I can confirm you have successfully completed the Developer Registration process. Please follow @ShivikaK instructions provided above (07/13/2021) to register your application, as your SP-API Developer Credentials have been already approved via case 8187158301.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by abdulrehmanGtech** [comment]
Please any one can help with amazon Selling Partner API 
I created application in selling central account I got client_id in this format {{amzn1.application-oa2-client.xxxx }} api need format like this {{amzn1.sellerapps.app.xxxx}}
  Please help me how can I find proper client id 
For api following this doc(shorturl.at/itGV9)
Api link (https://github.com/amzn/selling-partner-api-docs)

**Comment by stefanosx** [comment]
Hello,

I have also a similar problem. I have created a seller central account, and now I want to upgrade my account to a developer type but I can not find a way to apply for it and also when I try this link: https://sellercentral.amazon.de/developer/register. I am getting an error that `You do not have permission to view this page`.

Can someone please advise me what I need to do?
