### ISSUE TITLE
Report API

### ISSUE THREAD

**Issue by alpodz** [amzn/selling-partner-api-docs#1022]
We are currently testing the new Reports and the APIs associated to get data required to track/ship/and view items within the new APIs. 

Note: All APIs are returning successful request acknowledgement in both sandbox and live accounts, they are not however not providing expected results.

Issue #1: Is there any column listing or sample reports for any of the reports requestable within the API. Particularly looking for Unshipped Orders Report - GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING
Requested or Scheduled Flat File Order Report (Shipping) - GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING
Amazon does not publish any report samples nor data covered in them and therefore if your trying to import this data or create future software, there is no way to actually program towards it unless you have data in the reports themselves (and access etc etc).

**Does Amazon provide ANY template/example output/column/datatype for any reports that are callable through the API? I guess they assume your going to request the report in the 'front-end' to get a sample?**

Issue #2: Reports API has been cancelling all requests to it for many reports. I do not know the exact cause but this is occurring on both developer accounts and our client's (non-developer) seller account. The Seller account did not have any recent orders so only those that covered data with date ranges in the distant past were able to be called. However, the reports that either don't specify a date range OR are short term (60 days) reports on all of the accounts we are using auto CANCEL. These reports do indeed contain restricted data but the RDT is being accepted for retrieving the report after the fact. (though like I said before they are indeed 'CANCELLED'.

Unshipped Orders Report - GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING
Requested or Scheduled Flat File Order Report (Shipping) - GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING

They always 'auto-cancel' after 5 seconds (even made polling of GetReport to 5 minutes to make sure I didn't interrupt something). I have also tried scheduling them with a subscription and they auto-cancel there as well. 
I checked with the non-developer seller account and this account has very recent data (current day). 

Additional Notes: I have tried using data ranges of less then 30 days for both of these reports and also tried with not including a date range. They always will 'CANCELLED' immediately after 5 seconds of processing. I have paused all activity during 10 minutes after requesting a report just to make sure I'm not auto-cancelling them by simply looking at their status.

**Is this issue because the application is still in draft? (our self-authorized seller account did not have active/new orders against it so the reports were stale and beyond the 60 day look back for those reports that contain PII data. The Orders API however did return the PII Data when looking beyond the 60 days look back.**

**Comment by UoooBarry** [comment]
Same issue

**Comment by diegocvazquez** [comment]
@UoooBarry 
Thanks for responding,  are you creating the report with a RestrictedDataToken ?

**Comment by UoooBarry** [comment]
> @UoooBarry I will try it, in the documentation it is metioned that this is a restricted report Type https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md , but @alpodz it is mentioning this, will try and let you know

Thanks a lot, I will have a check as well

**Comment by diegocvazquez** [comment]
@UoooBarry , @alpodz 

I have made some progress on this, basically this only seems to affect the report GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING, at the time of creating the report, I am setting a value  for the parameters dataStartTime and dataEndTime, in this way;  ​DateTime.UtcNow.AddDays(-30), DateTime.UtcNow);
​Now  the report is wroking and not getting cancelled. I think that what it is happening is that if you dont put the dates the report is comming empty, and the SP-API markt it as cancelled. I have also implmemented the token and it seems to work okay.
If possible let me know if this is working for you guys?
Thanks for your help

**Comment by UoooBarry** [comment]
@diegocvazquez 

Thanks a lot

**Comment by diegocvazquez** [comment]
@UoooBarry 
did it work?

**Comment by UoooBarry** [comment]
> @UoooBarry
> did it work?

I just tested it, it does work perfectly

**Comment by diegocvazquez** [comment]
@UoooBarry 
No problem! I think this should be in the documentation that if the dates are missing the report is empty and this show at cancelled

**Comment by alpodz** [comment]
I guess the question is.. the dates matter even for a report which is
supposed to not be date based?

**Comment by rain-axb** [comment]
It was really helpful for you to raise issues and share test results. Thank you.

But the problem is that the documentation doesn't mention dataStartTime anywhere. It's just says "Optional".
Worst of all, we have to figure it out by guessing and testing.👎

**Comment by Xriuk** [comment]
The problem of missing examples for reports still remains... am I supposed to place an order in my own account to see a report about it?

**Comment by alpodz** [comment]
Which is against their policy.. of course.
