### ISSUE TITLE
Upload feed  - request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by ferrarinim** [amzn/selling-partner-api-docs#1023]
I'm trying to update stocks of my inventory Amazon Catalog using SP-API and C#. 
This is my code:

     ` private static IRestRequest CreateRequestFeedDocument()
      {
          IRestRequest restRequest = new RestRequest("feeds/2020-09-04/documents", Method.POST);
    
          AmazonInventory obj = new AmazonInventory();
          obj.SKU = "GD4297-44";
          obj.Available = "true";
          obj.Quantity = "20";
          string xml = string.Empty;
    
          using (var stringwriter = new System.IO.StringWriter())
          {
             var serializer = new XmlSerializer(obj.GetType());
             serializer.Serialize(stringwriter, obj);
             xml = stringwriter.ToString();
           }

              restRequest.AddParameter("contentType", xml, ParameterType.RequestBody);
              restRequest.AddQueryParameter("MarketplaceIds", "APJ6JRA9NG5V4,A1PA6795UKMFR9,A13V1IB3VIYZZH,A1805IZSGTT6HS,A1F83G8C2ARO7P,A1RKKUPIHCS9HS,A2NODRKZP88ZB9");
            AssumeRoleResponse assumeRoleResponse = null;
      
            Task.Run(async () =>
            {
               assumeRoleResponse = await GetAssumeRoleTokenDetail();
            }).GetAwaiter().GetResult();
      
            // LWA credentials for app in amazon seller central
            var clientId = AmazonCredentials.Default.ClientId;
            var clientSecret = AmazonCredentials.Default.ClientSecret;
            // generate refresh token with 'Authorize' action for app in amazon seller central
            var refreshToken = AmazonCredentials.Default.RefreshToken;
      
            var lwaAuthCreds = new LWAAuthorizationCredentials
            {
               ClientId = clientId,
               ClientSecret = clientSecret,
               RefreshToken = refreshToken,
               Endpoint = new Uri("https://api.amazon.com/auth/o2/token")
            };
      
            restRequest = new LWAAuthorizationSigner(lwaAuthCreds).Sign(restRequest);
      
            var awsAuthCreds = new AWSAuthenticationCredentials
            {
               AccessKeyId = assumeRoleResponse.Credentials.AccessKeyId,
               SecretKey = assumeRoleResponse.Credentials.SecretAccessKey,
               Region = AmazonCredentials.Default.Region
            };
      
            restRequest.AddHeader("x-amz-security-token", assumeRoleResponse.Credentials.SessionToken);
      
            restRequest = new AWSSigV4Signer(awsAuthCreds)
               .Sign(restRequest, restClient.BaseUrl.Host);
      
            return restRequest;
         }

          restClient = new RestClient(live_url_base);
                IRestRequest restRequest = CreateRequestFeedDocument();
                var response = restClient.Execute(restRequest);`

I get the following error:

          `{
            "errors": [
             { 
                "code": "InvalidInput",
                "message": "Invalid Input",
                "details": ""
              }
             ]
          }`
On the web I found this solution:

adding this line:

        `      restRequest.AddJsonBody(new { contentType = "text/xml; charset=UTF-8" });`

But now I got this error

        `<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`

Where I'm wrong?

**Comment by sugatabagchi** [comment]
@ferrarinim I am facing the same issue. 
Though I am using the version 2021-06-30,  I am getting signature not match error.

**Comment by ferrarinim** [comment]
I HAVE NOT YET BE ABLE TO SOLVE

**Comment by sugatabagchi** [comment]
@ferrarinim  - I was able resolve the issue. Here is what I have done - 
1. call the create feed API to get the URL and feed document ID
2. use the above S3 URL which is a presigned URL to upload the XML feed - this is something not correctly documented in the API spec for feeds 2021-06-30. IT SHOULD BE HTTP PUT and NOT HTTP POST.

And I was able to upload the feed and received HTTP 200 w/o a body. After this I called the feed stauts API and cofirmed the feed was uploaded correctly.
also, make sure while uploading the feed using the s3 URL use the same content type header you used in the createFeed API call.

Thanks
Sugata

**Comment by abuzuhri** [comment]
> I'm trying to update stocks of my inventory Amazon Catalog using SP-API and C#.
> This is my code:
> 
> ```
>  ` private static IRestRequest CreateRequestFeedDocument()
>   {
>       IRestRequest restRequest = new RestRequest("feeds/2020-09-04/documents", Method.POST);
> 
>       AmazonInventory obj = new AmazonInventory();
>       obj.SKU = "GD4297-44";
>       obj.Available = "true";
>       obj.Quantity = "20";
>       string xml = string.Empty;
> 
>       using (var stringwriter = new System.IO.StringWriter())
>       {
>          var serializer = new XmlSerializer(obj.GetType());
>          serializer.Serialize(stringwriter, obj);
>          xml = stringwriter.ToString();
>        }
> 
>           restRequest.AddParameter("contentType", xml, ParameterType.RequestBody);
>           restRequest.AddQueryParameter("MarketplaceIds", "APJ6JRA9NG5V4,A1PA6795UKMFR9,A13V1IB3VIYZZH,A1805IZSGTT6HS,A1F83G8C2ARO7P,A1RKKUPIHCS9HS,A2NODRKZP88ZB9");
>         AssumeRoleResponse assumeRoleResponse = null;
>   
>         Task.Run(async () =>
>         {
>            assumeRoleResponse = await GetAssumeRoleTokenDetail();
>         }).GetAwaiter().GetResult();
>   
>         // LWA credentials for app in amazon seller central
>         var clientId = AmazonCredentials.Default.ClientId;
>         var clientSecret = AmazonCredentials.Default.ClientSecret;
>         // generate refresh token with 'Authorize' action for app in amazon seller central
>         var refreshToken = AmazonCredentials.Default.RefreshToken;
>   
>         var lwaAuthCreds = new LWAAuthorizationCredentials
>         {
>            ClientId = clientId,
>            ClientSecret = clientSecret,
>            RefreshToken = refreshToken,
>            Endpoint = new Uri("https://api.amazon.com/auth/o2/token")
>         };
>   
>         restRequest = new LWAAuthorizationSigner(lwaAuthCreds).Sign(restRequest);
>   
>         var awsAuthCreds = new AWSAuthenticationCredentials
>         {
>            AccessKeyId = assumeRoleResponse.Credentials.AccessKeyId,
>            SecretKey = assumeRoleResponse.Credentials.SecretAccessKey,
>            Region = AmazonCredentials.Default.Region
>         };
>   
>         restRequest.AddHeader("x-amz-security-token", assumeRoleResponse.Credentials.SessionToken);
>   
>         restRequest = new AWSSigV4Signer(awsAuthCreds)
>            .Sign(restRequest, restClient.BaseUrl.Host);
>   
>         return restRequest;
>      }
> 
>       restClient = new RestClient(live_url_base);
>             IRestRequest restRequest = CreateRequestFeedDocument();
>             var response = restClient.Execute(restRequest);`
> ```
> 
> I get the following error:
> 
> ```
>       `{
>         "errors": [
>          { 
>             "code": "InvalidInput",
>             "message": "Invalid Input",
>             "details": ""
>           }
>          ]
>       }`
> ```
> 
> On the web I found this solution:
> 
> adding this line:
> 
> ```
>     `      restRequest.AddJsonBody(new { contentType = "text/xml; charset=UTF-8" });`
> ```
> 
> But now I got this error
> 
> ```
>     `<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`
> ```
> 
> Where I'm wrong?

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by pandabamboo90** [comment]
Hi @ferrarinim,

I was able to fix this issue, make sure you followed these steps below

1. Use PUT method, not POST (thanks @sugatabagchi for pointing this out)
2. Check your "Content-Type" header value when you create FeedDocument (Step 1). 
`Ex: "text/xml"`
3. When you call the pre-signed S3 URL, the "Content-Type" header value **MUST BE EXACTLY SAME** with the value you used in Step 1. 
`Ex: "text/xml"`
