### ISSUE TITLE
Endpoint to get customer order billing information 

### ISSUE THREAD

**Issue by ferrarinim** [amzn/selling-partner-api-docs#1024]
I'm using Amazon Selling Partner API to import orders in my application. I'm using orders/v0/orders to get the orders list and foreach order returned I call

/orders/v0/orders/{orderId}/address to get shipping address
/orders/v0/orders/{orderId}/orderItems to get items in order
/orders/v0/orders/{orderId}/buyerInfo to get buyerEmail and buyerName
Now, the last thing I need is to get the eventual billing address.

I search in SP-API documentation but I didn't find anything useful.

**Comment by kevinvenclovas** [comment]
Hi, did you get the BuyerTaxInfo in the BuyerInfo back ? https://github.com/amzn/selling-partner-api-docs/issues/1939

**Comment by braeutigamj** [comment]
I asked the "Amazon API Technical Integration Support **-Paid" in October 2021 and this was the response:
I have checked with internal teams and Unfortunately, it seems that is no option to fetch billing address through APIs at the moment. However, I would like to suggest you to try allowing billing details in your order reports in the seller central website and and fetch the GET_ORDER_REPORT_DATA_INVOICING report through Reports API and check if your required details are being fetched.

At that time, there were no plans to integrate the billing information into the API.
