### ISSUE TITLE
Some question of website authorization workflow.

### ISSUE THREAD

**Issue by Abbotton** [amzn/selling-partner-api-docs#1026]
Sorry for my bad english.

There is such a description in the [`Selling Partner Api Developer Guide`](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#constructing-an-oauth-authorization-uri):
> You need to construct OAuth authorization URIs for the marketplaces in which selling partners will authorize your application. For example, if a seller has a Seller Central account for Mexico, they will need an OAuth authorization URI for Mexico (example: ) to initiate authorization of your application. Authorizations are regional, so when the authorization is complete your application will have access to the seller's account in any marketplace in the North America region. The same concepts apply to vendors using Vendor Central.https://sellercentral.amazon.com.mx/apps/authorize/consent?application_id=amzn1.sellerapps.app.0bf296b5-36a6-4942-a13e-EXAMPLEfcd28

Based on my understanding of the website authorization workflow, I have a few questions to ask.

1. If I am creating a SAAS platform, do I need to apply for different SP-APIs and create different applications in North America, Europe and the Far East?

2. If a seller account has stores in North America and Europe at the same time, does it need to bind two stores on our platform and authorize them separately?
 
3. If a North American seller account is successfully authorized, and we have obtained the access_token of this account, can we operate the US, Mexico and Canada stores corresponding to this account according to the marketplace Id? Does this logic apply to Europe and the Far East?

I think there are many developers who have such questions and hope to get answers from the official team. thank you very much.

**Comment by vaidas-lungis** [comment]
According to 
https://github.com/amzn/selling-partner-api-docs/issues/2007

> credentials being per-region (not per-marketplace) 

And this is what I also understand from the documentation.

So answering your questions from my perspective (not the official team) 

1. One application is enough for all the regions
2. Yes, two authorizations for NA and EU
3. Access token is for region so you get access to others marketplaces if seller account supports it
