### ISSUE TITLE
How can i remove a listing?

### ISSUE THREAD

**Issue by konghou** [amzn/selling-partner-api-docs#1028]
I created a listing through amazon-sp-api Feed, and now I want to delete this listing. Which method should I use? I read all the documents, but did not find any relevant instructions. Does anyone know which method it is? Thank you.

**Comment by vikingcodes** [comment]
@konghou You need to use Feed API but OperationType type should be "Delete".

Check this link may be helpful

https://stackoverflow.com/questions/46436690/how-to-delete-product-from-inventory-on-amazon-via-mws-api

**Comment by jlevers** [comment]
You should be able to use the `deleteListingsItem` call from the Listings API -- documentation is [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md#deletelistingsitem).

**Comment by konghou** [comment]
> @konghou You need to use Feed API but OperationType type should be "Delete".
> 
> Check this link may be helpful
> 
> https://stackoverflow.com/questions/46436690/how-to-delete-product-from-inventory-on-amazon-via-mws-api

Thank you for your answer, good luck.

> @konghou You need to use Feed API but OperationType type should be "Delete".
> 
> Check this link may be helpful
> 
> https://stackoverflow.com/questions/46436690/how-to-delete-product-from-inventory-on-amazon-via-mws-api

Thank you for your answer, according to your answer has been successfully deleted, good luck.

**Comment by konghou** [comment]
> You should be able to use the `deleteListingsItem` call from the Listings API -- documentation is [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md#deletelistingsitem).

This should be another way to delete. I will try again when I have time. Thank you for your answer. Good luck.

**Comment by chapmanjw** [comment]
@konghou There are multiple ways to delete listings with feeds and APIs. The two primary methods are the `deleteListingsItem` API call mentioned above and the JSON_LISTINGS_FEED with the Feeds API. 

Documentation for reference: 

- https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md
- https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md
- https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md
- https://github.com/amzn/selling-partner-api-docs/tree/main/references/feeds-api/schemas/JSON_LISTINGS_FEED

While there are other feed types that support deleting listings, the JSON_LISTINGS_FEED is our primary offering moving forward for bulk listings programmatically.
