### ISSUE TITLE
Report "Dangerous Goods (DG) Status" not found (For Amazon developers)

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#103]
Hello,
I saw a new report in SellerCentral, 'Dangerous Goods (DG) Status' (new report), but I did not find it in either MWS or SellingPartner.
Would it be possible to add it?

**Comment by pprbhm** [comment]
Hi, We don't have any specific timeline or enough requirement of feature addition- Currently we don't offer Dangerous Goods (DG) Status' but if you can make a case of the requirement, you can start here by submitting a Support [case](https://developer.amazonservices.com/support)

**Comment by brenjt** [comment]
A good case for this report is that it's useful for our customers. I'd like to be able to alert my users when their products have been flagged as dangerous.
