### ISSUE TITLE
[BUG] Documentation - Vendor retail analytics reports

### ISSUE THREAD

**Issue by jamesp26** [amzn/selling-partner-api-docs#1032]
We noticed today that 3 new Vendor Central reports have been added to the documents. When i try and call these i get a 403:

{ code: 'Unauthorized',
       message: 'Access to the resource is forbidden',
       details: '' } 

I can call other Vendor end points for my client (such as purchase orders). My client is has brand registry and can see Sales Diagnostic / Inventory Health in Vendor Central.

The documentation mentions a 'Brand Analytics Selling Partner API role'. I cant see this mentioned anywhere else and its not one of the roles in our SPAPI app setup.  How do we get access to these?

Thanks!

**Comment by moltar** [comment]
Want to know this too!

**Comment by jamesp26** [comment]
Is there any help available on this? I've asked in the support portal and a support rep and none of them know about a 'Brand Analytics' Selling Partner API role.  Its hard to know what to do when this role is not referenced in any other section of the documentation.

**Comment by rugved1991** [comment]
Hi @jamesp26, @moltar and @Uyenkim1990,

Thanks for bringing this to our attention. The Brand Analytics role is available for use for private developers working on vendor central. For public applications using seller central its not possible to add the 'Brand Analytics' role by self-service. We are working with the internal teams to add this role on the edit app page. I will update this issue once we have it enabled.

Thanks,
Rugved
Solutions Architect, SP API.

**Comment by moltar** [comment]
@rugved1991 Any ETA on the general availability of these reports? I have a few clients who are excited about this.

**Comment by moltar** [comment]
@rugved1991 per today's "_Selling Partner API October Release Announcement_" email, which mentions "Amazon Brand Analytics Reports":

> **Search Terms report** The Search Terms report type contains click and conversion share data on the top-3 clicked ASINs by search keyword and department for a marketplace, and relative search frequency rank for each search term. Data is available at different date range aggregation levels: DAY, WEEK, MONTH, QUARTER. Requests cannot span multiple periods. For example, a request at WEEK level could not start on 2021-06-06 and end on 2021-06-19 as this would span two weeks.
> 
> If you are familiar with the Consumer Behavior dashboards in Vendor Central and Seller Central, this is the API version of the Amazon Search Terms dashboard found there.
> 
> **Market Basket Analysis report** The Market Basket Analysis report types contains data on the items that are most commonly purchased in combination with the items in the customer's basket (cart) at checkout. The data is available across different reporting periods: DAY, WEEK, MONTH, and QUARTER. Requests can span multiple reporting periods.
> 
> If you are familiar with the Consumer Behavior dashboards in Vendor Central and Seller Central, this is the API version of the Market Basket Analysis dashboard found there.
> 
> **Promotion Performance report** The Promotions Performance report type contains data to help selling partners optimize their promotions and adjust their advertising strategies. You can use this report to keep track of your promotional calendar and download performance data on past promotions.
> 
> Currently three promotion types are supported: Best Deal, Lightning Deal, and Price Discount. This report supports start dates up to two years before the current date.

Does that mean these reports are now GA?

**Comment by amistry007** [comment]
Hi @rugved1991 - could you provide an update on this issue and how soon it can be resolved?

**Comment by JeromeXapix** [comment]
Hey @jevoniuk
Following your recent announcement regarding the [new available reports](https://github.com/amzn/selling-partner-api-docs/discussions/1782) only for selling partners with the Brand Analytics Selling Partner API role, it seems that this role is not available by self-service for public applications using seller central, would you know if this is something you are currently working on? Could you give us the process to require this role in case if this is not something you will prioritise?

**Comment by estebanangel** [comment]
Is this available for private apps for Seller Central? our client is a seller and not a vendor, and they really want to get the reports listed on the docs. Thanks!

**Comment by amistry007** [comment]
Hi @rugved1991  - could you provide any update at all on this issue...we really want to get to using this as soon as possible

**Comment by amistry007** [comment]
@JeromeXapix / @estebanangel / @moltar have any of you managed to find a workaround to get these reports from the API yet?

**Comment by Javadebi** [comment]
Anyone knows how to get this report?

**Comment by jesusvalle** [comment]
I find myself in the same situation.
I have an authorized vendor, and I can't request a single report, with a "unauthorized" on all calls.

Any news?

**Comment by jlevers** [comment]
I'm running into this issue too -- I'm working on an analytics application for a client, and just discovered that I can't get these reports, which are key to the application I'm building. It seems bizarre to me that these reports would only be accessible via a private Vendor app.

Any update here? @rugved1991 @ShivikaK @parvathm

**Comment by pecalleja** [comment]
any news about this?

**Comment by kmander** [comment]
I had a call recently with folk in the SP-API team and there was acknowledgement that these reports should be available to sellers (and not just vendors), but there are some requisites that aren't yet in place – and that these will be 'coming soon'.

**Comment by NA-Dev** [comment]
I am using a private Vendor app, and still can't get any reports. No one at API will/can tell me what the issue is.
