### ISSUE TITLE
[BUG] GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 report getting You exceeded your quota for the requested resource

### ISSUE THREAD

**Issue by rohitdobariya** [amzn/selling-partner-api-docs#1033]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 report getting You exceeded your quota for the requested resource also Not able to see what is the call limit for this report.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreports

**Description of what the documentation currently says**
There is no limit for particular report Type as I am not able to see anywhere into doc 

**Description of what the documentation should say**
Doc must say that each report type limit for call

**Comment by johnkw** [comment]
In the documentation you link to it says quite clearly "Settlement reports cannot be requested or scheduled."

It would be good if that error message were improved though, since there is no "quota".  That's not a documentation issue though, that's a bug in the SP-API error message.

**Comment by ezpinsky** [comment]
@rohitdobariya The request rate limit for the getReport operation is stated in the docs here https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#get-reports2020-09-04reports

> <a name="getreports"></a>
> ### GET /reports/2020-09-04/reports
> **Operation: getReports**
> 
> #### Description
> Returns report details for the reports that match the filters that you specify.
> 
> **Usage Plan:**
> 
> | Rate (requests per second) | Burst |
> | ---- | ---- |
> | 0.0222 | 10 |

**Comment by ezpinsky** [comment]
I might add that the **real** annoying thing about the GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 report is that you can only request the last 90 days worth of data... Please @jenilew can we get this 90 day restriction removed? The data for this report can be already accessed manually in seller central going back to the beginning of a seller accounts history so why can't we access it through the reports api?

**Comment by rohitdobariya** [comment]
> In the documentation you link to it says quite clearly "Settlement reports cannot be requested or scheduled."
> 
> It would be good if that error message were improved though, since there is no "quota". That's not a documentation issue though, that's a bug in the SP-API error message.

@johnkw Thanks for the reponse but see this link that i have mentioned in the my issues ::https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreports
I am not going to request or schedule but I am get the reports.

**Comment by rohitdobariya** [comment]
@ezpinsky Thanks for the response and I already know the limit for the API calls but its always throws QuotaExceeded
Not sure why 
what is the mean by "Burst" its per day or per second what is that mean ?

**Comment by alpodz** [comment]
Burst is basically your 'queue size'... the Rate (requests per second).. (0.0222 Rate / 10 Burst for Report). 
aka you can send 10 requests instantly and get serviced but your next request after 10 won't return a success until 
0.0222 * 45 = 45 seconds later.

**Comment by alpodz** [comment]
What Amazon 'should' implement is a header that returns how much of a Queue you have remaining, this is implementing on many more advanced versions of this type of queueing method.

**Comment by rohitdobariya** [comment]
@alpodz Thanks for your suggestion but in that is the case I am just get the reports using report Types and try to get reportDocumentId its only one API call no other API call, I am getting "Excceded Qute" in https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreports and I am sure Only one call

**Comment by alpodz** [comment]
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE right?

**Comment by rohitdobariya** [comment]
> GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE

GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2

**Comment by alpodz** [comment]
Flat File V2 Settlement ReportreportType value:GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 | Tab-delimited flat file alternate version of the Flat File Settlement Report. Price columns are condensed into three general purpose columns: amounttype, amountdescription, and amount. For Seller Central sellers only.

I guess I would ask 'are you Seller Center seller?' :) I'm not even certain 'what that means' though.

**Comment by rohitdobariya** [comment]
Yes but its not related to "exceeded quota" issue
