### ISSUE TITLE
Sample Code Page does not exist

### ISSUE THREAD

**Issue by vicky-3001** [amzn/selling-partner-api-docs#104]
Hello,

I quote below from README.md:

"The sample-code directory contains sample code for using Selling Partner API. Currently, we have sample Java code available for using the Messaging API and the Solicitations API. Keep an eye out for more to come!"

sample-code is a hyperlink which points to URL https://github.com/amzn/selling-partner-api-docs/tree/main/sample-code, however this page does not exist

Can someone look into this issue please?

**Comment by rugved1991** [comment]
README fixed.

**Comment by vicky-3001** [comment]
You fixed the README by removing those lines, instead of providing sample!
