### ISSUE TITLE
Invalid method in SellersApi class

### ISSUE THREAD

**Issue by vicky-3001** [amzn/selling-partner-api-docs#105]
As per the documentation:

Step 4. Create an instance of the Sellers API and call an operation
With your AWSAuthenticationCredentials, AWSAuthenticationCredentialsProvider, and LWAAuthorizationCredentials instances configured you can create an instance of SellersApi and call an operation.

Example:

SellersApi sellersApi = new SellersApi.Builder()
  .awsAuthenticationCredentials(awsAuthenticationCredentials)
  .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
  .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
  .endpoint("https://sellingpartnerapi-na.amazon.com")
  .build();

However,  SellersApi.Builder() doesnt exist in JAR file generated using swagger from URL https://github.com/amzn/selling-partner-api-models/tree/main/models/sellers-api-model

Can someone please help?

**Comment by shuaiys** [comment]
try dependency "sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar"  in "sellingpartner-api-aa-java/target" to your project

**Comment by vicky-3001** [comment]
I found the solution.

Add below annotations 

@Data
@Builder

**Comment by reynoldsdl** [comment]
@vicky-3001 I have same issue. Where are you adding the annotations ?

**Comment by litao1254** [comment]
I have same issue. Where are you adding the annotations ?

**Comment by litao1254** [comment]
> I found the solution.
> 
> Add below annotations
> 
> @DaTa
> @builder

I have same issue. Where are you adding the annotations ?
