### ISSUE TITLE
FulfillmentInbound API Bug

### ISSUE THREAD

**Issue by 854350999** [amzn/selling-partner-api-docs#1074]
What API:
```FulfillmentInbound```

What interface:
```getShipments```

Description:
When I was using the api, when I specified ```ShimentStatusList``` as ["WORKING","CANCELLED"], he successfully returned the content to me, and when I specified the ShipmentStatusList as the ```all status```, he returned a ```null list``` to me. This makes me wonder, shouldn’t the second way ```include``` the return of the first way?

Specific code:
first:
```python
res = FulfillmentInbound(credentials=credentials,
                         marketplace=Marketplaces.GB).get_shipments(QueryType=["SHIPMENT", "DATE_RANGE"],
                                                                    ShipmentStatusList=["WORKING",
                                                                                        "CANCELLED"],
                                                                    LastUpdatedAfter="2021-07-07T00:00",
                                                                    LastUpdatedBefore="2021-07-14T00:00")
```
It successfully returned the response to me

second:
```python
res = FulfillmentInbound(credentials=credentials,
                         marketplace=Marketplaces.GB).get_shipments(QueryType=["SHIPMENT", "DATE_RANGE"],
                                                                    ShipmentStatusList=["RECEIVING",
                                                                                        "WORKING",
                                                                                        "SHIPPED",
                                                                                        "ERROR",
                                                                                        "CLOSED",
                                                                                        "IN_TRANSIT",
                                                                                        "DELIVERED",
                                                                                        "CHECKED_IN"],
                                                                    LastUpdatedAfter="2021-07-07T00:00",
                                                                    LastUpdatedBefore="2021-07-14T00:00")
```
It returned a null list to me!

**Comment by bxb100** [comment]
add `CANCELLED` , `DELETED` try again !! 
[There are ten status](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatuslist)

**Comment by 854350999** [comment]
Thanks for answering!


But in fact I have passed in all the status of the shipmentStatus, but it still returned to me empty, but when I designated the ```last shipmentStatus``` as Cancelled, it successfully returned to me. 

so whether this interface is certain Under the conditions, the last shipmentStatus will be automatically selected as the ```filter``` condition.
