### ISSUE TITLE
PII - Restricted Access Request

### ISSUE THREAD

**Issue by petyayuliyanova** [amzn/selling-partner-api-docs#1080]
Hi everyone,

We have requested access to PII data a month ago, have been asked for additional information which we provided in a timely manner. 

However, yesterday we got rejected but in the mail there wasn't a specific reason for the rejection. 

Based on the response we’ve received and our research across all related issues on this topic here in GitHub, It seems like we successfully passed the security screening step and we were in line with all privacy requirements imposed by the team of Amazon.

@ShivikaK , @jchavest13  - Would you be so kind as to help us to find out the reason for rejection so we can better determine what we should improve so we can be accepted and granted with PII access?

We believe our approach on handling PII data is up-to-date with the industry standards and best practices. Our application aims to serve many sellers in Eastern Europe & Middle East which will greatly support the development of the region.

Our Case ID is: 7059305982

Thanks in advance!

**Comment by jchavest13** [comment]
Hi @petyayuliyanova,

I've submitted an internal request to review your case regarding you request for upgrading SP-API access to Restricted being rejected.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by petyayuliyanova** [comment]
Hi @jchavest13 ,

It's been a while since you've requested internal review of our case, would you mind to share some information about it, whether it is still for review or it was rejected again?

Can you help us to find out the reason for rejection so we can better determine what we should improve so we can be accepted and granted with PII access?

Thanks again,
Petya
