### ISSUE TITLE
Generated Java SDK's getAuthorizationCode unauthorized

### ISSUE THREAD

**Issue by MaximeMarcaisBoxtal** [amzn/selling-partner-api-docs#1081]
Hi,

I have built the JAVA library as described in [Generating a Java SDK with LWA token exchange and authentication](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication), and added the dependencies to my project. My app is Published and "hybrid".

I try to [Get an LWA authorization code from MWS credentials](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md#step-1-get-an-lwa-authorization-code) from the generated AuthorizationApi, but I get the following response:
`{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`

Request:
`Request{method=GET, url=https://sellingpartnerapi-eu.amazon.com/authorization/v1/authorizationCode?sellingPartnerId=XXXXXXXXXXXXXX&developerId=XXXXXXXXXXXX&mwsAuthToken=amzn.mws.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, tag=Request{method=GET, url=https://sellingpartnerapi-eu.amazon.com/authorization/v1/authorizationCode?sellingPartnerId=XXXXXXXXXXXXXX&developerId=XXXXXXXXXXXX&mwsAuthToken=mzn.mws.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, tag=null}}`

Generated headers:
`Accept: application/json
Content-Type: application/json
User-Agent: Swagger-Codegen/1.0.0/java
x-amz-access-token: Atc|MQEB...
X-Amz-Security-Token: FwoGZXIv...
Host: sellingpartnerapi-eu.amazon.com
X-Amz-Date: 20210715T134204Z
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20210715/eu-west-1/execute-api/aws4_request, SignedHeaders=accept;content-type;host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=8f81bbf9...`

Am I missing something? Thanks for your help!

Best regards,

**Comment by xzz953337446** [comment]
@MaximeMarcaisBoxtal  I have the same problem, have you solved it now?
