### ISSUE TITLE
java.lang.NumberFormatException exception when I call getItemOffers

### ISSUE THREAD

**Issue by rohitdobariya** [amzn/selling-partner-api-docs#1082]
**Describe the bug**
java.lang.NumberFormatException exception when I call getItemOffers In Java

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getitemoffers

**Screenshots**
![image](https://user-images.githubusercontent.com/35292044/125861280-afc81e61-f3b8-4438-b9bc-92e4822c3b3e.png)

**Additional context**
Its working yesterday with same code and today is not working

**Comment by rohitdobariya** [comment]
@ShivikaK 
Can you take look this issue ? 
this was working fine yesterday same code and today not working with same input

**Comment by rohitdobariya** [comment]
@ShivikaK appreciate your support. please check this we are stuck here. this service suddenly stop working and throw exception
other wise i have to do manually API call and mapping the response to POJO  .

**Comment by parvathm** [comment]
Hi @rohitdobariya ,

I am not able to reproduce the issue with the ASIN that I am making the request. Can you please open a [support case](https://sellercentral.amazon.com/gp/mws/contactus.html?) and give us your request details, request id and time stamp so we can see which ASIN you are using? Is it possible to debug the raw response and see which attribute is throwing NumberFormatException?

Please share the case id here for reference.

Thanks,
parvathm,
Selling Partner API Developer Support.

**Comment by rohitdobariya** [comment]
@parvathm Thanks for the response but seems like working now. this is the happen with report some time its not working and sometime is goes right

**Comment by rohitdobariya** [comment]
@parvathm In the response why i am not getting parent level marketplaceId and sku and in identifier sellerSKU when we get this ?
