### ISSUE TITLE
[BUG] Documentation - Report Types

### ISSUE THREAD

**Issue by DomoES** [amzn/selling-partner-api-docs#1084]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#vendor-retail-analytics-reports

**GET_VENDOR_INVENTORY_HEALTH_REPORT** returns 
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Report Type _GET_VENDOR_INVENTORY_HEALTH_REPORT_",
      "details": ""
    }
  ]
}
```

I believe it actually needs to be **GET_VENDOR_INVENTORY_HEALTH_AND_PLANNING_REPORT** - which does work.

The other 2 (_GET_VENDOR_SALES_DIAGNOSTIC_REPORT_, _GET_VENDOR_DEMAND_FORECAST_REPORT_) work fine.

**Comment by jamesp26** [comment]
If you don't mind me asking, how did you get access to the 'Brand Analytics' role needed for these reports.  I have Brand Registered vendor clients who are desperate to have these reports automated, who we have integrated into our SPAPI app to work with PO's etc.  However, i don't see the 'Brand Analytics' role available to our app. We only see 'Amazon Fulfilment' and 'Product Listing'.

**Comment by IgniteMosquito** [comment]
Hi @DomoES !
Are you building private vendor app or you just have a public one? We were going initially to build it for Sellers, but now we're looking into it, as some brands are on VC too. Just wondering if you followed the same SP-API guideline for developers? Did you get the Brand Analytics role by default for your app?
Appreciate your help!

**Comment by DomoES** [comment]
@IgniteMosquito - You'll have to have a Domo Account to use it - so I guess private in that way.... but public to the Domo Platform I believe.

I did follow the same SP-API guidelines. The only difference for vendors was the initial authentication endpoint - everything else has been the same.

I was told by the PM team that we had to request our app to be granted access to these reports. I don't know how normal that is or anything.

**Comment by IgniteMosquito** [comment]
Thank you @DomoES ! Honestly, there's no documentation how to get access. Would you be able to ask the PM if they had to raise a support case or just contact Amazon rep? We are stuck and our Amazon rep is unavailable at the moment :(
