### ISSUE TITLE
Getting blank screen after vendor auth

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#1086]
Cannot authorize a Vendor Central account.

I'm using a completely fresh Chrome profile, without any extensions, cookies, sessions, or anything like that. This is 100% fresh, newly created profile.

And, btw, the same code works for Seller Central auth just fine.

Steps to reproduce:

# Step 1:

URL: `https://vendorcentral.amazon.com/apps/authorize/consent?.........`

# Step 2

![screenshot-20210716T100050-0hlpTAAg](https://user-images.githubusercontent.com/491247/125885139-6a170298-4bed-4316-8e5b-7931d3a8f7ec.png)

# Step 3

Just get a completely blank screen and nothing is happening.

![screenshot-20210716T100212-2XI9Zt7h](https://user-images.githubusercontent.com/491247/125885253-202e1edd-eaac-4598-a6e0-a88df4c4a75d.png)

## Console log

![screenshot-20210716T100342-SeVl2fN3](https://user-images.githubusercontent.com/491247/125885338-d1a0eabc-5dde-460a-b37e-64f2efcdf321.png)

**Comment by jamesp26** [comment]
We had this yesterday trying to auth an account from Japan. Tried in Firefox and it worked.
