### ISSUE TITLE
MWS API vs. SP-API

### ISSUE THREAD

**Issue by Sellcon** [amzn/selling-partner-api-docs#1088]
Hi, 
Could you tell me when exactly MWS API will be closed? I have an app with MWS API endpoints, what I have to do to migrate data from MWS to SP-API?  
thanks

**Comment by rohitdobariya** [comment]
@Sellcon 
the key differences between MWS and SP-API? SP-API offers all Selling Partners and third-party developers a number of improvements over MWS, such as modernized, JSON-based REST API design standards, OAuth2
Here is the migration info what will help you :: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#migrating-authorization-from-amazon-marketplace-web-service

**Comment by codingmonkey1985** [comment]
Hi Rohit,
We might be needing some assistance in this area, where we are assisting one of our partners with SP-API. Can we connect?

Harish

**Comment by rohitdobariya** [comment]
@codingmonkey1985 Yes we can connect let me know how we can connect

**Comment by Sellcon** [comment]
Hello, 
thanks.
Can you tell me what I need to do now? How long will MWS be available?

**Comment by rohitdobariya** [comment]
@Sellcon Please join here we can discuss here :: https://join.skype.com/xt7qmx9Ax0ri

**Comment by rohitdobariya** [comment]
@Sellcon seems like you joined but not hear my voice and text as well

**Comment by Sellcon** [comment]
Yes I have a problem with video chat. Do you have some video or guidebook?

**Comment by rohitdobariya** [comment]
Currently I do not have video or guidebook but you can refer this :: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#migrating-authorization-from-amazon-marketplace-web-service

**Comment by Sellcon** [comment]
How long will MWS be available?

**Comment by ezpinsky** [comment]
@Sellcon See discussion https://github.com/amzn/selling-partner-api-docs/discussions/1037 which should answer all your questions. In short, they are phasing out specific MWS APIs starting July 31, 2022.

**Comment by abdulrehmanGtech** [comment]
please someone help me about  OAuth selling partner api i am search for this amzn1.sellerapps.app.xxxx...
  i have not clue where to find it ??  i have amzn1.application-oa2-client.0272259bc......

**Comment by rohitdobariya** [comment]
> please someone help me about  OAuth selling partner api i am search for this amzn1.sellerapps.app.xxxx...
>   i have not clue where to find it ??  i have amzn1.application-oa2-client.0272259bc......

Hi @abdulrehmanGtech I will help you you can add me on Skype rohitavira or call me +91 8530429249
