### ISSUE TITLE
How to create a valid XML file using XSD

### ISSUE THREAD

**Issue by aniruddhaad** [amzn/selling-partner-api-docs#1089]
Hi,

I am not sure how to create a valid XML file using XSD for uploading inventory, prices feed. 

Is there any quick way?

Asking this because the thing which was working in MWS is not working any longer in SP-API-

<?xml version="1.0" encoding="utf-8" ?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema">
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>A3VBYO68OZ4LBR</MerchantIdentifier>
</Header>
<MessageType>Price</MessageType>
<PurgeAndReplace>false</PurgeAndReplace><Message>
<MessageID>1</MessageID>
<OperationType>Update</OperationType>
<Price>
<SKU>M680-GC6051</SKU>
<StandardPrice currency="CAD">68.98</StandardPrice><MinimumSellerAllowedPrice currency="CAD">68.98</MinimumSellerAllowedPrice>
<MaximumSellerAllowedPrice currency="CAD">68.98</MaximumSellerAllowedPrice></Price>
</Message></AmazonEnvelope>

This gives us error -
Error validating XML document - failed to locate "Price" within "Message" element.

I have validated this XML here -
https://axxv.unifysell.de/

and everything looks good.

![image](https://user-images.githubusercontent.com/8513567/125983835-57fa084d-1129-48cc-978c-36c4ce67be95.png)

Any suggestions?

**Comment by wineloy** [comment]
try this, remember to use the feedtype "POST_PRODUCT_PRICING_DATA"
`<?xml version="1.0" encoding="iso-8859-1"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
  <Header>
    <DocumentVersion>1.01</DocumentVersion>
    <MerchantIdentifier>A3GMTEBEKIOOWE</MerchantIdentifier>
  </Header>
  <MessageType>Price</MessageType>
  <Message>
    <MessageID>1</MessageID>
    <OperationType>Update</OperationType>
    <Price>
      <SKU>YOUR SELLER SKU</SKU>
      <StandardPrice currency="XXX">0</StandardPrice>
      <MinimumSellerAllowedPrice currency="XXX">0</MinimumSellerAllowedPrice>
      <MaximumSellerAllowedPrice currency="XXX">0</MaximumSellerAllowedPrice>
    </Price>
  </Message>
</AmazonEnvelope>
`

**Comment by aniruddhaad** [comment]
Thanks for the reply Wineloy. 
The issue been resolved already.
