### ISSUE TITLE
HTTP/1.1 200 OK + error is returned

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#109]
# Request

```http
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01T00:00:00.000Z HTTP/1.1
host: sellingpartnerapi-na.amazon.com
```

# Response

```http
HTTP/1.1 200 OK
Date: Thu, 12 Nov 2020 13:57:22 GMT
Content-Type: application/json
Content-Length: 108
x-amzn-RequestId: 0e14bb2d-1ed0-41ed-814d-0fce9f3ca1c8
x-amzn-RateLimit-Limit: 1.0
x-amz-apigw-id: V5bSUGX8IAMFxYg=
X-Amzn-Trace-Id: Root=1-5fad3f41-6a7b5a5a74d8f4de1b3a9278
Expires: 0
Cache-Control: no-cache
Connection: close


{
"errors" : [{
    "code": "InvalidInput",
    "message": "Invalid request, please check your input."
}]
}
```

**Comment by GenderAPI** [comment]
below is working for me
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01

**Comment by moltar** [comment]
# Request

```http
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01 HTTP/1.1
```
@GenderAPI my request seems to be identical:

# Response

```http
HTTP/1.1 200 OK
Date: Thu, 19 Nov 2020 10:36:16 GMT
Content-Type: application/json
Content-Length: 108
x-amzn-RequestId: 80d7beef-6aad-45d0-8473-ab89b9e74c17
x-amzn-RateLimit-Limit: 1.0
x-amz-apigw-id: WQCZDGJSoAMFnTQ=
X-Amzn-Trace-Id: Root=1-5fb64aa0-51bd64d5028891df228356af
Expires: 0
Cache-Control: no-cache
Connection: close


{
"errors" : [{
    "code": "InvalidInput",
    "message": "Invalid request, please check your input."
}]
}
```

**Comment by GenderAPI** [comment]
You need to sort parameters as ASC as below

`GET /fba/inventory/v1/summaries?granularityId=A2EUQ1WTGCTBG2&granularityType=Marketplace&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01`

**Comment by GenderAPI** [comment]
you can not get all the inventory from here. you can only get past 18 months

if you want to get whole inventory please use reports api /reports/2020-09-04/reports

reportType= GET_MERCHANT_LISTINGS_ALL_DATA

**Comment by moltar** [comment]
> You need to sort parameters as ASC as below

My request is identical letter by letter to yours...

> you can not get all the inventory from here. you can only get past 18 months

Ok, I only requested from `2020-01-01`, like in your example.

**Comment by moltar** [comment]
Your example:

```
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01
```

My example:

```
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01
```

What is the difference?

**Comment by GenderAPI** [comment]
change the granularityType and granularityId order

not 
?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2

it must 

?granularityId=A2EUQ1WTGCTBG2&granularityType=Marketplace

amazon request the parameters in ASC sort this may the problem

**Comment by moltar** [comment]
But your request doesn't have it changed and you say it works. How come?

**Comment by GenderAPI** [comment]
my request was 
GET /fba/inventory/v1/summaries?granularityId=A2EUQ1WTGCTBG2&granularityType=Marketplace&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01

i never do as below it was my mistake sorry
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01



please read here

# Step 3: Create the canonical query string. In this example (a GET request),
# request parameters are in the query string. Query string values must
# be URL-encoded (space=%20). The parameters must be sorted by name.
# For this example, the query string is pre-formatted in the request_parameters variable.
canonical_querystring = request_parameters


[https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html](url)

**Comment by moltar** [comment]
> below is working for me
> GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01

**Comment by GenderAPI** [comment]
this was my mistake and i just edit with correct one

**Comment by moltar** [comment]
Ok, tried sorting, but still the same error.

```http
GET /fba/inventory/v1/summaries?granularityId=A2EUQ1WTGCTBG2&granularityType=Marketplace&marketplaceIds=A2EUQ1WTGCTBG2&startDateTime=2020-01-01 HTTP/1.1
```

**Comment by GenderAPI** [comment]
did you sort it also in canonical_querystring when you generate signature key.
can you send success requests for other references?

**Comment by moltar** [comment]
> did you sort it also in canonical_querystring when you generate signature key.

Yes

> can you send success requests for other references?

Yep. Other requests work just fine.

**Comment by ShivikaK** [comment]
Hello @moltar 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by moltar** [comment]
Hi Shivika, the issue is still there.

There is clearly an issue here that isn't personal to my account. The service returns an error with 200 HTTP code. That is not right no matter how you slice it.

Thanks.

**Comment by ShivikaK** [comment]
Hi @moltar 

Can you please create a support case with us to further troubleshoot the issue? If the issue has already been reported via support case, please share the case ID and we will look into it.

Thanks

**Comment by rugved1991** [comment]
Hi @moltar,

Are you still seeing this issue? Please let us know if we can close this issue.

Thanks,
Rugved
Solutions Architect, SP API
