### ISSUE TITLE
[BUG] "Access to requested resource is denied" message for Finances

### ISSUE THREAD

**Issue by yasunori0120** [amzn/selling-partner-api-docs#1092]
Hi,

I wrote a code using python as follows:

response = Orders(marketplace=Marketplaces.JP,credentials=credentials).get_orders(CreatedAfter=(datetime.now() - timedelta(days=5)).isoformat())

This code works fine, but another code

response = Finances(marketplace=Marketplaces.JP,credentials=credentials).list_financial_events(PostedAfter=(datetime.now() - timedelta(days=5)).isoformat())

returns response with "[{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]".

Why does this happen? The method Finances requires different credentials than the method Orders?

**Comment by jhullparkseed** [comment]
I will be curious if you get any responses that help.  I am having the same problem, but in my case it is with feeds.  I have asked the same questions ands gotten no actual response that would explain why I can get orders, but I cannot process/create feeds.

Getting a link to a page I've already not just read, but performed is not enough now.

**Comment by rohitdobariya** [comment]
@jhullparkseed 
@yasunori0120 

Lets resolve your issue. It might be issue with user, role ,sts and application role which you selected during the process.

**Comment by jhullparkseed** [comment]
I would love to have this issue resolved, but I have not yet gotten any tangible information as to how/why one set of methods works while other does not.  I am happy to have Amazon review how I set up my AWS roles/policies/users, but at the root is this basic issue of ORDERS working and FEEDS not.  More specific, I can do a GetFeeds, but not a CreateDocument using the same security settings.

Is the implication we need to have different security for different REST methods?

**Comment by rohitdobariya** [comment]
@jhullparkseed I will help you in that case.
I have created doc step by step screenshot for setup AWS and Seller central app.
Please join here https://meet.google.com/eyq-wuej-kih

**Comment by ericcj** [comment]
I had this problem but solved it by checking the boxes for the appropriate roles first in my developer profile and once that was approved then they appear to also check in the edit app screen, then an hour or so later the finances api which wasn't working before started working for me
