### ISSUE TITLE
GetFeeds shows all parameters as Optional, Call returns Invalid Input

### ISSUE THREAD

**Issue by jhullparkseed** [amzn/selling-partner-api-docs#1093]
In attempting 5o get a list of feeds I received the following error:

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "feedTypes;"
    }
  ]
}

In my code I am trying to get the last 30 days of feeds placing this call:

`            GetFeedsResponse feeds = amazonFeeds.GetFeeds(null, null, null, null, createdSince, null, null);
`

And in the GetFeedsWithHttpInfo code provided by the swagger IO generator we see this:

`            if (feedTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("csv", "feedTypes", feedTypes)); // query parameter
            if (marketplaceIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("csv", "marketplaceIds", marketplaceIds)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            if (processingStatuses != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("csv", "processingStatuses", processingStatuses)); // query parameter
            if (createdSince != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdSince", createdSince)); // query parameter
            if (createdUntil != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdUntil", createdUntil)); // query parameter
            if (nextToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "nextToken", nextToken)); // query parameter
`

According to the documentation *all* parameters are optional and in my vase I *am* providing at least one parameter, created since.  So either there *IS* a required field that is not marked in the documentation or the REST call requires empty parameters

If I change the program a little I get this error:

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "feedTypes;"
    }
  ]
}

Feed Types is not listed as required in the documentation.

**Comment by ashu9900** [comment]
According to https://github.com/amzn/selling-partner-api-models/blob/main/models/feeds-api-model/feeds_2020-09-04.json#L38 either feedTypes or nextToken is required.

**Comment by AshleyBurr** [comment]
I am trying this with the sandbox endpoint and I cannot get it to successfully return anything. Only 400 error. With or without the feedTypes, createdSince, next token only or anything.. very frustrating.
