### ISSUE TITLE
Docs feature: API diagram

### ISSUE THREAD

**Issue by weitzhandler** [amzn/selling-partner-api-docs#11]
Hi,

Would be nice if you could create a UML or similar diagram of all models and functions of the API, to give devs a summarized overview of it.
An API reference would be even nicer.

Thanks

**Comment by charliecode** [comment]
> Hi,
> 
> Would be nice if you could create a UML or similar diagram of all models and functions of the API, to give devs a summarized overview of it.
> An API reference would be even nicer.
> 
> Thanks

For now all I've seen available are the API docs based off the OAS, which you can self generate with the models via Swagger. https://github.com/amzn/selling-partner-api-models 

I'd assume they already have docs via html or the like coming down the pipeline for quicker reference as they did with MWS.

**Comment by weitzhandler** [comment]
That's great.
I'll generate them and start mingling and familiarizing with the models.
I see LWA is also required to work with the API. That's another point to consider providing a sandbox, so that developers can work with dummy accounts for testing and experiments without privacy policy etc.

Thanks for your input!

**Comment by charliecode** [comment]
> That's great.
> I'll generate them and start mingling and familiarizing with the models.
> I see LWA is also required to work with the API. That's another point to consider providing a sandbox, so that developers can work with dummy accounts for testing and experiments without privacy policy etc.
> 
> Thanks for your input!

From what I'm seeing a lot of the stuff I wished we had with MWS is part of SP-API. The flow does have the "version=beta" parameter which you add to the OAuth authorization URI  in order to test stuff out during auth. You can see that in the docs under "Testing the Website workflow" https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#website-workflow

**Comment by virenderkverma** [comment]
@weitzhandler I don't think we must require LWA to work with the API. 

We have two methods to authenticate API.

- LWAAuthorizationSigner - In LWA we need  ClientId = "...", ClientSecret = "",

- AWSSigV4Signer - In AWSSigV4Signer need to login using AWS Signature Version 4  and we need AccessKeyId = "...", SecretKey = "...",    Region = "..."

Have a look for reference  - https://github.com/amzn/selling-partner-api-docs/issues/11

Let me know if I am not correct

**Comment by evdeg** [comment]
@virenderkverma You need to use the LWA signature and AWS Signature Version 4 together to properly sign every SP-API request. These two pieces are used in combination to make sure every call to SP-API is authorized and authenticated.

1. The LWA signature is used to verify the selling partner has authorized the application that is making the call.

2. The AWS Signature Version 4 is used to authenticate the caller of the API. The AWS credentials used for this are the ones that belong to the IAM User you will need to create to get a SP-API application set up.

The current sandbox functionality requires valid LWA and AWS credentials to make calls to the sandbox endpoints. You can authorize your own application by following the [Self authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization-1) steps in the developer guide. You can also use the OAuth testing workflow that @charliecode pointed out to test the OAuth flow and have selling partners authorize your application before it has been published.

Regarding your original post about diagrams and API references, you can find API references in markdown format inside the [selling-partner-api/references](https://github.com/amzn/selling-partner-api-docs/tree/main/references) directory. We will publish use case guides, which include diagrams, in several weeks. 

Thank you both for your feedback!

**Comment by weitzhandler** [comment]
> The current sandbox functionality

@virenderkverma @evdeg thanks for your replies.

According to the [authorization](https://github.com/amzn/selling-partner-api-models/blob/main/models/authorization-api-model/authorization.json) schema, you need to provide a `sellingPartnerId`, a `developerId`, and a `mwsAuthToken`.

I've setup LWA and I would like to use the [SP-API Sandbox](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox), and I was wondering if there is a way to provide a Sandbox fake developer ID. Is this supported? Do you have any plans to provide this in the future?

**Comment by evdeg** [comment]
@virenderkverma Sorry for the delay in getting back to you. Currently, the SP-API Sandbox takes in pre-defined request parameters and provides static responses. These are defined in each of the API models for each operation in the "x-amazon-spds-sandbox-behaviors" objects under "responses". If you see request parameters defined you need to use those in your request to get the static response that is defined in the model. On the other hand, if you do not see parameters defined then you do not need to provide any request parameters to get the response.

Using the Authorization API model as an example, the [getAuthorizationCode](https://github.com/amzn/selling-partner-api-models/blob/76dfb38d8973918af4c65a3bc10b653b400385f2/models/authorization-api-model/authorization.json#L78-L89) operation has the following under 200 responses:

`"x-amazon-spds-sandbox-behaviors": [
              {
                "request": {
                  "parameters": {}
                },
                "response": {
                  "payload": {
                    "authorizationCode": "ANDMxqpCmqWHJeyzdbMH"
                  }
                }
              }
            ]`

When you call this operation using the sandbox endpoint you will need to use your application credentials and sign the request like a real production call but you do not need to provide any request parameters in this case. If the operation succeeds you will get the authorizationCode value defined in the JSON. If you do provide request parameters you will most likely get an error. Likewise, if a request parameter is defined you must provide the exact request parameters and values defined in the model to get the expected response back successfully. We are planning to build upon this functionality in the future.

Please let us know if you have any additional questions.

Thanks!
Evan
