### ISSUE TITLE
GET /fba/inventory/v1/summaries -- Query parameter [startDateTime] value is not a valid ISO date-time object

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#110]
Seems like `startDateTime` is mandatory, yet it is documented otherwise?

---

Docs: https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md#parameters

> All inventory summaries with available details are returned when the startDateTime and sellerSkus parameters are omitted.

# Request

```http
GET /fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=A2EUQ1WTGCTBG2&marketplaceIds=A2EUQ1WTGCTBG2 HTTP/1.1
host: sellingpartnerapi-na.amazon.com
```

# Response

```http
HTTP/1.1 400 Bad Request
Date: Thu, 12 Nov 2020 14:06:37 GMT
Content-Type: application/json
Content-Length: 202
x-amzn-RequestId: 2f4832d2-bc25-47b5-8561-d0015ac9a67b
x-amzn-RateLimit-Limit: 1.0
x-amz-apigw-id: V5cpCHTBoAMFfNg=
X-Amzn-Trace-Id: Root=1-5fad416c-2351eeca6c5e6ca329764d3f
Expires: 0
Cache-Control: no-cache
Connection: close

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "This is an invalid input",
      "details": "Query parameter [startDateTime] value is not a valid ISO date-time object."
    }
  ]
}
```

**Comment by moltar** [comment]
Also see #109, where a `startDateTime` value is provided, but an error (with 200 status) is thrown anyways.

**Comment by ShivikaK** [comment]
Hello @moltar 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support
