### ISSUE TITLE
Cannot read property 'functionalityId' of undefined

### ISSUE THREAD

**Issue by subash047** [amzn/selling-partner-api-docs#1103]
I am trying to submit the app to Amazon from the page https://sellercentral.amazon.com/sellingpartner/developerconsole/application/listing?appId=my-app-id. While the page loads I am seeing the following issue on the console.
{
    "m": "Expected field name to contain only valid characters, but it was App information.  It can only contain letters, numbers, and these symbols: .:@_/-",
    "name": "Error",
    "csm": "v5 ueLogError stack",
    "logLevel": "ERROR",
    "attribution": "Unspecified",
    "pageURL": "https://sellercentral.amazon.com/sellingpartner/developerconsole/application/listing?appId=amzn1.sp.solution.5fa9e30d-4177-466f-9694-5de67346f933",
    "f": "https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js",
    "l": "16",
    "s": [
        "Error: Expected field name to contain only valid characters, but it was App information.  It can only contain letters, numbers, and these symbols: .:@_/-",
        "at e.default (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:16:31445)",
        "at e.value (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:1:37924)",
        "at e.value (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:16:32722)",
        "at https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:47:12845",
        "at t.value (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:47:12489)",
        "at t.value (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:47:12583)",
        "at t.value (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:56:195727)",
        "at e.value (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:56:326459)",
        "at $a (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:32:70699)",
        "at Ga (https://d3o2tl81jsi9tx.cloudfront.net/sellingpartner/developerconsole/application/listing/main.517caf7487611b131421.min.js:32:70494)"
    ],
    "t": 1731
}

And also if i try to click on save and continue I am getting errors on the console regarding the undefined property. 

Uncaught TypeError: Cannot read property 'functionalityId' of undefined
    at main.517caf7487611b131421.min.js:formatted:68292
    at Array.map (<anonymous>)
    at e.value (main.517caf7487611b131421.min.js:formatted:68288)
    at e.value (main.517caf7487611b131421.min.js:formatted:68265)
(anonymous) @ main.517caf7487611b131421.min.js:formatted:68292
value @ main.517caf7487611b131421.min.js:formatted:68288
value @ main.517caf7487611b131421.min.js:formatted:68265

**Comment by 401009641** [comment]
![03](https://user-images.githubusercontent.com/20614254/126426737-35e8ebbd-1c2f-46ae-b7e8-24b64f8848b6.png)
This problem also occurred when I re-edited the app submission, and it has not been resolved for 3 months.
