### ISSUE TITLE
 searchDefinitionsProductTypes returns empty list for marketplace India

### ISSUE THREAD

**Issue by SouravPal95** [amzn/selling-partner-api-docs#1105]
I have been trying to use the feeds API to create product listings. However, any productType value I provided rendered a processing report with an error of `invalid or unsupported product type`. So I decided to use the search product definitions API endpoint for marketplaceID(A21TJRUUN4KGV) for India. It returned empty for LUGGAGE and every other keyword that I tried. Then I tried without any keyword and received `PRODUCT` as the only available type. Then on using it with requirements attribute `LISTING` I received a processing report with error message that cannot use product type `PRODUCT` to create products which is an a problem because that is all I can see...

**Comment by chapmanjw** [comment]
Hi @SouravPal95, resolving this issue in favor of the comment on this issue: https://github.com/amzn/selling-partner-api-docs/issues/1025#issuecomment-884512466. Thanks!
