### ISSUE TITLE
I submitted the application application, but there is no response for more than a month. Please review it for me. Thank you very much. My CASE ID is 8528379511

### ISSUE THREAD

**Issue by userbabu** [amzn/selling-partner-api-docs#1106]
**CASE ID :8528379511**

Please help me to review, we have completed the sandbox test, and now we need to officially submit the application

**Comment by ezpinsky** [comment]
Not sure if you've done this already, but if you don't hear back from them within a few days of making a case, it helps to take the initiative and respond to the case asking for a response. Do it once a day until they respond. It puts your case higher on whatever list they have.
