### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by roger-sanchez117** [amzn/selling-partner-api-docs#111]
Hi!

I am trying to create a new feed document, apparently I have an error when signing the request, the code that I am using to sign works correctly for GET requests, but with this one (POST) it tells me that the signature they calculate does not match the one that I send. I suspect that it is due to the body of the request, since in a GET request I do not send this data and it works correctly.

Error message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

The error indicates that my canonical request and string to sign should be as follows:

The Canonical String for this request should have been

'POST
/feeds/2020-09-04/documents

content-type:application/x-www-form-urlencoded; charset=utf-8
host:sellingpartnerapi-na.amazon.com
user-agent:ecommerce/1.0 (Language=PHP/7.2; Platform=Windows/10)
x-amz-access-token:xxxxxxxx
x-amz-content-sha256:affa87dbc404ba24c31d6dbf76692084f7f41ec57e7d2935db51abe24d34d529
x-amz-date:20201112T153447Z

content-type;host;user-agent;x-amz-access-token;x-amz-content-sha256;x-amz-date
affa87dbc404ba24c31d6dbf76692084f7f41ec57e7d2935db51abe24d34d529'

The String-to-Sign should have been

'AWS4-HMAC-SHA256
20201112T153447Z
20201112/us-east-1/execute-api/aws4_request
aa1bbba25bc0585b9b198fd18a67fbeeb786247f57abd070bbbc49639855895a'

My current canonical request and string to sign are as follows:

'POST
/feeds/2020-09-04/documents

host:sellingpartnerapi-na.amazon.com
user-agent:ecommerce/1.0 (Language=PHP/7.2; Platform=Windows/10)
x-amz-access-token:xxxxx
x-amz-date:20201112T153455Z
content-type:application/x-www-form-urlencoded; charset=utf-8
x-amz-content-sha256:affa87dbc404ba24c31d6dbf76692084f7f41ec57e7d2935db51abe24d34d529

host;user-agent;x-amz-access-token;x-amz-date;content-type;x-amz-content-sha256
affa87dbc404ba24c31d6dbf76692084f7f41ec57e7d2935db51abe24d34d529'

'AWS4-HMAC-SHA256
20201112T153455Z
20201112/us-east-1/execute-api/aws4_request
b42685bc02135de47118786f709c07445bc27d38802b1257b844a6c4fcbf69ea'

The only difference I see is that the headers are not in the same order, but checking the documentation it never says I have to sort them.

I hope you can help me. Thanks a lot.

**Comment by rogersv** [comment]
You can not control the order when the headers are sent but they should be sorted when signed. 
See https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html

```
Create the canonical headers and signed headers. Header names
# must be trimmed and lowercase, and sorted in code point order from
# low to high. Note that there is a trailing \n.
```

**Comment by roger-sanchez117** [comment]
Thank you very much for your answer. I have already found the solution, the problem was that I was including the content-type header in the canonical request and the signed headers. I also removed the x-amz-content-sha256 header. After doing this, I was able to make my request successfully.
