### ISSUE TITLE
[FEATURE] Documentation

### ISSUE THREAD

**Issue by uk-2** [amzn/selling-partner-api-docs#1112]
What's best practice on  

How to export amazon listings with (images,price,description,bullet points)  into our app?

Our purpose if we have a new user and they want to pull all their listings into our app 

How can we do this ?

**Comment by chapmanjw** [comment]
@uk-2 Currently, the Reports API offers the only mechanism to retrieve broad data in bulk a given sellers listings: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/reports-api-use-case-guide/reports-api-use-case-guide_2021-06-30.md. Such as the `GET_MERCHANT_LISTINGS_ALL_DATA` report.

If the seller is the brand owner of the related ASINs for their listings, you could also use the Catalog Items API to retrieve attributes (like description, etc.) for the item: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md. (In the case they are not the brand owner, you can still retrieve summary details like the title and thumbnail of the main image).
