### ISSUE TITLE
 How can I get product pictures from SP-API?

### ISSUE THREAD

**Issue by shuaiys** [amzn/selling-partner-api-docs#112]
I want to get the seller's product picture, but I can't find the specific API, can somebody please help?

**Comment by charliecode** [comment]
Hello @shuaiys! I haven't had the time yet to go over all the APIs but I think I found a solution for you. It appears things have changed a bit for the SP-API in this regards. For the MWS API you would use the "Products" api along with the GetMatchingProduct or GetMatchingProductForId operations. But for the SP-API I don't see a "Products" api but rather a [catalog-items-api](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md). It looks like the [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#getcatalogitem) and [listCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#listcatalogitems) operations are what you're looking for. Once you get the response you'll want to drill down to the [Item](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#item) and pay attention to the [AttributeSetList](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#attributesetlist) which should contain the "SmallImage". There you can find the [Image](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#image) along with it's URL, Height and Width. Hope this helps, maybe someone else has a better solution.

**Comment by shuaiys** [comment]
Thank you for your reply, but what is given in AttributeSetList seems to be a small picture of the product, not the main picture of the product. I don't know if these two concepts are the same

**Comment by charliecode** [comment]
@shuaiys If there's another way via the API to get a different picture, I have not used it. If you're able to find another way I'd love to hear the solution.

**Comment by intellifox-hq** [comment]
Unfortunately the API is quite dry in this regard. If you want the 1500x1500 image, you need to get it yourself without Amazon's help.

**Comment by shuaiys** [comment]
thank you, I will try other methods first.

**Comment by ZzwDaiZi** [comment]
In the previous MWS, the images obtained ended with ul400.jpg. I replaced 400 with 1600 to get high-definition images. In spapi, I haven't done this step yet. You can try it.

**Comment by pprbhm** [comment]
Hi, Looks like there are few suggestions for the issue. If you still face similar problem, you can try creating [support case ](https://developer.amazonservices.com/support) and we can help you.
