### ISSUE TITLE
FTXGatewayService.estimateLtlShipment returned error code: 412

### ISSUE THREAD

**Issue by gaurav-webs** [amzn/selling-partner-api-docs#1120]
@ShivikaK  @parvathm 

When I am calling `estimateTransport` every time it returns the same error,

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "FTXGatewayService.estimateLtlShipment returned error code: 412",
      "details": ""
    }
  ]
}
```
also not found any information in documentation regarding this error.

Also when I check in the seller center in **4. Shipping charges** section

It displays **"Unable to calculate shipping cost, please try again later."** something like this,
 
![screenshot-sellercentral amazon com-2021 07 22-16_28_10](https://user-images.githubusercontent.com/78719205/126629413-54c02f31-5110-4a11-9326-e3e3454b2626.jpg)

Can anyone explain why I am getting this?

**Updated (20-Aug-2021 08:45 AM(IST)) :-**

**_As I am still getting the above error but, after doing the following steps it solves, <ins>but this is not the solution<ins>_**,

As this issue is solved but for that,
Step1:-  I have passed the `SellerDeclaredValue` in `putTransportContent` API (As per the doc this field is optional).

![screenshot-github com-2021 08 20-09_00_09](https://user-images.githubusercontent.com/78719205/130174798-8550a39f-27bb-4990-a74d-87c649ef5fa7.jpg)

Step2:- Then need to login in Seller Center > Edit That shipment and then I press any up, down, left, right key from the keyboard in the Seller Declared Value textbox.
Step3:- Then I called `estimateTransport` and I am getting a successful response.

as this is not the solution.
as per the doc, the first thing the **seller declared value is optional**. but If I am not sending that value I am not able to call `estimateTransport`. because in seller center edit shipment page it display  **"Unable to calculate shipping cost, please try again later."**.
Also, every time user is not able to follow the above step that, the user calls the `putTransportContent` API then login to the seller center and edits the shipment and then presses any key seller declared value textbox, then again go to the website and then call `estimateTransport` API.

@ShivikaK  @parvathm 

any solution regarding this error?

**Comment by nafberger** [comment]
I had the same error, trial and error shows that the problem occurs after 27 pallets, that the max that amazon allows on a truck

try the estimate on seller central and u will see the errors coming up

**Comment by defenderjim** [comment]
@gaurav-webs 
Did you ever find out why you are getting error 412?
Same thing is happening to me, can't figure out the problem.
