### ISSUE TITLE
[FEATURE] Documentation FEEDS Use Case unclear on download feedDocument

### ISSUE THREAD

**Issue by jhullparkseed** [amzn/selling-partner-api-docs#1129]
Using the Feed Use Guide I have been able to get to the point where I successfully create a feed using CreateFeed.

Subsequently I can then check on the status using a combination of GetFeeds or GetFeed which then gets me to where I want more information.  Information like successes, failures, warnings and any messages.  It is not clear how I get this information.

In step 6:

Step 6. Download and decrypt the feed processing report

the documentation states to use the URL passed back from the getFeedDocument to download the file/report(?) and then there is a sample Java program to show how.  First, with 2021-06-30, there is no longer a need to decrypt.  The when I look at the java ode sample there are import statements that refer to:

import com.amazon.spapi.documents.DownloadHelper;

It takes digging to realize that is part of the project, but that is not very helpful in an already complex set of steps.  Even if you provided the raw request that would help better then just a java sample.

I feel it would be helpful to  create a sample of how to download the feedDocument in either c# or PHP as you do for the sellingpartnerAPIAA library.

**Comment by rohitdobariya** [comment]
@jhullparkseed I have implemented feed API into java spring boot. If you need to understand let me know I will show you full step and use case well.

**Comment by MST1122** [comment]
@rohitdobariya are you using FeedAPI to create new Listing also? if yes, then how are generating forms for input from users based on product type?

**Comment by rohitdobariya** [comment]
@MST1122 I have done using template and validate the data based on template.

**Comment by ashu9900** [comment]
> Using the Feed Use Guide I have been able to get to the point where I successfully create a feed using CreateFeed.
> 
> Subsequently I can then check on the status using a combination of GetFeeds or GetFeed which then gets me to where I want more information. Information like successes, failures, warnings and any messages. It is not clear how I get this information.
> 
> In step 6:
> 
> Step 6. Download and decrypt the feed processing report
> 
> the documentation states to use the URL passed back from the getFeedDocument to download the file/report(?) and then there is a sample Java program to show how. First, with 2021-06-30, there is no longer a need to decrypt. The when I look at the java ode sample there are import statements that refer to:
> 
> import com.amazon.spapi.documents.DownloadHelper;
> 
> It takes digging to realize that is part of the project, but that is not very helpful in an already complex set of steps. Even if you provided the raw request that would help better then just a java sample.
> 
> I feel it would be helpful to create a sample of how to download the feedDocument in either c# or PHP as you do for the sellingpartnerAPIAA library.

The usecase guide for 2021-06-30 does not mention decrypting the processing summary report. https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md#step-7-download-the-feed-processing-report

Are you referring the correct version of the corresponding usecase guide?

**Comment by MST1122** [comment]
@rohitdobariya can you share the template and explain a bit. I will be really grateful.

**Comment by rohitdobariya** [comment]
@MST1122 add me on Skype rohitavira

**Comment by abuzuhri** [comment]
> Using the Feed Use Guide I have been able to get to the point where I successfully create a feed using CreateFeed.
> 
> Subsequently I can then check on the status using a combination of GetFeeds or GetFeed which then gets me to where I want more information. Information like successes, failures, warnings and any messages. It is not clear how I get this information.
> 
> In step 6:
> 
> Step 6. Download and decrypt the feed processing report
> 
> the documentation states to use the URL passed back from the getFeedDocument to download the file/report(?) and then there is a sample Java program to show how. First, with 2021-06-30, there is no longer a need to decrypt. The when I look at the java ode sample there are import statements that refer to:
> 
> import com.amazon.spapi.documents.DownloadHelper;
> 
> It takes digging to realize that is part of the project, but that is not very helpful in an already complex set of steps. Even if you provided the raw request that would help better then just a java sample.
> 
> I feel it would be helpful to create a sample of how to download the feedDocument in either c# or PHP as you do for the sellingpartnerAPIAA library.

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp
