### ISSUE TITLE
What is feed content?

### ISSUE THREAD

**Issue by roger-sanchez117** [amzn/selling-partner-api-docs#113]
Hi!

I need to upload products to Amazon. After reading the API documentation I started to follow the tutorial to submit a feed found in the use guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md.

After creating a feed document as indicated in step 1, the createFeedDocument operation returns a presigned url in which I have to load the content of the feed (as indicated in step 2).

My doubts are:
1- What type of data should I upload to this pre-signed url as feed content?
2- Could you give me an example of a preferred code in the PHP language?

I clarify that my question IS NOT HOW TO ENCRYPT AND UPLOAD the data, rather WHAT DATA SHOULD I SEND ENCRYPTED in order to create a product listing.

**Comment by danpq14** [comment]
Same question In Java. I don't know how can I set feed content.

**Comment by rogersv** [comment]
Did you read this https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md#product-and-inventory-feeds

**Comment by roger-sanchez117** [comment]
> 
> 
> Did you read this https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md#product-and-inventory-feeds

Hi, @rogersv 

Yes, I had already read that documentation, but to be honest I don't quite understand it.

Should I build an XML file that is valid according to the XSD file of the type of feed I want to create and that is what I should send as feed content?

**Comment by rogersv** [comment]
This might help too https://images-na.ssl-images-amazon.com/images/G/02/rainier/help/XML_Documentation_Intl._V158772716_.pdf. The document is old but it looks like it is the same format now.

**Comment by roger-sanchez117** [comment]
> 
> 
> This might help too https://images-na.ssl-images-amazon.com/images/G/02/rainier/help/XML_Documentation_Intl._V158772716_.pdf. The document is old but it looks like it is the same format now.

Thank you. I will read it and I will be sharing any questions.

**Comment by danpq14** [comment]
Hi @roger-sanchez117 !
Can you give me some sample code about this issue when you complete ? It'll help me so much. Thank you

**Comment by roger-sanchez117** [comment]
> 
> 
> Hi @roger-sanchez117 !
> Can you give me some sample code about this issue when you complete ? It'll help me so much. Thank you

Hi @danpq14 

I read the documentation that @rogersv gave me, I understood the xsd that are provided for the feed types and I made a code to be able to generate an xml from the xsd.

I am working on the process to submit feeds, but I still cannot complete it, so I cannot confirm that this works.

I recommend you read the mentioned documentation.

**Comment by MST1122** [comment]
@roger-sanchez117 where can I contact you? I'm also stuck with this Feed creation.

**Comment by mukulcap** [comment]
Does anyone has any idea on how many messages can we upload in one batch?
