### ISSUE TITLE
report api GET_MERCHANT_LISTINGS_ALL_DATA is not real-time

### ISSUE THREAD

**Issue by wojiushimogui** [amzn/selling-partner-api-docs#1130]
I want to get all the items list(active/inactive/Incomplete) of the seller, I studied the report api, and I can get it by using GET_MERCHANT_LISTINGS_ALL_DATA, but it is not real-time,After a day, still no update.
for example , when items status change from Inactive to active，but report is old。

can somebody please help?

**Comment by johnkw** [comment]
This report is normally updated pretty quickly. If it's still wrong a day later you should open a Seller Support ticket.

**Comment by aidensgithub** [comment]
They don't send incomplete items. Which is very weird. It is mandatory. Somebody look at this.

**Comment by johnkw** [comment]
This is not a general SP-API issue, and should be closed, or updated with more detail from Seller Support. The prior comment also seems unrelated.
