### ISSUE TITLE
Lack of informations for ServiceFeeEventList in Financial Events API

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#1131]
Hi, I need help . I am not sure if I am missing the documentation or the api itself contains missing details or have bugs.
I created a script, a simple cron job that would fetch financial events with date range range), so for example from June 01 - June 30. The shipment event list and refund event list are all good, however for Service Fee event list, not enough information on it, example posted_date or amazon order id. The only available fields returned are `Fee Type(str), FeeAmount{}`.

With this kind of data, there is no way for me to filter the Servicefee based on date. Is there any one encountered this ? @ShivikaK  can you please take a look at this ? This is very important as servie fee lists are part of the  calculation on amazon fees we implemented in our app. See screenshot provided.
![bug1](https://user-images.githubusercontent.com/4607692/126776980-11255139-9735-4936-9ed4-fd7d934c7605.png)

Regards

**Comment by omrihaim** [comment]
Hey @ianrussel did you find any solution for this issue? Thanks in advance

**Comment by ianrussel** [comment]
@omrihaim unfortunately no.

**Comment by osso1007** [comment]
Hi, I'm having the same problem, could you help me? Thanks in advance o_sso_j@naver.com
