### ISSUE TITLE
Feeds API processing report error code 4002006 

### ISSUE THREAD

**Issue by aidensgithub** [amzn/selling-partner-api-docs#1133]
I was able to successfully download and decompress the response of feed processing report.
However, I don't understand the error, and how to rectify it based on the error code and messages displayed.
The error description says the "Version" field is wrong, I tried using both "1.0" and "2.0" for it, the same error code.
**Processing report payload:**
`{
  "header": {
    "sellerId": "A3UY995ZK*****",
    "version": "2.0",
    "feedId": "415520018***"
  },
  "issues": [
    {
      "code": "4002006",
      "severity": "ERROR",
      "message": "L???attribut 'version' ne correspond pas ?? la valeur requise."
    }
  ],
  "summary": {
    "errors": 1,
    "warnings": 0,
    "messagesProcessed": 0,
    "messagesAccepted": 0,
    "messagesInvalid": 0
  }
}`
**And the message file uploaded looks like so:**
`{
  "header": {
    "sellerId": "A3UY995ZK*****",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 1,
      "sku": "ABCTEST",
      "operationType": "UPDATE",
      "productType": "PRODUCT",
      "requirements": "LISTING",
      "attributes": {
        "parentage_level": [
          {
            "marketplace_id": "A13V1IB3VIYZZH",
            "value": "Parent"
          }
        ],
        "skip_offer": [
          {
            "marketplace_id": "A13V1IB3VIYZZH",
            "value": true
          }
        ],
        "externally_assigned_product_identifier": [
          {
            "marketplace_id": "A13V1IB3VIYZZH",
            "type": "ean",
            "value": "4712900735536"
          }
        ]
      }
    }
  ]
}`
It would be also very convenient to include error codes and their detailed description in documentation and their approximate solution.

**Comment by chapmanjw** [comment]
@aidensgithub You can find the JSON Schema's for the JSON_LISTINGS_FEED here: https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/schemas/JSON_LISTINGS_FEED/listings-feed-schema-v2.json.

The `version` in the header is statically `2.0` right now.

**Comment by aidensgithub** [comment]
@chapmanjw Yes, I know where the schema is, I am getting the same error with using `2.0`, that is mysterious to me, moreover I have tried to construct the message using productType definition schema for `PRODUCT` attributes as well. Everything seems legit to me.

**Comment by aidensgithub** [comment]
A little update on this issue. The above mentioned error was fixed, however the error description and code doesn't correspond to the actual problem at all.
Error was due to incorrect indication of `Document Id` during `createFeed` operation and the error was saying that there is something wrong with `version` ...my bad. But it doesn't change the fact that error codes and description doesn't give any valuable information. Currently I'm getting another error code of `4000000` which says: **`An internal error has occurred. Please try again.`**. And guess what, I don't know what should I do with this error `"description"`. `:/`

**Comment by chapmanjw** [comment]
@aidensgithub That error code is our generic catch all in the case something unexpected happened on our backend. Create a developer support case referencing this GitHub issue (and me - John Chapman, so it routes to my team internally), along with the seller id and feed reference id where you received that error. It’s more than likely you hit a bug on our side and we can dive deeper into that with a support case. Thanks.

**Comment by zhenshixz** [comment]
@chapmanjw Our team also encountered the same problem, can we arrange to deal with it as soon as possible, otherwise we will not be able to help users complete the publishing operation

**Comment by zhenshixz** [comment]
@chapmanjw May I ask whether the publication process can be completed correctly through your new API? Have you verified it?

**Comment by chapmanjw** [comment]
@zhenshixz Yes, with the product types supported by the Product Type Definitions API, the JSON_LISTINGS_FEED supports publishing new items. Creating a support case is the best way for us to investigate (and fix) the specific issue you are facing. For transparency, most of the "generic" error messages are a failure on our end to tell you what actually went wrong (which would tell you how to fix the payload) under certain edge case scenarios. Once you open a support case, let me know what the case id is so that I can get it pulled to my team for investigation. Thanks!

**Comment by 401009641** [comment]
你们写的Bug出奇的高，这样的团队还有存在的价值？
