### ISSUE TITLE
Inventory Sync - SubmitFeed Successor

### ISSUE THREAD

**Issue by IvanMConnex** [amzn/selling-partner-api-docs#1135]
Hello, how are you doing today? I am messaging you in regards to your new API.

Currently, we are using your previous, XML-based API to support inventory syncs (Among others) for our mutual customers, and while we've been able to update all our other endpoints in line with your more REST-based, JSON-oriented migration, your new inventory API eludes us.

Specifically, we use your MarketplaceWebService API to submit a feed request containing our customers' QuickBooks SKUs as a memory stream. We've looked at all the available documentation on your GitHub page, and we are unable to locate the successor to this format.

When it comes to having customers sync their inventory from QuickBooks into their Amazon accounts, should this still be implemented using the old MarketplaceWebService API? If so, what will need to change, if anything? If this will no longer be supported by the time the migration is finalized, what should we use instead - particularly, where should the SKUs go, exactly?

Please let me know at your earliest availability, and if you need more information from me regarding this issue. Thank you, and have a great weekend.

**Comment by chapmanjw** [comment]
We recently launched new JSON-based APIs and feeds that support accepting inventory updates. For reference:

- Listings Item APIs -> For submitting listing updates one at a time, the PATCH operation allows you to update just inventory (separately from all the data required to create a new listings with a PUT): https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md
- JSON_LISTINGS_FEED -> New feed type for the Feeds API that uses the same format as the Listings Item APIs: https://github.com/amzn/selling-partner-api-docs/tree/main/references/feeds-api/schemas/JSON_LISTINGS_FEED
- Product Type Definitions APIs -> APIs that provide JSON Schemas describing the data requirements for both the Listings Item APIs and JSON_LISTINGS_FEED: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md

**Comment by IvanMConnex** [comment]
Hello again, and thank you for your response - it was very helpful, and we've been able to make headway with the code migration on our end.

However, I see that one of the required fields in ListingsItemPutRequest is productType. What exactly should this field be? I ask because I looked through your documentation, and there is no clear indication as to what all the different productTypes are. Where might I be able to find this, or is this something that's seller-specified that we would have to make a separate call for?


Thank you, and have a good day.

**Comment by chapmanjw** [comment]
@IvanMConnex The Product Type Definitions API provides JSON Schemas for each of the supported Amazon product types to support creating new products with listings. For updating inventory, or other common attributes, you can use “PRODUCT” as the product type.
