### ISSUE TITLE
How to get the product asin created through the feed ?

### ISSUE THREAD

**Issue by qskane** [amzn/selling-partner-api-docs#1137]
I am using the `createFeed` API to listing a new product. Everything is going well. I can already see my newly created product on the seller central website.
My question is, **how do I get the newly assigned ASIN of the product?**
I currently use the `listCatalogItems` API to obtain an ASIN through SKU. Is this the recommended practice?
Any help is appreciated!

**Comment by aidensgithub** [comment]
@qskane Hello! Please leave a mail at **aidenscoding@gmail.com** I'll try to help

**Comment by MST1122** [comment]
@qskane @aidensgithub I am also trying to list a new product through FeedAPI. But I'm facing a problem with Product Type (Category) based HTML form generation and after submitting the form preparing that Data to be useable for FeedAPI. 

How are you guys doing that part? Any help or suggestion will be really appreciated.

**Comment by qskane** [comment]
@MST1122 Maybe you should take a look at this link, the content page you need is at the very bottom. 

[https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf
](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf)

**Comment by aidensgithub** [comment]
Are you guys using XML for listing, not JSON?

**Comment by aidensgithub** [comment]
I was about to create some discord channel, to help each other, shall we?)

**Comment by qskane** [comment]
@aidensgithub  Thanks for the solution provided.

>You mentioned: My question is, how do I get the newly assigned ASIN of the product?
For this part I assume you can use Reports API to retrieve all inventory items, it will return both ASIN of the new item and your SKU.
This one for example: GET_MERCHANT_LISTINGS_DATA 
selling-partner-api-docs/reporttype-values.md at main · amzn/selling-partner-api-docs (github.com)

**Comment by MST1122** [comment]
@aidensgithub 

> I was about to create some discord channel, to help each other, shall we?)

please create the channel and share the link at sikandartariq25@gmail.com
