### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by Emizy** [amzn/selling-partner-api-docs#1138]
New to amazon seller api endpoint usage, After going through all the documentation and i decided to try order endpoint in order to retrieve orders for an account but i got a 404 error, below is my url

https://sellercentral-europe.amazon.com/orders/v0/orders/?CreatedAfter=2021-07-14T15%3A42%3A57%2B00%3A00&MarketplaceIds=ATVPDKIKX0DER&MarketplaceIds=A39IBJ37TRP1C6

any help or correct way of structuring the url 

language: python

Please help #urgent

**Comment by ianrussel** [comment]
&MarkerplaceIds=['markerplace1','marketplace2']

**Comment by rugved1991** [comment]
Hi @Emizy,

Check out the new Selling Partner API on AWS QuickStart for a quick setup of SP APIs using Python Lambda.
https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

Feel free to open issues or provide feedback on the issues page of the QuickStart.

Thanks,
Rugved
Solutions Architect, SP API.
