### ISSUE TITLE
Quantity field in Inventory Report "GET_MERCHANT_LISTINGS_DATA" empty

### ISSUE THREAD

**Issue by PhenomEY** [amzn/selling-partner-api-docs#1141]
Hello,

i am retrieving a inventory report "GET_MERCHANT_LISTINGS_DATA" but the quantity field is emtpy for every position.
Any ideas what i missed?

**Comment by PhenomEY** [comment]
I need to retrieve the following data from active listings: ASIN, Quantity available at Amazon, SKU and ArticleName

do you recommend other endpoints to get this data?  So far i could not find anything besides the inventory reports

**Comment by yongchuan** [comment]
> I need to retrieve the following data from active listings: ASIN, Quantity available at Amazon, SKU and ArticleName in real time
> 
> do you recommend other endpoints to get this data? So far i could not find anything besides the inventory reports

have you  resolve it ?
