### ISSUE TITLE
No payload and errors in new version (2021-06-30) of report and feed API

### ISSUE THREAD

**Issue by gaurav2262** [amzn/selling-partner-api-docs#1142]
https://github.com/amzn/selling-partner-api-docs/discussions/1107

As per this announcement new version of the feed and report API is release.

But in the new version of Report and Feed API all method, there is no payload and errors is available on API result.

Following is just an example, but all the methods of Report and Feed API didn't return payload and errors.

Here is the old version response of `createReport` API

![screenshot-github com-2021 07 26-14_50_23](https://user-images.githubusercontent.com/16912752/126966204-6858788d-5398-4f51-8096-a57a89d1cabd.jpg)

Here is the new version response of `createReport` API

![screenshot-github com-2021 07 26-14_50_37](https://user-images.githubusercontent.com/16912752/126966242-0591b0a8-310d-4243-b8e7-16a58d1f198a.jpg)

As compared to the older version the payload and errors were removed from the response.

Can anyone explain why this was removed?

Is this correct and we need to handle responses like this or there is something error and we need to handle the response like an old response?

**Comment by gaurav2262** [comment]
@damianelder 

Thank you for your reply,

But as I review all other APIs like InboundShipment API, Order API, and other API we still get the payload and errors in API response, 
but only in Report API and Feed API, there is no payload and errors in response.

That's why I have the question that this response is correct and we need to handle the new response like this or something is wrong in the documentation and we need to handle the  response like an old response.

**Comment by damianelder** [comment]
the latest version for reports has no references to payload, the other may not be updated to the same I guess.   In my case I see getReports() method replaced getPayload() for getReports operation.

![image](https://user-images.githubusercontent.com/64195537/127137814-3af63027-fe22-41bc-8fdc-10498d79c1da.png)

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreportsresponse
