### ISSUE TITLE
How can i get my listing result

### ISSUE THREAD

**Issue by danielwu2014** [amzn/selling-partner-api-docs#1146]
I used this interface to successfully publish and return a submissionId, but how do I get the publication result? I did not find the document to get the results of the listing
https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md

**Comment by xiaoyu-tamu** [comment]
same question here 👍

**Comment by yizeku** [comment]
@danielwu2014 

**Listings Items API** how to add a new product?

**Comment by corbin-munce** [comment]
Same, how can we use the submissionId to get the result of operation?

**Comment by chapmanjw** [comment]
@danielwu2014 The `submissionId` is primarily used as a tracking identifier that can be used as a reference when investigating issues when contacting support. There is currently no API for retrieving data by the `submissionId`.

With that said, however, you are able to retrieve the final state of the listing with the `getListingsItem` operation: https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2021-08-01.md#getlistingsitem.

Additionally, there are two push notifications you can subscribe to: `LISTINGS_ITEM_STATUS_CHANGE` and `LISTINGS_ITEM_ISSUES_CHANGE` - https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md#notificationtype. These notifications can nudge your application to move to the next step in your workflow when a new item has been created, issues have been logged, etc.

**Comment by corbin-munce** [comment]
> There is currently no API for retrieving data by the `submissionId`

I think it is reasonable to expect a result from an API call when referencing the submission id.  Can this please be added as an enhancement?

**Comment by Fahed-selmi** [comment]
> @danielwu2014 The `submissionId` is primarily used as a tracking identifier that can be used as a reference when investigating issues when contacting support. There is currently no API for retrieving data by the `submissionId`.
> 
> With that said, however, you are able to retrieve the final state of the listing with the `getListingsItem` operation: https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2021-08-01.md#getlistingsitem.
> 
> Additionally, there are two push notifications you can subscribe to: `LISTINGS_ITEM_STATUS_CHANGE` and `LISTINGS_ITEM_ISSUES_CHANGE` - https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md#notificationtype. These notifications can nudge your application to move to the next step in your workflow when a new item has been created, issues have been logged, etc.

Hey, I see the changes in  `getListingsItem` but the product details page in not updated also when I caal `getCatalogItems`  I get the old values. Any thoughts?
