### ISSUE TITLE
Saudi Arabia marketplace

### ISSUE THREAD

**Issue by Tomer781** [amzn/selling-partner-api-docs#1148]
Amazon Saudi Arabia was one of the marketplaces of Europe region in mws.
We saw that Saudi Arabia isn't one of the supported marketplaces in sp api. Why is that? How can sellers from this marketplace connect via SPAPI (and how should we migrate existing Saudi Arabia sellers from MWS to SPAPI)

**Comment by damianelder** [comment]
hey can you share that reference, thanks.

**Comment by Tomer781** [comment]
Updating that the Saudi Arabia was added to the sp-api supported marketplaces and to developer guide and it's clear now that it's part of the EU region
