### ISSUE TITLE
Japan, Australia and Singapore

### ISSUE THREAD

**Issue by Tomer781** [amzn/selling-partner-api-docs#1149]
In MWS Japan, Australia and Singapore were divided into two regions, one for Japan and one for Australia and Singapore. In Sp-Api they are all part of the Far-East region. I'm tring to understand what will happen if I take an mws token of Japan/(Australia/Singapore) Seller and migrate it to an Sp-Api RefreshToken. Will the RefreshToken be valid for all the Far-East?

**Comment by teddy-codes** [comment]
Assuming that what happens with Europe is constant in the sp-api, you will have access to all marketplaces in the region.

**Comment by Tomer781** [comment]
@xbaha Haven't tried it yet, but a solution architect at Amazon told me that a migration from mws accessToken of JP should provide me RefreshToken that is valid for all the Far-East Region. The same with AU & Singapore.
That's a little bit weird because it means that a seller that authenticated with mws only for the "Japan region" suddenly gives me permissions to access JP+AU+Singapore, I'll try to remember to update here when I have a final answer. If I don't do that in the next month, Remind me to.
But I'm not sure we're talking on the same thing. My issue is really migration related.
Just to make clear, If a seller "sp-api authenticate you" to the Far-east region, you should have permissions to his JP+AU+Singapore marketplaces data.
