### ISSUE TITLE
[BUG] An internal error has occurred. Please try again for feed type JSON_LISTINGS_FEED 

### ISSUE THREAD

**Issue by 348786639** [amzn/selling-partner-api-docs#1150]
feedType : JSON_LISTINGS_FEED
encryption the file and upload.
{
	"header": {
		"sellerId": "xxxxxxxxxx",
		"version": "2.0",
		"issueLocale": "en_US"
	},
	"messages": [{
		"messageId": 1,
		"sku": "My-SKU-B11112",
		"operationType": "UPDATE",
		"productType": "AIR_MATTRESS",
		"attributes": {
			"safety_data_sheet_url": [{
				"language_tag": "en_US",
				"marketplace_id": "ATVPDKIKX0DER",
				"value": "www.safetysheetsRus.com/hazardous_substance/msds.pdf"
			}],
			"brand": [{
				"value": "this is brand",
				"language_tag": "en_US",
				"marketplace_id": "ATVPDKIKX0DER"
			}],
			"bullet_point": [{
				"value": "this is bullet_point",
				"language_tag": "en_US",
				"marketplace_id": "ATVPDKIKX0DER"
			}],
			"country_of_origin": [{
				"value": "US",
				"marketplace_id": "ATVPDKIKX0DER"
			}],
			"item_name": [{
				"value": "this is item_name",
				"language_tag": "en_US",
				"marketplace_id": "ATVPDKIKX0DER"
			}],
			"item_type_keyword": [{
				"value": "this is item_type_keyword",
				"marketplace_id": "ATVPDKIKX0DER"
			}],
			"product_description": [{
				"value": "this is product_description",
				"language_tag": "en_US",
				"marketplace_id": "ATVPDKIKX0DER"
			}],
			"supplier_declared_dg_hz_regulation": [{
				"value": "ghs"
			}],
			"ghs": [{
				"marketplace_id": "ATVPDKIKX0DER",
				"classification": [{
					"class": "health_hazard"
				}]
			}],
			"parentage_level":[{
				"marketplace_id": "ATVPDKIKX0DER",
				"value":"parent"
			}],
			"batteries_required":[{
				"marketplace_id": "ATVPDKIKX0DER",
				"value":false
			}]
		}
	}]
}

call api /feeds/2020-09-04/documents/{feedDocumentId} for process file

{
    "header":{
        "sellerId":"xxxxxxxxxxxx",
        "version":"2.0",
        "feedId":"52853018835"
    },
    "issues":[
        {
            "messageId":1,
            "code":"4000000",
            "severity":"ERROR",
            "message":"An internal error has occurred. Please try again."
        }
    ],
    "summary":{
        "errors":1,
        "warnings":0,
        "messagesProcessed":1,
        "messagesAccepted":0,
        "messagesInvalid":1
    }
}

**Comment by aidensgithub** [comment]
@348786639 Please refer to my issue, would recommend to contact developer support and open case. They answer pretty quickly, include all information needed and refer to your github issue. I had the same error, didn't figure this out. And please don't forget to close this issue with valid solution. Thanks!
https://github.com/amzn/selling-partner-api-docs/issues/1133
