### ISSUE TITLE
Feeds are not being processed. Stuck as IN_PROGRESS

### ISSUE THREAD

**Issue by aidensgithub** [amzn/selling-partner-api-docs#1151]
Feeds for listing and updating existent won't process.
**Feed status:**
```
class Feed {
    feedId: 416216018835
    feedType: JSON_LISTINGS_FEED
    marketplaceIds: [A1F83G8C2ARO7P]
    createdTime: 2021-07-27T13:25:01+00:00
    processingStatus: IN_PROGRESS
    processingStartTime: 2021-07-27T13:25:06+00:00
    processingEndTime: null
    resultFeedDocumentId: null
}
```
**Feed payload (message)**
```{
   "header":{
      "sellerId":"A3UY995ZK*****",
      "version":"2.0",
      "issueLocale":"en_US"
   },
   "messages":[
      {
         "messageId":1,
         "sku":"ABCTEST",
         "operationType":"UPDATE",
         "productType":"PRODUCT",
         "requirements":"LISTING_OFFER_ONLY",
         "attributes":{
            "purchasable_offer":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "currency":"GBP",
                  "our_price":[
                     {
                        "value_with_tax":"SomeValue"
                     }
                  ]
               }
            ],
            "color":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "language_tag":"en_US",
                  "value":"Black"
               }
            ],
            "condition_type":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "value":"used_like_new"
               }
            ],
            "country_of_origin":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "value":"SomeValue"
               }
            ],
            "item_name":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "language_tag":"en_US",
                  "value":"SomeValue"
               }
            ],
            "list_price":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "value_with_tax":"SomeValue",
                  "currency":"GBP"
               }
            ],
            "externally_assigned_product_identifier":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "type":"ean",
                  "value":"SomeValue"
               }
            ],
            "recommended_browse_nodes":[
               
            ],
            "fulfillment_availability":[
               {
                  "quantity":2,
                  "fulfillment_channel_code":"DEFAULT"
               }
            ],
            "bullet_point":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "language_tag":"en_US",
                  "value":"SomeValue"
               }
            ],
            "product_description":[
               
            ],
            "brand":[
               {
                  "marketplace_id":"A1F83G8C2ARO7P",
                  "language_tag":"en_US",
                  "value":"SomeValue"
               }
            ],
            "supplier_declared_dg_hz_regulation":[
               
            ]
         }
      }
   ]
}
```
I tried to validate message payload with productTypeDefintion and meta schema using the following [example](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/amazon-product-type-definition-meta-schema-v1.example-java.md). And no issues were found.
I checked all required parameters for listing.
@chapmanjw Could you please provide a full example of message Feed for listing and update with override for JSON_LISTINGS_FEED, maybe something wrong with message, which may crash the API and hangs it in_progress?
I tried many ways removed some attributes, added some, tried according to schema. I just can't figure this out.
Also I can't connect support and open case on every my test attempt which ends up like this, they only abort frozen feeds and don't provide the reason behind it or solution.
Thanks!

**Comment by gaurav2262** [comment]
@aidensgithub

You need to check `processingStatus` of feed using `getFeed` until the feed moves into one of the following states: DONE, CANCELLED, or FATAL. When the feed moves into the DONE state you have to call  `getFeedDocument`.

Note :- It takes some time to move the status from IN_PROGRESS to another status.

**Comment by SouravPal95** [comment]
This usually used to take a couple of minutes......but now....its been around 7-8 hours....and its suck IN_PROGRESS. Trying to push new feed gets the new feed stuck IN_QUEUE

**Comment by jamieroyce** [comment]
I have similar issue, both feeds for POST_ORDER_FULFILLMENT_DATA and POST_INVENTORY_AVAILABILITY_DATA have resulted in processingStatus "IN_QUEUE" for over 48 hours. After 2 hours on hold with Amazon and several "dropped calls" where I had to re-submit a new ticket, I still don't have this resolved. This is the first time I am using the Feeds API so I may have something obvious wrong, but have not been able to figure this out yet. 

This is what my POST_ORDER_FULFILLMENT_DATA feed looks like: 

`		content: `<?xml version="1.0" encoding="utf-8"?>
		<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
			<Header>
				<DocumentVersion>1.02</DocumentVersion>
				<MerchantIdentifier>A3RW***</MerchantIdentifier>
			</Header>
			<MessageType>OrderFulfillment</MessageType>
			<Message>
				<MessageID>1</MessageID>
				<OrderFulfillment>
					<AmazonOrderID>114-6430768-6694***</AmazonOrderID>
					<MerchantFulfillmentID>123456(made up number, don't know if I need this field)</MerchantFulfillmentID>
					<FulfillmentDate>2022-02-24T15:09:11+00:00</FulfillmentDate>
					<FulfillmentData>
						<CarrierCode>UPS</CarrierCode>
						<ShippingMethod>Standard</ShippingMethod>
						<ShipperTrackingNumber>94001111***</ShipperTrackingNumber>
					</FulfillmentData>
					<Item>
						<MerchantFulfillmentID>1</MerchantFulfillmentID>
						<Quantity>1</Quantity>
					</Item>
				</OrderFulfillment>
			</Message>
		</AmazonEnvelope>`,
		contentType: 'text/xml; charset=utf-8'`

I create a feed document, upload the feed with a success response, but no matter how long I wait, the result of getting the feed info is: 

`get_feed_infos {
  processingStatus: 'IN_QUEUE',
  marketplaceIds: [ 'ATVPDKIKX0DER' ],
  feedId: '39117301****',
  feedType: 'POST_ORDER_FULFILLMENT_DATA',
  createdTime: '2022-02-25T16:57:44+00:00'
}`

**Comment by vamaship-saud-qureshi** [comment]
Feeds API is such a pain.
No clear documentation, no examples either.
Mine failing with
**We encountered an internal error. Please try again.**

**Comment by KajdeMunter** [comment]
Yes this is annoying. Has anyone solved this issue yet?

Where do I even contact amazon so that they can cancel the stuck feed? How will we ever know why it is stuck in the first place?
