### ISSUE TITLE
[BUG]getreport has document  garbled code

### ISSUE THREAD

**Issue by rockyspruce** [amzn/selling-partner-api-docs#1155]
dear guy, i has some trouble, and need you help
api: getreport
datetime:  2021-07-20 ~   2021-07-21
reporttype : GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
remark: just appeared in one day, the question was the same when try to create a new report with the same datetime period again
the response body as follow:
!Q���4�I ߠ^��Yٖ���Z��Y��N/��88` �ͺ�!�{-$�%�x��w�.�Aq����k^��A�}%��F^��>����w����=V/�&�r�[n�F�w���6��Bo4�^�I~lL��7p{�����_u��W&�����0
��I3N�O�}��E0�Z��$���(�w5
{M/�6v��]����q��k��Y�V�۟�w#/��R�����D�7���dމ��m�B/��t�G��#O~l��^m��F��~���ak�Bs8	�pu�������'�����ɏ������'&W����øh�"��z'ǯ7�0����C���?��}zQ���ZE�`
�2�ޞ�mx�AE�Iи�*�,��t��^���?�'�i�&DK��"�*�P(]
��-^(�ւRmv_-a3�4��i[
�0Z$��H��O\~��� �!{+��t���Wh��O��\�t�K�1m�z�����
�^<�ݦw�|�μ�P(�N�����ت#ג��P��º�묑�֣��Ⱥqc���N݆�}H֫^k�\���G�W�Ç��p�p������^<����������s|@�»��;,�'~�j�h��[�@�r
���9#G�\���i��a�-���B8Xfی�j������W�	V��	�9�+��祶��՟��$
�ו���o���#
����x�	")ϲ$�w���נ~k��ɵ�`A%\��	�?��Y'/2�r�b0A�'�W+�X�N�oOy���i�h�&}����v�����~k�'�������{�ZJ��$��>|̬7����*
; #����7�E�e�$���f�?8 ������=>X������U�v��x!� Oz��44�f?���Gsu�m1rs��`����:/}��ԿT
_��;�

**Comment by damianelder** [comment]
Which version?  Assume 2020-09-04 as report documents are encrypted ad compressed and you would need to handle this

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md

The latest version they are not.

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md

**Comment by rockyspruce** [comment]
thanks very much , it's ok。just as u said, I havn't processed the compressed.
