### ISSUE TITLE
Retrieve Order Shipping Addresses From Multiple Order ID's

### ISSUE THREAD

**Issue by alexmillman2394** [amzn/selling-partner-api-docs#1157]
I need a way to bulk retrieve the shipping address by order id.

Right now the only way I can find is to make a single request the API for this information using the Orders API. We have about 10k - 20k orders a month, so to get this information for each order, we'd need to do 10k-20k individual requests to the API.

Am I missing documentation somewhere? Or is this the only way to get the data?

**Comment by DawidWawrzyniak** [comment]
You can use Reports Api.
