### ISSUE TITLE
Correct Canonical String and String To Sign as well as signature but invalid signature error.

### ISSUE THREAD

**Issue by mashhood1995** [amzn/selling-partner-api-docs#116]
I am trying to connect to SP-API for obtaining orders Created After a certain date but i have encountered this error:
`{ "errors": [ { "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'GET / CreatedAfter=20201116T125444Z&MarketplaceId=ATVPDKIKX0DER host:sellingpartnerapi-na.amazon.com x-amz-access-token:Atza|IwEBIMzLxXsQchY-WGw-nRN9iUxIDSzhppj2I359K3q5v0b7oFLrt_1Wvul8JvA7vUZjaoCfDxmTKOaIts6QhDvRMm1McB7IJtT8ktHpTElKarRndKH5ckCph_GqqQc2OuSfmS3VSHD7v1pqh8rIzaKIC9v9HcGdx-NGIgLLT0HlDkxaLC0r2U8NueAg9mGINtt5e7L8lQ7RMa9N-WQCFb8TADIEsSpwKK3WShira0z_0hFNoKKYFbxDxMlh5tI4jSCOGEZ_h8crnUJ_UrPY6vFaU01f1rNrHtD5aDYfeJCE_aax0S4_37wtwmDfTqvAiKxl7Y6uwO7uuRtjQo20_NMbpNir x-amz-date:20201116T125444Z host;x-amz-access-token;x-amz-date e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' The String-to-Sign should have been 'AWS4-HMAC-SHA256 20201116T125444Z 20201116/us-east-1/execute-api/aws4_request 9a54fa21548b508a4026f1927f3a67878e537600c1952f3dfb96e60a59ed89be' ", "code": "InvalidSignature" } ] }`

String to Sign as well as Canonical Request string exactly matches with that generated by my code . Signature generated by the code also seems to be correct when i verify it by using test credentials from amazon site . 
Here is my code . I am using netsuite suitescript 2.0 which is based on javascript. I have been trying since few days but couldn't figure out the so,lution for this issue . 

`var headers={
          'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'
        }
        var body={
          'grant_type': 'refresh_token',
          'refresh_token': refreshtoken,
          'client_id': client id here,
          'client_secret': client secret here
        };

        var response=https.post({
          url: 'https://api.amazon.com/auth/o2/token',
          headers: headers,
          body: body

        });

        var accessToken=JSON.parse(response.body).access_token;

        log.debug('Response is ',accessToken); //token retrieved successfully

        

        //Calculating timestamp in ISO 8601  format
        var today = new Date();

        var ISO8601Date=today.getUTCFullYear()+''+pad((today.getUTCMonth()+1))+''+pad(today.getUTCDate())+'T'+pad(today.getUTCHours())+''+pad(today.getUTCMinutes())+''+pad(today.getUTCSeconds())+'Z';

       log.debug('ISO 8601 date format ', ISO8601Date);
        

        log.debug('ISO 8601 date format ', today.getUTCFullYear()+'  '+(today.getUTCMonth()+1)+'  '+today.getUTCDate()+'T'+today.getUTCHours()+'  '+today.getUTCMinutes()+'  '+today.getUTCSeconds()+'Z');

       

        uri='GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceId=ATVPDKIKX0DER&CreatedAfter='+ISO8601Date;

        

        method = 'GET';

        
        canonical_uri ='/';
        

        canonical_querystring=encodeURI('CreatedAfter='+ISO8601Date+'&MarketplaceId=ATVPDKIKX0DER');

        

        canonical_headers = 'host:' + 'sellingpartnerapi-na.amazon.com' + '\n' + 'x-amz-access-token:' + accessToken + '\n'+ 'x-amz-date:' + ISO8601Date + '\n';

        signed_headers = 'host;x-amz-access-token;x-amz-date';

      
    var hmacsha256Data = CryptoJS.SHA256('');
    var payload_hash = CryptoJS.enc.Hex.stringify(hmacsha256Data);

  

        log.debug('Payload hash data ',hmacsha256Data);
        log.debug('Payload payload_hash ',payload_hash);

        

       canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash;

        log.debug('URI String ',canonical_request);

        /*************** TASK 2: CREATE THE STRING TO SIGN************* */
        var datestamp = today.getUTCFullYear()+''+(today.getUTCMonth()+1)+''+today.getUTCDate();

        region = 'us-east-1';
        service='sellingpartnerapi-na';
        algorithm='AWS4-HMAC-SHA256';

        log.debug('Date Stamp is '+datestamp);

       

        var canonicalsha256Data = CryptoJS.SHA256(canonical_request);
        var canonical_hash = CryptoJS.enc.Hex.stringify(canonicalsha256Data);

        log.debug('canonicalsha256Data is ',canonicalsha256Data);

        log.debug('canonical_hash is ',canonical_hash);

        algorithm = 'AWS4-HMAC-SHA256';
        credential_scope = datestamp + '/' + region + '/' + 'execute-api' + '/' + 'aws4_request';
        string_to_sign = algorithm + '\n' +  ISO8601Date + '\n' +  credential_scope + '\n' +  canonical_hash;

        log.debug('String to Sign ',string_to_sign);

        /************* TASK 3: CALCULATE THE SIGNATURE *************/

        secret_key=secret key here; //secret key for iam user 
        access_key=access key here; // access key for iam user

        signing_key = getSignatureKey(secret_key, datestamp, region, service);

        

        var signingsha256Data = CryptoJS.HmacSHA256(string_to_sign,signing_key);

        var signature= CryptoJS.enc.Hex.stringify(signingsha256Data);

        log.debug('Final signature is ',signature);

   

    /************* TASK 4: ADD SIGNING INFORMATION TO THE REQUEST *************/
    authorization_header = algorithm + ' ' + 'Credential=' + access_key + '/' + credential_scope + ', ' +  'SignedHeaders=' + signed_headers + ', ' + 'Signature=' + signature;

    headers = {host:'sellingpartnerapi-na.amazon.com','x-amz-access-token':accessToken,'x-amz-date':ISO8601Date, 'Authorization':authorization_header}

  

    /************** SEND THE REQUEST **************/
    request_url = 'https://sellingpartnerapi-na.amazon.com/orders/v0/orders' + '?' + canonical_querystring;

    log.debug('Request URL is ',request_url);

    var response = https.get({
      url: request_url,
      headers: headers
    });

    log.debug('Response Code is ',response.code); //Response code returned is 403
    log.debug('Response is ',response.body);  //invalid signature (details at top)
`
//HELPER FUNCTIONS

`function getSignatureKey(key, dateStamp, regionName, serviceName) {
  var kDate = CryptoJS.HmacSHA256(dateStamp, "AWS4" + key);
  var kRegion = CryptoJS.HmacSHA256(regionName, kDate);
  var kService = CryptoJS.HmacSHA256(serviceName, kRegion);
  var kSigning = CryptoJS.HmacSHA256("aws4_request", kService);
  return kSigning;
}
    function pad(n) {return n<10 ? '0'+n : n}`

**Comment by sherlock270** [comment]
I ran into this issue as well and fixed it by encoding my canonical_request and string_to_sign with utf-8 before hashing

**Comment by mashhood1995** [comment]
> I ran into this issue as well and fixed it by encoding my canonical_request and string_to_sign with utf-8 before hashing

Hi sherlock ,Thanks for responding , I used javascript encodeURI function to encode canonical_request and string_to_sign  with utf-8 but after doing so same error and additionally string_to_sign did not match with that provided by amazon response as well .. here is the latest response to my request :
`{ "errors": [ { "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'GET / CreatedAfter=20201117T085026Z&MarketplaceId=ATVPDKIKX0DER host:sellingpartnerapi-na.amazon.com x-amz-access-token:Atza|IwEBIFDROjvWuB9leGjh2NOTkNCGjEHY2JK0KSqZ8EvKVBqMP6T-cXTO2kREAtJBhXNyFhIsz6kVpiH0aXimWMd9iDGL2x5tJB0-p_cw54J-FZHau_5HeOvhJWFV9KNmedfTAAhh8N1lktjhjrjriCmV1Pc06GvZZjKU7_eAz4Hl_-tTL7apBRpgWnPWbvY81FXgCzxRwTYLqkVJh7cWSPm2-mHUdo58PyXp-JiyQGk1XyQKvVQjZBD55RWUFOuUbHB989yd0ySkw-MFiod7nV4eJjN7-tLbRQWzL_mgdXn75IjiqI9etLqq-Hn2sL87-fggSr2yDx92s8Ix49EUmHl6QoGX x-amz-date:20201117T085026Z host;x-amz-access-token;x-amz-date e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' The String-to-Sign should have been 'AWS4-HMAC-SHA256 20201117T085026Z 20201117/us-east-1/execute-api/aws4_request 433abd8607c6d57ca5af43910793cff3da0afa397d38d95dac8ba25428013eb2' ", "code": "InvalidSignature" } ] }`

**Comment by JacksonJeans** [comment]
Hello @mashhood1995 ,
I see that your `canonical_uri` is wrong.
You try to request orders but you do not consider the URI in the creation of the canonical request.
You have set the canonical URI statically to `/`. This can also be seen in the answer from Amazon, where the Canonical Request is as follows:

```
GET + "\n"
/ + "\n"
CreatedAfter=20201117T085026Z&MarketplaceId=ATVPDKIKX0DER...
```

Correct would be:
```
GET + "\n"
/orders/v0/orders/ + "\n"
CreatedAfter=20201117T085026Z&MarketplaceId=ATVPDKIKX0DER...
```

**Comment by mashhood1995** [comment]
> Hello @mashhood1995 ,
> I see that your `canonical_uri` is wrong.
> You try to request orders but you do not consider the URI in the creation of the canonical request.
> You have set the canonical URI statically to `/`. This can also be seen in the answer from Amazon, where the Canonical Request is as follows:
> 
> ```
> GET + "\n"
> / + "\n"
> CreatedAfter=20201117T085026Z&MarketplaceId=ATVPDKIKX0DER...
> ```
> 
> Correct would be:
> 
> ```
> GET + "\n"
> /orders/v0/orders/ + "\n"
> CreatedAfter=20201117T085026Z&MarketplaceId=ATVPDKIKX0DER...
> ```

Thanks Jackson.. actually i updated my code to make corrections to the uri as per your recommendations but i am still seeing same error.. 
URI string generated by my request (exactly matches with that provided in amazon response) 
GET /orders/v0/orders CreatedAfter=20201114T071224Z&MarketplaceId=ATVPDKIKX0DER host:sellingpartnerapi-na.amazon.com user-agent:test2/1.0 (Language=Javascript) x-amz-access-token:Atza|IwEBIM-nzVFb06CY-uxvBxSObj-bKPUTtfb7PLXHKTKSpZQjUKn6kZ8JuCE68CIuZeAFW4nRgLn7Gyz8Jfx3M0sK4OH3Vj5UZoLpLRHeaX2yXwgwG89U0ZjMatmQR0tSI5ZASxvlIk-JUDeu2-vGo65W7s8279r1fYwLPvlJ7KavBHqoddfoZj6p1kAnzqOAS5fPBOHznuebkRLpmLWM9D9lidsVg3A4p22IpkGKmQU79vm5ESir-GGHYz2Em4pQPdBgTH08qOrZc0Td-eWynCZoJ3qx1hCPMuEt_8yJ3NMzj6F_UGH9xyEeY85dIBV3CDvZE8Did7DPIcAR07XNjHUq8Yyu x-amz-date:20201119T071224Z host;user-agent;x-amz-access-token;x-amz-date e3b0c25898fc1c149afbf5c8996fb92427ae41e4649b934ca495991b7852b258

**Comment by JacksonJeans** [comment]
Hello,

now I see that you have a completely different hashed payload than before.

A GET request does not contain any data in the body, so the payload is empty. But your payload is: `e3b0c25898fc1c149afbf5c8996fb92427ae41e4649b934ca495991b7852b258`.

An empty hashed payload would look like this:
`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

When I make a GET request to the OrderAPI my payload is always empty.
Here is an example of what I have just done:

```
GET
/orders/v0/orders/
CreatedAfter=2020-11-18T23%3A00%3A00&MarketplaceIds=A1PA6795UKMFR9&MaxResultsPerPage=100
content-type:application/json; charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:xxx (Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201119T084012Z

content-type;host;user-agent;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Then I also notice that your canonical URI does not end with '`/`', which is always the case with GET requests.
Only with POST requests I miss the last '`/`'.

When I make POST request to, for example, ReportsAPI (here createReport -  operation):

```
POST
/reports/2020-09-04/reports

content-type:application/json;charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:xxx (Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201119T084302Z

content-type;host;user-agent;x-amz-date
527a08b221450d624dc50e4e8a627f563ccf514f8b58791702d2bf037029b8ae
```
I had solved the problems with the canonical URI in the past and at some point I solved them by experimenting. At that time there was no clear statement in the documentation. The bad example from Amazon in the documentation had caused some confusion. Here again the [reference](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) to it. 
Look at: 'Example Canonical URI with encoding'

In the following I also refer to my problem solution concerning the canonical URI. There you can find my PHP implementation to create the canonical request => [Stackoverflow](https://stackoverflow.com/questions/64714444/amazon-sellerpartnership-sp-api-signature-v4-problem-with-cannonicalrequest/64752573#64752573).

Good luck with implementation!

**Comment by rodrigojob** [comment]
I had this problem. I solved trying all secretKey...
Use IAM secretKey

You must considerate the body to create the payload in CannonicalString

**Comment by ericblade** [comment]
Had a similar problem, was using the LWA secret key rather than the AWS secret key.  Not sure if that helps :-)

**Comment by mashhood1995** [comment]
> Hello,
> 
> now I see that you have a completely different hashed payload than before.
> 
> A GET request does not contain any data in the body, so the payload is empty. But your payload is: `e3b0c25898fc1c149afbf5c8996fb92427ae41e4649b934ca495991b7852b258`.
> 
> An empty hashed payload would look like this:
> `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
> 
> When I make a GET request to the OrderAPI my payload is always empty.
> Here is an example of what I have just done:
> 
> ```
> GET
> /orders/v0/orders/
> CreatedAfter=2020-11-18T23%3A00%3A00&MarketplaceIds=A1PA6795UKMFR9&MaxResultsPerPage=100
> content-type:application/json; charset=UTF-8
> host:sellingpartnerapi-eu.amazon.com
> user-agent:xxx (Language=PHP/7.1; Platform=Windows/10)
> x-amz-date:20201119T084012Z
> 
> content-type;host;user-agent;x-amz-date
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> ```
> 
> Then I also notice that your canonical URI does not end with '`/`', which is always the case with GET requests.
> Only with POST requests I miss the last '`/`'.
> 
> When I make POST request to, for example, ReportsAPI (here createReport - operation):
> 
> ```
> POST
> /reports/2020-09-04/reports
> 
> content-type:application/json;charset=UTF-8
> host:sellingpartnerapi-eu.amazon.com
> user-agent:xxx (Language=PHP/7.1; Platform=Windows/10)
> x-amz-date:20201119T084302Z
> 
> content-type;host;user-agent;x-amz-date
> 527a08b221450d624dc50e4e8a627f563ccf514f8b58791702d2bf037029b8ae
> ```
> 
> I had solved the problems with the canonical URI in the past and at some point I solved them by experimenting. At that time there was no clear statement in the documentation. The bad example from Amazon in the documentation had caused some confusion. Here again the [reference](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) to it.
> Look at: 'Example Canonical URI with encoding'
> 
> In the following I also refer to my problem solution concerning the canonical URI. There you can find my PHP implementation to create the canonical request => [Stackoverflow](https://stackoverflow.com/questions/64714444/amazon-sellerpartnership-sp-api-signature-v4-problem-with-cannonicalrequest/64752573#64752573).
> 
> Good luck with implementation!

Thanks Jackson for helping, Signature issue is resolved, problem was in the URI as you mentioned as well as service used to generate signature key. I was using 'sellingpartnerapi-na' instead of 'execute-api' to generate signature key.
