### ISSUE TITLE
Cannot authorise a new developer - MD9000 

### ISSUE THREAD

**Issue by chanakaDe** [amzn/selling-partner-api-docs#1160]
I have a seller account in Germany and when I'm going to Authorise a new developer, I get the following error message. 

> This Developer is not currently eligible for new authorizations. - MD9000 

I simply need to get all the orders as a list. I was following all the given instructions and no good so far. 
Is this has to do anything with Oath ? 
In Developer Central, I can see,

> MWS credentials and also LWA credentials

I am developing this application using my own Amazon seller account and I'm not an outside developer. 

Appreciate your assistance and thank you in advance.

**Comment by mysaber** [comment]
version=beta ?
