### ISSUE TITLE
ProductTypeDefinitions API: Unable to add image urls to the `main_product_image_locator` attribute.

### ISSUE THREAD

**Issue by SouravPal95** [amzn/selling-partner-api-docs#1163]
I have been working with the SP API to add listing functionality to a project. I have been able to successfully upload products to the draft stage. But whenever I tried adding image urls to `main_product_image_locator` attribute, amazon returned a processing report with an error message saying that since the image is not hosted on AWS we cannot upload it. Is there a work around to this issue?

**Comment by MST1122** [comment]
@SouravPal95 how are you generating the UI form for Data Input from JSON-Schema?

**Comment by github-project** [comment]
@SouravPal95 How did you solve the above problem
