### ISSUE TITLE
how can I get the products on sale and product inventory of my shop?

### ISSUE THREAD

**Issue by justin-xean** [amzn/selling-partner-api-docs#1165]
Hello, I am a PHP developer, how can I get the products on sale and product inventory of my shop? 

Before that, the data I obtained through the {getReportDocument} interface in the report seemed to be an HTML page, which did not meet my expectations.

I wanted to get the array data like an order. 

Please tell me how to do it.

![image](https://user-images.githubusercontent.com/57519584/127583929-79a2d333-803b-4aee-b544-5e901e2dbffc.png)

**Comment by justin-xean** [comment]
This is a very urgent case, please deal with it as soon as possible

**Comment by justin-xean** [comment]
@rickdeee @salric @jenilew Please~~

**Comment by justin-xean** [comment]
I solved it by myself

**Comment by joseacevedo-slab** [comment]
how did you solve it?

**Comment by justin-xean** [comment]
Just through the report request, and then process the decrypted string~~~

**Comment by Javadebi** [comment]
> I solved it by myself

How did you do that?
