### ISSUE TITLE
Does getReports show reports created by other SP API applications?

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#1168]
When I call `getReports` for a particular report type, I usually see a lot of reports that I didn't create. Does `getReports` display reports of the requested type that are generated by SP API or MWS applications other than the one calling the API? E.g., if I call `getReports` from app X, do reports created by app Y show up?

If so, does app X creating a daily report prevent app Y from being able to create another instance of that same report within 4 hours? Do the report-related actions of one app affect what another app can do?

**Comment by moltar** [comment]
It definitely shows reports that you haven't imitated.

These are potential sources:

- User can generate a report in the UI in Seller Central
- Amazon generates some reports automatically on schedule
- Other API tools can trigger report generation. Some reports are "singletons".

**Comment by jlevers** [comment]
Ok, that fits with what I'm seeing -- thanks for the input!

Do you know if a report being generated by one tool can affect how soon another tool can generate the same report (e.g., with "daily" FBA reports that can only be generated once every 4 hours)?

**Comment by moltar** [comment]
Yes, defo has an effect.

As I said, think of them as singletons per seller account / marketplace combo. 😀

**Comment by jlevers** [comment]
Ah ok, gotcha.

I feel like this is a problematic setup, because you can't rely on being able to create a report at a particular time, even if _your_ application has waited the required period between `createReport` calls for a particular report. And if some other app has requested a report that you need too, but it's over a different time period than the one you want to request, you can't just use the report they've already created.

@parvathm @ShivikaK could either of you comment on why it's set up this way, and any solutions to the problem I'm mentioning above?

**Comment by moltar** [comment]
From my experience this only applies to reports that aren't time sensitive and only generated rarely.

This is sometimes documented. Eg it says this report is generated once every 72 hours. 

Anything that's time bound, eg orders, you should be able to generate multiple times.

**Comment by jlevers** [comment]
I don't think that fits with what I'm seeing, although I could certainly be misunderstanding.

Some reports come back `CANCELLED` when I call `createReport`, even if I've waited the requisite period (e.g., 4 hours for some daily FBA reports) between `createReport` calls. When I call `getReports` for the cancelled report type, I often see reports that were generated successfully over a similar time period as my `createReport` call attempted to fetch data for. It seems like these other reports (that I didn't create) are blocking me from creating a report of the same type within the waiting period (e.g., 4 hours), even if a different application created the blocking report(s).

**Comment by moltar** [comment]
See #1204
