### ISSUE TITLE
getOrderMetrics InvalidInput

### ISSUE THREAD

**Issue by sherlock270** [amzn/selling-partner-api-docs#117]
Hello, I'm trying to make a [getOrderMetrics](https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md#getordermetrics) request to the following endpoint: 
`https://sellingpartnerapi-eu.amazon.com/sales/v1/orderMetrics?marketplaceIds=A13V1IB3VIYZZH%2CA1805IZSGTT6HS%2CA1F83G8C2ARO7P%2CA1PA6795UKMFR9%2CA1RKKUPIHCS9HS%2CA1ZFFQZ3HTUKT9%2CA38D8NSA03LJTC%2CA62U237T8HV6N%2CAFQLKURYRPEL8%2CAPJ6JRA9NG5V4%2CAZMDEXL2RVFNN
&interval=2020-10-16T05%3A00%3A00-5%3A00--2020-11-16T22%3A57%3A00-5%3A00
&granularity=Hour
&granularityTimeZone=America%2FChicago`

The error I get is `{
  errors: [ { code: 'InvalidInput', message: 'Invalid Input', details: '' } ]
}` which has been very unhelpful. Am I missing something?

**Comment by rodrigojob** [comment]
Hello,

this Ids don't exist:
A62U237T8HV6N
AFQLKURYRPEL8
APJ6JRA9NG5V4
AZMDEXL2RVFNN 

And in request you ar using %2C, use comma
Don't leave space in querystring
wrong: 3A57%3A00-5%3A00 &granularity=Hour &granularityTi...
correct: 3A57%3A00-5%3A00&granularity=Hour&granularityTi...

**Comment by sherlock270** [comment]
Thank you for pointing out the non existent marketplace ids. The spaces in my original post came from the copy and pasting, not in my original request. After removing those and using commas rather than %2C I received errors saying the  signatures didn't match. Without the commas I still receive the same error. Here is my current request:
```https://sellingpartnerapi-eu.amazon.com/sales/v1/orderMetrics?granularity=Day&granularityTimeZone=UTC&interval=2020-10-20T05%3A00%3A00.000Z--2020-11-20T06%3A00%3A00.000Z&marketplaceIds=A13V1IB3VIYZZH%2CA1805IZSGTT6HS%2CA1F83G8C2ARO7P%2CA1PA6795UKMFR9%2CA1RKKUPIHCS9HS%2CAPJ6JRA9NG5V4```

**Comment by sherlock270** [comment]
I found out the problem is that the documentation [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md#getordermetrics) states that marketplaceIds is a < string > array of marketplace identifiers, but the api seems to have a limit of 1 marketplace id at a time.
