### ISSUE TITLE
Move the March 2022 MWS Products deprecation

### ISSUE THREAD

**Issue by teddy-codes** [amzn/selling-partner-api-docs#1170]
Hello, I have been in contact on another issue (#975) and there is currently going to be a huge problem with all the product research tools when this API is removed due to use cases being not supported. I tried to open a conversation with seller support, but as most of all developers (and sellers) know... they are useless. So, I am again reaching out via issues. I would like to try and gain certainty that our product will not all of a sudden stop working March 2022 due to us waiting for a solution to be provided from the sp-api team.

**Comment by txphi592** [comment]
We're in the same boat...

**Comment by ellis** [comment]
This has my vote too.  The ListCatalogItems method of the SP-API api, which @teddy-codes also talks about in #975, is very import to us because of the results are ordered like the organic search results for site visitors.

**Comment by teddy-codes** [comment]
@ellis I know that not a lot of people are going to listen to this feedback, but I wanted to kind of give you some insight of what I am currently building out and why I think that it's fine.

@chapmanjw has mentioned that v0 of the catalog-items api will have changes made before the deprecation. This means that there will absolutely be a new version of the catalog-api prior to deprecation.

IMO, the 2020-12-01 version of the document was just something that Amazon was able to tell us developers to work with until they had a final release for us. @jenilew also said in the announcement that RFC for the removed apis should be in before sept. 30th. This means that before the deprecation, there is going to be another version with the adjusted features available to us. There also was something in the announcement about the removal of the Products API that the v0 api is going to be deprecated (as I mentioned) and listCatalogItems is going to be removed in favor of searchCatalogItems, but the endpoints are the exact same. This is probably just an internal change that they are making.

The v0 api has some things already that @chapmanjw was talking about.
There are:
- Additional attributes (you can actually read a good majority of them)
- Throttling that is combined 18,000 from GMP and 3600 from LMP. (21,600 total requests/hour)

Honestly, the throttling is much less than ideal because now it is just 21,600 identifiers/terms per hours. Besides that, so far.. I am liking what I see. Not really sure what your thoughts are on this, but this seems like we are finally starting to get the giant to start moving with us after they pushed something and started thinking after.

**Comment by teddy-codes** [comment]
Apparently, disregard that whole comment.

https://github.com/amzn/selling-partner-api-docs/issues/975#issuecomment-915725915 confirms that there will be another version, but it will be a branch from the 2020 version not off of v0.

**Comment by ellis** [comment]
I added info related to this issue in https://github.com/amzn/selling-partner-api-docs/issues/829#issuecomment-926412291 with a response from the development team to a Support Case.  It sounds like they still don't see this as an important use case, have no plans to support it in the new endpoint, and have so far decided to disregard the negative impact that the removal will have.

**Comment by teddy-codes** [comment]
@chapmanjw Is this something that you might be able to help us out with?

**Comment by callumb123** [comment]
@chapmanjw can you comment on the concerns raised in this thread? I fear the deprecation date is going to approach very quickly with none of these issues being resolved

**Comment by txphi592** [comment]
@chapmanjw On 9/29/21 we received an email from Amazon (dev-reg-notice@amazon.com) indicating that Amazon “will be extending the date for when the Products API will be deprecated. In the coming weeks we will be posting a MWS deprecation roadmap to provide visibility and help developers plan their migration efforts for next year.” We have not seen such a roadmap published and have not seen a new deprecation date. Any insight on this? It’s important for us to understand the deadline for deprecation.
