### ISSUE TITLE
[BUG] Documentation GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA report RDT.

### ISSUE THREAD

**Issue by baran-ozer** [amzn/selling-partner-api-docs#1173]
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-an-rdt-and-call-restricted-operations there is no any clue what to write to "path" parameter on request body to get Restricted Data Token for download GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA report. Is there any one here that know something about it. Please help.

![rdt_for_reports_FAIL_1](https://user-images.githubusercontent.com/61375346/127781246-95ef4fc4-2401-4f6c-a99a-e9687b2a4dfa.png)

**Comment by defenderjim** [comment]
Ever get this to work?
reports/2021-06-30/reports

**Comment by defenderjim** [comment]
Ever get this working?  I have it working,
Don't use the RDT.  This report requires a start date in the body.

**Comment by baran-ozer** [comment]
Oh really?  We couldn't get this working. Is it possible to share your request? It would help a lot.

**Comment by defenderjim** [comment]
Are you able to make any SP-API calls successfully?
I ask so I understand if you have any success and the problem is just w/this endpoint or something else?
What language are you using?

1. First, request the report.
    POST to reports/2021-06-30/reports
    Header: Content-Type: application/json
    Body:  reportType = GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
	    , dataStartTime = startDate.ToString("yyyy-MM-ddTHH:mm:ssZ")
	    , marketplaceIds = new[] { marketPlaceId }
    Use the reportId in the response for the next step

2.  GET to reports/2021-06-30/reports/reportId
    Check status is "DONE".
    Use reportDocumentId from the response in the next step.

3.  GET to reports/2021-06-30/documents/" + reportDocumentId

4. Download the document using the url provided in the response of Step 3.

**Comment by baran-ozer** [comment]
Yes, we are able to SP-API calls?
We are using python.
Thanks a lot for helping, we will try these steps.

**Comment by defenderjim** [comment]
@baran-ozer Making any progress?

**Comment by Vaibhavipatel15** [comment]
> 
And What is startDate
