### ISSUE TITLE
[BUG] approvalSubmissions return 500 InternalFailure

### ISSUE THREAD

**Issue by tangshuai3211** [amzn/selling-partner-api-docs#1176]
Describe the bug:
Error returns 500 InternalFailure.
URL of the content on GitHub:
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/aplus-content-api-use-case-guide/aplus-content-api-use-case-guide_2020-11-01.md#Step-3-Get-the-content-document-approved-for-publication
![image](https://user-images.githubusercontent.com/45872296/127801238-78e8a252-a00e-4341-94d3-16edc533db02.png)
This is my request and response.

**Comment by AleemFeng** [comment]
Require it again.

**Comment by tangshuai3211** [comment]
> Require it again.

That's what happened last Saturday. I've been trying~

**Comment by tangshuai3211** [comment]
> Require it again.

I request it almost every half an hour, but I return the same 500 error messages every time

**Comment by justin-xean** [comment]
这个我帮不了你，但是我想问一下你拉到库存和在售商品没有？

**Comment by justin-xean** [comment]
@tangshuai3211 这个我帮不了你，但是我想问一下你拉到库存和在售商品没有？

**Comment by tangshuai3211** [comment]
> @tangshuai3211 这个我帮不了你，但是我想问一下你拉到库存和在售商品没有？

报告里有

**Comment by justin-xean** [comment]
> > @tangshuai32111帮不了你，不过我这个时候你拉到了现货和商品上没有？
> 
> 报告里有

报告返回是一个带p标签的csv，没办法写入csv啊

**Comment by justin-xean** [comment]
> > @tangshuai3211 这个我帮不了你，但是我想问一下你拉到库存和在售商品没有？
> 
> 报告里有

![image](https://user-images.githubusercontent.com/57519584/127823550-fdbd1f7a-fe9d-4f98-89b7-71905e73ea14.png)
我的返回是这样的，求告知怎么处理？

**Comment by AleemFeng** [comment]
Which one operation did you used?

**Comment by tangshuai3211** [comment]
> Which one operation did you used?

I have solved it. Thank you for your reply

**Comment by justin-xean** [comment]
> > Which one operation did you used?
> 
> I have solved it. Thank you for your reply

老哥，你怎么解决的，求告知
