### ISSUE TITLE
Waiting For PII Request Approval

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#1179]
Hİ,
I've been trying for a very long time to approve access to PII data.
Although I submitted the requested data several times, my applications were not accepted.
I have sent the requested information again. Could you please review and approve my application with the 8658933181 case number?
This is very urgent for our software team and business process.
Thanks

**Comment by emiproenterprise** [comment]
How can I find out if Amazon has approved my developer account to access PII information?
