### ISSUE TITLE
方便中国的开发者沟通交流，想创建一个沟通交流群，希望亚马逊管理员可以保留此issue ^_^

### ISSUE THREAD

**Issue by xin96** [amzn/selling-partner-api-docs#118]
为了方便中国开发者沟通交流，我想借助sp api doc，创建一个微信群，我的微信是9866181，大家可以加我微信，我拉大家进群交流。感谢亚马逊管理员提供此次机会，再次表示感谢🙏。

**Comment by jokerbink** [comment]
我也是中国的亚马逊开发者，微信281523824，欢迎加好友一起讨论

**Comment by xin96** [comment]
> 我也是中国的[亚马逊](http://track.uc.cn/lct?appid=2725715d66c1&turl=http://m.sm.cn/s?q=%E4%BA%9A%E9%A9%AC%E9%80%8A&from=wh10011&uks=%E5%85%A8%E9%83%A8_%E4%BA%9A%E9%A9%AC%E9%80%8A&cls=0&clt=5&rf=github.com&kid=3;uc_param_str=dnntnwvepffrgibijbprsvpidsdichei)开发者，微信281523824，欢迎加好友一起讨论

已添加，进群交流🤝🤝🤝

**Comment by kingsun-he** [comment]
我也是中国的亚马逊开发者，微信2382344313，欢迎加好友一起讨论

**Comment by baijianguo** [comment]
我也是中国的亚马逊开发者，微信w_yuetian，欢迎加好友一起讨论

**Comment by xin96** [comment]
亚马逊fba，箱子尺寸和重量上传的feed的问题都是这么解决的？
另外fba外箱标签打印api，面单是英文不是中文，和店铺后台打印的不一致？
