### ISSUE TITLE
[BUG] Documentation on 403 Reasons for getInventorySummaries

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-docs#1180]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
The reasons for the 403 is incorrect.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md

**Description of what the documentation currently says**
403 - Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, Invalid Signature or Resource Not Found.

**Description of what the documentation should say**
403 - Indicates access to the resource is forbidden or not implemented.  Possible reasons include the API is not available in that region, Access Denied, Unauthorized, Expired Token, Invalid Signature or Resource Not Found.

**Comment by kpconnell** [comment]
While 403 is probably actually a bug within the API, and it should be 404 or 501 when the european region is called for the inventory api, a 403 is returned, even though it is not an access problem, the documentation should reflect how the api is behaving, and it does not currently describe WHY the 403 is happening.

**Comment by codingkondi** [comment]
I got 403 as well while I called getReports Api with GET_AFN_INVENTORY_DATA reportType, and I doubt that my problem have to do with ur issue
