### ISSUE TITLE
Hello, after I applied for PII permission, the previously published application did not have permission, please help me to deal with it

### ISSUE THREAD

**Issue by userbabu** [amzn/selling-partner-api-docs#1186]
The APP released before applying for the PII permission still cannot access the PII information. I tried to create a new draft application for testing and can access the order PII information. What should I do?
Thank you very much

case ID : 8669061401

**Comment by userbabu** [comment]
> 我认为您的卖家帐户需要重新授权。

Happily, I have solved the problem

**Comment by emiproenterprise** [comment]
In a beta version of my application, can I get PII information?

How can I find out if Amazon has approved my developer account to access PII information?

**Comment by userbabu** [comment]
> In a beta version of my application, can I get PII information?
> 
> How can I find out if Amazon has approved my developer account to access PII information?

The draft status is the same as the published status. The draft status does not have PII permission, which means there is no after publishing.
