### ISSUE TITLE
GET /reports/2021-06-30/reports Access Denied

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-docs#1190]
We can create reports but can not get a list of all reports with a request to GET `/reports/2021-06-30/reports`. We need to fetch `GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2` which can not be created by request as they are auto-generated by Amazon every week to two weeks. 

The endpoint for getting reports list returns the error: "Access to the requested resource is denied." 

Is this an undocumented report listing requiring RDT or some other permission? The documents make no mention of a restriction, and we have only been getting the access denied error for report types that require RDT. We have done this process via MWS, so we are familiar with this report type. However, in this case, it is not working in the manner we would expect. 

For context, we can make requests for other reports and retrieve them. The issue seems to be specific to  GET `/reports/2021-06-30/reports` which we need to use.

Any insights would be appreciated. `Case ID 8673747561`

https://github.com/amzn/selling-partner-api-docs/blob/3fc147fdf7188f9598bf304efa1b5af6e4a25b01/references/reports-api/reporttype-values.md#settlement-reports

**Comment by rohitdobariya** [comment]
@tspicer I have implemented the same report and I am sure the issue is some you generated AWS and LWA credentials. Have you follow the step properly AWS and LWA credentials. ?

**Comment by tspicer** [comment]
@rohitdobariya, yes we are able to make requests for reports and then get those reports. However, in this case, the issue is a specific operation of getting a list with a request to `GET /reports/2021-06-30/reports`. The settlement report was an example of needing to get a list of reports, which throws the error. So if we can request and get a report, but get an error with `GET /reports/2021-06-30/reports`, this would lead me to think it is not an auth issue.

**Comment by rohitdobariya** [comment]
@tspicer add me on Skype:: rohitavira we can connect and check

**Comment by luckylion000** [comment]
@tspicer @rohitdobariya Did you solve your problem?

I am getting similar error. I've used this lib [https://github.com/DavidMuller/aws-requests-auth](url) for AWS Signature Version 4 Signing Process. And if I call selling partner api to create report, 
**POST** _https://sellingpartnerapi-na.amazon.com/reports/{current_date}/reports_

I am getting below error.
`{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`

**Comment by defenderjim** [comment]
@tspicer This endpoint does not require an RDT.
@luckylion999 
This is the wrong endpoint: POST https://sellingpartnerapi-na.amazon.com/reports/{current_date}/reports
The correct path: reports/2021-06-30/reports

**Comment by ashish-jmd4tech** [comment]
HI @tspicer 

We are also facing the same issue while accessing /reports/2021-06-30/reports . Report type is GET_ORDER_REPORT_DATA_SHIPPING. Other Apis e.g. for orders etc. work fine. So I don't think it is an issue with token. 

It will be great if you can tell us how did you solve it. 
-thks

**Comment by ashish-jmd4tech** [comment]
Hi @rohitdobariya 

Even for make request, we are getting access forbidden.  /reports/2021-06-30/reports.  Post.  

Json;"{\"reportType\" : \"GET_ORDER_REPORT_DATA_SHIPPING\", \"marketplaceIds\": [\"A21TJRUUN4KGV\"]}";

Do we need some permissions for the Selling Partner API role?

-thks

**Comment by rohitdobariya** [comment]
Hi
call me at 8530429249

**Comment by defenderjim** [comment]
@ashish-jmd4tech ,
Don't call any number. 
I have the reports endpoint working, it was a little tricky.
You don't need an RDT.

`POST to this endpoint: "reports/2021-06-30/reports"`

Here is working JSON

```
{"reportType":"GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT"
,"dataStartTime":"2022-01-24T00:00:00Z"
,"marketplaceIds":["ATVPDKIKX0DER"]}

```

**Comment by ashish-jmd4tech** [comment]
Thanks @defenderjim 
Yes, this reportType works. May be order reports/settlement reports requires more permissions.

Thanks @rohitdobariya for quick response.

**Comment by rohitdobariya** [comment]
Your welcome

**Comment by defenderjim** [comment]
>  May be order reports/settlement reports requires more permissions.
I don't think so. 
Be specific about what report you are trying to get, we can go from there. , I'll see if I can help.

**Comment by ashish-jmd4tech** [comment]
GET_ORDER_REPORT_DATA_SHIPPING

**Comment by rohitdobariya** [comment]
> @ashish-jmd4tech , Don't call any number. I have the reports endpoint working, it was a little tricky. You don't need an RDT.
> 
> `POST to this endpoint: "reports/2021-06-30/reports"`
> 
> Here is working JSON body for the request:
> 
> ```
> {"reportType":"GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT"
> ,"dataStartTime":"2022-01-24T00:00:00Z"
> ,"marketplaceIds":["ATVPDKIKX0DER"]}
> ```

Hi @defenderjim I am not sure you review this comment. you can see the report type which is @ashish-jmd4tech looking for resolve the issue.

**Comment by defenderjim** [comment]
@ashish-jmd4tech 


This JSON body will works for me, for the data shipping report.
```
{"reportType":"GET_ORDER_REPORT_DATA_SHIPPING"
  ,"dataStartTime":"2022-01-04T00:00:00Z"
  ,"marketplaceIds":["ATVPDKIKX0DER"]}

```


I have the restock report working.  
This is the json body I use:
`{"reportType":"GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT"
  ,"dataStartTime":"2022-01-14T00:00:00Z"
  ,"marketplaceIds":["ATVPDKIKX0DER"]}`

**Comment by ashish-jmd4tech** [comment]
HI @defenderjim 

Tried this one but it gives Access Denied. That is why I inferred that Order & Settlement reports require more permission.

**Comment by defenderjim** [comment]
Yes, I think you are right, the report, GET_ORDER_REPORT_DATA_SHIPPING, falls under the 

Direct-to-Consumer Shipping (Restricted) Role.
I think this is the Role "Direct-to-Consumer Delivery" in Seller Central => Partner Network => Develop Apps

Look here at the docs:
[https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/roles-to-rights/direct-to-consumer-shipping.md](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/roles-to-rights/direct-to-consumer-shipping.md
)

**Comment by ashish-jmd4tech** [comment]
Wonderful @defenderjim. Thanks a lot. I was looking for this doc.

**Comment by defenderjim** [comment]
Also,
Look at this page.
[https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md)
