### ISSUE TITLE
[DOUBT] Sending products to Amazon?

### ISSUE THREAD

**Issue by mateusconectala** [amzn/selling-partner-api-docs#1193]
Hi,

The only possibility to create products on amazon's marketplace is through the[ Feed API](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md#listings-feeds) resource using the POST_PRODUCT_DATA feedType, right? Is the data submission format only in XML?
In the documentation there is an [XSD file](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd), which validates the product information, there is also a specific XSD file for each category ([example](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductClothing.xsd)).

Knowing this, I would like to know the usefulness of the [Product Type Definitions](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md) resource, since it returns information for JSON Schemas validation.

Thanks.

**Comment by hongtao0770** [comment]
Hello @mateusconectala,

I have the same question, how should I add a product?

**Comment by wmh49877** [comment]
I have the same question! Does anyone have a tutorial?

**Comment by harili** [comment]
Hello, this might help you 👍 
https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide#tutorial-create-or-fully-update-a-listing
