### ISSUE TITLE
Report API not getting data as dataStartTime and dataEndTime

### ISSUE THREAD

**Issue by gaurav-webs** [amzn/selling-partner-api-docs#1197]
In MWS API I am getting a proper response but in SP API I am not getting a response as per the date.

I am using [Reports API(2021-06-30)](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md).

Report Type(MWS):- `_GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_`
Report Type(SP):- `GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL`

My code flow,

I am getting daily sales using the above report type, so I have set my logic something like I check a whole week data using loop that check the daily sales of that week, and if any date is missed so it will call [createReport](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#createreport) API for that date and then I am getting the report data with the help of [getReport](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreport).

Ex. let's take the example of the current week, for the date 2021-08-01 report was created successfully, but for 2021-08-02,2021-08-03, and 2021-08-04 miss because of some reasons.

so I have set the loop that creates the report for missing dates so when the first-time loop executes it creates a report for **2021-08-02 (Start Date = 2021-08-01T00:00:00-07:00, End Date= 2021-08-01T23:59:59-07:00)**, 
when the second-time loop executes it creates a report for **2021-08-03 (Start Date = 2021-08-02T00:00:00-07:00, End Date= 2021-08-02T23:59:59-07:00)**, 
and when the third-time loop executes it to create a report for **2021-08-04 (Start Date = 2021-08-03T00:00:00-07:00, End Date= 2021-08-03T23:59:59-07:00)**.

_**Note:- I am getting a report for the previous day so when i call on 2021-08-02 I am getting report data for 2021-08-01 and so on as this is my requirement.**_

so now I have 3 reportId for 3 dates
**_2021-08-02 = 6636380xxxxx
2021-08-03 = 6636390xxxxx
2021-08-04 = 6636400xxxxx_**

so now when I call [getReport](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreport) for the above report id so i am getting response like this
for **_2021-08-02 = 6636380xxxxx_** i am getting data  for **_2021-08-01_**,
for **_2021-08-03 = 6636390xxxxx_** i am getting data  for **_2021-08-01 and 2021-08-02_** so here i have pass **_(Start Date = 2021-08-02T00:00:00-07:00, End Date= 2021-08-02T23:59:59-07:00)_** then why i am getting data for 2 days?
for **_2021-08-04 = 6636400xxxxx_** i am getting data  for **_2021-08-01,2021-08-02 and 2021-08-03_** so here i have pass **_(Start Date = 2021-08-03T00:00:00-07:00, End Date= 2021-08-03T23:59:59-07:00)_** then why i am getting data for 3 days,?

For MWS I have the same logic in MWS I am also getting 3 ReportId.
but in MWs I am getting a proper response,
when I run my loop to get missing report data,

_**Note:- I am getting a report for the previous day so when I call on 2021-08-02 I am getting report data for 2021-08-01 and so on as this is my requirement.**_

like when I call on **_2021-08-02_** I am getting data for **_2021-08-01_**,
when I call on **_2021-08-03_** I am getting data for **_2021-08-02_**,
when I call on **_2021-08-04_** I am getting data for **_2021-08-03_**.

So in SP API, I am getting data combine in all reports, but in MWS I am getting a proper response of what I am sending the start date and end date.

Also one thing, I have noticed in SP API is that when I am calling a single day report I am getting a proper response like,
Using SP API if I call report only for one day **2021-08-04 (Start Date = 2021-08-03T00:00:00-07:00, End Date= 2021-08-03T23:59:59-07:00)**.

so here I am getting proper report data for **_2021-08-03_**. it raised an issue when I call multiple reports in the loop.

any help on this issue.

**Comment by gaurav-webs** [comment]
Found the mistake there is my mistake to create an array from xml.

**Comment by asifiq2000** [comment]
HI Gaurav, I read your message you have successfully Got the Report using Sp_API, could you please share its URL, Body, Headers, or any other parameters used, since I am getting issues, in sp-api document it is not mentioned clearly. please reply ASAP
