### ISSUE TITLE
Question about MWS deprecation deadlines

### ISSUE THREAD

**Issue by AitorUria** [amzn/selling-partner-api-docs#1198]
Hello everyone,

There’s some confusion about the 2 announcements below and if one supersedes the other one.

Do you mind confirming if the Deprecation of the MWS Products Operations of March 31, 2022, is still going ahead?

https://sellercentral.amazon.com/forums/t/update-important-notice-moving-migration-requirement-date-from-september-30-2021-to-july-31-2022/870391

https://sellercentral.amazon.com/forums/t/important-notice-amazon-mws-products-section-and-selling-partner-catalog-items-v0-operations-to-be-deprecated-on-march-31-2022/862895

See further note from: https://github.com/amzn/selling-partner-api-docs/discussions/1037

_"Is the Amazon MWS Products section affected?
No, this change does not affect Amazon MWS Products section."_

Thanks

cc: @jenilew

**Comment by jenilew** [comment]
Hi AitorUria, 

These are separate announcements / efforts. 

The SP-API Migration announcement (on [Seller Central forums](https://sellercentral.amazon.com/forums/t/update-important-notice-moving-migration-requirement-date-from-september-30-2021-to-july-31-2022/870391) and the [GitHub Discussions](https://github.com/amzn/selling-partner-api-docs/discussions/1037) ) affect the Amazon MWS Orders, Reports, and Merchant Fulfillment Network (MFN) sections. 

The Amazon MWS Products section and SP-API Catalog Items v0 deprecation announcements only relate to those two areas. 

While the timing of the announcements may make them seem related; they are distinct and do not affect each other. We have not received any information that indicates a delay in the Amazon MWS Product section and SP-API Catalog Items v0 deprecation timeline. It is still planned for March 31, 2022.

If anything does change with these timelines; we will post an announcement and send email. 

Thank you,

Jen
The Selling Partner API Team

**Comment by AitorUria** [comment]
Hello @jenilew,

Do you mind kindly following up on my last message? I've seen this same line of enquiry occurring on the Amazon Seller Forums too. 

Thanks for your help,

Aitor

**Comment by jenilew** [comment]
Hi AitorUria,

At this time, these changes apply to third-party developers. We will send updated communications when private developers will be affected. 

Thank you,

Jen
Selling Partner API Services Team

**Comment by AitorUria** [comment]
Thanks for the prompt response @jenilew

**Comment by Bobspadger** [comment]
Are amazon able to provide any information on when the deprecation for sellers mws access may possibly be? It would be nice to know if I need to start planning the works in for the next 3 / 6 / 9 months or if its going to be years etc

The last thing we want is a notice, then only  a few short months to be getting off the mws api's
