### ISSUE TITLE
[FEATURE][BUG] GetMyFeesEstimate for more than only 1 SKU / ASIN is missing

### ISSUE THREAD

**Issue by cgaugel** [amzn/selling-partner-api-docs#1199]
In the old MWS-API I was able to call GetMyFeesEstimate for multiple SellerSKU / ASIN.

See: https://docs.developer.amazonservices.com/en_US/products/Products_GetMyFeesEstimate.html

This feature is missing here. Please add this again, so we can go on with our migration von MWS to SP-API.

**Comment by rohitdobariya** [comment]
@cgaugel in SP-API you must have call API for each SellerSKU / ASIN. you may use Loop and maintain Rate limit

**Comment by cgaugel** [comment]
But the MWS-API was able to handle more than one ASIN / SKU per request...

**Comment by teddy-codes** [comment]
@chapmanjw This is another blocker for us... Not sure if you are on this team or not, but this is huge.

How can a seller calculate profitability going off just price - cost...  Fees have to be added if they are using the FBA service.

We need to get fba fees and referral fees for a given price at a given time. Promotions and such don't matter since those go away with time.

How can we get this implemented?

**Comment by cgaugel** [comment]
Still no response from Amazon about this bug here. @parvathm @chapmanjw look at this.

**Comment by aidensgithub** [comment]
@chapmanjw  is there any development going in this direction? We consider this request as very urgent. It plays a crucial role in migrating from old API and meet the basic needs for a stable functioning software.
Fees and searchCatalogItems need to be transformed to bulk operation requests!

**Comment by teddy-codes** [comment]
This is still very much an open issue.

**Comment by stefnats** [comment]
I agree, this should be addressed.

**Comment by ehrowe** [comment]
Critical for us as well. Performance on MWS was a problem as it is, as well as throttling. Don't know how we are supposed to make this work.

**Comment by stefnats** [comment]
@ehrowe this issue has been resolved by the May release, you can now check up to 20 items with a single call.

**Comment by damianelder** [comment]
documentation hasn't been updated to make it clear getMyFeesEstimates can accept up to 20 SKU's/ASIN's per request.
