### ISSUE TITLE
InvalidInput - Required parameter IdType not found

### ISSUE THREAD

**Issue by Diego616** [amzn/selling-partner-api-docs#120]
160/5000
I am trying to make a request in / catalog / v0 / items /? MarketplaceId = ATVPDKIKX0DER, after being able to form the canonical request, however it returns me this error:

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Required parameter IdType not found",
      "details": ""
    }
  ]
}

**Comment by rugved1991** [comment]
@Diego616 can you please provide us with the complete request and response along with the headers? Please remove any sensitive information from the headers. 

Thanks,
Rugved
Selling Partner API Developer Support

**Comment by rogersv** [comment]
From the swagger file:

> Returns a list of items and their attributes, based on a **search query OR item identifiers** that you specify.

I assume that you need to choose one of them.

**Comment by Diego616** [comment]
@rogersv, Thank you very much, that's right, as I saw that everything was optional, I ended up not passing any
