### ISSUE TITLE
PutTransportDetail ProNum length limit error

### ISSUE THREAD

**Issue by RJEspera** [amzn/selling-partner-api-docs#1200]
When sending the ProNum for an FBA shipment, I get an error saying the length must be less than or equal to 10.  We are using ProNums that are 11 characters in length, why is it limited to 10?

Here's the request data I'm sending:

PutTransportDetailsRequest transportDetailRequest = new PutTransportDetailsRequest()
{
	IsPartnered = true,
	ShipmentType = ShipmentType.SP,
	TransportDetails = new TransportDetailInput
	{
		NonPartneredLtlData = new NonPartneredLtlDataInput()
		{
			CarrierName = "ODFL",
			ProNumber = "99958569976"
		}
	}
};

And here's the error message:
 
1 validation error detected: Value '99958569976' at 'transportDetails.nonPartneredLtlData.proNumber' failed to satisfy constraint: Member must have length less than or equal to 10"

**Comment by RJEspera** [comment]
I've tried it with the following data as well, but still got the character limit 10 or less violation.

`PutTransportDetailsRequest transportDetailRequest = new PutTransportDetailsRequest()
{
	IsPartnered = false,
	ShipmentType = ShipmentType.LTL,
	TransportDetails = new TransportDetailInput
	{
		NonPartneredLtlData = new NonPartneredLtlDataInput()
		{
			CarrierName = "ODFL",
			ProNumber = "99958569976"
		}
	}
};`

**Comment by jackshuaiwei** [comment]
Have you solved this problem?

**Comment by giangithud** [comment]
This issue is still dragging down our work efficiency, please solve it!
