### ISSUE TITLE
'Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]'

### ISSUE THREAD

**Issue by Emizy** [amzn/selling-partner-api-docs#1201]
Business wise urgent

API ACTIONS:
      Restricted Data Token
      Operation: createRestrictedDataToken
      path: /tokens/2021-03-01/restrictedDataToken

We were trying to obtain buyerinfo,shippingAddress from the getOrders endpoint (/orders/v0/orders) by requesting for a restricted data token using the below requests

payload= {'restrictedResources': [{'method':'GET','path':'/orders/v0/orders','dataElements':['shippingAddress','buyerInfo]}]} 

we included the access token and neccessary authorization headers when making the request but still we always get 'Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]'

Restricted Data Github Use Case
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md

Any wayforward or head up on how to rectify this issue .

Language of implementation Python

**Comment by rohitdobariya** [comment]
@Emizy I hope you have PII access and seems like as off RDT is not required

**Comment by Emizy** [comment]
Thanks for prompt response..

**Comment by Mike-the-one** [comment]
I have the same issue

**Comment by thethree** [comment]
My problem was resolved.  The problem was `targetApplication`, in my case, I should NOT provide a `targetApplication`.

**Comment by ximo1984** [comment]
> restrictedResources is a standalone object rather than an array of objects

This works for me.

**Comment by miketimeturner** [comment]
> restrictedResources is a standalone object rather than an array of objects

Thanks man.

**Comment by huoshidehua** [comment]
how to fixed it

**Comment by martr84** [comment]
We had tried to get this working we went through the process of clicking edit app and ticking the DirectToConsumer Role after being approved for the role and then regenerating the refresh token. however that DID NOT work.

What DID work is creating a brand new app registration with the same role arn and ticking all the required roles as part of the initial setup. This gave us new lwa credentials, new app ids and new refresh tokens.

Hopefully this saves many hours of frustrations for other people.

**Comment by pandabamboo90** [comment]
> restrictedResources is a standalone object rather than an array of objects

Amazing Amazon !!!! 👎 👎 👎 

Your documentation said "restrictedResources" IS AN ARRAY, this worked for some countries (ex: AU)

But it doesn't work for UK country ... CHANGE IT TO OBJECT (as suggested) worked for UK 🤯 🤯 🤯

**Comment by schellj** [comment]
> restrictedResources is a standalone object rather than an array of objects

This does not work for me with clients in the North America selling region (don't have any currently in other regions).

I was having issues, though, because I didn't have a leading slash on the `restrictedResources[].path`; without the leading slash, I would get the `Application does not have access to one or more requested data elements` error when requesting the RDT. Hopefully this helps save someone two hours of their lives...
