### ISSUE TITLE
[BUG] getReport api GET_SELLER_FEEDBACK_DATA report always return processingStatus=CANCELLED

### ISSUE THREAD

**Issue by promisepk** [amzn/selling-partner-api-docs#1203]
**Describe the bug**
Created a GET_SELLER_FEEDBACK_DATA  report 
and then  call getReport api.

AWS4 Canonical Request: '"GET
/reports/2020-09-04/reports/50039018845

The Response processingStatus is cancelled.

**GetReportResponse **
```
class GetReportResponse {
    payload: class Report {
        marketplaceIds: [ATVPDKIKX0DER]
        reportId: 50039018845
        reportType: GET_SELLER_FEEDBACK_DATA
        dataStartTime: 2021-01-01T00:00Z
        dataEndTime: 2021-08-06T01:23:49Z
        reportScheduleId: null
        createdTime: 2021-08-06T01:23:49Z
        processingStatus: CANCELLED
        processingStartTime: 2021-08-06T01:23:55Z
        processingEndTime: 2021-08-06T01:24:01Z
        reportDocumentId: null
    }
    errors: null
}
```

**Comment by hehengkaifj** [comment]
set permission will be ok

**Comment by rohitdobariya** [comment]
Hi @promisepk it's a duplicate ticket. I have created same https://github.com/amzn/selling-partner-api-docs/issues/1101

**Comment by promisepk** [comment]
No data will always return  processingStatus=CANCELLED

**Comment by abuzuhri** [comment]
> No data will always return processingStatus=CANCELLED

I notes that when i request report for time less than 5 days i get CANCELLED status and the same if i fill enddate , I should only fill startdate .


there is no documentation for this problem in amazon https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#performance-reports but i notes that after testing many times


Its better to add this information in amazon doc
