### ISSUE TITLE
'message': 'Request has missing or invalid parameters and cannot be parsed.',  | Item Listing

### ISSUE THREAD

**Issue by Emizy** [amzn/selling-partner-api-docs#1206]
HELP NEEDED !!!

API ACTION
       PUT /listings/2020-09-01/items/{sellerId}/{sku}
      Operation: putListingsItem
      Description: Creates a new or fully-updates an existing listings item for a selling partner.

We having been trying to make use of the above endpoint just to upload / list our product  on amazon but we kept getting 'message': 'Request has missing or invalid parameters and cannot be parsed.', as response even though the message is well descriptive but currently had know clue on  cause of  the error.

Action Taken so far:
  1. Call the product definition endpoint which returns appropriate schema however its only return Product as the product type
  2. Construct the json equivalent of the schema returns via product definition endpoint ,which its passed with the picture below 
  3.
![image_2021-08-07_214633](https://user-images.githubusercontent.com/27526954/128613471-925cbbe2-b3e5-44a1-80c7-3873ed1ea99f.png)
sample json "brand": [
            {"value": "Sony", "marketplace_id": "A2NODRKZP88ZB9", "language_tag": "sv_SE"}
        ],
        "bullet_point": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "Breathable leather lining"
            },
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "Breathable leather lining 2"
            },
        ],
        "color": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "Cranberry"
            }
        ],
4. Validated using python jsonschema and return valid
5. make a request to the endpoint with this payload {'body': {'productType': 'PRODUCT', 'requirements': 'LISTING', 'attributes': {'brand': [{'value': 'Sony', 'marketplace_id': 'A2NODRKZP88ZB9', 'language_tag': 'sv_SE'}],}}

After passing through all the above process its always return 'message': 'Request has missing or invalid parameters and cannot be parsed.',

Currently don't know what exactly am doing wrong ,I will so much appreciate if you can point me to the right direction as this has really taken alot of my time just to get it working.

**Comment by hongtao0770** [comment]
Hi @Emizy !

I encountered the same mistake. Have you solved it?

Thank you.

**Comment by hashhesh** [comment]
Hi all

have any one solved have at least workarounds for this issue, I keep receiving this error 'The Amazon product type specified is invalid or not supported' whatever the productType I pass, it return with the sam error.

I hope one of amazon team read this thread soon because, it's really painful to have Feed and putListingsItem.
