### ISSUE TITLE
Listings Items - Get API

### ISSUE THREAD

**Issue by sellxgo-dev** [amzn/selling-partner-api-docs#1207]
I want to get Listing items for given seller, how do I do that. 
I dont see such API in
 https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md
Above link has create, delete and patch operation.

Also, I am interested to know what are filters it can expect. like date, type of product, etc.

**Comment by johnkw** [comment]
As far as I can tell, the only way to get listings is from the "Category Listings Report".  I agree this is a ridiculous situation though.  There needs to be a simple `GET` call for listings.  Right now the "listings-items-api" seem unusable.  See also bug #1025 for it being mostly undocumented in general, and bug #910 for the update being odd as well.

Until there's a reasonable `GET` option, I'm too scared to even try the arcane `PATCH` stuff, in case I get something wrong and can't figure out what I changed incorrectly.

**Comment by MST1122** [comment]
@johnkw are you listing items with LISTING API?

**Comment by johnkw** [comment]
No, I'm still using the non-API feed stuff, since as mentioned above the current API is too scary.  I can't risk breaking things.  This API needs a `GET` operation, and either simpler update operations, or at least dramatically improved documentation on them.

**Comment by hongtao0770** [comment]
@johnkw

 **listingsItems_2020-09-01**

How should I create a product with this?

**Comment by johnkw** [comment]
I haven't used it and wouldn't recommend it. The API needs a simple `GET` call to return all listings. @chapmanjw mentioned in bug #1025 at least improving the documentation, but without a simple straightforward `GET` to return all listings, it seems ridiculously scary - you're just sort of stabbing around in the dark.

**Comment by hongtao0770** [comment]
Hi @johnkw,

Is there another way to add a product? 

Thank you.

**Comment by johnkw** [comment]
https://sellercentral.amazon.com/inventory etc.

**Comment by hongtao0770** [comment]
Hi @johnkw,

Thank you for your patience.
Is there any way to add a product through the API?

Thanks.

**Comment by johnkw** [comment]
As per bug #440 this is now available.  As per bug #440 it still could use much more documentation, but I think this ticket can be closed.

**Comment by AnsonHwang86** [comment]
> I want to get Listing items for given seller, how do I do that. I dont see such API in https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md Above link has create, delete and patch operation.
> 
> Also, I am interested to know what are filters it can expect. like date, type of product, etc.

Hello, is this update? I want to get all listing's SKU for given seller(include merchant fullfilment and FBA), the FBA-inventory-api get only SKU of FBA's listings.
