### ISSUE TITLE
 response format is not in json type in solicitations for error

### ISSUE THREAD

**Issue by GenderAPI** [amzn/selling-partner-api-docs#121]
POST /solicitations/v1/orders/{amazonOrderId}/solicitations/productReviewAndSellerFeedback

i get below response error but not in json format

{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "You canâ€™t use this feature to request a review outside the 5-30 day range after the order delivery date.",
      "details": ""
    }
  ]

end charecter is missing

**"}"**

**Comment by rugved1991** [comment]
Thank you for the feedback, We are looking into it to see if there is any issue.

Thanks,
Rugved
Selling Partner API Developer Support

**Comment by rugved1991** [comment]
Thank you for bringing this to our attention. The team has fixed this issue and the response is now received in the correct JSON format.

Thanks,
Rugved
Selling Partner API Developer Support
