### ISSUE TITLE
Queries_SP API_Access

### ISSUE THREAD

**Issue by thunderbolt52** [amzn/selling-partner-api-docs#1214]
Hi,
I have few queries:

1.	How we can design our URI for sandbox calling, do we really need separate endpoints for sandbox authentication and production authentication for generating access token? Is it like for sandbox we only need header change mentioning as version=beta? 
2.	How we encode the request parameter while requesting Access token?
3.	Once we have access token generated, how we can access resource(like Orders, catalog etc) using SP API? Do we have predefined URI without need to Sign the request?

**Comment by RJEspera** [comment]
Sandbox and Prod authentication process flow are the same, the main difference is the endpoint. For sandbox you have to prefix the url with 'sandbox'.

**Comment by thunderbolt52** [comment]
@RJEspera 
Thank you..
1. Do you have any documentation for getting access token ?  
2. Are you aware of how to access resource using access token?
