### ISSUE TITLE
Updating Handling Time without updating Inventory

### ISSUE THREAD

**Issue by iosdevel** [amzn/selling-partner-api-docs#1223]
Does anyone know a way to update product offer handling time without resorting to product feeds as product feeds seems to require the updating of inventory which I do not want to do due to the unreliableness of receiving updated inventory numbers for fast selling products.

Many thanks in advance

**Comment by stefnats** [comment]
That's a good question. Plus: how to update quantities of a listing without having Amazon reset the handling time (aka lead time to ship / fulfillment latency)
