### ISSUE TITLE
Feature request: expose restock limits data

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#1224]
Please expose the Restock Limits data.

Not to be confused with "Restock Inventory Report" (`GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT`)

I'm talking about this report:

![screenshot-20210810T121955-BXLMg9Bf](https://user-images.githubusercontent.com/491247/128812228-843f31dc-0f6a-410d-a923-cf62a9328a69.png)

**Comment by chloe-envision** [comment]
+1, we would also like to see this exposed via the API. It's causing a lot of headaches for us.

**Comment by xbaha** [comment]
++++ I can't believe it's not there! how can I make a shipment if i can't check the limit???

**Comment by 15184351573** [comment]
+1

**Comment by johnkw** [comment]
Adding some keywords for the benefit of other people searching for this: Amazon FBA restock limits report or MWS / SP-API call.

Also +1, because wow is this a weird glaring hole in the API.

**Comment by miniyuuzhan** [comment]
Adding weight to the this request.
Not sure if this is the best channel to do so, but we could definitely like to have this information available on some FBA inventory reports.

**Comment by pierre-leblanc** [comment]
Adding weight to this request.
Not sure if this is the best channel to do so, but we could definitely like to have this information available on some FBA inventory reports.

**Comment by krithic15** [comment]
Hello,

Thank you for your suggestion. We have submitted your feature request to the appropriate team.
Thanks,
Krithi, Solutions Architect
Selling Partner Developer Services

**Comment by daiqi77777** [comment]
+1

**Comment by thisisjake** [comment]
+1

**Comment by amistry007** [comment]
+1

**Comment by midi-red** [comment]
Hello  @chapmanjw Is there any updates on this feature request? It has been long time since this feature request was submitted.
