### ISSUE TITLE
How to get the total cost of CPC(including SP, SD SB)

### ISSUE THREAD

**Issue by mcisys** [amzn/selling-partner-api-docs#1229]
I want to get the CPC spent of a shop, could you please show me where and how I can fetch this data?

**Comment by stefnats** [comment]
I think the selling partner Api is not suitable for this, have you tried connecting to the Amazon advertising Api instead?

**Comment by mcisys** [comment]
Yes, I also have searched in Amazon advertising API, but I don't know which api to use.

**Comment by tspicer** [comment]
This is specific to the Amazon Advertising API, not Selling Partner API(s). CPC may be a calculated metric, meaning Amazon supplies the costs and clicks and you can easily calculate CPC, CPA, and other metrics.

**Comment by mcisys** [comment]
OK, I know, thanks.
