### ISSUE TITLE
/orders/v0/orders/{AmazonOrderId} DefaultShipFromLocationAddress

### ISSUE THREAD

**Issue by rodrigojob** [amzn/selling-partner-api-docs#123]
When I make the GET for /orders/v0/orders/{AmazonOrderId} the field DefaultShipFromLocationAddress come with my address.
This is not sense.
The correct is come seller's Default Address

**Comment by JacksonJeans** [comment]
Hello @rodrigojob ,

The OrderV0 API has no attributes called `DefaultShipFromLocationAddress`.

Instead `AssignedShipFromLocationAddress` is now used for "DefaultFromAddress".

[...]
"The recommended location for the seller to ship the items from. It is calculated at checkout. The seller may or may not choose to ship from this location."
[...]

[Selling Partner API for Orders](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#order)

**Comment by dlumpp** [comment]
I am calling the `getOrder` operation in the NA sandbox (https://sandbox.sellingpartnerapi-na.amazon.com) and also getting a response with a `DefaultShipFromLocationAddress` and no `AssignedShipFromLocationAddress`. 

I haven't tried a call to a production endpoint to know if this is limited to the sandbox. 

Here is the full response payload from `/orders/v0/orders/TEST_CASE_200`
```
{
    "payload": {
        "AmazonOrderId": "902-1845936-5435065",
        "PurchaseDate": "1970-01-19T03:58:30Z",
        "LastUpdateDate": "1970-01-19T03:58:32Z",
        "OrderStatus": "Unshipped",
        "FulfillmentChannel": "MFN",
        "SalesChannel": "Amazon.com",
        "ShipServiceLevel": "Std US D2D Dom",
        "OrderTotal": {
            "CurrencyCode": "USD",
            "Amount": "11.01"
        },
        "NumberOfItemsShipped": 0,
        "NumberOfItemsUnshipped": 1,
        "PaymentMethod": "Other",
        "PaymentMethodDetails": ["Standard"],
        "IsReplacementOrder": false,
        "MarketplaceId": "ATVPDKIKX0DER",
        "ShipmentServiceLevelCategory": "Standard",
        "OrderType": "StandardOrder",
        "EarliestShipDate": "1970-01-19T03:59:27Z",
        "LatestShipDate": "1970-01-19T04:05:13Z",
        "EarliestDeliveryDate": "1970-01-19T04:06:39Z",
        "LatestDeliveryDate": "1970-01-19T04:15:17Z",
        "IsBusinessOrder": false,
        "IsPrime": false,
        "IsGlobalExpressEnabled": false,
        "IsPremiumOrder": false,
        "IsSoldByAB": false,
        "DefaultShipFromLocationAddress": {
            "Name": "MFNIntegrationTestMerchant",
            "AddressLine1": "2201 WESTLAKE AVE",
            "City": "SEATTLE",
            "StateOrRegion": "WA",
            "PostalCode": "98121-2778",
            "CountryCode": "US",
            "Phone": "+1 480-386-0930 ext. 73824",
            "AddressType": "Commercial"
        },
        "FulfillmentInstruction": {
            "FulfillmentSupplySourceId": "sampleSupplySourceId"
        },
        "IsISPU": false
    }
}
```

**Comment by qiangvei** [comment]
https://gitee.com/qiangvei/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderlist 
The name written in the document here is "AssignedShipFromLocationAddress", there is no "AssignedShipFromLocationAddress" in the actual returned name, only the name "DefaultShipFromLocationAddress", is it wrong?
