### ISSUE TITLE
VendorShipping-submitShipmentConfirmations Error

### ISSUE THREAD

**Issue by fengyuduke** [amzn/selling-partner-api-docs#1231]
Excuse me, I received an unexcept result when I tried to request the interface submitShipmentConfirmations for VendorShipping.

URL : https://sellingpartnerapi-na.amazon.com/vendor/shipping/v1/shipmentConfirmations

parameter ： 
class SubmitShipmentConfirmationsRequest {
    shipmentConfirmations: [class ShipmentConfirmation {
        shipmentIdentifier: 32802874962
        shipmentConfirmationType: Original
        shipmentType: SmallParcel
        shipmentStructure: null
        transportationDetails: class TransportationDetails {
            carrierScac: UPSN
            carrierShipmentReferenceNumber: 
            transportationMode: Road
            billOfLadingNumber: 
        }
        amazonReferenceNumber: 14529473801
        shipmentConfirmationDate: 2021-08-12T17:18:47.663+08:00
        shippedDate: 2021-08-11T00:00+08:00
        estimatedDeliveryDate: 2021-08-18T00:00+08:00
        sellingParty: class PartyIdentification {
            address: null
            partyId: RG6EF
            taxRegistrationDetails: null
        }
        shipFromParty: class PartyIdentification {
            address: null
            partyId: LN6CR
            taxRegistrationDetails: null
        }
        shipToParty: class PartyIdentification {
            address: null
            partyId: CLT2
            taxRegistrationDetails: null
        }
        shipmentMeasurements: class ShipmentMeasurements {
            grossShipmentWeight: class Weight {
                unitOfMeasure: G
                value: 3904
            }
            shipmentVolume: class Volume {
                unitOfMeasure: CuM
                value: 0.09
            }
            cartonCount: 2
            palletCount: 0
        }
        importDetails: null
        shippedItems: [class Item {
            itemSequenceNumber: 1
            amazonProductIdentifier: B098THKMPQ
            vendorProductIdentifier: 766990411188
            shippedQuantity: class ItemQuantity {
                amount: 10
                unitOfMeasure: Eaches
                unitSize: 1
            }
            itemDetails: class ItemDetails {
                purchaseOrderNumber: 4RMRZ8GU
                lotNumber: 
                expiry: class Expiry {
                    manufacturerDate: null
                    expiryDate: null
                    expiryAfterDuration: null
                }
                maximumRetailPrice: null
                handlingCode: null
            }
        }, class Item {
            itemSequenceNumber: 3
            amazonProductIdentifier: B09B2FDGMJ
            vendorProductIdentifier: 760932329487
            shippedQuantity: class ItemQuantity {
                amount: 2
                unitOfMeasure: Eaches
                unitSize: 1
            }
            itemDetails: class ItemDetails {
                purchaseOrderNumber: 4RMRZ8GU
                lotNumber: 
                expiry: class Expiry {
                    manufacturerDate: null
                    expiryDate: null
                    expiryAfterDuration: null
                }
                maximumRetailPrice: null
                handlingCode: null
            }
        }]
        cartons: [class Carton {
            cartonIdentifiers: [class ContainerIdentification {
                containerIdentificationType: AMZNCC
                containerIdentificationNumber: AMZNCC00004466452485
            }]
            cartonSequenceNumber: 0002
            dimensions: null
            weight: null
            trackingNumber: 1ZR873R70323009702
            items: [class ContainerItem {
                itemReference: 1
                shippedQuantity: class ItemQuantity {
                    amount: 10
                    unitOfMeasure: Eaches
                    unitSize: 1
                }
                itemDetails: null
            }]
        }, class Carton {
            cartonIdentifiers: [class ContainerIdentification {
                containerIdentificationType: AMZNCC
                containerIdentificationNumber: AMZNCC00004466452481
            }]
            cartonSequenceNumber: 0001
            dimensions: null
            weight: null
            trackingNumber: 1ZR873R70327672916
            items: [class ContainerItem {
                itemReference: 3
                shippedQuantity: class ItemQuantity {
                    amount: 2
                    unitOfMeasure: Eaches
                    unitSize: 1
                }
                itemDetails: null
            }]
        }]
        pallets: null
    }]
}

return : payload: class TransactionStatus {
        transactionStatus: class Transaction {
            transactionId: 636afb1c-9e89-4803-885c-a061dc20eaab-20210812030040
            status: Failure
            errors: class ErrorList {
                [class Error {
                    code: OLD_QuantityMatchesOrder_OLD
                    message: The ASN '32802874962'  (BSN02) has excess item quantities for the following PO-ASIN combinations : ' PO 4RMRZ8GU: B098THKMPQ,B09B2FDGMJ' . Amazon expects that quantity mentioned in the ASN should not be more than the difference of confirmed quantity and quantities submitted across previous ASNs. To review the quantities mentioned on previous ASNs please refer to VENDOR CENTRAL > SHIPMENTS > VIEW RECENT SHIPMENTS. It lists the ASNs submitted by you in last 90 days and you can search on the webpage using the PO# to find the previously submitted ASN for the same PO.
                    details: Please review the ASN to ensure that the quantities are accurate and in accordance with the shipment.  If they are accurate there is no action required on your end. \n\nIf you notice a mismatch, please submit an updated EDI 856 with corrected line-item quantities.
                }]
            }
        }
    }

*********************************************************************
I have checked the quantity mentioned in the ASN is not more than the difference of confirmed quantity and quantities submitted across previous ASNs.

![image](https://user-images.githubusercontent.com/48078087/129192793-4c481ba0-ba3b-44d2-a4c5-06457f34e1b4.png)

![image](https://user-images.githubusercontent.com/48078087/129192945-41689aea-34a3-4571-8977-184339b25cf1.png)

No ASNs have been submitted about this PO before.

**Comment by wonsky87** [comment]
这个ASN是后台生成的shipment Id，非彼ASIN

**Comment by wonsky87** [comment]
请问这个解决了吗？
