### ISSUE TITLE
FBA Reports Access Denied

### ISSUE THREAD

**Issue by zoborg** [amzn/selling-partner-api-docs#1234]
Using MWS we can successfully request and retrieve any types of report, since migrating to SP-API the following reports work correctly for example..

GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2

However when requesting 

GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA

We receive Unauthorized, is this a bug or expected behaviour? and if expected behaviour what scope is required to request this?

**Comment by kevnhowe** [comment]
I am having trouble when trying to get the Report Document Data. The session token is failing. How are you calling the GetReportDocumentData() method? Are you using the signed header with the security token?

**Comment by codingkondi** [comment]
I got same problem with this, while I called GetReports with GET_AFN_INVENTORY_DATA type and it would reply 403

**Comment by iamsr** [comment]
same issue
