### ISSUE TITLE
upload - createUploadDestinationForResource, python, [{'code': 'InvalidInput', 'message': 'Invalid Input', 'details': ''}]

### ISSUE THREAD

**Issue by boxlee82** [amzn/selling-partner-api-docs#1238]
none

**Comment by boxlee82** [comment]
url
https://sellingpartnerapi-na.amazon.com/uploads/2020-11-01/uploadDestinations/messaging/v1/orders/111-5856041-xxxxxxx/messages/warranty?marketplaceIds=ATVPDKIKX0DER&contentMD5=214178e487138b5b90f74f58e76a0a78

**Comment by poeily** [comment]
Hello, have you solved your problem. I have the same problem as you, on the createreport method
