### ISSUE TITLE
Feeds API 2021-06-30 returns SignatureDoesNotMatch while posting the Order Ack Feed

### ISSUE THREAD

**Issue by sugatabagchi** [amzn/selling-partner-api-docs#1239]
Hello,
I am using the above version of feed API and trying to post Order Ack. but it is showing Signature does not match error.
I have done the following - 
Step1- call the createFeed Operation  
Successfully received the response with URL and feedID

Step2 -  called the received pre-signed s3 URL in step 1 thru a Java program (w/o any creds. or permission) to post the Order Ack. XML.

but received the below error - 
`
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>intentionally removed</AWSAccessKeyId><StringToSign>AWS4-HMAC-SHA256
20210813T231457Z
20210813/us-east-1/s3/aws4_request
886fe7fc6b1cbede4f11dd4fcaf638d610e150cf6d6fe7e967d0f1ef1fb648c0</StringToSign><SignatureProvided>0747bae6a7b6ef989afc66baa212c2be3f54d7b7d9c0e3b6da250c622bf098ec</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 31 30 38 31 33 54 32 33 31 34 35 37 5a 0a 32 30 32 31 30 38 31 33 2f 75 73 2d 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 38 38 36 66 65 37 66 63 36 62 31 63 62 65 64 65 34 66 31 31 64 64 34 66 63 61 66 36 33 38 64 36 31 30 65 31 35 30 63 66 36 64 36 66 65 37 65 39 36 37 64 30 66 31 65 66 31 66 62 36 34 38 63 30</StringToSignBytes><CanonicalRequest>POST
//NinetyDays/amzn1.tortuga.3.367fda9b-7d04-461b-8b8e-80ca62c3b136.T385RI7PKRD2X8
X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=<accesskey removed>%2F20210813%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20210813T231457Z&amp;X-Amz-Expires=300&amp;X-Amz-SignedHeaders=content-type%3Bhost
content-type:text/xml; charset=utf-8
host:tortuga-prod-na.s3-external-1.amazonaws.com

content-type;host
UNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>50 4f 53 54 0a 2f 2f 4e 69 6e 65 74 79 44 61 79 73 2f 61 6d 7a 6e 31 2e 74 6f 72 74 75 67 61 2e 33 2e 33 36 37 66 64 61 39 62 2d 37 64 30 34 2d 34 36 31 62 2d 38 62 38 65 2d 38 30 63 61 36 32 63 33 62 31 33 36 2e 54 33 38 35 52 49 37 50 4b 52 44 32 58 38 0a 58 2d 41 6d 7a 2d 41 6c 67 6f 72 69 74 68 6d 3d 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 26 58 2d 41 6d 7a 2d 43 72 65 64 65 6e 74 69 61 6c 3d 41 4b 49 41 35 55 36 4d 4f 36 52 41 46 42 4f 51 4e 4c 54 46 25 32 46 32 30 32 31 30 38 31 33 25 32 46 75 73 2d 65 61 73 74 2d 31 25 32 46 73 33 25 32 46 61 77 73 34 5f 72 65 71 75 65 73 74 26 58 2d 41 6d 7a 2d 44 61 74 65 3d 32 30 32 31 30 38 31 33 54 32 33 31 34 35 37 5a 26 58 2d 41 6d 7a 2d 45 78 70 69 72 65 73 3d 33 30 30 26 58 2d 41 6d 7a 2d 53 69 67 6e 65 64 48 65 61 64 65 72 73 3d 63 6f 6e 74 65 6e 74 2d 74 79 70 65 25 33 42 68 6f 73 74 0a 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 74 65 78 74 2f 78 6d 6c 3b 20 63 68 61 72 73 65 74 3d 75 74 66 2d 38 0a 68 6f 73 74 3a 74 6f 72 74 75 67 61 2d 70 72 6f 64 2d 6e 61 2e 73 33 2d 65 78 74 65 72 6e 61 6c 2d 31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 0a 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3b 68 6f 73 74 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44</CanonicalRequestBytes><RequestId>TS1H7BA6FWE8JYDE</RequestId><HostId>n71aFzGB8hBcJ3MICsJJvLpCpmMWZqGoaivHEctRM6uGIsPMHFz/gNDDdF78JKRg08CJ5N5Yjfw=</HostId></Error>
`

could anyone please help what am I missing here?

Thanks
Sugata

**Comment by sugatabagchi** [comment]
opened a case to amazon support ID8707015141

**Comment by sugatabagchi** [comment]
The new version of feed API says to POST the feed to the presigned s3 URL, which is not correct- you must use a PUT.
This is resolved by me and closing this thread.

**Comment by sugatabagchi** [comment]
I was able resolve the issue. Here is what I have done -

    call the create feed API to get the URL and feed document ID
    use the above S3 URL which is a presigned URL to upload the XML feed - this is something not correctly documented in the API spec for feeds 2021-06-30. IT SHOULD BE HTTP PUT and NOT HTTP POST.

And I was able to upload the feed and received HTTP 200 w/o a body. After this I called the feed stauts API and cofirmed the feed was uploaded correctly.
also, make sure while uploading the feed using the s3 URL use the same content type header you used in the createFeed API call.

Thanks
Sugata

**Comment by vitahlin** [comment]
Sample code:
```java
String contentType = "application/xml; charset=UTF-8";
CreateFeedDocumentSpecification specification = new CreateFeedDocumentSpecification();
specification.setContentType(contentType);
ApiResponse<CreateFeedDocumentResponse> httpInfo = feedsApi.createFeedDocumentWithHttpInfo(specification);
CreateFeedDocumentResponse response = httpInfo.getData();

 OkHttpClient client = new OkHttpClient();

String contentType = String.format("application/xml; charset=%s", StandardCharsets.UTF_8);
Request request = new Request.Builder()
    .url(url)
    .put(RequestBody.create(MediaType.parse(contentType), xmlContent))
    .build();
Response response = client.newCall(request).execute();
if (!response.isSuccessful()) {
}
```


The content type of upload document must be the same as createFeedDocument request
