### ISSUE TITLE
My application has not been published，Can I use SP-API to call next?

### ISSUE THREAD

**Issue by shuaiys** [amzn/selling-partner-api-docs#124]
My application has not been published, but I have completed my self-authorization. Can I use SP-API to call next? But now I call the API and always return Forbidden.

**Comment by GenderAPI** [comment]
i am in same state
i can access the application with owner of the application.
and i had access non owner of the application
but today i disconnect the application. and try to reconnect with beta. 

i lost my access non owner of seller

**Comment by GenderAPI** [comment]
i can get access token and refresh token but when i try to send request to end point a get unauthorized error

**Comment by rodrigojob** [comment]
> My application has not been published, but I have completed my self-authorization. Can I use SP-API to call next? But now I call the API and always return Forbidden.

I believe that Yes. I use it like that.

**Comment by rodrigojob** [comment]
> i can get access token and refresh token but when i try to send request to end point a get unauthorized error

Are you signed your requisition?

**Comment by rodrigojob** [comment]
> i lost my access non owner of seller

Use refresh_token.

**Comment by GenderAPI** [comment]
> > i can get access token and refresh token but when i try to send request to end point a get unauthorized error
> 
> Are you signed your requisition?

yes i request for publish.

it is accepted but waiting for translations for 10 days

**Comment by rodrigojob** [comment]
No. 
You use authorization headers?

**Comment by GenderAPI** [comment]
i can get 
?selling_partner_id=****&spapi_oauth_code=****&state=***
and i can get access_token from parameters
and i can also get refresh_token

but i can not send success to end points with new tokens.

this for non application owner
but for application owner i can access

**Comment by GenderAPI** [comment]
this is why i get this error i disconnect application from the sellercentral application management page
before i can access

**Comment by charliecode** [comment]
Hello @shuaiys and @GenderAPI! Your tokens will not work for production calls until you submit your app for review in Developer Central and Amazon approves it. I encourage you to look at issue #66 which will give a more detailed explanation. Also issue #79 as it's a repeat of this issue.

**Comment by shuaiys** [comment]
Hello, thank you for your answer. I mean I am the owner of the program and I have completed my self-authorization. Can I access my own seller data through the api before I publish my program? Not other sellers.

**Comment by charliecode** [comment]
@shuaiys Yes, you can get your own data after you complete the self authorization. Amazon updated the docs today to help everyone understand this better. If you haven't read over the docs since earlier today, I would encourage you to look now as that section is a lot easier to understand.

**Comment by shuaiys** [comment]
thank you
