### ISSUE TITLE
[FEATURE] Documentation about a Report Schema

### ISSUE THREAD

**Issue by sleipi** [amzn/selling-partner-api-docs#1247]
**Describe the improvement**
Add a Schema documentation for the all existing Report Types. There is currently no documentation out there which describe the content of a Report Document and it makes it very hard for an Integrator to implement new reports types. Implement a new Report Type is mostly a try and error process with real seller credentials and operating on sensitive data.

**Description of what the documentation should say**
- In case of XML Reports a simple XSD Schema would be helpful
- In case of a Flat File describe
  - Properties (Columns)
  - Content Schema (string, number, ...) 
  - Is the field required/optional

**Comment by wolendranh** [comment]
hi @sleipi ! 

Thats not strictly API docs, but I found https://sellercentral.amazon.com/gp/help/help.html?itemID=201074420& useful in some cases.
