### ISSUE TITLE
[BUG] FbaOutbound

### ISSUE THREAD

**Issue by wehrmannit** [amzn/selling-partner-api-docs#1249]
When trying to create a FbaOutbound order, I receive this message:

```
 [400] {
    "errors": [
      {
        "code": "InvalidInput",
        "message": "Value  for parameter SellerId is invalid. Reason: InvalidValue.",
        "details": ""
      }
    ]
  }
```

Interestingly, the same code worked fine before, at least to my knowledge.

This is what I'm trying to POST:

```
Array
(
    [seller_id] => XX
    [ship_from_country_code] => PL
    [seller_fulfillment_order_id] => XX
    [displayable_order_id] => XX
    [displayable_order_comment] => Import
    [displayable_order_date] => 2021-08-15T10:17:38.000000Z
    [shipping_speed_category] => Standard
    [destination_address] => SellingPartnerApi\Model\FbaOutbound\Address Object
        (
            [container:protected] => Array
                (
                    [name] => XX
                    [address_line1] => XX
                    [address_line2] =>
                    [address_line3] =>
                    [city] => XX
                    [district_or_county] => XX
                    [state_or_region] =>
                    [postal_code] => XX
                    [country_code] => PL
                    [phone] => XXX
                )

        )

    [fulfillment_action] => Hold
    [items] => Array
        (
            [0] => SellingPartnerApi\Model\FbaOutbound\CreateFulfillmentOrderItem Object
                (
                    [container:protected] => Array
                        (
                            [seller_sku] => XXXX
                            [seller_fulfillment_order_item_id] => XXXX
                            [quantity] => 1
                            [gift_message] =>
                            [displayable_comment] =>
                            [fulfillment_network_sku] =>
                            [per_unit_declared_value] =>
                            [per_unit_price] =>
                            [per_unit_tax] =>
                        )

                )

        )

)


```

I've checked the documentation and there is no mention of seller_id being required. However, I tried adding the sellerId (in various notions) to the body and header, to no avail.

The request path is:
`/fba/outbound/2020-07-01/fulfillmentOrders`

I've tried this:

> Checked if the SKU is correct
> Checked if the SKU is available in the marketplace
> Checked if a random SKU would return a different result; it doesn't. 
> Checked if changing random values would change something...; nope.
> Checked if changing the address would change the response.
> Replaced MarketplaceID with shipment_from_country_code as suggested from other issues; when having both parameters, I get another error, with useful information, so that's fine.
> Checked if changing the order_id values would change something...

I'm at my wits' end and could need help. Anyone having the same issue?

**Comment by chenlixin93** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md#createfulfillmentorderrequest

@wehrmannit  There's no need to send the `SellerId` .

**Comment by wehrmannit** [comment]
> 
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md#createfulfillmentorderrequest
> 
> @wehrmannit There's no need to send the `SellerId` .

Yeah I know, but why would I get that "seller id is missing" error message?
