### ISSUE TITLE
Invalid Client

### ISSUE THREAD

**Issue by tharrington** [amzn/selling-partner-api-docs#125]
I am using this endpoint:

https://api.amazon.com/auth/o2/token
with params:
grant_type=refresh_token
refresh_token=VALUE_FROM_SELLER_CENTRAL_APP
client_id=VALUE_FROM_SELLER_CENTRAL_APP
client_secret=VALUE_FROM_SELLER_CENTRAL_APP

But I receive an invalid_client error (401).

If I look at the seller central app, there is a status:

Current edit is saved as draft

Is this the problem?

**Comment by rodrigojob** [comment]
for Selling Partner You have to do post with header             
'Host: api.amazon.com',
            'Content-Type: application/x-www-form-urlencoded'

And to LWA with
            'Host: api.amazon.com',
            'Authorization: Basic ' . base64_encode(client_id . ":" . client_secret),
            'Content-Type: application/json;charset=UTF-8'

**Comment by tharrington** [comment]
@rodrigojob I added the host to the header and I am getting the same error. What would the full curl request look like?

**Comment by tharrington** [comment]
@rodrigojob Ultimately I am trying to get this working in postman, FYI. Thanks in advance.

**Comment by rugved1991** [comment]
Try creating a new request in Postman. Sometimes there might be caching issue on Postman. This is a curl request from Postman:
curl --location --request POST 'https://api.amazon.com/auth/o2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'client_id=YOUR_APP_CLIENT_ID' \
--data-urlencode 'client_secret=YOUR_APP_CLIENT_SECRET' \
--data-urlencode 'refresh_token=YOUR_REFRESH_ROKEN'

**Comment by tharrington** [comment]
@rugved1991 Awesome, I got it working in Postman. However, I make a subsequent GET request:

https://sellingpartnerapi-na.amazon.com/orders/v0/orders?marketplace=ATVPDKIKX0DER

With the token received in the first call as a header param:

x-amz-access-token : 'Atza|MYSAMPLE'

And I get MissingAuthenticationToken error.

**Comment by rugved1991** [comment]
@tharrington Can you provide the complete request and response you are receiving along with headers? Feel free to blur out sensitive data.
The request should also contain either "CreatedAfter" or "CreatedBefore" parameter.

Thanks,
Rugved
Selling Partner API Developer Support

**Comment by tharrington** [comment]
@rugved1991 I believe I need to create and sign the canonical request. Is there a way to do this within postman?

**Comment by rugved1991** [comment]
@tharrington You can refer to the following links for more information:
https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-use-postman-to-call-api.html
https://learning.postman.com/docs/sending-requests/authorization/#aws-signature

If you are using IAM User in your app, leave "Session Token" empty. If you are using IAM Role, you will first have to create temporary credentials and then fill out the values in Postman.

Thanks,
Rugved
Selling Partner API Developer Support

**Comment by tharrington** [comment]
@rugved1991 I am still receiving 

```
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
```

In the headers, I am putting x-amz-access-token and the token I got from the first call to https://api.amazon.com/auth/o2/token

Then I am putting the Access Key and Secret Key I got from AWS user into the AWS Signature on the Authorization Tab in postman.

**Comment by tharrington** [comment]
@rodrigojob @rugved1991 

Also, I am using the self-authorization functionality. It is important to note the login I am using to Seller Central is NOT the same as the login I am using to AWS.

**Comment by tharrington** [comment]
@rodrigojob @rugved1991 Any ideas?

**Comment by tharrington** [comment]
First of all a huge thank you to @rogersv for helping debug this. Ultimately, I have to make a call to the STS endpoint to get an access key, secret access key, and session token. The session token is then added as a key value pair in the orders GET request with key x-amz-security-token. The access key and secret access key replaces the IAM access key and secret to create the canonical signature. 

Lastly, Postman would not complete the request. I assume it has something to do with added header values. However, I was able to use the "Code" button within postman to get the request as a curl. Running this curl in the terminal worked.
