### ISSUE TITLE
Seller account inactive due to no sales past 90 days 

### ISSUE THREAD

**Issue by SteveNavarc** [amzn/selling-partner-api-docs#1258]
Hello
Im a developer and just received an email saying that my seller account is now inactive. Im confused since to apply to use the SP-APIs we had to create a seller central account and create a developer profile. Does Amazon require developers to sell or should i ignore this message? Will we still get to use the SP-APIs if our account is inactive?  I did take the appropriate steps to get reactivated. Will i need to do this every 90 days? Any help would be very appreciated! Thank you

**Comment by SteveNavarc** [comment]
@jimmy-ross-xapix I followed the directions on the email and the reactivated my account within 8 hrs so they should reactivate you soon.  I just got another email saying that they downgraded my account from Professional to Individual. I thought we needed the professional to access the apis. I just upgraded again. But my questions to the amazon team is will this process change in the future? Will developers still need a seller account to access the apis? Will it need to be a professional account? Will we need to reactivate our accounts every 90 days? Will the APIs still work during a period of inactivity? Thank you!

**Comment by Morph21** [comment]
Does it really takes so long to answer a simple question? @Amazon
