### ISSUE TITLE
Retrieving Vendor reports at scale

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#1259]
I'm looking to create an SP API application for Vendors, which will involve retrieving Vendor reports. As far as I can tell from the documentation, Vendor reports are only available to Vendor accounts with SP API developer access, and access to the `Brand Analytics` SP API role.

Since Vendor Central accounts are invite-only, I have no way of making a Vendor account in order to apply for access to the Brand Analytics role. Is there something I'm missing here? It seems like if I'm understanding the documentation correctly, there's no way to develop full-featured Vendor Central applications unless you _already_ have access to a Vendor Central account.

**Comment by jesusvalle** [comment]
I have the same doubt, I push to see if anyone can help us with some information.
