### ISSUE TITLE
unable to connect using LWA

### ISSUE THREAD

**Issue by uk-2** [amzn/selling-partner-api-docs#126]
Hi

I am trying to connect via LWA for selling api for Amazon UK but having trouble .The purpose is to connect to the API using LWA and the user approves the connection and then amazon redirects to our app.

Please could you check if my url construct is correct and scope ?

https://api.amazon.com/auth/o2/?client_id=amzn1.application-XXXX&response_type=code&redirect_uri=http%3A%2F%2Fapp.XXX.uk%2Fauth%2Famzn_spapi%2Fcallback&scope=sellingpartnerapi%3Amigration.

Does anyone have a guide we can follow for Ror ?

Thank you so much for your support !

please tell me if i need to add anything

**Comment by rodrigojob** [comment]
Try this:
https://www.amazon.com/ap/oa?client_id={YOUR-CLIENT-ID}&scope=profile&response_type=code&state={YOUR-STATE-STRING}&redirect_uri=YOUR-URI

you don't need encode the uri

**Comment by ShivikaK** [comment]
Hello @uk-2 

Please refer to below Developer guide sections to understand how to generate the LWA refresh token once you have an authorization code and then use the refresh token to generate an access token required to make calls to SP API -

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#Step-4-Your-application-exchanges-the-LWA-authorization-code-for-a-LWA-refresh-token 

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token

If you are making a request to Grantless operations, change the scope parameter accordingly along with grant_type.

If you still require further assistance, please open a support case with us so we can pursue the investigation. 

Thanks, 
Shivika Khare
 Selling Partner API Developer Support
