### ISSUE TITLE
unknown marketplaceId

### ISSUE THREAD

**Issue by Feng-Xg** [amzn/selling-partner-api-docs#1260]
When I called sellers-api to request getMarketplaceParticipations, I got five marketplaceId, but I didn't know means about A1MQXOICRS2Z7M、A2ZV50J4W1RKNI、A3H6HPSLHAK3XG、AHRY1CZE9ZY4H.
What means all of these?

**Comment by ShivikaK** [comment]
Hello @AleemFeng 

Thank you for raising the issue.

Those do not appear to correct marketplace ID values and we will need to investigate this further.

Can you please provide us the entire request details and the exact response received along with timestamp and request ID?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by AleemFeng** [comment]
@ShivikaK 

___
request detail: 
![request](https://user-images.githubusercontent.com/19472852/129832275-3b98271a-bea9-4d4d-9abf-5257a9dbd433.png)

response -header:
![response-header](https://user-images.githubusercontent.com/19472852/129832390-726bbfaf-2077-4be5-96cf-1fd696556b05.png)

response payload: 
<img width="449" alt="Lark20210818-112807" src="https://user-images.githubusercontent.com/19472852/129832417-bfdb5bf7-2d72-4583-bbba-fa1571dc7d77.png">

**Comment by SWengineer-A** [comment]
@ShivikaK is there any update on this? I got `AHRY1CZE9ZY4H` as one of  marketplaces from https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference#get-sellersv1marketplaceparticipations
