### ISSUE TITLE
How to use access token in accessing SP API?

### ISSUE THREAD

**Issue by thunderbolt52** [amzn/selling-partner-api-docs#1268]
How we can use access token in calling SP-API? Does anyone is having any idea? Code snippet is helpful.

**Comment by pucsdian** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-add-headers-to-the-uri

@thunderbolt52  check this for what should be in header with access token

**Comment by thunderbolt52** [comment]
Thanks
