### ISSUE TITLE
UPLOAD_VAT_INVOICE Feed Type not available or working

### ISSUE THREAD

**Issue by fernlop** [amzn/selling-partner-api-docs#127]
It seems like the Feed for uploading invoices is not working yet. 
It isn't mentioned in the documentation and i get an error when trying to upload it.

Feed Type: UPLOAD_VAT_INVOICE or _UPLOAD_VAT_INVOICE_

Errors i get:
{"errors":[{"code":"Unauthorized","message":"Access to the resource is forbidden","details":""}]}
or when trying with "_"
{"errors":[{"code":"InvalidInput","message":"feed type __UPLOAD_VAT_INVOICE__ is invalid","details":""}]}

**Comment by DivingUp** [comment]
HI,
did you find a solution?
I'm also looking for a way to upload invoices via the API.
Thank you

**Comment by fernlop** [comment]
I found out i can't do anything tax related. 
Maybe its a permissions problem? I requested access to tax related information in my developer application.
I contacted Amazon and asked if they can revise my permission. 

Could you try access tax information and tell me if it works? Maybe its just a problem with my account. 
You can try /finances/v0/financialEventGroups , it doesn't work for me too. 

I can provide sample code for uploading tax invoices in NodeJS if you need it.

**Comment by DivingUp** [comment]
HI,
did you find a solution ?
I've the same Problem... no UPLOAD_VAT_INVOICE Files can be uploaded... all the other API's works fine for me...
thx

**Comment by fernlop** [comment]
@DivingUp No not yet but I'm still on it. 
MWS support told me there is no such feed type and I'm now in the process of "proofing" to them that this feed type exists and get help for it. 
Just to get a better feeling for how things work, are you able to access the Financial API "financialEvents" and "financialEventGroups"? I can't access them too and this seems related to permissions with tax related APIs.

**Comment by bastien-effetb** [comment]
Hi,
@fernlop did you manage to upload your invoices ? 
Did you asked access to Tax Invoicing and Tax Remittance on your developer profile ? 
I don't know which role is used for the invoice upload...

**Comment by fernlop** [comment]
@bastien-effetb no not really, i got ALL checkboxes active in my profile, so this shouldn't be be problem. 
I'm still fighting with the Seller and MWS Support about weither this API even exists, and when they admit it, that this is a problem on the side of amazon and not mine...

**Comment by bastien-effetb** [comment]
@fernlop thank you for your update, if you manage to get this working please let me know :)

**Comment by biancahuluban** [comment]
Hi @fernlop  
How did you fix the issue of "access forbidden"?
Is it related to tax permissions or Personal Information Permission? we did not found any solution to this issue. The first 2 calls are working, the SubmitFeed is giving this response.

Happy coding,
Bianca H

**Comment by diegocvazquez** [comment]
@biancahuluban 
Hi did you find out what the problem is ? I am facing the same situation, thanks!

**Comment by diegocvazquez** [comment]
Hello there, this is working for us in MWS but not working in SP-API I am also getting a 403 error, did any of you got this sorted out? 
thanks

**Comment by mtkumar82** [comment]
Hi, I am also getting the same 403 error when trying to use UPLOAD_VAT_INVOICE feed using Amazon SP API, Anybody please , if you found solution for this help me to solve this issue?
