### ISSUE TITLE
How to know if an order was delivered

### ISSUE THREAD

**Issue by yuri-lonesomelabs** [amzn/selling-partner-api-docs#1271]
Hi, we want to preform analysis for users on orders that were delivered. The closest thing that the Orders API provides is "OrderSatus" == "Shipped". It's not good enough because we don't really know if the order was delivered or not which is crucial to what we do.

Is there a way to tell though the API that it was delievered?

**Comment by wonsky87** [comment]
_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_ . 
you can try it.
