### ISSUE TITLE
Get all shipments from an AmazonOrderId

### ISSUE THREAD

**Issue by cooshal** [amzn/selling-partner-api-docs#1272]
Hi:

my experiences with Amazon API is minimal. So, it could be possible that my question might sound naive. I have been trying to get the list of shipments and thus the shipping labels of an order via AmazonOrderId. But, I could not figure out any API endpoints to accomplish this task or I might have missed out.

I have searched through the API docs, and all the JSON specifications, but did not find the relevant stuff. Kindly, could anyone please point me to the right API? I would really appreciate that.

Thank you in advance.

Kushal.

**Comment by kpconnell** [comment]
@cooshal what do you mean by labels?  If you are just looking for tracking numbers for consumer orders, those are in the report GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL

**Comment by cooshal** [comment]
Hi @kpconnell thank you for your feedback. 

I am currently trying to fetch the tracking numbers via AmazonOrderId, and ultimately the label data (e.g. the PDF stream of the label, etc.). I will take a look at GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL, and get back.

**Comment by cooshal** [comment]
Hi @kpconnell 

I tried to invoke the reports API, and tried to fetch, for example GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL. But, I got an empty list. 

For instance:

```
GetReportsResponse response = reportsApi.getReports(
        Arrays.asList("GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL"),
        null,
        marketPlaceIds, 
        25, 
        null,
        null, 
        null
);
```
At the moment, all I wanted to do is:

1. I have an AmazonOrderIdm which could be completed or pending or anything
2. I need the tracking information of this AmazonOrderId, anything like carrier name, tracking code, etc.

Thank you :)

**Comment by kpconnell** [comment]
> Hi @kpconnell thank you for your feedback.
> 
> I am currently trying to fetch the tracking numbers via AmazonOrderId, and ultimately the label data (e.g. the PDF stream of the label, etc.). I will take a look at GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL, and get back.

GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL provides the tracking number and carrier, I'm not sure why you would need a label...   please read all of the documentation about how to get a report in this repo under use cases, it is covered extensively.
