### ISSUE TITLE
What's the best way to handle this scenario : mistakenly use IAM ARN User instead of suggested IAM ARN Role in my hybrid App registration

### ISSUE THREAD

**Issue by isolutiontech** [amzn/selling-partner-api-docs#1274]
We have an existing MWS app in Appstore, so I'm migrating it to a hybrid App by following the office Guide step by step. The IAM ARN User and Role is created and completed the whole App registration process. Now it's published and registered as a hybrid App.

While testing the SP-API, I got the 403 "Access to requested resource is denied" error and only found out that in my app registration, I mistakenly put the IAM ARN User instead of Role in 'IAM ARN' field which is recommended by the official Guide.  Would like to correct the mistake but that field is greyed out and not allowed to change once filled in. 

I contacted Amazon dev support, but the response is to register a new app. This is not a solution. We need to migrate the existing app to a hybrid app so we can support the existing sellers without go through the authorization process with a new app.

So I'm wondering what's the best approach for a solution? Can Amazon suggest a real solution?

1. Amazon support somehow finds a way to correct the IAM ARN field?

2. I can actually use the IAM ARN User.
    then my question is what I need to do, is there documentation I can follow step by step?
    I read some threads here, people suggested using IAM ARN User in the first place. 
    Since I followed the official Guide to complete the whole thing, now to use ARN User, do I need to undo some things in IAM? Also what're the undocumented steps for ARN User?

help is much appreciated.

**Comment by One2r** [comment]
hi,@isolutiontech 
how do you resolve this? I encountered the same problem.

**Comment by isolutiontech** [comment]
you can use RAN User without changing any registration.

See this sample code here, it gives the samples to use Role and User.
https://github.com/clousale/amazon-sp-api-php
