### ISSUE TITLE
The BuyerInfo and ShippingAddress of the orders(/orders/v0/orders ) returned by the Orders-API are empty

### ISSUE THREAD

**Issue by xiazhaozhao** [amzn/selling-partner-api-docs#1275]
Dear, why is the seller information and delivery address returned by calling the RDT interface empty, the order status is delivered, and the information can be obtained by calling getOrderBuyerInfo and getOrderAddress separately.

Thanks!

**Comment by BillyGWML** [comment]
We are having the same issues.  It started 8/17/21 with a few orders. Now it's every order. No Customer Name and no Address1

**Comment by Mikki-U** [comment]
Same problem on our end too, started yesterday. Anyone have any solutions?

**Comment by BillyGWML** [comment]
Discussion is going on here with some good ideas: https://sellercentral.amazon.com/forums/t/intermitent-pii-missing-on-seller-fulfilled-orders/896438/14

**Comment by BillyGWML** [comment]
More information: https://github.com/amzn/selling-partner-api-docs/issues/394

**Comment by BillyGWML** [comment]
Ok. Ours just suddenly started working again. Yeay? Why?

**Comment by xiazhaozhao** [comment]
> Discussion is going on here with some good ideas: https://sellercentral.amazon.com/forums/t/intermitent-pii-missing-on-seller-fulfilled-orders/896438/14

very thankful!

**Comment by gopackagingproducts** [comment]
Hi,

SP-API Developer Profile Created
Case ID: 7077840972
Thank you for completing your Amazon Selling Partner API (SP-API) Developer Profile.
Your request for access to SP-API has been APPROVED

My organisation participates in Amazon Services Europe, and I want to integrate to manage my own business only.

We created api and status is Draft.

We would like to enerate shipping labels and send Amazon orders directly to customers. For this we need buyer name and complete delivery address. But buyer name and address line 1.

Please advise.

Many thanks

**Comment by xiazhaozhao** [comment]
> estricted Access Req

Thank you!
