### ISSUE TITLE
Sending SQS messages to a HTTP(S) endpoint

### ISSUE THREAD

**Issue by LunguAlexandruMihai** [amzn/selling-partner-api-docs#1279]
Hello Community, 

Is it possible to send SQS messages to a HTTP(S) endpoint ?  If so, how can it be?

Thank you very much !

**Comment by moltar** [comment]
SQS -> Lambda -> HTTP

**Comment by LunguAlexandruMihai** [comment]
@moltar Thank you! I thought there were another options.
