### ISSUE TITLE
getshipments  400 Bad Request

### ISSUE THREAD

**Issue by victor-haha** [amzn/selling-partner-api-docs#1280]
Please help me look at this problem,

**Request**
Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments?LastUpdatedAfter=2021-07-01T01%3A01%3A01Z&LastUpdatedBefore=2021-06-01T01%3A01%3A01Z&QueryType=DATE_RANGE&MarketplaceId=ATVPDKIKX0DER&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN, tag=Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments?LastUpdatedAfter=2021-07-01T01%3A01%3A01Z&LastUpdatedBefore=2021-06-01T01%3A01%3A01Z&QueryType=DATE_RANGE&MarketplaceId=ATVPDKIKX0DER&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN, tag=null}}

**Response**
Response{protocol=http/1.1, code=400, message=Bad Request, url=https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments?LastUpdatedAfter=2021-07-01T01%3A01%3A01Z&LastUpdatedBefore=2021-06-01T01%3A01%3A01Z&QueryType=DATE_RANGE&MarketplaceId=ATVPDKIKX0DER&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN}

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipments

**Comment by johnkw** [comment]
Your above post is fairly useless. An actual HTTP log with headers etc would be better.
