### ISSUE TITLE
Report `GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA` returns negative `per-unit-volume` value

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#1282]
Report description: https://sellercentral.amazon.com/gp/help/help.html?itemID=200740930&ref=efph_200740930_cont_200885390&language=en_US

> The volume in cubic feet of one unit (to the nearest 1/100 of an inch).

How can volume be negative?

Is it a black hole?

The value is `-16.39`

**Comment by johnkw** [comment]
Black holes do not have negative volume.

You should report that to Seller Central Support though.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
