### ISSUE TITLE
The options for enumerating PrepInstruction are not fully enumerated 

### ISSUE THREAD

**Issue by jason1004** [amzn/selling-partner-api-docs#1286]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#prepinstructionlist

![image](https://user-images.githubusercontent.com/13719529/130315654-18de6f8b-75df-4c66-aa33-e1808d1182e2.png)

The options for enumerating PrepInstruction are not listed completely. In fact, there are many unlisted options, and we can only find one to add one each time.

Can you provide all enumerated items?

**Comment by MST1122** [comment]
@jason1004 are you working with Listing API? If yes, then how are you validating your JSON data against a schema with custom vocabulary?

**Comment by IceShack** [comment]
Same issue. for me its the value `Boxing` that's missing so far
