### ISSUE TITLE
Invalid scope when migrating from mws to sp-api

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#1289]
![Screenshot 2021-08-22 151507](https://user-images.githubusercontent.com/37909821/130352349-2aa97b04-ae2e-4987-9fdb-4cb2d34163c3.png)

**Comment by Javadebi** [comment]
Anyone please??? What a dissapointing from amazon.

**Comment by ShivikaK** [comment]
Hello @Javadebi 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by hunaidnawaz-qbatch** [comment]
@ShivikaK
There is an error related to invalid cartonIds.
please guide me where I'm doing mistake.

As i passed value in **PackageLabelsToPrint** as
```
request_parameters = get_query_parameters({
  "PageType" => "PackageLabel_Thermal",
  "LabelType" => "UNIQUE",
  "PackageLabelsToPrint" => "FBAXXXXXXXXXU00001"
})

```
query params will be like this
"?PageType=PackageLabel_A4_4&LabelType=UNIQUE&PackageLabelsToPrint=FBAXXXXXXXXXU00001"

I'm getting this error.
```
["{",
 "  errors: [",
 "    {",
 "      code: InvalidInput,",
 "      message: Provided SellerCartonIds are not valid: [[FBAXXXXXXXXXU00001]] for Shipment: [FBAXXXXXXXXX],",
 "      details: ",
 "    }",
 "  ]",
 "}"]

```

**Comment by harili** [comment]
Hello,

Did anyone solve this issue ?
