### ISSUE TITLE
Feeds API POST_PRODUCT_DATA The "Message/Product/DescriptionData/MerchantShippingGroupName" (MY-SHIPPING-TEMPLATE-NAME) field contains an invalid value.

### ISSUE THREAD

**Issue by aniruddhaad** [amzn/selling-partner-api-docs#1290]
We are getting this error for many of our sellers -
Feed type: POST_PRODUCT_DATA 
The "Message/Product/DescriptionData/MerchantShippingGroupName" (MY-SHIPPING-TEMPLATE-NAME) field contains an invalid value.

Here is request XML -
<?xml version="1.0" encoding="utf-8" ?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema">
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>XXXXXXXXXX</MerchantIdentifier>
</Header>
<MessageType>Product</MessageType>
<PurgeAndReplace>false</PurgeAndReplace><Message>
<MessageID>1</MessageID>
<OperationType>Update</OperationType>
<Product>
<SKU>V728-417426</SKU>
<StandardProductID>
<Type>ASIN</Type>
<Value>B000B65NFU</Value>
</StandardProductID>
<ProductTaxCode>A_GEN_NOTAX</ProductTaxCode>
<Condition><ConditionType>New</ConditionType></Condition>
<DescriptionData>
<Title><![CDATA[BIJAN by Bijan Eau De Toilette Spray 1 oz (Men)]]></Title>
<Brand><![CDATA[Bijan]]></Brand>
<Description><![CDATA[Launched by the design house of Bijan in 1985, Bijan is classified as a sharp, spicy, lavender, amber fragrance. This masculine scent possesses a blend of mandarin, nutmeg, rosemary, musk, lavender, oakmoss and amber. It is recommended for daytime wear.]]></Description><BulletPoint><![CDATA[Bijan by Bijan for Men 1.0 oz Eau de Toilette Spray: Buy Bijan Colognes - Launched by the design ho]]></BulletPoint><BulletPoint><![CDATA[ Bijan is classified as a sharp]]></BulletPoint><BulletPoint><![CDATA[ spicy]]></BulletPoint><BulletPoint><![CDATA[ lavender]]></BulletPoint><BulletPoint><![CDATA[ amber fragrance. This masculine scent possesses a blend of mandarin]]></BulletPoint><MSRP currency="USD">36.00</MSRP>
<Manufacturer><![CDATA[Bijan]]></Manufacturer>
<MfrPartNumber><![CDATA[417426]]></MfrPartNumber><ItemType><![CDATA[men]]></ItemType><MerchantShippingGroupName><![CDATA[MY-SHIPPING-TEMPLATE-NAME]]></MerchantShippingGroupName>
</DescriptionData></Product>
</Message>
</AmazonEnvelope>

RequestId:f54f0eaa-401f-4b5e-91f3-f4dcd6482996
TimeStamp:20210823T094410Z 

I am able to replicate this issue everytime. Its not mentioned anywhere that  XML specifications have changed for Feeds API  (https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd) .

So where is the issue?

**Comment by MST1122** [comment]
@aniruddhaad are you not using the new Listing API?

And I have a question? how are you generating UI for input data for product listing? using some package?

**Comment by aniruddhaad** [comment]
> @aniruddhaad are you not using the new Listing API?
> 
> And I have a question? how are you generating UI for input data for product listing? using some package?

I think so. I am using new API i.e. by CreateDocument & UploadDocument etc. however the XML structure for the feed is still same I believe. Or you are referring to JSON feed?

**Comment by MST1122** [comment]
@aniruddhaad yes I'm referring to JSON feed. But my main question is how are you generating an HTML-based input form for users to input data based on the product category required for product listing.

**Comment by aniruddhaad** [comment]
> @aniruddhaad yes I'm referring to JSON feed. But my main question is how are you generating an HTML-based input form for users to input data based on the product category required for product listing.

nah... we do not collect it from users. We have it in our system already.

**Comment by aniruddhaad** [comment]
Amazon replied after 5 days and told me that the shipping template is different 👎 
Here products are not uploading so sellers are trying to do whatever they can and obviously they will not wait for 5 days until amazon support look at ticket. They might have changed it. 
On top of that, they just closed the ticket. what the hell!
I have created 2 tickets explaining same issue now and waiting for them to respond. I hope they don't take 5 more days 🙏

It would be benefit all the developers if amazon can mention more sensible errors in case amazon account has problems like not a pro seller etc.

**Comment by aidensgithub** [comment]
@aniruddhaad Did you resolve the issue? Or maybe there is any other way to assign shipping prices?

**Comment by aniruddhaad** [comment]
Well, this was resolved by simply not sending shipping template.
However with this new Seller partner API everything is working unpredictable.
Some time I got feed submission report (not found, invalid report id)
Some time i got the active item report (not found invalid report id)
some times items don't upload and throw error - Due to unusually high number of product upload we have temporary suspended listing ability (similar i don't remember exact wording now).
for some sellers active item report works, for some does not
for some seller item uploads & for some it does not work with no error whatsoever.
Sorry to say MWS was far more better than this. They must have added tons of feature but at least I don't see basic things working properly here.
In short losing lots of customers due to this SP-API and enforcing to change the APIs from MWS.

You can go through thread below to see what amazon responded to my ticket -
-------------------------------------------------
Their first reply -

I understand that you keep on receiving the Invalid Value error message when submitting a feed. After some testing, I was able to identify that the shipping template you want is indeed already created in Seller Central's shipping settings, thank you for the picture.

Now, from the picture you can see that the shipping template called in the feed is not set as "default", in this case the default template is the "US Template". Please make it the default template and try again.

-------------------------------------------------
My Reply -
We set the shipping template as default then we don't even need to send the shipping template to amazon no?
The whole point here was to send the shipping template so that seller can have items from multiple sources with different shipping templates & the solution you provided defeats the purpose. 
-------------------------------------------------

Their second reply-
This is Leon again, with the Amazon Developer Support team.

Regarding the invalid value error because of the "MerchantShippingGroupName" element not matching the default shipping template, I regret to inform that indeed that is the way it is supposed to work. I have informed our product management team of your feedback.

They will evaluate the feedback and details provided for future implementation. Thank you for taking the time to let us know about this limitation and its impact on your business. Your feedback helps us make continuous improvements that benefit all our customers.

-----------------------------------------

From the above conversation, it's crystal clear that no one knows what's needs to go in & out.

With such poor documentation and that too with no examples of any sort, it will take months to develop something which will look like working perhaps who knows. 

God bless poor developers!

**Comment by aniruddhaad** [comment]
Since you asked about limitation, this will impact if seller want to have items from different apps which needs to configure different shipping for their items. In this case it's not possible because in the amazon seller central only one shipping template can be set as default. 
That means seller can use only one app of it's type or all app that upload items to seller's amazon account must use same shipping cost.
