### ISSUE TITLE
Call SP API Using Public Application

### ISSUE THREAD

**Issue by gaurav-webs** [amzn/selling-partner-api-docs#1291]
Hello all,

Currently, I am using the private application, and everything is working fine, for the private application I am using self-authorization for `refresh_token`.

but now I want to set up the public application and I have one confusion that currently in the private application I am using the following credential to call SP API:- 

- Login with Amazon Client Id (client_id)
- Login with Amazon Client Secret (client_secret)
- AWS User Access Key ID (access_key_id)
- AWS User Secret Access Key (secret_access_key)
- AWS Role ARN (role_arn)
- Refresh Token (refresh_token) [For Private application I am using self authorization refresh_token]

so when we use the public applications what credentials do I want to get from the seller who uses my website?
as for the private application, I am using the above list that I have, so for the public application, I have to get all the above list from the seller?

**Comment by ShivikaK** [comment]
Hello @gaurav-webs 

Thank you for raising this issue.

For public application, you require all the above details mentioned which are the same as they are based on your SP API application. 

The difference is the refresh token which you get that is generated after Seller goes through the OAuth workflow process to authorize your public application. This token is a different value than your self-auth token. Each refresh token will be unique for that seller authorization.

Please review the OAuth workflow documented in our developer guide to understand next steps involved -
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#authorizing-selling-partner-api-applications

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#amazon-partner-network-authorization-workflow

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by gaurav-webs** [comment]
@ShivikaK  
Thank you for your reply,

my question is what I want to get from my customer who uses my website, the above all credentials of my developer account,

so now from customers who use my website are also required all the above credentials to use my website?

or do they just use website authorization flow and the refresh token which is generated that we have to only use no other detail we need to get from the user?

**Comment by ShivikaK** [comment]
Hello @gaurav-webs 

The LWA and AWS credentials associated with your application client are not different for each seller as they are based on your application client. It is the refresh token that is unique to each successful seller authorization. 

The seller who authorizes your account will be providing you with a short-lived authorization code which is required to be exchanged for a long-lived refresh token. So basically, the seller needs to go through the oauth workflow either through Appstore or your own website and then share the auth code generated at the end of a successful authorization.

Hope this helps clear the confusion and addresses your questions.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by gaurav-webs** [comment]
@ShivikaK 

Thank you for the reply,

Yes, clear now. 

I am just confused that which information I need to get from the customer who uses my website.

but now it is clear now, that I don't want to get any information I just have to set up website authorization flow to get the refresh token of customers.

Thank you,
