### ISSUE TITLE
[BUG] Failed to obtain vendor authorization code

### ISSUE THREAD

**Issue by ykl1993** [amzn/selling-partner-api-docs#1294]
Step 1:
 request url:  https://vendorcentral.amazon.fr/apps/authorize/consent?.........
 
 Step 2:
  What should I do to solve an error??
  
![image](https://user-images.githubusercontent.com/33823029/130540371-f1d607fd-29b1-48df-a3a6-03b36b69c0c4.png)

**Comment by ShivikaK** [comment]
Hello @ykl1993 

Thank you for raising this issue.

Please provide more details on the exact OAuth URL being used and is the application a 3rd party application developed for vendor API access or a private vendor application?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ykl1993** [comment]
hello @Shivika Khare


Thank you for your letter.


The site used by the customer is the French station.
When the customer opens and logs in according to my URL, an error will be prompted.
This is My OAuth URL:&nbsp;
https://vendorcentral.amazon.fr/ap/signin?clientContext=259-1023216-2493814&amp;openid.return_to=https%3A%2F%2Fvendorcentral.amazon.fr%2Fapps%2Fauthorize%2Fconsent%3Fapplication_id%3Damzn1.sellerapps.app.461079ce-abb0-493e-b3a1-e978e55edf0b%26state%3Da3cfd19b-dc3e-492c-9001-c43c165f962b%26redirect_uri%3Dhttps%253A%252F%252Ferp.allroot.net%252Fauth%252FauthCode.htm%253Fplatform%253DAmazonCloudERP&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=amzn_vc_fr_v2&amp;openid.mode=checkid_setup&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;pageId=amzn_vc_fr_auth&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;mons_redirect=sign_in

Thanks,
yingkailing


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 上午8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] Failed to obtain vendor authorization code (#1294)





 
Hello @ykl1993
 
Thank you for raising this issue.
 
Please provide more details on the exact OAuth URL being used and is the application a 3rd party application developed for vendor API access or a private vendor application?
 
Thanks,
 Shivika Khare
 Selling Partner API Developer Support
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShivikaK** [comment]
Hello @ykl1993 

As per your response, your application is a public application. Is that correct?

The OAuth URL for a public application to be authorized by a vendor account will be something as below -

https://vendorcentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.461079ce-abb0-493e-b3a1-e978e55edf0b&state=stateexample&redirect_uri=redirect_uri_example

If the above application is in draft state, please keep in mind to add version=beta parameter to the URL

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ykl1993** [comment]
Hi @Shivika Khare


Thank you for your very detailed answer.&nbsp;
According to your guidance, we have successfully solved the problem.

Thanks
yingkailing


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 凌晨3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] Failed to obtain vendor authorization code (#1294)





 
Hello @ykl1993
 
As per your response, your application is a public application. Is that correct?
 
The OAuth URL for a public application to be authorized by a vendor account will be something as below -
 
https://vendorcentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.461079ce-abb0-493e-b3a1-e978e55edf0b&amp;state=stateexample&amp;redirect_uri=redirect_uri_example
 
If the above application is in draft state, please keep in mind to add version=beta parameter to the URL
 
Please feel free to open a support case with us if you'd like deeper assistance with this issue.
 
Thanks,
 Shivika Khare
 Selling Partner API Developer Support
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ykl1993** [comment]
Hi @Shivika Khare


sorry,&nbsp;I'll trouble you again.&nbsp;
When the customer is using it, the first step is successful, but a white screen appears when he clicks next.
The following is a screenshot of the authorized address and page operation. We use the draft version.

https://vendorcentral.amazon.fr/apps/authorize/consent?application_id=amzn1.sellerapps.app.461079ce-abb0-493e-b3a1-e978e55edf0b&amp;state=66cb0339-3870-43e2-a47f-badf5b285a85&amp;version=beta&amp;redirect_uri=https%3A%2F%2Ferp.allroot.net%2Fauth%2FauthCode.htm%3Fplatform%3DAmazonCloudERP

First:


Second:




Thanks
yingkailing


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 凌晨3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] Failed to obtain vendor authorization code (#1294)





 
Hello @ykl1993
 
As per your response, your application is a public application. Is that correct?
 
The OAuth URL for a public application to be authorized by a vendor account will be something as below -
 
https://vendorcentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.461079ce-abb0-493e-b3a1-e978e55edf0b&amp;state=stateexample&amp;redirect_uri=redirect_uri_example
 
If the above application is in draft state, please keep in mind to add version=beta parameter to the URL
 
Please feel free to open a support case with us if you'd like deeper assistance with this issue.
 
Thanks,
 Shivika Khare
 Selling Partner API Developer Support
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShivikaK** [comment]
Hello @ykl1993 

I am unable to view these screenshots but it appears your app setup is proper and the OAuth is working as expected. Below is the OAuth URL for your app that I tested -

https://vendorcentral.amazon.co.uk/apps/authorize/consent?application_id=amzn1.sellerapps.app.461079ce-abb0-493e-b3a1-e978e55edf0b&state=66cb0339-3870-43e2-a47f-badf5b285a85&version=beta&redirect_uri=https://erp.allroot.net/auth/authCode.htm?platform=AmazonCloudERP

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support
