### ISSUE TITLE
Is access to the sandbox endpoints possible pre rollout?

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-docs#13]
I know it's already been stated that we're not able to complete our Application registration with SP-API until rollout and therefore not able to get a hold of access tokens to make requests to the production endpoint. Is it possible in any way at all to start hitting the sandbox endpoints to better prepare? Thanks!

**Comment by jlevers** [comment]
I would also be very interested in access to the sandbox/test endpoint :)

**Comment by evdeg** [comment]
@charliecode @jlevers Thank you both for your interest! As you know, the SP-API is in documentation preview at this time. The sandbox endpoints currently require a valid SP-API application. When you make a call to the sandbox endpoint the call is validated the same way as calls to production endpoints so it requires valid LWA and AWS credentials to be able to sign the requests. We do not have a sandbox endpoint that can be accessed without a valid SP-API application at this time.

**Comment by charliecode** [comment]
Thanks @evdeg can't blame a guy for trying! 😄

**Comment by evdeg** [comment]
The SP-API is live now and you can start calling the sandbox endpoints as soon as you have registered your application and have your LWA and AWS credentials. I am closing this issue since no action is required here.
