### ISSUE TITLE
Feed's status becomes CANCELED after submitted

### ISSUE THREAD

**Issue by tenitre** [amzn/selling-partner-api-docs#130]
Hi 

When I submit following feed through new SP API feed endpoints, its status immediately becomes CANCELED.

Any idea why?

Note: I am able to get my feed Id after successfully POST my feed document.

thanks

`<?xml version="1.0" encoding="utf-8" ?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amznenvelope.xsd">
	<Header>
	  <DocumentVersion>1.01</DocumentVersion>
	  <MerchantIdentifier>A**********X</MerchantIdentifier>
	</Header>
	<MessageType>Inventory</MessageType>
	<Message>
	  <MessageID>1</MessageID>
	  <OperationType>Update</OperationType>
	  <Inventory>
		<SKU>b07b**************bba6</SKU>
		<Quantity>1</Quantity>
		<FulfillmentLatency>1</FulfillmentLatency>
	  </Inventory>
	</Message>
</AmazonEnvelope>`

**Comment by parvathm** [comment]
Hi @tenitre , 

We need feed id to help you further. Please open a support case ( https://developer.amazonservices.com/support) with feed id details so we can pursue the investigation. 

Thanks,
Parvathi
Selling Partner API Developer Support

**Comment by tenitre** [comment]
Hi @parvathm 

Thank you for getting back to me, I created the support ticket,... Here  is my ticket id 7650089091

thanks in advance

**Comment by parvathm** [comment]
Hi @tenitre 

Thank you . We will provide further update on the case.

Thanks,
Parvathm
Selling Partner API Support.

**Comment by tenitre** [comment]
Thank you @parvathm
