### ISSUE TITLE
PII Request Rejected - Now What?

### ISSUE THREAD

**Issue by chadwixk** [amzn/selling-partner-api-docs#1300]
Amazon has been rejecting our request for PII as our solution is unique enough or some canned response, which is not true. That said, after 9 months of trying to get approved, we need to evaluate alternate plans.

Our solution does optimized order fulfillment for our clients, so we need PII access to support direct to consumer (not FBA) shipping from our system. Alternatives I've been thinking about:

1. Can each of our clients use their own credentials (and apply for PII access) ? I thought that's how some of the MWS apps have worked that I've used in the past...each user of the software had to apply for their own MWS credentials.
2. Is there a third party API that integrates with Amazon that we could integrate with?
3. Does the Amazon API, without PII access, allow us call it to create shipments and receive back a url to a shipping label (pdf, jpg, or ideally zpl)?
4. Any other suggestions/ideas?

**Comment by chadwixk** [comment]
Anyone?

**Comment by optikalefx** [comment]
You won't be able to continue without the PII acceptance. Even if you get your clients to sign up for their own selling partner accounts, you'll be filling out the exact same form. That form is intense, and you need to be a large enough company to have a security department with access controls, a legal department with policies, an HR department for handling employees, and IT department for handling authorization and grants, and developers that follow proper security protocols.

They also don't support ZPL at this time, you'll have to convert the PNG to ZPL yourself. My suggestion is to do everything that the PII form asks, then, allow your lawyers to write the responses to their questions. This isn't meant for a small company to be able to complete.

**Comment by margaret0303** [comment]
Hi. 
We also have been rejected but I would like to ask that even though some day we get PII access then still later on all our Customers will have to apply for that access each by each also? Or we will be able to share our credential?
Seeing @optikalefx comment it seems to be impossible to proceed.
