### ISSUE TITLE
How can I get parent ASIN from a ASIN ? 

### ISSUE THREAD

**Issue by shuaiys** [amzn/selling-partner-api-docs#131]
How can I get parent ASIN from a ASIN ?  And how can I get this Attributes from ASIN? 
![image](https://user-images.githubusercontent.com/35830373/99929977-56354300-2d8a-11eb-8c13-2d56e3a1f65c.png)

**Comment by shuaiys** [comment]
I cannot get the field "Relationships" from the interface getCatalogItem

**Comment by tabertantrum** [comment]
I'm running into the same issue of missing data from SP API on Relationships.

A call to GetMatchingProductForID in MWS returns all of the same values as the SP API counterpart (/catalog/v0/items/{ASIN} **except** for the Relationships

**Comment by parvathm** [comment]
> 
> 
> I'm running into the same issue of missing data from SP API on Relationships.
> 
> A call to GetMatchingProductForID in MWS returns all of the same values as the SP API counterpart /catalog/v0/items/{ASIN} **except** for the Relationships

Hi,

Sorry for the delay. This is similar to issue [#257 ] and is being addressed there. please monitor that link. 

Thanks,
Parvathm,
Selling Partner API Developer Support.
