### ISSUE TITLE
Can not get filtered out  orders as per multiple  OrderStatuses via Url

### ISSUE THREAD

**Issue by maltunok** [amzn/selling-partner-api-docs#1314]
Hello,
I've followed all the steps in docs and now successfully get the orders and all other relevant data.
The problem is I can not filter out orders as per multiple  OrderStatuses.

Postman successfully filters out when I enter params;  OrdersStatuses:Shipped,Canceled

But in code it does not work;;
 new Uri($"{OrderUrl}&CreatedAfter={DateTime.Now.AddDays(-15):yyyy-MM-ddTHH:mm:ssZ}&MarketplaceIds={xxxxxxxxx}");
"OrderUrl": "https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?OrderStatuses=Shipped,Canceled";

It is OK with one status;
"OrderUrl": "https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?OrderStatuses=Shipped
or
"OrderUrl": "https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?OrderStatuses=Canceled

I tried out array passing, encoding and many other options  but no help.

**Comment by iLoveSarabear** [comment]
Hi, I'm having a similar problem. Almost like it's ignoring the order status entirely when combined with a CreatedAfter date.

This also appears to have happened randomly.

**Comment by maltunok** [comment]
closed

**Comment by rajinish01** [comment]
@maltunok may I know how did you resolve this issue? I'm using python's library to get order details but it's just considering only first item in the list of `OrderStatuses`

### sample code 

```python3
from sp_api.api import Orders 
order_client = Orders(credentials=<credentials>, marketplace=Marketplaces.IN)
orders = order_client.get_orders(                                       
              CreatedAfter=(datetime.utcnow() - timedelta(days=self.days)).isoformat(),
               OrderStatuses=["Canceled", "Unshipped"],                
          )      
```
here in the above example it's giving out only `Canceled` orders but ignoring `Unshipped` orders can you please help me with this one

**Comment by maltunok** [comment]
Unfortunately I could not resolve, just sent one request for Canceled and one request for Unshipped, get the orders as per statuses and resolved the issue internally in the code
