### ISSUE TITLE
[Vendor Central] Updating developer profile with additional roles

### ISSUE THREAD

**Issue by asongate** [amzn/selling-partner-api-docs#1315]
After I update my developer profile to add additional roles, will I be able to access other API's (eg. catalogItems, Brand Analytics) with my existing app or do I need to create a new app?. Also will my existing app continue to work?

Thanks!

**Comment by ShivikaK** [comment]
Hello @asongate 

Thank you for raising this issue.

Once you update your developer profile for additional roles, you will need to edit your existing application and select those roles so they can be added to your application. 

Once the app is modified and saved, re-authorize the app which means generate a new refresh token and you will be able to make successful request to the new APIs.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by asongate** [comment]
Awesome!
Thank you @ShivikaK !

**Comment by frtlkmn** [comment]
> Hello @asongate
> 
> Thank you for raising this issue.
> 
> Once you update your developer profile for additional roles, you will need to edit your existing application and select those roles so they can be added to your application.
> 
> Once the app is modified and saved, re-authorize the app which means generate a new refresh token and you will be able to make successful request to the new APIs.
> 
> Thanks, Shivika Khare Selling Partner API Developer Support

Hello ShivikaK,
our developer profile and application approved but pending publishing.
we re-authorize the app but we cannot get rdt token right now. 
Do we need to wait for app publishing process?

**Comment by frtlkmn** [comment]
Tax Remittance(Restricted) is not approved again.
Do we need this authorization for getting mfn order buyerInfo field? 
we need to get address and other information for invoicing.

**Comment by franclin** [comment]
> Tax Remittance(Restricted) is not approved again. Do we need this authorization for getting mfn order buyerInfo field? we need to get address and other information for invoicing.

Hello @frtlkmn 
Did you get the RDT approve in the end? We're facing the same problem here
