### ISSUE TITLE
the java  can't import SellersApi class 

### ISSUE THREAD

**Issue by dingzheyan** [amzn/selling-partner-api-docs#132]
i had add  sellingpartnerapi-aa-java-1.0.jar   sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar to my  repository,
it can import LWAAuthorizationCredentials  class ,but can‘t import SellersApi 
![image](https://user-images.githubusercontent.com/28720657/99960544-e2199000-2dc7-11eb-84ca-636e90f6162c.png)

**Comment by shuaiys** [comment]
First of all, you only need to introduce the "sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar" dependency. Your problem may be that you didn’t use the swagger generator to generate SP-API.Confirm this step.

**Comment by gasper-vrhovsek** [comment]
I had the same issues using the swagger generator. The generated libraries do not include dependencies for the sellingpartnerapi and for javax.annotation.annotation-api. I added them manually before running mvn package and uploading to local mvn repo.

**Comment by WilliamChen-luckbob** [comment]
I had the same issues too. Even in sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar, there is no SellersApi .
But I found SellersApi  in swagger-java-client, then I tried to install both swagger-java-client and sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar into maven and put theminto my project. It seems working.

**Comment by ayoubAnbara** [comment]
> I had the same issues too. Even in sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar, there is no SellersApi . But I found SellersApi in swagger-java-client, then I tried to install both swagger-java-client and sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar into maven and put theminto my project. It seems working.

When are you found swagger-java-client?
