### ISSUE TITLE
Getting Error in CreateInboundShipmentPlan Api

### ISSUE THREAD

**Issue by arunobjectcode** [amzn/selling-partner-api-docs#1330]
I have used body part for creating shipment plan.

$body = array(
            'ShipFromAddress' => array(
                'Name' => 'Gorilla Store',
                'AddressLine1' => '9637 Pierrront ST',
                'AddressLine2' => 'BURKE',
                'DistrictOrCounty'=> 'US',
                'City' => 'Richmond',
                'StateOrProvinceCode' => 'VA',
                'CountryCode' => 'US',
                'PostalCode' => '20015'
            ),
            'LabelPrepPreference' => 'SELLER_LABEL',
            'ShipToCountryCode' => 'US',
            'ShipToCountrySubdivisionCode' => '',
            'InboundShipmentPlanRequestItems' => array(
                array(
                    'SellerSKU' => '',
                    'ASIN' => '',
                    'Condition' => 'NewItem',
                    'Quantity' => '5',
                    'QuantityInCase' => '',
                    'PrepDetailsList' => array(
                        'PrepInstruction' => 'BubbleWrapping ',
                        'PrepOwner' => 'SELLER'
                    )
                )
            )
        );

I am getting following error even I have tried to change country and address.

[400] Client error: `POST https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/plans` resulted in a `400 Bad Request` response: { "errors": [ { "code": "InvalidInput", "message": " Reason: Country field is missing, Name field is m (truncated...)

**Comment by wbmgaye** [comment]
take this param out `'ShipToCountrySubdivisionCode' => ''`

Look at the request params section of this https://docs.developer.amazonservices.com/en_UK/fba_inbound/FBAInbound_CreateInboundShipmentPlan.html

```
No. Specifying both ShipToCountryCode and ShipToCountrySubdivisionCode returns an error.
```
