### ISSUE TITLE
[BUG] ReportType _GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT_ missing from reporttype-values.md

### ISSUE THREAD

**Issue by Dragonsangel** [amzn/selling-partner-api-docs#1333]
**Describe the bug**
The MWS ReportType `_GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT_` is not defined anywhere in the SP-API Documentation.
From the ReportType changes from MWS to SP-API, the new ReportType should be `GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT`
This ReportType is not listen in the ReportType values documentation.

The only mention of the ReportType is in the announcement [Important Notice: Third-party developers using Amazon MWS Orders, Reports, and Merchant Fulfillment API sections must migrate to Selling Partner API by July 31, 2022](https://github.com/amzn/selling-partner-api-docs/discussions/1037)

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md

**Comment by jenilew** [comment]
Hi Dragonsangel, 

Thank you for the feedback. We are aware of this gap and are working to get the documentation updated for this report. 

Stay tuned for updates on the Announcements channel. We'll post an announcements when the update goes live. 

Best, 

Jen 
Selling Partner API Services Team

**Comment by johnkw** [comment]
See also bug #421 - none of the reports contents are documented.

**Comment by Dragonsangel** [comment]
This is still relevant and should not be closed. (Commenting to give not activity)

**Comment by skrzyh** [comment]
In my case when i asked for GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT i get always (only one call):

 "errors": [
    {
      "code": "QuotaExceeded",
      "message": "You exceeded your quota for the requested resource.",
      "details": ""
    }
  ]
}

**Comment by johnkw** [comment]
Turn this stupid bot off and resolve the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon @jenilew @parvathm

**Comment by GJ-JG** [comment]
Hi @Dragonsangel , the Github content has been migrated to our new doc page, you can refer [this new document page](https://developer-docs.amazon.com/sp-api/docs/report-type-values) and search for ```GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT```, you can find the report type there.
