### ISSUE TITLE
[BUG] Reports API. Access to requested resource is denied. Unauthorized

### ISSUE THREAD

**Issue by luckylion999** [amzn/selling-partner-api-docs#1335]
I am using aws_requests_auth library for AWS Signature Version 4 Signing Process.
And I called SP api for creating report.
But getting below error.
`{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`

Here is my code.
```
from aws_requests_auth.aws_auth import AWSRequestsAuth

auth = AWSRequestsAuth(
    aws_access_key=<aws_access_key>,
    aws_secret_access_key=<aws_secret_key>
    aws_host='sellingpartnerapi-na.amazon.com',
    aws_region='us-east-1',
    aws_service='execute-api'
)

endpoint = f'https://sellingpartnerapi-na.amazon.com/reports/{current_date}/reports'
body = {
    'reportType': 'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL',
    'dataStartTime': serializer.validated_data['data_start_time'],
    'marketplaceIds': serializer.validated_data['marketplace_ids']
}
headers = {'x-amz-access-token': serializer.validated_data['access_token']}

response = requests.post(endpoint, auth=auth, headers=headers, data=body)
```

Hope to get help asap.

**Comment by ShivikaK** [comment]
Hello @luckylion000 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation. In the support case, please provide request details including request ID and timestamp to troubleshoot the issue further.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
