### ISSUE TITLE
Inconsistent behavior in the 2020-12-01 version of the getCatalogItem endpoint

### ISSUE THREAD

**Issue by HaiderAgha94** [amzn/selling-partner-api-docs#1337]
I work for a selling partner that sells products on Amazon on the behalf of brands. We're registered with all of the brands, yet when using the [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#getcatalogitem) endpoint if I pass in `attributes` for the `includedData` param it gives me back the following error for most ASINs

"The includedData requested requires Brand Registry affiliation with the requested item. Remove the requested includedData item or register the brand of the item in Brand Registry with the seller."

The strangest thing is that for two particular brands I'm able to get the attributes for most of their products, but for the remaining products of the same brands I get the above error. Is there any explanation for this?

In the above cases the `brandName` property under `summaries` is the same for products that I'm able to get attributes for and products that I'm unable to get attributes for.

Out of the remaining brands, for 12 of them I'm unable to get attributes for any of their products.

For the two remaining brands I'm able to get attributes for all of their products.

What should we be looking to change in order to get attributes for all of our products?

**Comment by steven-so** [comment]
I am also running into this issue. Were you able to discover anything @HaiderAgha94 ?

**Comment by steven-so** [comment]
Is there a way to set the sellerId for the getCatalogItem request? I think the issue is because we are identified as the owner of multiple brands, and it's not assuming the correct sellerId.

I had a similar issue using the listingItems endpoint until I set the correct sellerId.

**Comment by HaiderAgha94** [comment]
@steven-so we put this in the backlog while we're waiting for an answer from Amazon. I have to say I'm glad I'm not the only one experiencing this issue.

I know that the listing item endpoints take the seller id as a path parameter, but I don't think there's a way to pass in the seller id for the get catalog item endpoint.
