### ISSUE TITLE
Missing AnyOfferChange Notification Details

### ISSUE THREAD

**Issue by tabertantrum** [amzn/selling-partner-api-docs#134]
We have been migrating our existing MWS application to SP API and found an issue of missing information in the SP API response on the AnyOfferChange notification, particularly the "isBuyBoxWinner" value.

The [documentation](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/notifications-use-case-guide-v1.md#offer) indicates this field (and others) are now marked as optional but doesn't clarify when they will be provided. Has anyone else come across this issue? We're getting the values back from MWS, so it seems like an SP API issue.

**Comment by tabertantrum** [comment]
This continues to be an issue for us with SP API. Below are two responses from MWS and SP API from the same notification out of Amazon from an AnyOfferChange type. The originally linked documentation in my issue does not clarify when optional fields will be provided, so we are unclear whether this is intended functionality from SP API (meaning a deprecation of this field from MWS) or an issue in the SP API not returning complete data in the response. This is somewhat related to #190 but given the response elements on that endpoint we believe this is an issue with SP API itself and not documentation needing further clarification. What do you think @seanevan?

### SP API Offers Element
``` json
{
  "Offers": [
    {
      "SellerId": "A1XXXXXXXXXXX",
      "SubCondition": "new",
      "SellerFeedbackRating": {
        "FeedbackCount": 6642,
        "SellerPositiveFeedbackRating": 100
      },
      "ShippingTime": {
        "MinimumHours": 0,
        "MaximumHours": 0,
        "AvailabilityType": "NOW",
        "AvailableDate": ""
      },
      "ListingPrice": {
        "Amount": 9.99,
        "CurrencyCode": "USD"
      },
      "Shipping": {
        "Amount": 0,
        "CurrencyCode": "USD"
      },
      "IsFulfilledByAmazon": true,
      "PrimeInformation": {
        "IsOfferPrime": true,
        "IsOfferNationalPrime": true
      },
      "IsFeaturedMerchant": true,
      "ShipsDomestically": true
    }
  ]
}
```

### MWS Offer Element
``` xml
<Offer>
    <SellerId>A1XXXXXXXXXXX</SellerId>
    <SubCondition>new</SubCondition>
    <SellerFeedbackRating>
        <SellerPositiveFeedbackRating>100</SellerPositiveFeedbackRating>
        <FeedbackCount>6642</FeedbackCount>
    </SellerFeedbackRating>
    <ShippingTime minimumHours="0" maximumHours="0" availabilityType="NOW" />
    <ListingPrice>
        <Amount>9.99</Amount>
        <CurrencyCode>USD</CurrencyCode>
    </ListingPrice>
    <Shipping>
        <Amount>0.00</Amount>
        <CurrencyCode>USD</CurrencyCode>
    </Shipping>
    <IsFulfilledByAmazon>true</IsFulfilledByAmazon>
    <IsBuyBoxWinner>true</IsBuyBoxWinner>
    <PrimeInformation>
        <IsPrime>true</IsPrime>
        <IsNationalPrime>true</IsNationalPrime>
    </PrimeInformation>
    <IsFeaturedMerchant>true</IsFeaturedMerchant>
    <ShipsDomestically>true</ShipsDomestically>
</Offer>
```

**Comment by cgaugel** [comment]
This is the most important information and Amazon has to add this.

**Comment by ShivikaK** [comment]
Hello @tabertantrum 

Thank you for raising this issue. 

We are currently investigating the issue reported here as well as in #427 with the engineering team and I will get back to you with an update accordingly.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by cgaugel** [comment]
Still no update

**Comment by ShivikaK** [comment]
Hello everyone,

The issue with IsBuyBoxWinner element in SP API has been identified and the engineering team is working on the fix.

I will let you know once I have an estimate on the timeline.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello everyone,

The issue with IsBuyBoxWinner element missing in SP API offers element has been resolved. 

Please let me know if you still observe any different behavior/result in SP API for the AnyOfferChanged notification. 

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by tabertantrum** [comment]
We have confirmed consistent, complete responses since yesterday. Closing issue.
