### ISSUE TITLE
[BUG] createReport return InvalidInput

### ISSUE THREAD

**Issue by poeily** [amzn/selling-partner-api-docs#1342]
I call createreport, but it always returns

{
"errors": [
{
"code": "InvalidInput",
"message": "Invalid Input",
"details": ""
}
]
}
x-amzn-RequestId: 967eb5fe-1ebe-4673-8649-58725ff91497
Who can help me

**Comment by poeily** [comment]
After I add x-amz-algorithm, x-amz-credential and x-amz-date, I still prompt the same error. What's wrong? Can you give an accurate answer!

x-amzn-RequestId: 2f3c7fee-ded7-4764-947b-bb3a3e2eb169

**Comment by ItHamza** [comment]
did you solve this?
