### ISSUE TITLE
Correct way to upload Box Content Information

### ISSUE THREAD

**Issue by SimonSauter** [amzn/selling-partner-api-docs#1348]
Hi Team,

The PutTransport endpoint gives you the possibility to specify a packageList object with box content info.  Is this the right way to update the corresponding step in the shipment workflow namely Shipment Packing?  I see the option to use FEED aswell.

Can someone advise which the right way to do it to avoid manual processing fee?

**Comment by 15184351573** [comment]
I think you can refer: http://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_ShipInventoryToAFN.html
