### ISSUE TITLE
Cannot get reports/2021-06-30/reports endpoint to work

### ISSUE THREAD

**Issue by defenderjim** [amzn/selling-partner-api-docs#1349]
I am able to succesfully call other endpoints.

I have tried other report types to no avail.

Ideas?

`POST to https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports`
Body:
 ```
   { "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA"
      , "dataStartTime": "2021-08-10T20:11:24.000Z"
      , "dataEndTime" : "2021-09-01T11:30:10.802Z"
      , "marketplaceIds": [ "ATVPDKIKX0DER" ]
    }
```

I always get the error response:
_"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."_

**Comment by ShivikaK** [comment]
Hello @defenderjim 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation. In the support case, please provide request details including request ID and timestamp to troubleshoot the issue further.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by defenderjim** [comment]
Ok, how do I do that?

**Comment by ShivikaK** [comment]
Hello,

You can open a support case using this [link](https://sellercentral.amazon.com/gp/mws/contactus.html?)

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by defenderjim** [comment]
Yes, I did that Aug 13, still waiting for an answer.

**Comment by ShivikaK** [comment]
Hello @defenderjim 

Please share the case ID so we can look into it and expedite a response.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by defenderjim** [comment]
8720870911

**Comment by fractalakash** [comment]
Hi , I am also facing similar issue . Did i get some help?

**Comment by DawidWawrzyniak** [comment]
Did you try sending requests without nanoseconds?
I have a similar problem with one of the endpoints.
 "dataEndTime" : "2021-09-01T11:30:10.**802**Z"

**Comment by fractalakash** [comment]
> Did you try sending requests without nanoseconds?
> I have a similar problem with one of the endpoints.
> "dataEndTime" : "2021-09-01T11:30:10.**802**Z"

Hey @DawidWawrzyniak, i am passing 'https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports?marketplaceIds=A1PA6795UKMFR9&reportType=RFQD_BULK_DOWNLOAD&dataStartTime=2021-07-01T00:00:00Z' as endpoint 
and receiving *The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details* as error.

I have tried the endpoint both wit nano seconds and without nano second.

**Comment by defenderjim** [comment]
POSTing the request with nano seconds should be ok as that is how it is in their docs.
Their documentation: [https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/reports-api-use-case-guide/reports-api-use-case-guide_2021-06-30.md]

Their example body:
POST https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports
{
  "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
  "dataStartTime": "2019-12-10T20:11:24.000Z",
  "marketplaceIds": [
    "A1PA6795UKMFR9",
    "ATVPDKIKX0DER"
  ]
}

Tried sending the request times multiple formats.  No Progress.  Opened a case w/Amazon which has been less than productive.

Tried with this body, to no avail:
 { "reportType":"GET_MERCHANT_LISTINGS_ALL_DATA"
 , "dataStartTime":"2021-09-21T10:26:01"
 , "dataEndTime" :"2021-09-22T10:26:01"
 , "marketplaceIds": ["ATVPDKIKX0DER"] }

**Comment by fractalakash** [comment]
> @DawidWawrzyniak
> @fractalakash
> 
> POSTing the request with nano seconds should be ok as that is how it is in their docs.
> Their documentation: [https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/reports-api-use-case-guide/reports-api-use-case-guide_2021-06-30.md]
> 
> Their example body:
> POST https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports
> {
> "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
> "dataStartTime": "2019-12-10T20:11:24.000Z",
> "marketplaceIds": [
> "A1PA6795UKMFR9",
> "ATVPDKIKX0DER"
> ]
> }
> 
> Tried sending the request times multiple formats. No Progress. Opened a case w/Amazon which has been less than productive.
> 
> Tried with this body, to no avail:
> { "reportType":"GET_MERCHANT_LISTINGS_ALL_DATA"
> , "dataStartTime":"2021-09-21T10:26:01"
> , "dataEndTime" :"2021-09-22T10:26:01"
> , "marketplaceIds": ["ATVPDKIKX0DER"] }

Did you get any luck in successfully getting the data using requests python? Were you able to download any report using below request
POST https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports

**Comment by defenderjim** [comment]
@fractalakash

> Did you get any luck in successfully getting the data using requests python? Were you able to download any report using below request

No.

**Comment by canercetin-randomguy** [comment]
This issue still persists.
`{"reportType":"GET_MERCHANTS_LISTINGS_FYP_REPORT","marketplaceIds":"ATVPDKIKX0DER"}`

When I send this body data to /reports/2021-06-30/reports, I get

`{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "marketplaceIds;"
    }
  ]
}
`

but according to documentation only required thing is body data.
![image](https://user-images.githubusercontent.com/92731060/201469826-52c24ee1-fb66-4144-ab72-66b2a4e14df0.png)

what the hell?

**Comment by frewper** [comment]
Reports API issue still exists, seems to be something wrong with the date. Trying the example in docs as mentioned in this thread

`"code": "InvalidInput",
            "message": "One or more parameters does not conform to the schema constraints.",
            "details": "dataEndTime;dataStartTime;"`

**Comment by Kpasha** [comment]
resolve the error in the code:

import requests
import json
from sellingpartnerapi import Configuration, ReportsV20210630Api, ApiException
from sellingpartnerapi.models.reports_v20210630.create_report_specification import CreateReportSpecification

# Selling Partner API Configuration
config = Configuration(
    lwa_client_id="<LWA client ID>",
    lwa_client_secret="<LWA client secret>",
    lwa_refresh_token="<LWA refresh token>",
    aws_access_key_id="<AWS access key ID>",
    aws_secret_access_key="<AWS secret access key>",
    endpoint="https://sellingpartnerapi-na.amazon.com"  # or another endpoint
)

# API instance for Reports
api_instance = ReportsV20210630Api(config)

# Report ID for fetching report
report_id = 'report_id_example'

# Report specification for creating report
create_report_payload = {
  "reportSpecification": {
    "reportType": "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
    "reportOptions": {
      "reportPeriod": "WEEK"
    },
    "dataStartTime": "2023-07-21T10:26:01",
    "dataEndTime": "2023-09-21T10:26:01",
    "marketplaceIds": [
      "A2VIGQ35RCS4UG"
    ]
  }
}

# Headers for API requests
headers = {
  'Content-Type': 'application/json'
}

# Fetching a report
def fetch_report():
    try:
        result = api_instance.get_report(report_id)
        print(result)
    except ApiException as e:
        print("Exception when calling ReportsV20210630Api->get_report:", e)

# Creating a report
def create_report():
    url = "https://sellingpartnerapi-eu.amazon.com/reports/2023-06-30/reports"
    try:
        response = requests.post(url, headers=headers, data=json.dumps(create_report_payload))
        print(response.text)
    except Exception as e:
        print("Exception when creating report:", e)

# Main function
def main():
    fetch_report()
    create_report()

if __name__ == "__main__":
    main()
