### ISSUE TITLE
Include Model Number in PurchaseOrder responses

### ISSUE THREAD

**Issue by Gareth-Lee-PBH** [amzn/selling-partner-api-docs#135]
endpoint: /vendor/orders/v1/purchaseOrders

The OrderItem model has the properties AmazonProductIdentifier and VendorProductIdentifier
Is it possible to also include field that contains Model Number, which is normally available when you download the PO from the vendor central?

![image](https://user-images.githubusercontent.com/59441304/100018857-0334ad80-2dd5-11eb-8e9d-321ab76cb24e.png)

**Comment by pprbhm** [comment]
Hello,
Thank you for contacting developer support team. This looks like an enhancement request apart from what we offer in vendor central. We can take this with engineering team to discuss the scope of the request. 

I would suggest to reach out to developer support directly related to your use case via creating a support case.
https://developer.amazonservices.com/support

**Comment by Gareth-Lee-PBH** [comment]
I'm unable to raise a ticket in developer support - it requires me to have access to a north American account

**Comment by nkev** [comment]
@Gareth-Lee-PBH  I have the same issue. Did you resolve this? i.e. Did you find an API call that returns both `ASIN` and  `Model Number` used in the Purchase Order?
