### ISSUE TITLE
[BUG] code=403, message=Forbidden

### ISSUE THREAD

**Issue by govpnvip** [amzn/selling-partner-api-docs#1356]
I am trying the new SP-API and I met the issue about authorization when call request.
 Access to requested resource is denied.
 Can you help me?

Date: Sat, 04 Sep 2021 02:33:06 GMT
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
x-amzn-RequestId: 01b58cf6-33ee-4367-ba6a-8e301fc59017
x-amzn-ErrorType: AccessDeniedException
x-amz-apigw-id: FHcjYFdboAMFTdA=
OkHttp-Sent-Millis: 1630722786130
OkHttp-Received-Millis: 1630722786700
Response{protocol=http/1.1, code=403, message=Forbidden, url=https://sellingpartnerapi-na.amazon.com/sellers/v1/marketplaceParticipations}

**Comment by yizeku** [comment]
Hello @govpnvip,

Verify that you have added the session token in the "X-Amz-Security-Token" header and that it is signed in all your requests.
