### ISSUE TITLE
[BUG] Documentation not clear in Upload the feed data 

### ISSUE THREAD

**Issue by abuzuhri** [amzn/selling-partner-api-docs#1358]
**Documentation not clear for Step 3. Upload the feed data**
We are not using java code we are using c# , and we need the step at least in description in order to submit XML please [open documentation](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md#step-3-upload-the-feed-data).

I try to send PUT to same URL and add XML in row body using POSTMAN , but i get error
![image](https://icanlo.com/Content/uploads/POSTMAN.JPG)

Please give us clear step what we should do , or what we need to send POSTMAN request.

**Comment by abuzuhri** [comment]
Problem solve after i change the content type to be same content type i use when submit CreateFeedDocument "application/json; charset=UTF-8"


Here the full code in c# if some one need it 

```CSharp
        private string postXMLData(string destinationUrl, string requestXml)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(destinationUrl);
            byte[] bytes;
            bytes = System.Text.Encoding.ASCII.GetBytes(requestXml);
            request.ContentType = LinqHelper.GetEnumMemberValue("text/xml; charset=UTF-8");
            request.ContentLength = bytes.Length;
            request.Method = "PUT";
            Stream requestStream = request.GetRequestStream();
            requestStream.Write(bytes, 0, bytes.Length);
            requestStream.Close();
            HttpWebResponse response;
            response = (HttpWebResponse)request.GetResponse();
            if (response.StatusCode == HttpStatusCode.OK)
            {
                Stream responseStream = response.GetResponseStream();
                string responseStr = new StreamReader(responseStream).ReadToEnd();
                return responseStr;
            }
            return null;
        }
```


You can use my open source project for c# [Amazon-SP-API-CSharp](https://github.com/abuzuhri/Amazon-SP-API-CSharp)

**Comment by yizeku** [comment]
Hello @abuzuhri,

Amazon SP-API has very good case support for java, but rarely has support for C#, I also developed it in C#, do you know if **JSON_LISTINGS_FEED** can be used to add products?

Can you help me?

Thank you.

**Comment by gokigoks** [comment]
@yizeku should be possible to add products with that feed type. See more [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md)

**Comment by abuzuhri** [comment]
I develop feed in my custom API Take look to my repository

**Comment by abuzuhri** [comment]
> Hello @abuzuhri,
> 
> Amazon SP-API has very good case support for java, but rarely has support for C#, I also developed it in C#, do you know if **JSON_LISTINGS_FEED** can be used to add products?
> 
> Can you help me?
> 
> Thank you.


@yizeku Yes please contact me i will help you

**Comment by yizeku** [comment]
@abuzuhri 

Can you give me your email to contact you?

**Comment by abuzuhri** [comment]
> @abuzuhri 
> 
> 
> 
> Can you give me your email to contact you?

Tareq.abuzuhri@gmail.com
