### ISSUE TITLE
[BUG] fulfillmentOutbound_2020-07-01 package tracking api response property "currentStatus" has an extra value OUT_FOR_DELIVERY

### ISSUE THREAD

**Issue by yeyu456** [amzn/selling-partner-api-docs#1363]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
fulfillmentOutbound_2020-07-01 tracking api response property "currentStatus" has an extra value OUT_FOR_DELIVERY.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md#currentstatus

**Description of what the documentation currently says**
missing enum value.

**Description of what the documentation should say**
Add enum value OUT_FOR_DELIVERY to currentStatus, and if there're other extra status, pls update as well.

**Screenshots**

**Additional context**

**Comment by ihoment-meihui** [comment]
I find other two enum values, DELIVERY_ATTEMPTED and RETURN_RECEIVED_IN_FC.

**Comment by avvarga** [comment]
Hello @yeyu456 and @ihoment-meihui ,

Thank you for reaching out regarding missing enum values for the currentStatus parameter of the getPackageTrackingDetails operation.

Please note that you can find the updated details regarding this in our new documentation site for the [CurrentStatus enum](https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-api-v2020-07-01-reference#currentstatus).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case] (https://developer.amazonservices.com/support) with us.

Thanks,
Alejandro C
Selling Partner API Developer Support
