### ISSUE TITLE
Where can I start writing an API?

### ISSUE THREAD

**Issue by msbeden** [amzn/selling-partner-api-docs#1366]
Hello,

I have a seller and developer account. We are a software company. Our main goal is to prepare amazon api and attract products with this api, add products, control orders and stock transactions. I need to use Selling Partner API for that too, right? MWS support will be withdrawn?

I've reached the "**Registering your application**" stage on https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md.

The data I have now are:

* LWA credentials
** Client identifier : amzn1.application-oa2-client.......
** Client secret : 76d8b.........
** Renewal Token : Atzr|IwEBIJ..............

roleArn: arn:aws:iam::.......:role/apiRole

"https://github.com/amzn/selling-partner-api-docs/blob/c76e63c403f7e3b2290cfeb65177af860babb838/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md#Tutorial-Migrate-an-Amazon-MWS-authorization-to-a-Selling-Partner-API-application" 

I want to login. What information does this correspond to? Can you help me I've been trying for days.

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

Please refer to below section of the SP API Developer Guide to understand how to connect to SP API after registering your application -

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#connecting-to-the-selling-partner-api

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by msbeden** [comment]
Hello there,
As you stated, I successfully created the "Step 1. Request a Login with Amazon access token" part. I got access_token as a result of LWA, but when I switched to "Step 2" I started to get stuck. I also added the header part in "Step 3".

Use the "GET" method in the document. But it also says "PUT" method, I didn't know which one to use. I tried both. I didn't get results. I am getting an error as in the picture.

What is the "shipmentId1" variable? Are we creating a fixed value ourselves?

I'm waiting for your help. Good work.

![2021-09-08_094039](https://user-images.githubusercontent.com/14031329/132459763-794cb305-5439-4190-8696-d303f80fcf51.png)
![2021-09-08_094356](https://user-images.githubusercontent.com/14031329/132459764-f14ad4d8-ac67-4b74-9da1-94118606bf17.png)

**Comment by mburakgunduz** [comment]
Can you reply urgently? I am also having the same problem.

**Comment by ShivikaK** [comment]
Hello @msbeden 

The shipmentId1 is just an example for the value of Shipment ID path variable provided in our documentation.

I would suggest referring to sandbox section to test connection to any API section of SP API by connecting to the sandbox endpoints. 

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by msbeden** [comment]
Hello.

I still didn't understand anything from the documentation available on Github. I'm trying to solve my operations with a ready-made php library.

I am trying to login with "https://github.com/amzn/selling-partner-api-models/tree/main/models/authorization-api-model". But I couldn't find where to get MWS token.

I developed an application under the "https://sellercentral.amazon.com.tr/sellingpartner/developerconsole/ref=xx_DevCon_dnav_xx" page. After this app is published on Amazon Appstore, I need to get MWS token by giving access to this app from my seller account, am I right?

**Comment by vdanyliv** [comment]
@msbeden I wrote several articles about SP-API, maybe you found something useful here 

[Amazon selling partner API (SPAPI) — how to quickly and simply integrate with new API (Part 1)
](https://vdanyliv.medium.com/amazon-selling-partner-api-spa-how-to-quickly-and-simply-integrate-with-new-api-part-1-c3ca05a91b43)

[Amazon selling partner API (SPAPI) — how to quickly and simply integrate with new API (Part 2)](https://vdanyliv.medium.com/amazon-selling-partner-api-spapi-how-to-quickly-and-simply-integrate-with-new-api-part-2-59d7458f24fe)

[Amazon selling partner API (SPAPI) — How to implement reports generation workflow with AWS Step Function (Part 1)](https://vdanyliv.medium.com/amazon-selling-partner-api-spapi-how-to-implement-reports-generation-workflow-with-aws-step-8f32b668851b)
