### ISSUE TITLE
listings-items-api operation putListingItem

### ISSUE THREAD

**Issue by salvatoremondino** [amzn/selling-partner-api-docs#1367]
Hi,
I need the correct JSON object to add new product to Amazon with listings-items-api operation "putListingItem".
I tried with example in this link (https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md#tutorial-create-or-fully-update-a-listing). The response is "ACCEPTED", but I don't see the product in Amazon Seller Center.

It's really urgent. Thank you very much

**Comment by MST1122** [comment]
@ShivikaK 
Listing API PUT Request, I get this response:
{
  "sku": "mouse_pad_test_sku",
  "status": "ACCEPTED",
  "submissionId": "e99a607285454204ae413bf2f0912fb8",
  "issues": []
}

For me, the new product shows in the "**Manage Inventory**" list, but when I edit the product, I get this message: 
"**This SKU has an inconsistent product classification with the ASIN. Please submit a feed to update this SKU to match the ASIN product classification**."

**Comment by yizeku** [comment]
Hello @MST1122,

productType : **GUITARS** 

The Amazon product type specified is invalid or not supported

Can you look at this problem?

Thank you.

**Comment by yizeku** [comment]
@salvatoremondino 

Can you send your body parameter? I also want to use the listing API to add products.

**Comment by salvatoremondino** [comment]
{
              "productType": "PRODUCT",
              "requirements": "LISTING_OFFER_ONLY",
              "attributes": {
                "item_name": [{
                  "value": "On-Stage Classic Sheet Music Stand, Nickel with Bag",
                  "language_tag": "en_US",
                  "marketplace_id": "APJ6JRA9NG5V4"
                }]
              }

This is my body parameter, the server response "ACCEPTED" but in Manage Inventory (Amazon Seller Center) I'don't see anything.  Can you help me?

**Comment by RexFang** [comment]
> @ShivikaK
> Listing API PUT Request, I get this response:
> {
> "sku": "mouse_pad_test_sku",
> "status": "ACCEPTED",
> "submissionId": "e99a607285454204ae413bf2f0912fb8",
> "issues": []
> }
> 
> For me, the new product shows in the "**Manage Inventory**" list, but when I edit the product, I get this message:
> "**This SKU has an inconsistent product classification with the ASIN. Please submit a feed to update this SKU to match the ASIN product classification**."

Hi Sikandar Tariq, Nice to meet you. I ran into the same problem that the response is "ACCEPTED", but I don't see the product in Amazon Seller Center. Do you know the broblem ? Thx

**Comment by MST1122** [comment]
> Hi Sikandar Tariq, Nice to meet you. I ran into the same problem that the response is "ACCEPTED", but I don't see the product in Amazon Seller Center. Do you know the problem? Thx

Hi RexFang, If the response is "ACCEPTED". then the product will appear in the Manage Inventory List. For me sometimes it takes few seconds and sometimes a few minutes.

**Comment by RexFang** [comment]
> > Hi Sikandar Tariq, Nice to meet you. I ran into the same problem that the response is "ACCEPTED", but I don't see the product in Amazon Seller Center. Do you know the problem? Thx
> 
> Hi RexFang, If the response is "ACCEPTED". then the product will appear in the Manage Inventory List. For me sometimes it takes few seconds and sometimes a few minutes.

Tks Sikandar Tariq, I give up the way put listing by listing api, and use feed api now. Feed  api is working. Listing item api maybe have some problem now.

**Comment by MST1122** [comment]
> Tks Sikandar Tariq, I give up the way put listing by listing api, and use feed api now. Feed  api is working. Listing item api maybe have some problem now.
Hi @RexFang . Please can you share sample request that you used to create listing?

**Comment by johninf2022** [comment]
Still nobody would like to share a full demo of creating a new listing with putItemListing?

**Comment by xinxiangshichengddd** [comment]
This issue still exists in late 2024 and noone has bothered to answer, fix or provide an explanation?

**Comment by Lemonn8** [comment]
> That question still exists in 2024 and no one has bothered to answer, fix or provide an explanation?

I have figured it out in the meantime. The "ACCEPTED" response is in upstream, but before a listing is uploaded, it is re-processed downstream, where more errors may occur. You can view those errors by GETting the SKU you attempted to upload.

Moreover, there's no serious documentation on Amazon's end regarding the required JSON parameters. What they suggest, and what happens to be the only possible way to figure it out, is to use the Product Type Definitions API. There, you'll be to GET a response that contains a link to a huge JSON, which, in turn, contains the logic for the requirements of each product type.

What I suggest is GETting the product to see which parameters are missing, then finding the accepted values for each parameter. Keep trial-and-erroring until it works.

That's Amazon for you! Good luck. Surprised noone has documented this process anywhere.

**Comment by chapmanjw** [comment]
These guides outline the main components to building out an end-to-end listings workflow using Selling Partner APIs: https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide and https://developer-docs.amazon.com/sp-api/docs/manage-product-listings-guide. 

For most workflows, the general pieces to put together are:

- Retrieving JSON Schemas from the Product Type Definitions API
- Submit Requests with the Listings Items API (PUT/PATCH/DELETE) and/or JSON_LISTINGS_FEED (Feeds API)
- Subscribe to Listings Status and Issues Change Notifications
- Read Post-Submission Processing Errors Using the Listings Items API (GET)

By validating using the JSON Schemas, most submission errors can be avoided. Additionally, there is a new "validation preview" option on the Listings Items API that provides a deeper preview of asynchronous processing to identify potential conflict errors (where submissions fail due to conflicting with existing catalog data) or eligibility errors.
