### ISSUE TITLE
'Creation of report schedule type 47700 is not allowed at this time' when creating GET_MERCHANT_LISTINGS_ALL_DATA schedule

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-docs#1368]
Hi! 

It is not possible to create report schedule for `GET_MERCHANT_LISTINGS_ALL_DATA` report as it results in error. 

API url used `/reports/2020-09-04/schedules`

Payload:

```
{'reportType': 'GET_MERCHANT_LISTINGS_ALL_DATA',
 'marketplaceIds': ['ATVPDKIKX0DER'],
 'period': 'P1D'}
```

This is blocking issue right now.

**Comment by JacobShopWired** [comment]
I am also running into this issue.
Currently having to run a corn job to request a report, which obviously isn't ideal.

**Comment by pecalleja** [comment]
Also experimenting the same issue. why there are some reports than do not allow to create the schedule?
payload :
```json
{
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ],
    "period": "P1D",
    "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
    "reportOptions": {},
    "nextReportCreationTime": "2021-12-21T12:00:00-05:00"
}
```

result:
400 Bad Request
```json
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Creation of report schedule type 47700 is not allowed at this time",
            "details": ""
        }
    ]
}
```

**Comment by michaelslobodskih** [comment]
aUnfortunately, the issue is still not resolved.  GET_MERCHANT_LISTINGS_ALL_DATA must have schedule possibility
