### ISSUE TITLE
I found no name and phone from the interface called "  GET /orders/v0/orders/{orderId}/address  "

### ISSUE THREAD

**Issue by ChenJevon** [amzn/selling-partner-api-docs#1369]
"orderAddress": {
        "AmazonOrderId": "111-4807156-1003403",
        "ShippingAddress": {
            "City": "FREMONT",
            "CountryCode": "US",
            "Name": "",
            "PostalCode": "94538-4507",
            "StateOrRegion": "CA"
        }
    }

**Comment by foxfiring** [comment]
PII

**Comment by yizeku** [comment]
@ChenJevon 

I have the same problem. How did you solve it? 

Can you help me?

Thank you.
