### ISSUE TITLE
[FEATURE] Feeds API Error messages

### ISSUE THREAD

**Issue by gokigoks** [amzn/selling-partner-api-docs#1370]
I've been getting an Error 400 on the create feed endpoint when it was working a few weeks ago when I left it. Is it possible to expound the details on this error? 

Error:
```
{
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
}
```

I'm using a tab-separated file and I am able to upload it with no issue. I did everything trying to debug this like changing each parameter to show exactly which one is erroneous and I still can't find what exactly is wrong with my request.

Here's my request:

```
    [body] => {"feedType":"POST_FLAT_FILE_INVLOADER_DATA","marketplaceIds": 
    ["A2EUQ1WTGCTBG2"],"inputFeedDocumentId":"feed-id-sample"}
    [headers] => Array
        (
            [User-Agent] => jlevers/selling-partner-api/3.1.3 (Language=PHP)
            [Accept] => application/json
            [Content-Type] => application/json
            [Host] =>  sellingpartnerapi-na.amazon.com
        )

    [request] => https://sellingpartnerapi-na.amazon.com/feeds/2021-06-30/feeds
```

Any help is appreciated.

**Comment by hellmark1990** [comment]
I have the same issue.
I get this error after all create feed fields have been provided and are valid.

**Comment by gokigoks** [comment]
@hellmark1990 Thank you for the support.

I'm just hoping they enhance the error messages they send back. I tried anything I can think of to find what my issue is but to no success. I feel like I'm feeling around the dark due to this. I'm not even sure if it's my code that's not working or if it's an issue on Amazon's side.

**Comment by hellmark1990** [comment]
@gokigoks In my case I had wrong merchant id. Now everything is fine.

**Comment by gokigoks** [comment]
@hellmark1990 Glad to hear you got yours resolved. 

Should not be my case though since I can query the ReportsAPI just fine.

**Comment by gokigoks** [comment]
Update: My issue with the feeds API might be due to our seller account having restrictions. This is noted when I try to 'add product via upload' from the seller account and are receiving "Sorry, the seller is blocked and cannot upload feeds in this marketplace (MERCHANT_STATUS_BLOCKED)".


It's very disheartening how unhelpful the error message is though.. I hope SP-API makes improvements. If the error messages made sense, I believe the amount of tickets/issues opened would be greatly reduced.
