### ISSUE TITLE
NOT ABLE TO VERIFY MY APP

### ISSUE THREAD

**Issue by sohailali26** [amzn/selling-partner-api-docs#1373]
Hi shivikaK

facing this issue while Authorizing as a new developer .

Something went wrong
This Developer is not currently eligible for new authorizations.

Error Code: MD9000

Also i have registered on the developer central and my app is in draft stage but dont know why its is not verifying , from where we get the support if we have any issue , seller cental support donot have any knowledge about this

**Comment by szkiecin** [comment]
1. Check if the API Type is "SP API"
2. Check if you assigned OAuth Login URI + OAuth Redirect URI:
![Screen Shot 2021-09-09 at 09 16 28](https://user-images.githubusercontent.com/13007156/132640506-df5513ad-611c-4153-bb74-b9beec7f5fc9.png)

**Comment by ShivikaK** [comment]
Hello @sohailali26 

Thank you for raising this issue.

You can open a support case with us by navigating to this [link](https://developer.amazonservices.com/support) 

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by sohailali26** [comment]
hi for the past few week i'm struggling to find the following credential :
1>AMAZON ACESS KEY ID
2> AMAZON SECRET KEY

pls help me out i have completed my app just want to link seller account to my module.
