### ISSUE TITLE
How get all data shipping order

### ISSUE THREAD

**Issue by lionalex** [amzn/selling-partner-api-docs#1375]
I try to get all shipping data of my orders in Amazon.
If I call 
`orders/v0/orders/$amazon_order_id`
I receive all data, but for BuyerInfo nothing and for ShippingAddress only some data. For example I don't see the street and the name of customer.
I try with normal call with SignRequest and Token from standard "auth/o2/token".
I read that for some data is necessary "restrictedDataToken", so I call
`/tokens/2021-03-01/restrictedDataToken`
and I receive a token, but if I use this "restrictedDataToken" in "x-amz-access-token" header for call orders/v0/orders/$amazon_order_id,  i receive this error:
`Access to requested resource is denied`

My code PHP to get restrictedDataToken is:
```
$response = $client->send(
                $this->getSignatureAWS()->signRequest(
                    new Request(
                        "POST",
                        $uri,
                        [
                            'Content-Type' => 'application/json',
                            "x-amz-access-token" => $this->getTokenAWS()
                        ],
                        json_encode(
                            [
                                "restrictedResources" => [
                                    "method" => "GET",
                                    "path" => "/orders/v0/orders",
                                    "dataElements" => ["buyerInfo","shippingAddress"]
                                ]
                            ]
                        ),
                        "1.1"
                    )
                )
            )->getBody()->getContents();
```

Where is error?

**Comment by Gounlaf** [comment]
According to the documentation, the RDT Token need to match the path of your request ; I guess you miss the `$amazon_order_id` in your `restrictedResources` payload

```php
$response = $client->send(
                $this->getSignatureAWS()->signRequest(
                    new Request(
                        "POST",
                        $uri,
                        [
                            'Content-Type' => 'application/json',
                            "x-amz-access-token" => $this->getTokenAWS()
                        ],
                        json_encode(
                            [
                                "restrictedResources" => [
                                    "method" => "GET",
                                    "path" => "/orders/v0/orders/$amazon_order_id",<--- here
                                    "dataElements" => ["buyerInfo","shippingAddress"]
                                ]
                            ]
                        ),
                        "1.1"
                    )
                )
            )->getBody()->getContents();
```

**Comment by lionalex** [comment]
Thanks for your comment, but with full path included order id, the response from amazon is the same: 403 Forbidden - Access to requested resource is denied

**Comment by AlexCB400** [comment]
I have the same problem. I have been getting a response:
`{
    "errors": [
      {
        "code": "InvalidInput",
        "message": "Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]",
        "details": ""
      }
    ]
  }`

**Comment by dnErf** [comment]
Hi, I am having same issue as well, I can get our RDT but when i used it on orders endpoint and replacing LWA token to RDT im getting denied.

Is there any update on this issue? or is there a work around to get the shipping address? Thanks for any help.

**Comment by diegocvazquez** [comment]
> Hi, I am having same issue as well, I can get our RDT but when i used it on orders endpoint and replacing LWA token to RDT im getting denied.
> 
> Is there any update on this issue? or is there a work around to get the shipping address? Thanks for any help.

Hi there,
does the developer account have access to PII information ?

**Comment by lionalex** [comment]
We founded the error.
In the body we have an error. This is the correct code:

```
$response = $client->send(
                $this->getSignatureAWS()->signRequest(
                    new Request(
                        "POST",
                        $uri,
                        [
                            'Content-Type' => 'application/json',
                            "x-amz-access-token" => $this->getTokenAWS()
                        ],
                        json_encode(
                            [
                                "restrictedResources" => [
                                   [  <--- here
                                    "method" => "GET",
                                    "path" => "/orders/v0/orders",
                                    "dataElements" => ["buyerInfo","shippingAddress"]
                                   ] <--- here
                                ]
                            ]
                        ),
                        "1.1"
                    )
                )
            )->getBody()->getContents();

```

The error was that in restrictedResources we must add another array content. In the code with the new array in "<--- here"

**Comment by dnErf** [comment]
> 
> Hi there, does the developer account have access to PII information ?

Hi, I think we do, we have MWS service that is currently running fine but I will re-check it if something happen on that level, thanks. Is there anything else we should look into?

**Comment by diegocvazquez** [comment]
> > Hi there, does the developer account have access to PII information ?
> 
> Hi, I think we do, we have MWS service that is currently running fine but I will re-check it if something happen on that level, thanks. Is there anything else we should look into?

Not that I can think of, was just an idea but if it works with MWS with the same developer id, I guess there is another problem

**Comment by dnErf** [comment]
thanks for answering my question. I'm going to leave a snippet of how we get and use the RDT (c# code) and hopefully someone can put us on right direction.

```
var assumeRoleResponse = await client.AssumeRoleAsync(assumeRoleRequest);

// RDT
IRestRequest rdtRequest = new RestRequest("/tokens/2021-03-01/restrictedDataToken", Method.POST);
rdtRequest = new LWAAuthorizationSigner(lwaAuth).Sign(rdtRequest);

var rdtElements = new string[] { "buyerInfo", "shippingAddress" };
var rdtResources = new { method = "GET", path = "/orders/v0/orders", dataElements = rdtElements };
var rdtBody = JsonConvert.SerializeObject(new { restrictedResources = rdtResources });
rdtRequest.AddJsonBody(rdtBody);

awsAuthenticationCredentials = new AWSAuthenticationCredentials
{
                AccessKeyId = assumeRoleResponse.Credentials.AccessKeyId,
                SecretKey = assumeRoleResponse.Credentials.SecretAccessKey,
                Region = "us-east-1"
};
rdtRequest = new AWSSigV4Signer(awsAuthenticationCredentials).Sign(rdtRequest, restClient.BaseUrl.Host);

var executedRdt = restClient.Execute(rdtRequest);
var amazonRdt = JsonConvert.DeserializeObject<RdtResponsePayLoad>(executedRdt.Content.ToString());

// -
// ORDERS
IRestRequest restRequest = new RestRequest("/orders/v0/orders", Method.GET);
restRequest.AddQueryParameter("MarketplaceIds", "ATVPDKIKX0DER");
restRequest.AddQueryParameter("CreatedAfter", StartDate); 

restRequest.AddHeader("x-amz-access-token", amazonRdt.RestrictedDataToken); // <-

restRequest.AddHeader("X-Amz-Security-Token", assumeRoleResponse.Credentials.SessionToken);
restRequest.AddHeader("X-Amz-Date", DateTime.Now.ToString("yyyyMMddTHHmmssZ"));

restRequest = new AWSSigV4Signer(awsAuthenticationCredentials).Sign(restRequest, restClient.BaseUrl.Host);

var executedRequest = restClient.Execute(restRequest);
```

**Comment by loaded02** [comment]
Hi, I am having the same issue here. We have access granted for PII level. I can query the sandbox sucessfully for restrictedDataToken, but on Production I receive `InvalidInput ... Application does not have access to one or more requested data elements: [shippingAddress]` Does it make sense to contact Amazon Support with this?

**Comment by corbin-munce** [comment]
> thanks for answering my question. I'm going to leave a snippet of how we get and use the RDT (c# code) and hopefully someone can put us on right direction.
> 
> ```cs
> var assumeRoleResponse = await client.AssumeRoleAsync(assumeRoleRequest);
> 
> // RDT
> IRestRequest rdtRequest = new RestRequest("/tokens/2021-03-01/restrictedDataToken", Method.POST);
> rdtRequest = new LWAAuthorizationSigner(lwaAuth).Sign(rdtRequest);
> 
> var rdtElements = new string[] { "buyerInfo", "shippingAddress" };
> var rdtResources = new { method = "GET", path = "/orders/v0/orders", dataElements = rdtElements };
> var rdtBody = JsonConvert.SerializeObject(new { restrictedResources = rdtResources });
> rdtRequest.AddJsonBody(rdtBody);
> 
> awsAuthenticationCredentials = new AWSAuthenticationCredentials
> {
>                 AccessKeyId = assumeRoleResponse.Credentials.AccessKeyId,
>                 SecretKey = assumeRoleResponse.Credentials.SecretAccessKey,
>                 Region = "us-east-1"
> };
> rdtRequest = new AWSSigV4Signer(awsAuthenticationCredentials).Sign(rdtRequest, restClient.BaseUrl.Host);
> 
> var executedRdt = restClient.Execute(rdtRequest);
> var amazonRdt = JsonConvert.DeserializeObject<RdtResponsePayLoad>(executedRdt.Content.ToString());
> 
> // -
> // ORDERS
> IRestRequest restRequest = new RestRequest("/orders/v0/orders", Method.GET);
> restRequest.AddQueryParameter("MarketplaceIds", "ATVPDKIKX0DER");
> restRequest.AddQueryParameter("CreatedAfter", StartDate); 
> 
> restRequest.AddHeader("x-amz-access-token", amazonRdt.RestrictedDataToken); // <-
> 
> restRequest.AddHeader("X-Amz-Security-Token", assumeRoleResponse.Credentials.SessionToken);
> restRequest.AddHeader("X-Amz-Date", DateTime.Now.ToString("yyyyMMddTHHmmssZ"));
> 
> restRequest = new AWSSigV4Signer(awsAuthenticationCredentials).Sign(restRequest, restClient.BaseUrl.Host);
> 
> var executedRequest = restClient.Execute(restRequest);
> ```

instead of:
```cs
rdtRequest.AddJsonBody(rdtBody);
```
try:
```cs
string jsonRequestBody = Newtonsoft.Json.JsonConvert.SerializeObject(rdtBody);
rdtRequest.AddBody(jsonRequestBody, "application/json");
```

**Comment by corbin-munce** [comment]
> thanks for answering my question. I'm going to leave a snippet of how we get and use the RDT (c# code) and hopefully someone can put us on right direction.
> 
> ```cs
> var rdtElements = new string[] { "buyerInfo", "shippingAddress" };
> var rdtResources = new { method = "GET", path = "/orders/v0/orders", dataElements = rdtElements };
> var rdtBody = JsonConvert.SerializeObject(new { restrictedResources = rdtResources });
> rdtRequest.AddJsonBody(rdtBody);
> 
> awsAuthenticationCredentials = new AWSAuthenticationCredentials
> ```

instead of 
```cs
rdtRequest.AddJsonBody(rdtBody);
```

try
```cs
rdtRequest.AddBody(rdtBody, "application/json");
```

**Comment by corbin-munce** [comment]
> thanks for answering my question. I'm going to leave a snippet of how we get and use the RDT (c# code) and hopefully someone can put us on right direction.
> 
> ```cs
> var rdtBody = JsonConvert.SerializeObject(new { restrictedResources = rdtResources });
> ```

put it in another array like this:
```cs
var rdtBody = JsonConvert.SerializeObject(new { restrictedResources = new object[] { rdtResources } });
```
