### ISSUE TITLE
OAuth Process Inconsistent from Amazon's side. Callback URI Malformed

### ISSUE THREAD

**Issue by bpyzikvc** [amzn/selling-partner-api-docs#1376]
We have an issue with the way Amazon sends us their callback URI. We were under the impression it would always be a full url. Recently, about 90% of the time, Amazon sends us https://sellercentral.amazon.com/apps/authorize/confirm/amzn1.sp.solution.XXX Which is exactly what we'd like to see.

The remaining times they only send us the end of that URI: /apps/authorize/confirm/amzn1.sp.solution.XXX

Can someone explain this inconsistency? Is it intentional?

**Comment by teb02** [comment]
Same **critical issue** appeared today (09/09/2021).

At the moment Amazon calls the sign-in URL with wrong amazon_callback_uri:
https://site/oauth/sign-in/amazon?amazon_callback_uri=/apps/authorize/confirm/amzn1.sellerapps.app

amazon_callback_uri should contain domain with protocol according to the official documentation: 
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md 

According to the standard:
https://datatracker.ietf.org/doc/html/rfc5849 
callback_uri should be absolute URI:
Absolute URIs typically take the form protocol://domain/path.

**Comment by ShivikaK** [comment]
Hello @teb02 and @bpyzikvc 

Thank you for raising this issue.

Are you experiencing this issue in only one region based authorization? Can you confirm which region is the oauth workflow returning relative amazon callback uri?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by teb02** [comment]
@ShivikaK I think the issue is on all regions. We have tested it on America and Europe regions.

**Comment by bpyzikvc** [comment]
@ShivikaK Is this something that will be looked into soon? We have customers that get failures when trying to authorize and there is nothing we can do for them.

**Comment by paulabirocchi** [comment]
I am also waiting for assistance from Amazon. :(

**Comment by ShivikaK** [comment]
Hello,

We have raised this issue to the engineering team. I will share more details and next steps once we are able to investigate the root cause.

Thank you for your patience and cooperation.

Regards,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello everyone,

The team made a fix that should resolve the issue with malformed callback URI.

If issue persists, please let us know and share examples of malformed URI observed.

Regards,
Shivika Khare
Selling Partner API Developer Support
