### ISSUE TITLE
My website's sign-in page does not appear at Step 2: The selling partner consents to authorize your application

### ISSUE THREAD

**Issue by paulabirocchi** [amzn/selling-partner-api-docs#1378]
Hi, 

I am stucked at "Step 2. The selling partner consents to authorize your application".
I can view the consent page. I ticked the box and clicked in "Log in to MascotReporting now", but it returns to the same web page, it does not appear any log in webpage. Could you help me please?

[printscreen.docx](https://github.com/amzn/selling-partner-api-docs/files/7143775/printscreen.docx)

**Comment by teb02** [comment]
Probably this is the same issue as in https://github.com/amzn/selling-partner-api-docs/issues/1376

**Comment by paulabirocchi** [comment]
Thanks @teb02. Does Amazon usually answer through this channel?

**Comment by bpyzikvc** [comment]
@paulabirocchi I would go into the settings of your app and verify that the OAuth Login URI is actually a link to your web page. My theory is that you have something like https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.0bf296b5-36a6-4942-a13e-EXAMPLEfcd28.

The documentation is not super clear but this is a mistake I made at first and it resulted in the same behavior. To check just go to the develop apps page on your seller central, then click 'edit app' on the one you are attempting to authorize.

**Comment by paulabirocchi** [comment]
Thank you @bpyzikvc . I will need assistance from my manager to access the develop apps page (probably on Tuesday).
My goal is to access Amazon API through Python. I'm familiar with Python, but new to API's. Does my app need to be published to get access through Python? All that I'm trying to do is to access the API through Python.

**Comment by bpyzikvc** [comment]
@paulabirocchi If you are creating an application for ONLY your own selling account then no it does not require it to be published. You would also be better off going through 'self authorization' process instead of OAuth since it is much simpler. 

If you are creating an application in python for other selling accounts you will need those accounts to go through oauth and the app needs to be published. Unfortunately you would not have a choice for this case.

**Comment by paulabirocchi** [comment]
Yes, I'm creating an application for only my selling account. I will take a look into 'self authorization'. Thank you.

**Comment by bpyzikvc** [comment]
@paulabirocchi  https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization

**Comment by rugved1991** [comment]
Hi @bpyzikvc,

You dont need have your app published if you are building a solution for your own account. If you are making the solution available for all sellers, only then you should initiate the app publish process.
For a quick deployment of Selling Partner API using Python, please feel free to check out the new AWS Quickstart for Selling Partner APIs. 
https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/
This is the quickest way to get started on using the Selling Partner APIs. 
Feel free to open issues or provide feedback on the Quickstart issues page.

Thanks,
Rugved
Solutions Architect SP API.

**Comment by paulabirocchi** [comment]
Hi @bpyzikvc 
I was able to follow the steps you mentioned in self authorization. Now I receive the message in Python: AuthorizationError: ('unauthorized_client', 'Not authorized for requested operation', 400). I have opened an issue about that https://github.com/amzn/selling-partner-api-docs/issues/1447, any help would be appreciated. Thank you.
