### ISSUE TITLE
This SKU has an inconsistent product classification with the ASIN

### ISSUE THREAD

**Issue by MST1122** [amzn/selling-partner-api-docs#1379]
@ShivikaK 
Listing API PUT Request, I get this response:
{
"sku": "mouse_pad_test_sku",
"status": "ACCEPTED",
"submissionId": "e99a607285454204ae413bf2f0912fb8",
"issues": []
}

For me, the new product shows in the "**Manage Inventory**" list, but when I edit the product, I get this message:
"**This SKU has an inconsistent product classification with the ASIN. Please submit a feed to update this SKU to match the ASIN product classification.**"

**Comment by salvatoremondino** [comment]
Hi, can do you send your body parameter?

**Comment by RexFang** [comment]
> @ShivikaK Listing API PUT Request, I get this response: { "sku": "mouse_pad_test_sku", "status": "ACCEPTED", "submissionId": "e99a607285454204ae413bf2f0912fb8", "issues": [] }
> 
> For me, the new product shows in the "**Manage Inventory**" list, but when I edit the product, I get this message: "**This SKU has an inconsistent product classification with the ASIN. Please submit a feed to update this SKU to match the ASIN product classification.**"

Hi Sikandar Tariq, did you had solve the problerm ? I ran into the same problerm now
