### ISSUE TITLE
{"error_description":"The authorization grant type is not supported by the authorization server","error":"unsupported_grant_type"}

### ISSUE THREAD

**Issue by pengyanbing84** [amzn/selling-partner-api-docs#138]
I’m using Request a Login with Amazon access token and encountered an error. Now I have finished, Registering as a developer, Registering your Selling Partner API application, please help me, thank you
I use Python3。
Is there a Python call example?

**Comment by 2445809596** [comment]
```
amazon_auth_url = 'https://api.amazon.com/auth/o2/token'
headers = {
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
}
data = {
    "code": lwa_code,
    "redirect_uri": redirect_uri,
    "client_id": client_id,
    "client_secret": client_secret,
    "grant_type": "authorization_code",
}
response = requests.post(url=amazon_auth_url, headers=headers, data=data)
```

**Comment by pengyanbing84** [comment]
> ```
> amazon_auth_url = 'https://api.amazon.com/auth/o2/token'
> headers = {
>     "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
> }
> data = {
>     "code": lwa_code,
>     "redirect_uri": redirect_uri,
>     "client_id": client_id,
>     "client_secret": client_secret,
>     "grant_type": "authorization_code",
> }
> response = requests.post(url=amazon_auth_url, headers=headers, data=data)
> ```

Thank you

**Comment by 2445809596** [comment]
加我名字就行

**Comment by winterstefan** [comment]
@pengyanbing84 @2445809596 Have you managed getting this working?

I face the same error while trying to get a valid token by LWA for using in Selling Partner API. See [this](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-your-application-exchanges-the-lwa-authorization-code-for-a-lwa-refresh-token) Github documentation for details.

**Comment by 2445809596** [comment]
@winterstefan I only have Python code. There is no problem with this part of the document

**Comment by MST1122** [comment]
Hi @winterstefan,
can you help me, where can I find my Developer ID? and also have you found the solution for your above-mentioned error, because I'm facing the same error?

**Comment by parvathm** [comment]
Hi,

Sorry for the delay. Were you able to get the access token? If you are still having issue please open a support case we will get back to you.

Thanks,
Parvathm,
Selling Partner API Developer Support.
