### ISSUE TITLE
Is report generation time-limited globally or by marketplace?

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#1381]
I'm trying to fetch the `GET_REFERRAL_FEE_PREVIEW_REPORT` report for a seller that participates in multiple marketplaces. The report doesn't let me fetch data for all marketplaces at the same time, so I need to create separate reports for the two marketplaces the seller participates in. The documentation for that report type says it can only be generated once every 24 hours -- does that mean that I can fetch one instance of the report for each marketplace every 24 hours, or can I only fetch a single marketplace's data in each 24-hour period?

**Comment by moltar** [comment]
I don't have the answer but this report has been the source of major pain for us.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by GJ-JG** [comment]
Hi all, thanks for the question!
This report type should allow each seller to request a report for each marketplace in every 24 hours.
You can create a ticket case to our dedicated developer support team for the further investigation and get help by providing the API details.
