### ISSUE TITLE
UPLOAD_VAT_INVOICE  403

### ISSUE THREAD

**Issue by huangtianjia** [amzn/selling-partner-api-docs#1382]
When I tried to use the function of uploading invoices according to the official documents(UPLOAD_VAT_INVOICE), I got stuck in the third step and kept responding to "Access to the resource is forbidden". Is there any example of successful upload?

Documentation:https://github.com/amzn/selling-partner-api-docs/blob/7bfacb95fc9ca2b3335a79acd40846deb3e9a161/guides/use-case-guides/feed-api-upload-invoice-guide-2020-09-04.md

When I go to the third step of Create a feed, it returns 403.
{
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
}

Is there any good solution?

**Comment by diegocvazquez** [comment]
@huangtianjia 
Same here did you make any progress ? I am having the same issue

**Comment by kdfhhao** [comment]
When migrating from MWS to SP-API, the PII invoice information will be cancelled by default, and the developer profile needs to be re-edited to apply for tax invoices (limited) to generate tax invoices that comply with tax regulations. Tax remittance (limited) permissions.

**Comment by Johnny-Bee** [comment]
> When I tried to use the function of uploading invoices according to the official documents(UPLOAD_VAT_INVOICE), I got stuck in the third step and kept responding to "Access to the resource is forbidden". Is there any example of successful upload?
> 
> Documentation:https://github.com/amzn/selling-partner-api-docs/blob/7bfacb95fc9ca2b3335a79acd40846deb3e9a161/guides/use-case-guides/feed-api-upload-invoice-guide-2020-09-04.md
> 
> When I go to the third step of Create a feed, it returns 403. { "code": "Unauthorized", "message": "Access to the resource is forbidden", "details": "" }
> 
> Is there any good solution?

This feature seems to be available only in EU
https://developer-docs.amazon.com/sp-api/docs/tax-invoicing-restricted-role#feeds-reports-and-notifications
![image](https://user-images.githubusercontent.com/6368644/201957585-3b95bfd7-8160-4869-b5f9-d60b67362f5d.png)

**Comment by GJ-JG** [comment]
Hi all, as Johnny mentioned mentioned this report is only available in EU. You can cut a ticket to our dedicated technical support, or please reopen this ticket if needed.
