### ISSUE TITLE
Unable to request a Login with Amazon access token

### ISSUE THREAD

**Issue by vincentgu818** [amzn/selling-partner-api-docs#1390]
Hello,

I am making the following post request according to the documentation:

URL: https://api.amazon.com/auth/o2/token

Parameters:
grant_type=refresh_token
refresh_token=\<hidden\>
client_id=amzn1.application-oa2-client.d01204b9397946a79a1dbf8098ca7d26
client_secret=\<hidden\>

The response I receive:
{
    "error_index": "UQ9as9cdbgs5WknHyot3QwAAAAAAAAABdy-K8aXs9sRaXrOuG0Dz0KBdVPd-LJj9qoauc6waZZod-2VXbowAcYC5GlMIZ1tsu3rcxhKAFEylhs-8aCMG-hgVMbniC_ZdM84BvlLLd6kfcaiUBetaS2xNshg7JTlk-M_Hk-zeWZExd9x3NbM2hNaUKcC_taON8YwpVYO-tJi4yUNvcK0er2-Oy_nZHIv9Ux3G1VNwOfJIfGUPEGwKcw==",
    "error_description": "Malformed request",
    "error": "invalid_request"
}

I cannot figure out what I am doing wrong. Could anyone help me?

Thank you.

**Comment by sugatabagchi** [comment]
what is your content-type header ? should be -> Content-Type: application/x-www-form-urlencoded
did you try with postman?

Thanks
Sugata

**Comment by vincentgu818** [comment]
Thanks for the reply.

I am using Postman. I added the Content-Type header. I still get the same response.

<img width="1070" alt="Screen Shot 2021-09-14 at 1 28 25 PM" src="https://user-images.githubusercontent.com/45300653/133329177-09e81ce7-ed19-4010-b7bd-1c5d7e8dd014.png">
<img width="1071" alt="Screen Shot 2021-09-14 at 1 28 13 PM" src="https://user-images.githubusercontent.com/45300653/133329180-10d04cad-d086-48fe-a811-6cbcccaee118.png">

**Comment by sugatabagchi** [comment]
You are adding the values as query parameters .
try the below one - this will work -
![image](https://user-images.githubusercontent.com/38392004/133331911-f55a2ced-bfbb-4404-9e79-cc05716a8f35.png)

**Comment by sugatabagchi** [comment]
you can also put it in body -
![image](https://user-images.githubusercontent.com/38392004/133333932-256635e4-3848-44cc-9e8c-e7c07ba344a2.png)

**Comment by vincentgu818** [comment]
It did work.

Thank you very much for your help!
