### ISSUE TITLE
[BUG] putListingItem productType is not support

### ISSUE THREAD

**Issue by ocpear** [amzn/selling-partner-api-docs#1395]
Hi,
I need the correct JSON object to add new product to Amazon with listings-items-api operation "putListingItem".

In [https://sellercentral.amazon.com/listing/download?ref_=xx_download_tnav_upload](https://sellercentral.amazon.com/listing/download?ref_=xx_download_tnav_upload), I choose productType 'DRINKING CUP' (
In "Product Classifier", I choose "Home & Kitchen" > "Storage & Organization" > "Kitchen Storage & Organization" > "Thermoses" > "Insulated Beverage Containers" > "Tumblers")

I tried with example in this link ([https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md#tutorial-create-or-fully-update-a-listing](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md#tutorial-create-or-fully-update-a-listing)). 

So I call this API with body (attributes has more items but I only list few items) 
 {
        productType: 'DRINKING CUP',
        requirements: 'LISTING',
        attributes: {
            item_name: [{value: 'beer-glasses item'}],
            item_type: [{ value: 'beer-glasses' }],
            feed_product_type:[{value:"drinkingcup"}],
            item_sku:[{value:"ABC123-PIL-P"}],
      }

but response is {"sku":"ABC123-PIL-P","status":"INVALID","submissionId":"83df43016fc948d89d36bb5613e1ebf4","issues":[{"code":"4000003","message":"The Amazon product type specified is invalid or not supported.","severity":"ERROR"}]}

I has tried productType is 'DRINKING CUP' or 'DRINKING_CUP', requirements is 'LISTING', 'LISTING_PRODUCT_ONLY', 'LISTING_OFFER_ONLY' but result is the same.
I got productType in [https://sellercentral.amazon.com/listing/download?ref_=xx_download_tnav_upload](https://sellercentral.amazon.com/listing/download?ref_=xx_download_tnav_upload) , so I believe it is correct.
Thank you very much.

**Comment by enesgenc07** [comment]
noooooooooooooooo

**Comment by enesgenc07** [comment]
> Try `productType: 'PRODUCT'`,

Could you give me success request ? 

My request is : 

{"productType":"LUGGAGE","attributes":{"item_name":[{"value":"SWEATSHIRT","language_tag":"en_US","marketplace_id":"XXXXXX"}]}}

https://sellingpartnerapi-na.amazon.com/listings/2020-09-01/items/sellerid/sku?issueLocale=en_US&marketplaceIds=XXXXXX

The Amazon product type specified is invalid or not supported.

**Comment by uk-2** [comment]
Did you manage to resolve this ?

Got: {​​​​​​\"sku\":\"cc_24\",\"status\":\"INVALID\",\"submissionId\":\"ac1eab4367b94cbabc14aecd4113a26f\",\"issues\":[{​​​​​​\"code\":\"4000003\",\"message\":\"The Amazon product type specified is invalid or not supported.\",\"severity\":\"ERROR\"}​​​​​​]

Try to list 24 packs of Coco COla 

Tried the following types 

'Grocery' and FoodAndBeverages

**Comment by chapmanjw** [comment]
As noted in the [Listings API use-case guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2021-08-01.md) under considerations, the Listings APIs do not yet support all product types. 

You can use the search operation (without keywords) of the Product Type Definitions APIs for the latest set of supported product types: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md#tutorial-search-available-product-type-definitions.

When reading attributes data from both the Listings (SKU) and Catalog (ASIN) APIs for product types that have not yet launched, they will use the root `PRODUCT` product type for the attributes returned. The Product Type Definitions API will effectively do the same when retrieving a definition. If you request a product type not yet launched, the API will return the definition for the first product type in the hierarchy that does (which is `PRODUCT` for most cases). In the response payload, you will see which product type was returned. (For `VIDEO_DVD` you will likely see `PRODUCT` was returned instead).
