### ISSUE TITLE
Error when getting RDT for directFulFillment gerOrders Api

### ISSUE THREAD

**Issue by pucsdian** [amzn/selling-partner-api-docs#1396]
:- error for getting rdt for vendor-direct-fulfillment-orders-api

endpoint :- https://sellingpartnerapi-na.amazon.com/tokens/2021-03-01/restrictedDataToken
inHeader :- 
 x-amz-access-token = Access_token
 Authorization = "working and tested" Authorization format --tested for vendor-orders

JsonBody in request :- 
`{
	"restrictedResources": [
		{
			"method": "GET",
			"path": "/vendor/directFulfillment/orders/v1/purchaseOrders"
		}
	]
}
`
error :- 
`{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}`

we have access to direct-to-consumer role
is anything we have to add in this request

**Comment by galeblue** [comment]
I have the same problem。
During API debugging, when the value of `path` does not contain "/", the API returns a successful response (including **RDT**), but this **RDT** is of no use, request body:
```json
{
	"restrictedResources": [
		{
			"method": "GET",
			"path": "getOrders"
		}
	]
}
```

response body:
```json
{
	"expiresIn": 3600,
	"restrictedDataToken": "Atz.sprdt|AYABeEXf8U1s..."
}
```

 When the `path` is "/ orders / V0 / orders", the API returns a failure response. The HTTP code is 400. 
According to API references [https://github.com/amzn/selling-partner-api-docs/blob/main/references/tokens-api/tokens_2021-03-01.md#error-responses-and-schemas](url), it represents a parameter error. I didn't find any exceptions in the request body:
```json
{
	"restrictedResources": [
		{
			"method": "GET",
			"path": "/orders/v0/orders"
		}
	]
}
```

response body:
```json
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}
```
My code is based on `selling-partner-api-models\clients\sample-code\restricted-data-token-workflow.java`

**Comment by pucsdian** [comment]
so how can we resolve this?
i also tried something like sending restricted resources as a object rather
than list then it gives a restricted token which is no usable bcoz when i
tried call any restricted api using it then response showing 500 internal
server error

**Comment by pucsdian** [comment]
@galeblue  
after updating roles in app 
reauthorize your app and generate refresh token again then this newRefreshToken u can use for get RDT

**Comment by pucsdian** [comment]
[https://github.com/amzn/selling-partner-api-docs/issues/1315#issuecomment-910965861](https://github.com/amzn/selling-partner-api-docs/issues/1315#issuecomment-910965861)
check this
Solved Error when getting RDT

**Comment by galeblue** [comment]
@pucsdian Yes, it works, thank you.

**Comment by pucsdian** [comment]
@galeblue 
is your vendor-directFulfillment-orders api working after using Rdt
for mine only GetOrder is working
and GetOrders giving 500 internal server error

**Comment by galeblue** [comment]
@pucsdian I'm developing a seller app for a seller account,  and not currently authorized to access any vendor accounts.
When i invoke GetOrders of vendor-directFulfillment-orders, it returns:
```json
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}
```

But i happened to find that GetOrders (orders-api) returns 500 while the endpoint is sandbox（https://sandbox.sellingpartnerapi-na.amazon.com）. 
Your problem may be caused by parameters or configuration.

**Comment by diegocvazquez** [comment]
@pucsdian 
I am having the same i issue I have all roles enabled I am getting the error; Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]

What roles did you set to get the token working?

**Comment by diegocvazquez** [comment]
@pucsdian 
I tested again, reseted the Refresh Token and it is working, thanks for your help!

**Comment by jamieroyce** [comment]
I was approved for PII and successfully created an RDT and was using this for the past couple weeks with the orders-api but then realized I needed the vendor-orders-api as I need to acknowledge purchase orders as we are drop shipping. I tried changing the endpoint to vendorOrders and am getting this same error now: 

"Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]"

I already had the direct-to-consumer and all other roles except the tax ones active. 

Why would the vendor-orders-api not work when the orders-api is working?

**Comment by coder771** [comment]
> for Vendor this role is necessary Direct-to-consumer shipping. for seller this roles is necessary Direct-to-consumer shipping. Tax remittance. Tax invoicing.
> 
> if u using for Vendor don't add dataElements and if u using for seller try to get RDT without adding dataElements

are you sure Tax remittance.
Tax invoicing. are needed for seller?

**Comment by pucsdian** [comment]
yes, as per docs it's required for seller account

**Comment by coder771** [comment]
> yes, as per docs it's required for seller account

can you please send a link to it.

**Comment by pucsdian** [comment]
This is new official link to doc for token usage,

https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide

**Comment by coder771** [comment]
> This is new official link to doc for token usage, https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide

Thanks for getting back, they have asked us questions like below, we dont really do these tax related stuff. not sure if we could just say we need access to these roles to get PII information on the question?

![image](https://user-images.githubusercontent.com/17831597/158987659-10bec0e0-b7f1-4c02-b06e-f8bbc133f069.png)

**Comment by pucsdian** [comment]
you have to fill up it, they will review if they found anything wrong u
have to fill required things again
if everything is ok they will accept and then u need to regenerate refresh
token and use it
