### ISSUE TITLE
[BUG] Documentation - CatalogItems no longer returning anything in the 'Attributes' element

### ISSUE THREAD

**Issue by jamesp26** [amzn/selling-partner-api-docs#1397]
The catalogItems_2020-12-01 API has stopped returning anything in the 'Attributes' element for both Sellers and Vendors. We were seeing data in these a short while ago, but now if requested these just return an empty object:

"attributes":{}

Calling the API like - **_includedData=attributes,identifiers,images,productTypes,salesRanks,summaries,variations**

Vendors and sellers are brand registered, and if they aren't asking for attributes would fail anyway

Nothing has changed in the documentation about this, so can only presume there is either a bug or the docs haven't been updated with any additional rules.  Any ideas?

**Comment by steven-so** [comment]
@jamesp26  I just tried to make a request and I also got an empty object. Sorry I don't have any helpful information, but you are not alone.

**Comment by jamesp26** [comment]
Thanks for confirming steven-so. Anyone on the Amazon side know if functionality has changed here and if the documentation should be updated?

**Comment by jamesp26** [comment]
Just checked again and attributes are now back. Is there a status page where you log known issues?
