### ISSUE TITLE
[FEATURE] Documentation "Partner Network menu" missing link

### ISSUE THREAD

**Issue by nikolayganovski1** [amzn/selling-partner-api-docs#1398]
In the developer guide, where it says "In the Partner Network menu, click Develop Apps"
There is no such thing, I see only these 3 items in the Partner Network menu:
- Find apps and Services
- Explore Services
- Manage service requests

**Comment by Sus-Bierbaum** [comment]
I have the same problem

**Comment by stefnats** [comment]
Are you having a professional seller central account or are you an individual plan? A professional plan is required. This comes with monthly cost unfortunately.

**Comment by nikolayganovski1** [comment]
I got the pro plan and it now shows.
