### ISSUE TITLE
Amazon Support asked us to schedule call to address PII access, no response for 6 weeks

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#1406]
On June 29th, after a client of mine applied for PII access, we got a response that said the following:

> ...This will require a demo (e.g. through screen share) of your application’s data flows and further review of your data protection controls over Personally Identifiable Information (PII). Please continue to monitor this case as a member of our team will reach out to you to schedule this assessment.

We have now responded to the case 3 separate times to try to schedule the screen share that was requested, and haven't heard anything back. It has been over 6 weeks, and we're done coding, but can't actually deploy anything because we haven't been able to get a response on this case. This is for an established shipping provider that's trying to migrate to the SP API, as you have requested that everyone do this year.

The case number is 8635705461.

Generally speaking, it's incredibly (and in my opinion, excessively) hard to get access to PII. I'm confident that there would be far more excellent Partner Network apps if it wasn't so difficult to get PII access. I've never seen another service make it nearly this hard to get access to data that so many people need.

**Comment by jlevers** [comment]
@parvathm @ShivikaK could we get someone to look at this please?

**Comment by parvathm** [comment]
Hi @jlevers,

We have updated the concerned team to work on your case.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by jchavest13** [comment]
Hi @jlevers,

Please accept our apologies for the delay getting back to you on your case. We thank you for your patience while we work to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
