### ISSUE TITLE
Tax Remittance and Tax Invoicing  Roles not Showing in developer profile of vendor Central Account

### ISSUE THREAD

**Issue by pucsdian** [amzn/selling-partner-api-docs#1409]
Urgent!!!!!!!!!!!!!!!!!!
there are only 2 option
Direct-to-Consumer Shipping
Amazon Fulfillment
[https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-authorization-to-access-pii-for-bulk-orders](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-authorization-to-access-pii-for-bulk-orders)
here they mentioned this roles are required but they are not in developer profile
I'am not  able to call getOrders Api it always respond with 500 internal server error

**Comment by ShivikaK** [comment]
Hello @pucsdian 

Thank you for raising the issue.

The Vendor APIs only require Direct to Consumer Shipping role for PII access. None of the API operations in Vendor APIs require either of the Tax roles and hence they are not offered to 1p vendors in Vendor Central Developer Profile.

Please review below link for role descriptions -
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md 

If you are receiving 500 error for getOrders API, please open a support case with us to further investigate the error.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by pucsdian** [comment]
@ShivikaK  
Thank you mam
get-order API was working with RDT for to get info of single order but now it also giving 500 error
and from starting get-Orders API receiving  500 error
receiving 500 error for get-Orders API  and get-order API and Case id: 8979579791

**Comment by coder771** [comment]
@pucsdian was this issue resolved for you? I'm getting same error

**Comment by pucsdian** [comment]
@coder771 
issue resolved for me
I haven't made any changes on my side but it is working somehow
and make sure to regenerate refresh token again after making changes in roles in vendor central account

**Comment by pucsdian** [comment]
@coder771 
let me know here if u need any help regarding this

**Comment by coder771** [comment]
@ShivikaK is Tax remittance.
Tax invoicing. roles needed to access PII Data in seller or vendor api?
