### ISSUE TITLE
/shipping/v1/shipments 

### ISSUE THREAD

**Issue by tao5340** [amzn/selling-partner-api-docs#1410]
**Request parameters**:
{"clientReferenceId":"PK12109170035467","containers":[{"containerReferenceId":"[406-8342005-5629112]","containerType":"PACKAGE","dimensions":{"height":1.50,"length":16.00,"unit":"CM","width":11.00},"items":[{"quantity":1,"title":"adapter","unitPrice":{"unit":"USD","value":8.57},"unitWeight":{"unit":"kg","value":1}}],"value":{"unit":"USD","value":8.57},"weight":{"unit":"kg","value":1}}],"shipFrom":{"addressLine1":"5/F,Diguang digital technology park,Guangming District","addressLine2":null,"addressLine3":null,"city":"Shenzhen","copyEmails":null,"countryCode":"CN","email":null,"name":"Zhang Yunlu","phoneNumber":"18098956715","postalCode":"518132","stateOrRegion":"Guangdong"},"shipTo":{"addressLine1":"House number b-1/81 kaler niwas guru tegh bahadur nagar","addressLine2":"Banga road nawanshahr","addressLine3":null,"city":"NAWANSHAHR","copyEmails":null,"countryCode":"IN","email":null,"name":"Harry Kaler","phoneNumber":"8872275007","postalCode":"144514","stateOrRegion":"PUNJAB"}}
**Response**：
{
    "errors": [
        {
            "code": "InternalFailure",
            "message": "We encountered an internal error. Please try again.",
            "details": ""
        }
    ]
}

**Comment by pucsdian** [comment]
@tao5340 
are u sending request to sandbox or production

**Comment by tao5340** [comment]
Yes, this is my request Id 00F07d82-5C66-4779-9F08-68FA85d71E70,
