### ISSUE TITLE
Access to resources is denied

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#1413]
Hello, I want to make a request to sp API but get Access to resources is denied error. I have done everything right and still getting the error.

```
CustomError: Access to requested resource is denied.
    at SellingPartner.callAPI (C:\Users\Administrator\Desktop\amazonbd\back-end\amazonbd\node_modules\amazon-sp-api\lib\SellingPartner.js:573:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'Unauthorized',
  details: '',
  type: 'error'
}
```

**Comment by ShivikaK** [comment]
Hello @Javadebi 

Thank you for raising this issue.

Please refer to our FAQs for further assistance on access denied error -
https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs
(Why am I getting Unauthorized - Access Denied error (403 error code) for my API request after completing registration successfully?)

If error still persists, please open a support case with us for further investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by abuzuhri** [comment]
> Hello @Javadebi
> 
> Thank you for raising this issue.
> 
> Please refer to our FAQs for further assistance on access denied error -
> https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs
> (Why am I getting Unauthorized - Access Denied error (403 error code) for my API request after completing registration successfully?)
> 
> If error still persists, please open a support case with us for further investigation.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

> Hello, I want to make a request to sp API but get Access to resources is denied error. I have done everything right and still getting the error.
> 
> ```
> CustomError: Access to requested resource is denied.
>     at SellingPartner.callAPI (C:\Users\Administrator\Desktop\amazonbd\back-end\amazonbd\node_modules\amazon-sp-api\lib\SellingPartner.js:573:13)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
>   code: 'Unauthorized',
>   details: '',
>   type: 'error'
> }
> ```

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by Javadebi** [comment]
@abuzuhri Thank you but I'm using JS.
