### ISSUE TITLE
Add Category XSDs to selling-partner-api-docs

### ISSUE THREAD

**Issue by ibond84** [amzn/selling-partner-api-docs#1415]
> For more information about Category XSDs, see "XSDs" in the Seller Central Help for your marketplace.

The list of XSDs is empty in  the Seller Central Help. It is a urgent problem to search in the internets these category XSDs... Please add the actual   Category XSDs here in github.

**Comment by jenilew** [comment]
Hello ibond84, 

Thank you for the feedback. Is this in relation to a specific announcement? If so, which announcement are you referring to? 

In general, XSDs can be located at [https://sellercentral.amazon.com/gp/help/G1611](https://sellercentral.amazon.com/gp/help/G1611).

Please note that each XSD is a downloadable file. If your browser has a pop-up blocker, you will need to disable it for the page to successfully download the XSD. You will also need a text editor (such as Notepad) to open and view the file once downloaded. 

Best regards, 

Jeniffer
Selling Partner API Services team

**Comment by minifreak** [comment]
Hi Jeniffer,

Apart of what ibond84 says, lots of XSDs listed in https://sellercentral.amazon.es/gp/help/help.html?itemID=1611&language=en_ES&ref=ag_1611_cont_69042 have references to lots of missing XSDs. A clear example of this is the Product Feed. This is a big problem when trying to generate (java) classes from these schemas (using jaxb-xjc for example). The only thing I could find in that regard is this https://github.com/dmichael/amazon-mws/tree/master/examples/xsd which is completely outdated and unmantained.

Without all the schemas is impossible to implement properly the Selling Partners Feeds API

**Comment by jenilew** [comment]
Hi minifreak,

I was able to download the Product Feed XSD this morning without issue from https://sellercentral.amazon.com/gp/help/help.html?itemID=1611&language=en_ES&ref=ag_1611_cont_69042. 

I'm not disputing that you're (or others are) having challenges. I am trying to understand those challenges. 

It may be a faster path to open a support case when you are having trouble with downloading an XSD. That allows Amazon to report on the number of times it has failed and prioritize putting a better solution in place. 

I will share the feedback in this thread with the Amazon team responsible for publishing and maintaining the XSDs and we'll look into the issue. 

If you can provide more specifics of which XSDs you're seeing consistently fail or be outdated; that will be helpful. 

Thank you,

Jeniffer
Selling Partner API Services team

**Comment by minifreak** [comment]
Hi Jenniffer,

Thanks for your response. I probably didn't make myself clear. All the links listed in https://sellercentral.amazon.com/gp/help/help.html?itemID=1611&language=en_ES&ref=ag_1611_cont_69042 work.  What I meant is that most XSDs referenced within them are missing. The product feed is a clear example of what I'm saying. Just try to open it and you'll see lots of:

```
<xsd:include schemaLocation="ClothingAccessories.xsd"/>
<xsd:include schemaLocation="ProductClothing.xsd"/>
....
```
All those specific Product Feed schemas are missing. Only place I could find an outdated version of them (some not even exist) are from the link I posted above.

Any help will be really appreciated. Thanks in advance.

**Comment by vaidas-lungis** [comment]
☝️ I experienced same behavoir. Its very difficult to track changes of the XSDs

**Comment by ibond84** [comment]
>In general, XSDs can be located at https://sellercentral.amazon.com/gp/help/G1611.

There was an error displaying this topic. ..

**Comment by ibond84** [comment]
https://sellercentral.amazon.de/gp/help/help.html?itemID=G1611
 Produktkategorie-XSDs (Category XSD)

Diese Tabelle enthält Links zu XSDs für die Produktkategorie-Feeds. (This table contains the XSDs)

But the table is empty!
