### ISSUE TITLE
[FEATURE] /vendor/directFulfillment/orders/v1/purchaseOrders/{purchaseOrderNumber} How to get authorization

### ISSUE THREAD

**Issue by mjb1ifkr** [amzn/selling-partner-api-docs#1417]
How to get authorization

I requested this interface (FBM) order, but an error was reported
{
   "errors": [
     {
       "message": "Access to requested resource is denied.",
      "code": "Unauthorized",
      "details": ""
     }
   ]
}

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

Please refer to our FAQ regarding access denied errors -

https://github.com/amzn/selling-partner-api-docs/wiki/SP-API-for-Vendors---Error-FAQs
(Why am I getting an "403: Unauthorized - Access Denied" error for my API request after completing registration successfully?)

If error persists post troubleshooting via above FAQ, please open a support case with us for further investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support
