### ISSUE TITLE
 Maybe this can help solve the "403 Forbidden" problem

### ISSUE THREAD

**Issue by shuaiys** [amzn/selling-partner-api-docs#142]
I have seen that many developers have encountered the '403 Forbidden' problem. To sum up, IAM is basically not bound to the application. After the application is created, the ARN Role cannot be modified, so you need to confirm to create the IAM first.
in conclusion:
1. If the application is in draft status, after completing self-authorization, you can only call yourself.
2. Confirm that the IAM is created correctly.
3. Confirm that the created application is bound to the Role created in step 2.

Hope these can help you.

**Comment by gasper-vrhovsek** [comment]
We also had 403 issues that went away after reconfiguring the IAM. With self authorization we can call every api, except for the AuthorizationApi (which is a grantless opreation and actually doesn't need the refresh token). But now we get 
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Developer ID 35XXXXXXXXXX is not associated with the application id.",
      "details": ""
    }
  ]
}
```
When trying to authorize with credentials from a previously MWS approved seller partner. Do you think this is also somehow linked to the IAM configuration? Our application is published (not in draft), we have previously MWS authorized partners, but we do not have any authorized with the new LWA flow (this is still in dev & testing process).

Best regards,
Gasper

**Comment by shuaiys** [comment]
If you can call the api in the draft state, have you tried to re-authorize and then call the api in the production state? If you have gone through these processes and the call fails, I am sorry that I cannot help you temporarily. If you solve it with this problem, I would be happy to listen to your suggestions.

**Comment by gasper-vrhovsek** [comment]
We reauthorized a couple of times now. It even doesn't matter what `mwsAuthToken` i input into the `authApi.getAuthorizationCodeAsync` call, the error response is always the same.

**Comment by BeeBee234** [comment]
Howdy Hi,

FYI, I was getting "403: Forbidden" responses even though my credentials were set up properly and in the right place.

C# users can test the following sandbox calls using the example code in https://github.com/amzn/selling-partner-api-models/issues/31 to confirm their credentials:

        var resource = $"/orders/v0/orders";
        IRestRequest restRequest = new RestRequest(resource, Method.GET);
        restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
        restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);

or

    var resource = $"/vendor/orders/v1/purchaseOrders";
    IRestRequest restRequest = new RestRequest(resource, Method.GET);
    restRequest.AddParameter("createdAfter", "2019-08-20", ParameterType.QueryString);
    restRequest.AddParameter("createdBefore", "2019-09-21", ParameterType.QueryString);

The "Access Denied' and "Internal Server Error" messages returned from sandbox calls appear to be bogus as well.

Good luck and spread good cheer,

Brian

**Comment by ShivikaK** [comment]
Hi @BeeBee234 ,

We will need to work with you via a support case to troubleshoot and resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support
