### ISSUE TITLE
sellercentral.amazon.com/apps/authorize/confirm/ In website authorization flow is broken

### ISSUE THREAD

**Issue by yuri-lonesomelabs** [amzn/selling-partner-api-docs#1420]
When navigating to https://sellercentral.amazon.com/apps/authorize/confirm/amzn1.sp.solution.xxxxx as part of the web authorization flow (confirm -> sign up -> apps/authorize/confirm) getting a broken page. The page looks like this:
![image](https://user-images.githubusercontent.com/85734171/134012298-969b228e-3560-487b-8c93-03f7d3b2a023.png)

The console looks like this:

![image](https://user-images.githubusercontent.com/85734171/134011962-a70bc5ea-f122-46db-a8a3-f11587b32776.png)

Is any one else experiencing this?

**Comment by IgniteMosquito** [comment]
I had this issue with Chrome browser only. Switched to Firefox and it worked. I was told by our team, that Chrome started working again - maybe they updated something. Do you have the latest Chrome version?

**Comment by yuri-lonesomelabs** [comment]
@IgniteMosquito it's working now. Thanks

**Comment by yuri-lonesomelabs** [comment]
This issue is back! Anyone else is experiencing this?
