### ISSUE TITLE
[BUG] Documentation：getShipments

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-docs#1429]
When calling /fba/inbound/v0/shipments using a date range, I get an error that seems wrong.

My call is:

GET /fba/inbound/v0/shipments?LastUpdatedAfter=2020-10-25T14%3A18%3A49Z&LastUpdatedBefore=2020-12-24T13%3A18%3A49Z&MarketplaceId=ATVPDKIKX0DER&QueryType=DATE_RANGE

and response is:

"code": "InvalidInput",
"message": "At least one of ShipmentStatusList and ShipmentIdList must be provided",
"details": ""
Considering I set QueryType=DATE_RANGE, it should use LastUpdatedAfter and LastUpdatedBefore and not ShipmentStatusList or ShipmentIdList.

I wouldn't expect a bug like this, so is it me doing something wrong ?

**Comment by cpiggott** [comment]
You need to also pass in the type of shipments that you are expecting to get back. You can see a list of the statuses here: [Status List](https://github.com/amzn/selling-partner-api-docs/blob/a56f4fac467c0e251b9b89ae39ba7c12be65e776/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatuslist)

**Comment by yan15195755798** [comment]
> 您还需要传入您希望退回的货件类型。您可以在此处查看[状态列表](https://github.com/amzn/selling-partner-api-docs/blob/a56f4fac467c0e251b9b89ae39ba7c12be65e776/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatuslist)：[状态列表](https://github.com/amzn/selling-partner-api-docs/blob/a56f4fac467c0e251b9b89ae39ba7c12be65e776/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatuslist)

If you bring the status，DATE_RANGE will be invalid
