### ISSUE TITLE
Can not exchange LWA code for token with Java generated CL

### ISSUE THREAD

**Issue by gasper-vrhovsek** [amzn/selling-partner-api-docs#143]
Hi,

i am trying to exchange the LWA code i get from a seller following [Step 3. Amazon sends you the authorization information](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-amazon-sends-you-the-authorization-information), but don't see anything in the SP-API that could do this. The closest is the [authorization-api-model](https://github.com/amzn/selling-partner-api-models/tree/main/models/authorization-api-model), but that accepts a MWS token and is causing [other issues](https://github.com/amzn/selling-partner-api-docs/issues/140).

Is this not yet supported by the selling partner JAVA api library, and should we do the requests manually?

Best regards,
Gasper

**Comment by intellifox-hq** [comment]
Hi @gasper-vrhovsek 

Is this the operation you want to do?

```js
const get_new_token = async (refresh_token) => {
  try {
    const lwa = 'https://api.amazon.com/auth/o2/token'

    const lwa_response = await axios.post(lwa, {
      grant_type: 'refresh_token',// 	The type of access grant requested. Must be authorization_code.
      refresh_token,// 	The LWA authorization code that you received in Step 3. Amazon sends you the authorization information.
      client_id,// 	Part of your LWA credentials. To get this value, see Viewing your developer information.
      client_secret,// 	Part of your LWA credentials. To get this value, see Viewing your developer information.
    })

    return lwa_response.data.access_token
  } catch (e) {
    console.log(e)
    throw e
  }
}
```

**Comment by gasper-vrhovsek** [comment]
Hi @intellifox-hq 

yes this is the one. I guess i'll have to do it manually, but i was expecting the generated API to support it, since the tutorial mentions the api supporting hybrid apps. Either way, it's not too different from the getAuthorizationCode in the api, except that one works with the MWS token.

Best,
Gasper
