### ISSUE TITLE
Messaging API available for Vendor Central (Responding to Reviews)

### ISSUE THREAD

**Issue by vrk7bp** [amzn/selling-partner-api-docs#1434]
I was wondering if the Selling Partner API for Messaging is available for Vendor Central users as well as Seller Central users?Specifically if a vendor wanted to use the createNegativeFeedbackRemoval to try to resolve negative reviews.

Overall what I'm trying to do is make it easier for Vendor's to respond to negative reviews via Buyer-Seller Messaging, using this workflow: https://sellercentral.amazon.com/gp/help/external/help.html?itemID=VAL8YDBQ8NRZNS4&language=en_US&ref=efph_VAL8YDBQ8NRZNS4_cont_XATYDG72KXPG7EM.

Is this possible via the Selling Partner API? And if so, is the createNegativeFeedbackRemoval the right endpoint to follow for this?

In general given that the Selling Partner API covers both Seller Central and Vendor Central, would be great to have in the documentation which endpoints/methods work for which type of accounts.

**Comment by ShivikaK** [comment]
Hello @vrk7bp 

Thank you for raising this issue.

Currently we do not provide Messaging API for Vendors, but we have provided your valued feedback to our Product team.

Currently we only support the Retail and Direct Fulfillment for Vendors along with the vendor analytics reports released recently.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by vrk7bp** [comment]
Thanks @ShivikaK, I appreciate the response. Just for my full understanding, is there any way for a Vendor that's part of Vendor Central to respond to reviews or reach out to buyers? Even if not through the API?
