### ISSUE TITLE
Amazon rest API to create product for my seller central

### ISSUE THREAD

**Issue by chprasad92** [amzn/selling-partner-api-docs#1438]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/1437

<div type='discussions-op-text'>

<sup>Originally posted by **chprasad92** September 24, 2021</sup>
Hello, 

I've been trying to find amazon rest API from which we can create Product and update product.

If anyone can help me with any documentation that would be real help. 

Regards, 
Chandan </div>

**Comment by rugved1991** [comment]
Hi @chprasad92,

Check out the new Selling Partner API on AWS QuickStart for a quick setup of SP APIs using Python Lambda. The IAM setup is automated so no need to worry about the setup. Just follow the instructions on the deployment guide of the QuickStart and you will be up and running in no time.

https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

Feel free to open issues or provide feedback on the issues page of the QuickStart.

For creating and updating products, you can use the Product Definitions API and Listings API.
https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-type-definitions-api/definitionsProductTypes_2020-09-01.md
https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md

For any product which is not listed in the Product type definitions API response for sellers, you can use the Feeds API.
https://github.com/amzn/selling-partner-api-docs/tree/main/references/feeds-api
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md

Thanks,
Rugved
Solutions Architect, SP API.
