### ISSUE TITLE
how create POST request

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#144]
Hello,
I try to make a POST request via postman or PHP, but I can't find the solution
i tried sending in json and x-www-form-urlencoded, but nothing works

Postman body x-www-form-urlencoded : 
![image](https://user-images.githubusercontent.com/46819385/100226730-6c750780-2f20-11eb-8215-e53c85d61e37.png)
 
and in JSON : 
![image](https://user-images.githubusercontent.com/46819385/100226781-7f87d780-2f20-11eb-98bb-54add91121d6.png)

Response : 
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}

have I formed the body incorrectly? I have the same answer in PHP

**Comment by hashhesh** [comment]
Hi guys
@poeily 
@AteqEjaz 
, did anyone got any solution or workaround??, I am facing the same issue with createReport as well
Thanks
