### ISSUE TITLE
[BUG] I called the api /orders/v0/orders/{orderId}/address but error response the code ​404

### ISSUE THREAD

**Issue by 348786639** [amzn/selling-partner-api-docs#1445]
I called the api /orders/v0/orders/{orderId}/address but error response the code 404 ?

Why response 404

orderId：113-9940460-2101826
Marketplace：ATVPDKIKX0DER
Timestamp：1632708010165
requestId：904404e2-0ff1-4477-a763-240c5b20aac1

Response：
code: 404
message : not found
header: {Server=[nginx], Date=[Mon, 27 Sep 2021 02:00:10 GMT], Content-Length=[0], Connection=[keep-alive], OkHttp-Sent-Millis=[1632708010165], OkHttp-Received-Millis=[1632708010786]}
responseBody:azon api service error!

**Comment by yuri-lonesomelabs** [comment]
Are you able to retrieve the order at `/orders/v0/orders/{orderId}` (without the address)?
