### ISSUE TITLE
get orders  list not data ,but  my  Sellers in the background has orders

### ISSUE THREAD

**Issue by dingzheyan** [amzn/selling-partner-api-docs#145]
Get URL and params:
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?LastUpdatedAfter=2020-10-20T17:30:08&LastUpdatedBefore=2020-11-25T13:16:14Z&MarketplaceIds=[A1F83G8C2ARO7P]

**Comment by dingzheyan** [comment]
it return 
{
  "payload": {
                  "LastUpdatedBefore": "2020-11-25T13:16:14Z",
                          "Orders" : [
            ]
      }
}

as a matter of fact ,my uk has orders 
![Uploading image.png…]()

**Comment by BeeBee234** [comment]
Hello,

For C# users the following sandbox call works (if your credentials are setup properly), using the example code in https://github.com/amzn/selling-partner-api-models/issues/31 :

        var resource = $"/orders/v0/orders";
        IRestRequest restRequest = new RestRequest(resource, Method.GET);
        restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
        restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);

Good luck and have fun,

Brian

**Comment by parvathm** [comment]
Hi @dingzheyan,

Sorry for the delay. Are you able to get orders in your response now?  Please open a support case if you still have issues downloading orders.

Thanks,
Parvathm,
Selling Partner API Developer Support.
