### ISSUE TITLE
sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

### ISSUE THREAD

**Issue by NarutoJxt** [amzn/selling-partner-api-docs#1454]
**Describe the bug**
  I has followed the docs [sp api docs](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-5-add-an-aws-security-token-service-policy-to-your-iam-user) to finish folloing steps:
  1. Registering as a developer
  2. Creating and configuring IAM policies and entities
  3. Registering your application
      but in the step,When I choose the App Type,the choice is only SP API like this:
![飞书20210929-140538](https://user-images.githubusercontent.com/48872068/135212226-c622300a-7d75-421a-bbf2-fb043fc29650.jpg)
     Amd at last, I ignore that.
  4. I also authorize this app and get the refresh token
  .I get all  things,such as role arn,access_sexret,acsess_secret_key,refresh_tolen,iam,client_id,client_secret. But When I use these info to access sp api with python,I get this error. 

# Code
```

from sp_api.api import VendorDirectFulfillmentShipping
from sp_api.base import Marketplaces
credentials=dict(
        refresh_token = "xxxxxxxxx",
        lwa_app_id='xxxxxxxxx',
        lwa_client_secret='xxxxxx',
        aws_secret_key='xxxxxxxxxx',
        aws_access_key='xxxxxxxxxx',
        role_arn='xxxxxxxx',
)
orders = VendorDirectFulfillmentShipping(credentials=credentials,marketplace=Marketplaces.JP).get_shipping_label(purchaseOrderNumber="xxxxxx")
print(orders)
```

# Error
```
/Users/lx/PycharmProjects/AWS/venv/bin/python /Users/lx/PycharmProjects/AWS/SpApi/test.py
Traceback (most recent call last):
  File "/Users/lx/PycharmProjects/AWS/SpApi/test.py", line 13, in <module>
    orders = VendorDirectFulfillmentShipping(credentials=credentials,marketplace=Marketplaces.JP).get_shipping_label(purchaseOrderNumber="65ZLK6SH")
  File "/Users/lx/PycharmProjects/AWS/venv/lib/python3.7/site-packages/sp_api/base/helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "/Users/lx/PycharmProjects/AWS/venv/lib/python3.7/site-packages/sp_api/api/vendor_direct_fulfillment_shipping/vendor_direct_fulfillment_shipping.py", line 106, in get_shipping_label
    return self._request(fill_query_params(kwargs.pop('path'), purchaseOrderNumber), params=kwargs)
  File "/Users/lx/PycharmProjects/AWS/venv/lib/python3.7/site-packages/sp_api/base/client.py", line 105, in _request
    return self._check_response(res)
  File "/Users/lx/PycharmProjects/AWS/venv/lib/python3.7/site-packages/sp_api/base/client.py", line 112, in _check_response
    raise exception(error)
sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]
```

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

To access Direct Fulfillment Vendor API, you are required to have access to the restricted Direct-To-Consumer shipping role. You will need to resubmit your Developer Profile to request access to the restricted role.

Additionally if you are creating a private vendor application via Vendor Central, you will only be shown option for SP API. 

MWS does not support Vendor APIs integration, it is only possible via SP API and it is only available in Seller Central for developers who were approved for MWS prior to SP API launch.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by paulamascot** [comment]
Hello, 
I have this same error when trying to get Vendor Orders information through the SP API for the Marketplaces: IT, SE and NL.

I was able to get Vendor Orders information normally for UK, DE and ES. 

Does anyone know what is happening with IT, SE and NL? 

Thank you.

**Comment by baran-n** [comment]
Hello,

I am also getting the same error message.

If you solved the problem, could you tell me how?

Thank you.
