### ISSUE TITLE
Product Feed submission stuck in IN_PROGRESS for last 48 hrs..

### ISSUE THREAD

**Issue by SouravPal95** [amzn/selling-partner-api-docs#1455]
I was using the feeds API to submit a json listings feed payload. Usually the feed processing report gets generated quite fast but on this particular occassion it has been stuck for 48 hours in IN_PROGRESS stage without any developments. I have reached out to developer support and they have been least helpful..... case id: 7377409152.

**Comment by stefnats** [comment]
Hey,

I experience this too sometimes.

If this happens regularly, you need to upload smaller feeds and divide into chunks. 
If this happens once, you need to contact *seller* support and tell them to redirect to the feed department. Tell them see stuck feed / batch ID and that you wish to cancel.
If it is in *SUBMITTED* state, you can cancel via API, but not in *IN_PROGRESS* state.

**Comment by SouravPal95** [comment]
i had information on only two products

**Comment by lemnisk8** [comment]
Hi,
Did you manage get any resolution for this?
My feed has been IN_QUEUE for more than 5 days. 
Cancelling and resubmitted doesn't seem to be helping too...

**Comment by SouravPal95** [comment]
yes ... but only through the help of seller support. They removed the feeds stuck in the pipeline and shared a document with us according to which feeds of  a particular type....say... products feed....should be in counts of one per 12 mins....no more than that...

**Comment by iamricks** [comment]
This has been happening for the last 1.5 years for me, lately i have feeds where only some of the products get processed and the others don't without any feedback because the feed submission never finishes processing. I have also been experiencing very long processing times, it will take hours just to upload a few products.

**Comment by KajdeMunter** [comment]
This discussion helped fix the stuck IN_PROGRESS feeds for me: https://github.com/amzn/selling-partner-api-docs/discussions/1918
