### ISSUE TITLE
Is it possible to reuse the Amazon SP-API developer profile in another sales channel?

### ISSUE THREAD

**Issue by ykuni-software-developer** [amzn/selling-partner-api-docs#1472]
Our developer profile was approved for Amazon SP-API in one of our sales channels. Our plan is to use the approved developer profile for another sales channel when we try to register another application for that sales channel. However, from that sales channel, it asked us to create a developer profile first before registering an application.

Is it possible to reuse an approved Amazon SP-API developer profile from one sales channel to another channel?

**Comment by ykuni-software-developer** [comment]
I think I mean both marketplace or region. For example, our developer profile is approved for Brand X so we initially registered our application for that brand or store. We also have brand Y which is another store different from Brand X. We want Brand Y to use the same application we developed for Brand X. However, the application only currently pulls data for Brand X and not Brand Y. We want to pull both data for Brand X and Brand Y.  Is there a way to do that? Would authorizing the application for Brand Y help?
It currently pulls data from the North American Region and not other regions. Upon reviewing our developer application use case section, we only check the North American region and not the other regions. Is there any way to add other regions to access?

**Comment by kpconnell** [comment]
it is application id / seller id pair specific.  I don't believe this is
documented but this is how it works (and if you think about it, this is
pretty much the only sensible way for them to implement it..).
