### ISSUE TITLE
GET /catalog/2020-12-01/items/{asin}

### ISSUE THREAD

**Issue by tzumbo** [amzn/selling-partner-api-docs#1474]
Hi,
for some ASIN and when, include data contains 'images' the response is the following error:

**Invalid value 'PT10' for 'variant', must be one of 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06', 'PT07', 'PT08', 'SWCH'"**

**Comment by chapmanjw** [comment]
This issue was addressed as noted here: https://github.com/amzn/selling-partner-api-docs/issues/2248
