### ISSUE TITLE
[BUG] Documentation "SP API+ MWS" option missing on Register Screen

### ISSUE THREAD

**Issue by volkankorkmaz** [amzn/selling-partner-api-docs#1476]
While registering the new app client on Seller Central, the "SP API+ MWS" option does not appear in the API Type options. 

Is this normal?

![image](https://user-images.githubusercontent.com/4518416/136181994-2d48f813-6bb1-4631-bc3d-3ae25db3f282.png)

I don't see Full MWS Access and MWS Authorization Token for my app! My App name is JIT...

![image](https://user-images.githubusercontent.com/4518416/136182714-00423039-6308-4918-a408-75aea75ab7a4.png)

**Comment by max0783** [comment]
Same issue! Is it deprecated already?
