### ISSUE TITLE
getOrderMetrics limit clarification

### ISSUE THREAD

**Issue by sherlock270** [amzn/selling-partner-api-docs#148]
[Documentation](https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md#getordermetrics) states that the query parameter `marketplaceIds` is a list of marketplace identifiers, and the type is listed as < string > array. However, when testing the operation I have found that there appears to be a limit of one marketplace id. Is this correct?

**Comment by parvathm** [comment]
Hi @sherlock270 

According to the documentation MarketplaceId's should accept list of values. If that is not what you are seeing can you please open a support case  (https://developer.amazonservices.com/support) so we can pursue the investigation.

Thanks,
Parvathm,
Selling Partner API Support.

**Comment by sherlock270** [comment]
Thank you @parvathm for the quick response. I have opened a support case (case id: 7660831741)

**Comment by discover59** [comment]
Is there any api to get other order metrics such as sessions in business report?

**Comment by sntgprz** [comment]
Hello.
Has this been solved?
I'm having a similar problem in the Reports API calling the createReports operation. I get an "invalid input" response.

API call:

`POST https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports
{
  "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
  "marketplaceIds": [
    "ATVPDKIKX0DER"
  ]
}`

Response:
`{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}`

Is the problem marketplace ID?

**Comment by ShivikaK** [comment]
Hello @sherlock270 

Your case 7660831741 has been resolved with the resolution that the operation doesn't support multiple marketplace id's and only has a limit of 1. We have noted your feedback for updating the documentation regarding this.

Please confirm that your issue is fixed.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
