### ISSUE TITLE
[BUG] No API for fetching Product listing

### ISSUE THREAD

**Issue by IamSantosh** [amzn/selling-partner-api-docs#1482]
I'm using SP-API and I've successfully obtained the LWA token for the user and also integrated the refresh token part. I've also been able to hit the 'GET' API of Selling Partner and received success response. 

**Describe the bug**
I want to fetch all the listings of the users but I didn't find any listing API using which I can fetch all his listing. 

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md

**Description of what the documentation should say**
There should be a Listing API using which we can fetch all product listings for the users.

**Comment by stefnats** [comment]
Alright, I understand. So when you fix #1481 this issue is also solved. I posted my 2 cents there.
