### ISSUE TITLE
putListingsItem api with 4000001 error code

### ISSUE THREAD

**Issue by jia333** [amzn/selling-partner-api-docs#1491]
i tried with https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md#putlistingsitem
my request body is 
{
	"productType": "LUGGAGE",
	"requirements": "LISTING",
	"attributes": {
		"brand": [{
			"marketplace_id": "ATVPDKIKX0DER",
			"language_tag": "en_US",
			"value": "ADIDAS"
		}]
	}
}
and i got a response like this
{
	"issues": [{
		"attributeName": "brand",
		"code": "4000001",
		"message": "The provided value for 'brand' is invalid.",
		"severity": "ERROR"
	}],
	"sku": "testsku",
	"status": "INVALID",
	"submissionId": "51af1b3d10814dc691e6eba36376ac53"
}
so i want to know what's the valid value for 'brand'?

**Comment by kmodlesk** [comment]
@jia333 were you able to figure this out? I have the same error

**Comment by shirushi-dev** [comment]
me too

**Comment by jamieroyce** [comment]
me too too

**Comment by chapmanjw** [comment]
@jamieroyce @shirushi-dev @kmodlesk @jia333,

To troubleshoot these specific types of errors, can you provide more recent submission ids for us to investigate? 

Given the public forum, we can provide some general information about the causes. However, for more specific details related to the sellers/vendors + SKUs these apply to, contacting Developer Support would be the best path forward: https://developer.amazonservices.com/support
