### ISSUE TITLE
[BUG] Hybrid app Japanese marketplace authorization is not available

### ISSUE THREAD

**Issue by fengzidk** [amzn/selling-partner-api-docs#1494]
The seller cosent that the authorization callback information contains the following fields:

- state
- selling_partner_id
- mws_auth_token
- spapi_oauth_code

When i try to use mws_auth_token,Amazon returned an error message:
`
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "No MWS Authorization exists",
      "details": ""
    }
  ]
}
`

**this is amazon bug?**

**Comment by chespinoza** [comment]
@fengzidk I'm having the same issue I wonder if you could solve this.
