### ISSUE TITLE
[BUG] orders.getOrderItemsBuyerInfo empty BuyerCustomizedInfoDetail CustomizedURL

### ISSUE THREAD

**Issue by lmuestak** [amzn/selling-partner-api-docs#1496]
**Describe the bug**
No matter which which method orders.getOrderItemsBuyerInfo or getOrderItems the BuyerInfo.CustomizedURL is always empty.
I've some orders in which definitely this information is set.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderitembuyerinfolist

**Description of what the documentation currently says**
API result is empty

**Description of what the documentation should say**
API result should provide the file url in BuyerCustomizedInfoDetail.CustomizedURL for download

**Screenshots**
![image](https://user-images.githubusercontent.com/3002593/136836512-4318371a-28d0-40c7-9f20-8025fdcc83ec.png)

**Additional context**

**Comment by lmuestak** [comment]
Hi Bowserlord,

excuse me, but what is a RDT?

Best regards

**Comment by MisterDruck** [comment]
As far as I know you need an RDT.
"You can get an RDT that provides authorization to access Personally Identifiable Information (PII) "
Possible that customized product information are "PII"?

Same as for buyer information with name and address.

**Comment by thai101795** [comment]
I am also having the same problem.
Is there any solution now?

**Comment by jimiscott** [comment]
Why is the customise URL deemed restricted data? Insane!
