### ISSUE TITLE
Authorization of access to PII information to get shipping und billing address information.

### ISSUE THREAD

**Issue by trustindialog** [amzn/selling-partner-api-docs#1499]
Hi, 

we have serious problems in creating an account in order to access billing and shipping informations. 

The system we are currently using still uses the old MWS-access and will not migrate this to the new API. On October 26th they will no longer have access to personal data, so will have no chance to proccess orders ... :-(

We opened a case (**7402495902**) but the authorizattion is rejected. 
@jchavest13 ... Is there any chance to get this authorization?

Any suggestions?

Regards,

Andreas

**Comment by Johnny99211** [comment]
Any update here? I have the exact same problem but I've already got my PII access but can only see a shipping address...
