### ISSUE TITLE
Selling Partner API is not yet live

### ISSUE THREAD

**Issue by seanevan** [amzn/selling-partner-api-docs#15]
Hi all,

I am writing to clear up some confusion that is reflected in recent GitHub issues. As mentioned in our Hello, World! issue, Selling Partner API is not yet generally available. This means that unless you have been part of our private beta you will not be able to call the API just yet.

Having said that, please watch these repositories - we will have news very soon in that regard!

Best regards,
Sean Evans
Manager, Support Engineering

**Comment by misterakko** [comment]
Any chance to become part of the beta team now (or maybe for the future developments of the system)? 🥺

**Comment by CebulMaciej** [comment]
if it is possible, i would take part in using beta :)

**Comment by martinmakesitwork** [comment]
Hi, we want to be part ob beta as well. Let me know if it's possible.

**Comment by EffectConnect** [comment]
Any information as to when the Selling Partner API will be live for public use?

**Comment by daapower** [comment]
I have my LWA keys as that part went live couple days ago. I'm getting a 500 error when hitting the API. Am I doing something wrong or is SP API not live yet

Thanks

**Comment by seanevan** [comment]
Hi all,

SP-API endpoints are live, but we have not yet made registration for SP-API widely available. Please stay tuned, as we will  share news on that front in the coming days.

Best regards,
Sean

**Comment by evdeg** [comment]
SP-API endpoints and registration is live now. See the [announcement](https://github.com/amzn/selling-partner-api-docs/issues/24).
