### ISSUE TITLE
Advertising API

### ISSUE THREAD

**Issue by 401009641** [amzn/selling-partner-api-docs#150]
Hello, excuse me, I want to download the API data of advertising. I didn't find it in AWS. Where should I find these development documents? thank you！

**Comment by pengyanbing84** [comment]
Hi, where can I view the advertising API?

**Comment by winterstefan** [comment]
Hello @401009641 and @pengyanbing84 

This documentation repository reflects information about the `Amazon Selling Partner API`, only. If I understand you correctly, you're searching for the official API documentation for the `Amazon Advertising API`.

If so, you can find plenty of information right [here](https://advertising.amazon.com/API/docs/en-us). As far as I'm concerned, the authentication mechanism is identical to this SP-API. All other endpoints are located in a very separate scope.
