### ISSUE TITLE
The security token included in the request is invalid

### ISSUE THREAD

**Issue by Francesco-accline** [amzn/selling-partner-api-docs#1506]
Hello, I tried to contact support forum but my seller central credentials aren't recognized in that section, maybe because mine is an Italian marketplace

After obtaining an access_token, I tried to call SP API to retrieve a list of orders from the sandbox endpoint.
I get this response

"errors": [
    {
      "message": "The security token included in the request is invalid.",
      "code": "InvalidInput"
    }

the call is made through CURL using php shell_exec command

this is my CURL request

/usr/local/bin/curl -k -i  https://sandbox.sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2021-10-01  -H 'host:sandbox.sellingpartnerapi-eu.amazon.com' -H 'x-amz-access-token:Atza|IwEBIIckH6QJtK3AqzjJc2yA7fJhc3Fxc1Dkb4ln6LYSBrqK1ehR8QFQxRhKpvB5DMPSi6Fas6SROl49J5Y8W--bI7gK8O-lAlPvVM1fNSfCciz6sDM_TlyxcK5EFvXES-lOOK1xp5AGTfnleXTcdpYfhI6eruUW4o-mD0_MG4nq11mLF6yDGk37kZKS2KYpTq3oNOVen28FTrzzY4HzbqNCuQ5BD7zDF8aZ7VgRMRJ60zuANu4duDfMrJOLmz-q4VWjdUlW2KWU00-IY5pnNoE1j0dgC8Pcm8ePP8x4JeFuw4uA9S0tQX68t2ISV2J7qdaErw0vEO3uN46NOeYkxCAeBUhc' -H 'Content-Type:application/x-www-form-urlencoded;charset=UTF-8' -H 'x-amz-date:20211013T105602Z' -H 'Authorization:AWS4-HMAC-SHA256 Credential=amzn1.application-oa2-client.**a5b6016f7dcaXXXXXXXXXXXXXXXXX**/20211013/eu-west-1/execute-api/aws4_request,SignedHeaders=host;x-amz-access-token;Content-Type;x-amz-date,Signature=dc93ff761cac1839629353f9913a12f855e1d42277ec8ecda5d0a1bda2fb629f'

(I obscured my client id)

This is the request ID e7fcc8fa-f551-488d-bc91-f5a5ce48ac0d.

I've read somewhere that an X-Amz-Security-Token header is also required, but I don't know how to get it.
Can you help me please or can You address me to a working support page to solve my issue?
Thank You in advance.

**Comment by j782sdnm** [comment]
[Francesco-accline](https://github.com/Francesco-accline) did you solve the issue? is it related to "different emails"? I ask this question because I am facing the same issue :|.

**Comment by MrJamesFeng** [comment]
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.

i'm facing the same  issue, have you found resolution,tks !

**Comment by malekashkar** [comment]
Facing the same issue at the moment. Attempting to use aws4 npm module to sign the request for me and https NodeJS module to send the request.

Really can't seem to figure out what's causing it though :/
