### ISSUE TITLE
Where can I view the API for getting ads

### ISSUE THREAD

**Issue by pengyanbing84** [amzn/selling-partner-api-docs#151]
Where can I view the API for getting ads
I am using Python. Is there any Python3 interface documentation?

**Comment by tspicer** [comment]
You are in the wrong place for that info. See https://advertising.amazon.com/API/docs/en-us

**Comment by pengyanbing84** [comment]
> You are in the wrong place for that info. See https://advertising.amazon.com/API/docs/en-us

Hi, I have successfully registered as a SPAPI developer and can get reports. Can I directly use the advertising API? I see the document uses the advertising API to have a corresponding configuration file, may I ask?
