### ISSUE TITLE
API to retrieve Business Information

### ISSUE THREAD

**Issue by therubioftw** [amzn/selling-partner-api-docs#1519]
I'm getting no help, so I assume it means there's no way to currently do it?

### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/1495

<div type='discussions-op-text'>

<sup>Originally posted by **therubioftw** October 11, 2021</sup>
Is there an API that returns account information, like the Business Address, Legal Entity and so forth?
Basically what is available here, under Seller Account Information:

![image](https://user-images.githubusercontent.com/63039754/136775283-5fc9e006-4cf7-4589-a506-dc34b31aa949.png)

Currently the only thing returning with the LWA and SP-API tokens are an email, a name and the Merchant Token - and frankly, usually the email and name are internal and useless...

Thanks!</div>

**Comment by bchecketts** [comment]
It is pretty insane that one can not find the Seller Name anywhere in the API. I've brought this up to Amazon on several occasions, but they have never addressed it.  The obvious place to add it is as part of the response in the Sellers /  Marketplace Participations endpoint at https://github.com/amzn/selling-partner-api-docs/blob/main/references/sellers-api/sellers.md

**Comment by tspicer** [comment]
As @bchecketts pointed out, important metadata for the seller account does not exist. It should be part of the sellers-api assuming the sellers-API meets the stated objective as a source of metadata about a seller. 

As pointed out by @therubioftw LWA reflects something different, the metadata from the user authorizing the app. It does not reflect the metadata for the seller account. 

Ideally, the seller-api would additionally return business information as highlighted in the OP. At a minimum, just adding the merchant Merchant Name (i.e., Acme Corp, My Sock Sales,...) would be a great start.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by GJ-JG** [comment]
Hi all, thanks for the feedback.
Can you please share some valid use cases why business information like business name, business address and legal entity are needed?

**Comment by therubioftw** [comment]
> 

Hi @GJ-JG,
We want to offer sellers a few different financial services, and retrieving this information from the API would allow us to skip a few of the questions we have to ask. Anything that can reduce friction will be helpful :)
With this information specifically, it would allow us another level of identity verification - cross checking with their Amazon store legal ownership.

**Comment by tspicer** [comment]
@GJ-JG , I think one of the primary reasons is for parity.  Amazon Advertising API has a profile endpoint
https://advertising.amazon.com/API/docs/en-us/reference/2/profiles

This allows you to get metadata for an advertiser ID.  At this point, Selling Partner does not provide an endpoint which provides consistent metadata about the Seller (or Vendor). Like the Ads API, the scope of who has access to this metadata should be limited to those who are authorized to access.

Like Amazon Ads, the profile metadata acts as a look-up table, so when Amazon Ads returns X data with profile_ID 1234567890, you have a path to look up "who the heck is profile ID 1234567890".  Not having this information becomes increasingly problematic at scale, with 100s or 1000s of sellers.
