### ISSUE TITLE
Documentation around OAuth authorization for vendors could be greatly improved

### ISSUE THREAD

**Issue by Guerri114** [amzn/selling-partner-api-docs#1521]
When using OAuth to authorize vendors there are a number of nuances that are not described in the documentation. As such, developers have to struggle through the process, devoting valuable development time towards debugging a clunky OAuth process instead of developing integrations with the numerous Selling Partner APIs.

**Nuances**
- In most cases, a single company who has a "vendor" relationship with Amazon has multiple (N) vendor accounts (at least one per marketplace if not multiple per marketplace). This means that you need to the authorization process N times if you want to get the full scope of retail data and API access for that vendor. Creating a new vendor group with all of the company's vendor codes is not an option as there are some API features which are vendor group based rather than vendor code based (e.g. Vendor retail analytics).
- The **switch accounts** feature in Vendor Central breaks the OAuth flow, and is not usable (but I wish it was!). Instead, you have to direct vendors to first log in to the marketplace-specific Vendor Central host (i.e. vendorcentral.amazon.fr for France) and then click the developer-provided OAuth URL for that specific marketplace.

**Recommendations**
1. Update the GitHub documentation to reflect these nuances.
2. Create a UI in Vendor Central that would allow ONE employee at the vendor company to authorize multiple of their company's Vendor Central accounts to a developer at one time.
3. Stop the **switch accounts** feature from breaking the OAuth flow.

**Comment by SimonLit** [comment]
@Guerri114 Thanks for leaving this ticket.
I was running into the switch account OAuth problem on Vendor Central.
