### ISSUE TITLE
vendor-direct-fulfillment-inventory-api-model's error with only submitting vendorProductIdentifier in an item

### ISSUE THREAD

**Issue by jdliangli** [amzn/selling-partner-api-docs#1522]
**Describe the bug**
For vendor-direct-fulfillment-inventory-api-model, I'm trying to update inventory of items by calling the operation submitInventoryUpdate.

Inside the documentation, for SubmitInventoryUpdateRequest, inside ItemDetails, there are buyerProductIdentifier and vendorProductIdentifier. The document says "Either buyerProductIdentifier or vendorProductIdentifier should be submitted".

But when I only submitted the vendorProductIdentifier, the update transaction failed. But If I submitted both identifiers or only buyerProductIdentifier, the transaction was successful.

The error transaction status response Object is

class TransactionStatus {
transactionStatus: class Transaction {
transactionId: 174362f1-90f3-435d-a6a7-44fea05d4bd4-20211012202546
status: Failure
errors: class ErrorList {
[class Error {
code: INVALID_ITEM_ID
message: 409304 is not a valid product ID
details: Ensure that your product ID (SKU/UPC/EAN) is correctly mapped to an Amazon ASIN.
}]
}
}
}

The request Object is

class SubmitInventoryUpdateRequest {
inventory: class InventoryUpdate {
sellingParty: class PartyIdentification {
partyId: J####
}
isFullUpdate: false
items: [class ItemDetails {
buyerProductIdentifier: null
vendorProductIdentifier: 409304
availableQuantity: class ItemQuantity {
amount: 9
unitOfMeasure: Each
}
isObsolete: false
}]
}
}

The vendorProductIdentifier is correct, I can get the value inside the vendor-direct-fulfillment-order-api-model;s Order object.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-direct-fulfillment-inventory-api/vendorDirectFulfillmentInventoryV1.md#itemdetails

**Description of what the documentation currently says**
The vendor selected product identification of the item. Either buyerProductIdentifier or vendorProductIdentifier should be submitted.

**Description of what the documentation should say**
I don't know, I think it is vendorProductIdentifier cannot be used alone.

**Screenshots**
![image](https://user-images.githubusercontent.com/20564416/137410246-f941da6c-7133-4407-8834-072b75b3857e.png)

**Additional context**

**Comment by isaackleinbart** [comment]
This is still an issue. I am experiencing the same thing.

When I try providing our SKU as the "vendorProductIdentifier" it gives me the following error: 'code': 'INVALID_ITEM_ID', 'message': 'FLP10134-PK is not a valid product ID', 'details': 'Ensure that your product ID (SKU/UPC/EAN) is correctly mapped to an Amazon ASIN.'

This error occurs on multiple items I have tried. I have verified that these items are indeed valid SKUs in our catalog.

**Comment by coder771** [comment]
@isaackleinbart @jdliangli do you know how to fix this please.having same issues

**Comment by isaackleinbart** [comment]
> @isaackleinbart @jdliangli do you know how to fix this please.having same issues

No. We resorted to storing a mapping of SKU to ASIN in our own DB to use the call with an ASIN. @sungolivia can we reopen this and get some support as it's still an ongoing issue?

**Comment by coder771** [comment]
> > @isaackleinbart @jdliangli do you know how to fix this please.having same issues
> 
> No. We resorted to storing a mapping of SKU to ASIN in our own DB to use the call with an ASIN. @sungolivia can we reopen this and get some support as it's still an ongoing issue?

We have been doing the same. But for some reason still doesn't work. Not sure if the ASIN updated by customer in our system is not correct. Everything else looks fine. Do you send the ASIN in buyerProductidentifier?

**Comment by coder771** [comment]
> > @isaackleinbart @jdliangli do you know how to fix this please.having same issues
> 
> No. We resorted to storing a mapping of SKU to ASIN in our own DB to use the call with an ASIN. @sungolivia can we reopen this and get some support as it's still an ongoing issue?

Also do we need to send vendorproductidentifier sku as well for it to work?

**Comment by isaackleinbart** [comment]
Using the `buyerProductidentifier` and providing an ASIN works in our case.

**Comment by coder771** [comment]
> Using the `buyerProductIdentifier` and providing an ASIN works in our case.

For some reason that too doesn't work. Do you know of any method call i can use to get ASIN to be sure the ASIN customer is providing is correct for the SKU.  As that could be the only reason its not working

**Comment by isaackleinbart** [comment]
> > Using the `buyerProductIdentifier` and providing an ASIN works in our case.
> 
> For some reason that too doesn't work. Do you know of any method call i can use to get ASIN to be sure the ASIN customer is providing is correct for the SKU. As that could be the only reason its not working

Try this one: https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#getlistingsitem

**Comment by coder771** [comment]
> Using the `buyerProductIdentifier` and providing an ASIN works in our case.

Are you sending in vendorProductIdentifier as well or just the buyerProductIdentifier?
