### ISSUE TITLE
API access: No changes have been made to your SP-API access at this time.

### ISSUE THREAD

**Issue by vikapytlyk** [amzn/selling-partner-api-docs#1526]
Hi there!
We found your blog where you help solve SP-API blockers and we need your advice also  

Briefly about the idea of the project:
We are working on OMF middleware is a web application for inventory management in the warehouse (for one logistics company, which has its own warehouse). The user will be able to replenish the warehouse (by creating inbound shipment) and place orders and deliver orders from the warehouse to addresses (by creating outbound shipment). From marketplaces (it will be Amazon, Shopify) orders should automatically come to the logistics company, which are integrated into the middleware by API. Once an order appears on the marketplace, it should be automatically transferred to the logistics company and displayed in the middleware order list with some status. (for example: when the order is packed, delivered, and whether there was a return of goods or not).

We have already built such a system and integrated it with Shopify, we just need an expert who had experience working with Amazon Seller Central  SP-API to build integration with Amazon and our system, where users will be able to handle FBM and FBA orders.

BLOCKER:
Our main blocker, that we were rejected 2 times but did not receive a clear explanation of what is wrong, could you help us pass the validation to get this API? 
 request (ID7303244252) according to  Restricted SP-API
Could you give a more detailed description of the reason why our application was denied?
And what do we need to improve to gain access?

API: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by pazion** [comment]
Same problem here, terrible stance from Amazon.
Tell us what is wrong, we review and fix.
