### ISSUE TITLE
[BUG] The PetSupplies.xsd document is missing unit_count and unit_count_type attributes

### ISSUE THREAD

**Issue by CKTara** [amzn/selling-partner-api-docs#1527]
![image](https://user-images.githubusercontent.com/27659909/137472727-484dc473-1886-46b4-bbe7-490c35f29104.png)

https://m.media-amazon.com/images/G/01/SPEx/XSD_PreProd/PetSupplies.xsd
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/PetSupplies.xsd

The PetSupplies.xsd document is missing unit_count and unit_count_type attributes

**Comment by IvanMtze** [comment]
Is there any update on this issue?
