### ISSUE TITLE
I cannot get buyer's name and address

### ISSUE THREAD

**Issue by iceleo-com** [amzn/selling-partner-api-docs#1529]
I try all operations (getOrders, getOrder, getOrderAddress) to get Buyer's Shipping Address
I see the Address Response specifications on the document https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#address is very rich details. But I only receive the below result:

```
{
    "AmazonOrderId": "114-7501041-2098618",
    "ShippingAddress": {
        "StateOrRegion": "ME",
        "PostalCode": "04107-1234",
        "City": "CAPE ELIZABETH",
        "CountryCode": "US",
        "Name": ""
    }
}
```

May anyone point out what I missing?

**Comment by stefnats** [comment]
You must contact developer support to be able to retrieve PII data.

**Comment by ahlmackie** [comment]
Yes you need to be authorised to access PII data, then call a RDT token to use instead of your normal LWA token. There is a use case guide in the docs
