### ISSUE TITLE
How can I POST new product?

### ISSUE THREAD

**Issue by GrelaM100** [amzn/selling-partner-api-docs#153]
Hi,
I am trying to POST product using SP-API. As far as I understand I should create feed using createFeed method from feeds-api with feedType = " POST_PRODUCT_DATA". However I don't know what feedOptions should I set. In use case guide I found request example for an Easy Ship order. Where can I find information about specific values of feedOptions parameter for every feedType?

**Comment by roger-sanchez117** [comment]
In my experience, I recommend that you learn what is the process that Amazon establishes to load products. This involves learning about the product catalog, listings, product detail pages, and offers.

According to the tests I have done, you can load products with different types of files, each one has similar purposes but some are better adapted to some situations than others.

I have already been able to load products with the POST_PRODUCT_DATA feed for which you have to use an XML that you can generate from the schemas indicated [here](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf).

You can also use the POST_FLAT_FILE_INVLOADER_DATA feed, for this you will have to use an Excel template that later you will have to convert to a tab-separated-values file. This template can be obtained from Seller Central.

**Comment by voronytskyi** [comment]
For more details you can see here: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md

**Comment by madhupatel-hub** [comment]
Hi, @roger-sanchez117  can you please provide me a sample working XML?
[create_product.txt](https://github.com/amzn/selling-partner-api-docs/files/6120817/create_product.txt)
![Screenshot (127)](https://user-images.githubusercontent.com/59440968/110744837-5df8f480-8260-11eb-9dfe-5049e2150826.png)

Actually, I'm trying to create the product but it's giving me errors.

I'm not much familiar with the XSD format, I guess I'm doing something wrong.
error say i need to pass external_product_information,country_of_origin,size_name,color_name field. 
But when I'm passing it, giving me the same error so I'm a little bit confused about what I doing wrong.
can you please help me? 
I have also attached my XML file and error screenshot.
Thanks in Advance
Madhu Patel

**Comment by alpapazzo** [comment]
> In my experience, I recommend that you learn what is the process that Amazon establishes to load products. This involves learning about the product catalog, listings, product detail pages, and offers.
> 
> According to the tests I have done, you can load products with different types of files, each one has similar purposes but some are better adapted to some situations than others.
> 
> I have already been able to load products with the POST_PRODUCT_DATA feed for which you have to use an XML that you can generate from the schemas indicated [here](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf).
> 
> You can also use the POST_FLAT_FILE_INVLOADER_DATA feed, for this you will have to use an Excel template that later you will have to convert to a tab-separated-values file. This template can be obtained from Seller Central.

Hello Roger, I tried to upload a Flat file, but for each type: POST_FLAT_FILE_INVLOADER_DATA  and POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA that are 2 differents files, I got the same error: 

Exception when calling FeedsApi->createFeedDocument: [400] Client error: `POST https://sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/feeds` resulted in a `400 Bad Request` response: { "errors": [ { "code": "InvalidInput", "message": "1 validation error detected: Value \u0027[]\u0027 (truncated...)

I call the createFeedDocument fist, so I get the documentId, and the signature elements. So I use utf8_encode to convert the file to utf8 and then I encrypt the and upload the file. When I call "createFeed" I get that error. 

Do you have any suggestions ?

Thanks

**Comment by wmh49877** [comment]
> In my experience, I recommend that you learn what is the process that Amazon establishes to load products. This involves learning about the product catalog, listings, product detail pages, and offers.
> 
> According to the tests I have done, you can load products with different types of files, each one has similar purposes but some are better adapted to some situations than others.
> 
> I have already been able to load products with the POST_PRODUCT_DATA feed for which you have to use an XML that you can generate from the schemas indicated [here](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf).
> 
> You can also use the POST_FLAT_FILE_INVLOADER_DATA feed, for this you will have to use an Excel template that later you will have to convert to a tab-separated-values file. This template can be obtained from Seller Central.

hi @roger-sanchez117 , Do I need to write the xml file by myself, and then upload it encrypted through feeds? Is the process like this?

**Comment by iamsr** [comment]
I am also getting external_product_information error even though I checked xsd there is no such field. In excel templates external_production_information is referred to HSN Code but not sure how or what variable needed in xml to input that. Need help.

**Comment by mtkumar82** [comment]
I found out the issue. Please check the solution below it works for me.

<Message>
    <MessageID>1</MessageID>
    <OperationType>Update</OperationType>
    <Product>
  <SKU>5678999993</SKU>
  <StandardProductID>
    <Type>ASIN</Type>
    <Value>5678999993</Value>
  </StandardProductID>
  <ProductTaxCode>A_GEN_NOTAX</ProductTaxCode>
  <DescriptionData>
    <Title>MULE 3L - Racing Red/Pitch Blue</Title>
    <Brand>CAMELBAK</Brand>
    <Description>This is a test product description.</Description>
    <BulletPoint>Perfect for hiking.</BulletPoint>
    <BulletPoint>Bladder for hydration.</BulletPoint>
    <MSRP currency="AUD">100.00</MSRP>
    <Manufacturer>CAMELBAK</Manufacturer>
    <ItemType>outdoor-backpacks</ItemType>
   <CountryOfOrigin>US</CountryOfOrigin>
  </DescriptionData>
  <ProductData>
    <Outdoors>
      <ProductType>
        <OutdoorRecreationProduct>
        </OutdoorRecreationProduct>
      </ProductType>
      <VariationData>
      </VariationData>      
    </Outdoors>
  </ProductData>
</Product>
</Message>

New to add <CountryOfOrigin>COUNTRY_CODE</CountryOfOrigin> COUNTRY_CODE should be like US, IT, UK etc,  and  <CountryOfOrigin> must be used inside the  <DescriptionData> tag.  Hope it should work and help other.

**Comment by iamsr** [comment]
where to put "LaunchDate"? Earlier it was inside the Product tag but now it won't work with that schema.

**Comment by rugved1991** [comment]
Hi,

Please let us know if this issue persists. If you are still seeing an issue, please open a support case and provide us the case ID.

Best,
Rugved
Solutions Architect, SP API

**Comment by qiuzhiqiang18857889321** [comment]
Excel模板中格式是怎么样的？与后台手动模板刊登商品模板一致吗？为什么我一直在报错
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]
}

**Comment by rugved1991** [comment]
Hi,

When using the XSD or Flat_file options with the Feeds API, you have to generate an XML or CSV file first and then upload it to the Feeds API. The format of the XML and CSV file depends on the type of Feed you are working with. You can use this [doc](https://developer-docs.amazon.com/sp-api/docs/feeds-attributes) for more information on different types of Feeds and their attributes. 
For more information on how to generate a feed please refer to seller central help pages linked [here](https://sellercentral.amazon.com/help/hub/reference/G200384270).

You can also use the latest Listings API for 1x1 listing submission. If you are interested in bulk submissions, you can use the latest [JSON_LISTINGS_FEED](https://developer-docs.amazon.com/sp-api/docs/feed-json-schemas) which uses the latest JSON schema as a reference for validating submissions. 

Please refer to our [Listings Management Workflow Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide) for more information on how to build and manage listings workflows.

As always, if there are any specific issues with a feed submission, please open a developer support case to troubleshoot the issue in detail.

Best,
Rugved
Solutions Architect, SP API

**Comment by albinsopaj** [comment]
> In my experience, I recommend that you learn what is the process that Amazon establishes to load products. This involves learning about the product catalog, listings, product detail pages, and offers.
> 
> According to the tests I have done, you can load products with different types of files, each one has similar purposes but some are better adapted to some situations than others.
> 
> I have already been able to load products with the POST_PRODUCT_DATA feed for which you have to use an XML that you can generate from the schemas indicated [here](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf).
> 
> You can also use the POST_FLAT_FILE_INVLOADER_DATA feed, for this you will have to use an Excel template that later you will have to convert to a tab-separated-values file. This template can be obtained from Seller Central.

@roger-sanchez117 

Is it compulsory to use both of them (**_POST_PRODUCT_DATA_** and **_POST_FLAT_FILE_INVLOADER_DATA_**) to upload products to Amazon Marketplace or can I use only the latter (provided that I already possess a .xlsx file) and completely skip the former?

**Comment by albinsopaj** [comment]
> > In my experience, I recommend that you learn what is the process that Amazon establishes to load products. This involves learning about the product catalog, listings, product detail pages, and offers.
> > According to the tests I have done, you can load products with different types of files, each one has similar purposes but some are better adapted to some situations than others.
> > I have already been able to load products with the POST_PRODUCT_DATA feed for which you have to use an XML that you can generate from the schemas indicated [here](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf).
> > You can also use the POST_FLAT_FILE_INVLOADER_DATA feed, for this you will have to use an Excel template that later you will have to convert to a tab-separated-values file. This template can be obtained from Seller Central.
> 
> hi @roger-sanchez117 , Do I need to write the xml file by myself, and then upload it encrypted through feeds? Is the process like this?

@wmh49877 

I'm following this, and therefor waiting for an answer.
