### ISSUE TITLE
The 'NonPartneredSmallParcelData' upload 'Dimensions' and 'Weight' 

### ISSUE THREAD

**Issue by lzy6666666** [amzn/selling-partner-api-docs#1532]
**Describe the bug**
The store manager requires us to upload the packing size of the goods, but there is no such 'Dimensions' nad ' 'Weight'' field in the 'NonPartneredSmallParcelData'.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#nonpartneredsmallparceldatainput

**Description of what the documentation currently says**
There is no such 'Dimensions' nad ' 'Weight'' field in the 'NonPartneredSmallParcelData' for PutTransportDetailsRequest.

**Description of what the documentation should say**
How to upload  size  nad weight  for 'NonPartneredSmallParcelData' type.

**Comment by 401009641** [comment]
Has the problem been solved?

**Comment by smartzhanghandsome** [comment]
没人处理吗 ？

**Comment by lzy6666666** [comment]
收到，谢谢!!!（自动回复）

**Comment by abhishek-hopstack** [comment]
@lzy6666666 have found the solution for this issue ?
cc: @401009641 @smartzhanghandsome

**Comment by cjill** [comment]
Hello @lzy6666666 . I also met the same problem. Have you solved it now?

**Comment by lzy6666666** [comment]
收到，谢谢!!!（自动回复）
