### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by wangyufenghff** [amzn/selling-partner-api-docs#1539]
We request the Asin offers below, the result has two win buybox Asins. And we check the AmazonUI in https://www.amazon.com/dp/B089394PCY?th=1, the BuyBoxWinner is none of the two sellers. 

https://sellingpartnerapi-na.amazon.com/products/pricing/v0/items/B089394PCY/offers?MarketplaceId=ATVPDKIKX0DER&ItemCondition=New 

---------------------------------------------

HTTP/1.1 200 OK
Date: Tue, 19 Oct 2021 08:59:51 GMT
Content-Type: application/json
Content-Length: 25256
Connection: keep-alive
x-amzn-RequestId: 8a36782d-55be-4e9c-92a3-9774386b5e45
x-amzn-RateLimit-Limit: 5.0
x-amz-apigw-id: HcpZOG8SIAMFjFQ=
X-Amzn-Trace-Id: Root=1-616e8907-5b5c61341cacd8ce5c884905

{
  "payload":{
        "ASIN": "B089394PCY",
                "status": "Success",
            "ItemCondition": "New",
            "Identifier": {
    "MarketplaceId": "ATVPDKIKX0DER",
    "ItemCondition": "New"
            ,"ASIN": "B089394PCY"
                      },
            "Summary": {

                  "LowestPrices": [
                            {
          "condition": "new",
          "fulfillmentChannel": "Amazon",
                                                          "LandedPrice": {
                        "CurrencyCode": "USD",
            "Amount": 17.24
                      },
                      "ListingPrice": {
                        "CurrencyCode": "USD",
            "Amount": 17.24
                      }
                                  , "Shipping": {
                        "CurrencyCode": "USD",
            "Amount": 0.00
                      }
                                  }
            ,                    {
          "condition": "new",
          "fulfillmentChannel": "Merchant",
                                                          "LandedPrice": {
                        "CurrencyCode": "USD",
            "Amount": 17.15
                      },
                      "ListingPrice": {
                        "CurrencyCode": "USD",
            "Amount": 17.15
                      }
                                  , "Shipping": {
                        "CurrencyCode": "USD",
            "Amount": 0.00
                      }
                                  }
                                    ],
      
                        "BuyBoxPrices": [
                                            {
                    "condition": "new"
                                                                                                    ,"LandedPrice": {
                                        "CurrencyCode": "USD",
                    "Amount": 17.29
                                        }
                                        ,"ListingPrice": {
                                        "CurrencyCode": "USD",
                    "Amount": 17.29
                                        }
                                                            ,"Shipping": {
                                        "CurrencyCode": "USD",
                    "Amount": 0.00
                                        }
                                                                            }                     ],
      
                  "NumberOfOffers": [
                                    {
          "condition": "new",
          "fulfillmentChannel": "Amazon"
                        ,"OfferCount": 10
                      }
            ,                    {
          "condition": "new",
          "fulfillmentChannel": "Merchant"
                        ,"OfferCount": 9
                      }
                                    ],
      
                  "BuyBoxEligibleOffers": [
                            {
          "condition": "new",
          "fulfillmentChannel": "Amazon"
                        ,"OfferCount": 10
                  }
            ,                    {
          "condition": "new",
          "fulfillmentChannel": "Merchant"
                        ,"OfferCount": 7
                  }
                                    ],
      
            
                            "ListPrice": {
        "CurrencyCode": "USD",
        "Amount": 28.29
        },
              
                            "CompetitivePriceThreshold": {
        "CurrencyCode": "USD",
        "Amount": 26.22
        },
              
            
            
            "TotalOfferCount": 19

    },
    
    "Offers": [
                {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 17.15
          },
                                "ShippingTime": {
                    "maximumHours": 72,
          
                    "minimumHours": 48,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 449
                    ,"SellerPositiveFeedbackRating": 68.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A3RUI6TF4JZCM2",
                                "IsFeaturedMerchant": false,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 17.24
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
                    "availableDate": "2021-11-09T09:53:00Z",
          
        "availabilityType": "FUTURE_WITH_DATE"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 87
                    ,"SellerPositiveFeedbackRating": 98.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "A22A2AY8M8XHEL",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 17.29
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
                    "availableDate": "2021-10-30T20:00:00Z",
          
        "availabilityType": "FUTURE_WITH_DATE"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 2982
                    ,"SellerPositiveFeedbackRating": 96.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "A1DOURQACSJE3X",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 17.29
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
                    "availableDate": "2021-10-25T13:58:00Z",
          
        "availabilityType": "FUTURE_WITH_DATE"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 333
                    ,"SellerPositiveFeedbackRating": 99.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "A1G2UTNTSAU3EH",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 17.29
          },
                                "ShippingTime": {
                    "maximumHours": 48,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 372
                    ,"SellerPositiveFeedbackRating": 75.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A1NV4DXGQJPP6L",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": true,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 3.98
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 13.89
          },
                                "ShippingTime": {
                    "maximumHours": 48,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 1338
                    ,"SellerPositiveFeedbackRating": 92.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A1HUG5PT14A5GE",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 18.00
          },
                                "ShippingTime": {
                    "maximumHours": 48,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 16
                    ,"SellerPositiveFeedbackRating": 94.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "AQR9HLM22HRYS",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 18.57
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
                    "availableDate": "2021-10-20T07:28:00Z",
          
        "availabilityType": "FUTURE_WITH_DATE"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 683
                    ,"SellerPositiveFeedbackRating": 100.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "AAAZF3WTD7IAL",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 18.95
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 387
                    ,"SellerPositiveFeedbackRating": 91.0
                  },
                                "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "A2R2RITDJNW1Q6",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": true,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 19.50
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 1893
                    ,"SellerPositiveFeedbackRating": 98.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "A37BNBK8KJ7XV1",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 19.99
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 3684
                    ,"SellerPositiveFeedbackRating": 100.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "AMKVOB8E3YLFK",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 21.09
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
          
        "availabilityType": "NOW"
        },
                                "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A2XZ7JICGUQ1CX",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 22.46
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 690
                    ,"SellerPositiveFeedbackRating": 100.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "ANOJRGS7TIJWE",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 23.23
          },
                                "ShippingTime": {
                    "maximumHours": 0,
          
                    "minimumHours": 0,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 1048
                    ,"SellerPositiveFeedbackRating": 99.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": true,
        "IsNationalPrime": true
        },
                                "SubCondition": "new",
                        "SellerId": "A2QZB2ZASZYLDN",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": true
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 23.70
          },
                                "ShippingTime": {
                    "maximumHours": 24,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 2826
                    ,"SellerPositiveFeedbackRating": 95.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A3RMX5MOTQC3ON",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 23.85
          },
                                "ShippingTime": {
                    "maximumHours": 48,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 18
                    ,"SellerPositiveFeedbackRating": 83.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "AXOXZTJ6H7KLS",
                                "IsFeaturedMerchant": false,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 23.94
          },
                                "ShippingTime": {
                    "maximumHours": 24,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 23069
                    ,"SellerPositiveFeedbackRating": 90.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A2LK89FN6S2UNW",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 25.00
          },
                                "ShippingTime": {
                    "maximumHours": 48,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 16
                    ,"SellerPositiveFeedbackRating": 94.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "AQR9HLM22HRYS",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
        ,            {
                            "Shipping": {
          "CurrencyCode": "USD",
          "Amount": 0.00
          },
                                    "ListingPrice": {
              "CurrencyCode": "USD",
              "Amount": 27.10
          },
                                "ShippingTime": {
                    "maximumHours": 48,
          
                    "minimumHours": 24,
          
          
        "availabilityType": "NOW"
        },
                        "SellerFeedbackRating": {
        "FeedbackCount": 613
                    ,"SellerPositiveFeedbackRating": 79.0
                  },
                        "ShipsFrom": {
                  "Country": "US"
        },
                        "PrimeInformation": {
        "IsPrime": false,
        "IsNationalPrime": false
        },
                                "SubCondition": "new",
                        "SellerId": "A33M186JYS6IM4",
                                "IsFeaturedMerchant": true,
                        "IsBuyBoxWinner": false,
                                      "IsFulfilledByAmazon": false
      }
                      ],
        "marketplaceId": "ATVPDKIKX0DER"
  }
}

**Comment by nathan-protempo** [comment]
Buybox winner in the UI varies based on:
- whether you are logged in 
- whether you have a Prime account
- geographic location
and probably some other factors. 

I would treat this "buybox winner" flag with caution as the docs don't explain what basis they are using for selecting those sellers, and there are often multiple concurrent buybox sellers depending on the above factors.
