### ISSUE TITLE
Error: "Content is not allowed in trailing section" when submitting feeds POST PRODUCT DATA, POST_INVENTORY_AVAILABILITY_DATA and POST_PRODUCT_PRICING_DATA.

### ISSUE THREAD

**Issue by roger-sanchez117** [amzn/selling-partner-api-docs#154]
Hi!

I have a problem sending feeds of type POST PRODUCT DATA, POST_INVENTORY_AVAILABILITY_DATA and POST_PRODUCT_PRICING_DATA, yesterday I was able to do it without any problem, but now it shows me the following error in the feed processing report: "XML Parsing Fatal Error at Line 2 , Column 517: Content is not allowed in trailing section. Content is not allowed in trailing section ".

Does anyone else have this problem? Have they been able to solve it?

**Comment by ShivikaK** [comment]
Hello @roger-sanchez117 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @roger-sanchez117 

As we haven’t received any response from you regarding this, I will close this issue.
Please open a support case with us for any errors with your API requests and we can assist you further.

Thanks,
Shivika Khare
Selling Partner API Developer Support
