### ISSUE TITLE
Amazon Partner Network authorization workflow: Confirmation page intermittently shows empty.

### ISSUE THREAD

**Issue by rbarro-ecom** [amzn/selling-partner-api-docs#1543]
In our **Amazon Seller Central Partner Network authorization workflow** implementation, the login redirection works but when we redirect to the confirmation, it shows a blank page most of the time.

![image](https://user-images.githubusercontent.com/41913358/138064344-10ae41a4-731e-4431-879a-d8b707b1e716.png)

When this happens, we have to refresh the page multiple times for it to load properly.

This is the url that we generated.

`https://sellercentral.amazon.com/apps/authorize/confirm/{app id}?redirect_uri={redirect url}&amazon_state=MTYzNDcxOTk3Njk2Mu-_vWfvv71Y77-9Ve-_vWBpLTzvv73vv71w77-977-977-9fkrvv73vv71rfe-_ve-_vXZONO-_vRs677-9Se-_vTRy77-977-977-9Ye-_vV7vv73vv70177-9EO-_ve-_vQMR3rATKUzvv70P77-977-9UO-_vX8=&state=HxitvyrieUVWE9tAl4hyaaJTzd5pS71pmfWNCRLfAMU&version=beta`

and this is the error that we are noticing every time this happens.

```
Uncaught (in promise) Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.e.render (d3at80me5lazse.cloudfront.net/apps/manage/static/1.4ca45fa53d999999bae2.min.js:2)
    at d3at80me5lazse.cloudfront.net/apps/manage/static/main.676fb363446be29a10de.min.js:1
    at d3at80me5lazse.cloudfront.net/apps/manage/static/main.676fb363446be29a10de.min.js:1
    at Object.next (d3at80me5lazse.cloudfront.net/apps/manage/static/main.676fb363446be29a10de.min.js:1)
    at d3at80me5lazse.cloudfront.net/apps/manage/static/main.676fb363446be29a10de.min.js:1
    at new Promise (<anonymous>)
    at n (d3at80me5lazse.cloudfront.net/apps/manage/static/main.676fb363446be29a10de.min.js:1)
    at d3at80me5lazse.cloudfront.net/apps/manage/static/main.676fb363446be29a10de.min.js:1
    at d3at80me5lazse.cloudfront.net/apps/manage/static/1.4ca45fa53d999999bae2.min.js:2
    at Array.forEach (<anonymous>)
```

Can you help us?

**Comment by arimourao** [comment]
So, no one is going to answer this? I'm having the exactly same problem! In the console shows the problem is that occurs a CSP violation trying to load scripts and css. But this is totally on the side of Amazon, how am I supposed to handle this?!

**Comment by jimmy-ross-xapix** [comment]
Hi, we are seeing the same issue since this morning and raised a case with Amazon: ID 9505747981

It seems to be affecting all our users so is really critical for us too.

**Comment by nirmay** [comment]
Same for us, we raised a ticket - 9506113701

please look into this asap, several of ours are raising this us,

**Comment by openbridge-james** [comment]
We have the same issue, it is also reported here by another user.

https://github.com/amzn/selling-partner-api-docs/issues/1935

**Comment by tspicer** [comment]
same issue

**Comment by parvathm** [comment]
Hi,

Thank you for notifying us. We are looking into this issue and will update the fix as soon as possible.

Thanks,
Parvathm
SP API Developer Support.

**Comment by parvathm** [comment]
Hi,

We have resolved this issue. Please check and let us know if you are still facing same issue.

Thanks,
Parvathm
SP AP Developer Support.

**Comment by rbarro-ecom** [comment]
It did not fix for me. Note that this does not happen on the first try.

![image](https://user-images.githubusercontent.com/41913358/150788708-b5ccc1f8-4fbd-4a8b-aabb-e30bee3f4039.png)
