### ISSUE TITLE
How do I get messages in an order?

### ISSUE THREAD

**Issue by yizeku** [amzn/selling-partner-api-docs#1549]
![image](https://user-images.githubusercontent.com/33300443/138226075-2c1a0aa4-9465-40cd-9442-54cc959d5749.png)
I want to get the corresponding message list in the order, but I can't find the corresponding API.

I tried this api, but it didn't return any useful information.
**/messaging/v1/orders/orderId**

How can I get the message corresponding to the order?

**Comment by bsglm** [comment]
Hello

I was wondering about the answer to this question because 
I didn't find it. how can I get order message content via SP API
