### ISSUE TITLE
MFN  product   how to shipments in the api,How to write  tracking information 

### ISSUE THREAD

**Issue by dingzheyan** [amzn/selling-partner-api-docs#155]
MFN product how to shipments in the api How to write  tracking information

**Comment by shaoruisky** [comment]
@dingzheyan https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md

**Comment by dingzheyan** [comment]
ok,thank you
