### ISSUE TITLE
Restricted Access Request

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#1553]
Hello,
We have been requesting PII access for more than 6 months. 
We provide all the information and documents requested by Amazon, but these requests are denied without any clear reason.
Due to this problem, our software development process and our customers are suffering. 
We have to access this information as soon as possible and satisfy our customers.
The final answer is as follows:

"Hello,

 Thank you for your response.

 We have reviewed the information you provided and determined that you will not be given access to Restricted SP-API roles based on your application. Your SP-API access remains unchanged at this time.

 We evaluate all Public Developer applications that request Restricted SP-API access, for a variety of technical and business criteria including, but not limited to, launch readiness, services offered, and supported geographies.

 If you decide to build a publicly available application with the SP-API roles you already have access to, it is required to be listed in the Amazon Selling Partner Network. You can submit a new Listing form, or make edits to an existing listing, within Developer Central: https://sellercentral.amazon.com/sellingpartner/developerconsole

 We look forward to listing your application in the Amazon Selling Partner Network."

We would like to receive support and contact on the phone in this regard.
Could you please show us a solution?
If we learn about our missing information and documents, we will complete it as soon as possible.

Thanks

**Comment by abuzuhri** [comment]
> @hkncnr07 , I was told in my SP-API response that _"accessing Personally Identifiable Information (PII) as a Public developer is not supported by our policies"_. I have yet to find this policy that Public Developers, including those with prior PII approval, are no longer eligible.

Is that mean public developers will never have access to PII ?
