### ISSUE TITLE
问题：java.lang.RuntimeException: Error getting LWA Access Token

### ISSUE THREAD

**Issue by 18061734391** [amzn/selling-partner-api-docs#1557]
原因：获取RDT的时候异常
错误：java.lang.RuntimeException: Error getting LWA Access Token
操作步骤：调用vendor/orders/v1/purchaseOrders时候发现他是受限制的请求，必须要通过先获取RDT，但是通过https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#step-1-get-an-rdt-getorders解决策略中的https://github.com/amzn/selling-partner-api-models/blob/main/clients/sample-code/RestrictedDataTokenWorkflow.java获取RDT报错。
报错位置：
   CreateRestrictedDataTokenResponse response = tokensApi.createRestrictedDataToken(restrictedDataTokenRequest);
内置的tokensApi会调用内置的jar里面的方法创建一个请求
            Response response = this.okHttpClient.newCall(accessTokenRequest).execute();
执行请求的时候返回了一个错误码
Response{protocol=http/1.1, code=400, message=Bad Request, url=https://api.amazon.com/auth/O2/token}
内置请求是：Request{method=POST, url=https://api.amazon.com/auth/O2/token, tag=null}
抛出异常:               
            1.throw new IOException("Unsuccessful LWA token exchange");
            2.throw new RuntimeException("Error getting LWA Access Token", var9);

**Comment by bxb100** [comment]
1. first check your LWA oauth is right, such as refreshToken value etc.
2. then check your account is vendor
