### ISSUE TITLE
x-amz-access-token or X-Amz-Security-Token ?

### ISSUE THREAD

**Issue by wanghuoling** [amzn/selling-partner-api-docs#156]
I download aws-sdk for php. the php file "SignatureV4.php"  in line 258 code is:
 $parsedRequest['headers']['X-Amz-Security-Token'] = [$token];
the param name is "X-Amz-Security-Token".
But the "Selling Partner API Developer Guide" document  is: "x-amz-access-token"。
So my question " which  param name  is right? "

**Comment by zhanfjunjun** [comment]
Both parameters are required

**Comment by rodrigojob** [comment]
> Both parameters are required

Nope.
I create a class to insert the header in request. So, I re-create the signature method

**Comment by tenitre** [comment]
In my experience @zhanglaoye  is right, you need to provide both otherwise you keep getting Forbidden

good luck

**Comment by wanghuoling** [comment]
Thanks every.I tried,must be include these two parameters in process.this question is solved.But i meet other problem.
