### ISSUE TITLE
Amazon SPAPI Restricted Access Role

### ISSUE THREAD

**Issue by Hulk-Tron** [amzn/selling-partner-api-docs#1562]
Hello, @jchavest13

For getting the shipping address via getOrderAddress API, I updated the developer profile.

But I got the following answer,

"We have completed our assessment and have determined that you do not meet the requirements for Restricted SP-API. To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third-party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon."

CASE ID: 7451217952

Can you guide us regarding amazon's response?

**Comment by Hulk-Tron** [comment]
Hi @jchavest13 & @rugved1991 Any comment on above issue ?

**Comment by Hulk-Tron** [comment]
Hi @ShivikaK & @parvathm 
I have not heard anything about my issue.

**Comment by jchavest13** [comment]
Hi @Hulk-Tron,

Please accept our apologies for the delay getting back to you. 

I have created an internal request for the team evaluating SP-API access upgrade assessments to review your case. We thank you for your patience while we work to address your concern as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by Hulk-Tron** [comment]
Hi @jchavest13,
The case is already closed can you please let me know exactly why the request was denied as the reply was generic.

**Comment by delicatessen** [comment]
@Hulk-Tron Did you solve this problem? We're having the same issue
