### ISSUE TITLE
Create subscribtion `/notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED` - StateConflict

### ISSUE THREAD

**Issue by nazarvovk** [amzn/selling-partner-api-docs#1564]
Calling `/notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED` results in the following error:
```json
"request": {
    "method": "POST",
    "url": "notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED",
    "data": {
        "payloadVersion": "1.0",
        "destinationId": "289c5e5d-e4b8-4bcb-aebb-5dba3aca1781"
    }
},
"response": {
    "status": 409,
    "headers": {
        "date": "Sat, 23 Oct 2021 09:11:17 GMT",
        "content-type": "application/json",
        "content-length": "140",
        "connection": "close",
        "x-amzn-requestid": "2a1ce555-36e8-46ed-a2b2-b327ae297eeb",
        "x-amz-apigw-id": "Hp20VH44oAMFjhA=",
        "x-amzn-trace-id": "Root=1-6173d1b5-5172fa3226fbf4012a550724"
    },
    "statusText": "Conflict",
    "data": {
        "errors": [
            {
                "code": "StateConflict",
                "message": "The resource specified conflicts with the current state."
            }
        ]
    }
}
```

There's nothing in the docs about this kind of error and how to deal with it.

**Comment by weswilliams-channeladvisor** [comment]
I'm having this issue as well and unable to find any resolution.

**Comment by matheustiny** [comment]
Same here.

**Comment by kzpreneur17** [comment]
I was able to create subscription earlier, but getting this error now!

**Comment by arimourao** [comment]
Good to know no one at amazon really cares about bugs and stuff.

**Comment by parvathm** [comment]
Hi,

@arimourao did you open a [support case](https://sellercentral.amazon.com/gp/mws/contactus.html) with latest request id and time stamp which will help to debug the issue quickly? Can you please share the case id. 

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by AJ-AUS** [comment]
Was this resolved? I am also having this problem

**Comment by matheustiny** [comment]
I realized that this happen when you already have a subscription created for that subscription and app id.
