### ISSUE TITLE
[c#] upload xml document content for feed (/feeds/2020-09-04/documents)

### ISSUE THREAD

**Issue by bjt19882222** [amzn/selling-partner-api-docs#1566]
Hi,

i need to post an xml feed for "CartonContentsRequest" with c#.
I think i have to do the following steps:

1.) post call to "/feeds/2020-09-04/documents" with 
`string json = "{\"contentType\":\"text/xml; charset=ISO-8895-1\"}";`
This returns: "url", "key", "initializationVector"
This step is working for me. I receive the 3 values.

2.) upload the xml content to the returned url from step 1. the xml content must be encrypted and have to post with "PUT"
i will not get an c# script working to upload an xml content to the returned url.
have someone an short working example to show how to upload the document content?

thx.

**Comment by abuzuhri** [comment]
Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp
