### ISSUE TITLE
[BUG] createReport - GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT - Access to the resource is forbidden

### ISSUE THREAD

**Issue by forFutrue** [amzn/selling-partner-api-docs#1567]
POST /reports/2021-06-30/reports
{
            "reportType": "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
            "reportOptions": {"reportPeriod": "MONTH"},
            "dataStartTime": '2021-09-01T00:00:00', 
            "dataEndTime": '2021-09-30T00:00:00', 
            "marketplaceIds": ['ATVPDKIKX0DER']
}

Responses: 
{'errors': [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]}

Other reports can be obtained normally

**Comment by moltar** [comment]
@forFutrue were you able to get this working? Trying to get it to work, and getting the same errors.

**Comment by ydancziger** [comment]
Same here

**Comment by pecalleja** [comment]
same here

**Comment by vicky-3001** [comment]
Hi,

I am facing the same issue. Able to get other reports, but not GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT

{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}

**Comment by radug-cpc** [comment]
@forFutrue , have you had any luck with this? We're facing the same problem for a different report type: GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
