### ISSUE TITLE
Sales API Operation: getOrderMetrics (GET /sales/v1/orderMetrics) returns '0' for all response parameters

### ISSUE THREAD

**Issue by nirmalsunny** [amzn/selling-partner-api-docs#1568]
The operation 'getOrderMetrics' is returning '0' for 'unitCount', 'orderItemCount', 'orderCount' and 'averageUnitPrice' although the product had significant amount of sales in the past. I have tried with with different ASINs, Intervals, Granularities and Granularity Time Zones but, all it returns is zero.
Marketplace : UK

Here's the response:
<html>
<body>

object(stdClass)#4703 (1) {
--
  | ["payload"]=>
  | array(13) {
  | [0]=>
  | object(stdClass)#4747 (6) {
  | ["interval"]=>
  | string(36) "2020-09-01T00:00Z--2020-10-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4749 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4746 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [1]=>
  | object(stdClass)#4753 (6) {
  | ["interval"]=>
  | string(36) "2020-10-01T00:00Z--2020-11-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4760 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4748 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [2]=>
  | object(stdClass)#4755 (6) {
  | ["interval"]=>
  | string(36) "2020-11-01T00:00Z--2020-12-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4745 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4744 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [3]=>
  | object(stdClass)#4743 (6) {
  | ["interval"]=>
  | string(36) "2020-12-01T00:00Z--2021-01-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4742 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4740 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [4]=>
  | object(stdClass)#4739 (6) {
  | ["interval"]=>
  | string(36) "2021-01-01T00:00Z--2021-02-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4738 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4737 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [5]=>
  | object(stdClass)#4736 (6) {
  | ["interval"]=>
  | string(36) "2021-02-01T00:00Z--2021-03-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4735 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4686 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [6]=>
  | object(stdClass)#4732 (6) {
  | ["interval"]=>
  | string(36) "2021-03-01T00:00Z--2021-04-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4733 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4730 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [7]=>
  | object(stdClass)#4731 (6) {
  | ["interval"]=>
  | string(36) "2021-04-01T00:00Z--2021-05-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4726 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4729 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [8]=>
  | object(stdClass)#4728 (6) {
  | ["interval"]=>
  | string(36) "2021-05-01T00:00Z--2021-06-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4727 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4723 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [9]=>
  | object(stdClass)#4725 (6) {
  | ["interval"]=>
  | string(36) "2021-06-01T00:00Z--2021-07-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4724 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4720 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [10]=>
  | object(stdClass)#4722 (6) {
  | ["interval"]=>
  | string(36) "2021-07-01T00:00Z--2021-08-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4721 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4716 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [11]=>
  | object(stdClass)#4719 (6) {
  | ["interval"]=>
  | string(36) "2021-08-01T00:00Z--2021-09-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4718 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4717 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | [12]=>
  | object(stdClass)#4713 (6) {
  | ["interval"]=>
  | string(36) "2021-09-01T00:00Z--2021-10-01T00:00Z"
  | ["unitCount"]=>
  | int(0)
  | ["orderItemCount"]=>
  | int(0)
  | ["orderCount"]=>
  | int(0)
  | ["averageUnitPrice"]=>
  | object(stdClass)#4715 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | ["totalSales"]=>
  | object(stdClass)#4714 (2) {
  | ["amount"]=>
  | float(0)
  | ["currencyCode"]=>
  | string(3) "GBP"
  | }
  | }
  | }

</body>
</html>

**Comment by tina7ti** [comment]
Hello, any news regarding that? have you found a solution for that?

**Comment by nirmalsunny** [comment]
Yes, it is working with our own products.
