### ISSUE TITLE
No mws_auth_token from Amazon when authorizing hybrid app via Website workflow

### ISSUE THREAD

**Issue by akashkaushik33** [amzn/selling-partner-api-docs#157]
I am trying to get the mws_auth_token for calls mws APIs. But I am not receiving mws_auth_token in the query parameters.

I am using version=beta parameter in the query parameters as my app is not published yet.

Here is the ref code:

```
// creating the OAuth url
const amazonAuthUrl = `https://sellercentral.amazon.com/apps/authorize/consent?application_id=${AMAZON_APP_ID}&state=${amazonAuthState}&version=beta`;

// Redirecting users to OAuth url
redirect(amazonAuthUrl);
```
Then Amazon adds the spApiOauthCode on the redirect route which I use to get refresh token and access token.
SP-APIs are working fine though. 

The only issue is, I do not get the mws_auth_token in query parameters even though my app is hybrid.

Please let me know if I am missing something.
Any help is appreciated.

**Comment by parvathm** [comment]
Hi @akashkaushik33,

Can you please open a support case [here](https://sellercentral.amazon.com/gp/mws/contactus.html) with your application id details so we can investigate further.

Thanks,
Parvathm,
Selling Partner API Support.

**Comment by parvathm** [comment]
Hi,

Its been a while since we responded. I am closing this issue now. If you still have issues please give us the case id so that we can follow up.

Thanks,
Parvathm,
Selling Partner API Developer Support.
