### ISSUE TITLE
amazon sp-api with access denied with no details

### ISSUE THREAD

**Issue by snpatel17** [amzn/selling-partner-api-docs#1570]
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

I have configured it as follow:
STS policy -> AWS User 
SellingPartnerAPI policy -> IAM Role
registered app using ROLE ARN

I need to get client details (for fetching orders every day) and order details, and the following is my code. Looking forward for help. 

public string GetloginUrl(string redirectUrl, string state, string guid)
        {
  
            return string.Format("https://sellercentral.amazon.ca/apps/authorize/consent?application_id="+app_id+"&state="+state+ "&redirect_uri="+ redirect_uri+ "&version=beta");
        }

        public void SignWithAccessToken(string code)
        {
            var client22 = new RestClient("https://api.amazon.com/auth/o2/token");
            client22.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("content-type", "application/x-www-form-urlencoded");

            request.AddParameter("grant_type", "refresh_token");
            request.AddParameter("client_id", client_id);
            request.AddParameter("client_secret", client_secret);
            request.AddParameter("code", code);
            request.AddParameter("refresh_token",refresh_token);
            
           
            IRestResponse response22 = client22.Execute(request);

            var tokens = JObject.Parse(response22.Content);
            AccessToken serStatus = JsonConvert.DeserializeObject<AccessToken>(response22.Content);            

            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

            var resource = "/orders/v0/orders";
            IRestRequest restRequest = new RestRequest(resource, Method.GET);

            restRequest.AddParameter("createdAfter", DateTime.UtcNow.AddDays(-5).ToString("yyyy-MM-dd"), ParameterType.QueryString);
            restRequest.AddParameter("createdBefore", DateTime.UtcNow.ToString("yyyy-MM-dd"), ParameterType.QueryString);
            restRequest.AddQueryParameter("marketplaceIds", "ATVPDKIKX0DER");
            var client = new RestClient("https://sellingpartnerapi-na.amazon.com");

            var lwaAuthorizationCredentials = new LWAAuthorizationCredentials
            {
                ClientId = client_id,
                ClientSecret = client_secret,
                Endpoint = new Uri("https://api.amazon.com/auth/o2/token"),
                RefreshToken = refresh_token,
            };

            restRequest= new LWAAuthorizationSigner(lwaAuthorizationCredentials).Sign(restRequest);
      
            AssumeRoleResponse response1 = null;
            using (var STSClient = new AmazonSecurityTokenServiceClient(accesskey, secretkey, RegionEndpoint.USEast1))
            {
                var req = new AssumeRoleRequest()
                {
                    RoleArn = RoleARN,
                    DurationSeconds = 950, 
                    RoleSessionName = Guid.NewGuid().ToString()
                };

                response1 = STSClient.AssumeRoleAsync(req, new CancellationToken()).Result;
            }

            //auth step 3
            var awsAuthenticationCredentials = new AWSAuthenticationCredentials
            {
                AccessKeyId = response1.Credentials.AccessKeyId,
                SecretKey = response1.Credentials.SecretAccessKey,
                Region = "us-east-1"
            };

            restRequest.AddHeader("x-amz-security-token", response1.Credentials.SessionToken);

            restRequest = new AWSSigV4Signer(awsAuthenticationCredentials)
                            .Sign(restRequest, client.BaseUrl.Host);
           
            var response = client.Execute(restRequest);

**Comment by wisdomleo** [comment]
Solution from Tareq Abuzuhri abuzuhri:

https://github.com/amzn/selling-partner-api-docs/issues/1413

please check the forth question at bwloe amazon official page:

https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs

**Comment by coder771** [comment]
@snpatel17  how did you solve this. having same issue

**Comment by coder771** [comment]
@snpatel17 thanks for getting back. what do we need to do get the access to these restricted path from amazon. my app is in draft state at the moment

**Comment by carlshi12r44** [comment]
@snpatel17  Hi there, sorry for the ping, we are having similar issue and we think the root cause might be due to the fact that the AWS account we used to call the endpoint is not registered as a developer for SP-API. Does that mean we need to also register the AWS account as the developer for SP-API? Thank you

**Comment by cnr91** [comment]
I have same issue, did you solve it?
