### ISSUE TITLE
putListingsItem api with InvalidInput error code  [main_product_image_locator ][BUG] Documentation

### ISSUE THREAD

**Issue by DLR2020** [amzn/selling-partner-api-docs#1571]
I tried adding image urls to the main_product_image_locator attribute.  I get this response:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Unable to Retrieve Media Content for URL \u0027Media Content is Not Hosted by Amazon or Amazon Web Services (such as AWS S3 or AWS CloudFront)\u0027: https://mycompanyname.com/dg9-hrqCRePNnovO/cat0322frotest.jpg.",
      "details": ""
    }
  ]
}
Does Amazon not support images on users' own servers ? 
Is there a solution to this problem？
It's really urgent. Thank you very much

**Comment by adam-aido** [comment]
This is still an existing issue

**Comment by sbosman1** [comment]
Hello we are also facing this issue, the old xml upload doesn't require that the images are hosted on Amazon. Why would this be required using the new API. We need to use techniques creating a product on Amazon new API and old legacy XML upload. Please resolve this issue we don't want to use the old legacy api any more.

**Comment by DLR2020** [comment]
I couldn't solve the problem, so I can only store the images to S3.

**Comment by sbosman1** [comment]
> I couldn't solve the problem, so I can only store the images to S3.

its not for free right to store images on S3, because we have to upload all the images of our customers to S3 first and add you can use the putListingsItem  method? We only want to send a url of image and let Amazon download the image to their server.

**Comment by legolas108** [comment]
If storing images on S3 was a requirement, then why would the JSON product type schema mention `"http://www.companyname.com/images/1250.offer.jpg"` as example URL e.g. for the `main_offer_image_locator` property?

**Comment by matspin** [comment]
> If storing images on S3 was a requirement, then why would the JSON product type schema mention `"http://www.companyname.com/images/1250.offer.jpg"` as example URL e.g. for the `main_offer_image_locator` property?

we have the same problem

**Comment by wszwc** [comment]
Hi, thank you for your discussion. I also have the same problem. If the new API comes with paid content, I think this is not progress. This change is a very bad and unacceptable thing for users. I deeply hope that the Amazon team can Take this issue seriously, thank you
