### ISSUE TITLE
Are generated reports paginated?

### ISSUE THREAD

**Issue by JacobShopWired** [amzn/selling-partner-api-docs#1575]
Are the generated reports paginated or do the report documents contain all information?

I want to get all the listings in an account, I have 10 in my account currently and I'm getting 10 through the reports API, but I'm not sure if at some point I will need to handle pagination.
I'm also not sure at what level pagination will occur (report or report document).

If anyone knows how reports work with pagination, and can let me know. It would be appreciated, the documentation for this seems to be lacking.

**Comment by ianrussel** [comment]
I tried the order and merchantlistings report.Not paginated.The result will be in bulk (They will be in compress files(zip))

**Comment by JacobShopWired** [comment]
> I tried the order and merchantlistings report.Not paginated.The result will be in bulk (They will be in compressed files(zip))

Ok thank you 👍🏼
