### ISSUE TITLE
[BUG] Documentation - Feeds API / CreateFeedDocumentResponse

### ISSUE THREAD

**Issue by rain-axb** [amzn/selling-partner-api-docs#1590]
**Describe the bug**
The response of [Step 1. Create a feed document](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md#step-1-create-a-feed-document) in feeds api use case guide is different from the document([CreateFeedDocumentResponse](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md#step-1-create-a-feed-document)) in references.

**URL of the content on GitHub**
- Use case guide: [Step 1. Create a feed document](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md#step-1-create-a-feed-document)
- References: [CreateFeedDocumentResponse](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md#step-1-create-a-feed-document)

**Description of what the documentation currently says**
A successful response includes the encryptionDetails in feeds api use case guide.

**Description of what the documentation should say**
But there is NO encryptionDetails in references document.

**Screenshots**
Feeds api use case guide
<img width="1037" alt="use case guide" src="https://user-images.githubusercontent.com/67897193/139621184-1ceeafd2-37c7-44a4-977c-85b80dc5a5f8.png">

References
<img width="918" alt="References" src="https://user-images.githubusercontent.com/67897193/139621199-fc4ada35-e9af-427c-bd90-5a88d7e674b8.png">

**Additional context**
Which explanation is correct?

**Comment by abuzuhri** [comment]
Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by vaidas-lungis** [comment]
I tried to understand your question

it is not a bug.
https://github.com/amzn/selling-partner-api-docs/discussions/1107

There are two versions of feeds API. The older one requires encryption and the other is not.
Please check pages and versions

There are two guides 

![Screenshot 2021-11-04 at 15 12 04](https://user-images.githubusercontent.com/5111555/140319306-e2f1c231-b942-4bd2-9121-194f826b2f4a.png)
https://github.com/amzn/selling-partner-api-docs/tree/main/guides/en-US/use-case-guides/feeds-api-use-case-guide

![Screenshot 2021-11-04 at 15 14 40](https://user-images.githubusercontent.com/5111555/140319648-7c04b774-c2ec-48df-838d-3e968fb7dcf0.png)

https://github.com/amzn/selling-partner-api-docs/tree/8c567ddb84a66e741eda7f0850b2be443870aeed/references/feeds-api

Version `2021-06-30` does not require encryption 
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md

**Comment by rain-axb** [comment]
@vaidas-lungis Thank you so much.
