### ISSUE TITLE
[BUG] Documentation for new READY_TO_SHIP ShipmentStatus

### ISSUE THREAD

**Issue by ezerway** [amzn/selling-partner-api-docs#1591]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
On my dashboard, i have some shipments, which are marked as 'READY_TO_SHIP',  But when i try get them by api, i got  the error:

`[400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid ShipmentStatus: READY_TO_SHIP",
      "details": ""
    }
  ]
}
`
**URL of the content on GitHub**
Please provide the GitHub URL for the documentation where you see the bug.
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatus

**Description of what the documentation currently says**
Please describe the section/paragraph of the documentation where you see the bug.
The documentation isn't up to date, Currently we have a new status 'READY_TO_SHIP'

**Description of what the documentation should say**
A clear and concise description of the guidance you expected to see in the documentation.
Need update doc also api to solve the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/54234094/139677029-e13e63e5-c55d-4810-9570-5a13d63e7e8c.png)

**Additional context**

**Comment by joyceeeen** [comment]
any updates on this? Encountering this issue as well in MWS API
