### ISSUE TITLE
[BUG] /fba/inventory/v1/summaries startDateTime returning unexpected results

### ISSUE THREAD

**Issue by bookbyteinico** [amzn/selling-partner-api-docs#1595]
We are trying to convert from MWS ListInventorySupply calls over to getInventorySummaries in SPAPI. We are calling the endpoint with the startDateTime parameter and it is returning way more results than the same MWS ListInventorySupply calls would for the same starting datetime. For instance on MWS we pass a time from 5 minutes ago and get back say 5 results. the same time passed to getInventorySummaries is returning (hundreds / thousands?) of results one result at a time via a next token and subsequent calls. We stopped the calls after getting back several hundred so unsure on how many this would return if we kept calling by next token.

**Comment by kenmed55** [comment]
I'm seeing the same behavior. Looks like the "startDateTime" parameter is being ignored. 

Anyone have any idea what's happening here?

**Comment by inicolay** [comment]
we opened a support case but have not gotten back any helpful info yet. please let me know if you discover anything @kenmed55

**Comment by shmurf** [comment]
Anyone figure this out yet? Seems like the "startDateTime" parameter is indeed being ignored, but not completely ignored because if you send an invalid string you will get the error
Query parameter [startDateTime] value is not a valid ISO date-time object

**Comment by inicolay** [comment]
we still have the issue

**Comment by ShaneOH** [comment]
Hi, I had this issue too, and in my case it was because I was relying on `nextToken` and not expecting to need the initial arguments once I have `nextToken`. However, I got the following from support:

> This is Adrian, I understand you are concerned about the 'startDateTime' parameter that seems to be ignored when calling getInventorySummaries using nextToken.
> 
> I have looked into this matter, the ideal call pattern to get Inventory Summary data with startDateTime filter, would be to include that filter to the initial request and all the subsequent requests as well along with the next token.
> 
> It is an expected behavior where the API would return empty array of "InventorySummaries" but still return a "NextToken". The same behavior is called out in the API use-case guide:
> 
> https://developer-docs.amazon.com/sp-api/docs/fba-inventory-api-v1-use-case-guide#pagination-in-getinventorysummariesresponse

So that actually did fix it in my case. Here are some sample query strings for anyone still stuck:

```
GET /fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&startDateTime=2022-08-12T04%3A21%3A49%2B00%3A00&marketplaceIds=ATVPDKIKX0DER
```

```
GET /fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&startDateTime=2022-08-12T04%3A27%3A24%2B00%3A00&nextToken=xxx&marketplaceIds=ATVPDKIKX0DER
```

and so on. 

Thanks Adrian! Hope this helps anyone else still running into this same issue!
