### ISSUE TITLE
spapi upload 

### ISSUE THREAD

**Issue by AceGray** [amzn/selling-partner-api-docs#1598]
post https://sellingpartnerapi-na.amazon.com/uploads/2020-11-01/uploadDestinations?marketplaceIds=ATVPDKIKX0DER&contentMD5=phW0L6hC1rlon0ZCYNKlvQ%3D%3D&contentType=application%2Foctet-stream

to upload xml content return error   "message": "Access to requested resource is denied."

Is it because of this interface; Do you need special permission

**Comment by abuzuhri** [comment]
Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by vicdoz** [comment]
In some requests the API returns this response if the request is wrong.Yes, very confusing.

Review the params, body, headers, etc because is possible you don't have an authentication problem...

**Comment by ShivikaK** [comment]
Hello @AceGray 

Thank you for raising this issue.

Please open a support case so we can pursue the investigation. In the support case, please provide request details including request ID and timestamp to troubleshoot the issue further.

Thanks,
  Shivika Khare  
Selling Partner API Developer Support

**Comment by AceGray** [comment]
Excuse me? How does spapi synchronize the XML data of order logistics information to Amazon stores through the interface post / uploads / 2020-11-01 / uploaddestinations / {resource}?
