### ISSUE TITLE
ReportTypes Response Unauthorized

### ISSUE THREAD

**Issue by dishcheng** [amzn/selling-partner-api-docs#1599]
reportTypes: 
1、GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT (reportPeriod: WEEK)
params
```
[
            'reportOptions'=>[
                'reportPeriod'=>'WEEK'
            ],
            'reportType'=>'GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT',
            'marketplaceIds'=>['ATVPDKIKXXXXX'],
            'dataStartTime'=>'2021-10-24T00:00:00',
            'dataEndTime'=>'2021-10-30T23:59:59',
 ]
```

2、GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA
3、GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA

post request route `reports/2020-09-04/reports`

when I   request  create reports above three report types ,
amazon response
```
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
```

I tried report type 'GET_MERCHANT_LISTINGS_ALL_DATA', It response the data that I need

I want to know whether that three report types can be requested.

**Comment by abuzuhri** [comment]
Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by dishcheng** [comment]
> Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

Thanks,but I use php,not C#

**Comment by IgniteMosquito** [comment]
Does your app have access to Fulfilment reports scope (for FBA) and Brand Analytics (for search terms?).
The FBA reports are for Seller Central only.
The Search Terms report is for Vendor Central only.

So you will have to use separate tokens for these reports.

**Comment by ShivikaK** [comment]
Hello @dishcheng 

Thank you for raising this issue.

The reports stated above for which you are receiving access denied error require different role to be added to your application. Please verify that you have the necessary role for the report types and try again.

For reference, below documentation describes all the roles available in SP API -

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md

**Comment by peter200694013** [comment]
Hello @ShivikaK,

I have the same issue, which role is needed for report GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT? There is no explain for it in oles-in-the-Selling-Partner-API.md.

Thanks,
Peter
