### ISSUE TITLE
Is there a way to register as a developer to Amazon's SP-API using a Vendor account?

### ISSUE THREAD

**Issue by tallipits** [amzn/selling-partner-api-docs#16]
Hi,
I'd like to register as a developer to the new Selling Partner API (SP-API) by Amazon. This [doc ](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-as-a-developer) says I can do so using Seller Central, but I have a Vendor account, and therefore I need to use the Vendor Central.

Is there a way to do that?

**Comment by cafeasp** [comment]
Yes, login to your vendor central and submit a ticket under Support->Contact Us->API Integration->Registration and access->Send an email. Make sure you include your IAM, ARN info and make sure you are an administrator in vendor central and your vendor code.

**Comment by LemarinelNet** [comment]
Almost same question : 
I'm a freelance, and one of my customers wants me to dev some APIs for his stock management software.
He has a SellerCentral account, but I don't.
He already tried to register his developper profile, but did answer the form without understanding the technical questions, so he has been refused ...
So, do I need to sign-up a sellercentral pro/paid account to be able to dev around API (like MWS did required until now), or do SP-API allows me to dev, and he will just have to authorize my application ?

Thanks for your answers !

**Comment by evdeg** [comment]
> 
> 
> Yes, login to your vendor central and submit a ticket under Support->Contact Us->API Integration->Registration and access->Send an email. Make sure you include your IAM, ARN info and make sure you are an administrator in vendor central and your vendor code.

@cafeasp Thank you for your answer! 

@tallipits The answer provided by @cafeasp is the correct procedure for Vendors to get access to the Vendor API's that are available in SP-API. Eventually we are planning to bring the docs and models for Vendor API together in GitHub as well. Right now they are only available in Vendor Central. However, in order to register for Vendor API you will still need to use Vendor Central regardless. 

@LemarinelNet For the other Selling Partner API's currently listed in this repository you will need to use Seller Central to register for access and you do need a pro selling account in order to do so. Once you have registered as a developer and created your application then your customer (the seller) and any other sellers can authorize your application.

**Comment by evdeg** [comment]
@tallipits The [Selling Partner API Developer Guide For Vendors](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuideForVendors.md) is available in this repo now and it has instructions specifically for vendor access.

Thanks!
Evan

**Comment by tallipits** [comment]
@evdeg thanks for the reference.

I do see under the link provided, at step 6 the following steps:

To register your application
1.  Sign in to Vendor Central using the credentials that you used to register as a developer.
2. In the Integration dropdown menu, Click API Integration. The Developer Central page will appear.
3. ...

I cannot follow up on step #2 because I cannot find Integration dropdown menu.
What am I missing?

Thanks,
Tal

**Comment by tallipits** [comment]
@cafeasp thanks for your reply.

I've logged into [vendor central](https://vendorcentral.amazon.com) using my account and under  `Support->Contact Us` I couldn't find `API Integration`. 

What am I doing wrong?

Thanks,
Tal

**Comment by rakeshsivaji** [comment]
@evdeg  I am not able to register in vendor central  account

**Comment by Priyankk18k** [comment]
I'm not able to Register as a developer and get my Developer Id, Access key, and secret key. In the new SP-API doc it says the developer central page will appear and you have to follow the instruction to register but I'm unable to find any instruction on the developer central page. Can Anyone help?

**Comment by jessej3000** [comment]
I tried to register in seller central... but the sms verification is not sending me an OTP...

**Comment by jessej3000** [comment]
If I try "call"... it will say "Called too early"

**Comment by jessej3000** [comment]
Seems like if you are from a different country other than the US registering as an sp-api is not possible...
