### ISSUE TITLE
Exchange LWA authorization code for LWA refresh token with version=beta

### ISSUE THREAD

**Issue by gasper-vrhovsek** [amzn/selling-partner-api-docs#160]
Does [this](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-your-application-exchanges-the-lwa-authorization-code-for-a-lwa-refresh-token) work with an application in `DRAFT` state? Or do we have to have an approved application?

Best regards,
Gasper

**Comment by uk-2** [comment]
it works in draft state i believe

**Comment by gasper-vrhovsek** [comment]
Hm, this is strange. With our application in draft i can execute steps from 1.-3. and receive the spapi_oauth_code. But when i try to exchange that code for a LWA access and refresh tokens LWA rejects the code. Is there anything similar to the `version=beta` parameter for `/auth/o2/token` call?

**Comment by wanghuoling** [comment]
what's  amazon return message ?

**Comment by wanghuoling** [comment]
my application is DRAFT  state too. but i don't meet this problem.

**Comment by gasper-vrhovsek** [comment]
When calling the `/auth/o2/token` we get this return message:

`{"error_description":"The request has an invalid parameter : code","error":"invalid_request"}%`

We're currently doing it manually, so i suspect we're not in the 4.5 second time limit described [here](https://developer.amazon.com/en-US/docs/alexa/account-linking/configure-authorization-code-grant.html#overview-of-the-authorization-code-grant-flow). Although this is alexa account linking docs, it uses the same endpoint. And i would assume the same 4.5 second limitation. 

@wanghuoling you can go with the whole authorization flow with your app in draft state? You receive the access and refresh tokens? Can you then call the SP_API with those tokens?

**Comment by Abbotton** [comment]
@gasper-vrhovsek Hi, Gasper, I got problem too. Are you solve this?

**Comment by rugved1991** [comment]
Hi @gasper-vrhovsek @wanghuoling,

If you are still seeing this issue please let us know. The "version=beta" flag is only used while the application is in the "Draft" status. 

Best,
Rugved
Solutions Architect, SP API

**Comment by vmishra-godaddy** [comment]
> Hi @gasper-vrhovsek @wanghuoling,
> 
> If you are still seeing this issue please let us know. The "version=beta" flag is only used while the application is in the "Draft" status.
> 
> Best, Rugved Solutions Architect, SP API

@rugved1991 I am getting the same error.

{"error_description"=>"The request has an invalid grant parameter : code", "error"=>"invalid_grant"}
