### ISSUE TITLE
Permit Hybrid Apps without MWS developer IDs for all 3 regions (e.g NA only) to be authorizable by new sellers in any region

### ISSUE THREAD

**Issue by JTimings** [amzn/selling-partner-api-docs#1601]
We have a published hybrid application. The hybrid app only has a NA Developer ID associated with it (since we were never issued EU and FE Developer IDs and can no longer obtain these). In this scenario it appears a hybrid app cannot be authorized by an EU or FE seller. The error message MD5100 is returned with API response:

```
{
  "messageCode": "INVALID_INPUT",
  "errorMessage": "Invalid input from dependency:MarketplaceApplicationPermissionsService",
  "messageProperties": {
    "MarketplaceApplicationPermissionsService": "The permission has MWS role but no configured MWS AccountId for authorization for application : amzn1.sellerapps.app.XXX"
  }
}
```

We wouldn't expect to gain MWS access to EU or FE sellers (only NA sellers since we have developer ID for this), but sellers from any region should be able to authorize our app for sp-api access only without hitting an error.

Otherwise hybrid apps are useless for developers without all 3 regional developer IDs who want to expand their app usage to other regions in future.

**Comment by norberttech** [comment]
same problem here 😢

**Comment by ShivikaK** [comment]
Hello @JTimings 

Thank you for raising this issue.

We will investigate this and get back to you with next steps.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by JTimings** [comment]
Hi @ShivikaK thanks for the reply. Do you have a rough ETA for looking into this? It's a blocker for us currently.
