### ISSUE TITLE
[BUG] Documentation Feed xml ill-formed

### ISSUE THREAD

**Issue by Toqu-tang** [amzn/selling-partner-api-docs#1603]
When I created a feed and uploaded the xml as below:
`<?xml version="1.0" encoding="UTF-8" ?> <AmazonEnvelope> <Header> <DocumentVersion>1.01</DocumentVersion> <MerchantIdentifier>A3G9058027Y8NP</MerchantIdentifier> </Header> <MessageType>OrderFulfillment</MessageType> <Message> <MessageID>1</MessageID> <OrderFulfillment> <AmazonOrderID>112-2992556-4457039</AmazonOrderID> <FulfillmentDate>2021-11-01T06:28:29-07:00</FulfillmentDate> <FulfillmentData> <CarrierCode>UPS</CarrierCode> <ShippingMethod>UPS Mail Innovations</ShippingMethod> <ShipperTrackingNumber>92748963438445543484654335</ShipperTrackingNumber> </FulfillmentData> <Item> <AmazonOrderItemCode>07311545772442</AmazonOrderItemCode> <Quantity>1</Quantity> </Item> </OrderFulfillment> </Message> </AmazonEnvelope>`

It returned me an error "The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 1, column 706";

But when I reduce by two characters such as below:
1.Change the `<MerchantIdentifier>A3G9058027Y8NP</MerchantIdentifier>` to `<MerchantIdentifier>A3G9058027Y8</MerchantIdentifier>`
2. Or change the `<ShipperTrackingNumber>92748963438445543484654335</ShipperTrackingNumber>` to `<ShipperTrackingNumber>9274896343844554348465</ShipperTrackingNumber>`
It will return success.
But in fact, I should not change my real MerchantIdentifier or real ShipperTrackingNumber.
So would you mind helping me solve this problem?

**Comment by 18811409790** [comment]
The api is "/feeds/2020-09-04/documents" SP API

**Comment by shahviren1985** [comment]
Try this one -

<?xml version="1.0"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              	xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.01</DocumentVersion>
		<MerchantIdentifier>A3G9058027Y8NP</MerchantIdentifier>
	</Header>
	<MessageType>OrderFulfillment</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<OrderFulfillment>
			<AmazonOrderID>112-2992556-4457039</AmazonOrderID>
			<FulfillmentDate>2021-11-01T06:28:29-07:00</FulfillmentDate>
			<FulfillmentData>
				<CarrierCode>UPS</CarrierCode>
				<ShippingMethod>UPS Mail Innovations</ShippingMethod>
				<ShipperTrackingNumber>92748963438445543484654335</ShipperTrackingNumber>
			</FulfillmentData>
			<Item>
				<AmazonOrderItemCode>07311545772442</AmazonOrderItemCode>
				<Quantity>1</Quantity>
			</Item>
		</OrderFulfillment>
	</Message>
</AmazonEnvelope>

**Comment by shahviren1985** [comment]
![image](https://user-images.githubusercontent.com/4075110/140962847-e7c216b4-a17a-40f6-96d4-1b94ca337571.png)
