### ISSUE TITLE
[BUG] 400 Bad Request when using NextToken on GetOrder

### ISSUE THREAD

**Issue by neatokara** [amzn/selling-partner-api-docs#1606]
I am still receiving a 400 Bad Request response, when calling the /orders/v0/orders endpoint.

This bug #812 was closed and said to be resolved using url encoding, although is still not working for me on this specific endpoint. 

Can this issue be reopened and looked back into?

Thank you

**Comment by MichaelLan** [comment]
Hi @neatokara, I'm getting the same response (Error 400), I encode url and it doesn't work, have you found any solution?

**Comment by fernadodemitropulos** [comment]
I have the same problem, can someone help us?

**Comment by papaDhk** [comment]
Can you try decreasing the `MaxResultsPerPage ` request parameter value?
It may be related to the response data size.

**Comment by flagile** [comment]
this problem for order api is still existing, could you pls have to fix? thank you very much @ShivikaK [ShivikaK(https://github.com/ShivikaK)
