### ISSUE TITLE
how to import the JAVA library after generate a Java SDK with LWA token exchange.

### ISSUE THREAD

**Issue by luisjorp** [amzn/selling-partner-api-docs#161]
Im having some problems trying to connect to the Selling Partner API using a generated Java SDK.
Im using Java but I dont know how and what to import to my java project.
I tried to import the client directory but I get the next error alert
<img width="1161" alt="Captura" src="https://user-images.githubusercontent.com/6946476/100627632-d6a8f600-32ec-11eb-85b0-bee36c35be25.png">
 Thanks for helping me! :)

**Comment by ShivikaK** [comment]
Hi @luisjorp 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support
