### ISSUE TITLE
The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 21, column 18

### ISSUE THREAD

**Issue by AceGray** [amzn/selling-partner-api-docs#1612]
send  POST_ORDER_FULFILLMENT_DATA  xml content
<?xml version="1.0" encoding="UTF-8"?>
<amazonenvelope xsi:nonamespaceschemalocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <documentversion>1.01</documentversion>
        <merchantidentifier>zhengbohebohe@163.com</merchantidentifier>
    </header>
    <messagetype>OrderFulfillment</messagetype>
    <message>
        <messageid>1</messageid>
        <operationtype>Update</operationtype>
        <orderfulfillment>
            <amazonorderid>702-8070817-3981849</amazonorderid>
            <fulfillmentdate>2021-11-04T09:40:06Z</fulfillmentdate>
            <fulfillmentdata>
                <carriername>Canada Post</carriername>
                <shippingmethod>Canada Post</shippingmethod>
                <shippertrackingnumber>1023038796604735</shippertrackingnumber>
            </fulfillmentdata>
        </orderfulfillment>
    </message>
</amazonenvelope>

return 
The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 21, column 18

**Comment by shahviren1985** [comment]
Can you share the xml data you are pushing? May be I can have a look at it?
and also request content type

**Comment by yingyuhaonan** [comment]
我得windows可以linux不行，我真的是头秃

**Comment by yingyuhaonan** [comment]
> Can you share the xml data you are pushing? May be I can have a look at it? and also request content type

大哥，你们解决了没有啊
