### ISSUE TITLE
getCatalogItem endpoint bug

### ISSUE THREAD

**Issue by SteveNavarc** [amzn/selling-partner-api-docs#1613]
Hi 
Our selling partner is registered with all their brands yet when I pass the includeData param  I get back the following error for most of the asins. 

"The includedData requested requires Brand Registry affiliation with the requested item. Remove the requested includedData item or register the brand of the item in Brand Registry with the seller."

The weird part is that for some products we get the attributes, but for the others the API doesnt return anything.  

Is there something else we need to be doing? 

Thank you!

**Comment by chapmanjw** [comment]
Hello @SteveNavarc,

We removed the requirement for brand registry affiliation for the attributes data in September. You should be able to request that for any item now. 

Thanks!
