### ISSUE TITLE
[BUG] Multiple Marketplaces = Incomplete Data in Reports

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#1614]
**Describe the bug**
I have tested these reports with multiple sellers:
GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
GET_MERCHANT_LISTINGS_ALL_DATA

It may be affecting others. 

- When requesting with multiple marketplace IDs in the request, I would expect to receive the inventory or merchant listing reports containing all products for those marketplaces
- However, the reports in the response seem only contain data for 1 seemingly randomly chosen marketplace
- Therefore, requesting a report for 1 marketplace (e.g. Germany) is accurate, but for multiple you end up with a random marketplace that may include less data than

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md

**Description of what the documentation currently says**
Documentation suggests that multiple marketplaces can be entered. 

**Description of what the documentation should say**
Either this is a bug in the SP API itself, or it should be made clear that one marketplace ID should be used at a time to retrieve complete data. 

**Screenshots**

**Additional context**

**Comment by jlevers** [comment]
+1 -- I've run into this same issue recently. The documentation makes it seem that if you supply multiple marketplace IDs, you should get data for all listings in all marketplaces, but actually you just get a single marketplace's data (but there's no way of knowing _which_ marketplace that data is for).

**Comment by moltar** [comment]
> +1 -- I've run into this same issue recently. The documentation makes it seem that if you supply multiple marketplace IDs, you should get data for all listings in all the marketplaces you specify, but actually you just get a single marketplace's data (but there's no way of knowing _which_ marketplace that data is for).

Yeah, a bit insane if you ask me...

**Comment by Javadebi** [comment]
+1
I have the same issue and for example if you want to seperate marketplaces with currency you get a problem with europe same currency.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
