### ISSUE TITLE
How to get Feed Result Document? (/feeds/2020-09-04/documents/{feedDocumentId} Returns Forbidden)

### ISSUE THREAD

**Issue by tenitre** [amzn/selling-partner-api-docs#162]
I am able to submit the feed without a problem, also able to get Feed using FeedId (/feeds/2020-09-04/feeds/{feedId}). 

This issues is whenever I try to get feed document using the feeddocumentId provided with /feeds/2020-09-04/feeds/{feedId} I have got Forbidden Error

Note that I am using ResultFeedDocumentId to try to retrieve the result of the feed submission

Anyone has experienced this?

**Comment by JacksonJeans** [comment]
Hello @tenitre ,

can you show me your canonical request? Maybe the devil hides here in the small details of processing and transmitting your request.

**Comment by tenitre** [comment]
Hi @JacksonJeans 

Thank you for chiming in, here is my canonical request:

GET
/feeds%25E2%2580%258B/2020-09-04%25E2%2580%258B/documents%25E2%2580%258B/amzn1.tortuga.3.c9daf3fc-dbe5-4eb0-aacc-0584df5468de.T8EQUAZLRGFJC

host:sellingpartnerapi-na.amazon.com
x-amz-access-token:Atza|IwEBIGS-apkrcrUeNUC-qNq_4r9K-KnQJf27xDbFxK7******************************************ClrhyqjMHVSx_z2QWAbu2ZJLNGGYDcay6stP9Dlsmot4OvcvIwBtugsPE75W
x-amz-date:20201201T155408Z
x-amz-security-token:FwoGZXIvYXdzEBkaDEC/IoxS3HqNe834MyLIAYfCpxFwxMeKXiTvwZoWGavlTJOFCkPk**********************************EOQ=

content-type;host;x-amz-access-token;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855


The weird thing is I don't know where these things come from "%25E2%2580%258B"

thanks
Oz

**Comment by JacksonJeans** [comment]
@tenitre ,

Here is my canonical query. Yours should look like this in the end.

```
GET
/feeds/2020-09-04/documents/amzn1.tortuga.3.06934726-f85b-489e-8d3e-bc5e7b365517.T3F29I2DR45WMN/

content-type:application/json ;charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:Julian Tietz(Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201201T160834Z

content-type;host;user-agent;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
Here I get an answer with the status 200 and the corresponding file as URL.

1. Your encoding of the URI looks very strange. Make sure that the encoding is the one given in the [documentation](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html).

2. You specify `content-type` as a signed header, but `content-type` is not in your canonical request as a header.

**Comment by tenitre** [comment]
@JacksonJeans 

Thank you for the tip... that was the problem..

 - I was testing whether i need to provide xml as my content type so I forgot it there.

-  The real issue was the weird chars in the path, the thing is I copied the path from swagger editor and pasted it into Visual Studio so these chars are being carried there even though you dont see them... 

best
Oz
