### ISSUE TITLE
[BUG] fba/inbound/v0/shipments  with DateRange QueryType get error

### ISSUE THREAD

**Issue by guoliesheng** [amzn/selling-partner-api-docs#1620]
When calling fba/inbound/v0/shipments with DateRange query params always giving ErrorMessage:'At least one of ShipmentStatusList and ShipmentIdList must be provided' error.
In my opinion, why should I add status or id params when I just want to query shioment in specify date range

**Comment by adeelsohailahmed** [comment]
This bug is still present as of now.
