### ISSUE TITLE
Phase 2 for New Product Types and Template changes are not available

### ISSUE THREAD

**Issue by alisonheld-channeladvisor** [amzn/selling-partner-api-docs#1622]
The changes that were called out in the announcement below as live as of Sept 30th are not actually in any XSDs. Can anyone confirm **when** we will actually see these changes reflected in the XSDs? This announcement implies that they are available now.

### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/1617

<div type='discussions-op-text'>

<sup>Originally posted by **jenilew** November  4, 2021</sup>
Hi All,

As previously announced on July 14th, Amazon is launching new Product Types across XSDs worldwide. The goal is to enable enhanced product search and a simplified product overview by surfacing key product information in a structured format at the top of product detail pages instead of unstructured bullet points. This will help customers to read through the top product specifications, evaluate key differences between products and make purchase decisions quicker.

This second phase of new Product Types are available as of September 30, 2021. You can [download the list of affected Product Types](hhttps://m.media-amazon.com/images/G/01/SPEx/XSD_PreProd/Phase_2/PT_XSD_Links_Phase-2._CB1198675309_.xlsx) with the corresponding XSD categories in Microsoft Excel format (.xlsx).

For each new Product Type, you can view the XSD by clicking the link in the Microsoft Excel list. 

#### Which marketplaces are affected?
This change applies to all marketplaces.

#### Who is affected?
Developers with applications that upload and update product listings using feeds based on the category-specific inventory file templates and XSDs are affected by this change.

#### What action is required?
If you have an application that is affected by this change, be sure to adjust your application workflow on the category-specific file templates and XSD templates listed [here](https://m.media-amazon.com/images/G/01/SPEx/XSD_PreProd/Phase_2/PT_XSD_Links_Phase-2._CB1198675309_.xlsx).

</div>

**Comment by alisonheld-channeladvisor** [comment]
@jenilew - Please see this question about your recent announcement on Phase 2 changes.

**Comment by jenilew** [comment]
Hi @alisonheld-channeladvisor,

There is a link to the affected product types and XSD template links in the last line of the announcement. Each product type in the list has a corresponding link to the XSD.

Are you not able to navigate to the XSD templates linked from that file?

Thank you,

Jenilew
Amazon Selling Partner Team

**Comment by alisonheld-channeladvisor** [comment]
Jenilew,

We are able to access these and see the PreProd XSDs but we cannot adjust our templates because the XSD changes aren't in production. The message seems to imply that they are now live in the production XSDs. 

Because the links in the file are still PreProd we are still waiting on go live, is that accurate? Is there an ETA on when the XSDs will be live?
