### ISSUE TITLE
[BUG] GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT 

### ISSUE THREAD

**Issue by peter200694013** [amzn/selling-partner-api-docs#1626]
>REQUEST：/reports/2020-09-04/reports
CreateReportSpecification
{
    "reportType": "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
    "reportOptions": {
        "reportPeriod": "DAY"
    },
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ],
    "dataStartTime": "2021-11-01T00:00:00Z",
    "dataEndTime": "2021-11-01T00:00:00Z"
}

>RESPONSE：
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}

Available to selling partners who have the **Brand Analytics Selling Partner API role** and who are registered in Amazon's Brand Registry.

There isn't the role "Brand Analytics Selling Partner API role" in the document - https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md

**Comment by etsourcing2** [comment]
I got the same question!

**Comment by dangquanghai** [comment]
I has the same question!

**Comment by shirushi-dev** [comment]
me too 😭

**Comment by moltar** [comment]
Here they said it is not ready for public yet 🙄 

https://github.com/amzn/selling-partner-api-docs/issues/1032#issuecomment-926871408

**Comment by peter200694013** [comment]
> Here they said it is not ready for public yet roll_eyes
> 
> [#1032 (comment)](https://github.com/amzn/selling-partner-api-docs/issues/1032#issuecomment-926871408)

Thanks for your answer.

**Comment by MohanKittusamy** [comment]
Still the same issue exist

**Comment by MohanKittusamy** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/108753388/193444836-4191f9dd-8af2-4ec0-aa81-8c599577464d.png">

**Comment by michelexport** [comment]
Is the report now available?

**Comment by RMagician** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/2351
