### ISSUE TITLE
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE and ListFinancialEvents return "Access to requested resource is denied.", required  roles are added 

### ISSUE THREAD

**Issue by greatbag** [amzn/selling-partner-api-docs#1627]
Hello @ShivikaK ,
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE and ListFinancialEvents return "Access to requested resource is denied.", required  roles are added ,please look in.
appId ：amzn1.sp.solution.e6a1a39f-80ef-42df-a208-37780f23a095
![image](https://user-images.githubusercontent.com/35184007/140632909-0c51d876-6f8c-4246-9f4e-ad0254df7469.png)
![image](https://user-images.githubusercontent.com/35184007/140632941-27a8323e-5892-4846-a16c-4bc5321ab489.png)

**Comment by shahviren1985** [comment]
Even I am getting error to access GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE & GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 report.

I am not sure if this report falls under Tax invoicing. I don't have access to tax invoicing, but then I should get access denied error. Here I am getting bad request error with request is not allowed temporarily. 

However we are not getting access denied but we are getting 
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Request for report type 1117 is not allowed at this time",
            "details": ""
        }
    ]
}

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Request for report type 1118 is not allowed at this time",
            "details": ""
        }
    ]
}

**Comment by rohitdobariya** [comment]
@greatbag Mostily the issue in generating the AWS and Seller central SP-API credentials. 
@shahviren1985 its not falls in RDT you can review here :: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md

**Comment by rohitdobariya** [comment]
@greatbag you can join and will check 
 https://join.skype.com/y5ot7Hev0apY
