### ISSUE TITLE
Internal Server Error calling APIs

### ISSUE THREAD

**Issue by felixcheruiyot** [amzn/selling-partner-api-docs#163]
My setup is on Python3 using Python's requests library.

I have the app created from Seller Central and LWA tokens from https://developer.amazon.com/. I'm able to authorize requests and generate an access token.

I'm also able to assume the role and parse the results in my request:

```
def assume_role():
    client = boto3.client("sts")
    response = client.assume_role(
        RoleArn=ARN_ROLE,
        RoleSessionName=uuid4().hex
    )
    content = response.get("Credentials")
```

Here is the request I'm sending:

`{
    'method': 'GET',
    'url': 'https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders/?MarketplaceIds=ATVPDKIKX0DER',
    'headers': {
        'user-agent': 'Jeto/build1611 (Language=Python3; Host=sellerscentral.example.com)',
        'Accept-Encoding': 'gzip, deflate',
        'Accept': '*/*',
        'Connection': 'keep-alive',
        'x-amz-security-token': 'FwoGZ..........',
        'x-amz-date': '20201201T062643Z',
        'host': 'sandbox.sellingpartnerapi-na.amazon.com',
        'x-amz-access-token': 'Atza......',
        'Authorization': 'AWS4-HMAC-SHA256 Credential=ASIAUC2DTN...../20201201/us-east-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date, Signature=90ac8b1a7f6562eada1063a7ec0de04f4fc9d2e5ae006cc6b6adac2ce4812ba9',
        'Content-Type': 'application/x-amz-json-1.0'
    },
    '_cookies': < RequestsCookieJar[] > ,
    'body': None,
    'hooks': {
        'response': []
    },
    '_body_position': None
}`

I'm getting a 500 error code with the following error description: The region is `us-east-1`:

```
{
  "errors": [
    {
      "message": "We encountered an internal error. Please try again.",
     "code": "InternalFailure"
    }
  ]
}
```

**Comment by rogersv** [comment]
It usually happens when you are not using the exact parameters defined for the sandbox. Check for the sandbox calls defined in the swagger file.

**Comment by felixcheruiyot** [comment]
Hi @rogersv 

Thank you for your support.

I've added the following querystring parameters as per https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json#L156 and I still getting the error:

```
querystr = "CreatedAfter=TEST_CASE_200"
querystr +="&MarketplaceIds=ATVPDKIKX0DER"
```

Below is my full code for this piece:
`def list_items(access_token):
       endpoint = "https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders"
       marketplace_id = "ATVPDKIKX0DER"
       CreatedAfter = "TEST_CASE_200"
       querystr = "CreatedAfter=TEST_CASE_200"
        querystr +="&MarketplaceIds=ATVPDKIKX0DER"
    
    assumed_role = assume_role()
    x_amz_security_token = assumed_role.get("SessionToken")

    access_key = assumed_role.get("AccessKeyId") #AWS_ACCESS_KEY_ID
    secret_key = assumed_role.get("SecretAccessKey") #AWS_SECRET_ACCESS_KEY
    region = "us-east-1"
    service = "execute-api"
    host = "sandbox.sellingpartnerapi-na.amazon.com"
    content_type = "application/x-amz-json-1.0"
    t = datetime.datetime.utcnow()
    amzdate = t.strftime('%Y%m%dT%H%M%SZ')
    date_stamp = t.strftime('%Y%m%d')
    amz_target = ''
    user_agent = "Jeto/build1611 (Language=Python3; Host=sellerscentral.jeto.digital)"
    signed_headers = 'host;user-agent;x-amz-access-token;x-amz-date'
    method = 'GET'
    canonical_uri = '/orders/v0/orders'
    canonical_querystring = querystr
    canonical_headers = 'host:' + host + '\nuser-agent:'+user_agent + \
        '\n'+'x-amz-access-token:'+access_token +\
        '\n' + 'x-amz-date:' + amzdate+"\n"
    payload_hash = hashlib.sha256(('').encode('utf-8')).hexdigest()

    canonical_request = method + "\n" + canonical_uri + "\n" + canonical_querystring + "\n" + \
        canonical_headers + "\n" + signed_headers + "\n" + payload_hash

    algorithm = 'AWS4-HMAC-SHA256'
    credential_scope = date_stamp + '/' + region + \
        '/' + service + '/' + 'aws4_request'
    string_to_sign = algorithm + '\n' + amzdate + '\n' + credential_scope + \
        '\n' + hashlib.sha256(canonical_request.encode('utf-8')).hexdigest()
    signing_key = getSignatureKey(secret_key, date_stamp, region, service)

    # Sign the string_to_sign using the signing_key
    signature = hmac.new(signing_key, (string_to_sign).encode(
        'utf-8'), hashlib.sha256).hexdigest()
    authorization_header = algorithm + ' ' + 'Credential=' + access_key + '/' + \
        credential_scope + ', ' + 'SignedHeaders=' + \
        signed_headers + ', ' + 'Signature=' + signature
    

    headers = {'x-amz-security-token': x_amz_security_token, 'x-amz-date': amzdate, 'user-agent': user_agent, 'host': host,
               'x-amz-access-token': access_token, 'Authorization': authorization_header, 'Content-Type': content_type}
    request_url = endpoint + '?' + canonical_querystring
    
    resp = requests.get(url=request_url, headers=headers)
    print(resp.text)
    print(f'Response code: {resp.request.__dict__}')

`

**Comment by felixcheruiyot** [comment]
I'm still struggling with the issue.

I've tried everything and even toggle both live and sandbox endpoints and still not working. 

I even decided to redo it in NodeJS just in case it was an issue with the Python request library and still no success.

**Response**

```
{
  errors: [
    {
      message: 'We encountered an internal error. Please try again.',
      code: 'InternalFailure'
    }
  ]
}
```

**Code:**

```
const axios = require('axios')
const aws4 = require('aws4')
const aws_sdk = require('aws-sdk');

require('dotenv-defaults').config()

aws_sdk.config.update({
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    region: 'us-east-1',
})
aws_sdk.config.region = 'us-east-1'
aws_sdk.config.credentials.accessKeyId = process.env.AWS_ACCESS_KEY_ID
aws_sdk.config.credentials.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY

const ROLE_ARN = process.env.ROLE_ARN
const ACCESS_TOKEN = 'Atza|IwE........'

async function orderRequest() {
    new aws_sdk.STS().assumeRole({
        RoleArn: ROLE_ARN,
        RoleSessionName: 'sp-909'
    }, function (err, resp) {
        if (err) throw new Error(err)
        let accessKeyId = resp.Credentials.AccessKeyId
        let secretAccessKey = resp.Credentials.SecretAccessKey
        let sessionToken = resp.Credentials.SessionToken
        let opts = buildRequestOptions(ACCESS_TOKEN, accessKeyId, secretAccessKey, sessionToken)

        opts.data = ""
        opts.url = 'https://' + opts.host + opts.path
        opts.method = 'get'
        axios(opts).then((resp) => {
            console.log(resp.data)
        }).catch((err) => {
            console.error(err.response.data)
        })
    })
}

function buildRequestOptions(access_token, accessKeyId, secretAccessKey, sessionToken) {
    const opts = aws4.sign({
        host: 'sandbox.sellingpartnerapi-na.amazon.com',
        method: 'GET',
        path: '/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER&CreatedAfter=TEST_CASE_200',
        region: 'us-east-1',
        service: 'execute-api',
        headers: {
            'User-Agent': 'JejoDigital/1.0 (Language=JavaScript; Platform=Ubuntu/16)',
            'x-amz-access-token': access_token

        }
    }, {
        accessKeyId: accessKeyId,
        secretAccessKey: secretAccessKey,
        sessionToken: sessionToken
    })
    return opts;
}

orderRequest()
```

This is draining, worked on it for more than 2 weeks. I need help in troubleshooting it.

Thanks.

**Comment by rogersv** [comment]
Hi @felixcheruiyot, do you still get a 500 or do you get a new error?

**Comment by felixcheruiyot** [comment]
> Hi @felixcheruiyot, do you still get a 500 or do you get a new error?

I'm getting 500

**Comment by felixcheruiyot** [comment]
> Hi @felixcheruiyot, do you still get a 500 or do you get a new error?

This is the error description with status 500.

```
{
  errors: [
    {
      message: 'We encountered an internal error. Please try again.',
      code: 'InternalFailure'
    }
  ]
}
```

Thank you very much for reaching out.

**Comment by rogersv** [comment]
I think this is your problem `request_url = endpoint + '?' + canonical_querystring`. You should use the original query string.

**Comment by felixcheruiyot** [comment]
> I think this is your problem `request_url = endpoint + '?' + canonical_querystring`. You should use the original query string.

I have tried it with `querystr`, and I get the same error. The variable `canonical_querystring` is actually the same as `querystr` as in the above. 

They both end up building the same result > https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders/?MarketplaceIds=ATVPDKIKX0DER&CreatedAfter=TEST_CASE_200

I was following this example https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html and I've figured out it was unnecessary to reasign `querystr`

**Comment by KevinJ1978** [comment]
Did anyone get this resolved?  I'm having the same issue, I can make successful POST requests, but all GET request return the 500 response metioned above.

**Comment by felixcheruiyot** [comment]
Unfortunately, I was not able to get it done. Good to hear you were able to do a POST, I'll test mine later tomorrow and let you know if it works then we can zero in the issue to be around GET requests.

**Comment by BeeBee234** [comment]
Howdy,

For the C# folks out there, using the code example in https://github.com/amzn/selling-partner-api-models/issues/31 with the sandbox and substituting the following works (if your credentials are all lined up correctly):

            var resource = $"/orders/v0/orders";
            IRestRequest restRequest = new RestRequest(resource, Method.GET);
            restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
            restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);

For reference when I was testing /vendor/orders/v1/purchaseOrders using the following, I got "Internal Server Error, Please Try Again.":

            // the following returns "Internal Server Error, Please Try Again."
            restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);
            restRequest.AddParameter("MarketplaceIds", "[\"ATVPDKIKX0DER\"]", ParameterType.QueryString);

or

            //the following returns "Internal Server Error, Please Try Again."
            restRequest.AddParameter("CreatedAfter", "{\"value\": \"TEST_CASE_200\"}", ParameterType.QueryString);
            restRequest.AddParameter("MarketplaceIds", "{\"value\": [\"ATVPDKIKX0DER\"]}", ParameterType.QueryString);

The following finally worked:

            restRequest.AddParameter("createdAfter", "2019-08-20", ParameterType.QueryString);
            restRequest.AddParameter("createdBefore", "2019-09-21", ParameterType.QueryString);

...which tells me that the "Internal Server Error" message is bogus and you are on the right track when you see it.

Good luck and have a beautiful day,

Brian

**Comment by pprbhm** [comment]
Hi @felixcheruiyot Were you able to solve the issue through community help and the documentation provided here in Repository. If u still require help, please open a [Support Case](https://developer.amazonservices.com/support) with Developer Support team for detailed troubleshooting.
Thank you

**Comment by coder771** [comment]
@BeeBee234 I'm passing in values same as in your first screenshot still getting the error. do you know what it could be
