### ISSUE TITLE
Generating report for GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 resulting in error Request for report type 1118 is not allowed at this time

### ISSUE THREAD

**Issue by shahviren1985** [amzn/selling-partner-api-docs#1633]
POST Request URL - https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports

Request Body - {
  "reportType": "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
  "marketplaceIds":["A21TJRUUN4KGV"]
}

Response - 400 bad request
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Request for report type 1118 is not allowed at this time",
            "details": ""
        }
    ]
}

**Comment by whitedevils** [comment]
any solution?

**Comment by 0573xieguojia** [comment]
Reports API-Settlement Reports
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Request for report type 1117 is not allowed at this time",
      "details": ""
    }
  ]
}

how CAN i fixed this issue? could anyone help with me.

**Comment by 0573xieguojia** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#settlement-reports

Settlement reports cannot be requested or scheduled. They are automatically scheduled by Amazon. You can search for these reports using the getReports operation.

**Comment by Anuj4444** [comment]
Hello @shahviren1985 

Have you got solution to this problem?
I am getting the same error. 
Please let me know

**Comment by stefnats** [comment]
@Anuj4444 if I'm not mistaking, then @0573xieguojia already gave the answer?!

**Comment by Anuj4444** [comment]
@shahviren1985 yes He gave answer, but this is kind of dead end, I was hoping if you got any solution to this issue.

**Comment by usman-rind** [comment]
> POST Request URL - https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports
> 
> Request Body - { "reportType": "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2", "marketplaceIds":["A21TJRUUN4KGV"] }
> 
> Response - 400 bad request { "errors": [ { "code": "InvalidInput", "message": "Request for report type 1118 is not allowed at this time", "details": "" } ] }

Did you get any solution please share it will be hepful.

**Comment by hugoganet** [comment]
Hello @usman-rind, those type of report cannot be requested or scheduled. 
You have to "skip the first step". 
Directly use the getReports operation, it doesn't take a reportId, only reportType.

Here is the doc for this operation : [Operation: getReports](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreport)
And here is the doc about the [Settlement report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement)

Hope it help.
