### ISSUE TITLE
GetMyFeesEstimateForSKU error when SellerSku contains "/" in its name

### ISSUE THREAD

**Issue by wineloy** [amzn/selling-partner-api-docs#1637]
Hello everyone I am trying to use the [GetMyFeesEstimateForSKU ](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-fees-api/productFeesV0.md#getmyfeesestimateforsku) operation, but some of my seller Sku contain the symbol * / * or * + *, which causes the URL to break since it takes it with a separator and does not escape it, I already tried coding the seller sku and the url complete, but I can't get it to work

**Comment by stefnats** [comment]
Could you please share a request and response?

**Comment by kpconnell** [comment]
+1 on this issue, not clear how to encode and sign a request with a / in it.

**Comment by wineloy** [comment]
@stefnats Sure for example the next Sku *EP-CAT-5E-V2/W* contain one slash 
the body of request is:
    {
        "FeesEstimateRequest" :{
            "MarketplaceId" :"xxxxxxxxxxxxxxxx",
            "PriceToEstimateFees":{
                "ListingPrice":{
                    "CurrencyCode":"MXN",
                    "Amount":316.65
                }
            },
            "Identifier":"1",
            "IsAmazonFulfilled": false,
            "SellerSku": **"EP-CAT-5E-V2/W"**
        }
    }

 Without Encode the Sku /products/fees/v0/listings/ **EP-CAT-5E-V2/W** /feesEstimate
 response Amazon: 
    {
      "errors": [
        {
          "message": "Access to requested resource is denied.",
         "code": "Unauthorized",
         "details": ""
        }
      ]
    }


when Encode URL with HttpUtility.UrlEncode or Any tool  /products/fees/v0/listings/ **EP-CAT-5E-V2%2fW** /feesEstimate

Reponse Amazon is:

    {
      "errors": [
        {
            "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
      The Canonical String for this request should have been
      'POST
      /products/fees/v0/listings/EP-CAT-5E-V2%252fW/feesEstimate",
    
         "code": "InvalidSignature"
        }
      ]
    }

Some Solution ??

**Comment by sreecodeslayer** [comment]
Why are these issues being closed when there is an apparent issue troubling many endpoints?
