### ISSUE TITLE
[BUG] Rate Limit Change for Amazon Fulfilled Shipments Data Report?

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#1641]
CaseID: 9185839181

**Describe the bug**
Until recently, we could create and download this report by staying within the rate limit of 0.0167 per second and ensuring we do not request the same report more than once every 30 mins as stated in documentation:

SP API: reports - POST /reports/2020-09-04/reports
Operation: createReport
reportType: GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL

But we are suddenly getting quota exceeded error messages: 
Response body: { "errors": [ { "code": "QuotaExceeded", "message": "You exceeded your quota for the requested resource."

Has there been a change to the rate limit? Can you update the documentation?

**URL of the content on GitHub**
Please provide the GitHub URL for the documentation where you see the bug.

**Description of what the documentation currently says**
Please describe the section/paragraph of the documentation where you see the bug.

**Description of what the documentation should say**
A clear and concise description of the guidance you expected to see in the documentation.

**Screenshots**

**Additional context**

**Comment by jimmy-ross-xapix** [comment]
same issue here

 https://github.com/amzn/selling-partner-api-docs/issues/1624

**Comment by JeromeXapix** [comment]
@jimmy-ross-xapix 
the issue occurred again for this new seller
- https://seller-reporting-sync.eu-west.xapix.io/sync_runs/144570

It seems to be working fine when re-syncing + It was not an issue here as no reports seem available anyway (CANCELLED) but we might want to still investigate this one as it seems that it is still occurring for  new sellers

**Comment by JeromeXapix** [comment]
Just noticed that we are getting the error every-time from the 13. api call on for the last 5 sellers we added for Suma.
Can we maybe add a temporisation between the calls as it seems that we are hitting the limit rate always?
