### ISSUE TITLE
[BUG] Documentation - Listings Items

### ISSUE THREAD

**Issue by GeorgeJalland** [amzn/selling-partner-api-docs#1643]
**Describe the bug**
In the 'Selling Partner API for Listings Items' reference document the product **'sku'** is required in the path for requests to this endpoint. Having tested this, I believe what is actually require is the product **'ASIN'**.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2021-08-01.md

**Description of what the documentation currently says**
the product 'sku' is required in the path for requests to this endpoint

**Description of what the documentation should say**
Having tested this, I believe what is actually require is the product 'ASIN'.

**Comment by GeorgeJalland** [comment]
Hi, any updates on this?

**Comment by chapmanjw** [comment]
The Listings Items APIs are for creating and managing listings on Amazon. Listings are keyed by seller-defined SKU identifiers. Once listings are submitted, they are associated with Catalog Items keyed by ASIN identifiers. Sellers can influence which ASIN their listings are associated with by means of various identifying product attributes, such as the merchant suggested ASIN or externally assigned product identifiers.

Sellers do not author data directly to Catalog Items by ASIN. Sellers create listings and Amazon reconciles listings data from one or more sellers into the Catalog Items.
