### ISSUE TITLE
Getting FATAL on GET_FBA_MYI_ALL_INVENTORY_DATA

### ISSUE THREAD

**Issue by rohitdobariya** [amzn/selling-partner-api-docs#1645]
@ShivikaK Please check and If anyone has any suggestions much appreciated.
1 ) I am getting FATAL when I try to get the report:: Report Type:: GET_FBA_MYI_ALL_INVENTORY_DATA
2 ) How I can check the report type is uses start time and end time or not? do we have any documents?
3 ) In the Settlement report not getting all the orders which are placed and delivered. Seems like a bug in API.

**Comment by jesusvalle** [comment]
I am having the same problem with GET_FBA_MYI_ALL_INVENTORY_DATA report, but only sometimes.

I make exactly the same request (without startDate and endDate), and sometimes it randomly returns DONE or FALSE.

I don't understand anything.

**Comment by hoellenpferd** [comment]
Same problem here (without startDate and endDate). Maybe there is some kind of hidden limitation?

**Comment by YueXiaolong** [comment]
> Same problem here (without startDate and endDate). Maybe there is some kind of hidden limitation?

I think so. My test shows that dulpicate request （with same datetime/date range）will get an FATAL error. 
But I don't know the limit-reset time.

**Comment by jesusvalle** [comment]
> > Same problem here (without startDate and endDate). Maybe there is some kind of hidden limitation?
> 
> I think so. My test shows that dulpicate request （with same datetime/date range）will get an FATAL error. But I don't know the limit-reset time.

I have been doing some tests (requesting a report per country in Europe), and the conclusion I have reached is that there is some kind of internal throtling of about 30 minutes for the same country. 

I did tests alternating different countries in blocks of 5, 10, 15, 20, 25 minutes, and they all gave fatal. Until I exceeded 30 minutes, I did not get a DONE status.

I have written to amazon mws support, to see if they can offer any information on this.

If someone can run a battery of tests to test my theory, that would be great.

**Comment by hoellenpferd** [comment]
Today I tried 6 API Calls for 6 different Marketplaces (With fresh quota). And every call was successful. If I try a second one I get the FATAL error. So I think I would have to wait a proper time to retry the call so I can confirm your theory.

**Comment by jesusvalle** [comment]
> Today I tried 6 API Calls for 6 different Marketplaces (With fresh quota). And every call was successful. If I try a second one I get the FATAL error. So I think I would have to wait a proper time to retry the call so I can confirm your theory.

Would you mind testing the call with the same country in blocks of 5 minutes to verify if we have approximately the same waiting time?

Thank you very much

**Comment by jesusvalle** [comment]
I received the following response from Amazon support:

> Thank you for your report.
> 
> After carefully review, I found the reason of report:251400018948 fails with status Cancelled/Fatal is because Throttling.
> 
> Please kindly check the link below, as per github, A near real-time FBA report is generated no more than once every 30 minutes. This means that after a near real-time FBA report is generated following your report request, a 30-minute waiting period must pass before Amazon will generate an updated version of that report.
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#fulfillment-by-amazon-fba-ro determine the best way to proceed, and we look forward to offering a solution sometime in the future.eports
> 
> Unfortunately, the system is designed like this, if the system cancelled the report because throttling , then as developer support team,we cannot control of it. At this time, we do not have plans to increase throttling thresholds. However, we are looking into the issue to determine the best way to proceed, and we look forward to offering a solution sometime in the future.

Therefore, we can confirm that the internal throtling is 30 minutes.

**Comment by hoellenpferd** [comment]
Thank you very much for the feedback!

**Comment by rohitdobariya** [comment]
Thanks you very much guys for the feedback.

**Comment by rohitdobariya** [comment]
Any Idea about **3 ) In the Settlement report not getting all the orders which are placed and delivered. Seems like a bug in API.**

**Comment by wbmgaye** [comment]
@jesusvalle would you happen to know which reports are considered near real time or are all fba reports considered near real time? Running into this issue with `GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA`

**Comment by YueXiaolong** [comment]
@wbmgaye Check the descrtiption of each report type, which shows `Near real time` or `Daily`. 
And `GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA` is updated every 3 days, check the desctiption: 
> The content is updated at least once every 72 hours. To successfully generate a report, specify the StartDate parameter for a minimum 72 hours prior to NOW and EndDate to NOW.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by hongfei-zhou** [comment]
Is this getting fixed?
