### ISSUE TITLE
[BUG] putTransportDetails results in 400 Bad Request

### ISSUE THREAD

**Issue by ericfragola** [amzn/selling-partner-api-docs#1647]
Removed

**Comment by ericfragola** [comment]
We've found that using IsPartnered is causing the issue 

We can proceed with non partnered SP and LTL but not partnered
Anyone else run into this same issue?

**Comment by bjpierre** [comment]
Love looking for an issue I'm having and seeing that someone had the issue I'm having, then resolved it and instead of posting the solution for others to use they deleted the question :)
