### ISSUE TITLE
CreateFeed MARS_AUTOMATE_PRICING_MULTI_MARKETPLACE_FEED returns 403

### ISSUE THREAD

**Issue by kaipaysen** [amzn/selling-partner-api-docs#1649]
I'm trying to migrate some Feeds related mws code to the SP-API. Uploading Feeds works fine with feedType "POST_FLAT_FILE_INVLOADER_DATA" but not with "MARS_AUTOMATE_PRICING_MULTI_MARKETPLACE_FEED". Same feed works fine with MWS.

Assigned Roles should not be an issue as all roles are checked. Any ideas what's wrong?

```
backend_1   | --> POST https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/feeds HTTP/1.1
backend_1   | Content-Type: application/json; charset=utf-8
backend_1   | Content-Length: 186
backend_1   | Accept: application/json
backend_1   | User-Agent: Swagger-Codegen/1.0.0/java
backend_1   | x-amz-access-token: Atza|ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
backend_1   | Host: sellingpartnerapi-eu.amazon.com
backend_1   | X-Amz-Date: 20211112T122831Z
backend_1   | Authorization: AWS4-HMAC-SHA256 Credential=AKIA-ZZZZZZZZZZ-/eu-west-1/execute-api/aws4_request, SignedHeaders=accept;content-type;host;user-agent;x-amz-access-token;x-amz-date, Signature=ZZZZZZZZZ
backend_1   | 
backend_1   | {"feedType":"MARS_AUTOMATE_PRICING_MULTI_MARKETPLACE_FEED","marketplaceIds":["A1PA6795UKMFR9"],"inputFeedDocumentId":"amzn1.tortuga.3.be40eaea-964d-44d9-867d-9c5f5a20dee6.ZZZZZZZZZ"}
backend_1   | --> END POST (186-byte body)
backend_1   | <-- HTTP/1.1 403 Forbidden (99ms)
backend_1   | Date: Fri, 12 Nov 2021 12:28:31 GMT
backend_1   | Content-Type: application/json
backend_1   | Content-Length: 139
backend_1   | Connection: keep-alive
backend_1   | x-amzn-RequestId: bdf00617-b08a-42ac-822c-5e10501dda90
backend_1   | x-amz-apigw-id: IsOdeFcpDoEFvIA=
backend_1   | X-Amzn-Trace-Id: Root=1-618e5def-776c5f575b7fe6564e6dfba6
backend_1   | OkHttp-Sent-Millis: 1636720111618
backend_1   | OkHttp-Received-Millis: 1636720111716
backend_1   | 
backend_1   | {
backend_1   |   "errors": [
backend_1   |     {
backend_1   |       "code": "Unauthorized",
backend_1   |       "message": "Access to the resource is forbidden",
backend_1   |       "details": ""
backend_1   |     }
backend_1   |   ]
backend_1   | }
backend_1   | <-- END HTTP (139-byte body)
```

**Comment by stefnats** [comment]
This report type is neither documented here in sp Api nor in MWS. Could you elaborate where you found this and a bit more details?

**Comment by kaipaysen** [comment]
> This report type is neither documented here in sp Api nor in MWS. Could you elaborate where you found this and a bit more details?

That feedType is related to amazons automated prices. Didn't find any documentation as well but it works fine in MWS.

**Comment by gmendozamb** [comment]
Hello @kaipaysen
Can you please share what you did to solve it ?

**Comment by kaipaysen** [comment]
@gmendozamb MWS credentials differ from SP Api credentials (at least here)

**Comment by gmendozamb** [comment]
@kaipaysen Yes here too and they don't give any new credentials anymore, hope they add this feature to the SP API.

**Comment by RubenAlvarezMoreno** [comment]
Hello,
Any update regarding this?
I have migrated 90% of the code to SP-API and this feed is pending.
I have contacted the support but they do not give me a clear answer, it seems that they do not know anything related to this type of feed.

**Comment by gmendozamb** [comment]
@RubenAlvarezMoreno I didn’t find anything on my end, pls let me know if you do find something.

**Comment by RubenAlvarezMoreno** [comment]
@gmendozamb Of course, if I find the solution, I'll post it here, I hope the support will respond correctly, since I've tried the same thing as you and I get the same error when it works perfectly in MWS.
@abuzuhri perfect example and similar to mine is written above, if you find anything please comment

**Comment by madcorp206** [comment]
> Same feed works fine with MWS.

Did it really work via MWS? Does it still ?

I tried to send a _MARS_AUTOMATE_PRICING_MULTI_MARKETPLACE_FEED_ via MWS but it's stuck in _IN_PROGRESS_ state, and nothing happens.

**Comment by kaipaysen** [comment]
@madcorp206 yes it did work and still does. MARS_AUTOMATE_PRICING_MULTI_MARKETPLACE_FEED ain't fast.

**Comment by madcorp206** [comment]
@kaipaysen thanks for the feedback.
In the end, feed was stuck due to a bad content-type (text/xml) sent in the request, MWS support had to manually cancel it.

With the good content-type it does work fine.

**Comment by RubenAlvarezMoreno** [comment]
Good morning,
I have had several meetings with technical support and apparently they will not enable this feed in SP-API.
Any idea for when this feed is not enabled with the change of api? so I go ahead.
Regards.

**Comment by sergisolanellas** [comment]
Anyone knows if finally this feed type will include in the new SP API version? I tried but don't work.

**Comment by martin3mf** [comment]
Any news regarding this topic?

**Comment by wtom** [comment]
I'm also stuck with this.
I tried content_type "text/xml; charset=UTF-8" and "text/tab-separated-values; charset=UTF-8", both with no success. 
Error is Unauthorized. MWS still works fine, but at the end of the month the migration to SP-API has to be completed.

**Comment by sergisolanellas** [comment]
> I'm also stuck with this. I tried content_type "text/xml; charset=UTF-8" and "text/tab-separated-values; charset=UTF-8", both with no success. Error is Unauthorized. MWS still works fine, but at the end of the month the migration to SP-API has to be completed.

I think this option is not enabled in SP-API. If anyone has information, please share it.
