### ISSUE TITLE
Listing items under an existing ASIN

### ISSUE THREAD

**Issue by midi-red** [amzn/selling-partner-api-docs#1650]
I have been searching for an example for listing items under an existing ASIN, but no luck so far. Say, I want to sell an item that is already being sold by some other sellers and exists in Amazon catalog, how can I list my items under same ASIN with my seller sku? 

ListingItemsApi [put call](https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2021-08-01.md#putlistingsitem) does not take an ASIN parameter. I would assume this is not the correct endpoint. 
Another option is to use feeds api? I am not sure about this one!
Could someone point me to a document that shows a workflow about how to list items under an existing ASIN? Or which endpoint should I use? 

Thanks in advance!

**Comment by biancahuluban** [comment]
Hi,
Here is a documentation that might help, if you have already the ASIN you can publish using the ASIN, if not than maybe a product report generation will help.
https://m.media-amazon.com/images/G/01/AmazonServices/Site/MWS_Integrators_HowToGetStarted._CB1519803481_.pdf

![image](https://user-images.githubusercontent.com/79015817/143543369-1a052f5d-99fc-4b35-91d2-2ad04264e0b2.png)

**Comment by whitedevils** [comment]
I'm in same situation of @midi-red, all the examples use MWS and feed documentation. What we need is an example of how to use "putlistingitem" of SP-API. The use case guide is too much simple to use.
