### ISSUE TITLE
What is the report type for  "Inventory reconciliation" report FBA ?

### ISSUE THREAD

**Issue by rohitdobariya** [amzn/selling-partner-api-docs#1652]
I want to know what is the report type there in SP API if I want to download the "Inventory reconciliation" report
Here is the header which I downloaded report from Seller central and I want this using SP-API
"sku","fnsku","asin","product-name","condition","beginning-quantity","ending-quantity","received","returned","found","sold","removed","lost","disposed","other","discrepant-quantity"

**Comment by stefnats** [comment]
This is not solved and would be good if this report type was downloadable via Api.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
