### ISSUE TITLE
[BUG]/vendor/transactions/v1/transactions/{transactionId}  always returns status: processing

### ISSUE THREAD

**Issue by ykl1993** [amzn/selling-partner-api-docs#1653]
use
/vendor/transactions/v1/transactions/{transactionId}
Interface to obtain the transaction information for confirming the order, and Amazon console displays that the order has been confirmed successfully!
But the interface always returns status: processing

What should I do? To get the correct results

Thank you!

**Comment by pucsdian** [comment]
same issue...
so for just make it working we are checking directly status of PO, but it is not reliable cause if we updated acknowledgement we cant check it is it accepted or not without check PO Status API which is headache 
hoping from amazon team to reply as soon as to this issue../

**Comment by lw-andrewsmith** [comment]
+1
