### ISSUE TITLE
Listing products api

### ISSUE THREAD

**Issue by ItHamza** [amzn/selling-partner-api-docs#1655]
I am trying to get all my products in my seller account but couldn't find a API for this. Can we only get products one by one by SKU in listing API or there is any simpler way to get all products? Or atleast some products with creation date or something similar.

**Comment by ItHamza** [comment]
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md](url)
Is it available for UK region or any chance to available soon?

**Comment by abhitheawesomecoder** [comment]
Is it possible to get all my products in my seller account with one API call? I am non FBA seller in India.

**Comment by stefnats** [comment]
You can just use the reports Api. There are many different report types that can deliver all the data that you need
