### ISSUE TITLE
Fba Inventory API

### ISSUE THREAD

**Issue by ItHamza** [amzn/selling-partner-api-docs#1657]
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md](url)
Is it available for UK region or any chance to available soon?

_Originally posted by @ItHamza in https://github.com/amzn/selling-partner-api-docs/issues/1655#issuecomment-968869321_

**Comment by stefnats** [comment]
Correct, it is available in all regions now.
