### ISSUE TITLE
[FEATURE] Retrieve vendors catalog from catalog api

### ISSUE THREAD

**Issue by robinchen123** [amzn/selling-partner-api-docs#1664]
Now we have to get vendor's asins from reports. If there's an api which can retrieve vendors catalog, It would be very helpful for us to check items.

**Comment by lw-andrewsmith** [comment]
+1

**Comment by robinchen123** [comment]
@lw-andrewsmith I've find the same question and it is answered , Please refer to https://github.com/amzn/selling-partner-api-docs/discussions/1718. This ticket would be closed.
