### ISSUE TITLE
Report: `_GET_DATE_RANGE_FINANCIAL_TRANSACTION_DATA_`

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#1668]
It is possible to download this report via the API, however not request it. It can be requested via Seller Central UI only.

Can this report be added?

If not, what alternatives can you recommend for getting the same data?

**Comment by jesusvalle** [comment]
Hi moltar,

You can get the information in this report from the finances calls of the new sp-api.
Even so, it is a bit chaotic, as some data does not indicate the country or date.
