### ISSUE TITLE
[BUG] getting a FATAL error on the GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA report

### ISSUE THREAD

**Issue by ydancziger** [amzn/selling-partner-api-docs#1673]
Hi,

I'm working on getting the GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA report but sometimes it works fine and with the same data passing we sometimes get a FATAL error and sometimes it works fine, 

That's a problem when creating a software that will rely on that report.

Any help on that?

**Comment by orpeleg8** [comment]
I'm experiencing the same issue...
