### ISSUE TITLE
FBAInboundTransportationFee - information not complete

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#1675]
hi, I need to get Amazon fees , and one of them is the `Inbound transportation fees`. After days of finding the api call to retrieve these fee, I discovered the financial events api. However, the response from this api is useless since I cant map it to the products.

      api =>  financialEvents?max_results_per_page=100&posted_before=2021-10-20&posted_after=2021-10-19&next_token

       response from api => "ServiceFeeEventList": [
                     {
                          "FeeList": [
                             {
                                  "FeeType": "FBAInboundTransportationFee",
                                  "FeeAmount": {
                                   "CurrencyCode": "EUR",
                                  "CurrencyAmount": -30.2
                              }
                             },
                          {
                            "FeeType": "FBAInboundTransportationProgramFee",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -3.02
                            }
                        }
                    ]
                },
                {
                    "FeeList": [
                        {
                            "FeeType": "Subscription",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -39
                            }
                        }
                    ]
                }
            ],
            "SellerDealPaymentEventList": [],
        `

As you can see in response, it doesnt provide which Asin /products belongs, so a customer will not know how much is the inbound fee for each product. Is there any api that can return this results being mapped to sku/products?

Regards,

Ian

**Comment by ianrussel** [comment]
we already have 2 potential clients backing out due to inaccurate amazon fees in the dashboard.Do you have plan to fix this issue ?

**Comment by ianrussel** [comment]
not yet resolve

**Comment by shanetheboland** [comment]
@ianrussel Any update on this? Having the same issue. No PostedDate for the fees and no associated SKU or ASIN.
