### ISSUE TITLE
VendorShipping-submitShipmentConfirmations Error

### ISSUE THREAD

**Issue by ykl1993** [amzn/selling-partner-api-docs#1680]
class SubmitShipmentConfirmationsRequest {
    shipmentConfirmations: [class ShipmentConfirmation {
        shipmentIdentifier: 1637144422
        shipmentConfirmationType: Original
        shipmentType: SmallParcel
        shipmentStructure: null
        transportationDetails: class TransportationDetails {
            carrierScac: UPSN - UNITED PARCELSERVICE INC
            carrierShipmentReferenceNumber: null
            transportationMode: null
            billOfLadingNumber: 02440000
        }
        amazonReferenceNumber: ARN1637144422999
        shipmentConfirmationDate: 2021-11-17T18:20:22.999+08:00
        shippedDate: 2021-12-03T12:00Z
        estimatedDeliveryDate: 2021-12-07T12:00Z
        sellingParty: class PartyIdentification {
            address: null
            partyId: JN5FQ
            taxRegistrationDetails: null
        }
        shipFromParty: class PartyIdentification {
            address: class Address {
                name: Yitong Lin
                addressLine1: Room 901, Unit 8, Tongjian Building
                addressLine2: null
                addressLine3: null
                city: Shenzhen
                county: null
                district: null
                stateOrRegion: GUANGDONG
                postalCode: 518000
                countryCode: CN
                phone: null
            }
            partyId: RJ5YL
            taxRegistrationDetails: null
        }
        shipToParty: class PartyIdentification {
            address: null
            partyId: MME2
            taxRegistrationDetails: null
        }
        shipmentMeasurements: null
        importDetails: null
        shippedItems: [class Item {
            itemSequenceNumber: 001
            amazonProductIdentifier: B07SR18XCB
            vendorProductIdentifier: 6972444182007
            shippedQuantity: class ItemQuantity {
                amount: 72
                unitOfMeasure: Eaches
                unitSize: 1
            }
            itemDetails: class ItemDetails {
                purchaseOrderNumber: 3NEK6URT
                lotNumber: null
                expiry: null
                maximumRetailPrice: null
                handlingCode: null
            }
        }]
        cartons: [class Carton {
            cartonIdentifiers: [class ContainerIdentification {
                containerIdentificationType: AMZNCC
                containerIdentificationNumber: B07SR18XCBU000001
            }]
            cartonSequenceNumber: 001
            dimensions: null
            weight: null
            trackingNumber: null
            items: [class ContainerItem {
                itemReference: B07SR18XCB
                shippedQuantity: class ItemQuantity {
                    amount: 36
                    unitOfMeasure: Eaches
                    unitSize: 1
                }
                itemDetails: null
            }]
        }, class Carton {
            cartonIdentifiers: [class ContainerIdentification {
                containerIdentificationType: AMZNCC
                containerIdentificationNumber: B07SR18XCBU000002
            }]
            cartonSequenceNumber: 002
            dimensions: null
            weight: null
            trackingNumber: null
            items: [class ContainerItem {
                itemReference: B07SR18XCB
                shippedQuantity: class ItemQuantity {
                    amount: 36
                    unitOfMeasure: Eaches
                    unitSize: 1
                }
                itemDetails: null
            }]
        }]
        pallets: null
    }]
}

// return back response
{
	[class Error {
		code: OLD_MinimumPO message: The ASN '1637144422' (BSN02) does not have Purchase Order(PO) mentioned on the PRF01 segment.Amazon expects a valid PO number in PRF01 segment of EDI856 details: Please submit an updated EDI 856 with at least 1 PO.Failure to submit a new ASN might lead to a No ASN Chargeback.
	}]
}

**Comment by ykl1993** [comment]
> 请问一个 这个问题你解决了么？

没有, 正在努力寻找解决方法

**Comment by ahlmackie** [comment]
Hi, I am also having this issue. Has anyone been able to resolve?

**Comment by ykl1993** [comment]
sorry,&nbsp;At present, I still fail.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] VendorShipping-submitShipmentConfirmations Error (Issue #1680)





 
Hi, I am also having this issue. Has anyone been able to resolve?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wonsky87** [comment]
请问这个解决了吗？我也是遇到这个问题了。
