### ISSUE TITLE
[BUG] How do we send Shipping mode through the APIs?

### ISSUE THREAD

**Issue by drod516** [amzn/selling-partner-api-docs#1684]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
When using putTransportDetails there is no option for sending the Shipping Mode

We have to go into seller central to update this manually 

**Screenshots**
![image](https://user-images.githubusercontent.com/8659801/142263895-763149c8-2773-41b7-9ce8-4d5049cd518f.png)

**Additional context**

**Comment by NetRushJacob** [comment]
I confirm this is a missing piece of the APIs that appears to be a required step to submitting a shipment to Amazon.

Bit more detail:
- Small Parcel, Non-Partnered
- Carton Contents submitted via feed POST_FBA_INBOUND_CARTON_CONTENTS or 2D barcodes

Some further links:
- [Carrier and tracking information requirements](https://sellercentral.amazon.com/help/hub/reference/GVZWBSSV464ZRWNJ) : Makes no reference to the 'Shipment mode' dropdown
- [News announcement](https://sellercentral.amazon.com/gp/headlines.html?id=GT6644AY3Y7BKHSE&ref=nslp_at_11_GT6644AY3Y7BKHSE_en-US_ttl_rf_recent_news_12) speaking to the required carrier tracking information; no mention of the 'Shipment mode' dropdown
- [Send/replenish inventory](https://sellercentral.amazon.com/help/hub/reference/201021880) makes reference to the Shipment mode, but does not indicate any reference to setting it except in Seller Central

**Comment by ericfragola** [comment]
@drod516 did you find a solution ? We ran Into the same error
