### ISSUE TITLE
[BUG] Documentation - Requesting Orders Data

### ISSUE THREAD

**Issue by jesusvalle** [amzn/selling-partner-api-docs#1692]
Good morning,

I am trying to request a report of orders of the type: GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE

When I make the request, I get an error message: Access to the resource is forbidden.

Is it necessary to request a restricted data token? I have been looking at the restricted report types, and this particular one was not listed.

Has anyone requested them and could you please clarify?

Best regards

**Comment by stefnats** [comment]
I see you closed the issue, could you share the solution, just in case somebody in the future has the same problem?

**Comment by jesusvalle** [comment]
Apparently, the report must now be ordered under the name: 

> _GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL _

That's what I have been told by the support.
