### ISSUE TITLE
Unauthorized response for getMessagingActionsForOrder

### ISSUE THREAD

**Issue by hh-19** [amzn/selling-partner-api-docs#1705]
I am receiving "Access to requested resource is denied" for the getMessagingActionsForOrder operation. I have all the required permissions in my developer profile and have been using the SP API without issue for many other use cases, so I know it is not an issue with credentials or how the API calls are made. 

Thanks

**Comment by stefnats** [comment]
Hey, I see you closed the issue. What was the solution?
