### ISSUE TITLE
"status" column is miss in FeedType "GET_MERCHANT_LISTINGS_ALL_DATA"

### ISSUE THREAD

**Issue by yongchuan** [amzn/selling-partner-api-docs#1706]
when use FeedType "GET_MERCHANT_LISTINGS_ALL_DATA" to get report data.
the "status" column is miss.

**Comment by PerfectWorld233** [comment]
if "status" not in rowData:
    pass

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
