### ISSUE TITLE
Request for SP-API PII access rejected for the third time!

### ISSUE THREAD

**Issue by karinamendonca29** [amzn/selling-partner-api-docs#1709]
Hi,

I have submitted an application thrice for the access. Can you please help me understand the exact reason it's being rejected. What do I need to do to be granted access? It's really important that I get this sorted since I have a client waiting for this development.

**Comment by stefnats** [comment]
I'm not associated with Amazon, so I can't tell you, but as far as I know, they don't give away new PII access right now. Please correct me if I'm wrong.

**Comment by hkncnr07** [comment]
Hi @stefnats,
Are you saying that Amazon is not currently accepting new PII access right applications?
Are you sure about this?

**Comment by DDDDDID** [comment]
I obtained the PII permission last year, and I must pass Amazon's strict review before I can get it.

**Comment by stefnats** [comment]
@hkncnr07 no, i'm not sure about this, this was just what i read here and on seller forums.

But then, there's @DDDDDID who have successfully applied. Maybe contact developer support, i think they might to help you better.
