### ISSUE TITLE
PostedDate:  time zone for order invoices

### ISSUE THREAD

**Issue by howardliptzin** [amzn/selling-partner-api-docs#171]
I am using the webservice to integrate Amazon data with our Enterprise resource planning (ERP) system. The “PostedDate” in the XML file that we have downloaded from the webservice seems to be UTC.

Question: will all the data for *invoicing* related to different marketplaces always refer to UTC or will the date be related to the local time zone? This becomes critical for transactions around midnight when the date of the transaction could change.

Thanks in advance.

**Comment by JacksonJeans** [comment]
Hello @howardliptzin ,
As far as I know Amazon always uses the UTC time zone. I have never used another one. In all documentation, regardless of Selling Partner API, where I have read through, UTC is always a default value or required timezone. 

For example AWS Signature V4:
[Handling dates in Signature V4](https://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html)

**Comment by ShivikaK** [comment]
Hello,

As we haven’t received any response from you regarding this, I will close this issue.
Please open a support case with us for any errors with your API requests and we can assist you further.

Thanks,  
Shivika Khare  
Selling Partner API Developer Support
