### ISSUE TITLE
How can I find ship to addresses when creating shipment?

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#1710]
Hello Im trying to create a shipment using sp api, but I can't find ship to addresses. What api should I call to get these addreses? Also how can I find clientReferenceId?

**Comment by zsf3** [comment]
Do you have PII roles enabled on your account and SP-API app?

**Comment by Javadebi** [comment]
> Do you have PII roles enabled on your account and SP-API app?

Yes I do

**Comment by bjpierre** [comment]
Did you ever work this out? I'm attempting to get the ship to address of a shipment created via SellerCentral and it doesn't seem possible via the FBA/Inbound APIs
