### ISSUE TITLE
I test it in sandbox with calling putTransportDetails(PUT /fba/inbound/v0/shipments/{shipmentId}/transport) method, but return 500 error.[BUG] Documentation

### ISSUE THREAD

**Issue by xupucha** [amzn/selling-partner-api-docs#1713]
Selling Partner API for Fulfillment Inbound
PUT /fba/inbound/v0/shipments/{shipmentId}/transport
Operation: putTransportDetails

I need sends transportation information to Amazon about an inbound shipment refer to fulfillmentInboundV0.json.
So I test it in sandbox with calling putTransportDetails(PUT /fba/inbound/v0/shipments/{shipmentId}/transport) method, but return 500 error.

invove params:
class PutTransportDetailsRequest {
    isPartnered: true
    shipmentType: SP
    transportDetails: class TransportDetailInput {
        partneredSmallParcelData: null
        nonPartneredSmallParcelData: class NonPartneredSmallParcelDataInput {
            carrierName: USPS
            packageList: class NonPartneredSmallParcelPackageInputList {
                [class NonPartneredSmallParcelPackageInput {
                    trackingId: werwrwerwrwrer
                }]
            }
        }
        partneredLtlData: null
        nonPartneredLtlData: null
    }
}

error:
{
  "errors": [
    {
      "message": "We encountered an internal error. Please try again.",
     "code": "InternalFailure"
    }
  ]
}

any help? Thanks a lot.

Call the createFeedDocument operation, specifying the content type for the feed that you are submitting.

**Comment by 15184351573** [comment]
NonPartneredSmallParcelDataInput  = isPartnered: false
