### ISSUE TITLE
The report status of the uploaded product is always in'IN_QUEUE' or'IN_PROGRESS'

### ISSUE THREAD

**Issue by yafeng33** [amzn/selling-partner-api-docs#1715]
After uploading products using "feeds.createFeed", the result obtained through "feeds.getFeed" has been in'IN_QUEUE' or'IN_PROGRESS' for 6 hours, what should I do?

My code is as follows

let msg_str=`<?xml version="1.0" encoding="utf-8"?>
       <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
         <Header>
           <DocumentVersion>1.01</DocumentVersion>
           <MerchantIdentifier>ckhw</MerchantIdentifier>
         </Header>
         <MessageType>Product</MessageType>
         <PurgeAndReplace>false</PurgeAndReplace>
          <Message>
           <MessageID>1</MessageID>
           <OperationType>Update</OperationType>
           <Product>
               <SKU>QZN5XiRzapepmDtt9BD</SKU>
               <LaunchDate>2021-11-24T12:06:00</LaunchDate>
               <DescriptionData>
                        <Title>coat women</Title>
                        <Brand>N\P</Brand>
                        <Description>coat 100% Polyester</Description>
                        <BulletPoint>1</BulletPoint>
                        <BulletPoint>2</BulletPoint>
                        <BulletPoint>3</BulletPoint>
                        <BulletPoint>4</BulletPoint>
                        <BulletPoint>5</BulletPoint>
                         <Manufacturer>N\P</Manufacturer>
                        <MaxOrderQuantity>1</MaxOrderQuantity>
                        <ShippingWeight unitOfMeasure="KG">0.50</ShippingWeight>
                        <MerchantShippingGroupName>Migrated Template</MerchantShippingGroupName>
                        <SearchTerms>coat</SearchTerms>
                        <PlatinumKeywords>COAT</PlatinumKeywords>
                        <DepartmentName>Women</DepartmentName>
                        <CountryOfOrigin>CN</CountryOfOrigin>
               </DescriptionData>
               <ProductData>
                    <Clothing>
                        <VariationData>
                            <Parentage>parent</Parentage>
                            <VariationTheme>ColorSize</VariationTheme>
                        </VariationData>
                        <ClassificationData>
                            <ClothingType>Coat</ClothingType>
                            <OccasionAndLifestyle>Casual</OccasionAndLifestyle>
                            <TargetGender>female</TargetGender>
                        </ClassificationData>
                         <AgeRangeDescription>adult</AgeRangeDescription>
                             <ApparelSizeSystem>as1</ApparelSizeSystem>
                            <ApparelBodyType>regular</ApparelBodyType>
                            <ApparelHeightType>regular</ApparelHeightType>
                    </Clothing>
                </ProductData>
           </Product>
         </Message>
<Message>
           <MessageID>2</MessageID>
           <OperationType>Update</OperationType>
           <Product>
               <SKU>QZN5XiRzapepvDVt9JDu4IJXDsF</SKU>
               <StandardProductID>
                <Type>UPC</Type><Value>6976591921359</Value></StandardProductID>
               <LaunchDate>2021-11-24T12:06:00</LaunchDate>
                              <DescriptionData>
                        <Title>COAT</Title>
                        <Brand>N\P</Brand>
                        <Description>Description</Description>
                        <BulletPoint>6</BulletPoint>
                        <BulletPoint>7</BulletPoint>
                        <BulletPoint>8</BulletPoint>
                        <BulletPoint>9</BulletPoint>
                        <BulletPoint>10</BulletPoint>
                        <MaxOrderQuantity>1</MaxOrderQuantity>
                        <ShippingWeight unitOfMeasure="KG">0.50</ShippingWeight>
                        <MerchantShippingGroupName>Migrated Template</MerchantShippingGroupName>
                        <SearchTerms>coat</SearchTerms>
                        <DepartmentName>Women</DepartmentName>
                        <PlatinumKeywords>Coat</PlatinumKeywords>
                        <RecommendedBrowseNode>7420706011</RecommendedBrowseNode>
                        <Manufacturer>N\P</Manufacturer>
                        <SizeName>3x_l</SizeName>
                        <SizeMap>3x_l</SizeMap>
                        <CountryOfOrigin>CN</CountryOfOrigin>
                        <ItemType>COAT</ItemType>
               </DescriptionData>
               <ProductData>
                    <Clothing>
                        <VariationData>
                            <Parentage>child</Parentage>
                            <VariationTheme>ColorSize</VariationTheme>
                        </VariationData>
                        <ClassificationData>
                            <Size>3x_l</Size>
                            <Color>black</Color>
                            <OccasionAndLifestyle>Casual</OccasionAndLifestyle>
                            <ClothingType>Coat</ClothingType>
                            <Department>Women</Department>
                            <ColorMap>black</ColorMap>
                            <SizeMap>3x_l</SizeMap>
                            <TargetGender>female</TargetGender>
                            <AgeRangeDescription>adult</AgeRangeDescription>
                            <ApparelSizeClass>alpha</ApparelSizeClass>
                             <ApparelSizeSystem>as1</ApparelSizeSystem>
                            <ApparelBodyType>regular</ApparelBodyType>
                            <ApparelHeightType>regular</ApparelHeightType>
                            <ApparelSize>3x_l</ApparelSize>
                            <ApparelSizeTo>3x_l</ApparelSizeTo>
                        </ClassificationData>
                    </Clothing>
                </ProductData>
           </Product>
         </Message>
       </AmazonEnvelope>`;

let feed = {
            content: msg_str,
            contentType: 'text/xml; charset=utf-8'
        };
        const feed_upload_details = await sellingPartner.callAPI({
            operation: 'createFeedDocument',
            endpoint: "feeds",
            body: {
                contentType: feed.contentType,
            },
            method: "POST",
            options: {
                version: "2020-09-04"
            }
        });
        let res = await sellingPartner.upload(feed_upload_details, feed);
        const rs = await sellingPartner.callAPI({
            operation: 'createFeed',
            endpoint: "feeds",
            body: {
                feedType: "POST_PRODUCT_DATA",
                marketplaceIds: ["A2EUQ1WTGCTBG2"],
                inputFeedDocumentId: feed_upload_details.feedDocumentId
            },
            method: "POST",
            options: {
                version: "2020-09-04"
            }
        });

const feed_rs = await sellingPartner.callAPI({
        operation: 'getFeed',
        endpoint: "feeds",
        path: {
            feedId: 'xxxxxx'
        },
        options: {
            version: "2020-09-04"
        }
    });
console.log("feed_rs", feed_rs);

the request result as follows:

     processingStatus: 'IN_PROGRESS',
      marketplaceIds: [ 'ATVPDKIKX0DER' ],
      feedId: 'xxxxxx',
      feedType: 'POST_PRODUCT_DATA',
      createdTime: '2021-11-24T05:08:14+00:00',
      processingStartTime: '2021-11-24T05:08:21+00:00'

**Comment by aibirriaga** [comment]
Hello, it's still in_progress? what is the difference between IN_QUEUE and IN_PROGRESS? I am trying to upload a feed for product listings but the feed is IN_QUEUE for an hour.

**Comment by yafeng33** [comment]
@aibirriaga in_progress is a stage before IN_QUEUE

**Comment by yafeng33** [comment]
Is there a better way to create products？

**Comment by aibirriaga** [comment]
> Is there a better way to create products？

yes, you can create them one by one using listings api but the feeds api fits better to our requirements. By the way, the feed is steel IN_QUEUE for almost 24h

**Comment by yafeng33** [comment]
@aibirriaga  As far as I know, the listing api can only modify and delete products, not create new products.I didn't do any processing and it is no longer blocked. But there are new problems。
`<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>caihai</MerchantIdentifier>
    </Header>
    <MessageType>Product</MessageType>
    <PurgeAndReplace>false</PurgeAndReplace>
    <Message>
        <MessageID>4</MessageID>
        <OperationType>Update</OperationType>
        <Product>
            <SKU>uFzvHkFN625jBha7xCXS1ZO9Bb6X7DPFA</SKU>
            <StandardProductID>
                <Type>UPC</Type>
                <Value>6902427821357</Value>
            </StandardProductID>
            <Condition>
                <ConditionType>New</ConditionType>
            </Condition>
            <DescriptionData>
                <Title>Men T-Shirt</Title>
                <Brand>N\P</Brand>
                <Description>Lyric sheeting by Peacock Alley</Description>
                <BulletPoint>plain weave (percale)</BulletPoint>
                <BulletPoint>100% Egyptian cotton</BulletPoint>
                <MSRP currency="USD">12.50</MSRP>
                <ItemType>T-Shirt</ItemType>
                <RecommendedBrowseNode>3271420011</RecommendedBrowseNode>
                <MerchantShippingGroupName>Migrated Template</MerchantShippingGroupName>
            </DescriptionData>
            <ProductData>
                <Clothing>
                    <VariationData>
                        <VariationTheme>ColorSize</VariationTheme>
                    </VariationData>
                    <ClassificationData>
                        <Size>Large</Size>
                        <Color>black</Color>
                        <ClothingType>Shirt</ClothingType>
                        <Department>mens</Department>
                        <ColorMap>black</ColorMap>
                        <MaterialComposition>100% Cotton</MaterialComposition>
                        <CareInstructions>Machine Wash</CareInstructions>
                        <OccasionAndLifestyle>Casual</OccasionAndLifestyle>
                        <Season>Summer</Season>
                        <StyleName>T-Shirt</StyleName>
                        <CollarType>Collarless</CollarType>
                        <SleeveType>HalfSleeve</SleeveType>
                        <CountryOfOrigin>IN</CountryOfOrigin>
                        <SizeMap>Large</SizeMap>
                        <FabricType>Cotton</FabricType>
                        <MaterialType>Cotton</MaterialType>
                        <NeckStyle>RoundNeck</NeckStyle>
                        <PatternStyle>Printed</PatternStyle>
                        <CollectionName>MyColl 1</CollectionName>
                        <SpecialFeature>Trendy</SpecialFeature>
                        <SpecialFeature>Latest</SpecialFeature>
                        <SpecialFeature>Round neck</SpecialFeature>
                        <TargetGender>male</TargetGender>
                        <Theme>Cartoon</Theme>
                        <OccasionType>Evening</OccasionType>
                    </ClassificationData>
                    <AgeRangeDescription>adult</AgeRangeDescription>
                    <ShirtSizeClass>alpha</ShirtSizeClass>
                    <ShirtSizeSystem>as1</ShirtSizeSystem>
                    <ShirtSizeTo>l</ShirtSizeTo>
                    <NumberOfPieces>9</NumberOfPieces>
                    <UnitCount>1</UnitCount>
                    <PPUCountType>count</PPUCountType>
                    <MaterialTypeFree>Cotton</MaterialTypeFree>
                    <ShirtSize>l</ShirtSize>
                </Clothing>
            </ProductData>
        </Product>
    </Message>
</AmazonEnvelope>`
The error report is as follows
`{
  "AmazonEnvelope": {
    "Header": {
      "DocumentVersion": 1.02,
      "MerchantIdentifier": "A3BM8Z5CBUMQWY"
    },
    "MessageType": "ProcessingReport",
    "Message": {
      "MessageID": 1,
      "ProcessingReport": {
        "DocumentTransactionID": 50480018956,
        "StatusCode": "Complete",
        "ProcessingSummary": {
          "MessagesProcessed": 1,
          "MessagesSuccessful": 0,
          "MessagesWithError": 1,
          "MessagesWithWarning": 0
        },
        "Result": {
          "MessageID": 4,
          "ResultCode": "Error",
          "ResultMessageCode": 5000,
          "ResultDescription": "XML Parsing Error at Line 71, Column 32: cvc-complex-type.2.4.a: Invalid content was found starting with element &apos;ShirtSize&apos;. One of &apos;{MaterialTypeFree}&apos; is expected.",
          "AdditionalInfo": {
            "SKU": "QZN5XiRzxpepvDvt9JDu4IJXDsF"
          }
        }
      }
    }
  }
}`
But the element "MaterialTypeFree" already exists

**Comment by yafeng33** [comment]
My problem has been solved, caused by incorrect sorting of elements in xml

**Comment by aibirriaga** [comment]
@yafeng33 it is definitely possible to make partial updates of products with listing feeds using "operationType": "PARTIAL_UPDATE",

**Comment by yafeng33** [comment]
@aibirriaga thinks
