### ISSUE TITLE
Missing Enum value "READY_TO_SHIP" in fulfillment_inbound get shipments / get shipment items

### ISSUE THREAD

**Issue by saleweaver** [amzn/selling-partner-api-docs#1716]
Concerns:

https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatuslist

**Describe the bug**
When requesting inbound shipments through the api using 

```
QUERY_TYPE = DATE_RANGE
SHIPMENT_STATUS_LIST = [
                'WORKING', 'SHIPPED', 'RECEIVING',
                'CANCELLED', 'DELETED',
                'CLOSED', 'ERROR', 'IN_TRANSIT',
                'DELIVERED',
                'CHECKED_IN'
            ]
```
and providing valid values, shipments in status "READY_TO_SHIP" are not returned by the API.

When adding "READY_TO_SHIP" to the list of statuses, the api throws an Invalid Input error for READY_TO_SHIP. 
When requesting the same shipment by its shipment_id, it gets returned with "READY_TO_SHIP" as its status.

**URL of the content on GitHub**

https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#shipmentstatuslist

**Expected behavior**

All shipment statuses should be requestable.

**Comment by saleweaver** [comment]
Would someone be so kind to address this?

**Comment by joyceeeen** [comment]
Any update on this?

@ShivikaK

**Comment by joyceeeen** [comment]
Requesting to please check on this issue. @ShivikaK @chapmanjw @jevoniuk Thanks!

**Comment by parvathm** [comment]
Hi @saleweaver/ @joyceeeen,

Can you please open a [support case](https://sellercentral.amazon.com/gp/mws/contactus.html) with request id and time stamp details for both where it returned invalid request and where asking for shipment id returned READY_TO_SHIP status? This will help us to address the issue quickly.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by saleweaver** [comment]
Hi @parvathm,

thanks for your response. I'm only a developer, can I send you the request id otherwise? 

Can you reproduce the behavior?

**Comment by joyceeeen** [comment]
Will let @saleweaver open a support case so to avoid duplicate. @saleweaver counting on you :)

**Comment by joyceeeen** [comment]
Do they have any update on this @saleweaver ?

**Comment by saleweaver** [comment]
> Do they have any update on this @saleweaver ?

Greetings from Amazon,

...

I understand that you are querying functionality of the getshipment operation. &quot;READY_TO_SHIP&quot; is not being accepted as a valid query input in relation to shipment status query, but is being returned as a valid shipment status in response to shipment ID query. I.E. The status is detected as invlid as an input, but is returned as a valid output.

I am working with our Inbound Shipment API developers to gather more information on why this is, and to drive a resolution which will allow &quot;READY_TO_SHIP&quot; to be accepted as a valid query input. As soon asI have more information available I will follow up with you directly by email.

**Comment by joyceeeen** [comment]
> > Do they have any update on this @saleweaver ?
> 
> Greetings from Amazon,
> 
> ...
> 
> I understand that you are querying functionality of the getshipment operation. "READY_TO_SHIP" is not being accepted as a valid query input in relation to shipment status query, but is being returned as a valid shipment status in response to shipment ID query. I.E. The status is detected as invlid as an input, but is returned as a valid output.
> 
> I am working with our Inbound Shipment API developers to gather more information on why this is, and to drive a resolution which will allow "READY_TO_SHIP" to be accepted as a valid query input. As soon asI have more information available I will follow up with you directly by email.

May I know if they have an update on this?

**Comment by saleweaver** [comment]
>>> May I know if they have an update on this?

Here's the latest message from Amazon:
...
As of yet I have not secured a resolution, however I would like to assure you that we are working on this and the issue has been escalated for prioritisation.
...

**Comment by joyceeeen** [comment]
> > > > May I know if they have an update on this?
> 
> Here's the latest message from Amazon: ... As of yet I have not secured a resolution, however I would like to assure you that we are working on this and the issue has been escalated for prioritisation. ...

Do they have an update on this?

**Comment by uk-2** [comment]
Please can you update us on this ?

**Comment by joyceeeen** [comment]
> > > > May I know if they have an update on this?
> 
> Here's the latest message from Amazon: ... As of yet I have not secured a resolution, however I would like to assure you that we are working on this and the issue has been escalated for prioritisation. ...

Hi! I was wondering if Amazon Team gave you an update on this? Thanks!

**Comment by buithehien1991** [comment]
Any update? Error still happen now

**Comment by buithehien1991** [comment]
@saleweaver  please use my repo

gem 'amz_sp_api', github: 'buithehien1991/amz_sp_api'
