### ISSUE TITLE
BUG: Order API Empty Payload

### ISSUE THREAD

**Issue by ezpinsky** [amzn/selling-partner-api-docs#1717]
**When Bug Occurs**
 When making a request to the Orders-API using the getOrder operation and specifying a **removal order id** in the path.

**Expected Outcome**
Payload with [Order Object](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#order) containing all info relating to the removal order id.

**Actual Outcome**
Receive empty payload.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorder

**Further Context**
The issue at hand seems to be that it is impossible to programmatically request information about a removal order id from the API. Does anyone know if there is something I can specify in the request to get back a real payload? Or is their another api to get information about the removal order other than the removal order shipment detail report in the reports-api?

**Comment by stefnats** [comment]
As far as I know there is no such api, but you could download a report about removals.
