### ISSUE TITLE
Reports + Marketplaces

### ISSUE THREAD

**Issue by NetRushJacob** [amzn/selling-partner-api-docs#172]
CreateReport allows passing in a list of MarketplaceIds. However, the data that is returned does not appear to be correct if you include US + CA.

We have a single seller account for US and CA. The design implies we can call CreateReport for both US and CA and expect a report that has valid data for both marketplaces.

However, the resulting report is not accurate. 
Calling for just US, I get US data with correct numbers; all CA SKUs are present, but with 0s in all quantities
Calling for just CA, I get CA data with correct numbers; all US SKUs are present, but with 0s in all quantities
**Calling for both US and CA, I get US data with correct numbers; all CA SKUs are present, but with 0s in all quantities**

**Expected Results**
Calling for just US, I get US data with correct numbers; no other SKUs are present
Calling for just CA, I get CA data with correct numbers; no other SKUs are present
Calling for both US and CA, I get US and CA data with correct numbers; if SKUs are present in both US and CA, the data is summed OR a MarketplaceId column is added to differentiate the rows; no other SKUs are present

(FYI, this is the same as MWS APIs results, and likely tied directly to that)

**Comment by golshefsky** [comment]
How did you configure the POST request for CreateReport?  This is the response I receive from the API on a POST even though both parameters are present.  I'm not having any problems with parameters on a GET request.

`
BadRequest
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "marketplaceIds;reportType;"
    }
  ]
}
`

**Comment by pprbhm** [comment]
Hi Do you have any example requestID's for us to take a look. This looks like a invalid input parameter in the request. If you want more detailed troubleshooting steps, please open a [Support Case](https://developer.amazonservices.com/support) with Developer Support team. 
Posting personally identifiable information such as SellerID, Account ID is not advisable on public developer forums such as GitHub.
