### ISSUE TITLE
catalog/listCatalogItems Interface problem

### ISSUE THREAD

**Issue by xintity** [amzn/selling-partner-api-docs#1721]
Hello:
   We found that when calling the catalog/listCatalogItems interface, if you use a non-saleable SKU (that is, a SKU with 0 inventory), you can't get any data. What other ways can I get the SKU relationship and other information?

**Comment by stefnats** [comment]
You could upgrade to the latest version of that api `2020-12-01` and use `searchCatalogItems`:

https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#searchcatalogitems
