### ISSUE TITLE
Using which endpoint I can retrieve non FBA inventory list of Seller 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [amzn/selling-partner-api-docs#1722]
Using which endpoint I can retrieve non FBA inventory list of Seller

**Comment by abhitheawesomecoder** [comment]
Is it possible to get all my products in my seller account with one API call? I am non FBA seller in India.

**Comment by stefnats** [comment]
Sure, use the Reports API, you can use almost all inventory reports:

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#inventory-reports

**Comment by abhitheawesomecoder** [comment]
> Sure, use the Reports API, you can use almost all inventory reports:
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#inventory-reports

Can I get response (Seller Product/Inventory List) in Json or Array format?
