### ISSUE TITLE
[BUG] GetSubscription/CreateSubscription Leads to Access to requested resource is denied / Unauthorized.

### ISSUE THREAD

**Issue by antonycartwright** [amzn/selling-partner-api-docs#1725]
Hi Everyone,

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#what-is-the-notifications-api

I've followed the set up guide above for this (above) but I get an error. I'm using FikaAmazonAPI for C#, but I think the problem might lie with Amazon or something missing in the documentation (or maybe with me).

Basically, the GetSubscription/CreateSubscription request isn't successful. The only error I get is "Access to requested resource is denied Unauthorized."

I've checked the request, and again after it's signed and all appears fine. I can use GetDestination, GetOrders without any problems! I've spent about 20hrs on this same problem now and it's driving me mad!

Just wondering if anyone could help out. Thanks, Antony...

**Comment by webinsect-rishabh** [comment]
Did you solve this issue ?
