### ISSUE TITLE
The application is published but the MWS token is not coming.

### ISSUE THREAD

**Issue by msbeden** [amzn/selling-partner-api-docs#1729]
Hello.

I have both developer and seller profile. As a developer, I published my own app. However, as in the attached picture, the MWS token acquisition screen always stays in the loop. So when I press authorize, it throws it back to the same page. I can't get to the token page. What could be the reason for this? Can you help me?

![amazon](https://user-images.githubusercontent.com/14031329/143827240-69ade6f8-bb80-4e8b-9370-a2114e23b646.png)

**Comment by stefnats** [comment]
I had the same problem. Is this a hybrid application (MWS&SP)?
Creating a ticket solved the problem for me.
