### ISSUE TITLE
Getting FBA inbound shipment availability with SP-API

### ISSUE THREAD

**Issue by spchuang** [amzn/selling-partner-api-docs#1732]
I have been digging through the SP-API documentation to find out if there's data that shows when the incoming FBA inventory will be available for selling.

I am currently using report type `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL` to get all the POs with SKU and quantity, but I couldn't find where to see when those incoming inventory are estimated to be available for selling.

**Comment by stefnats** [comment]
Take a look at Report Types `GET_FBA_MYI_ALL_INVENTORY_DATA` or `GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA` - They should contain the data you are looking for.

**Comment by spchuang** [comment]
@stefnats  do those 2 reports show inbound shipment data (to FBA warehouses)?

**Comment by stefnats** [comment]
Hey @spchuang can you confirm that `afn-inbound-receiving-quantity` is the metric you are looking for ?

**Comment by stefnats** [comment]
Oh i see, you might want to know *when* the item / FNSKU is arriving? For that, i don't know that. I thought you meant that you need to inbound receiving/shipped quantity and not the actual date.

**Comment by johnkw** [comment]
This is a duplicate of bug #357. Please close in favor of the original.
