### ISSUE TITLE
Amazon SP-API: getMarketPlace api throws forbidden error

### ISSUE THREAD

**Issue by kannansathish** [amzn/selling-partner-api-docs#1734]
I am trying to access the SP API for gettingMarketPlace.
I have created the IAM USer, roles, and policy and then created the partner app in seller central.
When I access the API below error is thrown
io.swagger.client.ApiException: Forbidden
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:974)
	at io.swagger.client.ApiClient.execute(ApiClient.java:890)
	at io.swagger.client.api.SellersApi.getMarketplaceParticipationsWithHttpInfo(SellersApi.java:144)
	at io.swagger.client.api.SellersApi.getMarketplaceParticipations(SellersApi.java:131)
![Screenshot 2021-11-30 002416](https://user-images.githubusercontent.com/7507486/143992579-df91d8d0-26e2-482f-893b-303914efdb4e.png)
I am able to get the token and other data which is attached
Tried the same with refreshtoken and Scopes

**Comment by zhaoxianzhuang** [comment]
I have the same question, how do you resolve it

**Comment by kannansathish** [comment]
> question



> question

I started using the role instead of user. Thats the one change I did. Also

you need to create
AWSAuthenticationCredentials object
AWSAuthenticationCredentialsProvider object
and LWAAuthorizationCredentials
and needs to be passed to SellersApi

**Comment by mohit11115** [comment]
I have a weird issue, I am able to retrieve order details and everything works fine, but only in few systems. I tried running the same code, everything same on another computer and it gave a forbidden error.

As soon as this is executed orderV0Api.getOrderwithHttpInfo (OrdersV0Api.java), it gives a forbidden error.

What could be wrong? Please help.

**Comment by zjjzhengjunjie** [comment]
Sellers API can be called on my side, but only this API can be called. Other APIs respond to forbidden; Have you solved this problem?
