### ISSUE TITLE
Easyship Schedule Pickup & generate invoice

### ISSUE THREAD

**Issue by karan4364** [amzn/selling-partner-api-docs#1736]
Hi, I got the PII permission for buyer information and shipping labels. I want to generate invoices and labels using easyship feed API.

We are trying to use https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2020-09-04.md API 
 create feed (POST_EASYSHIP_DOCUMENTS) but before using this API. we need to move our order for fulfilment, and for that we need to generate a scheduled pickup slot. like in MWS API documentation and API flow. 
 
But we can not find anything in this documentation. If is there any other way to fulfil orders then plz mention it. So, we can fulfil our orders and generate invoices and labels using Easyship.

**Comment by hussain3134** [comment]
> Hi, I got the PII permission for buyer information and shipping labels. I want to generate invoices and labels using easyship feed API.
> 
> We are trying to use https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2020-09-04.md API create feed (POST_EASYSHIP_DOCUMENTS) but before using this API. we need to move our order for fulfilment, and for that we need to generate a scheduled pickup slot. like in MWS API documentation and API flow.
> 
> But we can not find anything in this documentation. If is there any other way to fulfil orders then plz mention it. So, we can fulfil our orders and generate invoices and labels using Easyship.

Hi Karan, Can you please check your profile for collaboration request?
