### ISSUE TITLE
web navigation failure question 

### ISSUE THREAD

**Issue by yc-czw** [amzn/selling-partner-api-docs#174]
in selling-partner-api-docs/guides/developer-guide/SellingPartnerApiDeveloperGuide(中文).md 
Links under the directory cannot jump to the specified location on the page
![image](https://user-images.githubusercontent.com/72860189/100960423-2ee52f80-355b-11eb-9d85-527cd6fb4e89.png)

**Comment by parvathm** [comment]
Hi @yc-czw,

Thank you for the feedback. We have updated our documentation team about the same and it should be fixed soon.

Thanks,
Parvathm,
Selling Partner API Developer Support.
