### ISSUE TITLE
Product category and browse path information missing in GET_MERCHANT_LISTINGS_ALL_DATA report

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#1740]
When I generate a `GET_MERCHANT_LISTINGS_ALL_DATA`, the columns containing product category and browse path data (`zshop-category1` and `zshop-browse-path`) are blank. I've tested this across several different seller accounts, and those fields are blank for every seller I've tested.

After doing some research, I see that people were running into this same issue with the old MWS system. Would it be possible to get this fixed so that we can retrieve the data we need? cc @ShivikaK @parvathm

Thanks!

**Comment by parvathm** [comment]
Hi @jlevers,

Thank you for raising the issue. Can you please give more details?  When you say same issue is with old MWS system meaning these columns zshop-category1 and zshop-browse-path are always blank and if those can be populated ? Can you please open a [support case ](https://sellercentral.amazon.com/gp/mws/contactus.html) with your report ids so we can investigate further.

Thanks,
Parvathm
SP API Developer Support.

**Comment by jlevers** [comment]
Yes, that's correct. I've opened a support case -- its reference number is 9286550631. Thanks!
