### ISSUE TITLE
[BUG] Order Acknowledgement not updating PO and not able to retrieve transaction ID status using API

### ISSUE THREAD

**Issue by RogerGatco** [amzn/selling-partner-api-docs#1744]
Hello,

  In short, Having two issues: 

1. The Order Acknowledgement sent over is not updating the PO.
2. When I get the Transaction ID, I'm not able to get the Transaction Status using the API

 I'm sending over an Order Acknowledgement 

`{
  "acknowledgements": [
    {
      "purchaseOrderNumber": "1O9JCZ4W",
      "sellingParty": {
        "partyId": "GATC9"
      },
      "acknowledgementDate": "2021-12-01T08:22:41.4170084-08:00",
      "items": [
        {
          "itemSequenceNumber": "1",
          "amazonProductIdentifier": "B01M3O6M0J",
          "vendorProductIdentifier": "011296148802",
          "orderedQuantity": {
            "amount": 1,
            "unitOfMeasure": "Eaches",
            "unitSize": 1
          },
          "netCost": {
            "currencyCode": "USD",
            "amount": "21"
          },
          "itemAcknowledgements": [
            {
              "acknowledgementCode": "Rejected",
              "acknowledgedQuantity": {
                "amount": 1
              },
              "rejectionReason": "TemporarilyUnavailable"
            }
          ]
        }
      ]
    }
  ]
}`

and I'm receiving the transaction ID at the end
`{"payload":{"transactionId":"3d918995-7acd-460d-8916-569aed7a87b2-20211201162243"}}`

Even after 15-30 mins the changes sent over in the acknowledgement are not being updated.

I'm not able to get the  Transaction Status either 

using GET
/vendor/transactions/v1/transactionStatus/{transactionId}

I get 'Access to requested resource is denied'

This is the method in my code

` static public void GetTransactionStatus(string TransactionID, string accessToken)        {
            Root grooty = JsonConvert.DeserializeObject<Root>(accessToken);
            RestClient restClient = new RestClient(live_url_base);
            // live_url_base = "https://sellingpartnerapi-na.amazon.com";
            // get_transaction_state = "/vendor/transactions/v1/transactionStatus"
            // content_form_urlencoded = "application/x-www-form-urlencoded"
            IRestRequest restRequest = new RestRequest(get_transaction_state + "/"+ TransactionID, Method.GET);
           restRequest.AddHeader("x-amz-access-token", grooty.access_token);
            restRequest = signatureHelper.SignRequest(restRequest, restClient, content_form_urlencoded);
            var result = restClient.Execute(restRequest);        }`

**Comment by ykl1993** [comment]
me too!!!!!

**Comment by pucsdian** [comment]
hey @RogerGatco 
the actual path is "/vendor/transactions/v1/transactions/{transactionId}"
the doc is bit wrong, so u can check [getTransactionStatus](https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-transaction-status-api/vendorTransactionStatus.md#get-vendortransactionsv1transactionstransactionid)

**Comment by ykl1993** [comment]
hi,
Thank you for your suggestion. At present, we also call the gettransactionstatus interface to check the status


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] Order Acknowledgement not updating PO and not able to retrieve transaction ID status using API (Issue #1744)





 
hey @RogerGatco
 the actual path is "/vendor/transactions/v1/transactions/{transactionId}"
 the doc is bit wrong, so u can check getTransactionStatus
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huoshidehua** [comment]
how to fixe it  ， 我目前用transactionId 获取 TransactionStatus 的数据 全是404？

**Comment by ykl1993** [comment]
sorry,&nbsp;We haven't solved this problem yet




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] Order Acknowledgement not updating PO and not able to retrieve transaction ID status using API (Issue #1744)





 
how to fixe it  ， 我目前用transactionId 获取 TransactionStatus 的数据 全是404？

**Comment by RogerGatco** [comment]
@huoshidehua @ykl1993 

The solution was provided by @pucsdian 

Instead of using /vendor/transactions/v1/transactionStatus

use /vendor/transactions/v1/transactions/{TransactionID}

**Comment by huoshidehua** [comment]
![image](https://user-images.githubusercontent.com/8519297/192214588-554901a3-47c9-4703-ae28-e0d466c9f8f4.png)


> @huoshidehua @ykl1993
> 
> The solution was provided by @pucsdian
> 
> Instead of using /vendor/transactions/v1/transactionStatus
> 
> use /vendor/transactions/v1/transactions/{TransactionID}

![image](https://user-images.githubusercontent.com/8519297/192214630-ad95bb5a-384b-4818-a2f2-dfe4b79a5f46.png)
through pic above it has used the url "/vendor/transactions/v1/transactions/{TransactionID}" ,but no working yet

**Comment by RogerGatco** [comment]
That is correct. That is how the url should look like.

**Comment by huoshidehua** [comment]
> That is correct. That is how the url should look like.

@RogerGatco But you know what?
it doesn't work

**Comment by RogerGatco** [comment]
This may be of further help

I used this to build my program  (C# Project):
https://github.com/cafeasp/Selling-Partner-API

and here's a video tutorial about it:
https://www.youtube.com/watch?v=5clKZvJdPk8

Hope that helps.
