### ISSUE TITLE
[BUG] Anyone else getting errors: Message: Invalid Input when using GET Purchase order call?

### ISSUE THREAD

**Issue by RogerGatco** [amzn/selling-partner-api-docs#1745]
Hi,

   Sometimes when I'm downloading the Purchase orders using GET /vendor/orders/v1/purchaseOrders

I'll get the following error message after going through a few pages

`{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
`

After maybe 2-3 tries it will work and download the complete list with no issue. Not sure if this is a Bug on the API or my code.

Anyone else experience this?

**Comment by wolendranh** [comment]
@RogerGatco 
I am getting same error for `/vendor/orders/v1/purchaseOrdersStatus`
We you able to resolve your issue?
