### ISSUE TITLE
BuyerInfo is blank when GiftMessage is present (RDT provided)

### ISSUE THREAD

**Issue by optikalefx** [amzn/selling-partner-api-docs#1746]
- I'm able to successfully use an RDT to make calls to getOrder and getOrderItems AND see the PII data. 
- For any order that does *not* have a gift message, I'm able to see BuyerInfo and see the email and name.

However, we are trying to get giftMessages to work. On our test orders where we can see gift messages in seller central, when we request the getOrderItems or getOrder with the RDT for those orders with giftMessages, then buyerInfo is blank.

x-amzn-requestid:'b921e3ed-8237-4b36-b2c9-eed071364a56'
x-amzn-trace-id:'Root=1-61a8450e-3218739012ec80cf50844cf1'

Is there a bug that doesn't allow BuyerInfo when there is a giftMessage present? How else can I get the gift message?

![image](https://user-images.githubusercontent.com/926885/144355485-c35a8027-a15f-4293-850c-11c555b4a375.png)

Proof of order with gift message in seller

![image](https://user-images.githubusercontent.com/926885/144355629-430c9f77-32ba-4356-b2f3-a898d56cd978.png)

**Comment by daniel031699** [comment]
@optikalefx 
Now I can get the RDT correctly. When calling the getorders interface with RDT, I always prompt unauthorized. Can you help me?
{ "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }

**Comment by fanslin** [comment]
So then did you get the BuyerInfo? Why can't I get BuyerInfo
