### ISSUE TITLE
OAuth for Amazon Seller Central is not authorizing and redirecting back to redirect_url

### ISSUE THREAD

**Issue by harshgour** [amzn/selling-partner-api-docs#1750]
Our application uses SP-API

This is dummy url - https://sellercentral.amazon.in/apps/authorize/confirm/amzn1.sp.solution.b0a3b81a-2003-4b3d-b53e-442a44d2a724?redirect_uri=<redirect-uri>&amazon_state=MTYzODQ1NzQxNjUxNmpu77-9XSdLbe-_vV_vv71h77-9HSbvv73vv71lFO-_vXTvv70H77-977-90ZDvv73vv71US1Hvv73vv70H77-9asuLfjvvv701C--_vXDvv71IOx1cSO-_ve-_ve-_vVsS77-9QkE2Elo%3D&state=am5fgl71523&version=beta

Here when we redirect for authorization completion. It gets stuck on this page
![image](https://user-images.githubusercontent.com/60436404/144451021-7007c908-b87e-4829-8ac5-1647859c1ba9.png)

After refreshing it multiple times, then it hits the redirect_url. It works sometimes in one go, and manier times we need to refresh it again and again to authorize.

this is not the behaviour described in the documentation.

**Comment by parvathm** [comment]
Hi,

Can you please open a support with urls you are using and workflow you are following? that will help us to understand better and find the root cause quickly.

Thanks,
Parvathm.
Selling Partner API Developer Support.

**Comment by harshgour** [comment]
Hey @parvathm ,

Thanks for so fast reply. What the issue here is - 

When we go for authorizing the app (consent) on sellercentral using the URL and then Approves it from sellercentral.
It redirects us back to callback_url and then again when we call amazon sellercentral url back. On the confirmation page it gets stuck. Being a developer when i traced this issue. Its because there are two network calls happening on sellercentral page for authorizing which sometimes doesnot happen.

![image](https://user-images.githubusercontent.com/60436404/144457534-e43e9dcd-a5ec-4def-a168-a789186513c2.png)

And this is because, it gets stuck on the page and we need to refresh it again for that network points are hit. When authorization happens then only it redirects us back to our application.

If anything remains unclear from my part, please ask me. We are facing this issue and it is really big for us now and needs to be resolved asap.

**Comment by mattybaer** [comment]
This is very much still happening to me as well. I am setting up my SP Hybrid APP. Our clients will be very confused when logging in their account if this happens. Did you figure anything else out @harshgour ?
