### ISSUE TITLE
Trying to find a way to get the author and publication date of book listings.

### ISSUE THREAD

**Issue by chriskshipcor** [amzn/selling-partner-api-docs#1757]
For some reason, Author and Publication date are not in either of the enforced nor not enforced attributes for listings in the ABIS_BOOK category when looking at the Product Type Definitions, which is resulting in those fields not showing up in the attributes section for the getCatalogItem response. Does anyone know of another way to get this information. I have also tried the listing information under product pricing api returns which doesn't provide the information either. 

It shows up in the MWS getMatchingProduct so the information has to be somewhere right?

**Comment by sbosman1** [comment]
i'm facing the same issue with the endpoint definitions missing attributes:

https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-type-definitions-api/definitionsProductTypes_2020-09-01.md

Even if the requirementsEnforced  ENFORCED it displays attributes that are not required also.  

The allowed values of attributes where are they located in which endpoint because I didn't find in the documentation?

**Comment by chapmanjw** [comment]
We are in the process of migrating product types to the Listings and Definitions APIs. The search operation of the Definitions APIs will list the product types that have been migrated for a particular marketplace: https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-type-definitions-api/definitionsProductTypes_2020-09-01.md.

For product types not yet migrated, requests will rollup to the root `PRODUCT` product type, which provides only the attributes common to all items. 

`ABIS_BOOK` is not yet launched.

**Comment by chapmanjw** [comment]
We do have this poll up around handling of attributes in the Catalog Items API for product types not yet migrated: https://github.com/amzn/selling-partner-api-docs/discussions/1609. So far, everyone is in favor of returning all attributes, even if they are not yet in the Definitions API or submittable in the Listings APIs.

We are using that feedback to guide our 2022 feature roadmap.

**Comment by sbosman1** [comment]
What is the timeline when e.g. marketplace NL  DE the definitions will work. Right now NL marketplace doesn't give any definitions. The DE marketplace gives not the required attributes e.g. countryoforigin is missing.

**Comment by chapmanjw** [comment]
@sbosman1 You should expect to see NL product types becoming available throughout 2022 (I don't have exact timelines). The product types currently launched in the DE marketplace should all be correct. Which product type(s) are you seeing missing required attributes (and any beyond country of origin)? Can you provide me a sample of your request?

**Comment by sbosman1** [comment]
@chapmanjw 

The category is: Automotive> Motorbikes, Accessories & Parts > Motorbike Clothing > Motorbike Helmets > Motorbike Helmets

the required fields in the amazon portal see screenhots, but the the api response of the required fields see below. Alot of difference. 

GET /definitions/2020-09-01/productTypes/AUTOMOTIVE_HELMET?requirements=LISTING_PRODUCT_ONLY&requirementsEnforced=ENFORCED&locale=en&marketplaceIds=A1PA6795UKMFR9


json respose of producttype "AUTOMOTIVE_HELMET"
`{
	"metaSchema": {
![listing_product_part1](https://user-images.githubusercontent.com/9403068/148087463-715d1f9d-eee1-4cea-8774-1bac6cc60434.jpg)
![listing_product_part2](https://user-images.githubusercontent.com/9403068/148087470-dac7ae0d-f0d7-453d-9f7d-590bab125950.jpg)
		"link": {
			"resource": "https://selling-partner-definitions-prod-dub.s3.eu-west-1.amazonaws.com/schema/amazon-product-type-definition-meta-schema-v1.json",
			"verb": "GET",
		},
	},
	"schema": {
		"link": {
			"resource": "https://selling-partner-definitions-prod-dub.s3.eu-west-1.amazonaws.com/schema/PRODUCT.json/",
	"requirements": "LISTING_PRODUCT_ONLY",
	"requirementsEnforced": "ENFORCED",
	"propertyGroups": {
		"offer": {
			"title": "Offer",
			"description": "Product Offer",
			"propertyNames": [
				"list_price",
				"max_order_quantity",
				"gift_options",
				"uvp_list_price"
			]
		},
		"images": {
			"title": "Images",
			"description": "Provide media content, such as product images",
			"propertyNames": [
				"main_product_image_locator",
				"other_product_image_locator_1",
				"other_product_image_locator_2",
				"other_product_image_locator_3",
				"other_product_image_locator_4",
				"other_product_image_locator_5",
				"other_product_image_locator_6",
				"other_product_image_locator_7",
				"other_product_image_locator_8",
				"swatch_product_image_locator"
			]
		},
		"shipping": {
			"title": "Shipping",
			"description": "Information to determine shipping and storage of your product (e.g., package dimensions, weight, volume)",
			"propertyNames": [
				"item_dimensions",
				"item_package_dimensions",
				"item_package_weight"
			]
		},
		"safety_and_compliance": {
			"title": "Safety & Compliance",
			"description": "Information to indicate product compliance, hazardous materials, and legal and safety warnings (e.g., lithium batteries, choking hazards, Consumer Product Safety Information Act (CPSIA))",
			"propertyNames": [
				"country_of_origin",
				"batteries_required",
				"batteries_included",
				"battery",
				"num_batteries",
				"number_of_lithium_metal_cells",
				"number_of_lithium_ion_cells",
				"lithium_battery",
				"supplier_declared_dg_hz_regulation",
				"hazmat",
				"safety_data_sheet_url",
				"item_weight",
				"ghs"
			]
		},
		"product_identity": {
			"title": "Product Identity",
			"description": "Information to uniquely identify your product (e.g., UPC, EAN, GTIN, Product Type, Brand)",
			"propertyNames": [
				"item_name",
				"merchant_suggested_asin",
				"recommended_browse_nodes"
			]
		},
		"product_details": {
			"title": "Product Details",
			"description": "Information and characteristics to describe the product to support search, browse and detail page content (e.g., bullets, product features, model, style name)",
			"propertyNames": [
				"generic_keyword",
				"color",
				"language"
			]
		}
	},
	"locale": "en",
	"marketplaceIds": [
		"A1PA6795UKMFR9"
	],
	"productType": "PRODUCT",
	"productTypeVersion": {
		"version": "Up9pF5YUJ95hQD2x8sDBXkaY3B3oE1sJO",
		"latest": true,
		"releaseCandidate": false
	}
}`

**Comment by chapmanjw** [comment]
@sbosman1 If you use the search operation of the Product Type Definitions API, you can see that `AUTOMOTIVE_HELMET` has not yet been migrated to the APIs. If you look in the response of your get request, you can see that the product type was rolled up to `PRODUCT` (which is the root product type containing attributes applicable to all product types). 

Once the `AUTOMOTIVE_HELMET` product type launches in the APIs, you will see comparable requirements and attributes in both the APIs and Seller Central. 

You can poll the search operation for the updated list of launched product types. And you can subscribe to this notification that will notify you when new product types are launched: https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#product_type_definitions_change
