### ISSUE TITLE
400 Bad Request in SP-API

### ISSUE THREAD

**Issue by Raf2061** [amzn/selling-partner-api-docs#176]
I'm new in SP-API
Recently I've open an account developer and I've follewed all the istructions in https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuideForVendors.md creating and AWS Account, with IAM User, Role and Policy. Also i've created an app linked to IAM Role. 
I worke in PHP I'm able to get access_token but when send curl to the sandbox for purchaseOrders I receive 400 Bad Request, obviously I check more and more my code but I don't find any trouble (check data format, check signing key, check signature calculation, canonical headers, credential scope format, authorization header etc).
I write to support twice in a week but none answer me. Someone have had same problem and could help me?
Thanks

**Comment by ramieblatt** [comment]
I experienced a slew of these 400 Bad Request errors when working with the purchaseOrders API call and finally narrowed it down to the encoding of the createdAfter and createdBefore URL parameters. They need to be escaped. It was easier to simply truncate to use date only (vs escaping date and time). 

Please note another issue you might run into after you get past the 400 Bad Request issue is that you need to send the 'x-amz-access-token' header name using lowercase, ie 'X-Amx-Header-Token' will fail with an 'Access Denied' error with message 'Access token is missing in the request header'. 

Here is a (redacted) working production call, below.

```
_> GET https://sellingpartnerapi-na.amazon.com/vendor/directFulfillment/orders/v1/purchaseOrders?shipFromPartyId=XXXX&limit=N&createdAfter=2020-12-02&createdBefore=2020-12-05&sortOrder=DESC&includeDetails=true
Content-Type: application/json
Cache-Control: no-cache
Host: sellingpartnerapi-na.amazon.com
x-amz-access-token: Atza|IwEBI...
x-amz-date: 20201206T015109Z
User-Agent: ....
x-amz-content-sha256: e3b0c44298f....
Authorization: AWS4-HMAC-SHA256 Credential=AKI...../20201206/us-east-1/execute-api/aws4_request, SignedHeaders=cache-control;content-type;host;user-agent;x-amz-access-token;x-amz-content-sha256;x-amz-date, Signature=86c21....
Connection: close


< 200 OK
Date: Sun, 06 Dec 2020 01:51:10 GMT
Content-Type: application/json
Content-Length: 4018
Connection: close
x-amzn-RequestId: 4a8c6f....
x-amzn-RateLimit-Limit: 10.0
x-amz-apigw-id: XG3aMH....
X-Amzn-Trace-Id: Root=1-5fcc3.....

{"payload":{"pagination":{"nextToken":"WyJUV2d...."},"orders":[{"purchaseOrderNumber":"Tt....","orderDetails":{"customerOrderN....._

```

**Comment by Raf2061** [comment]
Thank You for your response, I've tried but the response is the same

my url is : 
https://sandbox.sellingpartnerapi-eu.amazon.com/vendor/orders/v1/purchaseOrders?createdBefore=2019-09-21T00:00:00Z&createdAfter=2019-08-20T14:00:00Z&includeDetails=true&limit=2&sortOrder=DESC

header:
Authorization:AWS4-HMAC-SHA256 Credential=AKI.../20201214/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date, Signature=c3b4...
host:https://sandbox.sellingpartnerapi-eu.amazon.com
user-agent: ...
x-amz-access-token:Atza...
x-amz-date:20201214T105134Z

I notd that yout have also cache-control, content-type and x-amz-content-sha256 but the documentation nothing says about these.

**Comment by ramieblatt** [comment]
Your createdAfter and createdBefore URL parameters either need to be escaped or truncated. It was easier for us to simply truncate to use date only (vs escaping date and time, ie "2019-09-21" vs "2019-09-21T00:00:00Z"). 

That is, tweak your URL to be more like below:

https://sandbox.sellingpartnerapi-eu.amazon.com/vendor/orders/v1/purchaseOrders?createdBefore=2019-09-21&createdAfter=2019-08-20&includeDetails=true&limit=2&sortOrder=DESC

Regarding headers, the cache-control and content-type are pretty standard, as long as you include those in the signing process canonical URL it wshould be fine. The x-amz-content-sha256 header is added by the signing process.

We use the AWS SDK to sign our requests.

**Comment by FloderCC** [comment]
I am working on uploading a product using Feed. And if I use sandbox mode, it also returns an error 400. However, in production mode it works fine

**Comment by tigusigalpa** [comment]
I've got the same error `400 bad request` with Auth API call, the reason was because of `host` header param: https://stackoverflow.com/a/71550626/724816

**Comment by rugved1991** [comment]
Hi @tigusigalpa,

If you are still seeing the same issue, please respond on this case. If you have opened a support case, please provide the case ID and we will follow up on it.

Best,
Rugved
Solutions Architect, SP API

**Comment by Romerolweb** [comment]
Hi,
I am having the same error.
Those are the parameters I am sending. I also tried truncating the "createdSince" and "createdUntil", but it returned the same error.
Params.
array(2) {
  ["query"]=>
  array(6) {
    ["feedType"]=>
    string(18) "JSON_LISTINGS_FEED"
    ["marketplaceIds"]=>
    string(13) "ATVPDKIKX0DER"
    ["pageSize"]=>
    int(10)
    ["processingStatuses"]=>
    string(9) "CANCELLED"
    ["createdSince"]=>
    string(24) "2021-08-16T05:51:56.743Z"
    ["createdUntil"]=>
    string(25) "20221-05-16T05:51:56.743Z"
  }
  ["method"]=>
  string(3) "GET"
}

**Comment by kdfhhao** [comment]
When I use the order number to update the order status, the following problem occurs. When the same code is accessed normally in North America, the following error is reported in Europe, which is completely nonsensical.
400 bad request
Your browser sent a request that this server could not understand.<br />
Size of a request header field exceeds server limit.

**Comment by rugved1991** [comment]
Hi,

Please feel free to reopen the issue if the issue still persists. 

Best,
Rugved
Solutions Architect, SP API

**Comment by albinsopaj** [comment]
> I am working on uploading a product using Feed. And if I use sandbox mode, it also returns an error 400. However, in production mode it works fine

Hello. Did you manage to solve your problem? I'm now facing this problem and am unable to solve it. Any little help would be welcomed. Thanks :)
