### ISSUE TITLE
orders/v0/orders Endpoint Returns Invalid Input When I Use NextToken Parameter 

### ISSUE THREAD

**Issue by whoisylmz** [amzn/selling-partner-api-docs#1760]
Hello!

I saw a similar issue under issues part but I still get this issue.

These is my request url: https://sellingpartnerapi-fe.amazon.com/orders/v0/orders?MarketplaceIds=A1VC38T7YXB528&CreatedAfter=2021-11-01T13:57:31.2311892-04:00&NextToken=48UVp5s4HXCaJqJYLDm0ZAmQazDrhw3CgLPzztbN4VLsPvcBDhk+ZSuvAXYoXBqsxqXyQLkGMBs8VhF73Xgy+7L5zZNaYhY9Z8nuGvBXu6ASqUXfCwRkC6jG/gs8du+iInTAy+XKVmRZBY+oaVuyc8QON+K1yc/YUvmX//oc7yrefkpTke4IDKBJzjTnMzPGf2GLmUGyr9UGnxD0RJmrryegoU0IPZxXbpikPhlKHkMiDjaCzOAHHsAnamzXeKHXMBO/reDY2s/1iHKpBf1TYGdbSH0uKs2BeLE0br61/ZdFU0/4LsbyGM+RCEjxtHY0FjoFWhvlQsXg8bNdZQXmAExq8POkbR6G1Vj7+03w3rpNs9lQRwXrBpQYabVIwlZ4AbSBeM4dJKFPoHVKB7NbV61OyEkQXs5840YeQQ6QUZ97kFxOI2l86A==

and here is the result: 

{
    "errors": [
        {
            "message": null,
            "code": "InvalidInput"
        }
    ]
}

Thanks for your interest!

**Comment by JeromeXapix** [comment]
Hey,

You might need to encode the token before adding it as a QS parameter (e.g. in javascript: encodeURIComponent(YOUR_TOKEN)). This worked for me.

Hope it helps!

**Comment by whoisylmz** [comment]
It works for me!!! Yes! Thanks a lot!

**Comment by saleweaver** [comment]
In general, you don't pass anything but the NextToken to a NextToken operation
