### ISSUE TITLE
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE | Not getting all orders data. 

### ISSUE THREAD

**Issue by EvolverPawan** [amzn/selling-partner-api-docs#1761]
We have a polling mechanism into the our app to periodically fetch data from GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE but we are not getting all orders in this report. 
We are polling the data everyday and checking all the settlement reports newly generated by amazon.
Any suggestions what could be the reason we are not getting all the data.

Any suggestions are appreciated. Thanks.

**Comment by kzpreneur17** [comment]
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE only gives data for last 90 days.

**Comment by michelexport** [comment]
Hi guys, we are experiencing the same issues, from GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE we can not pull down "previous reserve amount balance" and "payable to amazon" fields, they are not displayed at all.
Anyone experiencing the same?

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
