### ISSUE TITLE
Is inventory report content same for all marketplaces?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#1765]
Hello,
Does anyone know that **GET_MERCHANT_LISTINGS_ALL_DATA** inventory **report content is same for all marketplaces**. If so, can I use same parse report content method for all marketplaces?
Thanks

**Comment by xiaoyu-tamu** [comment]
No

**Comment by arturll7** [comment]
@xiaoyu-tamu thank you for the answer. Do you have the templetes for different marketpalces (canada, australia, japan ...)?
Or is there an Amazon page that shows the exact the inventory report file content?

**Comment by saleweaver** [comment]
There isn't any such information available. At least I haven't found it in 10 years.
