### ISSUE TITLE
Not able to create subscription for FULFILLMENT_ORDER_STATUS

### ISSUE THREAD

**Issue by sunita1988** [amzn/selling-partner-api-docs#1766]
HI i have created SQS with standard and also added policy

{
"Version": "2008-10-17",
"Statement": [
{
"Sid": "__sender_statement",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::124327721787:root"
},
"Action": [
"SQS:SendMessage",
"SQS:GetQueueAttributes"
],
"Resource": "arn:aws:sqs:us-east-1:124327721787:SQS_Standart"
}
]
}

i can able to create a destination

[resource] => Array
(
[sqs] => Array
(
[arn] => arn:aws:sqs:eu-west-1:124327721787:notification
)

                        [eventBridge] => 
                    )

                [destinationId] => 291d0c5a-8ad6-43d0-9cd1-1e12f8027bf0
                [name] => order_status
but when i am going to create subscripton i am getting error access denie can any one help in this .

this is the parameter i am using for create subscription

$notification_type = 'FULFILLMENT_ORDER_STATUS';
$subscription_body = '{
"payloadVersion":"1.0",
"destinationId": "4301ee2e-18a5-4c8a-b886-ff599db680a6"

}';

Thanks & Regards

**Comment by kpconnell** [comment]
Create destination is grantless.  When you exchange an LWA token you have to do something like the follow:

`   LWACredentials.RefreshToken = grantless ? null : refreshToken;
            LWACredentials.Scopes = grantless ? new List<string> { "sellingpartnerapi::notifications" } : null;
`

**Comment by sunita1988** [comment]
Hi
I can able to create a destination by using grantless but when I am doing
create subscription i am getting an access denied issue, for create
subscription i am doing without grantless

Thanks in advance
