### ISSUE TITLE
Create Feed Failing - Unauthorized

### ISSUE THREAD

**Issue by NetRushJacob** [amzn/selling-partner-api-docs#177]
Pulling focus back to a specific issue that #122 started with, but went in a different direction.

We are unable to call the CreateFeed API with any success. All our attempts are met with Unauthorized - Access to the resource is forbidden responses.

So far, all our other calls are working as expected (Feeds, Reports, Orders, Fulfillment Inbound, so far).

We follow the Feeds [Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md) and are able to get through steps 1 and 2 without issue. When we pass the CreateFeedRequest to the POST, it fails. 

We are using C# Standard 2.1 | Core 3.1 and RestSharp 106.11.7 (latest)
Our application is configured to have all roles and authorized on our seller account
Our application uses the user IAM (vs role)

**Request Body:**
```
{
  "feedType":"POST_FLAT_FILE_LISTINGS_DATA",
  "marketplaceIds":["ATVPDKIKX0DER"],
  "inputFeedDocumentId":"amzn1.tortuga...."
}
```

**Signed Headers:**
```
accept;content-type;host;x-amz-access-token;x-amz-date
```

**Canonical Request:**
```
POST
/feeds/2020-09-04/feeds

accept:application/json
content-type:application/json; charset=UTF-8
host:sellingpartnerapi-na.amazon.com
x-amz-access-token:Atza|...
x-amz-date:20201203T182652Z

accept;content-type;host;x-amz-access-token;x-amz-date
de39df29a3b28878725b5e0c7cb3a5214955df90b1c2dabeb998515183ced897
```

**String to Sign:**
```
AWS4-HMAC-SHA256
20201203T182652Z
20201203/us-east-1/execute-api/aws4_request
74ee49ac6b3c078155e7863f76cd42f11b3179feccd8f8e9a8c1e44853c8ca34
```

**Authorization Header:**
```AWS4-HMAC-SHA256 Credential=AKIA.../20201203/us-east-1/execute-api/aws4_request, SignedHeaders=accept;content-type;host;x-amz-access-token;x-amz-date, Signature=2c27c...
```

**Response Headers:**
```
Date: Thu, 03 Dec 2020 18:28:53 GMT
x-amzn-RequestId: 14dfbf41-3e75-4902-ba4c-f9511fb722d2
x-amz-apigw-id: W_Qv5GRsIAMFYOw=
X-Amzn-Trace-Id: Root=1-5fc92e65-0b4d90bf6505a5284f0c45d0
Content-Type: application/json
```

**Response Content:**
```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}
```

**Comment by parvathm** [comment]
Hi @NetRushJacob ,

We are looking into the issue. Can you please open a [support case](https://developer.amazonservices.com/support) with your application id details we can further investigate.

Thanks,
Parvathm
Selling Partner API Developer Support

**Comment by NetRushJacob** [comment]
@parvathm Case number 7688793201
Thank you!

**Comment by parvathm** [comment]
Hi @NetRushJacob,

We fixed the issue with POST_FLAT_FILE_LISTINGS_DATA feed type. Can you please try the request now? 

Thanks,
Seller Partner API Developer Support.

**Comment by tharrington** [comment]
@parvathm I have been receiving a similar error. I opened a case with amazon but haven't heard back. Can you help?

ID 7675148021

**Comment by NetRushJacob** [comment]
@parvathm I can confirm that the create feed worked this time around!  Thank you for pushing through and fixing it!!

**Comment by voronytskyi** [comment]
Same issue on my end. Support request ID: 6587222652 (amazon.co.uk)

**Comment by hinavinayak** [comment]
@tharrington @voronytskyi 
Hello, Please ensure that your applications have the 'Product Listing' Role assigned to it to be able to create POST_FLAT_FILE_LISTINGS_DATA feed. 

You will need to create a new refresh-token when add the role.

**Comment by hinavinayak** [comment]
> @parvathm I can confirm that the create feed worked this time around! Thank you for pushing through and fixing it!!
> 
> Any chance some detail can be put here on the fix so others might know what to do if they run into it?

The POST_FLAT_FILE_LISTINGS_DATA Feed was originally missed during the mapping of the feeds to a role. Once we mapped the feed to the correct role the access denied issue was resolved. Since you had the ProductListing Role assigned to the application

**Comment by esalesplatform** [comment]
Tnx
