### ISSUE TITLE
Note - SP API Feeds , Orders  and Few other API Service availability

### ISSUE THREAD

**Issue by pprbhm** [amzn/selling-partner-api-docs#1771]
Beginning [12/07/2021] at [7:55 AM PST], Marketplace Web Service APIs, SP API and other tools were reported to be experiencing an error rate increase. We are currently investigating the issue.

**Comment by gokigoks** [comment]
Can confirm 504 and 500 errors coming back from the getAuthorizationCode endpoint as well.

**Comment by parvathm** [comment]
Hi,

Services are operating at normal capacity now. If you have any issues or questions regarding this please open a support case.

Thanks,
Parvathm,
Selling Partner API Developer Support.
