### ISSUE TITLE
Service Fee Event Lists - Not enough informations

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#1778]
Hi,

I found another bug in Amazon' financial events api.
Its related to ServiceFeeEventList response

               ` "ServiceFeeEventList": [
                {
                    "AmazonOrderId": "xl9o50V981",
                    "FeeList": [
                        {
                            "FeeType": "FBADisposalFee",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -0.28
                            }
                        }
                    ]
                },
                {
                    "AmazonOrderId": "xl9o50V981",
                    "FeeList": [
                        {
                            "FeeType": "FBADisposalFee",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -4.48
                            }
                        }
                    ]
                },
                {
                    "AmazonOrderId": "xl9o50V981",
                    "FeeList": [
                        {
                            "FeeType": "FBADisposalFee",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -0.4
                            }
                        }
                    ]
                }
            ],
`

As you can see in the screenshot, there's no other helpful information like posted_date, purchase_date , etc related to dates. This a useless response since we don't know which date this fee happened/created.Also notice the amazon order id, its kind of messed up, I think the correct format for the order id is 333-xxxxxxx-xxxxxx.

I hoped somebody from amazon support will finally fix bugs like this

**Comment by stefnats** [comment]
Hey there, 

i think you could use the `GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA` Report for this:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#fulfillment-by-amazon-fba-reports

> Tab-delimited flat file report. This report contains all the removal orders, including the items in each removal order, placed during any given time period. This can be used to help reconcile the total number of items requested to be removed from an Amazon fulfillment center with the actual number of items removed, along with the status of each item in the removal order. Content updated in near real-time. For FBA sellers. For Marketplace and Seller Central sellers.

The `AmazonOrderId` is not the Order ID as in "a buyer orders something from the seller over Amazon", but this is the "Removal Order ID" when the FBA Seller creates a Removal Order to dispose/reship his FBA Inventory. Hope that helps!

**Comment by ianrussel** [comment]
Hi @stefnats , thanks for the comment.I already tried the report `GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA`, the data is not complete also. Thats why I tried the financial events api.  For example, October 28, we have disposal fee, but cant find it.I even tried to pull the report for the whole month(starttime October 1 - endtime October31).The report contains request_date, last_date_updated and shipment_dates

**Comment by arshul-acqu** [comment]
I am also facing the same issue, posted_date is missing on service fee events

**Comment by ITmoxiang** [comment]
Excuse me, has this problem been solved? I have the same problem.

**Comment by ianrussel** [comment]
@ITmoxiang no. We already lost 2 customers due to inaccurate data .

**Comment by ianrussel** [comment]
Why this issue still not solve?.???????????

**Comment by little-eyes** [comment]
I am also facing it. Can we resolve this issue ASAP? it makes the financial data un-reliable from this API.

**Comment by ianrussel** [comment]
still unsolve for many months.i closed it as amazon doesnt want to help

**Comment by kmizzi** [comment]
Can confirm this is still a problem

**Comment by mott7** [comment]
Please fix this issue urgently.

**Comment by takeno-dev** [comment]
I think that is the problem too.
I want to get these Date so I am running the process in periods of 1 day each. It is very annoying.

**Comment by widdydev** [comment]
> I think that is the problem too. I want to get these Date so I am running the process in periods of 1 day each. It is very annoying.

Same, I'm fetching the financial events for each date with the corresponding "postedAfter" and "postedBefore" date and overwrite the posted_date with my date.
Nevertheless, it would be helpful to get at least the ASIN or SKU of the disposed item.
