### ISSUE TITLE
PO updatedAfter and updatedBefore is returning all POs in VendorCentral

### ISSUE THREAD

**Issue by skagrawal10** [amzn/selling-partner-api-docs#178]
Hi,

in PO Orders API, I would like to get incremental data and hence passing these below as request parameters - 

updatedAfter=2020-12-01&updatedBefore=2020-12-03

But, it is returning all PO orders. where as createdAfter & createdBefore filters are working fine as expected.

**Comment by ShivikaK** [comment]
Hello @skagrawal10 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
