### ISSUE TITLE
Step 2. Encrypt and upload the feed data. SignatureDoesNotMatch

### ISSUE THREAD

**Issue by voronytskyi** [amzn/selling-partner-api-docs#179]
Hi to Everyone, 

I trying to complete this feed submissions request: https://github.com/amzn/selling-partner-api-docs/blob/a5ccbdd2f0918dca6960dfbefedf4ebebe758a74/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md#step-2-encrypt-and-upload-the-feed-data

But I getting this error: SignatureDoesNotMatch
![image](https://user-images.githubusercontent.com/17167509/101212924-394e1900-3682-11eb-826c-74beac53c73d.png)

Looks like I have to sign my content data. But for some reason X-Amz-Signature is already set in this request (it comes from previous Create Feed Document request).

Pls advice

**Comment by markfrederik** [comment]
Hi Voronytskyi,

Did you find the reason for this issue (SignatureDoesNotMatch) ?
Could you please share the solution for this if you have it ?

Thanks.

**Comment by ahmet-hub** [comment]
Hi markfrederik,

Did you find the reason for this issue (SignatureDoesNotMatch) ?
Could you please share the solution for this if you have it ?

Thanks.
