### ISSUE TITLE
reports-api: access to the resource is forbidden 

### ISSUE THREAD

**Issue by forFutrue** [amzn/selling-partner-api-docs#1796]
I am using python, It works fine when calling the GET_MERCHANT_LISTINGS_ALL_DATA or GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL.

My client is has brand registry, When i try and call GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT i get a 403:
{'errors': [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]}

Can you help me with the issue?

**Comment by forFutrue** [comment]
Our account does not have the [brand analytics] role option, but Other accounts can choose this.

![our](https://user-images.githubusercontent.com/88941579/145732649-6bb29145-7dab-42df-97e9-e0c15cf00235.jpg)
![other account](https://user-images.githubusercontent.com/88941579/145732671-6ac38ca8-d4b3-425d-acbf-10b832753782.jpg)

**Comment by stefnats** [comment]
Did you enable the vendors option as seen on the top right in your Screenshot?

**Comment by forFutrue** [comment]
> 

yes, enable vendors option.

**Comment by estebanangel** [comment]
we have the same issue here, we wanted to query the Brand Analytics endpoints but we're not able to add the role into the app settings and dev profile. Any clue on how to do it? the checkbox doesn't appear
