### ISSUE TITLE
for help, who can tell me the process of fba shipment create 

### ISSUE THREAD

**Issue by bk757** [amzn/selling-partner-api-docs#1798]
step1、i post createInboundShipmentPlan Request and Get Response:
Array
(
    [payload] => Array
        (
            [InboundShipmentPlans] => Array
                (
                    [0] => Array
                        (
                            [ShipmentId] => FBA16HWXD2MC
                            [DestinationFulfillmentCenterId] => GYR3
                            [ShipToAddress] => Array
                                (
                                    [Name] => GYR3
                                    [AddressLine1] => 8181 W ROOSEVELT ST
                                    [City] => PHOENIX
                                    [StateOrProvinceCode] => AZ
                                    [CountryCode] => US
                                    [PostalCode] => 85043-2356
                                )

                            [LabelPrepType] => SELLER_LABEL
                            [Items] => Array
                                (
                                    [0] => Array
                                        (
                                            [SellerSKU] => ML-O7U9-E179
                                            [FulfillmentNetworkSKU] => X00319LNDL
                                            [Quantity] => 29
                                        )

                                )

                            [EstimatedBoxContentsFee] => Array
                                (
                                    [TotalUnits] => 29
                                    [FeePerUnit] => Array
                                        (
                                            [CurrencyCode] => USD
                                            [Value] => 0.3
                                        )

                                    [TotalFee] => Array
                                        (
                                            [CurrencyCode] => USD
                                            [Value] => 8.7
                                        )

                                )

                        )

                )

        )

)

step 2: i post  createInboundShipment and get a Eorre:
[GuzzleHttp\Exception\ClientException]
  Client error: `PUT https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments/FBA16HWXD2MC` resulted in a `400 Bad Request` response:
  {
    "errors": [
      {
        "code": "InvalidInput",
        "message": "ShipmentId does not exist",
        "details": ""
     (truncated...)

The ShipmentId I got by Step1 createInboundShipmentPlan , why it say not exist? 

What is the problem？

**Comment by bk757** [comment]
有没有中国的开发者帮助一下，谢谢！

**Comment by yao-big** [comment]
这不就是 货件ID不存在吗?  你先查下货件ID返回的状态看一下

**Comment by yao-big** [comment]
一个是计划 一个是货件
