### ISSUE TITLE
How to query Seller SKU with ASIN?

### ISSUE THREAD

**Issue by kestrel1974** [amzn/selling-partner-api-docs#1802]
Hi,

I have tried to use the catalog-items-api (getCatalogItem and searchCatalogItems), product-pricing-api (getPricing) with ASIN as input to retrieve the seller SKU, which is need to patch the inventory or price using the listing-items-api.
The products are usually added using the web interface and the SKU is generated by Amazon.
The SKU in the returned data is always null and getting "attributes" for returned data is also null.
Is this an authorization issue or is it simply not possible to query my seller SKU for a given ASIN?

Thanks, Daniel.

**Comment by PengBridgeMedia** [comment]
Anyone has the answer? I got the same problem.

**Comment by nkev** [comment]
I have the same issue for weeks. Does anyone know which API to call to get the Vendor SKU by ASIN? Surely, it's possible!
