### ISSUE TITLE
Which API to use for FedEx shipment confirmation?

### ISSUE THREAD

**Issue by ZaidPathan** [amzn/selling-partner-api-docs#1803]
We are using SP-API to get orders and then create FedEx shipping label for that order.
We now want to confirm the shipment via API, how can we achieve this?
We tried to look into [merchant fulfilment API](https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md), however couldn't find any API related to it.

**Comment by hardikradixweb** [comment]
Hello @ZaidPathan,

Did you found any solution for this?

**Comment by ZaidPathan** [comment]
@hardikradixweb Sorry, couldn't find such API yet.
