### ISSUE TITLE
[BUG] The Inventory Health report will be discontinued in 2022 and is being replaced by the new Manage Inventory Health report.

### ISSUE THREAD

**Issue by ditinus** [amzn/selling-partner-api-docs#1804]
The Inventory Health report will be discontinued in 2022 and is being replaced by the new Manage Inventory Health report. When will the "Manage Inventory Health report" be available in SP-API?

**Comment by eric-zhu-uw** [comment]
Agreed. Would be nice to get Manage Inventory Health report accessible through SP-APIs since it's provides real-time data vs. the stale data in Inventory Health report.

**Comment by moltar** [comment]
Yes, looking for that too.

March is just around the corner.
