### ISSUE TITLE
Can't create a GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING always return 400 [SANDBOX]

### ISSUE THREAD

**Issue by daygarcia** [amzn/selling-partner-api-docs#1806]
Hello everyone,

I am implement the Reports API and last week i created some working reports using the json below:

```json
{
	"report_type": "GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING",
	"data_start_time": "2021-12-12T15:04:48+00:00"
}
``` 

But now I'm trying to create a FBA report, more specifically GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA and always receive a 400 error

```json
[{"code":"InvalidInput","message":"Could not match input arguments"}]
```

The error now occurs both on GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING (before working) and GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA 

The error is not clear enough about how to fix the request

Thanks

**Comment by jprochazka** [comment]
Having the same issue.
It seems to only happens when using the sandbox for me.

**Comment by DayGarcia** [comment]
> Having the same issue. It seems to only happen when using the sandbox for me.

For me too. I edited the title to include sandbox only

**Comment by deadmouse** [comment]
@DayGarcia @jprochazka Could you solve the error?

**Comment by deadmouse** [comment]
For me it has been resolved by reading this: [https://github.com/jlevers/selling-partner-api/issues/168](https://github.com/jlevers/selling-partner-api/issues/168). Only specific data can be sent, otherwise SPAPI returns error. Example with CreateReportSchedule:

```
$createReportScheduleSpecification = new CreateReportScheduleSpecification();
$createReportScheduleSpecification->setReportType("FEE_DISCOUNTS_REPORT");
$createReportScheduleSpecification->setMarketplaceIds(["A1PA6795UKMFR9", "ATVPDKIKX0DER"]);
$createReportScheduleSpecification->setPeriod("PT5M");
$createReportScheduleSpecification->setNextReportCreationTime("2019-12-10T20:11:24.000Z");
```
