### ISSUE TITLE
Developer xxxxx does not have access to this application id.

### ISSUE THREAD

**Issue by One2r** [amzn/selling-partner-api-docs#1809]
Hi,@ShivikaK

I am getting the following error when accessing the resource https://sellingpartnerapi-eu.amazon.com/authorization/v1/authorizationCode, I have crated the case 9347608531.

And my app was Published, I got this error from a mouth ago to now. 

I really need you help .

**Comment by ShivikaK** [comment]
Hello @One2r 

Thank you for raising this issue.

Your support case is being reviewed by the support team and you should receive an update on the case within 7 days.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by One2r** [comment]
@ShivikaK Thanks

**Comment by r00mz** [comment]
@ShivikaK 
same to the issue, And my app was published, I will be crazy!.I had created the case 9488929101.
please help me, thx

**Comment by lobotomisador** [comment]
@One2r @r00mz I think this is because the seller account needs to authorize you as a developer in order for your calls to go through on their behalf.
