### ISSUE TITLE
POST /uploads/2020-11-01/uploadDestinations/messaging return 403,can you help me?

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-docs#181]
GuzzleHttp\Exception\ClientException
Client error: `POST https://sellingpartnerapi-na.amazon.com/uploads/2020-11-01/uploadDestinations/messaging` resulted in a `403 Forbidden` response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...) 

url:/uploads/2020-11-01/uploadDestinations/messaging
method:POST
request is:
 array:3 [▼
  "query" => array:2 [▼
    "marketplaceIds" => "ATVPDKIKX0DER"
    "contentMD5" => "c72b9698fa1927e1dd12d3cf26ed84b2"
  ]
  "headers" => array:1 [▼
    "x-amz-access-token" => "Atza|IwEBIOinGtHdX9lGS0NGVYDKL3ZG9w4YJEDelbkLwdUk59nrl1UpjW4D_flZoFoq9_z_H_ic-f-8z0MKgQmJJcumDDlC_0xPApsD9fjg4tJKBVLKuJaZZTePWoEpk9nCw2JBs8V2L9LT9sx5ZNgrph7kTSW ▶"
  ]
  "synchronous" => true
]

**Comment by pprbhm** [comment]
Hi, What is your authorization status? Are you authorized to make call for this url:/uploads/2020-11-01/uploadDestinations/messaging? In order check logs, we need your AppId, RequestID, SellerID which is not advisable to post in public forum like GitHub. If you want to get more detailed troubleshooting steps please open a [Support Case](https://developer.amazonservices.com/support)
