### ISSUE TITLE
It would be very useful to have a bulk catalog API solution

### ISSUE THREAD

**Issue by coopernate** [amzn/selling-partner-api-docs#1816]
It would be very useful to have a bulk catalog API that would allow all ASINs to be returned when passing a selling partner id instead of having to call for each individual ASIN.  My company is using catalog data to understand the impact on brand analytics and also stores some attribution over time to determine if changes result in increased/decreased sales activity and customer sentiment.
==========================================================
It would be super useful to have an option to retrieve the catalog data for multiple ASINs all at once, so we don't have to loop over all our ASINs. 

My company uses the ASIN metadata to match it with our internal product metadata, but since we have noticed this data is not available in the Sales Diagnostic report generated by the API, the catalog API would be our best option.

_Originally posted by @DanielaZamoraUribe in https://github.com/amzn/selling-partner-api-docs/discussions/1718_

**Comment by chapmanjw** [comment]
@coopernate Going to resolve this issue in favor of the https://github.com/amzn/selling-partner-api-docs/discussions/1718 discussion (so we can have one thread to discuss). Thanks!
