### ISSUE TITLE
GetOrders:  return empty payload

### ISSUE THREAD

**Issue by ghost** [amzn/selling-partner-api-docs#1818]
I sent the following request using JavaAPI
```
AWS4 Canonical Request: '"GET
/orders/v0/orders
CreatedAfter=2020-09-01&MarketplaceIds=ATVPDKIKX0DER
accept:application/json
content-type:application/json
host:sellingpartnerapi-na.amazon.com
user-agent:Swagger-Codegen/1.0.0/java
x-amz-access-token:Atza|***

accept;content-type;host;user-agent;x-amz-access-token;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```
But returned an empty payload
```
 "payload": {
      "pagination": null,
      "orders": null
    },
```
Can someone help me?

**Comment by Mike-the-one** [comment]
I have the same issue.  Have you resolved this?

**Comment by adillucky** [comment]
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2021-04-27T16:20:44Z&MarketplaceIds=AKOAFLDV1D5DL

{
    "payload": {
        "Orders": [],
        "CreatedBefore": "2022-04-27T16:26:45Z"
    }
}

i m also facing this type of issue i have many orders in seller center but when i try to get order according to order ID its working  but when i try to get all orders i m facing this issue.

**Comment by coder771** [comment]
> https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2021-04-27T16:20:44Z&MarketplaceIds=AKOAFLDV1D5DL
> 
> { "payload": { "Orders": [], "CreatedBefore": "2022-04-27T16:26:45Z" } }
> 
> i m also facing this type of issue i have many orders in seller center but when i try to get order according to order ID its working but when i try to get all orders i m facing this issue.

do you know what was causing this.getting this issue in postman
