### ISSUE TITLE
Update Documentation: Step 1. Request a Login with Amazon access token

### ISSUE THREAD

**Issue by MST1122** [amzn/selling-partner-api-docs#183]
Please change documentation under the heading "Step 1. Request a Login with Amazon access token".
with the given example amazon gives the error: 

"error_description" => "The authorization grant type is not supported by the authorization server"
"error" => "unsupported_grant_type"

`Content-Type: application/x-www-form-urlencoded;charset=UTF-8`
to 
`Content-Type: application/json`

I figured it out after spending almost a week.

**Comment by parvathm** [comment]
Hi @MST1122,

When we use httpurlconnection and set the request property of content type as application/x-www-form-urlencoded;charset=UTF-8 we are able to get Accesstoken from server without any issues. Can you please check if there is some other issue?

Thanks,
Parvathm,
Selling Partner API Developer Support.
