### ISSUE TITLE
IsBuyBoxWinner returns incorrect data in both GetListingOffers and ANY_OFFER_CHANGED 

### ISSUE THREAD

**Issue by igoryan-k** [amzn/selling-partner-api-docs#1830]
Hello, I am getting issues with determining the buy box winner using the SP API.

GetListingOffers documentation says that IsBuyBoxWinner could be True for up to two offers (1 FBM and 1 FBA), but I found that it doesn’t guarantee that some other offer is an actual buy box winner.

Here is an example that I am observing. I receive a list of 20 offers with the top 4:

71.39 FBM - IsBuyBoxWinner = False
71.50 FBM- IsBuyBoxWinner = True
73.00 FBA - IsBuyBoxWinner = True
**74.63 FBA - IsBuyBoxWinner = False**
…

The actual winner is offer 4 - $74.63, even though offer 3 is marked with IsBuyBoxWinner = True.

GetCompetitivePricing() returns offer 2 as BuyBoxPrices.

I am seeing the exact same data via the ANY_OFFER_CHANGED feed for this ASIN.

Is this a known issue?

**Comment by stefnats** [comment]
I observe the same issue for years, also in MWS. Amazon says everything is correct.

**Comment by xiaoyu-tamu** [comment]
Multiple sellers can own buy box. It then determined dynamically based on customer location.

**Comment by iamricks** [comment]
@xiaoyu-tamu is correct, buybox can be awarded to multiple people, Amazon puts weight on what region your item is at, if something is closer to a customer it can take buybox in that region while another seller may take buybox in another region. You can use a VPN to verify this, just test different regions and you'll notice that you might have it in one region and not another.

**Comment by nathan-protempo** [comment]
The documentation states:

> **IsBuyBoxWinner**
> When true, the offer is currently in the Buy Box. There can be up to two Buy Box winners at any time per ASIN, one that is eligible for Prime and one that is not eligible for Prime.

Note that the documentation does not say anything about one being FBA and one being FBM, only that one is the buybox winner for Prime customers and one that is for non-Prime customers. 

However, as noted above, Amazon can display a different buybox winner based on geographic location which makes the concept of a flag that indicates "the" buybox winner very suspect.

**Comment by emilianmanolache** [comment]
We're noticing the same issue. The reported BuyBox winner is incorrect. Tried multiple delivery addresses from different geographical locations, and it's the same.
