### ISSUE TITLE
Reports API: All Orders by Order Date - Missing Item Id Column

### ISSUE THREAD

**Issue by NetRushJacob** [amzn/selling-partner-api-docs#1831]
We're working on consuming the All Orders by Order Date report and have identified that the Order Item Id column does not exist. 

Without it, the data can appear duplicated as some orders contain two Order Items for the same product (same quantity, price, all fields can be the same), with different Order Item Ids. 

Is there any way to get this column present in the report?

**Comment by ShaneOH** [comment]
@NetRushJacob Did you ever get this solved? We had to switch from using the flat file to using the XML file

**Comment by NetRushJacob** [comment]
Solved? No. 
Worked around? Yes. We process the report and add a windowed row number as a pseudo line item Id.
Summing would also be an option, but would require consuming the entire report into memory before dumping it to staging for consuming into the warehouse.

**Comment by tspicer** [comment]
This issue should not be closed. The order item ID should be included in these reports.
