### ISSUE TITLE
[BUG] URL Encoding Problem

### ISSUE THREAD

**Issue by abuzuhri** [amzn/selling-partner-api-docs#1832]
Bug in **Url with SKU and SKU include  +** 

**Describe the bug**
we try to call feesEstimate and profide SKU in the URL the function work perfect even if the SKU include space of dash , but if the SKU include (+) then we get error 

**URL we call**
/products/fees/v0/listings/SKU1 + SKU2-FBA/feesEstimate

**URL we call after full decoding**
https://sellingpartnerapi-eu.amazon.com/products/fees/v0/listings/SKU1%20+%20SKU2-FBA/feesEstimate

**Error message we get**
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/products/fees/v0/listings/SKU1%2520%2B%2520SKU2-FBA/feesEstimate
```

**Description of what happen**
We notes the URL mention in error message is not same URL requested there double encoding for SKU (SKU1 + SKU2-FBA) first encoding (SKU1%20+%20SKU2-FBA) second encoding that came in error message (SKU1%2520%2B%2520SKU2-FBA)

**Header Keys**
**x-amzn-RequestId**=a3f559f3-92fc-495a-b5d2-4bf28ab82598
**x-amz-apigw-id**=KqwocH03joEFznA=

**Comment by bpyzikvc** [comment]
@abuzuhri Unless I am misunderstanding your sku values, you cannot use this api call for more than one sku at a time. You will need to do one call for SKU1 and a second separately for SKU2-FBA.

If you have a single sku of 'SKU1 + SKU2-FBA' then I am not sure what your solution would be

**Comment by abuzuhri** [comment]
Hi @bpyzikvc 

I want have single SKU as 'SKU1 + SKU2-FBA'  amazon accept to have this SKU so i also expect API accept same SKU

**Comment by bpyzikvc** [comment]
Have you tried SKU1%20%2B%20SKU2-FBA ?

**Comment by abuzuhri** [comment]
Yes get same problem

**Comment by YueXiaolong** [comment]
@abuzuhri Did you solve it?

**Comment by abuzuhri** [comment]
> @abuzuhri Did you solve it?

Yes

**Comment by YueXiaolong** [comment]
@abuzuhri Well, can u put more info for that?
For fees estimate, the new api `getMyFeesEstimates` doing well with no url encode issue. But for other api, there is no new version to use, so I still get a url space encode problem, eg(ListingApi#listingItem)。
Thanks!

**Comment by abuzuhri** [comment]
Which programming language you are using , if it’s c# try use my library 
https://github.com/abuzuhri/Amazon-SP-API-CSharp

it’s has most of api ready to use

**Comment by YueXiaolong** [comment]
@abuzuhri I'am using Java. Anyway, Thanks a lot. I will check out your api later.

**Comment by damianelder** [comment]
seeing similar with Products API using PHP

**Comment by abuzuhri** [comment]
Problem solved on my library

**Comment by damianelder** [comment]
Uri.EscapeDataString?
