### ISSUE TITLE
Create shipments - Invalid input - Message 40fda35b-d253-4cf8-9f2f-84eb6962ee7b

### ISSUE THREAD

**Issue by dsimon79** [amzn/selling-partner-api-docs#1835]
Selling Partner API => merchant-fulfillment-api => Operation: createShipment
When using this endpoint the method is responding with the error.
The error-message isn't very meaningful, and we don't know what's wrong with the request.
What's the meaning of the message  ' 40fda35b-d253-4cf8-9f2f-84eb6962ee7b'?
How can we fix this issue?
Which data are wrong in the request body?

Hint: the original PII where replaced by test....

Request:
```JSON
    {
      "ShipmentRequestDetails": {
        "AmazonOrderId": "123-1234567-1234567",
        "ShipFromAddress": {
          "Name": "testcompany GmbH & Co. KG",
          "AddressLine1": "teststreet 1",
          "Email": "info@testcompany.com",
          "City": "testtown",
          "StateOrProvinceCode": "",
          "PostalCode": "12345",
          "CountryCode": "DE",
          "Phone": "(0 11 22) 123456"
        },
        "PackageDimensions": {
          "Unit": "centimeters",
          "Length": 18,
          "Width": 12,
          "Height": 8
        },
        "Weight": {
          "Unit": "g",
          "Value": 400
        },
        "ItemList": [
          {
            "OrderItemId": "12345678901234",
            "Quantity": 1
          }
        ],
        "ShippingServiceOptions": {
          "DeliveryExperience": "DeliveryConfirmationWithoutSignature",
          "CarrierWillPickUp": true
        }
      },
      "ShippingServiceId": "DPDDE_PTP_PRIME_DOM",
      "ShippingServiceOfferId": "agUNjy5yUMFQtPYSVSNgr7WbKOWz2BTujIOPx5PU8lu49v9gdo/rdW9QM18U0kx6d1R17ZqFuSYI3bHa8zFLGx8XrE0Tiha3tzpYBsnSNMN3DPSkyW5WbvIi3joyoj8+q5+fjOp7WdUuP4Qg+XoLeEf7UhAyg38fcIDEiTbKvNqVJjw6WEC/UOlT4Gapfmu3xpGpKW2kZQ2Pp8r5HTkiTmVECHzr1mRA5Fl/SRHgvpjo5vC2rnRHc8kMiYlmotI0EFE7k+ibtflblXOFxRoBNd6P7sl0w4erSf334BpKDkWM4cP0pf29eLYNU5OrU2eJ"
    }
 ```

Response:
```Javascript
errors: [
                {
                               code: 'InvalidInput',
                               message: ' 40fda35b-d253-4cf8-9f2f-84eb6962ee7b',
                               details: ''
                }
]
```
Headers:
'x-amzn-requestid': 'b4452408-f46e-4bed-a2fa-c57d45be1e91'
'x-amz-date: 20211216T081158Z\r\n'

**Comment by herolzwcj** [comment]
这个问题你有解决了吗？我测试这个接口的的时候有的订单可以，有的订单直接反回InvalidInput。可以加微信jsonluo一起探讨一下。

**Comment by dsimon79** [comment]
I solved the issue by myself after some research. I found the following answers to my questions.

- What's the meaning of the message ' 40fda35b-d253-4cf8-9f2f-84eb6962ee7b'?
This seams to be the UUID of an ShipmentId related to the specified Order. It can also be a list of ShipmentId's seperated by a comma.

- How can we fix this issue?
You can fix this issue by canceling the existing Shipment before creating a new one.

- Which data are wrong in the request body?
The request body itself doesn' cantain invalid data. Just the order itself was completely shipped because it still has a shipment.
