### ISSUE TITLE
MFN_ORDER_STATUS_CHANGE returns Access to requested resource is denied

### ISSUE THREAD

**Issue by danielBroadhurst** [amzn/selling-partner-api-docs#1836]
I have successfully created notifications to link to an EventBus on an Amazon Account, but when I try to create a subscription to the 'MFN_ORDER_STATUS_CHANGE' notifcationType it always returns an Unauthorized response, "Access to requested resource is denied".

If it helps here is the 'x-amzn-requestid': 'f4afc54c-29cd-4749-80be-79a294a86cb1'.

**Comment by kpconnell** [comment]
You can't create a subscription to that event with event bridge. Only SQS.

**Comment by danielBroadhurst** [comment]
> You can't create a subscription to that event with event bridge. Only SQS.

This is incorrect, I have created an SQS Destination this morning and tried to create the MFN_ORDER_STATUS_CHANGE subscription and I still recieved 'Access to requested resource is denied.'

I can create subscriptions to other notifications fine and my App has all the required permissions enabled.

**Comment by danielBroadhurst** [comment]
> > > You can't create a subscription to that event with event bridge. Only SQS.
> > 
> > 
> > This is incorrect,
> 
> Actually, it _is_ correct.

Well whenever I complete the following POST request:

url: 'https://sellingpartnerapi-eu.amazon.com/notifications/v1/subscriptions/MFN_ORDER_STATUS_CHANGE',
body: '{"payloadVersion":"1.0","destinationId":"<SQS Destination ID>"}'

+ all required headers

I get the following error:
{
  date: 'Mon, 10 Jan 2022 16:43:48 GMT',
  'content-type': 'application/json',
  'content-length': '141',
  connection: 'close',
  'x-amzn-requestid': '6dbb3c62-1e8e-4674-bf0e-131199fd6d25',
  'x-amzn-errortype': 'AccessDeniedException',
  'x-amz-apigw-id': 'LvRKvEETjoEFwlg='
}
{
  message: 'Access to requested resource is denied.',
  code: 'Unauthorized',
  details: ''
}
