### ISSUE TITLE
listCatalogItems  Required parameter IdType not found

### ISSUE THREAD

**Issue by dingzheyan** [amzn/selling-partner-api-docs#184]
When I according to https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md  request  ,it was return errors.
https://sellingpartnerapi-eu.amazon.com/catalog/v0/items?MarketplaceId=A13V1IB3VIYZZH
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Required parameter IdType not found",
      "details": ""
    }
  ]
}

**Comment by rogersv** [comment]
You need to choose one of the search modes. See

> Returns a list of items and their attributes, **based on a search query OR item identifiers** that you specify. When based on a search query, provide the Query parameter and optionally, the QueryContextId parameter. When based on item identifiers, provide a single appropriate parameter based on the identifier type, and specify the associated item value. MarketplaceId is always required.

**Comment by aspence07** [comment]
I'm dealing with this same issue.

I still get the same 'Invalid Input' error when I set the 'Query' parameter in the request.

**Comment by madhupatel-hub** [comment]
@aspence07 you need to pass one of any optional parameters,after that it will work.
Example: https://sellingpartnerapi-eu.amazon.com/catalog/v0/items?MarketplaceId=A21TJRUUN4KGV&SellerSKU=Z1-DVHW-8B5D
