### ISSUE TITLE
SP-API: Multiple tracking number for Order Fullfilment

### ISSUE THREAD

**Issue by sugatabagchi** [amzn/selling-partner-api-docs#1847]
Hi Experts,
We are using XML-based Shipment confirmation to update seller central. In this case, we are sending the tracking numbers for the shipments.
In some cases, we have multiple tracking numbers for the same orderitem id or for different tracking numbers for each orderitemID.
As Amazon's XSD for order fullfilment can hold only 1 traking number and the cardinality of the node Message is 1, how is it possible to send multiple tracking numbers for same orderItemID or for different orderItem IDs each having sepearte tracking numbers.
The XML Documentatin - https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf
says we can have multiple message nodes within the same envelope, but with different messageID values and the message type being the same for all.
can any one share a sample of working XML that worked properly/correctly. 

Please refer the below links which we have tried already-
https://stackoverflow.com/questions/52212178/add-multiple-tracking-numbers-to-an-amazon-order-using-mws-api

https://stackoverflow.com/questions/52609498/amazon-order-fulfillment-with-multiple-packages-for-one-order-post-order-fulfil

Request your kind help on this.
Thanks
Sugata

**Comment by kpconnell** [comment]
sugatabagchi - I believe this is inherent because there is no user experience to view multiple tracking numbers for the same item on the consumer side.  You can send them in two different messages.....  but I think the last one in wins and that is that.

**Comment by DevBrent** [comment]
Seeing as MWS has never supported multi-package shipments your only option is to use a carrier's "multi-piece shipping" which provides one master tracking number for the entire shipment of multiple packages. Notably, USPS does not support this.
