### ISSUE TITLE
The processingStatus of Report GET_SELLER_FEEDBACK_DATA  is always return CANCELLED

### ISSUE THREAD

**Issue by sinpobox** [amzn/selling-partner-api-docs#1849]
Hi, We need to obtain a customer feedback data from amazon, so we created the type of GET_SELLER_FEEDBACK_DATA Report ,and got the reportId. When we want to get the report with the reportId, the api always return CANCELLED of processingStatus, That why ?  and What can we do to fix this ?

**Comment by sinpobox** [comment]
the return payload like this
{"payload":{"reportType":"GET_SELLER_FEEDBACK_DATA", "processingEndTime":"2021-12-28T03:21:31+00:00", "processingStatus":"CANCELLED", "marketplaceIds":["ATVPDKIKX0DER"], "reportId":"58268018989", "dataEndTime":"2021-12-28T02:53:39+00:00", "createdTime":"2021-12-28T03:21:19+00:00", "processingStartTime":"2021-12-28T03:21:25+00:00", "dataStartTime":"2021-09-29T00:00:00+00:00"}}

**Comment by rohitdobariya** [comment]
@sinpobox  connect me here I will help you to resolve this issue https://join.skype.com/Iw3VgaE7r3me

**Comment by kpconnell** [comment]
Duplicate  #1329
