### ISSUE TITLE
No access to tax related information

### ISSUE THREAD

**Issue by fernlop** [amzn/selling-partner-api-docs#185]
I can't access any information related to taxes. 
I should have access to everything. I checked every role in the developer profile and got accepted.

**Examples:**
Get VAT ID for business orders in **/orders/v0/orders** or **/orders/v0/orders/{orderId}** API:
In the old MWS API, there was an object called **TaxRegistrationDetails** which contained the registration id and country. 
The new SP API doesn't return this object even with business orders that have a registered tax id. 

I'm not able to upload tax invoices through a feed type **UPLOAD_VAT_INVOICE**:
I can create and upload other feeds but when trying to upload the invoices i get an unauthorized error:
`{"code":"Unauthorized","message":"Access to the resource is forbidden","details":""}`

I can't get financial events through **/finances/v0/financialEventGroups** or **/finances/v0/financialEvents** API:
When i try to get financial event i receive an unauthorized error.:
`{"message":"Access to requested resource is denied.","code":"Unauthorized","details":""}`
I have access the financial events for an order with **/finances/v0/orders/{orderId}/financialEvents**, but everything else will result in an error.

It seems like this is all related to restrictions to tax related information. I double checked my access requested in the developer profile and even re-submitted the form and used a new generated refresh token. 

**Contact with MWS Support:**
I opened a case (6546747312) with MWS Support and they told me they are not responsible for "the review or appeal of Developer Registration and Assessment forms" and have forwarded this to the Developer Registration Team, but they never replied me. 

> Hello from Amazon Selling Partner Support,
> 
> We understand that you have questions about MWS PII access.
> 
> The Amazon MWS Support team is not involved in the review or appeal of Developer Registration and Assessment forms, so we are not able to assist you directly. However, we have informed the Developer Registration Team and they will contact you in the following 3 business days in order to help you with the Registration Process.
> 

Then i opened a new case (6573616692) with the Team that should be responsible for this but still got no response too. 

I want to make clear, i don't have general problems to access the SP API, just with this specific tax related endpoints!

**Comment by biancahuluban** [comment]
Hi @fernlop,

As you know, because you replied to me with valuable info, I am trying to upload invoices via the MWS Api; now I receive the 403 Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. I know that I should have access to everything...do you know any possible hint? I receive it at the CreateFeed after CreateFeedDocument and Upload File steps. :(

**Comment by alesconti** [comment]
@fernlop did you find the solution to upload invoice vi sp-api ?

**Comment by jchavest13** [comment]
Hi @fernlop,

Upon review, I could confirm that all your Developer Registration cases have been successfully resolved and all SP-API roles you have requested have been approved as well. 
Therefore, if you still need assistance on this topic, please submit a request for SP-API technical support here: 
- https://sellercentral.amazon.co.uk/gp/mws/contactus.html

Regards,
Julian,
Developer Registration Specialist

**Comment by kevinvenclovas** [comment]
@fernlop do you find the solution we need also the TaxRegistrationDetails on the new SP API.

**Comment by ZieglerReybex** [comment]
Has someone found a solution? I can not get the buyer-tax-registration-id for FBA orders. The report GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL only returns buyer-tax-registration-country and buyer-tax-registration-type and the /orders/v0/orders/{orderId} returns NULL for TaxRegistrationDetails.

**Comment by ansgarbecker** [comment]
I'm also facing this issue. Is there someone out there with any solution to that?
Could it be the report `GET_ORDER_REPORT_DATA_TAX` contains the missing `TaxRegistrationDetails` ?
