### ISSUE TITLE
Hey, I hope I can get help. I encountered a gzip decompression problem when unzipping the report document.

### ISSUE THREAD

**Issue by wdschn** [amzn/selling-partner-api-docs#186]
I am using python to do development based on the SP API. 

When I get the decompression key of the report document through [/reports/2020-09-04/documents/{reportDocumentId}](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#getreportdocument), I get the file through the returned url, and I get It is a GZIP compressed file, but an error occurred when I used gzip.decompress to decompress it.

```python
duco = get_report_ducoment() 
# duco like this
# {
#    'payload':  {
#            'reportDocumentId': 'amz.....,
#            'compressionAlgorithm': 'GZIP', 
#            'encryptionDetails': {
#                    'standard': 'AES', 
#                    'initializationVector': 'LsUf/N..., 
#                    'key': '/57WFCP....'
#             }, '
#            url': 'https://tortuga....'
#    }
#}
resp = requests.get(duco.get('payload',{}).get('url'))
gzip.decompress(resp.content) # raise error
```

err :
```python
...

  File "/Volumes/MyData/codes/amazon_back/amazonspapi/reports.py", line 57, in get_report_document_content
    resp_content = gzip.decompress(resp.content)
  File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 548, in decompress
    return f.read()
  File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\xc3c')
```

Are there any other rules I don’t know about gzip decompression?

**Comment by GenderAPI** [comment]
i Have the same problem. 
do we need to first gzip then AES decription
or first AES decription then gzip?

i try both and get same BadGzipFile Error

**Comment by GenderAPI** [comment]
i find java helper  first it does  decription then decomprassion

https://github.com/amzn/selling-partner-api-models/blob/main/clients/sellingpartner-api-documents-helper-java/src/main/java/com/amazon/spapi/documents/DownloadBundle.java



public InputStream newInputStream() throws CryptoException, IOException {
        Closeable closeThis = null;
        try {
            InputStream inputStream = new FileInputStream(document);
            closeThis = inputStream;

            inputStream = cryptoStreamFactory.newDecryptStream(inputStream);
            closeThis = inputStream;

            if (compressionAlgorithm != null) {
                switch (compressionAlgorithm) {
                    case GZIP:
                        inputStream = new GZIPInputStream(inputStream);
                        closeThis = inputStream;
                }
            }

            closeThis = null;
            return inputStream;
        } finally {
            IOUtils.closeQuietly(closeThis);
        }
    }

**Comment by wdschn** [comment]
> i find java helper first it does Decrypt then Unzip
> 
> https://github.com/amzn/selling-partner-api-models/blob/main/clients/sellingpartner-api-documents-helper-java/src/main/java/com/amazon/spapi/documents/DownloadBundle.java
> 
> ```
> public InputStream newInputStream() throws CryptoException, IOException {
>         
> Closeable closeThis = null;
>         
> try {
> 
>             InputStream inputStream = new FileInputStream(document);
>             closeThis = inputStream;
> 
>             inputStream = cryptoStreamFactory.newDecryptStream(inputStream);
>             closeThis = inputStream;
> 
>             if (compressionAlgorithm != null) {
>                 switch (compressionAlgorithm) {
>                     case GZIP:
>                         inputStream = new GZIPInputStream(inputStream);
>                         closeThis = inputStream;
>                 }
>             }
> 
>             closeThis = null;
>             return inputStream;
>         } finally {
>             IOUtils.closeQuietly(closeThis);
>         }
>     }
> ```

Similarly, I have tried ungzip first and then aes decryption, or first aes decryption and then ungzip, both of which are also BadGzipFile. Have you found a solution?

**Comment by SenQi-666** [comment]
> I am using python to do development based on the SP API.
> 
> When I get the decompression key of the report document through [/reports/2020-09-04/documents/{reportDocumentId}](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#getreportdocument), I get the file through the returned url, and I get It is a GZIP compressed file, but an error occurred when I used gzip.decompress to decompress it.
> 
> ```python
> duco = get_report_ducoment() 
> # duco like this
> # {
> #    'payload':  {
> #            'reportDocumentId': 'amz.....,
> #            'compressionAlgorithm': 'GZIP', 
> #            'encryptionDetails': {
> #                    'standard': 'AES', 
> #                    'initializationVector': 'LsUf/N..., 
> #                    'key': '/57WFCP....'
> #             }, '
> #            url': 'https://tortuga....'
> #    }
> #}
> resp = requests.get(duco.get('payload',{}).get('url'))
> gzip.decompress(resp.content) # raise error
> ```
> 
> err :
> 
> ```python
> ...
> 
>   File "/Volumes/MyData/codes/amazon_back/amazonspapi/reports.py", line 57, in get_report_document_content
>     resp_content = gzip.decompress(resp.content)
>   File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 548, in decompress
>     return f.read()
>   File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 292, in read
>     return self._buffer.read(size)
>   File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 479, in read
>     if not self._read_gzip_header():
>   File "/opt/miniconda3/envs/py3amazon/lib/python3.8/gzip.py", line 427, in _read_gzip_header
>     raise BadGzipFile('Not a gzipped file (%r)' % magic)
> gzip.BadGzipFile: Not a gzipped file (b'\xc3c')
> ```
> 
> Are there any other rules I don’t know about gzip decompression?

Hi.Have you solved this problem and what should be done here.

**Comment by GenderAPI** [comment]
i still get same error
and no solutions still

**Comment by SenQi-666** [comment]
> i still get same error
> and no solutions still

I have solved this problem. When I request report api to download the report, I don’t need to unzip it. Is it must to decompress when requesting the feed api? I don't know.

**Comment by GenderAPI** [comment]
do you have 
'compressionAlgorithm': 'GZIP' variable on your payload response?

and guys do you get character problem when AES Decryption with UTF-8;
i get the first line is unsuppoerted characters so i use so i use "ISO-8859-1" 

def decrypt(key, iv, enc):
    unpad = lambda s: s[:-ord(s[len(s) - 1:])]
    enc = requests.get(enc).content
    iv = base64.b64decode(iv)
    key = base64.b64decode(key)
    cipher = AES.new(key, AES.MODE_CBC, iv)
    result = unpad(cipher.decrypt(enc[AES.block_size:]))

    result = result.decode("ISO-8859-1")


the first line may the problem when unzipped file

**Comment by SenQi-666** [comment]
> do you have
> 'compressionAlgorithm': 'GZIP' variable on your payload response?
> 
> and guys do you get character problem when AES Decryption with UTF-8;
> i get the first line is unsuppoerted characters so i use so i use "ISO-8859-1"
> 
> ```
> def decrypt(key, iv, enc):
>     unpad = lambda s: s[:-ord(s[len(s) - 1:])]
>     enc = requests.get(enc).content
>     iv = base64.b64decode(iv)
>     key = base64.b64decode(key)
>     cipher = AES.new(key, AES.MODE_CBC, iv)
>     result = unpad(cipher.decrypt(enc[AES.block_size:]))
>     result = result.decode("ISO-8859-1")
> ```
> 
> the first line may the problem when unzipped file

The'compressionAlgorithm':'GZIP' variable is on my payload response. I did not get the character problem when decrypting with AES, but if the report is an xml file, there are some space characters at the end that need to be deleted, otherwise it will cause the xml display to fail. No matter whether there is'GZIP' or not, there is no need to decompress, I did not decompress but the request succeeded.

**Comment by wdschn** [comment]
I solved this problem, and I hardly encountered any unexpected problems after testing. I found that Cp1252 encoding was used in some reports. The code looks like this

```python


def ase_cbc_decryptor(key, iv, encryption):
    cipher = Cipher(algorithms.AES(base64.b64decode(key)), modes.CBC(base64.b64decode(iv)))
    decryptor = cipher.decryptor()
    decrypted_text = decryptor.update(encryption)
    unpadder = padding.PKCS7(algorithms.AES.block_size).unpadder()
    unpaded_text = unpadder.update(decrypted_text)
    return unpaded_text + unpadder.finalize()

def get_report_document_content(self, key, iv, url, compression_type=None):
    resp = requests.get(url=url)
    resp_content = resp.content

    decrypted_content = ase_cbc_decryptor(key=key, iv=iv, encryption=resp_content)

    if compression_type == 'GZIP':
       decrypted_content = gzip.decompress(decrypted_content)

      code = 'utf-8'
      if 'cp1252' in resp.headers.get('Content-Type', '').lower():
          code = 'Cp1252'
      return decrypted_content.decode(code)
```

**Comment by GenderAPI** [comment]
so what it returns **if compression_type !== 'GZIP':**

`import gzip
import requests

from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

def ase_cbc_decryptor(key, iv, encryption):
    cipher = Cipher(algorithms.AES(base64.b64decode(key)), modes.CBC(base64.b64decode(iv)))
    decryptor = cipher.decryptor()
    decrypted_text = decryptor.update(encryption)
    unpadder = padding.PKCS7(algorithms.AES.block_size).unpadder()
    unpaded_text = unpadder.update(decrypted_text)
    return unpaded_text + unpadder.finalize()

def get_report_document_content(self, key, iv, url, compression_type=None):
    resp = requests.get(url=url)
    resp_content = resp.content

    decrypted_content = ase_cbc_decryptor(key=key, iv=iv, encryption=resp_content)

    if compression_type == 'GZIP':
       decrypted_content = gzip.decompress(decrypted_content)

    code = 'utf-8'
    if 'cp1252' in resp.headers.get('Content-Type', '').lower():
        code = 'Cp1252'
    return decrypted_content.decode(code)`

**Comment by wdschn** [comment]
> so what it returns **if compression_type !== 'GZIP':**
> 
> ```
> import gzip
> import requests
> 
> from cryptography.hazmat.primitives import padding
> from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
> 
> def ase_cbc_decryptor(key, iv, encryption):
>     cipher = Cipher(algorithms.AES(base64.b64decode(key)), modes.CBC(base64.b64decode(iv)))
>     decryptor = cipher.decryptor()
>     decrypted_text = decryptor.update(encryption)
>     unpadder = padding.PKCS7(algorithms.AES.block_size).unpadder()
>     unpaded_text = unpadder.update(decrypted_text)
>     return unpaded_text + unpadder.finalize()
> 
> def get_report_document_content(self, key, iv, url, compression_type=None):
>     resp = requests.get(url=url)
>     resp_content = resp.content
> 
>     decrypted_content = ase_cbc_decryptor(key=key, iv=iv, encryption=resp_content)
> 
>     if compression_type == 'GZIP':
>        decrypted_content = gzip.decompress(decrypted_content)
> 
>     code = 'utf-8'
>     if 'cp1252' in resp.headers.get('Content-Type', '').lower():
>         code = 'Cp1252'
>     return decrypted_content.decode(code)
> ```

It is stated in the document that currently only GZIP is supported, if there is no compression, there is no compression_type field.

**Comment by GenderAPI** [comment]
below code is writen for amacom.co.jp


```
def get_report_document_content(key, iv, url, compression_type=None):
    resp = requests.get(url=url)
    resp_content = resp.content

    decrypted_content = ase_cbc_decryptor(key=key, iv=iv, encryption=resp_content)
    if compression_type == 'GZIP':
        decrypted_content = gzip.decompress(decrypted_content)

    code = 'utf-8'
    if 'cp1252' in resp.headers.get('Content-Type', '').lower():
        code = 'Cp1252'

    if 'windows-31j' in resp.headers.get('Content-Type', '').lower():
        code = 'Shift_JIS'
    return decrypted_content.decode(code)
```
