### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by franciscocha** [amzn/selling-partner-api-docs#1862]
I am unable to use the provided code to execute without an error.  SellersApi does not have a Builder() and I am unable to follow your example in your documentation. Please update the documentation or the code so that we can follow your examples.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-an-instance-of-the-sellers-api-and-call-an-operation

```
SellersApi sellersApi = new SellersApi.Builder()
  .awsAuthenticationCredentials(awsAuthenticationCredentials)
  .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
  .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
  .endpoint("https://sellingpartnerapi-na.amazon.com")
  .build();
```

**Comment by ayoubAnbara** [comment]
I have the same problem. What's is the solution? , Why did you close the issue?

**Comment by franciscocha** [comment]
So the documentation had some confusing steps.
The original step didn't inject the aa jar. Which was found here https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-client-library
java -jar C:\SwaggerToCL\swagger-codegen-cli.jar generate -i C:\SwaggerToCL\Sellers.json -l java -o C:\SwaggerToCL\Sellers_JavaCL

The one you want is this. https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication
java -jar C:\SwaggerToCL\swagger-codegen-cli.jar generate -i C:\SwaggerToCL\Sellers.json -l java -t [path to selling-partner-api-models\clients\sellingpartner-api-aa-java folder]\resources\swagger-codegen\templates\ -o C:\SwaggerToCL\Sellers_JavaCL
