### ISSUE TITLE
[BUG] Unable to create new subscription - No destination with id .... for applicationId ....

### ISSUE THREAD

**Issue by shahviren1985** [amzn/selling-partner-api-docs#1868]
We are able to create new destination for one region per application. This is the API response which we are getting for getDestinations:
{
    "payload": {
        "resource": {
            "sqs": {
                "arn": "<our SQS ARN>"
            },
            "eventBridge": null
        },
        "destinationId": "7172dc64-1677-4053-9244-7bd747139d9d",
        "name": "resourceSpecification"
    }
}

However when we pass this destination id to create new subscription, we are getting error -
No destination with id 7172dc64-1677-4053-9244-7bd747139d9d for applicationId amzn1.sp.solution.<GUID>

This is happening for Far East region. us-west-2

Request id - 1a3dff3f-6da3-4839-bc92-0e92ba43f482
Date timestamp - Sun, 02 Jan 2022 14:30:12 GMT

Same error with the UAE region. We do have destination id but unable to create subscription.

Our Amazon Support Ticket # - 7561696642

**Comment by ezeginsberg** [comment]
Your payload looks quite strange. It must contain a valid SQS object (with a non-empty 'arn' string) OR a valid EventBridge object (with a non-empty 'name', 'region' and 'accountId' strings). In your example the previous condition is false.

**Comment by Aneverland** [comment]
I also encountered this problem, do you know how to solve it?

**Comment by iamricks** [comment]
The create destination payload should look more like:

```
{
  resourceSpecification: { 
    sqs: { 
      arn: "[Your arn]"
    } 
  }, 
  name: "[Some Name]"
}
```
