### ISSUE TITLE
Which API I can use to just to get list of Product Types

### ISSUE THREAD

**Issue by DhananjayETP** [amzn/selling-partner-api-docs#1869]
Hi,
can you please help to advise which API I can use for getting only of the list of Product Types of Amazon without any other details.  I have gone through Product  Type Definition API ([https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-type-definitions-api/definitionsProductTypes_2020-09-01.md#producttypedefinition]   but it gives attributes of product types also.  What I need for my application just to show list of Product types and then for selected product type by the user then get product type definition of this selected type.

**Comment by chapmanjw** [comment]
Use the search operation with no keywords: https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-type-definitions-api/definitionsProductTypes_2020-09-01.md#searchdefinitionsproducttypes. That will give you the full list of available product types for the given marketplace with the Product Type Definitions APIs.
