### ISSUE TITLE
Shipping API - All requests run into an InternalFailure / SignatureException and non-wellformed JSON-return

### ISSUE THREAD

**Issue by JacksonJeans** [amzn/selling-partner-api-docs#187]
Hello dear community,

I probably have the privilege to fix this bug. 
All requests to the "`/shipping/v1/`" -endpoint run into an error, except getTrackingInformation. It's absolutely not clear to me why, since all other requests are working fine and I did not change the domain logic of my client for calls to the "`/shipping/v1/`" -endpoint.

### Operation getRates:
**canonical request:**
```
POST
/shipping/v1/rates

content-type:application/json;charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:xxx(Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201207T152229Z

content-type;host;user-agent;x-amz-date
f71a7df46cad8bb9108125636cdf20081f519473333983687e1d1278ffec434f
```
**http body:**
```json
{"shipTo":{"name":"JacksonJeans","addressLine1":"xxxxxxx","addressLine2":null,"addressLine3":null,"stateOrRegion":"NRW","city":"Krefeld","countryCode":"DE","postalCode":"47799","email":"xxxxxxx","copyEmails":null,"phoneNumber":null},"shipFrom":{"name":"xxxxInternational GmbH","addressLine1":"Gahlingspfad 53","addressLine2":null,"addressLine3":null,"stateOrRegion":"NRW","city":"Krefeld","countryCode":"DE","postalCode":"47804","email":"xxxxxxx","copyEmails":null,"phoneNumber":null},"serviceTypes":{"0":"Amazon Shipping Standard"},"shipDate":"2020-12-07T15:22:28+00:00","containerSpecifications":{"0":{"dimensions":{"length":60,"width":60,"height":30,"unit":"CM"},"weight":{"unit":"kg","value":2}}}}
```
**error:**
```
object(xxxx\Amazon\ErrorList)#42 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    [0]=>
    object(xxxx\Amazon\Error)#36 (3) {
      ["code"]=>
      string(12) "InvalidInput"
      ["message"]=>
      string(14) "Invalid input."
      ["details"]=>
      string(0) ""
    }
  }
}
```

### Operation getAccount:
**canonical request:**
```
GET
/shipping/v1/account/

content-type:application/json;charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:xxxx(Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201207T154345Z

content-type;host;user-agent;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**http body**
`null`

**error:**
```json
{ "errors": [ { "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'GET /shipping/v1/account content-type:application/json;charset=UTF-8 host:sellingpartnerapi-eu.amazon.com user-agent:xxxx(Language=PHP/7.1; Platform=Windows/10) x-amz-date:20201207T154345Z content-type;host;user-agent;x-amz-date e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' The String-to-Sign should have been 'AWS4-HMAC-SHA256 20201207T154345Z 20201207/eu-west-1/execute-api/aws4_request f20d5dd0d0b1b0e7b4a0e2edcffce221d48221b65334d355dc1ba55a851dd025' ", "code": "InvalidSignature" } ] }
```

_**btw:**_
With most InvalidSignature exceptions you send me a newline character "**\n**" with the middle of the JSON code, which makes the JSON format invalid. I have problems parsing InvalidSignatureExceptions every time - that's a bit annoying.

**RAW**:
`{ \n "errors": [ { "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'GET /shipping/v1/account content-type:application/json;charset=UTF-8 host:sellingpartnerapi-eu.amazon.com user-agent:xxxx(Language=PHP/7.1; Platform=Windows/10) x-amz-date:20201207T154345Z content-type;host;user-agent;x-amz-date e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' The String-to-Sign should have been 'AWS4-HMAC-SHA256 20201207T154345Z 20201207/eu-west-1/execute-api/aws4_request f20d5dd0d0b1b0e7b4a0e2edcffce221d48221b65334d355dc1ba55a851dd025' ", "code": "InvalidSignature" } ] }`

### Operation createShipment

**canonical request:**
```
POST
/shipping/v1/shipments

content-type:application/json;charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:xxxxx(Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201207T155201Z

content-type;host;user-agent;x-amz-date
8c0ecebfd51d109dbd54d077496d74b5ff37cb80edb781d536f453ac502c9077
```

**http body:**
```json
{"clientReferenceId":"ReferenzDesClientsMAX40Zeichen","shipTo":{"name":"JackonsJeans","addressLine1":"xxxxxx","addressLine2":"optional","addressLine3":"optional","stateOrRegion":"NRW","city":"Krefeld","countryCode":"DE","postalCode":"47799","email":"xxxxxx@xxxx.de","copyEmails":["xxx@xxxx.de"],"phoneNumber":"xxxxxx"},"shipFrom":{"name":"xxxxInternational GmbH ","addressLine1":"Gahlingspfad 53","addressLine2":"optional","addressLine3":"optional","stateOrRegion":"NRW","city":"Krefeld","countryCode":"DE","postalCode":"47804","email":"xxx@xxxxxx.de","copyEmails":["xxx@xxxxxx.de"],"phoneNumber":"xxxxx"},"containers":{"0":{"containerType":"PACKAGE","containerReferenceId":"ReferenzZumPaket","value":{"value":1125.1799999999998,"unit":"EUR"},"dimensions":{"length":100,"width":100,"height":50,"unit":"CM"},"items":[{"quantity":72,"unitPrice":{"value":12.99,"unit":"EUR"},"unitWeight":{"unit":"kg","value":0.1},"title":"FLEXFIT Cap"},{"quantity":10,"unitPrice":{"value":18.99,"unit":"EUR"},"unitWeight":{"unit":"kg","value":0.1},"title":"GILDAN Sweatshirt"}],"weight":{"unit":"kg","value":8.2}}}}
```

**error:**
```
object(xxxx\Amazon\ErrorList)#48 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    [0]=>
    object(xxxx\Amazon\Error)#42 (3) {
      ["code"]=>
      string(12) "InvalidInput"
      ["message"]=>
      string(14) "Invalid input."
      ["details"]=>
      string(0) ""
    }
  }
}
```

Has anyone managed to work with this API yet? 

Since the listed operations did not work already, I have not tried the others (purchaseLabel, purchaseShipment and getShipment and cancelShipment).

**Comment by rogersv** [comment]
@JacksonJeans both `containerSpecifications` and `containers` should be arrays according to the docs. In your example you have `"containers":{"0":`. Try to use `"containers": [ {"containerType":"PACKAGE"...} ]` instead.

**Comment by JacksonJeans** [comment]
Thank u @rogersv !,

There was a little mistake on my part 😄.
For whatever reason my objects have done this. But I have now fixed the error. 

To be on the safe side, I only work with the example parameter values from the model documentation.
Now I only work with the example parameter values from the model documentation, because I still get an error with my values. With the example values as well.

### getRates -operation

**http body:**
```json
{"shipTo":{"name":"test name 2","addressLine1":"some Test address 2","addressLine2":null,"addressLine3":null,"stateOrRegion":"CA","city":"Los Angeles","countryCode":"US","postalCode":"90013","email":null,"copyEmails":null,"phoneNumber":null},"shipFrom":{"name":"test name 1","addressLine1":"some Test address 1","addressLine2":null,"addressLine3":null,"stateOrRegion":"CA","city":"Los Angeles","countryCode":"US","postalCode":"90013","email":null,"copyEmails":null,"phoneNumber":null},"serviceTypes":["Amazon Shipping Standard"],"shipDate":null,"containerSpecifications":[{"dimensions":{"length":36,"width":15,"height":12,"unit":"CM"},"weight":{"unit":"lb","value":0.08164656}}]}
```

**error:**
```
object(xxxxx\Amazon\ErrorList)#40 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    [0]=>
    object(xxxxx\Amazon\Error)#34 (3) {
      ["code"]=>
      string(15) "InternalFailure"
      ["message"]=>
      string(51) "We encountered an internal error. Please try again."
      ["details"]=>
      string(0) ""
    }
  }
}
```

Whatever the reason. Same game with the createShipment operation:
### createShipment-operation
**http body:**
```json
{"clientReferenceId":"911-7267646-6348616","shipTo":{"name":"test name 2","addressLine1":"some Test address 2","addressLine2":null,"addressLine3":null,"stateOrRegion":"CA","city":"Los Angeles","countryCode":"US","postalCode":"90013","email":"testEmail2@amazon.com","copyEmails":null,"phoneNumber":"1234567890"},"shipFrom":{"name":"test name 1","addressLine1":"some Test address 1","addressLine2":null,"addressLine3":null,"stateOrRegion":"CA","city":"Los Angeles","countryCode":"US","postalCode":"90013","email":"testEmail1@amazon.com","copyEmails":null,"phoneNumber":"1234567890"},"containers":[{"containerType":"PACKAGE","containerReferenceId":"ContainerRefId-01","value":{"value":29.98,"unit":"USD"},"dimensions":{"length":36,"width":15,"height":12,"unit":"CM"},"items":[{"quantity":2,"unitPrice":{"value":14.99,"unit":"USD"},"unitWeight":{"unit":"lb","value":0.08164656},"title":"String"}],"weight":{"unit":"lb","value":0.08164656}}]} 
```
**btw...**
Amazons uses this logic here after the example values: If piece weight = 0.5KG, and we have 2 items of it in a package, then logically the weight of the package is also 0.5KG. Look at items `quantity`, `unitWeight` and compare this with the `weight` from `containers`.. 😃  [Link to documentation](https://github.com/amzn/selling-partner-api-models/blob/main/models/shipping-api-model/shipping.json)

Of course this is wrong. Correct would be 1.0KG. I took this from their example: `weight: 0.08164656` and `unitWeight: 0.08164656`

**error:**
```
object(GIDUTEX\Amazon\ErrorList)#44 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    [0]=>
    object(GIDUTEX\Amazon\Error)#38 (3) {
      ["code"]=>
      string(15) "InternalFailure"
      ["message"]=>
      string(51) "We encountered an internal error. Please try again."
      ["details"]=>
      string(0) ""
    }
  }
}
```

Why my signature would not be valid or wrongly calculated using the getAccount() operation is absolutely not obvious to me. Rarely had problems with the signature.

**Comment by JacksonJeans** [comment]
I got the error solved myself.

### getAccount operation
The canonical requirement for getAccount should be like this:
```
GET
/shipping/v1/account

content-type:application/json;charset=UTF-8
host:sellingpartnerapi-eu.amazon.com
user-agent:xxxxx(Language=PHP/7.1; Platform=Windows/10)
x-amz-date:20201210T142927Z

content-type;host;user-agent;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
without "/" at the end of the `CanonicalURI`.

For the other operations, you will probably only get an answer **if the account is valid.**
In the description of the model file for the "Shipping API" says the following:
"Encountered an unexpected condition which prevented the server from fulfilling the request."[...]

I suspect a non-valid account is exactly the reason for an unexpected condition error like this.
Unfortunately, I don't have another account to test this on.

**Comment by Jaimin-Devhero** [comment]
Hello

I am using the amazon shipping api v2 - get rates api 

error: 
[2022-08-24 14:53:52]: {
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}

my request:

{"shipTo":{"name":"Jane Doe","addressLine1":"Vreugdenhillaan","addressLine2":"50","addressLine3":"test","city":"Utrecht","countryCode":"nl","postalCode":"3526 ZA"},"shipFrom":{"name":"A1","addressLine1":"4 Neal Street","city":"London","countryCode":"GB","postalCode":"WC2H 9QL"},"shipDate":"2022-08-26T12:00:00Z","packages":[{"dimensions":{"length":100,"width":200,"height":300,"unit":"CENTIMETER"},"weight":{"unit":"OUNCE","value":10},"insuredValue":{"value":10,"unit":"GBP"},"packageClientReferenceId":"Jy6cUhHRLEqVYUTz8eD0nlgl","items":[{"quantity":1,"weight":{"unit":"OUNCE","value":10}}]}],"channelDetails":{"channelType":"EXTERNAL"}}

Can someone guide me is there anything wrong ?

**Comment by ck-subir** [comment]
Hello, 
I am facing the same issue. Can someone help me to solve this ?
