### ISSUE TITLE
Create shipments - Invalid input

### ISSUE THREAD

**Issue by herolzwcj** [amzn/selling-partner-api-docs#1875]
I am trying to make a call to Merchanfullfillment - create shipment (POST /mfn/v0/shipments ), but it returns the error

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}

{"ShipmentRequestDetails":{"AmazonOrderId":"111-4570444-244XX21","ItemList":[{"OrderItemId":"630915XXX6922","Quantity":1}],"ShipFromAddress":{"Name":"WUO HOUSEWARE","AddressLine1":"2XXX Belleza Lane","Email":"test@test.com","City":"XXX","StateOrProvinceCode":"NV","PostalCode":"89074","CountryCode":"US","Phone":"+1 763-225-XXX ext. XXX"},"PackageDimensions":{"Unit":"inches","Length":5.0,"Width":5.0,"Height":5.0},"Weight":{"Unit":"oz","Value":2.0},"ShippingServiceOptions":{"DeliveryExperience":"DeliveryConfirmationWithoutSignature","CarrierWillPickUp":false}},"ShippingServiceId":"USPS_PTP_FC"}

**Comment by herolzwcj** [comment]
ID9445207211

**Comment by Shoprunners** [comment]
Same here, case ID: 9445693511
