### ISSUE TITLE
[BUG] OriginalTotal of listFinancialEventGroups API is empty

### ISSUE THREAD

**Issue by WXinFfly** [amzn/selling-partner-api-docs#1878]
Hi. I use the listFinancialEventGroups API of Finances-api to obtain ProcessingStatus which is Closed but OriginalTotal is empty. Actually, OriginalTotal has data in the backend of the store. How can I solve this problem? Now this problem affects my business

API：
![lQLPDhsHeMcZt-PM480CabALxKdkDOiEoQHc6js9gL4A_617_227](https://user-images.githubusercontent.com/25562509/148317864-797ea90c-58c0-452e-ae56-13fe75d18d59.png)

Shop backstage：
![image](https://user-images.githubusercontent.com/25562509/148317817-4b969091-d2ac-46a3-a32f-78353b58a779.png)

**Comment by liyouzhuo** [comment]
I ran into the same problem

**Comment by WXinFfly** [comment]
@seanevan

**Comment by WXinFfly** [comment]
@rickdeee

**Comment by WXinFfly** [comment]
@evdeg

**Comment by skuio** [comment]
Experiencing the same

**Comment by liyouzhuo** [comment]
> Experiencing the same

bro, is there any solution?

**Comment by ElyeM** [comment]
Same issue here, any solution or workaround?

**Comment by liyouzhuo** [comment]
@salric

**Comment by liyouzhuo** [comment]
@mentiaa

**Comment by liyouzhuo** [comment]
@jevoniuk
@jenilew
@#6DKasto

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

The issue has been reported to our respective engineering team and is currently being investigated. Once the root cause is identified, I will get back to you with further details and next steps to resolve the same. If you have raised a support case with us, please continue monitoring the case for further updates.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by WXinFfly** [comment]
> Hello,
> 
> Thank you for raising this issue.
> 
> The issue has been reported to our respective engineering team and is currently being investigated. Once the root cause is identified, I will get back to you with further details and next steps to resolve the same. If you have raised a support case with us, please continue monitoring the case for further updates.
> 
> Thanks, Shivika Khare Selling Partner API Developer Support

Hi ShivikaK

Thank you for your reply, when is this question expected to be answered?

**Comment by parvathm** [comment]
Hi,

Sorry for the delay in response. This issue is fixed. If you are still facing same issue please open a support case.

Thanks,
Parvathm
SP API Developer API Support.

**Comment by grmiatov** [comment]
Hi @parvathm,  we notice again high  rates of empty Original Totals in the EU region

**Comment by always404** [comment]
Hi @parvathm ,

Starting from Friday, the same problem appeared again, ProcessingStatus which is Closed but OriginalTotal is empty. The appearance rate is almost 100%, North America and EUROPE all appears this problem. Please repair as soon as possible. Response as follows:
![image](https://github.com/amzn/selling-partner-api-docs/assets/62318419/b66a38f8-2fed-4b28-accf-a15d250a5c90)

Thanks,
Dev.

**Comment by kobeleehom** [comment]
Same issue here, any solution or workaround?
