### ISSUE TITLE
How to get shipping templates list?

### ISSUE THREAD

**Issue by yizeku** [amzn/selling-partner-api-docs#1879]
![image](https://user-images.githubusercontent.com/33300443/148341953-ed6eb14e-8a78-4760-b040-6470696a422f.png)

**/definitions/2020-09-01/productTypes/PRODUCT** 

I tried to get it with this API, but found that it did not contain _merchant_ shipping_ group_.

How else can I get shipping templates?

**Comment by chapmanjw** [comment]
@yizeku There is currently no API that provides shipping templates directly. The Product Type Definitions API will populate them when a `sellerId` is provided and the product type has the `merchant_shipping_group` attribute. The `PRODUCT` product type does not have the `merchant_shipping_group` attribute defined. However, product types like `LUGGAGE` do. 

This is certainly not an ideal way to get this information. We are exploring how information like this can/should be made available in an API in the future (such as a "listings context" API or something like that to provide seller-specific information used when creating listings).

**Comment by yizeku** [comment]
@chapmanjw Thanks for your help, now I can get shipping templates by other product types.

**Comment by silasfrigo** [comment]
Hi @yizeku, can you paste here an exemple of how you are getting the shipping templates(the request)? I tried this method but the return does not contain the merchang_shipping_groups. Thanks!
