### ISSUE TITLE
Something went wrong This Developer is not currently eligible for new authorizations.MD9000

### ISSUE THREAD

**Issue by xiaoxi9011** [amzn/selling-partner-api-docs#1880]
I am getting the error MD9000 (without &version=beta). I can successed (with &version=beta). I have already submitted the app. The status of my app is "Submitted". Can you please help me?
The APP ID is amzn1.sp.solution.c8ef9a0a-4f9b-4425-ae5b-ef1d47ed9ae0.

**Comment by xbaha** [comment]
I think the app should be in Published status to remove the beta param

**Comment by xiaoxi9011** [comment]
I've removed it.But,it still reports an error.

Something went wrong
This Developer is not currently eligible for new authorizations.

App ID: amzn1.sp.solution.c8ef9a0a-4f9b-4425-ae5b-ef1d47ed9ae0

Error Code: MD9000
