### ISSUE TITLE
[BUG] Merging multiple inbound shipments going to same destination

### ISSUE THREAD

**Issue by midi-red** [amzn/selling-partner-api-docs#1881]
I was reading through the Amazon MWS documentation http://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_CreateShipment200Items.html and realized that it was allowing merging multiple shipment batches into single one where it is applicable which could reduce shipping and processing overheads. It states that we could utilize `UpdateInboundShipment` api to merge multiple shipment batches. On the other had, the new SP-API does not allow adding items as stated here https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#updateinboundshipment , which prevents merging applicable shipments. Could someone elaborate what is the reason behind this change? Is there a way to merge multiple shipment batches in the new SP-API?

**Comment by ehrowe** [comment]
We also need to support this use case in order to have functional parity with what we do in MWS. If the merge shipment use case is not going to be supported, we need to know this ASAP.

**Comment by Jonny14231** [comment]
I'd also like to know!

**Comment by 8mpg** [comment]
We would really like this feature to be added back to SP-API.

**Comment by 8mpg** [comment]
no updates? Not only do I think this really helps sellers but this will help Amazon consolidate shipments for less frequent deliveries and starting over each shipment their staff has to check in. Its a big labor saver for Amazon

**Comment by truonggiang347** [comment]
It appears that the Send to Amazon workflow does allow merging shipments without even replacing existing 2D Barcode for previous shipment. Can we merge using Send to Amazon for shipment that was created by SP API?

**Comment by cmlkx** [comment]
Hello, we would also like to know if there have been any updates on the ability to merge ShipmentPlans headed to the same FC. @sungolivia @chapmanjw

**Comment by GJ-JG** [comment]
Hi all, the current SP-API doesn't support merge shipment plans.
As you might know, we announced [Shipments that have been created, viewed, or edited using Send to Amazon cannot be viewed or edited via API](https://developer-docs.amazon.com/sp-api/changelog/send-to-amazon-will-replace-the-sendreplenish-workflow-for-api-created-shipments).
When SP-API and Send To Amazon have 100% compatibility and if SP-API can support merging shipment plans, we will announce it in our platform, but the ETA is not decided yet.

**Comment by hellokids86** [comment]
Ok we are eagerly waiting on this.

**Comment by teddy-codes** [comment]
I've been checking in periodically over the past few months regarding the ability to merge shipments via the API. Unfortunately, I haven't seen any updates...

Not having this feature is causing inefficiencies and additional costs for the sellers that we support. Merging two small parcel shipments that are destined for the same location into one LTL shipment would be far more cost-effective and efficient.

Could you please provide an update on when this feature might be available?

**Comment by teddy-codes** [comment]
I've been checking in periodically over the past few months regarding the ability to merge shipments via the API. Unfortunately, I haven't seen any updates...

Not having this feature is causing inefficiencies and additional costs for the sellers that we support. Merging two small parcel shipments that are destined for the same location into one LTL shipment would be far more cost-effective and efficient.

@GJ-JG Could you please provide an update on when this feature might be available?
