### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by Abdo99ab** [amzn/selling-partner-api-docs#1882]
We have an unsolved issue that's going about a month ago, with SP API services, we have registered to developer account successfully, followed the steps in SP API Documentation properly here: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

And created our app to access Vendor data, however we are facing a problem in connecting to the service, the authentication works fine and we get the access token using refresh token, however when we use the access token in the endpoint it always give: Access to requested resource is denied

We have tried some of the suggestions here in the issues but nothing worked. Our IAM user and role are properly created as instructed in the documentation

You'll find in the attached everything concerning requests and their response
[requests.zip](https://github.com/amzn/selling-partner-api-docs/files/7823673/requests.zip)
The request ID: cfdc97af-c9ed-48e6-b297-b9dde653a3ec
The timestamp: Thu, 06 Jan 2022 14:00:07 GMT
The reply time: 613ms
The error type: AccessDeniedException

We'd like to solve this issue in the nearly possible time

**Comment by AlexioDanje** [comment]
I am having the same issue, **Invalid Signature**.  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
The Canonical String for this request should have been
'POST
/shipping/v1/shipments

**Comment by coder771** [comment]
@Abdo99ab @AlexioDanje did you find the reason for this issue?

**Comment by Abdo99ab** [comment]
@coder771 For my case I did solve it.
I had a problem because I was using the access key and secret key from AWS directly when I first created the user.
I solved that by using the sts policy and from there I get AccessKey, SecretKey and SessionToken and use all these three to make the signature of Amazon.

**Comment by coder771** [comment]
@Abdo99ab thanks for getting back. Do we need to check below marketplaces in developer profile  and get approval from Amazon to make these calls work, or do they work without any approval
![image](https://user-images.githubusercontent.com/17831597/154063861-1779fe82-27b5-4cc0-a75b-deb4285f01a4.png)

**Comment by Abdo99ab** [comment]
@coder771 in my case, we didn't have a list of marketplaces listed in use cases and we didn't even select the direct to consumer delivery because we don't need it, I used this api for vendor, so if you're in seller I don't think I can help you.

**Comment by coder771** [comment]
@Abdo99ab no worries
