### ISSUE TITLE
Is there any API related to automatic pricing?

### ISSUE THREAD

**Issue by christopy-dev** [amzn/selling-partner-api-docs#189]
Hello, is there any API related to automatic pricing?

**Comment by fengmiq** [comment]
@nickname-sb how to use messaging-api?can you share method

**Comment by fengmiq** [comment]
> Hello, is there any API related to automatic pricing?

feeds-api

**Comment by nickname-sb** [comment]
> @ nickname-sb如何使用messaging-api？可以共享方法吗？

Your request marketplaceIds parameter can only contain one value.
![image](https://user-images.githubusercontent.com/36065190/102181133-ff341100-3ee4-11eb-96c0-60b3f7ec0c76.png)

**Comment by nickname-sb** [comment]
> @nickname-sb how to use messaging-api?can you share method

Your request marketplaceIds parameter can only contain one value.

![image](https://user-images.githubusercontent.com/36065190/102181520-b03aab80-3ee5-11eb-9aca-da27318ec9b2.png)

**Comment by fengmiq** [comment]
@nickname-sb I want to send confirmCustomizationDetails message,but cant't work, return error:Invalid amazonOrderId and template combination.

**Comment by nickname-sb** [comment]
> @nickname-sb I want to send confirmCustomizationDetails message,but cant't work, return error:Invalid amazonOrderId and template combination.

Sorry, I only called the getMessagingActionsForOrder method, because it did not return a specific buyer message, I cannot proceed with the next step, so there is no way to help you.

**Comment by fengmiq** [comment]
@nickname-sb thank you
