### ISSUE TITLE
GET_V2_SELLER_PERFORMANCE_REPORT doesn't contain data from the requested time period

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#1895]
When I request the `GET_V2_SELLER_PERFORMANCE_REPORT` report for the last 7, 30, or 60 days, or a time period from 120 days ago to 90 days ago, I get the same data no matter what. The particular piece of data that I'm interested in (the order defect data) always specifies the same 60-day date range in the `reportingDateRange` field: `2021-10-29T00:00:00Z` to `2021-12-27T23:59:59Z`.

This makes the report nearly useless, because I can't predict what time period I'm going to get data from when I request the report. I also need to aggregate data from the past year, but I can't do that either, because I'm getting data for a static time period regardless of the `data_start_time` and `data_end_time` I specify. It's possible to specify a custom date range when retrieving this data via Seller Central, so I would expect the same to be true here.

Is there any way to actually get data from a custom date range for this report?

I've also opened a Seller Central case related to this issue (case #9470018101).

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
