### ISSUE TITLE
Which Method support to get Customer Message Info

### ISSUE THREAD

**Issue by GL128** [amzn/selling-partner-api-docs#1898]
Hi all, we want to get and reply customer message info by API. But we can't find the method.

Many Thanks

**Comment by Mike-the-one** [comment]
I'm looking for the same... I see there are apis for retrieve messages by order, but I don't see a way to reply buyer message via api.

Ideally this is what I need

1. API to retrieve all messages (not per order)
2. Be able to reply to buyer message by API.

Thanks

**Comment by stefnats** [comment]
This is nothing I work with regularly, but I have an idea.
In order reports (or maybe even order Api) there are buyer emails that are specific to orders and buyers. That way, you can send messages to the buyer via email.

**Comment by romeolandry** [comment]
Hi, 
I am Interessting to know if there is upate about  this Issue?.

I have the same Problem as @GL128.
