### ISSUE TITLE
getItemOffers Response Missing Elements

### ISSUE THREAD

**Issue by tabertantrum** [amzn/selling-partner-api-docs#190]
We are unable to receive a well-formed response from the [getItemOffers operation](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getitemoffers).

So far, all responses regardless of ASIN are returning the same missing / incomplete data points in the Summary.

Our application is configured to have all roles and authorized on our seller account
Our application uses the user IAM (vs role)

Request:
```
GET
/products/pricing/v0/items/B07HGR9M6Z/offers
```

Response Headers:
```
Date: Tue, 08 Dec 2020 15:27:23 GMT
x-amzn-RequestId: e11c0cf9-3d56-401d-bad7-007b9b8c67c3
x-amz-apigw-id: XPU2NEvioAMFrCw=
X-Amzn-Trace-Id: Root=1-5fcf9b5a-79678793685271b93a63bf7f
Content-Type: application/json
```

Relevant Response Content:
  ```
"BuyBoxPrices": [
        {
          "condition": ""
        },
        {
          "condition": ""
        },
        {
          "condition": ""
        },
        {
          "condition": ""
        }
      ],
      "NumberOfOffers": [
        {
          "condition": "new",
          "fulfillmentChannel": "Amazon"
        },
        {
          "condition": "new",
          "fulfillmentChannel": "Merchant"
        }
      ],
      "BuyBoxEligibleOffers": [
        {
          "condition": "new",
          "fulfillmentChannel": "Amazon"
        },
        {
          "condition": "new",
          "fulfillmentChannel": "Merchant"
        }
      ],
      "TotalOfferCount": 30
```

The BuyBoxPriceType returned is effectively empty. It always returns four objects in the array, but each object only includes the key condition. It does not include a value for condition or any of the other keys defined in the BuyBoxPriceType (LandedPrice, ListingPrice, Shipping, Points).

The OfferCountType for both NumberOfOffers and BuyBoxEligibleOffers are returning the appropriate condition and fulfillmentChannel for current offers on the ASIN, but OfferCount is not included.

**Comment by johnkw** [comment]
Every ASIN I've looked at has this weird data: `"BuyBoxPrices": [{"condition": ""},{"condition": ""},{"condition": ""},{"condition": ""}]`

For example see attached the complete payload from `GET /products/pricing/v0/items/B07YF4FNL1/offers` .
[offers.txt](https://github.com/amzn/selling-partner-api-docs/files/5933573/offers.txt)

The documentation at https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#buyboxpricetype indicates there are 4 required fields, but `LandedPrice`, `ListingPrice`, `Shipping` are all missing, and `condition` seems to have an invalid value.

What's going on there?

**Comment by wulfw9** [comment]
@ShivikaK can please look into this? new app here, so unfortunately MWS is not an option. 
thank you

**Comment by johnkw** [comment]
Instead of weird chunks of non-documentation-compliant blank `BuyBoxPrices`, I'm now getting real data. Not sure if it's completely correct, but this bug seems fixed. I'm not exactly certain when the fixed happened, but probably around 10 days ago? Here's a log of the same call from above, but now showing valid data:

[log.txt](https://github.com/amzn/selling-partner-api-docs/files/6047458/log.txt)

Looks like someone fixed the API server, so I think this bug can be closed...?

**Comment by tabertantrum** [comment]
Confirmed this is consistently returning results. Closing issue.
