### ISSUE TITLE
ANY_OFFER_CHANGED subscription not firing

### ISSUE THREAD

**Issue by iamricks** [amzn/selling-partner-api-docs#1901]
I created a new SQS queue, created a destination and created a subscription successfully but i am not receiving any notifications for offer changes.

On the account i set the notifications on, i did have them setup through MWS i am not sure if there is some conflict here?

**Comment by iamricks** [comment]
I'm still not receiving any `ANY_OFFER_CHANGED` notifications.

I am migrating the last dependency i have with MWS, i'm moving stores to a new SQS queue and removing their MWS subscription and adding the subscription to the new destination through SP-API but i stop receiving notifications.

I've tried deleting everything and starting from scratch, new destination new subscription but i get nothing.

**Comment by iamricks** [comment]
Figured it out, i was missing [Step 1. Grant Selling Partner API permission to write to your SQS queue](https://github.com/amzn/selling-partner-api-docs/blob/97de7c3fabf53d541572cd1f89a5efb6583df1f9/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md) 

There should be some validation added where SP-API attempts to send a message to the queue to make sure authentication is correct.

**Comment by stefnats** [comment]
Actually, in MWS there was a call to test the sending privileges to an sqs queue. I wonder why it was not ported. Or maybe not ported yet.
Glad you could figure it out though.
