### ISSUE TITLE
[FEATURE] Grantless Notification Calls

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-docs#1904]
As developers, we need to be able to remove subscriptions from merchant accounts after our application is de-authorized so that notifications associated with the application no longer are received.  

Add GET /notifications/getSubscriptionsForMerchant/{sellerId} (grantless)
Modify grantfulness of DELETE /notifications/v1/subscriptions/{notificationType}/{subscriptionId} to grantless

Alternative:  Automatically remove subscriptions upon an application being de-authorized.

**Comment by stefnats** [comment]
I'm pretty sure that subscriptions are automatically removed or notifications are not sent anymore after deauthorization. I don't have a source on this but on my experience.
If it wasn't, it could create a cost bottleneck, for example for old customers that are not paying anymore, there could still be paid sqs calls.
