### ISSUE TITLE
Getting FATAL error on both GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA and GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#1906]
I want to get some data but I get FATAL error on both GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA and GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA. Why is that? if there is a rate limiter just say it. I haven't request this endpoint for 2 hours and still getting FATAL error.

**Comment by stefnats** [comment]
+1 I also receive that *sometimes* for estimated fba fees data.

**Comment by wbmgaye** [comment]
+1 also receiving this error. Any updates on this?

**Comment by wbmgaye** [comment]
I was able to resolve this issue and posted steps on a similar issue, hope it helps.

https://github.com/amzn/selling-partner-api-docs/issues/82#issuecomment-1079013737
