### ISSUE TITLE
inbound shipment item QuantityInCase always empty for shipments created via Send to FBA workflow

### ISSUE THREAD

**Issue by xiaoyu-tamu** [amzn/selling-partner-api-docs#1911]
![image](https://user-images.githubusercontent.com/33362998/149576352-049b597a-5e5d-4b26-a547-de8de34cf846.png)

![image](https://user-images.githubusercontent.com/33362998/149576067-5e6960b0-ffd5-4d90-9835-87997d604a93.png)

it should return correct QuantityInCase value "100" for FBA shipment created via Send to FBA. This information is needed for reconcile

**Comment by olsavmic** [comment]
We are having the same problem, the issue is still present. Amazon support confirmed the existence of the bug and according to their representative, a new API is coming in 2024 with a fix.
