### ISSUE TITLE
Getting REPORT_PROCESSING_FINISHED notifications for the report for which createReport request was not called.

### ISSUE THREAD

**Issue by raghavendra8s** [amzn/selling-partner-api-docs#1914]
This is related to SP-API. We have implemented push notifications

Approach: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#tutorial-set-up-notifications-amazon-simple-queue-service-workflow

We are observing that we are receiving notifications for the report types which we have not requested at all. Since we have not requested we don't download the report and it keeps coming continuously.

There are thousands of messages we are getting.

"notificationVersion" : "2020-09-04",
"notificationType" : "REPORT_PROCESSING_FINISHED",
"payloadVersion" : "1.0",
"eventTime" : "2022-01-03T16:22:54.260Z",
"payload" : {
"reportProcessingFinishedNotification" : {
"sellerId" : "XXXXXXX",
"reportId" : "550984018995",
"reportType" : "GET_MERCHANT_LISTINGS_ALL_DATA",<---------------------------------------
"processingStatus" : "DONE",
"reportDocumentId" : "amzn1.tortuga.3.f70507f2-b27e-4f6e-a04d-22ff900ebdd1.T1M61YJDPXQ56Z"
}
},
"notificationMetadata" : {
"applicationId" : "amzn1.sellerapps.app.b9c9ae66-1c09-4e56-a16c-5418d355b283",
"subscriptionId" : "fd362a85-4892-4fcd-9a6e-e7493bbeef82",
"publishTime" : "2022-01-03T16:22:54.411Z",
"notificationId" : "568105ed-4b91-443b-9d5e-118b6c96383e"
}

Please have a look

Thanks

**Comment by tho-masn** [comment]
@raghavendra8s Did you find out what the issue is/was? I'm experiencing the exact same behaviour.
After subscribing I'm getting those notifications, although I didn't create the reports.

**Comment by adeelsohailahmed** [comment]
as
