### ISSUE TITLE
access oauth url return Error Code:MD1000

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-docs#192]
I access oauth URI  https://sellercentral.amazon.com/apps/authorize/consent?application_id=xxxxx&state=xxxx fail,return error:MD1000,can you help me?the application_id must publish?

**Comment by lantaoGitHub** [comment]
no

**Comment by fengmiq** [comment]
@lantaoGitHub 应用未发布，通过生产授权链接授权出错，授权链接加上测试参数可以授权。你们没有遇到吗？

**Comment by lzy6666666** [comment]
How did your test process pass？ I use 'https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample&version=beta',  it return  can not find appid and Code:MD1000 also.

**Comment by ZzwDaiZi** [comment]
Please check if the URL in your app is filled in below. I didn't fill in the URL before, and it return can not find appid. What's the code returned? I forgot

**Comment by fengmiq** [comment]
@lzy6666666 appidexample change to yourself application id

**Comment by lzy6666666** [comment]
The problem has been resolved because My parameter added Spaces to my parameters when the URI jumped
