### ISSUE TITLE
How can I test redirect link authorized by using http://localhost?

### ISSUE THREAD

**Issue by twanlee** [amzn/selling-partner-api-docs#1921]
Hi you guys! 
I'm currently testing a draft app from my own computer. But when I enter the redirect link, I can not use localhost for testing! Is there any way I can test by local? Or do I have to buy a VPS and register a domain and push my code there to test?
![image](https://user-images.githubusercontent.com/61691162/149753645-aecfc611-8436-4e2d-8ed9-169abe9c241f.png)

**Comment by mmmatej** [comment]
Hey @twanlee. You can try with NGROk (https://ngrok.com/), which will expose your local server over a secure tunnel...
