### ISSUE TITLE
SP-API Auth  get MD5100, And Why the 'Auth redirect uri' has not been triggered!Looking forward to apply, thank u

### ISSUE THREAD

**Issue by juncai-pan** [amzn/selling-partner-api-docs#1926]
hello, @JordanForeman @hinavinayak @prashanthseshadri @ferrants @sellerjd  I used SP Application to Auth, but get a MD5100 result, like this

App ID: amzn1.sp.solution.15891a75-4618-4351-98ae-65d242ac1073
Error Code: MD5100

we config the 'Auth redirect uri' of the application, but The 'Auth redirect uri' has not been triggered。
why we get this result(MD5100),
we must marking the box "Enable OAuth from Appstore" in Edit App page?But donot have this checkbox now!
auth uri:https://sellercentral.amazon.com/apps/authorize/consent?state=83a9d8d859cc4e92a1e4d086c5a73b33&application_id=amzn1.sp.solution.15891a75-4618-4351-98ae-65d242ac1073&version=beta

Looking forward to your feedback, thank you。
![lADPF9eQEKyoUzHNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/49940912/149903746-0dffd7bd-b2fa-4423-8b22-1e3758b81228.jpg)
![47f98d5844cbe88c9bfd6a842a49545](https://user-images.githubusercontent.com/49940912/149903827-3f164e8e-6a70-4df2-ac3f-52a3f1771d31.png)
![f9ea66ed5cb91ede9c1638dc1569347](https://user-images.githubusercontent.com/49940912/149903872-76a4e113-401b-463f-acde-4564821bd206.png)

**Comment by hinavinayak** [comment]
Hello,

You need to provide both Oauth Login and Redirect URIs for the application configuration to take those values. This will resolve the error you are getting.
