### ISSUE TITLE
[BUG] GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT Data does not match Front End

### ISSUE THREAD

**Issue by cantonalex** [amzn/selling-partner-api-docs#1929]
Case ID: 9499366121

Did multiple tests for most current monthly data and Search Term rank does not match what is on the front end with the API output. This is a massive bug.

I am also only getting 1.75m rows instead of the 1.9m showing on brand analytics.

https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports
{
"reportType": "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
"marketplaceIds":["ATVPDKIKX0DER"],
"reportOptions": {"reportPeriod": "MONTH"},
"dataEndTime": "2021-12-31",
"dataStartTime": "2021-12-01"
}

f) amzn1.sp.solution.2ed81117-3fc3-4330-aa32-285ae534b25c

**Comment by hongfei-zhou** [comment]
<img width="109" alt="5150" src="https://user-images.githubusercontent.com/50116930/173895771-cbf9e3e1-ff6f-4c1a-a072-609bee87441a.png">

We have a customer whose use case is to provide asin filters in the UI to prioritize fulfillment. We can't do this in seller partner API with the current `reportOptions`.

**Comment by gabiginorio** [comment]
Likewise, I'm looking to provide asin and keyword filters but it doesn't seem to be an option in SP-API with the current `reportOptions`. Is there an opportunity to bump up this ticket??
