### ISSUE TITLE
[BUG] Why /finances/v0/financialEvents has no FBALiquidationEventList data

### ISSUE THREAD

**Issue by mjb1ifkr** [amzn/selling-partner-api-docs#1930]
**Describe the bug**
There are Liquidations data in the financial details I downloaded from the Amazon backend
![image](https://user-images.githubusercontent.com/87471695/150062149-cba5449d-ed43-4b74-b8eb-ff2f3b8a2653.png)

But through [https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md#financialevents], the FBALiquidationEventList data cannot be requested.
![image](https://user-images.githubusercontent.com/87471695/150062311-4e8b55c3-534e-4c48-a25a-e7a01fc6a784.png)

**URL of the content on GitHub**
[Please provide the GitHub URL for the documentation where you see the bug.](https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md#financialevents)

**Comment by masterevgeni** [comment]
I have same problem, with "FBALiquidationEventList" and "SellerDealPaymentEventList".
Any solution for this?

**Comment by danpe** [comment]
Bummer this is closed automatically, instead of being fixed 😢
