### ISSUE TITLE
[BUG] getCatalogItem return double quote error

### ISSUE THREAD

**Issue by littleylv** [amzn/selling-partner-api-docs#1931]
**Describe the bug**
when the item_name contains `"`, getCatalogItem return with `\"`
for example: https://www.amazon.co.uk/dp/B075LN87WY here it shows `KATUR 3/4" Round LED Front...`, but getCatalogItem returns:
```
[language_tag] => en_GB
[value] => KATUR 3/4\" Round LED Front...
[marketplace_id] => A1F83G8C2ARO7P
```
same problem to `generic_keyword`, `product_description`, `bullet_point`

**URL of the content on GitHub**
[Please provide the GitHub URL for the documentation where you see the bug.](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#getcatalogitem)

**Comment by chapmanjw** [comment]
Both `item_name` in the `attributes` and `itemName` in the `summaries` sections are correctly encoded for JSON:

```
{
  "asin": "B075LN87WY",
  "attributes": {
    "item_name": [
      {
        "language_tag": "en_GB",
        "value": "KATUR 3/4\" Round LED Front Rear Side Marker Indicators Light Waterproof Bullet Clearance Marker Light 12V for Car Truck (Amber)",
        "marketplace_id": "A1F83G8C2ARO7P"
      }
    ]
  },
  "summaries": [
    {
      "marketplaceId": "A1F83G8C2ARO7P",
      "brandName": "KATUR",
      "browseNode": "303682031",
      "itemName": "KATUR 3/4\" Round LED Front Rear Side Marker Indicators Light Waterproof Bullet Clearance Marker Light 12V for Car Truck (Amber)",
      "manufacturer": "KaTur",
      "modelNumber": "10",
      "sizeName": "10pcs Amber"
    }
  ]
}
```

Without the `\` in front of the double-quote, the JSON would be invalid.

How are you parsing/consuming the `attributes` data? It's likely that something isn't decoding the string correctly.

**Comment by littleylv** [comment]
@chapmanjw  But my json string (`\\\"`) is not like yours (`\"`):
```

        "item_name":[
            {
                "language_tag":"en_GB",
                "value":"KATUR 3/4\\\" Round LED Front Rear Side Marker Indicators Light Waterproof Bullet Clearance Marker Light 12V for Car Truck (Amber)",
                "marketplace_id":"A1F83G8C2ARO7P"
            }
        ],
```

and i am using PHP `json_decode` to parse it:
```
[item_name] => Array
                (
                    [0] => Array
                        (
                            [language_tag] => en_GB
                            [value] => KATUR 3/4\" Round LED Front Rear Side Marker Indicators Light Waterproof Bullet Clearance Marker Light 12V for Car Truck (Amber)
                            [marketplace_id] => A1F83G8C2ARO7P
                        )

                )
```

**Comment by chapmanjw** [comment]
@littleylv I can confirm what you are seeing. There is a component in between our backend systems and external clients that is transforming this result incorrectly. I will update this issue once we have a path forward for fixing it. Thanks!

**Comment by chapmanjw** [comment]
@littleylv The fix for this has been deployed.

**Comment by littleylv** [comment]
@chapmanjw Thank you very much! 👍  I have conformed that works now.
