### ISSUE TITLE
[BUG] Documentation - listingsItems_2021-08-01 getListingsItem no longer returning anything in the 'Attributes' element

### ISSUE THREAD

**Issue by TimoFedd** [amzn/selling-partner-api-docs#1936]
The listingsItems_2021-08-01 API has stopped returning anything in the 'Attributes' element. 
"attributes":{}

Calling the API like -includedData=attributes,summaries

**Comment by chapmanjw** [comment]
@TimoFedd Do you have a request id I can investigate (`X-Amzn-RequestId` response header)? Thanks.

**Comment by chapmanjw** [comment]
@TimoFedd I see attributes data in the raw response for that request. How are you interacting with the API (i.e. the Swagger Codegen client)?

By default, the Swagger Codegen clients use a generic `Object` to represent the `attributes` data. The issue with that behavior is that JSON deserializers do not have any properties to map the data to and thus you end up with an empty object. 

You can override what class the Codegen uses for those objects, see https://github.com/amzn/selling-partner-api-models/issues/195#issuecomment-998160956. This will hopefully get added to the SP API documentation soon.

**Comment by TimoFedd** [comment]
@chapmanjw That worked. Thank you very much!
