### ISSUE TITLE
Help required with RDT Tokens or PII Access

### ISSUE THREAD

**Issue by danielrona** [amzn/selling-partner-api-docs#1938]
Hi there, I'm confused maybe someone here can help me out.

We've several customers using our ERP System who are also Amazon Sellers, 
now we want to offer them a direct integration of the ERP to Amazon,
to import orders, create shipping slips and invoices.

As far as I understood it from the docs you need a Restricted Data Token (RDT) to get any PII Data (like Name or Address), 
but to get a RDT you need the to fill out the Restricted Access Request in your Developer Profile (https://sellercentral.amazon.de/developer/register).

Now I've filled the application out several times (in german first, then in english) 
and I only get canned responses that the request was denied.

Considering that we're fullfilling or surpassing all the requirements I can't figure out what seems to be the problem nor do the responses suggest what is missing.

Case : 7525583442
> To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications.

Case : 7548068612
> We evaluate all Public Developer applications that request Restricted SP-API access, for a variety of technical and business criteria including, but not limited to, launch readiness, services offered that can be viewed on a public facing website, and supported geographies.

Case : 7581220252
> As previously mentioned, we have determined that you will not be given access to Restricted SP-API roles based on your application. Your SP-API access remains unchanged at this time. We evaluate all Public Developer applications that request Restricted SP-API access, for a variety of technical and business criteria including, but not limited to, launch readiness, services offered that can be viewed on a public facing website, and supported geographies. Please note that this decision is final and we may not respond to further inquiries about this.

Since, no one apart from us could link our ERP system to Amazon, so yes I would say this is materially different from existing applications, as we're not building a "public app" I don't see any problems with our request. The last response said this decision is final again without any reasoning or explanation. 

I tried asking the Developer Support but apparantly they do not actually help us developers or don't want to? I got canned responses there too.

Case : 7548036892
> Hello from Amazon Selling Partner Support,Upon investigation, We see that you don't have access to PII information. However you have currently submitted the form.We request you to follow up on the case ID: 7548068612 for further update.For any other query, kindly open a new case.Kind regards,

Case : 7575036552
> Upon research I found that you need to verify your credit card details with your bank in all Europe marketplaces. Kindly update the Credit Card on file and wait for a maximum of 48 hours.

Apparantly we needed to verify our CC in ***all*** marketplaces, wich we did and reapplied.

Maybe I missunderstood and I do not need a RDT for customer data? 

But then the docs seem to be misleading, otherwise I don't see how we could ever achieve linking our ERP to the Seller Centrals from our customers.

**Comment by WWangYu** [comment]
Amazon seems to only open PII permissions for large companies (because the requirements are too strict), I also tried to apply for PII, but it was always rejected.

**Comment by danielrona** [comment]
> Amazon seems to only open PII permissions for large companies (because the requirements are too strict), I also tried to apply for PII, but it was always rejected.

That does not make any sense, while I agree PII Data is important to protect there should be no artifical restrictions to retrieve the data if our customers are giving us permissions to retrieve the Data, while we're in compliance with all the required privacy standards. Especially in Europe/Germany PII Data is a high-value high-protect dataset and germanys laws are quite harsh if you do not follow those.

**Comment by franclin** [comment]
> > Amazon seems to only open PII permissions for large companies (because the requirements are too strict), I also tried to apply for PII, but it was always rejected.
> 
> That does not make any sense, while I agree PII Data is important to protect there should be no artifical restrictions to retrieve the data if our customers are giving us permissions to retrieve the Data, while we're in compliance with all the required privacy standards. Especially in Europe/Germany PII Data is a high-value high-protect dataset and german laws are quite harsh if you do not follow those.

Hello @danielrona 
We're also facing the same issues. Did you get your request approved in the end? If so, what trick did you use in the end?

Thanks

**Comment by franclin** [comment]
> Amazon seems to only open PII permissions for large companies (because the requirements are too strict), I also tried to apply for PII, but it was always rejected.

Hello @WWangYu 
We're also facing the same issues. Did you manage to get your request approved in the end? What was the trick then?

Thanks

**Comment by fazal26** [comment]
Any update on this one ?

**Comment by danielrona** [comment]
Nope, we gave up.

**Comment by fazal26** [comment]
thanks for feedback guys.

**Comment by franclin** [comment]
> thanks for feedback guys.

How far did you get @fazal26 ?
