### ISSUE TITLE
getReports

### ISSUE THREAD

**Issue by DanieleGargini-Intarget** [amzn/selling-partner-api-docs#194]
Hi,
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md

I use https://sellingpartnerapi-eu.amazon.com/reports/2020-09-04/reports
method:GET
params:{}

and I get this errors

{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Vendor Group amzn1.vg.1237271 is not authorized to access vendor reports",
      "details": ""
    }
  ]
}

which kind of permission do I need?

**Comment by nodisk8800** [comment]
You need the access_token, Signature,Params(if required)
See the document
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by rugved1991** [comment]
Hi @DanieleGargini-Intarget,

If you are still seeing the same issue please let us know. We have launched reports specific for vendors. 
https://developer-docs.amazon.com/sp-api/docs/report-type-values#brand-analytics-reports
https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports

Best,
Rugved
Solutions Architect, SP API
