### ISSUE TITLE
[BUG] Endpoint: PUT listings-items-api ERROR fabic_type

### ISSUE THREAD

**Issue by CelestePerez** [amzn/selling-partner-api-docs#1942]
Actual behavior

When trying to create a Listing via API with listings-items-api we received the following error: fabric_type: the attribute is invalid 

This happens in the Product type AROMA_DIFFUSER, in the Diffusers category, which does not have a fabric_type attribute required when trying to upload this item via Seller Central. Nonetheless, when trying to upload it via API, then this fabric_type attribute is required and blocks us from creating a successful listing.

If in the attribute fabric_type data is not sent in the JSON Object, the API shows process success when trying to create the Listing. But in Seller Central, we can visualize the listing in the Incomplete listings list.

Expected behavior

When trying to create a Listing via API with listings-items-api in the Product type AROMA_DIFFUSER, in the Diffusers category, fabric_type attribute is not required and a successful listing is created.

**Comment by CelestePerez** [comment]
Yes Jhon, of course.

response {
  sku: 'DD-SD-W21',
  status: 'ACCEPTED',
  submissionId: '3a70a15975fe4b1689a939f6ed3b9383',
  issues: []
}
UTC Thu, 20 Jan 2022 19:26:25 GMT

Let me know if you need anything else.

**Comment by chapmanjw** [comment]
@CelestePerez When submitting to the Listings APIs, we perform some validations up front synchronously. However, there are some processing errors that only occur asynchronously. In this case, an async error was logged for a missing `part_number`. You can use the `getListingsItem` operation to retrieve these errors: https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#getlistingsitem. 

You can also subscribe to Listings Issues Notifications to receive notifications as soon as these issues are logged to the listing.
