### ISSUE TITLE
[BUG] supplier_declared_has_product_identifier_exemption 

### ISSUE THREAD

**Issue by CelestePerez** [amzn/selling-partner-api-docs#1943]
Actual behavior

When trying to create a Listing via API with listings-items-api we received the following error in Sellers Central: Make sure that all standard product ids (UPC,EAN,ISBN, JAN) are correct. 

The API showed success in uploading the listing, but when visualizing it from the Sellers Central, it appeared in the incomplete listings list, with the Make sure that all standard product ids (UPC,EAN,ISBN, JAN) are correct. 

This particular listing has an approved Amazon GTIN excemption. Case log ID 9414602951 

In the JSON Object, the supplier_declared_has_product_identifier_exemption was set to TRUE.

This happens in the Product type COFFEE, in the Roasted Coffee Beans category, which according to the API belongs to the Product type API: PRODUCT, since COFFEE is not yet supported by the existing API. 

Expected behavior

When trying to create a Listing via API with listings-items-api in the Product type COFFEE, in the Roasted Coffee Beans category, and setting supplier_declared_has_product_identifier_exemption in TRUE, then the UPC,EAN,ISBN, JAN is not required and a successful listing is created.

**Comment by chapmanjw** [comment]
@CelestePerez As mentioned under `Considerations` in the [Listings API use-case guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2021-08-01.md), the Listings APIs do not yet support all product types. We are migrating product type content and making those available in the APIs as they are ready.

You can refer to the [search operation of the Product Type Definitions API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md#tutorial-search-available-product-type-definitions) with no keywords to get a complete list of what product types are available for a given marketplace.

**Comment by CelestePerez** [comment]
Yes, this is what we did, but it did not apply the exemption as requested via API. The request ID in this case is 

response {
  sku: 'AVC-ODC-LL2',
  status: 'ACCEPTED',
  submissionId: 'fb029d68c23041738b8b9a0e02344e54',
  issues: []
}
UTC Thu, 20 Jan 2022 19:34:03 GMT

Thank you!

**Comment by CelestePerez** [comment]
Any updates? @chapmanjw

**Comment by chapmanjw** [comment]
@CelestePerez Creating items without product identifiers requires a GTIN exemption for the given brand and marketplace. Setting `supplier_declared_has_product_identifier_exemption` to `true` on the submission side is a mechanism to skip providing the product identifier when you already know you are GTIN exempt. After submission, this is validated asynchronously, producing missing attribute errors if you are actually not GTIN exempt. 

Refer to https://sellercentral.amazon.com/help/hub/reference/GU3L6JPGXADSNNU5 for more information on GTIN excemptions.
