### ISSUE TITLE
[BUG] main_offer_image_locator in listings-items-api

### ISSUE THREAD

**Issue by CelestePerez** [amzn/selling-partner-api-docs#1944]
Actual behavior

When trying to create a Listing via API with listings-items-api we received the following error in Sellers Central: Images could not be associated with this SKU. This error may be resolved by addressing other product data errors. Error code 20005.

The API showed success in uploading the listing, but when visualizing it from the Sellers Central, it appeared in the incomplete listings list, with the Images could not be associated with this SKU. This error may be resolved by addressing other product data errors. Error code 20005. Make sure that all standard product IDs [such as UPC, ISBN, EAN or JAN codes are correct] 

In the JSON Object, we sent:
"externally_assigned_product_identifier": {
      "type": "upc",
      "value": "65832542****",
      "marketplace_id": "ATVPDKIKX0DER"
    }
UPC code is under GS1 standard and complies with AMAZON requirements.

This happens in the AROMA_DIFFUSER Product type , in the Diffusers category.

Expected behavior

When trying to create a Listing via API with listings-items-api in the Product type AROMA_DIFFUSER, in the Diffusers category, and uploading images within the requirements, then a successful listing is created.

**Comment by chapmanjw** [comment]
@CelestePerez Can you provide me a request id (`X-Amzn-RequestId` response header) and UTC timestamp for the request so I can take a look at what happened?

**Comment by CelestePerez** [comment]
We changed the UPC for an EAN and the same error is showing.

"externally_assigned_product_identifier": {
      "type": "upc",
      "value": "63424009****"
    }

response {
  sku: 'DD-SD-W21',
  status: 'ACCEPTED',
  submissionId: '3a70a15975fe4b1689a939f6ed3b9383',
  issues: []
}
UTC Thu, 20 Jan 2022 19:26:25 GMT

Thank you

**Comment by lilveniceguy** [comment]
@chapmanjw  Is there an alternative solution for this situations? I'm getting the same issue, thanks!

**Comment by chapmanjw** [comment]
@CelestePerez Looking at that submission, it appears that you are trying to create a new item (i.e. not trying to sell an existing item in Amazon's catalog). However, the `LISTING_OFFER_ONLY` requirements set was used. The `LISTING_OFFER_ONLY` requirements set only works for creating listings for existing items.

If you use the `LISTING` requirements set, you will see the up-front validation errors for the missing attributes required to create a new item. In this instance, `part_number` is missing. When using the Listings Items Get API, you will see the two error messages (one for the missing attribute(s) and one for the image).

Images are processed separately from the textual content for listings. When you see image errors like `Images could not be associated with this SKU. This error may be resolved by addressing other product data errors.`, the processing of the textual product content is what actually failed and the image couldn't be processed.

**Comment by chapmanjw** [comment]
@lilveniceguy When you see `Images could not be associated with this SKU. This error may be resolved by addressing other product data errors.`, as mentioned above, this is due to not being able to process images because other data failed to process. When investigating these issues, look for other issues on the item related to product attributes (either by calling an API or viewing the item on Seller Central).
