### ISSUE TITLE
Reports fetch for different marketplaces have the same data

### ISSUE THREAD

**Issue by ykuni-software-developer** [amzn/selling-partner-api-docs#1945]
I was trying to fetch Amazon FBA reports using the reports API endpoint. I've also created different schedule reports for each marketplace we have access to.
However, when I try to fetch these reports for each marketplace. They contain the same data.
I am also using a python wrapper library for the Amazon SP-API.

**Comment by kpconnell** [comment]
Think this should be merged with #1961
