### ISSUE TITLE
Order Fulfillment Feed(POST_ORDER_FULFILLMENT_DATA) display:The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 1, column 820.

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-docs#195]
**I send xml:**
`<?xml version="1.0" encoding="UTF-8"?><AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-base.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Header><DocumentVersion>1.01</DocumentVersion><MerchantIdentifier>A30TSXXXX</MerchantIdentifier></Header><MessageType>OrderFulfillment</MessageType><Message><MessageID>1</MessageID><OperationType>Update</OperationType><OrderFulfillment><AmazonOrderID>111-8876736-68970XX</AmazonOrderID><FulfillmentDate>2020-12-09T09:47:06.000Z</FulfillmentDate><FulfillmentData><CarrierName>FedEx</CarrierName><ShippingMethod>FedEx First Class</ShippingMethod><ShipperTrackingNumber>781113347XXX</ShipperTrackingNumber></FulfillmentData><Item><AmazonOrderItemCode>50055952950XXX</AmazonOrderItemCode><Quantity>1</Quantity></Item></OrderFulfillment></Message></AmazonEnvelope>`
**return**:
`{
    "errcode": 0,
    "errmsg": "ok",
    "data": {
        "Header": {
            "DocumentVersion": "1.02",
            "MerchantIdentifier": "A30TS8QXFXXX"
        },
        "MessageType": "ProcessingReport",
        "Message": {
            "MessageID": "1",
            "ProcessingReport": {
                "DocumentTransactionID": "53935018605",
                "StatusCode": "Complete",
                "ProcessingSummary": {
                    "MessagesProcessed": "0",
                    "MessagesSuccessful": "0",
                    "MessagesWithError": "1",
                    "MessagesWithWarning": "0"
                },
                "Result": {
                    "MessageID": "9223372036854775807",
                    "ResultCode": "Error",
                    "ResultMessageCode": "50001",
                    "ResultDescription": "The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 1, column 820."
                }
            }
        }
    }
}`
**can you supply a demo?**

**Comment by nodisk8800** [comment]
My request XML:

<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">  
  <Header> 
    <DocumentVersion>1.02</DocumentVersion>  
    <MerchantIdentifier>xxxxxx</MerchantIdentifier> 
  </Header>  
  <MessageType>OrderFulfillment</MessageType>  
  <PurgeAndReplace>false</PurgeAndReplace>  
  <Message> 
    <MessageID>xxxx</MessageID>  
    <OrderFulfillment> 
      <AmazonOrderID>xxx-xxxxxxx-xxxxxxx</AmazonOrderID>  
      <FulfillmentDate>2020-12-20Txx:xx:xx</FulfillmentDate>  
      <FulfillmentData> 
        <CarrierName>USPS</CarrierName>  
        <ShippingMethod>FirstClass</ShippingMethod>  
        <ShipperTrackingNumber>92748xxxxx</ShipperTrackingNumber> 
      </FulfillmentData> 
    </OrderFulfillment> 
  </Message> 
</AmazonEnvelope>


It success to upload Tracking Number.
I hope it can help you.

**Comment by nodisk8800** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">  
  <Header> 
    <DocumentVersion>1.02</DocumentVersion>  
    <MerchantIdentifier>xxxxxx</MerchantIdentifier> 
  </Header>  
  <MessageType>OrderFulfillment</MessageType>  
  <PurgeAndReplace>false</PurgeAndReplace>  
  <Message> 
    <MessageID>xxxx</MessageID>  
    <OrderFulfillment> 
      <AmazonOrderID>xxx-xxxxxxx-xxxxxxx</AmazonOrderID>  
      <FulfillmentDate>2020-12-20Txx:xx:xx</FulfillmentDate>  
      <FulfillmentData> 
        <CarrierName>USPS</CarrierName>  
        <ShippingMethod>FirstClass</ShippingMethod>  
        <ShipperTrackingNumber>92748xxxxx</ShipperTrackingNumber> 
      </FulfillmentData> 
    </OrderFulfillment> 
  </Message> 
</AmazonEnvelope>
`

**Comment by nodisk8800** [comment]
![999](https://user-images.githubusercontent.com/76502612/102957683-ff03c900-4515-11eb-8eec-2c116d723879.jpg)

**Comment by nodisk8800** [comment]
![XML Request Image Click Here ](https://user-images.githubusercontent.com/76502612/102957713-1642b680-4516-11eb-8a6f-c65bf2f5e6ee.jpg)

**Comment by nodisk8800** [comment]
[XML request Image](https://github-production-user-asset-6210df.s3.amazonaws.com/76502612/102957713-1642b680-4516-11eb-8a6f-c65bf2f5e6ee.jpg)

**Comment by nodisk8800** [comment]
[----------XML request Image ---------------](http://github-production-user-asset-6210df.s3.amazonaws.com/76502612/102957713-1642b680-4516-11eb-8a6f-c65bf2f5e6ee.jpg)

**Comment by fengmiq** [comment]
@nodisk8800 you are delete item section,but I need use part fulfillment

**Comment by nodisk8800** [comment]
My Seller Partner fulfillment one order one package one trackingnumber.
So no need the Item elements.

**Comment by MrYing** [comment]
@nodisk8800 I have a similar question
return error:
`XML Parsing Fatal Error at Line 1, Column 226: The element type &quot;Header&quot; must be terminated by the matching end-tag &quot;&lt;/Header&gt;&quot;. The element type &quot;Header&quot; must be terminated by the matching end-tag &quot;&lt;/Header&gt;&quot;.`
But my xml is :
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.02</DocumentVersion>
        <MerchantIdentifier>XXXXXXXX</MerchantIdentifier>
    </Header>
    <MessageType>Product</MessageType>
    <PurgeAndReplace>true</PurgeAndReplace>
    <Message>
        <MessageID>10001</MessageID>
        <OperationType>Update</OperationType>
        <Product>

**Comment by luoshishu** [comment]
I have a similar question.
So , How do you solve this problem? 

@fengmiq

**Comment by nodisk8800** [comment]
@fengmiq 
你的XML中发货时间:
<FulfillmentDate>2020-12-09T09:47:06.000Z</FulfillmentDate>
我这边是使用:
<FulfillmentDate>2020-12-09T09:47:06</FulfillmentDate>

你可以去掉后面的时区再试一下, 这个时间本身默认的时区是 0 时区.

**Comment by nodisk8800** [comment]
有问题可以到我们的Q-Q群里问吧,普通的技术问题可能更快能解决

**Comment by qingwuit** [comment]
@nodisk8800  草稿状态是否无法获取到orderItems的订单价格，感觉根据接口获取的实际字段信息，比文档少很多。

**Comment by nodisk8800** [comment]
草稿状态也可以取到有关的价格信息

**Comment by jieett** [comment]
> 草稿状态也可以取到有关的价格信息

龙哥 qq群通过一下

**Comment by luoshishu** [comment]
@nodisk8800 我也有一些问题想问你 , 麻烦提供联系的qq号

**Comment by chenlixin93** [comment]
说一下我遇到的情况，希望对其他人有帮助

I'd like to talk about my situation and hope it can help others.

mws成功提交的模板，到了 sp-api 这边一直报错

The template successfully submitted by MWS has been reporting errors to SP API.

```
The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 27, column 18.
```

**原因竟是 sp-api 这边识别不到最后一行的换行**

**The reason is that SP API can't recognize the line feed of the last line**

- 原始模板

```
//  PHP
$feed = <<<XML
<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
<Header>
<DocumentVersion>1.02</DocumentVersion>
<MerchantIdentifier>xxxxxxx</MerchantIdentifier>
</Header>
<MessageType>OrderFulfillment</MessageType>
<Message>
<MessageID>1</MessageID>
<OrderFulfillment>
<AmazonOrderID>xxx-xxxxxxx-xxxxxxx</AmazonOrderID>
<FulfillmentDate>2021-07-06T05:54:39</FulfillmentDate>
<FulfillmentData>
<CarrierName>DHL</CarrierName>
<ShippingMethod>Expedited</ShippingMethod>
<ShipperTrackingNumber>xxxxxxxxxx</ShipperTrackingNumber>
</FulfillmentData>
<Item>
<AmazonOrderItemCode>xxxxxxxxxxxxxx</AmazonOrderItemCode>
<Quantity>1</Quantity>
</Item>
</OrderFulfillment>
</Message>
</AmazonEnvelope>
XML;
```

- 打印效果

![image](https://user-images.githubusercontent.com/22536294/124716168-590a3000-df36-11eb-8e2e-02431a529b44.png)

- 修改模板

```
//  PHP
$feed = <<<XML
<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
<Header>
<DocumentVersion>1.02</DocumentVersion>
<MerchantIdentifier>xxxxxxx</MerchantIdentifier>
</Header>
<MessageType>OrderFulfillment</MessageType>
<Message>
<MessageID>1</MessageID>
<OrderFulfillment>
<AmazonOrderID>xxx-xxxxxxx-xxxxxxx</AmazonOrderID>
<FulfillmentDate>2021-07-06T05:54:39</FulfillmentDate>
<FulfillmentData>
<CarrierName>DHL</CarrierName>
<ShippingMethod>Expedited</ShippingMethod>
<ShipperTrackingNumber>xxxxxxxxxx</ShipperTrackingNumber>
</FulfillmentData>
<Item>
<AmazonOrderItemCode>xxxxxxxxxxxxxx</AmazonOrderItemCode>
<Quantity>1</Quantity>
</Item>
</OrderFulfillment>
</Message>
</AmazonEnvelope>

XML;
```

- 打印效果

![image](https://user-images.githubusercontent.com/22536294/124717354-a2a74a80-df37-11eb-9787-187355fa8c0c.png)

- 提交成功 Submitted successfully

**Comment by yingyuhaonan** [comment]
> 草稿状态也可以取到有关的价格信息

我也想加QQ

**Comment by jimshi95** [comment]
请问哪里可以加qq群
