### ISSUE TITLE
[BUG] patchListingsItem is not working！

### ISSUE THREAD

**Issue by J-W-Chan** [amzn/selling-partner-api-docs#1950]
x-amzn-RequestId：21d67965-365f-4c4f-a0ef-fff753bbf496
X-Amzn-Trace-Id：Root=1-61ea6550-7a6c2c2766a119e87bd15655
I tried to change the purchasable_Offer from 2.99 USD to 2.96 USD  using patchListingsItem  API. 
The API return successful, but the actual the seller center did not change.

**Comment by od081274gil** [comment]
HI @J-W-Chan  did you find a solution to this problem?

**Comment by J-W-Chan** [comment]
still no work
