### ISSUE TITLE
[BUG] Time is ignored when getting Orders

### ISSUE THREAD

**Issue by JowJoris** [amzn/selling-partner-api-docs#1951]
**Describe the bug**
When retrieving orders with the parameter `createdAfter` and the value set to for example '2022-01-19T23:59:59' all the orders from 2022-01-19 are retrieved.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-orders-api/vendorOrders.md

**Description of what the documentation currently says**
`createdAfter` can be filtered by DateTime

**Description of what the documentation should says**
`createdAfter` can only be filtered by Date

**Comment by littleylv** [comment]
`Must be in ISO-8601 date/time format.`

try using `ISO-8601` format like `2020-02-15T14:00:00-08:00`?

**Comment by JowJoris** [comment]
@littleylv I tried it with the following time: `2022-01-24T16:59:59+14:00` which gets converted to `24/01/2022 03:59:59` by C# DateTime.Parse(). The response is still orders with the following `PurchaseOrderDate = {24/01/2022 03:19:54 +00:00}`. I fixed it currently by checking if the PurchaseOrderNumber already exists within my database, if so I ignore the order, but it's not ideally.

**Comment by littleylv** [comment]
@JowJoris 

> 2022-01-24T16:59:59+14:00 which gets converted to 24/01/2022 03:59:59

`2022-01-24T16:59:59+14:00` means `2022-01-24 02:59:59+00:00` UTC time, so the response with `PurchaseOrderDate = {24/01/2022 03:19:54 +00:00}` (`03:19:54` > `02:59:59`) should be expected

**Comment by JowJoris** [comment]
> "2022-01-24T16:59:59+14:00 means 2022-01-24 02:59:59+00:00 UTC time, so the response with PurchaseOrderDate = {24/01/2022 03:19:54 +00:00} (03:19:54 > 02:59:59) should be expected

I tried with your example to change it to `2022-01-24T17:59:59+14:00` which means `2022-01-24 03:59:59` and still getting the same orders.
