### ISSUE TITLE
Vendor Usage of Shipments API

### ISSUE THREAD

**Issue by rayworrell** [amzn/selling-partner-api-docs#1952]
Hello, everyone!

I was wondering if there is someone out there that would be able to help me with an API call that is vexing me.

I'm a retail vendor, and Amazon recently opened up API access to our breed of cat.  Most recently (November 2021), they opened up access to the shipments API where vendors could create routing requests instead of going into Vendor Central.

I'm sure I've lost most of your interests by now, but for those still hanging on...

Is there anyone out there who has been successful in taking advantage of this functionality?

Any call I make to https://sellingpartnerapi-na.amazon.com/vendor/shipping/v1/shipments results in an "Access to requested resource is denied." error.  I'm able to use other APIs, such as the https://sellingpartnerapi-na.amazon.com/vendor/shipping/v1/shipmentConfirmations, with no problems.  

I've reached out to Amazon.  They are insisting they need to see an example of the data in and data out.  I keep trying to explain that I can't send any data because of the access denied blocker.  They keep insisting my developer account has access.

Any advice for this weary programmer?

Thanks, All,
Ray.

**Comment by ANarayanan-Cervello** [comment]
@rayworrell Are you using the Saleweaver wrapper for SP-API?

**Comment by mukeshpiplai** [comment]
@rayworrell Hi Ray, I have an error with https://sellingpartnerapi-na.amazon.com/vendor/shipping/v1/shipmentConfirmations, ie 'Access to requested resource is denied", Can you guide us to solve this?

**Comment by wonsky87** [comment]
Did you solve this problem?
I'm having this trouble too.

**Comment by mukeshpiplai** [comment]
@wonsky87 Yes, It solved

**Comment by wonsky87** [comment]
@mukeshpiplai  can you help me? i have no idea.
