### ISSUE TITLE
[BUG] Not clear how to retrieve PurchaseOrders from all the EU regions with one app

### ISSUE THREAD

**Issue by semso-software** [amzn/selling-partner-api-docs#1957]
We have followed the documentation the create an api integration. We have created the app in the german vendor central. We can retrieve purchase orders from the sp-api. But we cannot retrieve the purchase orders from other regions like Spain, Italy. It's not clear what we have to do by following the current documentation.

request: /vendor/orders/v1/purchaseOrders/
endpoint: https://sellingpartnerapi-eu.amazon.com

**Comment by YEE271** [comment]
Hello, I would like to ask if you have solved this problem. After authorizing the German supplier credentials, I cannot access the French supplier data in the same region. The French supplier needs to be authorized again before they can access, that is, a single authorization is only a single site
