### ISSUE TITLE
[BUG] Inbound shipment Create function

### ISSUE THREAD

**Issue by uk-2** [amzn/selling-partner-api-docs#1962]
**Describe the bug**

We are trying to create a shipment plan using :

```
POST /fba/inbound/v0/shipments/{shipmentId}
Operation: createInboundShipment
```
FOR AMAZON UK  Marketplace but we are getting no where we keept hitting this error message : 

"message": "Access to requested resource is denied.", "code": "Unauthorized", "details": ""

Does anyone know why ?
```
request body is correct::
          "ShipFromAddress": {
            "Name": "EXAMPLE",
            "AddressLine1": "EXAMPLE",
            #"AddressLine2": "",
            "DistrictOrCounty": "EXAMPLE",
            "City": "EXAMPLE",
            "StateOrProvinceCode": "EXAMPLE",
            "CountryCode": "GB",
            "PostalCode": "EXAMPLE"
          },
          "LabelPrepPreference": "SELLER_LABEL",
          "ShipToCountryCode": "GB",
          "InboundShipmentPlanRequestItems": [
            {
              "SellerSKU": "E8-SOKR-LARY",
              "ASIN": "B01FK5SVC1",
              "Condition": "NewItem",
              "Quantity": 1,
              "QuantityInCase": 1,
              "PrepDetailsList": [
                "PrepInstruction": "Labeling",
                "PrepOwner": "SELLER"
              ]
            }
          ]
```

Does anyone know if inbound shipment API even works for EU  specifically for UK Sellers?  
I don't believe we have a permission because we are able to rertive getInboundGuidance for a SKU so therefore assume inbound api works for UK ?

We have all permission roles ticked in develop apps and we are using the SPAPI for other functions in our app and it works.

@ShivikaK @parvathm

 @cpiggott @CarlosSiles21

**Comment by CarlosSiles21** [comment]
@uk-2  Based on the message your credentials are not correct. We have these marketplaces working but remember that each marketplace has its own credentials.

**Active Service Urls**
https://mws.amazonservices.com
https://mws.amazonservices.ca
**https://mws.amazonservices.co.uk**
https://mws.amazonservices.de
https://mws.amazonservices.it
https://mws.amazonservices.fr
https://mws.amazonservices.es

I recommend you to use the MWS Scratchpad [(](https://mws.amazonservices.com/scratchpad/index.html)

**Comment by uk-2** [comment]
Thanks yes it was the service url
