### ISSUE TITLE
it's incorrect to ever send floating point numbers as money

### ISSUE THREAD

**Issue by ericblade** [amzn/selling-partner-api-docs#1964]
... there was a chance to fix this when rolling out a new API, but somehow it was made even worse -- the old API would usually send strings for money, now you're sending raw floating point numbers.

This is something that should *never* be done.  Ever.  In any API anywhere in the world.  

Use integers or strings, never floats.

**Comment by ianrussel** [comment]
too many bugs unfixed

**Comment by vaidas-lungis** [comment]
bump
