### ISSUE TITLE
[FEATURE] Documentation - how to make the oauth refer back to a different login page?

### ISSUE THREAD

**Issue by ericblade** [amzn/selling-partner-api-docs#1966]
The OAuth configuration allows you to specify multiple login pages, presumably for implementing multiple staging pipelines for an application, such as a production, staging, dev, etc.   (it notably specifically disallows you from using 'localhost', BOO, prevents from rapid testing without doing weird workarounds) 

The help on that field, says you can specify which login url to return to.  It doesn't say *how* you do so, nor can I find it anywhere in the documentation.

If you have multiple stages setup, such as a prod, staging, and dev server setup, how do you tell the OAuth which one you are?

**Comment by stefnats** [comment]
You need to add the redirect_uri param and add this URL to your app in seller central.

**Comment by ericblade** [comment]
so, if i have a secondary url setup as https://staging.mysite.com/login , when i send the user to authorize via sellercentral, i'd add &redirect_uri=https://staging.mysite.com/login ?

**Comment by petergzli** [comment]
Hey @stefnats @ericblade I'm actually attempting this too. As Eric is suggesting I am too using multiple for different environments with staging, etc. 

I am currently trying to add a staging redirect_uri however it is still redirecting back to my primary. Is there a wait/processing time from Amazon until it activates or do I need to re-submit my app for the new redirect_uri to be activated?

**Comment by ericblade** [comment]
re-opening because it hasn't been put into the documentation, even if the g iven solution is correct
