### ISSUE TITLE
Tracking amazon fees, many of them are incomplete details

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#1972]
Hi, we are trying to track all amazon fees and show them to our customers. However, most of them seem incomplete both in reports API and financial events. 
I would like to seek help on how/what/where in the API I can fetch the complete details specifically for the following fees

- Subscription
- RemovalFee

Here is the response when calling the financial events API

           ` "GuaranteeClaimEventList": [],
            "ChargebackEventList": [],
            "PayWithAmazonEventList": [],
            "ServiceProviderCreditEventList": [],
            "RetrochargeEventList": [],
            "RentalTransactionEventList": [],
            "ProductAdsPaymentEventList": [],
            "ServiceFeeEventList": [
                {
                    "AmazonOrderId": "T630nVKh2j",
                    "FeeList": [
                        {
                            "FeeType": "FBARemovalFee",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -0.25
                            }
                        }
                    ]
                },
                {
                    "AmazonOrderId": "T630nVKh2j",
                    "FeeList": [
                        {
                            "FeeType": "FBARemovalFee",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -0.25
                            }
                        }
                    ]
                },
                {
                    "FeeList": [
                        {
                            "FeeType": "Subscription",
                            "FeeAmount": {
                                "CurrencyCode": "EUR",
                                "CurrencyAmount": -39
                            }
                        }
                    ]
                }
            ],
            "SellerDealPaymentEventList": [],
            "DebtRecoveryEventList": [],
            "LoanServicingEventList": [],
            "AdjustmentEventList": [
                {
                    "AdjustmentType": "CommissionCorrection",
                    "PostedDate": "2022-01-19T02:45:25+00:00",
                    "AdjustmentAmount": {
                        "CurrencyCode": "EUR",
                        "CurrencyAmount": 134.59
                    }
                },`

As you can see above, we need informations for `Subscriptions` and `RemovalFee` under `ServiceFeeEventList` like what we have in `CommissionCorrection` under `AdjustmentEventList`. Without fields related to date, `ServiceFeeEventList` is useless, because how can we know when are those fees happening or which product / asin / SKU they are related to?

I know there are still lots of unresolved issues related to this topic, but please can you help us finally solve this? We are spending too much time banging our heads just to solve this issue but to no avail.

And honestly, we already lost two customers because of these unresolved issues on the amazon API side.

**Comment by kpconnell** [comment]
First:  If you have a client that is looking for to-the-cent matching, you might consider looking for a different client. 

Second: Subscriptions aren't sku related.

Third:  Have you checked the removal orders report for correlating order ids?
