### ISSUE TITLE
amz listing An internal error occurred. Please resubmit your data. For more details, seehttp://sellercentral.amazon.com/gp/errorcode/5002

### ISSUE THREAD

**Issue by github-project** [amzn/selling-partner-api-docs#1974]
An internal error occurred. Please resubmit your data. For more details, see http://sellercentral.amazon.com/gp/errorcode/5002,There is no record of the SKU corresponding to this update on your account. This commonly occurs when there are other issues on your SKU.,We cannot associate an image with this SKU because the SKU was not created due to another error. Correct all other errors associated with it and resubmit your inventory file to resolve this error.

**Comment by stefnats** [comment]
Hey there, when does this appear? Can you provide request and response data?

**Comment by DLR2020** [comment]
I had the same problem yesterday

{
  "header": {
    "sellerId": "",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 9821,
      "sku": "JYB3001FN128bHY",
      "operationType": "UPDATE",
      "productType": "CHAIR",
      "requirements": "LISTING",
      "attributes": {
        "item_name": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "Upland 77\" Long Reclining Single Chaise—JYB3001FN128bHY"
          }],
        "brand": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "***"
          }],
        "item_type_keyword": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "dining-chairs"
          }],
        "item_type_name": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "country_of_origin": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "US"
          }],
        "product_description": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "bullet_point": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "This patio chaise lounge has a wide backrest, which can be adjusted to different positions according to your preference."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "This lounge chair is made of all-weather fabric and heavy-duty powder-coated steel frame, which ensures the weather resistance and durability for long term use. Besides, the extra support bars let it bear a maximum 300 pounds of load."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "Made of high-quality fabric, this recliner is skin-friendly and breathable, allowing you to enjoy the cool outdoors even in summer."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "The recliner is in a classical and stylish appearance, which is a great addition and adds a unique charm to your outside space. Furthermore, the lightweight design makes the chair easy to carry and move."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "With detailed instruction and all accessories included in the package, you can assemble this recliner in a short time effortlessly."
          }],
        "supplier_declared_dg_hz_regulation": [
          {
            "value": "not_applicable"
          }],
        "condition_type": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "new_new"
          }],
        "batteries_required": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": false
          }],
        "parentage_level": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "parent"
          }],
        "child_parent_sku_relationship": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "child_relationship_type": "variation"
          }],
        "variation_theme": [
          {
            "name": "SIZE"
          }]
      }
    },
    {
      "messageId": 9831,
      "sku": "D0102HH362G4sjSK",
      "operationType": "UPDATE",
      "productType": "CHAIR",
      "requirements": "LISTING",
      "attributes": {
        "externally_assigned_product_identifier": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "type": "upc",
            "value": "676351527994"
          }],
        "item_name": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "Upland 77\" Long Reclining Single Chaise—JYB3001FN128bHY"
          }],
        "brand": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "****"
          }],
        "item_type_keyword": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "dining-chairs"
          }],
        "purchasable_offer": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "currency": "USD",
            "our_price": [
              {
                "schedule": [
                  {
                    "value_with_tax": 148.44
                  }]
              }]
          }],
        "fulfillment_availability": [
          {
            "quantity": 0,
            "fulfillment_channel_code": "DEFAULT",
            "lead_time_to_ship_max_days": 3
          }],
        "item_weight": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "unit": "pounds",
            "value": 31
          }],
        "item_depth_width_height": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "depth": {
              "unit": "inches",
              "value": 48
            },
            "width": {
              "unit": "inches",
              "value": 6.3
            },
            "height": {
              "unit": "inches",
              "value": 24
            }
          }],
        "item_package_weight": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "unit": "pounds",
            "value": 31
          }],
        "item_package_dimensions": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "height": {
              "unit": "inches",
              "value": 24
            },
            "length": {
              "unit": "inches",
              "value": 48
            },
            "width": {
              "unit": "inches",
              "value": 6.3
            }
          }],
        "product_description": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "bullet_point": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "This patio chaise lounge has a wide backrest, which can be adjusted to different positions according to your preference."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "This lounge chair is made of all-weather fabric and heavy-duty powder-coated steel frame, which ensures the weather resistance and durability for long term use. Besides, the extra support bars let it bear a maximum 300 pounds of load."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "Made of high-quality fabric, this recliner is skin-friendly and breathable, allowing you to enjoy the cool outdoors even in summer."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "The recliner is in a classical and stylish appearance, which is a great addition and adds a unique charm to your outside space. Furthermore, the lightweight design makes the chair easy to carry and move."
          },
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "With detailed instruction and all accessories included in the package, you can assemble this recliner in a short time effortlessly."
          }],
        "main_product_image_locator": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "media_location": "https://d2a59xdbgccpo7.cloudfront.net/dg-UOqNFeziCcVg/d0102heviy7.jpg"
          }],
        "supplier_declared_dg_hz_regulation": [
          {
            "value": "not_applicable"
          }],
        "condition_type": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "new_new"
          }],
        "parentage_level": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "child"
          }],
        "child_parent_sku_relationship": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "child_relationship_type": "variation",
            "parent_sku": "JYB3001FN128bHY"
          }],
        "variation_theme": [
          {
            "name": "SIZE"
          }],
        "color": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": ""
          }],
        "size": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "natural"
          }],
        "style": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "material": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "seat": [
          {
            "language_tag": "en_US",
            "back_interior_height": [
              {
                "value": 0,
                "unit": "inches"
              }],
            "depth": [
              {
                "value": 0,
                "unit": "inches"
              }],
            "height": [
              {
                "value": 0,
                "unit": "inches"
              }],
            "length": [
              {
                "value": 0,
                "unit": "inches"
              }]
          }],
        "manufacturer": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": "****"
          }],
        "is_fragile": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": false
          }],
        "number_of_items": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": 1
          }],
        "is_assembly_required": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": false
          }],
        "number_of_boxes": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": 1
          }],
        "part_number": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": ""
          }],
        "model_name": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "model_number": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": ""
          }],
        "item_shape": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "form_factor": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "included_components": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "cpsia_cautionary_statement": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "no_warning_applicable"
          }],
        "item_type_name": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "language_tag": "en_US",
            "value": ""
          }],
        "country_of_origin": [
          {
            "marketplace_id": "ATVPDKIKX0DER",
            "value": "US"
          }]
      }
    }
  ]
}

**Comment by github-project** [comment]
@stefnats request data {
"header": {
"sellerId": "",
"version": "2.0",
"issueLocale": "en_US"
},
"messages": [
{
"messageId": 9821,
"sku": "JYB3001FN128bHY",
"operationType": "UPDATE",
"productType": "CHAIR",
"requirements": "LISTING",
"attributes": {
"item_name": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "Upland 77" Long Reclining Single Chaise—JYB3001FN128bHY"
}],
"brand": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"item_type_keyword": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "dining-chairs"
}],
"item_type_name": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"country_of_origin": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "US"
}],
"product_description": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"bullet_point": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "This patio chaise lounge has a wide backrest, which can be adjusted to different positions according to your preference."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "This lounge chair is made of all-weather fabric and heavy-duty powder-coated steel frame, which ensures the weather resistance and durability for long term use. Besides, the extra support bars let it bear a maximum 300 pounds of load."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "Made of high-quality fabric, this recliner is skin-friendly and breathable, allowing you to enjoy the cool outdoors even in summer."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "The recliner is in a classical and stylish appearance, which is a great addition and adds a unique charm to your outside space. Furthermore, the lightweight design makes the chair easy to carry and move."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "With detailed instruction and all accessories included in the package, you can assemble this recliner in a short time effortlessly."
}],
"supplier_declared_dg_hz_regulation": [
{
"value": "not_applicable"
}],
"condition_type": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "new_new"
}],
"batteries_required": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": false
}],
"parentage_level": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "parent"
}],
"child_parent_sku_relationship": [
{
"marketplace_id": "ATVPDKIKX0DER",
"child_relationship_type": "variation"
}],
"variation_theme": [
{
"name": "SIZE"
}]
}
},
{
"messageId": 9831,
"sku": "D0102HH362G4sjSK",
"operationType": "UPDATE",
"productType": "CHAIR",
"requirements": "LISTING",
"attributes": {
"externally_assigned_product_identifier": [
{
"marketplace_id": "ATVPDKIKX0DER",
"type": "upc",
"value": "676351527994"
}],
"item_name": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "Upland 77" Long Reclining Single Chaise—JYB3001FN128bHY"
}],
"brand": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"item_type_keyword": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "dining-chairs"
}],
"purchasable_offer": [
{
"marketplace_id": "ATVPDKIKX0DER",
"currency": "USD",
"our_price": [
{
"schedule": [
{
"value_with_tax": 148.44
}]
}]
}],
"fulfillment_availability": [
{
"quantity": 0,
"fulfillment_channel_code": "DEFAULT",
"lead_time_to_ship_max_days": 3
}],
"item_weight": [
{
"marketplace_id": "ATVPDKIKX0DER",
"unit": "pounds",
"value": 31
}],
"item_depth_width_height": [
{
"marketplace_id": "ATVPDKIKX0DER",
"depth": {
"unit": "inches",
"value": 48
},
"width": {
"unit": "inches",
"value": 6.3
},
"height": {
"unit": "inches",
"value": 24
}
}],
"item_package_weight": [
{
"marketplace_id": "ATVPDKIKX0DER",
"unit": "pounds",
"value": 31
}],
"item_package_dimensions": [
{
"marketplace_id": "ATVPDKIKX0DER",
"height": {
"unit": "inches",
"value": 24
},
"length": {
"unit": "inches",
"value": 48
},
"width": {
"unit": "inches",
"value": 6.3
}
}],
"product_description": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"bullet_point": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "This patio chaise lounge has a wide backrest, which can be adjusted to different positions according to your preference."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "This lounge chair is made of all-weather fabric and heavy-duty powder-coated steel frame, which ensures the weather resistance and durability for long term use. Besides, the extra support bars let it bear a maximum 300 pounds of load."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "Made of high-quality fabric, this recliner is skin-friendly and breathable, allowing you to enjoy the cool outdoors even in summer."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "The recliner is in a classical and stylish appearance, which is a great addition and adds a unique charm to your outside space. Furthermore, the lightweight design makes the chair easy to carry and move."
},
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "With detailed instruction and all accessories included in the package, you can assemble this recliner in a short time effortlessly."
}],
"main_product_image_locator": [
{
"marketplace_id": "ATVPDKIKX0DER",
"media_location": "https://d2a59xdbgccpo7.cloudfront.net/dg-UOqNFeziCcVg/d0102heviy7.jpg"
}],
"supplier_declared_dg_hz_regulation": [
{
"value": "not_applicable"
}],
"condition_type": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "new_new"
}],
"parentage_level": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "child"
}],
"child_parent_sku_relationship": [
{
"marketplace_id": "ATVPDKIKX0DER",
"child_relationship_type": "variation",
"parent_sku": "JYB3001FN128bHY"
}],
"variation_theme": [
{
"name": "SIZE"
}],
"color": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": ""
}],
"size": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "natural"
}],
"style": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"material": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"seat": [
{
"language_tag": "en_US",
"back_interior_height": [
{
"value": 0,
"unit": "inches"
}],
"depth": [
{
"value": 0,
"unit": "inches"
}],
"height": [
{
"value": 0,
"unit": "inches"
}],
"length": [
{
"value": 0,
"unit": "inches"
}]
}],
"manufacturer": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": "***"
}],
"is_fragile": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": false
}],
"number_of_items": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": 1
}],
"is_assembly_required": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": false
}],
"number_of_boxes": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": 1
}],
"part_number": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": ""
}],
"model_name": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"model_number": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": ""
}],
"item_shape": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"form_factor": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"included_components": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"cpsia_cautionary_statement": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "no_warning_applicable"
}],
"item_type_name": [
{
"marketplace_id": "ATVPDKIKX0DER",
"language_tag": "en_US",
"value": ""
}],
"country_of_origin": [
{
"marketplace_id": "ATVPDKIKX0DER",
"value": "US"
}]
}
}
]
}
