### ISSUE TITLE
Not Getting Phone No and BuyerEmail details for Amazon orders

### ISSUE THREAD

**Issue by rajat-garg** [amzn/selling-partner-api-docs#1976]
Orders API is returning **anonymized email address** and **not returning the phone no** of buyer. We have got access for all three options (Tax remittance, Tax invoice, Direct-To-Consumer Shipping) and also checked all three in the application.
I am using postman client to send the request and using AWS Signature as header. (It automatically provides the Authorization AWS 4 signature for amazon). Here are the request details:

Request details:
GET https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/XXX-XXXXXXX-XXXXXXX/

Headers:
x-amz-access-token:  Atz.sprdt|******************

Response Body: 200 OK (Note: I have pasted only buyer related generic response and omitted the other fields)
{
    "payload": {
        "BuyerInfo": {
            "BuyerEmail": "xxxxxxxxxxxx@marketplace.amazon.de",
            "BuyerName": "XXX"
        },
        "AmazonOrderId": "XXX-XXXXXX-XXXXXX",
        "ShippingAddress": {
            "StateOrRegion": "XXXXXX",
            "AddressLine2": "XXXXXXX",
            "AddressLine1": "XXX XXXXXX",
            "PostalCode": "XXX",
            "City": "XXXXXX",
            "CountryCode": "XX",
            "AddressType": "XXXX",
            "Name": "Test Customer"
        },
    }
}

 As you see in the response Phone no is missing and email address is also anonymized. Is there any way to get these details or any other API call which we need to make. Can someone please look into this?

**Comment by cccaimingjian** [comment]
Maybe you should check this link. https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-authorization-to-access-pii-for-bulk-orders
