### ISSUE TITLE
'400 bad request' without error message in all of my calls to SP-API

### ISSUE THREAD

**Issue by CesarObedFL** [amzn/selling-partner-api-docs#1977]
i've opened [case 9541973211]

Obviouslly, i've forgot or missed something, but i don't know what...

i'm trying to connect to the sp-api with my php app, and i`ve already get the access_token and the refresh token, i sign my headers like the documentation says and i use cURL to tried to reach the api, but when i made any call i only get a 400 bad request response without any other message that could help me to resolve the problem...

i`ve tried the nexts uri`s and a lot of optionals parameters:

    /orders/v0/orders/702-0470549-1171452
    /orders/v0/orders?MarketplaceId=A1AM78C64UM0Y8
    /reports/2022-01-27/reports?reportTypes=OrderDate&MarketplaceId=A1AM78C64UM0Y8&createdSince=2022-01-01&createdUntil=2022-01-26

![Bad Request](https://user-images.githubusercontent.com/27329427/151422365-883fbb60-37ea-4b5c-9261-11ab9e696794.png)

i hope someone can help me

**Comment by lobotomisador** [comment]
@CesarObedFL you have not posted enough information for someone to determine what could be the cause of the Bad Request.

you need to post the complete headers Authorization header you are generating (make sure to cross out the credentials) https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

plus the other required parameters in the request such as the security and access tokens.

**Comment by CesarObedFL** [comment]
@lobotomisador Hi and thank you for your answer...
i don´t know why i'm getting the bad request response, but i solved the issue developing an concurrent api with node and the aws' sp-api sdk...
i guess the problem is in the signing process, that don't match with the aws signing, so the process of signing my request is doing by the sdk...
