### ISSUE TITLE
The Product Pricing endpoint fails for SKUs containing forward slashes

### ISSUE THREAD

**Issue by krupalpatel7877** [amzn/selling-partner-api-docs#1983]
I just tested GetMyFeesEstimateForASIN and GetMyFeesEstimateForSKU (both of which has SKU in the path) using SKU "LS22E45KDWV/XY" and still receive an error: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

**Comment by stefnats** [comment]
Seems like a duplicate of #1973 and #1637
I think there's no solution so far, but maybe open a ticket with developer support.
