### ISSUE TITLE
how to create sdk client all the API endpoints 

### ISSUE THREAD

**Issue by coder771** [amzn/selling-partner-api-docs#1993]
how to create 1 sdk client for all the API swagger models

**Comment by stefnats** [comment]
That's not possible. It's only one API client per API. However, you can write your own wrapper around these clients.

**Comment by coder771** [comment]
So i used swagger codegen and somehow created separate model folders for each api, I think i can do that to separate clients as well, but wondering if the classes in client folder for all api are same is it needed. can I not just use it to call all the api endpoints

![image](https://user-images.githubusercontent.com/17831597/152135358-1461479e-65dc-4064-bf3b-34a12ee9b556.png)
