### ISSUE TITLE
[FEATURE] Fetch ShipToAddress of an inbound shipment after creating it?

### ISSUE THREAD

**Issue by bjpierre** [amzn/selling-partner-api-docs#1994]
Hey, We're automating our FBA work flow.

If I'm missing it then please let me know, but it currently seems as though the only time the ShipToAddress of an API is ever exposed is when you create a shipment plan. This requires your app to bypass seller central, which is not ideal. We'd like to be able to have our team create an inbound shipment via SellerCentral, and then have automated systems create an internal work order, pick and ship them automatically. This whole flow works perfect, except as we aren't creating shipment plans with the CreateInboundShipmentPlan, but rather SellerCentral, we are unable to automatically fetch the request for these shipments.
 It would be ideal if this information could be added to the getShipments or getShipmentItemsbyShipmentId responses.
 
  I don't believe that this information falls under PII.

**Comment by uk-2** [comment]
Need to bit more on  "pick and ship automatically"

Wouldn't you just fit your sops around this ?

**Comment by bjpierre** [comment]
Yes, and we have, but it's not ideal to have to have someone go and manually input the address from seller central (ship to amazon) when the rest of the work flow is automated.

**Comment by Bowens20832** [comment]
I 2nd this feature as needed... The api only gives you a fulfillment center address when you create a shipment via the API... If a shipment is created inside Seller Central, you only get back the fulfillment center id, and not it's full address info.. There isn't any other endpoints for querying for FC addresses.
