### ISSUE TITLE
Order webhooks

### ISSUE THREAD

**Issue by buzali** [amzn/selling-partner-api-docs#2]
Do you support or plan to support webhooks?

It would be very useful to get notified about new orders via a webhook instead of having to pull orders data frequently.

**Comment by edaik** [comment]
We've heard a high amount of interest from customers for more event-driven push notifications, specifically for order status. This is on our roadmap and we're currently working on it. Stay tuned for more information.

Today we have an API ([Notifications.json](https://github.com/amzn/selling-partner-api-models/blob/main/models/notifications-api-model/notifications.json)) to subscribe to push notifications, including all those available in MWS. Here is the Notifications [API reference ](https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md). 

We will be posting a use case guide tutorial for the Notifications API soon as well.

**Comment by gregblass** [comment]
This is disappointing. After using such incredible API's such as Stripe, I figured a company as gigantic as Amazon would be a no brainer to have webhook support. We just want to know when an order was placed on amazon so we can keep track of it on our end. Aren't webhooks perfect for that?

**Comment by estroz** [comment]
Order notifications would be _really_ nice to have.

**Comment by JorisA-JT** [comment]
Is there already a webhook subscription for new orders?

**Comment by Syntaf** [comment]
Was this issue closed because it is no longer on Amazon's roadmap?

Completely agree with @gregblass , it's crazy to expect users to use polling with one of the largest sellers in the entire world. Platforms like Woo, BigCommerce, Shopify, Clover, and Square all support webhooks but Amazon does not?

I mean absolutely no disrespect to the developers on this project, but it's very disappointing to see how poor seller support is for Amazon marketplace apps.

**Comment by mjisaak** [comment]
Is this implemented now? Can we use the Notification API to subscribe on order events? What would be the correct `NotificationType`?

**Comment by Syntaf** [comment]
@mjisaak To my knowledge there are no event types offering for orders. You'll need to poll the orders API endpoint on a fixed schedule to retrieve past / new orders.

**Comment by mjisaak** [comment]
@Syntaf Thanks for the quick response. Do you know whether I can use the SP-API for that or do I have to use the old MWS? Maybe you can also tell me which API endpoints provide me that information as I am not aware of the APIs yet. BR

**Comment by Syntaf** [comment]
@mjisaak You should be able to use the SP-API orders reference to fetch orders, check the API docs in this repo to get specifics.

**Comment by chrisptang** [comment]
> This is disappointing.
> 
> After using top-tier API's like Stripe, I figured a company as gigantic and rich as Amazon would be a no brainer to have webhook support in their seller API...especially their most recent/updated version of their seller API.
> 
> We just want to know when an order was placed on amazon so we can keep track of it on our end. Aren't webhooks perfect for that? It seems like one of the most basic and core features that this API should focus on, is it not?
> 
> Asking users to use polling seems so ridiculously antiquated.

Actually they force us to use AWS SQS or Event Bridge with the so call [Notification API](https://github.com/amzn/selling-partner-api-models/blob/main/models/notifications-api-model/notifications.json). This is really disappointing.

**Comment by FloderCC** [comment]
> 
> 
> Is there already a webhook subscription for new orders? I really need it.

Please have someone found a solution?

**Comment by jakobowsky** [comment]
Isn't it what you are looking for:
1. Use case:  https://github.com/amzn/selling-partner-api-docs/blob/97de7c3fabf53d541572cd1f89a5efb6583df1f9/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#any_offer_changed
2. Schema: https://amazonservicesstatic.com/json-schemas/notifications/AnyOfferChangedNotification.json

**Comment by stefnats** [comment]
@jakobowsky I think the MFN_ORDER_STATUS_CHANGE type would be more suitable, because it's about orders and not offers.
Downside to that type is that only MFN orders are handled by that notification. I think Amazon wanted to fulfill the use case that a merchant can handle and fulfill their orders more quickly. That isn't needed by fba, because Amazon takes care of most time-critical things.

**Comment by ohabash** [comment]
Amazon Selling Partner API is the worst part of my job.

**Comment by eugene-kim** [comment]
> Great question. We've heard a high amount of interest from customers for more event-driven push notifications, specifically for order status. This is on our roadmap and we're currently working on it. Stay tuned for more information.
> 
> Today we have an API ([Notifications.json](https://github.com/amzn/selling-partner-api-models/blob/main/models/notifications-api-model/notifications.json)) to subscribe to push notifications, including all those available in MWS. Here is the Notifications [API reference ](https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md).
> 
> We will be posting a use case guide tutorial for the Notifications API soon as well.

@edaik are there any updates on this? It's almost been 2 years

**Comment by avvarga** [comment]
Hello all,

I would first like to thank you for your patience as I understand this is a long sought after improvement to the Selling Partner API and it took some time before it could be implemented.

That being said, I am glad to confirm that the [ORDER_STATUS_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#order_status_change) notification, joins the [MFN_ORDER_STATUS_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#mfn_order_status_change) and the [FULFILLMENT_ORDER_STATUS](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#fulfillment_order_status) notifications as of our [January 19th release](https://developer-docs.amazon.com/sp-api/changelog/january-2022-sp-api-release-1).

I have added links to the Notifications API Use-case-guides for each of the mentioned Notification Types and to the announcement that can be seen in our [new Documentation Website](https://developer-docs.amazon.com/sp-api/).

As this addresses the concern presented here, and this is a 2 year old issue, I am locking it. 

Thanks,
Alejandro C
Selling Partner API Developer Support
