### ISSUE TITLE
Vendor Oauth Flow - Error MD5100

### ISSUE THREAD

**Issue by jesusvalle** [amzn/selling-partner-api-docs#2001]
Hello,

These months we set up a SP application to link Sellers with our platform. Everything works correctly.

Now, we were trying to authorize vendor accounts, but when we generate the corresponding url (https://vendorcentral.amazon.es/apps/authorize/confirm/{my app id}), and accept from the vendor account the permissions, amazon returns us an error code **_MD5100_**.

By console, the error code returned is exactly the following:

**_{"messageCode":"INVALID_INPUT","errorMessage":"Invalid input from dependency:MarketplaceApplicationPermissionsService","messageProperties":{"MarketplaceApplicationPermissionsService":"Invalid application permission version id : amzn1.amds.permission.EUAmazon.b6bf3387-311a-3e90-d95a-c65e090faa4b"}}_**

What do we need to authorize vendor accounts, i'm missing something?

In addition, I have noticed that in the documentation, it is indicated that when registering an SP type application, 2 checkboxes should appear: one for seller, and another for vendor. But in my case they do not appear, is it normal?

I am using a pure SP API App (converted from an hybrid app)

Thank you so much.

**Comment by rugved1991** [comment]
Hi @jesusvalle,

Thanks for reaching out. Can you try adding "version=beta" parameter to your vendor authorization URL? For vendor authorizations you cannot used the published version as the published version of your app is only able to accept Seller Central authorizations. Once we have an AppStore for vendor central, you would be able to drop the "version=beta" parameter. But for now, you will have to add it to your OAuth URL while receiving authorization from vendors.

https://vendorcentral.amazon.es/apps/authorize/consent?application_id=your_app_id&version=beta

Let me know if this works. If you are still seeing an issue, I would request you to open up a support case and provide us the case ID here.

Rugved
Solutions Architect, SP API

**Comment by jesusvalle** [comment]
Good morning rugved, thanks for your reply.

When I did the tests I also tried with the parameter version=beta and it didn't work. In this case, the error message I receive from the console is the following:

errorMessage: "Invalid input from dependency:MarketplaceApplicationPermissionsService"
messageCode: "INVALID_INPUT"
messageProperties: {MarketplaceApplicationPermissionsService: "No roles found for permission set"}
MarketplaceApplicationPermissionsService: "No roles found for permission set"

I opened a support case more than a week ago, but unfortunately I have not received any response yet. (ID: 7598920832)

**Comment by kglowinski** [comment]
Hey there @rugved1991, is there any update on this? We're seeing the same issue (case ID: 9532279971)

**Comment by jesusvalle** [comment]
As for me, I still have no response to my case since I opened it on January 26th.

**Comment by rugved1991** [comment]
Hi @jesusvalle,

Can you confirm if you are able to see Vendor roles on your application once you click on "Edit App" button? If you have signed up as a public developer in your developer profile, you should be able to see a "Vendor" checkbox in your app settings. Once you enable this checkbox, you should be able to see Vendor roles which can be added to the application.
Please select these roles and reauthorize your application once you save and exit.
If you are unable to view the "Vendor" roles on your app settings, please open a support case and provide a screenshot of the app settings page.

Rugved
Solutions Architect, SP API

**Comment by jesusvalle** [comment]
Hello @rugved1991,

No, there are no such checks, I commented it at the beginning of the issue.

I will proceed to open a case.

**Comment by vaidas-lungis** [comment]
@jesusvalle Can you eloborate if you managed to solve your issue?

**Comment by jesusvalle** [comment]
> 
From the support I didn't get any answer to the problem.

Finally the solution was to edit my developer profile (without touching anything, just enter the section and click on save changes), and when I edited my app again, the checks appeared to enable the vendor permissions and process the change to be able to link them.
