### ISSUE TITLE
What are the changes for getOrders call after Aug 31 2021?

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-docs#2003]
Amazon stated last year:

> Additionally by August 31, 2021, we will launch an update to the Selling Partner API for Orders to return the required data based on your eligibility within a single call similar to MWS Orders API.

What are the changes?

The SP-API (before Aug 31, 2021) to get orders so that merchant can fill requires the following calls:

```
getOrders
getOrderBuyerInfo
getOrderAddress
getOrderItems
getOrderItemsBuyerInfo
```

If I have 100 orders, I will have:

```
getOrders (x1)
getOrderBuyerInfo (x100)
getOrderAddress (x100)
getOrderItems (x100)
getOrderItemsBuyerInfo (x100)
```

So total 401 calls.

So, what exactly was changed after Aug 31/2021, will the `getOrders` call return all the information (buyer information, shipping address, order item details) for merchant to fulfill the order?

Thanks

**Comment by nothinman** [comment]
...and on top of that you get the silly rate limits. while I do understand the limits are needed to prevent abuse, I do not understand why these API limits are so damn low. it's not that anyone can call the API. you need to exchange a lot of data before you're authorised to access the API. this should be nearly unlimited for own apps running on own set of credentials.

**Comment by vaidas-lungis** [comment]
Also count in the additional limits in case of restricted data tokens ;)
