### ISSUE TITLE
orders/v0 with CreatedBefore and CreatedAfter not working since yesterday

### ISSUE THREAD

**Issue by xbaha** [amzn/selling-partner-api-docs#2004]
I am trying to get orders here:

https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER&CreatedAfter=2022-02-02T14%3a44%3a52Z&CreatedBefore=2022-02-02T16%3a44%3a52Z

It has worked for the past 2 months, but suddenly since yesterday, I am getting the below error:
```
\n  \"errors\": [\n    {\n      
\"code\": \"InvalidInput\",\n      
\"message\": \"The input you have submitted is not valid. Please check your input and try again.\",\n      
\"details\": \"\"\n    }\n  ]\n}"  
```

Has anyone had a problem with this call and these parameters? 

If I remove CreatedBefore the call works ok.
I checked the computer time is synced, and my CreatedBefore > CreatedAfter
besides, this call used to work before and nothing has changed on my end.

**Comment by Mike-the-one** [comment]
@xbaha  I hope this is an error from your side. I am not even able to get orders, always return null.

**Comment by xbaha** [comment]
@Mike-the-one no I dought it, It worked for the past 2 months, and it's working now if I just removed CreatedBefore or CreatedAfter.

**Comment by Mike-the-one** [comment]
@xbaha thanks for letting me know

**Comment by kpconnell** [comment]
Check our CreatedAfter, make sure it's not super close to current time...  a few seconds difference between your computers time and AWS will cause this problem as it thinks you are setting the end date to sometime in the future.

**Comment by sixdimensionalarray** [comment]
I see exactly the same behavior as @xbaha, can confirm.  It seems like the only thing working for me is if I use CreatedAfter and CreatedBefore <= ( now - exactly 2 minutes ).

For example, assume today is 2/5/2022 01:30:00 UTC.  If I want to pull the orders created on the current day, up to now, I can pull successfully using only CreatedAfter=2022-02-05T00:00:00Z and CreatedBefore=2022-02-05T01:28:00Z (which is two minutes prior 1:30:00UTC).

I am not sure what this two minutes is about?

**Comment by xbaha** [comment]
@sixdimensionalarray It means NO FRESH DATA for you, only Amazon has this privilege.

**Comment by kpconnell** [comment]
> @sixdimensionalarray It means NO FRESH DATA for you, only Amazon has this privilege.

For FBM, you would use the notifications api for access to fresh orders.  For MCF, you created them, you should have them,  For FBA..   unlikely there is ever a real business need for very recent orders (at least that I can think of when thinking about their agreement with amazon).

**Comment by xbaha** [comment]
@kpconnell I disagree, There are many cases (including our core business) that need very recent orders, also, good luck with the notifications API if it really works!

**Comment by kpconnell** [comment]
> @kpconnell I disagree, There are many cases (including our core business) that need very recent orders, also, good luck with the notifications API if it really works!

Ok, I'm all ears.  Name one business action that is within the terms and conditions of Amazon you can take within five minutes of an order that would positively affect a seller's business performance on the platform.

**Comment by xbaha** [comment]
@kpconnell I can name a lot, but they go deep into different logics and this thread is not about this topic.

**Comment by gmacmaster-vft** [comment]
I'm still seeing this behavior. Any resolutions out there?
