### ISSUE TITLE
Roles may not be assumed by root accounts

### ISSUE THREAD

**Issue by TimoFedd** [amzn/selling-partner-api-docs#2005]
I followed the instruction to create an IAM user, role and policy (https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-2-create-an-iam-user) but i get the message "Roles may not be assumed by root accounts" from the API. Does anyone has an idea?

**Comment by TimoFedd** [comment]
Nevermind, i used the wrong credentials

**Comment by fonefun** [comment]
im getting same error any help
