### ISSUE TITLE
Handling problematic SKUS in createInboundShipmentPlan

### ISSUE THREAD

**Issue by jesusvalle** [amzn/selling-partner-api-docs#2012]
With the createInboundShipmentPlan call, when one of the products fails, the api returns an error message in string. So the problematic skus can't be handled correctly.

Is there any call by which the skus can be checked before trying to make the plan? I thought that with the getInboundGuidance call I could do it, but I have seen that it does not return any error with SKUS that do cause failures when creating the plan.

**Comment by uk-2** [comment]
You need to use [fba-inbound-eligibility-api](https://github.com/amzn/selling-partner-api-docs/tree/main/references/fba-inbound-eligibility-api)

This should give you any errors for a SKU

**Comment by jesusvalle** [comment]
> You need to use [fba-inbound-eligibility-api](https://github.com/amzn/selling-partner-api-docs/tree/main/references/fba-inbound-eligibility-api)
> 
> This should give you any errors for a SKU

Thank you very much, I had been looking into this call for a few days.

What I find disastrous is that it has a quota of only 1 call per second. I have customers with 500000 products per country. It will take a long time to complete.

**Comment by uk-2** [comment]
I guess they want it only called at the add to shipment plan ?

When do you plan to call this ?

We are implementing this call in our FBA shipment workflow only.

We have over 500 SKU's and plan to offer our app other customers later on
