### ISSUE TITLE
InvalidInput, Could not match input arguments or Unauthorized responce form Orders/Feed API

### ISSUE THREAD

**Issue by tgamushet** [amzn/selling-partner-api-docs#2013]
I am following this doc [selling-partner-api](https://developer-docs.amazon.com/sp-api/docs/what-is-the-selling-partner-api)

The manager has filled out his developer profile application, then from the root seller central account, he created (SELLER CENTRAL) account for me, I have the right to create API apps and view orders.

Then I used my Amazon account to access [amazon console](https://console.aws.amazon.com/iamv2/home?#/home) and proceed with steps in this  [creating-and-configuring-iam-policies-and-entities](https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities) guide.

Please note, these are TWO different accounts, one (1) an account where IAM user, role, and policy are created, (2) is where we have SP-API app created (the app uses IAM ARN role created with the account (1)).
In our case, we need [selfauthorized](https://developer-docs.amazon.com/sp-api/docs/self-authorization) [private vendor application](https://developer-docs.amazon.com/sp-api/docs/viewing-your-application-information-and-credentials) _"Private vendor applications. Vendor applications that are available only to your organization, and are self-authorized."_ That app will not be posted to the Amazon app store.
Complete steps that I did are:

1. Created IAM user (arn:aws:iam::XXXXXXXXX:user/<my-user>)
2. Created IAM policy (arn:aws:iam::XXXXXXXXX:policy/<execute-sp-api-policy>)
3. Created IAM role (arn:aws:iam::XXXXXXXXX:role/<execute-sp-api-role>)

As a result User (arn:aws:iam::XXXXXXXXX:user/<my-user>) has next inline policies

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}`
and
`{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": "sts:AssumeRole",
        "Resource": "arn:aws:iam::XXXXXXXXX:role/<execute-sp-api-role>"
    }
}`
4) Register and self authorized our application (VENDOR CENTRAL account
I followed [registering-your-application doc](https://developer-docs.amazon.com/sp-api/docs/registering-your-application)

_To register your application (for private vendor applications)
In the Integration menu, click API Integration.
The Developer Central page appears.
Click Add new app client.
The App registration page appears.
Complete the form._

**API TYPE: SP-API
ROLE FIELD: arn:aws:iam::XXXXXXXXX:role/<execute-sp-api-role>** 

In the Form, not all app roles checkboxes appear [list of roles](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api)

Roles that are available in our case: **Amazon Fulfilment** and **Brand Analytics** checked.
No, I will not delegate access to PII to another developer's application. checked
I then followed [self-authorization](https://developer-docs.amazon.com/sp-api/docs/self-authorization)

_To self-authorize your application (vendor application)
Sign in to Vendor Central using the credentials that you used to [register as a developer](https://developer-docs.amazon.com/sp-api/docs/self-authorization#registering-as-a-developer).
In the Integration menu, click API Integration.
The Developer Central page appears.
For the application that you want to authorize, click the arrow next to the Edit App button, and then click Authorize.
The Authorize application page appears.
Click Generate refresh token.
Your Login with Amazon (LWA) refresh token appears. If you click Generate refresh token again a new refresh token is generated. Generating a new refresh token does not invalidate previous refresh tokens._

Credentials we used:

- Refresh token step 6 in [self-authorize your application doc](https://developer-docs.amazon.com/sp-api/docs/self-authorization)
- lwa_app_id and lwa_client_secret  APP LWA Credentials that can be found at _Vendor Central page -> Integration -> API Integration -> LWA Credentials view button._
- aws_accsess_id, aws_access_key (arn:aws:iam::XXXXXXXX:user/<sp-api-user>) credentials
 
**Why does it have only two checkboxes?** 

There should be more roles according to the [roles-in-the-selling-partner-api](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api) 

**According to the Amazon support I need a "Direct-to-Consumer Shipping (Restricted)" role to make a request to the orders API.**

![image](https://user-images.githubusercontent.com/89845601/152541427-86aef35e-8f99-41e0-83f7-ead3bb89369f.png)

With my refresh_token I am able to call https://api.amazon.com/auth/o2/token to obtain my credentials to make API calls. 

I was also able to call https://sts.amazonaws.com?Version=2011-06-15&Action=AssumeRole&RoleSessionName=postmanSpApi&RoleArn=<my-arn-role>

And get my AccessKeyId, SecretAccessKey, SessionToken from XML responce.

when I call to /orders/v0/orders?MarketplaceIds=A1F83G8C2ARO7P
`[
    {
        "code": "InvalidInput",
        "message": "Could not match input arguments"
    }
]`

My exact calls are:

`curl --location --request GET 'https://sandbox.sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A1F83G8C2ARO7P' \
--header 'x-amz-access-token: <token received in responce to /auth/o2/token>' \
--header 'X-Amz-Security-Token: <SessionToken from STS AssumeRole endpoint>' \
--header 'X-Amz-Date: 20220204T140911Z' \
--header 'Authorization: AWS4-HMAC-SHA256 Credential=<AccessKeyId from STS AssumeRole endpoint>/20220204/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=<Signature calculated from AMZv4 Authorization>'`

Response is:

`[
    {
        "code": "InvalidInput",
        "message": "Could not match input arguments"
    }
]`

My Feeds call has a response:

`curl --location --request GET 'https://sandbox.sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/feed/?MarketplaceIds=A1F83G8C2ARO7P' \
--header 'x-amz-access-token:  <token received in responce to /auth/o2/token>' \
--header 'X-Amz-Security-Token: <SessionToken from STS AssumeRole endpoint>' \
--header 'X-Amz-Date: 20220204T142239Z' \
--header 'Authorization: AWS4-HMAC-SHA256 Credential=<AccessKeyId from STS AssumeRole endpoint>/20220204/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=<Signature calculated from AMZv4 Authorization>'`

`{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}`

I have read a lot of issues and amazon docs before posting this question, I know it happens with other people too, but I had no luck with figuring out what I am doing wrong by myself. Any suggestions why I am getting these responses from API?

I also opened a support ticket and shared there a request id and some other info that is helpful to debug. I will post an answer if I find it.

**Comment by AlexioDanje** [comment]
I am having the same issue with the create Shipment API, can someone help please

**Comment by franciscocha** [comment]
I think you have the steps confused. If you are providing this app for a client you aren't allowed to self authorize it. This is stated at the top of https://developer-docs.amazon.com/sp-api/docs/self-authorization.  

> When you create a private application for your own organization you can self authorize it to access your account information

**Comment by tgamushet** [comment]
@franciscocha I am sorry to confuse you, I meant the manager from the seller department (the same organization), we want to restrict managers and devs, so each one can do their part of the work only. I don't need to have access to the root account and they don't have a need to create or see app creds. That's why I asked to feel in the developers form from the root account and then I was granted access to the account with the API Integration role. 

Anyway, I opened an Amazon support ticket and they said that I need to proceed with the following steps: 

_Go to the vendor central account with the account that I used to fill in the developers' profile (root one). Then Integration -> API Integration. Choose your app from the list. Click Edit App and check the checkbox with  "Direct-to-Consumer Shipping (Restricted)". Press save and exit._ 

I'd like to state to anyone who has the same problem that there is no such a checkbox. So it's a bug in the documentation or in the frontend part of a vendor central (checkbox does not appear). I will post the solution if a find it here.

**Comment by franciscocha** [comment]
@tgamushet I believe the issue lies on your relationship with Amazon. Amazon has a specific definition for vedors and sellers which one are you?

> Seller. A seller lists and sells their own goods on Amazon's retail website. After an item is sold, it is either (1) directly fulfilled by the seller using inventory managed by the seller, or (2) fulfilled through the Fulfillment by Amazon (FBA) program, using the seller's FBA inventory.
> 
> Vendor. A vendor supplies the inventory that is sold by Amazon on Amazon's retail website. There are two main types of vendors: Retail procurement vendors and Direct fulfillment vendors.

**Comment by tgamushet** [comment]
@franciscocha The company has registered a vendor account, It sells directly to amazon, so I believe Amazon identifies this account as a vendor one.

**Comment by tgamushet** [comment]
@franciscocha Direct fulfillment

**Comment by tgamushet** [comment]
@AlexioDanje Were you able to get any orders in the first place?

**Comment by tgamushet** [comment]
So I managed to get help from support, turns out I was using the wrong URL, I had to use https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-orders-api-v1-reference#get-vendordirectfulfillmentordersv1purchaseorders 

This works fine.

**Comment by aglehg** [comment]
v1 I meant /vendor/directFulfillment/orders/v1/purchaseOrders.

You are correct, for the live version. But in my comment the url is for the sandbox. In the sandbox, for the  /orders/v0/orders endpoint,  the CreatedAfter is that string  :) 

If you check the documentation for the model and search for x-amzn-api-sandbox, you'll find a list of arguments for the endpoint. Sandbox arguments do NOT necessarily respect the documented format for the live version. Could not find docs on why they are what they are, or what options you have apart from that list of arguments in the model. If anyone knows.. certainly will make everyone's life easier to have better docs.

**Comment by franciscocha** [comment]
@aglehg orders and vendor direct fulfillment are 2 very different things.

I'm assuming that the devs chose not to use an actual date as to not cause confusion if the API isn't changed for a very long time. Since there is a point when orders do get archived and they will no longer be available. Or else the test endpoint would imply all order would be available via the endpoint.

**Comment by luckdragon** [comment]
in my case, if I send the query to production it works fine, but I get this same error when sending to sandbox, so either sandbox isn't the same code (i.e. expecting the same parameters), or something else is different with it

**Comment by franciscocha** [comment]
@luckdragon Not sure if this is what you are doing but you have to make sure you use the exact parameters identified in the json files for sandbox calls. You can't just use the same production call in sandbox and expect it to work.

**Comment by luckdragon** [comment]
thank you for saying that, I didn't know there were different parameters
for the sandbox, because, I mean, why would you want the production and
sandbox environments to work the same way, right?

**Comment by franciscocha** [comment]
Yeah the sandbox call unfortunately only cover very specific case. Still at least there is a sandbox.

**Comment by tarekrahme** [comment]
Hello
@aglehg What do you mean by format being TEST_CASE_200 for the CreatedAt?
I am getting the `Could not match input arguments` error 
```
performed EASY effective_url=https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=A1AM78C64UM0Y8%2CATVPDKIKX0DER&CreatedAfter=2023-03-20T17%3A50%3A53 response_code=400 return_code=ok total_time=0.345002
```

**Comment by franciscocha** [comment]
@tarekrahme if you look at the json model for the sandbox the value for CreatedAfter has to be TEST_CASE_200 and the MarketplaceIds value has to be ATVPDKIKX0DER for the sandbox to return values.

https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json#L274-L288

**Comment by tarekrahme** [comment]
@franciscocha thank you so so much!
