### ISSUE TITLE
Canonical Request using Python

### ISSUE THREAD

**Issue by ElStraussos** [amzn/selling-partner-api-docs#202]
Hi SP-API Community,
i experience problems creating the Authorization part of the API-Call using Python. I can exclude any other problems than the AWS4 Signature because when i use the internal AWS Signature module of Postman i receive the requested data from the API.
I am using STS, so i receive an AccessKeyId, a SecretAccessKey and a Session Token/Security Token.
The API GET request should go to the following path: 

https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A1PA6795UKMFR9&CreatedAfter=2020-05-10

Thanks for you help in advance!

**Code for AWS4 Signature**

`import sys, os, base64, datetime, hashlib, hmac, urllib
import requests # pip install requests

method = 'GET'
service = 'execute-api'
host = 'sellingpartnerapi-eu.amazon.com'
region = 'eu-west-1'
endpoint = 'https://sellingpartnerapi-eu.amazon.com'

def sign(key, msg):
    return hmac.new(key, msg.encode('utf-8'), hashlib.sha256).digest()

def getSignatureKey(key, dateStamp, regionName, serviceName):
    kDate = sign(('AWS4' + key).encode('utf-8'), dateStamp)
    kRegion = sign(kDate, regionName)
    kService = sign(kRegion, serviceName)
    kSigning = sign(kService, 'aws4_request')
    return kSigning

access_key = AccessKeyId
secret_key = SecretAccessKey
if access_key is None or secret_key is None:
    print('No access key is available.')
    sys.exit()

t = datetime.datetime.utcnow()
amz_date = t.strftime('%Y%m%dT%H%M%SZ') # Format date as YYYYMMDD'T'HHMMSS'Z'
datestamp = t.strftime('%Y%m%d') # Date w/o time, used in credential scope

canonical_uri = '/orders/v0/orders' 

canonical_headers = 'host:' + host + '\n' + 'x-amz-date:' + amz_date + '\n'
signed_headers = 'host;x-amz-date;x-amz-security-token'

algorithm = 'AWS4-HMAC-SHA256'
credential_scope = datestamp + '/' + region + '/' + service + '/' + 'aws4_request'

canonical_querystring = 'MarketplaceIds=A1PA6795UKMFR9&CreatedAfter=2020-05-10'
canonical_querystring += '&X-Amz-Algorithm=AWS4-HMAC-SHA256'
canonical_querystring += '&X-Amz-Security-Token=' + SessionToken
canonical_querystring += '&X-Amz-Credential=' + urllib.parse.quote_plus(access_key + '/' + credential_scope)
canonical_querystring += '&X-Amz-Date=' + amz_date
canonical_querystring += '&X-Amz-Expires=30'
canonical_querystring += '&X-Amz-SignedHeaders=' + signed_headers

payload_hash = hashlib.sha256(('').encode('utf-8')).hexdigest()

canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash

string_to_sign = algorithm + '\n' +  amz_date + '\n' +  credential_scope + '\n' +  hashlib.sha256(canonical_request.encode('utf-8')).hexdigest()

signing_key = getSignatureKey(secret_key, datestamp, region, service)

signature = hmac.new(signing_key, (string_to_sign).encode("utf-8"), hashlib.sha256).hexdigest()

authorization_header = algorithm + ' ' + 'Credential=' + access_key + '/' + credential_scope + ', ' +  'SignedHeaders=' + signed_headers + ', ' + 'Signature=' + signature

headers = {'x-amz-date':amz_date, 'Authorization':authorization_header, 'x-amz-access-token': access_token, 'X-Amz-Security-Token': SessionToken}

request_url = endpoint + '?' + canonical_querystring

print('\nBEGIN REQUEST++++++++++++++++++++++++++++++++++++')
print('Request URL = ' + request_url)
r = requests.get(request_url, headers=headers, data = payload)

print('\nRESPONSE++++++++++++++++++++++++++++++++++++')
print('Response code: %d\n' % r.status_code)
print(r.text)

print(authorization_header)`

**Comment by KevinJ1978** [comment]
What is the reponse code you are getting?   If you are receiving a 500 server error code, this is what I am currently getting only for GET requests.  If it's 403 and you have a signature problem, it will tell you in the reponse.

**Comment by ElStraussos** [comment]
Hi Kevin, thans for your response! At the moment I am getting an "400 Invalid Input", so i guess there is still a problem with that canonical request. I thought maybe someone could provide an exemplary code to create the  authorization in Python using the Selling Partner API, so we could figure things out. Will keep this thread updatet once i find a working solution and would be greatful for further contribution about this topic!
Flo

**Comment by rogersv** [comment]
It looks like you are mixing two different approaches from https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html
I would suggest that you put the x-amz-... variables in the header only. Also use lowercase for the header names. I know the documentation says it should work with uppercase but it seems that lowercase is required.

This python example https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html is not completely correct. Note the comments in the code. It says that query parameters should be sorted and url-encoded BUT it is not a standard url-encoder see https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

**Comment by ElStraussos** [comment]
Hi Guys, thanks for your responses. I took a different approach that actually worked in terms of signing the request. I used the AWSRequestsAuth Module. Now i get my orders in JSON Format :)

**Here is the Python code:**
`from aws_requests_auth.aws_auth import AWSRequestsAuth

auth = AWSRequestsAuth(aws_access_key=AccessKeyId,
                       aws_secret_access_key=SecretAccessKey,
                       aws_token=SessionToken,
                       aws_host='sellingpartnerapi-eu.amazon.com',
                       aws_region='eu-west-1',
                       aws_service='execute-api')


endpoint = 'https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A1PA6795UKMFR9&CreatedAfter=2020-05-10'

headers = {'x-amz-access-token': access_token} 

r = requests.get(endpoint, auth=auth, headers=headers)`

**Comment by rakeshsivaji** [comment]
@ElStraussos  can you share the python code you used to get the STS response temperorary credentials, I am facing issue in it

**Comment by ElStraussos** [comment]
Hey,
thanks for your question!
This is how i retrieve my temporary credentials: 

1. Make sure to get the settings in the AWS Management Console right according to the Selling Partner API (here i had most of my problems because i didn't read it properly :D)

2. This is my Python Code:
3. 
import boto3

#Register AmazonClient, you could or rather should save your keys in the boto3 environments, however this works too
AMZ_Client = boto3.client('sts', aws_access_key_id = 'AKI...', aws_secret_access_key = 'QP....', region_name = 'eu-west-1')

#Assume Role and get temporary Keys and Session Token
res = AMZ_Client.assume_role(
    RoleArn='arn:aws:iam::022:role/AWS_SellerAPI',
    RoleSessionName='SellingPartnerAPI'
)
Credentials = res["Credentials"]
AccessKeyId = Credentials["AccessKeyId"]
SecretAccessKey = Credentials["SecretAccessKey"]
SessionToken = Credentials["SessionToken"]

Best regards,
Florian

**Comment by rakeshsivaji** [comment]
@ElStraussos  thank you, one more doubt, I have created a seller central account as a developer and tested  and executed, by same way is it possible to create vendor central account  as a developer

**Comment by KevinJ1978** [comment]
In my experience, you need to be invited to join Vendor Central.  So whoever currently maintains the Vendor Central account you require access to will send an invite.  You then link your Seller Central account with Venor one, and then follow the instructions in the API documentation available under Integration / API Integration.

**Comment by nuvoretail-developer** [comment]
import sys, os, base64, datetime, hashlib, hmac, urllib
from collections import OrderedDict
import requests

method = 'GET'
service = 'execute-api'
host = 'sellingpartnerapi-eu.amazon.com'
region = 'eu-west-1'
endpoint='https://sellingpartnerapi-na.amazon.com'
access_key = 'XXX'
secret_key = 'YYY'



def sign(key, msg):
    return hmac.new(key, msg.encode('utf-8'), hashlib.sha256).digest()

def getSignatureKey(key, dateStamp, regionName, serviceName):
    kDate = sign(('AWS4' + key).encode('utf-8'), dateStamp)
    kRegion = sign(kDate, regionName)
    kService = sign(kRegion, serviceName)
    kSigning = sign(kService, 'aws4_request')
    return kSigning


t = datetime.datetime.utcnow()
amz_date = t.strftime('%Y%m%dT%H%M%SZ') 
datestamp = t.strftime('%Y%m%d')



canonical_uri = '/orders/v0/orders'



headers_to_sign = {'host': host, 'x-amz-date': amz_date,'content-type':'application/x-www-form-urlencoded; charset=utf-8'}

ordered_headers = OrderedDict(sorted(headers_to_sign.items(), key=lambda t: t[0]))


canonical_headers = ''.join(map(lambda h: ":".join(h) + '\n', ordered_headers.items()))

signed_headers = ';'.join(ordered_headers.keys())



algorithm = 'AWS4-HMAC-SHA256'
credential_scope = datestamp + '/' + region + '/' + service + '/' + 'aws4_request'


canonical_querystring = 'MarketplaceIds=A21TJRUUN4KGV&CreatedAfter=2019-05-10'


payload_hash = hashlib.sha256(('').encode('utf-8')).hexdigest()


canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash


string_to_sign = algorithm + '\n' +  amz_date + '\n' +  credential_scope + '\n' +  hashlib.sha256(canonical_request.encode('utf-8')).hexdigest()


signing_key = getSignatureKey(secret_key, datestamp, region, service)


signature = hmac.new(signing_key, (string_to_sign).encode("utf-8"), hashlib.sha256).hexdigest()



request_url = endpoint + '?' + canonical_querystring

authorization_header = "AWS4-HMAC-SHA256 Credential={}/{}, SignedHeaders={}, Signature={}".format(access_key, credential_scope, signed_headers, signature)

headers = {
    
    
    "user-agent": "MyAmazonApp/1.0 (Language=Python; Platform=Windows/10)",
    'x-amz-access-token': f'{access_token}',
    'host': host,
    'x-amz-date': amz_date,
    'x-amz-security-token':'YYY',
    'Authorization': authorization_header
    
}

response = requests.get(request_url, headers=headers)


print(response)

After implementing the above steps, i am getting "<Response [403]>
{'message': 'Forbidden'}"
please help me out.. 
if i am doing anything wrong please let me now..
thanks a lot in advance!!!!

**Comment by rogersv** [comment]
@nuvoretail-developer 
Host and endpoint are for two different regions (eu and na). That is probably the cause. The other parts looks correct.

**Comment by nuvoretail-developer** [comment]
@rogersv thanks for the help. it means lot. 
still i am getting and error.. 
and could you please tell me what is session token ?
"X-Amz-Security-Token' : "SessionToken"
i have known to three keys which are being used here in my code.. access_key, secret_key and access_token, and everyone used SessionTokenin their code.

**Comment by rogersv** [comment]
@nuvoretail-developer you will get the session-token from the sts assume role response. The assume role will give you a new key and secret too.

**Comment by nuvoretail-developer** [comment]
@rogersv thanxx a lot. it really means a lot

**Comment by nuvoretail-developer** [comment]
@rogersv As you said, i have performed the steps.. and this time i am getting different error.
it shows like this...[
![Annotation 2021-03-20 121516](https://user-images.githubusercontent.com/80046831/111861681-30a1fa00-8976-11eb-8d40-4fb562b01da8.png)
](url)

**Comment by rogersv** [comment]
@nuvoretail-developer I do not know why you get a 500 but the headers that you send is incorrect. You need to add all required headers.

You should see a "SignedHeaders" part in the auth if you print it. These headers needs to be add to the request.

**Comment by nuvoretail-developer** [comment]
@rogersv please have a look at this code..  i have added the "SignedHeaders" as per your last response but still facing the same error in both of codes...
method = 'GET'
service = 'execute-api'
host = 'sellingpartnerapi-eu.amazon.com'
region = 'eu-west-1'
endpoint='https://sellingpartnerapi-eu.amazon.com'

access_key=AccessKeyId
secret_key=SecretAccessKey



def sign(key, msg):
    return hmac.new(key, msg.encode('utf-8'), hashlib.sha256).digest()

def getSignatureKey(key, dateStamp, regionName, serviceName):
    kDate = sign(('AWS4' + key).encode('utf-8'), dateStamp)
    kRegion = sign(kDate, regionName)
    kService = sign(kRegion, serviceName)
    kSigning = sign(kService, 'aws4_request')
    return kSigning


t = datetime.datetime.utcnow()
amz_date = t.strftime('%Y%m%dT%H%M%SZ') 
datestamp = t.strftime('%Y%m%d')



canonical_uri = '/sellers/v1/marketplaceParticipations'



headers_to_sign = {'host': host, 'x-amz-date': amz_date}

ordered_headers = OrderedDict(sorted(headers_to_sign.items(), key=lambda t: t[0]))


canonical_headers = ''.join(map(lambda h: ":".join(h) + '\n', ordered_headers.items()))

signed_headers = ';'.join(ordered_headers.keys())



algorithm = 'AWS4-HMAC-SHA256'
credential_scope = datestamp + '/' + region + '/' + service + '/' + 'aws4_request'


canonical_querystring = 'MarketplaceIds=A21TJRUUN4KGV'


payload_hash = hashlib.sha256(('').encode('utf-8')).hexdigest()


canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash


string_to_sign = algorithm + '\n' +  amz_date + '\n' +  credential_scope + '\n' +  hashlib.sha256(canonical_request.encode('utf-8')).hexdigest()


signing_key = getSignatureKey(secret_key, datestamp, region, service)


signature = hmac.new(signing_key, (string_to_sign).encode("utf-8"), hashlib.sha256).hexdigest()



request_url = endpoint + '/sellers/v1/marketplaceParticipations'+'?' + canonical_querystring

authorization_header = "AWS4-HMAC-SHA256 Credential={}/{}, SignedHeaders={}, Signature={}".format(access_key, credential_scope, signed_headers, signature)

headers = {
    
    
    "user-agent": "MyAmazonApp/1.0 (Language=Python; Platform=Windows/10)",
    'x-amz-access-token': f'{access_token}',
    'host': host,
    'x-amz-date': amz_date,
    'x-amz-security-token':SessionToken,
    'authorization': authorization_header
    
}

response = requests.get(request_url, headers=headers)


print(response.text)


![image](https://user-images.githubusercontent.com/80046831/111862813-bc6b5480-897d-11eb-85c7-9620a67c122e.png)

**Comment by rogersv** [comment]
@nuvoretail-developer I meant the headers that you sign needs to be in the actual header. Just like your first example.



> headers = {
> 
> "user-agent": "MyAmazonApp/1.0 (Language=Python; Platform=Windows/10)",
> 'x-amz-access-token': f'{access_token}',
> 'host': host,
> 'x-amz-date': amz_date,
> 'x-amz-security-token':SessionToken,
> 'authorization': authorization_header
> }

**Comment by nuvoretail-developer** [comment]
thanks a lot
but again i am getting the same error
![image](https://user-images.githubusercontent.com/80046831/111862999-c477c400-897e-11eb-866e-fdc42a87ec3e.png)

**Comment by nuvoretail-developer** [comment]
@rogersv if you have sample code or something like that could you share it

**Comment by PrashantMalaviya** [comment]
run this code ....optput is geting this repiting

from aws_requests_auth.aws_auth import AWSRequestsAuth
import requests
import boto3
from time import sleep
header = {
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
}
d = {
    "grant_type": "client_credentials",
    "scope": "sellingpartnerapi::notifications",
    "refresh_token": xxxx,
    "client_id": xxxx,
    "client_secret": xxxx,
}
response = requests.post("https://api.amazon.com/auth/o2/token", headers=header, data=d)
print(response.status_code)
data = response.json()
access_token = data['access_token']
print("access_token:-",access_token)
##############################################
sleep(2)
amw_client = boto3.client(
    'sts',
    aws_access_key_id=xxxx,
    aws_secret_access_key=xxxx,
)
response = amw_client.assume_role(
    RoleArn=xxxx,
    RoleSessionName='SellingPartnerAPI'
)
AccessKeyId = response['Credentials']['AccessKeyId']
SecretAccessKey = response['Credentials']['SecretAccessKey']
SessionToken = response['Credentials']['SessionToken']
print("AccessKeyId:-",response['Credentials']['AccessKeyId'])
print("SecretAccessKey:-",response['Credentials']['SecretAccessKey'])
print("SessionToken:-",response['Credentials']['SessionToken'])
##############################################################################
sleep(2)
auth = AWSRequestsAuth(aws_access_key=AccessKeyId,
    aws_secret_access_key=SecretAccessKey,
    aws_token=SessionToken,
    aws_host='sellingpartnerapi-eu.amazon.com',
    aws_region='eu-west-1',
    aws_service='execute-api')

endpoint = 'https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A21TJRUUN4KGV&CreatedAfter=2021-01-05'

headers = {'x-amz-access-token': access_token}

r = requests.get(endpoint, auth=auth, headers=headers)
print(r.status_code)
print(r.text)

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
my output is :-
200
access_token:-xxxx

AccessKeyId:- xxxx
SecretAccessKey:- xxxx
SessionToken:- xxxx
403
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by Shahzeb42Digital** [comment]
> What is the reponse code you are getting? If you are receiving a 500 server error code, this is what I am currently getting only for GET requests. If it's 403 and you have a signature problem, it will tell you in the reponse.
> 
> Also I believe you need to add the x-amz-access-token, and x-amz-security-token to the canonical and signed headers.

Hello. I have same problem and I am getting rosponse code 401. It could be possible for you to help me?
