### ISSUE TITLE
[QUESTION] Order Billing Adress

### ISSUE THREAD

**Issue by kevinvenclovas** [amzn/selling-partner-api-docs#2020]
Hi,

where can i find the order billing adress. Currently we create our invoices with the shipping address but this is in some cases not very useful.

Is there an Report or somethink were i can get the billing adress from orders?

Thanks
Kevin

**Comment by kevinvenclovas** [comment]
Someone can help me?

**Comment by stefnats** [comment]
I think you need access to PII which you can request with developer support

**Comment by maltunok** [comment]
Order API PII also does not provide invoice info I guessi you shoud use report Api

**Comment by Johnny99211** [comment]
@maltunok how? I can not see any way to get the billing address there...
