### ISSUE TITLE
Error Code: MD5100 application without publishing it as public

### ISSUE THREAD

**Issue by vbled** [amzn/selling-partner-api-docs#2021]
Something went wrong
We are sorry but we encountered an error while processing your request.

Please contact Selling Partner Support and provide them with the following information:

App ID: amzn1.sp.solution.05a2fc47-6971-4c84-8f4c-0a6a55f6a720

Error Code: MD5100

**Comment by sungolivia** [comment]
Hey @vbled not sure if you are still running into this issue, but there is a [blog](https://developer-docs.amazon.com/sp-api-blog/docs/troubleshooting-selling-partner-api-authorization-errors) troubleshooting authorization errors and [error FAQ](https://developer-docs.amazon.com/sp-api/page/sp-api-errors-frequently-asked-questions)!
