### ISSUE TITLE
Inbound fulfilment Prep Instructions bug 

### ISSUE THREAD

**Issue by uk-2** [amzn/selling-partner-api-docs#2025]
Hi
We are having issues with inbound fulfilment, we trying to send prep instructions for a shipment plan .  

Issue for PrepInstruction field:

For API POST /fba/inbound/v0/plans
We create JSON:
{  
"ShipFromAddress": {
  "Name": company_name,
  "AddressLine1": office_address,
  "City": company_city,
  "StateOrProvinceCode": company_state_or_province_code,
  "CountryCode": "GB",
  "PostalCode": company_postal_code
},
"LabelPrepPreference": "SELLER_LABEL",
"InboundShipmentPlanRequestItems": [
  "SellerSKU": "my_sku",
  "ASIN": "my_asin",
  "Condition": "NewItem",
  "Quantity": 2,
  "PrepDetailsList": [
    {
      "PrepOwner": "AMAZON",
      "PrepInstruction": "Labeling",
    },
 ]
]
}
**Above code works well But if I try to set this point:**

"PrepDetailsList": [
  {
    "PrepOwner": "AMAZON",
    "PrepInstruction": "Taping", **#or any other it doesn't work**
  },
]

"code": "InvalidInput",
"message": "This operation may be partially successful, Please check the status. Reason: [Incorrect PrepInstruction provided. Please call GetPrepInstructionsForSKU operation to determine required PrepInstruction for your SKUs. Corresponding items for the error: [[FNSKU: 'my_fnsku', MSKU: my_sku]]].",
      "details": ""

**When i use prepInstructions API operation for this SKU it returns only**
"PrepInstructionList"=>["Labeling"] bot not any other (Polybagging, Taping, BubbleWrapping etc)

**How I can use other PrepInstruction different then 'Labeling'?**

What we are trying to do is allow the user to choose prep owner and then select prep services for SKU .

@ShivikaK @parvathm
@cpiggott @CarlosSiles21

Thank you for  your help

**Comment by uk-2** [comment]
@chapmanjw

**Comment by chapmanjw** [comment]
@uk-2 This is outside of my wheelhouse. I would recommend contacting Developer Support.

**Comment by cpiggott** [comment]
I'm unsure here as well @uk-2 

We so all prep in-house, so hopefully Amazon support can help

**Comment by mikhaill** [comment]
@uk-2 Did you ever figure out the solution the problem? Hitting same roadblock and can't find anything.

**Comment by uk-2** [comment]
no we gave up on prep since we dont use amazon for prep
but our shipment flow in our app is pretty faster

**Comment by mikhaill** [comment]
Thanks @uk-2 . After some more headbanging we got it figured out.

**Comment by paulo2703** [comment]
@mikhaill Could you briefly share your findings pls?
