### ISSUE TITLE
[BUG] Removal Orders do not appear in Selling Partner API for Orders getOrders Method 

### ISSUE THREAD

**Issue by CelestePerez** [amzn/selling-partner-api-docs#2027]
We are currently requesting orders with the getOrders method and filtering by CreatedAfter / CreatedBefore or LastUpdatedAfter / LastUpdatedBefore for the Amazon US Marketplace.

We have removal orders that correspond to the dates that we are filtering and these orders do not come in the response. 

This is what we see in Amazon Sellers Central:
![image (23)](https://user-images.githubusercontent.com/56774509/153220967-e558c3f5-1cb2-41ed-bb5b-aa561d7fc254.png)

We are requesting with these parameters and those orders are not coming in the response.
{
    MarketplaceIds: ['ATVPDKIKX0DER'],
    MaxResultsPerPage: 100,
    CreatedAfter : '2022-02-02T00:00:00Z'
    CreatedBefore : '2022-02-07T18:52:11Z'
}

Request ID for this call was: 

'x-amzn-requestid': '8ce12c16-5ab4-490b-ae51-38e78d299171',
'x-amzn-trace-id': 'Root=1-6203d5bb-142352b0038b667d0a22a9db'
{
    MarketplaceIds: ['ATVPDKIKX0DER'],
    MaxResultsPerPage: 100,
    LastUpdatedAfter : '2022-02-02T00:00:00Z'
    LastUpdatedBefore : '2022-02-07T18:52:11Z'
}

Request IDs for this call are:
'x-amzn-requestid': 'e2dbba0c-b596-4a5b-a024-53548575dd94',
'x-amzn-trace-id': 'Root=1-6203d611-1926f53f58bbd2a3227518ee'

**Comment by puppsupr** [comment]
Hi, 

If you are still facing this issue, can you please open a [support case](https://developer.amazonservices.com/support) so we can pursue the investigation.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
