### ISSUE TITLE
[BUG] Documentation - getOrderBuyerInfo depreciation date and expected GetOrders behaviour

### ISSUE THREAD

**Issue by IgniteMosquito** [amzn/selling-partner-api-docs#2031]
Based on this documentation: https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#getorderbuyerinfo, the endpoint should be depreciated last month. Although, I see it is still live, and the getOrders endpoint (BuyerInfo object) is null, while getOrderBuyerInfo gives us the data.
To be clear, we do not have PII, but we can still retrieve the @marketplace.amazon.xxx buyer email from the "soon-to-be-depreciated" endpoint.

Do you know if there are any changes in dates? We want to build the final integration, but we also don't want to use something that will be depreciated.

Apologies if it has been mentioned somewhere, but I wasn't able to find any related issue.

**Comment by bpyzikvc** [comment]
@IgniteMosquito A depricated endpoint means that it will still work but will no longer be supported or updated. 
You COULD continue to use it but I would suggest taking advantage of the newest update for Get Orders that returns buyer info in the same call. What you need to do to make the buyerinfo object not null is to use a restricted data token generated with the following info.

`'{
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/orders/v0/orders",
      "dataElements": ["buyerInfo", "shippingAddress"]
    },
    {
      "method": "GET",
      "path": "/orders/v0/orders/{orderId}/orderItems",
      "dataElements": ["buyerInfo"]
    }
  ]
}'`

If you use a restricted data token in place of the access token for get orders and get order items you will get the same amount of info that used to take 5 full api calls. Good luck!
