### ISSUE TITLE
running java application with {"field":"invalid_grant","message":"The request has an invalid grant parameter : code"}

### ISSUE THREAD

**Issue by nickjinxn** [amzn/selling-partner-api-docs#2035]
Hi,
I am trying to  exchange the LWA authorization code for a LWA refresh token by java application.  There was an error message that "The request has an invalid grant parameter : code" to me.   This message is only happens in the EKS container。 If I move the application to EKS host to run, it works well and I can get refresh token.  Same machine one is running container and one is running host. Does any one can help me? Thank you.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/10817245/153513357-f9fa1d52-0b2d-40f7-aee3-2afe7dc1cefe.png">

**Comment by rohitdobariya** [comment]
Hi, @nickjinxn Let's connect and resolve your issues. drop me an email rohitavira@gmail.com

**Comment by nickjinxn** [comment]
sorry for my mistake
