### ISSUE TITLE
We have blocked the ability of your MWS & SP-API account from accepting new seller authorizations

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#2038]
Context: we have developed a private application for a client _(an agency that works with sellers)_.

They have received the following email:

> You have indicated that your application is used internally only and not intended to be used by other Amazon Sellers and you haven't showed any desire to list your application in the Amazon Seller Central Partner Network and, we have blocked the ability of your MWS & SP-API account (Merchant ID: ....) from accepting new seller authorizations. 

This makes no sense.

Why would an agency need to list their **private** application in a public app store?

If anything, this would have the opposite effect. If a random seller gets confused and authorizes their seller account, our client would accidentally get the data from some _random_ seller, who isn't their client.

And don't tell me this doesn't happen, because I know for a fact that it does by someone elses' account.

Your policies are backwards and need to be revised ASAP.

**Comment by uk-2** [comment]
Internal apps have different set of rules to adhere to .

Your agency app is public facing therefore you need to specifically how you will protect other sellers data and potentially 10's of customers  order data .

I understand what you want to achieve but you have told amazon the app is for your own seller account.  

You can still block third party signs by disable signs up i guess.

**Comment by moltar** [comment]
> Internal apps have different set of rules to adhere to .

There is no such thing as an "internal app".

The two options when signing up for SP API are:

- **Option 1**: My organization sells on Amazon and I only want to integrate to manage my own business only.
- **Option 2**: My organization builds and offers publicly available applications.

So neither applies for a private app that can auth other sellers.

We did not select "Option 2", because we do not want to list the app.

**Comment by uk-2** [comment]
Option 1 implies internal business usage only 
Option 2 implies - we would like to offer a multi tenant environment

Going with option 1 risks your clients because amazon could assume they are linked accounts because you have stated option 1.
I would reapply and go with option 2 and disable public sign ups your to app.

**Comment by moltar** [comment]
@uk-2 Do you work for Amazon? Is this an official guideline?

**Comment by uk-2** [comment]
> @uk-2 Do you work for Amazon? Is this an official guideline?

No i don't work for Amazon but i am a Amazon seller based on experience of 7 years.

Anywhere good luck!

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
