### ISSUE TITLE
Please Update: "Connecting to the Seller Partner API" / Step 2

### ISSUE THREAD

**Issue by antonycartwright** [amzn/selling-partner-api-docs#204]
Hi, thanks for the documentation.

Please update this section of the documentation:

![image](https://user-images.githubusercontent.com/64788269/101984977-a9f5c680-3c7c-11eb-92b9-e7ff00069685.png)

The documentation implies lack of case sensitivity. Please make a warning; "Endpoint parameters are case-sensitive. Check here for Endpoint details": https://github.com/amzn/selling-partner-api-docs/tree/main/references

If you miss a parameter, you will get an error like "Missing Parameter". If you mix the parameters around, you'll get an error which tells you the expected parameter order.

If you get the case wrong, however, you'll get "Invalid Signature" which is terribly ambiguous. Some headers don't appear to be case sensitive, but endpoint params are. Please express this in the documentation.

Regarding the C# SDK; canonising a string fails to correct case sensitivity when it probably should do. _Case sensitivity validation should be part of the canonisation process IMO._

Antony...

**Comment by MrYing** [comment]
Hello, can you tell me that your signature can be adjusted? My signature always shows that the authorization failed. I checked my IAM account and policy. They are consistent with the document description, but it has always been like this. If you encounter similar problems, can you guide me?

my Request  and Response:
BEGIN REQUEST++++++++++++++++++++++++++++++++++++
Request URL = https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/shipmentId1/preorder/confirm?marketplaceid=A1F83G8C2ARO7P&needbydate=2012-10-17

RESPONSE++++++++++++++++++++++++++++++++++++
Response code: 403

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by antonycartwright** [comment]
> Hello, can you tell me that your signature can be adjusted? My signature always shows that the authorization failed. I checked my IAM account and policy. They are consistent with the document description, but it has always been like this. If you encounter similar problems, can you guide me?
> 
> my Request and Response:
> BEGIN REQUEST++++++++++++++++++++++++++++++++++++
> Request URL = https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/shipmentId1/preorder/confirm?marketplaceid=A1F83G8C2ARO7P&needbydate=2012-10-17
> 
> RESPONSE++++++++++++++++++++++++++++++++++++
> Response code: 403
> 
> {
> "errors": [
> {
> "message": "Access to requested resource is denied.",
> "code": "Unauthorized",
> "details": ""
> }
> ]
> }

Try a different end point. That error message which you get back isn't helpful. I also received that error when I had the wrong path.

Try an endpoint which we know works.

**Comment by ShivikaK** [comment]
Hello @MrYing 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @MrYing,

As we haven’t received any response from you regarding this, I will close this issue.
Please open a support case with us for any errors with your API requests and we can assist you further.

Thanks,
Shivika Khare
Selling Partner API Developer Support
