### ISSUE TITLE
How to fetch RDT token for Selling Partner API for Direct Fulfillment Orders and Direct Fulfillment Shipping

### ISSUE THREAD

**Issue by rajat-garg** [amzn/selling-partner-api-docs#2040]
I am trying to fetch the shipping labels and packaging slips for our Seller Central account but I am not able to generate the RDT token for these requests. 

Acc. to these docs:
https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide
https://github.com/amzn/selling-partner-api-docs/issues/822

we need RDT for following operations/apis. 
getShippingLabels
getPackingSlips
getCustomerInvoices

But on the Token Api references page (https://github.com/amzn/selling-partner-api-docs/blob/main/references/tokens-api/tokens_2021-03-01.md#createrestricteddatatoken) , is showing path available only for orders and shipping api. (PFA screenshot)

![image](https://user-images.githubusercontent.com/6449114/153846370-bed7dff4-363f-44ee-b38e-27d903eeb1d9.png)

Can you please update the document with the other paths as well, I have already tried these paths for getPackingSlips and CustomerInvoices api but it is throwing following error.

Request URL: https://sellingpartnerapi-eu.amazon.com/vendor/directFulfillment/orders/v1/purchaseOrders?createdBefore=20211212T120000Z&createdAfter=20211111T110000Z

(Called it with RDT and STS tokens on postman)

```
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}

```

**Comment by rajat-garg** [comment]
@coder771 , I tried with both Access token and RDT today as well and getting the same error. I am also facing this issue in eu-west-1 region.  Is it possible that its not working for this region. I saw some APIs (FBA Inventory , Get All Features etc) only works for America region.

**Comment by emilianmanolache** [comment]
We're getting this access error as well, for calls that were perfectly working until the past weekend.
There's something wrong with the Amazon API.

**Comment by hoanghiep** [comment]
I have the same problem :(

**Comment by krithic15** [comment]
> Hi @krithic15 , Thanks for the response. Could you please tell where can I check this information in the seller central account. I am not able to find this option. If its related to roles then all the roles are selected in the application. ![image](https://user-images.githubusercontent.com/6449114/154684970-f1f2dd01-f0c5-4ca7-b8a3-a9d5a9deff9f.png)

Hello @rajat-garg,
To use an existing app for vendor integration, please follow the below steps

* Log-in to Seller Central as the primary account owner and go to Developer Central console and click on *Edit App*
* Choose *Vendors* under *Business entities supported* and then select the necessary Vendor roles
* Then click on *Save and exit*
* Receive 3P Authorization from a vendor
* DONE: Now you are ready to begin calling Selling Partner APIs for vendors.

If you do not see the *Business entities* field, please re-submit your Developer Profile[try de-selecting and then selecting any of the options just to trigger submission] and that should help with enabling the *Business entities* field on the *Edit App* page. Please let me know if this helps.

Thanks,
Krithi, Solutions Architect, Selling Partner API

**Comment by pucsdian** [comment]
@rajat-garg 
Regarding path
In every Rdt Request path will be , path without query string like
in this case
https://sellingpartnerapi-eu.amazon.com/vendor/directFulfillment/orders/v1/purchaseOrders?createdBefore=20211212T120000Z&createdAfter=20211111T110000Z

path = /vendor/directFulfillment/orders/v1/purchaseOrders
