### ISSUE TITLE
[FEATURE] Documentation

### ISSUE THREAD

**Issue by pranav-shah-mpf** [amzn/selling-partner-api-docs#2041]
GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT API returns data for all departments / categories. Also, output file is single file and size is approximately more than 1.6 GB.

To leverage Big data stack, it is good to deliver data into multiple files instead of one. Moreover, if users are interested in specific set of departments then there should be a way to get only those data. Requesting to add input parameter to filter data by department / category.

**Comment by kmander** [comment]
We'd love the ability to specify a department (amazon.com in our case) as an input parameter. We only wish to parse data from this one department, but it's already now a heavy load to filter out redundant data.

**Comment by CarlosEscobarJB** [comment]
Hey @krithic15 Any update on this? The same features as the API feeding SC UI are essential like department, asin, searchTerm, I even see a limit prop in the request! that with the period scope will make this perfect.

**Comment by Philomath88** [comment]
+1
