### ISSUE TITLE
Order Report takes very very very long time to generate

### ISSUE THREAD

**Issue by littleylv** [amzn/selling-partner-api-docs#2042]
I wonder if it is proper to submit issue here but we have opened a case and the Amazon Support could not give us any useful replies.

Since 2022-02-11 the `_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_` report takes over one hour to finish processing the request, even the report includes just about 200 orders which only takes about 3 or 5 minutes before.

And this only happens in NA marketplaces.

**Comment by emilianmanolache** [comment]
We're having the same problem. Both with reports, and also with feeds. 
Amazon, please fix this. It's very urgent, as it interferes with our pricing algorithm.
Thank you.

**Comment by ehrowe** [comment]
This is also happening in MWS, so it seems to be an Amazon system problem. I have customers whose orders report is taking in excess of 8 hours to complete. I wish it was only an hour. And only in NA.

**Comment by littleylv** [comment]
I am closing this issue as the report is behaving normally since 2022-02-16.
