### ISSUE TITLE
getOrderMetrics -- specifying "all" for marketplaceIds results in 403

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#2044]
I attempted to call `getOrderMetrics` with multiple `marketplaceIds`. Since that parameter is an array, I assumed I could specify multiple marketplaces. However, when I specified more than one marketplace ID, I got back this error:

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "{getOrderMetrics.arg3[0].id\u003dmust match \"(all|A[0-9A-Z]{1,20})\"}",
      "details": ""
    }
  ]
}
```

The regex in that error indicates two things:
* Only one marketplace at a time is supported. It would be great if the docs made that clear.
* I should be able to pass the string `'all'` in the `marketplaceIds` parameter.

I tried passing `'all'`, and was greeted with a `403 Unauthorized` error. Is there some specific set of credentials I need in order to make that call?

Thanks! cc @ShivikaK @parvathm @jenilew

**Comment by usmansheikh2019** [comment]
marketplaceIds: ["A2EUQ1WTGCTBG2", "A1AM78C64UM0Y8"]   
This is also giving the same error

**Comment by vinodbhoj** [comment]
Did you find the solution? I am facing similar issue

**Comment by GJ-JG** [comment]
Hi all, thank you very much for the feedback and we will deliver this request internally.
I'm closing this issue but if we launched this feature we will announce it publicly.
