### ISSUE TITLE
Please make a heading for C# programmers at "Generating a Java SDK with LWA token exchange and authentication"

### ISSUE THREAD

**Issue by antonycartwright** [amzn/selling-partner-api-docs#205]
I've been using the C# SDK. The documentation lacks a lot of detail for us too. In my opinion, a new header for C# should be added here:

![image](https://user-images.githubusercontent.com/64788269/101985463-145c3600-3c80-11eb-8f3c-38ad8c9b2d4f.png)

The documentation should probably give us at least basic steps for C# and then say "skip to Connecting to the Selling Partner API" when finished. In reality, there is a lot of missing detail for C#. In due time, this could be added to the documentation. I'd say there is around 3-4 pages of material to cover for C#.

**Comment by bilal-yasin** [comment]
@antonycartwright could you create a document somewhere if you have done all the steps successfully ? that could help others.

**Comment by antonycartwright** [comment]
> @antonycartwright could you create a document somewhere if you have done all the steps successfully ? that could help others.

I finally became successful last week but haven't had time to review the project yet. I could make a guide if I had time. If I get time over the next few weeks, I'll do this. Antony...

**Comment by bilal-yasin** [comment]
> > @antonycartwright could you create a document somewhere if you have done all the steps successfully ? that could help others.
> 
> I finally became successful last week but haven't had time to review the project yet. I could make a guide if I had time. If I get time over the next few weeks, I'll do this. Antony...

I am stuck with an "Access to requested resource is denied",  "Unauthorized" error. I am still trying to resolve this. A guide will be great or any hint on how to get this ressolved.

**Comment by antonycartwright** [comment]
> > > @antonycartwright could you create a document somewhere if you have done all the steps successfully ? that could help others.
> > 
> > 
> > I finally became successful last week but haven't had time to review the project yet. I could make a guide if I had time. If I get time over the next few weeks, I'll do this. Antony...
> 
> I am stuck with an "Access to requested resource is denied", "Unauthorized" error. I am still trying to resolve this. A guide will be great or any hint on how to get this resolved.

Hi, show your code. Antony...

**Comment by bilal-yasin** [comment]
I have tried "Website work flow" and "Self authorization"
Code for Website Work Flow
`               
                var token = //get the access_token form database and refresh it if expired;
                var client = new RestClient("https://sandbox.sellingpartnerapi-na.amazon.com");
                IRestRequest restRequest = new RestRequest("/orders/v0/orders", Method.GET);
                restRequest.AddQueryParameter("MarketplaceIds", "ATVPDKIKX0DER");
                restRequest.AddHeader("x-amz-access-token", token.AccessToken);
                var credentials = new SellerAPICredentials()
                {
                    AWSKey = "My aws key",
                    AWSSecret = "My aws secret",
                    RoleARN = "My role arn",
                    ClientId = "My client id",
                    ClientSecret = "My client secret",
                    RefreshToken = "My refresh token"
                };
                restRequest = AmazonService.SignWithSTSKeysAndSecurityToken(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
                var response = client.Execute(restRequest);
`
For Self Authorization
`
                var baseUrl = "https://sellingpartnerapi-na.amazon.com";
                var client = new RestClient(baseUrl);
                IRestRequest restRequest = new RestRequest("/orders/v0/orders", Method.GET);
                restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
                restRequest.AddParameter("CreatedAfter", DateTime.UtcNow.AddDays(-5).ToString("yyyy-MM-dd"), ParameterType.QueryString);
                var credentials = new SellerAPICredentials()
                {
                    AWSKey = "My aws key",
                    AWSSecret = "My aws secret",
                    RoleARN = "My role arn",
                    ClientId = "My clientId",
                    ClientSecret = "My client secret",
                    RefreshToken = "My refresh token"
                };
                restRequest = AmazonService.SignWithAccessToken(restRequest, credentials.ClientId, credentials.ClientSecret, credentials.RefreshToken);
                restRequest = AmazonService.SignWithSTSKeysAndSecurityToken(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
                var response = client.Execute(restRequest);
`
Functions used here are from this issue https://github.com/amzn/selling-partner-api-models/issues/31

**Comment by antonycartwright** [comment]
> I have tried "Website work flow" and "Self authorization"
> Code for Website Work Flow
> 
> ```cs
>                 var token = //get the access_token form database and refresh it if expired;
>                 var client = new RestClient("https://sandbox.sellingpartnerapi-na.amazon.com");
>                 IRestRequest restRequest = new RestRequest("/orders/v0/orders", Method.GET);
>                 restRequest.AddQueryParameter("MarketplaceIds", "ATVPDKIKX0DER");
>                 restRequest.AddHeader("x-amz-access-token", token.AccessToken);
>                 var credentials = new SellerAPICredentials()
>                 {
>                     AWSKey = "My aws key",
>                     AWSSecret = "My aws secret",
>                     RoleARN = "My role arn",
>                     ClientId = "My client id",
>                     ClientSecret = "My client secret",
>                     RefreshToken = "My refresh token"
>                 };
>                 restRequest = AmazonService.SignWithSTSKeysAndSecurityToken(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
>                 var response = client.Execute(restRequest);
> ```
> 
> For Self Authorization
> 
> ```cs
>                 var baseUrl = "https://sellingpartnerapi-na.amazon.com";
>                 var client = new RestClient(baseUrl);
>                 IRestRequest restRequest = new RestRequest("/orders/v0/orders", Method.GET);
>                 restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
>                 restRequest.AddParameter("CreatedAfter", DateTime.UtcNow.AddDays(-5).ToString("yyyy-MM-dd"), ParameterType.QueryString);
>                 var credentials = new SellerAPICredentials()
>                 {
>                     AWSKey = "My aws key",
>                     AWSSecret = "My aws secret",
>                     RoleARN = "My role arn",
>                     ClientId = "My clientId",
>                     ClientSecret = "My client secret",
>                     RefreshToken = "My refresh token"
>                 };
>                 restRequest = AmazonService.SignWithAccessToken(restRequest, credentials.ClientId, credentials.ClientSecret, credentials.RefreshToken);
>                 restRequest = AmazonService.SignWithSTSKeysAndSecurityToken(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
>                 var response = client.Execute(restRequest);
> ```
> 
> Functions used here are from this issue [amzn/selling-partner-api-models#31](https://github.com/amzn/selling-partner-api-models/issues/31)

Your code looks fine to me. Take a look at your region and check that. Also, check permissions/policies/roles. For me, I gave the user and the role full permissions in the console area.

**Comment by coder771** [comment]
@antonycartwright  can you please share your basic code for get orders using c# sdk.

**Comment by rugved1991** [comment]
Hi @ClementeGao, @coder771,

Please let us know if you are still facing any issues.
@antonycartwright @bilal-yasin  thanks for the feedback regarding the C# SDK guide. We will surface this feedback to our tech writers. If you have created a guide already, please feel free to share with the developer community.

Best,
Rugved
Solutions Architect, SP API
