### ISSUE TITLE
'host:' not a valid key=value pair (missing equal-sign) in Authorization header

### ISSUE THREAD

**Issue by RotoLZak** [amzn/selling-partner-api-docs#2055]
Amazon SP API it's something new for me.

I want to connect via SP API to get some data from my auction.

I have already read [selling-partner-api-docs/SellingPartnerApiDeveloperGuide.md at main · amzn/selling-partner-api-docs · GitHub](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md).

According to this guide I need to get through 4 steps:

1. Request a Login with Amazon access token
2. Construct a Selling Partner API URI
3. Add headers to the URI
4. Create and sign your request

My header:

`Array
(
    [0] => Authorization: AWS4-HMAC-SHA256 Credential=AKIAYGLOOEXAMPLE/20220215/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token, Signature=4XXXXXXXXXX host: sellingpartnerapi-eu.amazon.com user-agent: My Selling Tool/2.0 (Language=PHP7;Platform=Windows/10) x-amz-access-token=Atza|IwEBXXXXXEXAMPLE x-amz-date: 20220215T124706Z
)`

MY URI
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/xxx-xxxxxxx-xxxxxxx
I've made all this steps and in response I got it:

`stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [message] => 'host:' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=AKIAXXXXXXXXXXXXXXX/20220215/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token, Signature=f359c1b0abaEXAMPLE host: sellingpartnerapi-eu.amazon.com user-agent: My Selling Tool/2.0 (Language=PHP7;Platform=Windows/10) x-amz-access-token=Atza|IwEBEXAMPLE x-amz-date: 20220215T123742Z'.
                    [code] => InvalidInput
                )
        )
)`

Help me with properly request header creation :)

**Comment by littleylv** [comment]
Your header is not correct. It should be like:

```
Array
(
    [x-amz-access-token] => xxx
    [x-amz-date] => 20220215T123742Z
    [x-amz-security-token] => yyy
    [Authorization] => AWS4-HMAC-SHA256 Credential=******/20220218/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=**********
    [host] => sellingpartnerapi-eu.amazon.com
)
```

**Comment by RotoLZak** [comment]
"x-amz-security-token" is necessary? 
After request without it, I got:
```php
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [message] => Access to requested resource is denied.
                    [code] => MissingAuthenticationToken
                )

        )

)

**Comment by littleylv** [comment]
Yes. Both 'x-amz-access-token' and `x-amz-security-token` are required.

**Comment by RotoLZak** [comment]
But in this documentation there isn't any reference about `x-amz-security-token`?
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md
How I can create `x-amz-security-token` ?

**Comment by littleylv** [comment]
It is not mentioned in the document but it is necessary for Role IAN. See [https://github.com/amzn/selling-partner-api-docs/issues/1362](https://github.com/amzn/selling-partner-api-docs/issues/1362)

> How I can create x-amz-security-token ?

If you are using PHP, check this: [https://github.com/clousale/amazon-sp-api-php/blob/master/lib/AssumeRole.php#L51](https://github.com/clousale/amazon-sp-api-php/blob/master/lib/AssumeRole.php#L51)

Or document here: [https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_Examples](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_Examples)

**Comment by RotoLZak** [comment]
@littleylv 
Is any easier way to get session token to x-amz-security-token?
Or could you describe this step by step?
