### ISSUE TITLE
[BUG]  Data of 2021-11-09 are missed in Sales Diagnostic and Inventory Forecast and Inventory Health report

### ISSUE THREAD

**Issue by robinchen123** [amzn/selling-partner-api-docs#2057]
Hi Amazon,
We retrieve empty data of the day 2021-11-09 for all of our vendor clients.  Do you have any opinion on it?

**Comment by jlevers** [comment]
Hey @robinchen123 -- from what you've said above, it sounds like you've been able to authorize other vendors with your SP API application and retrieve reports for those vendors. From what's said in #1989, I'm curious how you were able to do that. Are you part of the closed beta that @rugved1991 mentioned in that issue?
