### ISSUE TITLE
getTrackingInformation always returns TrackingId not found?

### ISSUE THREAD

**Issue by yunlei000** [amzn/selling-partner-api-docs#2058]
getTrackingInformation always returns TrackingId not found?
first of all,
i try getShipment wethod with corrrect shipmentId and return correct json,part of returned json is:
"shipmentId": "xxxxxxxxxxxxxxxx",
...
"status": "PURCHASED",
"trackingId": "289787061893",
"createdDate": "2022-02-14T07:34:07Z",
"lastUpdatedDate": "2022-02-14T07:34:07Z"
second,
i try getTrackingInformation with above "trackingId": "289787061893" query:/shipping/v1/tracking/289787061893
it return “TrackingId not found”
some other trackingIds with this method  also returns such error
does someone know why?

**Comment by williamQyq** [comment]
same issue here.
