### ISSUE TITLE
[BUG] Unable to fetch Reports API

### ISSUE THREAD

**Issue by optikalefx** [amzn/selling-partner-api-docs#2059]
We have access to all of this through MWS but we are trying to convert to SP.

If we make a call to `reportClient.getReportSchedules` we get `Access to the resource is forbidden`
requestId:'73bbff03-cba3-4ed8-8bf9-5d98bde94cd3'

So we will try to get an RDT instead, even though it's not documented that we need one.
Here is our call to get the RDT, the path is found in the documentation.

```
const rdt = await tokensClient.createRestrictedDataToken({
			body: {
				restrictedResources: [
					{
						dataElements: ['buyerInfo'],
						method: 'GET',
						path: 'reports/2021-06-30/schedules',
					},
				],
				targetApplication: 'XXX',
			},
		});
```

This returns 

```
Application does not have access to one or more requested data elements: [buyerInfo]
```
requestId:'13ae69fd-83f2-445c-a7ef-cd57398d4e35

Our application does have sufficient permissions and is published

![image](https://user-images.githubusercontent.com/926885/154730593-569bdd40-dabe-44b9-a7e5-99299f3c1f71.png)

Lastly to note, we can get RDTs for other calls like GetOrders. So it's something related to reports.

Thanks!

**Comment by rohitdobariya** [comment]
@optikalefx You don't required RDT for reportClient.getReportSchedules.
I hope you have done the necessary steps for migrating the MWS token to SP. 
Let me know if you need any help.

**Comment by optikalefx** [comment]
@rohitdobariya Thanks for confirming we don't need one. Are there any steps that you think I might be missing? We can make other calls with multiple seller accounts just fine. It's only Reports that throw the above errors.

**Comment by optikalefx** [comment]
@rohitdobariya I have an update, other reports do work. We're finding that _GET_FLAT_FILE_ORDERS_DATA_ gives the 403 forbidden error. What permission do we need to add to enable us to download this report? You can see the roles our app has above in the screenshot.

**Comment by rohitdobariyaleanspace** [comment]
@optikalefx all are good for the role. I don't think it is an issue about the role. you have a proper role in accessing the report.
Let's meet and resolve your issue. Join me on zoom :: https://zoom.us/j/5424961335?pwd=WTJFTy8wUVIyWEhuVHJlZi9LOXVXUT09

**Comment by optikalefx** [comment]
For anyone who sees this, Amazon seller support answered my question

```

I understand you are getting an Access to resource is forbidden error when trying to call report _GET_FLAT_FILE_ORDERS_DATA_.

Please note that _GET_FLAT_FILE_ORDERS_DATA_ is a report only available through MWS, and using a Report type enumeration that doesn't match the SP API enumerations will result in this error.

Despite the report being deprecated, you can search for the SP API Orders reports that contain the information you need:

Report Type values
https://developer-docs.amazon.com/sp-api/docs/report-type-values

I think you will find useful this announcement related to the MWS reports being deprecated or divided on SP API:
https://github.com/amzn/selling-partner-api-docs/discussions/1037
```

**Comment by rohitdobariya** [comment]
Great!
