### ISSUE TITLE
A published application with the provided app-id not found when converting the credentials from MWS to SP-API

### ISSUE THREAD

**Issue by fabioxgn** [amzn/selling-partner-api-docs#2060]
I'm getting this error when trying to convert a MWS authorization to SP-API:

```JSON
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "A published application with the provided app-id not found",
      "details": ""
    }
  ]
}
```

Does the published app need to be the app that was converted from the MWS application? 

I have multiple Hybrid Apps now (some created for testing) and I do not know which one (if any) was converted from the MWS application. My suspicion is that the app we published was not converted. Is there a way to know if a hybrid app was converted from MWS? Or is this error a different problem?

**Comment by fabioxgn** [comment]
> @fabioxgn its the one that matches the roleArn you're using to gain access. That's the app that has to be published. I just went through this the other day. Your app needs to be hybrid, published and approved, with Oauth URLs and that ARN is what you need to be using in your application to get the converted auth token.

Hi @optikalefx thank you! I totally forgot about the `client_id` I was using the `client_id` from the unpublished app. Now I was able to get an authorization code!

**Comment by jiangdi0924** [comment]
@fabioxgn  Hi,  i got same issue, can you explain which is the `client_id`  ?

**Comment by fabioxgn** [comment]
> 

Hi @jiangdi0924 the client ID is displayed when you click `view` in the LWA Credentials column:
![image](https://user-images.githubusercontent.com/1084729/161263991-d64149de-ef8a-4308-b837-d9467d4f59c2.png)

![image](https://user-images.githubusercontent.com/1084729/161264082-966dfadb-aba9-45d4-b482-020cdf86c044.png)

You need to use the client id from a published application to be able to convert the MWS credentials:

![image](https://user-images.githubusercontent.com/1084729/161264174-cbb53378-e928-482f-8538-503d5a0642c4.png)
