### ISSUE TITLE
GetOrders NextToken

### ISSUE THREAD

**Issue by evoaaron** [amzn/selling-partner-api-docs#2066]
When attempting to use GetOrders with NextToken we get the following error:

**Code:**
InvalidInput

**Message:**
We could not decode your NextToken. Possible reasons include: a transmission error, improper quoting or a truncation problem.

The first GetOrders call without a NextToken is always successful.

We are encoding the NextToken parameter as part of the CanonicalQueryString. I expect this is to do with encoding + from %2B to %20 though is required to form the valid AWS signature. Signature passes though we're always get the NextToken error. 

Has anybody managed to get past this specifically with GetOrders?

**Comment by evoaaron** [comment]
Fixed. Was only encoding the NextToken to generate the signature, not also on the actual query string value itself.

**Comment by raja1621** [comment]
Even in the postman also experiencing the same behaviour..


This is the nextToken : 6JkUr3EONUZ/YYuZQbKv1QafEPREmauvizt1MIhPYZZluiVR8M5tjb3NrVfax7yFO5bKYL++GMIFKcR+MgahmN8ytOVgN7d/KyNtf5fepe0z86MVYTeRn5+xawTG5fq35m1IW7252CuS68vI7Bqws+weLxD7b1CVUvtIY+Vf/zrRsOXkIz7NY1c9OrvMs1nhZjy1N1wvaxle0zIeaOVNezxWEXvdeDL7wQtuOcfwlBt73CqrS1ae6rmt7Z4zY0bm3DUoFBT4Hs0wE7+t4NjazyEZY027dXAVTSGshRBy6ZTthhfBGj6Dwur8WCwcU8Vc25news0zC1z6KdWXsQoz8/srgabKffb0T5cSvBf6cCzMdtkJ3EQY19CgUhcwM0jGiXa4GKsnC3JuDoxUf0M3XoEDUrIQbaP8J6omjbJhecrDlfXgssOal3umy/UYNPEn


Here is the response of postman : 
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "We could not decode your NextToken. Possible reasons include: a transmission error, improper quoting or a truncation problem.",
            "details": ""
        }
    ]
}

**Comment by raja1621** [comment]
We are facing the same issue with multiple api's 
1) getOrders
2) InboundShipments

**Comment by raja1621** [comment]
Can someone, please tell us how to resolve... We are depending on this api's alot.

**Comment by radug-cpc** [comment]
> Fixed. Was only encoding the NextToken to generate the signature, not also on the actual query string value itself.

How exactly did you encode the NextToken and how did you pass it to the request?
