### ISSUE TITLE
Different performance in different countries

### ISSUE THREAD

**Issue by 4379711** [amzn/selling-partner-api-docs#207]
- I use the same role and can work successfully in **us** 
- But in **uk** ,there is a part of interface got 403,such as `/fba/inventory/v1/summaries`, But it works well on `/orders/v0/orders`,why?

**Comment by parvathm** [comment]
Hi @4379711 

The resource path /fba/inventory/v1/summaries is only available in NA as of now.  We are aware of this gap and working with the relevant team to address it. Sorry for the inconvenience caused.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by jlevers** [comment]
@parvathm it would be extremely helpful to get an up-to-date list of which endpoints are working, and in which regions. Would that be possible?

**Comment by arkhipkin** [comment]
@parvathm is there any possibility to get inventory details from SP API for the DE marketplace?

**Comment by danielbebbernovacode** [comment]
@parvathm Is the issue being worked on? There was no update since November and we need this API be available for an application.
