### ISSUE TITLE
ResultMessageCode 5001 : Cannot find the declaration of element 'String'.

### ISSUE THREAD

**Issue by mdfmtetreault** [amzn/selling-partner-api-docs#2073]
As described by the documentation [here](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#tutorial-submit-a-feed), I'm following every step mentioned in the article to submit a feed, but the Feed Processing Report indicates me that there is an error, detailed with the Code 5001.

![Capture](https://user-images.githubusercontent.com/100236232/155209630-08f0cf21-56b1-4b92-a609-4902f8e505fa.PNG)

"_XML Parsing Fatal Error at Line 1, Column 11: cvc-elt.1: Cannot find the declaration of element 'String'. cvc-elt.1: Cannot find the declaration of element 'String'._"

I've first tried using a feed that I've constructed myself, it gave the error in the picture above. I've then taken the XML example mentioned during step 2 that you can find [here](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#step-2-construct-a-feed) and slightly adapted it for my example (ex.: changing SKU, ASIN, Title and Description) but submitting  it is giving the same error than my first feed.

It should be noted that this issue is encountered regardless if I try sending a feed with type POST_PRODUCT_DATA, POST_INVENTORY_AVAILABILITY_DATA, POST_PRODUCT_PRICING_DATA, I'm getting the same issue. Using C# to go through all of these steps.

How can this be resolved?

**Comment by avvarga** [comment]
Hello @mdfmtetreault,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Alejandro C.
Selling Partner API Developer Support

**Comment by MCutrin** [comment]
Hi, I know this may be a long shot since the issue is closed, but I would like to know if there has been any developmentes on the initial problem since I'm facing the same issue. Thanks in advance.
