### ISSUE TITLE
[BUG] Allow for the creation of shipments with more than 200 items through the API 

### ISSUE THREAD

**Issue by DavidRHid** [amzn/selling-partner-api-docs#2075]
**fulfillment_inbound/feeds**
In MWS the creation of larger shipments was done by combining shipments through 'UpdateInboundShipment' as seen here: https://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_CreateShipment200Items.htmlhttps://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_CreateShipment200Items.html
However, it seems the SP_API doesn't allow for that https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#updateinboundshipment "Updates or removes items from the inbound shipment identified by the specified shipment identifier. **Adding new items is not supported**."

When Using feeds it is possible to create larger shipment plans via POST_FLAT_FILE_FBA_CREATE_INBOUND_PLAN https://developer-docs.amazon.com/sp-api/docs/feed-type-values#fulfillment-by-amazon-feeds
However, there is no function to turn that plan into a real shipment through feeds, and the createInboundShipment operation, which I use for small shipment plans, requires a shipment identifier originally returned by the createInboundShipmentPlan operation (not run when using feeds).
This seems like a glaring oversight that needs to be added now so large companies can integrate this API.
Any solutions?
Thank you

**Comment by hamduc7** [comment]
I have this same problem. Is there any update?

**Comment by fr3shn3ss** [comment]
Still an issue. Shouldn't be closed

**Comment by hamduc7** [comment]
3-Mar-2013: the problem still exists

The API document does not mention about this limitation.
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#inboundshipmentplanrequestitem

But if we create a shipment plan that has >200 SKUs, we will receive error:

**Error: Number of InboundShipmentPlanRequestItems exceeded the maximum allowed limit of 200 per createInboundShipmentPlan request.**

Please solve the issue before close this ticket

Thank you

**Comment by neoxyte** [comment]
I  myself need help with this issue. Why are they penalizing big sellers like us? The current work around is to make multiple shipments and just put those shipments on the same truck (as long as they go to the same FC).

**Comment by jlevers** [comment]
Any update here? This is causing issues for several clients of mine.

**Comment by fr3shn3ss** [comment]
I have built a script to use Send To Amazon to create 1500 sku shipments. Shoot me a private message and I'll send it to you

**Comment by truonggiang347** [comment]
> I have built a script to use Send To Amazon to create 1500 sku shipments. Shoot me a private message and I'll send it to you

How to PM you?

**Comment by homes2001** [comment]
has anyone figured out how to send shipments with > 200 SKUs?
