### ISSUE TITLE
issue in creating notification Subscription Id with createSubscription() for notification type ANY_OFFER_CHANGED

### ISSUE THREAD

**Issue by webinsect-rishabh** [amzn/selling-partner-api-docs#2076]
I am facing an issue in creating notification Subscription Id with createSubscription() for notification type ANY_OFFER_CHANGED. Before this i have generated destination id with createDestination with grantless token. Destination id is created successfully, but i am unable to create Subscription Id. I tried with grantless token and default token but no success. I am getting error 403 , Unauthorized , Access to requested resource is denied.  Please some one help me on this. TIA

**Comment by starstong** [comment]
hi, i meet same probledm , do you solve it ?

**Comment by starstong** [comment]
hi  look thiss issue : https://github.com/amzn/selling-partner-api-docs/issues/359#
