### ISSUE TITLE
How to get Amazon Sponsored Discount for Buy Shipping

### ISSUE THREAD

**Issue by c0ry** [amzn/selling-partner-api-docs#2078]
Does anyone know how to get Amazon Sponsored Discount pricing for Buy Shipping with the Selling Partner API?

It says in this link https://sellercentral.amazon.com/help/hub/reference/G7X4G8VWJS9B8UUN?  "Sellers are able to access the discount when using Buy Shipping through Seller Central and the Merchant Fulfillment API. Sellers who use Buy Shipping via the Merchant Fulfillment API will need to call Get Eligible Shipping Services API (GESS API) first, before calling CreateShipment API. "

But when I get eligible shipping services via https://sellingpartnerapi-na.amazon.com/mfn/v0/eligibleShippingServices  it is not showing me the discount pricing that I see in Seller Central for the same order.

**Comment by Toyganozu** [comment]
Seller Central and API has pricing discrepancy on the call Get Eligible Shipping Services API . This is a bug, i am also having the same issue,
