### ISSUE TITLE
submit Feed Sandbox

### ISSUE THREAD

**Issue by coder771** [amzn/selling-partner-api-docs#2081]
I'm getting below response on create feed document call to  (https://sandbox.sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/documents)

{"feedDocumentId":"3d4e42b5-1d6e-44e8-a89c-2abfca0625bb","url":"https://d34o8swod1owfl.cloudfront.net/Feed_101__POST_PRODUCT_DATA_.xml"}

but when I'm trying to postXMLData to https://d34o8swod1owfl.cloudfront.net/Feed_101__POST_PRODUCT_DATA_.xml I'm getting  

The remote server returned an error: (403) Forbidden.

So is this not available on Sandbox?

**Comment by albinsopaj** [comment]
> I'm getting below response on create feed document call to (https://sandbox.sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/documents)
> 
> {"feedDocumentId":"3d4e42b5-1d6e-44e8-a89c-2abfca0625bb","url":"[https://d34o8swod1owfl.cloudfront.net/Feed_101__POST_PRODUCT_DATA_.xml"}](https://d34o8swod1owfl.cloudfront.net/Feed_101__POST_PRODUCT_DATA_.xml%22%7D)
> 
> but when I'm trying to postXMLData to https://d34o8swod1owfl.cloudfront.net/Feed_101__POST_PRODUCT_DATA_.xml I'm getting
> 
> The remote server returned an error: (403) Forbidden.
> 
> So is this not available on Sandbox?

Hello. Did you manage to solve your issue? Now, I'm facing the same thing and I really don't know what to do. Thanks in advance.
