### ISSUE TITLE
report GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE gets cancelled all the time

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#2085]
I want to create a report with GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE type and everytime I request It gets cancelled.
Why is that????
Any reason? 
At least give proper error

**Comment by Javadebi** [comment]
```
SellingPartnerAPI.callAPI({
          operation: "createReport",
          //@ts-ignore
          endpoint: "reports",
          body: {
            //@ts-ignore
            reportType: "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
            marketplaceIds: ["ATVPDKIKX0DER"],
            dataStartTime: s.toISO(),
            dataEndTime: e.toISO(),
          },
        }).then((res) => {
          console.log(res);
}
```

**Comment by adrian-amz** [comment]
Hello @Javadebi,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C.
Selling Partner API Developer Support

**Comment by naloqab** [comment]
Any updates to this issue? It seems silly to ask users to open support cases and not post a solution publicly. Now everyone has to open a case.

**Comment by Javadebi** [comment]
> GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE

I don't remember if I opened a support case or not, but I passed this report and didn't use it

**Comment by Javadebi** [comment]
> Any updates to this issue? It seems silly to ask users to open support cases and not post a solution publicly. Now everyone has to open a case.

I don't remember if I opened a support case or not, but I passed this report and didn't use it

**Comment by GonzaloGDV** [comment]
@naloqab could you resolve this issue?

**Comment by naloqab** [comment]
@GonzaloGDV Yes. I believe the report gets cancelled without returning an error when there's no data to return within the selected date range. The solution for me was to use a wider date range. Although I know for fact that I had some customer returns during the date range that I had initially selected. This report does not seem to capture all of the customer returns for whatever reason. It's been a few months now since I've looked into all of this, but it might have to do with FBA vs FBM returns.

**Comment by titansoftime** [comment]
Getting same issue with GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE. Cancelled every time. No explanation. The other report I use GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL works every time.

**Comment by GonzaloGDV** [comment]
The Cancelled is returned when there is not data, but it would be better if it could return an empty array
