### ISSUE TITLE
[BUG] Why can't the Japanese site get the same reports as the English sites? 

### ISSUE THREAD

**Issue by annisun2020** [amzn/selling-partner-api-docs#2086]
**Describe the bug**

I use this api get the activelistings report, other site is normal, but Japan site i get the strange report，
why the report  of Japan site encoding is SHIFT_JIS ?  why can't be UTF-8 ? why can't be the same report title with other site?
Why Japan is a maverick？

It's annoying to have to make many adjustments every time you download a Japanese report to be compatible with other site reports.

 
**Screenshots**
english site report title  like this, it's same report title and encoding.
![image](https://user-images.githubusercontent.com/68275306/155945687-432a5cab-63d9-4e61-bc31-1f5797d9a88c.png)

but Japan site report is shift-jis, and every one report title is different with other sites.

![image](https://user-images.githubusercontent.com/68275306/155946006-c9c85daa-6b30-435a-a69d-d08a38dfe140.png)

**Comment by bardo-olsen** [comment]
**Workaround:**
Ask users to change feed processing language to English on SellerCentral

Settings > Account Info 
Under "Business Information" section, click "Language for feed processing report"

then select English(US)

it will work properly. 

Hope that we won't request it from user and we can use UTF-8.

**Comment by annisun2020** [comment]
not work , japan is a magic country, a country on mars !
