### ISSUE TITLE
How i remove version=beta or do i have to remove?

### ISSUE THREAD

**Issue by bardo-olsen** [amzn/selling-partner-api-docs#2088]
Hi, 
I have a hybrid application and i've implemented orders succesfully but i'm not quite sure that i've implemented auth flow correctly.

Everything is ok for MWS and my users are already connected. Works perfect.

I'm requesting access via following url:

https://sellercentral.amazon.com.mx/apps/authorize/consent?application_id=amzn1.sellerapps.app.XXXX&state=amazon.com.mx&redirect_uri=https://my-awesome-website.com/OAuthRedirect

It's redirecting to MWS Access Request page.

But when i add &version=beta parameter, 
https://sellercentral.amazon.com.mx/apps/authorize/consent?application_id=amzn1.sellerapps.app.XXXX&state=amazon.com.mx&redirect_uri=https://my-awesome-website.com/OAuthRedirect&version=beta

it redirects to Selling Partner API page.

Now the question: 
Is it OK to request production-level access for SP-API via using "version=beta" ? 
Or how i can generate link that does not contain version=beta for SP-API Access Request?

It's not looking ok to add the word "beta" in a kind of production-level URL.

I've looked documents a lot but i couldn't find a proper answer.
Please advise

Thanks.

**Comment by alexey55501** [comment]
Hi guys, any updates on this topic? I'm struggling with the same question too
