### ISSUE TITLE
Restricted Data Token  - Unauthorized.

### ISSUE THREAD

**Issue by rmanjusha** [amzn/selling-partner-api-docs#2089]
Need help on generating restricted data token  . CaseId  - 9710807751

generate restricted data token call gives Unauthorized error . Application is authorized to use for US Market place .

**Comment by adrian-amz** [comment]
Hello @[rmanjusha](https://github.com/rmanjusha),

Thank you for providing a Support Case related to this matter.

We will continue to monitor the situation on the case and post any relevant details here.

Thanks,
Adrian C.
Selling Partner API Developer Support
