### ISSUE TITLE
[BUG] getOrders returns same orders even when using different next Token.

### ISSUE THREAD

**Issue by vamaship-saud-qureshi** [amzn/selling-partner-api-docs#2090]
I am trying to fetch all orders (using ordersV0) from via sp api for a given account.
But the api keeps giving me same orders for every request (even when using different nextToken that I got in the previous request which always comes different than before).
Attaching log below.
NextToken: null
array:100 [
  0 => "404-9841926-7184314"
  1 => "406-1120300-3233145"
  2 => "403-5293005-4522707"
  3 => "406-0726429-6379522"
  4 => "171-6002267-3585947"
  5 => "171-2293159-0497906"
  6 => "171-1744750-5601150"
  7 => "404-6949232-0439522"
  8 => "402-1511088-3378761"
  9 => "408-2915763-8156303"
  10 => "402-8006018-1521165"
  11 => "402-1705498-4457142"
  12 => "408-7589474-1920335"
  13 => "405-9474614-7195529"
  14 => "408-0373173-8890767"
  15 => "408-3379282-0689120"
  16 => "403-0811589-7497953"
  17 => "171-1027709-4321942"
  18 => "406-4216545-2567556"
  19 => "171-9992756-2234756"
  20 => "171-1918310-9614713"
  21 => "171-6058287-3857129"
  22 => "408-9406763-4641130"
  23 => "171-6067954-4791529"
  24 => "405-6866244-5997144"
  25 => "171-0844712-1601109"
  26 => "402-1150454-3694733"
  27 => "171-7488870-2271545"
  28 => "408-7023248-6264325"
  29 => "408-3809744-3132344"
  30 => "408-8122802-0032327"
  31 => "406-2828130-9663540"
  32 => "405-6179805-3456323"
  33 => "402-2888388-1485956"
  34 => "407-7979381-1037938"
  35 => "406-7086745-2007563"
  36 => "405-9092489-3893155"
  37 => "405-4596091-5804346"
  38 => "403-2377310-7227509"
  39 => "405-8969593-1671532"
  40 => "408-8220346-2617162"
  41 => "402-5542822-4065127"
  42 => "408-8036910-8251538"
  43 => "405-7714500-2660355"
  44 => "402-3202687-2928325"
  45 => "402-5463381-1565905"
  46 => "402-3254093-5170743"
  47 => "407-6313817-1729144"
  48 => "408-0894324-0095557"
  49 => "408-7802873-0797922"
  50 => "403-0228916-7906750"
  51 => "405-6754431-2830750"
  52 => "403-7475186-6833127"
  53 => "404-7377018-5078767"
  54 => "405-6605435-5189166"
  55 => "402-3088488-2364335"
  56 => "402-4881823-7407559"
  57 => "406-8900243-2052322"
  58 => "407-1302144-1527513"
  59 => "404-7973091-5177123"
  60 => "171-6477107-0654749"
  61 => "407-2951251-7807562"
  62 => "405-4502563-0626724"
  63 => "407-3317129-1837164"
  64 => "407-3160736-2132352"
  65 => "408-5482505-2974702"
  66 => "406-9690720-6719549"
  67 => "404-3596404-3407556"
  68 => "406-5411121-3703533"
  69 => "408-4500006-3557137"
  70 => "404-8312328-6913101"
  71 => "406-8129500-4807532"
  72 => "408-9474111-9803515"
  73 => "406-7774574-8782767"
  74 => "407-9358549-1105141"
  75 => "407-1133728-5268310"
  76 => "403-6312042-8438708"
  77 => "402-9808661-6449921"
  78 => "402-4028136-3385104"
  79 => "408-1014166-4677917"
  80 => "404-8730180-0323520"
  81 => "171-7038155-6977115"
  82 => "406-9366338-5907557"
  83 => "403-0005577-4393940"
  84 => "408-4910482-2139508"
  85 => "402-9650102-2121903"
  86 => "407-3716531-3309100"
  87 => "406-0822602-7205121"
  88 => "407-8411150-3627538"
  89 => "402-7430814-4097943"
  90 => "408-5041119-1924330"
  91 => "408-7575002-0808337"
  92 => "404-4255373-7244354"
  93 => "407-5210915-8557157"
  94 => "403-5439774-1865941"
  95 => "402-3794660-7624357"
  96 => "402-4843616-3615567"
  97 => "407-6007317-3430761"
  98 => "402-2032150-0868317"
  99 => "171-5831291-2998723"
]
NextToken: IIN1wwuftRSaJqJYLDm0ZAmQazDrhw3CeUUacWJ5TFJUojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy+y0VVZKEl9LuspXSJW6v/52rJ/HQYjloaQ9pHN41m0qaInTAy+XKVmRZBY+oaVuycwQFure81U/C3FGn+XdtVB94QHwVlk9J2x89dUf46GNof2GLmUGyr9UGnxD0RJmrryegoU0IPZxX3JgSYI+YbKWwzTUE+8P5Y31s4Ruvx7wWMBO/reDY2s+lLK7IMTJG+oWZaQSHenVJIIYkgmdzyCpNQzRAUqdu/u9W9k/g4x4611Ds5w1QtjV2w8niSQCqBjOPK+Zzoe2U/OdEYkeU1VS1Ppo7b2+tmYZgBBFaUbjPExu1fOh4QqENhc5mKlYDhZ0yvnoilCknjKTPDr6j2hjL52R7aRQ/Y22iMYFXG9yK6G4I/dhxbeqSO+rXZfBZj1W6OUKz1nLa90j3xRqYo/7tjrdcUMduE4+envNcHi41bkjozTHzBh6HLLADg2syys9mNOdUz8cZ
^ array:100 [
  0 => "404-9841926-7184314"
  1 => "406-1120300-3233145"
  2 => "403-5293005-4522707"
  3 => "406-0726429-6379522"
  4 => "171-6002267-3585947"
  5 => "171-2293159-0497906"
  6 => "171-1744750-5601150"
  7 => "404-6949232-0439522"
  8 => "402-1511088-3378761"
  9 => "408-2915763-8156303"
  10 => "402-8006018-1521165"
  11 => "402-1705498-4457142"
  12 => "408-7589474-1920335"
  13 => "405-9474614-7195529"
  14 => "408-0373173-8890767"
  15 => "408-3379282-0689120"
  16 => "403-0811589-7497953"
  17 => "171-1027709-4321942"
  18 => "406-4216545-2567556"
  19 => "171-9992756-2234756"
  20 => "171-1918310-9614713"
  21 => "171-6058287-3857129"
  22 => "408-9406763-4641130"
  23 => "171-6067954-4791529"
  24 => "405-6866244-5997144"
  25 => "171-0844712-1601109"
  26 => "402-1150454-3694733"
  27 => "171-7488870-2271545"
  28 => "408-7023248-6264325"
  29 => "408-3809744-3132344"
  30 => "408-8122802-0032327"
  31 => "406-2828130-9663540"
  32 => "405-6179805-3456323"
  33 => "402-2888388-1485956"
  34 => "407-7979381-1037938"
  35 => "406-7086745-2007563"
  36 => "405-9092489-3893155"
  37 => "405-4596091-5804346"
  38 => "403-2377310-7227509"
  39 => "405-8969593-1671532"
  40 => "408-8220346-2617162"
  41 => "402-5542822-4065127"
  42 => "408-8036910-8251538"
  43 => "405-7714500-2660355"
  44 => "402-3202687-2928325"
  45 => "402-5463381-1565905"
  46 => "402-3254093-5170743"
  47 => "407-6313817-1729144"
  48 => "408-0894324-0095557"
  49 => "408-7802873-0797922"
  50 => "403-0228916-7906750"
  51 => "405-6754431-2830750"
  52 => "403-7475186-6833127"
  53 => "404-7377018-5078767"
  54 => "405-6605435-5189166"
  55 => "402-3088488-2364335"
  56 => "402-4881823-7407559"
  57 => "406-8900243-2052322"
  58 => "407-1302144-1527513"
  59 => "404-7973091-5177123"
  60 => "171-6477107-0654749"
  61 => "407-2951251-7807562"
  62 => "405-4502563-0626724"
  63 => "407-3317129-1837164"
  64 => "407-3160736-2132352"
  65 => "408-5482505-2974702"
  66 => "406-9690720-6719549"
  67 => "404-3596404-3407556"
  68 => "406-5411121-3703533"
  69 => "408-4500006-3557137"
  70 => "404-8312328-6913101"
  71 => "406-8129500-4807532"
  72 => "408-9474111-9803515"
  73 => "406-7774574-8782767"
  74 => "407-9358549-1105141"
  75 => "407-1133728-5268310"
  76 => "403-6312042-8438708"
  77 => "402-9808661-6449921"
  78 => "402-4028136-3385104"
  79 => "408-1014166-4677917"
  80 => "404-8730180-0323520"
  81 => "171-7038155-6977115"
  82 => "406-9366338-5907557"
  83 => "403-0005577-4393940"
  84 => "408-4910482-2139508"
  85 => "402-9650102-2121903"
  86 => "407-3716531-3309100"
  87 => "406-0822602-7205121"
  88 => "407-8411150-3627538"
  89 => "402-7430814-4097943"
  90 => "408-5041119-1924330"
  91 => "408-7575002-0808337"
  92 => "404-4255373-7244354"
  93 => "407-5210915-8557157"
  94 => "403-5439774-1865941"
  95 => "402-3794660-7624357"
  96 => "402-4843616-3615567"
  97 => "407-6007317-3430761"
  98 => "402-2032150-0868317"
  99 => "171-5831291-2998723"
]
NextToken: RnzVKAPYpdiaJqJYLDm0ZAmQazDrhw3CeUUacWJ5TFJUojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy+y0VVZKEl9LuspXSJW6v/51bBAyHf9lMKdAUiQd9xiFuInTAy+XKVmRZBY+oaVuycwQFure81U/C3FGn+XdtVB94QHwVlk9J2x89dUf46GNof2GLmUGyr9UGnxD0RJmrryegoU0IPZxX3JgSYI+YbKWwzTUE+8P5Y31s4Ruvx7wWMBO/reDY2s+lLK7IMTJG+oWZaQSHenVJIIYkgmdzyCpNQzRAUqdu/u9W9k/g4x4611Ds5w1QtjV2w8niSQCqBjOPK+Zzoe2UF/ggKWw/3K10WfvE9f6gpebkPjaCZnZLlhJsta4Er5aRaNLBSDZucuqlqXPkhrilna280Xppb3C4j82rnQIibuid57EZErUQxZ3Kw6H4OtTybTtm9g5xl6wV403V0q++EQFMgLQm3HqSO+rXZfBZj3qt/y3C2UGZ1NsiWXNVm2lva8glSbtrYzjf4WnzFk+K
^ array:100 [
  0 => "404-9841926-7184314"
  1 => "406-1120300-3233145"
  2 => "403-5293005-4522707"
  3 => "406-0726429-6379522"
  4 => "171-6002267-3585947"
  5 => "171-2293159-0497906"
  6 => "171-1744750-5601150"
  7 => "404-6949232-0439522"
  8 => "402-1511088-3378761"
  9 => "408-2915763-8156303"
  10 => "402-8006018-1521165"
  11 => "402-1705498-4457142"
  12 => "408-7589474-1920335"
  13 => "405-9474614-7195529"
  14 => "408-0373173-8890767"
  15 => "408-3379282-0689120"
  16 => "403-0811589-7497953"
  17 => "171-1027709-4321942"
  18 => "406-4216545-2567556"
  19 => "171-9992756-2234756"
  20 => "171-1918310-9614713"
  21 => "171-6058287-3857129"
  22 => "408-9406763-4641130"
  23 => "171-6067954-4791529"
  24 => "405-6866244-5997144"
  25 => "171-0844712-1601109"
  26 => "402-1150454-3694733"
  27 => "171-7488870-2271545"
  28 => "408-7023248-6264325"
  29 => "408-3809744-3132344"
  30 => "408-8122802-0032327"
  31 => "406-2828130-9663540"
  32 => "405-6179805-3456323"
  33 => "402-2888388-1485956"
  34 => "407-7979381-1037938"
  35 => "406-7086745-2007563"
  36 => "405-9092489-3893155"
  37 => "405-4596091-5804346"
  38 => "403-2377310-7227509"
  39 => "405-8969593-1671532"
  40 => "408-8220346-2617162"
  41 => "402-5542822-4065127"
  42 => "408-8036910-8251538"
  43 => "405-7714500-2660355"
  44 => "402-3202687-2928325"
  45 => "402-5463381-1565905"
  46 => "402-3254093-5170743"
  47 => "407-6313817-1729144"
  48 => "408-0894324-0095557"
  49 => "408-7802873-0797922"
  50 => "403-0228916-7906750"
  51 => "405-6754431-2830750"
  52 => "403-7475186-6833127"
  53 => "404-7377018-5078767"
  54 => "405-6605435-5189166"
  55 => "402-3088488-2364335"
  56 => "402-4881823-7407559"
  57 => "406-8900243-2052322"
  58 => "407-1302144-1527513"
  59 => "404-7973091-5177123"
  60 => "171-6477107-0654749"
  61 => "407-2951251-7807562"
  62 => "405-4502563-0626724"
  63 => "407-3317129-1837164"
  64 => "407-3160736-2132352"
  65 => "408-5482505-2974702"
  66 => "406-9690720-6719549"
  67 => "404-3596404-3407556"
  68 => "406-5411121-3703533"
  69 => "408-4500006-3557137"
  70 => "404-8312328-6913101"
  71 => "406-8129500-4807532"
  72 => "408-9474111-9803515"
  73 => "406-7774574-8782767"
  74 => "407-9358549-1105141"
  75 => "407-1133728-5268310"
  76 => "403-6312042-8438708"
  77 => "402-9808661-6449921"
  78 => "402-4028136-3385104"
  79 => "408-1014166-4677917"
  80 => "404-8730180-0323520"
  81 => "171-7038155-6977115"
  82 => "406-9366338-5907557"
  83 => "403-0005577-4393940"
  84 => "408-4910482-2139508"
  85 => "402-9650102-2121903"
  86 => "407-3716531-3309100"
  87 => "406-0822602-7205121"
  88 => "407-8411150-3627538"
  89 => "402-7430814-4097943"
  90 => "408-5041119-1924330"
  91 => "408-7575002-0808337"
  92 => "404-4255373-7244354"
  93 => "407-5210915-8557157"
  94 => "403-5439774-1865941"
  95 => "402-3794660-7624357"
  96 => "402-4843616-3615567"
  97 => "407-6007317-3430761"
  98 => "402-2032150-0868317"
  99 => "171-5831291-2998723"
]
NextToken: hPYkj6LNSxSaJqJYLDm0ZAmQazDrhw3CeUUacWJ5TFJUojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy+y0VVZKEl9LuspXSJW6v/52hp7K18JkenHnrxT9IcECbInTAy+XKVmRZBY+oaVuycwQFure81U/C3FGn+XdtVB94QHwVlk9J2x89dUf46GNof2GLmUGyr9UGnxD0RJmrryegoU0IPZxX3JgSYI+YbKWwzTUE+8P5Y31s4Ruvx7wWMBO/reDY2s+lLK7IMTJG+oWZaQSHenVJIIYkgmdzyCpNQzRAUqdu/u9W9k/g4x4611Ds5w1QtjV2w8niSQCqBjOPK+Zzoe2Uvg5LxQ+qresQXXucmbXVG24gS8mdPENVtxLIxtev7NTFl9YlFwhxBG9gRgrVJO0APMG4jNqghnlDZBmR6xJsElFWFRtCfy55tspPXiBISAn4eXflOgspfOpiEha25o2rdCbhDHgpTA85n32a+IrXXKm8ERy2ZulUaVNS98yTam8lm/KEU+35Fw==
^ array:100 [
  0 => "404-9841926-7184314"
  1 => "406-1120300-3233145"
  2 => "403-5293005-4522707"
  3 => "406-0726429-6379522"
  4 => "171-6002267-3585947"
  5 => "171-2293159-0497906"
  6 => "171-1744750-5601150"
  7 => "404-6949232-0439522"
  8 => "402-1511088-3378761"
  9 => "408-2915763-8156303"
  10 => "402-8006018-1521165"
  11 => "402-1705498-4457142"
  12 => "408-7589474-1920335"
  13 => "405-9474614-7195529"
  14 => "408-0373173-8890767"
  15 => "408-3379282-0689120"
  16 => "403-0811589-7497953"
  17 => "171-1027709-4321942"
  18 => "406-4216545-2567556"
  19 => "171-9992756-2234756"
  20 => "171-1918310-9614713"
  21 => "171-6058287-3857129"
  22 => "408-9406763-4641130"
  23 => "171-6067954-4791529"
  24 => "405-6866244-5997144"
  25 => "171-0844712-1601109"
  26 => "402-1150454-3694733"
  27 => "171-7488870-2271545"
  28 => "408-7023248-6264325"
  29 => "408-3809744-3132344"
  30 => "408-8122802-0032327"
  31 => "406-2828130-9663540"
  32 => "405-6179805-3456323"
  33 => "402-2888388-1485956"
  34 => "407-7979381-1037938"
  35 => "406-7086745-2007563"
  36 => "405-9092489-3893155"
  37 => "405-4596091-5804346"
  38 => "403-2377310-7227509"
  39 => "405-8969593-1671532"
  40 => "408-8220346-2617162"
  41 => "402-5542822-4065127"
  42 => "408-8036910-8251538"
  43 => "405-7714500-2660355"
  44 => "402-3202687-2928325"
  45 => "402-5463381-1565905"
  46 => "402-3254093-5170743"
  47 => "407-6313817-1729144"
  48 => "408-0894324-0095557"
  49 => "408-7802873-0797922"
  50 => "403-0228916-7906750"
  51 => "405-6754431-2830750"
  52 => "403-7475186-6833127"
  53 => "404-7377018-5078767"
  54 => "405-6605435-5189166"
  55 => "402-3088488-2364335"
  56 => "402-4881823-7407559"
  57 => "406-8900243-2052322"
  58 => "407-1302144-1527513"
  59 => "404-7973091-5177123"
  60 => "171-6477107-0654749"
  61 => "407-2951251-7807562"
  62 => "405-4502563-0626724"
  63 => "407-3317129-1837164"
  64 => "407-3160736-2132352"
  65 => "408-5482505-2974702"
  66 => "406-9690720-6719549"
  67 => "404-3596404-3407556"
  68 => "406-5411121-3703533"
  69 => "408-4500006-3557137"
  70 => "404-8312328-6913101"
  71 => "406-8129500-4807532"
  72 => "408-9474111-9803515"
  73 => "406-7774574-8782767"
  74 => "407-9358549-1105141"
  75 => "407-1133728-5268310"
  76 => "403-6312042-8438708"
  77 => "402-9808661-6449921"
  78 => "402-4028136-3385104"
  79 => "408-1014166-4677917"
  80 => "404-8730180-0323520"
  81 => "171-7038155-6977115"
  82 => "406-9366338-5907557"
  83 => "403-0005577-4393940"
  84 => "408-4910482-2139508"
  85 => "402-9650102-2121903"
  86 => "407-3716531-3309100"
  87 => "406-0822602-7205121"
  88 => "407-8411150-3627538"
  89 => "402-7430814-4097943"
  90 => "408-5041119-1924330"
  91 => "408-7575002-0808337"
  92 => "404-4255373-7244354"
  93 => "407-5210915-8557157"
  94 => "403-5439774-1865941"
  95 => "402-3794660-7624357"
  96 => "402-4843616-3615567"
  97 => "407-6007317-3430761"
  98 => "402-2032150-0868317"
  99 => "171-5831291-2998723"
]

**Comment by adrian-amz** [comment]
Hello @[vamaship-saud-qureshi](https://github.com/vamaship-saud-qureshi),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C.
Selling Partner API Developer Support
