### ISSUE TITLE
Why getOrderItems require restricted token?

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-docs#2092]
Does anyone know why `getOrderItems` is restricted operation?

`getOrderItems` does NOT contain any PII data.  So why?

So if I have 10 unshipped orders I need to ship, I need to make 21 calls:

1. 1 x `getOrders`;
2. 10 `getOrderItems` call, each has its own restricted data token (since resource path is different) so times 2, 20 calls.

Amazon implemented rate limit so that we don't flood their system, on the other hand, their not well designed API forces us to `flood` their system with redundant calls.  Anyone understands this? 

I don't understand.

Why cannot you make `getOrders` call to return everything we need for shipping?

Please explain.

Thanks

**Comment by foxfiring** [comment]
getOrders 可以返回 每个订单的详细 ShippingAddress 。

**Comment by Mike-the-one** [comment]
@foxfiring True, but it doesn't return order items.

**Comment by mjmeli** [comment]
you don't need a new RDT per call, use generic paths as the documentation mentions (https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#terminology). you can share one RDT per hour across all orders calls

**Comment by Mike-the-one** [comment]
> you don't need a new RDT per call, use generic paths as the documentation mentions (https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#terminology). you can share one RDT per hour across all orders calls
> 
> > Generic path. A path in a restricted resource that contains a generic identifier, such as {orderId} or {shipmentId}. For example, orders/v0/orders/{orderId}/address

Thanks!  This helps!

**Comment by jizhouwu** [comment]
Hi Guys,
I have the Role 'Direct-to-Consumer Shipping (Restricted)',  but when my app calls the API '/orders/v0/orders/{orderId}/address', it returns null, how to solve it?

**Comment by rugved1991** [comment]
Hi @jizhouwu,

If the order is in "Pending" status, you would not receive the buyerInfo on the order. Please confirm if you are requesting the order address for an order which is not in "Pending" or "PendingAvailability" status. If you continue to see the issue for a correct order status, please open a developer support case using this [link](https://developer.amazonservices.com/support).

Best,
Rugved
Solutions Architect, SP API

**Comment by jizhouwu** [comment]
> 

Hi rugved1991, 
I just confirmed the order status is shipped, I can get the order info like items, amount, etc. except the address, see below:
class GetOrderAddressResponse {
    payload: class OrderAddress {
        amazonOrderId: 114-aaaaaaa-9999999(hide manually)
        shippingAddress: class Address {
            name: 
            addressLine1: null
            addressLine2: null
            addressLine3: null
            city: PUNTA GORDA
            county: null
            district: null
            stateOrRegion: FL
            municipality: null
            postalCode: 33950-8281
            countryCode: US
            phone: null
            addressType: null
        }
    }
    errors: null
}
