### ISSUE TITLE
Call getCatalogItem method in the CatalogApi class,return a wrong item class

### ISSUE THREAD

**Issue by waha613** [amzn/selling-partner-api-docs#2093]
**I want get an asin infomation,so i Call getCatalogItem method in the CatalogApi class.**
```
 CatalogApi catalogAPI = SellingPartnerAPICatalogUtil.getCatalogAPIInstance(sellingPartnerAPIConfig, accountInfo);

        GetCatalogItemResponse catalogItem = null;
        try {
            catalogItem = catalogAPI.getCatalogItem(accountInfo.getMarketplaceID(), asin);

            Item payload = catalogItem.getPayload();

        } catch (ApiException e) {
            System.out.println(e.getResponseBody());
        }
```
**However, the property of the Item class does not match the attributes I want in the document.
in the document,the item contain:**
<html>
<body>
<h3 class="heading heading-3 header-scroll" align="" style="box-sizing: border-box; margin-top: var(--markdown-title-marginTop,1em); margin-bottom: var(--markdown-title-marginBottom,1rem); line-height: 1.25; color: rgb(79, 90, 102); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: var(--markdown-title-size,1.25em); font-weight: var(--markdown-title-weight,600); display: flex; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center; position: relative; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="heading-text" style="box-sizing: border-box; -webkit-box-flex: 1; flex: 1 1 100%;">Item</div><a aria-label="Skip link to Item" class="heading-anchor-icon fa fa-anchor" href="https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference#item" style="color: inherit; text-decoration: none; display: inline !important; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: 1; font-family: FontAwesome; font-size: 0.8rem !important; text-rendering: auto; -webkit-font-smoothing: antialiased; box-sizing: border-box; transition: all 0.2s ease 0s; opacity: 0; order: -1; right: 800px; margin-right: -0.8rem; transform: translateX(-100%); position: absolute !important; top: unset !important; padding: 0.8rem 0.2rem 0.8rem 0px !important;"></a></h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 15px; color: rgb(79, 90, 102); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An item in the Amazon catalog.</p><div class="rdmd-table" style="box-sizing: border-box; margin-top: 15px; margin-bottom: 15px !important; display: block; position: relative; color: rgb(79, 90, 102); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="rdmd-table-inner" style="box-sizing: content-box; min-width: 100%; overflow: auto; width: 800px;">

Name | Description | Schema
-- | -- | --
Identifiersrequired | The identifiers that uniquely identify the item. | IdentifierType
AttributeSetsoptional | A list of attributes of the item. | AttributeSetList
Relationshipsoptional | A list of variation relationship information for the item. | RelationshipList
SalesRankingsoptional | A list of sales rank information for the item by category. | SalesRankList

</div></div>
</body>
</html>

**the item class in my java program :**
```
package com.amazon.spapi.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

@ApiModel(
    description = "An Amazon order item identifier and a quantity."
)
public class Item {
    @SerializedName("OrderItemId")
    private String orderItemId = null;
    @SerializedName("Quantity")
    private Integer quantity = null;
    @SerializedName("ItemWeight")
    private Weight itemWeight = null;
    @SerializedName("ItemDescription")
    private String itemDescription = null;
    @SerializedName("TransparencyCodeList")
    private TransparencyCodeList transparencyCodeList = null;
    @SerializedName("ItemLevelSellerInputsList")
    private AdditionalSellerInputsList itemLevelSellerInputsList = null;
```

So, how can I get the contents of Item mentioned in the document?
[https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference#item](url)

**Comment by stefnats** [comment]
When generating the Api clients from different models, you chose the same namespace. So the orders item overwrote the catalog item.

**Comment by waha613** [comment]
thank you very much ,my bro

> When generating the Api clients from different models, you chose the same namespace. So the orders item overwrote the catalog item.
