### ISSUE TITLE
GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL

### ISSUE THREAD

**Issue by wu-json** [amzn/selling-partner-api-docs#2096]
It seems like creating reports using the create report API for `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL` gives `FATAL` errors on any timeframes that are older than 18 months. Anyone else experiencing this?

**Comment by waha613** [comment]
When i create report  for `GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA` always give `CANCELED` errors at fisrt time,then i try again,it give me `FALAT` ,when i request for the third time，it give me `Exceeded quota` error！It's always like this for the last few days.

**Comment by fruch17** [comment]
> When i create report for `GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA` always give `CANCELED` errors at fisrt time,then i try again,it give me `FALAT` ,when i request for the third time，it give me `Exceeded quota` error！It's always like this for the last few days.

I have the  same issue in the report GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL always give CANCELED.
Somebody know what is the issue ?

**Comment by xwin1989** [comment]
I also get same problem, 
if i create report for GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL type. create report API return 429 code for me..  
but..  I already wait 2m and re-invoke for this API..
