### ISSUE TITLE
Add An Item To The Seller Inventory Through EAN/GTIN

### ISSUE THREAD

**Issue by yohanbrg** [amzn/selling-partner-api-docs#2098]
Hello, 

Is there a way to add an item to the seller inventory through its EAN/GTIN ? 

I found this endpoint but I don't see which json property to fill to accomplish this (https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#putlistingsitem)

Thanks for your help

**Comment by stefnats** [comment]
You can use Feeds API with Type `POST_FLAT_FILE_INVLOADER_DATA` and then use `product-id-type = EAN`
This is the template for Amazon.de:

https://sellercentral.amazon.de/gp/help/external/G201584910?language=de_DE&ref=efph_G201584910_cont_GPM9AKV2HMSBGCZR#:~:text=Laden%20Sie%20die-,Listing%20Loader%2DVorlage,-herunter%20und%20f%C3%BChren

**Comment by yohanbrg** [comment]
Thanks @stefnats ! 

If someone at Amazon read this, could you please tell me when it will be possible to add an item throught its EAN/GTIN with this endpoint ? https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#putlistingsitem

Thanks
