### ISSUE TITLE
Do reports have UTF-8 encoding now?

### ISSUE THREAD

**Issue by teb02** [amzn/selling-partner-api-docs#21]
Previous API generates reports in ISO-8859-1 encoding (NA). As we see now reports in NA have UTF-8 encoding.
1. Is this correct, encoding of Reports will be UTF-8? 
2. What encoding of Reports will be for Japanese marketplace?

**Comment by evdeg** [comment]
Hello @teb02 ,

Thank you for posting your question about report encoding in Selling Partner API. You are correct. All reports have UTF-8 encoding in SP-API and that applies to all marketplaces.

Thanks,
Evan

**Comment by tusbar** [comment]
@evdeg this is definitely not true.

I am receiving reports encoded in `iso-8859-1` from all marketplaces (tested `GET_MERCHANT_LISTINGS_ALL_DATA` on MX, US, CA, DE, FR).

**Comment by ehrowe** [comment]
UTF-8 is an encoding. ISO-8859-1 is a character set. It indicates how to translate the encoded characters.  ISO-8859-1 is a  Western European character set.  [https://www.charset.org/charsets/iso-8859-1]  If you fail to use the correct character set when decoding an encoded set of characters, you will get ? characters in your decoded result. Most of the time, .NET is able to correctly translate a UTF-8 encoded set of characters. Your database, however, may or may not correctly save the characters. For instance, Chinese and Japanese characters will not display correctly on a database that uses a Latin character set.

**Comment by ynaft** [comment]
I get encoding CP932 for the JP marketplace, like this:

<?xml version="1.0" encoding=CP932"?>

**Comment by xEverth** [comment]
For the same report GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA retrieved via API, if I get it for a North-American based marketplace I have to open with encoding windows-1252, for European countries I need to use utf-8
Is this written in the documentation anywhere or returned in some header when retrieving the report?

**Comment by xEverth** [comment]
EDIT:
![image](https://github.com/amzn/selling-partner-api-docs/assets/8996551/33f0e48a-943c-4b6c-a798-2d4dcbe22cc2)
No that's defeinitely not a tab delimited flat file https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba#remote-fulfillment-eligibility
