### ISSUE TITLE
I have been dev for 7 years and I can say with guarantee this is the WORST documentation I have seen in my life.

### ISSUE THREAD

**Issue by sharedStake-dev** [amzn/selling-partner-api-docs#210]
I can understand typos. I can understand logical errors of mixing AWS with MWS though they are not the same.
BUT
missing code?

uncompilable code?

urls pointing to amazon.com instead of sellercentral.amazon.com?

Horrible documentation, horrible code. Team of 3 devs splitting our hairs over this piece of crappy documentation for weeks and making no headway.

Is there a way startups can get together and donate some money to make this documentation a bit readable and not give migraine every time I scroll by it?

HEY HOW ABOUT AN ACTUAL RESPONSE OR AN APOLOGY? ?!?!

CLOSING AN ISSUE WITH NO RESPONSE IS NOT SUPPORT @seanevan 

BUT HEY BULLY THE COMMUNITY LIKE YOU DO YOUR SUBORDINATES. 
WEVE ALL HEARD OF WHAT MANAGEMENT AT AMZN IS LIKE. 
YOUR ACTIONS ARE SEVERELY DISRESPECTFUL. 
DO YOU EVEN CODE BRO? 

original issue that got closed after 10days with no replies after it went viral on HN
https://github.com/amzn/selling-partner-api-docs/issues/180

**Comment by seanevan** [comment]
Hi @sharedStake-dev, please see my reply on the original issue.

Thanks,
Sean Evans
Manager, Support Engineering
