### ISSUE TITLE
Vendor - Patch Listing Item

### ISSUE THREAD

**Issue by jesusvalle** [amzn/selling-partner-api-docs#2107]
According to the documentation, with the patchListingsItem call, you can send both a sellerId and a vendorcode to update a product.

https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2021-08-01.md#patch-listings2021-08-01itemsselleridsku

With sellers everything works perfect, but with vendors there is no way to update a product, receiving the error:

"Invalid 'sellerId' and 'marketplaceId' combination provided".

The marketplace is correct, it is a spanish account and a spanish product. I have tried to make the call sending both the full vendor code (amzn1.vg.XXXXXXXXX), and sending only the last numbers, but nothing seems to work.

Has anyone managed to update vendor products correctly?

Thank you very much

Call:

```
{
	query: {
		marketplaceIds: ['A1RKKUPIHCS9HS'],
	},
	body: {
		patches: [
			{
				op: 'replace',
				path: 'item_name',
				value: [
					{
						value: 'Title_to_update',
					},
				],
			},
		],
		productType: 'PRODUCT',
	},
	path: {
		sellerId: 'amzn1.vg.XXXXXXX',
		sku: 'XXX',
	},
}
```

**Comment by cypris75** [comment]
Try to use the 5 character vendor code (not amzn1.vg.XXXXXXXXX), e.g. "ABCDE". Most of the time this is what you find in the manufacturerCode with a given product.

**Comment by jesusvalle** [comment]
> Try to use the 5 character vendor code (not amzn1.vg.XXXXXXXXX), e.g. "ABCDE" as the sellerId. Most of the time this is what you find in the manufacturerCode with a given product.

Hello, thank you very much for your help. Unfortunately, in my case, this field is not useful as vendor code.

**Comment by machine-user-typew** [comment]
HI @cypris75 @jesusvalle Is it possible to get this `amzn1.vg.xxx` code from Vendor Central UI?

**Comment by chapmanjw** [comment]
@jesusvalle For vendor submissions, the `sellerId` would be the vendor code (which is visible on the Vendor Central UI).
