### ISSUE TITLE
invalid_client when exchange an LWA authorization code for an LWA refresh token

### ISSUE THREAD

**Issue by ngLynx** [amzn/selling-partner-api-docs#211]
I following the guide to exchange an LWA authorization code for an LWA refresh token.
I face 2 issues:

- content-type: 
the example on the guide using application/x-www-form-urlencoded;charset=UTF-8. but the amazon server return this content type is not supported, so i change to application/json.

- invalide client
I send application json data using 
{
  code: 'XXXX',
  grant_type: 'authentication_code',
  client_id: 'XXXXXX',
  client_secret: 'XXXXX',
 redirect_uri: 'XXXXX'
}
I get errors, say invalid client.
please help.

**Comment by graedwin** [comment]
Hi @ngLynx, We will need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation. 

Thanks,
Javier Villalobos
Selling Partner API Developer Support
