### ISSUE TITLE
[BUG] GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT report is too big

### ISSUE THREAD

**Issue by dishcheng** [amzn/selling-partner-api-docs#2111]
GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT

When I handle this report , memory is out of limit, it is too big

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 769324402 bytes)

**Comment by stefnats** [comment]
Hey there, seems like you are using PHP. Unfortunately this is not an Api error, but an error while parsing the file. So technically, no error on Api side, but seems a very inefficient and memory consuming way in your software.

**Comment by stefnats** [comment]
halaxa / json-machine might be a php package that could help you with that. Again, this is nothing Amazon sp Api specific.
