### ISSUE TITLE
Amazon SPAPI Direct-to Consumer Restricted Access 

### ISSUE THREAD

**Issue by lyzmartin** [amzn/selling-partner-api-docs#2118]
Hello,

We are trying to pull the shipping addresses through getOrderAddress API. We have submitted initially have been rejected.  Since then, we have upgraded our PII Policies and have submitted again with updated answers in the form .

But we got the following answer,

"We evaluate all Public Developer applications that request Restricted SP-API access, for a variety of technical and business criteria including, but not limited to, launch readiness, services offered that can be viewed on a public facing website, and supported geographies."

CASE ID: 9566871831

Can you guide us regarding the response so that we know where we need to improve?

**Comment by purplefish-it** [comment]
Did you get anywhere with this?  We've had exactly the same unhelpful response from Amazon without any explanation of what we can do to resolve it.
