### ISSUE TITLE
For Amazon SP-API how do you close and re-list a listing by API?

### ISSUE THREAD

**Issue by crazybee47** [amzn/selling-partner-api-docs#2119]
In the sellercentral interface i can close listing and re-list closed listing.

![image](https://user-images.githubusercontent.com/32307323/157917192-ebb0c742-76d2-441b-835f-4bb7b4e1985c.png)

I didn’t find these methods in the SP-API. I tried to do this through ListingPutRequest, and loading POST_FLAT_FILE_INVLOADER_DATA feed, specifying “d” in the add-delete column. Unsuccessfully.

Please tell me if there is a way to Close and Re-list listing via the SP-API?

**Comment by johnkw** [comment]
This is a duplicate of bug #1565 - please closed this in favor of the original, which also has some additional information.
