### ISSUE TITLE
added billToParty id in vendor invoice still got following error

### ISSUE THREAD

**Issue by pucsdian** [amzn/selling-partner-api-docs#2124]
Following is the invoice I sent in POST request (values changed for security reason) but structure is as below
{
    "invoices": [
        {
            "shipToParty": {
                "address": {
                    "stateOrRegion": "stateOrRegion",
                    "postalOrZipCode": "postalOrZipCode",
                    "addressLine1": "Amazon.com Services, Inc",
                    "name": "Amazon.com",
                    "city": "city",
                    "addressLine2": "addressLine2",
                    "countryCode": "countryCode"
                },
                "partyId": "partyId"
            },
            "paymentTerms": {
                "discountPercent": "0.0",
                "netDueDays": 30
            },
            "remitToParty": {
                "partyId": "RemitToPartyID"
            },
            "shipFromParty": {
                "partyId": "ShipFromPartyID"
            },
            "invoiceTotal": {
                "amount": "105.0",
                "currencyCode": "USD"
            },
            "items": [
                {
                    "netCost": {
                        "amount": "105.0",
                        "currencyCode": "USD"
                    },
                    "purchaseOrderNumber": "purchaseOrderNumber",
                    "vendorProductIdentifier": "vendorProductIdentifier",
                    "amazonProductIdentifier": "amazonProductIdentifier",
                    "invoicedQuantity": {
                        "amount": 1,
                        "unitOfMeasure": "Eaches"
                    },
                    "itemSequenceNumber": 1
                }
            ],
            "date": "date",
            "id": "InvoiceID",
            "billToParty": {
                "address": {
                    "stateOrRegion": "stateOrRegion",
                    "postalOrZipCode": "postalOrZipCode",
                    "addressLine1": "Amazon.com.indc LLC",
                    "name": "Amazon.com.indc LLC",
                    "city": "city",
                    "addressLine2": "addressLine2",
                    "countryCode": "countryCode"
                },
                "partyId": "partyId"
            },
            "invoiceType": "Invoice"
        }
    ]
}

I got following response when i checked status of invoice, I can understood for remitToParty info is not complete but about other address
{
	"payload": {
		"transactionStatus": {
			"transactionId": "transactionId",
			"status": "Failure",
			"errors": [
				{
					"code": "AmazonlinkTransformError-900034",
					"message": "/invoice/remitToParty[1]: User Command Error: Vendor Postal Code Missing",
					"details": "/invoice/remitToParty[1]"
				},
				{
					"code": "AmazonlinkTransformError-900034",
					"message": "/invoice/billToParty[1]/partyId[1]/partyId: User Command Error: The invoice doesn't caontain bill to country code",
					"details": "/invoice/billToParty[1]/partyId[1]/partyId"
				},
				{
					"code": "AmazonlinkTransformError-900034",
					"message": "/invoice/remitToParty[1]: User Command Error: Vendor Address missing",
					"details": "/invoice/remitToParty[1]"
				},
				{
					"code": "AmazonlinkTransformError-900034",
					"message": "/invoice/remitToParty[1]: User Command Error: Vendor Name missing",
					"details": "/invoice/remitToParty[1]"
				},
				{
					"code": "AmazonlinkTransformError-900034",
					"message": "/invoice/billToParty[1]/address[1]/name[1]/name: User Command Error: Vendor Name missing",
					"details": "/invoice/billToParty[1]/address[1]/name[1]/name"
				}
			]
		}
	}
}

**Comment by MktpStar** [comment]
hi,
have you solved this?
I'm getting the same errors.
thanks!

**Comment by pucsdian** [comment]
@MktpStar 
yes
in my case there is no address in the remitToParty only partyId was there so i added address and it worked
so add address along with id in each party details if possible

**Comment by MktpStar** [comment]
yes, exactly my experience : the order in SP-API only contains billTo partyId and the warehouse code.
in order to send the invoice, it seems that I need to match the warehouse code to an address and, more importantly, to a VAT ID.

but how?
any pointers would be greatly appreciated.
Thank you
