### ISSUE TITLE
Register as Developer menu in the sellercentral-europe.amazon.com?

### ISSUE THREAD

**Issue by sellerfaster** [amzn/selling-partner-api-docs#213]
In the https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#global-applications section, it says:
 _You only need to register as a developer once, in the region and marketplace of your choice, to be able to create a Selling Partner API application that can be authorized by a seller from any region or marketplace._

In the https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-as-a-developer section, it says:
_Sign into Seller Central with the credentials that you want to associate with your developer account. In the **Apps & Services** menu, click Develop Apps._

As I understand from these sections, I can register as developer from any seller-central region for example **sellercentral-europe**. However, in the sellercentral-europe, **there is no Apps and Services menu.**

Can someone help me one this issue?

**Comment by rogersv** [comment]
It is only visible if you have a pro seller account.

**Comment by sellerfaster** [comment]
My seller account is already professional.
But, there is no **Apps & Services** menu. Can this menu be **User Permissions > Visit Developer Credentials**?

Also, I opened my europe (U.A.E) seller account as an individual. Is that matters for developer registration?

thanks in advance.

**Comment by seanevan** [comment]
Hi @sellerfaster, We will need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation. 

Thanks,
Sean Evans
Selling Partner API Developer Support
