### ISSUE TITLE
catalog-items-api Does Not Return The Correct Image

### ISSUE THREAD

**Issue by xbaha** [amzn/selling-partner-api-docs#2133]
When requesting [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#getcatalogitem) for a certain ASIN, If this ASIN is in a variation and it's out of stock, the parent image is returned.

I am unsure if this is the intended behavior, it could be, please advise.

**Comment by stefnats** [comment]
Do you have an example request and response?

**Comment by xbaha** [comment]
No, I do not.
The image link in the response is not the product requested.
