### ISSUE TITLE
LISTINGS_ITEM_STATUS_CHANGE in Notification API

### ISSUE THREAD

**Issue by kairav646** [amzn/selling-partner-api-docs#2134]
Hi ,

I am trying to create subscription of 'LISTINGS_ITEM_STATUS_CHANGE' of notification. It is giving me and error {'code': 'InvalidInput', 'message': 'Request has missing or invalid parameters and cannot be parsed.', 'details': ''}. But all other notification subscription is working fine . 

Thank you

**Comment by stefnats** [comment]
I think you are using SQS for this.
This needs to use Event ridge as stated here:

https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide
