### ISSUE TITLE
ASIN not returned in GET_MERCHANT_LISTINGS_ALL_DATA

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#2137]
We are not getting ASIN in GET_MERCHANT_LISTINGS_ALL_DATA reports for the **amazon.fr** marketplace. Is this a default behaviour or a bug?

**Comment by stefnats** [comment]
I have experienced this too for a long time and I think it is only for listings on FR marketplace that have been listed through EAN (product ID type 4) initially. I think you need to call another Api, for example getPricing in the product pricing Api.

**Comment by evenchengithub** [comment]
I have the same problem, but there is no solution.
