### ISSUE TITLE
Finances API regression from MWS to SP-API (using FinancialEventGroupId and PostedBefore)

### ISSUE THREAD

**Issue by marvs** [amzn/selling-partner-api-docs#2139]
Using the ListFinancialEvents API route on the Finances API for MWS we are able to query for Financial Events by specifying BOTH a FinancialEventGroupId AND PostedAfter + PostedBefore.

https://docs.developer.amazonservices.com/en_US/finances/Finances_ListFinancialEvents.html

It is actually possible to pass in BOTH a FinancialEventGroupId AND PostedAfter + PostedBefore and have it filter results using BOTH of those parameters.
This querying pattern is critical for our application, since we tally financial events on a monthly basis per marketplace (matching the format of the Date Range Reports in Seller Central).
Without querying in this fashion we absolutely cannot fully migrate our application to the new SP-API.

Unfortunately, in the new SP-API in the "Finances API" of the 2 available API endpoints:
https://developer-docs.amazon.com/sp-api/docs/finances-api-reference
* `GET /finances/v0/financialEventGroups/{eventGroupId}/financialEvents`
* `GET /finances/v0/financialEvents`

NEITHER one will accept BOTH a FinancialEventGroupId AND PostedAfter + PostedBefore.
* `GET /finances/v0/financialEventGroups/{eventGroupId}/financialEvents` only accepts the FinancialEventGroupId.
* `GET /finances/v0/financialEvents` only accepts PostedAfter + PostedBefore.

To allow us to migrate, we need one of these 2 API routes to accept BOTH a FinancialEventGroupId AND PostedAfter + PostedBefore.

Any assistance/advice you can provide us on this issue would be greatly appreciated.

Sample requests:

**GET /finances/v0/financialEvents**

* x-amzn-requestid: `125df6a4-bf40-44a2-8729-03ef95934f19`

This request returns an error since the FinancialEventGroupId is not recognized.

**GET /finances/v0/financialEventGroups/{eventGroupId}/financialEvents**

* x-amzn-requestid: `132379ff-a809-4d71-af03-88dd3f439848`

This request contains the PostedAfter and PostedBefore parameters but it does not filter the response (it ignores the supplied dates).

**Comment by hehengkaifj** [comment]
i have same question

**Comment by ynaft** [comment]
We have the same issue. 
Is there any solution for this?

**Comment by ynaft** [comment]
Still a relevant issue, causing big problems

**Comment by histonedev** [comment]
I agree, this is a critical issue. may cause alot of issues

**Comment by marvs** [comment]
Amazon now added the `PostedAfter` and `PostedBefore` parameters to the `listFinancialEventsByGroupId` endpoint, so this has been resolved.

https://developer-docs.amazon.com/sp-api/docs/finances-api-reference#listfinancialeventsbygroupid
