### ISSUE TITLE
Error when passing multiple `marketplaceIds` to the FeedAPI

### ISSUE THREAD

**Issue by daris-trngl** [amzn/selling-partner-api-docs#2141]
I'm trying to create a **POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA** Feed, passing multiple `marketplaceIds`, but it seems to not work.

If I use an array with only one id in the `marketplaceIds` field (i.e. `['APJ6JRA9NG5V4']`) it works correctly, but when I try using an array of multiple ids (i.e. `['APJ6JRA9NG5V4', 'A13V1IB3VIYZZH']` ) I get the following error:

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]
}
```
Despite the fact that it should accept an array of string, as per the official documentation.

Is this a correct behavior specific for this Feed Type? Unfortunately I haven't found any explanation in the API documentation and the only explanation I can think of is related to the lack of currency in the price field, which could generate errors when affecting multiple marketplaces.

In this case, therefore, I will have to create a feed for each interested marketplace. Right?
Is there anyone else who has encountered this same problem and found a solution?

Thanks in advance.

**Comment by stefnats** [comment]
This is a feed for updating price and quantity. Let's say you specify marketplace ids for France and UK. Now, you want to change the price to 10. In this case, the price is not distinct, because there are different currencies.

Because of that, I think it is working as expected.

**Comment by jlevers** [comment]
+1 to what @stefnats said -- you can't upload price and quantity data for more than one marketplace at a time, since many marketplaces use different currencies, and you may have different quantities available in different marketplaces. You'll have to upload a separate feed for each marketplace you want to update.

**Comment by daris-trngl** [comment]
Ok so it's a currency related issue, as I suspected, but I still wanted to be sure as it's not explicitly stated and maybe I was using the wrong approach.
Thanks to both of you for confirming.
