### ISSUE TITLE
May I ask which interface can get platform commission

### ISSUE THREAD

**Issue by shkingve** [amzn/selling-partner-api-docs#2143]
I've been looking for it for a long time

**Comment by stefnats** [comment]
Just to clarify, do you mean the referral fees of an order?

**Comment by shkingve** [comment]
yes

**Comment by stefnats** [comment]
Then you should take a look at the finances Api. It states the fees that have been charged for every order.

**Comment by shkingve** [comment]
Thanks,I found it.

**Comment by Abbotton** [comment]
Hi, @shkingve , Can you share which api specifically it is? Thanks．
