### ISSUE TITLE
[BUG] Documentation FulFillment-Inbound getShipmentItemsByShipmentId Bug and inconsistent workflow in endpoint

### ISSUE THREAD

**Issue by JacksonJeans** [amzn/selling-partner-api-docs#215]
**Describe the bug**
The error affects the documentation itself and the domain logic of the `getShipmentItemsByShipmentID` operation.

I only ever get the same response from this operation from the second request using `NextToken`.

In my opinion, the API should only set `NextToken` as required instead of `MarketplaceId` and `shipmentId` in combination with the `NextToken`.

If I omit the MarketplaceId and shipmentId in the second call and only specify the NextToken, my call is invalid.

**URL of the content on GitHub**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getShipmentItemsByShipmentId](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getShipmentItemsByShipmentId)

[https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#GetShipmentItemsResult](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#GetShipmentItemsResult)

**Description of what the documentation currently says**

Currently, the operation is based on the assumption that no `NextToken` can be specified and that the entire list of items sent with the shipment can be found in ItemData in one call.

getShipmentItemsByShipmentId Operation:
Type | Name | Description | Schema
-- | -- | -- | --
Path | shipmentId  required | A shipment identifier used for selecting items in a specific inbound shipment. | string
Query | MarketplaceId  required | A marketplace identifier. Specifies the marketplace where the product would be stored. | string

GetShipmentItemsResult:
Name | Description | Schema
| ---- | ---- | ---- |
|   ItemData   |   A list of item information for an inbound shipment.   |   InboundShipmentItemList   |
|   NextToken   |   When present and not empty, pass this string token in the next request to return the next response page.   |    string  |

**Description of what the documentation should say**
The documentation should state, already in the operation, whether a NextToken can be specified as a parameter and whether MarketplaceId and shipmentId must also be specified in the second call.

Currently, the documentation regarding the operation does not indicate that a NextToken is expected or can be specified. Unlike the documentation for, for example, the Order, Feeds and Report API.

**Additional context**
In addition, the inbound interface does not work consistently against the orders, reports, and feeds endpoints. 
The query string in the URI must not be preceded by "/", which is necessary in the other requests. This also applies to the calculation and creation of the signature for the canonical request. 

For example:
My URI for orders: 
getOrder:
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/408-9433449-0649117/
is valid.

and here with query string:
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/?LastUpdatedAfter=2020-12-15T23%3A00%3A00&MarketplaceIds=A1805IZSGTT6HS&MarketplaceIds=A1PA6795UKMFR9&MaxResultsPerPage=100
is valid.

In the InboundAPI, however:

getTransportDetails:
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/transport
is valid.

https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/transport/ 
will be invalid.

and here with query string:
getShipmentItemsByShipmentId
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/items?MarketplaceId=A1PA6795UKMFR9&shipmentId=FBA15DDQDL4V

is valid.

https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/items/?MarketplaceId=A1PA6795UKMFR9&shipmentId=FBA15DDQDL4V

will be invalid.

Finding that out first was very hard.

**Comment by SHAXperiment** [comment]
I can confirm the issue. I have the same problem.

**Comment by parvathm** [comment]
Hi @JacksonJeans ,

We appreciate your feed back. I have forwarded your feedback to our documentation team and we are also looking into why getShipmentItemsByShipmentId is not returning valid response when NextToken is given in the request . I will provide an update here once we have a solution.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by JacksonJeans** [comment]
@parvathm Thanks a lot.

A little additional info afterwards:
I have now also noticed that the shipment I queried for test purposes also only contains one SKU. Normally I should not receive a NextToken anymore, because no further result can be expected.

Here is the original answer from my query:
```
object(XXXXX\Amazon\FulfillmentInbound\GetShipmentItemsResult)#30 (2) {
  ["ItemData"]=>
  object(XXXXX\Amazon\FulfillmentInbound\InboundShipmentItemList)#29 (1) {
    ["storage":"ArrayObject":private]=>
    array(1) {
      [0]=>
      object(XXXXX\Amazon\FulfillmentInbound\InboundShipmentItem)#6 (8) {
        ["ShipmentId"]=>
        string(12) "FBA15DDQDL4V"
        ["SellerSKU"]=>
        string(15) "T011-23809-1016"
        ["FulfillmentNetworkSKU"]=>
        string(10) "X00185OW6R"
        ["QuantityShipped"]=>
        int(36)
        ["QuantityReceived"]=>
        int(36)
        ["QuantityInCase"]=>
        int(0)
        ["ReleaseDate"]=>
        NULL
        ["PrepDetailsList"]=>
        object(XXXXX\Amazon\FulfillmentInbound\PrepDetailsList)#27 (1) {
          ["storage":"ArrayObject":private]=>
          array(2) {
            [0]=>
            object(XXXXX\Amazon\FulfillmentInbound\PrepDetails)#34 (2) {
              ["PrepInstruction"]=>
              string(8) "Labeling"
              ["PrepOwner"]=>
              string(6) "SELLER"
            }
            [1]=>
            object(XXXXX\Amazon\FulfillmentInbound\PrepDetails)#33 (2) {
              ["PrepInstruction"]=>
              string(11) "Polybagging"
              ["PrepOwner"]=>
              string(6) "SELLER"
            }
          }
        }
      }
    }
  }
  ["NextToken"]=>
  string(500) "AAAAAAAAAQCD/QA1BXF2+SY5OQ+nFnApVgEAAAAAAACBjTLyULFH/VZii+93jYlvbCZM2VNti5Y5Jb/KIfMfF4RYtketSllP4Perpoy848yWbB9cVi4UfYE4jZVONOi3xQPGSPzieuEC8qVSsVETJn0/UYRAS9X29+3UsAUE/ZudaOWyl79NqrK0Fiz/sbLxT22CDaek8k5arnGywdj3dEx1o66D6prgCqd6K6vsidMwh9lh+dBbmdlt1vdkT5EeiCSaeshyRRvGauBXs/XWtX9V7mmJHf53DQPOMPd6ZDuATx3MKNDEMUmoPEVSzmMI5eS2UgXYq/AgfZCzzjaB3bAOSoVJzrPqOoCfa6oBRynUxkdbgb3P2HQYL/E4FSV8q5N8tCkaLfKn9kuCm3u+oHtmbH5exAKTzdUPVlXErZ3AZLG4ljMU8kkWfLaePx1tiH2zyFwW3V59fqCAkZeEhI3EbB7Gf5xhMyE35CS9jgjSKWQ2Yio="
}
```

**Comment by parvathm** [comment]
Hi @JacksonJeans ,

We are working on addressing the inconsistencies around orders, reports, and feeds endpoints with extra slash at the end. 
Regarding getShipmentItemsByShipmentId Operation it doesn't take the NextToken in the request. I think you need to use getShipmentItems with marketplace id and NextToken.

Can you please open a [support case](https://developer.amazonservices.com/support) regarding issue with one SKU returning NextToken if you think NextToken is not valid and doesn't have any data.

**Comment by johnkw** [comment]
The comment above regarding "NextToken" being incorrectly included when there is no next page is almost identical to bug #321 except the above is for GetShipmentItemsResult and bug #321 is for getshipmentsresult.  This may warrant another separate ticket if bug #321 is fixed separately from this being fixed?

**Comment by kingsun-he** [comment]
When I try to use getShipmentItemsByShipmentId, the max numbers of items returned is 200. If I have more than 200 items, I can't get all my items Because the nexttoken doesn't work.

**Comment by joyceeeen** [comment]
No updates on this?

**Comment by cpiggott** [comment]
> 

I've had a ticket open for almost 7 months in regards to the nextToken issues on SP-API with the generic "I'm sending you an update to ensure you we are working towards a resolution of this issue."

It's the same canned message every three to four days with no real progress seen on the outside. I genuinely hope they are working on this, but I don't see it being fixed anytime soon...

**Comment by nhaustov** [comment]
To clarify the problem here - it is possible to get more items if getShipmentItemsByShipmentID returns 200 items. You just have to use [getShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitems) with QueryType=NEXT_TOKEN and NextToken obtained from getShipmentItemsByShipmentID. However, this is definitely not obvious from the documentation.

The other problem mentioned in the thread does exist - getShipmentItemsByShipmentID always returns NextToken in the response, even if the number of items in the shipment is small (<200). So if you are not careful, you will request getShipmentItems with this NextToken and get empty array in the response, wasting a request and (already low) rate limits. A workaround is to check the number of items in the response and skip getShipmentItems request if it is < 200 even if there is NextToken. It would be good if this problem was fixed though.

**Comment by SH-SierraSierra** [comment]
Can confirm this is still an issue. @nhaustov I tried your suggestion for getting shipment items past the initial 200 returned, but I got a 400 error with the message "Invalid NextToken". Do you have any more detail you could provide in terms of query parameters passed to getShipmentItems?

**Comment by johnkw** [comment]
Please turn this horrible bot off and only close the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon @jenilew @parvathm

**Comment by Brit4sh** [comment]
This is still an issue, exactly as described.

**Comment by elliottwood80** [comment]
Coincidentally, I'm also having this same issue as described. Is there any chance of an update @parvathm

**Comment by mtarique** [comment]
Hi,

I solved this but I have to look at their API code getShipmentItems() method in PHP jlevers selling partner API for correct order of parameters and obviously yes it's not clearly mentioned in their documentation -

So, for example in order to make getShipmentItems api call with next token we have to make it in this way
`$api->getShipmentItems('NEXT_TOKEN', $mpId, null, null, $nextToken);`

**API code getShipmentItems() method in PHP jlevers selling partner API**

```
/**
     * Operation getShipmentItems
     *
     * @param  string $query_type Indicates whether items are returned using a date range (by providing the LastUpdatedAfter and LastUpdatedBefore parameters), or using NextToken, which continues returning items specified in a previous request. (required)
     * @param  string $marketplace_id A marketplace identifier. Specifies the marketplace where the product would be stored. (required)
     * @param  string $last_updated_after A date used for selecting inbound shipment items that were last updated after (or at) a specified time. The selection includes updates made by Amazon and by the seller. Must be in ISO 8601 format. (optional)
     * @param  string $last_updated_before A date used for selecting inbound shipment items that were last updated before (or at) a specified time. The selection includes updates made by Amazon and by the seller. Must be in ISO 8601 format. (optional)
     * @param  string $next_token A string token returned in the response to your previous request. (optional)
     *
     * @throws \SellingPartnerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SellingPartnerApi\Model\FbaInboundV0\GetShipmentItemsResponse
     */
    public function getShipmentItems($query_type, $marketplace_id, $last_updated_after = null, $last_updated_before = null, $next_token = null)
    {
        $response = $this->getShipmentItemsWithHttpInfo($query_type, $marketplace_id, $last_updated_after, $last_updated_before, $next_token);
        return $response;
    }
```
**If your next token contains any next pages it will return them if not it will simply returns nothing**
