### ISSUE TITLE
[BUG] getListingsItem don't return any attributes

### ISSUE THREAD

**Issue by piotr-lottestyle** [amzn/selling-partner-api-docs#2151]
**Describe the bug**

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2021-08-01.md

**Description of what the documentation currently says**
attributes in getListingsItem response returns ItemAttributes

**Description of what the documentation should say**
attributes in getListingsItem response returns null, always

**Screenshots**
-

**Additional context**
-

**Comment by stefnats** [comment]
I see you closed the issue, what was the solution?

**Comment by piotr-lottestyle** [comment]
@stefnats I added includedData=issues,attributes,summaries,offers,fulfillmentAvailability and everything works

**Comment by Braveman1999** [comment]
> @stefnats我添加了includedData=issues、attributes、summaries、offers、fulfillmentAvailability，一切正常。
> 
> 文档没问题：
> 
> ```
> GET https://sellingpartnerapi-na.amazon.com/listings/2021-08-01/items/AXXXXXXXXXXXX/50-TS3D-QEPT
>   ?marketplaceIds=ATVPDKIKX0DER
>   &issueLocale=en_US
>   &includedData=issues,attributes,summaries,offers,fulfillmentAvailability
> ```

**Comment by Braveman1999** [comment]
can you get 'attribute' info?

**Comment by Braveman1999** [comment]
> can you get 'attribute' info?

attribute  corresponds to ItemAttribute.class in the SDK,but ItemAttribute.class no field.   all of which are override methods
