### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by willytjandra** [amzn/selling-partner-api-docs#2152]
We're building an app for public application using selling partner API. Is there a way to test our code without using real seller data? i.e. authorization? Currently we have registered an application with Amazon. Obviously we do not want to use production app for testing.

Do we need to register a new app for development purpose? It seems overkill. We looked at sandbox, it seems like it still needs to have real seller access token to fetch mock data. Is this correct?

Cheers,

**Comment by lobotomisador** [comment]
@willytjandra there is no way to test it without a real seller. You can use the sandbox with the real seller to prevent touching real data.
