### ISSUE TITLE
[FEATURE] GET /catalog/2020-12-01/items - Add `attributes` for `IncludedData`

### ISSUE THREAD

**Issue by fegbers** [amzn/selling-partner-api-docs#2153]
**Describe the improvement**
Add the ability to also request `attributes` as part of the `IncludedData` query parameter for the [searchCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#get-catalog2020-12-01items) endpoint. This could reduce additional requests to the [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#getcatalogitem) endpoint for each resolved ASIN, e.g. to retrieve package dimensions.

**URL of the content on GitHub**
- [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#getcatalogitem) 
-  [searchCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#get-catalog2020-12-01items)
- [includeddata](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#includeddata)

**Description of what the documentation currently says**
Currently it is not possible to request `attributes` as part of the `IncludedData` query parameter (correctly documented!).

**Description of what the documentation should say**
[getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#getcatalogitem) and [searchCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#get-catalog2020-12-01items) should have the same `IncludedData` possibilities to be able to use these APIs interchangeable (e.g. request via EAN (searchCatalogItems) or ASIN (getCatalogItem)).

The issue is also created in the [selling-partner-api-models-Repository](https://github.com/amzn/selling-partner-api-models/issues/233).

**Comment by littleylv** [comment]
I think this should be available in the version. See #2017 

> The getCatalogItem and searchCatalogItems provide access to the same sets of data (i.e., attributes available on the searchCatalogItems operation).

**Comment by fegbers** [comment]
> I think this should be available in the version. See #2017
> 
> > The getCatalogItem and searchCatalogItems provide access to the same sets of data (i.e., attributes available on the searchCatalogItems operation).

@littleylv  Thanks for pointing that out, I didn't see the discussion.
