### ISSUE TITLE
[Rate Limits] Are some rates worse for SP-API compared to MWS?

### ISSUE THREAD

**Issue by callumb123** [amzn/selling-partner-api-docs#216]
There are 2 endpoints that on the face of it appear to have much worse rate limits than their MWS equivalent.

getMyFeesEstimateForASIN - SP-API has a rate of 1 per second with a max of 1 ASIN per request. The MWS equivalent (GetMyFeesEstimate) has a rate of 10 per second with 20 ASINs per request.

getCompetitivePricing - SP-API has a rate of 1 per second with 20 ASINs per request. MWS (GetCompetitivePricingForASIN) has a rate of 10 per second with 20 ASINs per request.

Please let me know if I have read this wrong but if not this will make it very difficult for me to fully move to SP-API.

**Comment by cgaugel** [comment]
Are here any news?

**Comment by xiaoyu-tamu** [comment]
both are 10 per second.

**Comment by radixdt2480** [comment]
can you please give call getCompetitivePricing  how we get pricing using sp api
