### ISSUE TITLE
Reports API Endpoint - Cancelled Reports

### ISSUE THREAD

**Issue by benkingery** [amzn/selling-partner-api-docs#2162]
I have been using MWS API for Reports successfully for years.  I am developing new engine internally to request/download/consume Reports Endpoint for SP-API.

All of the reports that I request are coming back "CANCELLED".  Can anyone help me know why these are all coming back as Cancelled?  Below is a list of report types that I am requesting.

GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING (I understand this one may be because I have not called it with RDT)
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA
GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA

**Comment by webs-harsh-rana** [comment]
I have the same issue with the new sp API for the below Reports, anyone has a solution for this?

1. GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
2. GET_RESERVED_INVENTORY_DATA
3. GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA
4. GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA

All above reports are working properly on mws API.

**Comment by puppsupr** [comment]
Hello,

If you are still facing this issue, in order to correctly resolve it, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API

**Comment by webs-harsh-rana** [comment]
@puppsupr 

How can we fix the issue in SP API Reports CANCELLED Reports?

In the FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA reports, when we call them from local, we get a DONE status, but a CANCELLED status when we call them from my Production Server.

Can you please provide some information on how I can resolve this issue? 

Thanks for your support.
