### ISSUE TITLE
Sponsored brand Video - API calls 

### ISSUE THREAD

**Issue by himanshu29-tech** [amzn/selling-partner-api-docs#2166]
We are making advertising API calls for our multiple clients. While we are requesting data for the "Sponsored Brands" campaigns type we are not receiving the data for Sponsored brand Video campaigns within the portfolio. I cannot see an exception for video ads in the advertising API documentation, https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi#/Campaigns/listCampaigns.

Can you please have a look into this? Is there a separate API call needed for video ads?

Thanks

**Comment by sungolivia** [comment]
Hi @himanshu29-tech  it sounds like this is related to Ads API, please refer to below link to contact their technical support team!
https://advertising.amazon.com/API/docs/en-us/info/support

Thanks!
