### ISSUE TITLE
Vendors - Vendor Code, listings, catalog

### ISSUE THREAD

**Issue by ayushchd** [amzn/selling-partner-api-docs#2169]
I was playing around with the SP API for a vendor account in `IN`. I am running into the following issues and I couldn't find clear documentation around these.

1. How can I get all listings for a particular vendor? I would like the image, title, price, ASIN, SKU, etc for everything that is in the vendor's catalog. On the UI, it's available at this URL: `https://www.vendorcentral.in/hz/vendor/members/products/mycatalog`
2. I tried using the [Catalog V0 API](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference) but kept getting `Access Denied` error. The [newer catalog API](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2020-12-01-reference), does not give price information and is for the entire Amazon catalog and I don't see a way to get all products only of the vendor whose credentials I am using.
3. The Listings API works, but I need to know the SKU and vendor code before hand. I am unclear on how I can get all SKU/vendor codes combinations at once. Is there a way to get the vendor codes?
4. I've also tried using the Inventory report but it says the report type isn't supported for vendor groups.

In general, is there a guide available on what functionalities are supported for vendors vs sellers?

**Comment by jesusvalle** [comment]
For now (as far as I have been able to see), there is no call to see the total list of vendor products, as well as vendorCodes and so on. 

This is essential, and the vendor part is still very underdeveloped by Amazon.

**Comment by ayushchd** [comment]
Hi @puppsupr that doesn't really help. 

Would you be able to help me with specific questions that I've posted above?

**Comment by ThanhLuan0932** [comment]
> I was playing around with the SP API for a vendor account in `IN`. I am running into the following issues and I couldn't find clear documentation around these.
> 
> 1. How can I get all listings for a particular vendor? I would like the image, title, price, ASIN, SKU, etc for everything that is in the vendor's catalog. On the UI, it's available at this URL: `https://www.vendorcentral.in/hz/vendor/members/products/mycatalog`
> 2. I tried using the [Catalog V0 API](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference) but kept getting `Access Denied` error. The [newer catalog API](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2020-12-01-reference), does not give price information and is for the entire Amazon catalog and I don't see a way to get all products only of the vendor whose credentials I am using.
> 3. The Listings API works, but I need to know the SKU and vendor code before hand. I am unclear on how I can get all SKU/vendor codes combinations at once. Is there a way to get the vendor codes?
> 4. I've also tried using the Inventory report but it says the report type isn't supported for vendor groups.
> 
> In general, is there a guide available on what functionalities are supported for vendors vs sellers?

Hi @ayushchd, did you solved your problem ? I have same issue when used C# code with SP-API with developer console of vendorcentral.amazon.com. I can't call any API from doc https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference. Error "Access to requested resource is denied"
![Picture3](https://user-images.githubusercontent.com/33895995/178448983-22d8027f-a15e-4e9b-8538-7061b920b5ae.png)
