### ISSUE TITLE
[Feature] Seller restricted on product

### ISSUE THREAD

**Issue by callumb123** [amzn/selling-partner-api-docs#217]
I don't believe there are any endpoints that can achieve this yet and so wanted to make a request.

It would be very useful to have an endpoint (or addition to existing endpoint) that lets us check if a seller is eligible to sell a particular product. For example, most sellers are unable to sell Nike products due to it being a restricted brand. We should be able to get this information from the API instead of forcing the seller the check this manually.

**Comment by fr3shn3ss** [comment]
There is an API for this. I haven't used if myself though
https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-restrictions-api/listingsRestrictions_2021-08-01.md

**Comment by rugved1991** [comment]
Hi @callumb123,

Please check out the [Listing Restrictions API](https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-restrictions-api/listingsRestrictions_2021-08-01.md) for more information about any restrictions for a listing. I will close this issue as this feature is now available through API. If you have any questions or issues, feel free to open new issue.

Best,
Rugved
Solutions Architect, SP API
