### ISSUE TITLE
Getting data which matches Custom Unified Transaction Report via sp-api

### ISSUE THREAD

**Issue by ninad-measured** [amzn/selling-partner-api-docs#2170]
There is a report generated from seller central via the following steps:

1. Login to seller central.
2. Click on left menu and go to Payments.
3. In Payments Dashboard, click on Date Range Reports.
4. Generate a Transaction Report for a specific date range.
5. It shows up as Custom Unified Transaction Report in the list to download.

I'm trying to get data from the API which matches this data. I could not find a specific report to get this here: https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md

I have attempted to get data using [orders](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorders) and [orderItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorderitems) API .

However the total revenue in these orders never seem to match. I'm comparing totals of product sales column in the UI report to the ItemPrice->Amount column (From orderItems API). I'm aware that the UI report is in PST and API report is in UTC and have accounted for that when comparing. I've also tried with both CreatedAfter-CreatedBefore and LastUpdatedAfter-LastUpdatedBefore yet no match.

Am I using the right API to get the data I need?
Is there is another report that can be generated via API which matches exactly with the Custom Unified Transaction Report?

**Comment by ezpinsky** [comment]
The Settlement reports seem have the same information as date range try using the GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 report

**Comment by Sasireka2198** [comment]
Anyone have download this report? I'm keep getting "Request for report type 1118 is not allowed at this time" error message whenever I try create request for this report.
