### ISSUE TITLE
I can't upload feed content with Postman

### ISSUE THREAD

**Issue by waha613** [amzn/selling-partner-api-docs#2176]
I want to submit a Feed request which feed typy is POST_FLAT_FILE_FBA_CREATE_REMOVAL.

Follow the steps stated in the sp-api documentation,
I create a feed document,get the url and documentId at first,
Then I need to upload the content from the URL I got in the previous step，
there is just have a simple code example in the sp-api documentation,
![image](https://user-images.githubusercontent.com/91399025/162133135-0c8f448f-d3be-4276-999e-199738b53ea0.png)

So, I followed the sample code and sent a put request with postman.
![image](https://user-images.githubusercontent.com/91399025/162134056-f891e013-4d39-40ed-8f18-4dd9aa81fe26.png)

I try to choose form-data, x-www-form-urlencoded, raw or binary, but it all prompts that the signature is wrong.

so, how do I need to do to upload feed content through postman.

**Comment by lobotomisador** [comment]
@waha613 this is not related to the form-data, but rather to the Signature in the headers.
Double check that you are generating the Authentication header correctly. https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by rohitdobariyaleanspace** [comment]
@waha613 can you share a sample flat file please? I need this.
