### ISSUE TITLE
x-mws-quota Information missing on POST /feeds/2021-06-30/feeds

### ISSUE THREAD

**Issue by cgaugel** [amzn/selling-partner-api-docs#2178]
@parvathm 

I am missing the following information on POST a new Feed to the /feeds/2021-06-30/feeds Endpoint:

- x-mws-quota-max
- x-mws-quota-remaining
- x-mws-quota-resetsOn

Those header resonses exists in MWS but not in SP-API anymore. We need this headers to handle File-Uploads for several countries.

For example, I have a customer with marketplaces in Germany, Italy, Spain, Netherlands, Poland and France. Now, if I have done 10 uploads for Germany, how do I know how many times I am allowed to upload for each of the other countries?

You cant remove headers you are sending in MWS.

**Comment by stefnats** [comment]
Hey Chris,

I can't provide a source, but I'm pretty sure, that I read recently either here or in the Api models repo that those headers have been removed, maybe even only for the feeds Api.

While this is very inconvenient for some use cases, Amazon provides a rate limiter interface in their swagger codegen templates for Java and c#. So, im not speaking for Amazon, but the best approach here would be to handle this client wise or library wise.
