### ISSUE TITLE
sp-api UPLOAD_VAT_INVOICE 403 Access to the resource is forbidden

### ISSUE THREAD

**Issue by kdfhhao** [amzn/selling-partner-api-docs#2179]
When migrating from MWS to SP-API, the PII invoice information will be cancelled by default, and the developer profile needs to be re-edited to apply for tax invoices (limited) to generate tax invoices that comply with tax regulations. Tax remittance (limited) permissions.

**Comment by sungolivia** [comment]
Hey @kdfhhao not sure if you are still running into this issue, can you re-open and describe the issue further?

**Comment by kdfhhao** [comment]
Thanks, it has been resolved.



***@***.***
 
From: Olivia Sung
Date: 2022-05-10 08:12
To: amzn/selling-partner-api-docs
CC: kdfhhao; Mention
Subject: Re: [amzn/selling-partner-api-docs] sp-api UPLOAD_VAT_INVOICE 403 Access to the resource is forbidden (Issue #2179)
Closed #2179.

**Comment by alexanderkalkbrenner** [comment]
Hello, I have the same issue: 

We are a seller and private developer account based in Germany. We try to upload our invoices via the UPLOAD_VAT_INVOICE feed and get the same error:

REQUEST: 

POST [https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/feeds HTTP/1.1](https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/feeds%20HTTP/1.1)

{
    "feedType":"UPLOAD_VAT_INVOICE",
    "marketplaceIds":["A1PA6795UKMFR9"],
    "inputFeedDocumentId":"amzn1.tortuga.4.eu.4ad92713-cb83-4356-af66-4e2ca7d8d8b2.T3L3HLA1X80UCV",
    feedOptions: {
        "metadata:orderid": "3xx-14xxxxx-1458xxx",
        "metadata:documenttype": "Invoice",
        "metadata:invoicenumber": "F30417xxxxx"
    }
}

RESPONSE:


{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}

Our App has set all available permissions; but i am not sure if there would have to be more options?

<img width="815" alt="Bildschirmfoto 2024-04-05 um 14 05 52" src="https://github.com/amzn/selling-partner-api-docs/assets/26714476/cc18f2cc-6b4f-4afd-8b41-488599ee7a2b">
