### ISSUE TITLE
getEligibleShipmentServices (Merchant Fulfillment): Has anyone been able to successfully call this in the sandbox using C#?

### ISSUE THREAD

**Issue by BeeBee234** [amzn/selling-partner-api-docs#218]
Howdy Hi,

Has anyone been able to successfully call getEligibleShipmentServices (Merchant Fulfillment) in the sandbox using C#?  

I'm getting a 'Access denied/Unauthorized/Forbidden' response for the following, using the example code (which works - see further below) in https://github.com/amzn/selling-partner-api-models/issues/31 :

            var resource = $"/mfn/v0/eligibleShippingServices";
            IRestRequest restRequest = new RestRequest(resource, Method.POST); //NOT "GET"!
            restRequest.AddParameter("ShipmentRequestDetails", "{\"AmazonOrderId\": \"903-5563053-5647845\",\"ItemList\": [{\"OrderItemId\": \"52986411826454\",\"Quantity\": 1}]}", ParameterType.QueryString);
            restRequest.AddParameter("ShipFromAddress", "{\"Name\": \"John Doe\",\"AddressLine1\": \"300 Turnbull Ave\",\"Email\": \"jdoeasdfllkj@yahoo.com\",\"City\": \"Detroit\",\"StateOrProvinceCode\": \"MI\",\"PostalCode\": \"48123\",\"CountryCode\": \"USA\",\"Phone\": \"7132341234\"}", ParameterType.QueryString);
            restRequest.AddParameter("PackageDimensions", "{\"Length\": 10,\"Width\": 10,\"Height\": 10,\"Unit\": \"inches\"}", ParameterType.QueryString);
            restRequest.AddParameter("Weight", "{\"Value\": 10,\"Unit\": \"oz\"}", ParameterType.QueryString);
            restRequest.AddParameter("ShippingServiceOptions", "{\"DeliveryExperience\": \"NoTracking\",\"CarrierWillPickUp\": false,\"CarrierWillPickUpOption\": \"ShipperWillDropOff\"}", ParameterType.QueryString);
  
I CAN make a successful call to the following endpoint using the C# sample code from https://github.com/amzn/selling-partner-api-models/issues/31 after many iterations and many 'Access denied/Unauthorized/Forbidden' responses, which tells me that my credentials are set up properly and that 'Access denied' is bogus:

            var resource = $"/vendor/orders/v1/purchaseOrders";
            IRestRequest restRequest = new RestRequest(resource, Method.GET);
            restRequest.AddParameter("createdAfter", "2019-08-20", ParameterType.QueryString);
            restRequest.AddParameter("createdBefore", "2019-09-21", ParameterType.QueryString);

Thank you very much and have a splendid day,

Brian

**Comment by BeeBee234** [comment]
FYI, it looks like the following is the correct syntax:

            var resource = $"/mfn/v0/eligibleShippingServices";
            IRestRequest restRequest = new RestRequest(resource, Method.POST);
            //create GetEligibleShipmentServicesRequest object
            GetEligibleShipmentServicesRequest request = new GetEligibleShipmentServicesRequest();
            ShipmentRequestDetails requestDetails = request.ShipmentRequestDetails;
            requestDetails.AmazonOrderId = "903-5563053-5647845";
            Item item = new Item();
            requestDetails.ItemList.Add(item);
            requestDetails.ItemList[0].OrderItemId = "52986411826454";
            requestDetails.ItemList[0].Quantity = 1;
            requestDetails.ShipFromAddress.Name = "John Doe";
            requestDetails.ShipFromAddress.AddressLine1 = "300 Turnbull Ave";
            requestDetails.ShipFromAddress.Email = "jdoeasdfllkj@yahoo.com";
            requestDetails.ShipFromAddress.City = "Detroit";
            requestDetails.ShipFromAddress.StateOrProvinceCode = "MI";
            requestDetails.ShipFromAddress.PostalCode = "48123";
            requestDetails.ShipFromAddress.CountryCode = "US";
            requestDetails.ShipFromAddress.Phone = "7132341234";
            requestDetails.PackageDimensions.Length = 10;
            requestDetails.PackageDimensions.Width = 10;
            requestDetails.PackageDimensions.Height = 10;
            requestDetails.PackageDimensions.Unit = MerchantFulfillment.UnitOfLength.Inches;
            requestDetails.Weight.Value = 10;
            requestDetails.Weight.Unit = MerchantFulfillment.UnitOfWeight.Oz;
            requestDetails.ShippingServiceOptions.DeliveryExperience = MerchantFulfillment.DeliveryExperienceType.NoTracking;
            requestDetails.ShippingServiceOptions.CarrierWillPickUp = false;
            requestDetails.ShippingServiceOptions.CarrierWillPickUpOption = MerchantFulfillment.CarrierWillPickUpOption.ShipperWillDropOff;
            restRequest.AddJsonBody(request);

Here's a little more information from the error I'm receiving: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method."

Again, this works for other calls that I successfully make to the sandbox.  Does it make sense that it would change for a different endpoint call?

Enjoy,

Brian

**Comment by ShivikaK** [comment]
Hello @BeeBee234 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
