### ISSUE TITLE
 Returns Empty reponse for Seller retail analytics report type - GET_SALES_AND_TRAFFIC_REPORT

### ISSUE THREAD

**Issue by ShotaTakahashiPro** [amzn/selling-partner-api-docs#2183]
Hey guys!
Our developer profile got approved for the Brand Analytics role but the report returns empty data. Could you help me to figure out the issue? Thank you!

// Source Code
...
await sellingPartner.callAPI({
operation:'createReport',
body:{
reportType:'GET_SALES_AND_TRAFFIC_REPORT',
marketplaceIds:marketplace_ids,
dataEndTime:'2022-03-31T00:00:00+00:00',
dataStartTime:'2022-03-01T00:00:00+00:00',
reportOptions: {dateGranularity:"MONTH", asinGranularity:"CHILD"}
}
});
...
let res_reports = await sellingPartner.callAPI({
operation:'getReports',
query:{
reportTypes:'GET_SALES_AND_TRAFFIC_REPORT',
MarketplaceIds:marketplace_ids,
dataEndTime:'2022-03-31T00:00:00+00:00',
dataStartTime:'2022-03-01T00:00:00+00:00',
reportOptions: {dateGranularity:"MONTH", asinGranularity:"CHILD"}
}
});

// Console log
...
[{"reportType":"GET_SALES_AND_TRAFFIC_REPORT","processingEndTime":"2022-04-08T02:13:36+00:00","processingStatus":"DONE","marketplaceIds":["APJ6JRA9NG5V4"],"reportDocumentId":"amzn1.spdoc.1.3.2fb0e3ef-492f-48d4-8094-9f3630750364.T2NZQ8AYL0BMHH.44900","reportId":"177022019090","dataEndTime":"2022-03-31T00:00:00+00:00","createdTime":"2022-04-08T02:13:23+00:00","processingStartTime":"2022-04-08T02:13:27+00:00","dataStartTime":"2022-03-01T00:00:00+00:00"}]
...
[]

**Comment by ShotaTakahashiPro** [comment]
Thanks for your comment, @stefnats 
Yes, my answer to your both questions is yes. The role is correctly assigned and re-authorized.

**Comment by joshkatona** [comment]
This might not apply in your case but I just solved a similar issue in our application. We were doing some post-processing to transform report results from tab-delimited flat files into JSON before returning them. Since this report is already JSON, our application returned an empty JSON file because there were no rows to transform. Once I just returned the JSON the report works as expected.

**Comment by shirushi-dev** [comment]
I'm accessing from Japan, but access is denied.
I own the "Brand Analysis" authority.


RequestParam
````
  array(5) {
    ["report_options"]=>
    array(2) {
      ["dateGranularity"]=>
      string(3) "DAY"
      ["asinGranularity"]=>
      string(3) "SKU"
    }
    ["report_type"]=>
    string(28) "GET_SALES_AND_TRAFFIC_REPORT"
    ["data_start_time"]=>
    string(25) "2022-04-16T00:00:00+09:00"
    ["data_end_time"]=>
    string(25) "2022-04-18T00:00:00+09:00"
    ["marketplace_ids"]=>
    array(1) {
      [0]=>
      string(14) "A1VC38T7YXB528"
    }
  }
}
```

Response
```
  [403] {
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
```

**Comment by stuart-so** [comment]
> Hey guys! Our developer profile got approved for the Brand Analytics role but the report returns empty data. Could you help me to figure out the issue? Thank you!
> 
> // Source Code ... await sellingPartner.callAPI({ operation:'createReport', body:{ reportType:'GET_SALES_AND_TRAFFIC_REPORT', marketplaceIds:marketplace_ids, dataEndTime:'2022-03-31T00:00:00+00:00', dataStartTime:'2022-03-01T00:00:00+00:00', reportOptions: {dateGranularity:"MONTH", asinGranularity:"CHILD"} } }); ... let res_reports = await sellingPartner.callAPI({ operation:'getReports', query:{ reportTypes:'GET_SALES_AND_TRAFFIC_REPORT', MarketplaceIds:marketplace_ids, dataEndTime:'2022-03-31T00:00:00+00:00', dataStartTime:'2022-03-01T00:00:00+00:00', reportOptions: {dateGranularity:"MONTH", asinGranularity:"CHILD"} } });
> 
> // Console log ... [{"reportType":"GET_SALES_AND_TRAFFIC_REPORT","processingEndTime":"2022-04-08T02:13:36+00:00","processingStatus":"DONE","marketplaceIds":["APJ6JRA9NG5V4"],"reportDocumentId":"amzn1.spdoc.1.3.2fb0e3ef-492f-48d4-8094-9f3630750364.T2NZQ8AYL0BMHH.44900","reportId":"177022019090","dataEndTime":"2022-03-31T00:00:00+00:00","createdTime":"2022-04-08T02:13:23+00:00","processingStartTime":"2022-04-08T02:13:27+00:00","dataStartTime":"2022-03-01T00:00:00+00:00"}] ... []

I just ran into the same exact issue, and our problem was that we first needed to generate a report using the createReport  operation or by setting up a schedule for the report to be created. I manually generated a single report with the code below and my list was no longer empty. The reports are listed based on the creation date so be sure to set your range to include the day you create the report on even if the report that you created was for a different date.  

```
await sellingPartner.callAPI({
      operation: "createReport",
      endpoint: "reports",
      body: {
        reportType: "GET_SALES_AND_TRAFFIC_REPORT",
        marketplaceIds: ["ATVPDKIKX0DER"],
        dataStartTime: "2022-03-31T00:00:00+00:00",
        dataEndTime: "2022-03-31T23:59:59+00:00",
        reportOptions: { dateGranularity: "MONTH", asinGranularity: "CHILD" },
      },
});
```

**Comment by kenyonduan** [comment]
Hi guys!

I saw this sentence in the [document](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api#frequently-asked-questions): _**Note: If you have a published hybrid SP-API application you must relist your application before reauthorization.**_ 

Does this mean that my application needs to be re-approved? and will I be able to access the Sp-API during the approval period?
