### ISSUE TITLE
[FEATURE] Documentation: Does throttling occur per-region?

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2184]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the improvement**
Could you make it clear in the documentation if rate limiting will occur per (Seller, Application), or per (Seller, Application, Region)?

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md

**Description of what the documentation currently says**
The documentation does not make mention of Marketplaces/Regions today.

**Description of what the documentation should say**
Either:
- "All usage plans are specific to application-Selling Partner pairs, globally"
- "All usage plans are specific to application-Selling Partner-Region tuples"

**Screenshots**

**Additional context**

**Comment by stefnats** [comment]
Well, technically both are correct.
A Selling Partner ID is regional. So, let's say if you have Amazon USA, Amazon Mexico, Amazon Germany and Amazon France you have 2 Selling Partner IDs: One for Amazon North America Region and one for Amazon Europe Region (two different seller central Accounts)

**Comment by kennedyjustin** [comment]
Thanks for the info - will keep this issue open because I do think the docs would benefit from some discussion about the Seller<->Region<->Marketplace relationship.

**Comment by ehrowe** [comment]
I think the question is really more relevant to throttling. The relationship between sellers and regions is not unclear, it's the impact of that relationship on usage limits. That's what needs more clarity.
