### ISSUE TITLE
dead link - Website authorization workflow: Step 0

### ISSUE THREAD

**Issue by scmor3** [amzn/selling-partner-api-docs#2186]
In the table of contents under **Website authorization workflow** the link to steps 1-4 will jump down to the appropriate section, but **step 0** doesn't work jump to the correct section. When left-clicking it does nothing. When opening in a new tab it takes you to the top of the page.

**Comment by puppsupr** [comment]
Hi,
Thanks for pointing this out. We will make the correction.

Thanks and Regards,
Supriya Puppala
Solutions Architect, Selling Partner API
