### ISSUE TITLE
[TYPO] Website Authorization Flow: Step 1

### ISSUE THREAD

**Issue by scmor3** [amzn/selling-partner-api-docs#2187]
In the description of **redirect_uri** the second sentence is missing the word **be** as in "This must **be** an OAuth Redirect URI that you specified when you registered your application."
![typo1](https://user-images.githubusercontent.com/46556653/162856412-edf0781a-62a7-4cdf-9483-d6aef96aaf7d.PNG)

**Comment by puppsupr** [comment]
Hi, 
Thanks for pointing this out. We will make the correction.

Thanks and Regards,
Supriya Puppala
Solutions Architect, Selling Partner API
