### ISSUE TITLE
Tracking numbers

### ISSUE THREAD

**Issue by damscss** [amzn/selling-partner-api-docs#219]
Hey boys,
how to update orders tracking number with this new api ?
Thanks for your help,

**Comment by nodisk8800** [comment]
Use Feed API
https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2020-09-04.md

FeedType = POST_ORDER_FULFILLMENT_DATA

**Comment by pprbhm** [comment]
Hello,
This issue looks stale. Resolving it for now, please reach out to developer support team in case of technical assistance related to API.
