### ISSUE TITLE
Invalid Access: You do not have permissions to view this page

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-docs#2191]
We have users reporting that when attempting to authorize our app, they are getting "Invalid Access; You do not have permissions to view this page". Our customers are fairly sophisticated and this error is occurring across a number of the seller accounts they are managing.  There appears to be no documentation on the specific user permissions settings required in Seller Central "User Permissions". We attempted to document this ourselves, but the customer still gets this error.

Would appreciate any recommendations for user permissions, especially for reporting API and Order API access.

https://docs.openbridge.com/en/articles/5391780-amazon-selling-permissions

**Comment by rugved1991** [comment]
Hi @tspicer,

The seller needs to login with their primary user credentials in order view the app consent page. They can check the "User Permissions" section under "Account Settings" to identify who is the primary owner of the account.  

Best,
Rugved
Solutions Architect, SP API

**Comment by tspicer** [comment]
@rugved1991 , let me give you a use case as that might assist in getting clarity.  

I have a user who is NOT the primary account owner for Seller X. My user email is "foo@company.com" was added to Seller X as a user. The primary account owner set all permission levels within Seller Central "User Permissions” to NONE for foo@company.com. Now, using my email address  "foo@company.com”, I attempt to go through a web OAuth flow for Seller X. Since I have all permissions set to NONE for Seller X, the Oath screen at Amazon says “Invalid Access; You do not have permissions to view this page”.

Now, what permissions need to be set in “User Permissions” for Seller X so the user “foo@company.com” can complete the OAuth process for Seller X?

**Comment by tspicer** [comment]
> Hi @tspicer,
> 
> The seller needs to login with their primary user credentials in order view the app consent page. They can check the "User Permissions" section under "Account Settings" to identify who is the primary owner of the account.
> 
> Best, Rugved Solutions Architect, SP API

Thanks for this clarification. So only the primary account owner can view the app consent page? This does not align with our experience. For example, I have personally been invited as a user to other seller accounts and I can complete the Oauth process for those sellers without being the primary account owner. I have been granted admin access in user permissions, but certainly not the primary account owner.

**Comment by tspicer** [comment]
hi @rugved1991 ,

Good news. It appears that a secondary user can in fact be an authorizer assuming they are assigned "admin" permissions. We have validated this across 12 different sellers as a test. This is critical for agencies and others who are not primary account owners.  Can you confirm this is expected and not a bug? We would hate to suggest this path and then have it change.

https://docs.openbridge.com/en/articles/5391780-amazon-selling-permissions

**Comment by NA-Dev** [comment]
Which permissions does a secondary user need to be an Admin on to register as a developer? We have a non-technical person as the primary account, and it will be really difficult to register and manage access to the API via a game of telephone.

**Comment by tspicer** [comment]
@NA-Dev , the link I shared shows these secondary user permissions. See https://docs.openbridge.com/en/articles/5391780-how-to-configure-amazon-selling-partner-permissions. Also, you can see this troubleshooting doc as well: https://docs.openbridge.com/en/articles/5915575-troubleshooting-sp-api-user-permissions

**Comment by Dmusulas** [comment]
Hey, @kaviga! 

No I have not managed to solve this, at the end I had to walk the client through the process on a video call to authorize app and send me tokens that I needed.

Really difficult to work with non-tech client using this platform...

**Comment by jessewasily** [comment]
Hi everyone!

I'm trying to build a private app for API access. I'm a seller at a company looking to automate some of our data functions but I'm still running into the issues above. After confirming I have admin access everywhere possible, I still cannot access the develop apps page. Any suggestions?

**Comment by andrenpt** [comment]
We are also not able to access the developer page:
![image](https://user-images.githubusercontent.com/15822165/210136160-aa09b967-c0ea-444c-97ce-e065be749301.png)

This is really frustrating and Amazon it's not helpful

**Comment by Blochergroup** [comment]
Same Issue here. Has anybody solved this?

**Comment by mazaheri** [comment]
still the same for my friend
