### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2192]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
The documentation does not make it clear whether or not an RDT is required to access the Orders API, if no PII is required.

**URL of the content on GitHub**
https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide

**Description of what the documentation currently says**
Currently the documentation only says that you are required to use an RDT.

**Description of what the documentation should say**
I would like if it was clear whether or not *all* Orders API calls will fail (example: getOrders) without an RDT, or if only Orders API calls that require PII will fail without an RDT.

**Screenshots**

**Additional context**
Because there is a July 31st deadline for the Tokens API, I need to know whether or not my current integration is fine, or if I need to use an RDT to access simple order information that does not contain an PII.

**Comment by puppsupr** [comment]
Hi, 

The RDT deadline have been increased to July 31st 2023. Please check this [link](https://developer-docs.amazon.com/sp-api/changelog/important-notice-discontinued-support-lwa-tokens-can-no-longer-retrieve-pii-in-selling-partner-api) for the official announcement. 

You need RDT only if you would like to access the PII data. Without RDT you can still access the Get Order/Get Orders where you receive response without the PII.

Thanks for the feedback regarding adding the RDT details in the documentation. We will work to add these details.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
