### ISSUE TITLE
ReportsApi 2021-06-30 - GetReportsAsync() - Returns reportTypes Missing

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2195]
Documentation states that all parameters for GetReportsAsync() are Required = NO

https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-use-case-guide

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "reportTypes;"
    }
  ]
}

**Comment by lobotomisador** [comment]
@nrogers805 you need to encode the reportTypes in the URL for GET requests.

**Comment by nrogers805** [comment]
> @nrogers805 you need to encode the reportTypes in the URL for GET requests.

I think you have misunderstood the issue but thanks anyway. Its a documentation issue

**Comment by lobotomisador** [comment]
@nrogers805 sorry I don't understand what `GetReportsAsync()` is, I presume you are using a library to make the calls for you, the error that library is throwing is due to what I mentioned. Let me know If you are still seeing an issue after encoding the params in the request correctly.
