### ISSUE TITLE
Where to apply for Advertising API?

### ISSUE THREAD

**Issue by deadmouse** [amzn/selling-partner-api-docs#2197]
I know this is not the right place to ask, but I don't know where to ask. 

Following the documentation to apply for Advertising API: [https://advertising.amazon.com/API/docs/en-us/setting-up/step-2-complete-application](https://advertising.amazon.com/API/docs/en-us/setting-up/step-2-complete-application) I am unable to find the section "Advertising API" to request API access. I sign in [advertising.amazon.es](https://advertising.amazon.es/) (Advertising console) and I have searched through all menus but I don't find this:

![imagen](https://user-images.githubusercontent.com/6352552/163456017-2117cf43-cabe-4eb2-90a9-0a964fb4610b.png)

What am I missing? I signed in with the admin account.

**Comment by sungolivia** [comment]
Hi @deadmouse!

It looks like you can access their technical support via this link!
https://advertising.amazon.com/API/docs/en-us/info/support 

Best of luck,
Olivia
Solutions Architect, SP API
