### ISSUE TITLE
JSON_LISTINGS_FEED - Some basic operations.

### ISSUE THREAD

**Issue by BashaBill** [amzn/selling-partner-api-docs#2201]
Before I start: I have been here > https://developer.amazonservices.com/support. After logging in there is no 'Create a Question' button available, so I cannot create a question. Maybe its only available to Americans.

My question is relating to JSON_LISTINGS_FEED product feed type.

Basically, I am working from a starting point of having an Ean with a free stock value and a platform price.

What I need to be able to do is:

1. Create a new listing using the Ean, free stock value and platform price (if its not already listed)
2. Update the free stock value and price (using the Ean) if we already have the item listed.

As it stands we have implemented most of the sandbox test calls to Amazon SP-API and these are just fine.

We are now attempting to submit a feed (FeedType : JSON_LISTINGS_FEED) with only a couple of products but cannot find any documentation showing us what the structure of the JSON should be.

We are successfully creating the feed and submitting JSON via the returned URI and FeedId and are receiving responses like "Missing attributes".. which is not very helpful.

This is useful: => https://github.com/amz-tools/amazon-sp-api/issues/68
This is useful too: => https://github.com/amzn/selling-partner-api-docs/issues/2068

It seems like there are a lot of developers struggling with trying to work out how to use SP-API, due to the lack of documentation provided by Amazon.

Has anyone even found a the list of acceptable JSON attributes for this feed type?

Any help appreciated.

**Comment by vaidas-lungis** [comment]
In the [April 2022 SP-API Release Announcement /discussions/2194](https://github.com/amzn/selling-partner-api-docs/discussions/2194) there is a link to new documentation https://developer-docs.amazon.com/sp-api-news/docs
Previously it was a good guide at this repo https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md but they updated with a link to new docs page. If you check the previous revisions you would get a nice article how to start.

**Comment by BashaBill** [comment]
Thanks for your reply @vaidas-lungis. 👍 

I have been working through the documentation you have linked to for a while now and am currently trying to get the product definition types from the end point exposed by Amazon. That's not going well either, when asking for any product type I am just getting '403 Access Denied'.. (for the simple sandbox response) and I have no idea why. All the other sand box requests for Feeds API, Listings API, Tokens API, Orders API are all working just fine with 'Response 200'.

All I need really need to do is successfully list a 'Book' (not even sure if that product type is setup for the JSON_LISTING_FEED type).

If you or anyone else can provide me the JSON attributes for the product type 'Book' that would get me a tiny step closer to listing a product.

Thanks for your help.

**Comment by BashaBill** [comment]
OK, I now have the Product Type Definitions endpoint giving me a sensible response (from the live endpoint and not the sandbox). For me the sandbox is broken.

The result: there is no Product Type: Books for the UK market place.

:(

**Comment by BashaBill** [comment]
OK, so just an update.

I am now able to list, and update products using the Amazon SP-API JSON_LISTINGS_FEED but only when I provide the ASIN.

This is due to the requirement of having to provide the marchant_suggested_asin (which when left out causes an error in the feed processing)

Anybody know of a way to list items using an EAN? thanks

**Comment by RobertMartin-nz** [comment]
Hi HashaBill

I cant see 'marchant_suggested_asin' in the docs (https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2).  When I try to send my feed up I get 

{
  "header": {
    "sellerId": "",
    "version": "2.0",
    "feedId": "993256019117"
  },
  "issues": [
    {
      "code": "4002001",
      "severity": "ERROR",
      "message": "Item 'Feed' cannot be parsed."
    }
  ],
  "summary": {
    "errors": 1,
    "warnings": 0,
    "messagesProcessed": 0,
    "messagesAccepted": 0,
    "messagesInvalid": 0
  }
}



Feed example (just trying to update available qty)

{
  "header": {
    "sellerId": "A############",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 1,
      "sku": "9781788932004",
      "operationType": "PARTIAL_UPDATE",
      "attributes": {
        "fulfillment_availability": [
          {
            "fulfillment_channel_code": "DEFAULT",
            "quantity": 5
          }
        ]
      }
    }
  ]
}

**Comment by BashaBill** [comment]
I know, crazy isn't it. The merchant_suggested_asin is not even mentioned. Thanks Amazon.

**Comment by Romerolweb** [comment]
> In the [April 2022 SP-API Release Announcement /discussions/2194](https://github.com/amzn/selling-partner-api-docs/discussions/2194) there is a link to new documentation https://developer-docs.amazon.com/sp-api-news/docs Previously it was a good guide at this repo https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md but they updated with a link to new docs page. If you check the previous revisions you would get a nice article how to start.
> 
> BTW, json schema depends on the product type you are trying to submit.

May you explain how the Json schema depends on the product type?

I have seen documentation and some examples (https://spapi.cyou/swagger/index.html?urls.primaryName=feeds-api-model#/). however, I would appreciate your help.

**Comment by RobertMartin-nz** [comment]
> I know, crazy isn't it. The merchant_suggested_asin is not even mentioned. Thanks Amazon.

Hi bashBill

Tried it but unfortunately still not working for me....

{
  "header": {
    "sellerId": "AXXXXXX",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 1,
      "sku": "9781788932004",
      "merchant_suggested_asin": "1788932005",
      "operationType": "PARTIAL_UPDATE",
      "attributes": {
        "fulfillment_availability": [
          {
            "fulfillment_channel_code": "DEFAULT",
            "quantity": 5
          }
        ]
      }
    }
  ]
}
 
but still returning.  NOTE in the result it says sellerid is empty.  I am sending sellerid, which I am putting MerchantID from Seller Central in, perhaps this is the issue?

{
"header": {
"sellerId": "",
"version": "2.0",
"feedId": "993256019117"
},
"issues": [
{
"code": "4002001",
"severity": "ERROR",
"message": "Item 'Feed' cannot be parsed."
}
],
"summary": {
"errors": 1,
"warnings": 0,
"messagesProcessed": 0,
"messagesAccepted": 0,
"messagesInvalid": 0
}
}

**Comment by chapmanjw** [comment]
`merchant_suggested_asin` is not a valid property of a feed message for the JSON_LISTINGS_FEED. In this particular feed submission, why are you trying to provide it?

As-is, your feed example does not meet the JSON Schema for the JSON_LISTINGS_FEED format: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2. `merchant_suggested_asin` should not be there on the feed message (unless you are trying to change that attribute, which would go inside the `attributes` instead) and you are missing `productType`.

Here is a corrected example:

```
{
  "header": {
    "sellerId": "AXXXXXX",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 1,
      "sku": "9781788932004",
      "operationType": "PARTIAL_UPDATE",
      "productType": "PRODUCT",
      "attributes": {
        "fulfillment_availability": [
          {
            "fulfillment_channel_code": "DEFAULT",
            "quantity": 5
          }
        ]
      }
    }
  ]
}
```

We recommend using a standard JSON Schema validator with the feed schema prior to submission in order to prevent these feed parsing errors: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2.

**Comment by chapmanjw** [comment]
For the available attributes and their valid data structures as to what you can put into the message attributes, refer to the Product Type Definitions API: https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference

**Comment by BashaBill** [comment]
> `merchant_suggested_asin` is not a valid property of a feed message for the JSON_LISTINGS_FEED. In this particular feed submission, why are you trying to provide it?
> 
> As-is, your feed example does not meet the JSON Schema for the JSON_LISTINGS_FEED format: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2. `merchant_suggested_asin` should not be there on the feed message (unless you are trying to change that attribute, which would go inside the `attributes` instead) and you are missing `productType`.
> 
> Here is a corrected example:
> 
> ```
> {
>   "header": {
>     "sellerId": "AXXXXXX",
>     "version": "2.0",
>     "issueLocale": "en_US"
>   },
>   "messages": [
>     {
>       "messageId": 1,
>       "sku": "9781788932004",
>       "operationType": "PARTIAL_UPDATE",
>       "productType": "PRODUCT",
>       "attributes": {
>         "fulfillment_availability": [
>           {
>             "fulfillment_channel_code": "DEFAULT",
>             "quantity": 5
>           }
>         ]
>       }
>     }
>   ]
> }
> ```
> 
> We recommend using a standard JSON Schema validator with the feed schema prior to submission in order to prevent these feed parsing errors: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2.

If I do not provide the merchant suggested asin attribute, the feed is rejected with a message: no merchant suggested asin provided.. I have to provide one..

**Comment by kingsun-he** [comment]
I want to modify the quantity and price. The quantity is ok. But I can't change the price. Here is my message schema. Do you have any idea? @chapmanjw 

`  "messages": [    
    {
      "messageId": 1,
      "sku": "VGOUK-VM-048",
      "operationType": "PATCH",
      "productType": "PRODUCT",
      
	  "patches" : [
			{
				"op": "replace",
				"path": "/attributes/purchasable_offer",
				"value":[
				   {
					   "currency" : "GBP",
				       "our_price" : [{"schedule": [{"value_with_tax": 285.93}]}],
				       "marketplace_id" : "A1F83G8C2ARO7P"

				   }
				]
				
		    }
		]
			
      
    },
	
	{
      "messageId": 2,
      "sku": "VGOUK-VM-048",
      "operationType": "PARTIAL_UPDATE",
      "productType": "PRODUCT",
      "attributes": {
        "fulfillment_availability": [
          {
            "fulfillment_channel_code": "DEFAULT",
            "quantity": 10
          }
        ]
      }
    }
	
	
  ],`

**Comment by kingsun-he** [comment]
It seems that it works. But it is too late. We have to wait a long time to see the result.
