### ISSUE TITLE
Returns "Access to the resource is forbidden" reponse  report type - GET_SALES_AND_TRAFFIC_REPORT

### ISSUE THREAD

**Issue by shirushi-dev** [amzn/selling-partner-api-docs#2203]
Returns "Access to the resource is forbidden" reponse report type - GET_SALES_AND_TRAFFIC_REPORT 

I'm accessing from Japan, but access is denied.
I own the "Brand Analysis" authority.
Is it impossible to access from Japan?

```
//RequestParam
  array(5) {
    ["report_options"]=>
    array(2) {
      ["dateGranularity"]=>
      string(3) "DAY"
      ["asinGranularity"]=>
      string(3) "SKU"
    }
    ["report_type"]=>
    string(28) "GET_SALES_AND_TRAFFIC_REPORT"
    ["data_start_time"]=>
    string(25) "2022-04-16T00:00:00+09:00"
    ["data_end_time"]=>
    string(25) "2022-04-18T00:00:00+09:00"
    ["marketplace_ids"]=>
    array(1) {
      [0]=>
      string(14) "A1VC38T7YXB528"
    }
  }
}



//Response
  [403] {
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]

**Comment by shirushi-dev** [comment]
Do you know who it is?
Has it been released yet?
It is unclear which countries have been released and which have not.

**Comment by nassuf** [comment]
Hi @shirushi-dev 
Good point that your app have Brand Analytics role granted.

You then need the seller to authorize your app once again if it was already done.
This way the brand analytics role will be added to the seller and it should work.

**Comment by shirushi-dev** [comment]
Hi @nassuf 
Thanks for giving me the response.
I have done that action but can not.
Maybe it is invalid in Japan.

**Comment by Adrian-T-AMZN** [comment]
Hello @[shirushi-dev](https://github.com/shirushi-dev),


In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.


Thanks,

Adrian T.

Selling Partner API Developer Support

**Comment by PG408** [comment]
Have u solve this problem?

**Comment by vinodbhoj** [comment]
Did you resolve this issue /

**Comment by RestricePlanoax** [comment]
> Hello @[shirushi-dev](https://github.com/shirushi-dev),
> 
> In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.
> 
> Thanks,
> 
> Adrian T.
> 
> Selling Partner API Developer Support

Hi @Adrian-T-AMZN ,

I am getting this error while trying to create report with "GET_SALES_AND_TRAFFIC_REPORT" type 

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Report type 44900 does not support account ID of type class com.amazon.partner.account.id.VendorGroupId.",
            "details": ""
        }
    ]
}

can you please help ?

**Comment by shirushi-dev** [comment]
I solved it here.

**Comment by kramx7** [comment]
@shirushi-dev I have the same issue. May I know how you resolve the issue?  Thanks
