### ISSUE TITLE
LISTINGS_ITEM_STATUS_CHANGE MarketplaceID inaccurate

### ISSUE THREAD

**Issue by DanielLanger** [amzn/selling-partner-api-docs#2209]
According to https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#listings_item_status_change the `MarketplaceId` returned in the `LISTINGS_ITEM_STATUS_CHANGE` notification is the `Amazon marketplace identifier of the affected listings item`.

However, this MarketplaceID is often incorrect - specifically, it doesn't always the listing where the status has changed. Most commonly, it returns the US marketplaceID when the issue has occurred in Canada or Mexico.

Has anyone noticed this as well, or have a fix to ensure accuracy?

**Comment by DanielLanger** [comment]
Any thoughts?

**Comment by unstory** [comment]
I have checked the listings api. The listings api return the listings status include "BUYABLE", "DISCOVERABLE","DELETED", however, the "BUYABLE" status is incorrect, the "DISCOVERABLE" status is correct.I think the listings api status is the same as the notification api. 
I have not noticed your problem.
Buy the way, could you tell me how to configure eventBridge? I found the document is incorrect.
I can't find the follow options in AWS:
![image](https://user-images.githubusercontent.com/9627373/169738834-8fafa66c-575c-4307-ac7c-02e9efc1ec17.png)

**Comment by chapmanjw** [comment]
@DanielLanger This should not be the case (i.e. the marketplace in the notification should correspond to the marketplace where the issues occurred). Can you open a developer support case so that the team that owns these notifications can dive into your specific examples? https://developer.amazonservices.com/support
