### ISSUE TITLE
CustomizedURL returns empty string in BuyerCustomizedInfo

### ISSUE THREAD

**Issue by padraicbc** [amzn/selling-partner-api-docs#221]
For custom orders `CustomizedURL` is empty. Using the MWS API I can pull the url with no issues but I get no url back for any of our many custom orders using the `sp-api` . 

```
{
    "payload": {
        "OrderItems": [
            {
                "OrderItemId": "xxxxxxxx",
                "BuyerCustomizedInfo": {
                    "CustomizedURL": ""
                }
            }
        ],
        "AmazonOrderId": "xxx-xxxxxxx-xxxxxxx"
    }
}
```
Also using the `golang` v4 sdk to sign I have to lowercase  post signing and before submitting the request as below or the api complains about missing headers/tokens:

```
    for k, v := range r.Header {
		delete(r.Header, k)
		r.Header[strings.ToLower(k)] = v
	}
```

**Comment by parvathm** [comment]
Hi @padraicbc 

We will need more details to investigate further. Can you [open a support case](https://developer.amazonservices.com/support) to resolve this issue. 

Thanks,
Parvathm,
Selling partner API Developer support.
