### ISSUE TITLE
How to create a "manufacturer" (Maker of the product) item with Listings Api

### ISSUE THREAD

**Issue by shirushi-dev** [amzn/selling-partner-api-docs#2213]
I would like to know how to create a "manufacturer" (Maker of the product) item with Listings Api. 
The creation and editing of other items has already been completed.

I couldn't do it below

`
    $data = [    
        "product_type" => "PRODUCT",  
                "requirements" => "LISTING_OFFER_ONLY",  
                "attributes" => [  
                    "manufacturer" => [  
                        [  
                            "language_tag" => "ja_JP",  
                            "value" => "test_manufacturer",  
                            "marketplace_id" => "A1VC38T7YXB528",  
                        ],  
                    ],  
]
`

Responce
`
{
    "sku": "testsku",
    "status": "INVALID",
    "submissionId": "6d14ff886bf34f45bae820db37e3dd2a",
    "issues": [
        {
            "message": "The attributes are invalid.",
            "severity": "ERROR",
            "attributeNames": [
                "manufacturer"
            ]
        }
    ]
}
`

**Comment by vaidas-lungis** [comment]
Maybe related to https://github.com/amzn/selling-partner-api-docs/issues/1246 🤷
