### ISSUE TITLE
An error will occur if do not enter any optional items.

### ISSUE THREAD

**Issue by shirushi-dev** [amzn/selling-partner-api-docs#2214]
ListingsApi > ListingsItemPutRequest

 merchant_suggested_asin
  description: If you have an existing ASIN, enter the existing ASIN. In other cases no input is required

Why are you prompted?

<img width="549" alt="スクリーンショット 2022-04-21 15 59 43" src="https://user-images.githubusercontent.com/82862062/164393193-95eb6281-d537-4e29-8d2f-4239b5375410.png">

**Comment by shirushi-dev** [comment]
@BashaBill 
That's what I want to know too.

Even though "merchant_suggested_asin" is not a required field,
 "message": "'merchant_suggested_asin' is required but not supplied." is displayed.

**Comment by BashaBill** [comment]
Well, if you find out please post it here, I will do the same. Thanks

**Comment by shirushi-dev** [comment]
👍！！
