### ISSUE TITLE
SellingPartnerApiDeveloperGuideForVendors 3rd party Registering as a developer

### ISSUE THREAD

**Issue by syndic8-stephen** [amzn/selling-partner-api-docs#222]
**Describe the improvement**
The Vendor central documentation assumes that all Vendor Central API developers need to be Vendor Central customers and be their own API developers.   We are a software provider with Vendor Central and Seller Central customers.   We have developed an MWS integration and plan on upgrading it for Seller central partner API.  As Vendor central is invite-only I see no way to develop for Vendor central integration and register ourselves as a developer which our Vendor central customers want.   Either there should be guidelines on how to apply to become a vendor central developer or more details on limitations.  e.g. can the customer apply or petition for access on our behalf,  do we have to develop as if a consultant to the customer and they register as the developer initially,  and if so it is possible to easily make the integration available to our other vendor central customers after?.  If this app is registered to their developer profile it would seem that would not work.    

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuideForVendors.md

**Description of what the documentation currently says**
To register as a developer

Sign into Vendor Central for your marketplace with the credentials that you want to associate with your developer account. See Vendor Central URLs for a list of URLs by marketplace.

**Comment by pflajszer** [comment]
+1 . We're not able to develop a client app due to this limitation. Is there any kind of explanation/statement/resolution of this on the horizon? Thanks, Pav

**Comment by yiweixia** [comment]
+1 My team has a similar use case. @ShivikaK, can you shed some light on this?

**Comment by tomhirschfeld** [comment]
@syndic8-stephen were you ever able to get past this issue? if so how?

**Comment by tomhirschfeld** [comment]
also @seanevan any insights here?

**Comment by rugved1991** [comment]
Hi @syndic8-stephen, @tomhirschfeld, @pflajszer and @yiweixia,

Thanks for reaching out. The Vendor Developer Guide available on the GitHub repository is focused primarily for vendors who are developing an application for their own account. If you are a software provider working with multiple vendors and sellers, you will be using your application on seller central to integrate with both sellers and vendors. The OAuth flow remains the same for both Selling Partners: Sellers and Vendors.  
You will have to change your OAuth URL based on the Selling Partner you would like authorization from. For sellers, you will use Seller Central domain while for vendors, you will use Vendor Central domain.
Eg:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=your_application_id&version=beta&state=examplestate 
https://vendorcentral.amazon.com/apps/authorize/consent?application_id=your_application_id&version=beta&state=examplestate 

We are working on updating our documentation to add vendor authorization flow for public developers. 

Thanks,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi,

Please note that in order to authorize vendors successfully, you will need to use a pure SP API application. Hybrid application will not be able to authorize the vendors.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by yiweixia** [comment]
Hi @rugved1991,

Thanks for the detailed response! 

Under the App registration page in seller central, I need to enter the OAuth Login URI. I have it set to our seller central login URI right now. Will the same app work if we send them to the vendor central auth page with the same application ID? Or do we need to create two separate apps, with separate OAuth Login URIs?

Also, is there a way for us to create a vendor central testing account so we can go test this onboarding process?

**Comment by rugved1991** [comment]
Hi @yiweixia,

Please use custom HTTPS URLs for Login and Redirect which belong to your application. If you use Seller Central login URL, it will not work. 
You can use the same application for receiving authorization from vendors. You would just need to change the OAuth URL to "vendorcentral" instead. If you have converted your MWS app to hybrid, then you wont be able to use vendor APIs, you would need to create a new SP API application.
Its not possible to create test vendor accounts. You will have to work with one or two vendors to receive authorization and test out the APIs. 

Thanks,
Rugved
Solutions Architect, SP API

**Comment by gaochenyue** [comment]
@rugved1991 so the vendors still have to create their own application with all the required roles before authorizing developers to access their SP API, correct?
