### ISSUE TITLE
Invalid request on getListingOffers operation for SKUs containing special characters

### ISSUE THREAD

**Issue by umutyusuf** [amzn/selling-partner-api-docs#2224]
We are facing an issue with calling the getListingOffers operation with special characters. SKUs that remain the same after URL encoding works properly but the ones that change after the URL encode operation result in an invalid response. We are using generated Java SDK to perform the calls.

Here is the response

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "HE14-367\u0026@2\u0026$388 is an invalid SKU for marketplace ATVPDKIKX0DER",
      "details": ""
    }
  ]
}
Requested URL: https://sellingpartnerapi-na.amazon.com/products/pricing/v0/listings/HE14-367%26%402%26%24388/offers?MarketplaceId=ATVPDKIKX0DER&ItemCondition=New

Also, this issue applies to the following SKU as well. `New_33033_37.85_20201011_Goodwill`

I've seen other cases for different services being resolved but `getListingOffers` is still failing. Similar issue #742 and #467

**Comment by puppsupr** [comment]
Hi,

Our engineering team has identified the root-cause and working on the fix. I will provide an update once fix is deployed.

Thanks and Regards,
Supriya Puppala, 
Solutions Architect, Selling Partner API

**Comment by puppsupr** [comment]
Hi,

Our engineering has fixed the getListingsItem issue. Can you please check and let me know if the issue is resolved ?

Thanks and Regards,
Supriya Puppala,
Solutions Architect, Selling Partner API

**Comment by umutyusuf** [comment]
hey @puppsupr it's resolved, thanks.
