### ISSUE TITLE
Vendor is not enabled for EDI - SP-API amazon france

### ISSUE THREAD

**Issue by prakashjnv90** [amzn/selling-partner-api-docs#2228]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2220

<div type='discussions-op-text'>

<sup>Originally posted by **prakashjnv90** April 24, 2022</sup>
when we submit invoice using sp-api(retail fulfilment) for france, we get error message "Vendor is not enabled for EDI".
Does anyone know what i am missing? or advise how to resolve this?</div>

**Comment by krithic15** [comment]
Hello @prakashjnv90,

Can you please open a support case with response headers? We would need to look into the backend configuration to debug the issue.

Best,
Krithi, Solutions Architect
Selling Partner API Services
