### ISSUE TITLE
[BUG] api  GET /reports/2020-09-04/reports 400     JAVA#SDK

### ISSUE THREAD

**Issue by lzy6666666** [amzn/selling-partner-api-docs#223]
the all parameters  is  optional ,  but response 400  "Bad request" ，after I add all the parameters, it's still the same

**Comment by JacksonJeans** [comment]
Hello @lzy6666666 ,

may you show us your canonical request and the full URI including query string? 
I highly doubt this is a bug on Amazon interfaces side - for once - as I've been working with this endpoint for quite a while.

Probably the problem will be apparent with the data requested above.

**Comment by lzy6666666** [comment]
@JacksonJeans 
Sorry, it's my careless this time.
1.The docs has instructions  Either reportTypes or nextToken is required, but I only saw the option in front;
Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports, tag=Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports, tag=null}}
![image](https://user-images.githubusercontent.com/44083667/102679995-76bcb580-41ef-11eb-8d03-26302240fa2c.png)

2.  I used MW reportTypes,  so this is Bad request.
Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports?reportTypes=_GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE_, tag=Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports?reportTypes=_GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE_, tag=null}}

3. now , this is ok.
Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports?reportTypes=GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL, tag=Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports?reportTypes=GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL, tag=null}}

4. sorry, It was my carelessness that caused the problem，thank you for your help!

**Comment by wanjinyu1988** [comment]
reportTypes=GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
SO where can i get the reportTypes ducumention?

**Comment by lzy6666666** [comment]
> reportTypes=GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
> SO where can i get the reportTypes ducumention?

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md
