### ISSUE TITLE
GetOrders - InvalidInput: We could not decode your NextToken.

### ISSUE THREAD

**Issue by hetkpatel** [amzn/selling-partner-api-docs#2230]
Using the [aws-quickstart/quickstart-amazon-selling-partner-api](https://github.com/aws-quickstart/quickstart-amazon-selling-partner-api), I am able to fetch the first 100 orders when running `/orders/v0/orders`. However, I receive the following error when I try to use the `NextToken` param to fetch the next pagination of orders:
```
{
"errors": [
      {
        "code": "InvalidInput",
        "message": "We could not decode your NextToken. Possible reasons include: a transmission error, improper quoting or a truncation problem.",
        "details": ""
      }
    ]
}
```

Here is the GET request I am using to get the next set of orders:
```
auth = AWS4Auth(AccessKeyId, SecretAccessKey, 'us-east-1', 'execute-api', session_token=SessionToken)
headers = {'content-type': 'application/x-www-form-urlencoded','Accept': 'application/json','x-amz-access-token':access_token}
params = {'MarketplaceIds': marketplaceId, 'NextToken': 'J3%2FldqIwXEKaJqJYLDm0ZAmQaz......YSMji4wF0IiRkRQPq0Hy%2BPFdKaQ%3D%3D'}

ordersResponse = requests.get("https://sellingpartnerapi-na.amazon.com/orders/v0/orders", params=params, headers=headers, auth=auth)
```
I have read other issue regarding `NextToken` + `GetOrders` and have tried the following:
- Changed `content-type` from `application/json` to `application/x-www-form-urlencoded` in the header
- Used `encodeuricomponent()` to encode the `NextToken` before adding it to the params list

**Comment by corbin-munce** [comment]
Comparing my next tokens, I'm not seeing any % characters.  Are you encoding the next token when adding as a param?

**Comment by hetkpatel** [comment]
Yes, I'm using the javascript function `encodeURIComponent(TOKEN)` before passing it as a parameter.

If I don't encode it, this is the error message I get:
```
{
    "errors": [
    {
    "code": "InvalidSignature",
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
    ....
}
```

**Comment by karan-nukani** [comment]
try to replace + with %2B and = with %3D in next token.. I have tried and it works for me...
I have had the same problem. I'm using PHP and cURL commands, but I think this issue can involve other languages/interfaces (I also have had problems using Postman.com). I temporarily resolve it by pre-encoding NextToken values replacing + and = symbols with %2B and %3D respectively. The parameter is properly received by Amazon and the signature works correctly also.
It works for me..Thanks
