### ISSUE TITLE
[BUG] FBA Inventory APIs often fail while generation

### ISSUE THREAD

**Issue by nguyentoanit** [amzn/selling-partner-api-docs#2231]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
Inventory APIs rarely generate report successfully in EU region.
Use same parameters:

```json
{
    "marketplaceIds": [
        "A1PA6795UKMFR9"
    ],
    "reportType": "GET_AFN_INVENTORY_DATA"
}
```

Report API v2021-06-30 often retrieved `"processingStatus": "FATAL"` when generation.

Here is report response which I got from [getReport](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreport) API:

```json
{
    "reportType": "GET_AFN_INVENTORY_DATA",
    "processingEndTime": "2022-04-26T10:00:07+00:00",
    "processingStatus": "FATAL",
    "marketplaceIds": [
        "A1PA6795UKMFR9"
    ],
    "reportId": "REPORT_ID",
    "dataEndTime": "2022-04-26T09:59:53+00:00",
    "createdTime": "2022-04-26T09:59:53+00:00",
    "processingStartTime": "2022-04-26T09:59:58+00:00",
    "dataStartTime": "2022-04-26T09:59:53+00:00"
}
```

**URL of the content on GitHub**
N/A

**Description of what the documentation currently says**
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference

**Description of what the documentation should say**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by avvarga** [comment]
Hello @nguyentoanit,

Thank you for bringing this to our attention.

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation and provide the following details:

- Request ID
- Timestamp
- Full copy of the request and response attached in a .txt file

Once you do so, please post the Case ID so we can keep track of the situation.

Thanks,
Alejandro C
Selling Partner API Developer Support

**Comment by cgaugel** [comment]
Bug still here.

**Comment by moltar** [comment]
The issue is still happening!

**Comment by moltar** [comment]
I don't think any additional details are needed. SP API team can just run some analysis on the failures and see that this report fails _A LOT_ more across the board on many accounts.

**Comment by moltar** [comment]
@avvarga Not sure why this was closed? Has this been fixed already?

**Comment by metaprice** [comment]
😂 Same here but no response to my tickets

**Comment by metaprice** [comment]
Its still not fixed.

**Comment by cgaugel** [comment]
It is still not fixed.

**Comment by cgaugel** [comment]
The issue is still happening!

**Comment by ethan2wen** [comment]
still happening

**Comment by metaprice** [comment]
Still happening

**Comment by receta-erp** [comment]
I'm confident this issue relates to the type of report being requested and the frequency you are able to request the data.  Specific reports appear to have time limits during each request.  If a second request for the same report is made within a period of time, that 'second' request will fail.  

For example.  The "GET_AFN_INVENTORY_DATA_BY_COUNTRY" report can only be requested once every 30 mins or so.  Anything before that will fail with a FAIL error.
