### ISSUE TITLE
how do i get all surported CarrierName and ShippingMethod from api

### ISSUE THREAD

**Issue by ex-melody** [amzn/selling-partner-api-docs#2234]

**Comment by bpyzikvc** [comment]
There is info about the requirements here as well as a link to a spreadsheet with the values.

Article: https://github.com/amzn/selling-partner-api-docs/issues/772
Spreadsheet: https://m.media-amazon.com/images/G/03/VTR_Comm_May2021/EU_MFN_Carrier_Ship_Method_Seller_Central_Drop_Down.xlsx
