### ISSUE TITLE
ListInboundShipments in SPAPI

### ISSUE THREAD

**Issue by uk-2** [amzn/selling-partner-api-docs#2235]
Does ListInboundShipments exist in SPAPI ?

I want to download previous shipments

**Comment by adrian-amz** [comment]
Hello @uk-2,

Thank you for reaching out regarding ListInboundShipments for SP-API.

You can find details regarding this in our [InboundShipmentInfo](https://github.com/amzn/selling-partner-api-docs/issues/2235).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case] (https://developer.amazonservices.com/support) with us.

Thanks,

Adrian C.
Selling Partner API Developer Support

**Comment by simeyla** [comment]
It's called `GetShipments` in the `FulFillmentInboundService`
