### ISSUE TITLE
Developer account restricted to NA Region

### ISSUE THREAD

**Issue by bpyzikvc** [amzn/selling-partner-api-docs#2236]
I have a working SP-API application that works for the NA region. I am attempting to be able to use the same application to service the EU and FA region but my developer seems to only have access to NA. 

I get the following message when attempting the OAuth process for the EU region, "The application provided does not have an MWS developer ID for this region."

Is it possible to add the other regions to my current developer account? or do I need to create new developers for the other regions (I had issues with this previously, Amazon said you should only have one developer account)?

**Comment by paulamascot** [comment]
I'm currently having the same issue. Amazon gave me permission to create developer profiles for other accounts, but not for France, for some reason. They rejected my developer profile 3 times already and I don't know how to add vendor account for France in other developer profile already created  :(

**Comment by stefnats** [comment]
Hey there, just a guess in the dark.
Is the application a Hybrid MWS app? If so, did you input your old dev ids for all regions (must be different)
You can see the application details in seller central partner network - > develop apps

**Comment by bpyzikvc** [comment]
@stefnats You are correct that it is a hybrid and the other regions do not have dev ids associated with them. However I do not have any dev ids for those regions and I would prefer to not have to go through another review process for a dev account. 

Is there a workaround? also noticed that those fields disappear if I select ONLY SP-API for the app so would that solve my issue?

**Comment by rodrifed** [comment]
Hello @bpyzikvc,

One developer profile is enough to serve all regions (NA, EU and FE). In order to enable this functionality, you have to select the marketplaces you want to support in the developer profile registration form and in the app. To do it, go to **Partner Network --> Develop Apps --> View profile**, and under **Use Cases** select the marketplaces you want to support.
After the changes are saved, reviewed and accepted, you should be able to execute the OAuth flow for the marketplaces you selected.
While building the [OAuth authorization URI](https://developer-docs.amazon.com/amazon-shipping/docs/authorizing-selling-partner-api-applications#constructing-an-oauth-authorization-uri), make sure to include the correct seller central url.

Thanks,
Federico
Selling Partner Developer Services

**Comment by bpyzikvc** [comment]
@rodrifed Thank you for the response however I do not have any options there. Here is a screenshot of the Use Cases section on my screen.

![image](https://user-images.githubusercontent.com/87151318/166491055-07a325b4-2f03-47fc-8470-35c9395aea9c.png)

**Comment by rodrifed** [comment]
Hi @bpyzikvc,

It looks like you are presented a legacy version of the developer profile form. Please fill all information and submit the form; after approved, you should see the **supported marketplaces** section.

Thanks,
Federico
Selling Partner Developer Services

**Comment by bpyzikvc** [comment]
@rodrifed Okay will do. Will this cause issues with using the developer now? I have many people using the application so I cannot afford disruption.

**Comment by rodrifed** [comment]
Hello @bpyzikvc,

If you are offering your application/product to third parties (sellers/vendors) you should select **Public Developer**.

Thanks,
Federico
 Selling Partner Developer Services

**Comment by bpyzikvc** [comment]
@rodrifed Hi I just wanted to bump this issue. I have not tried your solution as I am worried about my current users. Are you sure that there will be no disruption if I go through this process?

**Comment by rodrifed** [comment]
Hello @bpyzikvc,

That's correct, you will not lose any existing authorization.

Thanks,
Federico
Selling Partner Developer Services

**Comment by bpyzikvc** [comment]
@rodrifed We have finally got through with our developer application and now have access to all marketplaces there. Our listing also has been published with all marketplaces selected. 

However when a customer authorizes our app from the marketplace, they get an error.
"Something went wrong
The application provided does not have an MWS developer ID for this region. Error Code: MD9010"

What else are we missing?

**Comment by rodrifed** [comment]
@bpyzikvc I would kindly ask you to open a support case using the [Contact Us form](https://developer.amazonservices.com/support) with all the details.
Developer support will be able to assist you.
