### ISSUE TITLE
Developer profile rejected 3 times for France vendor account

### ISSUE THREAD

**Issue by paulamascot** [amzn/selling-partner-api-docs#2239]
Hi, 
I've already got permission from Amazon for my vendor accounts: DE, UK, IT, NL, ES. For some reason, Amazon is rejecting my developer profile for France. I already tried 3 times, and they rejected it, saying that I can use a single developer profile for what I need. 
However, in the documentation, it is written that I could apply separetely for developer profiles for each vendor account. https://developer-docs.amazon.com/sp-api/docs/about-vendor-groups

Now, I'm stacked because I cannot finish my script without France's data. 
I saw that I could add the vendor code for France in other vendor account, but now I already created the developer profile and it is not possible to add new vendor codes.

**Comment by rodrifed** [comment]
Hi @paulamascot,

You can add the FR vendor code to one of the vendor accounts in which you registered a developer profile by following the steps under **To add or remove vendor codes from your vendor group** in [this link](https://developer-docs.amazon.com/sp-api/docs/about-vendor-groups). After approved, you will have access to FR vendor account data from this developer account.

Thanks,
Federico
Selling Partner Developer Services

**Comment by paulamascot** [comment]
Hi @rodrifed,

I've followed the steps, and I sent a message to the Amazon support on 29th April. On 30th April they answered with this:
''Hello, my name is Jannio from Developer Services
Your issue is being reviewed and this case will be updated by one of our specialists
Saludos,
Jannio F.''

Since 30th April I didn't receive any update and I'm still waiting for an answer from Amazon.

**Comment by rodrifed** [comment]
Hi @paulamascot,

That means the case still needs some more investigation from the support team. Please wait for an answer from them.

Thanks,
Federico
Selling Partner Developer Services

**Comment by paulamascot** [comment]
Hi @rodrifed , 

Amazon authorized and added the vendor code for France in my Spain Developer Profile. 
I tried again to access it through the Seller Partner-API Python using the credentials for Spain Developer Profile, but changing the Marketplace = FR. I didn't work. 
I'm using it like this: 
VendorOrders(marketplace= 'Marketplaces.FR' ,credentials=credentials).get_purchase_orders(**kwargs)

Should I re-submit the Developer Profile for Spain?
