### ISSUE TITLE
C# Feed Sample/Guide/Library Struggles and Woes!

### ISSUE THREAD

**Issue by antonycartwright** [amzn/selling-partner-api-docs#224]
Hi everyone,

I have all of the stuff set up. I'm now able to make calls to API end points and receive a response after weeks of research and playing around.

What I can't do is anything with feeds. Has anyone managed to do anything at all with feeds? Is there any sample code or a guide of any sort?

I realise that this is a new API, but my client has been waiting 4 weeks now and I've been unable to deliver anything meaningful. In my opinion, the API has been released too early and we should have the option of using the old API.

For C#, for feeds, we are missing;
A guide.
Sample code.
A client library.
A workflow flowchart.

I can see that the new API is good and that Amazon is keen to get it pushed out, but us C# developers are really struggling. At the moment, my bill is over £900 which I'm going to have to waive in its entirety because I've not been able to deliver. I've had a conversation this morning where I've told my client that I'm unable to continue and that no fees are payable.

I understand that this is a new API, and they we're all trying to help eachother, but this is Amazon's API and in my opinion, instead of us struggling and spending hundreds of hours trying to work out their product, they should have already done this prior to releasing the API. Alternatively, they could allow us to use the old, mature API.

Thanks, Antony..

**Comment by pprbhm** [comment]
Hello,
As per documentation we have this so far for c#  https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp
Please follow the guide and if you have any particular technical issue while connecting with Feeds API you are welcome to connect developer support team via a case [here](https://developer.amazonservices.com/support)
