### ISSUE TITLE
[BUG] IsReplacementOrder inside GetOrders response returns a string "False" when it should return a boolean False

### ISSUE THREAD

**Issue by AmrMashrah** [amzn/selling-partner-api-docs#2240]
### Describe the issue

`"Orders": [
                        "IsReplacementOrder": false
`

Documentation States that IsReplacementOrder returns a Boolean.

When trying to deserialize an error occurs because it seems to be coming back as a string.
![image](https://user-images.githubusercontent.com/82926246/165987861-0528a6c9-cd90-43b8-9318-d26da7f0be70.png)
![image](https://user-images.githubusercontent.com/82926246/165988683-6b28d180-9d3e-4627-a88a-a42be66457f6.png)
To solve this issue we change the IsReplacementOrder to a string
public string? IsReplacementOrder { get; set; }

### Links

https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#order
https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-model

**Comment by adrian-amz** [comment]
Hello @AmrMashrah,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C.
Selling Partner API Developer Support
