### ISSUE TITLE
Feed().create_feed() not working correctly. Invalid request parameters

### ISSUE THREAD

**Issue by Roman1Boba1** [amzn/selling-partner-api-docs#2246]
I was doing "submit_feed" operation which call - "create_feed_document" and "create_feed" functions.
From "create_feed_document" I received "feedDocumentId" in payload but then "create_feed" failed with error 400 and response - "sp_api.base.exceptions.SellingApiBadRequestException: [{'code': 'InvalidInput', 'message': 'Invalid request parameters', 'details': ''}]"

Request looks like this
xml_file = open('filename.xml', 'r')
![image](https://user-images.githubusercontent.com/99268334/166438350-6c68955f-f0e0-40a1-aca2-4a9b0b84dd79.png)
document, feed = api.Feeds(credentials=credentials, marketplace=Marketplaces.US).submit_feed("POST_FBA_INBOUND_CARTON_CONTENTS", xml_file)

# submit_feed trigger a createFeedDocument (return 200) and created_feed (return 400 error in this case)

Also I was tried to do "create_feed" separately and received same response. And tried with Feed()._request()

**Comment by hellsing23** [comment]
same problem

**Comment by rodrifed** [comment]
Hi @Roman1Boba1,

Are you using any specific SDK/library?
Also, while submitting the request, are you specifying all mandatory input parameters? Please refer to this link for additional information: https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#step-4-create-a-feed.

Thanks,
Federico
Selling Partner API Developer Services

**Comment by Roman1Boba1** [comment]
Hi, @rodrifed, thank you for reply.
I am using specific sdk for python.
In request i send - feedType, inputFeedDocumentId (from createFeedDocument) and marketplaceids.
It was working month ago.
https://github.com/saleweaver/python-amazon-sp-api/blob/master/sp_api/api/feeds/feeds.py

**Comment by Roman1Boba1** [comment]
![image](https://user-images.githubusercontent.com/99268334/166486218-e186dcee-011c-4349-82b0-19f2cdd7a61e.png)
Also here screen from postman

**Comment by rodrifed** [comment]
Hello @Roman1Boba1,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation, and provide the following details:
* RequestId
* Timestamp
* Input payload
* API response

Thanks,
Federico
Selling Partner Developer Services
