### ISSUE TITLE
Unexpected value PT09 in ItemImage.VariantEnum - Catalog Items API v2020-12-01

### ISSUE THREAD

**Issue by ttimbul** [amzn/selling-partner-api-docs#2248]
The Catalog Items API model is incomplete or incorrect.

Test item:
  ASIN: B07GJBBGHG
  Marketplace: ATVPDKIKX0DER (US)

The [API model](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2020-12-01-model) shows:
```
"ItemImage": {
      "description": "Image for an item in the Amazon catalog.",
      "properties": {
        "variant": {
          "description": "Variant of the image, such as MAIN or PT01.",
          "example": "MAIN",
          "type": "string",
          "enum": [
            "MAIN",
            "PT01",
            "PT02",
            "PT03",
            "PT04",
            "PT05",
            "PT06",
            "PT07",
            "PT08",
            "SWCH"
          ],
          ...
```

Yet the ASIN includes variants up to P14:

```
{
    "variant": "PT14",
    "link": "https://m.media-amazon.com/images/I/51b4i0pRMzL.jpg",
    "height": 1600,
    "width": 1600
},
```

As a result the generated Java client throws an Exception: "Unexpected value 'PT09'"
Perhaps it should not be defined as an enum, or you need to include ALL possible variant values in the model.

**Comment by chapmanjw** [comment]
@ttimbul We have a fix deploying for this issue that should be in production next week. For v2020-12-01 and v2022-04-01, these values are enumerated, so we need to adhere that enumeration on these versions as to not break clients (such as what you are experiencing). 

Note: This enumeration is currently limited to the images that you can set via the Listings APIs (corresponding to `main_product_image_locator`, `other_product_image_locator_1`, etc. attributes on Listings API submissions). 

In the future, we may change this, but that would require a version bump of the API as to not break existing clients.

**Comment by ttimbul** [comment]
Glad to hear you're on the case.

As a workaround I manually modified the generated client to return the value as a String, but obviously that's not the best solution. I have seen other values such as FRONT. Not sure where they come from if they can't be created on the Listings API, but if there is a difference, from where I stand it may indeed be best to disconnect the two from each other.
(Our software doesn't allow listing creation, it only queries the catalog).

Could I also point you to a somewhat related [issue with the Fulfillment Inbound API](https://github.com/amzn/selling-partner-api-docs/issues/2304)?
It appears to me that poor handling of enums is an issue that pervades throughout the API.

**Comment by chapmanjw** [comment]
@ttimbul The fix for the images has finished deploying in all regions. You should no longer see those. 

For the issue on the other API, I would suggest opening a case to Developer Support. They can route that issue to the correct team. Thanks!
