### ISSUE TITLE
[BUG] The shipToAddress from createInboundShipmentPlan API response is different from Amazon seller central

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#2250]
Hi,

We use the createInboundShipmentPlan API to create an inbound shipment plan, we got the shipToAddress from the response is different from Amazon seller central.

the response is as follows:
```
{
    "payload": {
        "InboundShipmentPlans": [
            {
                "ShipmentId": "FBAXXXXXXXXX",
                "DestinationFulfillmentCenterId": "WRO5",
                "ShipToAddress": {
                    "Name": "Amazon Fulfillment Poland sp. z o.o.",
                    "AddressLine1": "Okmiany",
                    "AddressLine2": "Chojnow",
                    "City": "Okmiany",
                    "StateOrProvinceCode": "Dolnoslaskie voivodeship",
                    "CountryCode": "PL",
                    "PostalCode": "59-225"
                },
                "LabelPrepType": "SELLER_LABEL",
                "Items": [
                    {
                        "SellerSKU": "TEXXXXXXXX",
                        "FulfillmentNetworkSKU": "XXXXXXXXXX",
                        "Quantity": 200
                    },
                    {
                        "SellerSKU": "TEUXXXXXXX",
                        "FulfillmentNetworkSKU": "X000XXXXXXX",
                        "Quantity": 40
                    },
                    {
                        "SellerSKU": "TE7XXXXXX",
                        "FulfillmentNetworkSKU": "X00XXXXXXX",
                        "Quantity": 50
                    },
                    {
                        "SellerSKU": "TEXXXXXXX",
                        "FulfillmentNetworkSKU": "X00XXXXXXX",
                        "Quantity": 75
                    }
                ],
                "EstimatedBoxContentsFee": {
                    "TotalUnits": 365,
                    "FeePerUnit": {
                        "CurrencyCode": "EUR",
                        "Value": 0.14
                    },
                    "TotalFee": {
                        "CurrencyCode": "EUR",
                        "Value": 51.1
                    }
                }
            }
        ]
    }
}
```
The ship-to address on Amazon seller central is as follows:
![image](https://user-images.githubusercontent.com/8305040/166886987-58e9294f-859c-43ec-9d47-0e3300660b0b.png)

Why the ship-to address from API is different from the ship-to address on Amazon seller central between the same FBA shipment.

**Comment by LindaNC** [comment]
Hello shipwirenarayan

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda C.
Selling Partner API Developer Support

**Comment by cjill** [comment]
Hello,  @NancyLin 
I have a similar situation to yours. My address is correct, but through createInboundShipmentPlan API access to the country is PL, actually I want to sent to DE. DE is also displayed in Amazon seller central. Have you solved the problem now? Looking forward to your reply. thank you.

**Comment by cjill** [comment]
Hello, @NancyLin
I have a similar situation to yours.  Have you solved the problem now? Looking forward to your reply. thank you.

**Comment by marvinpaul95** [comment]
We have the same problem with XDR1 Fulfillmentcenter - did anybody find a solution for this?
