### ISSUE TITLE
Conversion to MWS & SP-API Hybrid APP

### ISSUE THREAD

**Issue by ramsesIII** [amzn/selling-partner-api-docs#2251]
When I convert from MWS to MWS & SP-API Hybrid the "old code" connect POST where SellerId, MWSAuthToken and AWSAccessKeyId are submitted continues to work ????
OR Do I also have to convert the "old MWS code" with an authorization that passes to Oauth ????

If I also have to convert the "old MWS code", Do you think I can create a new Test App in DRAFT mode only SP-API to do our tests ??

**Comment by kpconnell** [comment]
The "old code", if it is using a legacy MWS Token generated through seller central, does not need or care about a selling partner application, and can continue to use its token(s).

If you generate a new seller partner hybrid App, and a seller grants you permission (using Oauth flow), you'll get a new MWS token that is associated with the new app.  This token could be used in the "old code" provided those MWS calls are not deprecated (which is happening pretty quickly this year, see announcements..) 

And yes, draft mode seems to work generally speaking for all testing use cases that i can think of (except of course having your app appear in the marketplace) 

Hope this helps.
