### ISSUE TITLE
No MWS Authorization exists

### ISSUE THREAD

**Issue by shipwirenarayan** [amzn/selling-partner-api-docs#2252]
Whenever I am migrating any customer from MWS to SP I am getting "No MWS Authorization exists" error. If I migrate the US region connection then its working fine. Only facing issues with CA and Uk region connections. Please check the error details below,

`{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "No MWS Authorization exists",
            "details": ""
        }
    ]
}`

`resulted in a `400 Bad Request` response:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "No MWS Authorization exists",
      "details": ""
 (truncated...)

`

**Comment by LindaNC** [comment]
Hello shipwirenarayan

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda C.
Selling Partner API Developer Support

**Comment by mvladoi** [comment]
Hello, I am facing the same issue. Do you know what might be a possible explanation for this error message?

**Comment by stefnats** [comment]
My guess would be that OP posted that he tries to get sp Api Auth credentials for different regions from the same mws Auth tokens, which is not possible. Each sellerid (and mws token) is unique to the region.

**Comment by mvladoi** [comment]
Whenever I am migrating any customer from MWS to SP I am getting "No MWS Authorization exists" error. For me the situation is different, If I migrate the EU region connection then its working fine. Only facing issues with US region connections. 

To get the grantless LWA access token (code) I used the https://sellingpartnerapi-{customer.region}.amazon.com/authorization/v1/authorizationCode  which works fine. 

To exchange the code for a refresh token I use the seller mwsAuthToken,   sellingPartnerId, and my  developerId associated with the seller region. 
   
What is the meaning of this error: 

``` [{'code': 'InvalidInput', 'message': 'No MWS Authorization exists', 'details': ''}]```
