### ISSUE TITLE
putTransportDetails is incomplete

### ISSUE THREAD

**Issue by zakm** [amzn/selling-partner-api-docs#2253]
There does not appear to be an option to send the shipping mode (Air, Ground, etc) and the NonPartnered data inputs don't have options for dimensions and weights. For this reason you must finish a shipment in Seller Central because this information is still required but it is not currently possible to provide it via the API.

All options available in SC should also be available in the API.

**Comment by amandalynn** [comment]
We are having the same issue.  However, it does seem that if we complete this shipment through the API that this doesn't necessarily pose a problem with the SPD Non-APC shipment. What we're finding is that you can't can't go back and forth between using the API and SC easily.  We're also finding similar with the SPD - Non-APC carton dimensions. There's no way to send them and it locks up the SC API until they're entered.
