### ISSUE TITLE
What is merchant identifier in feeds header?

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#2257]
Hello I want to call feeds but I need to pass the merchant identifier in header, Where can I find it?

**Comment by kpconnell** [comment]
SellerId

**Comment by Adrian-T-AMZN** [comment]
Hello @{developer(s)},

Thank you for reaching out regarding the merchant identifier in feeds header.

As [kpconnell](https://github.com/kpconnell) mentioned, the merchant identifier is the SellerId. This can be found in Seller Central under Settings - Account Info - Your Merchant Token.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by ramieblatt** [comment]
Trying to do that and:

You currently have limited access to Amazon selling services.
We are currently experiencing technical difficulties with this tool and are working on resolving this issue. Please try again in 15 minutes.

It has been that way a long time. Is there an independent way to ascertain the MerchantIdentifier perhaps from all the other crdentials stack we may already use in all the other Seller API calls?

**Comment by ramieblatt** [comment]
And I can confirm that it's the same old SellerID used in all the other SellerAPI calls (and deprecated MWS calls too).
