### ISSUE TITLE
[BUG] PII Missing From Response Regardless of Enabled Role

### ISSUE THREAD

**Issue by aadedeji-dxt** [amzn/selling-partner-api-docs#226]
According to the documentation, a [particular](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md) role needs to be enabled for the getOrderAddress and getOrderBuyerInfo operations. Access to this role was requested and granted, and I have confirmed that this role is enabled for the application that is making the authorized call to the getOrderAddress and getOrderBuyerInfo SP-API endpoints.

Even with this role enabled, the GetOrderBuyerInfoResponse and GetOrderAddressResponse are incomplete and stripped of PII necessary to perform merchant fulfilled shipping and tax invoicing application functions. An example GetOrderAddressResponse is copied below:

{
"payload": {
"AmazonOrderId": "xxx-xxxxxxx-xxxxxxx",
"ShippingAddress": {
"PostalCode": "xxxxx",
"City": "xxxxx",
"CountryCode": "xx",
"Name": ""
}
}
}

Is there anything else that needs to be done in order to receive a full response (with PII included) from the getOrderAddress and getOrderBuyerInfo endpoints? Enabling the role specified in the documentation does not seem to be sufficient for a full response.

**Comment by parvathm** [comment]
Hi @aadedeji-dxt,

We will need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation. 

Thanks,
Parvathm
Selling Partner API Developer Support.
