### ISSUE TITLE
InternalFailure from getAuthorizationCode

### ISSUE THREAD

**Issue by peter200694013** [amzn/selling-partner-api-docs#2262]
Based on https://developer-docs.amazon.com/sp-api/docs/authorization-api-use-case-guide, I want to get authorization to call Selling Partner API operations on behalf of a seller who previously authorized us.

Response from /authorization/v1/authorizationCode as below. I have tried many time, I always got the following error. Is there advice for this issue?
{
"errors": [
{
"code": "InternalFailure",
"message": "We encountered an internal error. Please try again.",
"details": ""
}
]
}

**Comment by fruch17** [comment]
Hello,

I have the same issue, i don't know how fix it , somebody can help me please ??

**Comment by puppsupr** [comment]
Hi @fruch17,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API

**Comment by nrogers805** [comment]
> Based on https://developer-docs.amazon.com/sp-api/docs/authorization-api-use-case-guide, I want to get authorization to call Selling Partner API operations on behalf of a seller who previously authorized us.
> 
> Response from /authorization/v1/authorizationCode as below. I have tried many time, I always got the following error. Is there advice for this issue? { "errors": [ { "code": "InternalFailure", "message": "We encountered an internal error. Please try again.", "details": "" } ] }

Hi, did you get this resolved ?

I am now getting the same issue even though the process has been working fine for months but stopped and getting this error for last few days
