### ISSUE TITLE
For Amazon SP-API how to close and re-list a listing by API?  please tell me,thank you 

### ISSUE THREAD

**Issue by wushao** [amzn/selling-partner-api-docs#2263]
![image](https://user-images.githubusercontent.com/4292410/167753105-a165e4a3-b8f3-4672-bee0-6fe403e12d3c.png)

I didn’t find these methods in the SP-API. 
Please tell me if there is a way to Close and Re-list listing via the SP-API? 
This is important to me, please.

**Comment by johnkw** [comment]
This is a duplicate of bug #1565 - please close this in favor of the original, which also has some additional information.
