### ISSUE TITLE
How to access France Vendor data through Developer Profile for Spain?

### ISSUE THREAD

**Issue by paulamascot** [amzn/selling-partner-api-docs#2266]
Hi,

My previous issue was closed (https://github.com/amzn/selling-partner-api-docs/issues/2239 ) so I opened a new one.
I requested for Amazon to include the vendor Code for France inside my Spain Developer Profile. As I understand they already included it. 

 However, I cannot access the France's data through the credentials for Spain.
I'm using:
VendorOrders(marketplace= 'Marketplaces.FR') ,credentials=credentials).get_purchase_orders(**kwargs)
with the credentials for Spain.
It is returning the data for Spain, instead of France.

I already tried to re-authorize the APP.

Any help is appreciated. Thank you.

**Comment by YEE271** [comment]
Hello, I would like to ask if you have solved this problem. After authorizing the German supplier credentials, I cannot access the French supplier data in the same region. The French supplier needs to be authorized again before they can access, that is, a single authorization is only a single site
