### ISSUE TITLE
[BUG] Bad Request when using NextToken on getReports

### ISSUE THREAD

**Issue by 547377507** [amzn/selling-partner-api-docs#2271]
I receive a 400 Bad Request response, when calling the getReports endpoint.
![image](https://user-images.githubusercontent.com/13267376/168422825-7ed3726f-dd8e-4a09-9255-6d67755abb20.png)

when I have the NextToken in the request I submitted 
```
    "errors": [
        {
            "code": "InvalidInput",
            "message": "NextToken cannot be specified with other input parameters",
            "details": "createdUntil;createdSince;pageSize;marketplaceIds;processingStatuses;reportTypes;"
        }
    ]
```

Thanks

**Comment by 547377507** [comment]
> @547377507 - When calling get Reports with next token it will not take any other request parameters you need to pass only nextToken

Thank you. I'll try again

**Comment by bijbara0827** [comment]
Hello i have same issue even only passing next token i am still getting same error. 
`reports = []
        res = Reports().get_reports(reportTypes=['GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE'],
						marketplaceIds=marketplace)
        reports = reports + res.payload.get('reports')
        print(res)
        while res.next_token:
            res = Reports().get_reports(nextToken = res.next_token)
            reports = reports + res.payload.get('reports')
        print(reports)
        print(len(reports))`

`sp_api.base.exceptions.SellingApiBadRequestException: [{'code': 'InvalidInput', 'message': 'NextToken cannot be specified with other input parameters', 'details': 'marketplaceIds;'}]
`

**Comment by 547377507** [comment]
@bijbara0827 
![image](https://user-images.githubusercontent.com/13267376/182540809-5b02425d-7d48-4c22-9ee3-929daf9ef3ed.png)
Only nextToken will be sent when the next request is made

**Comment by bijbara0827** [comment]
@547377507 still its giving me error for marketplaceIds
