### ISSUE TITLE
GET_V2_SELLER_PERFORMANCE_REPORT - still stuck on "IN PROGRESS"

### ISSUE THREAD

**Issue by therubioftw** [amzn/selling-partner-api-docs#2272]
Currently we are automating the requests for 3 reports for a few hundred customers, daily.
As of this morning, 2 of them are working, but `GET_V2_SELLER_PERFORMANCE_REPORT` is stuck on `IN PROGRESS` on all of them.

Anyone else seeing this? I realize there was a full-on outage over the past few days - could it be related to that?
Perhaps there's just a long queue of requests Amazon is currently working through?

**Comment by vikingcodes** [comment]
We also facing similar kind of problem with BPO reports.

**Comment by therubioftw** [comment]
We're slowly seeing it come back to normal, we're at about 25% now. Perhaps it was just a long backlog of requests.
The low level of communication from Amazon on this (and in general frankly) is really frustrating.

**Comment by stefnats** [comment]
Also, this seems to be a problem which occurs regularly with other types of reports and even with feeds. I've seen Tickets here with a processing time of a report of 100+ hours. Something seems to get stuck there.

It has always been like this for over 10 years, so it is neither SP Api nor MWS specific. Those APIs just act as messaging layer to the reports/feeds infrastructure.
I don't see Amazon fixing the root of the problem anytime soon.
