### ISSUE TITLE
How can I  create shipment with vendor central account by sp-api?

### ISSUE THREAD

**Issue by ChenRenHu** [amzn/selling-partner-api-docs#2281]
The company's account is Vendor Account. Now we need to integrate vendor's order process into our system. The process is as follows: 

getPurchareOrder ---> comfire order --->  create shipments  --->   submit asn --->   create invoice.

Now I've found that sp - API for vendor only getPurchaseOrders submitAcknowledgement (comfirm), SubmitShipmentConfirmations, submitInvoices;

How can I do this?

**Comment by wonsky87** [comment]
Vendor  Retail?
It is not available for SP-API.
