### ISSUE TITLE
WHO IS MONITORING THESE OPEN ISSUES AS NON HAVE BEEN RESPONDED TO ??

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2284]
How do I raise a complain about this much maligned SP-API

It is clearly not ready to go live by end of JULY 2022

No one is responding to these issues on github and the support team are taking days to respond / fix the outstanding issues

**Comment by nrogers805** [comment]
BUMP

**Comment by Trimakas** [comment]
Clearly no one.. plus the help desk is completely worthless. After a week of trying with them, they suggest that "it must be something with your code".. wow.. Yea I don't get how such a big tech player releases such poor technology.

**Comment by nrogers805** [comment]
> Clearly no one.. plus the help desk is completely worthless. After a week of trying with them, they suggest that "it must be something with your code".. wow.. Yea I don't get how such a big tech player releases such poor technology.

its all a total joke !

**Comment by avvarga** [comment]
Hello @nrogers805 and @Trimakas,

I apologize for any issues that you may have encountered while using our Selling Partner API or with our Support Team.

I understand that you may be experiencing issues with SP API and that some of those may have been posted here in the Issues Tab, however, please take into consideration that, while we are monitoring the Issues Tab in GitHub for potential widespread bugs and Feature Requests, we do not provide Technical Support by this means for several reasons, the main ones being that:

1- The information posted here is public, and in most cases, troubleshooting requires private information regarding your Application or Developer Profile to be provided.
2- The Issues Tab is intended for issues with the repository, the code or any feature requests. For support issues like error codes received when calling our APIs, we have a dedicated Support Team, who will reply to most issues within 24 hours and, if additional investigation is needed, will be able to reach our back-end teams to work alongside them to reach a resolution.

Finally, I would like to mention that we are aware that the GitHub Issues Tab is not being monitored as it should and we are working on improving this, however, it is worth noting that the above will continue to be true and no troubleshooting assistance will be given by this means.

Thanks,
Alejandro C.
Selling Partner API Developer Support
