### ISSUE TITLE
I would like to list my items using the Listing Item API.

### ISSUE THREAD

**Issue by shirushi-dev** [amzn/selling-partner-api-docs#2286]
API > ListingsApi > put:ListingsItem

①Request Param
"product_type" => "PRODUCT",
"requirements" => "LISTING_PRODUCT_ONLY",
"requirements_enforced" => "ENFORCED", 
 "attributes" => [~]

①Response
        {
            "code": "4000004",
            "message": "Creating products is not supported with the \"PRODUCT\" Amazon product type. Either specify a specific Amazon product type or specify an offer-only requirements set.",
            "severity": "ERROR"
        }

------------------------------------------------------------------------

②Request Param
"product_type" => "BUILDING_MATERIAL",
"requirements" => "LISTING_PRODUCT_ONLY",
"requirements_enforced" => "ENFORCED", 
 "attributes" => [~]

②Response
        {
            "code": "4000003",
            "message": "The Amazon product type specified is invalid or not supported.",
            "severity": "ERROR"
        }
   

No matter what I specify for "product_type" I cannot listing my products. I understand that the product type is being migrated, but does this mean that I will not be able to use the product listing function until the migration is complete?

From Japan

**Comment by chapmanjw** [comment]
@shirushi-dev The Product Type Definitions API search operation (https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference) and the Product Type Changed Notifications (https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#product_type_definitions_change) are the best way to keep up-to-date with product type launches on the Definitions and Listings APIs.

At this time, we have not yet migrated and launched product types in Japan. Some product types should, however, be coming later in the year for Japan. Use the API and notification above to stay up-to-date. 

Thanks!

**Comment by panhaoyu** [comment]
Any new progress, please? Hope to use the excellent listings api in Japna.

**Comment by shirushi-dev** [comment]
> Any new progress, please? Hope to use the excellent listings api in Japna.

Unfortunately, no progress has been made.

**Comment by xiaoallen** [comment]
Any new progress, please?

**Comment by xiaoallen** [comment]
Any new progress, please? @chapmanjw

**Comment by xiaoallen** [comment]
or any plan? @chapmanjw
