### ISSUE TITLE
Integrate sellering-partner-api and mws credential

### ISSUE THREAD

**Issue by newsandeep** [amzn/selling-partner-api-docs#2287]
Hi,

I am not able to create mws credential getting error below:
Something went wrong
This Developer is not currently eligible for new authorizations.

Error Code: MD9000

Also can you provide me integration document of selling-partner-api in java doc

Regards,
Sandeep Mishra

**Comment by stefnats** [comment]
Seems like Amazon has blocked new authorizations for you. Contacting dev support might be your best approach.
