### ISSUE TITLE
[BUG] A typo in the reply error message for restrictedDataToken

### ISSUE THREAD

**Issue by magik092** [amzn/selling-partner-api-docs#2288]
I am in the process of implementing a proprietary resource handler using an RDT token. In the process, I encountered a typo in the body of the error message.
Request URL: `https://sellingpartnerapi-eu.amazon.com/tokens/2021-03-01/restrictedDataToken`
Request body: `{"restrictedResources":[]}`
Response errors[0].message: `Empty target resource arguement found`
 Typo in `argu` `e` `ment` -> `argument`

**Comment by johnzhang2013** [comment]
Have you resolved it yet? I am also facing this error.
@magik092

**Comment by magik092** [comment]
My problem was only typo in error message. Problem of Empty target was an non valid request body. You have to pass `method` key and `path` key. `dataElements` is optional.
Example request:
```
{"restrictedResources":[{"method":"GET","path":"\/orders\/v0\/orders","dataElements":[]}]}
```

**Comment by jrmaia** [comment]
Any solution? I have the same issue

**Comment by GJ-JG** [comment]
Hi @magik092 , thank you very much for letting us know the typo.
We have asked the team to fix it

**Comment by magik092** [comment]
Hi @MilordAxel, Our mistake was sending an incomplete request. As I mentioned above, when we pass `method` key and `path` key it was solve the problem. This request works well for our scenario:
```
{"restrictedResources":[{"method":"GET","path":"\/orders\/v0\/orders","dataElements":[]}]}
```

**Comment by MilordAxel** [comment]
> Hi @MilordAxel, Our mistake was sending an incomplete request. As I mentioned above, when we pass `method` key and `path` key it was solve the problem. This request works well for our scenario:
> 
> ```
> {"restrictedResources":[{"method":"GET","path":"\/orders\/v0\/orders","dataElements":[]}]}
> ```

But this solve not work for me. Can you help me?

**Comment by MilordAxel** [comment]
> Hi @MilordAxel, Our mistake was sending an incomplete request. As I mentioned above, when we pass `method` key and `path` key it was solve the problem. This request works well for our scenario:
> 
> ```
> {"restrictedResources":[{"method":"GET","path":"\/orders\/v0\/orders","dataElements":[]}]}
> ```

@magik092 but this solve not work for me. Can you help me solved my problem?

**Comment by magik092** [comment]
I think you have to contact Amazon to resolve your Issue.

**Comment by StormTech07** [comment]
I have same problem, did you had resolve this problem?

**Comment by thirdpartycook** [comment]
For me, the JSON body was not constructed correctly

Incorrect JSON which I was sending
$data['restrictedResources'] = array('method' => $library_request['methodRDS'],'path' => $library_request['pathRDS'],  'dataElements' => $library_request['dataElementsRDS']);
json_encode($data, JSON_UNESCAPED_SLASHES);

{"restrictedResources":{"method":"GET","path":"/orders/v0/orders","dataElements":"buyerInfo"}}

Correct JSON
$data['restrictedResources'][] = array('method' => $library_request['methodRDS'],'path' => $library_request['pathRDS'],	'dataElements' => $library_request['dataElementsRDS']);

{"restrictedResources":[{"method":"GET","path":"/orders/v0/orders","dataElements":"buyerInfo"}]}
