### ISSUE TITLE
How can I get seller info (shop name,..) after got access token?

### ISSUE THREAD

**Issue by twanlee** [amzn/selling-partner-api-docs#2291]
Hi guys,
I'm recently building an app. I can get access token after authorized but the values return has only seller id. How can I get their name or shop to display on the management page? I've read all of the authorized documents but I found nothing!
If anyone has this experience, please help!
Thank you, guys!

**Comment by moltar** [comment]
There is no way.

**Comment by twanlee** [comment]
> There is no way.

Thank you for answering me! May I ask you one more! How could we identify the seller's store on our system to let them know what is precisely their shop they want to you if they have 2 more stores?

**Comment by chapmanjw** [comment]
@twanlee and @moltar Currently, there is no API that provides this information. With that said, however, we are aware of the gap in experience and are looking at what we can add to our roadmap to fill this gap. Beyond the name of the seller account, are their any other account-specific details that your use-cases need?

**Comment by twanlee** [comment]
> @twanlee and @moltar Currently, there is no API that provides this information. With that said, however, we are aware of the gap in experience and are looking at what we can add to our roadmap to fill this gap. Beyond the name of the seller account, are their any other account-specific details that your use-cases need?

Hi @chapmanjw , Thank you for answering. For my case, sellers authorized us to post product to their store on amazon. We need at least their brand name for using Feeds API to post their product! 
![image](https://user-images.githubusercontent.com/61691162/174529213-dfd90f3e-bd06-4d19-95af-48629e717332.png)

**Comment by MoorsTech** [comment]
> @twanlee and @moltar Currently, there is no API that provides this information. With that said, however, we are aware of the gap in experience and are looking at what we can add to our roadmap to fill this gap. Beyond the name of the seller account, are their any other account-specific details that your use-cases need?

I think a reasonable set of attributes for both seller and vendor accounts would be:

- Account Name
- Timezone
- Country (I believe only available for sellers right now)
- Vendor Code

Also, Is there any ETA on this?

**Comment by puneet-banknovo** [comment]
is there any update on when we can get this api ?
