### ISSUE TITLE
listings-items-api operation PatchListingItem

### ISSUE THREAD

**Issue by fengyuduke** [amzn/selling-partner-api-docs#2292]
API > ListingsApi > patch:ListingsItem

I wanna try to replace the product_description of Item,but failed.

requestUrl : Request{method=PATCH, url=https://sellingpartnerapi-na.amazon.com/listings/2021-08-01/items/JOBN7/312547306706?marketplaceIds=ATVPDKIKX0DER, tag=Request{method=PATCH, url=https://sellingpartnerapi-na.amazon.com/listings/2021-08-01/items/JOBN7/312547306706?marketplaceIds=ATVPDKIKX0DER, tag=null}}

Parameter : ListingsItemPatchRequest {
    productType: MOUTHWASH
    patches: [class PatchOperation {
        op: replace
        path: /attributes/product_description
        value: [class ProductDescription {
            value: Zero alcohol anticavity mouthwash with 6 benefits in 1. Helps prevent cavities. Restores enamel. Strengthens tooth. Kills bad breath germs. Cleans the whole mouth
        }]
    }]
}

Result : class ListingsItemSubmissionResponse {
    sku: 312547306706
    status: INVALID
    submissionId: e16ef293b6624f23990b9ea7b23b75f4
    issues: [class Issue {
        code: null
        message: The attributes are invalid.
        severity: ERROR
        attributeNames: [product_description]
    }]
}

Otherwise,we really want to do is replace the images of asin.How Can I pack the parameters?

**Comment by chapmanjw** [comment]
@fengyuduke Using the Product Type Definitions API as the selling partner you are using the Listings API for is the best way to get the valid attributes and attribute structure that applies for that selling partner. Note, there are differences in the attributes between sellers and vendors. If you are requesting JSON Schemas from the Product Type Definitions API with your developer seller account, they would not work when submitting for vendors. You need to call the Product Type Definitions API  as the vendor to get the correct schemas.

**Comment by fengyuduke** [comment]
Our purpose is replace images、description and other attributes about asin.We visit the 'PatchListingItem' Api  is right?

**Comment by fengyuduke** [comment]
If the Patch ListingApi is correct,the response :
class ListingsItemSubmissionResponse {
    sku: 312547306706
    status: INVALID
    submissionId: cc9aae55525b484bac1b1a4ad24acfc5
    issues: [class Issue {
        code: 90220
        message: 'package_contains' is required but not supplied.
        severity: ERROR
        attributeNames: [package_contains]
    }, class Issue {
        code: 4005006
        message: An item in your catalog already exists for the value of 'external_product_id' and the value of 'external_product_id' is not editable. For different products, resubmit with a different value.
        severity: ERROR
        attributeNames: [external_product_id]
    }, class Issue {
        code: 90220
        message: 'package_level' is required but not supplied.
        severity: ERROR
        attributeNames: [package_level]
    }]
}.

This three attributeNames are not involved in request parameters .

**Comment by chapmanjw** [comment]
@fengyuduke When processing vendor submissions, they are merged with the existing listings data and then validated. To troubleshoot these specific listings, please contact Developer Support. There is likely already issues on these listings that need to be resolved before they can be edited.
