### ISSUE TITLE
[BUG] Documentation - vendor report deprecation

### ISSUE THREAD

**Issue by jamesp26** [amzn/selling-partner-api-docs#2297]
In the SP-API release announcement yesterday, the following 3 reports were listed as vendor reports being deprecated on the 27th June:

•	GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA
•	GET_EXCESS_INVENTORY_DATA
•	GET_FBA_INVENTORY_AGED_DATA

These are not vendor reports, and its the first we've seen that these are being deprecated as these are reports we use. I can't see any reference to these in report migration documentation. Were these added to the email in error?

**Comment by mentiaa** [comment]
Thank you for raising this issue. Previous communication of this deprecation was announced in [March 2022](https://developer-docs.amazon.com/sp-api/changelog/march-2022-sp-api-release-announcement#report-deprecations). Documentation is now [updated](https://github.com/amzn/selling-partner-api-docs/discussions/2289). 

Thanks,
Abby
Selling Partner API Documentation
