### ISSUE TITLE
Missing OAuth authorization URIs: Possible Docs Issue?

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-docs#23]
In docs under "Authorizing Selling Partner API applications" => "Website Workflow" => "Step 0. Set up your OAuth authorization URIs" when referring to setting up the "Authorize" button it states - "When the seller clicks the button, your website loads an OAuth authorization URI into the browser and the seller is redirected to a Seller Central sign-in page. **You get your OAuth authorization URIs when you register your application.**"

I've registered for the SP-API and the above mentioned **OAuth authorization URIs** are blank in Seller Central. It is instead an input box for me to add my own. In the docs it does mention using the correct URI per region when linking to your "Authorize" button, but I haven't seen anywhere where the direction is to add them yourself in Seller Central nor which ones to add specifically. The docs do give the following example "https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample" not sure if you would simply switch the top level domain for different regions or what but regardless the documentation doesn't seem to match with the experience. Please let me know if I'm missing something. Thanks!

**Comment by charliecode** [comment]
So it appears this needs to be made more clear in the documentation. I was able to use the example URI ("https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample", can also add &version=beta to the end for testing) to get a successful redirect to Seller Central which runs the client through approving the developer. I would imagine if you wanted to get setup for another region all you would do is change the top level domain of the URI. However, the docs mention that these URI's come pre-filled when you register your app and they did not for me. Hope this helps.

**Comment by charliecode** [comment]
I should also mention, even though using the example URI does send the user to Seller Central and allows them to approve the developer. It does not actually redirect after this is done. Therefore I've started a separate issue ( #26 ) to address this as well.

**Comment by ShivikaK** [comment]
Hello,

Thank you for reaching out and conveying this concern.

We are working on updating the documentation to clarify the confusion around "Setting up your OAuth Authorization URIs" and the step of providing login and redirect URIs during registration which is required for the OAuth workflow setup.

**Comment by ShivikaK** [comment]
While we are working on getting the developer guide updated, please refer below to the authorization URI information -

The OAuth Authorization URI for NA region is -

**https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&version=beta&state=stateexample**
Replace {applicationId} with the ID of the application that you have updated.

Please note that the OAuth authorization URI's are regionalized.
For other regions the URL is basically the same but you are required to change the domain for whichever Seller Central site you want to authorize.

For example, below is the link for UK and JP:

**https://sellercentral.amazon.co.uk/apps/authorize/consent?application_id={appidexample}&version=beta&state={stateexample}**

**https://sellercentral.amazon.co.jp/apps/authorize/consent?application_id={appidexample}&version=beta&state={stateexample}**

**Comment by rodrigojob** [comment]
The Marketplace Appstore workflow Step 3. The seller signs into your website example URL is wrong. 
https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&version=beta&state=stateexample

https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.2eca283f-9f5a-4d13-b16c-474EXAMPLE57?redirect_uri=https://d2yzyfnnpjylxu.cloudfront.net/landing.html&amazon_state=amazonstateexample&state=-37131022&version=beta

**Comment by EstebanSP-506** [comment]
Hello charliecode,

Please accept our sincere apology for the delay in getting back to you.

I have documented your inputs here, and in https://github.com/amzn/selling-partner-api-docs/issues/26

The documentation update is currently under review.

Thanks,

Esteban

Selling Partner API Developer Support
