### ISSUE TITLE
Orders API - getOrderItemsBuyerInfo response: BuyerCustomizedInfo.CustomizedURL is empty.

### ISSUE THREAD

**Issue by nodisk8800** [amzn/selling-partner-api-docs#230]
I am develop the Orders API(https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md) in the Selling Partner API (SP-API).

I call getorderitemsbuyerinfo API(https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorderitemsbuyerinfo),to get the "CustomizedURL",and the getorderitemsbuyerinfo response is:

{"payload":{"OrderItems":[{"OrderItemId":"xxx","BuyerCustomizedInfo":{"CustomizedURL":""}}],"AmazonOrderId":"xxx"}}

I want to get this "CustomizedURL" to download Customized Infomation,but the "CustomizedURL" in response return empty.
I am sure the order is a Customized Order,it contain the CustomizedURL.
I try another Customized OrderID,and the "CustomizedURL"  also return empty.

But,I try MWS API,call ListOrderItems API with same orderid,it can return the "CustomizedURL" and download the Customized Infomation zip file by ""CustomizedURL"" successful.

One of the x-amzn-RequestId: 8ed9bb57-d6a3-47d3-897a-0bb2f7f6e9dd.

If need more details ,reply this issues.
Thanks!

@parvathm 
@amzn

**Comment by wangjue666** [comment]
@nodisk8800   Is your app in draft status ？  If so, some of the returned information is missing。

**Comment by nodisk8800** [comment]
app私用,不想公开url,所以只能保持  draft status .

**Comment by nodisk8800** [comment]
@ShivikaK 
The Case ID is 7745187661.
Thanks!

**Comment by ShivikaK** [comment]
Hello @nodisk8800 

We have received your support case and are working on it. 

We will get back to you via case correspondence for any additional information required.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
