### ISSUE TITLE
Upload order invoice, feeds api, UPLOAD_VAT_INVOICE - 79513	Error

### ISSUE THREAD

**Issue by raduprime** [amzn/selling-partner-api-docs#2301]
Hello,
I'm trying to upload an invoice via SP-API version 2021-06-30 according to this documentation: https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#createfeedspecification
I'm able to create the feed document, upload the invoice, creating the feed also works ( I receive no errors in the request).
When the feed status is marked as done (checked via the getFeed route), I retrieve the feed document to see if there are any errors (following the docs, ofcourse: https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#getfeeddocument)

In the feed document report I get this error: 
Feed Processing Summary:
	Number of records processed		1
	Number of records successful		0

original-record-number	sku	error-code	error-type	error-message
1		79513	Error	Please provide metadata:shippingid or metadata:orderid,metadata:invoicenumber,metadata:totalamount,metadata:totalvatamount

The route for creating the feed is: POST: /feeds/2021-06-30/feeds

The payload for creating the feed is (I replaced real data with mocked data): 

{
        feedType: 'UPLOAD_VAT_INVOICE',
        inputFeedDocumentId: 'feedDocId',
        marketplaceIds: [ 'marketplaceId' ],
        feedOptions: {
          AmazonOrderId: 'orderNr',
          DocumentType: 'Invoice',
          InvoiceNumber: 'the invoice number',
          TotalAmount: 34.62,
          TotalVATAmount: 5.53
        }
}

PLease let me know why I'm getting the error above since I'm doing everyting as it's specified in the documentation.

**Comment by raduprime** [comment]
In the meantime I found out the issue which was the feedOptions object.
I will leave it here in case anyone will ever encounter this issue. The correct object format is: 

 feedOptions: {
      'metadata:orderid': amazonOrderId,
      'metadata:invoicenumber': invoiceNumber
    };

**Comment by davhol86** [comment]
Hi @raduprime 

im trying to accomplish the same, but i allways get error 403 Unauthorized when trying to create the feed with POST:  /feeds/2021-06-30/feeds.

```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}
```

I can call other endpoints like the GET:/sellers/v1/marketplaceParticipations without problem.

Have any idea?

By the way i've a private seller app and registered the app with the user IAM not the role. Not sure if thats the problem?

**Comment by raduprime** [comment]
Did you read this? https://github.com/amzn/selling-partner-api-docs/issues/404#issuecomment-882016084

**Comment by davhol86** [comment]
I have this permission in the APP-Registration, but the app registration is related to a iam user not a role....

**Comment by davhol86** [comment]
Hi @raduprime , 
now I've understand what u ment by tax role. It's not the permission when u register the app, but the tax role in the developer profile.
I really think that could be the solution of my problem. I don't have access to the Seller Center, so I will check this next week with our customer and let u know.
Thank u for the advice!

**Comment by Philomath88** [comment]
Has anyone encountered this error before? 

original-record-number  sku     error-code      error-type      error-message
1               79555   Error   The uploaded document is invalid.
