### ISSUE TITLE
Authorization of access to PII information to get Tax Invoice 

### ISSUE THREAD

**Issue by MenTheeRengan** [amzn/selling-partner-api-docs#2302]
We need to download GET_GST_MTR_B2B_CUSTOM, GET_GST_MTR_B2C_CUSTOM reports, purchase orders, and invoice details from Amazon seller central account., Because Amazon only provides these reports on the 7th of next month, we have to upload them into our ERP system on the shipment date and we have submitted tax details before month-end as well as we are getting more orders nowadays so we couldn't upload into our ERP system manually. So we plan to integrate through API.

We have logged this issue multiple times But They are rejecting without saying any proper reason. This time we submitted it 15 days back still it showing under review.

Our Developer ID: 608779083906
Last Case ID: 7707606792

**Comment by msaiyamjain** [comment]
I am having the same issue @MenTheeRengan. Did you find any solution for this?

**Comment by MenTheeRengan** [comment]
> I am having the same issue @MenTheeRengan. Did you find any solution for this?

No i don't any solution for this.
