### ISSUE TITLE
Attribution window for sales and traffic report

### ISSUE THREAD

**Issue by discover59** [amzn/selling-partner-api-docs#2303]
I use `GET_SALES_AND_TRAFFIC_REPORT` report to get sales and traffic by day.

To achieve it, I set DAY in "dateGranularity" option.
But the data returned for same day is different if I pull it again next day.

I guess it's due to attribution window of the metrics such as views, sessions, etc.
What's the attribution window of this report?

**Comment by krithic15** [comment]
Hello @discover59,
Reports may take up to a week to populate data after a reporting periods closes (e.g. day, week, month). We aim to update all weekly reports within 72 hours (i.e. Tuesday) and continuously work to improve our system to get reports to you faster. For a reportPeriod set to 'DAY', kindly wait up to 72 hours to pull the report.

Best,
Krithi, Solutions Architect, SP API
