### ISSUE TITLE
Missing FeeAmountAdjustment in RemovalShipmentAdjustmentEventList (Finances API)

### ISSUE THREAD

**Issue by CrackHead007** [amzn/selling-partner-api-docs#2306]
The RemovalShipmentItem has 4 different Currency fields: **[Revenue, FeeAmount, TaxAmount, TaxWithheld]**

![image](https://user-images.githubusercontent.com/104869329/169836385-d459c3a7-8368-4c41-9bbf-d101f1f23d16.png)

But RemovalShipmentItemAdjustment has just 3: **[Revenue, TaxAmount, TaxWithheld]**

![image](https://user-images.githubusercontent.com/104869329/169836620-963e0732-f8aa-4001-8e20-a0f2f4258b5d.png)

In Amazon Seller Central looking at specific groups would show:
Liquidations and Liquidations Adjustments would contain three fields: **[LiquidationsBrokerageFee, Principal, Tax]**

**Adjustments has data missing in the API.**

**Comment by clegendre** [comment]
Could we reopen this issue please, since this is not fixed?
Or maybe there is a workaround available?
