### ISSUE TITLE
API to Check Enabled Roles

### ISSUE THREAD

**Issue by wangjoshuah** [amzn/selling-partner-api-docs#2307]
Is there an API on the SP API that I can ping with my customer account's authorized token to check what roles are enabled for the token? I have multiple customers who have authorized my application over a long period of time. During that time, my application has been granted additional roles from Amazon. Is there any way I can check which customer tokens have the new roles and which don't by pinging the SP-API? Or will I have to do trial and error with catching 403s?

**Comment by krithic15** [comment]
Hello @wangjoshuah,
We have this feature request added to our roadmap but I am unable to share an ETA at the moment. We appreciate your patience!

Best,
Krithi, Solutions Architect, SP API
