### ISSUE TITLE
[BUG] Access to requested resource is denied.

### ISSUE THREAD

**Issue by KhoaDauTay** [amzn/selling-partner-api-docs#2308]
I have created a Fast-API backend for receiving the ASIN product from the client and sending it to the SP-API. Everything works very well in the local environment. But when I deploy to Lamda I always get a 403 error with the following message: "Access to the requested resource is denied."

```
{'Date': 'Tue, 24 May 2022 04:41:43 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'x-amzn-RequestId': '58fff0ba-29e6-4185-bf61-100fbc468045', 'x-amzn-ErrorType': 'AccessDeniedException', 'x-amz-apigw-id': 'SnRBMGdsoAMFuLw='}
```
If someone has similar errors please help me fix them. Note: The client id, key, IAM id, IAM key, Role ARN information all work fine in Local.

**Comment by jrmaia** [comment]
Solve this? I have the similar issue
