### ISSUE TITLE
Unclear rate and burst

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#2309]
Hello, Im trying to send requests to [listingItems](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#get-listings2021-08-01itemsselleridsku) and I have used settimeout to exactly call 2 requests in one second. With that Im still getting too many requests. Can someone explain what have I done wrong???

Also the file is my timings in utc
[time.txt](https://github.com/amzn/selling-partner-api-docs/files/8760822/time.txt)

**Comment by chapmanjw** [comment]
@Javadebi I suggest contacting Developer Support so that they can investigate the specific calls coming from your application. Retries are often a culprit that masks the true rate you are seeing, but we would need to verify.
