### ISSUE TITLE
Always "Access to requested resource is denied"

### ISSUE THREAD

**Issue by goodiebag45** [amzn/selling-partner-api-docs#231]
I simply cannot get access to SellingPartner and I am completely lost trying to find the reason.

At first I followed the instructions, but received "Unauthorized" calling marketplaceParticipations. Contacted support and after 6 weeks received an answer indicating they looked at the request from someone else. Replied back with a new request and have waited 2 weeks for reply.

Not familiar with github, so only today I found this "Issues", and could see that many other had problems. And I did not call "AssumeRole", so I thought I had found the reason. But I still cannot access SellingPartner.

I downloaded the aws-sdk for Go and I am using that to call "AssumeRole" and then using V4Sign before sending request. I still get "Unauthorized".

I also tried setting the needed policy for IAM User instead of IAM Role and in Sellers Central create the app for user and not role. Doing that I could skip the "AssumeRole".  But I still get "Unauthorized".

These 2 solutions seemed to solve the problem for everybody else, but not me. So what am I missing?

Since support has about 6 weeks of waiting before replying, it will take forever, so I am hoping someone maybe have had similar problem or just have a suggestion what to look at. Maybe there is some simple PHP or Golang code, that I can just plug my AccessKey, SecretKey, etc. in and test if that works.

It just seems I am the only one with this problem now, and I could really use some help.

**Comment by weiliguo15634145** [comment]
Have you found the answer , I had the same problem , And I need your help.
