### ISSUE TITLE
Operation getInventorySummaries not returning all products

### ISSUE THREAD

**Issue by dane5102** [amzn/selling-partner-api-docs#2312]
I'm trying to call the getInventorySummaries operation listed here to make a list of all our products and their inventories:
https://developer-docs.amazon.com/sp-api/docs/fbainventory-api-v1-reference

The problem isn't calling the operation itself. I can make the call but it for some reason returns backs "most" of products. Some products are just missing from the results after calling the operation and I'm very stumped as to why. I believe I'm handling the pagination correctly with the 'nextToken' variable (after the first call just make the same call again but pass the nextToken as a parameter into the query line, until 'nextToken' isn't returned from a call), so I don't think I'm skipping over a page of results or anything like that. 

I outputted the SKU of each product as it went through each page in the results, and it looks like the items it would output were sorted alphabetically based on SKU. Each page would have a max of 50 products and while it went through one page, I noticed that one of the SKUs that was missing from earlier should've been a part of that page, but it just looks like it was skipped entirely, and I noticed the same thing for other products on the other result pages. Even if I was skipping a page of results somehow, that product that was missing should've been on that page regardless, which is why I don't think I'm handling pagination wrong. I believe that out of the total amount of products the operation should be returning, it's missing around 100 of them.

The call I'm making is excluding the 'sellerSkus' and 'startDateTime' parameters, which should theoretically return every single product, but some are just missing. However, if I include the 'sellerSkus' parameter and input the SKUs that were missing from the initial call, the results come back just fine and I can view their inventory data. The data is definitely there and it's grabbable, but for whatever reason calling that operation without those two parameters, which again should return all products, just decides to skip over some products. Any idea on why this is happening?

**Comment by dane5102** [comment]
Fixed, I was unaware you had to encode the token before passing it through.

**Comment by johninf2022** [comment]
@dane5102 
It is so lucky of you to fix it well.  However, I am still struggling with this operation.
I followed the instructions of this call but always got an error message. 
------------------
"errors": [
 {
      **"code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""**
}
]
------------------
I used these following parameters in the request.
$params = [];
$params['details'] = true;
$params['granularityType'] = 'Marketplace';
$params['granularityId'] = $marketplace_id;
$date = new DateTime('2022-06-01 00:00:00', new DateTimeZone('UTC'));
$params['startDateTime'] = $date->format("Y-m-d\TH:i:s.v\Z");

**What makes me very depressed is the error message didn't tell me which parameter is invalid.**

By the way, most of my other calls could work well such as getItemEligibilityPreview/createFeedDocument/createReport etc.

Great appreciate it if somebody could help me go through this issue.

**Comment by johninf2022** [comment]
Oh... I don't know how to make an appraise for the AMZ SP-API...

I finally fixed it myself with one funny modification.
$params['details'] = true;   to  $params['details'] = 'true';

It works well now.....

**Comment by peanutli1985** [comment]
> Fixed, I was unaware you had to encode the token before passing it through.

how did you fix it?

**Comment by dani24gl** [comment]
Also I fixed this issue using the parameter 'details' with the text 'true', BUT is also worth noting that even when the docs says that the `details` param is optional that's not true, It's actually **mandatory**
