### ISSUE TITLE
Error Code: MD9000 This Developer is not currently eligible for new authorizations

### ISSUE THREAD

**Issue by judev-jbgonzales** [amzn/selling-partner-api-docs#2314]
Hello:
I have created a private app and used Self authorization, however, I try to register the developer on amazon seller and I get MD9000 error.
Can you help me? I don't know what steps to follow to be able to consume the API.

Id app: amzn1.sp.solution.ef2e1320-90c7-4377-abb1-2a692ec53738

**Comment by sungolivia** [comment]
hey @judev-jbgonzales  have you tried the suggestion mentioned in this blog?
https://developer-docs.amazon.com/sp-api-blog/docs/troubleshooting-selling-partner-api-authorization-errors
