### ISSUE TITLE
Create Feed Invalid Request Parameters POST_ORDER_FULFILLMENT

### ISSUE THREAD

**Issue by mcbrideke** [amzn/selling-partner-api-docs#2315]
I am on step 4 of the Feed Guide trying to upload a test document to update order fulfillment https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide.

Error: Invalid Request Parameters

Here's the XML im trying to upload:
```
<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.02</DocumentVersion>
        <MerchantIdentifier>XXX</MerchantIdentifier>
    </Header>
    <MessageType>OrderFulfillment</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <OperationType>Update</OperationType>
        <OrderFulfillment>
            <AmazonOrderID>XxybsdA</AmazonOrderID>
            <MerchantFulfillmentID>1</MerchantFulfillmentID>
            <FulfillmentDate>2022-05-23T18:51:57Z</FulfillmentDate>
        </OrderFulfillment>
    </Message>
</AmazonEnvelope>
```
Here is my Create Feed Request:
```
{
      "resource": "/feeds/2021-06-30/feeds",
      "parameters": [
        {
          "name": "application/json",
          "value": "{\"feedType\":\"POST_ORDER_FULFILLMENT_DATA\",\"marketplaceIds\":[\"ATVPDKIKX0DER\"],\"inputFeedDocumentId\":\"amzn1.tortuga.*****\"}",
          "type": "RequestBody"
        },
        {
          "name": "x-amz-access-token",
          "value": "Atza|******",
          "type": "HttpHeader"
        },
        {
          "name": "X-Amz-Security-Token",
          "value": "*******",
          "type": "HttpHeader"
        },
        {
          "name": "X-Amz-Date",
          "value": "*****",
          "type": "HttpHeader"
        },
        {
          "name": "host",
          "value": "sellingpartnerapi-na.amazon.com",
          "type": "HttpHeader"
        },
        {
          "name": "Authorization",
          "value": "******",
          "type": "HttpHeader"
        },
        {
          "name": "Accept",
          "value": "application/json, application/xml, text/json, text/x-json, text/javascript, text/xml",
          "type": "HttpHeader"
        }
      ],
      "method": "POST",
      "uri": "https://sellingpartnerapi-na.amazon.com/feeds/2021-06-30/feeds"
    }
```
Additional Info:

- im signing this call just like all the previous calls that needed to be signed, so no issue there i think
- the content type for the previous two steps were set as contentType = "text/xml; charset=UTF-8", so the content types should all match up
- im using c# and using restSharp library to make all my calls

Possible Problems:

- something is missing or incorrect in the xml
- honestly i dont know my merchant id (where do you find it in vendor central??) so ive just been putting a placeholder there
- something is off from the previous calls that did not cause an error

**Comment by gonzalo-meto** [comment]
Hello, I'm doing the same  feed type implementation.
`<?xml version="1.0" encoding="iso-8859-1" ?>
	<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	  <Header>
		<DocumentVersion>1.01</DocumentVersion>
		<MerchantIdentifier>M_EXAMPLE_123456</MerchantIdentifier>
	  </Header>
	  <MessageType>OrderFulfillment</MessageType>
	  <PurgeAndReplace>true</PurgeAndReplace>
	  <Message>
		<MessageID>1</MessageID>
		<OrderFulfillment>
			<AmazonOrderID>123-1231233-12312312</AmazonOrderID>
			<FulfillmentDate>2022-05-26 12:00:00</FulfillmentDate>
			<FulfillmentData>
				<CarrierCode>FedExx</CarrierCode>        
				<CarrierName>Name</CarrierName>
				<ShipperTrackingNumber>123-123-321</ShipperTrackingNumber>
			</FulfillmentData>
		</OrderFulfillment>
	  </Message>
	</AmazonEnvelope>`

This is the xml that I'm Sending and is returning me a 200 code. 

It seems that MerchantFulfillmentID is optional if AmazonOrderId element is present.

**Comment by mcbrideke** [comment]
@gonzalo-meto thanks for the response, but no luck trying your xml unfortunately.
Can I ask:
1) are you setting the content type of the create feed specification and upload feed document calls to: text/xml; charset=iso-8859-1
2) what language are you working with and how you are formatting your xml string to send in the call

**Comment by gonzalo-meto** [comment]
Hello,
1. No in the HttpClient I'm setting the ContentType to "text/xml; charset=UTF-8". It really depends on the version you are using, It seems the newest version requires "contentType" but in the 2020 version the param should be "content_type". Check out the syntax.
2. I'm using PHP using the Clousale library. The code where I format the xml is as shown below
`$xml = new SimpleXMLElement("<?xml version=\"1.0\" encoding=\"utf-8\"?><AmazonEnvelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='amzn-envelope.xsd' ></AmazonEnvelope>" );
	  
array_to_xml( $array, $xml );
	  
$xmlString =  $xml->asXML();`

Then I encrypt the data and sent it:
`
$encryptedFeedData = openssl_encrypt(utf8_encode($xmlString), 'aes-256-cbc', $key, OPENSSL_RAW_DATA, $initializationVector);
`

Right now I've completed the 8 steps the tutorial shows, but as I'm sending dummy data, the report display errors. I'll be creating an amazon order to full test this steps. 
I'll be around in case you need something else
