### ISSUE TITLE
Why do I have to be a vendor to see the Category for a product?

### ISSUE THREAD

**Issue by chriskshipcor** [amzn/selling-partner-api-docs#2317]
Unlike the Catalog Items API v0, Catalog Items API v2020-12-01 and Catalog Items API v2022-04-01 require vendor credentials to get the category tree and category IDs for a listing. Why is it that a Seller account can create and edit listings but it can't see the category through the API? Often times a listing will lose its browse node and we are currently unable to tell until it's too late and not selling.

**Comment by chapmanjw** [comment]
The v0 `listCatalogCategories` API operation is currently the only one that provides the category tree, which is available to sellers: https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference#listcatalogcategories.

The product category and sub-category information in the `vendorDetails` of v2020-12-01 and v2022-04-01 are vendor-specific financial classifications. They are not the same thing as browse categories / classifications.

The `summaries` section of v2022-04-01 provide the browse classification (the leaf node), but not the whole tree. 

While I cannot speak to a specific timeline, we are working on a replacement for the `listCatalogCategories` API operation for searching, traversing, and looking up browse classifications / categories.

**Comment by hamduc7** [comment]
Hi @chapmanjw 
_"While I cannot speak to a specific timeline, we are working on a replacement for the listCatalogCategories API operation for searching, traversing, and looking up browse classifications / categories."_

=>Is there any update on this issue?.

 I would like to get the root category and Sales rank for a given ASIN but I cannot find an API for this purpose.
