### ISSUE TITLE
reports-api: access to the resource is forbidden 

### ISSUE THREAD

**Issue by thai101795** [amzn/selling-partner-api-docs#2319]
I am using Java, When i try and call GET_ORDER_REPORT_DATA_SHIPPING i get a 403:
{'errors': [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]}
(My application had "Amazon Fulfillment" role )

Can you help me with the issue?

**Comment by thai101795** [comment]
[](url
![shitumon](https://user-images.githubusercontent.com/99698722/170668773-6a522a41-ef30-4ca7-9ec6-3a12fce2a8e4.png)
)

**Comment by thai101795** [comment]
![shitumon2](https://user-images.githubusercontent.com/99698722/170669053-4b208a87-c16a-4b95-8350-7255e8d94477.png)

**Comment by thai101795** [comment]
My request: (Connection info i also added)
{"reportTypes":["GET_ORDER_REPORT_DATA_SHIPPING"],"marketplaceIds":["A1VC38T7YXB528"]}

**Comment by thai101795** [comment]
when i call to GET_FLAT_FILE_OPEN_LISTINGS_DATA i will get null data.
![shitumon4](https://user-images.githubusercontent.com/99698722/170671655-e08c5920-319b-45a9-8f61-4620d65ad07f.png)

**Comment by dane5102** [comment]
Have you had it working before or is this the first time? I ask because maybe it might be an Amazon sided issue. My app was running the API just fine a few days ago then suddenly I'm getting "Access to resource is denied" for any call I make. Nothing was changed at all, so I can't imagine that I did something to break it.

**Comment by rohitdobariyaleanspace** [comment]
@thai101795 after review your code on screensort seems like you make mistakes on creating AWS credentials, make sure you tested on postman collection first and that your credentials working as expected.

**Comment by rohitdobariya** [comment]
@thai101795 after review your code on screensort seems like you make mistakes on creating AWS credentials, make sure you tested on postman collection first and that your credentials working as expected.

**Comment by thai101795** [comment]
@rohitdobariya Thanks for the reply from you.

I tried on postman also same error.

I have also set up step-by-step according to the instructions, the order and feed are fine, only the report is error, can you help me with some settings related to the report?

**Comment by rohitdobariya** [comment]
@thai101795 you can join me here will discuss . meet.google.com/ogx-doba-ysz

**Comment by thai101795** [comment]
@rohitdobariya I am very sorry for going out now. Can I discuss with you in 4 hours? when we discuss it would be great if we can talk in Japanese.

**Comment by thai101795** [comment]
@rohitdobariya I am very sorry for going out now. Can I discuss with you in 4 hours? when we discuss it would be great if we can talk in Japanese.
