### ISSUE TITLE
getCatalogItem response is Unauthorized.

### ISSUE THREAD

**Issue by luoshishu** [amzn/selling-partner-api-docs#232]
I want to using the spapi [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#getcatalogitem) to get product's data.

Now , My Request:
Request URL = https://sellingpartnerapi-eu.amazon.com/catalog/v0/items/B08KG9M3K4?MarketplaceId=ATVPDKIKX0DER
Response http code is '403', and the message is '{"message": "Access to requested resource is denied.","code": "Unauthorized","details": ""}'

--------------------------------

But , At the same time using the same access token's other spapi [getPricing](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing)
Request URL = https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/price?MarketplaceId=ATVPDKIKX0DER&ItemType=Asin&Asins=B08KG9M3K4
Response http code is 200. This is right.

This is why? How can i do for correct it?

**Comment by w2m** [comment]
I have a similar problem. The same access token can recv  respones data when call the orders and report api, but when call the FBA inventory api, Response http code is '403', and the message is '{"message": "Access to requested resource is denied.","code": "Unauthorized","details": ""}'

**Comment by Jethro-Wilkinson** [comment]
I'm having a similar issue as well. When using product fees api I get a 403 response but I have no problems when using the orders api.

**Comment by yusufdonmez** [comment]
It is maybe because of role that you get access from "developer profile".

By the I want to learn which role should we get access to reach the which api endpoints.
Is there a schema etc. explain that ?
roles:
![image](https://user-images.githubusercontent.com/245283/103282222-2bbc5280-49e6-11eb-84c9-1b34efdd9875.png)
APIs:
![image](https://user-images.githubusercontent.com/245283/103282258-41ca1300-49e6-11eb-9c2d-f074a3a4528a.png)

**Comment by luoshishu** [comment]
Your reply is likely to be the cause of the problem, because I found that the developer's role option only checked "inventory and order management".

Now I'm going to re apply for the developer registration to try.

Thank you very much！ @yusufdonmez

**Comment by codernice** [comment]
i call every api all return this problem,what can i do

**Comment by weiliguo15634145** [comment]
Have you found the answer , I had the same problem , And I need your help.

**Comment by luoshishu** [comment]
The reason for my problem is that there Amazon's AWS developer Account is no product listing in Roles.

Hoping This Helps. @weiliguo15634145

**Comment by estebanangel** [comment]
I have the same problem, in the Roles page in the APP details there's only 3 options, not 6 as showed in the screenshot. How can we have access to the rest of the roles?
