### ISSUE TITLE
not able to get order information from Canada marketplace 

### ISSUE THREAD

**Issue by pucsdian** [amzn/selling-partner-api-docs#2320]
hi, need urgent help
i have refresh token for north america region so that
i have access to US marketplace and i can get order information for US orders
but when I am trying to get order information from canada marketplace
got following error
`{
	"errors": [
		{
			"code": "ResourceNotFound",
			"message": "Cannot find resource by the given URI"
		}
	]
}`

so my que's is:
1 . do i need to make change in previously got token to make it work 
2. do i need to generate credentials for canada too
3.  any other suggestion ,,

**Comment by Adrian-T-AMZN** [comment]
Hello @pucsdian,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
