### ISSUE TITLE
Can't create Brand Analytics report

### ISSUE THREAD

**Issue by hongfei-zhou** [amzn/selling-partner-api-docs#2326]
My app is approved and published with `Brand Analytics` role. But when calling `createReport` API for report:
```
{
	"reportType": "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT",
	"reportOptions": {
		"reportPeriod": "DAY"
	},
	"dataStartTime": "2022-04-03T00:00:00+00:00",
	"dataEndTime": "2022-04-24T00:00:00+00:00",
	"marketplaceIds": ["ATVPDKIKX0DER"]
}
```
I am still getting
```
{
	"errors": [
		{
			"message": "Access to requested resource is denied.",
			"code": "Unauthorized",
			"details": ""
		}
	]
}
```

Same for other brand analytics reports like:
`GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT`
`GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT `

On OAuth page, I do get brand analytics permission in the list.
![64703E41-61CF-4AF8-8F1D-C6AFD2CBC47A_1_201_a](https://user-images.githubusercontent.com/50116930/171194785-935e6d37-a9bc-4c5e-8f4c-2d52e110d8ec.jpeg)

**Comment by wolendranh** [comment]
hi! are you sure that `marketplace_id` you are using in request matches vendor marketplace id and that app was given consent from same `marketplace_id`?

**Comment by hongfei** [comment]
> hi! are you sure that `marketplace_id` you are using in request matches vendor marketplace id and that app was given consent from same `marketplace_id`?

Yes, the vendor is US market-based.

**Comment by hongfei-zhou** [comment]
Don't know why, but it looks like the request passed when using the java library. but not when using insomnia.
