### ISSUE TITLE
SP-Api Access to requested resource is denied & you do not meet the requirements for Restricted SP-API

### ISSUE THREAD

**Issue by rumenPenchev** [amzn/selling-partner-api-docs#2329]
Hello,
We have developer account from 6 years.
Now we started developing public SP-API. Following documentation we registered IAM user, role, etc. but on request for orders or listings we are getting:
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
So we send a case to amazon about this problem and they let us to submit developer account and to ask for application registration and we got this:
We have completed our assessment and have determined that you do not meet the requirements for Restricted SP-API. To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon.

 No changes have been made to your SP-API access at this time. 

Can you help?

**Comment by rumenPenchev** [comment]
No we still have this problem. I made new IAM user, role, etc following documentation bit result is the same.

**Comment by misi-ict** [comment]
@rumenPenchev Did you solve this problem? We're having the same issue

Is there anyone who maneged to get PII access? We have filled in the necessary documents and questions in our Developer profile.
But Amazon keep telling us:
We have reviewed the information you provided and determined that you are not eligible for access to the Amazon SP-API you requested

BUT without telling us what do we have to change or improve to get the permission.

**Comment by mikhail-ketov** [comment]
try to call different regions

**Comment by delicatessen** [comment]
@mikhail-ketov you mean check separate different regions while applying?

**Comment by mikhail-ketov** [comment]
@delicatessen nope, i mean during the api call, because access token works only on 1 region(for which was authorized)

**Comment by delicatessen** [comment]
@mikhail-ketov yeah but the question is regarding the Restricted SP-API data
no matter what region in API call, it will not return the client data if there is no authorized access

**Comment by zejrej956** [comment]
@delicatessen were you able to resolve this issue? I am having the same issue too.

**Comment by delicatessen** [comment]
> @delicatessen were you able to resolve this issue? I am having the same issue too.

No, multiple rights request submissions, but still the same rejection response from Amazon
