### ISSUE TITLE
[BUG] fulfillment-inbound-api

### ISSUE THREAD

**Issue by CelestePerez** [amzn/selling-partner-api-docs#2330]
We are currently in the process of integrating the fulfillment-inbound-api of the selling-partner-api into our application and we are running into one case where we can not find a way to use said API to fulfill.

On Seller central, we can plan and create shipments that contain boxes in which we can package multiple different SKUs together, later we can specify dimensions / weight for that box and we can include all the items inside that box.

After reviewing and testing the fulfillment-inbound-api, we can not find a way to implement this.

We can create a Shipment plan (https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#createinboundshipmentplan) which require some information about the products, their SKU, ASIN, and fundamentally Quantity and Quantity In Case but we can not create a package where we group these items.
After we create the Shipment Plan we obtain a list of Shipments to send the products, and when we create an Inbound Shipment (https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#createinboundshipment) we have to match the shipments created in the first step, sending the products to the corresponding fulfillment center.

Is there a way to implement the functionality we are currently using in Seller Central with the fulfillment-inbound-api ?

Thank you in advance,
Best Regards

**Comment by marvinpaul95** [comment]
We have the same issue: the UI offers different shipment combinations for Inbound Shipment Plans than the API. Via the UI, some items can go in the same carton, but with the API they can't (using the same settings).
