### ISSUE TITLE
I am not able to retrieve 'Amazon Fees' of the Transaction View from the Selling Partner API

### ISSUE THREAD

**Issue by maggiep-1** [amzn/selling-partner-api-docs#2331]
I am trying to retrieve data from the Transaction View fields, especially from the ‘Amazon Fees’ field. I have tried to retrieve different report types such as ‘GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA’, ‘GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2’, etc.  but I am not able to retrieve the desired data. Is there any chance that this field is named differently on the API compared to the UI terminology? 
According to a Selling Partner API issue (refer to: https://github.com/amzn/selling-partner-api-docs/issues/741), there is still no answer for this problem. Can you take care of this issue, please?

The Transaction View on UI:
![Screenshot 2022-06-03 160002](https://user-images.githubusercontent.com/106821251/171869194-f1ee00fc-d9e1-4c95-87f4-f861c2550c46.jpg)

**Comment by nina691** [comment]
Has anyone been able to get this type of report? Or know if it is possible to get the same information via the Finances API using the following request:
_**GET /finances/v0/orders/{orderId}/financialEvents**_. The whole finances v0 endpoint is supposed to return the following model https://developer-docs.amazon.com/sp-api/docs/finances-api-v0-model and I see some fees returned there. I am not sure whether it is the same information though.

**Comment by petma** [comment]
GET /finances/v0/orders/{orderId}/financialEvent
sometimes, I can't get  result by this api，why?

**Comment by Muhammad-Abdullah-Developer** [comment]
Hay @maggiep-1  You could easily get transaction details with /finances/v0/financialEvents PATH.

I hope u would have already found the solution. 👍
