### ISSUE TITLE
Brand Analytics Search Query Performance Report

### ISSUE THREAD

**Issue by ykuni-software-developer** [amzn/selling-partner-api-docs#2337]
I have not seen the availability to access Brand Analytics Search Query Performance Report in the documentation. Is this available in the SP-API or not yet?

**Comment by krithic15** [comment]
Hello @ykuni-software-developer, 
Please refer to the list of report types available via SP API in this link. https://developer-docs.amazon.com/sp-api/docs/report-type-values

Best,
Krithi, Solutions Architect, SP API

**Comment by djpecot** [comment]
Yep, I'm also looking for this. To clarify, I think what is being referenced is the data behind the [Search Query Performance Dashboard](https://sellercentral.amazon.com/gp/help/external/8J4CB5ZBF3NX7TP). From checking above documentation, it doesn't seem available at the moment. Are there plans to have it in the API?

**Comment by samborambo305** [comment]
+1

**Comment by djpecot** [comment]
This may be out of scope for this repo. @krithic15 if you could point us to where we can file a feature/endpoint request for the SP-API, that would be awesome!

**Comment by kmander** [comment]
Did you ever find it @djpecot?

**Comment by amistry007** [comment]
@djpecot or @kmander did you guys ever find out info on this?

**Comment by TalhaQuddoos** [comment]
@amistry007 It doesn't seem to be available through the API so far. As a workaround for now, we download the reports manually and then parse it programmatically. Painful but works for the time being.

**Comment by mohammad-unybrands** [comment]
We are looking for the SQR Data as well. Is there are location for feature request.

**Comment by LukasChristoph** [comment]
Same here, would really appreciate the possibility to fill a feature request!

**Comment by kmander** [comment]
We've made a workaround through a custom build Chrome extension that extracts the data during an active session.

**Comment by amistry007** [comment]
@kmander is this something you can share?

**Comment by aludvigsson** [comment]
> @kmander is this something you can share?

hey, I have created a mockup chrome extension for this, you can view source at https://github.com/aludvigsson/sqp-fetcher

**Comment by amistry007** [comment]
@aludvigsson amazing - thanks for this!

**Comment by tarikBerradaHmima** [comment]
+1 for this report to be available through API please
