### ISSUE TITLE
Unexpected response in List Inbound Shipments

### ISSUE THREAD

**Issue by goodiebag45** [amzn/selling-partner-api-docs#234]
When calling /fba/inbound/v0/shipments using a date range, I get an error that seems wrong.

My call is:

`GET  /fba/inbound/v0/shipments?LastUpdatedAfter=2020-10-25T14%3A18%3A49Z&LastUpdatedBefore=2020-12-24T13%3A18%3A49Z&MarketplaceId=ATVPDKIKX0DER&QueryType=DATE_RANGE`

and response is:

```
"code": "InvalidInput",
"message": "At least one of ShipmentStatusList and ShipmentIdList must be provided",
"details": ""
```

Considering I set QueryType=DATE_RANGE, it should use LastUpdatedAfter and LastUpdatedBefore and not ShipmentStatusList or ShipmentIdList.

I wouldn't expect a bug like this, so is it me doing something wrong ?

**Comment by ShivikaK** [comment]
Hello @goodiebag45 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
