### ISSUE TITLE
All Shipping API give 500 - InternalFailure

### ISSUE THREAD

**Issue by mircoisendu** [amzn/selling-partner-api-docs#2343]
Hello,

I'm trying to implement for European marketplaces the integration with Amazon Shipping API.

**_Anyone have had success with /shipping API ??_** 

I've implemented the OAuth authorization flow from front-end to backend and it seem to work properly, it's retrieving the access and refresh token, than it call STS assumeRole and retrieve all the Credentials needed to call SP-API.

Then I tried:
1) shipping.getAccount (GET /shipping/v1/account), 
   but it gives an **empty payload** as result, instead of {accountId: "something"}

2) shipping.createShipment (POST /shipping/v1/shipments),
but it give 
```
{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}
```

3) shipping.getRates (POST /shipping/v1/rates), it give the same **internalFailure** as above

Do we need some special permission ? 

We have everything enabled:
![Screenshot 2022-06-10 at 13 08 27](https://user-images.githubusercontent.com/107251776/173052550-80e5c847-f812-4d15-8fa6-911bfdbe8b12.png)

 Do you know if for Shipping API we need to use Restricted Data Token (RDT)  ?

Thank you to everyone helping :)

**Comment by ProNotion** [comment]
I see the same issue, I am just trying to get a shipment and the request consistently returns an internal failure with the message "We encountered an internal error. Please try again.". Did you find a solution to this or is there an issue with the API?

**Comment by ProNotion** [comment]
This is still not working and I am at a loss as to how to resolve it. Has anyone had any sort of success with this?

**Comment by aaalekseev** [comment]
+1

**Comment by SteveHoTW** [comment]
My team is facing the same issue.
Anyone has solutions?

**Comment by zfh970745204** [comment]
+1

**Comment by zfh970745204** [comment]
I encountered the same problem, did you solve it?

**Comment by zfh970745204** [comment]
@ProNotion @mircoisendu @SteveHoTW @aaalekseev I encountered the same problem, did you solve it?

**Comment by NA-Dev** [comment]
I am also having an issue where I get the Internal error response. For me it happens after a certain number of pages when fetching all our shipments in a loop using nextToken. Amazon API support tickets don't help because they just piddle around for weeks only to come back and say nothing is wrong. Then they ask me for a new request ID to get them to look into it again. Very infuriating.

**Comment by ProNotion** [comment]
> I encountered the same problem, did you solve it?

I don't have the issue any longer but can't exactly remember how I resolved it. However, the @NA-Dev comment makes me seem to think it was because I was making requests outside the available ranges. E.g. requesting a page of results that was greater than the number of pages available, or an invalid date range (perhaps a date greater than `now`).

**Comment by Ziyun-KyLin** [comment]
{
    "ship_to": {
        "name": "Yara swain",
        "addressLine1": "6597 w. Desert blossom way",
        "addressLine2": "",
        "addressLine3": "",
        "companyName": "Harvard",
        "stateOrRegion": "AZ",
        "city": "Florence",
        "countryCode": "US",
        "postalCode": "85132",
        "email": "8p0fmm56lf3vd7j@marketplace.amazon.com",
        "phoneNumber": "1-202-8631292"
    },
    "ship_from": {
        "name": "Kameron Frederick",
        "addressLine1": "11918 Kirkholm Drive",
        "addressLine2": "",
        "addressLine3": "",
        "companyName": "test gs",
        "stateOrRegion": "Texas",
        "city": "Houston",
        "countryCode": "US",
        "postalCode": "77089",
        "email": "zmg2ps6nbsbht6b@marketplace.amazon.com",
        "phoneNumber": "5869098233"
    },
    "return_to": {
        "name": "xin ming",
        "addressLine1": "CHARLOTTE, NC 95336-8555, USA",
        "addressLine2": "",
        "addressLine3": "",
        "companyName": "test gs",
        "stateOrRegion": "NC",
        "city": "CHARLOTTE",
        "countryCode": "US",
        "postalCode": "28210",
        "email": "zmg2ps6nbsbht6b@marketplace.amazon.com",
        "phoneNumber": "5869098233"
    },
    "ship_date": "2023-09-01T03:40:38Z",
    "packages": [
        {
            "dimensions": {
                "length": 20.01,
                "width": 10.01,
                "height": 50.01,
                "unit": "CENTIMETER"
            },
            "weight": {
                "unit": "KILOGRAM",
                "value": 1.2
            },
            "insuredValue": {
                "value": 10,
                "unit": "USD"
            },
            "sellerDisplayName": "",
            "packageClientReferenceId": "sku1001",
            "items": [
                {
                    "itemValue": {
                        "value": 10,
                        "unit": "USD"
                    },
                    "description": "this is my Description",
                    "quantity": 1,
                    "weight": {
                        "unit": "KILOGRAM",
                        "value": 1.2
                    },
                    "isHazmat": false
                }
            ]
        }
    ],
    "channel_details": {
        "channelType": "EXTERNAL"
    }
}请求
ShippingV2Api->getRates: [
    500
] {
    "errors": [
        {
            "code": "InternalFailure",
            "message": "We encountered an internal error. Please try again.",
            "details": ""
        }
    ]
}

**Comment by saioaortiz13** [comment]
Did u solve this problem? I got it trying to get the GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
