### ISSUE TITLE
Reports - "One or more required parameters missing"

### ISSUE THREAD

**Issue by Jethro-Wilkinson** [amzn/selling-partner-api-docs#235]
Hi, I'm trying to create a report but I am receiving the following error:

"InvalidInput - One or more required parameters missing"

I've had a look through the documentation and I cannot for the life of me see what parameter(s) I'm missing. Here's my request:

```
$response = $this->send(
    "GET",
    "/reports/2020-09-04/reports",
    [
        "marketplaceIds" => implode(",", $marketplaceIds),
        "dataStartTime" => "2020-12-01T00:00:00.000Z",
        "dataEndTime" => "2020-12-24T23:59:59.999Z",
        "reportType" => "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL"
    ],
    ["x-amz-access-token" => $this->accessToken]
);
```

If anyone has any ideas I'd really appreciate it. Maybe I'm just being blind but I've read through the docs what feels like a hundred times and I'm sure I've included everything that's required.

**Comment by nodisk8800** [comment]
You need to encode the ParamsValue to request.

url+encode(name1)=encode(value1)&encode(name2)=encode(value2)

I call this API is successfull.

**Comment by sherlock270** [comment]
If you're trying to create a report it should be a POST request

**Comment by Jethro-Wilkinson** [comment]
You're totally right it should be POST. I can't believe I missed that. I'm still getting the same error but I'll keep trying and if I manage to solve I'll post my solution and close this.

Thanks

**Comment by sherlock270** [comment]
One thing that tripped me up trying to create a report was making sure I had the content-type header set to application/json.

**Comment by Drageir** [comment]
Maybe this is already solved, but this worked for me by making the marketplaceIds a list of values. Example: marketplaceIds = [MMMMMM,XXXXXXX,AAAAAA]

**Comment by abuzuhri** [comment]
> Hi, I'm trying to create a report but I am receiving the following error:
> 
> "InvalidInput - One or more required parameters missing"
> 
> I've had a look through the documentation and I cannot for the life of me see what parameter(s) I'm missing. Here's my request:
> 
> ```
> $response = $this->send(
>     "GET",
>     "/reports/2020-09-04/reports",
>     [
>         "marketplaceIds" => implode(",", $marketplaceIds),
>         "dataStartTime" => "2020-12-01T00:00:00.000Z",
>         "dataEndTime" => "2020-12-24T23:59:59.999Z",
>         "reportType" => "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL"
>     ],
>     ["x-amz-access-token" => $this->accessToken]
> );
> ```
> 
> If anyone has any ideas I'd really appreciate it. Maybe I'm just being blind but I've read through the docs what feels like a hundred times and I'm sure I've included everything that's required.

Do you solve the problem I have the same error

**Comment by tontonnono** [comment]
solved on my end by setting marketplaceIds as a true array, not a coma separated list 

`"marketplaceIds" => ['ATVPDKIKX0DER'],`
