### ISSUE TITLE
Missing sp-api role Brand Analytics

### ISSUE THREAD

**Issue by vicky-3001** [amzn/selling-partner-api-docs#2351]
Hi,

I am not able to see the Brand Analytics selling partner role under my app in developer console. I am able to see the other roles

Reference : https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api

Can someone help me please?

**Comment by DavidMendes91** [comment]
![image](https://user-images.githubusercontent.com/302133/173773145-90411019-2ad2-41b9-8005-15c70658e33e.png)
Brand Analytics role is a developer level role, 
not an application level role.

Its is added to your developer profile, not your app profile.

In developer central, go to your developer profile and add it. You won't be able to create new apps until the review process is complete

**Comment by vicky-3001** [comment]
Got it, thanks

**Comment by RMagician** [comment]
Just got the role, now the app-level role is available

**Comment by AJ-AUS** [comment]
Great, thank you - found it!
