### ISSUE TITLE
searchCatalogItems 2022-04-01 - Invalid \\u0027asin\\u0027 provided.

### ISSUE THREAD

**Issue by AndreyBaryshev** [amzn/selling-partner-api-docs#2356]
I faced with the issue for searchCatalogItems.
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#get-catalog2022-04-01items

Yesterday `[16 06 2022 11:58:24 UTC]` I did this request and got success response with data.
`GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?sellerId=XXXXXXX&identifiers=XXXXXXX%2CYYYYYYY%2CZZZZZZZ&marketplaceIds=ATVPDKIKX0DER&identifiersType=ASIN&pageSize=20&includedData=attributes%2Cdimensions%2Cidentifiers%2Cimages%2CproductTypes%2Crelationships%2CsalesRanks%2Csummaries
`

Today `[17 06 2022 06:06:22 UTC]` I tried to make the same request but I got this error:
`'{\n  "errors": [\n    {\n      "code": "InvalidInput",\n      "message": "Invalid \\u0027asin\\u0027 provided.",\n      "details": ""\n    }\n  ]\n}'`

Also, request with **JUST ONE** identifier works ok, but if I try to pass more than one it returns error above.

**Comment by AndreyBaryshev** [comment]
Look's like between [16 06 2022 11:58:24 UTC] and [17 06 2022 06:06:22 UTC] this endpoint has been updated.

Hello @chapmanjw, I saw you [comment](https://github.com/amzn/selling-partner-api-docs/issues/2295#issuecomment-1157924238) and I think It's can be tied.

Thank you!

**Comment by feapaydin** [comment]
Having exactly the same issue.

Failing query parameters:
```json
{
  "marketplaceIds": "MMMMMMMMMMMMMM",
  "identifiers": "XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX",
  "identifiersType": "ASIN",
  "includedData": "attributes,identifiers,images,productTypes,salesRanks,summaries,relationships",
  "pageSize": 20
}
```

Working when:
```json
{
  "marketplaceIds": "MMMMMMMMMMMMMM",
  "identifiers": "XXXXXXXXXXX",
  "identifiersType": "ASIN",
  "includedData": "attributes,identifiers,images,productTypes,salesRanks,summaries,relationships",
  "pageSize": 20
}
```

**Comment by jamesp26** [comment]
We just refactored all our tools to use the new search endpoint. I can confirm we are getting the **_u0027 provided_** error.

Any news on a resolution as nothing is currently working for us.

**Comment by chapmanjw** [comment]
@AndreyBaryshev Thanks for reporting. We already have code queued up for deployment that will fix this. Will update this once that goes out. Thanks.

**Comment by chapmanjw** [comment]
@AndreyBaryshev The fix for this issue has been deployed to all regions. Have a great weekend!

**Comment by Nilanth** [comment]
@chapmanjw 
Still getting this error
```
 "code": "InvalidInput",
      "message": "Invalid \u0027identifiers\u0027 value provided.",
      "details": ""
```

**Comment by chapmanjw** [comment]
> @chapmanjw Still getting this error
> 
> ```
>  "code": "InvalidInput",
>       "message": "Invalid \u0027identifiers\u0027 value provided.",
>       "details": ""
> ```

Do you have a Request ID and timestamp for the failed request(s)?

**Comment by nejimz** [comment]
Hello,

I have the same problem like this but the identifiers type is SKU.
Can you help me on this?

Endpoint: /catalog/2022-04-01/items
Operation: searchCatalogItems
Run Datetime: 2023-10-05 00:12:17

Params:
[
 "marketplaceIds" => "XXXXXXXX"
  "identifiers" => "sku_1"
  "identifiersType" => "SKU"
  "includedData" => "identifiers,attributes,images,productTypes,salesRanks,summaries"
  "sellerId" => "xxxxx"
  "pageSize" => 20
]

Errors:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}

**Comment by nejimz** [comment]
Hello,

I have the same problem like this but the identifiers type is SKU.
Can you help me on this?

Endpoint: /catalog/2022-04-01/items
Operation: searchCatalogItems

Request ID: 1b5f4ed8-1896-43ea-b193-109e0b45694f
Run Datetime: 2023-10-05 00:12:17

Params:
```
[
 "marketplaceIds" => "XXXXXXXX"
  "identifiers" => "sku_1"
  "identifiersType" => "SKU"
  "includedData" => "identifiers,attributes,images,productTypes,salesRanks,summaries"
  "sellerId" => "xxxxx"
  "pageSize" => 20
]
```

Errors:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```
