### ISSUE TITLE
Seller business report issue

### ISSUE THREAD

**Issue by discover59** [amzn/selling-partner-api-docs#2357]
When I get report data using GET_SALES_AND_TRAFFIC_REPORT report, the aggregation values are different.

For example, `unitsOrdered` in `salesAndTrafficByDate` is 2800 and sum of `unitsOrdered` in `salesAndTrafficByAsin` is 2810.
This happened when I used below report options.
```
reportOptions={
    "dateGranularity": "DAY",
    "asinGranularity": "SKU",
},
dataStartTime="2021-02-21T00:00:00Z",
dataEndTime="2021-02-21T00:00:00Z",
```

Why are the values different?

**Comment by adrian-amz** [comment]
Hello @discover59 ,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian C.
Selling Partner API Developer Support

**Comment by discover59** [comment]
@adrian-amz I did create a ticket already, but still didn't get clear answer.
Is it development issue or support issue?

**Comment by ayushchd** [comment]
@adrian-amz Support doesn't work at all. Have opened cases, but there is no investigation done whatsoever.

**Comment by chikichunchik** [comment]
@discover59 Do you have any solution?
