### ISSUE TITLE
[BUG] "shipping_time" of offers on ProductPricingApi are incorrect

### ISSUE THREAD

**Issue by Rin-Oka** [amzn/selling-partner-api-docs#2358]
Now, I can get offers information about my listingItem by ProductPricingApi/getItemOffers.
The result contains "shippint_time" of offers, especially "maxmum_hours" and "minimun_hours".
However, the two data are different from data displayed on amazon Product page.
I want to get the latter, "shipping_time" display on amazon Product page.
Is it a bug? or can I get the information by other api?

**Comment by adrian-amz** [comment]
Hello @Rin-Oka,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C.
Selling Partner API Developer Support
