### ISSUE TITLE
operation createFeed return  Invalid request parameters

### ISSUE THREAD

**Issue by wangjue666** [amzn/selling-partner-api-docs#236]
request 

```
 let res = await FeedsModel.createFeeds({
            feedType: 'POST_PRODUCT_DATA',
            inputFeedDocumentId: genGoodXml(selling_partner_id),
            marketplaceIds: [MarketplaceId]
  })
//url is  POST 'https://sellingpartnerapi-na.amazon.com/feeds/2020-09-04/feeds'

```
response

```
{
  errors: [
    {
      code: 'InvalidInput',
      message: 'Invalid request parameters',
      details: ''
    }
  ]
}
```
Did I do something wrong ？

**Comment by wangjue666** [comment]
All requests from the order module are responding normally， but createFeed  can make this kind of mistake，It would be better if there was a createFeed request for an example

**Comment by nodisk8800** [comment]
Did you call  createFeedDocument successfull and then upload xml document successfull?

**Comment by nodisk8800** [comment]
1,要先调用  createFeedDocument  API,  参数contentType="text/xml; charset=UTF-8" (根据实际业务使用相应的类型)
取到 url,key,initializationVector,feedDocumentId ,这一步没有什么难点.

2,然后使用 key,initializationVector 加密你要上传的文件,使用 http put的方式上传到 url.

3,确认上传成功之后,调用 createFeed API,调用成功会返回 {"payload":{"feedId":"xxxxxxx"}}.

如果文件上传不成功,或者前后使用的contentType不一样,那 createFeed 的调用就会失败.

**Comment by wangjue666** [comment]
@nodisk8800  I don't even know how to fill in the contentType of createFeedDocument ！   
![1608878029(1)](https://user-images.githubusercontent.com/24707417/103123152-488f1800-46be-11eb-966d-57da00bd3af1.png)

**Comment by wangjue666** [comment]
@nodisk8800  ok  I'll have a try Thank you bro！

**Comment by nodisk8800** [comment]
看得懂中文吧?
搞英文真是累.

**Comment by wangjue666** [comment]
@nodisk8800  好滴 老铁 上传文件是 FeedDocumentEncryptionDetails 这个接口吗

**Comment by newpepsi** [comment]
> 看得懂中文吧?
> 搞英文真是累.

feed 的 xml 格式是怎么样的？

**Comment by wangjue666** [comment]
@nodisk8800  解决了老铁！

**Comment by nodisk8800** [comment]
恭喜恭喜!又走出一个坑!!

**Comment by nodisk8800** [comment]
要不要加我们的QQ技术群啊?
273745406

**Comment by nodisk8800** [comment]
> 
> 
> > 看得懂中文吧?
> > 搞英文真是累.
> 
> feed 的 xml 格式是怎么样的？

根据业务的不同,xml的格式各不相同.具体看相应的文档和 xsd 文件.

**Comment by wangjue666** [comment]
@nodisk8800  加组织了 给通过下吧

**Comment by LINJINTIANDE** [comment]
这个是什么问题 我也遇到正在解决，有些账号到这一步就报这个错误。但很多账号都不会报这个错误，都是正常的

**Comment by LINJINTIANDE** [comment]
@nodisk8800 这个是什么问题 我也遇到正在解决，有些账号到这一步就报这个错误。但很多账号都不会报这个错误，都是正常的

**Comment by LINJINTIANDE** [comment]
@wangjue666 @nodisk8800  这个是什么问题 我也遇到正在解决，有些账号到这一步就报这个错误。但很多账号都不会报这个错误，都是正常的

**Comment by wangjue666** [comment]
@LINJINTIANDE  确定文件PUT上传成功了吗？

**Comment by LINJINTIANDE** [comment]
> @LINJINTIANDE 确定文件PUT上传成功了吗？

put是成功的 返回 200，大部分账号能上传产品的，只是个别账号到createFeed就报错误的 ，Invalid request parameters ，我也搞不懂原因

**Comment by nibaijing** [comment]
我也也遇到这个问题，按上面的方法试了，没有效果。怎么回事？

> @nodisk8800 解决了老铁！

你是怎么解决的?

**Comment by nodisk8800** [comment]
到群里问吧

**Comment by lycnihao** [comment]
> 要不要加我们的QQ技术群啊?
> 273745406

我申请了

> 到群里问吧

我也遇到这个问题了按照上面的操作还是没有解决，申请加群了可以同意下吗

**Comment by yao657355700** [comment]
> @nodisk8800 解决了老铁！

老铁，你是怎么解决的？
我这一步 createFeedDocument 一直报错 
 [body] => {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}

**Comment by paly76** [comment]
> > @LINJINTIANDE 确定文件PUT上传成功了吗？
> 
> put是成功的 返回 200，大部分账号能上传产品的，只是个别账号到createFeed就报错误的 ，Invalid request parameters ，我也搞不懂原因

老哥，我的也是这个问题，你的解决了吗？？？

**Comment by AisxLee** [comment]
> 要不要加我们的QQ技术群啊? 273745406

@nodisk8800 申请了，一直没审核，麻烦给通过下吧
