### ISSUE TITLE
How to properly get Variations data from SearchCatalogItems 2022-04-01

### ISSUE THREAD

**Issue by AndreyBaryshev** [amzn/selling-partner-api-docs#2361]
I try to get data about variation types and values from SearchCatalogItems endpoint.

I see `variationTheme` with `["item_package_quantity", "size"]` but it's not matched with field names in `summaries`.

How to properly get product variation types and values?

![image](https://user-images.githubusercontent.com/75067606/174523539-c3da82c8-ac66-46de-ab60-945679c4f23f.png)

**Comment by chapmanjw** [comment]
@AndreyBaryshev Use the `attributes` data by specifying that in the `includedData`. The `summaries` section contains high-level details common to most types of items in the catalog. The `attributes` data provides all of the "raw" reconciled attributes for an item. Variation themes vary by product type, marketplace, etc. and the modeled `summaries` section does not attempt to include every possible variation theme attribute.
