### ISSUE TITLE
[BUG] getListingsItem with multiple marketplaceIds but only return one item

### ISSUE THREAD

**Issue by littleylv** [amzn/selling-partner-api-docs#2362]
**Describe the bug**
I have an amazon account selling in EU marketplaces.
When I call the `getListingsItem` api: https://sellingpartnerapi-eu.amazon.com/listings/2021-08-01/items/{MySellerId}/{MySku}?includedData=summaries&issueLocale=en_US&marketplaceIds=A1RKKUPIHCS9HS%2CA13V1IB3VIYZZH (attention to the sort: A1RKKUPIHCS9HS and A13V1IB3VIYZZH), it only return A1RKKUPIHCS9HS item:

```
{
    "sku":"{MySku}",
    "summaries":[
        {
            "marketplaceId":"A1RKKUPIHCS9HS",
            "asin":"{MyASIN}",
            ........{other atrributes}......
        }
    ]
}
```

When I call the `getListingsItem` api: https://sellingpartnerapi-eu.amazon.com/listings/2021-08-01/items/{MySellerId}/{MySku}?includedData=summaries&issueLocale=en_US&marketplaceIds=A13V1IB3VIYZZH%2CA1RKKUPIHCS9HS (attention to the sort: A13V1IB3VIYZZH and A1RKKUPIHCS9HS), it only return A13V1IB3VIYZZH item:

```
{
    "sku":"{MySku}",
    "summaries":[
        {
            "marketplaceId":"A13V1IB3VIYZZH",
            "asin":"{MyASIN}",
            ........{other atrributes}......
        }
    ]
}
```

**URL of the content on GitHub**
[[Please provide the GitHub URL for the documentation where you see the bug.](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#getlistingsitem)](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#getlistingsitem)

**Description of what the documentation currently says**

Query | marketplaceIds | required | A comma-delimited list of Amazon marketplace identifiers for the request. | < string > array(csv)
-- | -- | -- | --

@[chapmanjw](https://github.com/chapmanjw) Please take a look at this issue. Thanks.

**Comment by chapmanjw** [comment]
@littleylv We built the API models for the Listings Items APIs to support multiple marketplaces in the API contract, but we currently limit these to lists of one. The purpose is to enable us to launch multi-marketplace and global listings features incrementally without requiring API version bumps as we expand the capabilities of the APIs.

There is, however, a missing validation here. You should be receiving an error indicating that too many marketplace identifiers were provided (as you would see in other Listings Item API operations). We have a fix going out to address this. Thanks for reporting this issue.

I will close this Github issue once that deploys to production. And stay tuned to future release announcements for multi-marketplace and global listings features coming in the future.

**Comment by xEverth** [comment]
Are there any updates on multi-marketplace support for Listings, Catalogs and Feeds? Does updating the price of 1 product across multiple marketplaces require multiple calls, even if in the same region?
