### ISSUE TITLE
Private App

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#2371]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2366

<div type='discussions-op-text'>

<sup>Originally posted by **vikingcodes** June 21, 2022</sup>
@chapmanjw @ShivikaK 

We run Amazon Training & Launch Program.

We need download some report from customer's account like inventory and order reports on daily basis and integrate into our database.

But we don't want launch our app on app store for public because our app designed for some specific seller who onboard on our platform.

We have any option to create private app ? Or any other options ?

</div>

**Comment by WWangYu** [comment]
URL: https://developer-docs.amazon.com/sp-api/changelog/application-authorization-limits-and-listing-restrictions

It must be a public program, otherwise there will be a limit on the number of authorizations

**Comment by sungolivia** [comment]
Like @WWangYu mentioned there is an option to create private app but it's only for use within your company or organization. If it's not too late, definitely check out public vs private devs:
https://developer-docs.amazon.com/sp-api/docs/registering-as-a-developer


Definitely also keep in mind of the number of auth limits as well:
https://developer-docs.amazon.com/sp-api/docs/application-authorization-limits
