### ISSUE TITLE
How can I update our listing price by ListingsAPi

### ISSUE THREAD

**Issue by Rin-Oka** [amzn/selling-partner-api-docs#2373]
I want to update our listing price by ListingsApi.
I used the function ListingsApi/patchListingsItem. 

Following is the data for patch.
`[
op:"replace",
path:"/attributes/purchasable_offer",
value:[
            'marketplace_id'=>MARKETPLACE_ID,
            'currency'=>'JPY',
            'our_price'=>[
                'schedule'=>[
                    'value_with_tax'=> price
                ]
            ]
        ]
]    `

However, error result returned.
`[code] => 4000001
                                    [message] => The provided value for 'purchasable_offer' is invalid.
                                    [severity] => ERROR
                                    [attribute_names] => Array
                                        (
                                            [0] => purchasable_offer
                                        )`

How should I set parameters?

**Comment by Adrian-T-AMZN** [comment]
Hello @[Rin-Oka](https://github.com/Rin-Oka),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by chapmanjw** [comment]
The Product Type Definitions API provides JSON Schemas describing the proper formatting and requirements for attributes, you can use these to understand how to put together an individual attribute and then use the patch api: https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide

**Comment by sweetdream34310** [comment]
Hello Community, I am new here.
I am developing the amazon pricing management software and using the sp api.
I want to update the regular price (Estimated fee per unit sold) with sku, not business price

I wrote like this and it is working correctly for the UK , but not working for EU( DE, FR, IT, ES, NL, SE, PL ... )

let sellingPartner = new SellingPartnerAPI({
credentials: {
SELLING_PARTNER_APP_CLIENT_ID: SELLING_PARTNER_APP_CLIENT_ID,
SELLING_PARTNER_APP_CLIENT_SECRET: SELLING_PARTNER_APP_CLIENT_SECRET,
AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID,
AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY,
},
region: 'eu',
refresh_token: REFRESH_TOKEN
});

. . .

let resData = await sellingPartner.callAPI({
operation: 'patchListingsItem',
endpoint: 'listingsItems',
path: {
sellerId: process.env.SELLER_ID,
sku: sku
},
query: {
marketplaceIds: marketplaceId,
},
body: {
productType: "PRODUCT",
patches: [
{
op: "replace",
path: "/attributes/purchasable_offer",
value:
[
{
currency: "GBP",
marketplace_id: marketplaceId,
our_price: [
{
schedule: [
{
value_with_tax: parseFloat(price)
}
]
}
]
}
]
}
]
},
options: {
version: '2021-08-01'
}
});

I am not sure why it is working for the UK but not working for others.
Please help me.
Thank you.
