### ISSUE TITLE
[BUG] ANY_OFFER_CHANGED notification not always deliver the correct price info?

### ISSUE THREAD

**Issue by CLK240** [amzn/selling-partner-api-docs#2376]
found the bug, for SP-API, we will get multiple marketplaces notifications.

**Comment by LindaNC** [comment]
Hello @CLK240,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support
