### ISSUE TITLE
[BUG] searchCatalogItems does not return the search identifiers or keywords in the result

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-docs#2378]
**API**:
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#searchcatalogitems

ISSUE: the **keywords** and **identifiers** now allows maximum 20 values. We cannot know if the result X belongs to searching keyword A,... 

For example, let say we search keywords="hary, boss". We will have about 279 results, how do we know if ASIN ABC belongs to the search keyword 'hary' or 'boss'?

MWS API has this behavior: they are in "ID" and IDType in GetMatchingProductForIdResult 
https://docs.developer.amazonservices.com/en_US/products/Products_GetMatchingProductForId.html
 `<GetMatchingProductForIdResult Id="9781933988665" IdType="ISBN" status="Success">`

**Comment by txphi592** [comment]
Facing this issue as well @chapmanjw

**Comment by LindaNC** [comment]
Hello @hamduc7,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support

**Comment by chapmanjw** [comment]
For identifier-based searches, requesting the `identifiers` in the `includedData` parameters will allow you to map the ASINs found back to their related identifiers. For these, each identifier is treated as a separate lookup.

For keyword-based searches, however, the results are based on matching some or all of the keywords (it performing a single lookup in the search indexes with all of the keywords provided).

**Comment by hamduc7** [comment]
@chapmanjw Thank you
Identifier-based search: I currently use that workaround. But there is an issue.  Let's say you search these 2 UPCs: 028444196790,082676217845
You will see that the UPC 082676217845 is in both results.

**Comment by chapmanjw** [comment]
@hamduc7 If you search for just `082676217845`, you can see that there are (currently) 3 different ASINs associated with that UPC. When extracting results for `028444196790` and `082676217845`, you will have overlapping sets in this scenario.

**Comment by hamduc7** [comment]
@chapmanjw In my case, I must use a batch of 20 IDs to search. That is why I found that issue.

**Comment by chapmanjw** [comment]
@hamduc7 The response data here is accurate. A product identifier can map to more than one ASIN (i.e., multiple sizes or colors of the same item may share a UPC identifier, but be represented by different ASINs). There is no mechanism by which we can provide you a 1-to-1 mapping of identifier to ASIN as that is not how the Amazon catalog works. 

When handling the results and mapping the resulting ASINs back to the input identifiers, some ASINs will be mapped to multiple inputs and some inputs will be mapped to multiple ASINs. The best way to handle this would be to extract a map of input identifier to the list of ASINs containing that identifier (which may result in the same ASIN being in multiple mappings).

**Comment by chapmanjw** [comment]
@hamduc7 The net result is the same, in MWS the responses would have the ASINs duplicated whereas the SP-APIs provide each unique ASIN once.

To illustrate, lets say we have 3 UPCs that exist on 3 different ASINs. When querying those 3 UPCs in one batch request to the MWS API, you would have received a response containing the same ASINs 3 times:

MWS Input (Batch): 

- Request 1 - UPC1, Request 2 - UPC2, Request 3 - UPC3

MWS Output (Batch):

- Response 1 - UPC1
  - ASIN1 + Attributes
  - ASIN2 + Attributes
  - ASIN3 + Attributes
- Response 2 - UPC2
  - ASIN1 + Attributes
  - ASIN2 + Attributes
  - ASIN3 + Attributes
- Response 3 - UPC3
  - ASIN1 + Attributes
  - ASIN2 + Attributes
  - ASIN3 + Attributes
  
The SP `searchCatalogItems` API operation is not a "batch operation". It does not take a list of separate requests and provide a list of separate responses. It's a query operation that allows you to query the Amazon catalog by one or more identifiers (in this case), with the results containing the unique ASINs found for the query. 

In this scenario, the net results, however, are the same: you still get back the same ASINs along with the ability to correlate them back to the applicable identifiers.

SP Input (Single Query):

- UPC1,UPC2,UPC3

SP Output:

- ASIN1 + Attributes
  - UPC1
  - UPC2
  - UPC3
- ASIN2 + Attributes
  - UPC1
  - UPC2
  - UPC3
- ASIN3 + Attributes
  - UPC1
  - UPC2
  - UPC3
  
There is nothing preventing a client application from taking the response above and pivoting it to match the previous MWS behavior (i.e., duplicating the ASIN data):

- UPC1
  - ASIN1 + Attributes
  - ASIN2 + Attributes
  - ASIN3 + Attributes
- UPC2
  - ASIN1 + Attributes
  - ASIN2 + Attributes
  - ASIN3 + Attributes
- UPC3
  - ASIN1 + Attributes
  - ASIN2 + Attributes
  - ASIN3 + Attributes

**Comment by hamduc7** [comment]
Hi @chapmanjw, thank you for your explanation. I really appreciate

**Comment by gokigoks** [comment]
@chapmanjw  This is also an issue when searching ISBN  in 13-digit format, and the identifiers property in a result returning ISBN-10 or no ISBN at all. Please reconsider adding a search identifier property to the results for the batch request.

**Comment by gokigoks** [comment]
Hi @hamduc7 were you able to come up with a workaround for this issue?

**Comment by hamduc7** [comment]
Hi @gokigoks 
Yes we must map back the "Identifiers" in the results with the input

This is my pseudo code:

For each ID in the Inputs
begin
   For each result in the Results
      Check if result.ASIN/UPC.... is equal to the ID ->Yes, putout [ID, result]
end

So you see one ID may have 1 or many results

**Comment by DarkwaveMD** [comment]
As an example to issue mentioned above - UPC 000050097425 - in results I get only EAN's and GTIN  in the list of  the identifiers so it's impossible to map it back to 000050097425.

**Comment by gokigoks** [comment]
@DarkwaveMD Same issue but with ISBN. I can offer nothing but sympathies at this point as were already 1 week from end-of-life. But if by some miracle you find a reliable workaround, would appreciate it if you can share. Thank you.
