### ISSUE TITLE
Normal authorization, when requesting data, the following error is reported, I don't know why

### ISSUE THREAD

**Issue by WGY117385** [amzn/selling-partner-api-docs#2379]
{"error_description":"The request has an invalid grant parameter : refresh_token. User may have revoked or didn't grant the permission.","error":"invalid_grant"

**Comment by LindaNC** [comment]
Hello @WGY117385,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support
