### ISSUE TITLE
confusion on authorization with different marketplaces and same region

### ISSUE THREAD

**Issue by wanghao0123** [amzn/selling-partner-api-docs#2384]
hi, there,
    I'm confusing about authorization, for example, one shop in same AWS region but have many marketplaces in sales, should I authorize the shop once by the AWS region or many times by marketplaces ? such as US and CA，both in North America
    thanks

**Comment by jimmy-ross-xapix** [comment]
> Once.

unless you are authorizing multiple Far East country, where they have to be authorized individually...

**Comment by littleylv** [comment]
@jimmy-ross-xapix You are right.
For NA and EU: once
For Far East(Singapore/Australia/Japan): authorize every marketplace

**Comment by wanghao0123** [comment]
@littleylv @jimmy-ross-xapix  
really appreciate， thanks
