### ISSUE TITLE
[FEATURE] GetListingOffers Response needs to return Minimum Order Quantity

### ISSUE THREAD

**Issue by Domino-the-cat** [amzn/selling-partner-api-docs#2391]
Hi

It would be extremely useful if the call  GET /products/pricing/v0/listings/{SellerSKU}/offers  returned a response that included the "minimum order quantity"   [MOQ] for each of the offers in the response.

Users need this MOQ to be able to using pricing data well.

Thanks

Dom

**Comment by LindaNC** [comment]
Hello @Domino-the-cat,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details may be required from your end.

Thanks,
Linda
Selling Partner API Developer Support

**Comment by Domino-the-cat** [comment]
Thanks Linda, case opened on id 7846600632
