### ISSUE TITLE
Feature Request: Access Backend Search Terms for Products

### ISSUE THREAD

**Issue by samborambo305** [amzn/selling-partner-api-docs#2396]
- The documentation suggests that the backend search terms field is not programmatically accessible via the API

Preferred solution:
- Make the backend search terms field available on the item object for CRUD operations

**Comment by chapmanjw** [comment]
@samborambo305 What do you mean by "backend search terms"? What are you specifically looking for?

**Comment by samborambo305** [comment]
When using Seller Central to create or update products in the catalog there is a field called "search terms"
![Screen Shot 2022-07-19 at 6 19 47 PM](https://user-images.githubusercontent.com/73838754/179858232-3ef93552-0b38-4066-9d42-f8a749b24434.png)

**Comment by chapmanjw** [comment]
@samborambo305 That attribute is `generic_keyword` (`Search Terms` is the display label for it). When calling the Catalog Items API `getCatalogItem` or `searchCatalogItems` operations, you can request the `attributes` `includedData`. If the ASIN has this attribute present, it will be included in the `attributes` data.

**Comment by samborambo305** [comment]
Interesting, can this attribute also be updated?

**Comment by chapmanjw** [comment]
Yes. The Listings Items APIs accept this attribute as part of a listing. Listings for the same ASIN are reconciled to produce what you see on the Amazon.com detail pages and in the Catalog Items APIs.

At this time, not all product types are supported by theses APIs. You can use the Product Type Definitions APIs to see which product types are currently supported and retrieve the schemas for each product type (defining the attributes, requirements, etc.). 

- Listings Items APIs: https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide
- Product Type Definitions APIs: https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide

**Comment by samborambo305** [comment]
Interesting, thank you for the help
