### ISSUE TITLE
What is the SP-API equivalent to GET_ORDERS_DATA?

### ISSUE THREAD

**Issue by ShaneOH** [amzn/selling-partner-api-docs#2397]
Hi, 

In the [MWS Reports API](https://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html#ReportTypeCategories__OrderReports) there are reports such as `_GET_ORDERS_DATA_` and `_GET_FLAT_FILE_ORDERS_DATA_`. However these seem to no longer be there in the [SP-API Report Types](https://developer-docs.amazon.com/sp-api/docs/report-type-values#order-reports). 

What is the equivalent to migrate?

**Comment by stefnats** [comment]
There is a similar issue #2135 and those report types are addressed in this depreciation notice:
https://github.com/amzn/selling-partner-api-docs/discussions/1037

**Comment by ShaneOH** [comment]
Hey @stefnats -- thanks for the response!

On the issue https://github.com/amzn/selling-partner-api-docs/discussions/2135 there is no clear answer. I see @lashaLobjanidzeXentral mention there's an "aggregation" of 3 report types -- I can't tell if there's an actual aggregation functionality (which I don't see mention of in [the docs](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#report)), or if he just means informally combining the results of the 3, and furthermore that commentator was having a hard time getting the reports working and could not confirm it was the replacement, it looks like. 

I did indeed also check in https://github.com/amzn/selling-partner-api-docs/discussions/1037 before posting this, and it does seem to imply that `_GET_ORDERS_DATA_` has a correlation simply by virtue of it not being listed in that section below, but I can't find any docs describing a one-to-one or similar mapping from MWS Report Types to SP-API Report Types, which is frustrating.

**Comment by sat-it** [comment]
Hi,

my statements refer to the EU.

please note description of Report Type Values
https://developer-docs.amazon.com/sp-api/docs/report-type-values

equivalent to GET_ORDERS_DATA is:

MFN:
XML - GET_ORDER_REPORT_DATA_INVOICING
TXT - GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING
(both only contains MFN Orders)

I don't work with xml. I did a quick comparison of the results from both reports.
GET_ORDER_REPORT_DATA_INVOICING also contains BuyerTaxRegistrationId, BillingAdress and ShippingAdress.

BUT, please note, the SP-API Report are not 1:1.
in my case, missing fields in "GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING" are:

bill-name
gift-message-text
default-ship-from-address... (8 Fields)

I opened a case on amazon and am still waiting for a response...

**Comment by ShaneOH** [comment]
For anyone coming across this I eventually opened a case with support directly and got the following response:

> Also, GET_ORDERS_DATA is deprecated in SP-API and was split into the following SPAPI reports: GET_ORDER_REPORT_DATA_INVOICING, GET_ORDER_REPORT_DATA_TAX and GET_ORDER_REPORT_DATA_SHIPPING.

Seems to line up a bit with what you're saying too @sat-it -- closing this issue now since it's mostly answered at this point
