### ISSUE TITLE
[BUG] FBA shipment creation changes to Send to Amazon but there are no SP APIs that match this workflow

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#2398]
Hello,

We received the notice that FBA shipment creation changes to Send to Amazon after September 1, 2022. But there are no SP APIs that match this workflow.

The “Send to Amazon” workflow needs to upload the box's quantity, weight, and dimension before creating a shipment. But now the Fulfillment inbound API workflow is to create inbound shipment plan and create inbound shipment, and then upload the box's quantity, weight, and dimension. 

What can we do to match the "send to Amazon" workflow via SP API?

**Comment by kingsun-he** [comment]
The replacement of Send/replenish inventory with Send to Amazon won't affect [Amazon Marketplace Web Service API](https://sellercentral-europe.amazon.com/gp/help/G200389230?language=en_GB&ref=ag_G200389230_cont_home) or [Selling Partner API](https://developer.amazonservices.com/gp/mws/docs.html). You can continue to access details and make changes to shipments that you create with APIs from your Shipping Queue after September 1.

**Comment by adrian-amz** [comment]
Hello @NancyLin,

Thank you for reaching out regarding {FBA shipment creation changes to Send to Amazon but there are no SP APIs that match this workflow}.

You can find details regarding this in our [Fulfillment Inbound API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#createinboundshipmentplan).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian C
Selling Partner API Developer Support
