### ISSUE TITLE
[BUG] Documentation  How can I update our product Image by listingItemApi-patchListingItem 

### ISSUE THREAD

**Issue by Braveman1999** [amzn/selling-partner-api-docs#2400]
this is the case I submitted for update Image，Is it failed. The response prompt 400
{
  "productType":"PRODUCT",
  "patches":[
    {
      "op":"replace",
      "path":"/attributes/main_product_image_locator",
      "value":[
        {
          "media_location": "https://imghz.epean.com.cn/trade/c9a94ad82c90ff4563d8.jpg",
          "marketplace_id": "ATVPDKIKX0DER"
        }
      ]
    }
   ]
 }

but I can update Item_name with fllowing code .  I very confused，because they  belong to same level in  attributes 

{
  "productType":"PRODUCT",
  "patches":[
    {
      "op":"replace",
      "path":"/attributes/item_name",
      "value":[
        {
          "value": "AmazonBasics 16\" Underseat Spinner Carry-On",
          "marketplace_id": "ATVPDKIKX0DER"
        }
      ]
    }
   ]
 }

**Comment by Braveman1999** [comment]
thank you  for you help

**Comment by Braveman1999** [comment]
I already resolve this question，I haven`t changed anything,but today the call was succeful

**Comment by chapmanjw** [comment]
You can find documentation about image hosting for submissions with the Listings APIs here: https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide#submitting-images-and-other-media-attributes
