### ISSUE TITLE
[BUG] Documentation The Documentation for Selling Partner APIs needs to be updated

### ISSUE THREAD

**Issue by roko79** [amzn/selling-partner-api-docs#2401]
I was following the [Using Postman for Selling Partner API models](https://developer-docs.amazon.com/sp-api/docs/using-postman-for-selling-partner-api-models) guide to make a test request and fetch data from the Selling Partner API. 
I couldn't make request, because there are missing fields in the request header (like the **x-amz-access-token**), I had to add it manually. I had to stop the video several times to figure out what's the difference between the downloaded model, and between what I've seen on the video. You cannot find anything on the developer-docs site that tells you to add the missing fields to the request header otherwise it won't work. 
All the required steps should be documented and instead of those shot and muted videos we should see more details in the videos explaining the steps instead of just clicking and scrolling around...

Thanks.

**Comment by adrian-amz** [comment]
Hello @roko79,

Thank you for proposing an enhancement to the [Using Postman for Selling Partner API models](https://developer-docs.amazon.com/sp-api/docs/using-postman-for-selling-partner-api-models).

We submitted the feature request for review. Once we receive additional information, we will post an update.

Thanks,
Adrian C
Selling Partner API Developer Support
