### ISSUE TITLE
[BUG] Operation getOrders returns "Access to requested resource is denied"

### ISSUE THREAD

**Issue by kmcconnell** [amzn/selling-partner-api-docs#2403]
I am getting the following when sending a request to /orders/v0/orders via Postman after following instructions and examples provided at https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api and https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference.

```json
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
```

1. We have registered a self-authorized app client in _Draft_ status and has an ARN IAM attached as described at https://developer-docs.amazon.com/sp-api/docs/registering-your-application.
2. I've checked the inline and role policies for the ARN IAM. They are exactly as described at https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities#step-4-create-an-iam-role.
3. We are able to successfully request an LWA access token following the docs at https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-1-request-a-login-with-amazon-access-token.
4. Using the AWS Signature authorization method in Postman, we're able to send a request to /orders/v0/orders following the docs at https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference. However, we get the Unauthorized response above.

It is somewhat unclear if the _getOrders_ operation requires an RDT since it is listed here https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-operations. However, then at https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#step-1-get-an-order-id, it's explained that you need an order ID to get an RDT and to call _getOrders_ for a list of order IDs, then get an RDT for a specific order ID and then use the RDT with a subsequent call such as _getOrderItems_. So, it seems to me that the initial _getOrders_ call should/does not require an RDT.

Thus, it's not clear what else needs to be done to resolve the Unauthorized response from the _getOrders_ operation.

**Comment by Adrian-T-AMZN** [comment]
Hello @[kmcconnell](https://github.com/kmcconnell),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by kmcconnell** [comment]
We opened a support case weeks ago and continue to receive no response. The level of support from Amazon has been appalling quite frankly. 

I don't know why this issue would be closed so quickly when the documentation does not clearly reflect what is required.

**Comment by tekka** [comment]
In my case,
My mistake was setted the array into restrictedResources without nesting.

![キャプチャ](https://user-images.githubusercontent.com/133705/180913420-539646bf-7ef6-431f-ad38-38ee580457e1.PNG)

**Comment by jrmaia** [comment]
Any solution? I have the same issue

**Comment by kmcconnell** [comment]
Hi Junior,

In our case, it was because restrictedResources has a different signature method than the rest of the API methods.

We were using Postman which only has the built-in AWS Signature type (v4 signing method).

I've reported the issue with Postman at https://github.com/postmanlabs/postman-app-support/issues/11075.

Ultimately, it won't work out of the box yet. You've got to build both signing methods into your project and test from there instead.

K
________________________________
