### ISSUE TITLE
CreateReport Being Throttles after 1 call, not respecting the burst rate of 15

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-docs#2408]

**Comment by KajdeMunter** [comment]
I'm experiencing the same with `POST https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/feeds`

**Comment by cmlkx** [comment]
I'm seeing the same behavior for CreateReport.  It seems like no quota is being restored.
It should be 0.0167 sec / 15 burst according to:
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2020-09-01-reference#createreport

60 / 0.0167 ~= 1 call per minute... but it seems liek the restore is not happening at all.  Please help!

**Comment by cmlkx** [comment]
Ok, interesting follow-up.  It seems like only these reports throw a 529 error:

- GET_FLAT_FILE_PENDING_ORDERS_DATA
- GET_PENDING_ORDERS_DATA
- GET_CONVERGED_FLAT_FILE_PENDING_ORDERS_DATA

The other reports appear to work fine.

**Comment by cmlkx** [comment]
Update 2022-07-19:
I have it in my notes that GET_FLAT_FILE_PENDING_ORDERS_DATA is for the JP marketplace only... so I guess this is fine!

**Comment by adrian-amz** [comment]
Hello @nafberger @KajdeMunter @cmlkx,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C
Selling Partner API Developer Support

**Comment by nafberger** [comment]
Adrian 

with me it turned out 2 things, there is a report limit which is different then regular throttling, its not documented at all, and also when passing in wrong start dates and end dates to reports sometimes the error comes back as throttles.
