### ISSUE TITLE
upload CreateFeed Upload 400 errors. Invalid request parameters

### ISSUE THREAD

**Issue by LINJINTIANDE** [amzn/selling-partner-api-docs#241]
{
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
CreateFeed,Some account uploads will not report 400 errors, but some account uploads and reports 400. The parameters are the sam

**Comment by nodisk8800** [comment]
I call createFeedDocument API, upload file, and createFeed ,all are successfull.

May be some parameters Invalid ,check you parameters .

**Comment by nodisk8800** [comment]
我这边调用全部正常,没有问题的.
再看一下文档,检查一下你的API调用.

**Comment by LINJINTIANDE** [comment]
我知道是某些参数错误，但是我多数账号上传产品是成功，只有少数的账号到createdFeed这一步失败，我看了参数都一样的。我还专门上传同一个产品，一个账号成功，一个账号失败。而且参数都一样的 就那个documentId这个参数不一样

**Comment by LINJINTIANDE** [comment]
@nodisk8800 关键就两三个账号上传出现这个问题，大部分账号都是正常的。我尝试上传的参数都一样，就documentId这个参数不一样。那个400的还是报400，成功的还是成功

**Comment by nodisk8800** [comment]
同个applicationid 吗?
