### ISSUE TITLE
[BUG] 400 Error: Duplicate requests submitted.  Cannot run batch request.

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2410]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
When calling `getItemOffersBatch`, I receive a 400 error occasionally:

```
Duplicate requests submitted.  Cannot run batch request.
```

**URL of the content on GitHub**
This is an API Response.

**Description of what the documentation currently says**
Right now the documentation doesn't say anything about this error.

**Description of what the documentation should say**
It would be nice to know why this error is occurring, and what actions I can take for it not to occur. This is different from a `429 Too Many Requests` error, so is there a separate limit that we cannot breach for this particular API?

**Screenshots**
N/A

**Additional context**
The reason why I must call this API in the first place is because `getListingOffersBatch` doesn't return `BuyBoxEligibleOffers`. Including that data in `getItemOffersBatch` would also resolve this issue.

**Comment by adrian-amz** [comment]
Hello @kennedyjustin,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C
Selling Partner API Developer Support

**Comment by ahmetsametoglu** [comment]
Hi @kennedyjustin,
Did you find a solution?
