### ISSUE TITLE
[QUESTION] Amazon Pay

### ISSUE THREAD

**Issue by dingledorf** [amzn/selling-partner-api-docs#2411]
Where is Amazon Pay in the documentation? Will Amazon Pay settlement reports appear in getReports for "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"? If not how can we pull the list of transactions/reports?

Thanks

**Comment by CrionaAm** [comment]
Hello @dingledorf 

There is no Pay sepcific section of the guide, as there is not Pay specific API feature. The disbursement report which covers Amazon Pay is the same report which covers Selling on Amazon and it is covered in the reporttypes documentation page here:


Thanks,
{Insert Name}
Selling Partner API Developer Support
