### ISSUE TITLE
[C#] Access to requested resource is denied when used SP-API with Vendor central !

### ISSUE THREAD

**Issue by ThanhLuan0932** [amzn/selling-partner-api-docs#2417]
Hi everyone, I'm having a problem for 2 weeks. I have a sample C# source code from GitHub: 
https://github.com/abuzuhri/Amazon-SP-API-CSharp
, then I also searched for the same source code but got the same error: "**Access to requested resource is denied.**" when call APIs ex: 
sellingpartnerapi-na.amazon.com/catalog/v0/items, 
sellingpartnerapi-na.amazon.com/products/pricing/v0/price
![Picture3](https://user-images.githubusercontent.com/33895995/178432565-c26c96cf-83ff-415c-972d-e45aa709a2aa.png)

Specifically, for authentication I followed the instructions at 
https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities

My User - IamConsole
![userIam](https://user-images.githubusercontent.com/33895995/178432663-9ffec42d-46fe-4475-97e0-895f653da510.PNG)
My Role - IamConsole
![roleIam](https://user-images.githubusercontent.com/33895995/178432687-5bab4aba-0bf0-42d3-9f7c-816af4623ae6.PNG)
Content policy:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}`
Content AsumeRole
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::XXXXXXXXXX:role/SellingPartner_Role",
            "Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": "true"
                }
            }
        }
    ]
}`

And on https://vendorcentral.amazon.com/sellingpartner/developerconsole I used role Arn to call api from my code
![web](https://user-images.githubusercontent.com/33895995/178435174-cffa5194-127c-40e1-910e-4b356be73eb7.png)

I also referenced other GitHub issues but still haven't found the solution, can someone help me !
Thanks all !

-------------
In my case:
Environment: https://vendorcentral.amazon.com
Marketplace: US
Language code: C#
My location: Asia

**Comment by CrionaAm** [comment]
Hello @ThanhLuan0932 ThanhLuan0932

In order to correctly resolve this issue, please open a support case (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Críona
Selling Partner API Developer Support
