### ISSUE TITLE
[FEATURE] Healthcheck possible?

### ISSUE THREAD

**Issue by Bowserlord** [amzn/selling-partner-api-docs#2422]
Hello together,

is there a good solution for a healthckeck if the amazon-sp-api-servers are currently accessible or not?
The call should not include any tokens or developer-keys.

Thank you very much in advance.

**Comment by liyouzhuo** [comment]
Access to requested resource is denied.

**Comment by CrionaAm** [comment]
Hello @Bowserlord 

Thank you for your proposal. We do not yet have an SP-API equivalant to the MWS API healthdashboard (http://status.mws.amazon.com/?reg=US), and access denied errors may be returned for a wide variety of reasons. 

We are currently working on an equivalant however, we do not have an estimated time of when the implementation will be complete.

As soon as this occurs, we will post an announcement in the [Announcements Section](https://developer-docs.amazon.com/sp-api/changelog) (https://developer-docs.amazon.com/sp-api/changelog) of our documentation site.

You can also review our [Release Notes](https://developer-docs.amazon.com/sp-api/page/release-notes) (https://developer-docs.amazon.com/sp-api/page/release-notes) regarding all changes made to our APIs.

Thanks,
Críona
Selling Partner API Developer Support
