### ISSUE TITLE
[BUG] GET_MERCHANT_LISTINGS_ALL_DATA returns invalid byte sequences

### ISSUE THREAD

**Issue by yutveg** [amzn/selling-partner-api-docs#2423]
**Describe the bug**
The reports API works great except for the GET_MERCHANT_LISTINGS_ALL_DATA report. We're pulling it in and trying to transcode it to UTF-8 to process, but it seems like it was improperly encoded in CP1252 in the first place so we can't work with the data. 

 
**Example of issue**
Here's an example of the byte sequences we are getting from the response body:
```
\x1F\x8B\b\x00\x00\x00\x00\x00\x00\x00\xD4\xBD\xD9r\xE3H\x96(\xF8\x8C\xFB\x15\xA8\xB6\xB1LEW@\x01w\xEC\xAA\xB4\xBC\xC6}\xDF\xC1\rmmc\x90\x04I\xE8 \t5H\x86\x82\xF9!\xF7\v\xE7}~a\xCEq,\xEE\xA4\xC0\b(\xB3j\xE6NF\x95\xA4C:\xC1\xE3\xDB\xD9\x97\xF0\x10l\x95\x9D\xBF\r\xA4\x10\xFFz\f\xF6\x0Fq\xF8z\b\xA3\x9D\xB4\t\xF7\x87p\xF7\xAC\x84\x8F\xD2>\xD8l\x82X\xD9\x7F=J\xAFq\xF8\x10H\xFF}\xF4w\x87\xF0p\x92\xA2\xD7`\xA7<\xFA\a\xF8\xFC\xD6\x7F\x0E\x94c\xBCI\x9E\x14\xEE\x95\xAD\x1F\x7F\r\x0E\xAF\e\x1F>\xF0\x1AG\x8F\xC7\x87\x03<L9\x9C^\x03\xE9\x8F\xFDK\xF4\xAA\xEC_\xC2\xD7W\xFC\x8E\xA7 E`\x17\x1D\xD2\xBF\x1E\xA2\xDDc\xC8\x10I\xC6>\xC0\x97<G\xF1\x89\xA4\xF0}\x1C\xBD\xED\x03\xE5\xD5?\xBCdO;Dq\xF0\x14G\xBB\x03<\xCF
```

**Additional context**
We are using Ruby and HTTParty to pull this report.

As per the docs, we are creating a report, and then once it is completed we are getting the URL where the report is located.
```ruby
report_data = @sp_request_factory.create_request(uri: "/reports/2021-06-30/documents/#{document_id}", method: "GET")
res = HTTParty.get(report_data['url'], :debug_output => log)
```

The debug_output shows the result of this.

When we try to encode it into UTF-8 (even when replacing the 5 codepoints that Ruby doesn't support in 1252) the output looks like garbage.

```ruby
report_data = @sp_request_factory.create_request(uri: "/reports/2021-06-30/documents/#{document_id}", method: "GET")
res = HTTParty.get(report_data['url'], :debug_output => log)
utf8_string = res.body.encode('utf-8', invalid: :replace, undef: :replace) 
```

The utf8_string contains characters like this:
```
ç}~aÎq,î¤(³jæNF•¤C:ÁãÛÙ—ðl•�¿
¯ðG�Ç‡<L9œ^é�ýKôªì_Â×WüŽ§ E`Ò¿¢ÝcÈIÆ>À—<Gñ‰¤ð}½íåÕ?¼dO;DqðG»<Ï?ã@ò÷áŽ°Ÿ”ýÔ¤·p³aß«„»Cï|ü
\u007F³9IÁ÷×\u0000¾1xÌÑÊ¾)Ú<>�OBº‡‰<EqöE�\n
```

**Comment by XRLZX8** [comment]
maybe you need decompress the res

**Comment by yutveg** [comment]
Looks like you're right. Makes me wonder why the Content-Encoding header isn't returned in the response. HTTParty will decompress for you but if it's not set how is one suppose to know it's compressed?

**Comment by yutveg** [comment]
It was a decompression issue. The tortuga URL that the Selling Partners API gives to fetch the report doesn't include a Content-Encoding header for clients to know to decompress it, definitely something that should be mentioned in the docs

**Comment by XRLZX8** [comment]
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreportdocument
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#reportdocument
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#compressionalgorithm

your  "report_data"  may have the compressionAlgorithm field

**Comment by yutveg** [comment]
> https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreportdocument https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#reportdocument https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#compressionalgorithm
> 
> your "report_data" may have the compressionAlgorithm field

It doesn't
