### ISSUE TITLE
Example request for Orders API

### ISSUE THREAD

**Issue by tswapnil** [amzn/selling-partner-api-docs#243]
`
 GetOrdersResponse resp = apiInstance.getOrders(marketPlaceIds, createdAfter, createdBefore,
                        lastUpdatedAfter, lastUpdatedBefore, orderStatuses, fulfillmentChannels, paymentMethods, buyerEmail,
                        sellerOrderId, maxResultsPerPage, easyShipShipmentStatuses, nextToken, amazonOrderIds);
`

getting a 400 Bad Request . Can someone provide an example of parameters to specify in the API request that would return a 200 code ?

**Comment by tswapnil** [comment]
@seanevan  Could you please assist with the issue above ? I am getting a response as follows - 

Response{protocol=http/1.1, code=400, message=Bad Request, url=https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2021-01-07T00%3A11%3A12.515020&CreatedBefore=2021-01-07T00%3A11%3A12.515060&LastUpdatedAfter=2021-01-07T00%3A11%3A12.515020&LastUpdatedBefore=2021-01-07T00%3A11%3A12.515060&BuyerEmail=&SellerOrderId=&MaxResultsPerPage=1&NextToken=&OrderStatuses=Unshipped&MarketplaceIds=A21TJRUUN4KGV&FulfillmentChannels=MFN&PaymentMethods=Other}

How could this be a bad request ?

**Comment by cohlar** [comment]
I think you shouldn't specify more than one date
