### ISSUE TITLE
Order API not working with RDT

### ISSUE THREAD

**Issue by night-fury-web** [amzn/selling-partner-api-docs#2432]
Today I got an error in GetOrders API with restricted data token.
It says "Your browser sent a request that this server could not understand. Size of a request header field exceeds server limit".
The endpoint works fine without RDT.

Since I use this on my private business application, PII data is needed and this issue is critical for me.

Please let me know what's wrong with this.

**Comment by JsonSong89** [comment]
I have the same problem , 
and few days ago ,it works fine . 
I can't fetch any significative infomation from this error message .

**Comment by night-fury-web** [comment]
@Adrian-T-AMZN @LindaNC Would you check this issue?

**Comment by kdfhhao** [comment]
When I use the order number to update the order status, the following problem occurs. When the same code is accessed normally in North America, the following error is reported in Europe, which is completely nonsensical.
404 bad request.
Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.

**Comment by kdfhhao** [comment]
> I have the same problem, it started on July 17th, what should I do?

Since July 17, Amazon has removed the PII permission of MWS. It is estimated that this has caused a bug, and we can only wait for Amazon to fix it.

**Comment by kevinvenclovas** [comment]
Same issue -.-

**Comment by night-fury-web** [comment]
> > I have the same problem, it started on July 17th, what should I do?
> 
> Since July 17, Amazon has removed the PII permission of MWS. It is estimated that this has caused a bug, and we can only wait for Amazon to fix it.

I can get PII data using MWS API.

**Comment by kdfhhao** [comment]
> > > I have the same problem, it started on July 17th, what should I do?
> > 
> > 
> > Since July 17, Amazon has removed the PII permission of MWS. It is estimated that this has caused a bug, and we can only wait for Amazon to fix it.
> 
> I can get PII data using MWS API.

mws to spapi

**Comment by kdfhhao** [comment]
There is no official statement. I guess the official bug needs to contact the official for confirmation.

**Comment by tonygalluscio** [comment]
Message from Amazon Developer Support: 

_I understand your RDT calls have been recently failing with a " Size of a request header field exceeds server limit." error. This is a known issue, affecting a portion of RDT calls for EU sellers. Our Technical team is currently working to address this, and I will notify you when they are finished. The impact should already be reduced from when it was first identified._

**Comment by Johnny99211** [comment]
Seems to work for me again!

**Comment by omidnoorani** [comment]
We are having the same exact problem. It is still not working for us. Anyone has any updates on this issue? Thank

**Comment by omidnoorani** [comment]
It started working for us around 12:14p PT (a few minutes before I posted here). 
@Johnny99211 --  We were on the latest version of the SDK already. Thanks for the suggestion.

**Comment by graedwin** [comment]
Hello! 

We recently deployed a fixed for this issue. Feel free to contact us again for any questions but we were able to confirm that there are no more errors.

**Comment by Philomath88** [comment]
@graedwin We recently got approved for the RDT but when I call for a RDT:

`async function getRestrictedToken() {
  try {
    const response = await sellingPartner.callAPI({
      operation: 'tokens.createRestrictedDataToken',
      endpoint: 'tokens',
      body: {
        restrictedResources: [
          {
            method: 'GET',
            path: '/reports',  // You need to replace this placeholder
            dataElements: ['TransactionID']  // You need to replace this placeholder
          }
        ]
      },
      version: '2021-06-30'
    });

    if (response && response.restrictedDataToken) {
      console.log('restrictedDataToken: ', response.restrictedDataToken);  // Corrected a typo here: 'reponse' -> 'response'
      return response.restrictedDataToken;
    } else {
      throw new Error('Restricted data token not found in response');
    }
  } catch (error) {
    console.error('Failed to obtain restricted token:', error);
    throw error;
  }
}`


I get this error: 

Failed to obtain restricted token: CustomError: Application does not have access to one or more requested data elements: [TransactionID]
    at SellingPartner.callAPI (/Users/maximiliandoelle/Projects/selling/node_modules/amazon-sp-api/lib/SellingPartner.js:705:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRestrictedToken (/Users/maximiliandoelle/Projects/selling/modules/createReport.js:289:22) {
  code: 'InvalidInput',
  details: '',
  type: 'error'
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

CustomError: Application does not have access to one or more requested data elements: [TransactionID]
    at SellingPartner.callAPI (/Users/maximiliandoelle/Projects/selling/node_modules/amazon-sp-api/lib/SellingPartner.js:705:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRestrictedToken (/Users/maximiliandoelle/Projects/selling/modules/createReport.js:289:22) {
  code: 'InvalidInput',
  details: '',
  type: 'error'
}

I have rotated the secret since rotation as well as reauthorised the app

**Comment by Philomath88** [comment]
@graedwin We also got recently approved for the RDT but can't access restricted values... Could you check whether we truly have access? The Amazon dev support (ticket) is not being helpful...
