### ISSUE TITLE
restrictedDataToken API returns 400 Bad Request (was working previously)

### ISSUE THREAD

**Issue by tonygalluscio** [amzn/selling-partner-api-docs#2434]
At 0305 am GMT on 7/19/2022 the restrictedDataToken API suddenly started returning an error after running for several months with no error. 

I can still get a regular token and I don't see anything wrong with the header.

I get the same error messages from our application code and from POSTMAN.

Here is the curl output with verbose turned on:

* upload completely sent off: 218 out of 218 bytes
< HTTP/1.1 400 Bad Request
< Date: Tue, 19 Jul 2022 10:06:17 GMT
< Content-Type: application/json
< Content-Length: 278
< Connection: keep-alive
< x-amzn-RequestId: a48a18a0...
< x-amz-apigw-id: VglEEF...
< X-Amzn-Trace-Id: Root=1-62d68219-...
<
* Connection #0 to host sellingpartnerapi-na.amazon.com left intact
2022-07-19_100617 ERROR[400]: amzn_post_message() failed.
400 Bad Request
Bad Request
<p>Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.</p>

Is anyone having this same issue?

**Comment by Rajesh-ExertisGO** [comment]
we are facing same issue

**Comment by tonygalluscio** [comment]
@Rajesh-ExertisGO was yours working previously and when did it stop working?

We are currently trying to determine if it is an issue on our end or if something changed in the SP-API. Our solution has been running for months with no issue.

**Comment by Rajesh-ExertisGO** [comment]
> @Rajesh-ExertisGO was yours working previously and when did it stop working?
> 
> We are currently trying to determine if it is an issue on our end or if something changed in the SP-API. Our solution has been running for months with no issue.

Yes we have been using it for months, it stopped working now. I have spent half a day trying to figure out if something is broken on our server side.

**Comment by tonygalluscio** [comment]
> > @Rajesh-ExertisGO was yours working previously and when did it stop working?
> > We are currently trying to determine if it is an issue on our end or if something changed in the SP-API. Our solution has been running for months with no issue.
> 
> Yes we have been using it for months, it stopped working now. I have spent half a day trying to figure out if something is broken on our server side.

Ours stopped working at 0305 GMT on July 19, 2022. Does that line up with when yours stopped working?

**Comment by Rajesh-ExertisGO** [comment]
First error message we got was around 11 pm GMT on July 18th 2022, but noticed today morning as orders were no flowing through

**Comment by tonygalluscio** [comment]
Looks like others are having the same issue: https://github.com/amzn/selling-partner-api-docs/issues/2432

**Comment by omidnoorani** [comment]
Are there any updates on this issue?
We are having the same exact problem. It stated this morning. It has been working fine for months. 
Some people in https://github.com/amzn/selling-partner-api-docs/issues/2432 say that it's now working for them but not for us.

**Comment by kdfhhao** [comment]
The official statement has fixed the bug.
