### ISSUE TITLE
[BUG] Upload product, createFeed select Japan, Saudi Arabia site, Invalid request parameters

### ISSUE THREAD

**Issue by LINJINTIANDE** [amzn/selling-partner-api-docs#244]
The value of the site is also written in accordance with the document, uploaded to other sites can upload success, confused!
![image](https://user-images.githubusercontent.com/42436479/103271124-57ded000-49f4-11eb-9e1d-a60482c53dff.png)

Each time you upload to both sites, you get 400 errors
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }

**Comment by nodisk8800** [comment]
搞来搞去，都是我们这几个人在反馈问题

**Comment by nodisk8800** [comment]
你这2个站点是不是没在经营了啊？

**Comment by LINJINTIANDE** [comment]
@nodisk8800 那个没有经营的我上传上去了，那个经营的我没有上传上去，这个就奇怪了。。。

**Comment by LINJINTIANDE** [comment]
@nodisk8800 一个日本站没有经营的我上传上去了，有个日本站还在经营的我没有上传上去，这个就奇怪了。。。 都是同样的参数。我都怀疑是账号的问题

**Comment by fengmiq** [comment]
@nodisk8800 官方都不理我们，提一个问题几周都没有反应，看来你可以做官方的客服了

**Comment by yusufdonmez** [comment]
> The value of the site is also written in accordance with the document, uploaded to other sites can upload success, confused!
> ![image](https://user-images.githubusercontent.com/42436479/103271124-57ded000-49f4-11eb-9e1d-a60482c53dff.png)
> 
> Each time you upload to both sites, you get 400 errors
> {
> "code": "InvalidInput",
> "message": "Invalid request parameters",
> "details": ""
> }

Is there an API for UPLOAD_PRODUCT_DATA ?

**Comment by LINJINTIANDE** [comment]
@yusufdonmez Yes, but there are two accounts. The process of uploading to Japan and Saudi Arabia is uploaded to createFeed, and the error shown in the picture is reported. There is no problem with other accounts

**Comment by linsiming** [comment]
> @yusufdonmez Yes, but there are two accounts. The process of uploading to Japan and Saudi Arabia is uploaded to createFeed, and the error shown in the picture is reported. There is no problem with other accounts

I also encountered the same problem. How can I solve this problem?

**Comment by linsiming** [comment]
@yusufdonmez @LINJINTIANDE 
I also encountered the same problem. How can I solve this problem?

Is it possible that the app is not available? Draft status now！

**Comment by StefanosPs** [comment]
I have the same problem.
I am getting this response from my code.
So, I tried to use  [amazon-sp-api (client for the Amazon Selling Partner API)]( https://github.com/amz-tools/amazon-sp-api ), and I am still getting the same response.

**Comment by linsiming** [comment]
I have resolved it because I did not follow the official process.
createFeed must be uploaded first, and then created using the FeedDocumentId returned by createFeedDocument。

**Comment by linsiming** [comment]
> I have the same problem.
> I am getting this response from my code.
> So, I tried to use [amazon-sp-api (client for the Amazon Selling Partner API)](https://github.com/amz-tools/amazon-sp-api), and I am still getting the same response.

I have resolved it because I did not follow the official process.
createFeed must be uploaded first, and then created using the FeedDocumentId returned by createFeedDocument。

**Comment by StefanosPs** [comment]
@linsiming, I am following the official process. 
For example, when I implement  amazon-sp-api (client for the Amazon Selling Partner API), I follow the example of the [link](https://github.com/amz-tools/amazon-sp-api#encrypt-and-upload-feeds)

**Comment by StefanosPs** [comment]
@linsiming  thanks for your reply!!
Could you be more specific about the step you follow; 
It will help me if you describe and the names of each HTTP request header.

**Comment by linsiming** [comment]
Do you use XML or CSV? 
This may be caused by the loss of required parameters in XML. 
It's not necessarily a problem with the createFeed .
@StefanosPs

**Comment by StefanosPs** [comment]
I am using XML.
For my test I put the XML from official amazon documentation:  https://images-na.ssl-images-amazon.com/images/G/02/rainier/help/XML_Documentation_Intl._V158772716_.pdf
example
`<?xml version="1.0" ?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amznenvelope.xsd">
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>XXXXXXX</MerchantIdentifier>
</Header>
<MessageType>Product</MessageType>
<PurgeAndReplace>true</PurgeAndReplace>
<Message>
<MessageID>1</MessageID>
<OperationType>Update</OperationType>
<Product>
<SKU>TEST-DEV-000001</SKU>
<ProductTaxCode>A_GEN_TAX</ProductTaxCode>
<LaunchDate>2005-07-26T00:00:01</LaunchDate>
<DescriptionData>
<Title>Lyric 500 tc Queen Flat Sheet, Ivory</Title>
<Brand>Peacock Alley</Brand>
<Description>Lyric sheeting by Peacock Alley is the epitome of simple and classic elegance. The flat sheets
and pillowcases feature a double row of hemstitching. The fitted sheets fit mattresses up to 21 inches deep.
The sheets are shown at left with tone on tone monogramming, please call for monogramming details and prices.
Please note, gift wrapping and overnight shipping are not available for this style.</Description>
<BulletPoint>made in Italy</BulletPoint>
<BulletPoint>500 thread count</BulletPoint>
<BulletPoint>plain weave (percale)</BulletPoint>
<BulletPoint>100% Egyptian cotton</BulletPoint>
<Manufacturer>Peacock Alley</Manufacturer>
<SearchTerms>bedding</SearchTerms>
<SearchTerms>Sheets</SearchTerms>
<ItemType>flat-sheets</ItemType>
<IsGiftWrapAvailable>false</IsGiftWrapAvailable>
<IsGiftMessageAvailable>false</IsGiftMessageAvailable>
</DescriptionData>
<ProductData>
<Home>
<Parentage>variation-parent</Parentage>
<VariationData>
<VariationTheme>Size-Color</VariationTheme>
</VariationData>
<Material>cotton</Material>
<ThreadCount>500</ThreadCount>
</Home>
</ProductData>
</Product>
</Message>
<Message>
</AmazonEnvelope>`

**Comment by linsiming** [comment]
@StefanosPs you lost upc .
```
<StandardProductID>
      <Type>UPC</Type>
      <Value>******</Value>
</StandardProductID>
```

**Comment by StefanosPs** [comment]
@linsiming thanks again for your help, but I still get the error "InvalidInput".
Do you know any tool to check my XML except  https://mws.amazonservices.com/scratchpad/index.html

**Comment by cdragon1116** [comment]
Same issue, getting error after sucCessfully upload xml file

```
{"errors"=>[{"code"=>"InvalidInput", "message"=>"Invalid Input", "details"=>""}]}
```

**Comment by 401009641** [comment]
真TMD拉垮，bug一大堆，响应的提示信息也是模糊不清

**Comment by LINJINTIANDE** [comment]
@401009641 早点脱坑，那不是人干的

**Comment by emilianmanolache** [comment]
Same issue here, with POST_PRODUCT_PRICING_DATA.
Only happens on Amazon Japan (haven't tried Saudi Arabia), but works on all Europe and North America marketplaces.

**Comment by emilianmanolache** [comment]
We're having the exact same issue
