### ISSUE TITLE
Important: Amazon Marketplace Web Service (MWS) End-of-Life Dates

### ISSUE THREAD

**Issue by HIT2022Seller** [amzn/selling-partner-api-docs#2440]
Hello - We want to confirm the RDT token is NOT required until 2023 for the SP-API to function. We are using the shipment functions specifically to generate labels for seller fulfilled prime

### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2404

<div type='discussions-op-text'>

<sup>Originally posted by **jevoniuk** July  6, 2022</sup>
Amazon Marketplace Web Service (MWS) will no longer be available after **December 31, 2023**.

In 2020 we announced the launch of Selling Partner API (SP-API), a modernized suite of REST APIs using standards that today's developers expect, which includes all the functionality available in Amazon MWS plus many new APIs. SP-API will fully replace MWS, and we are migrating developers to SP-API as we work to deprecate MWS.

SP-API offers a number of improvements over MWS such as modernized, JSON-based REST API design standards, OAuth2.0 selling partner authorization using Login with Amazon, and a test endpoint. Integrating all applications with SP-API will provide the best experience for developers and selling partners.

In 2021 we began working on the migration for all public third-party MWS developers to ensure their apps are fully integrated with Selling Partner API (SP-API) by the end of 2022. You can view the [migration updates for all third-party public developers](https://developer-docs.amazon.com/sp-api/changelog/important-selling-partner-api-migration-updates-for-all-public-mws-developers) for more information.

## Migration dates for private developers

**We are now announcing the migration due dates that will affect all private application developers who are using MWS.**

- **Private developer:** A developer that builds application(s) that integrate their own company with Amazon APIs.
- **Private application:** An application that is available only to your organization and is self-authorized.

**All private MWS developers must take action.** The action you take depends on whether you want to continue to own and operate a private app, or if you want to start using a third-party app to replace your existing private app functionality.

### Replacing a private app with third-party solutions

Private app developers who decide to not continue to own and operate a private app may consider authorizing a third-party app solution to replace their private app functionality. This must be done by the dates mentioned below to avoid loss of functionality. We encourage you to visit the [Amazon Seller Central Partner Network (ASCPN)](https://sellercentral.amazon.com/partnernetwork) to search through over 2000 vetted apps.

### Maintaining a private app

Private developers who want to continue to own and operate a private app must migrate usage of MWS API sections to SP-API by the following dates:

#### July 31, 2023

Applications that do not migrate will not be able to successfully retrieve data from these sections in MWS beginning August 1, 2023:

- MWS Merchant Fulfillment (MFN)
- Orders
- Reports
- Products

#### December 31, 2023

Applications that do not migrate will not be able to successfully retrieve data from all other MWS API sections beginning January 1, 2024:

- Feeds
- Finances
- Fulfillment Inbound Shipment
- Fulfillment Inventory
- Fulfillment Outbound Shipment
- Recommendations
- Sellers
- Subscriptions
- Push Notifications Schemas

**Applications that do not fully migrate will not be able to successfully retrieve data from any sections in MWS beginning January 1, 2024.**

We are focused on providing the necessary information, tools, and assistance to migrate your apps to SP-API. A list of resources is provided at the bottom of this announcement, and we will continue to share information and resources related to the migration process in the coming months.

## Restricted Data Token (RDT) requirement

Effective **July 31, 2023**, all developers whose SP-API applications have SP-API roles related to Direct-to-Consumer Fulfillment, Shipping, Tax, or Reports must use the new Restricted Data Token (RDT) via the Tokens API to make a successful API call for some operations. 

RDTs are a new access protocol for some operations and report types in the Orders, MFN, Shipping, and Reports sections.

The Selling Partner API for tokens provides a secure way to access a customer's personally identifiable information (PII). You can call the Tokens API to get a Restricted Data Token for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.

For more information, see the [Tokens API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide).

## Which marketplaces are affected?

This affects all marketplaces.

## Who is affected?

All Private Developers with self-authorized (“private”) applications using Amazon MWS.

## What action is required?

- Private developers using MWS Orders, Reports, Merchant Fulfillment, or Products API sections who want to continue to own and operate a private app, must migrate these sections to SP-API by **July 31, 2023**.
- Private developers whose SP-API applications have Direct-to-Consumer Fulfillment, Tax, Shipping, or Reports use cases must use the new Restricted Data Token (RDT) via the Tokens API by **July 31, 2023**.
- Private developers using all other MWS sections who want to continue to own and operate a private app, must migrate all other MWS API sections to SP-API by **December 31, 2023**.
- **If you decide you do not want to continue to own and operate a private app, or do not want to migrate your app to SP-API, you have the option to find a third-party app solution to replace your current business automation services.** Depending on your business automation needs, you should plan to authorize a third-party app by the due dates mentioned above. We encourage you to visit the [Amazon Seller Central Partner Network (ASCPN)](https://sellercentral.amazon.com/partnernetwork), to review over 2000 vetted apps that offer various automation solutions for your business needs. 

If your organization is affected by this, please monitor the forums for new posts with information related to migration.

## More information

These resources are available to aid your migration:

- [SP-API Migration FAQs](https://developer-docs.amazon.com/sp-api/page/sp-api-migration-faqs)
- [Migration Hub](https://developer-docs.amazon.com/sp-api/page/migration-hub)
- [SP-API Migration Guide](https://developer-docs.amazon.com/sp-api/docs/amazon-mws-to-sp-api-migration-guide)
- [Seller University videos](https://sellercentral.amazon.com/learn)
- [SP-API Getting Started Videos](https://www.youtube.com/playlist?list=PLyrrqKCT7jFKENJO9n_Y68-5o2GZLgLUU)
- [SP-API AWS Quickstart](https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/)
- [SP-API Developer Guide](https://developer-docs.amazon.com/sp-api/docs/what-is-the-selling-partner-api)
- [Tokens API Reference](https://developer-docs.amazon.com/sp-api/docs/tokens-api-v2021-03-01-reference)
- [Tokens API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide)
- [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2020-12-01-use-case-guide)
- [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide)

Best regards,

The Amazon MWS Migration Support team</div>

**Comment by Adrian-T-AMZN** [comment]
Hello @HIT2022Seller,

Thank you for reaching out regarding enforcement of the RDT token.

To confirm, effective July 31, 2023, all developers whose SP-API applications have Direct-to-Consumer Fulfillment, Tax, Shipping, or Reports use cases must use the new Restricted Data Token (RDT) via the Tokens API to make a successful API call for some operations. 

When RDT is enforced, LWA tokens to access restricted operations and report types will be blocked and developers will be able to access these APIs only with RDT.

You can find details regarding this in the migration hub: https://developer-docs.amazon.com/sp-api/page/migration-hub

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian T.
Selling Partner API Developer Support
