### ISSUE TITLE
Feed Processing Delays

### ISSUE THREAD

**Issue by graedwin** [amzn/selling-partner-api-docs#2443]
Seller feeds were stuck in pending status starting on 07/21 at 18:10 PDT.

Dev teams have identified a potential root cause and are actively working to resolve it. Still no ETA but I will keep posting updates here

Javier Villalobos
Amazon - Site Reliability Engineer

**Comment by EstebanSP-506** [comment]
Seller feeds were stuck in pending status starting on 07/21 at 18:10 PDT and 07/23 at 02:00 PDT

The backlog is fully recovered and Feed processing delays were resolved. 

Esteban S.
Amazon - Site Reliability Engineer
