### ISSUE TITLE
Get Non PII data from getOrders

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#2447]
We are using the following APIs, but we don't require PII data from these APIs. Still, do we need RDT to get non-PII data from the below APIs?

Orders
 - GetOrders
 - GetOrder
 - GetOrderItems

**Comment by TkTech** [comment]
We are also running into this _severe_ limitation. We want to call `getOrders` for vendor analytics, but we don't _want_ to access PII. We simply don't need it. The available reports can only provide aggregates (`GET_VENDOR_SALES_REPORT`) which is nearly useless. These endpoints need open, non-PII alternatives that do not require an RDT.

**Comment by LindaNC** [comment]
Hello @[Nilanth](https://github.com/Nilanth),

Thank you for reaching out regarding your question about PII information in the Orders APIs. 

You can find details regarding this in our https://developer-docs.amazon.com/sp-api/docs/amazon-mws-to-sp-api-migration-guide#features-of-selling-partner-api. For the APIs you have requested, the calls will provide information without RDT but it will not have PII information.  
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

@[TkTech](https://github.com/TkTech) - This sounds like a different issue, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Linda
Selling Partner API Developer Support
