### ISSUE TITLE
Request for additional parameter for marketplace ID in priceFeed XSD

### ISSUE THREAD

**Issue by AJ-AUS** [amzn/selling-partner-api-docs#2448]
**Describe the bug**
There is no parameter for marketplace ID within the XSD.

**Use Case**
Even though It is possible to specify multiple marketplaces to post feeds, it is not possible to update multiple marketplaces because there is no parameter for marketplace ID within the object. Because SKUs may be identical in alternate marketplaces, it is not possible to update multiple marketplaces simultaneously.

**Comment by chapmanjw** [comment]
@AJ-AUS Moving forward, I would suggest transitioning your price updates use-case to the newer Listings APIs (one listing per submission) and/or JSON_LISTINGS_FEED feed format for the Feeds APIs (multiple listings per submission). 

Currently, the Listings APIs will allow price updates for one marketplace at a time. However, we are working to expand this to accept multiple-marketplace updates in the future (which will enable price updates per marketplace within a single submission). 

- Listings Items API (single submissions): https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide
- Product Type Definitions API (provides schemas for Listings API and JSON_LISTINGS_FEED submissions): https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide
- JSON_LISTINGS_FEED Schema (schema for the feed document itself): https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2

While these do not yet enable multi-marketplace submissions for price updates, they will be the mechanisms that will accept multi-marketplace updates in the future. Stay tuned to release announcements for these features. Thanks.
