### ISSUE TITLE
Machine2Machine Authentication 

### ISSUE THREAD

**Issue by ChrisLeeBare** [amzn/selling-partner-api-docs#245]
Hi,

I may missed a specific point in the dev guide. 
Scenario:
We developed an ERP Module for our customers to interact with the Amazon SP API mainly gathering reports and create inventory bookings etc.
We have no website, which a user authorizes etc. It's basically machine2machine auth and communication (ERP Module <-> Amazon).
The old api allowed authentication with SellerId, MWSAuthToken, AwsAcccessKeyId and SecretKey which was provided by our customers and was configured in our ERP Module. 

But I can't find the right workflow with the new api.
1. Marketplace Auth Workflow -> requires iirc a website where the user logs ins.
2. Website Auth Workflow -> requires also a website
3. Self-Auth Workflow -> works but only allows access to our own seller central account.

What is the correct workflow for a pure machine2machine auth workflows for our ERP Module.
Thanks in advance.

**Comment by nodisk8800** [comment]
搞来搞去，都是我们几上在反馈问题

**Comment by parvathm** [comment]
Hi @ChrisLeeBare ,

Marketplace or Website Auth workflow is recommend for 3p authorizations but you can try sharing your OAuth Authorizations URIs until your application is published. Please refer to this section https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#authorizing-selling-partner-api-applications on how to create OAuth URIs. Please open a support case if you want to discuss more about workflow that works for you.

Thanks,
Parvathm,
Selling Partner API Developer Support.
