### ISSUE TITLE
I would like to list my items using the Listing Item API

### ISSUE THREAD

**Issue by ThalesGama** [amzn/selling-partner-api-docs#2454]
Please, I query the product type of ABIS_BOOK, and it returns me the necessary parameters. See below

GET- https://sellingpartnerapi-na.amazon.com/definitions/2020-09-01/productTypes/ABIS_BOOK?marketplaceIds=A2Q3Y263D00KWC

![image](https://user-images.githubusercontent.com/109821991/180829024-c424ec9d-3d9b-499c-9138-a48a4375e5a9.png)

PROBLEM, when trying to list my product for sale, I get the message stating that I can not use the type ABIS_BOOK, is not available for BRAZIL ?

![image](https://user-images.githubusercontent.com/109821991/180829775-45687aaa-e799-4e81-b6e2-9063e23974a5.png)

**Comment by chapmanjw** [comment]
@ThalesGama We are in the process of migrating support for product types to the APIs (Listings Items and Product Type Definitions APIs). You can use the following to stay up-to-date on the latest available product types for each marketplace:

- Product Type Definitions API Search (call without providing keywords to get the whole list): https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide#tutorial-search-available-product-type-definitions
- PRODUCT_TYPE_DEFINITIONS_CHANGE (push notification sent when new product types are migrated/launched and when new versions are available): https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#product_type_definitions_change
