### ISSUE TITLE
FeedPutRequest - CredentialsMalformed

### ISSUE THREAD

**Issue by Muschke** [amzn/selling-partner-api-docs#2456]
When you perform a post request to this url: https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/documents, you receive a feedDocumentId and a URL. 

This URL consist of a request to https://tortuga-prod-eu.s3-eu-west-1.amazonaws.com/%2FNinetyDays/amzn1.tortuga.3.11c0e5b7-fff0-4dab-bac1-f13645aa279a.T2WTUGMZ4PTSYL, followed by some parameters:
- X-Amz-Algorithm
- X-Amz-Date
- X-Amz-SignedHeaders
- X-Amz-Expires
- X-Amz-Credential
- X-Amz-Signature

In accordance to all the other requests in the api we have been doing, the next request do do the actual update, doens't need us to generate a signature that matches the request.  So we make a request to the url https://tortuga-prod-eu.s3-eu-west-1.amazonaws.com-url we got from amzon, with the body:
`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>identifier</MerchantIdentifier>
    </Header>
    <MessageType>Inventory</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <Inventory>
            <SKU>sku</SKU>
            <Quantity>quantity</Quantity>
        </Inventory>
    </Message>
</AmazonEnvelope>`
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>identifier</MerchantIdentifier>
    </Header>
    <MessageType>Inventory</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <Inventory>
            <SKU>sku</SKU>
            <Quantity>quantity</Quantity>
        </Inventory>
    </Message>
</AmazonEnvelope>

what do we get back instead of 200 or 202? 
"the Credential is mal-formed; expecting "&lt;YOUR-AKI"

What are we doing wrong for this putRequest? We got the url from amazon like that in the first place..

note: when we decode the url, we get past the credentials error. Though we still get an error of unmatching signatures. Which is still strange cause we get the signature from amazon.

**Comment by LindaNC** [comment]
Hello @[Muschke](https://github.com/Muschke),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support

**Comment by Muschke** [comment]
Dear Linda

We already fixed it by ourselves, but you shouldn't just close this way cause the problem was caused by bad/non-existing/incorrect developper documentation. You could  learn a lot from things like this.

Opening support cases never helps, you don't get answers, the cases  don't get read well by the "support".

And you really don't need extra details to reply to this. 

kind regards
