### ISSUE TITLE
 [Question] Vendor Central can get DF suppressed listings report？

### ISSUE THREAD

**Issue by zuosai5** [amzn/selling-partner-api-docs#2461]
I have a question, as a Vendor Central user, can I use the API https://developer-docs.amazon.com/sp-api/docs/report-type-values get Direct Fulfillment suppressed listings report？

Suppressed Listings Report
reportType value:
GET_MERCHANTS_LISTINGS_FYP_REPORT

**Comment by NA-Dev** [comment]
I would also love to be able to get that list from the API as a vendor. The GET_MERCHANTS_LISTINGS_FYP_REPORT is not available for us, and I think it would not include Direct Fulfillment anyway.
