### ISSUE TITLE
[BUG] CATALOG ITEMS API-getCatalogItem have not get ReleaseDate information

### ISSUE THREAD

**Issue by zuosai5** [amzn/selling-partner-api-docs#2464]
We have been informed via“SP-API Throttling Adjustments” that Catalog Items API v0 will be deprecated on Sept.30 thus we are currently migrating into Catalog Items API v2022-04-01. However, we are not able to find the return command for the data “ReleaseDate”. Is this attribute no longer available in the new version? If it is still available, how do I get it?

**Comment by gokigoks** [comment]
I wish they made all the catalog fields available in MWS also available in SPAPI e.g. label, isAdultProduct, etc.
