### ISSUE TITLE
All places we get a 403

### ISSUE THREAD

**Issue by chetanshind** [amzn/selling-partner-api-docs#2466]
Hello,

I am using this API and it is working for the first call but for the nextToken I am getting 403.

https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?granularityType=Marketplace&granularityId=ATVPDKIKX0DER&marketplaceIds=ATVPDKIKX0DER&details=true&nextToken=70393764%3ABL134%252DU

This is the URL that I am generating. Please can you suggest why I am getting a 403 [ "code": "InvalidSignature"]   

======================

Also when I was testing another API  https://sellingpartnerapi-na.amazon.com/orders/v0/orders?CreatedAfter=2022-07-18T00%253A00%253A00Z&MarketplaceIds=ATVPDKIKX0DER&NextToken=<long token>  
this URL worked for the initial request where I got the first Token and then I kept on pulling next payload by sending the nextToken that I was get as part of the response. But suddenly again I got a 403. But this time the message was a bit different

Forbidden -- Server understood the request, but will not grant access, even with different credentials

Is this a case of wrong Error messages or is it that there was suddenly a 403 case generated?

Please can you help so that we can proceed on this issue.

Regards,
Chetan

**Comment by Adrian-T-AMZN** [comment]
Hello @chetanshind,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
