### ISSUE TITLE
searchCatalogItems 2022-04-01 Sandbox Failed to match parameters [BUG] Documentation

### ISSUE THREAD

**Issue by defenderjim** [amzn/selling-partner-api-docs#2467]
When trying to hit the searchCatalogItems Sandbox endpoint , I get the error response "Could not match input arguments".

Here is the URL for the endpont:
    [https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#searchcatalogitems]

Here is the URL for the documentation on how to invoke the sandbox response:
    [https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-model]

Docs say to use these values to match the sandbox data.
   ```
 includedData: "attributes","dimensions","identifiers","images","productTypes","relationships","salesRanks","summaries","vendorDetails"
    marketplaceIds: "ATVPDKIKX0DER"
    keywords: "samsung","tv"
```

Here is my request:

    GET https://sandbox.sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items
    ?keywords=samsung%2ctv
    &marketplaceIds=ATVPDKIKX0DER
    &includedData=attributes%2cdimensions%2cidentifiers%2cimages%2cproductTypes%2crelationships%2csalesRanks%2csummaries%2cvendorDetails

**Comment by chapmanjw** [comment]
@defenderjim My team is working on resolving this issue. I will update this issue once resolved.

**Comment by pecalleja** [comment]
Any update on this?

**Comment by getvicky83** [comment]
any update on this ,my response says accessdenied when sandbox parameters are used

**Comment by defenderjim** [comment]
@getvicky83 Does the call work on the live site?

**Comment by defenderjim** [comment]
@getvicky83 You wrote that you are getting Access Denied error.  That means you are not constructing the call correctly.
Or that you do not have the correct role permission.  You must have the Product Listing role .

**Comment by OlehKosylo** [comment]
> @getvicky83 You wrote that you are getting Access Denied error. That means you are not constructing the call correctly. Or that you do not have the correct role permission. You must have the Product Listing role .

My error is: "Could not match input arguments".
About Access Denied, man above

**Comment by smargoli2** [comment]
I am getting Input Mismatch error, can you please resolve this? What is the static sandbox input supposed to be?
