### ISSUE TITLE
FBM

### ISSUE THREAD

**Issue by ghost** [amzn/selling-partner-api-docs#247]
Hallo...
As we need to call createShipment Api(FBM). And this Api requires two paramater ShipmentRequestDetails, ShippingServiceId,
So we need to call getEligibleShipmentServices first because getEligibleShipmentServices returns ShippingServiceList(which contains ShippingServiceId ).
To call getEligibleShipmentServices API we requires ShipmentRequestDetails object .Schema for this object requires
AmazonOrderId,ItemList,ShipFromAddress,PackageDimensions,weight.
And each  PackageDimensions requires Length, Width,Height,Unit
Issue I sell my product by email.. so we have no weight Etc.....so how can I inform amazon(FBM) by API ? my product is delivered.

**Comment by newpepsi** [comment]
this api is complex
