### ISSUE TITLE
End Of Life Date - Product API Confirmation 

### ISSUE THREAD

**Issue by AJ-AUS** [amzn/selling-partner-api-docs#2470]
A GitHub announcement says that the Products API end-of-life date is August 1st, but Developer Support sent a 30-day warning stating that Products API would be deprecated on September 30th. Which is it??

(screenshots attached)

<img width="885" alt="image" src="https://user-images.githubusercontent.com/70714438/182014477-b64b24c7-124d-4200-93d2-486caf8101d6.png">

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/70714438/182014503-49e072f2-8de0-4389-904b-654bcad5e39e.png">

**Comment by Adrian-T-AMZN** [comment]
Hello @AJ-AUS,

Thank you for reaching out regarding the MWS Products section deprecation date.

Effective September 30, 2022, all third-party developed applications (public applications) authorized by selling partners using the Amazon MWS Products section must migrate to the [Selling Partner API for Catalog Items](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2020-12-01-reference) and [Selling Partner API for Listings Items](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference).

You can find details regarding this in the migration hub: https://developer-docs.amazon.com/sp-api/page/migration-hub

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian T.
Selling Partner API Developer Support
