### ISSUE TITLE
EventBridge Notification Rule [BUG] Documentation

### ISSUE THREAD

**Issue by defenderjim** [amzn/selling-partner-api-docs#2471]
The documentation on how to create an event rule does not match the AWS Console work flow.  The docs need to be updated.

The document is here, check out Step 3.
[https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide]

To check the actual work flow
[https://us-east-1.console.aws.amazon.com/events/home?region=us-east-1#/rules/create]

Under "Step 3."  --> procedures 6,7,8, & 9 do not match the workflow.

**Comment by sungolivia** [comment]
Hey @defenderjim this is awesome, thanks for pointing this out!

Did you know that you can actually provide this feedback directly to our tech writing team?
Go back to the [use case guide](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide),  and the section where it says 'Did this page help you?' will take you to provide a feedback as well!
![Screen Shot 2022-09-20 at 2 05 30 PM](https://user-images.githubusercontent.com/7606170/191364531-e9f26822-f78b-4643-b72f-d1de9c4197a8.png)
