### ISSUE TITLE
[BUG] Documentation - DeemedResellerCategory enum missing values

### ISSUE THREAD

**Issue by IThompsonKC** [amzn/selling-partner-api-docs#2473]
Currently, when looking at the documentation for the DeemedResellerCategory enum, it only specifies IOSS & UOSS:

https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#deemedresellercategory

We have had orders come down with a value of CA_MPF which caused problems until we included this as a valid value.

Could the documentation be updated to include all possible values for this enum please?

**Comment by IThompsonKC** [comment]
Found another value today of NZ_VOEC. Are we able to get a full list of values that could be passed down for this field please?

**Comment by sungolivia** [comment]
Hey @IThompsonKC thanks for pointing this out!

Did you know that you can submit this feedback to our tech writing team directly?
Just navigate to the bottom of the page you linked up there and click on 'Did this page help you?' and it will take you to fill out a feedback!
![Screen Shot 2022-09-20 at 2 09 14 PM](https://user-images.githubusercontent.com/7606170/191365109-c257726e-da53-4047-a72c-dbd0720a0024.png)
