### ISSUE TITLE
[BUG] Merchant Fulfilment sandbox calls returning erroneous data for label

### ISSUE THREAD

**Issue by IThompsonKC** [amzn/selling-partner-api-docs#2475]
When attempting to use the createShipment sandbox call in the Merchant Fulfilment section of the API, the label that is returned in the FileContents section (https://developer-docs.amazon.com/sp-api/docs/merchant-fulfillment-api-v0-reference#filecontents) can't be processed due to the Contents not being a valid base64 string.

We have our process working with live data, but it's just the sandbox data that is incorrect.

Could this be updated to have a valid response that can be processed?

**Comment by bjt19882222** [comment]
i can confirm this.
either the base64 encoding or the gzip compression is wrong.
i am working with c#

crazy thing is: if the FileContents of the label is a png file everything works great. (e.g DPD Label)

if the label is a pdf file (e.g: DHL Label) my c# decompression code is not working
