### ISSUE TITLE
[BUG] Rate-Limits of POST /products/fees/v0/feesEstimate are totally wrong

### ISSUE THREAD

**Issue by cgaugel** [amzn/selling-partner-api-docs#2482]
The Rate-Limits of the POST /products/fees/v0/feesEstimate endpoint are wrong. This is the rate limit in the documentation:

https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference#post-productsfeesv0feesestimate

![image](https://user-images.githubusercontent.com/3075098/182888508-f743afef-256e-4b5c-a54a-a06723b16f71.png)

I am calling this Api-Endpoint with a sleep of 6 seconds between every call. This is the result of my requests:

04.08.22 - 15:32:02 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:32:09 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:32:15 SUCCESS.
04.08.22 - 15:32:22 SUCCESS.
04.08.22 - 15:32:28 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:32:34 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:32:40 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:32:46 SUCCESS.
04.08.22 - 15:32:53 SUCCESS.
04.08.22 - 15:32:59 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:06 SUCCESS.
04.08.22 - 15:33:12 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:18 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:24 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:30 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:36 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:42 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:48 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:33:54 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:34:00 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:34:06 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:34:19 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."
04.08.22 - 15:34:25 "code": "QuotaExceeded",      "message": "You exceeded your quota for the requested resource."

Also in the response there is no quota information available.

Here is a request id of a previous try with the same QuotaExceeded responses:

Date of request: Thu, 04 Aug 2022 14:46:51 GMT
x-amzn-RequestId: 6ffd28a6-2055-4663-9a5b-55ba9295c353

Anyone else having this problems?

Thanks

**Comment by jamesyanyuk** [comment]
@cgaugel were you ever able to resolve this? We're experiencing the exact same issue with the getListingsItem call. The documentation states a rate limit of 5 requests/second. We're lucky if we can consistently call this once every 20 seconds. We run into throttling on the first call even after not calling this operation for hours for a particular seller ID.
