### ISSUE TITLE
[BUG]FEEDS About POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO

### ISSUE THREAD

**Issue by AisxLee** [amzn/selling-partner-api-docs#2485]
I have some questions about SP API uploading carton information:
1. Does the box size have to be uploaded? If you don't upload the box size (POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO), but only upload the contents of the box (POST_FBA_INBOUND_CARTON_CONTENTS), will Amazon charge extra because it doesn't have the box size?
2. POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO is uploading still "workflow for submitting a feed"?
3. I use "Feeds API v2020-09-04",
When calling the "createFeedDocument" interface, the corresponding "contentType" value is "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=UTF-8".
When calling the "createFeed" interface, the corresponding "feedType" value is "POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO".
However, the information returned by calling the "getFeedDocument" interface is "The file format is invalid. The Excel pack list should be uploaded as a .xlsx file."
I tried. Windows creates a new xlsx, generates xlsx with PHP, "contentType" is replaced by "application/vnd.ms-excel; charset=UTF-8", blank excel, etc., but the information returned by "getFeedDocument" remains unchanged...

I'm almost depressed!

**Comment by johnkw** [comment]
Anything involving Excel sounds like an absolute nightmare. We use `POST_FBA_INBOUND_CARTON_CONTENTS` which is XML (not good), but better than Excel. There is no box sizing on there. FBA has never asked. The SKU/ASIN has box sizing though, so I assume FBA could make use of that knowledge if they wanted to for some reason.

**Comment by johnkw** [comment]
See also bug #881 which would replace the hideous XML with just a normal REST post.

**Comment by AisxLee** [comment]
@johnkw  I have seen this issue, but I have not been helped. I use the request in the SDK, but the SDK is uploaded after encrypting xlsx into a string, and the type is still “application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;”.
Is it possible that xlsx must be encrypted for uploading? However, if encryption is not required to upload the "payload" returned by "createFeedDocument", is it unnecessary

**Comment by johnkw** [comment]
Like I said don't use it. Use the one I mention above instead. And don't use the extra encryption layer garbage - use the new feed that removed that pointless cruft.

**Comment by AisxLee** [comment]
I tried. If it is not encrypted, calling "getFeed" returns "processingStatus=FATAL"

**Comment by johnkw** [comment]
Well make sure you're using /feeds/2021-06-30/feeds/

**Comment by AisxLee** [comment]
I have tried both `/feeds/2021-06-30/feeds/` and `/feeds/2021-06-30/feeds/`, but they still return an error
 `original-record-number	sku	error-code	error-type	error-message
100001	-	1	Error	The file format is invalid. The Excel pack list should be uploaded as a .xlsx file. ()`

**Comment by bjpierre** [comment]
The feed you are talking about isn't even mentioned in the feeds API docs anymore as far as I can tell. Like Johnkw mentioned, it would be better to migrate away from your feed and onto POST_FBA_INBOUND_CARTON_CONTENTS which is an XML based feed not an Excel based feed. This is what my implementation uses. As long as you follow the steps in the docs (create document, upload to that doc with the given url, and then create the feed based on that) then you shouldn't have to mess with an extra encryption layer.

**Comment by duomi** [comment]
> Anything involving Excel sounds like an absolute nightmare. We use `POST_FBA_INBOUND_CARTON_CONTENTS` which is XML (not good), but better than Excel. There is no box sizing on there. FBA has never asked. The SKU/ASIN has box sizing though, so I assume FBA could make use of that knowledge if they wanted to for some reason.

![image](https://user-images.githubusercontent.com/18242618/187014991-9d12b001-529b-40a0-b457-180abae1f99f.png)
Amazon help documentation says box and weight information is required.

**Comment by johnkw** [comment]
I should clarify that it's possible that weight thing becomes important if you put more than one SKU into a box.  We only stack SKUs on the pallets.  There is never any extra "box" other than the SKU itself in a box.
