### ISSUE TITLE
Issue with getListingOffers

### ISSUE THREAD

**Issue by emilianmanolache** [amzn/selling-partner-api-docs#2487]
Hi,

There is a serious issue with the getListingOffers endpoint.
It returns wrong data.

Here is an example ASIN: B07H516N9Q
The getListingOffers API endpoint returns these offers:
#1 Seller A2M1DK69L6WDGN, Price 19.95 USD, Not Prime, Not BuyBox Winner
#2 Seller A2M1DK69L6WDGN, Price 19.95 USD, Prime, Not BuyBox Winner
#3 Seller A2M1DK69L6WDGN, Price 19.95 USD, Not Prime, Not BuyBox Winner
#4 Seller A2WFHSQKIDF365, Price 21.79 USD, Not Prime, Not BuyBox Winner
#5 Seller A2WFHSQKIDF365, Price 21.89 USD, Prime, Not BuyBox Winner
#6 Seller A1FOHY84DQ48, Price 21.95 USD, Prime, Not BuyBox Winner
#7 Seller A2FQQGLEBZFB7A, Price 22.02 USD, Prime, BuyBox Winner
#8 Seller A1MUP1YMA0UJ0D, Price 24.95 USD, Not Prime, Not BuyBox Winner

So the API reports #7 as the BuyBox winner.

However, the Amazon store page shows #2 as the BuyBox winner:
https://www.amazon.com/dp/B07H516N9Q

This is really critical for our application.

Please advise.
Thank you!

**Comment by isarzhan** [comment]
BuyBox Winner in different regions is different, if you set different zip code you will get varied sellers.

**Comment by emilianmanolache** [comment]
This is not the case. I've tried multiple zip codes from different regions (NY, LA, Florida, Seattle), and the store shows the same BuyBox.

**Comment by emilianmanolache** [comment]
Please help as this is a really urgent issue affecting our business every hour we can't get this to work.
Does Amazon monitor these issues?

**Comment by emilianmanolache** [comment]
Same issue is reported here:
https://github.com/amzn/selling-partner-api-docs/issues/1830

**Comment by LindaNC** [comment]
Hello @{[emilianmanolache](https://github.com/emilianmanolache)},

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda 
Selling Partner API Developer Support
