### ISSUE TITLE
Send post_product_data new asins to multiple Merchants

### ISSUE THREAD

**Issue by Kernel1453** [amzn/selling-partner-api-docs#2488]
Hello,
I use POST_PRODUCT_DATA when creating asin and I can add as many products as I want for a store. But I can only use 1 merchantId in Header and I have to send xml repeatedly for each store and this process takes too long. How can I send the products of more than one store in the same XML for different merchants in the same region? Is this possible, if possible how can we do it?

i sent this xml while creating ASIN in one store.

                            <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
                              <Header>
                                <DocumentVersion>1.01</DocumentVersion>
                                <MerchantIdentifier>MY_MERCHANT_ID</MerchantIdentifier>
                              </Header>
                            <MessageType>Product </MessageType>
                            ' . $messages . '
                            </AmazonEnvelope>
$messages .= "
" . $message_id . "
Update

" . $product["sku"] . "

ASIN
" . $product["asin"] . "

**Comment by chapmanjw** [comment]
All listings submissions (whether using the Feeds API or the Listings APIs) are scoped to the account you are accessing the API on-behalf of. There are no listings tools that enable a single submission to affect multiple seller accounts.
