### ISSUE TITLE
API orders/v0/orders/{orderId}/buyerInfo  No Buyer Information

### ISSUE THREAD

**Issue by MrYing** [amzn/selling-partner-api-docs#249]
I call the interface orders `orders/v0/orders/{orderId}/buyerInfo` as described in the document
The structure of the returned value obtained is as follows：
`{"payload":{"AmazonOrderId":" xxxxxxxx","BuyerEmail":"xxxxxxxxx@marketplace.amazon.co.uk"}}`

I cannot get the buyer information in the API interface response value described in the official document. Can you tell if this is due to a permission problem or other reasons. If it is a permission problem, please describe what should I do?

**Comment by ShivikaK** [comment]
Hello @MrYing 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
