### ISSUE TITLE
[BUG] searchCatalogItems 2022-04-01 - Request several SKUs with commas

### ISSUE THREAD

**Issue by ulandj** [amzn/selling-partner-api-docs#2490]
When I request catalog items using SKUs via `searchCatalogItems` endpoint, it doesn't return items which SKUs contain commas. The same issue was discussed here - https://github.com/amzn/selling-partner-api-docs/issues/2295#issuecomment-1157924238

params to request:
```
identifiers=["square,4pcd,marble,", "ABC"]
identifiersType=SKU
```

in the url it look like this:
`?identifiers=square%2C4pcd%2Cmarble%2C%2CABC&identifiersType=SKU&`

I tried to escape values which are contain commas and make request with query params:
`?identifiers=square%252C4pcd%252Cmarble%252C%2CABC&identifiersType=SKU&`

Request headers:
```
x-amz-date: 20220808T131156Z
x-amzn-requestid: 62e0ae74-a2dc-4329-afd3-da50b002bbcb
```

But both of requests return item with SKU=`ABC` only. 
Do we still need to request an item where SKU with commas individually(one at a time)? Is there an ETA for solution?
Thanks

**Comment by ulandj** [comment]
cc @chapmanjw

**Comment by KyleJune** [comment]
I've encountered this same issue. The documentation says comma delimited but there doesn't appear to be a way to escape commas in SKU values, it always uses them as a separator. In the schema column here it says array(csv) but if I try putting quotes around any SKU it will just result in it not finding a match. This causes requests to fail for me when I try requesting 20 SKUs at a time due to it thinking I'm trying to request more than 20 skus.

![image](https://user-images.githubusercontent.com/3241653/184452338-172a2400-c2e5-4201-bf42-bf03f3e42dbf.png)

**Comment by chapmanjw** [comment]
@ulandj and @KyleJune This is a known issue that we are currently blocked on resolving (I don't have an ETA for addressing this issue permanently). Essentially, what should happen is that the commas contained within the SKUs are encoded but the list separator remains a literal comma. The issue we are facing is that all commas (whether encoded or literal) are received as encoded in our backend systems.

In the meantime, we have a workaround that allows for a single SKU to be retrieved that contains commas. Essentially, when we received the encoded commas, we lookup the whole string as a single SKU as well as each comma separated string. Using the example from the original question (`"square,4pcd,marble,", "ABC"`), we receive `square%2C4pcd%2Cmarble%2CABC` in our backend. In this less than ideal workaround, we take that and lookup the following SKUs: `square,4pcd,marble,ABC`, `square`, `4pcd`, `marble`, and `ABC`, returning the ASINs for whatever ones we actually find. 

From your end, if you detect a SKU that contains a comma, we suggest calling the `searchCatalogItems` operation one SKU at a time. And provide multiple SKUs per request only when no commas are present. 

Note: If you request the `identifiers` section when making your request, we include the SKU in the identifiers section. This enables you to confirm the SKU we found and looked up the ASIN data by.

**Comment by kennedyjustin** [comment]
We have the same issue with `getPricing`, `getCompetitivePricing`. Can you confirm the same fix works for these APIs as well?

**Comment by KyleJune** [comment]
@chapmanjw Any updates on this issue? We have found some companies have a lot of SKUs that contain commas in them, so the workaround of making a single request for each SKU results in us having to make 20x as many requests to get their whole catalog of items, which they have thousands of.

Maybe one workaround could be to pass multiple identifiers. For example, if I have 2 skus, maybe you could support requesting them by passing identifiers twice. In JavaScript, the URLSearchParams object has a way to get them all.

```js
new URLSearchParams("identifiers=a,b,c&identifiers=d,e,f").getAll("identifiers")
// returns ["a,b,c", "d,e,f"]
```

Another option would be to use csv encoding like the API documentation suggests. In CSV you can escape values like commas and double quotes. That was what I first tried when I encountered this issue previously.

**Comment by chapmanjw** [comment]
@KyleJune Using expanded parameters is one of the avenues we are exploring. Using proper CSV encoding is our preference, but both the literal and encoded commas are all getting replaced with encoded commas by the time it reaches the systems that handle the requests. 

The most I can offer at this time is that this particular issue (the comma-encoding) is an extremely complicated problem for us to address (I really wish it was a simple fix). Until we do, the single-item lookups is our only viable workaround.

**Comment by kennedyjustin** [comment]
@chapmanjw would you be able to comment on the status of `getPricing` and `getCompetitivePricing`?

**Comment by rugved1991** [comment]
Hi,

This is a known issue and it is important to make sure you are encoding the SKU before sending in the request. Please refer to this documentation for more information on URL encoding: https://developer-docs.amazon.com/sp-api/docs/url-encoding

If you are still seeing the same issue after URL encoding, please open a developer support case using the below link: https://developer.amazonservices.com/support

I hope this helps.
Have a great day!

Best,
Rugved
Solutions Architect, SP API

**Comment by nejimz** [comment]
Hello,

I have the same problem like this but the identifiers type is SKU.
Can you help me on this?

Endpoint: `/catalog/2022-04-01/items`
Operation: `searchCatalogItems`

Request ID: `1b5f4ed8-1896-43ea-b193-109e0b45694f`
Run Datetime: `2023-10-05 00:12:17`

Params:
```
[
 "marketplaceIds" => "XXXXXXXX"
  "identifiers" => "sku_1"
  "identifiersType" => "SKU"
  "includedData" => "identifiers,attributes,images,productTypes,salesRanks,summaries"
  "sellerId" => "xxxxx"
  "pageSize" => 20
]
```

Errors:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```
