### ISSUE TITLE
PUT https://sellingpartnerapi-na.amazon.com/listings/2020-09-01/items/SellerId/SKU000012?marketplaceIds=ATVPDKIKX0DER

### ISSUE THREAD

**Issue by gbconstacloud** [amzn/selling-partner-api-docs#2496]
I am getting this error in putListingsItem api for LUGGAGE productType

Request :

`{
    "productType": "LUGGAGE",
    "requirements": "LISTING",
    "attributes": {
        "condition_type": [
            {
                "value": "new_new",
                "marketplaceIds": "ATVPDKIKX0DER"
            }
        ],
        "item_name": [
            {
                "value": "My Basics 16 inch Underseat Spinner Carry-On",
                "language_tag": "en_US",
                "marketplace_id": "ATVPDKIKX0DER",
                "model_name": "test"
            }
        ],
        "brand": [
            {
                "value": "not_applicable"
            }
        ],
        "model_name": [
            {
                "value": "not_applicable"
            }
        ],
        "merchant_suggested_asin": [
            {
                "value": "B0937LGVY7"
            }
        ],
        "supplier_declared_dg_hz_regulation": [
            {
                "value": "not_applicable"
            }
        ],
        "batteries_required": [
            {
                "value": false
            }
        ],
        "material": [
            {
                "value": "not_applicable"
            }
        ],
        "style": [
            {
                "value": "Samsung_12"
            }
        ],
        "bullet_point": [
            {
                "value": "not_applicable"
            }
        ],
        "model_number": [
            {
                "value": "not_applicable"
            }
        ],
        "item_type_keyword": [
            {
                "value": "not_applicable"
            }
        ],
        "product_description": [
            {
                "value": "not_applicable"
            }
        ],
        "item_type_name": [
            {
                "value": "not_applicable"
            }
        ],
        "color": [
            {
                "value": "red"
            }
        ],
        "country_of_origin": [
            {
                "value": "US"
            }
        ],
        "item_package_dimensions": [
            {
                "height": {
                    "unit": "inches",
                    "value": {
                        "title": "Item Package Height",
                        "description": "Provide the package height as a numeric value.",
                        "editable": true,
                        "hidden": false,
                        "examples": [
                            "3"
                        ],
                        "type": "number",
                        "minimum": 0,
                        "maximum": 9878954
                    }
                }
            },
            {
                "length": {
                    "value": 16.50,
                    "unit": "inches"
                }
            },
            {
                "width": {
                    "value": 4.20,
                    "unit": "inches"
                }
            }
        ],
        "department": [
            {
                "value": "US"
            }
        ],
        "supplier_declared_material_regulation": [
            {
                "value": "not_applicable"
            }
        ],
        "item_package_weight": [
            {
                "value": "4",
                "unit": "kilograms"
            }
        ]
    }
}
`

Response 

`{
    "sku": "SKUABV789654",
    "status": "INVALID",
    "submissionId": "2aa4950e8f9a4b1e8f71dbf126d0a95a",
    "issues": [
        {
            "code": "99022",
            "message": "Required value missing for field width.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        },
        {
            "code": "99022",
            "message": "Required value missing for field height.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        },
        {
            "code": "99022",
            "message": "Required value missing for field length.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        },
        {
            "code": "90180",
            "message": "The value '{hidden:\"false\",examples:[\"3\"],editable:\"true\",description:\"Provide the package height as a numeric value.\",maximum:\"9878954\",title:\"Item Package Height\",type:\"number\",minimum:\"0\"}' in the field 'height.value' for the attribute 'item_package_dimensions' has the wrong type. The provided type is 'STRUCT' while the expected type is 'DECIMAL'.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        }
    ]
}`

**Comment by chapmanjw** [comment]
@gbconstacloud The payload above is malformed for multiple attributes. My suggestion would be to use the Product Type Definitions API to retrieve the JSON Schema describing the valid format of these attributes. Using the JSON Schema, you are able to validate that your payload meets the requirements *before* submitting to the Listings APIs.

https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide

**Comment by gbconstacloud** [comment]
can you please send me a sample working json for "LUGGAGE" productType ?

**Comment by Twoandfrommike** [comment]
@chapmanjw 

so... how do you use the Product Type Definitions API to get the json structure? 
i mean you does it have  a parameter where you specify what you want to receive?

asking 'cuz i got a big object as a response and was useless to be honest.

thanks
