### ISSUE TITLE
[FEATURE] Amazon Referral Fee Category

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2498]
**Describe the improvement**
Right now it is not documented how an ASIN's fee category can be retrieved from the SP API. Is this just the WebsiteDisplayGroup?

**Description of what the documentation should say**
Somewhere it should be documented what the fee category for an ASIN is, as there are many use cases that could benefit from this.

For example, are the categories here: https://sellercentral.amazon.com/gp/help/external/G200332540?language=en_US, different from https://sellercentral.amazon.com/gp/help/external/GTG4BAWSY39Z98Z3, and are these just the WebsiteDisplayGroups?

**Comment by kennedyjustin** [comment]
Also, for example, if the fee category is included in a report, that could also work!

**Comment by rahulwecp** [comment]
Second this.
Is there any way to get this information?
