### ISSUE TITLE
BUG: getItemOffersBatch 

### ISSUE THREAD

**Issue by VTTodorov** [amzn/selling-partner-api-docs#2502]
Im getting the error `InvalidInput: InvalidInput Duplicate requests submitted.` when calling `getOffersBatch`.
The request works fine with an array with a single request, but adding 2 or more returns error.

Example request:  [https://jsonblob.com/1008720373273083904](https://jsonblob.com/1008720373273083904)

Edit: Removing `ItemCondition` and `ConsumerType` from every object in the `requests` array except the first one resolves the issue. Example: 

` requests": [{
                    "uri": "/products/pricing/v0/items/B01N3TAGLS/offers",
                    "method": "GET",
                    "MarketplaceId": "ATVPDKIKX0DER",
                    "ItemCondition": "New",
                    "CustomerType": "Consumer"
                }, {
                    "uri": "/products/pricing/v0/items/B07B9QFG81/offers",
                    "method": "GET",
                    "MarketplaceId": "ATVPDKIKX0DER",
                }] `

**Comment by gokigoks** [comment]
In my experience, we got this error when we passed a batch containing duplicate ASINs.

**Comment by ahmetsametoglu** [comment]
Hi @VTTodorov, 
Did you find a problem?

**Comment by GJ-JG** [comment]
Hi @VTTodorov , please follow gokigoks's comment and try first. If still get the same error then please re-open the ticket and It will help if you can paste the request and response details too.
