### ISSUE TITLE
[BUG] CarrierName UPS is not supported.

### ISSUE THREAD

**Issue by AshwinPitroda** [amzn/selling-partner-api-docs#2507]
While calling "putTransportDetails" api for FBA non partnered small parcel shipment I am getting  "CarrierName UPS is not supported".

@seanevan @chapmanjw

**Comment by Adrian-T-AMZN** [comment]
Hello @AshwinPitroda,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
