### ISSUE TITLE
Access to the requested resource is denied , "Unauthorized"

### ISSUE THREAD

**Issue by Shanthini828** [amzn/selling-partner-api-docs#251]
@guy734 

In SignedHeaders I don;t see x-amz-access-token that is in the request url.  

Thanks,
Parvathm
Selling Partner Developer Support.

_Originally posted by @parvathm in https://github.com/amzn/selling-partner-api-docs/issues/212#issuecomment-745696852_

**Comment by nodisk8800** [comment]
You must add  x-amz-access-token=accesstoken in request header.
