### ISSUE TITLE
getCompetitivePricing does not return pricing information

### ISSUE THREAD

**Issue by harvetech** [amzn/selling-partner-api-docs#2513]
I have a list of ASINS. I want to get all the offers on a particular ASIN including FBA, FBM, etc. However, when I try with any Asin, I get the success code 200 but there is no pricing information in the response. Below is the response that I get. 

```
{'status': 'Success',
 'ASIN': 'B09SGGPF9Y', 
'Product': {'Identifiers': 
{'MarketplaceASIN': {'MarketplaceId': 'A1PA6795UKMFR9', 'ASIN': 'B09SGGPF9Y'}
```

My client does not currently offer the Asin for which I need pricing data.  Is there any other endpoint that I can query to get this data? I tried getPricing as well but it didn't work. Strange enough getCompetitivePricing would work for the FR marketplace but not for the DE marketplace. 

Any help will be highly appreciated. Thanks.

**Comment by CrionaAm** [comment]
Hello @harvetech, 

Please open a case directly with us in Developer support, including the full requests and responses attached as .txt file attachment. This will allow is to look more specifically into why details were returned for one marketplace and not another, and to help determine the best solution for your needs. 

To open a support case: 

https://developer.amazonservices.com/support


Thank You,
Críona,
Selling Partner API Developer Support
