### ISSUE TITLE
getMyFeesEstimateForASIN does not return FBA Fees

### ISSUE THREAD

**Issue by jignesh-tops** [amzn/selling-partner-api-docs#2516]
Hello

I am using Product Fees API ([getMyFeesEstimateForASIN](https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference#getmyfeesestimateforasin)) to fetch the estimate FBA Fees but it seems not working for some ASINs like B01MCX483K, B08K5Z4VTR etc.

POST /products/fees/v0/items/B08K5Z4VTR/feesEstimate
Body:
![image](https://user-images.githubusercontent.com/110090906/186118639-56bd9f67-b09c-4c34-a419-aca20058e388.png)

Response:
![image](https://user-images.githubusercontent.com/110090906/186118781-7cda7049-654e-44a0-b040-324327d2d86d.png)

**Comment by CrionaAm** [comment]
Hello @{developer},

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
{Insert Name}
Selling Partner API Developer Support

**Comment by Javadebi** [comment]
@jignesh-tops did you find any result?
