### ISSUE TITLE
Hi @guy734,

### ISSUE THREAD

**Issue by guy734** [amzn/selling-partner-api-docs#252]
Hi Shivika

I am trying to work with amazon support for 2 weeks now, with no real answer yet.
I appreciate it if you can escalate it from your side.
The opened case id:  7764065161   

Thanks
Guy 

Hi @guy734, 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support

_Originally posted by @ShivikaK in https://github.com/amzn/selling-partner-api-docs/issues/212#issuecomment-747061600_

**Comment by guy734** [comment]
@ShivikaK

**Comment by ShivikaK** [comment]
Hello @guy734 

We have escalated your case and are working on it. 

Please add all the required information such as request details including request ID and timestamp to the case  7764065161 for further investigation.
