### ISSUE TITLE
TrialShipmentEventList and ShipmentSettleEventList event data is not returned by requesting the listFinancialEventsByOrderId interface

### ISSUE THREAD

**Issue by JasonYe88** [amzn/selling-partner-api-docs#2521]
I am based on transaction data type: TBYB Order Payment. Get the corresponding platform order number and request the listFinancialEventsByOrderId api interface to obtain data. It is found that the data of the two events TrialShipmentEventList and ShipmentSettleEventList are not returned.

**response result**:
Array
(
    [code] => 200
    [info] => Successful
    [data] => Array
        (
            [payload] => Array
                (
                    [FinancialEvents] => Array
                        (
                            [ShipmentEventList] => Array
                                (
                                )

                            [RefundEventList] => Array
                                (
                                )

                            [GuaranteeClaimEventList] => Array
                                (
                                )

                            [ChargebackEventList] => Array
                                (
                                )

                            [PayWithAmazonEventList] => Array
                                (
                                )

                            [ServiceProviderCreditEventList] => Array
                                (
                                )

                            [RetrochargeEventList] => Array
                                (
                                )

                            [RentalTransactionEventList] => Array
                                (
                                )

                            [PerformanceBondRefundEventList] => Array
                                (
                                )

                            [ProductAdsPaymentEventList] => Array
                                (
                                )

                            [ServiceFeeEventList] => Array
                                (
                                )

                            [SellerDealPaymentEventList] => Array
                                (
                                )

                            [DebtRecoveryEventList] => Array
                                (
                                )

                            [LoanServicingEventList] => Array
                                (
                                )

                            [AdjustmentEventList] => Array
                                (
                                )

                            [SAFETReimbursementEventList] => Array
                                (
                                )

                            [SellerReviewEnrollmentPaymentEventList] => Array
                                (
                                )

                            [FBALiquidationEventList] => Array
                                (
                                )

                            [CouponPaymentEventList] => Array
                                (
                                )

                            [ImagingServicesFeeEventList] => Array
                                (
                                )

                            [TaxWithholdingEventList] => Array
                                (
                                )

                            [NetworkComminglingTransactionEventList] => Array
                                (
                                )

                            [AffordabilityExpenseEventList] => Array
                                (
                                )

                            [AffordabilityExpenseReversalEventList] => Array
                                (
                                )

                            [RemovalShipmentAdjustmentEventList] => Array
                                (
                                )

                            [RemovalShipmentEventList] => Array
                                (
                                )

                        )

                )

        )

)

**Comment by CrionaAm** [comment]
Hello @JasonYe88,

I can confirm that it is a bug we are aware of, and a solution is currently being prepared for implementation. We hope to have this resolved quite soon and will update when we have confirmation.

Thank you for flagging,

Críona.
Selling Partner API Developer Support

**Comment by JasonYe88** [comment]
Hello Críona.

Can you tell us your schedule or repair time during the repair, or let us know when the repair is complete, so that I can carry out our work, thank you very much

best wishes you have a nice day
