### ISSUE TITLE
Cannot get TBYB Order Payment type order financial data

### ISSUE THREAD

**Issue by juebanwei** [amzn/selling-partner-api-docs#2522]
Cannot get TBYB Order Payment type order financial data

Interface : https://developer-docs.amazon.com/sp-api/docs/finances-api-reference#listfinancialeventsbyorderid

**Comment by CrionaAm** [comment]
Hello @juebanwei,

I can confirm that it is a bug we are aware of, and a solution is currently being prepared for implementation. We hope to have this resolved quite soon and will update when we have confirmation. 

Thank you for flagging,

Críona. 
Selling Partner API Developer Support

**Comment by juebanwei** [comment]
Hi, has the bug been fixed?

**Comment by daniel-golembo** [comment]
Hi, has the bug been fixed?
