### ISSUE TITLE
Service Fee Event Lists - Not enough informations

### ISSUE THREAD

**Issue by liangwaihong** [amzn/selling-partner-api-docs#2525]
Hi,

I need more response information in Amazon' financial events api.
Its related to ServiceFeeEventList response

           ` "ServiceFeeEventList": [
            {
                "AmazonOrderId": "xl9o50V981",
                "FeeList": [
                    {
                        "FeeType": "FBADisposalFee",
                        "FeeAmount": {
                            "CurrencyCode": "EUR",
                            "CurrencyAmount": -0.28
                        }
                    }
                ]
            },
            {
                "AmazonOrderId": "xl9o50V981",
                "FeeList": [
                    {
                        "FeeType": "FBADisposalFee",
                        "FeeAmount": {
                            "CurrencyCode": "EUR",
                            "CurrencyAmount": -4.48
                        }
                    }
                ]
            }
        ],
As you can see in the screenshot, I need the api to return more useful information, such as posted_date, purchase_date and other date-related information, the information of this interface is very important, because we want to use it to accurately count a certain The cost incurred by a certain site in time, without these statistics, it will become very difficult, I hope to get the help of technical experts

**Comment by mott7** [comment]
This is very important. Please add date related data to the service fee transactions.

**Comment by takeno-dev** [comment]
I think that is the problem too.
I want to get these Date so I am running the process in periods of 1 day each. It is very annoying.

**Comment by ritikacd** [comment]
Hi @liangwaihong
We recommend checking out [Settlement reports ](https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement)to get more information on the date. You can find report attributes here: https://developer-docs.amazon.com/sp-api/docs/settlement-reports-attributes 

Thank you, 

Hello @liangwaihong, 

Thank you for reaching out regarding the date information from Finance APIs for the _ServiceFeeEventList_. 

You can find details regarding this in our [Settlement reports](https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement). Please see here report attributes including information about the dates: https://developer-docs.amazon.com/sp-api/docs/settlement-reports-attributes 
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Ritika Chaudhary
Selling Partner API Developer Support
