### ISSUE TITLE
Feed API, carrier code, case senstive? Purolator vs PUROLATOR

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-docs#2530]
I don't know where is the official doc for supported carrier codes, this is the list I am using

https://help.godatafeed.com/hc/en-us/articles/360000065032-Orders-Amazon-accepted-carrier-code-values

and we are sending this to Amazon

```xml
<FulfillmentData>
<CarrierName>PUROLATOR</CarrierName>
<ShippingMethod>Purolator-PurolatorGround</ShippingMethod>
<ShipperTrackingNumber>xxxxxxxx</ShipperTrackingNumber>
</FulfillmentData>
```

And it resulted in `Other` category, of course lowered the customer's VTR.

So the developers in Amazon is using a `equals` comparison instead of `equalsIgnoreCase`?

**Comment by mianzaid** [comment]
The official doc is in your panel. For the Japanese market the below link is valid.

https://sellercentral.amazon.co.jp/help/hub/reference/641?ref=efph_641_cont_200200040&locale=ja-JP

**Comment by Mike-the-one** [comment]
@mianzaid Thanks, this is the English link
https://sellercentral.amazon.com/help/hub/reference/G641

The list is really old, Amazon never updated it.  It doesn't even have Purolator there.

![image](https://user-images.githubusercontent.com/37592183/188414804-99aa341f-fbb5-48b5-adb2-e51b6de6e91f.png)

**Comment by palytoxin** [comment]
there are all carrierCode in the [amzn-base.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd)
