### ISSUE TITLE
InternalFailure - We encountered an internal error. Please try again. - Attempting to get MWS Hybrid Auth Code

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2537]
This error started around 24 hours ago - all working fine before 

Raised issue with support but getting nowhere as they are just not responding - please help !

{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}

**Comment by nrogers805** [comment]
is there anybody from amazon monitoring these issues ??

**Comment by sungolivia** [comment]
hey @nrogers805 if you are already engaged with our developer support, please continue the conversation there!
