### ISSUE TITLE
[BUG] GetOrderItems API is truncating product name

### ISSUE THREAD

**Issue by ryanjpaul** [amzn/selling-partner-api-docs#2538]
When we call the GetOrderItems API, we get order items returned with their titles truncated to 150 characters.
However, the InventorySummary api is returning products with product names that are **not** truncated.

This is inconsistent behavior, and causing issues on our end.

**Comment by DanielLanger** [comment]
+1 seeing this too

**Comment by sungolivia** [comment]
Hey @ryanjpaul  @DanielLanger  do you have specific examples that can be reproduced if this is still consistently happening?

**Comment by DanielLanger** [comment]
Yes, I can provide this - however, we are a technology partner managing accounts on behalf of customers. What information can I provide that will assist in your debugging that is not customer sensitive data?

**Comment by DanielLanger** [comment]
@sungolivia
