### ISSUE TITLE
Changes to OAuth Login URI not saved

### ISSUE THREAD

**Issue by gokigoks** [amzn/selling-partner-api-docs#2539]
We changed the Oauth Login URI of our App through 'Edit APP'. This was a few weeks back but the changes for this don't seem to be taking effect when I tried it now. I also changed the Oauth Login URI at the same time as the Oauth Redirect URI but only the changes on the latter seem to have worked. 

Has anyone else experienced this?

**Comment by jamesp26** [comment]
We have exactly the same issue. When sellers renew our app in 'manage apps' in seller central it directs to our old setup. Have a support case open but its very slow to get them to understand what the issue is.

**Comment by gokigoks** [comment]
@jamesp26 I raised a ticket with our issue and the support said that I needed to edit the 'App Listing' itself and go through the 3 stages and then save and submit. This re-published the app I believe. I'm hoping it works cause it will take 10 days. 10 days closer to end-of-life for MWS.

**Comment by jamesp26** [comment]
Thanks - have done the same although support were not as helpful. Fingers crossed.

**Comment by gokigoks** [comment]
@jamesp26 our 0Auth login URI has finally been updated.
