### ISSUE TITLE
send-a-product-list-to-amazon-with-sp-api-in-php

### ISSUE THREAD

**Issue by totem80** [amzn/selling-partner-api-docs#2540]
I should automatically send a product list daily to amazon, using the new API with php. The documentation is very extensive, could you give me a simple example and the steps to take? Thank you

**Comment by gokigoks** [comment]
In my opinion, your best bet would be to look for an SP-API library in your language as there is no hand-holding in SPAPI. For PHP, I would suggest trying https://github.com/jlevers/selling-partner-api

**Comment by totem80** [comment]
> In my opinion, your best bet would be to look for an SP-API library in your language as there is no hand-holding in SPAPI. For PHP, I would suggest trying https://github.com/jlevers/selling-partner-api

thanks for the answer, but to use the old mws api what should I do? I didn't quite understand the account issue. Do I need to create a developer profile from seller central, and another account on aws? This is a bit confusing

**Comment by gokigoks** [comment]
@totem80 If you are currently on MWS and are migrating to SPAPI, the topic in this [link](https://developer-docs.amazon.com/sp-api/docs/hybrid-selling-partner-api-applications) is a good place to start

**Comment by totem80** [comment]
> @totem80 If you are currently on MWS and are migrating to SPAPI, the topic in this [link](https://developer-docs.amazon.com/sp-api/docs/hybrid-selling-partner-api-applications) is a good place to start
no, I don't want to use the new API, I want to use the old ones for php. I just don't understand how to go about having a developer profile accepted by amazon. From my client's seller account I would fill out the developer profile form, with my client's data. All right?

**Comment by sungolivia** [comment]
I second @totem80 on the migration though as [MWS is coming to an end eventually.](https://developer-docs.amazon.com/sp-api/page/migration-hub#important-migration-dates-and-information-for-public-developers)

You can start by checking out the SP-API and follow the tutorials to find which methods would suit your scenario the best and for your client as well.

- https://developer-docs.amazon.com/sp-api/docs/amazon-mws-to-sp-api-migration-guide
- https://developer-docs.amazon.com/sp-api/docs/tutorial-convert-a-public-amazon-mws-application-into-a-selling-partner-api-application
- https://developer-docs.amazon.com/sp-api/docs/tutorial-create-a-private-selling-partner-api-application
