### ISSUE TITLE
getItemOffers return wrong data comparing to amazon.com

### ISSUE THREAD

**Issue by fr3shn3ss** [amzn/selling-partner-api-docs#2549]
**API** : https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getitemoffers

**ASIN** : 079451233X

API returns only 1 Used condition offer while [Amazon.com](https://www.amazon.com/dp/079451233X/?aod=1) shows 337 used offers

**API output:** 

[
 {
  "Shipping": {
   "CurrencyCode": "USD",
   "Amount": 0
  },
  "ListingPrice": {
   "CurrencyCode": "USD",
   "Amount": 13.14
  },
  "ShippingTime": {
   "maximumHours": 48,
   "minimumHours": 24,
   "availabilityType": "NOW"
  },
  "SellerFeedbackRating": {
   "FeedbackCount": 59057,
   "SellerPositiveFeedbackRating": 94
  },
  "ShipsFrom": {
   "Country": "US"
  },
  "PrimeInformation": {
   "IsPrime": false,
   "IsNationalPrime": false
  },
  "SubCondition": "very_good",
  "SellerId": "A1NUD6LVRJ5MT7",
  "IsFeaturedMerchant": true,
  "IsBuyBoxWinner": false,
  "IsFulfilledByAmazon": false
 }
]

**Comment by Adrian-T-AMZN** [comment]
Hello @fr3shn3ss,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
