### ISSUE TITLE
[BUG] [429] QuotaExceeded during getItemOffers call

### ISSUE THREAD

**Issue by mlrahman** [amzn/selling-partner-api-docs#2554]
We are having issue of calling the API endpoint **getItemOffers**. Most of the time it's returning us

`string(140) "[429] {
  "errors": [
    {
      "message": "You exceeded your quota for the requested resource.",
     "code": "QuotaExceeded"
    }
  ]
}"`

We have set a pricing algorithm for which we need to call this API endpoint several times in each minute. It was working fine but since last 10 days most of the time it's returning us the above mentioned error.

If there are any solution for that please let us know.

Thanks

**Comment by gokigoks** [comment]
same experience here. It's already very low plus this issue.. Hope they consider increasing the limit for itemOffersBatch. It's very low compared to MWS. 1800 (SPAPI) compared to 36000 (MWS).

**Comment by sungolivia** [comment]
well the limit shouldn't have changed from MWS to SP-API, but if you are experiencing that then I would suggest working with developer support to investigate further!
https://developer.amazonservices.com/support

**Comment by rugved1991** [comment]
Hi @mlrahman and @gokigoks,

You should use getItemOffersBatch operation to call 20 ASINs in a single request. This operation has the same limit compared to MWS. For more information on the using the Pricing Batch operation please refer to our blog [Reducing API Calls with Batch Functionality](https://developer-docs.amazon.com/sp-api-blog/docs/reducing-api-calls-with-batch-functionality#product-pricing-api-batch-operations).

Best,
Rugved
Solutions Architect, SP API

**Comment by AhmedX6** [comment]
@rugved1991 , facing this issue right now on batch item offers.. we agree it's 2 req / sec ?
One req is 10 asins ?

Why quota exceeded when I do this ?

**Comment by AhmedX6** [comment]
Same issue here @ashemez but 0 answer from SP Api Solution Architects.. Since 2 weeks now... So weird.

**Comment by rugved1991** [comment]
Hi @ashemez and @AhmedX6,

Thanks for reaching out. We announced a change a few months back regarding lowering the limit for getItemOffersBatch operation. Please check out this announcement for more information: https://developer-docs.amazon.com/sp-api/changelog/update-starting-july-10th-2023-the-rate-for-the-getitemoffersbatch-operation-within-the-product-pricing-api-will-be-lowered

For future updates and announcements, please subscribe to our [RSS feed](http://developer-docs.amazon.com/sp-api/changelog.rss). 

Best,
Rugved
Solutions Architect, SP API
