### ISSUE TITLE
[BUG] ANY_OFFER_CHANGED notifications missing frequently

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2555]
**Describe the bug**

Ever since migrating to the new SP API, we are receiving less ANY_OFFER_CHANGED notifications. I haven't been able to pinpoint this exactly, but whenever we submit price updates for listings via Feeds (POST_PRODUCT_PRICING_DATA), we occasionally do not receive corresponding offer changes for these updates. This results in us continuously submitting feeds for the same listing (maybe 5 or 6 feeds in a row), until we finally receive an offer change displaying our desired price.

I have confirmed that this occurs for listings *in* the top 20 offers *and* with fulfillable inventory.

I have also seen this happen on listings where Amazon.com has the buy box (but it is not limited to this scenario).

The result of this, is that when this scenario happens, we cannot compete as well on a listing, which is worse for Amazon sellers and Amazon customers.

**Comment by AJ-AUS** [comment]
@kennedyjustin We too are seeing the same issue, did you get a response from developer support for this?
