### ISSUE TITLE
[FEATURE] enable downloading for product catalog like the one shown in vendor central console

### ISSUE THREAD

**Issue by hongfei-zhou** [amzn/selling-partner-api-docs#2558]
We are trying to download the `Product Catalog` report through the API but couldn't find an appropriate way. The existing catalog item API requires ASINs and only 20 ASINs at a time. It would be best if we can download all Product Catalog for the authorized account.

**Comment by wolendranh** [comment]
Hi! I am also looking for same functionality. It is possible to download `Vendor Catalog` from Dashboard. And there is similar API - Catalog API. But Catalog api requires to provide Identifiers like ASIN, ISBN etc. Is there a way to just query "all vendor catalog" trough api?

@chapmanjw maybe you can help?
