### ISSUE TITLE
Access to the requested resource is denied , "Unauthorized"

### ISSUE THREAD

**Issue by avaneshrajput** [amzn/selling-partner-api-docs#256]
Hi I am getting this error on /orders/v0/orders.

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by yusufdonmez** [comment]
here is the document that explains which roles do you need to activate to get the resources:
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md

I think **Direct-to-Consumer Shipping (Restricted)** role you need to activate.

**Comment by avaneshrajput** [comment]
@yusufdonmez 
thanks for the update, but the issue is resolved.

**Comment by codernice** [comment]
I have same problem,how did you solve it

**Comment by codernice** [comment]
> 
> 
> Hi I am getting this error on /orders/v0/orders.
> 
> {
> "errors": [
> {
> "message": "Access to requested resource is denied.",
> "code": "Unauthorized",
> "details": ""
> }
> ]
> }

I have same problem,how did you solve it
