### ISSUE TITLE
Restricted API Approval Pending

### ISSUE THREAD

**Issue by mahesh-pawar** [amzn/selling-partner-api-docs#2564]
Hi @jchavest13

SP-API Developer Profile Update: Restricted Access Request
ID 7972315282

We are experiencing a problem with regards to getting access to the
Direct-to-Consumer Delivery(Restricted) API. Any help to get approved and access to the SP-API

It would be great if anyone can help with this approval.

**Comment by sungolivia** [comment]
Unfortunately, with regards to getting access to restricted APIs, you would need to continue to conversation in the case you have opened. However, if there is an outage or bug with any of the SP-API, this is the right place to do so!
