### ISSUE TITLE
[BUG] GET_ORDER_REPORT_DATA_SHIPPING No requested record is seen in the Amazon System

### ISSUE THREAD

**Issue by AllenHongjun** [amzn/selling-partner-api-docs#2565]
**Describe the bug**
GET_ORDER_REPORT_DATA_SHIPPING No requested record is seen in the Amazon System  The old interface using mws is visible. Does anyone know what is

ServiceUrl:https://sellingpartnerapi-na.amazon.com
marketplaceId: ATVPDKIKX0DER
RequestID. 309616019254

POST /reports/2020-09-04/reports

GET /reports/2020-09-04/documents/{reportDocumentId}

Body of request:
```json
[{"Name":"application/json","Value":"{\"reportOptions\":null,\"reportType\":\"GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING\",\"dataStartTime\":\"2022-09-18T10:52:49.975Z\",\"dataEndTime\":\"2022-09-19T10:52:49.975Z\",\"marketplaceIds\":[\"ATVPDKIKX0DER\"]}","Type":4,"DataFormat":2,"ContentType":""},{"Name":"X-Amz-Date","Value":"20220919T025305Z","Type":3,"DataFormat":2,"ContentType":""},{"Name":"host","Value":"sellingpartnerapi-na.amazon.com","Type":3,"DataFormat":2,"ContentType":""},{"Name":"Authorization","Value":"AWS4-HMAC-SHA256 Credential=AKIAUFAB***MZHXYWEGQ/20220919/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date, Signature=b355db1ddb577ffb283d3ba3b1*****3de17f3d53db94444e3d6e9b","Type":3,"DataFormat":2,"ContentType":""},{"Name":"x-amz-access-token","Value":"Atza|IwEBIOXiV6PZLSGfExcah7qJ-0rooA***Y2LMbGL7XSkDOsjfI6-Rud6FEEOU842CZTU7saraL1Yl5GGM86f5FWT3J9-yZPWfkkNHAnjdiVsCSqaUJnhjuy3OYj****zH19hT1iP5t9s8K7ZWjCfus2urjfeSnFCsFvnUoxDMe-tlhsnK4X8fKjGRtC2-yepW2r0rCsdzisdA3fJESt8SiaEYrjQwwMg","Type":3,"DataFormat":2,"ContentType":""}]

```

**Screenshots**
I need to find the application record in the report record, but I could not find it
![image](https://user-images.githubusercontent.com/20527121/190956896-6b659364-36ff-4df3-8d76-8b5f2315cab3.png)

**Comment by rugved1991** [comment]
Hi @AllenHongjun,

Please open a support case using the link below for further investigation:
https://developer.amazonservices.com/support
Please include complete request response along with request IDs in the support case. The developer support team will be able to investigate the issue further.

Best,
Rugved
Solutions Architect, SP API

**Comment by RestOp** [comment]
> **Describe the bug** GET_ORDER_REPORT_DATA_SHIPPING No requested record is seen in the Amazon System The old interface using mws is visible. Does anyone know what is
> 
> ServiceUrl:https://sellingpartnerapi-na.amazon.com marketplaceId: ATVPDKIKX0DER RequestID. 309616019254
> 
> POST /reports/2020-09-04/reports
> 
> GET /reports/2020-09-04/documents/{reportDocumentId}
> 
> Body of request:
> 
> ```json
> [{"Name":"application/json","Value":"{\"reportOptions\":null,\"reportType\":\"GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING\",\"dataStartTime\":\"2022-09-18T10:52:49.975Z\",\"dataEndTime\":\"2022-09-19T10:52:49.975Z\",\"marketplaceIds\":[\"ATVPDKIKX0DER\"]}","Type":4,"DataFormat":2,"ContentType":""},{"Name":"X-Amz-Date","Value":"20220919T025305Z","Type":3,"DataFormat":2,"ContentType":""},{"Name":"host","Value":"sellingpartnerapi-na.amazon.com","Type":3,"DataFormat":2,"ContentType":""},{"Name":"Authorization","Value":"AWS4-HMAC-SHA256 Credential=AKIAUFAB***MZHXYWEGQ/20220919/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date, Signature=b355db1ddb577ffb283d3ba3b1*****3de17f3d53db94444e3d6e9b","Type":3,"DataFormat":2,"ContentType":""},{"Name":"x-amz-access-token","Value":"Atza|IwEBIOXiV6PZLSGfExcah7qJ-0rooA***Y2LMbGL7XSkDOsjfI6-Rud6FEEOU842CZTU7saraL1Yl5GGM86f5FWT3J9-yZPWfkkNHAnjdiVsCSqaUJnhjuy3OYj****zH19hT1iP5t9s8K7ZWjCfus2urjfeSnFCsFvnUoxDMe-tlhsnK4X8fKjGRtC2-yepW2r0rCsdzisdA3fJESt8SiaEYrjQwwMg","Type":3,"DataFormat":2,"ContentType":""}]
> ```
> 
> **Screenshots** I need to find the application record in the report record, but I could not find it ![image](https://user-images.githubusercontent.com/20527121/190956896-6b659364-36ff-4df3-8d76-8b5f2315cab3.png)

Hello,

have you solved it?

Thanks!
