### ISSUE TITLE
Recently updated FBA Fee

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#2566]
Hello, I'm using `GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA` report to get my FBA fee but it is giving me old FBA fee. Do you guys have any newer update?

**Comment by rugved1991** [comment]
Hi @Javadebi,

If you are seeing incorrect data in the report, please open a support case with examples. The support team will investigate the issue further.

Best,
Rugved
Solutions Architect, SP API
