### ISSUE TITLE
Add Shipped Orders

### ISSUE THREAD

**Issue by ThalesGama** [amzn/selling-partner-api-docs#2569]
Please,

I'm consuming the orders through the https://sellingpartnerapi-na.amazon.com/orders/v0/orders API, and I would like to mark it as Shipped, and add the TrackingID.

I'm not finding it in the API References

The order is delivered by our company, so I just need to mark that it was shipped with your TrackingID.

Below is an example of an order with the information manually aggregated.

![image](https://user-images.githubusercontent.com/109821991/191078259-928b8248-d16e-492f-8d7c-22f4891bdebe.png)

**Comment by rugved1991** [comment]
Hi @ThalesGama,

You can use the Feeds API to update the order and let Amazon know that the Order has been shipped. You can use the Order Fulfillment Feed or Flat File Order Fulfillment Feed (POST_ORDER_FULFILLMENT_DATA or POST_FLAT_FILE_FULFILLMENT_DATA) for this purpose. Please check the Order Feeds section here: https://developer-docs.amazon.com/sp-api/docs/feed-type-values#order-feeds

Best,
Rugved
Solutions Architect, SP API
