### ISSUE TITLE
[BUG] No Relationships object in new listCatalogItems

### ISSUE THREAD

**Issue by andrija29** [amzn/selling-partner-api-docs#257]
Greetings,

In the MWS API there is GetMatchingProduct endpoint which in the response contains Relationship object that contained parent info (ASIN and marketplace).

In the SP-API there is no endpoint that returns us parent info. I don't have a clue how to connect related products without that. I think that it might be a bug that you don't return that info anymore, since it is usually critical.

Can you please take a look and say if it is intentional, and if it's not is there any other way to figure out product parent?

And please, don't tell me to contact your support since you need 2 months to answer a simple question, I gave up from your support.

Sincerely,
Andrija Milojevic

**Comment by sultanshakir** [comment]
@seanevan any update?

**Comment by piotr-lottestyle** [comment]
@ShivikaK can please look into it? After spending lot of time into SP-API we are forced to use outdated MWS API

**Comment by vikingcodes** [comment]
@andrija29  In MWS we have VariationParent element which contains parent ASIN.

![image](https://user-images.githubusercontent.com/976073/107396432-c0f15180-6b23-11eb-84ae-61108c21854c.png)


But when you look at reference document and model

https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#getcatalogitem
https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json

You will not found any "VariationParent" element

See response of getCatalogItem , response does not contains parent ASIN.

`{
  "payload": {
    "Identifiers": {
      "MarketplaceASIN": {
        "MarketplaceId": "ATVPDKIKX0DER",
        "ASIN": "B076TVM2BQ"
      }
    },
    "AttributeSets": [
      {
        "MaterialType": [
          "Cotton"
        ],
        "Brand": "Royal Hotel",
        "Color": "Solid Gray",
        "Label": "Royal Hotel Bedding",
        "ListPrice": {
          "Amount": 155.99,
          "CurrencyCode": "USD"
        },
        "Manufacturer": "Royal Hotel Bedding",
        "PackageDimensions": {
          "Height": {
            "value": 5.7086614115,
            "Units": "inches"
          },
          "Length": {
            "value": 12.6771653414,
            "Units": "inches"
          },
          "Width": {
            "value": 9.2125984158,
            "Units": "inches"
          },
          "Weight": {
            "value": 4.7619848592,
            "Units": "pounds"
          }
        },
        "ProductGroup": "Home",
        "ProductTypeName": "BED_LINEN_SET",
        "Publisher": "Royal Hotel Bedding",
        "Size": "King",
        "SmallImage": {
          "URL": "https://m.media-amazon.com/images/I/31C5taofq2L._SL75_.jpg",
          "Height": {
            "Units": "pixels",
            "value": 75
          },
          "Width": {
            "Units": "pixels",
            "value": 75
          }
        },
        "Studio": "Royal Hotel Bedding",
        "Title": "Royal's Solid Gray 1000-Thread-Count 4pc King Bed Sheet Set 100-Percent Cotton, Sateen Solid, Deep Pocket"
      }
    ],
    "SalesRankings": [
      {
        "ProductCategoryId": "home_garden_display_on_website",
        "Rank": 196382
      },
      {
        "ProductCategoryId": "3732781",
        "Rank": 826
      }
    ]
  }
}`

I think its bug.

**Comment by bfester** [comment]
+1 We have the exact same problem. Please fix.

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

We have identified this bug and are currently working on getting it resolved.

We will let you know once the issue has been fixed.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by tabertantrum** [comment]
@ShivikaK just checking in for an update on this one since it was identified 3 weeks ago. We are still encountering this issue of blank Relationships object returned from the getCatalogItem operation.

**Comment by ShivikaK** [comment]
Hello everyone,

The issue related to Relationships object not showing up in Catalog API operation has now been resolved.

Please verify the same and let me know if you still see any issues with the response payload.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @tabertantrum,

I have conveyed the issue to our engineering team for further investigation but if you can open a support case with us, it will help us track the issue better. If you do have a case created already, please share the case ID with me.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by tabertantrum** [comment]
@ShivikaK I have created Case ID 8082711641 for tracking this issue. Thanks for your help!

**Comment by estebanangel** [comment]
Hi, I have the exact same issue when I query the catalog items endpoint. Do you know when the fix will be ready?

Thanks

**Comment by ShivikaK** [comment]
Hello everyone,

The issue is still being investigated by our engineering team. I will let you know once we have an ETA on the fix.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by piotr-lottestyle** [comment]
@ShivikaK there is also no "parent" or "child" definition in models https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json and SPI API definition differs from what MWS is returning (relationships)

**Comment by estebanangel** [comment]
Are there any updates on this case? we really don't want to go back to MWS, even more after the time we invested on SP API. Thanks!!

**Comment by tabertantrum** [comment]
@ShivikaK the getCatalogItem response is now returning the Relationships object, but I believe there are still 2 issues. 

1. Missing Parent Element - the MWS specification and response returns the Relationships information within an element for VariationParent or VariationChild depending on the relationship. The SP API is not returning this and the SP API documentation does not indicate whether it should be returned.
2. Incomplete Variation Attribute Data - the response does not include all attribute values comprising the unique VariationTheme. 

For example, ASIN B007B9NXAC (a 12-pack of AmazonBasics AAA batteries) is returning a relationship with B00EZ1ZTFG. The front end of Amazon shows that Parent ASIN B00EZ1ZTFG uses VariationTheme Size and Style, and child ASIN B007B9NXAC is `Size: AAA 12-Pack`, `Style: Batteries`.

However, the response when calling getCatalogItems for Parent ASIN B00EZ1ZTFG only returns the following:
```
{
        "Identifiers":{
          "MarketplaceASIN":{
            "MarketplaceId":"ATVPDKIKX0DER",
            "ASIN":"B007B9NXAC"
          }
        },
        "Size":"AAA 12 Pack"
      },
```

**Comment by ShivikaK** [comment]
Hello @tabertantrum 

Thank you for raising this issue. I will check with our engineering team regarding the miss or if SP API response has been modified.

Please expect an update within this week.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Syntaf** [comment]
> @ShivikaK there is also no "parent" or "child" definition in models https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json and SPI API definition differs from what MWS is returning (relationships)

So... as it stands, is there _any_ way to determine relationships between products within the SP-API?

If a customer wants to import their catalog into my system, I don't currently see a way of determining which products are variants and which products are base items from the [response](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json)

**Comment by andrija29** [comment]
@ShivikaK Since yesterday we are not getting empty relationship object anymore, but now we are getting wrong Parent ASIN, or is it not a parent ASIN?
In Relationship object we are getting Identifiers object that contains MarketplaceID and ASIN, but that ASIN is not the same ASIN as the Parent ASIN on the Amazon shop page? Can you please explain.

**Comment by piotr-lottestyle** [comment]
it looks like Model definition was updated https://github.com/amzn/selling-partner-api-models/commit/cc2f4a2f883633a30aa52364c7b294aa85515e7b#diff-1d2e37196f60a21b5c949a27ca1b461f12521093e19fee8dee57572ba4d0cb9d

**Comment by piotr-lottestyle** [comment]
I hope this will fixed soon,  @ShivikaK we can't fully switch to SP API beacause of this. There is no way to find out which ASIN is Parent and which is Child

**Comment by AshokRaja10** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/1134#issuecomment-891900402 #

**Comment by abuzuhri** [comment]
Still Have same problem , any work around ?

**Comment by huythanhjv05** [comment]
@ShivikaK we dont want to back MWS because of this issue. Please help fix it

**Comment by masterevgeni** [comment]
I  still have same problem , any solution for it? ?

**Comment by piotr-lottestyle** [comment]
> I still have same problem , any solution for it? ?

Only workaround is to treat items with exactly one relationship as child since you can't even manually create listing with exactly one variant

**Comment by masterevgeni** [comment]
@piotr-lottestyle can you explain a little bit more about workaround?

**Comment by piotr-lottestyle** [comment]
@masterevgeni @ulandj 

Amazon SP API returns one entity in "Relationships" if item from getCatalogItem is child, it returns many entities in  "Relationships" if object is parent. So it is possible to detect is item in response a parent or a child

**Comment by panhaoyu** [comment]
Hello, please try listing item api. It may help.

**Comment by discover59** [comment]
@panhaoyu `getListingsItem` doesn't return parent asin.

**Comment by bret306** [comment]
![image](https://user-images.githubusercontent.com/114119756/191634891-b32aaf7b-ff29-4568-b317-bb204330da22.png)
![1663807751008](https://user-images.githubusercontent.com/114119756/191634695-f6ab61c9-c64a-4a0f-901a-926c8bc72493.jpg)
In 2022-04-01, relationships are still empty. Help please . Thanks.

**Comment by andrija29** [comment]
@ShivikaK Do we have any update on this issue? We are still encountering some products that are variations but don't have parent relationship?

**Comment by andrija29** [comment]
Can you @chapmanjw help with this? This is insanity, that we have such unstable functionality for almost 2 years now...

**Comment by robertoxm** [comment]
> @ShivikaK Do we have any update on this issue? We are still encountering some products that are variations but don't have parent relationship?

Was facing same issue. After a couple of hours of trial and error. I found that replacing "relationships" with "variations" worked. You could give it a try and let us know if this fixes it.
