### ISSUE TITLE
Is it really difficulty for Amazon to get the migration survey link right?

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-docs#2572]
Received many emails from Amazon (in the past months) asking for feedbacks about the migration, I always wanted to give my 2 cents, but seems Amazon doesn't want my 2 cents.

None of the links worked.  Email was sent from a no-reply address, so you would not be able to tell them the link isn't working.

Here is the most recent email:

![image](https://user-images.githubusercontent.com/37592183/191254971-9787e932-ec87-472f-bb91-f21ffd529f79.png)

Cool enough looks like they were aware of the issue and got the link fixed.  Here is what I see after I click the link:

![image](https://user-images.githubusercontent.com/37592183/191255437-f51869ee-a962-4e2a-9fcb-2727e8d28c2d.png)

I gave up.

**Comment by cmlkx** [comment]
same.  ^_^

**Comment by Adrian-T-AMZN** [comment]
Hello @Mike-the-one, @cmlkx,

Thanks for your feedback. To make sure we get the feedback from MWS developers, this link is invitation only and we have already received some responses. Could you share 1 of your migration case ID so we can resend the survey link via this case?

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by Adrian-T-AMZN** [comment]
Hello @Mike-the-one, @cmlkx,

We have identified the root cause of this issue and resent the survey link to the impacted developers, the issue is now resolved.

Thank you for bringing this to our attention and allowing us to assist you. 

Adrian T.
Selling Partner API Developer Support

**Comment by Mike-the-one** [comment]
Thanks @Adrian-T-AMZN  for fixing the issue.

Now, do you mind answer this?

https://github.com/amzn/selling-partner-api-docs/issues/1258

Thanks!

**Comment by Mike-the-one** [comment]
Thanks!
On Thu, Sep 22, 2022 at 04:45 PM, Adrian-T-AMZN ***@***.***> wrote:
	Hello @Mike-the-one (https://github.com/Mike-the-one), @cmlkx (https://github.com/cmlkx), 

	Thanks for your feedback. To make sure we get the feedback from MWS developers, this link is invitation only and we have already received some responses. Could you share 1 of your migration case ID so we can resend the survey link via this case? 

	Thanks,
 Adrian T.
 Selling Partner API Developer Support
