### ISSUE TITLE
[BUG] '/fba/inbound/v0/itemsGuidance'

### ISSUE THREAD

**Issue by falfer** [amzn/selling-partner-api-docs#258]
**Describe the bug**
When using the ressource '/fba/inbound/v0/itemsGuidance' with only 'marketplaceId' as a query parameter, an error gets responded: "The requested resource doesn't exist." I can only fetch a result, when I add optional query parameters like 'SellerSKUList'

**Description of what the documentation currently says**
The current documentation says, that only the 'marketplaceid' parameter is required. But using only that does not deliver a proper response.

**Comment by Jethro-Wilkinson** [comment]
Yeah I'm having the same issue with resources '/fba/inbound/v0/itemsGuidance' and '/fba/inbound/v0/prepInstructions'.

I'm trying to access this for European marketplaces. The parameters are all correct and yet I am getting a 404 - Not Found for both.
