### ISSUE TITLE
[BUG] [Vendor Direct Fulfillment Sandbox Test Data API v2021-10-28] [generateOrderScenarios successful but not create any fictional orders]

### ISSUE THREAD

**Issue by huoshidehua** [amzn/selling-partner-api-docs#2584]
## I'm submitting a bug with Vendor Direct Fulfillment Sandbox Test Data API v2021-10-28 

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Vendor Direct Fulfillment Sandbox Test Data API v2021-10-28 ,Operation: generateOrderScenarios,getOrderScenarios

## Expected Behavior

getOrderScenarios should be return a sucecss data,but now it returns "ResourceNotFound" all the time, and when i request generateOrderScenarios api and returns a transactionId successfully ,and then i request the api of [getOrders](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-orders-api-2021-12-28-reference#getorders) use sandbox url after 30-40 min,but it returns a empty  orders all the time,it should be returns list of fictional orders

## Current Behavior

generateOrderScenarios successful
getOrderScenarios should be return a sucecss data,but now it returns "ResourceNotFound" all the time
 [getOrders](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-orders-api-2021-12-28-reference#getorders) should be returns a list of fictional orders,but it always returns empty list

## Your Environment

java8,tomcat

**Comment by huoshidehua** [comment]
@hyandell

**Comment by huoshidehua** [comment]
@ferrants @prashanthseshadri @sellerjd

**Comment by sungolivia** [comment]
hey @huoshidehua can you provide below if you are able to reproduce it consistently?

- transactionId
- requestId
- URL datetime?

**Comment by huoshidehua** [comment]
thanks a lot firstly @sungolivia the information in below

- endpoint
 https://sandbox.sellingpartnerapi-fe.amazon.com

- region
   us-west-2

- transactionId
355b2104-6658-4c8a-a493-628e2cf8c733-20220926014347
- requestId
0e55832f-8bab-4a51-beae-b68f2c4f4fec
- URL datetime
Wed, 28 Sep 2022 01:01:18 GMT

**Comment by huoshidehua** [comment]
pls give some tips ,how to fix it @sungolivia

**Comment by sungolivia** [comment]
You can definitely leverage this [Transactions API ](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-transactions-api-2021-12-28-reference) with the provided transactionId to find the original request's status and the response should show the error why it failed.

Also don't forget to pass your own vendor code and not the one from example sample order from sandbox document!

**Comment by huoshidehua** [comment]
@sungolivia thanks a lot,when i use my vendor code it was working and Transactions API also working but when i request getOrderScenarios api the server always return like below,orders still empty:

```
{
    "transactionStatus": {
        "transactionId": "8582d790-89fd-4eca-9061-5af19951a67b-20221007011040",
        "status": null,
        "testCaseData": {
            "scenarios": [
                {
                    "scenarioId": "",
                    "orders": []
                }
            ]
        }
    }
}
```
and Transactions API return like this:

```
{
    "transactionStatus": {
        "transactionId": "8582d790-89fd-4eca-9061-5af19951a67b-20221007011040",
        "status": "PROCESSING",
        "errors": null
    }
}
```

**Comment by huoshidehua** [comment]
@hyandell @ferrants
