### ISSUE TITLE
How can I remove the main image and other product images once posted?  I am using Feed Type =" POST_FLAT_FILE_LISTINGS_DATA" and trying to post and revise the product. when I pass blank value in "main_image_url" and "other_image_url1 to 8". It does not remove existing images in the product. Please help me by using which API or feed_type, I can remove existing images.[Question] [SP-API] [Question]

### ISSUE THREAD

**Issue by kinjalAP** [amzn/selling-partner-api-docs#2588]
How can I remove the main image and other product images once posted? I am using Feed Type =" POST_FLAT_FILE_LISTINGS_DATA" and trying to post and revise the product. when I pass blank value in "main_image_url" and "other_image_url1 to 8". It does not remove existing images in the product. Please help me by using which API or feed_type, I can remove existing images.

**Comment by sungolivia** [comment]
please fill out the issue template for folks to take a look at!
Otherwise post a question in [Discussions](https://github.com/amzn/selling-partner-api-docs/discussions) tab!

**Comment by sungolivia** [comment]
Closing, feel free to reopen when you have the filled out according to our issue template!
