### ISSUE TITLE
createSubscription returns Unauthorized

### ISSUE THREAD

**Issue by goodiebag45** [amzn/selling-partner-api-docs#259]
I can call createDestination, but when I try to call createSubscription I always get "Access to requested resource is denied."

I followed the guide for notifications to SQS. It looks like there is a new interface for the Simple Queue Service, and instructions are for the old interface, so an update to the guide might be in place.

Anyway, I added the Principal 437568002678 below my ID in the JSON permissions, so I assume it will get full access even though the guide mentions only SendMessage and GetQueueAttributes is needed, but I had no idea how to do that.

Could the access denied be because of queue permissions?

**Comment by ShivikaK** [comment]
Hello @goodiebag45 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @goodiebag45 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @goodiebag45 

As we haven't received any response from you regarding this, I will close this issue.

Please open a support case with us for any errors with your API requests and we can assist you further.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
