### ISSUE TITLE
[BUG] The application upload feed in draft state is unuseful？

### ISSUE THREAD

**Issue by wangjue666** [amzn/selling-partner-api-docs#260]
**Describe the bug**
I uploaded a product feed,  this is response

```
{
  processingEndTime: '2021-01-04T02:58:24+00:00',
  processingStatus: 'DONE',
  marketplaceIds: [ 'A1AM78C64UM0Y8' ],
  feedId: '52952018631',
  feedType: 'POST_PRODUCT_DATA',
  createdTime: '2021-01-04T02:53:49+00:00',
  processingStartTime: '2021-01-04T02:53:56+00:00',
  resultFeedDocumentId: 'amzn1.tortuga.3.ed4f8910-45f9-4447-83f9-08e2ec0a8989.T31THGKBCXWQN4'
}
```
But I can't find the product in my shop！ Is it because the app is in draft state？

**Comment by MrYing** [comment]
hello, Why can't I access the interface / feeds / 2020-09-04 / documents? Can you help me to find out? 
Can you tell me the format of your post request?
`{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`
But there is no problem with my order interface call

**Comment by nodisk8800** [comment]
状态 是done之后，你要下载返回的文件resultFeedDocumentId，解密，读取内容，再判断 是否成功。

**Comment by nodisk8800** [comment]
@MrYing
你上传文档 的问题，可以到我们的Q-Q群里问

**Comment by wangjue666** [comment]
@nodisk8800  是滴 龙哥 上传和创建feed成功，并不意味着feed本身的处理也成功

**Comment by wangjue666** [comment]
@MrYing  加组织详细说说吧 错误是 Unauthorized  一般是身份认证错误

**Comment by nodisk8800** [comment]
一个API，要申请，组织好待上传的文件 , 加密上传，API调用，检查调用状态，下载解密，读取内容，判断是否成功，环环相扣,实在是太复杂了.
差不多电商平台最复杂的了...

**Comment by MrYing** [comment]
@nodisk8800 我调用的接口是feeds/2020-09-04/feeds，然后异常情况是无法认证，post的请求的问题还是权限的问题，订单信息我都掉的通啊。QQ群是多少

**Comment by wangjue666** [comment]
@MrYing  273745406

**Comment by weiliguo15634145** [comment]
我有unauthorized 问题 , 也有上传文档问题 , 我想知道unauthorized 是如何解决的 , 上传产品类目信息是如何解决的

**Comment by wangjue666** [comment]
@weiliguo15634145 上传FEED可以参考这个 #236
