### ISSUE TITLE
[BUG] [SP-API] [SP API - amazon premium a+ content ]

### ISSUE THREAD

**Issue by thirunavukarasan** [amzn/selling-partner-api-docs#2602]
## API missing for the amazon premium A+ content creation.

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by sungolivia** [comment]
hey @thirunavukarasan  can you please follow the template and fill it out as much as you can so someone can take a look?
