### ISSUE TITLE
[BUG] [SP-API] [feed: POST_FBA_INBOUND_CARTON_CONTENTS xml validation issue]

### ISSUE THREAD

**Issue by ayeletblanc** [amzn/selling-partner-api-docs#2608]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
I have a strong feeling that something is broken with the xml validation of the xml feed of type POST_FBA_INBOUND_CARTON_CONTENTS. At the very least, calling [createFeed](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#post-feeds2021-06-30feeds) should return a more indicative error, current errors are impossible to debug.

## Current Behavior
1. I'm following the [use case guide](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide).
2. In step 1, I'm using XML_CONTENT_TYPE = "text/xml; charset=utf-8"
3. In step 3 submitting a feed, with very few data, and according to multiple xml validators it complies with the schema [CartonContentsRequest.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CartonContentsRequest.xsd).
example feed:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CartonContentsRequest>
    <ShipmentId>FBA11AAAAA11</ShipmentId>
    <NumCartons>1</NumCartons>
    <Carton>
        <CartonId>0000000001</CartonId>
        <Item>
            <SKU>MY_SKU</SKU>
            <QuantityShipped>1</QuantityShipped>
            <QuantityInCase>1</QuantityInCase>
        </Item>
    </Carton>
</CartonContentsRequest>
```

4. step 4 - calling [createFeed](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#post-feeds2021-06-30feeds), with the following request:

` {
    "feedType": "POST_FBA_INBOUND_CARTON_CONTENTS",
    "marketplaceIds": [
      "ATVPDKIKX0DER"
    ],
    "inputFeedDocumentId": "amzn1.tortuga.4.na.xxxxxx"
  }`

This is the response:
` 
details: {
    "errors": [
      {
        "code": "InvalidInput",
        "message": "Invalid request parameters",
        "details": ""
      }
    ]
  }
`

I've opened a support issue in seller central, and have so far gathered from the thread:
1. problem is that xml validation fails, not an issue with the seller account or the shipment itself. More specific details were not supplied by the support team.
2. unlike most feeds, CartonContentsRequest should not be constructed with [amzn-envelope](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/amzn-envelope._TTH_.xsd)

So given that the xml is very small in size and complies with the schema according to any validator that I used, I must assume there either:

- there is some issue with the validator used for this type of feed
- something is missing in the documentation and should be added there
- there is some other issue with my process and the support team mistakenly said this is an xml validation issue

## Context/Screenshots
Trying to submit the carton content via feed- this is blocking me from downloading labels for inbound shipments that were created with the [FBA Inbound API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference). 

## Your Environment
using typescript and node.js for the feed.
However I have tried file upload using the [exact java code](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#upload-sample-code-java) in the manual to rule out that something is wrong with the way I'm uploading the file.

**Comment by phsilva** [comment]
@ayeletblanc FYI, I tried this and experienced something different thanwhat support told you. Apparently you do need a regular envelope. I tried without it and got a feed report saying `Missing tag "&lt;Header&gt;" for "&lt;AmazonEnvelope&gt;". (FBA_INBOUND_CARTON_003)`. Adding the message in a regular Amazon envelope solved it.

**Comment by ayeletblanc** [comment]
Using a different seller account, this error did not happen.
So this is definitely a bug in my opinion, the error should not be "Invalid request parameters" but "Invalid seller account" or something other of this sort. And support should be instructed that this error is not because of xml validation!

**Comment by haoxi911** [comment]
This XML format works for me:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
  <Header>
    <DocumentVersion>1.02</DocumentVersion>
    <MerchantIdentifier>XXXXX</MerchantIdentifier>
  </Header>
  <MessageType>CartonContentsRequest</MessageType>
  <Message>
    <MessageID>1</MessageID>
    <CartonContentsRequest>
      <ShipmentId>XXXXX</ShipmentId>
      <NumCartons>1</NumCartons>
      <Carton>
        <CartonId>U000001</CartonId>
        <Item>
          <SKU>XXXXX</SKU>
          <QuantityShipped>6</QuantityShipped>
          <QuantityInCase>6</QuantityInCase>
        </Item>
      </Carton>
    </CartonContentsRequest>
  </Message>
</AmazonEnvelope>
```

**Comment by dlamb22** [comment]
> This XML format works for me:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
>   <Header>
>     <DocumentVersion>1.02</DocumentVersion>
>     <MerchantIdentifier>XXXXX</MerchantIdentifier>
>   </Header>
>   <MessageType>CartonContentsRequest</MessageType>
>   <Message>
>     <MessageID>1</MessageID>
>     <CartonContentsRequest>
>       <ShipmentId>XXXXX</ShipmentId>
>       <NumCartons>1</NumCartons>
>       <Carton>
>         <CartonId>U000001</CartonId>
>         <Item>
>           <SKU>XXXXX</SKU>
>           <QuantityShipped>6</QuantityShipped>
>           <QuantityInCase>6</QuantityInCase>
>         </Item>
>       </Carton>
>     </CartonContentsRequest>
>   </Message>
> </AmazonEnvelope>
> ```

This works for me if I have 1 SKU. What about multiple SKUs? It says it works but does nothing when I check the shipment.
Anyone had any luck?
