### ISSUE TITLE
[DOC REQUEST] [SP-API] Clarify what role is required to GET/POST /notifications/v1/subscriptions

### ISSUE THREAD

**Issue by jlscott3** [amzn/selling-partner-api-docs#2609]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## No roles are documented as granting access to /notifications/v1/subscriptions 

None of the nonrestricted roles documented in the child pages of [Roles in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api) are documented as granting access to `/notifications/v1/subscriptions`. Product Listing, Pricing, Amazon Fulfillment, Buyer Communication, Selling Partner Insights, Finance and Accounting, and Inventory and Order Tracking all grant access to `/notifications/v1/destinations`, but I can't find any mention of subscriptions in any role. We started out with just Brand Analytics assigned to our app, because that grants access to the report we wanted to schedule. We could schedule the report and create a destination with that role, but we could not create a subscription. `POST /notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED` with our destination ID in the payload returned a 403 "Access to requested resource is denied" response.

We added all non-restricted roles to the app and re-generated the refresh token, and that allowed us to create a subscription. However, we'd rather not grant permissions that aren't needed. Can we get a doc update that indicates what role(s) is/are required for subscription creation? 

## Original report
Unclear at this point if this is a documentation issue or a bug, or if I'm just missing something. I'm attempting to call `GET /notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED` using an access token with `grant_type=refresh_token`. I get a 403 "Access to requested resource is denied" response. The same credentials can be used to `GET  /reports/2020-09-04/reports` successfully. 

## Expected Behavior
API endpoint returns a list of subscriptions.

## Current Behavior
`GET /notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED` returns `403  Access to requested resource is denied`.
Using the same credentials, `GET /reports/2020-09-04/reports` with  `reportTypes:=["GET_SALES_AND_TRAFFIC_REPORT"]` succeeds, so I know I have valid credentials.

I understand that the subscriptions endpoint requires `grant_type=refresh_token`, which is how I'm generating the access token.

## Context/Screenshots
This might be a role issue, but I can't find any documentation that describes what role is required to get access to the subscriptions endpoint. Edited to add: we applied all non-restricted roles to the application and we're still getting the 403 error. None of the roles documented in https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api and its child pages mention /notifications/v1/subscriptions.

As stated above, my credentials can be used with `GET  /reports/2020-09-04/reports`.

I also tried `POST /notifications/v1/subscriptions/REPORT_PROCESSING_FINISHED` with a [CreateSubscriptionRequest body](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-reference#createsubscriptionrequest) but that also returned 403 Access to requested resource is denied.

I was able to create a destination using a grantless access token.

**Comment by sungolivia** [comment]
just wondering, which roles do you have approved for and applied to the app config?
Also plugging this in case it helps!
https://developer-docs.amazon.com/sp-api-blog/docs/choosing-roles-for-developer-profile-and-sp-api-app

**Comment by jlscott3** [comment]
> just wondering, which roles do you have approved for and applied to the app config? Also plugging this in case it helps! https://developer-docs.amazon.com/sp-api-blog/docs/choosing-roles-for-developer-profile-and-sp-api-app

We started out with just the Brand Analytics role, but expanded that to all non-restricted roles after we ran into this issue. Specifically: Brand Analytics, Product Listing, Pricing, Amazon Fulfillment, Buyer Communication, Buyer Solicitation, Selling Partner Insights, Finance and Accounting, and Inventory and Order Tracking.

One thing that caught my attention is that I could not find any role that is documented to grant permission to `/notifications/v1/subscriptions` in the child pages of [Roles in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api). Product Listing, Pricing, Amazon Fulfillment, Buyer Communication, Selling Partner Insights, Finance and Accounting, and Inventory and Order Tracking all grant access to `/notifications/v1/destinations`, but I can't find any mention of subscriptions in any role. If that's correct, what do we need to do to authorize access to the subscriptions endpoint?

**Comment by cmlkx** [comment]
@jlscott3  - I have seen some other people say that after they were granted additional roles (more than what they had when the application was Authorized to the seller account), they had to complete the re-auth process again on the individual seller account you are trying to make the call for.  Not sure if you've tried that or not but maybe re-trying the auth would be helpful?

**Comment by jlscott3** [comment]
> @jlscott3 - I have seen some other people say that after they were granted additional roles (more than what the application had when it was initially Authorized to the seller account), they had to re-auth again on the individual seller account to gain access to the new permissions. Not sure if you've tried that or not but maybe canceling and re-doing the auth for the account you are trying to access would be helpful? 🤞 good luck!

@cmlkx That apparently helped, thank you! We re-generated the refresh token (I'm not familiar with the Seller Central console so I'm not sure exactly what happened here) and now we have access to the subscriptions endpoint. That's good, but it does leave the question of exactly what role is required. So I'm updating this to a documentation request - can you clarify exactly which role is required to get access to the subscriptions endpoint?

**Comment by sungolivia** [comment]
have you added a new role to your dev profile and app before getting new auths? I am trying to figure out if it's actually indeed the role issue as it's the first time I have heard of anyone with notification issue.

**Comment by sungolivia** [comment]
@jlscott3  closing for now but feel free to comment and I will definitely look into requesting doc update!
