### ISSUE TITLE
[BUG] [SP-API] [Issue] DeleteSubsciptionById throw error for Far East Region

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#2612]
Hi,

I subscribe a Japan marketplace to ANY_OFFER_CHANGE_NOTIFICATION using the CreateSubscription.
Then I get subscription id and I see the notifications received by sqs.
After that I try to unsubscribe with subscriptionId  using the DeleteSubscriptionById but it throws error "Unauthoried"

I try same steps for North America and Europe region and everything works succesfully.
This error occurs only at Far East regions.

Could you please help me what is the problem and how I can solve that?

Is there anyone who can try that?

Thanks

**Comment by sungolivia** [comment]
not sure which role you have but if you check for the role you are using, you can check if the specific notification is supported.

For example, pricing role mentions that for that specific notification type, it may not be available in FE region.
https://developer-docs.amazon.com/sp-api/docs/pricing-role#feeds-reports-and-notifications

**Comment by hkncnr07** [comment]
Hi thanks for answer,

I can succedfully subscribe to ANY_OFFER_CHANGED_NOTIFICATON but deleteSubscriptionById not working.

**Comment by takeno-dev** [comment]
I am facing the same problem in Japan.
