### ISSUE TITLE
[Set Bug] Documentation

### ISSUE THREAD

**Issue by ditinus** [amzn/selling-partner-api-docs#2615]
**Describe the improvement**
Set country code of the United Kingdom in [Marketplace IDs page](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids#europe:~:text=United%20Kingdom,UK)

**URL of the content on GitHub**
This content is not available on github

**Description of what the documentation currently says**
Currently the documentation stating country code of United Kingdom as UK

**Description of what the documentation should say**
It should state it as GB

**Screenshots**
![Marketplace-IDs](https://user-images.githubusercontent.com/68376831/193990122-631be149-4432-4177-a146-e4aa65e999e8.png)

**Additional context**
**Though it's not a very big issue but it creates the problem for developer.** 

As I wrote code according to this and while testing for getMarketplaceParticipations operation got an error.

**Comment by sungolivia** [comment]
hey @ditinus  thanks for pointing this out, really appreciate it.
Did you know that you can provide this direct feedback to our tech writing team on the website itself that you linked?
Just scroll to the bottom of that page and provide this feedback!
![Screen Shot 2022-10-05 at 11 53 02 AM](https://user-images.githubusercontent.com/7606170/194139409-af457e68-ca97-4c3f-89c0-68631590e6a2.png)
