### ISSUE TITLE
MD9999 error occurred during seller authorization

### ISSUE THREAD

**Issue by rxxy** [amzn/selling-partner-api-docs#262]

**Comment by nodisk8800** [comment]
问题都没有说清楚...
大概率是权限、授权、签名之类的问题

**Comment by rxxy** [comment]
`https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.xxxxxxxxx&state=123456`

抱歉，是在使用以上链接在卖家店铺打开时发生的，打开后显示以下内容。

```
Something went wrong
We are sorry but we encountered an error while processing your request.

Please contact Seller Support and provide them with the following information:

App ID: amzn1.sellerapps.app.xxxxxxxx

Error Code: MD9999
```

但如果我在链接后加入version=beta，就可以正常调出授权页面。我发现有两三个人也遇到同样问题

**Comment by nodisk8800** [comment]
我一直使用 version=beta, 没有测试去掉这个参数的情况.
帮不到你啊

**Comment by nodisk8800** [comment]
你的应用是 草稿 的状态吗?

**Comment by rxxy** [comment]
是发布状态。

**Comment by goodiebag45** [comment]
I get the same response. Any english reason or solution for this ?

**Comment by rxxy** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/149#issuecomment-737314028


mybe having an application published but oAuth URLs in draft state.
