### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by hasancagli** [amzn/selling-partner-api-docs#2621]
## I'm getting an "unauthorized", and "access denied" error in my basic application. 

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

In the tutorials I watched and the official docs I've read, I saw that people are accessing the API after following SP-API docs.

## Current Behavior

But in my script, I'm doing everything the same with the docs, but I'm getting the error I said in the title. You can also see the error down below.

## Context/Screenshots

<img width="594" alt="image" src="https://user-images.githubusercontent.com/53555551/194343564-a85b96d8-9473-43eb-ac2e-ca79becd6db9.png">
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/53555551/194343703-a52052aa-424f-4fdb-84ec-92113d3b5240.png">

**Comment by sungolivia** [comment]
can you link which doc you are referring to? and the tutorial?

**Comment by hasancagli** [comment]
Hi, thanks for your answer! Yesterday, I tried again with a different AWS account and my problem is solved now. I don't really know what caused this problem but it is working after that.
