### ISSUE TITLE
[BUG] [SP-API] [Issue] "We encountered an internal error. Please try again." when calling getListingsProduct 

### ISSUE THREAD

**Issue by huythanhjv05** [amzn/selling-partner-api-docs#2627]
Hi guys.
I'm using getListingsProduct to get Product Info on orders normally. Suddenly , this morning I got a message error response when use it.
Error Response:  "We encountered an internal error. Please try again."

These are my parameters: 
{
	"operation": "getListingsItem",
	"endpoint": "listingsItems",
	"path": {
		"sellerId": "XXXXXXXXXX",
		"sku": "Y9ZYZRJCGN"
	},
	"query": {
		"marketplaceIds": "ATVPDKIKX0DER",
		"issueLocale": "en_US",
		"includedData": "issues,attributes,summaries,offers,fulfillmentAvailability"
	}
}

Could you tell me what happened with the SP-API library?

**Comment by piotr-lottestyle** [comment]
We are affected with this too

**Comment by sungolivia** [comment]
Hey @huythanhjv05 @piotr-lottestyle we have ongoing issue at the moment:
https://github.com/amzn/selling-partner-api-docs/discussions/2626

**Comment by sungolivia** [comment]
if this issue persists, please open again with the issue template filled out, thanks!
