### ISSUE TITLE
[BUG] [SP-API] [Issue] We stopped receiving the majority of ANY_OFFER_CHANGED notifications

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2628]
## I'm submitting a...

<pre><code>[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

ANY_OFFER_CHANGED notifications

## Expected Behavior

We receive ANY_OFFER_CHANGED notifications for subscriptions for our customers.

## Current Behavior

Starting on October 6, 23:00, we stopped receiving ANY_OFFER_CHANGED notifications for many of our customers in NA region. This results in our service not being able to react to competitors price changes.

## Context/Screenshots

<img width="1105" alt="Screen Shot 2022-10-07 at 9 45 43 AM" src="https://user-images.githubusercontent.com/46265478/194568421-990ab8a8-b7f9-4846-8985-b50183e3b9f9.png">

## Your Environment

For context, we recently (within the last two months) migrated our MWS notifications over to SP notifications.

**Comment by KyleJune** [comment]
We have the same issue with the POST_INVENTORY_AVAILABILITY_DATA feed. Amazon support just told us that the time feeds tack to process may vary depending on time of day and how many feeds they have to process. I re-checked a feed from yesterday and it now shows as being done, it took 12 hours and 10 minutes to complete.

It appears the MWS status page now recognize there is an issue even though they dismissed our support ticket and marked it as answered. The below status page was for the old MWS api but it appears they are also using it for the SP-API.

http://status.mws.amazon.com/

> Beginning 10/06/22 at 15:46, Marketplace Web Service APIs were reported to be experiencing an error rate increase. We are currently investigating the issue.

> [20:05 PST] We are seeing impact to multiple Amazon APIs and services since 15:46. We are currently investigating the issue and do not have an ETA for recovery.

**Comment by rugved1991** [comment]
Hi @KyleJune,

Thank you for reaching out.

http://status.mws.amazon.com/

From 15:46 on 10/06/2022 to 09:20 on 10/07/2022, several Amazon Services were experiencing issues. Service is once again operating at normal capacity at 09:20. Please note that this outage caused a Feed backlog, which may take up to 16 hours to clear. There is no need to re-submit feeds sent during the outage period.

@kennedyjustin 
You should be able to receive notifications again. Please reopen this issue if you are still experiencing the same issue.

Best,
Rugved
Solutions Architect, SP API
