### ISSUE TITLE
 [SP-API] [Issue] Unable to get the received quantity of Vendor Purchase Orders

### ISSUE THREAD

**Issue by KZXSF** [amzn/selling-partner-api-docs#2639]
I read the interface documentation of vendor order that it will return the receivingStatus field (https://developer-docs.amazon.com/sp-api/docs/vendor-orders-api-v1-reference#orderitemstatus-receivingstatus), But I looked at all the orders returned by the API and there is no such field. For example, PO:********, the quantity received can be seen in the vendorcentral, but the field cannot be obtained with the API.

**Comment by sungolivia** [comment]
Please fill out the issue template! Otherwise this issue will be closed soon!
