### ISSUE TITLE
How to deal with the empty data obtained by getcatalogitem API?

### ISSUE THREAD

**Issue by WXinFfly** [amzn/selling-partner-api-docs#264]
I want to get the basic information of the product, but when I get the data through the getcatalogitem API, the result is empty. How can I solve this problem?

![image](https://user-images.githubusercontent.com/25562509/103612756-11dbbc00-4f60-11eb-9c8f-82d0bc0de1bf.png)

![image](https://user-images.githubusercontent.com/25562509/103612841-42235a80-4f60-11eb-9d1b-56f8202a0942.png)

**Comment by gaziz86** [comment]
I am experiencing exact same problem. I am actually not even sure why getCatalogItem method even set to return Item class, this class has objects of Order Item and no 'item details for items in the catalog' as is stated in SP-API documentation.

Were you able to resolve/understand the issue? Could anyone check this, I really need to start using SP-API but no luck so far.

**Comment by StoreCreation** [comment]
![question](https://github.com/amzn/selling-partner-api-docs/assets/151637470/eb484b6a-4745-479b-8761-4dea7bd3e3db)
How to solve this to get getSolicitationActionsForOrder
