### ISSUE TITLE
[BUG] [Merchant Fulfillment] [eligibleShippingServices] eu region

### ISSUE THREAD

**Issue by brock-rb2t** [amzn/selling-partner-api-docs#2653]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I'm attempting to use the eligibleShippingServices endpoint to return a list of shipping service offers. I've read issue [#352](https://github.com/amzn/selling-partner-api-docs/issues/352), my request body is nearly identical to other requests that have been shared and stated as being successful. 

Does this service not work in the eu region?

## Context/Screenshots

POST https://sellingpartnerapi-eu.amazon.com/mfn/v0/eligibleShippingServices

Request Body: 
```
{
  "ShipmentRequestDetails": {
    "AmazonOrderId": "202-1374856-1418762",
    "ItemList": [
      {
        "OrderItemId": "31534645441067",
        "Quantity": 1
      }
    ],
    "ShipFromAddress": {
      "Name": "John Doe",
      "AddressLine1": "123 Street Name",
      "City": "City Name",
      "PostalCode": "SL1 4QU",
      "CountryCode": "UK",
      "Email": "test@gmail.com",
      "Phone": "+11231231234"
    },
    "PackageDimensions": {
      "Length": 31.75,
      "Width": 23.24,
      "Height": 8.64,
      "Unit": "centimeters"
    },
    "Weight": {
      "Value": 1540,
      "Unit": "g"
    },
    "ShippingServiceOptions": {
      "DeliveryExperience": "DeliveryConfirmationWithoutSignature",
      "CarrierWillPickUp": true,
      "CarrierWillPickUpOption": "CarrierWillPickUp"
    }
  }
}
```
Response headers: 
```
{
  "Date": "Wed, 19 Oct 2022 19:02:12 GMT",
  "Content-Type": "application/json",
  "Content-Length": "117",
  "Connection": "keep-alive",
  "x-amzn-RequestId": "556c4bf4-9863-4a18-989f-4a184d4d99af",
  "x-amzn-RateLimit-Limit": "5.0",
  "x-amz-apigw-id": "aRB0MFksjoEFUkA=",
  "X-Amzn-Trace-Id": "Root=1-635049b4-165b901e4c84e339188bf5f6"
}
```
Response body: 
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```

**Comment by chrisskhoury** [comment]
Hi @brock-rb2t 

I also saw that the JSON format that you shared does not match the JSON in the documentation we have, you can check [this](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper-docs.amazon.com%2Fsp-api%2Fdocs%2Fmerchant-fulfillment-api-v0-reference%23geteligibleshipmentservicesrequest&data=05%7C01%7CSteffen.Serries%40arvato-scs.com%7Ced4ff4621b10420a8e7708daf23e6f45%7C659c3a90ec904772b772cebe2050a82e%7C0%7C0%7C638088647261225820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ehuzhznayhhK7K%2FRAFJc%2FbAnhY8PjDI8dg0vuwaL3WA%3D&reserved=0) for the Body format that needs to be attached. 

Best,
Chris

**Comment by chrisskhoury** [comment]
resolving, feel free to reopen if issue persists
