### ISSUE TITLE
Sandbox - getting 'Unauthorized' error with Self-Authorized authentication flow.

### ISSUE THREAD

**Issue by RJEspera** [amzn/selling-partner-api-docs#266]
I get "Access to requested resource is denied"  while testing sandbox endpoint. (Unauthorized) error. I followed the instructions from https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox. I used Self Authorization and was able to get a refresh token, then an access token using the refresh token. I was also able to create and sign the request successfully.  I checked my IAM roles and policy, and they've been created according to the instruction.  I also made sure that I used the role arn when I created my test app.

Any idea what else I could be missing?

**Comment by RJEspera** [comment]
I found the solution to it here: https://github.com/amzn/selling-partner-api-docs/issues/24#issuecomment-738901323.

**Comment by weiliguo15634145** [comment]
Have you found the answer , I had the same problem , And I need your help.
