### ISSUE TITLE
I used the Product Feed  was unsuccessful 

### ISSUE THREAD

**Issue by MrYing** [amzn/selling-partner-api-docs#267]
I successfully uploaded the XML to the specified path, and downloaded the related report in the processing status is done status, but the report showed that the header of the XML was missing the tag. I confirmed many times that the header of the XML I uploaded was consistent with the tag. Encryption or other reasons, I have lost myself, who can point out?

uploaded the XML ：
`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.02</DocumentVersion>
        <MerchantIdentifier>XXXXXXX</MerchantIdentifier>
    </Header>
    <MessageType>Product</MessageType>
    <PurgeAndReplace>true</PurgeAndReplace>
    <Message>
        <MessageID>10001</MessageID>
        <OperationType>Update</OperationType>`

downloaded  the XML:
`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>XXXXXX</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>84629018632</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>0</MessagesProcessed>
				<MessagesSuccessful>0</MessagesSuccessful>
				<MessagesWithError>1</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
			<Result>
				<MessageID>0</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>5001</ResultMessageCode>
				<ResultDescription>XML Parsing Fatal Error at Line 1, Column 226: The element type &quot;Header&quot; must be terminated by the matching end-tag &quot;&lt;/Header&gt;&quot;. The element type &quot;Header&quot; must be terminated by the matching end-tag &quot;&lt;/Header&gt;&quot;.</ResultDescription>
			</Result>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>`

**Comment by nodisk8800** [comment]
你这个好像是上传的XML结构有问题

**Comment by MrYing** [comment]
还望指教一下，我格式化了，没有发现啥问题

**Comment by MrYing** [comment]
> 你这个好像是上传的XML结构有问题

还望指教一下，我格式化了，没有发现啥问题

**Comment by ykw090721** [comment]
@nodisk8800 请问你们的QQ群是哪个呢？我想申请一下

**Comment by nodisk8800** [comment]
> 
> 
> @nodisk8800 请问你们的QQ群是哪个呢？我想申请一下

273745406

**Comment by cdragon1116** [comment]
@MrYing May 
I was also trying to update a xml file, may I know what `contentType` you send when you create feedDocuments?
