### ISSUE TITLE
[FEATURE] CreateSubscriptionRequest.payloadVersion should be "required"

### ISSUE THREAD

**Issue by yadex205** [amzn/selling-partner-api-docs#2671]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

This is for a documentation bug.

**Describe the improvement**

The document says `payloadVersion` is *optional* but actually it's *required* by real API.

**URL of the content on GitHub**
https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-reference#createsubscriptionrequest

**Description of what the documentation currently says**
|Name|Description|Schema|
|-|-|-|
|**payloadVersion**<br />*optional*|The version of the payload object to be used in the notification.|string|

**Description of what the documentation should say**
|Name|Description|Schema|
|-|-|-|
|**payloadVersion**<br />*required*|The version of the payload object to be used in the notification.|string|

**Screenshots**
<img width="850" alt="image" src="https://user-images.githubusercontent.com/4597654/197714762-8cad49eb-2248-478c-8bb2-5617cdf372de.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/4597654/197713817-4ae66135-f37c-40b7-a6e4-7c9861101c17.png">

**Additional context**
None.

**Comment by sungolivia** [comment]
Hey @yadex205  did you know that you can provide direct feedback such as this lovely one to our tech writing team?
Follow through the feedback and you can enter your feedback or link this directly too!
<img width="821" alt="Screen Shot 2022-10-25 at 1 45 43 PM" src="https://user-images.githubusercontent.com/7606170/197845158-381736f4-9e33-4103-a896-35a01576cf32.png">
