### ISSUE TITLE
{"error_description":"The request has an invalid grant parameter : refresh_token","error":"invalid_grant"}

### ISSUE THREAD

**Issue by B627336** [amzn/selling-partner-api-docs#268]
Hi, anyone came across this error? When I try to exchange the refresh token for an access token, I get this error message. However, this is only the case when using the refresh token generate with authorization workflow. When I use the refresh token from self-authorization, the access token issuance works fine.

**Comment by nodisk8800** [comment]
Re authorization and get a new refreshtoken.

**Comment by ShivikaK** [comment]
Hello @B627336 

The spapi oauth code which is used to generate the refresh token is a short lived token valid only for 5 minutes. This error indicates that your oauth code has expired. Please keep in mind to immediately exchange the authorization code for a long lived refresh token after you receive the code.

Please let us know if you are still facing issues.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by B627336** [comment]
Hi Shivika, indeed it worked fine as explained above. Thank you, Robert

**Comment by manoj3676** [comment]
I'm getting same error, yes I've tried exchange it quickly less than in a minute but still facing this issue, I'm following [Resource](https://www.npmjs.com/package/amazon-sp-api#exchange-an-authorization-code-for-a-refresh-token). Here I also need to pass creds but in docs there is no requirement.` let sellingPartner = new SellingPartnerAPI({
      region: "eu",
      options: {
        only_grantless_operations: true,
      },
      credentials: aws_spi,
    });
    let res = await sellingPartner.exchange("spapi_oath_code");`
