### ISSUE TITLE
[BUG] [SP-API] [Issue] Regression: POST_PRODUCT_PRICING_DATA Feeds failing silently

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-docs#2681]
## I'm submitting a...

<pre><code>[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

`POST_PRODUCT_PRICING_DATA`
`Feeds` API

## Expected Behavior

I expect that when I receive a `FEED_PROCESSING_FINISHED` notification saying that a feed is `DONE`, and all of the messages (essentially price updates for listings) are accounted for in `messagesAccepted` field of the `resultFeedDocument`, that the price of the listing on Amazon will change.

## Current Behavior

My experience is that often times, after receiving confirmation that the feed is complete (status `DONE` and all messages are accepted), prices are still not updated on Amazon. Sometimes we retry the feed submission multiple times, and Amazon never updates.

When I say Amazon doesn't update, I mean:
1. Amazon.com doesn't show the price we updated the listing to, even after hours.
2. The `getPricing` API doesn't show the new price for the listing.
3. We do not receive an `ANY_OFFER_CHANGED` notification for the listing with our price change.

This essentially saying that `POST_PRODUCT_PRICING_DATA` are failing silently.

I do understand that there are occasions where the SP API falls behind with feed processing (and sometimes there are even larger outages), but this happens 24/7, all day for the sellers that use our SP Application.

This is a lose/lose/lose because:
1. Our own business (an Amazon repricing tool) loses customers to this issue.
2. Our customer's (Amazon sellers) loses business because they can't compete on a listing.
3. Amazon loses as well because the marketplace is not as competitive.

## Context/Screenshots

Tickets have been opened with Seller Central support outlining specific instances (we have many every minute).

The context is that we as a Repricing tool, need to know when we actually have successfully updated a price. If it is not when the feed has been successfully processed with a `DONE` status, and when it says all messages have been accepted, then when is it? Right now we have to check the `getPricing` API manually to verify a price update has actually been processed in Amazon's backend systems, or wait for an `ANY_OFFER_CHANGED` notification confirming our price update. Amazon should either:

1. Fix the issue of dropped price updates, or
2. Provide us a better mechanism to understand when a pricing update has actually gone through successfully

Some testing we plan on doing ourselves is to check the following:
1. Do feeds have some undocumented message limit, where some of our messages aren't getting through (getting chopped off)?
2. Is there some undocumented rate limit for updating listings apart from the feed submission rate limits?
3. Does `JSON_LISTINGS_FEED` also have this issue? Would moving to the `JSON_LISTINGS_FEED` solve this issue?

## Your Environment

We have a hybrid MWS/SP Application. We did not experience this issue when we were using the MWS API, but now this seems to be an issue when we use the SP API for feed submissions.

**Comment by sungolivia** [comment]
hey @kennedyjustin please keep an eye out in our discussion section as we are experiencing issue in feeds delay!
https://github.com/amzn/selling-partner-api-docs/discussions/2689

**Comment by blairanderson** [comment]
i'm having this same issue. 

Feed result shows zero errors. but hours later and sellercentral dashboard still showing old pricing.

**Comment by Kernel1453** [comment]
i'm having this issue now. url content is successful but i cant update item price. What can i do for this issue?
Thank you

**Comment by baltechies** [comment]
I'm having this same issue. 

`<ProcessingSummary>
<MessagesProcessed>1</MessagesProcessed>
<MessagesSuccessful>1</MessagesSuccessful>
<MessagesWithError>0</MessagesWithError>
<MessagesWithWarning>0</MessagesWithWarning>
</ProcessingSummary>`
