### ISSUE TITLE
[BUG] [SP-API] [Issue] Feed upload of type JSON_LISTINGS_FEED returning unexpected error

### ISSUE THREAD

**Issue by sitelicon** [amzn/selling-partner-api-docs#2685]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

We're uploading a listing feed of type **JSON_LISTINGS_FEED**.
When downloading the processed feed, we're getting the following error per every message sent in the feed:

```
{
  messageId: 1,
  code: 'BAD_REQUEST',
  severity: 'ERROR',
  message: "Invalid 'accountId' provided."
}
```

There is no `accountId` attribute or field described in the documentation neither in the `CELLULAR_PHONE` attributes that we have to include in the feed.

The requirements used in each message is `LISTING_OFFER_ONLY`, the operationType is `UPDATE` and the productType is `CELLULAR_PHONE`.

Is there a field that we're missing that is not documented? and if so, what's the field that we should add to the feed?

Thanks in advice.

**Comment by sungolivia** [comment]
hey @sitelicon might not be directly impacted by this but just wanted to let you know that we are experiencing feed delay issues!
https://github.com/amzn/selling-partner-api-docs/discussions/2689
