### ISSUE TITLE
[BUG] [SP-API] [Issue] Cannot set MSRP ("Manufacturer's Suggested Retail Price") of an existing product in the catalog.

### ISSUE THREAD

**Issue by erichocean** [amzn/selling-partner-api-docs#2688]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

AFAICT there is no API or attribute to set this value documented anywhere. If I missed it, please post a link. Otherwise, an example request showing setting the MSRP ("Manufacturer's Suggested Retail Price") on an existing product is what I'm looking for.

The "product MSRP" corresponds to the "Manufacturer's Suggested Retail Price" in SellerCentral when editing a listing/offer.

(I had hoped it would be _returned_ by an existing API, but I wasn't able to find that either. Again, if it exists, a link would help.)

Thanks!

**Comment by rugved1991** [comment]
HI @erichocean,

You can use the Feeds API to submit information to Amazon. Please take a look at the Pricing Feed under the [Listings Feeds](https://developer-docs.amazon.com/sp-api/docs/feed-type-values#listings-feeds). The Pricing feed will allow you to set the standard price for the listings you have created.
You can also use the [Listings API](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference) to create or update listings. For more information on which attribute to use for setting the standard price using Listings API, please refer to the product type schema using the [Product Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference).

Use Case Guides for reference:
Feeds API:
https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide
Listings API: 
https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide
https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide

Best,
Rugved
Solutions Architect, SP API

**Comment by erichocean** [comment]
High, I updated the title/issue. My problem is setting "Manufacturer's Suggested Retail Price", not "Standard Price". I've looked at the documentation you suggested and it's not listed there.

Any other suggestion?

**Comment by rugved1991** [comment]
Hi @erichocean,

You should use the "MaximumRetailPrice" to submit MSRP.

Best,
Rugved
Solutions Architect, SP API

**Comment by steven-so** [comment]
> Hi @erichocean,
> 
> You should use the "MaximumRetailPrice" attribute in the XSD to submit MSRP.
> 
> Best, Rugved Solutions Architect, SP API

Is MaximumRetailPrice the same as the "List Price" that you see on amazon listings (the strikeout price)? If not, what would that attribute be in the xml?
