### ISSUE TITLE
Feature Request: Api to download invoices generated by Amazon on our behalf

### ISSUE THREAD

**Issue by florianbepunkt** [amzn/selling-partner-api-docs#269]
We are not enrolled in the VCS (Vat calculation service), but due to changes in UK tax law, Amazon is generating invoices on our behalf. 

Currently we have no way of downloading these invoices and/or the invoice numbers. This makes bookkeeping a nightmare since we need to download all these invoices manually through seller central.

Please provide an endpoint for getting information about these invoices like invoice number and a possibility to download the PDF

**Comment by m4ciekm** [comment]
You can download invoice information with Amazon MWS, I haven't found any option to do so using Selling Partner API (SP-API).

**Comment by florianbepunkt** [comment]
@m4ciekm Can you point to a reference (documentation)? Just for clarification: You can download information via MWS in order to create invoices on your own and you can bulk download invoices if you are enrolled in the VCS program. But to my knowledge you cannot download invoice or invoice metadata (like invoice number) for invoices that are generated by Amazon on behalf of the seller (new UK VAT on eCommerce legislation in effect since Jan 1st).

If I'm wrong please let me know, you would really save my day

**Comment by m4ciekm** [comment]
You can get full VAT invoice information in the Amazon VAT Calculation Report, which can be either downloaded through seller central: https://sellercentral-europe.amazon.com/reportcentral/VAT_TRANSACTION/1 or via Amazon MWS http://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html see Tax Reports -> Amazon VAT Calculation Report

**Comment by florianbepunkt** [comment]
Yes, but I can use the url only if I am logged in to the seller central, as far as I can tell. Is there a way to download them with the MWS client on a server/cron job?

**Comment by m4ciekm** [comment]
You can download the invoices in bulk here: https://sellercentral-europe.amazon.com/tax/vatreports/bulkdownload  - choose Report type: VAT invoices. If you want to download them via a cron job, then I am not sure you can do this without a web browser (for logging in). You could automate it on a desktop running a script in python + Selenium.

**Comment by florianbepunkt** [comment]
Thank you for all the help. Sadly I cannot use the bulk download form. It only says that we are not enrolled to the VCS program (which we do not intend).

**Comment by m4ciekm** [comment]
Then I can recommend Selenium https://selenium-python.readthedocs.io/getting-started.html , you can run a python script in debug mode and stop it to log into to Seller Central on the web browser, then you can let the script run to download each PDF one by one.

**Comment by nodisk8800** [comment]
Request the report with reportType _GET_VAT_TRANSACTION_DATA_ 
In the flat file ,you can see the invoice download url:
https://www.Amazon.fr/gp/invoice/download.html?v=xxxxxxxxxx&t=EU_Retail_Forward

**Comment by nodisk8800** [comment]
In the  _SC_VAT_TAX_REPORT_  report, also have the invoice download url.

**Comment by florianbepunkt** [comment]
@nodisk8800 You are right. But how can I download the linked invoice pdf programmatically? The link only works if I am logged in as a user in seller central. But I would need to download via api.

**Comment by nodisk8800** [comment]
@florianbepunkt 

I know you issues.
Maybe execute the http POST request with account information to login,receive and save the cookies .
And then you can include the cookies in your http request to download pdf file.
But,It need account and password, it is not safe.

**Comment by nodisk8800** [comment]
The order invoices are the private data,not allow public access.
So,need the seller to login first.

**Comment by florianbepunkt** [comment]
Yes, I get there is no public access for PII data. My feature request is to provide an api endpoint to download the PDF invoices securely via API.

**Comment by florianbepunkt** [comment]
I probably found a way: SC_VAT_TAX_REPORT_INVOICE returns a list of document ids, which (in theory) should be accessible by the getReportDocument api. However I always receive a 403 when trying to list either the report or get the document, although I can list and download the report via MWS (but not the invoices)

**Comment by nodisk8800** [comment]
I think the id in invoice URL is not a documentid, it has different the reportDocumentId .

**Comment by florianbepunkt** [comment]
It would be great if one of the authors could shed some light on this:
`_ SC_VAT_TAX_REPORT_INVOICE_` gives a list of documentIds, just like for report or feed documents. However they are not downloadable via the `getFeedDocument` action.

**Comment by lihongjie0209** [comment]
same problem

**Comment by tobiaxor** [comment]
same problem here, seems there's no solution...

**Comment by kulisz** [comment]
someone found a solution to download invoices via sp api?

**Comment by piotr-lottestyle** [comment]
we experience the same problem

**Comment by luisdiazco** [comment]
@florianbepunkt was there a solution to this issue? 

What I am thinking is that either

use Amazon MWS to do this, so the program would take a hybrid approach using both SP API and MWS. 

or

 The invoice data can still be pulled from the API but it won't be downloaded as a PDF. Since the data can still be collected, a straightforward approach would be to build the pdf since all the data would be provided.

Note: 2nd solution is not plausible for my case since I need to collect the original pdf

**Comment by piotr-lottestyle** [comment]
@luisdiazco AFAIK there is no solution yet. It's even worse - Amazon won't let you download PDF if there is non-amazon referer in HTTP request

**Comment by tobiaxor** [comment]
I don't think Amazon will ever do this...
