### ISSUE TITLE
[BUG] [SP-API] [GetMyFeesEstimate client input error]

### ISSUE THREAD

**Issue by gokigoks** [amzn/selling-partner-api-docs#2693]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Product Fees V0 getMyFeesEstimates 
## Current Behavior

For some reason, we receive the error below for certain ASINs. (Until very recently?) This request works most of the time, but for some ASINs it throws the **InvalidParameterValue** error. 

Sample ASINs with the issue:
B07CV8QLJ9
B007Z3U4JC
B07L9G3FQW
B085CP1CL2
B0B3D4HH9Q

```
{
    "payload":{
        "FeesEstimateResult":{
            "Status":"ClientError",
            "FeesEstimateIdentifier":{
                "MarketplaceId":"ATVPDKIKX0DER",
                "SellerId":"XXXXXXXXXXX",
                "IdType":"ASIN",
                "IdValue":"B07CV8QLJ9",
                "IsAmazonFulfilled":true,
                "PriceToEstimateFees":{
                    "ListingPrice":{
                        "CurrencyCode":"USD",
                        "Amount":10.63
                    },
                    "Shipping":{
                        "CurrencyCode":"USD",
                        "Amount":1
                    }
                },
                "SellerInputIdentifier":"B07CV8QLJ9"
            },
            "Error":{
                "Type":"Sender",
                "Code":"InvalidParameterValue",
                "Message":"There is an client-side error. Please verify your inputs.",
                "Detail":[
                    
                ]
            }
        }
    }
}
```

**Comment by gokigoks** [comment]
Hi @chapmanjw,

Good day. Any chance this will get a quick look? Thank you.

**Comment by haffoudhi** [comment]
I m getting the same error in US and UK marketplaces.

**Comment by leandrotealdi** [comment]
Hi! Is there any update about this? Im facing the exact same issue currently... the SP API retrieves an error (the pattern of failure is not very clear, seems to be pretty random) and when checking the 'Details' field of the object is coming like an empty array....

**Comment by gokigoks** [comment]
This is still an issue for us. I googled for this error and the first result is my ticket. sigh..

This is a real issue because it fails randomly with no pattern.
