### ISSUE TITLE
Reports are not getting downloaded

### ISSUE THREAD

**Issue by Arul-Cointab** [amzn/selling-partner-api-docs#2694]
We are using the following report types 
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
 GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2
 GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA
GET_FBA_REIMBURSEMENTS_DATA
GET_REFERRAL_FEE_PREVIEW_REPORT
 B2B: GET_GST_MTR_B2B_CUSTOM
 B2C: GET_GST_MTR_B2C_CUSTOM

but  some how on the download report we are only getting the header as response in the api

**Comment by sungolivia** [comment]
I would actually recommend filing a ticket with our support team to further investigate!
https://developer.amazonservices.com/support
