### ISSUE TITLE
Missing IAM ARN on seller central page

### ISSUE THREAD

**Issue by LemarinelNet** [amzn/selling-partner-api-docs#27]
Seems very similar to #3 and #12 : 
I'm a freelance dev and trying to use SP-API for one of my customers.
I'm not able to see the IAM ARN on my customer's sellercentral account, as described in #12 or here... (my customer also has a MWS application already registered).
Is this a normal behavior ?

PS : my customer failed the assessment because he did respond randomly to the form, not understanding the questions... Now he can't fill the form, everything is greyed out...

Thanks for your help, Regards !

**Comment by ShivikaK** [comment]
Hello, 

Thank you for reaching out regarding your concern.

Can you please log a support case with us to further investigate the issue?
