### ISSUE TITLE
App Registration: Multiple OAuth Redirect URIs not working. Feature Request: OAuth should be CI/CD friendly.

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-docs#270]
In Developer Central App registration you have the opportunity to have two OAuth Redirect URIs. When adding two, only the first will ever work. The documentation does not state why only two are allowed, nor does the actual webpage state why two are allowed. Virtually every major API always gives the ability to add multiple URIs in these circumstances, obviously so a dev team can have multiple stages and test completely through their CI/CD with no issues. If this is the reason we're able to add multiple OAuth Redirect URIs, they should actually work. If this is not the case then either the documentation or the App Registration webpage should say why more than one are allowed. Also, if you're going to allow the additions of more than one for these reasons, then you should also be able to add more than two as it is common practice today to have at least 3 stages (sometimes more) for CI/CD, dev, staging and prod.

In general the entire OAuth flow is completely unfriendly to CI/CD. This should not be the case as virtually all major APIs are setup to be friendly to multiple stages. I request that rather than giving priority to continuing to build out new features and APIs for the SP-API and putting things like this on a backlog, that Amazon focus their resources to the very basic things like this, which should have been added to the API right from the start.

**Comment by cgaugel** [comment]
+1

**Comment by parvathm** [comment]
Hi @charliecode,

Thank you for your feedback. We are looking into it and update here with our findings.

Thanks,
Parvathm,
Selling Partner API developer support.

**Comment by rickdeee** [comment]
Hi @charliecode,

We clarified our guidance in the developer guide with regard to the redirect URL.

**Comment by charliecode** [comment]
Hello @rickdeee. You  are correct, it is possible to add more than one OAuth Redirect URI. However, only the first one listed actually works, leaving the remaining ones useless (please see attached screenshots).

![image](https://user-images.githubusercontent.com/22284644/114201258-d6f47600-990a-11eb-947e-ebcec29f332b.png)
![image](https://user-images.githubusercontent.com/22284644/114201281-df4cb100-990a-11eb-8543-56751b0a6c8c.png)

**Comment by rugved1991** [comment]
Hi @charliecode,

When you are adding multiple redirect URLs to the application, you will have to specify which URL to redirect to during OAuth flow. If you do not provide this information, the application will default to the first redirect URL configured on your application.
You will need to add "redirect_uri" parameter to the OAuth URL to let the application know which URL should the seller be redirected to.
Eg:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample&version=beta&redirect_uri=alternate_redirect_url

Let me know if this resolves your issue.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by charliecode** [comment]
@rugved1991 Thank you for that, I haven't setup the Marketplace Appstore workflow. [It is indeed mentioned there](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-the-seller-signs-into-your-website). I've setup the Website Workflow and the [redirect_uri is not mentioned there at all](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-0-set-up-an-%22authorize%22-button), looks like this would be another good place to update the documentation as the two flows are totally seperate.

**Comment by charliecode** [comment]
@rugved1991 BTW, I haven'y gotten an opportunity to verify that the Website Workflow OAuth uri will actually accept the redirect_uri param in the request. According to the docs it will not. I'll be able to verify next week. If it does not then you'll not only need to update the docs but also the OAuth endpoint to be able to handle the redirect_uri param. If I'm missing something, please let me know.

**Comment by rugved1991** [comment]
Hi @charliecode,

The redirect_uri parameter does work for website workflow too. I will inform the team to include it in the developer guide under website workflow.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by charliecode** [comment]
Hello @ShivikaK, would it be possible to close this issue out with a commit that fixes the issue? It's confusing when issues are closed before the fixes are actually pushed to the repository.

When researching issues in a repo it's common practice to assume an issue is fixed once it's closed. Therefore, many developers will first search for issues which are "open" when key-wording to filter for fixes, to save themselves time. By closing the issue now, it guarantees some will miss the fix held within this issue.

In this case the documentation has a major flaw as it's missing a parameter which should be added during the Website workflow but is still nowhere to be found in the documentation.

The SP-API launched back in Sept or Oct of 2020 if I recall, 7 or so months ago. I personally spent many hours needlessly trying to figure out why my multiple redirect uris were not working. I'm not the only one, as multiple others have also inquired about the same thing. That's just people who actually chime in here. Over 7 or so months can you imagine how many man hours could have been wasted on such a simple oversight? More than was necessary had the code written in the docs, actually been tested before publishing it.

Being that in some cases it's taken many months for issues to be fixed and committed to the repo once it's brought to Amazon's attention, we have to assume it may take some time before this fix is actually pushed, as it was only recently brought to Amazon's attention. Which could result in many more needlessly wasted hours by devs who can't find the answer because the issue is now closed.

We appreciate the extra support Amazon has been giving to the community, it doesn't go unnoticed. Perhaps this fix will be coming out quicker and that's why you closed it now. I mention the things above only because this is not the first time this has happened. 

For a TON of devs migrating over to the SP-API has been quite stressful, so whatever we can do to save them time and make things easier will always be greatly appreciated.

**Comment by ShivikaK** [comment]
Hello @charliecode,

Apologies for the whole confusion around closing out this issue.

I have reopened the issue and the fix is being worked upon as well. I will send an update once we have an ETA on this. 

Thank you for your cooperation!

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by charliecode** [comment]
@ShivikaK Your help is always greatly appreciated. Thank you for your understanding as well. 🙂

**Comment by charliecode** [comment]
@ShivikaK It certainly does clear out the confusion. Thanks a ton for this fix!

**Comment by hrhearn7** [comment]
For “Marketplace Appstore workflow”
I have my app (SP-API & MWS) in Draft state. My Beta URL takes the seller&selfauth to the consent page, but of course the “LOG INTO XXX” button does not work because I don’t understand what values go in : OAuth Login URI(I put the Beta url there) and/or ****OAuth Redirect URI****
We plan on using the “Marketplace Appstore workflow”

Beta Url testing "format" with (gets to consent page fine) and I put in "OAuth Login URI"" :https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.xxxx&version=beta

Case ID8294325061
