### ISSUE TITLE
[BUG] [SP-API] Missing Date Information for `InboundShipmentInfo` in FULFILLMENT INBOUND API

### ISSUE THREAD

**Issue by ProNotion** [amzn/selling-partner-api-docs#2706]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

`InboundShipmentInfo` is missing the shipment created and updated dates. You currently allow for `LastUpdatedBefore` and `LastUpdatedAfter` parameters in the `GET /fba/inbound/v0/shipments` requests but no dates are returned in the response object.

## SP-API Name and Version or Report/Feed Type

Fulfillment Inbound API v0 - getShipments

## Expected Behavior

Currently, there is no useful data returned that allows the date of the shipment to be determined. The response object should include the creation date and the last updated date.

## Current Behavior
No date information is returned.

## Context/Screenshots
We are importing shipments for tracking purposes and are unable to order or query data based on date.

**Comment by phstc** [comment]
Is there any update on this? I'm facing the issue. I can't tell when the shipment was created. 

@ProNotion Did you find any workaround?

**Comment by kmizzi** [comment]
I'm also facing this issue and it is high impact.

**Comment by ProNotion** [comment]
@phstc Annoyingly not a solution I am happy with but having no choice I think what I am having to do is request an inventory ledger report, filter on the shipment id and take the date from the first row of the report for that shipment. This obviously gives me neither the created date nor the updated date but the date it was received by Amazon. It's far from ideal but the support team don't seem interested and just confirmed they don't provide what I need in the API. It makes no sense why it is excluded! Perhaps if this bug report can get enough votes they might take notice and correct it.

**Comment by ericahrowe** [comment]
This has been an issue forever. It was this way in MWS also, and has never made any sense. The date is included as part of the shipment name, and we parse the date from that field. It's imperfect, and subject to date format errors, but it mostly works.

**Comment by ProNotion** [comment]
@ericahrowe That is assuming you don't rename your shipments or you do consistently name them but it's not the case for all sellers so that also is not reliable either plus you are still stuck with no updated date.

**Comment by phstc** [comment]
> @phstc Annoyingly not a solution I am happy with but having no choice I think what I am having to do is request an inventory ledger report, filter on the shipment id and take the date from the first row of the report for that shipment

That's a bummer! Are you using `GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA` + `received-date`? That's the closest I found.

I've seen some apps showing more details, for example, dates and even FBA cases (the ones that appear on the content tab). I'm wondering how they do it - if they use bots.

**Comment by ProNotion** [comment]
@phstc I think that probably gets you to the same place as I am in but I am using the report `GET_LEDGER_DETAIL_VIEW_DATA`.

I  also use a tool that shows the created date of shipments but it's very possible they are using a method similar to ours and not getting it directly from the API. The support case that was created for the issue resulted in them telling me it was not provided but no reason as to why.

**Comment by phstc** [comment]
> @phstc I think that probably gets you to the same place as I am in but I am using the report GET_LEDGER_DETAIL_VIEW_DATA.

@ProNotion hm I don't get the shipment ID through `GET_LEDGER_DETAIL_VIEW_DATA`. How do you track back to the shipment from the `GET_LEDGER_DETAIL_VIEW_DATA` report?

> The support case that was created for the issue resulted in them telling me it was not provided but no reason as to why.

Bummer! I opened a case as well, they are still investigating it. But likely to get the same response.

**Comment by ProNotion** [comment]
@phstc Filter on the `ReferenceId` using your shipment id. 

[See the docs here](https://sellercentral-europe.amazon.com/help/hub/reference/G4FKT5KQWFFJ7LDN#wjz_cjc_jcb) that break down the report fields. 

> Reference ID = Transaction ID, such as a shipment ID or adjustment ID

Hopefully that helps.

**Comment by phstc** [comment]
> [See the docs here](https://sellercentral-europe.amazon.com/help/hub/reference/G4FKT5KQWFFJ7LDN#wjz_cjc_jcb) that break down the report fields.

That's very helpful. Thank you. I wish they had that in the SP API docs. 

I don't have the Reference ID for any Event Type Shipment. It seems I'm only getting reference IDs for Adjustments. 

Reply from support: 

![image](https://user-images.githubusercontent.com/105652/216159362-5533c0bc-91d1-4f2b-8b60-e256b36cba58.png)

**Comment by ProNotion** [comment]
A slightly more positive response than I got but the same result, they will submit a feature request and that's probably the last we will hear about it! They call it an oversight but to me, it seems like it's too obvious to be that and that there is some other reason.

My request looks like this:

```
{
	"reportOptions": null,
	"reportType": "GET_LEDGER_DETAIL_VIEW_DATA",
	"dataStartTime": "2022-11-04T06:34:29.0420281Z",
	"dataEndTime": "2023-02-02T06:34:29.0406029Z",
	"marketplaceIds": ["A1F83G8C2ARO7P"]
}
```

Looking at the resulting report the `ShipmentId` is in the ReferenceId column on rows that have the `Receipts` event type

**Comment by DanielLanger** [comment]
+1 this is affecting us as well

**Comment by kk-wdt** [comment]
I had the same problem.The request params  include LastUpdatedAfter and LastUpdatedBefore.Splitting time into hours or days,you  will get an approximation of the update time.
