### ISSUE TITLE
[BUG] [SP-API] [Issue] FBM Inventory is getting updated in both places UK and Pan EU for the same SKU

### ISSUE THREAD

**Issue by yaswanthrazor** [amzn/selling-partner-api-docs#2716]
We are trying to sync FBM inventory levels for a SKU on UK and different inventory level on Pan EU. However, one is being replaced by the other as Feed API end point (POST_INVENTORY_AVAILABILITY_DATA) even after defining the marketplace and we are not able to use 2 different stock levels, can you please help us

![image](https://user-images.githubusercontent.com/97527708/200769818-cb8c9269-5a79-4db5-bdf1-7f4f88d92cdb.png)

**Comment by mchui199303** [comment]
> 我们正在尝试同步英国 SKU 的 FBM 库存水平和泛欧的不同库存水平。但是，即使在定义了市场之后，一个被另一个作为 Feed API 端点 (POST_INVENTORY_AVAILABILITY_DATA) 取代，我们无法使用 2 个不同的库存水平，请您帮助我们
> 
> ![图像](https://user-images.githubusercontent.com/97527708/200769818-cb8c9269-5a79-4db5-bdf1-7f4f88d92cdb.png)

I have the same problem, same sellersku different sites can't update stock individually
