### ISSUE TITLE
[BUG] fullfilment inbound GetShipments doesn't respect marketplaceId 

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-docs#2718]
when calling the get shipments call in the fulfillment inbound API, it sends u back all shipments, for all marketplaces, for example, if the merchant has a US CANADA and MEXICO store, and he makes a get shipments call and passes in the US marketplace value, it will give him all shipments from all NA marketplaces this is very annoying.

**Comment by GJ-JG** [comment]
Hi @nafberger , marketplaceId is required for calling getShipments API and you are able to get only US marketplace value if you specify ```ATVPDKIKX0DER```
Please re-open this ticket if you still receive all NA marketplaces even when you only specified US. It will help if you can paste the request and response details too.
