### ISSUE TITLE
[BUG] [SP-API] [Issue] createInboundShipmentPlan: Please provide item-level prep information for all SKUs or no item-level prep information at all

### ISSUE THREAD

**Issue by FKLC** [amzn/selling-partner-api-docs#2720]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
It should create an inbound shipment plan without returning an error.

## Current Behavior
I'm trying to call createInboundShipmentPlan with PrepDetailsList. After fetching prep requirements using getPrepInstructions I set items' PrepDetailsList accordingly, and for the others, I set them to `[]`. Here is what I pass to InboundShipmentPlanRequestItems:
```json
[
  {
    "SellerSKU": "somesku1",
    "ASIN": "asin12",
    "Condition": "NewItem",
    "Quantity": 3,
    "PrepDetailsList": [
      {
        "PrepInstruction": "Labeling",
        "PrepOwner": "SELLER"
      }
    ]
  },
  {
    "SellerSKU": "somesku2",
    "ASIN": "asin1",
    "Condition": "NewItem",
    "Quantity": 3,
    "PrepDetailsList": []
  }
]
```
For some weird reason however, it always returns `Please provide item-level prep information for all SKUs or no item-level prep information at all`, which I clearly do. I have PrepDetailsList for every item. I tried setting PrepDetailsList to `null` and `""` for items that don't have any prep requirement, but that also didn't work. What I've found so far is that, if all the items in the list have some sort of prep requirement, it works, but if only one of them don't, then it just returns the error message above. The other way also works, so, it just happens when there is a mix of items with prep details and item without.

**Comment by Aneverland** [comment]
{
    "SellerSKU": "somesku2",
    "ASIN": "asin1",
    "Condition": "NewItem",
    "Quantity": 3,
    "PrepDetailsList": [
      {
        "PrepInstruction": "NONE",
        "PrepOwner": "SELLER"
      }]
  }

**Comment by FKLC** [comment]
Thank you so much, it does work. Though, I don't think this is documented, so I'll keep it open.
