### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by Kernel1453** [amzn/selling-partner-api-docs#2723]
Hello,
We can add any new store from any region without any problem and get refresh_token. But when our user wants to make a request with this refresh token using inventory, order, report or any sp api, we get the following error. As stated in the error, the permissions are not revoked and we are sending refresh tokens. However, the code is already fixed and we can do the transactions we want with the previously added stores refresh tokens. We could not understand what the error is, we ask for your help.

[2022-11-14 14:30:34] local.ERROR: Client error: `POST https://api.amazon.com/auth/o2/token` resulted in a `400 Bad Request` response:
{"error_description":"The request has an invalid grant parameter : refresh_token. User may have revoked or didn't grant (truncated...)
 {"userId":19,"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://api.amazon.com/auth/o2/token` resulted in a `400 Bad Request` response:
{\"error_description\":\"The request has an invalid grant parameter : refresh_token. User may have revoked or didn't grant (truncated...)
 at /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)

**Comment by sungolivia** [comment]
please follow the issue template otherwise the issue will be closed!
