### ISSUE TITLE
putListingsItem image upload problem

### ISSUE THREAD

**Issue by arslansahin** [amzn/selling-partner-api-docs#2724]
Hello, I am having a problem with product images during the process of creating a new product with the amazon listings/2021-08-01/items/ method.
When I upload the product images to the s3 bucket and send them with the listing item method, the product image
https://sellercentral.amazon.com.tr/abis/listing/createFromDraft
cannot be viewed at.
When I look at the product detail page with the source code, there is a url in the src section of the product image.
s3://selling-partner-listings-api-media-staging-prod-dub/MerchantId/A3QKJ5YMP9Z914/Hk0rojjozeImw%2Fya9p%2BqNg%3D%3D

I am sending the product relative as below.

'main_product_image_locator' => [
    [
        'media_location' => 'https://nsoft.s3.eu-central-1.amazonaws.com/women-white-single-color-sports-shoes-1616337343.jpg'
    ]
]

s3 bucket permissions are set.
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::bucket-name/*",
                "arn:aws:s3:::bucket-name"
            ],
            "Principal": {
                "AWS": [
                    "arn:aws:iam::368641386589:role/Media-Download-Role"
                ]
            }
        }
    ]
}

https://ibb.co/nLqgN6Y

## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by mlemoing** [comment]
I have the same issue with the product type CELLULAR_PHONE_CASE

The attribute "main_product_image_locator has this configuration :

```
"main_product_image_locator": {
            "title": "Localisateur de l'image principale du produit",
            "description": "Indiquez la localisation et la source de l'image",
            "examples": [
                "Alimentation"
            ],
            "type": "array",
            "minItems": 1,
            "minUniqueItems": 1,
            "maxUniqueItems": 1,
            "selectors": [
                "marketplace_id"
            ],
            "items": {
                "type": "object",
                "required": [
                    "marketplace_id",
                    "media_location"
                ],
                "properties": {
                    "marketplace_id": {
                        "$ref": "#/$defs/marketplace_id"
                    },
                    "media_location": {
                        "title": "URL de l’image principale",
                        "description": "URL où se trouve l’image principale du produit spécifique à l’offre.",
                        "editable": true,
                        "hidden": false,
                        "examples": [
                            "http://www.companyname.com/images/1250.main.jpg"
                        ],
                        "type": "string",
                        "format": "uri",
                        "pattern": "^(https?|s3)://"
                    }
                },
                "additionalProperties": false
            }
        }
```

Therefore I send my own URL for 'media_location' has shown in the example : 

```
"examples": [
    "http://www.companyname.com/images/1250.main.jpg"
]
```

However, I get this error : 

"code": "invalidinput", 
"message": "Unable to Retrieve Media Content for URL 'Media Content is Not Hosted by Amazon or Amazon Web Services (such as AWS S3 or AWS CloudFront)'"

My url is a standard http link with which includes my CDN. I guess Amazon is not clear about what we can use and what we can't, they just force Sellers to migrate on SP-API and face issues like this one. In the end, we don't have any other choice to fully migrate images if we want to use them automatically.

Then I'm gonna test 2 other solutions :
- Create all products with SP-API and generate a CSV file which includes images to upload it manually on Seller Central. For my project, I only need to create images once.
- Creating feeds to upload my products, may be they allow private links to be uploaded by feeds

I'll let you know if you are interested.
