### ISSUE TITLE
[BUG] [SP-API] incomplete info regarding a shipments and shipment plans

### ISSUE THREAD

**Issue by animareverse** [amzn/selling-partner-api-docs#2728]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Why is not possible to get in any way the `ShipToAddress` and `CreationDate` values unless you use the `createInboundShipmentPlan`? If someone creates some shipment plans through the API and some directly in Seller Central, how can then get info about the shipments created in Seller Central?
And also it would be nice to get the `Total prep and labelling fees` via API instead of doing so many calls and calculations

## Expected Behavior
By using the ShipmentId it would be amazing to get all the info related to that shipment ( and related shipment plan: like `ShipToAddress` and `CreationDate` )

## Current Behavior
Currently there is no way to get these values through the API

**Comment by GJ-JG** [comment]
Hi @animareverse , it will help if you can paste the error message or the request/response details!

**Comment by animareverse** [comment]
@GJ-JG 😅 Ah well, there is no error, the info are just not returned. Anyway, I think nothing can be done about it
