### ISSUE TITLE
messaging api and order api

### ISSUE THREAD

**Issue by jason-json666** [amzn/selling-partner-api-docs#273]
1.When I call the /orders/v0/orders/{orderId}/buyerInfo SP API call,the structure of the returned value obtained is as follows：
{"payload":{"AmazonOrderId":" xxxxxxxx","BuyerEmail":"xxxxxxxxx@marketplace.amazon.co.uk"}}, have not buyer name and phone message;
2.I call getMessagingActionsForOrder, and its return data does not contain the buyer’s message

**Comment by nodisk8800** [comment]
好像大家都一样.
买家的信息 建议 从地址中取吧.

**Comment by hongjason** [comment]
> 好像大家都一样.
> 买家的信息 建议 从地址中取吧.

我从地址获取，但信息也不全的

**Comment by hongjason** [comment]
> 好像大家都一样.
> 买家的信息 建议 从地址中取吧.

{
    "payload": {
        "AmazonOrderId": "xxx-xxxxxxx-xxxxxxx",
        "ShippingAddress": {
            "PostalCode": "xxxxx",
            "City": "xxxxx",
            "CountryCode": "xx",
            "Name": ""
        }
    }
}

**Comment by nickname-sb** [comment]
> 好像大家都一样.
> 买家的信息 建议 从地址中取吧.

I also encountered the same problem, can you share your solution.

**Comment by Jis-collab** [comment]
Yes I also face the same problem .is there is solution ?

**Comment by nodisk8800** [comment]
Need PII.

**Comment by GuoCHong0210** [comment]
> > 好像大家都一样。
> > 买家的信息建议从地址中取吧。
> 
> {
> “ payload”：{
> “ AmazonOrderId”：“ xxx-xxxxxxx-xxxxxxx”，
> “ ShippingAddress”：{
> “ PostalCode”：“ xxxxx”，
> “ City”：“ xxxxx”，
> “ CountryCode”：“ xx”，
> “ Name” ：“”
> }
> }
> }

Me too. Have you solved it?

**Comment by rodrigojob** [comment]
For me have error
Exception when calling OrdersV0Api->getOrder: [500] Server error: `GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders/{orderId}/buyerInfo` resulted in a `500 Internal Server Error` response:

**Comment by fengmiq** [comment]
标题跟实际不符呀，跟消息接口messaging api无关呀。我遇到消息接口和上传消息文件接口问题，几个月也没有搞定，有哪位大侠搞定了发送自定义消息和上传消息文件的，跪求方法。

**Comment by nodisk8800** [comment]
上传消息 的功能我还没做过, 我做过 feed上传文件, 要加密上传,确实有是点难搞

**Comment by fengmiq** [comment]
@nodisk8800 大佬，不打算搞搞上传消息的接口测通了，前提是订单必须拥有相应的权限才行。但是我需要发送自定义消息和物流消息，我找了各种状态的订单，但是没有发现这两个消息的权限。郁闷了。发送消息上传附件的功能怎么也测不通，超级郁闷。开issue，平台也没人理，困扰我两三个月了

**Comment by nodisk8800** [comment]
@fengmiq 
我这边没有这个消息的业务需要,暂时还有好多事忙,先不做这个消息的功能了.
你这发送的消息,MWSAPI 能正常吗? 有时是SPAPI本身的问题.

**Comment by fengmiq** [comment]
@订单权限列表有的消息类型可以发送成功。但是想要的消息类型发送不了，上传消息附件的也不行。尴尬

**Comment by jason-json666** [comment]
Need PLL ，Permission problem solved

**Comment by jason-json666** [comment]
After Pll, must Refresh refresh_token

**Comment by PG408** [comment]
兄弟，你这边跑通了给用户发私信的API吗，是哪个

**Comment by jason-json666** [comment]
> 兄弟，你这边跑通了给用户发私信的API吗，是哪个

没有api，没找到

**Comment by PG408** [comment]
> > 兄弟，你这边跑通了给用户发私信的API吗，是哪个
> 
> 没有api，没找到

https://github.com/amzn/selling-partner-api-docs/blob/main/references/solicitations-api/solicitations.md
这个不知道是不是
