### ISSUE TITLE
SP-API Developer Profile Update : Restricted Access - D2C Shipment-PII-Role

### ISSUE THREAD

**Issue by Moeschie** [amzn/selling-partner-api-docs#2733]
Hello,

I've been trying to get the PII role for multiple months now. We are trying to do FBM+SFP but can't call the address information from the API. We are always rejected with this answer: 

"To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon."

We are not getting any further information on how you evaluate our planned app regarding other apps in the same category, as from our opinion we are bringing in features that are not yet available within this category.

Additionally, we asked a friend to submit a very similar application on the technical part and the data security part and they got the role granted how is this possible? 

We are already fullfilling Amazon orders through the multichannel plattform Plentymarkets, therefore it is hard for us to understand why we do not get access to the restricted PII?

Case-Id: 8159213252

Thanks in advance.

**Comment by vaidas-lungis** [comment]
Related to https://github.com/amzn/selling-partner-api-docs/discussions/2712
