### ISSUE TITLE
FulfillmentInbound updateShipment required fields are marked optional

### ISSUE THREAD

**Issue by zakm** [amzn/selling-partner-api-docs#2738]
In the MWS API, updating a shipment without passing some optional parameters such as ShipmentName, DestinationFulfillmentCenterId, or ShipmentStatus worked as expected. In the SP-API, these fields are still marked as optional but if they are not passed when calling `updateShipment`, then an error like `Request is invalid - ShipmentStatus must not be empty` will be returned.

I believe that either the documentation should be updated to reflect that they are not optional or the API should be updated to mirror the prior behaviour and the current documentation.

Thanks!

**Comment by sungolivia** [comment]
hey @zakm thanks for reporting! This is a valuable feedback! Can you actually submit this feedback to our documentation team? Whichever page you are on, at the bottom, after you click on thumbup/down, you can fill out this feedback, they would appreciate it so much!
<img width="344" alt="Screen Shot 2022-11-22 at 1 38 06 PM" src="https://user-images.githubusercontent.com/7606170/203394794-bca40741-a14f-4c0d-a0f0-b500cddb62d6.png">
