### ISSUE TITLE
How can I get an updated tracking number?

### ISSUE THREAD

**Issue by 9z** [amzn/selling-partner-api-docs#274]
Hello~!

I succeeded in updating the tracking number using feed api.

However, I couldn't find an api that can get the updated tracking number.

I thought I could get the updated tracking number with the orders api, but it wasn't.

please let me know~!

**Comment by nodisk8800** [comment]
Re call the Feed api to update the tracking number.

**Comment by 9z** [comment]
@nodisk8800 
Hello
What do you mean?
If I call the feed api again, the tracking number is updated, can't I get the tracking number?

**Comment by nodisk8800** [comment]
@9z 
Call the fee api again with new trackingnumber.
You can update the tracking number,but your can't receive any trackingnumber,API not return it.

**Comment by nodisk8800** [comment]
@9z 
And in your local DB, you must save the newest tracking number,and keep all history tracking number in log.
So ,get the tracking number in your DB,not from API.

**Comment by 9z** [comment]
@nodisk8800 
ok, thank you for advice!
