### ISSUE TITLE
GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT   TOO BIG [BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by ahmedfeki** [amzn/selling-partner-api-docs#2743]
Why you don't implement a pagination system or limit or search query  to the GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT report 
it's hard to get 12 million records in one request 
I increased the memory limit to the max my server can handle and still not able to get that report

**Comment by stefnats** [comment]
Instead of loading the whole json in memory, you should parse it partially. Im sure in your programming language there are streaming json parsers.
