### ISSUE TITLE
[BUG] [SP-API] [Issue] report GET_SELLER_FEEDBACK_DATA always return CANCELLED ,even have Negative feedback.

### ISSUE THREAD

**Issue by l172942736** [amzn/selling-partner-api-docs#2744]
## Expected Behavior

 my store have 1~3 star Feedback ,in my search date range( 10 year ),but report api always return CANCELLED  !!!!
```
{
    'report_id' => '50778019320',
    'report_type' => 'GET_SELLER_FEEDBACK_DATA',
    'data_start_time' => '2013-01-15T08:30:21+00:00',
    'data_end_time' => '2022-11-24T08:30:21+00:00',
    'report_schedule_id' => NULL,
    'created_time' => '2022-11-24T08:30:26+00:00',
    'processing_status' => 'CANCELLED',
    'processing_start_time' => '2022-11-24T08:30:30+00:00',
    'processing_end_time' => '2022-11-24T08:30:37+00:00',
    'report_document_id' => NULL,
}
```

## Context/Screenshots
my store feedback :
![24171321](https://user-images.githubusercontent.com/16515340/203743966-c7294ae7-9022-4a18-aef7-a83e5ec86c3d.png)

i think  it must have match data return .but  i always return CANCELLED  . 

Can anyone explain this...

**Comment by stefnats** [comment]
Could you try altering your inputs and see what happens? Especially a smaller time range, maybe just a few weeks or months, just for trying out.
I have never used this report, just that would be my approach for trying.

**Comment by l172942736** [comment]
> Could you try altering your inputs and see what happens? Especially a smaller time range, maybe just a few weeks or months, just for trying out. I have never used this report, just that would be my approach for trying.

now, i can get data within one year..thx
