### ISSUE TITLE
[FEATURE] Documentation: Troubleshooting for processingStatus FATAL

### ISSUE THREAD

**Issue by rejeenald** [amzn/selling-partner-api-docs#2746]
I already sent a ticket and I am not receiving a response yet from the team. I am so dependent with the SP-API documentation to troubleshoot the issue. I am trying to retrieve **GET_VENDOR_SALES_REPORT** and **GET_VENDOR_INVENTORY_REPORT**, and the documentation talks about the **processingStatus FATAL**, but only tells that the data is not yet available for download. However, I do not think that it is the case on my end because the **processingStartTime** and **processingEndTime** values from the response are too close to each other. It seems my request to get the reports is not actually being processed, and just failed at some point.

I tried to look for other ways such as getting the log data for me to investigate the cause of the FATAL processing status, but the documentation does not really provide one. If the cause is the unavailability of the report, then we need to know more than that and we need to know the next steps whenever such issue persists. Right now, there is really no information about that in the documentation.

If you may provide helpful steps or links of the pages of the documentation that we possibly missed, it would be a great great help!

Thank you!

**Comment by takeno-dev** [comment]
I am also having trouble with the same error. in Japan

**Comment by puppsupr** [comment]
Hi @rejeenald,

Thanks for the feedback regarding the reports status we have taken it into consideration. Can you please let me know if you are still facing similar issues with the reports processing.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
