### ISSUE TITLE
[SP-API] [Issue] Why product definition api response Product when I send the query with LAMP ?

### ISSUE THREAD

**Issue by WiFeng** [amzn/selling-partner-api-docs#2747]
First, I get all valid Prodcut Type from Report Api.  Report Type: GET_XML_BROWSE_TREE_DATA
Second, I want to get the json schema of the product type `LAMP`, but the response  schema url is `https://selling-partner-definitions-prod-dub.s3.eu-west-1.amazonaws.com/schema/PRODUCT.json`. Is it correct ? The schema contains all valid fields about `LAMP` ?

Now the SP-API  Listing JSON FEED is available on all product type or only support some function, and must use XML FEED for some cases ?

**Comment by rugved1991** [comment]
Hi @WiFeng.

If a Product Type is not supported by the Product Definitions API, it will respond back with the parent Product Type. "PRODUCT" PT is the default parent for all product types. You can use "PRODUCT" PT schema for the following use cases:
1. Edits (Patch) on common attributes
2. Creating offers (PUT) using "LISTING_OFFER_ONLY" requirement set.

JSON_LISTINGS_FEED can be used to edit any existing listing regardless of the product type. But, it would only support listing creation for the supported Product Types.

Best,
Rugved
Solutions Architect, SP API
