### ISSUE TITLE
Automate Repricing - Error when updating automated_pricing_merchandising_rule_plan

### ISSUE THREAD

**Issue by Jonny14231** [amzn/selling-partner-api-docs#2748]
Hello,

I believe Amazon has added this recenthly, but we're receiving the following error _[{'code': '4000000', 'message': 'An internal error has occurred. Please try again.', 'severity': 'ERROR'}]_ when trying to update the Automated Pricing Merchandising Rule Plan. We can successfully update the Minimum and Maximum Price.

```
dictionary = {
    "productType": "PRODUCT",
    "patches": 
        [{
            "op": "replace",
            "path": "/attributes/purchasable_offer",
            "value": [
                {
                    "marketplace_id": "A1F83G8C2ARO7P",
                    "automated_pricing_merchandising_rule_plan": [{"merchandising_rule": [{"rule_id": "Competitive Price Rule by Amazon"}]}],
                }
            ],
        }
        ]}
```

Highly appreciate it if anyone has any ideas.

**Comment by chapmanjw** [comment]
Hello @Jonny14231,

Unfortunately, the cat got out of the bad prematurely, so to speak. In the future, you will be able to associate pricing rules as part of your listings submissions. However, this feature is not yet complete. We are addressing the issue that caused these attributes/fields to show up in the Product Type Definitions API prematurely. Stay tuned to future product type change notifications for when this feature is fully implemented. 

Thanks,

John Chapman
