### ISSUE TITLE
[BUG] [SP-API] [Issue] getReport Socket Timeout

### ISSUE THREAD

**Issue by JaredAllen1** [amzn/selling-partner-api-docs#2753]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

I am making a request to `getReport` with the following request:

```
{
      host: `sellingpartnerapi-na.amazon.com`,
      path: `/reports/2021-06-30/reports`,
      method: `POST`,
      body: JSON.stringify({
        reportType: 'GET_MERCHANT_LISTINGS_DATA',
        marketplaceIds: [XXXXX],
      }),
      service: `execute-api`,
      headers: {
        ...authHeaders,
        'Content-Type': `application/json`,
      },
 },
```

The auth flow we are using shouldn't be the issue here since we are making requests to the Sales API with no issue..

## Expected Behavior
Report data being returned

## Current Behavior
No response from the server, resulting in socket timeout errors

**Comment by stefnats** [comment]
That's odd, i didn't experience it myself.

Maybe it has something to do with the recent outage described here?
https://github.com/amzn/selling-partner-api-docs/discussions/2763

Else it could help if you increased the timeout, can you try that?

Can you confirm that it is now working again?

**Comment by sungolivia** [comment]
Hey @JaredAllen1 can you try out what @stefnats  has suggested and re-open if you still experience it after trying out?
