### ISSUE TITLE
[FEATURE] Clarify if ORDER_STATUS_CHANGE Notification include new orders?

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#2762]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the improvement**
I would like to use the Notification API > ORDER_STATUS_CHANGE for tracking new orders. It is not clear in the documentation if new orders are included in the notifications or only changes to existing orders? Please clarify? 

**URL of the content on GitHub**
[Please provide the GitHub URL for the documentation content that could be improved.](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#order_status_change)

**Description of what the documentation currently says**
The ORDER_STATUS_CHANGE notification is sent whenever there is a change in the status of order availability.

**Description of what the documentation should say**
It should mention if the notifications include orders that have been **newly created or only changes to existing orders**

**Screenshots**

**Additional context**

**Comment by sungolivia** [comment]
Hey @jimmy-ross-xapix  thanks for sending this over! Did you know that you can make the feedback to our documentation team directly? 
![Screen Shot 2022-12-07 at 4 39 27 PM](https://user-images.githubusercontent.com/7606170/206327892-39c00c06-2530-4b5d-b0c2-3b335b431704.png)

**Comment by jimmy-ross-xapix** [comment]
arlight, done! thanks
