### ISSUE TITLE
PutTransportDetail ProNum length limit error

### ISSUE THREAD

**Issue by jackshuaiwei** [amzn/selling-partner-api-docs#2777]
When sending the ProNum for an FBA shipment, I get an error saying the length must be less than or equal to 10. We are using ProNums that are 11 characters in length, why is it limited to 10?

Here's the request data I'm sending:

PutTransportDetailsRequest transportDetailRequest = new PutTransportDetailsRequest()
{
IsPartnered = true,
ShipmentType = ShipmentType.SP,
TransportDetails = new TransportDetailInput
{
NonPartneredLtlData = new NonPartneredLtlDataInput()
{
CarrierName = "ODFL",
ProNumber = "99958569976"
}
}
};

And here's the error message:

1 validation error detected: Value '99958569976' at 'transportDetails.nonPartneredLtlData.proNumber' failed to satisfy constraint: Member must have length less than or equal to 10"

**Comment by lilveniceguy** [comment]
Hi @jackshuaiwei , we are having the same issue with Fedex, master tracking number have 12 characters and the api doesn't reveceived longer than 10.

Have you got any response or find out any alternative solution?

Best,
