### ISSUE TITLE
[BUG] [SP-API] [Warning	The XML field header is invalid]

### ISSUE THREAD

**Issue by hamzaafzal9009** [amzn/selling-partner-api-docs#2779]
I am using the Other Carrier option and added the tracking number myself, so when the customer receives the order it shows late on the customer panel. 
So, I am trying to update the order status from shipped to delivered. I haven't found any API endpoint for this task but when reading the API I noticed `POST_FLAT_FILE_FULFILLMENT_DATA` in **feeds data** so thought maybe it can update the order status still not sure though. 

I am at step 7 [ Download the feed processing report](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#step-7-download-the-feed-processing-report)

And I am getting ``Warning	The XML field heading is invalid, so values in this field were ignored. To correct this error, download the template again and use the new copy, or fix the field heading in your existing file.``

Here's the XML:

`<?xml version="1.0" encoding="iso-8859-1" ?> <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd"> <Header> <DocumentVersion>1.01</DocumentVersion> <MerchantIdentifier>MERCHAnT_TOKEN</MerchantIdentifier> </Header> <MessageType>OrderFulfillment</MessageType> <PurgeAndReplace>true</PurgeAndReplace> <Message> <MessageID>1</MessageID> <OrderFulfillment> <AmazonOrderID>123-1234567-1234567</AmazonOrderID> <FulfillmentDate>2022-12-13 23:20:00</FulfillmentDate> <FulfillmentData> <CarrierName>XYZ</CarrierName> <ShipperTrackingNumber>TRACKING_NUMBER</ShipperTrackingNumber> </FulfillmentData> </OrderFulfillment> </Message> </AmazonEnvelope>`

How can I fix this also am I in the right direction

**Comment by Lemodo20** [comment]
This is working on my side:

 

<?xml version="1.0" encoding="UTF-8"?>

<AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<Header>

<DocumentVersion>1.01</DocumentVersion>

<MerchantIdentifier>M_xxx</MerchantIdentifier>

</Header>

<MessageType>OrderFulfillment</MessageType>

 

<Message>

<MessageID>1</MessageID>

<OrderFulfillment>

<AmazonOrderID>404-xxxxxx-5401166</AmazonOrderID>

<FulfillmentDate>2022-12-13T08:23:21+01:00</FulfillmentDate>

<FulfillmentData>

<CarrierCode>DPD</CarrierCode>

<ShippingMethod>Classic</ShippingMethod>

<ShipperTrackingNumber>xxx</ShipperTrackingNumber>

</FulfillmentData>

<Item>

<AmazonOrderItemCode>xxx</AmazonOrderItemCode>

<Quantity>1</Quantity>

</Item>

</OrderFulfillment>

</Message>

 

 

</AmazonEnvelope>

Von: Hamza Afzal ***@***.***> 
Gesendet: Mittwoch, 14. Dezember 2022 00:36
An: amzn/selling-partner-api-docs ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [amzn/selling-partner-api-docs] [BUG] [SP-API] [Warning The XML field header is invalid] (Issue #2779)

 

I am using the Other Carrier option and added the tracking number myself, so when the customer receives the order it shows late on the customer panel.
So, I am trying to update the order status from shipped to delivered. I haven't found any API endpoint for this task but when reading the API I noticed POST_FLAT_FILE_FULFILLMENT_DATA in feeds data so thought maybe it can update the order status still not sure though.

I am at step 7 Download the feed processing report <https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#step-7-download-the-feed-processing-report> 

And I am getting Warning The XML field heading is invalid, so values in this field were ignored. To correct this error, download the template again and use the new copy, or fix the field heading in your existing file.

Here's the XML:

<?xml version="1.0" encoding="iso-8859-1" ?> <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd"> <Header> <DocumentVersion>1.01</DocumentVersion> <MerchantIdentifier>MERCHAnT_TOKEN</MerchantIdentifier> </Header> <MessageType>OrderFulfillment</MessageType> <PurgeAndReplace>true</PurgeAndReplace> <Message> <MessageID>1</MessageID> <OrderFulfillment> <AmazonOrderID>123-1234567-1234567</AmazonOrderID> <FulfillmentDate>2022-12-13 23:20:00</FulfillmentDate> <FulfillmentData> <CarrierName>XYZ</CarrierName> <ShipperTrackingNumber>TRACKING_NUMBER</ShipperTrackingNumber> </FulfillmentData> </OrderFulfillment> </Message> </AmazonEnvelope>

How can I fix this also am I in the right direction

**Comment by stefnats** [comment]
Hey there

Just to make it simple, you might be doing one these things to fix it:

- `CarrierCode` instead of `CarrierName`
- `FulfillmentDate` wrong / other format
- No `ShippingMethod`

Let me know if this helps :)

**Comment by sungolivia** [comment]
hey @hamzaafzal9009 can you try above suggestions and re-open if issue persists?
