### ISSUE TITLE
[BUG] [SP-API] [Issue] ANY_OFFER_CHANGED_NOTIFICATION Wrong value for IsFulfilledByAmazon in CO.UK Marketplace

### ISSUE THREAD

**Issue by metaprice** [amzn/selling-partner-api-docs#2781]
Hi there,

we have at least since today the problem that the field IsFulfilledByAmazon in the ANY_OFFER_CHANGED notification for CO.UK is not transferred correctly. In all other EU countries the value is transferred correctly, in CO.UK it is always "true", even if the item is FBM_PRIME and not FBA.

Is this currently the same for you guys?

Thanks

**Comment by sungolivia** [comment]
Hey @metaprice if you haven't done so, I would reach out to developer support to get this issue reported.
https://developer.amazonservices.com/support

If you have done so please leave the case ID or share the resolution with rest of the group!

**Comment by metaprice** [comment]
Here is nothing completed.
