### ISSUE TITLE
[BUG] [MWS] [Issue] This shipment was converted to Send to Amazon and no updates can be made to this shipment

### ISSUE THREAD

**Issue by peter200694013** [amzn/selling-partner-api-docs#2785]
We are using MWS API to create inboud shipmenet, then use API PutTransportontent to update tracking numbers to shipment. It failed to update tracking numers to shipment with PutTransportontent. The error is "**This shipment was converted to Send to Amazon and no updates can be made to this shipment**".

Is there any advice for this issue?

Thanks,
Peter

**Comment by kpconnell** [comment]
I believe they announced this well in advance - once you touch a shipment in seller central, you can no longer manipulate it in the API.

**Comment by GJ-JG** [comment]
Hi @peter200694013 , API-created shipments that have been viewed, or edited using Send to Amazon cannot be viewed or edited via API.
You can check the announcement from [here](https://developer-docs.amazon.com/sp-api/changelog/send-to-amazon-will-replace-the-sendreplenish-workflow-for-api-created-shipments) and don't forget to [subscribe](http://developer-docs.amazon.com/sp-api/changelog.rss)!
