### ISSUE TITLE
Unable to publish application - Urgently seeking help

### ISSUE THREAD

**Issue by davev74** [amzn/selling-partner-api-docs#279]
We have very carefully read and followed the steps here https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md and and still unable to get our application published in the web store.  We continually get "SPDC300 Error publishing app" error.  We have the authorization workflow working, and triple checked our IAM setup, and everything else in the guide.

Does anyone know what this means?  I have opened a support ticket, but we just get emails saying its being looked into, but no path to resolution as of yet.  The ticket was opened about 1 month ago.

**Comment by ShivikaK** [comment]
Hello @davev74 ,

This issue has been reported to us via case 7722238751 and it is being investigated by our engineering team. There is an additional issue created regarding this so I will go ahead and close this out as a duplicate.

Thanks,
Shivika Khare
Selling Partner API Developer Support
