### ISSUE TITLE
[BUG] [SP-API] [Issue] PUT listings erroring on an attribute not present in the schema

### ISSUE THREAD

**Issue by frankbarry** [amzn/selling-partner-api-docs#2791]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/listings/2021-08-01/items/{sellerId}/{sellerSku}

## Expected Behavior

Put request should succeed. Request body contains JSON for productType ART_CRAFT_KIT and is compliant with the schema for that productType. The schema does not include attribute `b2b_purchasable_offer` so it was not included.

## Current Behavior

Put request fails see below. Attribute `b2b_purchasable_offer` is not part of this product type's schema.
<pre><code>
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Fri, 16 Dec 2022 19:40:09 GMT
  Connection: keep-alive
  x-amzn-RequestId: 8300ac93-1f7d-4f39-a7dd-4b062cb30838
  x-amzn-RateLimit-Limit: 5.0
  x-amz-apigw-id: dQRv4EJiIAMFfcA=
  X-Amzn-Trace-Id: Root=1-639cc998-3303fa0f5f6e44f401a7f2f7
  Content-Type: application/json
  Content-Length: 253
}

  {"sku":"alice-1","status":"INVALID","submissionId":"8a98d15daad842ab90300283e97dbc99","issues":[{"code":"4000001","message":"The provided value for 'b2b_purchasable_offer' is invalid.","severity":"ERROR","attributeNames":["b2b_purchasable_offer"]}]}
</pre></code>

## Your Environment

Request JSON body is attached as a JSON file with .txt extension.
[serializedRequest.json.txt](https://github.com/amzn/selling-partner-api-docs/files/10248517/serializedRequest.json.txt)

**Comment by frankbarry** [comment]
So I was able to fix this because I noticed an issue with the request JSON (there was an error in the purchasable_offer section). However the bug still stands because the error message is just plain wrong. Please fix.

**Comment by sungolivia** [comment]
Hey @frankbarry can you submit this issue to our [Developer Support team](https://developer.amazonservices.com/support) to take up and comment here with the case ID?
Thanks so much for reporting!
