### ISSUE TITLE
Server Error while checking transaction status for a shipment confirmation

### ISSUE THREAD

**Issue by cafeasp** [amzn/selling-partner-api-docs#28]
I'm able to check the status for Acknowledge submitted with no issues but when checking for shipment confirmation the API is crashing.

https://sellingpartnerapi-na.amazon.com/vendor/directFulfillment/transactions/v1/transactions/20201005142211-eaff0231-ba04-4b71-ae53-my_transaction_id

API Returns:
{
"errors": [
{
"code": "InternalFailure",
"message": "We encountered an internal error. Please try again.",
"details": ""
}
]
}

I submitted multiple support tickets and all I get is try again later. What is the real issue?

**Comment by ShivikaK** [comment]
Hello,

Thank you for reaching out!

Can you share the case IDs that you have reported to us for this concern?

**Comment by cafeasp** [comment]
Hi,

Case Id 7456811131

Thanks for checking the case

**Comment by cafeasp** [comment]
Getting support in Vendor Central and in git project is the worse I ever seen for a company so big. Definitely Amazon does not have a good process to support new API's or to follow up on a professional matter.

**Comment by charliecode** [comment]
@cafeasp You're not alone. I feel your pain. **I know everyone at Amazon must individually be working very hard to get this stuff done and we def appreciate their hard work. But I'm also quite frustrated with the launch of this API, especially for such large a company.** It's obvious a lot of people are. Maybe they're understaffed? Maybe they were giving impossible deadlines to reach without a big enough team? I think we should be careful to call out the team while also letting our frustrations known in a respectful manner. It's clear there are issues which are eating into the pockets of individual developer's or companies, **which isn't fair**. At this point it would be nice if we could get some sort of formal acknowledgment from management of what's actually going on and how long they anticipate it to go on for. This way we can decide on an individual basis whether we want to suffer through this **or hold off until they do their own testing, on their own dime and get a professionally working API.**

**Comment by cafeasp** [comment]
@charliecode For sure no blame to the dev guys. I totally understand no disrespect for any of the developers. My comment was for the entity that made the decision to take this API to production without fully testing.

**Comment by parvathm** [comment]
Hi,

Please check the case for further investigation.

Thanks,
Parvathm
Selling Partner API Support.
