### ISSUE TITLE
Request for SP-API PII access rejected ! 

### ISSUE THREAD

**Issue by busedemirci** [amzn/selling-partner-api-docs#2806]
Hello ,
I'm trying to get permission for RDT access but it just doesn't work. Are public apps not allowed to access PII? I would be glad if you help.

**Comment by defenderjim** [comment]
You have to have the role permission.  Check it out in SC.
You also have to hit the api with a regular token to get an RDT.
Here is my code from Production to get an RDT.

`public static String getRestrictedToken(AmazonRegion region, String resource)
		{
		// https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md

			DateTime now = DateTime.Now;

			RegionToken rt = restrictedList.Find(x => x.regionName.CompareTo(region.region) == 0);
			if (rt == null ) {
				restrictedList.Add( rt = new RegionToken { regionName = region.region, refreshToken = region.refreshToken } );
			}

            if (rt.accessToken == null || DateTime.Compare(now, rt.expDateTime) > 0) {
                TokenRequest tokenRequest = null;

				RestClient restClient = new RestClient(region.url);//"https://sellingpartnerapi-na.amazon.com");

				IRestRequest restRequest = new RestRequest("tokens/2021-03-01/restrictedDataToken", Method.POST);

				restRequest.AddHeader("Content-Type", "application/json");

				restRequest.AddJsonBody(new RestrictedResources(resource));

				restRequest = Utils.signRequest(region, restRequest );


				IRestResponse response = restClient.Post(restRequest);


				if (response.IsSuccessful) {
				
					String json = response.Content;

					RestrictedResourceResponse tokenResponse = JsonConvert.DeserializeObject<RestrictedResourceResponse>(json);
                    rt.accessToken = tokenResponse.restrictedDataToken;
                    rt.expDateTime = DateTime.Now.AddSeconds(tokenResponse.expiresIn - 10); // Subtract 10s as buffer

				}
				else {
                    rt.accessToken = "";
                }
            }
            
            return rt.accessToken;
		}`

`	class RestrictedResourceResponse
	{
		public int expiresIn;	//: 3600,
		public String restrictedDataToken;		// Atz.sprdt|AYABeCcGbHzkvy
	}
`

**Comment by busedemirci** [comment]
Thank you very much for your help, but I'm having trouble with the permission part. We filled out the required parts for RDT in the developer profile and forwarded it to Amazon. But they said they could not give us permission to get PII information. What should we pay attention to when obtaining this permit? I think you got the necessary permits for RDT.

**Comment by defenderjim** [comment]
Over the years, Amazon has gotten very stingy giving out API access, especially for PII.  I think their default response is "No".  You should adjust your verbage in the application.  Do some research and get input from people who understand what they are looking for in an application.  You can't just say "I want it", which was possible years ago.

**Comment by busedemirci** [comment]
Yes, we've been rejected twice in a row and we can't figure out why. I guess they don't want to give this permission to small companies. But by doing so, they put the developers who use their APIs in a very difficult situation. I think at least a warning should be issued before starting to use the API. Anyway, thank you so much for your response.

**Comment by defenderjim** [comment]
I worked for a small company, it was granted.

**Comment by Lemodo20** [comment]
can you share, what you fill in the form?

**Comment by defenderjim** [comment]
Sorry, I no longer work at that company.

**Comment by busedemirci** [comment]
Can you tell me what Amazon is paying attention to in this form? What criteria did you meet as a company? I would be very happy if you could share it with us.

**Comment by defenderjim** [comment]
I didn't write the application.  I would make sure you answer positively to all their security questions "Do you do x?" =>  "Yes".
I would look around, ask on SO, find a consultant to help you.

**Comment by busedemirci** [comment]
OK. Thank you for your advice.

**Comment by Lemodo20** [comment]
I tried already 4 times with different answer to get access. Problem is also, that you have max. 500 characters, to describe, what you do.

Currently i need an correct answer for

1.2
1.3
1.4
1.6
2.1
2.3
2.6
4.1

maybe somebody can share correct answers and we can combine it at the end to a full solution

**Comment by busedemirci** [comment]
That would be really good. If our request is accepted, I will help.

**Comment by Lemodo20** [comment]
It's already helpful, when we create together a document with the correct answers

This are the Questions: If i answered it wrong, i got als a number on each question. If i don't know the number, i've add ?? instead.
You can find helpful information, what they expect here:
https://sellercentral-europe.amazon.com/mws/static/policy?documentType=DPP&locale=en_EN

Answers, who are correct are in bold text. Please add your answers, which worked on your side


?? Describe the application or feature(s) you intend to build using the functionality in the requested roles :

4.1 Describe why you require Personally Identifiable Information to build your application or feature :

1.2 Describe the network protection controls used by your organization to restrict public access to databases, file servers, and desktop/developer endpoints :

1.3 Describe how your organization individually identifies employees who have access to Amazon Information, and restricts employee access to Amazon information on a need- to-know basis :

2.3 Describe the mechanism your organization has in place to monitor and prevent Amazon Information from being accessed from employee personal devices (such as USB flash drives, cellphones) and how are you alerted in the event such incidents occur 

?? Provide your organization's privacy and data handling policies to describe how Amazon data is collected, processed, stored, used, shared and disposed. You may provide this in the form of a public website URL :
**-> Just add URL from your companies Privacy Document**

2.1 Describe where your organization stores Amazon Information at rest and provide details on any encryption algorithm used :

2.4 Describe how your organization backups or archives Amazon Information and provide details on any encryption algorithm used :
**Data retrieved from Amazon is not stored, but processed internally immediately. Data not relevant for tax purposes is not stored.**

2.6 Describe how your organization monitors, detects, and logs malicious activity in your application(s) :

1.6 Summarize the steps taken within your organization's incident response plan to handle database hacks, unauthorized access, and data leaks : 

1.4 How do you enforce password management practices throughout the organization as it relates to required length, complexity (upper/lower case, numbers, special character) and expiration period?

How is Personally Identifiable Information (PII) protected during testing? 

2.5 What measures are taken to prevent exposure of credentials? :
**Developers must use different passwords for different accounts and systems.
Developers must use multifactor authentication (MFA) to log in to systems. 
Sensitive data must not be hard-coded in code, including keys, secret access keys or passwords. 
Sensitive credentials must not be exposed in public repositories. Developers must maintain separate test and production environments.**

2.7 How do you track remediation progress of findings identified from vulnerability scans and penetration tests? : 
**We're testing our applications periodically to assess products’ security is locate any security vulnerabilities that might be hidden in source code, before releasing it.
    We're using SonarQube (automated tracking and detecting Vulnerabilities tools) to developers automatically detect all open source components in an organization’s systems.**

2.7 How do you address code vulnerabilities identified in the development lifecycle and during runtime? : 
**We configure standard automation and integrate it into the tools developers already use.
We train application security awareness in the developers' IDEs.
We use CI/CD tools for deployment.
We use Splunk tool to quickly detect and respond to attacks to simplify threat management and minimise risk and protect systems.
We provide rapid remediation in the shortest possible time.**

2.7 Who is responsible for change management and how is their access granted? Please specify job title. : 
**The security system team is responsible for change management. They grant developers and operators access**

**Comment by busedemirci** [comment]
Hello ,
Of course, I will share our approved answers with you. So we can prepare a form together. But there is something I want to ask. What exactly is this :
https://sellercentral-europe.amazon.com/mws/static/policy?documentType=DPP&locale=en_EN link for? 
I saw that a few companies have published policies on their websites in accordance with the information written in this link. Do we, as developers, need to publish it? As an example I can give this link: https://bixme.com/pages/data-protection-and-handling-policy . 
We are not a seller, but do we still need to create such a policy and post it on our company's site?

**Comment by Lemodo20** [comment]
I got this link from Amazon. So your answer to the questions should be based on this document. I will have tomorrow an online meeting with a consulting company regarding SP  API. I will share, what they told me. I ask them, if they can help me to get this approval. I also write today an direct letter to Amazon Germany. Maybe i get there an answer also. A support ticket will be always answered with some bullshit

**Comment by busedemirci** [comment]
I would be very happy if you share the knowledge you have gained! If you need to write to me privately, I can also share my email address. It's been a really tough process and getting this permission is like a pain in the ass.

**Comment by busedemirci** [comment]
@Lemodo20 
Hello, were you able to talk with consulting company?

**Comment by Lemodo20** [comment]
i had yesterday the onlinemeeting, but they also don't know, what's to do in next step. I also send Amazon a few our ago a last try of the form. And what should i say. It works now. I get now Access to PII - Data. So it isn't impossilbe.

**Comment by busedemirci** [comment]
Oh really? Congratulations ! Can you share your answer with me? I also did send a form but I am pretty sure that they are not gonna accept it. Maybe I can try with your help at the next time.
