### ISSUE TITLE
Access to requested resource is denied. for /notifications/v1/destinations

### ISSUE THREAD

**Issue by riju-dc** [amzn/selling-partner-api-docs#2807]
We have been trying to set up notifications (Amazon Simple Queue Service workflow) following the tutorial [here](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#tutorial-set-up-notifications-amazon-simple-queue-service-workflow).

We have completed [step 1](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue).

The request in [step 2](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#step-2-create-a-destination) is however being met with "Access to requested resource is denied." message.

Steps performed to obtain a LWA access token for grantless operations:
Following the tutorial [here](https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-1-request-a-login-with-amazon-access-token), a request was made to obtain the LWA token.
Request:
```bash
curl --location --request POST 'https://api.amazon.com/auth/o2/token' \
--header 'User-Agent: python-sp-api0.6.5' \
--header 'Accept-Encoding: gzip, deflate' \
--header 'Accept: */*' \
--header 'Connection: keep-alive' \
--header 'content-type: application/x-www-form-urlencoded;charset=UTF-8' \
--header 'Content-Length: 223' \
--data-raw 'grant_type=client_credentials&client_id=amzn1.application-oa2-client.xxxREDACTEDxxx&scope=sellingpartnerapi%3A%3Anotifications&client_secret=xxxREDACTEDxxx'
```
The above yielded an access token like so:
Response:
```json
{
  "access_token": "Atc|XXXREDACTEDXXX",
  "scope": "sellingpartnerapi::notifications",
  "token_type": "bearer",
  "expires_in": 3600
}
```

The above token was used as the value of `x-amz-access-token` in the following cURL.
Request:
```bash
curl --location --request POST 'https://sellingpartnerapi-na.amazon.com/notifications/v1/destinations' \
--header 'user-agent: python-sp-api0.6.5' \
--header 'Accept-Encoding: gzip, deflate' \
--header 'Accept: */*' \
--header 'Connection: keep-alive' \
--header 'host: sellingpartnerapi-na.amazon.com' \
--header 'x-amz-access-token: XXXREDACTEDXXX' \
--header 'x-amz-date: 20221227T120602Z' \
--header 'content-type: application/json' \
--header 'Content-Length: 145' \
--header 'Authorization: AWS4-HMAC-SHA256 Credential=XXXREDACTEDXXX/20221227/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=XXXREDACTEDXXX' \
--header 'x-amz-security-token: XXXREDACTEDXXX' \
--data-raw '{
    "name": "DataChannelDestination",
    "resourceSpecification": {
        "sqs": {
            "arn": "arn:aws:sqs:us-east-1:XXXREDACTEDXXX:XXXREDACTEDXXX"
        }
    }
}'
```
which results in the following.
Response:
```json
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
```
Any assistance in this regard is deeply appreciated.

**Comment by nk-gears** [comment]
Same Issue. This is happening since few weeks back.

**Comment by MeenaAmz** [comment]
Hello, please refer to this [video](https://www.youtube.com/watch?v=vevSr4Ec77c) and make sure you have setup the SQS queue correctly with the required access.

**Comment by sungolivia** [comment]
@riju-dc  were you able to watch the video and resolve the issue as per what @MeenaAmz  has recommended?
