### ISSUE TITLE
can someone explain hybrid sp/mws apps?

### ISSUE THREAD

**Issue by ericblade** [amzn/selling-partner-api-docs#281]
The documentation seems to be utterly lacking in how to get that to work.  What returns the MWS tokens?

**Comment by nodisk8800** [comment]
Finish oauth ,then the MWS token/code/SellerID  will send to your callback uri

**Comment by ericblade** [comment]
so.. do you have to do it through the SellerCentral interface to apps, or can you also do it with a "Login with Amazon" button in the user facing app?  

Either way, though, it ends up passing the necessary values to the *user* rather than to what's going to be making use of them?  That doesn't seem like how it should work.

**Comment by nodisk8800** [comment]
I used Website workflow to call OAuth,and get the access_token/refresh_token/MWSToken successfull.

Config your application with redirect_uri, it can receive the access_token/refresh_token/MWSToken/code... after seller login and agree you application to access his amazon data.

**Comment by ericblade** [comment]
hmmm.  I get redirected with spapi_oauth_code, state, and selling_partner_id in the redirect uri.  No mention of MWS token.  I have API type set to SP and MWS : 
![image](https://user-images.githubusercontent.com/1451847/104245361-1c032c00-5432-11eb-8f56-1727b53b0e15.png)

Any other settings I need to ensure are somewhere?

When user requests auth, I'm popping a new window to https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.[...]&state=12345&version=beta

that redirects me back into my app with ?spapi_oauth_code=...&state=12345&selling_partner_id=(my id)

**Comment by nodisk8800** [comment]
When your auth yourself account,it is no MWSToken return.

**Comment by nodisk8800** [comment]
And... your application type must select the  MWS && SPAPI  option.

When other seller auth your application ,It can return then MWS token,
but,when auth yourself,MWSToken not return.

**Comment by ericblade** [comment]
... so how could i possibly write a functioning app, if i have to auth someone else to be able to check it?

**Comment by nodisk8800** [comment]
I had check it,it work successfull.
so ,don't worry. your app can do like this:

String mws_Auth_Token = request.getParameter("mws_auth_token");
if(mws_Auth_Token!=null && !"".equals(mws_Auth_Token)){
	//save the 	mws_Auth_Token
}

**Comment by ericblade** [comment]
So, I'd need to add in a check to see if it's specifically me, and there's no way for me to validate that it will actually receive the correct parameters for someone else?

**Comment by ericblade** [comment]
Alright, so, that seems to work -- if you receive selling_partner_id, then for users that aren't yourself, you will also receive mws_auth_token .. but for yourself, you will not receive a mws_auth_token.  I feel like Amazon should at least send a dummy auth token parameter, so one can test that they are receiving everything correctly with their own accounts, instead of having to say "hey, users of my app, could someone please confirm that (this operation) works correctly?"

**Comment by coder771** [comment]
If anyone got hybrid app working, how did you take care of new users. So if there were accounts that already have MWS Auth token we can use OAuth like above but if they are new accounts, I believe we need to use new Authentication method like authenticating with AWS Credentials and creating user and role in AWS Account?

**Comment by ericblade** [comment]
it's a bit of a mess that i'm not entirely understanding how i made it all work :-D but I am presently using Auth0 to OAuth to my application, to validate the user, and then my application has the user OAuth with Amazon for the MWS and SP-API authorizations.

**Comment by ericblade** [comment]
Re-open, as no one has actually explained the correct thing
