### ISSUE TITLE
[BUG] [SP-API] [Issue] Add videos to products

### ISSUE THREAD

**Issue by ooodogodogodogo** [amzn/selling-partner-api-docs#2816]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

We want to add videos to our products. Do we able to add videos via SP-API? If so, how can we do it?

## Context/Screenshots

We were able to upload products on Seller Central one by one, but we want to add multiple videos at the same time or one by one via SP-API
## Your Environment

We are working on Java SDK with Spring Boot.

**Comment by happy-bear-x** [comment]
I also have the same question. Have you solved this problem?
