### ISSUE TITLE
Australia Amazon marketplace but Endpoint link showing error 

### ISSUE THREAD

**Issue by sunil11475-dev** [amzn/selling-partner-api-docs#2834]
Hi, I tried to get token/authorization code for Australia Amazon marketplace but Endpoint link showing error, please check below. I got enabled Australia marketplace in my app which is approved and published. Don't have any issue with US and EU marketplace, its works perfectly.

Country | Marketplace ID | Country code
Australia | A39IBJ37TRP1C6 | AU
Endpoint - https://sellingpartnerapi-fe.amazon.com/ | us-west-2

```
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "MissingAuthenticationToken"
    }
  ]
}
```

**Comment by vetnotmanee** [comment]
The error 2834 in the Amazon marketplace Australia endpoint is a bug that prevents developers from getting a token or authorization code for the Australian marketplace. This bug has been reported to Amazon, but it has not yet been fixed.

There are a few workarounds that you can try if you are experiencing this error. First, you can try clearing your browser's cache and cookies. You can also try using a different browser. If these workarounds do not work, you can try contacting Amazon support for help.

Here are the steps on how to clear your browser's cache and cookies:

1. Open your browser.
2. Click on the three dots in the top right corner of the browser window.
3. Select "Settings."
4. Click on "Privacy and security."
5. Click on "Clear browsing data."
6. Select the "Cache" and "Cookies" options.
7. Click on "Clear data."

Here are the steps on how to contact Amazon support:

1. Go to the Amazon Seller Central website.
2. Click on the "Help" tab.
3. Select "Contact Us."
4. Select the "Selling Partner API" option.
5. Select the "Technical Support" option.
6. Fill out the contact form and submit it.

I hope this [dalda.com.au](https://dalda.com.au/) helps!
