### ISSUE TITLE
[Issue] order_item_id OrderItemId changed but OrderAdjustmentItemId did not change

### ISSUE THREAD

**Issue by HardBrick21** [amzn/selling-partner-api-docs#2836]
####  OrderItemId changed but OrderAdjustmentItemId did not change in RefundEventList, How to determine the corresponding relationship？

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[√] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by llxdxwd** [comment]
终于看到有人吐槽了。解决我两天了，还是有报告匹配不了。估计很多系统莫名多了很多销售额→_→。。。

**Comment by zengzhengtx** [comment]
排查了半天，一直在找自己的原因，以为是某些场景没考虑周全……心塞～

**Comment by archucheer** [comment]
我也在找个BUG，以为客户什么特殊操作导致的

**Comment by freedom64life** [comment]
this a good question，amazon engineers tell me why????

**Comment by jeremy-dragonfly** [comment]
Changing order IDs is causing massive problems for us too. We saw it start happening just within the last few days, is everyone else seeing the same thing? So far no useful information from support.

**Comment by sungolivia** [comment]
Please follow the issue template, otherwise this issue will be closed. Can you also put the English translation in the issue title as well? Thanks!

**Comment by GJ-JG** [comment]
Internally we have fixed this bug but the system may need some time until it reflects to all developers. Please leave your comment if still experiencing the issue.

**Comment by jeremy-dragonfly** [comment]
That's great news - can you clarify whether the order item IDs will be changing back to their original values? Or will the new order item IDs remain?

**Comment by mysaber** [comment]
> Internally we have fixed this bug but the system may need some time until it reflects to all developers. Please leave your comment if still experiencing the issue.

fixed？It is not fixed before it is released.

**Comment by archucheer** [comment]
> 

Could you please tell us the start time when the change of the order Item ID will have an impact? It will help us troubleshoot the problem

**Comment by archucheer** [comment]
> Please follow the issue template, otherwise this issue will be closed. Can you also put the English translation in the issue title as well? Thanks!

Could you please tell us the start time when the change of the order Item ID will have an impact? It will help us troubleshoot the problem

**Comment by HardBrick21** [comment]
This issue only influences the US region？

**Comment by rangyf** [comment]
> This issue only influences the US region？

yes, our data from other regions is not affected

**Comment by HardBrick21** [comment]
我服了  又出现了了  这次还不止美国站了 欧洲站也有了  30号开始更新的订单item id又变了

**Comment by fengzidk** [comment]
> This issue only influences the US region？

Affects at least NA regions,There may be problems with all data about order items: report, finance and order Api

**Comment by HardBrick21** [comment]
> > This issue only influences the US region？
> 
> Affects at least NA regions,There may be problems with all data about order items: report, finance and order Api

@fengzidk  We are seeing the same behavior in other region  today.  EU region

**Comment by mgimena** [comment]
The SP API Health Dashboard shows that the issue is corrected; however, when inspecting the data returned by the API, we can see that the Orders API for a specific order has the correct original OrderItemID, but the corresponding Finances API for that order still shows a wrong OrderItemId.

Affects both NA and EU regions. 

Is anybody seeing the same behavior?

**Comment by HardBrick21** [comment]
> The SP API Health Dashboard shows that the issue is corrected; however, when inspecting the data returned by the API, we can see that the Orders API for a specific order has the correct original OrderItemID, but the corresponding Finances API for that order still shows a wrong OrderItemId.
> 
> Affects both NA and EU regions.
> 
> Is anybody seeing the same behavior?

yes we are

**Comment by sungolivia** [comment]
Hey team, our team is aware of this issue with regards to Finance API, that should be reflected in our [health dashboard](https://sellercentral.amazon.com/sp-api-status).
![Screenshot 2023-02-21 at 8 51 00 AM](https://user-images.githubusercontent.com/7606170/220408805-ee515334-b8bd-43f1-a57e-272224525a1a.png)

**Comment by jason1004** [comment]
5月1号之后，欧洲市场再次出现OrderItemID 变化的问题

**Comment by chrischeer** [comment]
@sungolivia  The problem with the orderItemId change appeared again in 'Operation: getOrderItems', and this time in the European market on May 1st. So we had to develop a data comparison program to correct the data. May I ask whether your team has noticed this situation

**Comment by JsonSong89** [comment]
today is 6/8 , the bug appeared again... 
what the f**k they are doing ?
