### ISSUE TITLE
Amazon Order Item Personalization JSON File named NULL now

### ISSUE THREAD

**Issue by thebest0f** [amzn/selling-partner-api-docs#2839]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2838

<div type='discussions-op-text'>

<sup>Originally posted by **thebest0f** January  9, 2023</sup>
As of yesterday, the filename for the personalization specs started coming back as "null.json"

Anyone know why?</div>

**Comment by sungolivia** [comment]
closing due to duplicate post https://github.com/amzn/selling-partner-api-docs/discussions/2838
