### ISSUE TITLE
What is the reason that the order address interface does not get name and AddressLine1?

### ISSUE THREAD

**Issue by GuoCHong0210** [amzn/selling-partner-api-docs#284]
I can see the relevant information of the order in the seller's center. I tried many order numbers, but they are all the same problem.Only the four fields of stateorregion, city, countrycode and postalcode have data.

**Comment by yohanbrg** [comment]
Hello @GuoCHong0210 , This [issue](https://github.com/amzn/selling-partner-api-docs/issues/72) could help you, I encountered the same problem.

**Comment by GuoCHong0210** [comment]
> 您好@ GuoCHong0210，这个[问题](https://github.com/amzn/selling-partner-api-docs/issues/72)可以帮助您，我遇到了同样的问题。

Thank you very much. How can we solve it?

**Comment by 9z** [comment]
> > 您好@ GuoCHong0210，这个[问题](https://github.com/amzn/selling-partner-api-docs/issues/72)可以帮助您，我遇到了同样的问题。
> 
> Thank you very much. How can we solve it?

I wonder too!!
How can I get buyer address??

**Comment by GuoCHong0210** [comment]
> > > 您好@ GuoCHong0210，这个[问题](https://github.com/amzn/selling-partner-api-docs/issues/72)可以帮助您，我遇到了同样的问题。
> > 
> > 
> > 非常感谢你。我们该如何解决呢？
> 
> 我也想知道！
> 我如何获得买家地址？

It seems that the reason has been found, and the corresponding role needs to be checked in the developer data.[https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md](url)
