### ISSUE TITLE
[BUG] [SP-API] [Issue] SPAPI returning "No results" even if the product exists

### ISSUE THREAD

**Issue by saulocastelo-wiser** [amzn/selling-partner-api-docs#2853]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Searching on Amazon (**https://www.amazon.com/s?k=redkap+PT2A**) (**https://www.amazon.com/Red-Kap-Mens-Shop-Black/dp/B00O4WAQE0/ref=sr_1_1?keywords=red+kap+pt2a&qid=1673551319&sr=8-1**) I got a lot of results.

But using the API I get ZERO results {"numberOfResults":0,"items":[]}

## SP-API Name and Version or Report/Feed Type
**https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?keywords=redkap+PT2A&marketplaceIds=ATVPDKIKX0DER&includedData=identifiers,images,summaries,salesRanks**

## Expected Behavior

Should list the current searched product like the Web Search

## Current Behavior

No results are returned for the keywords redkap+PT2A.

No errors returned

Tested in ATVPDKIKX0DER

## Context/Screenshots

Not returning the products list, means that it doesn't exist, so it can't be bought.

**Comment by sungolivia** [comment]
If you are able to paste in the request details, that would help!

**Comment by tkalagbada** [comment]
@sungolivia What kind of request details are you wanting? The URL we shared already has information about the resource we are trying to reach, the rest of the request is just authentication data which is private.

**Comment by tkalagbada** [comment]
@sungolivia do we have any update on the above issue or question?

**Comment by rugved1991** [comment]
Hi @tkalagbada,

The Selling Partner API doesn’t mimic the search on Amazon.com. Please try searching with keywords “Red Kap” instead. If you are still seeing issues, please open a developer support case with the complete request response details along with headers.

Best,
Rugved
Solutions Architect, SP API
