### ISSUE TITLE
400 Bad Request - POST - /fba/outbound/2020-07-01/fulfillmentOrders - CreateOrderFulfillment API

### ISSUE THREAD

**Issue by benpeterswake** [amzn/selling-partner-api-docs#286]
"Method":"POST 
 "URL: "https://sandbox.sellingpartnerapi-na.amazon.com/fba/outbound/2020-07-01/fulfillmentOrders"

I am able to make requests to inventory api and the order api and it works, however for some reason any request to fulfillmentOrders (including /fulfillmentOrders/preview) fails. The response is as follows:

```
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>
```

I have tried in prod and sandbox environment, but i get the same result. I've checked my headers and my request body, but nothing makes a difference. It's almost like the endpoint just isn't accessible for me. Any ideas?

**Comment by yan15195755798** [comment]
400,一般情况下是缺少参数

**Comment by benpeterswake** [comment]
What role is required for this endpoint (fba/outbound/2020-07-01/fulfillmentOrders)?
I found this list (https://github.com/amzn/selling-partner-api-docs/tree/main/guides/roles), but it does not mention outbound fulfillment orders.

**Comment by liuzhaodong89** [comment]
我也遇到了一样的问题，所有的入参基本都填写完了但是依然报400错误
