### ISSUE TITLE
[Issue] [SP-API] 403 forbidden after an hour (report api)

### ISSUE THREAD

**Issue by ASchmidtGit** [amzn/selling-partner-api-docs#2872]
``## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

Report API:
- GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
- get_v2_settlement_report_data_flat_file

https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/documents/amzn1.spdoc.1.4.eu.6dde8110-7f4e-4cdc-8981-9e2f701b54f7.T135ND9ACUT3YX.1117?MarketplaceIds=A1PA6795UKMFR9

## Current Behavior
I set up ASP as source and mysql as destination in airbyte.
I can sync tables like "get_amazon_fulfilled_shipments_data_general" but if i try to get the "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL" or "get_v2_settlement_report_data_flat_file" report it fills the temp table and transform a good chunk of it but after an hour i get this error:

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/documents/amzn1.spdoc.1.4.eu.6dde8110-7f4e-4cdc-8981-9e2f701b54f7.T135ND9ACUT3YX.1117?MarketplaceIds=A1PA6795UKMFR9`

Logs for sync of GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
[16ce1edb_e6f9_4500_8b47_79e03fa45ebd_logs_102_txt.txt](https://github.com/amzn/selling-partner-api-docs/files/10457438/16ce1edb_e6f9_4500_8b47_79e03fa45ebd_logs_102_txt.txt)

Logs for sync of get_v2_settlement_report_data_flat_file
[16ce1edb_e6f9_4500_8b47_79e03fa45ebd_logs_97_txt.txt](https://github.com/amzn/selling-partner-api-docs/files/10457439/16ce1edb_e6f9_4500_8b47_79e03fa45ebd_logs_97_txt.txt)

## Context/Screenshots
I want to get the orders and fees etc. for the last 25 Months to implement them into dremio and superset.

## Your Environment
OS Version / Instance: Ubuntu
Memory / Disk: 100 GB
Deployment: Docker Swarm
Airbyte Version: 0.40.26
Source name/version: Amazon Selling Partner v. 0.2.30
Destination name/version: MySQL v. 0.1.20   (Mysql v. +8)

My SPI-API policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}
```

Is version 2012-10-17 still correct? Since the report url states version 2021-06-30?

Im confused that i get this error an hour and several hundred MBs into the sync, so it doesnt sound like a permission problem to me but i could be wrong.

EDIT:
These are my current policies in my role:
![image](https://user-images.githubusercontent.com/83596606/213469724-e52ceef3-de16-4965-a201-832cfecb6d15.png)

I just saw that there is a policy called "AmazonMobileAnalyticsFinancialReportAccess" which i could add. 
I will try it with this policy added to my role or should i add it as directly to the user as permission?

But if this is the source of the problem i dont understand how the 403 error gets thrown an hour into it

EDIT 2: 
I added the policy "AmazonMobileAnalyticsFinancialReportAccess" to my used role but get the same error

**Comment by sungolivia** [comment]
@ASchmidtGit closing this issue as you mentioned it's an error in the airbyte connector. If you think otherwise, feel free to reopen!
