### ISSUE TITLE
[BUG] [SP-API] [Issue] Something went wrong MD5200

### ISSUE THREAD

**Issue by DevBrent** [amzn/selling-partner-api-docs#2876]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:

## SP-API Name and Version or Report/Feed Type
OAuth

## Expected Behavior
Users should be able to reauthorize their store using the SP-API OAuth flow.

## Current Behavior
The user is instead greeted with an MD5200 error which can't be found on GitHub. This appears to have only started today, and for this user is able to be reproduced consistently. It is unknown if other users are impacted.

## Context/Screenshots

The user is currently unable to sync orders, fulfill orders, or keep their inventory accurate. This can directly impact seller performance guidelines and penalize the merchant.

![image](https://user-images.githubusercontent.com/4075001/213765778-856d0826-52e9-4153-b112-b73299f1467c.png)

**Comment by puppsupr** [comment]
Hi DevBrent@
In order to correctly resolve it, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
