### ISSUE TITLE
Where is "Units expected" and "Units located" for inbound shipments in the RECEIVING status?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#2880]
Where is "Units expected" and "Units located" for inbound shipments in the RECEIVING status?

Those field are visible on the https://sellercentral.amazon.com/fba/inbound-shipment/summary/FBAxxxxxxxxx/contents page.  However, searching the API documentation, I see nothing on those terms.

See also bug #425 which is a similar sort of field missing from the https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference docs.

It's unclear whether this is intentionally not provided, in which case this is a "Feature request", or if it's just badly documented, in which case it's a "Bug report" or "Documentation issue or request"

**Comment by johnkw** [comment]
Why was this closed? What is the resolution here?

What should the documentation say?  That it's intentionally missing this feature, or that it should be there?

**Comment by johnkw** [comment]
What is the actual resolution here? I'm concern now that this is "closed" it's been lost.

**Comment by bijbara0827** [comment]
Hi @johnkw  did you find any answer for this ? i am also facing same issue ?

**Comment by johnkw** [comment]
See #bug 2903

**Comment by johnkw** [comment]
See bug #2903

**Comment by phstc** [comment]
Hi @sungolivia 

I did submit it from the voting section you shared "Did this page help you?". 

Do you have any update here or on #2903?
