### ISSUE TITLE
[BUG] [SP-API] [Issue] Sandbox request correct parameters

### ISSUE THREAD

**Issue by Xriuk** [amzn/selling-partner-api-docs#2882]
Why the request parameters of the sandbox API do not match the requirements of the API itself?
If `/orders/v0/orders` requires `CreatedAfter` to be a string which "[...] must be in ISO 8601 format." and I create some validation on my side in order to send out correct requests, how am I supposed to send `"TEST_CASE_200"` as a valid ISO 8601 string value?
Any other date would have been fine...

**Comment by rugved1991** [comment]
Hi @Xriuk,

Thanks for sharing feedback. The sandbox endpoint is used to only test if you are able to make connect and make a successful call with the API. The request and response parameters are static and are to be used only to check for valid HTTP responses on the API.

Best,
Rugved
Solutions Architect, SP API
