### ISSUE TITLE
[BUG] [SP-API] [Issue] Shipping API Get Rates

### ISSUE THREAD

**Issue by defenderjim** [amzn/selling-partner-api-docs#2890]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
GetRates() v2
[https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference#getrates](https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference#getrates)

I
 `POST to /shipping/v2/shipments/rates`

I am getting the error 
`Invalid input : The currency unit passed into the request is invalid`

I am passing: ` insuredValue = new Currency { unit = "USD", value = 154 }`

## Expected Behavior

Should get successful response of GetRatesResponse

Should accept  ISO 4217 as per the docs, which is what I am using.

## Current Behavior

`Invalid input : The currency unit passed into the request is invalid`

This is the error, happens every time.

## Your Environment

Here is the full json body:
```

{
    "shipTo": {
        "stateOrRegion": "IL",
        "name": "Test Bob",
        "addressLine1": "100 Main St.",
        "city": "Chicago",
        "countryCode": "US",
        "postalCode": "60185"
    },
    "shipFrom": {
        "stateOrRegion": "MD",
        "email": "bob@xx.com",
        "phoneNumber": "301xxxxxx2",
        "name": "Test Frank",
        "addressLine1": "1100 Main St.",
        "city": "Rockville",
        "countryCode": "US",
        "postalCode": "20850"
    },
    "shipDate": "2023-01-28T12:00:00Z",
    "packages": [{
            "dimensions": {
                "length": 48.0,
                "width": 40.0,
                "height": 22.0,
                "unit": "INCH"
            },
            "weight": {
                "value": 4.0,
                "unit": "POUND"
            },
            "insuredValue": {
                "value": 30.0,
                "unit": "USD"
            },
            "isHazmat": false,
            "packageClientReferenceId": "asdf",
            "items": [{
                    "itemIdentifier": "xxxxxxxxxxxxxx",
                    "quantity": 7,
                    "weight": {
                        "value": 0.09,
                        "unit": "POUND"
                    },
                    "isHazmat": false
                }
            ]
        }
    ],
    "channelDetails": {
        "channelType": "AMAZON",
        "amazonOrderDetails": {
            "orderId": "113-xxxxxx-xxxxxx"
        }
    }
}

```

**Comment by defenderjim** [comment]
Error message is misleading.
If I add the following to the item detail, then it works.
` itemValue = new Currency { unit = "USD", value = 30`

**Comment by Ziyun-KyLin** [comment]
I also encountered this problem
