### ISSUE TITLE
How to get ShipmentId for Order?

### ISSUE THREAD

**Issue by marcelvossmint** [amzn/selling-partner-api-docs#2897]
Is there any way to get the shipmentId for an already shipped order?

Otherwise there seems to be no option to get the shipment oder label from the shipment resource, as the shipmentId is required.

e.g. call this action:

https://developer-docs.amazon.com/sp-api/docs/shipping-api-v1-reference#get-shippingv1shipmentsshipmentid

**Comment by GJ-JG** [comment]
Hi @marcelvossmint , shipmentId was created and returned in the response when calling [createShipment](https://developer-docs.amazon.com/sp-api/docs/shipping-api-v1-reference#createshipment) API. And please know what order ID is not passed in createShipment API, which means you need to create a key-value pair in your system to store order ID and shipment ID. With this, you are able to fetch shipment information using order ID.

**Comment by RiccardoRizzini** [comment]
Is it the only way? Cause the shipment was send manually.
I've the same problem but doesn't seems there is a solution

**Comment by hudson940** [comment]
I also need to get the shipping label for an order that already has the label generated within the seller central platform, do you found a way to do that?
