### ISSUE TITLE
@doverradio

### ISSUE THREAD

**Issue by sweetdream34310** [amzn/selling-partner-api-docs#2899]
@doverradio 
I am developing the amazon pricing management software and using the sp api.
I want to update the regular price (Estimated fee per unit sold) with sku, not business price

I wrote like this and it is working correctly for the UK , but not working for EU( DE, FR, IT, ES, NL, SE, PL ... )

```
        patch_data = {
            "productType":
            "PRODUCT",
            "patches": [
               {
                op: "replace",
                path: "/attributes/purchasable_offer",
                value": [{
                    marketplace_id : marketplaceId,
                    currency: currency,
                    our_price: [{
                        "schedule": [{
                            "value_with_tax": parseFloat(price)
                        }]
                    }]
                }]
            }]
        }
```

I am not sure why it is working for the UK but not working for others.
Please help me.
Thank you.

**Comment by sungolivia** [comment]
Please follow the issue template otherwise this issue will be closed!
