### ISSUE TITLE
Missing "Cancel" button (Seller Consents to Authorize Application)(Vague Docs)

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-docs#29]
In the SP-API docs under "Authorizing Selling Partner API applications" => "Website workflow" => "Step 2" it states:

"The seller views the consent page, reviews the data access requested by your application, and then clicks the Confirm button to continue. **The seller can click the Cancel button to exit without authorizing.**"

**The mentioned "Cancel" button is missing.** (see attached pic) This happens when testing with "&version=beta". It could also happen in prod but I haven't gotten that far yet.

I'm wondering what the default handling of this should be. I don't notice anything in the docs which states anything other than what is already quoted in this issue. There is no OAuth CancelRedirect URI to add when registering your application. So I'm guessing when the "Cancel" button is actually present and then clicked they'll be redirected back to the "OAuth Redirect URI" without the usual "spapi_oauth_code" in the response. We could of course handle it like that, if that's the case, although better ways to handle it do come to mind. Of course, I cannot test if that is the case since the "Cancel" button is missing. Looking forward to some direction. Thanks guys.

<img width="1920" alt="Screen Shot 2020-10-06 at 3 52 54 PM" src="https://user-images.githubusercontent.com/22284644/95269786-06f17e00-07ef-11eb-9915-39a58380cd4f.png">

**Comment by ShivikaK** [comment]
Hello,

The cancel button is not available on the consent page. We are working on correcting the developer guide with this information.

To cancel the workflow (if needed), you can directly close the consent page.

**Comment by ShivikaK** [comment]
Thanks for the feedback. We are actively considering how to support use cases like you have described.

**Comment by edaik** [comment]
Hi @charliecode , we are working to improve the auth cancellation experience currently and wanted to confirm an improved experience with the community. Currently, the authorization workflow can be triggered from Developers' websites or the appstore in Seller Central. When triggered, the OAuth workflow opens a new tab with the SC login/consent screen. The simplest implementation of the cancel button simply closes the window - with the original page/tab where authorization was initiated from still being present (whether on your website or your apps detail page in the seller central appstore).

Per your comment above, do you think a cancel button + alert/pop up that no permissions were granted will address potential customer concerns?

Appreciate the feedback!

**Comment by charliecode** [comment]
Hey @edaik. I can't speak as much to suggestions for the app store in Seller Central, as I haven't implemented that flow. As for the website flow, I respectfully don't think opening a new tab for the initial redirect to Seller Central is the way to go, at least for website flow. Opening new tabs for auth sends a message, whereas a simple redirect is a more seamless UX. Of course, it will be up to the individual dev on how they will implement the redirect to SC for the website flow. Whereas I believe you'll redirect the user to the client app for the app store flow. But if others engineer it like I will (no new tab) and the cancel button closes the page then that means the user needs to be interested (or worried) enough to manually get back into the app. 

Regardless, I'm not sure there is much value in a popup confirming cancellation as I believe clicking cancel will suffice, for either flow. Where I see the real value in allowing devs to add a "CancelRedirectURI" is the fact that just because a person clicks the cancel button, it doesn't necessarily mean they are not interested in the app. Perhaps that's what you guys are concerned about, if the person clicks cancel, it's "game over" and maybe you would prefer to not redirect the user back to the app. I could also see the extra work it would take because you'd need to split up the flow for the app store and website flows as it would probably be out of the question to redirect a user to the app after clicking cancel on the app store flow. However that could be taken care of by a simple redirect to apps app store page.

**But there is a single very real difference between the two flows here.** In the website flow, the user will have already signed up for the app and in some cases maybe even given credit card info (I won't ask for card info until SP-API creds are established, but some will). However, this really doesn't matter because either way it leaves the question open ended for the user, even though they clicked cancel for the creds, what happens back in the app now if the screen just disappears? This is where a "CancelRedirectURI" could help a ton for the website flow. Redirecting the user back to the app along with some sort of "cancel=true" param in the URL along with the "state" token gives the app the ability to either help convince the user that their data is safe with us, help the user cancel their newly created account, get rid of possible credit card data they may have given or a host of other things. This is why I think there would be a great benefit to both Amazon, the app and most importantly the consumer in adding this "CancelRedirectURI" and passing back the above mentioned params. Or something along those lines. Just my two cents and I am only a single opinion.

**Comment by edaik** [comment]
Thanks for the detail here. The suggestion of the "CancelRedirectURI" would be a net new feature in our auth flow. It's not come up with early adopters who implemented the website flow to date, but its interesting. 

As it stands today, if the user originates on the Dev website, they are logged in (and generally looking at a "login and authorize on Amazon" button with the accompanying instruction provided by the Developer). As the auth workflow is a separate tab today, if closed out or canceled the Seller still has open either 1) the Developers website or 2) Appstore detail page.

The addition of the currently missing cancel button is fairly lightweight and fills an identified gap. Happy to continue the discussion or get additional thoughts from the community on taking an additional 'CancelRedirectURI' and the experience it would enable.

**Comment by charliecode** [comment]
I'm not sure if there was a decision made to remove the original issues Cancel button and the docs just haven't been updated or if the docs are still correct and the Cancel button still needs added. But having come back to check this after a few months and the ambiguity is till there.

**Comment by rugved1991** [comment]
The Cancel button has been added to the consent page. Resolving this issue.

**Comment by phstc** [comment]
@rugved1991 I see the cancel button for the website workflow, but it links nowhere. I couldn't find an option to configure a cancel URL. 

How can I add a link to that button? 

![image](https://github.com/amzn/selling-partner-api-docs/assets/105652/caf20a00-02de-4fea-9a91-5854815d63e0)

The docs mention a "Cancel" link https://developer-docs.amazon.com/sp-api/docs/website-authorization-workflow but with no configuration for it.
