### ISSUE TITLE
Developer ID XXXXXXXXXXX is not associated with the application id

### ISSUE THREAD

**Issue by nicole-z91** [amzn/selling-partner-api-docs#2912]
Hi Amazon team,
We are a provider and we're migrating from mws to sp api, and we have met the following error when calling the 'Get authorization code' API:
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Developer ID 512415334568 is not associated with the application id.",
            "details": ""
        }
    ]
}

Our APP is published for long time. Also we intended to submit a case in the seller central while failed because a few information is required but on the page we're not able to input anything.
Could you please check if anything is alright with our developer ID, thank you!

**Comment by sungolivia** [comment]
Since you have to provide your developer ID, I would recommend contacting our developer support for this case!
https://developer.amazonservices.com/support

Check out the guideline so you can get answers you need!
https://developer.amazonservices.com/support-guidelines
