### ISSUE TITLE
[BUG] [SP-API] [Issue]Reports Api returns no data of GET_LEDGER_SUMMARY_VIEW_DATA report 

### ISSUE THREAD

**Issue by lyndon2333** [amzn/selling-partner-api-docs#2918]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Reports Api 
we use Reports Api to fetch GET_LEDGER_SUMMARY_VIEW_DATA report, and it worked fine before, but it returns no data of 'us-east-1' region account since 2023-02-10.

Request succeeded, but there is only 1 row (which is column name) in document content, and we can get full report data in report document whitch is dowloaded directly from Amazon, that means api should put these data in report document.

But same code works fine for accounts of eu-west-1 region.

**Comment by puppsupr** [comment]
Hi,
Are you still seeing issues ? If yes, can you please open a [support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) including your complete request, response details.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by weianguo** [comment]
`{
    "reportType": "GET_LEDGER_SUMMARY_VIEW_DATA",
    "marketplaceIds": ["ATVPDKIKX0DER"],
    "dataStartTime": "2023-03-01T00:00:00Z",
    "dataEndTime": "2023-03-01T23:59:59Z",
    "reportOptions": {
        "aggregateByLocation": "COUNTRY",
        "aggregatedByTimePeriod": "DAILY"
    }
}`
I've also encountered this issue where using GET_LEDGER_SUMMARY_VIEW_DATA returns empty data (just headers), while using GET_LEDGER_DETAIL_VIEW_DATA has no problem and can return the data.

**Comment by PratikshaAher29** [comment]
Hello,I am facing same issue. Do you have any solution? If yes,please share

**Comment by NA-Dev** [comment]
"body": {
                "reportType": "GET_LEDGER_SUMMARY_VIEW_DATA",
                "dataStartTime": "2023-03-01T00:00:00Z",
                "dataEndTime": "2023-03-01T23:59:59Z",
                "reportOptions": {
                    "aggregateByLocation":"COUNTRY",
                    "aggregatedByTimePeriod":"DAILY"
                }
            }

**Comment by mtkumar82** [comment]
As per Amazon SP APi documentation (https://developer-docs.amazon.com/sp-api/changelog/deprecation-notice-suppressed-listings-reports-and-fba-inventory-reports ) below Reports will no longer be available, 

Effective  January 31, 2023, the following reports will no longer be available in MWS or Selling Partner API:

    GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA
    GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA
    GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA
    GET_FBA_RECONCILIATION_REPORT_DATA
    GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA
    GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA

Can Anybody please help me to send the replacement reports for each of the above one?
