### ISSUE TITLE
[BUG] [SP-API] [Issue] GetPrepInstructions fails for skus with special characters

### ISSUE THREAD

**Issue by ericahrowe** [amzn/selling-partner-api-docs#2925]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP-API FbaInbound AP v0: getPrepInstructions

## Expected Behavior

The API should return PrepInstructions, including the SKUPrepInstructionsList for all valid, active SKUs provided in the SellerSKUList in the request. A special characters in the SKUs, including comma, plus sign, equal sign, and/or semi-colons should not cause the API to fail to properly identify the SKUs in the list.

## Current Behavior

If we provide a list of SellerSKUList SKUs, and any of the SKUs contain one of the following special characters:  , ; + (comma, semi-colon, plus sign, equals sign), the system fails to recognize those characters as part of the SKU, and returns no data or invalid data (if a similar SKU exists) for those SKUs.

This API requires passing the SellerSKUList as a query string parameter. Even HTML-encoding the query string parameter does not provide the correct response.

As we have just implemented this API in the past month, we only know that it has been happening since January 2023, but we have seen similar bug reports, like this one: https://github.com/amzn/selling-partner-api-docs/issues/2490

We have tried the workaround suggested in issue 2490, and it has not solved our problem.

Example using Postman with automatic Query String Encoding:
https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/prepInstructions?ShipToCountryCode=US&SellerSKUList=RSK3301-BLAK-5,6

Response:
{
    "payload": {
        "SKUPrepInstructionsList": [],
        "InvalidSKUList": [
            {
                "SellerSKU": "RSK3301-BLAK-5",
                "ErrorReason": "DoesNotExist"
            },
            {
                "SellerSKU": "6",
                "ErrorReason": "DoesNotExist"
            }
        ]
    }
}

In the case of a comma in the SKU, the API seems to treat the SKU as two SKUs. In other cases, the special character is replaced by a space:
https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/prepInstructions?ShipToCountryCode=US&SellerSKUList=CA105043+BZ175003

{
    "payload": {
        "SKUPrepInstructionsList": [],
        "InvalidSKUList": [
            {
                "SellerSKU": "CA105043 BZ175003",
                "ErrorReason": "DoesNotExist"
            }
        ]
    }
}

## Context/Screenshots

Our application allows our sellers to create inbound shipments to Amazon via the MWS inbound shipment APIs. These APIs require valid prep instructions be provided for each SKU in the inbound shipment.

After the MWS deadline, our users will still be able to download a Send to Amazon file, which also requires information about the prep instructions for the SKUs in the inbound shipment. At present, we can only get ASIN-level prep instructions for any SKUs that contain the referenced special characters. This does not provide our sellers with all the data they require in our system in order to create a valid SendToAmazon upload file.

Almost 1/3 of our sellers are affected by this bug.

**Comment by rugved1991** [comment]
Hi @ericahrowe,

Thanks for reaching out. This is a known issue and it is important to make sure you are encoding the SKU before sending in the request. Please refer to this documentation for more information on URL encoding: https://developer-docs.amazon.com/sp-api/docs/url-encoding

If you are still seeing the same issue after URL encoding, please open a developer support case using the below link: https://developer.amazonservices.com/support

I hope this helps.
Have a great day!

Best,
Rugved 
Solutions Architect, SP API
