### ISSUE TITLE
[BUG] [SP-API] [Issue] Fulfillment Inbound API v0 - getTransportDetails doesn't return mandatory field value AmazonReferenceId

### ISSUE THREAD

**Issue by 2DWorkflow** [amzn/selling-partner-api-docs#2926]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Fulfillment Inbound API v0 / getTransportDetails

## Expected Behavior

By calling getTransportDetails for LTL-partnered shipments we are expected to get a PartneredLtlDataOutput
(Information returned by Amazon about a Less Than Truckload/Full Truckload (LTL/FTL) shipment by an Amazon-partnered carrier.)

Including field:
AmazonReferenceId (required) - A unique identifier created by Amazon that identifies this Amazon-partnered, Less Than Truckload/Full Truckload (LTL/FTL) shipment.

## Current Behavior

There's no value returned in the response for the AmazonReferenceId field 

## Context/Screenshots

{
  "payload": {
    "TransportContent": {
      "TransportHeader": {
        "SellerId": ".......",
        "ShipmentId": "......",
        "IsPartnered": true,
        "ShipmentType": "LTL"
      },
      "TransportDetails": {
        "PartneredLtlData": {
          "Contact": {
            "Name": "Alex",
            "Phone": "+1800000",
            "Email": "testship@gmail.com"
          },
          "BoxCount": 1,
          "FreightReadyDate": "Wed Feb 15 00:00:00 GMT 2023",
          "PalletList": [
            {
              "Dimensions": {
                "Length": 40.0,
                "Width": 48.0,
                "Height": 40.0,
                "Unit": "IN"
              },
              "Weight": {
                "Value": 150.0,
                "Unit": "pounds"
              }
            }
          ],
          "SellerDeclaredValue": {
            "CurrencyCode": "USD",
            "Value": 10.0
          },
          "PreviewPickupDate": "Wed Feb 15 00:00:00 GMT 2023",
          "PreviewFreightClass": "70.0",
          "PartneredEstimate": {
            "Amount": {
              "CurrencyCode": "USD",
              "Value": 101.27
            },
            "ConfirmDeadline": "2023-02-13T12:39:25Z",
            "VoidDeadline": "2023-02-13T13:10:00Z"
          }
        }
      },
      "TransportResult": {
        "TransportStatus": "CONFIRMED"
      }
    }
  }
  
## Your Environment

We have an application for Amazon inbound shipment creation.

**Comment by dmelendez35** [comment]
@2DWorkflow , did you find out why is this happening?
