### ISSUE TITLE
[Question] How to make a request specifying a range of PurchaseOrderDate

### ISSUE THREAD

**Issue by Naoyuk** [amzn/selling-partner-api-docs#2932]
```
limit=100&createdAfter=2023-02-01T00:00:00.000Z&2023-02-08T00:00:00.000Z&sortOrder=DESC
```
I would think that requesting the query getPurchaseOrders would narrow the range of PuchaseOrderDate from `2023-02-01T00:00:00.000Z` to `2023-02-08T00:00:00.000Z`.
In reality, however, the response may include orders that are outside the range.
For example, sometimes, the response include an Order in 2021 that has already been closed.
Please tell me how to make a request specifying a range of PurchaseOrderDate under the above conditions.

**Comment by puppsupr** [comment]
Hi,

Can you please provide me the complete request details ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by Naoyuk** [comment]
Hi, Supriya

Thanks for replying.

This is the request details.

`https://sellingpartnerapi-na.amazon.com/vendor/orders/v1/purchaseOrders?createdAfter=2023-02-15T00%3A00%3A00.000&createdBefor=2023-02-22T00%3A00%3A00.000&limit=100&sortOrder=DESC`

**Comment by puppsupr** [comment]
Hi @Naoyuk,

Are you requesting the details in right way as per https://developer-docs.amazon.com/sp-api/docs/vendor-orders-api-v1-model ?

If you still see wrong order range, please provide your complete request and response details which shows wrong range of orders to check further.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
