### ISSUE TITLE
[BUG][SP-API]The report for the Belgium site returned an error

### ISSUE THREAD

**Issue by xiazhaozhao** [amzn/selling-partner-api-docs#2939]
Hello,
    The report for the Belgium site returned an error,reporttype:GET_SALES_AND_TRAFFIC_REPORT
error Message:
[{"code":"InvalidInput","message":"Report rejected for this client. Some of the marketplaces are not allowed for this Report","details":""}]

**Comment by discover59** [comment]
Same error for me.

**Comment by EpicPantz** [comment]
Hello, I have the same error. A list for all marketplaces that's unavailable would be great :)

**Comment by killuazoldyck1910** [comment]
Did anyone find the answer to this problem? I have the same error only for Belgium

**Comment by jimmy-ross-xapix** [comment]
i also have the same problem

**Comment by Raaghav-DC** [comment]
Was anyone able to figure this out?

**Comment by gg1198** [comment]
Did anyone get the report data successfully?

**Comment by ritikacd** [comment]
Hi @xiazhaozhao @gg1198 @Raaghav-DC @jimmy-ross-xapix @killuazoldyck1910 @discover59  @EpicPantz 

Thanks for reaching out. 

Selling Partner API team recently released a fix to resolve this issue, you should be able to request [Sales and Traffic Business Report](https://github.com/amzn/selling-partner-api-models/blob/main/schemas/reports/sellerSalesAndTrafficReport.json) in Belgium marketplace now successfully. 

Thanks,
Ritika Chaudhary
Selling Partner API Team

**Comment by gg1198** [comment]
Now it works fine for me.
Thanks, @ritikacd .
