### ISSUE TITLE
[BUG] /fba/inventory/v1/summaries inaccurate data

### ISSUE THREAD

**Issue by WXinFfly** [amzn/selling-partner-api-docs#294]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**
By calling /fba/inventory/v1/summaries API, it is found that there is a great delay in getting inventory data and background data, some of which are about two days late

**Comment by WXinFfly** [comment]
Hi @charliecode, can you help me to answer

**Comment by dlfajen** [comment]
In addition to the out-of-date data, it also seems to be returning data that is not in the specified marketplace. We are getting results back from both Mexico and Canada, but only the US marketplace was requested.

https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&startDateTime=2021-01-01T01%3A25%3A47.825-18%3A00&marketplaceIds=ATVPDKIKX0DER

Results include both US, Mexico, and Canadian SKUs, but oddly the quantity is the same for all.
