### ISSUE TITLE
[BUG] [SP-API] [Issue] getMyFeesEstimateForASIN isn't passing the [ListingPrice.Amount]

### ISSUE THREAD

**Issue by iololife** [amzn/selling-partner-api-docs#2942]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
Getting "Missing objects [ListingPrice.Amount] in body parameters" error while calling feesApi.getMyFeesEstimateForASIN(getMyFeesEstimateRequest,"##########"). I currently do not carry the ASIN in my inventory.

## SP-API Name and Version or Report/Feed Type
Product Fees API v0

## Expected Behavior

I should get a GetMyFeesEstimateResponse

## Current Behavior

I'm getting an "InvalidInput" error with details stating that "Missing objects [ListingPrice.Amount] in body parameters" even though I've specified ListingPrice.Amount in a FeesEstimateRequest object.

## Context/Screenshots

<img width="656" alt="Screenshot 2023-02-20 at 7 53 18 PM" src="https://user-images.githubusercontent.com/94832286/220243933-0da87588-7cf3-4bfb-84a6-dd63a353c0d7.png">
<img width="1159" alt="Screenshot 2023-02-20 at 7 53 37 PM" src="https://user-images.githubusercontent.com/94832286/220243952-b2e5ab83-f477-4896-81d5-c6cf979af457.png">

## Your Environment

MacStudio / Apple M1 Max / Ventura 13.1 / JDK 17

**Comment by rugved1991** [comment]
Hi @iololife,

Thanks for reaching out. Can you please confirm if you are able to make a successful call to the API endpoint using Postman? 
If you are only seeing an issue with calling this API while using the swagger generated classes, please open a developer support case to investigate the issue further. Please use this link to open a support case: https://developer.amazonservices.com/support
I hope this information helps.
Have a great day!

Best,
Rugved
Solutions Architect, SP API
