### ISSUE TITLE
[FEATURE] is it possible for getting lowest price of listing with more parameters?

### ISSUE THREAD

**Issue by codingkondi** [amzn/selling-partner-api-docs#295]
as the title,
when I use **getPricing** or **getCompetitivePricing** for getting prices or competitive prices , I could call these api with 20 skus or asins per request.

depend on[ product pricing docs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md),as far as I read that I only use **getListingOffers** or **getItemOffers** to get **response.Summary.LowestPrices** for lowest prices with **1 sku or asin** as parameter per request.

maybe I miss some core logics or descriptions at product pricing docs, I still wanna know is it possible for getting lowest price of listing with more parameters like **getPricing** or **getCompetitivePricing** ?

**Comment by yingyuhaonan** [comment]
hi,when i use getCompetitivePricing for get something by sku,but it return  ClientError,do you know why?
