### ISSUE TITLE
Parameter ShippingServiceOfferId not work on the API createShipment [BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by fruch17** [amzn/selling-partner-api-docs#2950]
Hello,

I have an issue in create shipment , normally it work fine, but when i want to use the parameter : "ShippingServiceOfferId" the api return me an error : 
"errors": [
{
	"code": "InvalidInput",
	"message": "The shipping offering Id has expired.  Please make another GetEligibleShippingServices call to get a new id.",
	"details": ""
}
],
"reason": "Bad Request",
"message": "InvalidInput - The shipping offering Id has expired.  Please make another GetEligibleShippingServices call to get a new id."

This error said that The shipping offering Id has expired, but ShippingServiceOfferId  only has 2 seconds of being created in the api getEligibleShipmentServices, how is it possible that it has expired.

It is the first time that I use this parameter ShippingServiceOfferId  on the api createShipment to try create the label with the same cost as in the eligible ones, currently the labels are being created with a higher cost than the one returned in the GetEligibleShippingServices  ones.

Can someone help me please..??

parameters request:
{
					"HazmatType": "None",
					"ShippingServiceId": "UPS_PTP_GND",
					"ShippingServiceOfferId": "AAAAAAAAAAAmOzjGXU6bZlRS76KCrz2NfAAAAAAAAADIGXCh/F7qr0uVcKGwC1bCM8ysrUzh0UirJwRZSDNLLAVCdwBfWbqD83JKd64oNJqObueANIwkxqsmOYDFbZGt/Rey24aRl3mZ6lTA7cQI0PFf6Ntv6wSI3H4jKbe0d6AaQR2XSZREsLg4ud/PPFFDfFJWtsaZES8/hj1T",
					"ShipmentRequestDetails": {
						"AmazonOrderId": "xxx-xxxx-xxxxxx",
						"PackageDimensions": {
							"Length": 8,
							"Width": 4,
							"Height": 2,
							"Unit": "inches"
						},
						"Weight": {
							"Value": 12,
							"Unit": "oz"
						},
						"ShipFromAddress": {
							"Name": "SHIPPING",
							"AddressLine1": "xxxx xxxxx",
							"AddressLine2": "xxxxx",
							"City": "xxxxx",
							"StateOrProvinceCode": "IL",
							"PostalCode": "60004",
							"CountryCode": "US",
							"Email": "support@xxxxx.com",
							"Phone": "2242412355"
						},
						"ShippingServiceOptions": {
							"DeliveryExperience": "DeliveryConfirmationWithoutSignature",
							"CarrierWillPickUp": false,
							"LabelFormat": "PDF"
						},
						"ItemList": [
							{
								"OrderItemId": "xxxxxxxxxxxxx",
								"Quantity": 1
							}
						]
					}
				}

Thank you.

**Comment by sungolivia** [comment]
please follow the issue template as it will help our team viewing/reporting this issue faster!

**Comment by ngupta33** [comment]
We are facing the same issue. How did you resolve the issue?

**Comment by fruch17** [comment]
> We are facing the same issue. How did you resolve the issue?

The issue happens when the address in GetEligibleShippingServices is different that in createShipment , if any character is different will be fails,  inclusive is case sensitive.

**Comment by ngupta33** [comment]
Thank you so much for your timely help! For us, the issue was the difference in L, W & H values getting passed in GetEligibleShippingServices and CreateShipment. This was unintentional but was causing this error to return.
