### ISSUE TITLE
[BUG] [SP-API] [Issue] Report marketplace Id filter dont work GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL

### ISSUE THREAD

**Issue by nassuf** [amzn/selling-partner-api-docs#2953]
Hello,

I am getting the GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL report.

Filtering on specific marketplacesIds does not affect the result.
And the responses orders does not include marketplaceIds either.

**Comment by jamesp26** [comment]
Never has done for all the years used the report. A number of the reports don't behave as they are described in the documentation.  You very much have to try them all out and 'appreciate' their quirks.
