### ISSUE TITLE
[BUG] "Content is not allowed in trailing section" when submitting "POST_PRODUCT_PRICING_DATA"

### ISSUE THREAD

**Issue by cgaugel** [amzn/selling-partner-api-docs#296]
Hello,

I try to update the price for one of my SKUs. This is my XML which I submitted:

`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope><Header><DocumentVersion>1.02</DocumentVersion><MerchantIdentifier>MY-SELLER-ID</MerchantIdentifier></Header><MessageType>Price</MessageType><Message><MessageID>1</MessageID><Price><SKU>MY-SKY-1</SKU><StandardPrice currency="USD">12.00</StandardPrice></Price></Message></AmazonEnvelope>`

And this is the Response:

`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>MY-SELLER-ID</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>MY-FEED-ID</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>0</MessagesProcessed>
				<MessagesSuccessful>0</MessagesSuccessful>
				<MessagesWithError>1</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
			<Result>
				<MessageID>0</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>5001</ResultMessageCode>
				<ResultDescription>XML Parsing Fatal Error at Line 2, Column 317: Content is not allowed in trailing section. Content is not allowed in trailing section.</ResultDescription>
			</Result>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>`

What is the problem here? There is no BOM or new line at the end / beginning of my XML...

@seanevan Please help

Thanks for your help.

**Comment by yan15195755798** [comment]
You change it to this：<?xml version="1.0" encoding="UTF-8"?> <AmazonEnvelope><Header><DocumentVersion>1.02</DocumentVersion><MerchantIdentifier>MY-SELLER-ID</MerchantIdentifier></Header><MessageType>Price</MessageType><Message><MessageID>1</MessageID><Price><SKU>MY-SKY-1</SKU><StandardPrice currency="USD">12.00</StandardPrice>
<Sale><SalePrice currency="USD">12.00</SalePrice></Sale</Price></Message></AmazonEnvelope>

**Comment by cgaugel** [comment]
> You change it to this：
> 
> 1.02MY-SELLER-IDPrice1MY-SKY-112.00
> 12.00</Sale

Please submit with code highlight.

**Comment by ashok-damani** [comment]
@cgaugel 
as you are trying to update pricing of an existing SKU, I have a query, when we create listing via SP Feed API, can we attach pricing at the same time, so that we won't need to update pricing in a second API call?

**Comment by aniruddhaad** [comment]
> @cgaugel
> as you are trying to update pricing of an existing SKU, I have a query, when we create listing via SP Feed API, can we attach pricing at the same time, so that we won't need to update pricing in a second API call?

No. Everything else will be same as MWS api call. At least until now, I did not found any enhancement they made which will actually helps/makes developers job easier.
This SP-API is not an enhancement to MWS api (May be they only enhanced how they handle things on backend only 😄  ).
