### ISSUE TITLE
[BUG] [SP-API] [Issue] Product Pricing getCompetitivePricing operation not returning the Used Featured Offer.

### ISSUE THREAD

**Issue by repriceit** [amzn/selling-partner-api-docs#2961]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Product Pricing API v0
getCompetitivePricing operation

## Expected Behavior

When there is a Used Featured Offer (also commonly referred to as the Used Buy Box) the getCompetitivePricing operation should return the pricing details of this offer.  This behavior worked as expected until about 5 days ago and now it is not returning the Used Featured Offer details.  This is causing a big issue with the FBA Sellers that we support, they are no longer able to price their Used FBA items against the Used Buy Box offer (featured offer).  

## Current Behavior

This operation still returns New Featured offer as expected, but not the Used Featured offer when present for a given product.  This has been happening for about 5 days, before this it worked perfectly since the Product Pricing API was created.  We have only tested this issue in the Amazon.com (US) Marketplace, and the issue is easily recreated doing a lookup using any ASIN that contains a Used Featured Offer.

**Comment by sungolivia** [comment]
please use the issue template as it will help our team get to viewing/reporting issues faster!

**Comment by jamesyanyuk** [comment]
We're experiencing the same. The offer data itself is not populated in the response. Calling `getListingOffers` on the same ASIN shows that there is infact a used buy box offer.

```
[
  {
    "ASIN": "<REDACTED_ASIN>",
    "Product": {
      "CompetitivePricing": {
        "CompetitivePrices": [],
        "NumberOfOfferListings": [
          {
            "condition": "Used",
            "Count": 12
          },
          {
            "condition": "Any",
            "Count": 12
          }
        ]
      },
      "Identifiers": {
        "MarketplaceASIN": {
          "MarketplaceId": "ATVPDKIKX0DER",
          "ASIN": "<REDACTED_ASIN>"
        }
      },
      "SalesRankings": [
        {
          "ProductCategoryId": "video_games_display_on_website",
          "Rank": <REDACTED_RANK>
        },
        {
          "ProductCategoryId": "4924904011",
          "Rank": <REDACTED_RANK>
        }
      ]
    },
    "status": "Success"
  }
]
```

**Comment by repriceit** [comment]
Received this from SP API Support today finally.  We ran our regression tests, and it indeed appears to be fixed.  Will close this bug.

=============

Hello Doug,

Thank you for your patience.

I received an update from the API owners and they confirmed the issue and a fixed that has been deployed already. 

Please make a new call to the getCompetitivePricing and let me know if the issue is fixed on your end.

I will be waiting for your reply.

Best regards,
 
Amalia G.
Selling Partner API Developer Support
