### ISSUE TITLE
[BUG] [SP-API] [ISSUE] - GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT returns NO DATA

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-docs#2965]
Hello,

## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe:
</code></pre>

## Expected Behavior
Requesting the `GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT` from the Reporting API returns a report file.

## Current Behavior
In the US marketplace, requests for `GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT` consistently return `NO DATA` from the API. This started to materialize on or around 2/24/23. In the UI, it appears reports do exist. However, why the API is responding with NO DATA for the US is unclear. 

We have made no changes to our code or request methodology. For EU marketplaces, everything appears to be working as expected.

**Comment by sungolivia** [comment]
please follow the issue template as it will help our team viewing/reporting this issue faster!

**Comment by tspicer** [comment]
@sungolivia , understand, I was looking for general direction to see if there is a broader outage or issue. There have been a number of instances where an issue existed that impacted API operations, but was not reported in the API status as degraded service. My question here is before we get too far into the weeds, is there an unreported outage or degraded service?

**Comment by sungolivia** [comment]
hey @tspicer I see where you are coming from. I would say with our current status quo, best place is the [announcement](https://developer-docs.amazon.com/sp-api/changelog) and [release notes](https://developer-docs.amazon.com/sp-api/page/release-notes) to keep up to date with the changes coming along.  ([RSS](https://developer-docs.amazon.com/sp-api/changelog.rss) also available 😄 )
