### ISSUE TITLE
gl_product_group_type not found in SPAPI

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#2966]
In MWS we used gl_product_group_type  .

But in SPAPI we are not able to find  gl_product_group_type in catalog API.

![image](https://user-images.githubusercontent.com/976073/221762476-b156b564-9390-4c88-a877-a1f40a3b4007.png)

**Comment by rugved1991** [comment]
Hi @vikingcodes,

Thanks for reaching out. This attribute is not available on SP API. Can you provide more context on the use case? You should be able to use "productTypes" attribute instead. If you still need this attribute, please open a new issue as a feature request and we will take the necessary action on our end.

Best,
Rugved
Solutions Architect, SP API
