### ISSUE TITLE
Documentation - Missing Saudi Arabia in vendors central url list 

### ISSUE THREAD

**Issue by vaidas-lungis** [amzn/selling-partner-api-docs#2967]
**Describe the improvement**
[Marketplace IDs page](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) has a Saudi Arabia entry, but [Vendor Central URL](https://developer-docs.amazon.com/sp-api/docs/vendor-central-urls) is missing.

**Description of what the documentation should say**
Explain why Saudi Arabia is missing in the Vendor Central URL page or point out it value is not available. Or add vendor central url to the list if it is supported  

**Screenshots**
![Screenshot 2023-02-28 at 12 06 17](https://user-images.githubusercontent.com/5111555/221822718-bbd20368-9278-4b37-b93c-0395ecf37f68.png)

Related issue 
https://github.com/amzn/selling-partner-api-docs/issues/1148

**Comment by sungolivia** [comment]
Hey @vaidas-lungis did you know that you can submit this documentation feedback directly to our doc site?
They would love to hear more like this from our developers!

Follow the prompt and please let them know about this!
![Screenshot 2023-02-28 at 11 19 11 AM](https://user-images.githubusercontent.com/7606170/221956691-6617b294-1522-4f46-97af-07203f769420.png)
