### ISSUE TITLE
Sellers Do Not Have an option to renew permissions 

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2968]
When a sellers expire, they are unable to renew as the Renew Permissions button is not available.

See attached image.
![Screenshot 2023-02-28 120622](https://user-images.githubusercontent.com/13421522/221850681-273b1401-580d-4a9f-9171-965532784fa5.jpg)

I have raised case's 7607891772 & 8457498942 but I am not getting a response.

7607891772  has been open for almost 4 weeks!

**Comment by puppsupr** [comment]
Hi nrogers805@,
What do you see when you click on "Enable Authorization" ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by nrogers805** [comment]
> Hi nrogers805@, What do you see when you click on "Enable Authorization" ?
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

The seller is taken through the Amazon permission process but then the the callback process is triggered, as if a new seller for the app an takes them through the incorrect workflow. When it should be taken the seller through the renewal workflow where they sign into the App.

Why is the renew button not dislayed ?

**Comment by puppsupr** [comment]
> > Hi nrogers805@, What do you see when you click on "Enable Authorization" ?
> > Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
> 
> The seller is taken through the Amazon permission process but then the the callback process is triggered, as if a new seller for the app an takes them through the incorrect workflow. When it should be taken the seller through the renewal workflow where they sign into the App.
> 
> Why is the renew button not dislayed ?

When did they loose permissions ?

**Comment by nrogers805** [comment]
> > > Hi nrogers805@, What do you see when you click on "Enable Authorization" ?
> > > Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
> > 
> > 
> > The seller is taken through the Amazon permission process but then the the callback process is triggered, as if a new seller for the app an takes them through the incorrect workflow. When it should be taken the seller through the renewal workflow where they sign into the App.
> > Why is the renew button not dislayed ?
> 
> When did they loose permissions ?

The permissions expired - they need to renew every 12 months - you know that , right ?

**Comment by puppsupr** [comment]
> > > > Hi nrogers805@, What do you see when you click on "Enable Authorization" ?
> > > > Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
> > > 
> > > 
> > > The seller is taken through the Amazon permission process but then the the callback process is triggered, as if a new seller for the app an takes them through the incorrect workflow. When it should be taken the seller through the renewal workflow where they sign into the App.
> > > Why is the renew button not dislayed ?
> > 
> > 
> > When did they loose permissions ?
> 
> The permissions expired - they need to renew every 12 months - you know that , right ?

Yeah, so I wanted to confirm if the lost permission in Feb 2023. I'll check on the renew button missing and provide updates.

**Comment by nrogers805** [comment]
why has this been closed without the updates you mentioned ?

**Comment by nrogers805** [comment]
> why has this been closed without the updates you mentioned ?

**Comment by puppsupr** [comment]
Hi @nrogers805,

I closed this since I have escalate your support case and the team is looking into it actively.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by nrogers805** [comment]
> Hi @nrogers805,
> 
> I closed this since I have escalate your support case and the team is looking into it actively.
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

But they have still not responded - not to even acknowledge they are investigating - this is really poor service

**Comment by nrogers805** [comment]
> > Hi @nrogers805,
> > I closed this since I have escalate your support case and the team is looking into it actively.
> > Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
> 
> But they have still not responded - not to even acknowledge they are investigating - this is really poor service

I have still not had any response - this is insane !

**Comment by nrogers805** [comment]
[sungolivia](https://github.com/sungolivia) 

Please get somebody to respond - this is getting a joke - I have cases open for weeks without a resolution to this error

**Comment by puppsupr** [comment]
Hi @nrogers805,
Your App : amzn1.sp.solution.xxxxxxxxxxxx88e3 is pure SP-API in the Draft version. The published version is still showing Hybrid (MWS + SP-API). This is what's breaking the auth workflow. You needs to re-list the app in order to fix auth issue.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by nrogers805** [comment]
> Hi @nrogers805, Your App : amzn1.sp.solution.xxxxxxxxxxxx88e3 is pure SP-API in the Draft version. The published version is still showing Hybrid (MWS + SP-API). This is what's breaking the auth workflow. You needs to re-list the app and make it pure SP API in order to fix auth issue.
> 
> Here is the documentation for the same. https://developer-docs.amazon.com/sp-api/docs/tutorial-convert-a-public-amazon-mws-application-into-a-selling-partner-api-application#step-10-convert-your-hybrid-selling-partner-api-application-to-a-full-selling-partner-api-application
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

the app is in published state and is SP-API - there are currently 2000 sellers using the app without any issues.

Support set the app to hybrid - I have tried to get them to change it back - this is the actual issue raised in case 7607891772 

see images
![7607891772 _1](https://user-images.githubusercontent.com/13421522/223790316-4c4e5da5-3ee5-45b2-b006-45a7d7364340.jpg)
![7607891772 _2](https://user-images.githubusercontent.com/13421522/223790344-58cd31f1-fce1-489a-8fe0-993741f6c877.jpg)

**Comment by nrogers805** [comment]
> Hi @nrogers805, If you have your SP API app fully working, You can go-ahead and convert to Pure SP API as stated above.
> 
> Make sure that,
> 
> 1. You need to implement the OAuth authorization workflow for getting authorizations through SP-API only and not MWS.
> 2. Migrate Amazon MWS authorizations to Selling Partner API authorizations.
> 3. Publish your app as Sp-API only in the Appstore.
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

I have already done that. The workflow was working fine until the support agent messed with the settings and chnaged it to hybrid. As you can see from the images , its SP-API and published
