### ISSUE TITLE
[BUG] [SP-API] NO AmazonOrderItemCode in report GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL 

### ISSUE THREAD

**Issue by suofiya** [amzn/selling-partner-api-docs#2973]
There is no field `AmazonOrderItemCode` in order flat file report. 
But I found it in xml report.
We hope that the report data should be consistent regardless of the report data format.

**Comment by yikeludan** [comment]
now What's the status of this bug? @suofiya

**Comment by threemonks** [comment]
Facing the same issue. Is this issue being actively investigated?
