### ISSUE TITLE
Amazon sp-api

### ISSUE THREAD

**Issue by VigneshQikink** [amzn/selling-partner-api-docs#2975]
Can someone please say where to find refresh token to get LWA Access Token. i searched for it but the documentations are not working. 

https://developer-docs.amazon.com/sp-api/docs/using-postman-for-selling-partner-api-models#generate-an-lwa-access-token-using-postman

**Comment by puppsupr** [comment]
Hi @VigneshQikink,

You will need to generate the refresh token from the developer central page in seller central for sellers or vendor central for vendors by clicking on "Authorize" for your registered application. 

https://developer-docs.amazon.com/sp-api/docs/viewing-your-application-information-and-credentials 

If you are using private seller/vendor application please refer to below documentation,

https://developer-docs.amazon.com/sp-api/docs/self-authorization
You can also refer to this video which shows example for Reports API for vendors, but its similar for sellers too : https://www.youtube.com/watch?v=QGnJr3VkwpA&t=130s

For public application here is the process to authorize,
https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by VigneshQikink** [comment]
Thank you got it

**Comment by gibtang** [comment]
Ok, I tried clicking on the 'Authorise app' to try to get the refresh token. But I do not get a response and no refresh token is shown. Is there something wrong? or I am missing out something?
