### ISSUE TITLE
[BUG] [SP-API] [Issue] Vendor account cannot access /notifications/v1 createDestination

### ISSUE THREAD

**Issue by NA-Dev** [amzn/selling-partner-api-docs#2979]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/notifications/v1.noticifications POST   createDestination 
## Expected Behavior
I'm able to make calls to other endpoints like listings, reports, etc. I have access granted to all roles except RDT. I am including an access token in the request properly. I would expect this one to work as well

## Current Behavior
Response is "Unauthorized"

## Context/Screenshots
I'd like to create a destination for using Event Bridge notifications. Even though not much is offered in notifications for Vendor accounts, I'd still like to get what little I can from this service.

**Request Headers**
Content-Type: application/json
Accept: application/json
x-amz-access-token: Atza|XXXXXXXXX
X-Amz-Content-Sha256: 2023171XXXXXXXXXXXXXXX
Host: sellingpartnerapi-na.amazon.com
X-Amz-Security-Token: XXXXXXXX=
X-Amz-Date: 20230303T210219Z
Authorization: AWS4-HMAC-SHA256 Credential=AXXXXXXXXXXXX/20230303/us-east-1/execute-api/aws4_request, SignedHeaders=accept;content-type;host;x-amz-access-token;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=1f027b541de14f9aa23fdde84c54c57923e5f48bade69b03a6a650c92c305aa2
User-Agent: PostmanRuntime/7.31.1
Postman-Token: 7db07bc8-8ed0-401d-9296-83bba946c3cb
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 164
Cookie: session-id=134-0298816-0363837; session-id-time=2307902806l; session-token="NgbgSngNsAM9pSamhXvmniBrzUE3VokOdZ2gNdiYT8WpsAA1z24smT3ICehZt0EV8UYb/hnp+wKNZP3um0YgkVM/3YSCxZgUgKKFbCUoW6pXER8AaOsuR18rmbO0wO4FrtJIjIwDfC76HnWhJHglSYidGFrFqqoRGpj6hDUtbmGlaEqvKRsIpqNuq1BF6yLmRfpD9siDC3qlaM93TdRVXa2AHNQIlnQ/vvU9AYEkI/g="; ubid-main=131-6912118-3049414

**Response Headers**
Date: Fri, 03 Mar 2023 21:02:20 GMT
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
x-amzn-RequestId: 3ad527e5-6ff5-4d49-ae08-700914068b35
x-amzn-ErrorType: AccessDeniedException

<img width="437" alt="response" src="https://user-images.githubusercontent.com/31260131/222830683-c7965c2e-e7f8-4397-879b-a279e161e136.png">

## Your Environment
Testing in postman using definitions pulled from the documentation.

**Comment by puppsupr** [comment]
Hi @NA-Dev, 
For which notification type you are facing this issue ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by NA-Dev** [comment]
> Hi @NA-Dev, For which notification type you are facing this issue ?
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

I get this error for both Event Bridge and SQS.

**Comment by NA-Dev** [comment]
@puppsupr I really need help resolving this, as I cannot access any notifications. Can you please give some direction as to how to resolve this, or if this is a bug that needs a fix on your end?

**Comment by puppsupr** [comment]
Hi @NA-Dev,
Are you making [Grantless calls](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) as required by createDestination ?

Also for vendors we have two notification types available : 
1. LISTINGS_ITEM_ISSUES_CHANGE 
2. PRODUCT_TYPE_DEFINITIONS_CHANGE

For which one are you trying to create the notifications ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by NA-Dev** [comment]
> 2\. PRODUCT_TYPE_DEFINITIONS_CHANGE

@puppsupr Yes, I am making Grantless calls following the documentation. I am trying to access both LISTINGS_ITEM_ISSUES_CHANGE and PRODUCT_TYPE_DEFINITIONS_CHANGE, but nothing is working. It is the same for my vendor account, and my seller account.  

I created a dev support ticket, and they predictably just copy pasted the documentation at me then closed the case. Need help!

**Comment by rugved1991** [comment]
Hi @NA-Dev,

In the above request details, I can see the AccessToken starts with "Atza|".
"x-amz-access-token: Atza|XXXXXXXXX"

This is an access token received from a seller authorization. You should be using grantless access token which starts with "Atc|". Please try using this access token and test again.

Have a great day!

Best,
Rugved
Solutions Architect, SP API

**Comment by NA-Dev** [comment]
@rugved1991 Now we are getting somewhere! Where is an example of a Grantless request? What scope do I use for the call?

**Comment by NA-Dev** [comment]
@rugved1991 Thanks, I made that change. Sadly, I still get the Unauthorized response. I am using AWS Signature auth with STS tokens generated using the new Atc| access token.

**Comment by NA-Dev** [comment]
@rugved1991 Thanks, I made that change and got it working!  Please instruct the people responding to Developer Support tickets about this. They were no help at all.

**Comment by yatanasov** [comment]
@puppsupr  I apologise for asking in a closed issue, but what could be the reason for not being able to create subscription for any notification type other than:

- LISTINGS_ITEM_ISSUES_CHANGE
- PRODUCT_TYPE_DEFINITIONS_CHANGE

For example, for LISTINGS_ITEM_STATUS_CHANGE - I am getting:

```
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}
```
