### ISSUE TITLE
The application status is published, but OAuth authorization is directed to the MWS authorization page. What's wrong

### ISSUE THREAD

**Issue by 468092882** [amzn/selling-partner-api-docs#298]
The application type is: SP and MWS, the application status has been released, the authorization in the production environment is directed to the MWS authorization page, instead of the SP API user agrees to the authorization page, the test authorization process (version=beta) is normal
![104687660-984f8500-573a-11eb-8a2f-795ffb78d143](https://user-images.githubusercontent.com/32814680/104702377-dfe10b80-5750-11eb-997b-0edf79675b3f.png)

**Comment by 468092882** [comment]
![BB7E0B80-836D-4904-942F-3E1677457ABE](https://user-images.githubusercontent.com/32814680/104687471-34c55780-573a-11eb-83d3-f28b6115ac9c.png)

**Comment by aryatekpia** [comment]
@468092882 please you also open a support case with amazon. they should know that this is affecting many people. this is been going on for a while and is blocker for apps that are in production like ours

**Comment by callumb123** [comment]
I second this, my application has just been approved and is now directing users to MWS auth page. Really not good given the amount of effort it was to get the application approved in the first place.

**Comment by 468092882** [comment]
> @468092882 please you also open a support case with amazon. they should know that this is affecting many people. this is been going on for a while and is blocker for apps that are in production like ours

Yes, I have opened a case, but there is no reply yet

**Comment by 468092882** [comment]
> I second this, my application has just been approved and is now directing users to MWS auth page. Really not good given the amount of effort it was to get the application approved in the first place.

You can open a case and wait for Amazon to process it, although they process it very slowly

**Comment by 468092882** [comment]
> 我第二，我的应用程序刚刚获得批准，现在将用户定向到MWS身份验证页面。考虑到首先要使应用程序获得批准的努力程度，这确实不好。

You can open a case and wait for Amazon to process it, although they process it very slowly

**Comment by 468092882** [comment]
Disappointed
