### ISSUE TITLE
[BUG] [SP-API] [Issue] Fulfillment Inbound API operation getTransportDetails returns no CarrierName for PartneredLtlData

### ISSUE THREAD

**Issue by aeveltstra** [amzn/selling-partner-api-docs#2981]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Fulfillment Inbound v0, operation getTransportDetails
[Documentation reference](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#gettransportdetails)

## Expected Behavior

Expecting to receive a carrier name shortly after the transport cost has been estimated.

## Current Behavior

After 3 hours, the API still does not return a carrier name.

## Context/Screenshots

We are trying to use the SP API to mimic and reduce manual labor. Not receiving the carrier name automatically means a person has to go into the Seller Central console and retrieve the name manually, and then send an email to our warehouse.

## Your Environment

Custom python programs running on AWS Lambda, using the standard requests library. Most operations work as desired and documented. I can attach anonymized request and response logs.

**Comment by rugved1991** [comment]
Hi @aeveltstra,

Are you sending a request to Amazon using putTransportDetails operation? Once you submit the request you can use the getTransportDetails operation to find more details about the cost of transport. You should also receive TransportStatus parameter in the response which can be used to keep track of the progress of your inbound shipment.
Please refer to this Use Case Guide for more information on the steps taken to submit Inbound Shipment: https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#task-1-submit-carton-content-information
If you are still seeing an issue, please open a developer support case with complete request and response details along with headers to investigate the issue further.
I hope this information helps.
Have a great day!

Best,
Rugved
Solutions Architect, SP API
