### ISSUE TITLE
Error executing "AssumeRole" on "https://sts.eu-west-1.amazonaws.com"

### ISSUE THREAD

**Issue by VigneshQikink** [amzn/selling-partner-api-docs#2983]
Error executing "AssumeRole" on "https://sts.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://sts.eu-west-1.amazonaws.com` resulted in a `403 Forbidden` response: Sender AccessDeni (truncated...) AccessDenied (client): User: arn:aws:iam::67211257:user/Qikink is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::67211257:user/Qikink - Sender AccessDenied User: arn:aws:iam::67211257:user/Qikink is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::6721257:user/Qikink 70570cbc-baab-4cc7-8053-f3f4dcc7bec8
 
 unable find the reason for this error. gave assume rele permissions in policy. still not working. any update in 2023

**Comment by puppsupr** [comment]
Hi @VigneshQikink,

Can you please try this : https://sts.amazonaws.com/?Version=2011-06-15&Action=AssumeRole&RoleSessionName=Test&RoleArn=arn:aws:iam::XXXXXXXXXXXX:role/SellingParSellingPart&DurationSeconds=3600
Replace arn:aws:iam::XXXXXXXXXXXX:role/SellingParSellingPart with your account ARN.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by sungolivia** [comment]
@VigneshQikink if above answer solved your issue, please close this issue :)
