### ISSUE TITLE
OAuth for both advertising api and selling partner api

### ISSUE THREAD

**Issue by discover59** [amzn/selling-partner-api-docs#299]
Is it possible to get authorization to access both advertising API and selling partner API with one click sign in?

Advertising API uses `https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.xxx&scope=cpc_advertising:campaign_management` while selling partner API uses `https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.xxxx&version=beta` to get authorization.

**Comment by donhmorris** [comment]
I am interested in this too. I tried to add the selling partner scope but I get an error.

It seems like a seller has to do two steps for an app that wants to use both the advertising and selling partner api's. A seller logs into their account via LWA with profile and advertising api scope. Then, the seller has to do another login with the selling partner scope. It's a bit confusing.

**Comment by vikingcodes** [comment]
@donhmorris I think you right . It may be URL redirection based on scope.  It make sense to redirect to different page because Advertising API and Selling Partner API have different permission levels.

**Comment by abdulrehmanGtech** [comment]
please someone help me about  OAuth selling partner api i am search for this amzn1.sellerapps.app.xxxx...
  i have not clue where to find it ??
