### ISSUE TITLE
GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA  Report type not working

### ISSUE THREAD

**Issue by maniicandy** [amzn/selling-partner-api-docs#2996]
Hi,

In the Selling partner API, This report type "GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA" suddenly stops working on Feb 16, 2023, till now this API call was not working, it returns the below error

`\"errors\": [ { \"code\": \"InvalidInput\", \"message\": \"Request for report type 2600 is not allowed at this (truncated...) )`

Also, I can't find this report type in the SPAPI documentation  
https://developer-docs.amazon.com/sp-api/docs/report-type-values

**Comment by ykaganovsky** [comment]
I've got the same exact error today. Please let me know if you got this resolved. If so - how? Thank you in advance.

**Comment by ykaganovsky** [comment]
@maniicandi. Please let me know if/how you resolved it.

**Comment by maniicandy** [comment]
@ykaganovsky , this report was types was depreciated, Use GET_LEDGER_DETAIL_VIEW_DATA instead 
ref: https://developer-docs.amazon.com/sp-api/changelog/january-2023-release-announcement

**Comment by ykaganovsky** [comment]
@maniicandy Thank you!
