### ISSUE TITLE
Developer Central

### ISSUE THREAD

**Issue by tanguy-r** [amzn/selling-partner-api-docs#3]
I'm facing the following problem:
I have an existing application using MWS and LWA. 
Following your announcement (awesome news btw!) I've proceeded with Steps 1-6 in "Registering Your Selling Partner API application" ( https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-6-register-your-application )

Everything is fine until "Viewing your developer information" section. You say "The Developer Central page appears, displaying the IAM ARN associated with your application(s)." But I am not seeing the IAM ARN, nor "Click View under LWA credentials for the application you want." within Seller Central / Developer Central.

Can you help me troubleshoot so that I can finish setting up as a Hybrid? Thank you

**Comment by edaik** [comment]
Hi @tanguy-r !

Thanks for taking a look at the documentation and integration steps. The experience  you're seeing is as planned and a result of not rolling the full self-service integration features to all our Developers yet as we're in doc preview . We anticipate making the self-service features available to all Developers starting later this month - we will post an announcement when the APIs and self-service features in Seller Central are launched in general availability.

Hope this helps,
Evan

**Comment by tanguy-r** [comment]
Excellent, thank you @edaik !

**Comment by LemarinelNet** [comment]
Hi,
It seems the services are live now, but I'm not able to see the IAM ARN on my sellercentral account, as described in #12 or here... (my customer also has a MWS application already registered). 
Is this a normal behavior ?

Regards !
