### ISSUE TITLE
Notifications-API Permissions for SQS-Queue and Testmessage

### ISSUE THREAD

**Issue by mike59999** [amzn/selling-partner-api-docs#30]
Hello,

it would be helpful if the guide has a section included which permissions are need to set for the sqs-queue.
I have an active Subscription for Any Offer Changed but no messages are coming in.
It would also be good when there is function to send a testmessage like it was in the old MWS-API.

best regards,

Michael

**Comment by seanevan** [comment]
@mike59999 Thanks for the feedback. I've relayed this to our technical writing team to clarify the SQS permissions that are needed in the Notifications use case guide. To troubleshoot the issue you are encountering, could you please [open a support case](https://developer.amazonservices.com/support) with us?

**Comment by codingkondi** [comment]
> @mike59999 Thanks for the feedback. I've relayed this to our technical writing team to clarify the SQS permissions that are needed in the Notifications use case guide. To troubleshoot the issue you are encountering, could you please [open a support case](https://developer.amazonservices.com/support) with us?

Hi Seanevan:
     
      I have same problem about  that, and I want to understand the report API for new version is work without any notification to SQS?

**Comment by seanevan** [comment]
Hi @codingkondi, you can find more details about the new Reports API in our [use case guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/reports-api-use-case-guide-2020-09-04.md). Please let me know if I've misunderstood your question.

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by codingkondi** [comment]
Hi @seanevan ,
I had read the new reports API and notification API, but the report guide never mentioned about SQS. and let me little confused
though I already used ur notification API creating destination to AWS SQS and subscription with notification type:"REPORT_PROCESSING_FINISHED" ,I still want to know is it a correct way  before calling report API?

**Comment by appleWindy** [comment]
Hi @seanevan , I have the same problem with @mike59999 .
and I have opened a case 2179383133.
Please help check it.

**Comment by appleWindy** [comment]
@mike59999 
Have you solved your problem?

**Comment by rugved1991** [comment]
Hi @appleWindy,

Can you please confirm if you are still seeing this issue? I would recommend you to refer to the [Notifications Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md) for more information on how to setup notification.

@codingkondi  You can use REPORT_PROCESSING_FINISHED notification type to receive message when a report is ready. If you do not want to setup notifications, you can use the getReport operation to check for status of the report.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by appleWindy** [comment]
@rugved1991 
Thank you for the reply.
The problem for me has been solved.
I will close the issue.
