### ISSUE TITLE
Inventory Update via Upload/Feeds Resets Handling Time

### ISSUE THREAD

**Issue by nicolasheady** [amzn/selling-partner-api-docs#3002]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
FEEDS API - POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA

The docs that seem to cover this are here: https://sellercentral.amazon.com/help/hub/reference/201576480
The page does not mention "handling-time", but it IS mentioned in the template you can download from that page. The template instructions, paragraph 3 in "How to use the file" says:
"If you do not provide a value for an attribute in the template, Amazon will retain the existing value that is already in your catalog."

When using the feed type "POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA" to submit a feed via SP-API, I'm submitting it with only the "sku" and "quantity" attributes. After the feed processes successfully, I can see the quantity updated correctly, but the handling time for the products was reset even though I did not provide a value.

I'm submitting my feeds using NodeJS.

**Comment by xiaohei16h** [comment]
@nicolasheady Hello, I have also encountered this issue and we have tried using the `Listing Items` PATCH  API https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide#tutorial-partially-update-a-listing .

 The submitted quantity has been successfully modified, but the `handling time` will also be reset. The submission is as follows:

```
{
    "productType": "HAT",
    "patches": [
        {
            "op": "replace",
            "path": "/attributes/fulfillment_availability",
            "value": [
                {
                    "fulfillment_channel_code": "DEFAULT",
                    "quantity": 5
                }
            ]
        }
    ]
}
```

Have you found a solution yet? Thank you very much

**Comment by nicolasheady** [comment]
> @nicolasheady Hello, I have also encountered this issue and we have tried using the `Listing Items` PATCH API https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide#tutorial-partially-update-a-listing .
> 
> The submitted quantity has been successfully modified, but the `handling time` will also be reset. The submission is as follows:
> 
> ```
> {
>     "productType": "HAT",
>     "patches": [
>         {
>             "op": "replace",
>             "path": "/attributes/fulfillment_availability",
>             "value": [
>                 {
>                     "fulfillment_channel_code": "DEFAULT",
>                     "quantity": 5
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> Have you found a solution yet? Thank you very much

I also encountered this error first, before switching to the file feeds. I have not found a solution, other than to include handling time values in my feed upload, or in my request via the PATCH API.

**Comment by lucnap** [comment]
The bug still persists

**Comment by danielu7** [comment]
We also encountered this error, is it possible to open this issue?
