### ISSUE TITLE
`Invalid path provided in patch at index of 0.` can be thrown from `PATCH /listings/2021-08-01/items/` for issues with the `value` field.

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#3005]
`Invalid path provided in patch at index of 0.` can be thrown from `PATCH /listings/2021-08-01/items/` for issues with the `value` field.  This is of course completely flawed and misleading.

**Comment by rugved1991** [comment]
Hi @johnkw,

Please open a developer support case using any of the following links:
Developer Support EU: https://developer.amazonservices.co.uk/support
Developer Support NA: https://developer.amazonservices.com/support
Developer Support FE: https://developer.amazonservices.com.au/support

This would required further investigation. Please add complete request and response along with headers to the support case. 

In general, this error message means that the path provided in the patch request is incorrect. Please make sure you are using the correct attribute name in the path and are using the format "/attributes/attribute_name". 

Also, make sure you are adding parent attribute in the patch request and not nested attributes. 
I hope this information helps. 
Have a great day!

Best,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @johnkw,

Can you please share the case ID? I can check internally and see if this is a broader issue.

Best,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @johnkw,

Thank you for surfacing this issue. We are currently working with internal teams to fix the error messaging on this issue. Please stay tuned for further updates!
Have a great day!

Best,
Rugved 
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @johnkw,

Thank you for your patience. The internal team has deployed a fix for this issue. Please test again and let us know if you are able to see the correct error message. 
If the issue still persists, feel free to reopen this issue.

Best,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @johnkw,

Thanks for confirming. Can you please provide request ID and timestamp for the request that is throwing wrong error? I can reach out to the internal team to take a look and investigate further.

Best,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @johnkw,

Thanks for sharing the details. The internal team has confirmed the issue should now be resolved. Please test again and let us know if you are no longer seeing the same issue.
Have a great day!

Best,
Rugved
Solutions Architect, SP API

**Comment by johnkw** [comment]
Add bug #3068 for the new incorrect message, which is at least slightly better than the prior incorrect message.
