### ISSUE TITLE
How can I get the logistics information of an order through API?

### ISSUE THREAD

**Issue by GuoCHong0210** [amzn/selling-partner-api-docs#301]
Check the document, but can not find the order and logistics before any connection

**Comment by ShivikaK** [comment]
Hello @GuoCHong0210 

Can you please elaborate on the information you are looking to retrieve via APIs?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello,

As we haven’t received any response from you regarding this, I will close this issue.
Please open a support case with us for any errors with your API requests and we can assist you further.

Thanks,
Shivika Khare
Selling Partner API Developer Support
