### ISSUE TITLE
[GET_AMAZON_FULFILLED_SHIPMENTS_DATA_TAX] Most of the orders doesn't have PII (Buyer Info, Shipping Address)

### ISSUE THREAD

**Issue by joyceeeen** [amzn/selling-partner-api-docs#3013]
Even with RDT and PII approval, I still can't get the complete PII data. Some of the orders have the Buyer Info, but most of it doesn't. Is this expected? 

I used to complete details from MWS

**Comment by daapower** [comment]
I am seeing the same thing, a lot of orders don't have the PII even though you can pull from get address individually but those calls have very limited allowances for calls
