### ISSUE TITLE
Self authorization long-lived refresh token `unsupported_grant_type`

### ISSUE THREAD

**Issue by cohlar** [amzn/selling-partner-api-docs#302]
Hi,

I am an FBA seller, I am trying to make a small serverless app for myself, and I am somehow struggling to get an Access Token with the long-lived Refresh Token. Any help would be greatly appreciated!

When requesting an Access Token, I get this response:
```
{
      error_description: 'The authorization grant type is not supported by the authorization server',
      error: 'unsupported_grant_type'
}
```

I have developed all the Oauth logic (i.e. not self authorized) for another app, and everything works fine with the Refresh Token generated by the LWA process - so I assume my code and IAM configuration are fine.

But for some reason, when skipping the LWA process and requesting directly an Access Token with the long-lived Refresh Token generated in Seller Central (self authorization flow), things don't work out for me.

This is the function I use to request an Access Token (in Node.js):

```
const getSellerAccessToken = async () => {
  const url = "https://api.amazon.com/auth/o2/token";
  const headers = {
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
  };
  const body = {
    grant_type: "refresh_token",
    refresh_token: process.env.SELF_AUTHORIZATION_REFRESH_TOKEN,
    client_id: process.env.LWA_CLIENT_ID,
    client_secret: process.env.LWA_CLIENT_SECRET,
  };
  try {
    const authCodeResponse = await axios.post(url, body, { headers });
    if (authCodeResponse.status === 200) {
      return authCodeResponse.data.access_token;
    }
    return Promise.reject(`Failed getting access token, error: ${authCodeResponse.statusText}`);
  } catch (e) {
    console.error(e);
    return Promise.reject(`Failed getting access token, error: ${e.message}`);
  }
};
```

Many thanks for your help!

**Comment by vdanyliv** [comment]
Hi @cohlar, take a look at this article https://vdanyliv.medium.com/amazon-selling-partner-api-spapi-how-to-quickly-and-simply-integrate-with-new-api-part-2-59d7458f24fe maybe it will help you

**Comment by nodisk8800** [comment]
The params can not in body.

All params in url:
https://api.amazon.com/auth/o2/token?grant_type=refresh_token&refresh_token=process.env.SELF_AUTHORIZATION_REFRESH_TOKEN&client_id=process.env.LWA_CLIENT_ID&client_secret=process.env.LWA_CLIENT_SECRET



Recommend to encode the value in url,like this:
name=encode(value)

axios.post(url, null, { headers });

**Comment by cohlar** [comment]
@vdanyliv thanks! I actually went through your article a few weeks ago when I built the LWA logic, and again yesterday night when I struggled with this... thank you for sharing though, it's been really useful! 🙏 

@nodisk8800 thanks you, are absolutely right, I actually moved them from query params to the body yesterday after reading @vdanyliv's post because I was getting the same error. But I was passing `{}` instead of `null` for the body which was clearly a mistake. I just refactored... and now I get the following error message.
I think it's much better, but something is still wrong and I'm not sure what.

```
{
    "errorMessage": "Failed getting access token, error: Request failed with status code 500"
}
```

**Comment by vdanyliv** [comment]
@cohlar try
```
const fetch = require('node-fetch');
const qs = require('qs');

module.exports.refreshLwaToken = async(refresh_token) => {
	const lwaBody = {
		refresh_token,
		grant_type: 'refresh_token',
		client_id: process.env.AMAZON_SELLER_APP_ID,
		client_secret: process.env.AMAZON_SELLER_APP_SECRET,
	};

	const refreshToken = await fetch(constants.spm.amazon.api.LWA_REFRESH, {
		method: 'POST',
		body: qs.stringify(lwaBody),
		headers: {'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'},
	});

	if (refreshToken.ok) {
		return await refreshToken.json();
	} else {
		throw new Error(refreshToken.statusText);
	}
};
```


Also before trying, I recommend you to run the request in Postman

**Comment by cohlar** [comment]
Wow @vdanyliv I made it work thanks to you - I was just missing the `qs.stringify` before the body. Thank you for your help!

Here is the code that works, in case anyone comes across the same issue:
```
export const getSellerAccessToken = async () => {
  const url = "https://api.amazon.com/auth/o2/token";
  const headers = {
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
  };
  const body = {
    grant_type: "refresh_token",
    refresh_token: process.env.SELF_AUTHORIZATION_REFRESH_TOKEN,
    client_id: process.env.LWA_CLIENT_ID,
    client_secret: process.env.LWA_CLIENT_SECRET,
  };
  try {
    const authCodeResponse = await axios.post(url, qs.stringify(body), { headers });
    if (authCodeResponse.status === 200) {
      return authCodeResponse.data.access_token;
    }
    return Promise.reject(`Failed getting access token, error: ${authCodeResponse.statusText}`);
  } catch (e) {
    console.error(e);
    return Promise.reject(`Failed getting access token, error: ${e.message}`);
  }
};
```
