### ISSUE TITLE
SellingApiForbiddenException when creating report GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA

### ISSUE THREAD

**Issue by nonfatalexec** [amzn/selling-partner-api-docs#3028]
I'm getting this exception
sp_api.base.exceptions.SellingApiForbiddenException: [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]
when trying to create the report "GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA".

Here is the code snippet:
`report_request = reports_api.create_report(reportType="GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA", dateStartTime=str(date.today() + dt.timedelta(days=-days_ago))+"T04:00:00", dateEndTime=str(date.today())+"T04:00:00")
`
A similar code has no issues:
`report_request = reports_api.create_report(reportType="GET_FLAT_FILE_OPEN_LISTINGS_DATA", dateStartTime=str(date.today())+"T04:00:00", dateEndTime=str(date.today())+"T04:00:00")
`

I have these roles in my app:

Finance & Accounting
Selling Partner Insights
Buyer Communication
Pricing
Inventory and Order Management
Brand Analytics
Amazon Fulfilment
Buyer Solicitation
Product Listing

How should I debug this?

**Comment by dmitrijslasko** [comment]
Hey, did you manage to fix this?

**Comment by nonfatalexec** [comment]
@dmitrijslasko I updated the refresh token for the permissions to take effect
