### ISSUE TITLE
"Offer Start Date" aka `'attributes' > 'purchasable_offer' > 'start_at'` cannot be updated via the Listings API

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#3031]
"Offer Start Date" aka `'attributes' > 'purchasable_offer' > 'start_at'` cannot be updated via the Listings API.  At the very least the list of non-update-able fields should be documented.

During the bug #3005 investigation, it was determined via support that this is missing from the API.

See also bug #440.

**Comment by rodrifed** [comment]
_Related to #3068.
Non-issue. Resolving_

**Comment by johnkw** [comment]
If this was never broken then Seller Support needs to be informed, because they think it's not updateable.  Also the documentation needs to be fixed to describe what is and is not updateable.
