### ISSUE TITLE
Unable to connect to the SP-API using grant_type=refresh_token

### ISSUE THREAD

**Issue by shashankshirke** [amzn/selling-partner-api-docs#304]
Hi guys,

We're trying to connect to the Amazon SP-API using the `grant_type=refresh_token` but are not able to get through. We're referring the official documentation and using the following parametes to connect.

```
POST /auth/o2/token HTTP/1.1
Host: sandbox.sellingpartnerapi-eu.amazon.com

grant_type=refresh_token
&refresh_token=XXXXXXXX (taken from app > authorize > Generate refresh token )
&client_id=XXXXXXXX (taken from app app > LWA credentials)
&client_secret=XXXXXXXX (taken from app > LWA credentials)
```

The response received for the above API call is as below:

**Response Header:**

```
HTTP/1.1 403 Forbidden
Date: Sat, 16 Jan 2021 10:49:35 GMT
Content-Type: application/json
Content-Length: 135
Connection: keep-alive
x-amzn-RequestId: 81db69fd-d904-4076-b7fb-187aa5899b87
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amz-apigw-id: ZPOt_HAljoEFX0Q=
```

**Response Body:**

```
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "MissingAuthenticationToken"
    }
  ]
}
```

We've read almost all the topics related to this particular topic in the issues section of this repo but couldn't locate a definitive solution to this.

![response](https://user-images.githubusercontent.com/7890147/104822845-91745f80-586b-11eb-9877-695e4714f71f.png)

Documentation steps referred: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token

@rogersv @winterstefan @charliecode requesting you guys to suggest the best way forward as it seems you guys had faced similar issues and have managed to resolve those successfully.

Thank you.
Shashank

**Comment by vdanyliv** [comment]
Take a look at this article, maybe you find it useful for such a case
https://vdanyliv.medium.com/amazon-selling-partner-api-spapi-how-to-quickly-and-simply-integrate-with-new-api-part-2-59d7458f24fe

**Comment by nodisk8800** [comment]
Do it on the production,not in sandbox.

**Comment by shashankshirke** [comment]
> Do it on the production,not in sandbox.

Hi, I tried calling the API using the production endpoint (https://sellingpartnerapi-eu.amazon.com) but it still gives the same 403 forbidden response as mentioned above.

Can you please help with a step-by-step process to follow? I am trying to connect to the Amazon India marketplace.

**Comment by shashankshirke** [comment]
> Take a look at this article, maybe you find it useful for such a case
> https://vdanyliv.medium.com/amazon-selling-partner-api-spapi-how-to-quickly-and-simply-integrate-with-new-api-part-2-59d7458f24fe

Hi @vdanyliv, thanks for sharing the article. I'll check by following the instructions you've given.

Correct me if I am wrong but this is what I've understood from your article;

1. We use the app `client ID`, `client secret` and `refresh_token` to generate the `access_token` (temp)
2. We use the `access_token` to connect to the API
3. Once the connection is authorized, we use the `access_token` to sign all further calls to the API

This works very well for self authorization workflow. Can you also guide me for website & app store workflows using the LWA method?

**Comment by vdanyliv** [comment]
@shashankshirke everything that you mention above is correct, if to talk about website / app store flow, everything is the same, except you need to handle application authorization, you can find how to do this in the official documentation

**Comment by nodisk8800** [comment]
> 
> 
> > Do it on the production,not in sandbox.
> 
> Hi, I tried calling the API using the production endpoint (https://sellingpartnerapi-eu.amazon.com) but it still gives the same 403 forbidden response as mentioned above.
> 
> Can you please help with a step-by-step process to follow? I am trying to connect to the Amazon India marketplace.

If there is anything you don't understand, I'll be glad to help you.
Do you have QQ id? I can send some code or remove desktop support for you.

**Comment by ShivikaK** [comment]
Hello @shashankshirke 

Did you manage to get past this error? 

Along with LWA credentials to generate access token, you also need to use your AWS credentials which must have been generated when you created the IAM entity during app registration process.

The Selling Partner API security model uses AWS authentication credentials. You need to configure the AWS credentials in your code for the SP API request.

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by shashankshirke** [comment]
> Hello @shashankshirke
> 
> Did you manage to get past this error?
> 
> Along with LWA credentials to generate access token, you also need to use your AWS credentials which must have been generated when you created the IAM entity during app registration process.
> 
> The Selling Partner API security model uses AWS authentication credentials. You need to configure the AWS credentials in your code for the SP API request.
> 
> Please feel free to open a support case with us if you'd like deeper assistance with this issue.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Hi @ShivikaK 

I am still not able to get past this error.

Are the AWS IAM credentials still required if we just want to connect using the self-authorization workflow? It'd be great if you can help me out with setting up the connection to the API or point me in the right direction. The currently available documentation seems very limited and confusing w.r.t to the various credentials and workflows.

If nothing, I'll raise a support case.

Thank you.

**Comment by ShivikaK** [comment]
Hello @shashankshirke 

We will need to work with you via a support case to resolve this issue. Please open a support case for further troubleshooting Once you have raised a support case, please share the case ID and I will look into expediting it.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by vikingcodes** [comment]
@shashankshirke  For generate access_token , you need use following as host.

**https://api.amazon.com/auth/o2/token** and select **"x-www-form-urlencoded"**

![image](https://user-images.githubusercontent.com/976073/105337103-0646f100-5c00-11eb-9b9c-4462d8b692d7.png)

**Comment by shashankshirke** [comment]
> @shashankshirke For generate access_token , you need use following as host.
> 
> **https://api.amazon.com/auth/o2/token** and select **"x-www-form-urlencoded"**
> 
> ![image](https://user-images.githubusercontent.com/976073/105337103-0646f100-5c00-11eb-9b9c-4462d8b692d7.png)

@vikingcodes thanks a lot!

Your solution was on point and it worked. The most important element was sending the API call using "x-www-form-urlencoded" method.

PS: This works perfectly for self-authorization. Does the marketplace login or website login workflow using LWA require any other special configuration?

Cheers & thanks ✌😁
