### ISSUE TITLE
[BUG] [SP-API] [Issue] InvalidInput - Invalid request parameters

### ISSUE THREAD

**Issue by amazing-user** [amzn/selling-partner-api-docs#3042]
Getting an error when trying to retrieve the error of the uploaded feed using the create feed, Feed Type: POST_PRODUCT_DATA
 
## SP-API Name and Version or Report/Feed Type
POST_PRODUCT_DATA v2021-06-30

I am following the step 4 in
https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#step-4-create-a-feed

API: /feeds/2021-06-30/feeds

getting below response:
    Response:
    {
      "errors": [
        {
          "code": "InvalidInput",
          "message": "Invalid request parameters",
          "details": ""
        }
      ]
    }
 
It was working 6 months ago but not working now. Seems something has changed.

**Comment by ritikacd** [comment]
Hi @amazing-user 

We recommend checking: 

1) Seller Central account status: https://developer-docs.amazon.com/sp-api-blog/docs/ensuring-healthy-seller-account-status#receiving-an-api-error When you login to Seller Central, you should see a warning in color that they need to rectify, to fix their account status. The error usually occurs when a problem was flagged with your Seller Central account or is missing critical payment information [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsellercentral.amazon.com%2Fhz%2Fsc%2Faccount-information&data=05%7C01%7Cv-anthorat%40microsoft.com%7C5f316a19435847b5367708dae832c5f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638077602235309192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PTd%2BcG3jYTnVYm9WEG%2FtbgihIwi2zG0bTrmbfJtDB5U%3D&reserved=0) (Ex: Charge Methods and Account info)

2) Review and fix any Amazon Performance notifications [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsellercentral.amazon.com%2Fperformance%2Fnotifications&data=05%7C01%7Cv-anthorat%40microsoft.com%7C5f316a19435847b5367708dae832c5f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638077602235465408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZXRRXJrKV62%2F4%2FSNuhOdt9quFUOldHLBFVtXbZTlCOE%3D&reserved=0) that might be relevant.

3) Check on headers passed in the _CreateFeed_ request, try testing by adding Content-Type = application/json in the header. 

Let us know if you still see this issue. 

Thank you.

**Comment by ritikacd** [comment]
Hi @amazing-user Please let us know if you're still facing this issue.

**Comment by amazing-user** [comment]
The account was disabled by Amazon. After re-enabling the account, it worked. Thank you!
It would have been great if it would have shown message like "Account disabled" rather than "InvalidInput".

**Comment by ritikacd** [comment]
Thanks for sharing the feedback, we would definitely pass it to our product team.

**Comment by albinsopaj** [comment]
> Hi @amazing-user
> 
> We recommend checking:
> 
> 1. Seller Central account status: https://developer-docs.amazon.com/sp-api-blog/docs/ensuring-healthy-seller-account-status#receiving-an-api-error When you login to Seller Central, you should see a warning in color that they need to rectify, to fix their account status. The error usually occurs when a problem was flagged with your Seller Central account or is missing critical payment information [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsellercentral.amazon.com%2Fhz%2Fsc%2Faccount-information&data=05%7C01%7Cv-anthorat%40microsoft.com%7C5f316a19435847b5367708dae832c5f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638077602235309192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PTd%2BcG3jYTnVYm9WEG%2FtbgihIwi2zG0bTrmbfJtDB5U%3D&reserved=0) (Ex: Charge Methods and Account info)
> 2. Review and fix any Amazon Performance notifications [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsellercentral.amazon.com%2Fperformance%2Fnotifications&data=05%7C01%7Cv-anthorat%40microsoft.com%7C5f316a19435847b5367708dae832c5f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638077602235465408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZXRRXJrKV62%2F4%2FSNuhOdt9quFUOldHLBFVtXbZTlCOE%3D&reserved=0) that might be relevant.
> 3. Check on headers passed in the _CreateFeed_ request, try testing by adding Content-Type = application/json in the header.
> 
> Let us know if you still see this issue.
> 
> Thank you.

Hi there. I'm getting the following error

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "marketplaceIds;feedType;inputFeedDocumentId;"
    }
  ]
}
```

This is the header of the request

![image](https://github.com/amzn/selling-partner-api-docs/assets/62503305/6c3a0e15-46a7-4ac8-90c5-715a89874f88)

Please let me know what have I done wrong. 

Thanks in advance.
Kind regards
