### ISSUE TITLE
Reports Always Fatal

### ISSUE THREAD

**Issue by 854350999** [amzn/selling-partner-api-docs#3047]
When I request GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT this report, it can be requested successfully if I specify a date from 2023-03-12 to 2023-03-18, and fails when I specify a date after that

**Comment by rugved1991** [comment]
Hi @854350999,

Please make sure you are adding the correct dates according to the reportPeriod mentioned in the reportOptions. The dates you have mentioned follow the reportingPeriod of 1 WEEK so it returns a valid response. If you add a date which spans for more than a week, it would throw an error.
If you still have additional questions or are running into same error, please provide the complete reportOptions value added to the request for further investigation. 

Best,
Rugved
Solutions Architect, SP API

**Comment by koralu** [comment]
Same for me, even if I have valid GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT parameters I'm still receiving FATAL status. 
`"errorDetails" : "A client error occurred. Please double check that your parameters are valid and fulfill the requirements of the report type."`

Report parameters:
`        reportOptions: {
          reportPeriod: "WEEK"
        },
        dataStartTime: "2022-10-02",
        dataEndTime: "2022-10-08", `

**Comment by jonlieureli** [comment]
Same issue here, my parameters have been working for months until now. I have valid parameters from `2023-03-19` to `2023-04-01` and it returns a FATAL status stating I have invalid parameters.

**Comment by Dachneg** [comment]
Hi 854350999
I had the same issue. Solved it when specified DateTimeKind.Utc in DateTime. Before the date range was sent as yyyy-MM-ddT00:00:00 after the fix it appeared as yyyy-MM-ddT00:00:00Z.

Good luck

**Comment by msaad1986** [comment]
I was facing same issue, 
I found out the work around that Report does not work with specific client's authentication token, when i change the authentication token of another account, Same report do work and gets downloaded.

**Comment by techashutosh1729** [comment]
I am facing the same issue. I cannot access the seller GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT.
Whenever i try for vendor then it gives exception that access is forbidden.
I got the url and then saved the data in an txt file. When i open the txt file it says `"errorDetails" : "A client error occurred. Please double check that your parameters are valid and fulfill the requirements of the report type."`. It always gives status as  FATAL.

**Comment by msaad1986** [comment]
@techashutosh1729 This issue got resolved at my end. I had to use different account credentials.
Somehow the account which i was using to get report data, its rights got revoked. Then i tried another account for same region and it worked.

**Comment by techashutosh1729** [comment]
@msaad1986 Can you please elaborate whether you are using a seller account or a vendor account? I used multiple accounts but the same is coming every-time.

**Comment by hongfei-zhou** [comment]
I am getting the same error on `GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT`, it was working previously and now returning this error. The parameters are the same as before.
