### ISSUE TITLE
UPLOAD_VAT_INVOICE uploading CreditNote

### ISSUE THREAD

**Issue by LukaszWypych** [amzn/selling-partner-api-docs#3051]
Hello,
reading documentation i see htat while uploading CreditNote via UPLOAD_VAT_INVOICE i need to provide TransactionId. Should i take id from somewhere or should i just generate random id?
It would be nice if documentation would say what id should it be.

**Comment by Xriuk** [comment]
Yes, it's not very clear

**Comment by Xriuk** [comment]
Apparently transactionId refers to the paramereter provided in the VIDR report from Vat Calculation Service. Not sure if without it you could upload credit notes...
