### ISSUE TITLE
[BUG] [SP-API] [Issue] FEE_PROMOTION Notificaitons not working

### ISSUE THREAD

**Issue by metaprice** [amzn/selling-partner-api-docs#3052]
Anyone else facing this problem? We've registered a lot of customers to that notification endpoint, but not a single notification has been received..

**Comment by sungolivia** [comment]
hey @metaprice can you fill out according to the issue template? Otherwise this thread won't be noticed from our team!

**Comment by metaprice** [comment]
This is not completed!
