### ISSUE TITLE
What is the SP-API equivalent Report for GET_FLAT_FILE_ORDERS_DATA?

### ISSUE THREAD

**Issue by VishruthVB** [amzn/selling-partner-api-docs#3053]
I wanted to know whats equivalent report type needs to be used from sp-API which was named **GET_FLAT_FILE_ORDERS_DATA** in **mws**.

**Comment by LukaszWypych** [comment]
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL or GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL depends on what suits you better

**Comment by ritikacd** [comment]
Hi @VishruthVB 
GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING report type should provide the same data. 

Thanks!

**Comment by ritikacd** [comment]
Hi @VishruthVB Can we close the ticket if suggested report works for you?
