### ISSUE TITLE
[BUG] [SP-API]  Trying to use VendorShippingV1Api /vendor/shipping/v1/shipments getShipmentDetails ,but get 404 ResourceNotFound.

### ISSUE THREAD

**Issue by niesheng** [amzn/selling-partner-api-docs#3060]
## I'm submitting a Bug report.

<pre><code>
$config = new \SellingPartnerApi\Configuration([
            "lwaClientId" => "XXX",
            "lwaClientSecret" => "XXX",
            "lwaRefreshToken" => "XXX",
            "awsAccessKeyId" => "XXX",
            "awsSecretAccessKey" => "XXX",
            "endpoint" => \SellingPartnerApi\Endpoint::EU,  
            "roleArn" => "XXX",
        ]);
        
        $apiInstance = new \SellingPartnerApi\Api\VendorShippingV1Api($config);
        $limit = 1; 
        sort_order = 'DESC';
        $created_after = '2023-01-01T00:00:00Z'; 
        $next_token = null;
        $result =  $apiInstance->getShipmentDetails($limit , $sort_order , $next_token , $created_after);
        print_r($result->getPayload());
</code></pre>

## SP-API Name and Version or Report/Feed Type
VendorShippingV1Api 
getShipmentDetails 
## Expected Behavior
 Get the shipment details.

## Current Behavior
Response code : 404  ResourceNotFound
Response message : Cannot find resource by the given URI

## Your Environment
Both PHP code and POSTMAN requests are used, and both return 404 errors.

**Comment by puppsupr** [comment]
Hi @niesheng,

Can you please [open a support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) so we can pursue the investigation as additional details are required from your end.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by niesheng** [comment]
> Hi @niesheng,
> 
> Can you please [open a support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) so we can pursue the investigation as additional details are required from your end.
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

Sure,I have submitted a case, hope it will be resolved.Thanks.
