### ISSUE TITLE
[BUG] [SP-API] [Issue] getMyFeesEstimates() returnsThere is an client-side error. Please verify your inputs

### ISSUE THREAD

**Issue by somin-elateagency** [amzn/selling-partner-api-docs#3065]
## I'm submitting a...

<pre>Issue regarding fees related sp api.Please let me know if this is required to assign 
any permission from Amazon Developer Central </pre>

## SP-API Name and Version or Report/Feed Type
Product Fees API v0
getMyFeesEstimateForASIN

## Expected Behavior
Should return fees value

## Current Behavior
Working good for marketplace UK but giving error for other marketplaces(DE,FR,IT,ES).

## Context/Screenshots

THIS IS THE RESPONSE OF LISTING API.
![image](https://user-images.githubusercontent.com/127078588/230554294-656e1771-7b11-4513-87b2-acb20adfcabd.png)

**Comment by dartheditous** [comment]
Could it simply be that you need to specify the list price in the marketplace's native currency, e.g. EUR?

**Comment by somin-elateagency** [comment]
> Could it simply be that you need to specify the list price in the marketplace's native currency, e.g. EUR?

Given screenshot is response of listing api.
https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference
As per api documentation ,this api accepts ASIN and sell price as an inputs.There is no parameter to send Currency.

Please elaborate if I'm wrong.

**Comment by HardBrick21** [comment]
Because sellers do not have some attributes set up for this ASIN, so that the fee service can not calculate the fba fee

**Comment by somin-elateagency** [comment]
> 

Which type of attributes ?Can you please give me some ideas ?

**Comment by somin-elateagency** [comment]
> Could it simply be that you need to specify the list price in the marketplace's native currency, e.g. EUR?

Yes You're correct .Listing price option is there in body parameter .Solved!

**Comment by gokigoks** [comment]
I'm still getting this issue. 

Small sample ASINs: B07733Q47J , B0773FSRJP, B0773CY498, B0773HBGWB. 

### Response:

```
{
   "payload":{
      "FeesEstimateResult":{
         "Status":"ClientError",
         "FeesEstimateIdentifier":{
            "MarketplaceId":"ATVPDKIKX0DER",
            "SellerId":"XXXXXXXXXXXXX",
            "IdType":"ASIN",
            "IdValue":"B07733Q47J",
            "IsAmazonFulfilled":true,
            "PriceToEstimateFees":{
               "ListingPrice":{
                  "CurrencyCode":"USD",
                  "Amount":89.26
               }
            },
            "SellerInputIdentifier":"B07733Q47J"
         },
         "Error":{
            "Type":"Sender",
            "Code":"InvalidParameterValue",
            "Message":"There is an client-side error. Please verify your inputs.",
            "Detail":[]
         }
      }
   }
}
```

I hope we can get more details from the error response on which field is causing the issue.
