### ISSUE TITLE
`Invalid empty value provided in patch at index of 0.` even though `value` is being provided.

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#3068]
Previously (as referenced in bug #3005 and bug #3031) Seller Support indicated that the `start_at` field is not allowed to be specified for `value`.  It's possible that's the reason for this error:

```
Content-Length: 300

{"patches": [{"op": "replace", "path": "/attributes/purchasable_offer", "value": {"currency": "USD", "start_at": {"value": "2001-06-06T07:00:00.000Z"}, "end_at": {"value": null}, "our_price": [{"schedule": [{"value_with_tax": 99.99}]}], "marketplace_id": "ATVPDKIKX0DER"}}], "productType": "PRODUCT"}



400
Date: Mon, 10 Apr 2023 13:09:56 GMT
Content-Type: application/json
Content-Length: 156
Connection: keep-alive
x-amzn-RequestId: 09a7f83e-bf13-4aea-88a1-9b8f0a2115f0
x-amzn-RateLimit-Limit: 5.0
x-amz-apigw-id: DKaZ0EcEoAMFkpg=
X-Amzn-Trace-Id: Root=1-64340aa4-0000000009a7f83ebf134aea
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid empty value provided in patch at index of 0.",
      "details": ""
    }
  ]
}
```

**Comment by rodrifed** [comment]
Hi @johnkw,

`purchasable_offer` attribute is of type array:
```
"purchasable_offer": {
        "title": "Purchasable Offer",
        "description": "The attribute indicates the Purchasable Offer of the product",
        "type": "array",
        ...
```
Therefore, you have to specify it's value under square brackets, like this:
```
{
        "patches": [
                {
                        "op": "replace",
                        "path": "/attributes/purchasable_offer",
                        "value": [
                                {
                                        "currency": "USD",
                                        "start_at": {
                                                "value": "2001-06-06T07:00:00.000Z"
                                        },
                                        ...
                                }
                        ]
                }
        ],
        "productType": "PRODUCT"
}
```

I hope the information above was useful.

Thank you,
Federico Rodriguez
Selling Partner Developer Services

**Comment by johnkw** [comment]
Oh wow thanks! So either Seller Support was wrong or bug #3031 just got fixed, because by sending that as an array I just successfully updated `start_at`.

The `400` response in this bug #3068 is wildly broken though.  Instead of:
`Invalid empty value provided in patch at index of 0.`
 it should say :
`"patches">"value" must be an array`

**Comment by johnkw** [comment]
If anything this bug should remain open, and bug #3031 should be closed.  This bug is about the horrible error message.

**Comment by johnkw** [comment]
@rodrifed sure would be good to re-open this one and close bug #3031 instead.

**Comment by rodrifed** [comment]
Hi @johnkw,

Thank you for your feedback.
While it is true that the error message could be improved, it is indicating the nature of the error. Therefore, it is not considered a bug.
But we will definitely use this to try to provide a better message.

Thank you,
Federico Rodriguez
Selling Partner Developer Services

**Comment by johnkw** [comment]
This should remain open so that when other people hit this bug it's easier to find in searches, even if the bug is not planning to be fixed any time soon.

**Comment by golliholzland** [comment]
since amazon won't fix  their API, maybe we should add this issue to the documentation
