### ISSUE TITLE
Unable to fetch purchaseOrders

### ISSUE THREAD

**Issue by DanielPurty** [amzn/selling-partner-api-docs#3072]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I am trying to get the purchase order of a vendor , by "**/vendor/directFulfillment/orders/v1/purchaseOrders**"
but the API is giving response as "_Access to requested resource is denied_",
I have used /created RDT by the following payload :[ {
         "method": "GET",
         "path": "/vendor/directFulfillment/orders/v1/purchaseOrders",
     }]

## Current Behavior

[{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': 'The access token you provided is revoked, malformed or invalid.'}]

**Comment by puppsupr** [comment]
Hi,

Can you please [open a support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) so we can pursue the investigation as additional details are required from your end.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
