### ISSUE TITLE
How to use the sp-api in EU

### ISSUE THREAD

**Issue by iAccidentallyGitHub** [amzn/selling-partner-api-docs#3088]
Hello,

I'm trying to integrate sp-api into our .NET solution in order to upload invoices to Amazon in Germany. I found this guide:
https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-the-c-sdk
I have followed it up to step 5 -I have cloned the selling-partner-api-models by running
`git clone https://github.com/amzn/selling-partner-api-models
`
Step 6 says to take a JSON file from the subfolders and copy it to to C:\SwaggerToCL. However, when I looked at the JSON files, I noticed they are specific for North America. They all contain the following string:
`ellingpartnerapi-na.amazon.com`
while some of them even appear to be specific to Brazil, containing the following:
```
"paths": {
    "/fba/outbound/brazil/v0/shipments/{shipmentId}": {
```

The guide doesn't contain any region specific instructions. 

How can I make it work for Germany? I suppose I could replace "https://sellingpartnerapi-na.amazon.com/" with "https://sellingpartnerapi-eu.amazon.com/" (according to this page https://developer-docs.amazon.com/sp-api/docs/sp-api-endpoints) but I have no idea what to do about "/fba/outbound/brazil/v0/shipments/{shipmentId}". Or do I not need that one for Germany?

Or am I missing something, and this whole thing is unusable for Europe?

Also, step 6 of the guide says 
"Navigate to the selling-partner-api-models\models folder in your local copy of the repository and copy a JSON file from the models subfolders into C:\SwaggerToCL. This blog post uses the [Sellers.json](https://github.com/amzn/selling-partner-api-models/tree/main/models/sellers-api-model) file."
I don't quite understand this. Do I get different parts of the API, based on which file I choose? If so, which file do I need in order to be able to upload invoices?
(I'm assuming uploading invoices is possible based on this https://github.com/amzn/selling-partner-api-docs/issues/404 )

**Comment by iAccidentallyGitHub** [comment]
Also, is there someone I could talk to about raising the version of .NET for the generated C# solution? It gave me .NET framework 4.7.2. and I had to spend considerable effort upgrading it to .NET 5.0

**Comment by skrzyh** [comment]
For upload invoice you need use https://github.com/amzn/selling-partner-api-models/blob/main/models/feeds-api-model/feeds_2021-06-30.json  type UPLOAD_VAT_INVOICE
