### ISSUE TITLE
Search Terms Report returning less data

### ISSUE THREAD

**Issue by kmander** [amzn/selling-partner-api-docs#3105]
We've noticed the GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT (using the daily reportPeriod) is now returning significantly less data than previously. This appears to have changed from 24th March onwards.

Amazon did make an announcement that from 15th March onwards, the data was set to to be more accurate. But I am not aware of any announcements of less data being available.

Formally, the dataset for the DAY reportPeriod would contain data on 1-2M search terms. Currently, it has now become around 350k search terms.

Regards,
Keith

**Comment by rugved1991** [comment]
Hi @kmander,

Thanks for reaching out. Can you please open a [developer support case](https://developer.amazonservices.com/support) with the report details showing discrepancy?
Please include the report information that showed 1M records and also details for the report showing 360K records. This would help us investigate the issue further. Please add the case ID here once it is created.

Best,
Rugved
Solutions Architect, SP API

**Comment by kmander** [comment]
@rugved1991: caseID = 12686443341

**Comment by rugved1991** [comment]
Hi @kmander,

Thanks for your patience. I have received an update from the internal teams that we have updated our click threshold to show the highest quality data and reduce the number of search terms with the lowest customer engagement. 

Best,
Rugved
Solutions Architect, SP API

**Comment by kmander** [comment]
Many thanks for following up on this, Rugved.

Might you also be able to find out what is the threshold for data that is included in the Top Search Terms report? The 'daily' report contains some 350k search terms. But there will be many more search terms that users do use. So what determines whether or not a search term is included in that daily report? I assume it might be that it had X number of searches, or produced X number of clicks/purchases?

Thanks again,
Keith

**Comment by takeno-dev** [comment]
I am also encountering the same problem.
Since March 25, the number of records has been greatly reduced by the fact that "department_name" is now only "Amazon.co.jp".
