### ISSUE TITLE
[BUG] [SP-API] [Issue][Reports]

### ISSUE THREAD

**Issue by newsandeep** [amzn/selling-partner-api-docs#3116]
Hi,
I have generated report for GET_MERCHANT_LISTINGS_ALL_DATA with dataStartTime and  dataEndTime but we are getting all listing data.
example - send input -
 {
  "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
  "dataStartTime": "2015-05-01T17:11:24.000Z",
  "dataEndTime": "2015-05-10T20:11:24.000Z",
  "marketplaceIds": [
    "A21TJRUUN4KGV"
  ]
}
got output - 
300	1	2021-06-02 15:25:33 IST	
499	25	2023-01-18 17:08:56 IST

please help me asap.

**Comment by rugved1991** [comment]
Hi @newsandeep,

Thanks for reaching out. The Inventory reports do not use the start and end data timestamps from the createReport request. These inventory reports will provide you a list of all applicable listings for the seller depending on the type of the inventory report requested.

Best,
Rugved
Solutions Architect, SP API
