### ISSUE TITLE
[BUG] [SP-API] [Issue] US Only GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT Schema Breaking Changes

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-docs#3117]
Promo Required Qty - Goal 1 (5/15/2023 to 6/14/2023) | Promo Required Qty - Goal 2 (6/15/2023 to 7/14/2023) | Promo Required Qty - Goal 3 (7/15/2023 to 8/14/2023) | Fulfillment Fee Discount - Goal 1 (5/15/2023 to 6/14/2023) | Fulfillment Fee Discount - Goal 2 (6/15/2023 to 7/14/2023) | Fulfillment Fee Discount - Goal 3 (7/15/2023 to 8/14/2023) | Received Qty - Goal 1 (5/15/2023 to 6/14/2023) | Received Qty - Goal 2 (6/15/2023 to 7/14/2023) | Received Qty - Goal 3 (7/15/2023 to 8/14/2023) | Discount earned - Goal 1 (5/15/2023 to 6/14/2023) | Discount earned - Goal 2 (6/15/2023 to 7/14/2023) | Discount earned - Goal 3 (7/15/2023 to 8/14/2023)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

The  `GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT` seems to have several additional columns recently added as of 5/10 for the US only.  These columns are absent in other reports for the same seller in other marketplaces (CA, MX). These columns are also absent in other regions (EU).

There is no documentation on these columns, nor are any changes in report definition for the US located here https://developer-docs.amazon.com/sp-api/docs/fba-inventory-reports-attributes#get_restock_inventory_recommendations_report

As column names, these need to be clarified given the variation they reflect by including actual data range references. We would strongly advise against including column names like the ones above as they are highly volatile, given the use of data ranges.

Could you confirm these changes?

**Comment by tspicer** [comment]
It appears that this impacts *some*, but not all US Sellers. Why this is occurring for some sellers and not others is unclear. The UI report exports also have these new columns for impacted accounts.

**Comment by bharathsundaresan23** [comment]
Any updates in this? We are facing the same issue.

**Comment by tspicer** [comment]
@bharathsundaresan23, we have not heard any news. Strangely, it appears on some US Seller accounts instead of others, making it difficult to troubleshoot.

**Comment by tspicer** [comment]
Hey @rugved1991 , any insight into this issue? This report's export from the UI also includes these new columns for some sellers. I assume this is a bug. However, is there a setting, like report localization, that the seller needs to turn off/on that will remove these columns?

**Comment by tspicer** [comment]
For reference, the Amazon-provided documentation for schemas does not include these columns:
https://developer-docs.amazon.com/sp-api/docs/fba-inventory-reports-attributes#get_restock_inventory_recommendations_report

This is a critical bug as the report is not meeting defined specifications.

**Comment by tspicer** [comment]
It looks like Amazon is running some special promotions for select sellers. As a result, the promotion is introducing breaking changes to report schemas. 

The promotion is referenced in the Amazon UI:

![screenshot-sellercentral amazon com-2023 05 24-22_14_05](https://github.com/amzn/selling-partner-api-docs/assets/3750968/85ed2782-e149-4665-83f3-c7a89e023a1c)

In the UI, you can see references to these columns that do not follow any known documentation, deviate from the published schema, and impact the API outputs. Amazon should NOT be introducing transitory schemas based on a limited-time promotion.  As it stands, any seller offered this promotion will have these reports continue to fail.

<img width="636" alt="Screenshot 2023-05-24 at 10 15 24 PM" src="https://github.com/amzn/selling-partner-api-docs/assets/3750968/c504d3b6-300c-46cc-8e65-47e501457008">

@bharathsundaresan23 , you may want to explore asking your customers how they can OPT OUT of this promotion so they can have their reports operational and reports reverted to the documented standard. Not sure that will work, but it is worth a try.

**Comment by wolendranh** [comment]
Hi! 
Fields were changed once again. 
Instead of something like
```
Promo Required Qty - Goal 1 (5/15/2023 to 6/14/2023)
```
Even new fields were introduced:
```
'Goal 1 Time-period' 
```
Are there any communications of why this is happening?
