### ISSUE TITLE
[BUG] [SP-API] [Issue] - Exception when calling ReportsV20210630Api->getReports: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }

### ISSUE THREAD

**Issue by aws-beginner-1108** [amzn/selling-partner-api-docs#3119]
```
I tested the below code in Post man and working fine with the credentials I provided in the configuration

I requested added all the information you explained in your example to fetch order or report but none of them is working

require 'vendor\autoload.php';
use SellingPartnerApi\Api\OrdersV0Api;
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "--added lwa client id---",
    "lwaClientSecret" => "--added lwa client secret---",
    "lwaRefreshToken" => "--added lwa refresh token---",
    "awsAccessKeyId" => "--added AWS Access ID---",
    "awsSecretAccessKey" => "--added AWS Secret Access Key---",
    "endpoint" => SellingPartnerApi\Endpoint::NA  // or another endpoint from lib/Endpoints.php
]);

$apiInstance = new SellingPartnerApi\Api\ReportsV20210630Api($config);
$report_types = array('GET_MERCHANT_LISTINGS_ALL_DATA'); // string[] | A list of report types used to filter reports. Refer to [Report Type Values](https://developer-docs.amazon.com/sp-api/docs/report-type-values) for more information. When reportTypes is provided, the other filter parameters (processingStatuses, marketplaceIds, createdSince, createdUntil) and pageSize may also be provided. Either reportTypes or nextToken is required.
$processing_statuses = array("REPORT_PROCESSING_FINISHED");
$marketplace_ids = array('A2RV2UH9I0FQ8N'); 
$page_size = 10;
$created_since = '2023-04-01T00:00:00Z';
try {
    $result = $apiInstance->getReports($report_types, $processing_statuses, $marketplace_ids, $page_size, $created_since);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ReportsV20210630Api->getReports: ', $e->getMessage(), PHP_EOL;
}


Expected Result :- should be return of reports list

But 
Actual Result :-  Exception when calling ReportsV20210630Api->getReports: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }


```

**Comment by aws-beginner-1108** [comment]
<?php
require str_ireplace('test','',__DIR__).'test\spapi\vendor\autoload.php';
use SellingPartnerApi\Api\OrdersV0Api;
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "--added lwa client id---",
    "lwaClientSecret" => "--added lwa client secret---",
    "lwaRefreshToken" => "--added lwa refresh token---",
    "awsAccessKeyId" => "--added AWS Access ID---",
    "awsSecretAccessKey" => "--added AWS Secret Access Key---",
    "endpoint" => SellingPartnerApi\Endpoint::NA  // or another endpoint from lib/Endpoints.php
]);

$apiInstance = new SellingPartnerApi\Api\ReportsV20210630Api($config);
$report_types = array('GET_MERCHANT_LISTINGS_ALL_DATA'); // string[] | A list of report types used to filter reports. Refer to [Report Type Values](https://developer-docs.amazon.com/sp-api/docs/report-type-values) for more information. When reportTypes is provided, the other filter parameters (processingStatuses, marketplaceIds, createdSince, createdUntil) and pageSize may also be provided. Either reportTypes or nextToken is required.
$processing_statuses = array("REPORT_PROCESSING_FINISHED");
$marketplace_ids = array('A2RV2UH9I0FQ8N'); 
$page_size = 10;
$created_since = '2023-04-01T00:00:00Z';
try {
    $result = $apiInstance->getReports($report_types, $processing_statuses, $marketplace_ids, $page_size, $created_since);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ReportsV20210630Api->getReports: ', $e->getMessage(), PHP_EOL;
}

**Comment by GJ-JG** [comment]
Hi @aws-beginner-1108 , thanks for using SP-API.

Have you checked our blog about Unauthorized trouble shooting?
Here are the related blogs you can refer to:

https://developer-docs.amazon.com/sp-api-blog/docs/troubleshooting-selling-partner-api-authorization-errors
https://developer-docs.amazon.com/sp-api-blog/docs/ensuring-healthy-seller-account-status
Best,
Jiang
