### ISSUE TITLE
GET to /fba/inbound/v0/shipmentItems - Invalid Input [BUG] [SP-API]

### ISSUE THREAD

**Issue by GonzaloGDV** [amzn/selling-partner-api-docs#3125]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

It should return a list of items in a specified inbound shipment, or a list of items that were updated within a specified time frame.

## Current Behavior

It returns an error message.  "code": "InvalidInput", "message": "Either the ShipmentId or a pair of LastUpdatedAfter and LastUpdatedBefore must be passed in input", "details": "".

## Your Environment

I am working in Postman and amazon-sp-api NPM package. Both return the same error message.
My URL: https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipmentItems?ShipmentId=FBA16QYHFC4N&LastUpdatedAfter=2022-04-30T03:58:30Z&LastUpdatedBefore=2022-05-15T03:58:30Z

**Comment by rugved1991** [comment]
Hi @GonzaloGDV,

Thanks for reaching out. The request you are sending is incorrect. You can either use Timestamps or NextToken to get the list of shipment items. You cannot use both in the request. Which param you are going to use should be informed using the "QueryType" query parameter.
Example request should be:
https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipmentItems?LastUpdatedAfter=2022-04-30T03:58:30Z&LastUpdatedBefore=2022-05-15T03:58:30Z&QueryType=DATE_RANGE

I hope this helps. I will work with the internal team to correct the error message as this operation does not accept ShipmentId.

Best,
Rugved
Solutions Architect, SP API

**Comment by mtarique** [comment]
HI @GonzaloGDV

I am getting the same error after making request `$api->getShipmentItemsByShipmentId($fbaShpId, $mpId);` I am getting a NextToken and then when I am making `$api->getShipmentItems('NextToken', $nextToken); `I am getting 

```
"errors": [
    {
      "code": "InvalidInput",
      "message": "Either the ShipmentId or a pair of LastUpdatedAfter and LastUpdatedBefore must be passed in input",
      "details": ""
    }
  ]
```

**Comment by mtarique** [comment]
Hi, 

I solved this but I have to look at their API code in PHP jlevers selling partner API for correct order of parameters and obviously yes it's not clearly mentioned in their documentation - 

So, for example in order to make getShipmentItems api call with next token we have to make it in this way `$api->getShipmentItems('NEXT_TOKEN', $mpId, '', '', $nextToken);`

**API Code** 
/**
     * Operation getShipmentItems
     *
     * @param  string $query_type Indicates whether items are returned using a date range (by providing the LastUpdatedAfter and LastUpdatedBefore parameters), or using NextToken, which continues returning items specified in a previous request. (required)
     * @param  string $marketplace_id A marketplace identifier. Specifies the marketplace where the product would be stored. (required)
     * @param  string $last_updated_after A date used for selecting inbound shipment items that were last updated after (or at) a specified time. The selection includes updates made by Amazon and by the seller. Must be in ISO 8601 format. (optional)
     * @param  string $last_updated_before A date used for selecting inbound shipment items that were last updated before (or at) a specified time. The selection includes updates made by Amazon and by the seller. Must be in ISO 8601 format. (optional)
     * @param  string $next_token A string token returned in the response to your previous request. (optional)
     *
     * @throws \SellingPartnerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SellingPartnerApi\Model\FbaInboundV0\GetShipmentItemsResponse
     */
    public function getShipmentItems($query_type, $marketplace_id, $last_updated_after = null, $last_updated_before = null, $next_token = null)
    {
        $response = $this->getShipmentItemsWithHttpInfo($query_type, $marketplace_id, $last_updated_after, $last_updated_before, $next_token);
        return $response;
    }
    
    **If your next token contains any next pages it will return them if not it will simply returns nothing**
