### ISSUE TITLE
/mfn/v0/shipments The Amazon Terms and Conditions were not accepted

### ISSUE THREAD

**Issue by lifu521** [amzn/selling-partner-api-docs#313]
The Amazon Terms and Conditions were not accepted
I want to create logistics information, but the above prompt appears, how do I solve it

**Comment by ShivikaK** [comment]
Hello @lifu521 

Can you please attach the screenshot of the prompt you received?

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by lifu521** [comment]
> 你好@ lifu521
> 
> 您能否附上收到的提示的屏幕截图？
> 
> 谢谢，
>  Shivika Khare 
> 销售合作伙伴API开发人员支持

![21](https://user-images.githubusercontent.com/29915412/105113358-b84ac400-5aff-11eb-9f4f-57c913295805.png)
![22](https://user-images.githubusercontent.com/29915412/105113370-bbde4b00-5aff-11eb-9972-ddf75196d49e.png)
The above indicates that my input is wrong, but I don't know what is wrong,Thank you very much for your reply

**Comment by lifu521** [comment]
> 你好，
> 
> 您可以检查收到的有关此货件的“获得合格的运输服务”请求的回复吗？该错误表明您为该货件选择的运输服务无效，因为不接受使用该运输服务的条款和条件。

**Comment by lifu521** [comment]
> Hello,
> 
> Can you check the response you received for Get Eligible Shipping Services request for this shipment? The error indicates that the Shipping Service that you have selected for the shipment is not valid, as terms and conditions were not accepted to use this shipping service.

Another question is where can I find the **ShippingServiceID**，The documentation just says it's a string

**Comment by ShivikaK** [comment]
For Merchant Fulfillment API, you first request the list of shipping services by using Get Eligible Shipping Services API. The response contains shipping service IDs which are acceptable for your shipment.

Please refer to reference guide for more details - https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md

**Comment by herolzwcj** [comment]
> The Amazon Terms and Conditions were not accepted I want to create logistics information, but the above prompt appears, how do I solve it

你的问题有解决了吗？我也遇到一些merchantFulfillment类的问题，能否一起探讨一下，我的微信号jsonluo
