### ISSUE TITLE
[BUG] [SP-API] [Issue] /fba/inventory/v1/summaries returns incomplete dataset when startDateTime parameter is specified

### ISSUE THREAD

**Issue by sergeyv-pipe17** [amzn/selling-partner-api-docs#3130]
## I'm submitting a...
<pre><code>[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
GET /fba/inventory/v1/summaries should allow to fetch all inventory items modified after date-time value provided in startDateTime parameter

### Prerequisites
- there are approximately 500 SKUs in seller central account, inventory levels are changing rapidly for subset of SKUs
- marketplace is ATVPDKIKX0DER
- /fba/inventory/v1/summaries is used with following common parameters
  - details=true
  - granularityType=Marketplace
  - granularityId=ATVPDKIKX0DER&
  - marketplaceIds=ATVPDKIKX0DER

### Test 1.
- pick arbitrary time in the past, e.g. now() - 24h - '2023-05-17T10:40:25Z'
- use /fba/inventory/v1/summaries to iterate through inventory
  - upon receiving each page, for each item retrieved keep values of sellerSku and lastUpdatedTime
  - if pagination.nextToken is available, then execute /fba/inventory/v1/summaries with nextToken={obtained nextToken value}
- once all SKUs received (500 as expected), filter list so that it only includes items with item.lastUpdatedTime > configured since value (e.g. '2023-05-17T10:40:25Z')
- final list would be shorter, for example 100 items

compare results with 

### Test 2.
- use the same since value as in Test 1.
- use /fba/inventory/v1/summaries to iterate through inventory, but now supply additional argument 
  startDateTime={since}
  - upon receiving each page, for each item retrieved keep values of sellerSku and lastUpdatedTime
  - if pagination.nextToken is available, then execute /fba/inventory/v1/summaries with nextToken={obtained nextToken value} and startDateTime={since}
- once all SKUs received compare results with a list obtained in Test 1.
- expectation is that all items those are in Test 1 result will be in Test 2 result as well, however observed results are more than a dozen 
of items is missing in Test 2 compared to Test 1.

### Additional observations
- Nature on pagination.nextToken value varies depending on whether startDateTime parameter is used or not, e.g.
  - when startDateTime is not in use, nextToken is B64({id}:{sku}), but when startDateTime is in use nextToken is B64({some_uuid})
  - when startDateTime is not in use, nextToken is not affected by recently introduced expiration policy of 30 seconds, but when startDateTime is in use nextToken lifetime is limited to 30 seconds.
- Based on results of monitoring this behavior over several days, it appears that Test 2 will always miss the same set of SKUs, regardless of
  - when execution attempt is made
  - what was configured value of {since}
- Based on examining our application logs we believe this behavior was introduced around mid-Apr 2023, around the same time expiration policy was introduced for nextToken

This is quite critical issue since it affects multiple customers of our application, in a way that we can not load up to date inventory information.

**Comment by rugved1991** [comment]
Hi @sergeyv-pipe17,

Thanks for reaching out. Please open a developer support case to investigate the issue further. 
Meanwhile, I would recommend you to take a look at the [FBA_INVENTORY_AVAILABILITY_CHANGES](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#fba_inventory_availability_changes) notification type. This notification type will provide you real time notifications whenever there is a change in the FBA inventory quantities. Currently, the notification frequency is once every 5 minutes. This notification will help to replace the call volume to Reports and FBA Inventory Summaries API.

Best,
Rugved
Solutions Architect, SP API
