### ISSUE TITLE
Unable to get approval for my developer profile. 

### ISSUE THREAD

**Issue by Muthukrish28** [amzn/selling-partner-api-docs#3138]
Kindly assist to approve my developer profile. 

Marketplace submitted in the request?  - ATVPDKIKX0DER
- Developer ID for the software/application/interface being used to submit the request - 904089174636

**Comment by GJ-JG** [comment]
Hi Muthukrish28,

Thanks for using the SP-API.
I believe the corresponding team has handled your request.

Please reopen this issue if it's still not approved/rejected.

Best,
Jiang
