### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by NA-Dev** [amzn/selling-partner-api-docs#3139]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
getListingsItem

## Expected Behavior

I can search, find, and get attributes for every item in my catalog

## Current Behavior

Some items do not have an associated SKU, so I have no way to get attributes for these. It would be better if ASIN was an option for identifier to search with.

## Context/Screenshots

I need shipping dimensions of ALL items in my catalog, and I can't do that with the API since some items are not found. These items exist in the catalog if I log in to the website.

**Comment by sungolivia** [comment]
@NA-Dev  can you update the issue title so others can take a look and not get buried amongst other issues?
