### ISSUE TITLE
[BUG] /fba/inbound/v1/eligibility/itemPreview - Not returning correct ineligibility codes

### ISSUE THREAD

**Issue by Jethro-Wilkinson** [amzn/selling-partner-api-docs#314]
For UK marketplace resource '/fba/inbound/v1/eligibility/itemPreview' is not sending back all of the correct ineligibility codes from what I can tell. There are ASINs that I know are Hazmat that are not returning the correct ineligibility codes.

For instance ASIN: B00AHUR1T6 is hazmat but is still eligible for Amazon fulfilled FBA. This should then get a code of 'FBA_INB_0016' but no codes are returned. No items from the list of ASINs I am using return this code when I know that a number of them should.

Some codes are correct however. I am getting 'FBA_INB_0050' for some ASINs that I know should have it.

**Comment by callumb123** [comment]
I am seeing this exact same issue. It seems like the endpoint is completely broken as it is saying many items are eligible that I know are Hazmat. I have even compared it against Amazon's own Dangerous goods checker (https://sellercentral.amazon.co.uk/gp/help/help.html?itemID=G201003400&language=en_GB) and this endpoint brings back completely different information 

I have raised a support case for this (CaseID: 7131826132) however as always the support handlers are being next to useless and seem to not even know that SP API exists.

**Comment by EthanTheMathmo** [comment]
Having a similar issue. Was trying to use eligibility preview to see which items to order from a wholesaler and the results were often wrong, e.g. B08JL2XSMZ is an item I am not eligible to add to my inventory, but the eligibility preview returned that I was eligible
