### ISSUE TITLE
[BUG] [SP-API] [Issue] /orders/v0/orders Service Issue?

### ISSUE THREAD

**Issue by ahlmackie** [amzn/selling-partner-api-docs#3146]
I'm submitting a...

[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:

API: /orders/v0/orders
host: https://sellingpartnerapi-eu.amazon.com

## Expected Behavior
Until about 4 days ago, return a list of orders

## Current Behavior
getting res status code of 400
All other api endpoints working fine
Was working on off for the last couple of days, now not at all

Is there a service issue?

**Comment by rugved1991** [comment]
Hi @ahlmackie,

Thanks for reaching out. Can you please open a developer support ticket to investigate this issue further? We would need complete request response along with headers to troubleshoot the error.
Developer Support EU: https://developer.amazonservices.co.uk/support
Developer Support NA: https://developer.amazonservices.com/support
Developer Support FE: https://developer.amazonservices.com.au/support

Best,
Rugved
Solutions Architect, SP API
