### ISSUE TITLE
[BUG] /finances/v0/orders/{orderId}/financialEvents - Returning empty arrays

### ISSUE THREAD

**Issue by Jethro-Wilkinson** [amzn/selling-partner-api-docs#315]
For the UK marketplace when trying to get financial events from an order-id I just get empty arrays sent back. I have tested this with orders that I know have been refunded. This is what I get back not matter what order-id I use:
 
    [payload] => Array ( 

        [FinancialEvents] => Array ( 

            [ShipmentEventList] => Array ( ) 
            [RefundEventList] => Array ( ) 
            [GuaranteeClaimEventList] => Array ( ) 
            [ChargebackEventList] => Array ( ) 
            [PayWithAmazonEventList] => Array ( ) 
            [ServiceProviderCreditEventList] => Array ( ) 
            [RetrochargeEventList] => Array ( ) 
            [RentalTransactionEventList] => Array ( ) 
            [PerformanceBondRefundEventList] => Array ( ) 
            [ProductAdsPaymentEventList] => Array ( ) 
            [ServiceFeeEventList] => Array ( ) 
            [SellerDealPaymentEventList] => Array ( ) 
            [DebtRecoveryEventList] => Array ( ) 
            [LoanServicingEventList] => Array ( ) 
            [AdjustmentEventList] => Array ( ) 
            [SAFETReimbursementEventList] => Array ( ) 
            [SellerReviewEnrollmentPaymentEventList] => Array ( ) 
            [FBALiquidationEventList] => Array ( ) 
            [CouponPaymentEventList] => Array ( ) 
            [ImagingServicesFeeEventList] => Array ( ) 
            [TaxWithholdingEventList] => Array ( ) 
            [NetworkComminglingTransactionEventList] => Array ( ) 
            [AffordabilityExpenseEventList] => Array ( ) 
            [AffordabilityExpenseReversalEventList] => Array ( ) 
            [RemovalShipmentAdjustmentEventList] => Array ( ) 
            [RemovalShipmentEventList] => Array ( ) 

        )

    )

**Comment by ahlmackie** [comment]
+1 getting the same issue

**Comment by estebanangel** [comment]
Same problem here

**Comment by stefnats** [comment]
Has anybody got it working?

**Comment by DevLest** [comment]
Has anyone found the issue here?
