### ISSUE TITLE
[BUG] [SP-API] [Issue] Unable to get the release date by getCompetitivePricing API.

### ISSUE THREAD

**Issue by DanielPurty** [amzn/selling-partner-api-docs#3151]
Hi all, 
I have a problem when trying to receive competitivePricing using SP-API. I am unable to get the release date for the asin I have provided.

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

GET /products/pricing/v0/competitivePrice 

## Expected Behavior
Fetch release date , using competitivePrice API . 

## Current Behavior
I was trying to get the release date for a list of asin , I was unable to get the release date for most the asin which I have provided .

**Comment by GJ-JG** [comment]
Hello @DanielPurty , thanks for using SP-API.

I don't see the attribute called "releaseDate" in the response of [getCompetitivePricing](getCompetitivePricing), can you please provide more details?

Best,
Jiang
