### ISSUE TITLE
The application status is published, but OAuth authorization is directed to the MWS authorization page. What's wrong[BUG] Documentation

### ISSUE THREAD

**Issue by 468092882** [amzn/selling-partner-api-docs#316]
The application type is: SP and MWS, the application status has been released, the authorization in the production environment is directed to the MWS authorization page, instead of the SP API user agrees to the authorization page, the test authorization process (version=beta) is normal
![104702377-dfe10b80-5750-11eb-997b-0edf79675b3f](https://user-images.githubusercontent.com/32814680/105113009-10cd9180-5aff-11eb-87d5-4f31c0fb9300.png)

**Comment by ShivikaK** [comment]
Hello,

We have received your case ID referred in https://github.com/amzn/selling-partner-api-docs/issues/288.

Please verify if you submitted the app for publishing after check marking the box "Enable OAuth from Appstore" in Edit App page. If not, please checkmark the box and submit the app again for publishing. 

After a new case has been created for this action, please share the case ID and I will look into expediting the process.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
