### ISSUE TITLE
[BUG] [SP-API] [Issue] Feeds stuck IN_QUEUE

### ISSUE THREAD

**Issue by alixleger** [amzn/selling-partner-api-docs#3161]
## I'm submitting a...

<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

JSON_LISTINGS_FEED / POST_INVENTORY_AVAILABILITY_DATA / POST_PRODUCT_PRICING_DATA feeds processed in less than 5 minutes. 

## Current Behavior

These last few days, each feed is processed in more than 15 minutes.

## Context/Screenshots

Cannot update our offers, create/update/delete our catalog with the SubmitFeed operation.
We have +500k offers to synchronise to 8 Amazon countries and all Feed types (json, xml, flat file) have now a huge processing times (15 minutes minimum for only 10k items).

We made a lot of cases about that, without answer.

**Comment by alixleger** [comment]
Hello @sungolivia , do you have informations about that issue ?

 We have implemented all the best practices: one feed every 20 minutes, maximum size of 10 MiB, our queue always has less than 10 feeds, but the processing time of each one is always bigger than 15 minutes…

**Comment by stefnats** [comment]
we experienced the same thing, i believe there was something stuck at that time. 
it happens regularly, i think, the Listing Items API might be a workaround, but not for that amount of data you are sending.

**Comment by akg397** [comment]
This is probably what happening https://github.com/amzn/selling-partner-api-docs/issues/3227
One stuck feed blocks all feeds
