### ISSUE TITLE
How to modify inventory of different sites in the same sellersku?

### ISSUE THREAD

**Issue by mchui199303** [amzn/selling-partner-api-docs#3167]
When using "Inventory feed" in the feed api or "patchListingsItem" in the listing item API to modify the inventory in Amazon's selling-partner-api, when the FBM inventory is updated for the same SKU in the UK and Pan-Europe, it cannot be updated separately Update the inventory of a certain site, even if the marketplaceIds has been specified in the interface, the result is that all sites of this sku have updated the inventory

**Comment by chapmanjw** [comment]
Within Amazon listings, inventory data (MFN quantity, lead time, restock date, etc.) is handled slightly differently than other data. Most listings data for a SKU applies only to the marketplace it was submitted for (seller + sku + marketplace keyed). However, inventory data is “marketplace agnostic” and applied to the seller + sku without taking into account the marketplace. Depending on your use-case, this can be beneficial. For example, if you have one pool of inventory for FR and ES, you can create listings in both with the same sku to use your one pool of inventory. However, if you have different inventory pools between FR and ES, you would need two different skus to handle those pools separately. 

As we continue to improve our listings experiences, this is something we can consider for a future improvement in our roadmap. 

In the meantime, we should get this on a FAQ somewhere in our developer documentation…
