### ISSUE TITLE
Signature expired - AP-API -Issue

### ISSUE THREAD

**Issue by nikunjhm** [amzn/selling-partner-api-docs#3169]
When I'm submitting Any API request through my PHP Code. I also matched Time zone with Amazon SP API but some times get getting following error. Any solutions ?

`Error: Status code 403: {
  "errors": [
    {
      "message": "Signature expired: 20230601T095950Z is now earlier than 20230601T135450Z (20230601T135950Z - 5 min.)",
     "code": "InvalidSignature"
    }
  ]
}`

**Following is time zone**
Server Time (UTC) GMT: 2023-06-01 13:59:50 pm
EST/EDT Time: 2023-06-01 09:59:50 am

**Comment by MetaMan2000** [comment]
I solved that issue by using GMT rather than my current timezone.

I am on EST and was using EST in my calls -- it would randomly work then randomly fail... switching to GMT solved that issue for me.

**Comment by nikunjhm** [comment]
> I solved that issue by using GMT rather than my current timezone.
> 
> I am on EST and was using EST in my calls -- it would randomly work then randomly fail... switching to GMT solved that issue for me.

First I'm use GMT and it wold total fail. Then I switched EST/EDT then it will work fine but some time it fails. so Little bit hard to figured out the issue.

**Comment by nikunjhm** [comment]
> In your example above it seems you are passing Amazon EST vs. GMT?
> 
> Error: Status code 403: { "errors": [ { "message": "Signature expired: 20230601T095950Z is now earlier than 20230601T135450Z (20230601T135950Z - 5 min.)", "code": "InvalidSignature" } ] }
> 
> Saying your signature is at 9:59 AM vs. they are expecting 1:59 PM (13:59) GMT

If I'm use GMT date I'm getting following error.

`Server Time (UTC) GMT: 2023-06-02 17:11:53 pm
EST/EDT Time: 2023-06-02 13:11:53 pm

Error: Status code 403: {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`

**Comment by MetaMan2000** [comment]
My guess is that switching to GMT has fixed the *TIME* issue with your signature -- now you have some other issue ... for example maybe your policy settings are not set properly to allow the action you are requestion.

I would check that -- I think switching to GMT has "moved you further" to fixing your problem, but that is just a guess as I am new to the API, though I did get mine working fully in the past few days.

**Comment by nikunjhm** [comment]
> My guess is that switching to GMT has fixed the _TIME_ issue with your signature -- now you have some other issue ... for example maybe your policy settings are not set properly to allow the action you are requestion.
> 
> I would check that -- I think switching to GMT has "moved you further" to fixing your problem, but that is just a guess as I am new to the API, though I did get mine working fully in the past few days.

If you have PHP would you please share code sample ?

**Comment by MetaMan2000** [comment]
Sorry I am using PERL and my code is still in test design mode so not very readable.
