### ISSUE TITLE
Getting 400 Errors when getting document ID, but only some times (using same script / call)?

### ISSUE THREAD

**Issue by haakon24** [amzn/selling-partner-api-docs#3175]
Hi everyone,

I have been having an issue lately when I try to retrieve the document ID from the Vendor Central API. The weird thing is that the exact same code / request will work one minute, but then be a bad request the next. Has anyone run into this before? I have tried contacting Amazon support but they are just running me in a circle asking the same questions over and over again without answering.

Here is one of my full calls that failed in case it helps, I can send the exact same request and it will work one minute and fail the next:

GET https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports/73148019502
400
141 ms
Network
Request Headers
x-amz-access-token: myaccestoken
Content-Type: application/json; charset=utf-8
X-Amz-Content-Sha256: myencodedcontent
Host: sellingpartnerapi-na.amazon.com
X-Amz-Date: 20230525T144457Z
Authorization: AWS4-HMAC-SHA256 Credential=mycredential/20230525/us-east-1/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-access-token;x-amz-content-sha256;x-amz-date, Signature=mysignature
User-Agent: PostmanRuntime/7.32.2
Accept: */*
Postman-Token: 31f76eee-17f4-46de-931a-470cdc1c44e4
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 297
Request Body
{
    "reportType": "GET_VENDOR_SALES_REPORT",
    "marketplaceIds": ["A1AM78C64UM0Y8"],
    "dataStartTime": "2023-01-01",
    "dataEndTime": "2023-01-01",
    "reportOptions": {
        "distributorView": "MANUFACTURING",
        "reportPeriod": "DAY",
        "sellingProgram": "RETAIL"
    }
}
Response Headers
Server: Server
Date: Thu, 25 May 2023 14:44:57 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: close
Response Body
x

**Comment by chrisskhoury** [comment]
Hello @haakon24 

I just wanted to check if you are aware of our latest announcement: 

https://developer-docs.amazon.com/sp-api/changelog/api-request-validation-for-400-errors-with-html-response

Technically we will reject requests that are not consistent with [HTTP RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230).

If you see a 400 error AND do not see a standard SP-API response body, check for the presence of a body or content length header for GET requests.

You can find more info in the link that I shared, and troubleshooting tips but the presence of a body or content length header are the most common causes for this.

Best:) 

Christopher El Khoury
Solution Architect
Selling Partner Developer Services

**Comment by chrisskhoury** [comment]
resolving, feel free to reopen if issue persists
