### ISSUE TITLE
[FEATURE] Documentation　There is no reference to the listInboundShipments operation.

### ISSUE THREAD

**Issue by any-yano-kentaro** [amzn/selling-partner-api-docs#3177]
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#inboundshipmentinfo
>Information about the seller's inbound shipments. Returned by the listInboundShipments operation.

- No search hits listInboundShipments

![スクリーンショット 2023-06-07 11 05 34](https://github.com/amzn/selling-partner-api-docs/assets/110013238/b4905f9e-273e-4a4e-b8bc-e306def4532e)

Please specify the location of the reference material.

**Comment by rugved1991** [comment]
Hi @any-yano-kentaro,

Thanks for surfacing the documentation error. I have requested the internal team to fix it. 
I will update this issue when the information is corrected.
Have a great day!

Best,
Solutions Architect, SP API
