### ISSUE TITLE
Hello @davev74

### ISSUE THREAD

**Issue by davev74** [amzn/selling-partner-api-docs#318]
Hello @davev74 

Please share the support case ID and I will look into expediting the issue for assistance.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

_Originally posted by @ShivikaK in https://github.com/amzn/selling-partner-api-docs/issues/291#issuecomment-763272197_

The last issue was locked and I could not add a comment.  The support case issue is 7722238751  thanks

**Comment by davev74** [comment]
7722238751

**Comment by ShivikaK** [comment]
Hello @davev74 

I have unlocked the original issue. I will close this issue out in favor of the original one.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
