### ISSUE TITLE
report still IN_QUEUE after 10 days

### ISSUE THREAD

**Issue by duwenice** [amzn/selling-partner-api-docs#3182]
{"payload":{"reportType":"GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL","processingStatus":"IN_QUEUE","marketplaceIds":["ATVPDKIKX0DER"],"reportId":"604492019501","dataEndTime":"2022-12-06T20:39:54+00:00","createdTime":"2023-05-24T13:51:43+00:00","dataStartTime":"2022-11-06T20:39:54+00:00"}}

**Comment by rugved1991** [comment]
Hi @duwenice,

Please use the issue templates to open new issues. We wont be able to provide recommendations or next steps without it.
For the above issue, please open a developer support case using this [link](https://developer.amazonservices.com/support). The developer support team will be able to troubleshoot the issue and provide guidance. Make sure you add information about the seller ID for whom the report is requested in the support case.
Have a great day!

Best,
Rugved
Solutions Architect, SP API
