### ISSUE TITLE
Clarification regarding amazon items api

### ISSUE THREAD

**Issue by ArvindArvind22** [amzn/selling-partner-api-docs#3185]
I have been using the "/catalog/2022-04-01/items" API for quite some time. 
I use a comma-delimited list of product SKUs as identifiers to search the Amazon catalog. SKU can also be composed using comma. When an SKU with a comma is passed as a query to the API request, it is considered as two SKUs instead of one and I receive this error response message - Too many 'identifiers' provided and Response Code - 400 from Amazon. We provided the max number of SKUs which is 20 but since the SKU had a comma in it, the total number of SKUs in the request is considered as 21. We also tried escaping the SKU using double quotes to preserve it, even that doesn't work. Is there any way to preserve the SKU of an item?

Example:
SKU: ITEMRED, MEDIUM
The SKU belongs to a single item, but it is being considered as two different SKUs based on the delimiter comma when passed as a query to the API.

API reference: [Api Documentation](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#get-catalog2022-04-01items)

**Comment by pkrawetkowski** [comment]
https://developer-docs.amazon.com/sp-api/docs/url-encoding#how-do-i-encode-a-url

check info at the bottom
