### ISSUE TITLE
[BUG] [SP-API] [Issue] image-url empty in _MERCHANT_LISTINGS_ reports

### ISSUE THREAD

**Issue by nrueckmann** [amzn/selling-partner-api-docs#3188]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Reports API v2021-06-30 / Inventory Report / *_MERCHANT_LISTINGS_*

## Expected Behavior
I expect to have the `image-url` included in *_MERCHANT_LISTINGS_* reports according to https://developer-docs.amazon.com/sp-api/docs/inventory-reports-attributes#get_merchant_listings_all_data

## Current Behavior
The columns `image-url`is present, but empty for all listings.

**Comment by stefnats** [comment]
Unfortunately, this is true for years, even in MWS times. 
Workaround is using the Catalog Items API, but difficult for 100k products of a seller.

**Comment by asifkhalid03** [comment]
![WhatsApp Image 2024-01-03 at 18 51 21_d02d8ed9](https://github.com/amzn/selling-partner-api-docs/assets/55079043/a719fc3b-612c-4023-a0cf-1e6b89f844b3)
Still I am facing the issue of empty image, we have image-url key but overall its empty.
