### ISSUE TITLE
ERROR MD5101 - Amazon seller partner 

### ISSUE THREAD

**Issue by himanshu046** [amzn/selling-partner-api-docs#3190]
Hello,
When I try to add an Amazon seller partner account to my website, I get this error.I know this error is related to redirect url mismatches, but I already checked all the links and they seem to be correct. so please help me. feel free to ask me for any further details 

Error Code: MD5101

![image (2)](https://github.com/amzn/selling-partner-api-docs/assets/53367312/a9ad34e9-3ec4-48c0-8416-da81410d9299)

**Comment by chrisskhoury** [comment]
resolving, feel free to reopen if issue persists
