### ISSUE TITLE
How do I update the B2B  price of an offer, using SPAPI ?

### ISSUE THREAD

**Issue by mantaval** [amzn/selling-partner-api-docs#3191]
How do I update the B2B  price of an offer, using SPAPI ?

**Comment by rodrifed** [comment]
Hi @mantaval,

Thank you for your question.

To update B2B prices you can use the [POST_PRODUCT_PRICING_DATA](https://developer-docs.amazon.com/sp-api/docs/feed-type-values#listings-feeds) feed. The same includes a BusinessPrice attribute for this purpose:
```
<xsd:element name="BusinessPrice" type="BasePriceCurrencyAmount" minOccurs="0"/>
```

If you are not currently using the Feeds API, you can find more information on how to create a feed and retrieve the results in the [Feeds API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide).

Thank you,
Federico
Selling Partner Developer Services
