### ISSUE TITLE
Direct to consumer shipping request rejected

### ISSUE THREAD

**Issue by danielerainone** [amzn/selling-partner-api-docs#3198]
Hi,
we are developing a new ERP software which, among the various functions, allows the automatic creation of packing slips for shipments through the various couriers we use and which we have integrated through their APIs.
We have tried to request the "Direct to consumer shipping" role several times without success, we are refused with the following message: "Additionally, we have also determined that you do not meet the requirements for Restricted SP-API. To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon.", CASE ID: 8678071492.

Since we have not found Apps on the store that we can integrate with our software that allow these actions, we would need this role to be approved by us. We wanted to know how we can proceed for approval. We also have our own internal courier that we use for short distances which cannot be supported by any currently existing app, but we have never mentioned it in the requests.

Thanks in advance for the time,
Good day!

**Comment by rodrifed** [comment]
Hi @danielerainone,

Unfortunately, we can not assist you in this channel with your restricted role application.
If you consider that you meet the criteria to get access to the Direct to consumer role, I encourage you to open a new role request and provide as much information as possible to justify your case. Explain how your solution is materially different to others, and provide evidence.
The vetting team will review your request and take action accordingly.

Thank you,
Federico
Selling Partner Developer Services

**Comment by franclin** [comment]
I also have the same issues. From previous cases, it looks like this process is very intricate. Have some recently being granted the Restricted Data Token Roles? 

We actually have several cases opened but to no avail and we have been working on this for over a year and there doesn't seem to be any light at the end of the tunnel. Here are some cases numbers: 12809127971 , 12741617791, 11875357071 all yielding the same results.

 Any tip would be much appreciated.
