### ISSUE TITLE
[EXPLANATION NEEDED] CatalogItems keywords search

### ISSUE THREAD

**Issue by MaksymV1999** [amzn/selling-partner-api-docs#3202]
Good day!

In documentation it is said :

> A comma-delimited list of keywords to search the Amazon catalog for. Note: Cannot be used with identifiers.

But there was nothing about the logic of searching by keywords.

Could you kindly explain the logic behind keywords? 
Is it type of: `keyword || keywords || keywords`  search
or: `keywords && keywords && keywords`  search?

Or  it works even differently?

Many thanks in advance!

**Comment by rodrifed** [comment]
Hi @MaksymV1999,

Thank you for your message.

Different keywords are separated by commas. In between commas, the words are separated by whitespace.
I would suggest that you experiment with the API a bit to see which query (e.g. using a comma after every word) works better for you.

Thank you,
Federico
Selling Partner Developer Services
