### ISSUE TITLE
[BUG] [SP-API] GET FLAT FILE ALL ORDERS DATA BY ORDER DATE GENERAL is giving blank buyer email and buyer name

### ISSUE THREAD

**Issue by naveenpatnana** [amzn/selling-partner-api-docs#3204]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other...
</code></pre>

We are trying to get the anonymous buyer email that Amazon gives in the front-end from GET FLAT FILE ALL ORDERS DATA BY ORDER DATE GENERAL report but it gives back blank data for the column buyer email.

## SP-API Name and Version or Report/Feed Type
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
Version: 2021-06-30
Type: Report

## Expected Behavior
This stream should ideally populate buyer email id and buyer name fields that Amazon provides in the front-end order level report

## Current Behavior
It populates blank buyer email id and buyer name.

## Context/Screenshots
We are trying to estimate the retention rates across different product categories, products and time periods. This information would help us take informed decision on products to offer to retain customers better.

**Comment by ericblade** [comment]
I do believe you need to have special permissions to be able to access identifying information about a customer from the API

**Comment by minifreak** [comment]
Perhaps you may have better luck if you call Orders#getOrderBuyerInfo operation when that data comes empty. I seem to remember I could get more data (but not all)

@ericblade if I'm not mistaken PII restrictions take place when your perform calls on behalf other sellers, you'd need a RDT in those cases. For self-signed apps I don't think that applies.

**Comment by GJ-JG** [comment]
Hi @naveenpatnana , 
Operations that return restricted data (such as Personally Identifiable information, in this case email address) are considered restricted operations, and require special authorization in the form of a Restricted Data Token (RDT).

You can find more details regarding this from:
- https://developer-docs.amazon.com/sp-api/docs/authorization-with-the-restricted-data-token#how-do-i-get-an-rdt
- https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#step-1-get-an-rdt

Best,
Jiang
Solutions Architect, Selling Partner API
