### ISSUE TITLE
[BUG] [SP-API] Has the long term storage fee changed the field name, I get a result of 0 for the data

### ISSUE THREAD

**Issue by ming0607** [amzn/selling-partner-api-docs#3206]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

Reports API v2021-06-30 reference
reportType:  GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA

## Expected Behavior

- I get the following array of results when I get the long term storage fee report. I asked Amazon customer service for this and did not get a valid answer. 

Results:

array (
    'snapshot-date' => '2023-06-15T09:03:00+00:00',
    'sku' => '******************************',
    'fnsku' => '******************************',
    'asin' => '******************************',
    'product-name' => '******************************',
    'condition' => 'New',
    'qty-charged-long-time-range-long-term-storage-fee' => 0,
    'per-unit-volume' => 0.0131,
    'currency' => 'USD',
    'long-time-range-long-term-storage-fee' => 0.0,
    'qty-charged-short-time-range-long-term-storage-fee' => 0,
    'short-time-range-long-term-storage-fee' => 0.0,
    'volume-unit' => 'cubic_feet',
    'country' => 'US',
    'enrolled-in-small-and-light' => 'N',
  ),

## Current Behavior

- From April 2023 onwards, reports that have waited until now have received a valid fee of 0, until now

## Context/Screenshots

- I would like to know if this report has changed fields and when the report will be available with the new field data

**Comment by rodrifed** [comment]
Hi @ming0607,

This report hasn't been updated recently, so you should be able to get the same data that you were getting before.
I would suggest that you verify if the missing column/s are selected in the report configuration in Seller Central account. Some columns can be activated/deactivated, which will influence the data that the SP-API report returns.

If the above doesn't help, could you please confirm which column/s are you missing?

Thank you,
Federico
Selling Partner Developer Services

**Comment by ming0607** [comment]
Thank you for your reply.

However, the content of the document I downloaded from the Seller Central report has changed in the fields after April 2023.
These changes are not mentioned in the SP-API.

The fields returned before April 2023:
qty-charged-long-time-range-long-term-storage-fee
long-time-range-long-term-storage-fee
qty-charged-short-time-range-long-term-storage-fee
short-time-range-long-term-storage-fee
![image](https://github.com/amzn/selling-partner-api-docs/assets/26814589/7cb9e532-1cde-4783-8817-ecbd70812016)


Fields returned after April 2023:
qty-charged
amount-charged
![image](https://github.com/amzn/selling-partner-api-docs/assets/26814589/f210381e-f959-4dbf-b30d-b3a7263d32c1)

**Comment by rodrifed** [comment]
Hi @ming0607,

Have you checked if you have the option to enable these columns in Seller Central?

Thank you,
Federico
Selling Partner Developer Services

**Comment by ming0607** [comment]
Thank you for your answer, I think I have found the reason

I am getting the report for too long a period of time and to get the latest fields I need to adjust the start date of the report to May 2023

I hope this will help anyone who is having the same problem

**Comment by ming0607** [comment]
![image](https://github.com/amzn/selling-partner-api-docs/assets/26814589/b5f2560d-1a63-4beb-a5cd-592f0c16fc2c)

hi
I have another question
Why do I get the results of the report that appear in the picture
Can you help me?

**Comment by rodrifed** [comment]
Hi @ming0607,

In order to troubleshoot this issue, I would kindly ask you to [contact Developer Support](https://developer.amazonservices.com/support).
They will be able to assist you on this.

Thank you,
Federico
Selling Partner Developer Services
