### ISSUE TITLE
[BUG] [SP-API] [Issue] Unauthorized, Access to requested resource is denied. 

### ISSUE THREAD

**Issue by RubenMacapugay** [amzn/selling-partner-api-docs#3208]
There is no error in the syntax. I tried a different solution, but it didn't work at all. I think the error comes from the IAMUSER Account, but I don't know where exactly it is. 

```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}
```
Please, can someone give me some solutions for this? Thank you

**Comment by leonardonakagawa** [comment]
Hello @RubenMacapugay,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support), so we can pursue the investigation, as additional details are required from your end.

Thanks,
Leonardo Nakagawa
Selling Partner API Developer Support
