### ISSUE TITLE
Question: Can I use a standardized authorization HTTP header instead of x-amz-access-token?

### ISSUE THREAD

**Issue by stephen-hill-safe-uk** [amzn/selling-partner-api-docs#3212]
Hello

To authenticate with SP-API you have to send the amazon specific HTTP header "x-amz-access-token".

Is there an alternative way to send the token using standardized http headers such as the "Authorization" header?

Many Thanks
Stephen

**Comment by GJ-JG** [comment]
Hi @stephen-hill-safe-uk ,
Currently SP-API officially supports "x-amz-access-token" as the header key and the value from authorizing step.
[Reference](https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-3-add-headers-to-the-uri)

Best,
Jiang
Solutions Architect, Selling Partner API
