### ISSUE TITLE
How long it takes to get developer account

### ISSUE THREAD

**Issue by yujingtaojing** [amzn/selling-partner-api-docs#3219]
SP-API Developer Profile Created
ID 13145682761

**Comment by kratoskat** [comment]
ours took about 1 month of back and forth. it was fun :)

**Comment by puppsupr** [comment]
Hi,
Closing this since the case has been actioned.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
