### ISSUE TITLE
getMessagingActionsForOrder not contains confirmCustomizationDetails and createConfirmDeliveryDetails message privillege

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-docs#322]
I can't send confirmCustomizationDetails and createConfirmDeliveryDetails message.
Uploads api can't work, return Access to requested resource is denied. can you supply a demo from PHP.

**Comment by ShivikaK** [comment]
Hello @fengmiq 

Did you manage to get past the issues you are facing? 

Please feel free to open a support case with us if you'd like deeper assistance with this.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by fengmiq** [comment]
@ShivikaK please help me，This problem has bothered me for two months

**Comment by ShivikaK** [comment]
Hello @fengmiq 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation. If you have already opened a case with us, please share the case ID with me.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by fengmiq** [comment]
@ShivikaK case ID is 7921222641,Tks!

**Comment by ShivikaK** [comment]
Hello @fengmiq 

Your support case has been received and our team will reach out to you if we require additional information. Please follow the case for updates. 

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
