### ISSUE TITLE
[BUG] [SP-API] [Issue] Invalid value 'JE_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS', 'SG_VOEC', 'GB_VOEC', 'NO_VOEC', 'CA_MPF', 'AU_VOEC', 'NZ_VOEC', 'CH_SUPPLIER_IMPORT'

### ISSUE THREAD

**Issue by dv336699** [amzn/selling-partner-api-docs#3221]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

This issue is similar to the one I'm reporting now 
https://github.com/amzn/selling-partner-api-docs/issues/1000

> Invalid value 'JE_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS', 'SG_VOEC', 'GB_VOEC', 'NO_VOEC', 'CA_MPF', 'AU_VOEC', 'NZ_VOEC', 'CH_SUPPLIER_IMPORT'`

This is a private integration and the seller is UK based.

In seller central I see
> Marketplace facilitator order (legislation: UK VAT on eCommerce): Amazon is collecting VAT on this transaction.
> 
> This is a marketplace facilitator order and hence VAT is being collected and remitted to the tax authorities by Amazon. Your net proceeds will not include VAT for marketplace facilitator order. Please visit [Tax regulations - help page](https://sellercentral.amazon.co.uk/gc/uk-voec-us?ref=VATed_UKVOEC_us) for additional information.

**Comment by jlevers** [comment]
Someone encountered this issue in my library too: https://github.com/jlevers/selling-partner-api/issues/570

**Comment by dv336699** [comment]
@jlevers thanks, I didn't realised it could be an issue with the php library. Closing.

**Comment by mcphelan** [comment]
This bug doesn't look fixed to me -  This breaks code when unrecognised enum is returned.

Are the models going to be updated to include these new Enums? As not mentioned here
https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json

Given the documentations suggest using them here - https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-the-c-sdk
