### ISSUE TITLE
[BUG] [SP-API] [Issue] createReport for `GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT` start returning FATAL status

### ISSUE THREAD

**Issue by hongfei-zhou** [amzn/selling-partner-api-docs#3222]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

**API Name**: createReport
**Version**: 2021-06-30

## Expected Behavior

using `createReport` to request for type `GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT` should return a job status of `DONE` with a document id to download the report. 

## Current Behavior

It is now returning `FATAL` status with message:
```
{
"errorDetails" : "A client error occurred. Please double check that your parameters are valid and fulfill the requirements of the report type."
}
```
It was working previously, nothing changed on the client side when it started returning FATAL.

## Context/Screenshots

```
Report {
    marketplaceIds: [A2EUQ1WTGCTBG2]
    reportId: 73422019541
    reportType: GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT
    dataStartTime: 2023-06-25T00:00Z
    dataEndTime: 2023-07-01T00:00Z
    reportScheduleId: null
    createdTime: 2023-07-03T14:20:12Z
    processingStatus: FATAL
    processingStartTime: 2023-07-03T14:20:18Z
    processingEndTime: 2023-07-03T14:20:30Z
    reportDocumentId: *********************************
}
```

**Comment by chrisskhoury** [comment]
Hello @hongfei-zhou ,

If you can open a developer support case it would be great, they will have the better tools to debug your issue.

Good luck:)

Chris
Solution Architect, SP API
