### ISSUE TITLE
Finance API data issues

### ISSUE THREAD

**Issue by ITmoxiang** [amzn/selling-partner-api-docs#3226]
I found SalesCommission and FBAMultitierPerUnitFee in the Finances API interface ShipmentEventList.Their amount data is positive, but according to the report data provided by the store backend, it is negative. Please check if the following is an API issue. Here is my request message

{
    "AmazonOrderId": "",
    "SellerOrderId": "",
    "MarketplaceName": "Amazon.com",
    "PostedDate": "2023-06-01T03:28:17Z",
    "ShipmentItemList": [
        {
            "SellerSKU": "",
            "OrderItemId": "",
            "QuantityShipped": 12,
            "ItemChargeList": [
                {
                    "ChargeType": "Principal",
                    "ChargeAmount": {
                        "CurrencyCode": "USD",
                        "CurrencyAmount": 131.88
                    }
                }
            ],
            "ItemFeeList": [
                {
                    "FeeType": "FBAMultitierPerUnitFee",
                    "FeeAmount": {
                        "CurrencyCode": "USD",
                        "CurrencyAmount": 38.64
                    }
                },
                {
                    "FeeType": "VariableClosingFee",
                    "FeeAmount": {
                        "CurrencyCode": "USD",
                        "CurrencyAmount": 0.0
                    }
                },
                {
                    "FeeType": "SalesCommission",
                    "FeeAmount": {
                        "CurrencyCode": "USD",
                        "CurrencyAmount": 19.8
                    }
                }
            ]
        }
    ]
}

**Comment by rapidsiege** [comment]
Any new developments on this issue? The API keeps returning some orders with these two positive FeeTypes, while in Sellercentral both in Orders and in the All Transactions report the exact same amounts are in negative with the usual FeeTypes (FBAPerUnitFulfillmentFee + Commission).

**Comment by ITmoxiang** [comment]
> At present, no one has given a solution. Please kindly reply if you find a solution in the future

**Comment by rapidsiege** [comment]
So just to shed some more light on the topic @ITmoxiang, although we don't have a definitive answer:
1. We had issues about a month ago with some `OrderItemId` values from the `listFinancialEventsByGroupId` API suddenly returning `:` at the end. These used to be numeric identifiers, e.g. `192839123095` -> now `192839123095:`
2. Upon checking this, ALL order lines with the `:` issue have `SalesCommission` & `FBAMultitierPerUnitFee`. We believe this might be some sort of flag they've created to avoid generating new columns. Could you share if these orders have this exact same issue on your end?
3. We can confirm that, as you mentioned beforehand, these orders appear in Amazon Sellercentral as if they were regular orders (`Principal` - `Commission` - `FBAPerUnitFulfillmentFee`), and that they have been included in the All Transactions reports and therefore have been paid to us.
4. As mentioned previously, the orders are placed by Amazon and FC of origin and the destination address are a perfect match. Investigating further, we've noticed that, whilst the Inventory Ledger Summary doesn't appear to have anything relevant, the Inventory Ledger Detailed View has a bunch of negative unit movements with the concept `Inventory Ownership Transfer` that essentially add up to the number of units ordered.

Our solution then will be to stop ignoring these orders, and transform the `SalesCommission` & `FBAMultitierPerUnitFee` types to `Commission` & `FBAPerUnitFulfillmentFee` and changing the sign from `+` to `-` to match what's been reported in Sellercentral. If anybody can has any valuable information to share regarding this topic, we'd be grateful.

**Comment by jimmy-ross-xapix** [comment]
did anyone hear any details directly from Amazon regarding this problem?
