### ISSUE TITLE
[BUG] [SP-API] [Issue] - feeds get stuck "IN_PROGRESS" causing complete stoppage of updates for days (i.e. Inventory)

### ISSUE THREAD

**Issue by akg397** [amzn/selling-partner-api-docs#3227]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
JSON_LISTINGS_FEED

## Expected Behavior

Expected Behavior: Feed processing should complete with DONE or Fatal

## Current Behavior
On occasion feeds get stuck "IN_PROGRESS" status for several days. 
Examples of stuck FEEDID: 209297019528, 209541019529, 209542019529, 210348019546
I believe the stuck feed issue have higher chance of occurring if feeds contains updates to multiple data points. Probably update time out and cause feed to get stuck.

## Context/Screenshots
Once a feed get stuck in  "IN_PROGRESS" - no further feeds will process. Can't send any more updates like inventory. Stuck feeds can only be cancelled by support - turnaround on ticket is few days.

**Comment by alixleger** [comment]
Same issue here, a feed is currently stuck "IN_PROGRESS" for almost 60 hours, blocking all our processing queue...

**Comment by akg397** [comment]
> Same issue here, a feed is currently stuck "IN_PROGRESS" for almost 60 hours, blocking all our processing queue...

In my experience - Once it stuck for more than 10 minutes - it will be stuck forever. You can't abort processing on your own. You will to open ticket to support - seems to be 3 days turnarround

**Comment by rodrifed** [comment]
Hi @akg397,

Thank you for your message.

We suggest that you take a look at the [Feeds API best practices](https://developer-docs.amazon.com/sp-api/docs/feeds-api-best-practices) in order to optimize your feeds workflows, which should help you prevent issues like the one you describe.

Thank you,
Federico
Selling Partner Developer Services

**Comment by akg397** [comment]
I did look at "best practices " there is no solution there.

> Hi @akg397,
> 
> Thank you for your message.
> 
> We suggest that you take a look at the [Feeds API best practices](https://developer-docs.amazon.com/sp-api/docs/feeds-api-best-practices) in order to optimize your feeds workflows, which should help you prevent issues like the one you describe.
> 
> Thank you, Federico Selling Partner Developer Services



> Hi @akg397,

> We suggest that you take a look at the [Feeds API best practices](https://developer-docs.amazon.com/sp-api/docs/feeds-api-best-practices) in order to optimize your feeds workflows, which should help you prevent issues like the one you describe.

I did look at "best practices " there is no solution to there
