### ISSUE TITLE
[BUG] [SP-API] [Issue] How to delete max_order_quantity

### ISSUE THREAD

**Issue by lai3221** [amzn/selling-partner-api-docs#3234]
For example:
I had set the max_order_quantity value for sku XXXXXXX;
so,how to delete max_order_quantity value?

**Comment by chrisskhoury** [comment]
Hello @lai3221,

For deleting an attribute value from the listing, you can call the [patchListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2020-09-01-reference#patch-listings2020-09-01itemsselleridsku) operation to partially update a listing using the Listings Items API. This includes the delete operation.

You can find an example here:
https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2020-09-01-use-case-guide#step-1-submit-listings-item-patch-request

Make sure to provide the correct path for the attribute.

Best,
Chris 
Solution Architect, Amazon
