### ISSUE TITLE
Vendor Access

### ISSUE THREAD

**Issue by Scan1337** [amzn/selling-partner-api-docs#3235]
Hi there. I am using the /items endpoint to get information for the requested product:

GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items
  ?identifiers=XXXXXXXXX,YYYYYYYY,ZZZZZZZZ
  &identifiersType=ASIN
  &marketplaceIds=ATVPDKIKX0DER
  &includedData=images,productTypes,salesRanks

However I am receiving an error:

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "FORBIDDEN",
            "details": "The includedData requested requires vendor access. Remove the requested includedData item and try again."
        }
    ]
}

I double and triple checked my seller account but unfortunately I can not find the error. I gave the application the right policies and roles specified in the AWS documentation such as AssumeRole and I also gave it fullAccess to PriceList and SellerProducts but still receiving this error. 

Same goes for the pricing endpoint {{host}}/products/pricing/v0/price?MarketplaceId={{marketplaceId}}&Asins=B09L5BG1RF&ItemType=Asin. The response returns success, however there is the offers [] list missing in the response so I am unable to see the offers even tho there should be some.

Someone got any idea where to search or find a solution? Even google search doesn't really help. 
Thanks so much for any help.

**Comment by natamartins** [comment]
The error you are receiving indicates that the request you made requires access to certain data ("includedData") from the supplier, but you do not have permission to access it. The error message suggests removing the "includedData" item from the request and trying again.   
I don't know much, but I think this might help you somehow!

const request = /* sua solicitação HTTP ou chamada de API aqui */;

// Verifique se a resposta contém erros
if (request.errors && request.errors.length > 0) {
  // Verifique se o erro é devido a acesso restrito
  const error = request.errors[0];
  if (error.code === 'InvalidInput' && error.details === 'O includedData solicitado requer acesso do fornecedor. Remova o item includedData solicitado e tente novamente.') {
    // Faça algo para lidar com o erro de acesso restrito, por exemplo, remover o "includedData" da solicitação e tentar novamente
    // Exemplo: request.includedData = null;
    // Em seguida, faça a solicitação novamente
  } else {
    // Lidar com outros erros
    console.error('Erro:', error);
  }
}

**Comment by natamartins** [comment]
n short, we check the response for errors and then check to see if the error is specific to restricted access to "includedData". If that's the case, you can take the appropriate action, such as removing the "includedData" from the request or taking any other necessary action. Otherwise, you can handle other errors or display the error message to the user.

**Comment by natamartins** [comment]
The exact code to handle the error may vary depending on the structure of your request or API call. The above example is a general approach to dealing with the specific error you are experiencing!

**Comment by springhuasheng** [comment]
> Hi there. I am using the /items endpoint to get information for the requested product:
> 
> GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items ?identifiers=XXXXXXXXX,YYYYYYYY,ZZZZZZZZ &identifiersType=ASIN &marketplaceIds=ATVPDKIKX0DER &includedData=images,productTypes,salesRanks
> 
> However I am receiving an error:
> 
> { "errors": [ { "code": "InvalidInput", "message": "FORBIDDEN", "details": "The includedData requested requires vendor access. Remove the requested includedData item and try again." } ] }
> 
> I double and triple checked my seller account but unfortunately I can not find the error. I gave the application the right policies and roles specified in the AWS documentation such as AssumeRole and I also gave it fullAccess to PriceList and SellerProducts but still receiving this error.
> 
> Same goes for the pricing endpoint {{host}}/products/pricing/v0/price?MarketplaceId={{marketplaceId}}&Asins=B09L5BG1RF&ItemType=Asin. The response returns success, however there is the offers [] list missing in the response so I am unable to see the offers even tho there should be some.
> 
> Someone got any idea where to search or find a solution? Even google search doesn't really help. Thanks so much for any help.

您好   是否解决了这个问题呢, 我也遇到这个问题了

**Comment by springhuasheng** [comment]
> Hi there. I am using the /items endpoint to get information for the requested product:
> 
> GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items ?identifiers=XXXXXXXXX,YYYYYYYY,ZZZZZZZZ &identifiersType=ASIN &marketplaceIds=ATVPDKIKX0DER &includedData=images,productTypes,salesRanks
> 
> However I am receiving an error:
> 
> { "errors": [ { "code": "InvalidInput", "message": "FORBIDDEN", "details": "The includedData requested requires vendor access. Remove the requested includedData item and try again." } ] }
> 
> I double and triple checked my seller account but unfortunately I can not find the error. I gave the application the right policies and roles specified in the AWS documentation such as AssumeRole and I also gave it fullAccess to PriceList and SellerProducts but still receiving this error.
> 
> Same goes for the pricing endpoint {{host}}/products/pricing/v0/price?MarketplaceId={{marketplaceId}}&Asins=B09L5BG1RF&ItemType=Asin. The response returns success, however there is the offers [] list missing in the response so I am unable to see the offers even tho there should be some.
> 
> Someone got any idea where to search or find a solution? Even google search doesn't really help. Thanks so much for any help.

includedData=attributes,dimensions,identifiers,images,productTypes,salesRanks,summaries,relationships,vendorDetails, 这是官方文档给出的, 不需要全部填写 填写你想获得的即可, 比如我需要 summaries和 relationships 可正常放回
