### ISSUE TITLE
[BUG] [SP-API] [Issue] ACCOUNT_STATUS_CHANGED missing marketplaceID

### ISSUE THREAD

**Issue by cgaugel** [amzn/selling-partner-api-docs#3236]
We have registered a customer with 2 countries (US / CA) for ACCOUNT_STATUS_CHANGED notification. Now the customer has received an ACCOUNT_STATUS_CHANGED notification that one country is "AT_RISK". But in the notification there is no MarketplaceID, so I can't tell the customer which country is AT_RISK exactly.

Could you please check this @sungolivia ?

Thank you

**Comment by rodrifed** [comment]
Hi @cgaugel,

This notification is at the account level, and not strictly related to a specific marketplace.
I understand that the selling partner is using the same account to operate in both US and CA marketplaces. If that's the case, they should log into Seller Central and review the notifications that are displayed also there, and remediate any issues.

Thank you,
Federico
Selling Partner Developer Services

**Comment by metaprice** [comment]
That's not really satisfying. Can you please add the marketplaceID? Then we can offer a usable feature to the customers.
