### ISSUE TITLE
[BUG] [SP-API] [Issue] CatalogItems#searchCatalogItems returns inconsistent data

### ISSUE THREAD

**Issue by minifreak** [amzn/selling-partner-api-docs#3237]
I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When calling SP-API CatalogItems#searchCatalogItems passing a list of SKUs and a marketplaceId, returns inconsistent data, depending on the marketplaceId being used.

## Expected Behavior
searchCatalogItems operation must return the same data for catalog items in the same way they are shown as bound with markeplaces in the Amazon Seller Central. Guess the same happens with Amazon Vendor Central, but I have no account to verify it.

## Current Behavior
Most of the products are listed in multiple marketplaces (as shown in ASC) but the API call returns most of them for a given marketplace (ie: Spain) but none or just a very few are returned for other marketplaces (ie: France, Germany, Italy, etc.)

Besides, as a suggestion for optimization, the operation only allows a single marketplaceId to be passed. It would be great to allow a list of marketplaces to be passed, as other API operations do. Unless, of course, that have been designed that way for reasons above my understanding.

## Context/Screenshots
This is a big blocking issue for us, since we can't map accordingly our products to the right marketplaces where they are being sold. That makes a lot of automation processes (in regard feeds and notifications mostly) to not deliver the expected results or not even be able to be triggered. However, if there are other means to obtain accurate mappings between catalog_items <-> marketplaces, I am all ears (couldn't find anything else so far).

## Your Environment
Not relevant

**Comment by rodrifed** [comment]
Hi @minifreak,

Thank you for reporting this issue.

Do I understand it correctly that you are querying the API with a number of SKUs that exist in a specific marketplace (e.g. France), but the response omits some of them?
If that's the case, I would kindly ask you to contact [Developer Support](https://developer.amazonservices.com/support) and provide request id, timestamp, input and output payload, and evidence of the SKUs existing in Seller Central (e.g. a screenshot). Our support team will be happy to assist you on this.

Thank you,
Federico
Selling Partner Developer Services

**Comment by minifreak** [comment]
Hi Federico,

I had a bug in my code so I confirm there was no issue with the call response. 

Apologies for the false reporting.
