### ISSUE TITLE
[Question] [SP-API] [How to differentiate between Seller flex (Seller fulfilled prime) vs FBA ]

### ISSUE THREAD

**Issue by mogupta** [amzn/selling-partner-api-docs#3242]
## How to differentiate between Seller flex (Seller fulfilled prime) vs FBA 

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
The getOrders API doesn't provide any data point to differentiate between Seller flex (Seller fulfilled prime) vs FBA.  How can I get the warehouse code from where the order was fullfilled.

**Comment by rodrifed** [comment]
Hi @mogupta,

Thank you for your message.

The [Order object](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#order) includes the following attributes to identify AFN/FBA and MFN orders, and the supply source/warehouse ID:
* **FulfillmentChannel:** Indicates whether the order was fulfilled by Amazon (AFN) or by the seller (MFN).
* **IsPrime:** When true, the order is a seller-fulfilled Amazon Prime order.
* **FulfillmentInstruction > FulfillmentSupplySourceId:** Denotes the recommended sourceId where the order should be fulfilled from.

Thank you,
Federico
Selling Partner Developer Services
