### ISSUE TITLE
[BUG] [SP-API] Vendor Central India URL is not working for OAuth 

### ISSUE THREAD

**Issue by naveenpatnana** [amzn/selling-partner-api-docs#3247]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

We are trying to get our app authenticated by our Amazon vendor central customers in India. However, the vendor central URL mentioned for India in the API document is showing a blank page restricting our customers to authenticate our app. 

https://developer-docs.amazon.com/sp-api/docs/vendor-central-urls

## Expected Behavior

The URL should redirect the user to the vendor central login page and once the user logs in with their Amazon vendor central credentials, it should redirect them to consent page just like it is happening for other regions.

## Current Behavior
There is blank page that is being shown when the user clicks on the below link (note that below link is for authenticating our application). But in general, the vendorcentral.amazon.in does not seem responsive.

https://vendorcentral.amazon.in/apps/authorize/consent?application_id=amzn1.sp.solution.3927bf0c-e182-4153-a8a0-56161a184df8&version=beta

## Context/Screenshots

We are a data analytics & reporting platform where our users get centralized, automated reporting across all platform at one place. Amazon vendor central is one of the crucial sources without which the reporting is incomplete. 

**Blank issue:**
<img width="1434" alt="Screenshot 2023-07-13 at 6 20 45 PM" src="https://github.com/amzn/selling-partner-api-docs/assets/90193804/7f443bf7-eaa8-4d6b-a889-cde727f5d388">

**Comment by rodrifed** [comment]
Hi @naveenpatnana,

The correct url is https://www.vendorcentral.in/.
We will update the documentation accordingly.

Thank you,
Federico
Selling Partner Developer Services
