### ISSUE TITLE
GetCatalogItem doesn't report root Sales Rank / Category

### ISSUE THREAD

**Issue by txphi592** [amzn/selling-partner-api-docs#3258]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/3257

<div type='discussions-op-text'>

<sup>Originally posted by **txphi592** July 19, 2023</sup>
I'm seeing this issue a lot and it's causing problems for our users (we are an SP-API Seller Partner with thousands of users). 

Issue- GetCatalogItem API is not reporting the root level Sales Rank/Category for certain ASINs vs the Amazon product page which IS reporting correctly. Why is the API reporting this differently than what Amazon is showing on the website? We need the root level category + sales rank for product analysis when analyzing how well a product is selling. In the ASIN example below, by not reporting Category "Toys & Games" & corresponding 40,883 Sales Rank in the API, this ASIN looks like it doesn't sell. The reality is that it DOES sell but the API is inexplicably omitting the most important Category / Sales Rank. **Why?**

I have made Support cases for this but Amazon SPAPI support has not been helpful (Case ID 11811268941).

Below is one example but there are many-

Here is GetCatalogItem response for ASIN B00005K424
![image](https://github.com/amzn/selling-partner-api-docs/assets/87911402/bf642629-3af8-4b7b-94ea-1862c44357af)

Here what Amazon shows for same ASIN on its product page [https://www.amazon.com/dp/B00005K424](url)
![image](https://github.com/amzn/selling-partner-api-docs/assets/87911402/fba44104-179d-46a2-a724-d78bc008cee9)

Any help would be greatly appreciated @sungolivia @rugved1991 @chapmanjw 
</div>

**Comment by jamesp26** [comment]
Raised this a while ago and gave up. Instead we use the rank in the ItemOffers API. The problem with that one is that is gives you browsenodeid instead of name but if retrieve the browse node report you can work out the descriptions.

**Comment by dkt2000** [comment]
@jamesp26 We checked ItemOffers API, but its not return browsernodeid. Its return Ranks

![image](https://github.com/amzn/selling-partner-api-docs/assets/60137669/00a81b88-3fc9-4b19-9d06-91fab7c57899)

We using ItemOfferAPI  - /products/pricing/v0/items/B00005K424/offers
