### ISSUE TITLE
[BUG] Documentation - Orders API - getOrders method

### ISSUE THREAD

**Issue by cohlar** [amzn/selling-partner-api-docs#326]
When calling the method `getOrders` from the `Orders` API with a `LastUpdatedBefore` that is under 2 minutes ago, I get the following error:
```
    {
      code: 'InvalidInput',
      message: 'The input you have submitted is not valid. Please check your input and try again.',
      details: ''
    }
```

The API works fine with older dates. I remember something about those 2 minutes from the MWS documentation, but I couldn't find this documented anywhere in the Selling Partner API for Orders doc.

**Comment by optikalefx** [comment]
This "undocumented" bug cost me 14 hours of research.

**Comment by jlevers** [comment]
FWIW, I'm still having this problem now. I just spent multiple hours trying to find the issue with my input, which turned out to just be that `CreatedBefore` had to be at least 2 minutes ago, as @cohlar said. This really should get fixed, or at the very least the error message should be clearer.

**Comment by Rajesh-ExertisGO** [comment]
wasted a day trying to figure out what is this bug.

**Comment by maxim-skuvault** [comment]
Still an issue. Wasted probably 2 dev days on this non-obvious behavior. Removing the `*before` filters ([this suggestion](https://github.com/amzn/selling-partner-api-docs/issues/326#issuecomment-950384733)) is not ideal in a lot of use-cases, like our. The Orders API is [still on version 0](https://developer-docs.amazon.com/sp-api/page/versions) while others have had multiple updates. Please fix this

**Comment by runesig** [comment]
We are also having issue with this. Please fix

**Comment by luonghoangcommonservices** [comment]
I'm also having this problem on the client's server.
`$created_before = gmdate($dateFormat, strtotime('now - 5 min'));`
`Array
(
    [marketplace_ids] => Array
        (
            [1] => APJ6JRA9NG5V4
        )

    [created_after] => 2022-07-31T22:00:00Z
    [created_before] => 2022-08-22T07:41:30Z
    [last_updated_after] => 
    [last_updated_before] => 
    [order_statuses] => Shipped
    [fulfillment_channels] => Array
        (
            [0] => AFN
            [1] => MFN
        )

    [amazon_order_ids] => 
    [max_results_per_page] => 100
)`
The reason is like @jlevers said above: created_before had to be at least 2 minutes ago. Even though i used gmdate and subtracted 5 minutes it seems the client's server has time zone difference.
Simple way i subtract 15 minutes, and error solved :)
`$created_before = gmdate($dateFormat, strtotime('now - 15 min'));`

**Comment by ShaneOH** [comment]
Just chiming in that this is still an issue 2 years later, and this should be fixed or at least documented

**Comment by NoxArt** [comment]
Yes, still an issue ... anyone?

**Comment by chrismcgahan** [comment]
Still an issue, but this bug report saved me. Thank you @cohlar!
