### ISSUE TITLE
[BUG] [SP-API] [Issue] GetCatalogItem no longer returns the 'generic_keyword' elements in Attributes

### ISSUE THREAD

**Issue by jamesp26** [amzn/selling-partner-api-docs#3263]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
For as long as we have been using the Catalog API, the attributes have included a 'generic_keyword' element. This was a very useful data point that could help determine if product listings were setup correctly for our clients. 

## Current Behavior
The Catalog API no longer returns the 'generic_keyword' elements in Attributes. The only way now it to manually go through each ASIN in either Seller or Vendor Central.

I am presuming this is a bug / oversight, as one of the usecases of the Catalog API is to be able to amend information and push back into Amazon. With the generic keyword missing, we would not be able to push information back in correctly.

**Comment by GJ-JG** [comment]
Hi @jamesp26 ,

Thanks for reaching out.
"generic_keyword" attribute will no longer be returned by the Catalog Items API.
Instead, you can use Listings Items API to view submitted values.
Reference: https://developer-docs.amazon.com/sp-api/docs/sp-api-release-notes#catalog-items-api-v2022-04-01

Best,
Jiang
