### ISSUE TITLE
[BUG] [SP-API] [Issue] Endpoints and authorization issue, as long as untrue data

### ISSUE THREAD

**Issue by ViniTamanhao** [amzn/selling-partner-api-docs#3264]
## Problem when calling the SP API being an Amazon Vendor

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Bug Description
I am trying to call the Vendor API to get my order reports from the API instead of having to log in the vendor center to check all the data. I just made all the authentication steps, from creating all the IAM requirements to generating the STS and LWA tokens, but I'm still facing an issue. After generating all the tokens, from some reason the only endpoint that doesnt return "Forbidden 403" is /vendor/orders/v1/purchaseOrders, and even tho it doesn't return a 403, it returns empty data, and by loggin in the Vendor center i can see there actually are purchaseOrders. Could anyone help me on why i seem to not have access to the other endpoints and why this one endpoint that is working seems not to be working correctly?

**Comment by ViniTamanhao** [comment]
I already called the authorization routes and they worked correctly:
Firstly: {{stsHost}}?Version=2011-06-15&Action=AssumeRole&RoleSessionName=Test&RoleArn={{IAM_ROLE_ARN}}&DurationSeconds=3600
and then: https://api.amazon.com/auth/o2/token

**Comment by ViniTamanhao** [comment]
for context, the one endpoint I'd really like to use is "/vendor/directFulfillment/orders/v1/purchaseOrders", but it returns unauthorized even tho I already gave all the necessary permissions on the vender center

**Comment by pkrawetkowski** [comment]
Direct Fulfillment and Retail are two different options
