### ISSUE TITLE
How self-authorize my application in only one customer

### ISSUE THREAD

**Issue by jjmg1945** [amzn/selling-partner-api-docs#3272]
Hello,

I have developed an application, with many scripts to connect throught SP-API and get and update information information of the orders. This application is for only one customer and I want not to publish this application. But I don't know how self-authorize this application in the client Seller Central.
I could do that with MWS API but not with SP-API.

Thanks in advance.

**Comment by leonardonakagawa** [comment]
Hello @{developer(s)},

Thank you for reaching out regarding Self Authorization with SP-API.

You can find details regarding this in our Self Authorization workflow [Self authorization](https://developer-docs.amazon.com/sp-api/docs/self-authorization).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Selling Partner API Developer Support
