### ISSUE TITLE
[HELP] Retriving all my merchant shipping groups from API.

### ISSUE THREAD

**Issue by silasfrigo** [amzn/selling-partner-api-docs#3276]
Hello. Is there a way for me to retrieve all my merchang_shippign_groups from the SP API? 
I tried passing seller_id in the product definitions API as the docs said, but it was not successfull. 
```
By providing the sellerId parameter with the Product Type Definitions API, you can retrieve the available shipping templates configured by the seller as an enumeration on the merchant_shipping_group attribute value.
```  https://developer-docs.amazon.com/sp-api/docs/migrating-listings-management-workflows#migrating-shipping-override-feeds-workflows

Thanks!

**Comment by leonardonakagawa** [comment]
Hello @silasfrigo,

Thank you for reaching out regarding `merchant_shipping_group`.

To find this information, you need to retrieve the `schema` from getDefinitionsProductType API into Product Type Definitions API. You can find details regarding this in our documentation [Product Type Definitions API v2020-09-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide).

After calling the `getDefinitionsProductType`, the `schema` attribute will be in the response payload, and you will be able to retrieve the schema link for it. After accessing it, you can search for the merchant_shipping_group attribute, which includes the keys (`enum`) and values (`enumNames`) for the merchant template.

Obs: 

1) Guarantee that you are passing the value LISTING into the `requirements` parameter of `getDefinitionsProductType`, so the `merchant_shipping_group` attribute will return into the payload of the `schema`

2) Certify that when listing a product or an offer through listing API's you are using the keys (`enum`) and not the values (`enumNames`)

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Selling Partner API Developer Support
