### ISSUE TITLE
[BUG] [SP-API] [Listings Items] There is no procurement in the response

### ISSUE THREAD

**Issue by Zhuqi95** [amzn/selling-partner-api-docs#3279]
## There is no procurement in the response

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Listings Items API v2021-08-01 reference
doc URL ：https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference

## Expected Behavior
Obtain the procurementin the response, Because I need costPrice 
![image](https://github.com/amzn/selling-partner-api-docs/assets/33742566/78ab4eb1-7b35-49e0-8cf1-93d079ed9eec)

## Current Behavior
procurement always is an empty array, Switching multiple groups of products remains the same

## Context/Screenshots
![image](https://github.com/amzn/selling-partner-api-docs/assets/33742566/bc0ec676-5568-4bec-a5cc-325e41b8e287)

## Your Environment
Interface for generating environment

**Comment by ritikacd** [comment]
Hi @Zhuqi95 

Thanks for reaching out. [Procurement details](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#itemprocurement) are only returned for vendor listings. Are you calling get listings API endpoint for a vendor's listing item? 

Thanks,
Ritika Chaudhary
Selling Partner API Team
