### ISSUE TITLE
[BUG] Documentation - Create a feed document - InvalidInput

### ISSUE THREAD

**Issue by tokicnikolaus** [amzn/selling-partner-api-docs#328]
Trying to create feed document (showed [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md#step-1-create-a-feed-document) ) and I'm getting `InvalidInput` error code.
Authentication works well (I tried other endpoints and it works) so I think headers are not the issue. 
Here is my sample code:

```
endpoint = 'https://sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/documents'
body = {
    "contentType": "text/tab-separated-values; charset=UTF-8"
}
resp = requests.post(
    endpoint,
    auth=self.amazon_auth.auth, 
    headers=self.amazon_auth.headers,
    json=body
)
return resp
```

Response code:
```
{'errors': [{'code': 'InvalidInput',
   'message': 'Invalid Input',
   'details': ''}]}

```

I was also trying to use different contentType and charset (like `text/plain`) but I receive same error code!

This is first step of [Submit feed tutorial](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md#tutorial-submit-a-feed).

**Comment by cdragon1116** [comment]
@tokicnikolaus 

Try to sign this additional header

```
{.  'Accept' => '*/*' }
```

**Comment by ritik-novostack** [comment]
@tokicnikolaus bro can u please put an example upload  values in  "text/tab-separated-values"  because i am really confused how to make feed data?

**Comment by tokicnikolaus** [comment]
@ritik-novostack we postponed usage of sp-api (didn't try feed api)  for some period of time, when I'll be back on this topic will write here how it is handled.
