### ISSUE TITLE
FinanceApi BUG : listFinancialEvents : InvalidInput

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-docs#3285]
The same error is returned on calling "listFinancialEvents" with [nextToken] parameter.
It seems that the error is caused since yesterday and happen irregularly. Sometimes the error is returned on the first [nextToken] , sometimes the error is returned on the 2nd/3rd/4th... [nextToken], and sometimes all the [nextToken] are requested successfully.

I change [MaxResultsPerPage] to "10" and try again, but the error is still caused. Is it a bug of selling-partner-api？

"errors": [
{
"code": "InvalidInput",
"message": "$errorResponse.Message",
"details": ""
}
]
}

**Comment by emildoa** [comment]
Just commenting that I'm having exactly the same issue.

**Comment by jimmy-ross-xapix** [comment]
we are having the same issue still

**Comment by JohnMirro** [comment]
We are too

**Comment by jimmy-ross-xapix** [comment]
also created this one earlier: https://github.com/amzn/selling-partner-api-docs/issues/3283

**Comment by naveenpatnana** [comment]
Even we are facing the same issue.

**Comment by titansoftime** [comment]
Same.

**Comment by cyrieu** [comment]
same issue

**Comment by bchecketts** [comment]
Same issue. retrying multiple times eventually gets it to work

**Comment by lizdeika** [comment]
same issue, even tried posted before/after 15minutes and MaxResults 1, nothing helps

**Comment by mid** [comment]
Same issue.

**Comment by rt3722** [comment]
Facing exact same issue.

**Comment by omrishaked** [comment]
This is a duplicate of https://github.com/amzn/selling-partner-api-docs/issues/3283

**Comment by titansoftime** [comment]
> This is a duplicate of #3283

The slight difference is that this ticket is for listFinancialEvents and #3283 is for listFinancialEventsByGroupId.

**Comment by lizdeika** [comment]
duplicate or not, it's 5 days already and it's still down

**Comment by emildoa** [comment]
@chrisskhoury Thanks for letting us know.

By the way, I went to the URL you shared and it seems like you're only flagging the ListFinancialEventsByGroupId endpoint as yellow, but the ListFinancialEvents is also behaving the same.

**Comment by chrisskhoury** [comment]
resolving as issue seems to be resolved, feel free to reopen if issue persists
