### ISSUE TITLE
GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE gets cancelled everytime 

### ISSUE THREAD

**Issue by fermions75** [amzn/selling-partner-api-docs#3287]
I am requesting GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE report and it gets cancelled everytime. I have tried it with many `dataStartTime` and `dataEndTime`, but no result. 

here is my request format - 
`{
    "reportType": "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
    "dataStartTime": "2023-03-01",
    "dataEndTime" : "2023-03-30",
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ]
}`

The response is - 
`{
    "reportType": "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
    "processingEndTime": "2023-07-30T18:25:38+00:00",
    "processingStatus": "CANCELLED",
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ],
    "reportId": "189396019568",
    "dataEndTime": "2023-03-30T00:00:00+00:00",
    "createdTime": "2023-07-30T18:25:24+00:00",
    "processingStartTime": "2023-07-30T18:25:31+00:00",
    "dataStartTime": "2023-03-01T00:00:00+00:00"
}`

**Comment by rugved1991** [comment]
Hi @fermions75,

Please open a developer support case to investigate this issue further. We would need additional details to troubleshoot the issue. Make sure you provide the Report ID, merchant ID for whom you are requesting this report and the region where the seller is located while opening developer support case. Please use the link below to open a case:
https://developer.amazonservices.com/support

Best,
Rugved
Solutions Architect, SP API
