### ISSUE TITLE
[BUG] [SP-API] Error converting value "Amazon Commercial Services Pty Ltd" to type 'System.Nullable`1[FikaAmazonAPI.AmazonSpApiSDK.Models.Orders.TaxCollection+ResponsiblePartyEnum]'. Path 'payload.OrderItems[0].TaxCollection.ResponsibleParty', line 1, position 123.

### ISSUE THREAD

**Issue by nickgoodmanuk** [amzn/selling-partner-api-docs#3288]
Getting this on some Amazon AU orders.

Error converting value "Amazon Commercial Services Pty Ltd" to type 'System.Nullable`1[FikaAmazonAPI.AmazonSpApiSDK.Models.Orders.TaxCollection+ResponsiblePartyEnum]'. Path 'payload.OrderItems[0].TaxCollection.ResponsibleParty', line 1, position 123.

## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by tank104** [comment]
It looks like Amazon has introduced a new enum for Australia but has not updated the API documentation:

https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#responsibleparty

It should list "Amazon Commercial Services Pty Ltd" but it doesn't.

**Comment by sagslow** [comment]
Hey, also having the same issue.  Any fixes? walk around?

**Comment by tank104** [comment]
Updated to the latest package as I have applied a fix to that overnight.
