### ISSUE TITLE
[BUG] [SP-API] [Issue] Generating GST_MTR_B2B,  GST_MTR_B2C amazon report 

### ISSUE THREAD

**Issue by anurag-osfin** [amzn/selling-partner-api-docs#3293]
PLEASE HELP US PROCESS GITHUB ISSUES FASTER BY PROVIDING THE FOLLOWING INFORMATION.
ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION.

## I'm submitting a...Bug regarding generating GST_MTR_B2B,  GST_MTR_B2C amazon report. 

I am getting response {
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to the resource is forbidden",
            "details": ""
        }
    ]
}

GST_MTR_B2B,  GST_MTR_B2C are not present in restricted token api.  Still I am not able to fetch report. Can someone guide me through this issue ?

## SP-API Name and Version or Report/Feed Type
I am sharing with you SP-API - sellingpartnerapi-eu.amazon.com
[API](url) Version: 2021-06-30

**Comment by ritikacd** [comment]
Hello @anurag-osfin 

Refer to the troubleshooting tips for [Access to requested source is denied](https://developer-docs.amazon.com/sp-api-blog/docs/troubleshooting-selling-partner-api-authorization-errors#access-to-requested-resource-is-denied) error for your API request. 

To access Tax reports GST_MTR_B2B & GST_MTR_B2C, your application needs access to the "[Tax Remittance (Restricted) role](https://developer-docs.amazon.com/sp-api/docs/tax-remittance-restricted-role#feeds-reports-and-notifications)" role, please verify and ensure this role is selected on your application configuration page. 


Thanks,
Ritika Chaudhary
Selling Partner API Team
