### ISSUE TITLE
offer incomplete status  when creating it using putListingsItem

### ISSUE THREAD

**Issue by ahmetsabri** [amzn/selling-partner-api-docs#3294]
i create offer using putListingsItem  **PUT /listings/2021-08-01/items/{sellerId}/{sku}** using these attributes :

 `{"externally_assigned_product_identifier":[{"type":"ASIN","value":"B000ILZAXI"}],"merchant_suggested_asin":[{"value":"B000ILZAXI"}],"skip_offer":[{"value":false}],"merchant_shipping_group":[{"value":"66f55f25-e36e-464f-9bb6-8db13f1dd364"}],"fulfillment_availability":[{"fulfillment_channel_code":"DEFAULT","quantity":100,"lead_time_to_ship_max_days":2}],"purchasable_offer":[{"price":{"currencyCode":{"value":"USD"},"amount":{"value":37.99}},"currency":"USD","our_price":[{"schedule":[{"value_with_tax":37.99}]}]}],"condition_type":[{"value":"new_new"}],"batteries_required":[{"value":false}],"supplier_declared_dg_hz_regulation":[{"value":"not_applicable"}]}`

`requirements:LISTING_OFFER_ONLY`
`product_type:PRODUCT`
I received `ACCEPTED`  in the response but it looks `incomplete` in my Amazon panel 
<img width="1416" alt="Screenshot 2023-08-04 at 00 41 38" src="https://github.com/amzn/selling-partner-api-models/assets/39857006/2156ecab-b037-4d9e-ba9d-cbde84849450">

**Comment by leonardonakagawa** [comment]
Hello @ahmetsabri 

Thank you for reaching out regarding creating an offer.

The `ACCEPTED` value means, the initial validations (synchronous) have passed, and the data has been submitted for further processing with the Amazon catalog.

To check if the offer has been processed correctly and created into Amazon catalog, you need to check the asynchronous data processing. It could be done with [LISTINGS_ITEM_STATUS_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#listings_item_status_change) or [LISTINGS_ITEM_ISSUES_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#listings_item_issues_change) notifications. They are sent once the new item has been created or processing issues have occurred. You can also, call the [getListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#get-listings2021-08-01itemsselleridsku) operation to inspect the listings item issues, if applicable. The item will be buyable when the SKU `status` be `BUYABLE` into `getListingsItem` operation or `LISTINGS_ITEM_STATUS_CHANGE` notification.

You can find details regarding this in our [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide) step 7 and 8.
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Selling Partner API Developer Support
