### ISSUE TITLE
[BUG] [SP-API] [Issue] /reports/2021-06-30/reports returning "One or more required parameters missing - reportTypes" even though documentation says OPTIONAL

### ISSUE THREAD

**Issue by MetaMan2023** [amzn/selling-partner-api-docs#3296]
Documentation for /report/2021-06-30/reports says "reportTypes" are OPTIONAL but API is returning error that reportTypes are not passed

https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreports

*** ERRORS ***

GET https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports

$VAR1 = [
  {
    'details' => 'reportTypes;',
    'message' => 'One or more required parameters missing',
    'code' => 'InvalidInput'
  }
];

## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by littleylv** [comment]
> **Either reportTypes or nextToken is required.**

**Comment by puppsupr** [comment]
Hi MetaMan2023,
Either reportTypes or nextToken is required field. Please refer to https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference.

Here is the video to run the Reports API : https://www.youtube.com/watch?v=QGnJr3VkwpA

Reports API use-case guide : https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-use-case-guide

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
