### ISSUE TITLE
[BUG] [SP-API] [Some values not getting  returned in the response]

### ISSUE THREAD

**Issue by raghavkunkee** [amzn/selling-partner-api-docs#3303]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP-API Catalog Items API v2022-04-01   

## Expected Behavior

The attribute values product_description , bullet_list should be presemt in the response of the search.

## Current Behavior

The attribute values product_description , bullet_list are missing in many ISBN's when searching. 
However the same is available on the site.
e.g : ISBN : 0007112491 

## Your Environment

Ubuntu

**Comment by rugved1991** [comment]
Hi @raghavkunkee,

Thanks for reaching out. Can you please confirm if you are using the "attributes" in the "includedData" parameter? The bullet_point will only be visible if you request for attributes. I am able to view the bullet points with the following request:
https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?identifiers=0007112491&identifiersType=ISBN&marketplaceIds=ATVPDKIKX0DER&includedData=relationships,attributes,dimensions,identifiers,images,productTypes,salesRanks,summaries

Best,
Rugved
Solutions Architect, SP-API

**Comment by raghavkunkee** [comment]
Hi Rugved,
Thanks for responding. This is not true, i am invoking the services exactly the way you are invoking but i dont get product_description (and bullet_list) always,  the rate is of return is very low, 1 on 20~30 records.
The difference with below is that i invoke service with india marketplace and appropriate url (eu region site)
Couple of samples (ISBN) you may wish to try  * 0000000620* 0000000108
If need to for full urls, or additional ISBNs i can provide 
note, most of items we search for we can see product description on the amazon.in portal. In case there is need to such ISBNs also let me know

Thanks

Sent from Yahoo Mail


On Saturday, August 19, 2023, 8:54 AM, Rugved Dighe ***@***.***> wrote:




Hi @raghavkunkee,

Thanks for reaching out. Can you please confirm if you are using the "attributes" in the "includedData" parameter? The bullet_point will only be visible if you request for attributes. I am able to view the bullet points with the following request:
https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?identifiers=0007112491&identifiersType=ISBN&marketplaceIds=ATVPDKIKX0DER&includedData=relationships,attributes,dimensions,identifiers,images,productTypes,salesRanks,summaries

Best,
Rugved
Solutions Architect, SP-API
