### ISSUE TITLE
Oauth redirect url

### ISSUE THREAD

**Issue by donhmorris** [amzn/selling-partner-api-docs#331]
Trying to test my developer authorization code using a local server running at localhost:4200 but the developer console in seller central does not allow the use of localhost.

Is this something that can be changed? Is there another route that I can take to develop my auth feature for using the api?

**Comment by nodisk8800** [comment]
I think you can use https://mytestdomain.com
and set mytestdomain.com point to 127.0.0.1 in windows host file.

**Comment by donhmorris** [comment]
I don't really know what that is about. i took a look at it. I don't want to get involved with it.

I think what needs to happen is to allow the use of localhost as a redirect just as LWA allows.

**Comment by xbaha** [comment]
> I don't really know what that is about. i took a look at it. I don't want to get involved with it.
> 
> I think what needs to happen is to allow the use of localhost as a redirect just as LWA allows.

have you found a way to add localhost?
