### ISSUE TITLE
[BUG] [SP-API] [Issue]Some values not getting returned in the response] 

### ISSUE THREAD

**Issue by raghavkunkee** [amzn/selling-partner-api-docs#3319]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP-API Catalog Items API v2022-04-01

## Expected Behavior

The attribute values product_description , bullet_list should be present in the response of the search.

## Current Behavior

The attribute values product_description , bullet_list are missing in many ISBN's when searching.
However the same is available on the site.
e.g : ISBN : 0007112491
I am invoking the services exactly the way you are invoking but i dont get product_description (and bullet_list) always,  the rate is of return is very low, 1 on 20~30 records.
The difference with below is that i invoke service with india marketplace and appropriate url (eu region site)
Couple of samples (ISBN) you may wish to try  * 0000000620* 0000000108
If need to for full urls, or additional ISBNs i can provide 
note, most of items we search for we can see product description on the amazon.in portal. In case there is need to such ISBNs also let me know

## Your Environment

Ubuntu

**Comment by IsaacSee** [comment]
Hi, any update on this issue? 
We seem to have the same issue.
