### ISSUE TITLE
[BUG] [SP-API] Encountering 500 Internal Error for Amazon SP API Order Endpoint

### ISSUE THREAD

**Issue by pratikshap31** [amzn/selling-partner-api-docs#3321]
**Issue Summary:**
I'm encountering a 500 Internal Server Error when using the Amazon Selling Partner API in relation to retrieving order data. This error occurred for the first time and is preventing me from retrieving order information.

**Error Details:**

**Endpoint:** GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders

**Error Messages:**
1. Request to GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders resulted in a 500 Internal Server Error response:
```
{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again."
    }
  ]
}
```

2. Request to GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders/113-6916467-1968214/orderItems resulted in a 500 Internal Server Error response:
```
{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again."
    }
  ]
}
```

**Steps to Reproduce:**
1. Make a GET request to the specified endpoint with the provided parameters.
2. Observe the received 500 Internal Server Error response along with the mentioned error messages.

**Expected Behavior:**
The API request to retrieve order information should return a valid response without any internal server errors.

**Additional Information:**
This is the first time I've encountered this error while using the Amazon Selling Partner API.
The error occurs when attempting to retrieve order details using the specified endpoint.
Assistance or guidance on resolving this issue would be greatly appreciated.

**Comment by rodrifed** [comment]
Hi @pratikshap31,

Thank you for contacting us.

Your issue requires debugging and troubleshooting from Amazon Developer Support team.
I kindly ask you to open a support case using our [Contact Form](https://developer.amazonservices.com/support).

Thank you,
Federico
Selling Partner Developer Services
