### ISSUE TITLE
[BUG] [SP-API] [Issue] Cannot access Vendor Purchase Orders

### ISSUE THREAD

**Issue by jashparekh** [amzn/selling-partner-api-docs#3323]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I am trying to access Vendor Purchase Orders using SP API but receiving 403 error. I have also created a case through Vendor Central and the Case ID is `13623786151`

## SP-API Name and Version or Report/Feed Type

SP API: `https://sellingpartnerapi-na.amazon.com/vendor/orders/v1/purchaseOrders/<purchase_order_id>`

I also tried accessing Catalog API but received the same error.

## Expected Behavior
Get order id

## Current Behavior
I am able to generate Access token using Refresh Token but cannot pull Purchase Orders

## Your Environment
Prod

**Comment by rodrifed** [comment]
Hi @jashparekh,

Thank you for contacting us.

Your issue requires debugging and troubleshooting from Amazon Developer Support team.
I kindly ask you to open a support case using our [Contact Form](https://developer.amazonservices.com/support).

Thank you,
Federico
Selling Partner Developer Services
