### ISSUE TITLE
[BUG] [SP-API] Invalid Date-Time field(s) error if lastUpdatedAfter in getOrders is in iso8601 format (Japan time)

### ISSUE THREAD

**Issue by asagawa0519** [amzn/selling-partner-api-docs#3324]
https://sellingpartnerapi-fe.amazon.com/orders/v0/orders?LastUpdatedAfter=2023-08-18T00:00:00+09:00&OrderStatuses=Unshipped,PartiallyShipped&MarketplaceIds=1VC38T7YXB528&FulfillmentChannels=MFNwould result in the following error.

> JSON.parse(response.body)
=> errors"=>[{"code"=>"InvalidInput", "message"=>"This is invalid input", "details"=>"Invalid date/time field [lastUpdatedAfter]"}]}]
+09:00 is removed and the response is returned normally. Why is this?

If it succeeds

https://sellingpartnerapi-fe.amazon.com/orders/v0/orders?LastUpdatedAfter=2023-08-18T00:00:00&OrderStatuses=Unshipped,. PartiallyShipped&MarketplaceIds=A1VC38T7YXB528&FulfillmentChannels=MFN

**Comment by asagawa0519** [comment]
It appears that LastUpdatedAfter must be UTC time.
Therefore, the JTC notation seems to have resulted in an error.
I would like the documentation to clearly state that the time is in UTC.

**Comment by cguweb-com** [comment]
I'm not sure about this issue, but I noticed another related

getOrders date params are out of order, meaning amazon expects lastupdate values before created. 

and I'm also getting error from amazon if I try null for all four, saying lastupdate values are required
