### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by MaksymV1999** [amzn/selling-partner-api-docs#3327]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Reports API and report Type is :GET_FLAT_FILE_OPEN_LISTINGS_DATA

There is a problem with reports we've discovered, previously for report type GET_FLAT_FILE_OPEN_LISTINGS_DATA there was an this set of columns included into the report 
`
sku	asin	price	quantity	Business Price	Quantity Price Type	Quantity Lower Bound 1	Quantity Price 1	Quantity Lower Bound 2	Quantity Price 2	Quantity Lower Bound 3	Quantity Price 3	Quantity Lower Bound 4	Quantity Price 4	Quantity Lower Bound 5	Quantity Price 5	Progressive Price Type	Progressive Lower Bound 1	Progressive Price 1	Progressive Lower Bound 2	Progressive Price 2	Progressive Lower Bound 3	Progressive Price 3
`

But now there is only this columns 
`
sku	asin	price	quantity
`

Could you kindly elaborate more on that behavior, where should I take the additional values now like Business price?

**Comment by rugved1991** [comment]
Hi @MaksymV1999,

We are still seeing the [documented](https://developer-docs.amazon.com/sp-api/docs/inventory-reports-attributes#get_flat_file_open_listings_data) report attributes being vended in the "GET_FLAT_FILE_OPEN_LISTINGS_DATA" report.  
Please open a developer support ticket using one of the below links to investigate this issue. Also do mention if you are seeing this across multiple sellers or specific sellers. You would also need to add report ID and seller ID to the ticket for whom you are requesting this report.
Developer Support EU: https://developer.amazonservices.co.uk/support
Developer Support NA: https://developer.amazonservices.com/support
Developer Support APAC: https://developer.amazonservices.com.au/support

Best,
Rugved
Solutions Architect, SP-API
