### ISSUE TITLE
[BUG] [SP-API] [Issue] Unable to get BuyerCustomizedInfo details

### ISSUE THREAD

**Issue by Chintan-Novus** [amzn/selling-partner-api-docs#3328]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
`/orders/v0/orders/:orderId/orderItems/buyerInfo`

## Expected Behavior
I should be able to retrieve the order item customization info

## Current Behavior
Not able to fetch the order item customization info from `/orders/v0/orders/:orderId/orderItems/buyerInfo`

## Context/Screenshots
![image](https://github.com/amzn/selling-partner-api-docs/assets/26324837/9f119235-2619-4eb7-bdd8-ce58f26181e7)

## Your Environment
Postman - `/orders/v0/orders/:orderId/orderItems/buyerInfo`

**Comment by Chintan-Novus** [comment]
+ @ShivikaK @leonardonakagawa @rugved1991 @LindaNC @Adrian-T-AMZN @parvathm @chrisskhoury @hyandell

Why am I able to see the customization information on the seller central dashboard, but is not available on the API?

**Comment by Chintan-Novus** [comment]
Related issues where I found no information
- https://github.com/amzn/selling-partner-api-docs/issues/1682
- https://github.com/amzn/selling-partner-api-docs/issues/674
- https://github.com/amzn/selling-partner-api-docs/issues/230
- https://github.com/amzn/selling-partner-api-docs/issues/221

**Comment by rugved1991** [comment]
Hi @Chintan-Novus,

Thanks for reaching out. Please open a developer support case using one of the below links to investigate this issue further.
Developer Support EU: https://developer.amazonservices.co.uk/support
Developer Support NA: https://developer.amazonservices.com/support
Developer Support APAC: https://developer.amazonservices.com.au/support

Feel free to update this issue with the findings from the support ticket for the developer community. Or add the case ID to this issue to track progress.

Best,
Rugved
Solutions Architect, SP-API

**Comment by jjuelotc** [comment]
I am finding this issue still exists. The BuyerInfo object included in the /orders/v0/orders/{orderId}/orderItems response is always a bunch of nulls but the SP-API documentation indicates that this customized info would be returned.

`"BuyerInfo": {
	"BuyerCustomizedInfo": {
		"CustomizedURL": "https://zme-caps.amazon.com/t/bR6qHkzSOxuB/J8nbWhze0Bd3DkajkOdY-XQbWkFralegp2sr_QZiKEE/1"
	},
	"GiftMessageText": "For you!",
	"GiftWrapPrice": {
		"CurrencyCode": "JPY",
		"Amount": "1.99"
	},
	"GiftWrapLevel": "Classic"
}`

With no indication of if there is info in this field, the only choice is to call /orders/v0/orders/{orderId}/orderItems/buyerInfo for every order in addition to calling /orders/v0/orders/{orderId}/orderItems.

Is there any plan to fix this?

**Comment by klou28** [comment]
We called /orders/v0/orders/{orderId}/orderItems/buyerInfo for every order in addition to calling /orders/v0/orders/{orderId}/orderItems but there is still no CustomizedURL information. We are migrating from MWS, and the deadline to move to SP-API will be in a few days. This bug is a show stopper for us, as we will have to manually download the customization of each order.  When can we expect a fix for this?

**Comment by ritikacd** [comment]
Hi @Chintan-Novus, 

Thanks for reaching out. BuyerCustomizedInfo is PII data and will be filtered when the developer doesn't have the permission to access it. If you have access to restricted roles, you can call [getOrderItems](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#getorderitems) operation passing the[ RDT token](https://developer-docs.amazon.com/sp-api/docs/tokens-api-v2021-03-01-reference#createrestricteddatatoken) to get the BuyerCustomizedInfo. 

Please also note that currently, BuyerCustomizedInfo is not provided for FBA orders. 

Thanks,
Ritika
Solutions Architect, SP-API
