### ISSUE TITLE
Amazon新手求教

### ISSUE THREAD

**Issue by laoshihaowojiaozhang** [amzn/selling-partner-api-docs#3333]
看了感觉没太看懂这是干啥的🤦‍♂️

**Comment by rugved1991** [comment]
Hi @laoshihaowojiaozhang,

Thanks for being SP-API Developer. Please let us know if you have any specific questions or issues you are running into. You can also search GitHub discussions for help from SP-API Developer Community. 
For getting started with SP-API development, please refer to these resources:
https://developer-docs.amazon.com/sp-api-blog/docs
https://www.youtube.com/playlist?list=PLUFIeZA9F5PwhNB2j5Ki_EuND_uTQcEak
https://www.youtube.com/watch?v=9bA4jT8aA_s&list=PLyrrqKCT7jFKENJO9n_Y68-5o2GZLgLUU

Best,
Rugved
Solutions Architect, SP-API

**Comment by laoshihaowojiaozhang** [comment]
thanks,i will try to watch and study it hardly during my worktime;  i'm Chinese that not good in english&👶🏻👶🏻i'm an amazon newer，everything is .......a mess😫😫😫

**Comment by wszwc** [comment]
你好，我也是中国人，希望可以取得联系交流一下关于SP API的问题，请问你有在关注吗？

**Comment by wszwc** [comment]
Hello brother, I am also Chinese. I hope I can get in touch to discuss issues about SP API. Are you paying attention?
