### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by DanielPurty** [amzn/selling-partner-api-docs#3338]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I am calling a "/catalog/2022-04-01/items" endpoint to get the attributes listPrice the API is giving me the wrong listPrice,
 

## Current Behavior

API is giving the Price as 1070.0. 
but the actual price for the product is :1520
API response :
{
    "items": [
        {
            "asin": "B000AR7AKG",
            "attributes": {
                "listPrice": [
                    {
                        "valueWithTax": 1070.0,
                        "currency": "INR"
                    }
                ]
            },
            "dimensions": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "item": {
                        "height": {
                            "unit": "inches",
                            "value": 2
                        },
                        "length": {
                            "unit": "inches",
                            "value": 5
                        },
                        "weight": {
                            "unit": "pounds",
                            "value": 0.09
                        },
                        "width": {
                            "unit": "inches",
                            "value": 2
                        }
                    },
                    "package": {
                        "height": {
                            "unit": "inches",
                            "value": 0.549999999439
                        },
                        "length": {
                            "unit": "inches",
                            "value": 9.0199999907996
                        },
                        "weight": {
                            "unit": "pounds",
                            "value": 0.14991433816
                        },
                        "width": {
                            "unit": "inches",
                            "value": 2.949999996991
                        }
                    }
                }
            ],
            "identifiers": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "identifiers": [
                        {
                            "identifierType": "EAN",
                            "identifier": "0046928012978"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "0616716087022"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "7147905967663"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "7535001268393"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "7611160123633"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "7611160691163"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "7611160705129"
                        },
                        {
                            "identifierType": "EAN",
                            "identifier": "7612446705123"
                        },
                        {
                            "identifierType": "GTIN",
                            "identifier": "07611160705129"
                        },
                        {
                            "identifierType": "UPC",
                            "identifier": "046928012978"
                        },
                        {
                            "identifierType": "UPC",
                            "identifier": "616716087022"
                        }
                    ]
                }
            ],
            "images": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "images": [
                        {
                            "variant": "MAIN",
                            "link": "https://m.media-amazon.com/images/I/61EZVls8udL.jpg",
                            "height": 2000,
                            "width": 2000
                        },
                        {
                            "variant": "MAIN",
                            "link": "https://m.media-amazon.com/images/I/3142xL7ZctL.jpg",
                            "height": 500,
                            "width": 500
                        },
                        {
                            "variant": "MAIN",
                            "link": "https://m.media-amazon.com/images/I/3142xL7ZctL._SL75_.jpg",
                            "height": 75,
                            "width": 75
                        }
                    ]
                }
            ],
            "productTypes": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "productType": "KNIFE_SHARPENER"
                }
            ],
            "relationships": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "relationships": [
                        {
                            "childAsins": null,
                            "parentAsins": [
                                "B0B49YCB3C"
                            ],
                            "variationTheme": null,
                            "type": "VARIATION"
                        }
                    ]
                }
            ],
            "salesRanks": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "classificationRanks": [
                        {
                            "classificationId": "3404440031",
                            "title": "Camping & Hiking Knife Sharpeners",
                            "link": "https://www.amazon.in/gp/bestsellers/sports/3404440031",
                            "rank": 1
                        }
                    ],
                    "displayGroupRanks": [
                        {
                            "websiteDisplayGroup": "sports_display_on_website",
                            "title": "Sports, Fitness & Outdoors",
                            "link": "https://www.amazon.in/gp/bestsellers/sports",
                            "rank": 2340
                        }
                    ]
                }
            ],
            "summaries": [
                {
                    "marketplaceId": "A21TJRUUN4KGV",
                    "adultProduct": false,
                    "autographed": false,
                    "brand": "Victorinox",
                    "browseClassification": {
                        "displayName": "Buy more &save",
                        "classificationId": "77441322031"
                    },
                    "color": "Black",
                    "contributors": null,
                    "itemClassification": "BASE_PRODUCT",
                    "itemName": "Victorinox, Dual Function Portable Knife Sharpener for straight blades with honing stone and ceramic discs for Chefs and Home-cooks, Black, Swiss Made",
                    "manufacturer": "Victorinox",
                    "memorabilia": false,
                    "modelNumber": "4.3323",
                    "packageQuantity": 1,
                    "partNumber": "VIC-4.3323",
                    "releaseDate": null,
                    "size": "Standard",
                    "style": null,
                    "tradeInEligible": false,
                    "websiteDisplayGroup": "kitchen_display_on_website",
                    "websiteDisplayGroupName": "Kitchen"
                }
            ],
            "vendorDetails": null
        }
    ]
}

## Context/Screenshots
screenshot of the B000AR7AKG asin price. 
<img width="1162" alt="Screenshot 2023-09-05 at 3 17 26 PM" src="https://github.com/amzn/selling-partner-api-docs/assets/119052609/c7b1adff-8568-4a10-9ec1-387f6ba93b39">

**Comment by hellfire989** [comment]
BUMP! I'm using /catalog/v0/items and I'm getting the same kind of error.
