### ISSUE TITLE
DHL Label using SP API

### ISSUE THREAD

**Issue by oaguayo1** [amzn/selling-partner-api-docs#3341]
After getting eligible shipping services from Amazon, we attempt to create a label using one of those services (in this case DHLMX_PTP_PACKAGE_EXPRESS). The createShipment request to SP API, however, returns the following error:

```
HTTP Code: 400
InvalidInput
The purchase request parameters are invalid, please call with the correct parameters or make another call to check eligible options.
```

This is the request we are making (real sensitive data has been replaced for privacy):

```
{
  "ShipmentRequestDetails": {
    "AmazonOrderId": "XXX-XXXXXXX-XXXXXXX",
    "ItemList": [
      {
        "OrderItemId": "YYYYYYYYYYYYYY",
        "Quantity": 1
      }
    ],
    "ShipFromAddress": {
      "Name": "Valid Company Name",
      "AddressLine1": "1410 Real Address",
      "Email": "real@email.com",
      "City": "Realcity",
      "StateOrProvinceCode": "NY",
      "PostalCode": "10015",
      "CountryCode": "US",
      "Phone": "5555555555"
    },
    "PackageDimensions": {
      "Length": 9,
      "Width": 6,
      "Height": 2,
      "Unit": "inches"
    },
    "Weight": {
      "Value": 15.9,
      "Unit": "oz"
    },
    "ShippingServiceOptions": {
      "DeliveryExperience": "DeliveryConfirmationWithSignature",
      "CarrierWillPickUp": "false",
      "DeclaredValue": {
        "CurrencyCode": "USD",
        "Amount": 99
      },
      "LabelFormat": "PDF"
    },
    "LabelCustomization": {
      "CustomTextForLabel": "201765149",
      "StandardIdForLabel": "AmazonOrderId"
    }
  },
  "ShippingServiceId": "DHLMX_PTP_PACKAGE_EXPRESS",
  "HazmatType": "None"
}
```

The error response above seems to indicate that we are failing to include some data ("purchase parameters"?) or maybe some of the data we are already sending is wrong?
Please advise.
Thank you.

**Comment by chrisskhoury** [comment]
Hello @oaguayo1 ,

Looking at the request sample you shared, I would recommend adding the ShippingServiceOfferId which identifies a shipping service order made by a carrier. This is returned via the previous call made to fetch eligible shipment services.

If the issue still persists, please open a developer support case with the full sample request/response for the team to have a look.

Link for CreateShipmentRequest payload: https://developer-docs.amazon.com/sp-api/docs/merchant-fulfillment-api-v0-reference#createshipmentrequest
Link for Developer Support: https://developer.amazonservices.com/support-guidelines

Thanks :)

Chris
Solution Architect, Amazon Selling Partner APIs

**Comment by chrisskhoury** [comment]
resolving, feel free to reopen if issue persists
