### ISSUE TITLE
This developer is currently not eligible to receive new authorizations.

### ISSUE THREAD

**Issue by Zhuangziyao** [amzn/selling-partner-api-docs#3349]
when seller use an American account to authorize my app,it will return mistake:
Something went wrong
This developer is currently not eligible to receive new authorizations.
App lD: amzn1.sp.solution.938ca155-10e1-4b2e-a4b6-0b1fadt2ae7b
Error Code: MD9000

sellerid：AVSICDBHYACSH
authoirize link：[https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.938ca155-10e1-4b2e-a4b6-0b1fadf2ae7b&amp;state=201501-1770358410334274816-1747887538238816640&amp;version=beta](https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.938ca155-10e1-4b2e-a4b6-0b1fadf2ae7b&state=201501-1770358410334274816-1747887538238816640&version=beta)

but if I use a japanese account to authorize,it will success
I wonder why would American account failed.

**Comment by leonardonakagawa** [comment]
Hello @Zhuangziyao, 

Thank you for reaching out regarding Application authorization.

You can find details regarding this in our documentation, [Why am I getting an MD9000 error code?](https://developer-docs.amazon.com/sp-api/docs/sp-api-errors-frequently-asked-questions#why-am-i-getting-an-md9000-error-code).

We kindly ask you to check all the bullet points mentioned in the link, if your application fits on any of the examples listed.

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solution Architect, Selling Partner API Developer Support
