### ISSUE TITLE
Shipping label api

### ISSUE THREAD

**Issue by utsavvasoya** [amzn/selling-partner-api-docs#3350]
Anyone, please help me
I need to get an API for the shipping labels, For this API I need a shipping ID,
So how can I get a shipping ID from API Please suggest.

**Comment by chrisskhoury** [comment]
Hello @utsavvasoya,

When purchasing a shipment via our APIs, for example [purchaseShipment](https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference#purchaseshipment), the shipmentId is returned in the response.

You can then use it with follow up operations like the [getShipmentDocuments](https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference#getshipmentdocuments).

You can also do this via the Merchant Fulfillment API: https://developer-docs.amazon.com/sp-api/docs/merchant-fulfillment-api-v0-use-case-guide. But the Shipping API v2 is the our latest version to use: https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference

Thanks,
Chris
Solution Architect, Amazon Selling Partner API
