### ISSUE TITLE
 View shipments that are Send to Amazon warehouse

### ISSUE THREAD

**Issue by MuhammadDanyal** [amzn/selling-partner-api-docs#3354]
How to view shipments that are Send to Amazon warehouse. Which API and report to call and how to get the status change notifications for Send To Amazon Shipments.

The API Endpoint that i am using is GET /fba/inbound/v0/shipments but i am getting an empty object although there is a shipment already created.

I am using PHP Jleevers sdk for the API call and below is  my API request:

$query_type = 'SHIPMENT';
$marketplace_ids = array('ATVPDKIKX0DER','A2EUQ1WTGCTBG2');
$shipment_status_list =array('READY_TO_SHIP','SHIPPED','RECEIVING','CANCELLED','DELETED','CLOSED','ERROR','IN_TRANSIT','DELIVERED','CHECKED_IN'); 
$last_updated_after = '2023-09-01T00:00:00.000Z';
 $last_updated_before = '2023-09-30T00:00:00.000Z';
 
 $response = $apiInstance->getShipments( $query_type, $last_updated_after,$shipment_status_list,$last_updated_before, $marketplace_ids);
 

If we can use any report for that then please recommend that as well

**Comment by rodrifed** [comment]
Hi @MuhammadDanyal,

Thank you for sharing your issues with us.

I noted that you are using `$query_type = 'SHIPMENT'`, but providing date filters (`$last_updated_after` and `$last_updated_before`).
Could you please try the same request but using `$query_type = 'DATE_RANGE'`? You can omit the `$shipment_status_list` parameter.
```
QueryType = DATE_RANGE
Returns shipments based on the date range information provided by the LastUpdatedAfter and LastUpdatedBefore parameters.
```

If after this change you are still facing issues, I would kindly ask you to create a developer support case using our [Contact us form](https://developer.amazonservices.com/support), informing about the shipment that the selling partner has already created and doesn't show in the results, request id and timestamp of the API call.
Our support team will be able investigate and provide an answer to you.

Thank you,
Federico
Selling Partner Developer Services

**Comment by MuhammadDanyal** [comment]
Hi the issue has been resolved. can you please share how can i get the status of the shipments and notifications against these shipments whenever there is a change in status of the shipments to Amazon warehouse by amazon.
Thanks

**Comment by rodrifed** [comment]
Hi @MuhammadDanyal,

We don't provide proactive notifications for inbound shipment status changes. We will take your request in consideration for future launches.

There are some operations that you can use to get up-to-date information about your shipments, like [/getShipmentItemsByShipmentId](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitemsbyshipmentid) and [/getTransportDetails](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#gettransportdetails).
Also, the [FBA_INVENTORY_AVAILABILITY_CHANGES](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#fba_inventory_availability_changes) notification will inform you about changes in the FBA inventory quantities, like when an inbound shipment is processed.

I hope the information above was useful.

Thank you,
Federico
Selling Partner Developer Services
