### ISSUE TITLE
Is it legal to scrape seller central?

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#3359]
Hello, I want to know is it legal to scrape seller central brand analytics page?

if not, how does some website has data that is only available in seller central?

**Comment by tspicer** [comment]
I assume by "legal" you mean does Amazon support this method of bypassing the API to access data. Per Amazon, using bots and scraping to scrape account data like reports is not permitted.

Amazon expressly states that granting user authorizations to Amazon Portals to manually or programmatically circumvent Amazon policies for data access violates AUP. As a result, if detected by Amazon, a Seller Central or Vendor Central account can be suspended or terminated. Amazon Advertising prohibits developers from requesting credentials for Amazon Advertising interfaces and services (e.g., log-in credentials for the Advertising Console) for use in their applications. They state, "Never ask for or accept an Amazon Advertising Participant's access credentials for any purpose," which is exactly how reports like this are "scraped"

Here are various docs:

* [Amazon Advertising API Terms](https://advertising.amazon.com/API/docs/license-agreement)

* [Amazon Advertising API Data Protection Policy](https://advertising.amazon.com/API/docs/policy/en_US)

* Amazon Advertising Partner Network Terms & Conditions

* [Amazon Developer Services Agreement](https://sellercentral.amazon.com/mws/static/agreement?locale=en_US)

* [Data Protection Policy (DPP)](https://sellercentral.amazon.com/mws/static/policy?documentType=DPP&locale=en_CA)

* [Acceptable Use Policies (AUP)](https://sellercentral.amazon.com/mws/static/policy?documentType=AUP&locale=en_CA)

**Comment by Javadebi** [comment]
> I assume by "legal" you mean does Amazon support this method of bypassing the API to access data. Per Amazon, using bots and scraping to scrape account data like reports is not permitted.
> 
> Amazon expressly states that granting user authorizations to Amazon Portals to manually or programmatically circumvent Amazon policies for data access violates AUP. As a result, if detected by Amazon, a Seller Central or Vendor Central account can be suspended or terminated. Amazon Advertising prohibits developers from requesting credentials for Amazon Advertising interfaces and services (e.g., log-in credentials for the Advertising Console) for use in their applications. They state, "Never ask for or accept an Amazon Advertising Participant's access credentials for any purpose," which is exactly how reports like this are "scraped"
> 
> Here are various docs:
> 
> * [Amazon Advertising API Terms](https://advertising.amazon.com/API/docs/license-agreement)
> * [Amazon Advertising API Data Protection Policy](https://advertising.amazon.com/API/docs/policy/en_US)
> * Amazon Advertising Partner Network Terms & Conditions
> * [Amazon Developer Services Agreement](https://sellercentral.amazon.com/mws/static/agreement?locale=en_US)
> * [Data Protection Policy (DPP)](https://sellercentral.amazon.com/mws/static/policy?documentType=DPP&locale=en_CA)
> * [Acceptable Use Policies (AUP)](https://sellercentral.amazon.com/mws/static/policy?documentType=AUP&locale=en_CA)

So, how does so many sites like stoke.com have this data?

**Comment by tspicer** [comment]
@Javadebi , you should ask them.  Only they can tell you if they are using official Amazon APIs. 

If any third party is asking for an email address. or for you to create a new user account to access your Seller or Vendor account, they are not using Amazon application OAuth processes. This should be a red flag.

**Comment by tspicer** [comment]
@Javadebi , to help you out, you can see what Stoke is doing by looking at their help docs.

They are asking people to invite a Stoke user to a Seller account.  They then ask that the Stoke user be granted permissions that allow this user access to Brand Analytics data. Stoke is then using reporting data Amazon does not make available via API in its products.   You can always send a note to Amazon (3p-security@amazon.com) and ask them if a commercial service like Stoke requesting a merchant  create a dedicated user account in their seller central  account to scrape non-API data is in compliance.
