### ISSUE TITLE
How can I get seller info (shop name or business name) after got access token?

### ISSUE THREAD

**Issue by puneet-banknovo** [amzn/selling-partner-api-docs#3362]
Hey,
Guys was looking out to get the shop name of the business after i got the token but seems like there is no API.
The existing issue was closed so opening a new one for the same.

https://github.com/amzn/selling-partner-api-docs/issues/2291

**Comment by delbertheihei** [comment]
Yes, I had the same problem, I thought I could get the data using the Sellers API, but it doesn't work!

**Comment by puneet-banknovo** [comment]
Yes @delbertheihei seems like this is the imp api everyone needs but no updates on that.
