### ISSUE TITLE
Notification： Amazon SQS unable to receive messages

### ISSUE THREAD

**Issue by delbertheihei** [amzn/selling-partner-api-docs#3366]
Hi，guys，

I'm having some problems with the Notification interface, and have found that there have been some Issue's that have appeared in the past, but they have all been closed at the moment.

After following the Amazon SP API docs and Blog docs, I have successfully created the destination and subscription with Type: REPORT_PROCESSING_FINISHED, but Amazon SQS is not able to receive the message.

Is it because my API Endpoint is us-east-1, but my SQS region is us-west-2, or is there some other problem?

When I investigated the SQS monitoring I found that I am receiving empty notifications when I call the Report interface to generate a report file.

This is very confusing.

**Comment by delbertheihei** [comment]
Update:
I went to create a new SQS queue at Region=us-east-1, but still the same problem, receiving empty messages!

**Comment by rodrifed** [comment]
Hi @delbertheihei,

Thank you for sharing your issue with us.

Having the SQS queue in us-west-2 region (or any other one) is acceptable. You should be able to receive the incoming messages anyways.
Have you followed the steps to [grant SP-API permissions to write to your SQS queue](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue)?
The SQS queue's access policy should look similar to this one:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
      },
      "Action": [
        "kms:GenerateDataKey",
        "kms:Decrypt"
      ],
      "Resource": "*"
    }
  ]
}
```

I would also encourage you to take a look at the [Reports Notifications Quick Start](https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api-reports-notifications/).
This quick start provides an out of the box solution to create reports and process them using Notifications.

Thank you,
Federico
Selling Partner Developer Services

**Comment by delbertheihei** [comment]
> Hi @delbertheihei,
> 
> Thank you for sharing your issue with us.
> 
> Having the SQS queue in us-west-2 region (or any other one) is acceptable. You should be able to receive the incoming messages anyways. Have you followed the steps to [grant SP-API permissions to write to your SQS queue](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue)? The SQS queue's access policy should look similar to this one:
> 
> ```
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Principal": {
>         "AWS": "arn:aws:iam::437568002678:root"
>       },
>       "Action": [
>         "kms:GenerateDataKey",
>         "kms:Decrypt"
>       ],
>       "Resource": "*"
>     }
>   ]
> }
> ```
> 
> I would also encourage you to take a look at the [Reports Notifications Quick Start](https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api-reports-notifications/). This quick start provides an out of the box solution to create reports and process them using Notifications.
> 
> Thank you, Federico Selling Partner Developer Services

Yeah，Thank you for your help.
I've found out what the problem was and I'm now able to receive messages properly. 

![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/e833ff0c-b282-4095-ba00-f8c32ed5eef8)
