### ISSUE TITLE
[BUG] [/orders/v0/orders] [Inquiry About Buyer Invoice Retrieval Endpoint in SP-API]

### ISSUE THREAD

**Issue by bessaleh** [amzn/selling-partner-api-docs#3369]
I am currently working with the Amazon Selling Partner API (SP-API) and am in need of a way to retrieve buyer invoice information for specific orders.

I have reviewed the SP-API documentation, but I couldn't find a specific endpoint or method for retrieving this information. I would greatly appreciate it if you could provide guidance on how to access buyer invoice data or if there is an endpoint available for this purpose.

**Comment by chrisskhoury** [comment]
Hello @bessaleh,

Regarding this, the GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT report can return this information. You can find the attributes that are returned via this report here: https://developer-docs.amazon.com/sp-api/docs/invoice-data-reports-attributes

You can find info on Reports API and how to use it here: https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-use-case-guide

Keep in mind you will need to apply for the Tax Invoicing Restricted Role: https://developer-docs.amazon.com/sp-api/docs/tax-invoicing-restricted-role

Also make sure to check our YouTube channel for some useful tutorial videos: https://www.youtube.com/@amazon-sp-api/

Thank you :)

Chris
Solution Architect - Amazon Selling Partner API
