### ISSUE TITLE
[BUG] [SP-API] [Notification] Failed to subscribe to some type

### ISSUE THREAD

**Issue by delbertheihei** [amzn/selling-partner-api-docs#3373]
### Question
When I create or get a subscription, the type of the subscription is [ITEM_INVENTORY_EVENT_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#item_inventory_event_change), [ITEM_SALES_EVENT_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#item_sales_event_change), but the return message: `"code": "Unauthorized", "message": "Access to requested resource is denied."`. 

But it's ok when I subscribe to other types, I don't see in the user guide documentation that this type requires a specific token, and I get all authorisation when I authorise the app.

I searched the previous Issue and found that someone else had the same problem, but didn't get a reply.
Hopefully I can figure out if it's just me or if it's a bug in the SP API

### Subscription Failure Return Message
![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/d06fc543-7a9a-44fa-b07c-b17694d9238b)

### Other types of subscription success
![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/a2cbb0e3-e554-4665-ac2a-5bfbca3169e6)

### Scope of authorisation of the  APP
![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/d5dcda41-b156-4a57-9b67-02e26ce7e579)

**Comment by ritikacd** [comment]
Hi @delbertheihei 

Thanks for reaching out. Your application doesn't have access to the right role to create subscription for the notification type: [ITEM_INVENTORY_EVENT_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#item_inventory_event_change), [ITEM_SALES_EVENT_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#item_sales_event_change)

Please request for the [Brand Analytics](https://developer-docs.amazon.com/sp-api/docs/brand-analytics-role#feeds-reports-and-notifications) role to create subscriptions for these notifications. You need to apply for the role by updating your developer profile form. Once a new role gets approved, edit your application to select the new approved role in your application. Please note that you will also need to generate a new refresh token to access resources associated with the new role. 

Let us know if you have any issues. 

Thanks,
Ritika Chaudhary
Selling Partner API Team

**Comment by delbertheihei** [comment]
Hi @ritikacd 
Thank you for your reply, I have changed the developer profile and it is under review. I'll keep trying to see if it works once the review is complete！
