### ISSUE TITLE
[SP-API] [Issue] Direct-to-Consumer Shipping information access denied

### ISSUE THREAD

**Issue by aoberschmidt** [amzn/selling-partner-api-docs#3376]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
Hello,
I work with multiple customers who need access to Direct-to-Consumer Shipping information using the same application and code across these customers, therefore during the application process we use similar answers to the questions giving.  This is the first time we've ran into a situation where we were not accepted based on identical prior submissions:

Here is the rejected response from Amazon on the submission for SP-API Developer Profile Update : Restricted Access Request (ie. Direct-to-Consumer Shipping)

"We have reviewed the information you provided and determined that it is virtually identical to information that has been submitted in the past by you or another account. Therefore, you are not eligible for access to the Amazon SP-API roles you have requested."

Is there anyway to move this forward and get them approved?
The case # is 13759150551

I have seen similar issues submitted but no resolution

**Comment by rodrifed** [comment]
Hi @aoberschmidt,

Thank you for your message.

If you are providing service to multiple customers, you should [register as a public developer](https://developer-docs.amazon.com/sp-api/docs/register-as-a-public-developer).
By doing this you would need to maintain just one developer profile, which could be authorized by multiple customers.

Creating one developer profile per selling partner is legit only if the code and infrastructure is specific to that selling partner. Based on your message, I understand you are using the same code (developer by you) for all selling partners. In that case, a public developer profile is required.

Thank you,
Federico
Selling Partner Developer Services

**Comment by aoberschmidt** [comment]
Thank you @rodrifed, I will proceed with the public developer registration
