### ISSUE TITLE
Cannot create new listings and ASINs

### ISSUE THREAD

**Issue by alexisbellido** [amzn/selling-partner-api-docs#3377]
Hello,

I'm building a tool to manage listings and I've been creating, deleting and recreating five to ten listings (and reusing SKUs) for the past week. All of these listings use "Generic" as the brand and today when I try to create a listing with putListingsItem I get these issues from getListingsItem:

```
        "issues": [
            {
                "code": "8566",
                "message": "SKU does not match any ASIN and the product data provided is not eligible for ASIN creation. Please check 1) your UPC/EAN/GTIN is registered in the G1 tool or 2) ensure brand name used to list the product is the exact brand name or affiliated with the UPC/EAN/GTIN. If these steps did not work please log into your account and search error code 8566 for further information.",
                "severity": "ERROR"
            },
            {
                "code": "8572",
                "message": "You are using UPCs, EANs, ISBNs, ASINs, or JAN codes that do not match the products you are trying to list. Using incorrect UPCs, EANs, ISBNs, ASINs or JAN codes is prohibited and it can result in your ASIN creation privileges being suspended or permanently removed. Please ensure you are always using the appropriate UPC, EAN, ISBN, ASIN or JAN code when listing a product. If you have reached this message in error, please contact Seller Support using the following link: https://sellercentral.amazon.com/hz/contact-us. For more information, refer to the ASIN Creation Policy Help Page - https://sellercentral.amazon.com/gp/help/201844590",
                "severity": "ERROR"
            },
            {
                "code": "8008",
                "message": "We cannot recognize your child SKU: [allskus-shark-child-6]. For help on how to proceed, see https://sellercentral.amazon.com/gp/errorcode/8008",
                "severity": "WARNING"
            }
        ],
```

I'm reading https://sellercentral.amazon.com/help/hub/reference/201844590 and I see there's an ASIN creation limit but I have no idea if that's the problem I'm encountering. Any suggestions on what I can do to resolve this problem?

I've created case 13890030221 for this.

Thank you.

**Comment by puppsupr** [comment]
Hi [alexisbellido](https://github.com/alexisbellido),
I do see that your case has been closed due to lack of response from your end. Can you please up date the case with requested details.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
