### ISSUE TITLE
[BUG] [SP-API] returned ShipmentId from createShipment Call seems not to be valid

### ISSUE THREAD

**Issue by DocMcSky** [amzn/selling-partner-api-docs#3380]
## creating a DPD Label for amazon prime order

I'm using the SP-API Merchant Fullfillment Calls (URI: /mfn/v0/shipments) to create a new DPD/DHL label for an amazon order.
I started calling the "getEligibleShipmentServices" and fetches me the serviceID "DPDDE_PTP_PRIME_DOM" togehter with the ServiceOfferId.
After that the next call is to create the label itself using the "createShipment" Call.
These is my payload array to make the createShipment call (of course the call itself uses JSON):

<pre>
    [ShipmentRequestDetails] => Array
        (
            [AmazonOrderId] => 333-7777777-7777777
            [SellerOrderId] => 123456789
            [ShipFromAddress] => Array
                (
                    [Name] => Seller GmbH
                    [AddressLine1] => Sellerstreet 123
                    [CountryCode] => DE
                    [PostalCode] => 12345
                    [City] => Germancity
                    [Email] => info@domain.de
                    [Phone] => 004912341234567
                )

            [PackageDimensions] => Array
                (
                    [Length] => 30
                    [Width] => 30
                    [Height] => 15
                    [Unit] => centimeters
                )

            [Weight] => Array
                (
                    [Value] => 3604
                    [Unit] => g
                )

            [ShippingServiceOptions] => Array
                (
                    [DeliveryExperience] => DeliveryConfirmationWithoutSignature
                    [CarrierWillPickUp] => 1
                )

            [ItemList] => Array
                (
                    [0] => Array
                        (
                            [OrderItemId] => 12345678901234
                            [Quantity] => 1
                        )

                )

        )

    [ShippingServiceId] => DPDDE_PTP_PRIME_DOM
    [ShippingServiceOfferId] => AAAAAAAAAQCiNLEtYkhmCblFhio3Y...and_so_on=
</pre>

## The Result of this Label-Call

The result is HTTP-200 ok, and I will receive a Label like this:

<pre>
[payload] => Array
        (
            [ShipmentId] => b3c3d3e3-xxxx-xxxx-xxxx-xxxxxxxxxxxx
            [AmazonOrderId] => 333-7777777-7777777
            [Insurance] => Array
                (
                    [CurrencyCode] => EUR
                    [Amount] => 0
                )

            [ItemList] => Array
                (
                    [0] => Array
                        (
                            [OrderItemId] => 12345678901234
                            [Quantity] => 1
                        )

                )

            [ShipFromAddress] => Array
                (
                    [Name] => Seller GmbH
                    [AddressLine1] => Sellerstreet 123
                    [CountryCode] => DE
                    [PostalCode] => 12345
                    [City] => Germancity
                    [Email] => info@domain.de
                    [Phone] => 004912341234567
                )

            [ShipToAddress] => Array
                (
                    [Name] => Mr. Customer
                    [AddressLine1] => 
                    [AddressLine2] => Street 123
                    [Email] => 
                    [City] => AnotherGermanCity
                    [PostalCode] => 12345
                    [CountryCode] => DE
                    [Phone] => 
                )

            [PackageDimensions] => Array
                (
                    [Length] => 30
                    [Width] => 30
                    [Height] => 15
                    [Unit] => centimeters
                )

            [Weight] => Array
                (
                    [Value] => 3604
                    [Unit] => g
                )

            [ShippingService] => Array
                (
                    [ShippingServiceName] => DPD Prime Domestic Seller2Home
                    [CarrierName] => DPD
                    [ShippingServiceId] => DPDDE_PTP_PRIME_DOM
                    [ShippingServiceOfferId] => AAAAAAAAAQCiNLEtYkhmCblFhio3Y...and_so_on=  (same code as received in getEligableService)
                    [ShipDate] => 2023-09-25T10:10:20Z
                    [EarliestEstimatedDeliveryDate] => 2023-09-26T00:00:00Z
                    [LatestEstimatedDeliveryDate] => 2023-09-26T00:00:00Z
                    [Rate] => Array
                        (
                            [CurrencyCode] => EUR
                            [Amount] => 2.99
                        )

                    [ShippingServiceOptions] => Array
                        (
                            [DeliveryExperience] => DeliveryConfirmationWithoutSignature
                            [DeclaredValue] => Array
                                (
                                    [CurrencyCode] => EUR
                                    [Amount] => 0
                                )

                            [CarrierWillPickUp] => 1
                        )

                )

            [Label] => Array
                (
                    [Dimensions] => Array
                        (
                            [Length] => 6
                            [Width] => 4
                            [Unit] => inches
                        )

                    [FileContents] => Array
                        (
                            [Contents] => H4sIAAAAAAAAAOy6Z1STX7cvSm+hC5GOSJdQl...the_label_code=
                            [FileType] => image/png
                            [Checksum] => aHlaPcxz...correct=
                        )

                    [LabelFormat] => PNG
                )

            [Status] => Purchased
            [TrackingId] => 01231234567890
            [CreatedDate] => 2023-09-25T10:10:21Z
        )
</pre>

## Where will be the bug

Well, the label is valid, the label is present in the order page in sellercentral, everything seems to be fine.

But however, we cannot call a service like "getShipment" (e.g. for printing the label again) or "cancelShipment" without getting back an error, at any time the same:

<pre>
Code: InternalFailure
Nachricht: We encountered an internal error. Please try again.
Details: 
</pre>

We uses the ShipmenId we've got from the createShipment Call.

## What did we try

Since Amazon canceled the Amazon MWS service a few days ago we uses till then the MWS Service to handle the orders and to create the labels. This is not working anymore, so we uses now the SP-API. 
However we tryed to use the "older" ShipmentIds we've git one or two weeks ago from the MWS Service and uses them in the actually SP-API Call "getShipment" and what should I say, ANY of these ShipmentIds will working fine and returns the expected behavior.

Will I use the new by SP-API generated ShipmentIds by using createShipment no one will work, any call returns the error above.

**Comment by chrisskhoury** [comment]
Hello @DocMcSky ,

Since you mentioned that you are relying on the shipmentId that is returned via the createShipment call, and the request is failing, do you mind opening a developer support case with the relevant information so that the team can debug this?

Thanks :)

Chris
Solution Architect, Amazon Selling Partner API

**Comment by DocMcSky** [comment]
Hello @chrisskhoury ,
thanks for your idea. In case of my first opinion something might went wrong here with our program code I decided to ask in this board if anybody may have similar problems or something else.
Well, of course we could start a case in the sellercentral support board.
There we could send real data within to check a real case.
