### ISSUE TITLE
Improve errors

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-docs#3388]
Why is Amazon so bad at writing documentation and providing error messages?

For example, in the case of a FATAL error in reports, [it states](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#processingstatuses):

'The report was aborted due to a fatal error.'

Wow, that really helps a lot. It's like saying tomorrow is not yesterday. Bravo to you, my lord; you are the wisest man in the kingdom.

**Comment by Feng-Xg** [comment]
Maybe they like use 'try catch throw'  :）
