### ISSUE TITLE
searchCatalogItems not working and produce only Invalid Input

### ISSUE THREAD

**Issue by nejimz** [amzn/selling-partner-api-docs#3397]
Hello,

I have a problem like this but the identifiers type is SKU.
Can you help me on this?

Endpoint: `https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items`
Operation: `searchCatalogItems`

Request ID: `1b5f4ed8-1896-43ea-b193-109e0b45694f`
Run Datetime: `2023-10-05 00:12:17`

Params:
```
[
 "marketplaceIds" => "XXXXXXXX"
  "identifiers" => "sku_1"
  "identifiersType" => "SKU"
  "includedData" => "identifiers,attributes,images,productTypes,salesRanks,summaries"
  "sellerId" => "xxxxx"
  "pageSize" => 20
]
```

Errors:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```

_Originally posted by @nejimz in https://github.com/amzn/selling-partner-api-docs/issues/2490#issuecomment-1748229996_

**Comment by Feng-Xg** [comment]
@nejimz 
'/catalog/2022-04-01/items' is not the correct value of Endpoint.
reference: https://developer-docs.amazon.com/sp-api/docs/sp-api-endpoints

**Comment by nejimz** [comment]
> @nejimz '/catalog/2022-04-01/items' is not the correct value of Endpoint. reference: https://developer-docs.amazon.com/sp-api/docs/sp-api-endpoints

Hi @Feng-Xg,
Thank you for dropping by I just updated complete endpoint.

Endpoint
`https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items`

**Comment by Feng-Xg** [comment]
> > @nejimz '/catalog/2022-04-01/items' is not the correct value of Endpoint. reference: https://developer-docs.amazon.com/sp-api/docs/sp-api-endpoints
> 
> Hi @Feng-Xg, Thank you for dropping by I just updated complete endpoint.
> 
> Endpoint `https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items`
> 
> Client Error: `` GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?identifiers=sku1&identifiersType=SKU&marketplaceIds=xxxxxxx&includedData=summaries&sellerId=xxxx&pageSize=10` resulted in a `400 Bad Request ``

@nejimz hi ,read the developer guide carefully, ruquest url has missing operation , it need to be 
GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items/XXXXXXXXXX
  ?marketplaceIds=ATVPDKIKX0DER
  &includedData=attributes,dimensions,identifiers,images,productTypes,salesRanks,summaries,relationships,vendorDetails

> https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-use-case-guide

**Comment by nejimz** [comment]
> > > @nejimz '/catalog/2022-04-01/items' is not the correct value of Endpoint. reference: https://developer-docs.amazon.com/sp-api/docs/sp-api-endpoints
> > 
> > 
> > Hi @Feng-Xg, Thank you for dropping by I just updated complete endpoint.
> > Endpoint `https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items`
> > Client Error: `` GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?identifiers=sku1&identifiersType=SKU&marketplaceIds=xxxxxxx&includedData=summaries&sellerId=xxxx&pageSize=10` resulted in a `400 Bad Request ``
> 
> @nejimz hi ,read the developer guide carefully, ruquest url has missing operation , it need to be GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items/XXXXXXXXXX ?marketplaceIds=ATVPDKIKX0DER &includedData=attributes,dimensions,identifiers,images,productTypes,salesRanks,summaries,relationships,vendorDetails
> 
> > https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-use-case-guide


@Feng-Xg I think you're referring for `getCatalogItem`
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#getcatalogitem
![image](https://github.com/amzn/selling-partner-api-docs/assets/12077438/9480635e-cc0e-49aa-b10e-03ee00b27e81)

This is the url for `searchCatalogItems`
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#searchcatalogitems
![image](https://github.com/amzn/selling-partner-api-docs/assets/12077438/ca6d70e6-8cbb-46e5-bb4b-ca418081ea08)

**Comment by Feng-Xg** [comment]
@nejimz It's no idea of that error, the request address and parameters are correct, literally. Maybe you could find at `https://developer-docs.amazon.com/sp-api/docs/resolving-400-errors`

**Comment by nejimz** [comment]
> @nejimz It's no idea of that error, the request address and parameters are correct, literally. Maybe you could find at `https://developer-docs.amazon.com/sp-api/docs/resolving-400-errors`

@Feng-Xg Checking on this.
Thank you

**Comment by nejimz** [comment]
Still the same error.
I tried removing all fields and adding one by one to produce some errors.

**Comment by leonardonakagawa** [comment]
Hi @nejimz,

When using the [`searchCatalogItems`](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#get-catalog2022-04-01items) operation for checking an SKU information, you need to ensure that, you are passing the parameters `identifiersType` as `SKU` and `identifiers` as the SKU code.

Example: `/catalog/2022-04-01/items?identifiersType=SKU&identifiers=SKU1234&marketplaceIds=ATVPDKIKX0DER&includedData=summaries&sellerId=XXXXXXXXXXXXX&pageSize=20`

I would recommend to check if you have approval for the Product Listing role in your developer profile. Also, if the Product Listing role selected in the App registration page for your application.

You can find details regarding this in our [Catalog Items API v2022-04-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-use-case-guide#step-1-search-for-items).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by Noor0** [comment]
@nejimz Did you figure out what the issue was?
