### ISSUE TITLE
[BUG] [SP-API] getcatalog brand name search is not working

### ISSUE THREAD

**Issue by immanuelt** [amzn/selling-partner-api-docs#3407]
https://{{apiUrl}}/catalog/2022-04-01/items?pageSize=20&brandNames=Christopher Knight Home&marketplaceIds=ATVPDKIKX0DER&keywords=Behrens Indoor Wood Coffee Table by Christopher Knight Home - Brown

When the brand name(eg brand name=Christopher Knight Home) contain space, the search is returning 0 results.

This is a bug

**Comment by mvwright23** [comment]
I'm seeing this too

**Comment by chrisskhoury** [comment]
Hello @immanuelt,

I think relying on the "_" character to split brand names that contain spaces should solve the issue.

so it would be:

https://{{apiUrl}}/catalog/2022-04-01/items?pageSize=20&brandNames=Christopher_Knight_Home&marketplaceIds=ATVPDKIKX0DER&....

Best,

Christopher

Solution Architect - SP API

**Comment by mvwright23** [comment]
I just tried replacing " " with "_" and confirms it works (i.e. "brandNames=Pearson_Education_ESL" instead of "brandNames=Pearson Education ESL". Thanks @chrisskhoury! I wish the documentation included this important point.....

**Comment by immanuelt** [comment]
Thank you for the help.
