### ISSUE TITLE
SP-API Vendor Retail Shipment Carton Label

### ISSUE THREAD

**Issue by redtechflow** [amzn/selling-partner-api-docs#3409]
I would like to know if there's really no way to print the carton label for Vendor Retail API?

If so, are there any workarounds on how we can print carton label? 

Thanks

**Comment by puppsupr** [comment]
Hi,
Currently there is no API to print carton label for Vendor Retail Procurement.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
