### ISSUE TITLE
Invalid response example at OrderAPI v0 model getOrders response

### ISSUE THREAD

**Issue by vaidas-lungis** [amzn/selling-partner-api-docs#3412]
**Describe the improvement**
Invalid response example at OrderAPI v0 model getOrders response https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-use-case-guide#response-example
Missing main `payload` property

**Description of what the documentation currently says**
```json
{
"NextToken": "2YgYW55IGNhcm5hbCBwbGVhc3VyZS4",
"Orders": [
  {
    "AmazonOrderId": "902-3159896-1390916",
    "PurchaseDate": "2017-01-20T19:49:35Z",
```
![Screenshot 2023-10-17 at 19 56 09](https://github.com/amzn/selling-partner-api-docs/assets/5111555/0360f47a-fdc4-4801-b2b3-edbb6869364d)

**Description of what the documentation should say**

```json
{
  "payload": {
    "NextToken": "2YgYW55IGNhcm5hbCBwbGVhc3VyZS4",
    "Orders": [
      {
```

like in the https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-model
![Screenshot 2023-10-17 at 19 57 55](https://github.com/amzn/selling-partner-api-docs/assets/5111555/4134611e-2116-4de3-8118-f334e2b8ee9d)

**Comment by rodrifed** [comment]
Hi @vaidas-lungis,

Thank you for reporting this issue.
We have already taken note, and will update the documentation accordingly.

Thank you,
Federico
Selling Partner Developer Services
