### ISSUE TITLE
[BUG] [SP-API] [Issue] Request GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT result in FATAL

### ISSUE THREAD

**Issue by hongfei-zhou** [amzn/selling-partner-api-docs#3413]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
API: createReport
Report: GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT

## Expected Behavior

The report should be successfully created.

## Current Behavior

run `createReport` API with `GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT` with `reportPeriod=DAY` and a start date and end date covering multiple days resulted in a FATAL error:
```
"errorDetails" : "dataStartTime must be the same day as dataEndTime when reportPeriod=DAY"
```
Based on the document [here](https://developer-docs.amazon.com/sp-api/docs/report-type-values-analytics#brand-analytics-reports), shouldn't we be able to request reports spanning over multiple periods?

**Comment by rodrifed** [comment]
Hi @hongfei-zhou,

Thank you for your message.

The `reportPeriod` attribute specifies the length of the time window of the requested report.
In your case, by specifying `reportPeriod=DAY` you are requesting data for a one-day period. Therefore, start and end date must be on the same day.
If you want to create a report spanning multiple days, you should use `reportPeriod=WEEK`, and use a Sunday for `dataStartTime` and a Saturday for `dataEndTime`.

Thank you,
Federico
Selling Partner Developer Services
