### ISSUE TITLE
createUploadDestinationForResource interface call returns Unauthorized, Why?

### ISSUE THREAD

**Issue by chengpan9** [amzn/selling-partner-api-docs#3414]
createUploadDestinationForResource interface call returns Unauthorized.
 
param:
POST https://sellingpartnerapi-na.amazon.com/uploads/2020-11-01/uploadDestinations/aplus/2020-11-01/contentDocuments?contentType=image/jpeg&contentMD5=9e92dc1ed22ffc814f063f02b1c0f233&marketplaceIds=ATVPDKIKX0DER

ResponseBody:
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}

**Comment by rodrifed** [comment]
Hi @chengpan9,

Thank you for your message.

Have you confirmed that the access token you are using is from a selling partner's account that has authorized your application to execute the aforementioned operation?
In your case, it is required that your application has the [Product Listing role](https://developer-docs.amazon.com/sp-api/docs/product-listing-role) selected, and the the selling partner's authorization was performed after the role was added to the application.

If the information above does not prove useful, I would kindly ask you to open a support case using the [Contact Us form](https://developer.amazonservices.com/support), and provide a description of the issue together with a sample request id and timestamp.

Thank you,
Federico
Selling Partner Developer Services
