### ISSUE TITLE
[BUG] [SP-API] [Issue] Report type GET_FBA_SNS_FORECAST_DATA return status CANCELLED

### ISSUE THREAD

**Issue by krystian-rzepa** [amzn/selling-partner-api-docs#3415]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
API: createReport
Report: GET_FBA_SNS_FORECAST_DATA

## Expected Behavior

The report should be successfully created.

## Current Behavior

After run createReport, status is changing from IN_QUEUE -> IN_PROGRESS -> CANCELLED.
Other reports like GET_FBA_INVENTORY_PLANNING_DATA works fine with my config.

**Comment by rodrifed** [comment]
Hi @krystian-rzepa,

Thank you for your message.

There are two reasons why a report can result in `CANCELLED` status:
1. An explicit cancellation request before the report starts processing.
2. An automatic cancellation if there is no data to return.

If the selling partner has not intentionally cancelled the report, it means that there was no data to return.
If you feel this is incorrect, I would kindly ask you to open a support case using our [Contact Us form](https://developer.amazonservices.com/support).

Thank you,
Federico
Selling Partner Developer Services
