### ISSUE TITLE
[BUG] [SP-API] [Issue]Warning！ Call getShipments returned shipmentList that shipmentStatus is null

### ISSUE THREAD

**Issue by moonight-zhou** [amzn/selling-partner-api-docs#3416]
Part of the code:
try {
	GetShipmentsResponse shipmentsResponse = client.getShipments("SHIPMENT", shopInfo.getMarketplaceId(), shipmentStatusList, shipmentIds,
			null, null, null);
	log.info(shipmentsResponse);
} catch (ApiException e) {
	log.error(e.getMessage());
}
Debug Screenshot:
![image](https://github.com/amzn/selling-partner-api-docs/assets/45207522/46a8d88f-ec58-46a9-80a8-209e33db8d2c)

**Comment by chrisskhoury** [comment]
Hello @moonight-zhou,

Did you try this with postman, you should receive an empty list there? I would change some of the request parameters, this means that there are no services available for the requested options.

Best,

Chris Khoury
Solution Architect, Amazon
