### ISSUE TITLE
Error Code: MD9000 This Developer is not currently eligible for new authorizations.

### ISSUE THREAD

**Issue by yiweixia** [amzn/selling-partner-api-docs#342]
I'm following the guide, and I'm at the step where I'm trying to onboard to my registered application with a trusted seller account. However, when the seller account goes to the OAuth URI, they get the following message.

> Something went wrong
> This Developer is not currently eligible for new authorizations.
> App ID: amzn1.sellerapps.app.21aed38e-a640-4575-898e-8f08dab34ef5
> Error Code: MD9000

I've followed all the steps in the guide, and I can't find any documentation on how to fix this. Any ideas why my developer account isn't eligible, or how to fix it?

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

Based on the app details, your application does not have the OAuth information required to initiate the OAuth workflow. You can still generate a refresh token by performing self-authorization but to perform 3p authorization, you need to add login and redirect URI information to your application.

Please edit the app and provide those details. After saving the changes, you should be able to initiate the workflow in draft stage.

Please let us know if issue persists and feel free to open the case to further troubleshoot the problem.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by yiweixia** [comment]
That solved it, thank you! 
I'm pretty new to this and didn't realize that OAuth required a redirect URI, so I didn't add them when registering the app. 

It may be helpful for less experienced developers to specify in the guide that those fields are required when registering the app, instead of just having

> 3.Follow the instructions to register your application.

Or putting a warning pop up if you try to register the application without it.

**Comment by davidkhardwick** [comment]
This post was very helpful and I agree with yiweixia's suggestion

**Comment by og77077** [comment]
I am getting the same error MD9000 (with &version=beta) and MD1000 (without &version=beta). I have already submitted the app and cannot change the redirect URI. The status of my app is "Submitted". Can you please help me?

**Comment by ianrussel** [comment]
Hi @ShivikaK , i have same issue. How do you mean the "logiin" in login and redirect URI. I added the redirect URI but how do you the "login" ? is it the login URI in my app ?

Thanks

**Comment by ShivikaK** [comment]
Hello @yiweixia,

Thank you for confirming that the resolution provided fixed the problem. 

We are working on making these fields easier to understand. 

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
> I am getting the same error MD9000 (with &version=beta) and MD1000 (without &version=beta). I have already submitted the app and cannot change the redirect URI. The status of my app is "Submitted". Can you please help me?

Hello @og77077,

Please open a new issue with us to report this issue if possible as this issue has been closed. If you can share the app ID, I can help get the submission cancelled. You cannot edit the app in submitted state.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by vipin-shrivastava** [comment]
@ShivikaK 

Can you please help me ?  how can i resolve this issue ?
![Screenshot_12](https://user-images.githubusercontent.com/58874186/124758390-28cd8c00-df4c-11eb-9f42-e660730c85a2.png)

**Comment by ddoni89** [comment]
Hi, 
Sorry, I am not a developer, just an Amazon seller who is trying to connect my seller accpount to Listing DoJo for a split test. I am encountering this error Error Code: MD9000

How can I go about it?

Many thanks 🙏

**Comment by KapilPandit0408** [comment]
How to add OAuth in Login and Redirect URI please guide me

**Comment by yanna0303** [comment]
> 

Hello, I also happened this issue and pretty new to this, and struggling with it for a few days.
It drives me almost crazy :(   
please help

**Comment by KapilPandit0408** [comment]
Try to give access to correct developer and provide use cases to AWS
