### ISSUE TITLE
Document what createInboundShipmentPlan actually creates.

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#344]
Document what createInboundShipmentPlan actually creates, if anything.  It seems to create nothing, which is confusing because it returns an FBA shipment ID in the result, as if it reserved that ID for you.  Yet there's no "GET /fba/inbound/v0/plans" endpoint, so if you don't immediately save that ID, it's lost forever.

The current documentation doesn't mention this at all: https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#createinboundshipmentplan

**Comment by falfer** [comment]
Same problem here.

**Comment by jesusvalle** [comment]
From the tests I have done, I understand that with the createInboundShipmentPlan call a "validation" of the plan is done, and with the shipmentId that returns, is what you can create the plan with through the createInboundShipment call (with this one you can see the plan from seller central).

Can anyone confirm this?

**Comment by johnkw** [comment]
Note that `createInboundShipmentPlan` reserves the right to split your planned shipment into multiple shipments. We've never had that happen. It would be a nightmare if Amazon told us to split pallets into sub-pallet pieces, so thankfully that's never happened. But the frightening threat is always hanging there as a possibility.

That said, it's still unclear what it actually creates.  Does it reserve that FBA shipment ID that it returns?  If you never use it, is it lost forever?  Is there a timeout and then it gets auto-deleted?  Very mysterious.

**Comment by johnkw** [comment]
The documentation is now at https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#inboundshipmentplan but does not address this. It is still a mystery where the ID is saved, if at all, and no indication in the doc that it is lost forever if you don't save it yourself.

**Comment by johnkw** [comment]
This is still very broken and mysterious. I suspect there is something really being created on the back end, but there's no way to `GET` it, which is bizarre.

**Comment by johnkw** [comment]
Still needs documentation.

**Comment by johnkw** [comment]
I just stumbled on a clue to this in the error message generated by POSTing a new shipment to `/fba/inbound/v0/shipments/` with an extra SKU that was not in original call to createInboundShipmentPlan:

```
"Error: You must include a valid ShipmentId with a call to the CreateInboundShipment operation. Get ShipmentId values by calling the CreateInboundShipmentPlan operation. The request to CreateInboundShipment must include only items and quantities that have been previously planned through CreateInboundShipmentPlan. If a ShipmentId is not used to create a shipment within 48 hours it will expire."
```

**Comment by chastain1337** [comment]
@johnkw this is helpful, I was wondering what would happen if we altered the plan before creating the shipment, but afraid to try it myself. This API is seriously lacking in documentation.

**Comment by johnkw** [comment]
This is addressed in the new API. It is now documented that a Plan is a real thing that exists, and there are calls to retrieve prior plans: https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplans

Whether the new API works or not is a topic for another day.
