### ISSUE TITLE
SP-API GET /catalog/2022-04-01/items/{asin}  included_data 'salesRank' does not work

### ISSUE THREAD

**Issue by gvarnum** [amzn/selling-partner-api-docs#3446]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/3445

<div type='discussions-op-text'>

<sup>Originally posted by **gvarnum** November  3, 2023</sup>
I'm having trouble returning json data for the above endpoint (GET  /catalog/2022-04-01/items/{asin}) when I include too many included_data data sets. Is there a limitation on the amount of data that can be returned per request that I am not aware of? Below is my error code when I add too many data sets:  "errors": [
    {
      "code": "InvalidInput",
      "message": "Request has missing or invalid parameters and cannot be parsed.",
      "details": ""
    }
  ]
} 
Returns expected json otherwise. 

Through further testing.... It seems like the 'salesRank' data set does not work through this endpoint. </div>

**Comment by domdellumich** [comment]
Mind providing a list of sample included_data parameters and the responses you seem for each? I've been using the salesRank attribute for quite some time without issue so it may be a formatting mishap in the way you're sending the requests.

**Comment by gvarnum** [comment]
No problem @domdellumich. All the potential params of included_data are [attributes, dimensions, identifiers, images, productTypes, relationships, summaries, vendorDetails, salesRank]. When I try to run just salesRank by itself I get the following 400 Client Error: Bad Request for url: https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items/B07V2PHS4J?marketplaceIds=ATVPDKIKX0DER&includedData=salesRank (Testing on a random ASIN)... All the other params return the expected response.

**Comment by rugved1991** [comment]
Hi @gvarnum,

Thanks for reaching out. The parameter added is incorrect. It should be "salesRanks".
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#includeddata

Best,
Rugved
Solutions Architect, SP-API

**Comment by gvarnum** [comment]
Thanks @rugved1991 this was driving me crazy, should've looked back at the Item variables.
