### ISSUE TITLE
Cannot get product from  catalog

### ISSUE THREAD

**Issue by CebulMaciej** [amzn/selling-partner-api-docs#345]
Hello. I Have problem. I registered application. I can generate access and refresh token for users but i cannot use any endpoint. i tried call:
https://sandbox.sellingpartnerapi-eu.amazon.com/catalog/v0/items?EAN=9786201515369&MarketplaceId=ATVPDKIKX0DER&version=beta

Response was Unauthorized, but now it is : InternalServerErrorException

IAM is set on user, which have policy given on Api Guide, attached as Managed Policy.

What i can to do with that?

Thanks you very much for every response :)

SellerId:196419853345
Operation:catalog/v0/items
MarketplaceId:ATVPDKIKX0DER
RequestId:78ad9e29-7d60-48dc-aecc-5d71be269b0c
TimeStamp:20210122T125449Z 

I wrote to support, because i have no idea how to resolve this problem, but in response was link to report this: 
https://services.amazon.co.eu/standards/contact-us.html
But this link does not work.
Where can i find any help to know, what is the exception reason?

**Comment by ShivikaK** [comment]
Hello,

We have received the support case reported for this issue and a Support Engineer will reach out to with next steps.

Meanwhile your sandbox endpoint is not correct as you are adding version=beta to the request which is not a valid endpoint.

Please refer to the sandbox documentation in our developer guide to understand how to create a sandbox request -
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox
