### ISSUE TITLE
关于 GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 的一些疑问

### ISSUE THREAD

**Issue by springhuasheng** [amzn/selling-partner-api-docs#3451]
1. 第一个问题, 我获取结算报告数据类型是: GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2, 但是通过接口只能获取到settlementId的结束时间是在当前时间之前的数据, 有没有别的办法或者方式 获取到的数据是和亚马逊后台下载的数据是一致, 就是获取到 未到settlementId结束时间的部分数据
2. 第二个问题, 是有一小部分settlementId丢失的情况, 比如 一个店铺的一个地区, 应该是有 10条settlementId的数据, 但是通过接口就获取到9条settlementId的数据 少了一条settlementId的数据 ( 并且settlementId的结束时间是在当前时间之前的) , 比较出问题是因为 和从亚马逊后台下载的数据和接口获取的数据进行了比较

**Comment by freedom64life** [comment]
please use english..
