### ISSUE TITLE
[BUG] [SP-API] [Issue]GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL garbled when product name start with "，and not end with "

### ISSUE THREAD

**Issue by mysaber** [amzn/selling-partner-api-docs#3460]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Report type : GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL

I am parsing GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL, it was found that the product name of the customer started with the symbol "", and then the product name in GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL report was wrong, resulting in no "end". The data in the entire report was garbled, and the format I downloaded was txt

**Comment by rodrifed** [comment]
Hi @mysaber,

Thank you for reporting this issue.

In order for our teams to do the corresponding analysis, I kindly ask you to [open a developer support case](https://developer.amazonservices.com/support). While doing it, please include merchant token, report id and timestamp, so we can identify the offending report document.

Thank you,
Federico
Selling Partner Developer Services

**Comment by mysaber** [comment]
Could you create some data in the sandbox for testing? This issue was feedback from the customer to us, and we cannot provide data to anyone, including Amazon, without authorization from the customer.

**Comment by rodrifed** [comment]
Hi @mysaber,

You don't have to include any customer data.
Merchant token, report id and timestamp are attributes that will help us identify the corresponding report in our internal systems, in order to troubleshoot the issue.

Thank you,
Federico
Selling Partner Developer Services

**Comment by mysaber** [comment]
As a developer, I don't have access to the production environment's data. Currently, in order to attract more users to use our software, we have signed confidentiality agreements with users, which are strictly enforced. We also request customers to download this report themselves from the Amazon backend, and it contains the same data. Can I ask customers to open a case and inquire through the Amazon backend? Because this issue is not specific to SP-API.

**Comment by mysaber** [comment]
> Hi @mysaber,
> 
> You don't have to include any customer data. Merchant token, report id and timestamp are attributes that will help us identify the corresponding report in our internal systems, in order to troubleshoot the issue.
> 
> Thank you, Federico Selling Partner Developer Services



> Reference in n

As a developer, I don't have access to the production environment's data. Currently, in order to attract more users to use our software, we have signed confidentiality agreements with users, which are strictly enforced. We also request customers to download this report themselves from the Amazon backend, and it contains the same data. Can I ask customers to open a case and inquire through the Amazon backend? Because this issue is not specific to SP-API.

**Comment by mysaber** [comment]
@

> Hi @mysaber,
> 
> You don't have to include any customer data. Merchant token, report id and timestamp are attributes that will help us identify the corresponding report in our internal systems, in order to troubleshoot the issue.
> 
> Thank you, Federico Selling Partner Developer Services

@rodrifed As a developer, I don't have access to the production environment's data. Currently, in order to attract more users to use our software, we have signed confidentiality agreements with users, which are strictly enforced. We also request customers to download this report themselves from the Amazon backend, and it contains the same data. Can I ask customers to open a case and inquire through the Amazon backend? Because this issue is not specific to SP-API.

**Comment by rodrifed** [comment]
Hi @mysaber,

In that case, yes, please ask the seller to open a support case.

Thank you,
Federico
Selling Partner Developer Services
