### ISSUE TITLE
[BUG] [SP-API] [Issue] main_product_image locator can't use private links, only Amazon hosting

### ISSUE THREAD

**Issue by mlemoing** [amzn/selling-partner-api-docs#3462]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
2021-08-01

## Expected Behavior
Upload products and offers with images hosted on my server, like the documentation explains.

The attribute "main_product_image_locator has this configuration for the product type CELLULAR_PHONE_CASE :

```
     "main_product_image_locator": {
            "title": "Localisateur de l'image principale du produit",
            "description": "Indiquez la localisation et la source de l'image",
            "examples": [
                "Alimentation"
            ],
            "type": "array",
            "minItems": 1,
            "minUniqueItems": 1,
            "maxUniqueItems": 1,
            "selectors": [
                "marketplace_id"
            ],
            "items": {
                "type": "object",
                "required": [
                    "marketplace_id",
                    "media_location"
                ],
                "properties": {
                    "marketplace_id": {
                        "$ref": "#/$defs/marketplace_id"
                    },
                    "media_location": {
                        "title": "URL de l’image principale",
                        "description": "URL où se trouve l’image principale du produit spécifique à l’offre.",
                        "editable": true,
                        "hidden": false,
                        "examples": [
                            "http://www.companyname.com/images/1250.main.jpg"
                        ],
                        "type": "string",
                        "format": "uri",
                        "pattern": "^(https?|s3)://"
                    }
                },
                "additionalProperties": false
            }
        }
```

Therefore I send my own URL for 'media_location' has shown in the example : 

```
"examples": [
    "http://www.companyname.com/images/1250.main.jpg"
]
```

## Current Behavior
However, I get this error : 

"code": "invalidinput", 
"message": "Unable to Retrieve Media Content for URL 'Media Content is Not Hosted by Amazon or Amazon Web Services (such as AWS S3 or AWS CloudFront)'"

My url is a standard http link with which includes my CDN. I guess Amazon is not clear about what we can use and what we can't, they just force Sellers to migrate on SP-API and face issues like this one. In the end, we don't have any other choice to fully migrate images if we want to use them automatically.

Then I'm gonna test 2 other solutions :
- Create all products with SP-API and generate a CSV file which includes images to upload it manually on Seller Central. For my project, I only need to create images once.
- Creating feeds to upload my products, may be they allow private links to be uploaded by feeds

## Your Environment
I use Postman for now (the app will be developped in PHP)

**Comment by rodrifed** [comment]
Hi @mlemoing,

Thank you for your message.

Indeed, images submitted through the Listings Items API have to be hosted in a publicly accessible S3 bucket, a private S3 bucket with corresponding permissions, or behind a CloudFront distribution.
You can find all requirements in [this link](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide#submitting-images-and-other-media-attributes):

```
The Listings Items API accepts product images and other media content attributes from the following sources:
- Publicly accessible Amazon S3 bucket content downloaded through HTTP or HTTPS URL
- Publicly accessible Amazon CloudFront distribution content downloaded through HTTP or HTTPS URL
- Private Amazon S3 bucket content downloaded through S3 URL (for example, s3://bucket-name/object-name.jpg)

Images hosted on third-party servers are not supported.

If you use a private Amazon S3 bucket, you must also configure your Amazon S3 bucket policy to allow the GetObject and ListBucket operations on the IAM Role accessing the bucket (arn:aws:iam::368641386589:role/Media-Download-Role).
```

We have taken note of your feedback, and apologize for the inconveniences the current set up might cause to you.

Thank you,
Federico
Selling Partner Developer Services

**Comment by fitz-97** [comment]
We have the same problem，but SP-API will not change

**Comment by chapmanjw** [comment]
One option you can explore to provide "Amazon hosted" content that is backed by your own origin servers / CDNs, you can create a CloudFront Distribution in your AWS account with a custom remote origin: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html#concept_CustomOrigin. This effectively creates a CDN/cache in your AWS account that falls back to your servers / CDNs and then caches that data. The AWS Free Tier covers most or all of the throughput that would be needed for most sellers: https://aws.amazon.com/cloudfront/pricing/.

The benefits to this approach for developers is that it meets the requirements for "Amazon hosted" content, provides a cache in-front of your remote server URLs (reducing how much Amazon needs to read from your remote server when processing the same URLs on multiple submissions or across different SKUs), reduces the error rates related to image downloads, and reduces the overall latency for processing your image submissions.
