### ISSUE TITLE
createFeed() operation returns "Invalid Input - One or more required parameters missing"

### ISSUE THREAD

**Issue by albinsopaj** [amzn/selling-partner-api-docs#3468]
Hello, there. I'm trying to call the createFeed() operation of Amazon SP Feeds API however I'm getting the following error:

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "marketplaceIds;feedType;inputFeedDocumentId;"
    }
  ]
}
```

Here is a screenshot of my Postman Post request.

![image](https://github.com/amzn/selling-partner-api-docs/assets/62503305/2a8c78b5-c5d0-48f8-9659-02d26bb83cae)

I tried uploading the feed document as JSON raw body, and it gave me a 200 OK status code.

My application is in draft mode.

I am really stuck and have no clue on how to move forward. Any help from anyone is highly appreciated. 

Thanks in advance.

**Comment by stefnats** [comment]
Did you try to add the `feedOptions` parameter? Even if it's just empty or null.

**Comment by albinsopaj** [comment]
> Did you try to add the `feedOptions` parameter? Even if it's just empty or null. Also, i think the `marketplaceIds` must be an array.

I am no longer having issues with createFeed() operation. It's working fine. However, I'm still stuck at the upload feed document step. I don't know if I must encrypt the file in advance before uploading it, and if so, how should I do it? Thanks in advance.

**Comment by stefnats** [comment]
No, you don't need to encrypt it. That was the old feeds api (the first one that they released in sp api).
You need to send a PUT request to the url that CreateFeedDocument gives you with the contents of the file as request body. Also make sure to specify the correct content-type. Hope that helps!

**Comment by albinsopaj** [comment]
> No, you don't need to encrypt it. That was the old feeds api (the first one that they released in sp api). You need to send a PUT request to the url that CreateFeedDocument gives you with the contents of the file as request body. Also make sure to specify the correct content-type. Hope that helps!

This is what I've come up so far.

    // Step 1. Create Feed Document

    $response = Drupal::httpClient()->post('https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/documents', [
      'headers' => [
        'x-amz-access-token' => $access_token,
      ],
      'json' => [
        "contentType" => "text/tab-separated-values; charset=UTF-8",
      ]
    ])->getBody();

    $feedDocumentData = json_decode($response, TRUE);
    $feedDocumentId = $feedDocumentData['feedDocumentId'];
    $feedDocumentUrl = $feedDocumentData['url'];

    // Step 2. Upload Flat File

    $response = Drupal::httpClient()->put($feedDocumentUrl, [
      'headers' => [
        'Content-Type' => 'text/tab-separated-values; charset=UTF-8',
      ],
      'json' => $file,
    ])->getBody();

    Drupal::messenger()->addMessage(t("Success"));
    
    // Step 3. Create Feed
    
    $feedResponse = Drupal::httpClient()->post('https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/feeds', [
      'headers' => [
        'x-amz-access-token' => $access_token,
      ],
      'json' => [
        "feedType" => "POST_FLAT_FILE_INVLOADER_DATA",
        "marketplaceIds" => [
          "APJ6JRA9NG5V4"
        ],
        "inputFeedDocumentId" => $feedDocumentId,
      ]
    ])->getBody();

    $feedData = json_decode($feedResponse, TRUE);

I'm not sure if the second step is correct. Whenever I execute the second method, when I download the Feed Processing Report I receive `a 90012	Fatal	The required sku field is missing from the file. To correct this error, download the template again and use the new copy, or insert the required field into your existing file`. But if I upload the same file using Add Products via Upload on Amazon Seller Central, the same file passes without errors. I really don't know what's going on.

What do you think? Could I've done something wrong? 

Thanks in advance. Albin

**Comment by stefnats** [comment]
a few thoughts on this

1. you should replace `text/tab-separated-values` with the contentType that you have from step 1 (createFeedDocument)
2. you should consider using JSON_LISTINGS_FEED or even better using the Listings Items API (if you don't need thousands of changes at a time) - if i'm correct that you create/update/delete listings items (SKU). In case that you try to modify ASIN related data (catalog items) then the Listings Items API wouldn't be the correct choice.

let me know if this helps, i had some issues with the contentType myself when i implemented this.

**Comment by stefnats** [comment]
oh and you might want to use a library instead making raw requests yourself. i found that [`jlevers/selling-partner-api`](https://github.com/jlevers/selling-partner-api) does a pretty good job here for PHP.

**Comment by albinsopaj** [comment]
I solved it. Anyway, thanks a lot for helping.
