### ISSUE TITLE
[BUG] [SP-API] Unable to change handling time 

### ISSUE THREAD

**Issue by umairge66** [amzn/selling-partner-api-docs#3476]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Unable to update handling time using patch operation [patchListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku)
## SP-API Name and Version or Report/Feed Type
patchListingsItem v2021-08-01

## Expected Behavior

When I submit this it should give me success response but it's giving error and It's hard to understand the problem
<pre>
{
    "productType": "PRODUCT",
    "patches": [
        {
            "op": "replace",
            "path": "/attributes/fulfillment_availability",
            "value": [
                {
                    "fulfillment_channel_code": "DEFAULT",
                    "lead_time_to_ship_max_days": 4
                }
            ]
        }
    ]
}
</pre>
Also have tried this
<pre>
{
    "productType": "PRODUCT",
    "patches": [
        {
            "op": "replace",
            "path": "/attributes/fulfillment_availability",
            "value": [
                {
                    "fulfillment_availability": [
                        {
                            "fulfillment_channel_code": "DEFAULT",
                            "lead_time_to_ship_max_days": 4
                        }
                    ]
                }
            ]
        }
    ]
}
</pre>
## Current Behavior

1st one giving this error
<pre>
{
    "sku": "1989605230",
    "status": "INVALID",
    "submissionId": "ee84f9ca89dd4615a26a5d68d580c980",
    "issues": [
        {
            "code": "90248",
            "message": "Based on the data from '[fulfillment_channel_availability#?.inventory#?.inventory_type]', the field '\"lead_time_to_ship\"' for the attribute 'fulfillment_availability' is not allowed. Expected at most '0' of field '\"lead_time_to_ship\"' for attribute 'fulfillment_availability'.",
            "severity": "ERROR",
            "attributeNames": [
                "fulfillment_availability"
            ]
        }
    ]
}
</pre>
and 2nd one giving this error

<pre>
{
    "sku": "1989605230",
    "status": "INVALID",
    "submissionId": "0f8982ec15594ea6ae0043c844ed79a9",
    "issues": [
        {
            "code": "99022",
            "message": "The field 'fulfillment_channel_code' for the attribute 'fulfillment_availability' does not have enough values. The required minimum is '1' value(s).",
            "severity": "ERROR",
            "attributeNames": [
                "fulfillment_availability"
            ]
        }
    ]
}
</pre>
## Context/Screenshots

My Input
![image](https://github.com/amzn/selling-partner-api-docs/assets/119076244/7896def4-74a3-4cf9-842a-a4a31994b1b5)
The output I am receivng 
![image](https://github.com/amzn/selling-partner-api-docs/assets/119076244/52c16f1b-09f3-4be1-9db2-6045cbaaa28d)

## Your Environment

I am testing it in postman everything is configured correctly

**Comment by stefnats** [comment]
Hey,
i'm doing it like this and it seems to work:

```
{
    "productType": "PRODUCT",
    "patches": [
        {
            "op": "replace",
            "path": "/attributes/fulfillment_availability",
            "value": [
                {
                    "fulfillment_availability": [
                        {
                            "marketplace_id": "ABCDE",
                            "fulfillment_channel_code": "DEFAULT",
                            "lead_time_to_ship_max_days": 4,
                            "quantity": 543
                        }
                    ]
                }
            ]
        }
    ]
}
```

I think you must deliver `marketplace_id` and `quantity` along with it.

Also, i think it's best to validate the JSON against json schema client-side (you can get the schema from product type definitions api) 

Hope that helps!

**Comment by umairge66** [comment]
Thanks it's worked like a charm
