### ISSUE TITLE
InvalidInput error on getting RDT token for Vendor central

### ISSUE THREAD

**Issue by summanbahadurVolo** [amzn/selling-partner-api-docs#3488]
Can any one guide me what i am doing wrong:
I want to get RDT token for :
{ "restrictedResources":
    [
        { "method": "GET" , "path": "/vendor/directFulfillment/orders/v1/purchaseOrders"}
    ]
 }

it gives me
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Application do not have access to some or all requested resource",
            "details": ""
        }
    ]
}

I have role Direct to Consumer Shipping (Restricted) role on my account.
Also, i can get RDT token generated correctly for other SPAPI paths like : /orders/v0/orders/{orderId}
tried regenerating refresh token . Kindly suggest what could be wrong.

**Comment by chrisskhoury** [comment]
Hello @summanbahadurVolo ,

Do you have Vendor checked in your Business entities supported for you App Registration page? This option helps you choose the Amazon Partners your application supports. 

Also did you try calling the /vendor/directFulfillment/orders/v1/purchaseOrders endpoint without an RDT? Using a normal access token instead?

Best,
Christopher El Khoury
Solution Architect, Amazon SP API

**Comment by summanbahadurVolo** [comment]
Hi Thanks for your response, But i was using wrong access token. The access token i was using to generate RDT was for seller center. 
For vendor center we needed to re-authorise and then generate a new refresh token separate for Vendor central.
