### ISSUE TITLE
GET_MERCHANT_LISTINGS_ALL_DATA report is using chartset:CP1252 and converting to charset=UTF-8 getting incorrect characters

### ISSUE THREAD

**Issue by maaguilera** [amzn/selling-partner-api-docs#3495]
We are using SP-API. 
When we download the content of the GET_MERCHANT_LISTINGS_ALL_DATA  report document
**The encoding no header is -->  Content-Type: text/plain; charset=Cp1252.** 

We try to convert it to UTF-8，but the document content always show me the Incorrect character.

For example:
Pi?a when the correct is Piña or Est?n when the correct is Están.

This problem does not appear when for GET_FLAT_FILE VAT INVOICE DATA_REPORT reports.
**The encoding no header is -->   Content-Type: text/plain; charset=UTF-8**

why the  GET_MERCHANT_LISTINGS_ALL_DATA report is using CP-1252 and not is using UTF-8?
This behavior is causing many characters to not be converted correctly.
Any solution to obtain the content of the listing correctly?

code used:
var wc = new System.Net.WebClient();
byte[]  cipherText = wc.DownloadData(Url);

string plaintext = null;
using (System.Security.Cryptography.Aes aesAlg = System.Security.Cryptography.Aes.Create())
            {
                aesAlg.Key = Convert.FromBase64String(key);
                aesAlg.IV = Convert.FromBase64String(initializationVector);
                System.Security.Cryptography.ICryptoTransform decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV);
                using (MemoryStream msDecrypt = new MemoryStream(cipherText))
                {
                    using (System.Security.Cryptography.CryptoStream csDecrypt = new System.Security.Cryptography.CryptoStream(msDecrypt, decryptor, System.Security.Cryptography.CryptoStreamMode.Read))
                    {
                     using (
                        StreamReader srDecrypt = new StreamReader(csDecrypt, new System.Text.UTF8Encoding(false)))
                        {
                            if (compressionAlgorithm != null)
                            {
                                plaintext = Decompress_2(csDecrypt,  new System.Text.UTF8Encoding(false));          

                            }
                            else
                            {
                                plaintext = srDecrypt.ReadToEnd();
                               
                            }
                        }
                    }
                }
            }
            return plaintext;

**Comment by stefnats** [comment]
i'm not that deep into C# right now, but this seems like a rendering bug and not with the API.

Couldn't you try to parse the file as it was delivered with the Content-Type header like using the `StreamReader` with the correct encoding?

**Comment by maaguilera** [comment]
thank @stefnats, it worked
