### ISSUE TITLE
Seller Partner Account info endpoint

### ISSUE THREAD

**Issue by brenjt** [amzn/selling-partner-api-docs#350]
I cannot find any endpoints in the docs in order to pull basic account info like the seller partner name. Does such an endpoint exist?

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

We offer a Sellers API which getMarketplaceParticipations operation used to return a list of marketplaces that the seller submitting the request can sell in and information about the seller's participation in those marketplaces.

https://github.com/amzn/selling-partner-api-docs/blob/main/references/sellers-api/sellers.md

**Comment by brenjt** [comment]
Unfortunately that only gives the list of marketplaces and the marketplace names. I am trying to find the name of the store that is selling in those market places.

**Comment by tspicer** [comment]
Having when the seller became active would be useful as well. It is impossible to make historical API calls for data when you have no way to programmatically determine a starting point.

**Comment by grtreexyz** [comment]
I also want to know how to get the seller store display name
or seller account infomation

**Comment by grtreexyz** [comment]
I also want to know how to get the seller store display name
or seller account infomation

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
