### ISSUE TITLE
[BUG] [SP-API] [Issue] GET_V2_SELLER_PERFORMANCE_REPORT still IN_QUEUE

### ISSUE THREAD

**Issue by julioyildo** [amzn/selling-partner-api-docs#3502]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Expected Behavior: Feed processing should complete with DONE or Fatal

## Current Behavior

Hello I'm trying to retrieve GET_V2_SELLER_PERFORMANCE_REPORT report, I can retrieve the data for EU but not for NA; report for NA are still IN_QUEUE. 

## Context/Screenshots

![Capture d’écran 2023-12-18 à 11 25 26](https://github.com/amzn/selling-partner-api-docs/assets/17247165/a0eb868a-b0e8-410b-a5d6-fb350ffaf3c9)

**Comment by stefnats** [comment]
without knowing all the details, but if something is IN_QUEUE it can be a hint on something else still processing. Can you check if there are other Reports still IN_PROGRESS?

**Comment by julioyildo** [comment]
Thank you @stefnats for your return. 
As you said, something else was still being processed in parallel, which blocked my call.

This ticket is now resolved. 

Thanks.
