### ISSUE TITLE
How to use getListingOffersBatch function in Amazon SP API

### ISSUE THREAD

**Issue by mtkumar82** [amzn/selling-partner-api-docs#3506]
I am facing issue to use getListingOffersBatch API to get response for all getLowestPricedOffersForSKU's using Amazon SP API, Actually this function required below paramenters

public function getListingOffersBatch(AccessToken $accessToken, string $region, \AmazonPHP\SellingPartner\Model\ProductPricing\GetListingOffersBatchRequest $get_listing_offers_batch_request_body) : \AmazonPHP\SellingPartner\Model\ProductPricing\GetListingOffersBatchResponse;

I am not sure how to pass \AmazonPHP\SellingPartner\Model\ProductPricing\GetListingOffersBatchRequest $get_listing_offers_batch_request_body this parameters there , Anybody please help me to use the batch offer API in php code.

**Comment by stefnats** [comment]
Seems like you are using https://github.com/amazon-php/sp-api-sdk
I think most of the people here are not familiar with it, so you should ask there.

**Comment by mtkumar82** [comment]
Yes @stefnats , But I found the way to use it, Writing it below, how it may help someone.

For getBatch offers by SKU:-
