### ISSUE TITLE
Usage Plans and Rate Limits in the Selling Partner API are shared between applications?

### ISSUE THREAD

**Issue by intellifox-hq** [amzn/selling-partner-api-docs#351]
Hi,

We respect the throttle limits in our code, waiting 1 seconds between each calls to `/finances/v0/orders/${order_id}/financialEvents` for each of our users.

- For most of our users, it works perfectly. We are the only ones using the resource, respecting the limits. We are able to reach 1.05 seconds per call as you could expect.

- However, for some users, they fail **very often**. Around one request out of ten is returned successfully.

All of these users told us they have allowed other applications through MWS/SP-API with similar capabilities.

Given we took every precaution to avoid throttle and are still being throttled only for these users, **our theory is that the rate limits are shared between competing applications**.

Questions:
- Have others witnessed this behavior?
- What strategies should we use to be able to get this information through the API even if a competitor is depleting this resource?

**Comment by johnkw** [comment]
The documentation at https://github.com/amzn/selling-partner-api-docs/blob/main/guides/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md implies yes, this can be per-account throttled. I don't think we've ever seen the "x-amzn-RateLimit-Limit" header - perhaps they're hammering the API enough to have been assigned that. It would be interesting to know how common that is.

**Comment by intellifox-hq** [comment]
Wow we were WRONG. The waiting necessary for this specific route is 2 secs with authorized burst of 30! We thought it was 1/1. Our bad...

_leaving the scene with the crowd launching tomatoes at us_
