### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by leoliang92** [amzn/selling-partner-api-docs#354]
We have decided to implement our own solution to call SP-API. After going through all the documentation and cases we could find for the past three days, we still cannot get a successful response back. We have set up everything it should be and tested with Postman without any issue, but we just simply cannot get it working in our code. Here is the error we got:

```
[
  {
    message: 'Access to requested resource is denied.',
    code: 'Unauthorized',
    details: ''
  }
]
```

**Code we wrote:**
```
const fetch = require('node-fetch')
const aws4 = require('aws4')
const AWS = require('aws-sdk');
const sts = new AWS.STS({apiVersion: '2011-06-15', accessKeyId: 'AKIAZ......', secretAccessKey: '1vNyD1ggSw....', region: 'us-east-1'})
const https = require('https')

module.exports = async (req, res) => {
    
    // build fetch options for fetching access token 
    let fetchOptions = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: new URLSearchParams({
            'grant_type': 'refresh_token',
            'refresh_token': 'Atzr|IwGDFGSDFGr.....',
            'client_id': 'amzn1.application-oa2-client.80....',
            'client_secret': 'c98554551....'
        })
      };

    // get access token
    let fetchResponse = await fetch('https://api.amazon.com/auth/o2/token', fetchOptions).then(res => res.json())

    // call STS assume role
    let role = await sts.assumeRole({
        RoleArn: 'arn:aws:iam::631022162040:role/SellingPartnerAPI',
        RoleSessionName: 'sp-api'
    }).promise()

    // sign the request using token and credentials from previous steps
    let signedRequest = aws4.sign({
        host: 'sellingpartnerapi-na.amazon.com',
        path: '/vendors/orders/v1/purchaseOrders?createdAfter=2021-01-12',
        method: 'GET',
        service: 'execute-api',
        region: 'us-east-1',
        headers: {
            'user-agent': 'mlabs/0.1 (Language=JavaScript; Platform=Node)',
            'x-amz-access-token': fetchResponse.access_token
        }
    }, {
        accessKeyId: role.Credentials.AccessKeyId, 
        secretAccessKey: role.Credentials.SecretAccessKey, 
        sessionToken: role.Credentials.SessionToken
    })

    let response = await getAPIResponse(signedRequest)

    res.end(response)
}

// make API call using https
async function getAPIResponse(signedRequest) {
    return new Promise((resolve, reject) => {
        https.request(signedRequest, (res) => {
          let data = '';
          const {statusCode} = res;
  
          res.on('data', chunk => (data += chunk));
          res.on('end', async() => {
            const res = data && JSON.parse(data);
  
            if (statusCode === 200) {
              resolve(res);
            } else {
                console.log(res.errors)
              reject({statusCode, res});
            }
          });
        }).end();
      });
}
```

Oddly enough, if we pasted the accessToken, accessKeyId, secretAccessKey, and sessionToken into Postman, we get a successful response back. Any help will be appreciated! We really need to get this working....Thank you!!

**Comment by rogersv** [comment]
I have not used the nodes library but I have checked the code and it looks like the aws4.sign function prepares the request wit the auth and signature but it does not add the headers for the tokens.

**Comment by leoliang92** [comment]
Hi @rogersv ! Thank you for the quick response. Could you explain that more? I think we do have the headers for the token as follows. It seems aws4 library is going to add those headers automatically.
```
headers: {
      'user-agent': 'mlabs/0.1 (Language=JavaScript; Platform=Node)',
      'x-amz-access-token': fetchResponse.access_token
  }
```
fetchReponse is the response we got from previous step to fetch the token, and its response is like this:
```
{
    "access_token": "Atza|IwE......",
    "refresh_token": "Atzr|IwE....",
    "token_type": "bearer",
    "expires_in": 3600
}
```

We followed the code example from the following post
#24 
 https://vdanyliv.medium.com/amazon-selling-partner-api-spapi-how-to-quickly-and-simply-integrate-with-new-api-part-2-59d7458f24fe
https://github.com/mhart/aws4/issues/68
https://github.com/mhart/aws4/issues/113#issuecomment-639291510

**Comment by rogersv** [comment]
I think you forgot to add the x-amz-security-token in the header (value from the role request)

**Comment by leoliang92** [comment]
@rogersv 
Ok I did not think that was required based on the posts that I referred to. Here is the response from role request:

```
{
  ResponseMetadata: { RequestId: 'a884066.....' },
  Credentials: {
    AccessKeyId: 'ASIAZF2.....',
    SecretAccessKey: 'Pey/nLVCU.......',
    SessionToken: 'FwoGZXIvYXdzEKf//////////wEaDKa.....',
    Expiration: 2021-01-29T22:48:26.000Z
  },
  AssumedRoleUser: {
    AssumedRoleId: 'AROAZ....i',
    Arn: 'arn:aws:sts::631.....'
  }
}
```

Do I use the session token from the response of the role request as the x-amz-security-token and place it in the headers like so?
```
 // sign the request using token and credentials from previous steps
    let signedRequest = aws4.sign({
        host: 'sellingpartnerapi-na.amazon.com',
        path: '/vendors/orders/v1/purchaseOrders?createdAfter=2021-01-12',
        method: 'GET',
        service: 'execute-api',
        region: 'us-east-1',
        headers: {
            'user-agent': 'mlabs/0.1 (Language=JavaScript; Platform=Node)',
            'x-amz-access-token': fetchResponse.access_token,
            'X-Amz-Security-Token': role.Credentials.SessionToken
        }
    }, {
        accessKeyId: role.Credentials.AccessKeyId, 
        secretAccessKey: role.Credentials.SecretAccessKey, 
        sessionToken: role.Credentials.SessionToken
    })
```
We still got the same error message: Access to requested resource is denied. I also tried using lower case 'x-amz-security-token,' but same result. Aslo, this is a sample response from aws4.sign

```
{
  host: 'sellingpartnerapi-na.amazon.com',
  path: '/vendors/orders/v1/purchaseOrders?createdAfter=2021-01-12',
  method: 'GET',
  service: 'execute-api',
  region: 'us-east-1',
  headers: {
    'user-agent': 'mlabs/0.1 (Language=JavaScript; Platform=Node)',
    'x-amz-access-token': 'Atza|IwEBIGvN9.....',
    'x-amz-security-token': 'FwoGZXIvYXdzEKf//////////wEaDKeXHIi....',
    Host: 'sellingpartnerapi-na.amazon.com',
    'X-Amz-Date': '20210129T215302Z',
    Authorization: 'AWS4-HMAC-SHA256 Credential=ASIAZF262..../20210129/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=535bf6694cf197883fe.....'
  }
}
```

**Comment by rogersv** [comment]
It looks correct. Maybe it is related to https://github.com/amzn/selling-partner-api-docs/issues/196. Is your app registered in an US account?

**Comment by leoliang92** [comment]
Yes, it is registered in an US account. We can get response back using Postman without issues. Any other suggestions?

**Comment by AlexFacile** [comment]
Hi i have the same issue, with very similar code, the request is signed correctly and have all the necessary paramenters, but still i have the same error response: 
```
errors: [
    {
      message: 'Access to requested resource is denied.',
      code: 'Unauthorized',
      details: ''
    }
  ]
```

@leoliang92 have you managed to solve? Thanks!

**Comment by leoliang92** [comment]
Hi @AlexFacile I did manage to solve the issue. Are you using aws4 package? If so, you should consider wrting your own signing method. I believe there are some errors on its signing method, but the developer of aws4 did not seem to find any issue. After switching to my own signing method, everything works great and no issue. Let me know if you need more info on how to write the singing method.

**Comment by AlexFacile** [comment]
Thanks for the reply, yes i'm using aws4 package and i've tried everything i can without success, so the solution it's to write my own sign method, i really appreciate if you can provide me some info / resource about that!

**Comment by leoliang92** [comment]
@AlexFacile Sorry I did not get back to you yesterday. So I found a different node package called amazon-sp-api, but it did not work for me either. However, I referenced its Signer class which helped me to write my own signing method. Here is the link to its github repository: https://github.com/amz-tools/amazon-sp-api

**Comment by AlexFacile** [comment]
Hi @leoliang92 Thank you again, yesterday i managed to wrote my own method but still have "Access to requested resource is denied." This is my signed Request and some information: 
```
{
  method: 'POST',
  host: 'sellingpartnerapi-eu.amazon.com',
  path: '/mfn/v0/eligibleShippingServices',
  headers: {
    Authorization: 'AWS4-HMAC-SHA256 Credential=ASIAWYXXXXXXXXXX/20210319/eu-west-1/execute-api/aws4_request,SignedHeaders=host;x-amz-date;x-amz-access-token;x-amz-security-token,Signature=e23176f3c79172c8b8df3303f039a835f56d1d80ffe19ce0818bd343ddd78193',
    Host: 'sellingpartnerapi-eu.amazon.com',
    'x-amz-date': '20210319T114856Z',
    'x-amz-access-token': 'Atza|IwEBICajrSfFEF3EZKkHQvJXXXXXXXXX',
    'x-amz-security-token': 'FwoGZXIvYXdzEDUaDEVP8k7R4YB2yARkeiKqAQuAtg53x6gX0fIoa+ODwhfVXXXXXX',
    'Content-Type': 'application/json; charset=utf-8'
  },
  body: data //(Json)
}
```
Info:
- I'm trying to use the merchant api
- If i do other request such as ordersV0 api with my custom sign it work
- I've tryed also many package and solution out there, same problem, in the end i wrote all from scratch

You see something that is wrong? Thanks. I've checked the policy/Role and User... i can't figure out where the problem is

**Comment by leoliang92** [comment]
Hi @AlexFacile ,

Sorry I have not gotten back to you. Have you resolved the issue? What library you are using to make the request? I am currently using request library. At first, I tried to use node fetch, but it failed with that error. Also, I think I read somewhere saying eu endpoint is having issues with selling partner api.

**Comment by AlexFacile** [comment]
Hello again @leoliang92, "eu endpoint is having issues with selling partner api." yes i've read it too, and i've also opened a support case in the amazon seller central support... i still have the issue, i've used axios and request library (actualy in use for a while) but nothing to do.

What i've done is:

- Configuring User/Policy/Role
- Registred new App in amazon seller (with Role IAM)
- Call the "auth/o2/token"
- Create temporary AWS Credentials (AccessKeyId, Secret, SessionToken)
- Configure the request i need
- Sign V4 (tried with some npm package like aws4 and amazon-sp-api and also custom signature)
- Execute the request with the error message "Access Denied"

What module i need to use:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md

i will also wait the response from seller central.
Thank you.

**Comment by leoliang92** [comment]
@AlexFacile , that's really odd....Have you tried to make the call using Postman and get a valid response back? If you can get data back from Postman, it means there is something wrong with your code.

**Comment by AlexFacile** [comment]
@leoliang92  sorry for the late response, seller central hasn't answered me yet, this is my try with Postman... 

![Schermata 2021-03-26 alle 12 56 29](https://user-images.githubusercontent.com/80537702/112629042-119ede80-8e34-11eb-9396-109c7836c610.png)
![Schermata 2021-03-26 alle 12 57 17](https://user-images.githubusercontent.com/80537702/112629078-1e233700-8e34-11eb-8e32-9d1ec6350dff.png)
![Schermata 2021-03-26 alle 12 57 43](https://user-images.githubusercontent.com/80537702/112629096-22e7eb00-8e34-11eb-810c-602f56bd2d73.png)

thanks as always for the help.

**Comment by leoliang92** [comment]
@AlexFacile Are you building the application for Seller Central or Vendor Central? They have different endpoint. If it is vendor central your url will look like this: https://sellingpartnerapi-na.amazon.com/vendor/orders/v1/purchaseOrders?purchaseOrderState=New

Also, is your marketplaceId correct?

This is the list of marketplaceId:
```
Country | marketplaceId | Country code
Spain | A1RKKUPIHCS9HS | ES
United Kingdom | A1F83G8C2ARO7P | GB
France | A13V1IB3VIYZZH | FR
Netherlands | A1805IZSGTT6HS | NL
Germany | A1PA6795UKMFR9 | DE
Italy | APJ6JRA9NG5V4 | IT
Sweden | A2NODRKZP88ZB9 | SE
Turkey | A33AVAJ2PDY3EV | TR
United Arab Emirates | A2VIGQ35RCS4UG | AE
India | A21TJRUUN4KGV | IN
```

**Comment by AlexFacile** [comment]
@leoliang92 I'm building the application for Seller Central, the modules of the api I refer are [`these`](https://github.com/amzn/selling-partner-api-docs/tree/main/references)

I've also got it the marketplace ID from the official Github page --->

![Schermata 2021-03-26 alle 15 00 27](https://user-images.githubusercontent.com/80537702/112642905-0e135380-8e44-11eb-9be3-6b0a4f4a9b87.png)

**Comment by leoliang92** [comment]
@AlexFacile Ok, so my guess is your code actually works. Before I even started coding, I was able to get the response back from Postman. It seems you do not have access to the endpoint.
![Screen Shot 2021-03-26 at 11 45 32 AM](https://user-images.githubusercontent.com/65548379/112673313-912bae00-8e32-11eb-9b92-f63c4cb4823f.png)

**Comment by AlexFacile** [comment]
@leoliang92 Sorry for late response, You mean i have some problem with policy/Role/User? because i double checked and seems that i have done all the steps of the official guide, also i'm using the same endpoint and region as explained in the guide 🤔

**Comment by rugved1991** [comment]
Hi @AlexFacile,

Can you please remove the "x-amz-security-token" from the request? You need to add the session token in the Authorization tab of Postman under "AWS Signature". The session token will be used to calculate the AWS SigV4 signature and added automatically to the Authorization header by Postman client.
Please make sure your application has the correct roles associated with it to call the APIs. For MFN, you would need "Direct-To-Consumer Shipping" role and for Orders, you would need "Inventory and Order Management" role.

@leoliang92 are you still facing any issues while calling the Vendor APIs? I saw that you are able to call the API successfully using Postman.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by Dakror** [comment]
I'm experiencing the same 403 issue using the same library for the MFN endpoint of getEligibleShipmentServices.

Our application has the correct role & auth setup, i can perform queries on the Orders API just fine.

**Comment by iamsr** [comment]
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}

still the same error. Is this issue resloved?

**Comment by premium-json** [comment]
I also have same problem. I'm getting true result through Postman but when i am trying to get the same result by my code, getting such error.



{
  "errors": [
    {
      "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/sellers/v1/marketplaceParticipations

accept:application/json
host:sellingpartnerapi-eu.amazon.com
x-amz-access-token:Atza|IwEBIEkM_DCalvjr7XXXXXXXXX
x-amz-date:20221212T102732Z

accept;host;x-amz-access-token;x-amz-date
e3b0c44XXXXXXXX'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20221212T102732Z
20221212/eu-west-1/execute-api/aws4_request
fe8aa3da93a6XXXXXXXX'
",
     "code": "InvalidSignature"
    }
  ]
}


`                string strAccessKey = txtAwsAccessKeyID.Text;
                string strSecretKey = txtAwsSecretKey.Text;
                DateTime dt;
                dt = DateTime.UtcNow;
                string amzdate = DateTime.UtcNow.ToString("yyyyMMddTHHmmss") + "Z";
                string strDate = DateTime.UtcNow.ToString("yyyyMMdd");
                string strService = txtAmzAPIEndpoint.Text;
                string strRegion = txtAmzRegionID.Text;
                string RegionID = txtAmzRegionID.Text;
                string MarketPlaceId = txtAmzMarketPlaceID.Text;
                string strContentType = "application/json";
                string host = "sellingpartnerapi-eu.amazon.com";
                string ReqType = "aws4_request";

                var lstScope = new List<string>();
                lstScope.Add(strDate);
                lstScope.Add(strRegion);
                lstScope.Add(strService);
                lstScope.Add(ReqType);

                var lstStringToSign = new List<string>();
                lstStringToSign.Add("AWS4-HMAC-SHA256");
                lstStringToSign.Add(amzdate);
                lstStringToSign.Add(String.Join("/", lstScope.ToArray()));

                string strStringToSign = String.Join("\n", lstStringToSign.ToArray());
                
                byte[] byteSigningKey = getSignatureKey(strAccessKey, strDate, strRegion, strService, ReqType);
                byte[] byteSignature = HmacSHA256(strStringToSign, byteSigningKey);

                string strAuthorization = "AWS4-HMAC-SHA256 " + "Credential=" + strAccessKey + "/" + strDate + "/" + strRegion + "/" + strService + "/" + ReqType +", SignedHeaders=accept;host;x-amz-access-token;x-amz-date, Signature=" + ToHex(byteSignature);
                //var TokenClient = new RestClient("https://sellingpartnerapi-eu.amazon.com/fba/inventory/v1/summaries?details=false&granularityType=Marketplace&granularityId=A33AVAJ2PDY3EV&startDateTime=&sellerSkus=&nextToken=&marketplaceIds=A33AVAJ2PDY3EV");
                var TokenClient = new RestClient("https://sellingpartnerapi-eu.amazon.com/sellers/v1/marketplaceParticipations");
                var TokenRequest = new RestRequest("", Method.Get);
                TokenRequest.RequestFormat = DataFormat.Json;
                TokenRequest.AddHeader("accept", strContentType);
                TokenRequest.AddHeader("host", host);
                TokenRequest.AddHeader("x-amz-access-token", txtAmzAccessToken.Text);
                TokenRequest.AddHeader("x-amz-date", amzdate);
                TokenRequest.AddHeader("Authorization", strAuthorization);
                RestResponse TokenResponse = TokenClient.Execute(TokenRequest);
                string TokenJson = TokenResponse.Content;
                //AmzRoot TokenSonuc = JsonConvert.DeserializeObject<AmzRoot>(TokenJson);
                txtSonuc.Text += TokenJson;


            }
            catch { }
        }
        string ToHex(byte[] array)
        {
            string strOutput = "";
            for (int i = 0; i < array.Length; i++)
            {
                strOutput += $"{array[i]:x2}";
            }
            return strOutput;
        }
        byte[] HmacSHA256(String data, byte[] key)
        {
            return new HMACSHA256(key).ComputeHash(ToBytes(data));
        }
        byte[] getSignatureKey(String key, String dateStamp, String regionName, String serviceName, String ReqType)
        {
            byte[] kDate = HmacSHA256(dateStamp, ToBytes("AWS4" + key));
            byte[] kRegion = HmacSHA256(regionName, kDate);
            byte[] kService = HmacSHA256(serviceName, kRegion);
            byte[] kSigning = HmacSHA256(ReqType, kService);

            return kSigning;
        }
        
        private static byte[] ToBytes(string str)
        {
            return Encoding.UTF8.GetBytes(str.ToCharArray());
        }

`
                
                
Could somebody help for the issue?
