### ISSUE TITLE
[BUG] [SP-API] [Issue] Same respond for every  PUT

### ISSUE THREAD

**Issue by Tharfernando** [amzn/selling-partner-api-docs#3544]
i m using sandbox to make listing requests for every listing i m getting the same respond .Is that it 

{
  "sku": "GM-ZDPI-9B4E",
  "status": "ACCEPTED",
  "submissionId": "f1dc2914-75dd-11ea-bc55-0242ac130003",
  "issues": []
}

**Comment by leonardonakagawa** [comment]
Hello @Tharfernando,

Thank you for reaching out regarding Sandbox environment.

Amazon has two sandbox environments. Dynamic and Static.

The Sandbox static endpoints, returns mocked responses for all Selling Partner APIs. For the PUT listingsItem API only the Static API is available.

The Selling Partner API dynamic sandbox routes requests to a sandbox backend that can return realistic responses based on the request parameters. You will find which are the dynamic sandbox environments looking in this link [How to make a dynamic sandbox call to the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox#how-to-make-a-dynamic-sandbox-call-to-the-selling-partner-api).


You can find details regarding this in our [The Selling Partner API static sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox).


If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by Tharfernando** [comment]
@leonardonakagawa 
hello 
i m getting the issue on production 

![image](https://github.com/amzn/selling-partner-api-docs/assets/154667624/ac5eb0ec-0d2c-4a99-b266-53f74e438acf)

does you have a generic json playload
