### ISSUE TITLE
[RANT] [SP-API] [Issue] Worst API design by far!

### ISSUE THREAD

**Issue by nooblyf** [amzn/selling-partner-api-docs#3547]
## I'm submitting a Rant

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe: Y'all need to rewrite this whole fucking thing
</code></pre>

## SP-API Name and Version or Report/Feed Type
All of them

## Expected Behavior

I shouldn't be losing my sanity working with this dogshite API (docs are just the cherry on top!) ☺️

## Current Behavior

Checkout Google APIs maybe you guys will learn a thing or two on how to build APIs instead of grinding leetcode all day

## Context/Screenshots

- Docs are cluttered, i have to make 5-10 meaningless clicks just to find a single metric definition
- Different rate & burst limits for each endpoint and they can be dynamic too great!!
- I have to provide what region the seller belongs to and use that URL domain accordingly?? i don't have a clue on why this should be a thing for us to handle
- Also have to provide what marketplace the seller sells to?? now i have to make unnecessary api request every time to check for this (i can't store it my side because it can change), filtering on this i would understand but making this a required param when this should be handled on amazon's side??
- No response structure info on reports API, endpoints spit out `xml`, `tsv` or `json` data, no consistency whatsoever 🥴
- Reports API fail with 'Invalid input' or just 'FATAL' status many times and i have to scrape the internet/docs to figure it out.
- Search is pretty much useless most of the time, you guys just added a basic text search which doesn't even have depth and called it a day huh??

## Your Environment

Doesn't matter

**Comment by rodrifed** [comment]
Hi @nooblyf,

Thank you for your feedback.

It is unfortunate that the API doesn't meet your expectations.
If you have concrete errors to report, I would kindly ask you to open a [Developer Support case](https://developer.amazonservices.com/support) and provide request id and timestamp, so our support team can investigate and help you overcome those.
For the general feedback that you've shared, we've taken note and will consider it going forward.

Thank you,
Federico
Selling Partner Developer Services

**Comment by nooblyf** [comment]
.

**Comment by nooblyf** [comment]
aaaaaaaa
