### ISSUE TITLE
API for Get buyer all messages & get positive feedback

### ISSUE THREAD

**Issue by surbhi-ctas** [amzn/selling-partner-api-docs#3559]
I'm looking for a way to get and reply to all buyer messages through SP API. I found it in the document, but I didn't get it.

Is there any API to get all buyer messages that we can see in "Buyer messages" section of Amazon Seller Central as well as API to reply to buyer messages via SP API.

Is there a way to get positive seller feedback using an API or a report? From Performance Report Type, we get negative and neutral feedback from 'GET_SELLER_FEEDBACK_DATA'. 

If you could help me resolve my two questions, I would greatly appreciate it.

**Comment by rugved1991** [comment]
Hi @surbhi-ctas,

Currently it is not possible to read and respond to buyer messages through SP-API. 

You can request product review and feedback through the Solicitation API and send templated messages through the Messaging API.
[Solicitation API](https://developer-docs.amazon.com/sp-api/docs/solicitations-api-v1-reference)
[Messaging API](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference)

Best,
Rugved
Solutions Architect, SP-API

**Comment by surbhi-ctas** [comment]
Hi @rugved1991 ,

It is very kind of you to respond to my inquiry, which is very helpful to me in further investigating. We would not be able to receive positive feedback based on orders(same as GET_SELLER_FEEDBACK_DATA) using SP API, right?
