### ISSUE TITLE
[BUG] [SP-API] [Issue] Oauth error MD9999

### ISSUE THREAD

**Issue by supermacro** [amzn/selling-partner-api-docs#3566]
Existing case id: 14692824131

It's been over 2 days and I have yet to receive a response in the case.

## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

Authorization

## Expected Behavior

When implementing the authorization URL and OAuth Flow as described in the ["Website authorization workflow"](https://developer-docs.amazon.com/sp-api/docs/website-authorization-workflow), a seller should be able to link their seller account with my application and be redirected to the **OAuth Redirect URI** that I already provided in the application I created on my public developer account.

## Current Behavior

After the seller is taken to seller central and logs in, I see an error page:

![Screenshot from 2024-01-29 22-47-28](https://github.com/amzn/selling-partner-api-docs/assets/10621548/e9171fb6-dd10-4cf7-85be-c9702349df82)

I used the following URL to direct the seller from my application to seller central to log in:

```
https://sellercentral.amazon.com/apps/authorize/consent?application_id=${APP_ID}?version=beta&state=${STATE}
```

Note that my application is in DRAFT, hence why `version=beta` is added as a query param

## Your Environment
I am using ngrok to create a login + redirect set of URIs:

- https://[my-permanent-domain].ngrok-free.app/login
- https://[my-permanent-domain].ngrok-free.app/success

**Comment by rugved1991** [comment]
Hi @supermacro,

Please open a [developer support case](https://developer.amazonservices.com/support) to investigate this issue further. There might be a few different reasons that might cause the MD9999 error so we would need to deep dive into the application setup.

Thanks,
Rugved
Solutions Architect, SP-API

**Comment by supermacro** [comment]
case id: 14692824131

**Comment by supermacro** [comment]
Hey @rugved1991 - any chance you could provide an update on case 14692824131? It was opened on feb 26 and there hasn't really been any useful info provided to me.

**Comment by supermacro** [comment]
Oh yes - thank you @leonardonakagawa
