### ISSUE TITLE
I don't have access to the development menu

### ISSUE THREAD

**Issue by emmendoza2794** [amzn/selling-partner-api-docs#358]
Greetings, it turns out that a few days ago in my seller central account I had access to the development menu and I could create and manage my own apps but today I realize that it does not appear in the menu and I have not been able to access the apps that I had created.
Has this happened to anyone?
Thank you very much for your time.

![image](https://user-images.githubusercontent.com/24445416/106402594-35c3dd80-63f8-11eb-98de-7e9afff91900.png)

**Comment by vikingcodes** [comment]
@emmendoza2794 Is this your professional seller account ? Amazon charge $39.99 apox. monthly .
