### ISSUE TITLE
createSubscription returns Unauthorized

### ISSUE THREAD

**Issue by MST1122** [amzn/selling-partner-api-docs#359]
I can call createDestination, but when I try to call createSubscription I always get "Access to the requested resource is denied."

I followed the guide for notifications to SQS. 

I added the Principal 437568002678 below my ID in the JSON permissions, so I assume it will get full access even though the guide mentions only SendMessage and GetQueueAttributes is needed, but I had no idea how to do that.

Could the access deny because of queue permissions?

I have seen another issue created by https://github.com/goodiebag45 and closed. but no solution is provided.

**My Access Policy:**

`{
  "Version": "2008-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "__owner_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::XXXXXXXXXX:root"
      },
      "Action": "SQS:*",
      "Resource": "arn:aws:sqs:eu-central-1:XXXXXXXXXXXX:AmazonOrdersEvents"
    },
    {
      "Sid": "Stmt1611753XXXXX",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
      },
      "Action": [
        "sqs:GetQueueAttributes",
        "sqs:SendMessage"
      ],
      "Resource": "arn:aws:sqs:eu-central-1:XXXXXXXXXXXX:AmazonOrdersEvents"
    },
    {
      "Sid": "__receiver_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::XXXXXXXXXXXX:role/SP-API-Developer"
      },
      "Action": [
        "SQS:ChangeMessageVisibility",
        "SQS:DeleteMessage",
        "SQS:ReceiveMessage"
      ],
      "Resource": "arn:aws:sqs:eu-central-1:XXXXXXXXXXXX:AmazonOrdersEvents"
    }
  ]
}`

@johnkw
@ShivikaK
@josephble

**Comment by ShivikaK** [comment]
Hello @MST1122 

Thank you for raising this issue.

Please share the request details of your createSubscription request for further investigation.

createSubscription is not a grantless operation so please ensure correct access token is being generated for this operation.

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by cgaugel** [comment]
createSubscription returns an subscriptionId for me, but I dont receive any notifications in my SQS-Queue. FIX THIS!

**Comment by fuzonmedia** [comment]
is it already solved ? I am not receiving notification too in my SQS.

**Comment by bingdor** [comment]
Do you resolve it?

**Comment by iamricks** [comment]
Whats the solution to this?

**Comment by webinsect-rishabh** [comment]
Have you solved this issue ? i am having the same issue.

**Comment by webinsect-rishabh** [comment]
@MST1122  Have you solved this issue ? i am having the same issue.

**Comment by MST1122** [comment]
@webinsect-rishabh Sorry man, No progress on this issue.

**Comment by webinsect-rishabh** [comment]
so you left the notification createSubscription process ?

**Comment by freedev1** [comment]
I was experiencing the same symptoms, namely that I could create a destination but I could not create a subscription for that destination. The mistake I was making was using the same authorization credentials for the two actions. I had to use a grantless authorization (with the notifications scope) to create the destination, but I had to use a refresh-token based authorization to create the subscription. It's all in the docs, _but_ incredibly unintuitive.

**Comment by starstong** [comment]
> I was experiencing the same symptoms, namely that I could create a destination but I could not create a subscription for that destination. The mistake I was making was using the same authorization credentials for the two actions. I had to use a grantless authorization (with the notifications scope) to create the destination, but I had to use a refresh-token based authorization to create the subscription. It's all in the docs, _but_ incredibly unintuitive.

solve it :)

**Comment by YAssineAbGit** [comment]
> I was experiencing the same symptoms, namely that I could create a destination but I could not create a subscription for that destination. The mistake I was making was using the same authorization credentials for the two actions. I had to use a grantless authorization (with the notifications scope) to create the destination, but I had to use a refresh-token based authorization to create the subscription. It's all in the docs, _but_ incredibly unintuitive.

Same
