### ISSUE TITLE
Get Inventory from SP-API

### ISSUE THREAD

**Issue by z85510** [amzn/selling-partner-api-docs#3591]
I'm trying to get inventory using this endpoint

`https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?marketplaceIds=A2EUQ1WTGCTBG2,ATVPDKIKX0DER,A1AM78C64UM0Y8&granularityType =Marketplace&granularityId =A2EUQ1WTGCTBG2`

Headers: 
```
content-Type : application/json
x-amz-access-token: Atza|I...
```

first of all, I don't know what I should use for `granularityId`, I want to get data from 3 marketplaces
then when I ran this endpoint I got 400 
```

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid request, please check your input.",
            "details": ""
        }
    ]
}
```

What am I doing wrong?

`https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?marketplaceIds=A2EUQ1WTGCTBG2&granularityType =Marketplace&granularityId =A2EUQ1WTGCTBG2`
I tried for just one marketplace but still getting error

**Comment by littleylv** [comment]
> `granularityType =Marketplace&granularityId =A2EUQ1WTGCTBG2`

Why you put a `space` before `=`?

**Comment by z85510** [comment]
Thanks, I didn't notice that

**Comment by rugved1991** [comment]
Hi @z85510,

Please refer to the [FBA Inventory API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/fba-inventory-api-v1-use-case-guide#get-all-available-inventory-summaries-with-full-details) for an example of the request for getInventorySummaries operation using marketplace as granularityType.

Best,
Rugved
Solutions Architect, SP-API
