### ISSUE TITLE
How to upate leadtimeToShip by Feeds API in Amazon SP API

### ISSUE THREAD

**Issue by moesama-zzt** [amzn/selling-partner-api-docs#3592]
I'm trying to update the leadtimeToShip using the Feeds API in the Amazon Selling Partner API (SP-API), but I'm encountering some difficulties. The leadtimeToShip refers to the time interval between when an order is placed and when the order item is shipped. I've gone through the relevant documentation, but I'm still unsure how to correctly use the Feeds API to achieve this goal.

I need guidance on how to construct the correct API request to update the leadtimeToShip.Any assistance, advice, or guidance from anyone familiar with using the Feeds API to update leadtimeToShip would be greatly appreciated.

**Comment by leonardonakagawa** [comment]
Hi @moesama-zzt,

you can use the attribute below:

```
"fulfillment_availability": [
            {
                "fulfillment_channel_code": "DEFAULT",
                "lead_time_to_ship_max_days": 30,
                "quantity": 7
            }
        ]
```

Where `lead_time_to_ship_max_days` is the handling time and you need to provide the time, in days, between when you receive an order for an item and when you can ship the item.

Using this attribute you are able to PATCH an item already create or PUT a new item via JSON_LISTINGS_FEED trough Feeds API.

You can find details regarding this in our [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide) and our [https://www.youtube.com/watch?v=-box2_OmQpE&list=PLUFIeZA9F5PxOt0_Mql1KFmusySdpGmYV](Lisitngs API Series on YouTube).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
