### ISSUE TITLE
[BUG] [SP-API] [Issue] Put Listing Item for new SKU is very slow only for -> PRODUCT (ABIS_BOOK) - Over 1 hour

### ISSUE THREAD

**Issue by FrankFerry** [amzn/selling-partner-api-docs#3596]
Good morning!!!

The problem occurs if you insert a listing with a new SKU (API's putListingsItem call). After more than an hour the status becomes BUYABLE and if you subsequently delete the SKU (deleteListingsItem) and insert it after 5 minutes (putListingsItem) then publication is almost immediate. Please note that there are no ISSUES!!!  (in the three response request:
1) first response request -> after putListingItem the ISSUES is empty
2) after DISCOVERABLE status the ISSUES is empty
3) after BUYABLE status the ISSUES is empty)

Only by waiting more than an hour does the publication result in the BUYABLE status. This only for ABIS_BOOK.

**Comment by benjifarmer** [comment]
I have this same issue. Did you ever figure out what was happening?
