### ISSUE TITLE
[BUG] Getting incorrect data on hitting listCatalogItems

### ISSUE THREAD

**Issue by HarshitTamrakar** [amzn/selling-partner-api-docs#360]
**Describe the bug**
On hitting 
### https://sellingpartnerapi-eu.amazon.com/catalog/v0/items?MarketplaceId=A21TJRUUN4KGV&Query=t
Which is suppose to search seller`s inventory with the given query parameter
**is returning products/items which does not belongs to that seller**

Example :- response =
{
        "Identifiers": {
          "MarketplaceASIN": {
            "MarketplaceId": "A21TJRUUN4KGV",
            "ASIN": "B07CN2BR66"
          }
        },
        "AttributeSets": [
          {
            "MaterialType": [
              "Polycarbonate"
            ],
            "Binding": "Kitchen",
            "Brand": "PHILIPS",
            "Color": "Cool Day Light",
            "ItemDimensions": {
              "Height": {
                "value": 7.0866,
                "Units": "inches"
              },
              "Length": {
                "value": 5.9055,
                "Units": "inches"
              },
              "Width": {
                "value": 7.0866,
                "Units": "inches"
              },
              "Weight": {
                "value": 0.3747858454,
                "Units": "pounds"
              }
            },
            "Label": "Signify Innovations India Limited",
            "ListPrice": {
              "Amount": 760,
              "CurrencyCode": "INR"
            },
            "Manufacturer": "Signify Innovations India Limited",
            "Model": "T-bulb",
            "NumberOfItems": 2,
            "PackageDimensions": {
              "Height": {
                "value": 2.5984251942,
                "Units": "inches"
              },
              "Length": {
                "value": 11.1811023508,
                "Units": "inches"
              },
              "Width": {
                "value": 4.8425196801,
                "Units": "inches"
              },
              "Weight": {
                "value": 0.7054792384,
                "Units": "pounds"
              }
            },
            "PartNumber": "T-bulb",
            "ProductGroup": "Lighting",
            "ProductTypeName": "LIGHT_BULB",
            "Publisher": "Signify Innovations India Limited",
            "Size": "Pack of 2",
            "SmallImage": {
              "URL": "https://m.media-amazon.com/images/I/41tQPk+pQcL._SL75_.jpg",
              "Height": {
                "Units": "pixels",
                "value": 75
              },
              "Width": {
                "Units": "pixels",
                "value": 75
              }
            },
            "Studio": "Signify Innovations India Limited",
            "Title": "Philips T-bulb Base B22 14-Watt LED Bulb (Pack of 2, Cool Day Light)",
            "Warranty": "2 year on product from date of invoice"
          }
        ],
        "SalesRankings": [
          {
            "ProductCategoryId": "kitchen_display_on_website",
            "Rank": 399
          },
          {
            "ProductCategoryId": "4205458031",
            "Rank": 9
          }
        ]
      }

this item doesn't belong to the seller

**Comment by stockarea** [comment]
Yes same for me as well. I am not getting the correct data of the seller's account. I am currently using sp-api for sandboxing and testing it
