### ISSUE TITLE
Listings API putListingsItem How To Create Listing

### ISSUE THREAD

**Issue by frankHHHHHHH** [amzn/selling-partner-api-docs#3620]
When I used the putListingsItem API to create a listing, I found that its input parameter has an attributes.The attribute parameter. I obtained the key corresponding to attributes through the getDefinitionsProductType interface, but how should I obtain the value enumeration values and related rules corresponding to the key?
    Please help me check if the process of creating a listing is correct, and how to obtain the enumeration values corresponding to the attributes. Thank you

**Comment by fan75886** [comment]
Hello, how did you solve it

**Comment by chapmanjw** [comment]
@frankHHHHHHH  @fan75886 The documentation here walks through the end-to-end workflow for creating listings via the APIs: https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide. The JSON Schema linked in the Product Type Definitions API response provides the attributes and attribute constraints (including enumerations) to generate a listings payload. That payload is then used as the `attributes` on the PUT request.
