### ISSUE TITLE
Document /reports/2020-09-04/documents/{reportDocumentId} cryptography with example

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#363]
Document /reports/2020-09-04/documents/{reportDocumentId} cryptography with example.

An excellent working example that explains what you're supposed to actually do is here:
https://github.com/amzn/selling-partner-api-docs/issues/186#issuecomment-756108550

The https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#reportdocumentencryptiondetails object should contain or link to the bug #186 example code, which is far more helpful than trying to explain it in words anyway.

**Comment by johnkw** [comment]
( The lack of documentation also came up in bug #71 )

**Comment by johnkw** [comment]
It was hinted in bug #576 that the API might be fixed to remove the need for all this craziness. If so this ticket could be closed when that fix occurs. Not sure what's going on there though.

**Comment by johnkw** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md is now available and seems to be working, and contains no mention of this extra seemingly pointless layer of cryptography.

It seems like the old documentation should no longer be addressed, except to put a big message on it to say it's now out of date, and to use the 2021-06-30 version instead.  @parvathm ?

**Comment by johnkw** [comment]
This is still relevant because https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md needs a huge red banner warning saying that API version is deprecated and to move to the new one, or some such.

**Comment by johnkw** [comment]
Still broken although now it's https://developer-docs.amazon.com/sp-api/docs/reports-api-v2020-09-01-reference that needs the fix.

Turn this stupid bot off and resolve the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon

**Comment by rugved1991** [comment]
Hi @johnkw,

We wont be adding a banner on the API reference page. We have provided recommendation in our docs that you should use the latest version of the API as it accounts for earlier bugs. We periodically send announcements regarding deprecations of the versions of APIs and will eventually remove the reference pages from documentation.
For more information, please review this [FAQ](https://developer-docs.amazon.com/sp-api/docs/sp-api-general-faqs#which-version-should-i-use-when-there-are-multiple-versions-of-the-same-api)

Best,
Rugved
Solutions Architect, SP API

**Comment by johnkw** [comment]
Actually there is a banner now.

It's not very prominent (should be highlight in a red background or something).  But it is there, so this is fixed.  It says:

> Effective June 27, 2023, the Selling Partner API for Reports v2020-09-04 will no longer be available and all calls to it will fail. Integrations that rely on the Reports API must migrate to [Reports v2021-06-30](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference) to avoid service disruption.
