### ISSUE TITLE
Selling-Partner App need the seller input our Developer ID when seller authorize.

### ISSUE THREAD

**Issue by qqqcai** [amzn/selling-partner-api-docs#364]
Our app is published recenly. 
When we testing for authorization in the AppStore, Here alert a window to ask seller to input MWS Developer ID. 
But there is no Developer ID for AMZ-SP.
When our app is in draft status, all step is ok, not need seller input the Developer ID, redirect to the Seller Control Center to allow the seller chose the access right.

There many people has the same problam[#288], we also tried some way [#316].

Our app is in Published (Current edit is pending approval) status. We can not know the effective until the approval finished

Our case ID is 7937726511

**Comment by MST1122** [comment]
@qqqcai I'm facing the same problem. have you found any solution or got a response from Amazon?

and where can I contact you? 
here is my skype_id: "live:sikandar_51". Please contact me, I have other issues to discuss also.

**Comment by ShivikaK** [comment]
Hello @qqqcai 

An application once submitted for being listed in appstore has to be approved after review. If the application has been approved, it will take up to 10 days for the changes to be fully published after which you should be able to test the Marketplace authorization workflow.

But please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @qqqcai 

Your app has been approved for publish as per case 7937726511 and your changes should have been fully published as well.
Can you please confirm if you are still facing any issues?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by qqqcai** [comment]
It has been resolved, thank you very much
