### ISSUE TITLE
[FEATURE] SP-API Private App development using SP-API 

### ISSUE THREAD

**Issue by Shubbu08** [amzn/selling-partner-api-docs#3643]
I am developing a Private application using SP-APIs. I registered as a private developer and followed the Amazon SP-API Developer University YouTube channel. 
https://www.youtube.com/@amazon-sp-api

1) Please let me know if creating an IAM account is mandatory for private application development.
2) I need help finding the IAM ARN option in the app registration screen shown in the link below. I don't see the IAM ARN option when I create a Private application.
https://www.youtube.com/watch?v=B8JVSRTz3QE&t=94s
3. Please share the link I can use and follow for the Private app creation.

**Comment by leonardonakagawa** [comment]
Hi @Shubbu08! 

Thanks for reaching out regarding registration as a Private developer.

IAM or AWS SigV4 is no longer necessary to access SP-API which means developers will not need to register for IAM resources or sign SP-API requests with AWS Signature Version 4. 

Instead, SP-API will continue to use [Login with Amazon](https://developer.amazon.com/docs/login-with-amazon/documentation-overview.html) (LWA) access tokens for each [SP-API request](https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api). LWA is based on OAuth 2.0, which has been broadly adopted for user-authorized exchanges across sites.

You can see the announcement [here](https://developer-docs.amazon.com/sp-api/changelog/sp-api-will-no-longer-require-aws-iam-or-aws-signature-version-4)

I'll provide feedback to update that YouTube video.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
