### ISSUE TITLE
Can't access report GET_VENDOR_TRAFFIC_REPORT

### ISSUE THREAD

**Issue by rodelrebs** [amzn/selling-partner-api-docs#3649]
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

I need help about what roles or rights I need to access **GET_VENDOR_TRAFFIC_REPORT**. Access to other reports like **GET_VENDOR_SALES_REPORT** is working fine but **GET_VENDOR_TRAFFIC_REPORT** returns:

`{
  "errorDetails": "Error in report request: Report requested with invalid user inputs. Please verify if you have correct Vendor Group Rights and/or required permissions to request this report."
}
`

**Comment by chrisskhoury** [comment]
Hello @rodelrebs,

There might be multiple reasons for this. Keep in mind you will need the [Brand Analytics](https://developer-docs.amazon.com/sp-api/docs/brand-analytics-role) Role to access this report. Also you will need to use a vendor refresh token for this flow and not a seller token.

I would recommend opening a ticket with [developer support](https://developer.amazonservices.com/de-de-support) to have a deeper dive on this.

Best,
Chris
Solution Architect, Amazon
