### ISSUE TITLE
Got Internal Server Error

### ISSUE THREAD

**Issue by 4379711** [amzn/selling-partner-api-docs#365]
> I confirm that my authentication information is correct because it can be accessed successfully on other interfaces .
> Can someone give me some suggestions, Thanks !

`POST`   **/shipping/v1/shipments**

Parameters:

```json
{
    "clientReferenceId": "test123456789",
    "shipTo": {
        "name": "Yara swain",
        "addressLine1": "6597 w. Desert blossom way",
        "stateOrRegion": "Az",
        "city": "Florence",
        "countryCode": "US",
        "postalCode": "85132"
    },
    "shipFrom": {
        "name": "Kameron Frederick",
        "addressLine1": "11918 Kirkholm Drive",
        "stateOrRegion": "Texas",
        "city": "Houston",
        "countryCode": "US",
        "postalCode": "77089"
    },
    "containers": [
        {
            "containerType": "PACKAGE",
            "containerReferenceId": "testContainer001",
            "value": {
                "value": 2,
                "unit": "USD"
            },
            "dimensions": {
                "length": 2,
                "width": 2,
                "height": 1,
                "unit": "CM"
            },
            "items": [
                {
                    "quantity": 1,
                    "unitPrice": {
                        "value": 2,
                        "unit": "USD"
                    },
                    "unitWeight": {
                        "unit": "g",
                        "value": 2
                    },
                    "title": "This is a title test !"
                }
            ],
            "weight": {
                "unit": "kg",
                "value": 1.5
            }
        }
    ]
}
```

Response:

```
{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}
```

**Comment by ShivikaK** [comment]
Hello @4379711 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by 4379711** [comment]
Hello @ShivikaK 
I submitted a case on sellercentral ,ID :7958113471 ;

**But the reply looks like a robot, unable to solve the problem**

This is my request :

POST **/shipping/v1/shipments**

requestId: **d6f52f70-ecee-45fd-8ef9-a2ccceef3abe**
timestamp: **2021-02-04T18:09:42-0800**

**_I get a 500 error response. And all interfaces about **shipments**, all get this error ._**

response:
    {
    "errors": [
    {
    "code": "InternalFailure",
    "message": "We encountered an internal error. Please try again.",
    "details": ""
    }
    ]
    }

**Comment by ShivikaK** [comment]
Hello @4379711 

Your case has been reopened and escalated for further investigation. Please monitor the case for next steps regarding the issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by nuvoretail-developer** [comment]
@ShivikaK i have facing the same issue.. 
please go through my code and let me know if i am doing any error...

![image](https://user-images.githubusercontent.com/80046831/111867920-27785380-899d-11eb-9675-2ec693e2b262.png)

**Comment by arook** [comment]
@4379711 Has your problem been solved? We have reached the same problem.

**Comment by nuvoretail-developer** [comment]
@4379711 still facing the same issue.

**Comment by darkwind14** [comment]
@ShivikaK , I also facing the same issue. All of API which related Shipping part (createShipment, getRates, getAccount …. etc) return error 500. Could you please let me know how to fix it?

```
response:
{
"errors": [
{
"code": "InternalFailure",
"message": "We encountered an internal error. Please try again.",
"details": ""
}
]
}
```

**Comment by Ziyun-KyLin** [comment]
我也遇到这个问题了

**Comment by yougotdefined** [comment]
I encounter the same error still.
