### ISSUE TITLE
Where can we get the Inbound Shipment Placement Fee amounts for shipments during creation?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#3659]
Where can we get the Inbound Shipment Placement Fee amounts for shipments during creation?

See also bug #3617 on how to pick the options (which awkwardly can't be done through the API itself).

**Comment by johnkw** [comment]
According to Amazon Support, the only option currently is to use https://sellercentral.amazon.com/revcal to manually specify the SKUs in question and get placement fees.

**Comment by ben-pierre** [comment]
This can now be done with the new Fulfillment Inbound API FYI

Well, supposedly, it's broken in about 9 different ways and can't be used if you have anything except the specific use case that they tested for in development. But alas, it has an end point for placement fees and choosing options.

**Comment by johnkw** [comment]
You found the placement fees?  Where are they?

Yeah we haven't gotten to make a shipment yet due to bug #3708.

**Comment by johnkw** [comment]
Oh neat, that does look correct in the docs.  I see https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#incentive on that.  I guess I'll go ahead and close this bug report, since it's theoretically solved by the new API.

Sure would love to know in bug 3708 how you got past that one. I thought that was a 100% blocker for everyone.
