### ISSUE TITLE
Rate / Burst documentation wrong on productPricingV0.md

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#368]
The Rate / Burst documentation is wrong on https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md in that it does not match what the API is doing.

I suspect maybe all of the calls on that page are wrong. They all say 1 / 1 right now.

For example on "GET /products/pricing/v0/items/{Asin}/offers" the Burst is definitely wrong. It says 1, but it seems to be 4 or 5.  The Rate is definitely not 1 - it might be .5?

**Comment by callumb123** [comment]
Exactly the same problem with ListCatalogItems. I fear they have just slapped 1 / 1 on most docs even if this isn't what has been implemented, but I hope I am wrong!
