### ISSUE TITLE
Selling accounts auto downgraded when they do not generate sales

### ISSUE THREAD

**Issue by hakanensari** [amzn/selling-partner-api-docs#37]
We maintain professional selling accounts in Europe and other regions purely to access MWS. If I understand correctly, we will continue using these credentials once we transition to the Selling Partner API.

As we do not generate any sales, the accounts get auto downgraded to individual every 90 days. I am wondering if there is any way to avoid this.

Also, would these auto downgrades have any harmful consequences? While I have not tested for a lengthy period, it seems our MWS access and users' auth tokens remain intact after downgrade. Amazon support staff, on the other hand, explained we should lose all access after a downgrade. 

_(Edited after exchange with support)_

**Comment by hakanensari** [comment]
I also wrote to MWS support through Seller Central and got this response:

> Regarding auto downgrading to Individual Selling Plan, Professional sellers that haven't made a sale in the past 90 days or sellers accounts has an outstanding debt that hasn’t been paid off will be automatically downgraded to an Individual Selling Plan so no additional fees would be charged to sellers.

While this explains the cause, it does not answer how we can avoid such auto downgrades and whether this may have an adverse effect on our access to MWS were we not to upgrade manually afterwards.

Any advice would be appreciated.

**Comment by seanevan** [comment]
Hi @hakanensari,

I have asked a member of our Developer Support team to contact you via support case so we can help resolve this for you.

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by hakanensari** [comment]
I'm assuming this issue will not happen again and am closing.

The latest update I got:

> I worked personally with this team and we are working together for them to identify MWS Developer accounts, as well as SP API Developer accounts, and these accounts, including yours, will not be downgraded again. Please feel free to upgrade your account, so you can have access to MWS features again.
