### ISSUE TITLE
[FEATURE] Documentation - TransportationOption - ShippingMode is a bit ambiguous as to what I'm going to get back

### ISSUE THREAD

**Issue by ben-pierre** [amzn/selling-partner-api-docs#3700]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the improvement**
fulfillment-inbound-api-v2024-03-20-reference - TransportationOption - ShippingMode has the comment of 

> The shipping mode associated with the transportation option. Available modes are ground small parcel, freight less-than-truckload (LTL), freight full-truckload (FTL) palletized, freight FTL non-palletized, ocean less-than-container-load (LCL), ocean full-container load (FCL), air small parcel, and air small parcel express.

This is a bit ambiguous. Am I going to get GSP, FTL, LTL, LCL, am I going to get "ground small parcel", "freight less than truckload", or am I going to get "ground-small-parcel", "freight-less-than-truckload"

**URL of the content on GitHub**
Doesn't look like these have made it to the GitHub yet

**Description of what the documentation currently says**
> The shipping mode associated with the transportation option. Available modes are ground small parcel, freight less-than-truckload (LTL), freight full-truckload (FTL) palletized, freight FTL non-palletized, ocean less-than-container-load (LCL), ocean full-container load (FCL), air small parcel, and air small parcel express.

**Description of what the documentation should say**
All the other enum esque values have a section "Can Be: ____, ____, ____" that explicitly provide the possible values

**Screenshots**

**Additional context**

**Comment by hinavinayak** [comment]
Hi @ben-pierre , you can see the ShippingMode values [here](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#shippingconfiguration).

Best,
Hina

**Comment by ben-pierre** [comment]
Thanks, this documentation is much better than what was originally there.
