### ISSUE TITLE
[BUG] [SP-API] [Issue] New FulfilmentInbound_2024_03_20 PrepInstruction => PrepOwner returns value explicitly not allowed according to the documentation

### ISSUE THREAD

**Issue by ben-pierre** [amzn/selling-partner-api-docs#3701]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

fulfillment-inbound-api-v2024-03-20 => ListPackingGroupItems =>ListPackingGroupItemsResponse => items => prepInstructions => prepOwner documentation states possible values are AMAZON or SELLER, but endpoint is returning MERCHANT
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#prepinstruction

## SP-API Name and Version or Report/Feed Type

fulfillment-inbound-api-v2024-03-20

## Expected Behavior
I would expect the value of prepOwner to fall within one of the values in the documentation

## Current Behavior
Am receiving the value "MERCHANT"

## Context/Screenshots
`{
  "pagination": {},
  "items": [
    {
      "labelOwner": "",
      "msku": "Redacted",
      "quantity": 150,
      "fnsku": "Redacted",
      "asin": "Redacted",
      "prepInstructions": [
        {
          "prepType": "ITEM_NO_PREP",
          "fee": {
            "amount": 0,
            "code": "USD"
          },
          "prepOwner": "MERCHANT"
        }
      ]
    },
    {
      "labelOwner": "",
      "msku": "Redacted",
      "quantity": 750,
      "fnsku": "Redacted",
      "asin": "Redacted",
      "prepInstructions": []
    }
  ]
}`

## Your Environment
Self written C# connector, prod environment.

**Comment by ben-pierre** [comment]
Label owner has the same issue. I create the shipment with "Seller" and that all works as expected, but then ListPackingGroupItems responds with "MERCHANT"

**Comment by daiqi77777** [comment]
Have you implemented the setPackingInformation interface?

**Comment by ben-pierre** [comment]
Developer Support Resolved this with Ticket 15091230151
