### ISSUE TITLE
[Auth] The authorization grant type is not supported by the authorization server

### ISSUE THREAD

**Issue by twanlee** [amzn/selling-partner-api-docs#372]
Hello you guys, i'm recenly got Error getting LWA Access Token while using SDK to connect to SP API. Then i test it on Postman like instruction here: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token
then i've got response: {
    "error_description": "The authorization grant type is not supported by the authorization server",
    "error": "unsupported_grant_type"
},
I read a document again and again, try with LWA Credentials in my app. Seems like nothing wrong. If anyone has got this issued, please share your experience!!!!

**Comment by twanlee** [comment]
Auth

**Comment by wyrd-code** [comment]
I also get this error

I'm using `node-fetch`, and following [the instructions for getting an access token via manual request](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token) from the docs.
