### ISSUE TITLE
Error : listItemComplianceDetails gives InternalFailure

### ISSUE THREAD

**Issue by ashish-greycube** [amzn/selling-partner-api-docs#3726]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/3724

<div type='discussions-op-text'>

<sup>Originally posted by **ashish-greycube** April 22, 2024</sup>
When i call https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listitemcompliancedetails

> {'mskus': ['U-2P-HAVC', 'U-ENAAS2'], 'marketplaceId': 'ATVPDKIKX0DER', 'path': '/inbound/fba/<version>/items/compliance', 'method': 'GET'}

It gives error

> {'code': 'InternalFailure', 'message': 'We encountered an internal error. Please try again.', 'details': ''}</div>

**Comment by harguph** [comment]
Hello @ashish-greycube ,

Thank you for bringing this up.

Please open a [developer support case](https://developer.amazonservices.com/support) sharing the full request and response so that the backend team can have a look to why this happened.
