### ISSUE TITLE
[BUG] [SP-API] [Issue] Get Listing and catalogue for Vendors

### ISSUE THREAD

**Issue by gaelayo** [amzn/selling-partner-api-docs#3728]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
I would like to be able to obtain the full listing and catalogue for a given Vendor. This is currently possible for _sellers_ with the **GET_MERCHANT_LISTINGS_ALL_DATA** report type.
The `searchCatalogItems` operation does not permit getting all the ASIN for a given seller, without specifying `keywords` or `identifiers`, thus having an incomplete results.

## Current Behavior
There is not way to get the catalogue or the listing for a vendor using the API.
The catalogue is obtainable from the front-end of Vendor central, but I would like to be able to 

## Context/Screenshots
This is certainly related to https://github.com/amzn/selling-partner-api-docs/issues/2169#issuecomment-1189515715 where @chapmanjw stated that there was no way to accomplish this, but that this was on the roadmap. It was two years ago, so I was wondering if there were any news about this.

**Comment by rugved1991** [comment]
Hi @gaelayo,

Thanks for resurfacing this feature request. We still have this feature request in our backlog. We do not have any specific ETAs on when this feature would be made available. Please stay tuned to our Announcements page for future updates.

Best,
Rugved
Solutions Architect, SP-API

**Comment by chapmanjw** [comment]
@gaelayo We are working on a `searchListingsItems` operation for the Listings Items API that will serve this function (and will behave similarly to the `searchCatalogItems` operation for the Catalog Items API). Stay tuned for announcements on when this becomes available.
