### ISSUE TITLE
EstimatedBoxContentsFee on /fba/inbound/v0/plans even for SELLER_LABEL plan

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#376]
On `/fba/inbound/v0/plans` I'm specifying `LabelPrepPreference` = `SELLER_LABEL` so I was expecting the result to not contain an `EstimatedBoxContentsFee` entry, yet it does.

`'FeePerUnit': {'CurrencyCode': 'USD', 'Value': 0.1}`

This seems to be the label fee, as if the shipment requested `AMAZON_LABEL`.  Why would `EstimatedBoxContentsFee` be present, even though there should not be a label fee for this shipment?

**Comment by ShivikaK** [comment]
Hello @johnkw 

Thank you for raising this issue.

EstimatedBoxContentsFee is a fee charged by Amazon for boxes without box content information. This fee is returned if the BoxContentsSource value is NONE.

**Comment by johnkw** [comment]
I should also make it clear this is only a bug in `POST /fba/inbound/v0/plans` it seems. Once the shipment is actually created, via `POST /fba/inbound/v0/shipments/shipmentId`, using the `shipmentId` returned from the `POST /fba/inbound/v0/plans`, then Seller Central shows the shipment does not actually have a per-box fee on it.

**Comment by ShivikaK** [comment]
Hello @johnkw 

If you can open a support case, we can further pursue this investigation and research the issue you are facing and verify if this is a bug.

If you did report it via a support case already, please share the case ID with me.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by johnkw** [comment]
This is really easy to reproduce, and doesn't seem to have anything to do with our account specifically, but ok. I created case 8013577271.

**Comment by ShivikaK** [comment]
Hello @johnkw 

As Support is currently working with you directly on this issue via case 8013577271, I am closing this issue. Please monitor the case for updates.

Thanks,
Shivika Khare
Selling Partner API Developer Support
