### ISSUE TITLE
searchCatalogItems wont return page 4 onwards

### ISSUE THREAD

**Issue by pricecheckgames** [amzn/selling-partner-api-docs#3763]
We can successfully call searchCatalogItems with a search term and retrieve results.  We are limiting the search to the video games category with query classificationIds=1025616 an example query would be...

keywords=mario&classificationIds=1025616&marketplaceIds=A1F83G8C2ARO7P&includedData=summaries,salesRanks&pageSize=20

Which returns 7795 results however we can only page through the first 3 pages, page 4 always gives an error 

Token for page two...
"9HkIVcuuPmX_bm51o3-igBfN45pxW4Ru7ElIM6GCECYCuXJKzT26f4uh3zTyUBNUGwLwMV8RoCxwt_JvE7qiRhYLhBk372mz40YIbo765NPKcfSUu42r2G4YUGGFlG71CSGlqUqhGrfcKwZQH2spwx1l1vj7KQoFIa7pWiOPHyaYWP7sBE9Fg7cGN2wE0an5ePw96h6ZL7mnNKMrrdFg-GNanEVRjipq"

Token for Page three
"9HkIVcuuPmX_bm51o3-igBfN45pxW4Ru7ElIM6GCECYCuXJKzT26f4uh3zTyUBNUNQxtyfwABp9wt_JvE7qiRhYLhBk372mz40YIbo765NPKcfSUu42r2G4YUGGFlG71CSGlqUqhGrfcKwZQH2spwx1l1vj7KQoFIa7pWiOPHyaYWP7sBE9Fg7cGN2wE0an5ePw96h6ZL7niJ7q1VFTczT1Bl34ufllu"

Token for Page four
"9HkIVcuuPmX_bm51o3-igBfN45pxW4Ru7ElIM6GCECYCuXJKzT26f4uh3zTyUBNUwn2tHUu9gh1wt_JvE7qiRhYLhBk372mz40YIbo765NPKcfSUu42r2G4YUGGFlG71CSGlqUqhGrfcKwZQH2spwx1l1vj7KQoFIa7pWiOPHyaYWP7sBE9Fg7cGN2wE0an5ePw96h6ZL7niJ7q1VFTczfp50DAC1n52f21sjEmsFr8="

This page always returns error no matter what keywords are used...

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}

Can anybody suggest a reason for this?  It is my understanding that the max pagination is 1000 results where I'm only getting 60

**Comment by surbhi-ctas** [comment]
Getting the same error in searchCatalogItems API,  [pricecheckgames](https://github.com/pricecheckgames) Did you resolve it?

It would be greatly appreciated if you could help me.
