### ISSUE TITLE
[BUG] Documentation Where are steps in aws console,i can't find these.

### ISSUE THREAD

**Issue by logerlink** [amzn/selling-partner-api-docs#377]
Hi!
**Describe the bug**
![image](https://user-images.githubusercontent.com/39935072/106852980-ee896580-66f3-11eb-9674-0971a90fbc5e.png)
I can't find these step in my aws console.
When calling **CreateDestination api** i got  error.just like:
`
IO.Swagger.Client.ApiException:“Error calling CreateDestination: {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}”
`
What should i do next?
**URL of the content on GitHub**
[step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/notifications-use-case-guide-v1.md#step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue)

**Comment by pprbhm** [comment]
Hi, We will have to work with you on a support case. Can you please create one here- https://developer.amazonservices.com/support

**Comment by weiliguo15634145** [comment]
Have you found the answer , I had the same problem.
