### ISSUE TITLE
[BUG] Documentation - Feed upload

### ISSUE THREAD

**Issue by gavranovic672** [amzn/selling-partner-api-docs#379]
C#
I am successfully logged in with LWA, i am calling CreateFeedDocumentSpecification and geting the response, with sandbox  the response is not valid, key and vector are not base64 (sandbox.sellingpartnerapi-eu.amazon.com). The live is returning data correctly. I am geting info from getFeed(), then from getFeedDocument(), and i am trying to download the file from the URL i got from getFeedDocument() and as a content i am recieving this: 
![image](https://user-images.githubusercontent.com/78155259/106904548-9f473300-66fb-11eb-87c6-a204e7dbe434.png)
how can i transform that into array of bytes?

**Comment by BlinglingGirl** [comment]
the charset is ISO-8895-1
