### ISSUE TITLE
New fields in inventory report

### ISSUE THREAD

**Issue by discover59** [amzn/selling-partner-api-docs#384]
From today I am getting new fields `Sell Remainder` and `Minimum Order Quantity` in inventory report `_GET_MERCHANT_LISTINGS_ALL_DATA_`.

Is this new feature or temporary? Any instruction for these fields are appreciated.

**Comment by johnkw** [comment]
Not sure about this in particular, but all of the reports need to be actually documented, explaining, in detail, what every column is.

**Comment by discover59** [comment]
@amazon-auto Need documentation
