### ISSUE TITLE
What is the meaning of blank condition fields in BuyBoxPrices?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#385]
Every ASIN I've looked at has this weird data: `"BuyBoxPrices": [{"condition": ""},{"condition": ""},{"condition": ""},{"condition": ""}]`

For example see attached the complete payload from `GET /products/pricing/v0/items/B07YF4FNL1/offers` .
[offers.txt](https://github.com/amzn/selling-partner-api-docs/files/5933573/offers.txt)

The documentation at https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#buyboxpricetype indicates there are 4 required fields, but `LandedPrice`, `ListingPrice`, `Shipping` are all missing, and `condition` seems to have an invalid value.

What's going on there?

**Comment by tabertantrum** [comment]
@johnkw I had the same issue in #190 and to date haven't seen any changes in output. I created a support ticket via seller central but no luck there either.

**Comment by johnkw** [comment]
Ah I missed that ticket. I'm moving my comment over to that one and closing this duplicate one.
