### ISSUE TITLE
SP-API Application Creation Error

### ISSUE THREAD

**Issue by praharpatel** [amzn/selling-partner-api-docs#388]
Hello, 

I am getting this error while creating a SP application is seller central. My developer profile has already been approved for SP-API with PII access. This is the error I am getting - 

`Something went wrongPlease try again at a later time If the problem persists, please contact Seller Support and provide them with the following information: SPDC300`

I have already opened a case on Seller Central and the CASE ID is - 7965991301

Can someone please assist me with this ?

**Comment by praharpatel** [comment]
Any thoughts on this issue ?

**Comment by ShivikaK** [comment]
Hello @praharpatel 

We have received your case and responded to it with next steps to troubleshoot the issue. Please monitor your case for further follow ups.

Thanks,
Shivika Khare
Selling Partner API Developer Support
