### ISSUE TITLE
Vendor Sales Data (ARA) and Brand Analytics API Access

### ISSUE THREAD

**Issue by dsmolinski50** [amzn/selling-partner-api-docs#39]
Amazon Team - are you going to be making data from ARA, ARA+P and/or Brand Analytic available via the API?

**Comment by tspicer** [comment]
This would be huge to have. It is the #1 request feature from our customers.

**Comment by jamesp26** [comment]
It would be nice to know if there is an official position on this. It is a highly requested feature and a while back it looked like there was mention of ARA reporting in the new(ish) vendor API documentation and it was subsequently removed.

**Comment by hgamit** [comment]
Team, When is this feature going to be made available? Any Timelines on this?

**Comment by adam91holt** [comment]
Some timelines would be much appreciated on this 👍

**Comment by avlly** [comment]
Upvoting to adding this feature to the API

**Comment by parvathm** [comment]
Hi,

We understand this functionality is of interest to developers and have shared the voice of customer with the owners of this data within Amazon as a desired use case. 

Thanks,
Parvathm
Selling Partner API Developer support.

**Comment by GeoffTK** [comment]
Another +1 for needing this!

**Comment by hareeshi** [comment]
+1 for this request

**Comment by JKWisx** [comment]
+1 for this vital requirement.

**Comment by tooobsias** [comment]
+1 from my side too

**Comment by moltar** [comment]
I think some of this has landed 🥳 

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#vendor-retail-analytics-reports

**Comment by Shubham12Baid** [comment]
+1 for feature addition

**Comment by mkdir700** [comment]
> I think some of this has landed 🥳
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#vendor-retail-analytics-reports

thank you guys!

**Comment by rugved1991** [comment]
Thanks for providing feedback on what you would like from the API. We are constantly improving the API and would appreciate such feedback.
Keep them coming!

Rugved
Solutions Architect, SP API

**Comment by baptlma** [comment]
+1 for feature addition
