### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by Kpatel2629** [amzn/selling-partner-api-docs#391]
I am trying to access the Order endpoint of seller-API but getting the 403 (Forbidden) response code.

something like this `{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}`

here is the endpoint i am making the request to :- **https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER**

<img width="755" alt="amazon_seller_error" src="https://user-images.githubusercontent.com/52803154/107265827-b8f5bc80-6a12-11eb-9cda-72b733f2acc5.PNG">

**Comment by Kpatel2629** [comment]
I am using aws signature to for authentication also i am including the access_token in header.

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

Please confirm if you have the required role for this API access. If you have the role, please verify which IAM ARN is associated with your application and if you have attached the IAM policy correctly for the same. Please note, if your app has an IAM role entity, you are required to refer to below link to understand how to create and sign your request -

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-and-sign-your-request

Please feel free to open a support case with us if you'd like deeper assistance with this issue. If you have reported a case please share the case ID.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by AlexKraso** [comment]
@ShivikaK Hello. We have the same issue - ticket ID7954684761. We added all additional data about this incident: request, response, roles, ids. Can you please check the ticket?

**Comment by ShivikaK** [comment]
Hello @AlexKraso 

We have received your case and responded to it with next steps to troubleshoot the issue. Please monitor your case for further follow ups.

Thanks,
Shivika Khare
Selling Partner API Developer Support
