### ISSUE TITLE
Question about signing up to SPAPI and IAM ARN's

### ISSUE THREAD

**Issue by jamesp26** [amzn/selling-partner-api-docs#395]
I have a current setup where I build against MWS in a test AWS account and I deploy these to a production AWS account.

I would like to migrate to SP API but would like the same setup. I have to provide an IAM ARN when applying for SP API. Will i have to sign up to SP API twice (once for dev and once for live) or can i use an IAM ARN that is shared across my 2 AWS accounts.

At this stage i dont want to be doing anything that impact my existing MWS account.

Thanks!

**Comment by diegocvazquez** [comment]
> I have a current setup where I build against MWS in a test AWS account and I deploy these to a production AWS account.
> 
> I would like to migrate to SP API but would like the same setup. I have to provide an IAM ARN when applying for SP API. Will i have to sign up to SP API twice (once for dev and once for live) or can i use an IAM ARN that is shared across my 2 AWS accounts.
> 
> At this stage i dont want to be doing anything that impact my existing MWS account.
> 
> Thanks!

Did you get any response on this subject I am also facing this situation

**Comment by jamesp26** [comment]
No - it would be nice to understand what the recommended approach is, especially now we have deadlines to deprecate MWS.

My assumption is that we need to request 2 apps - 1 for development and 1 for production. But again, i dont know if request 2 apps will be seen as a problem.

**Comment by diegocvazquez** [comment]
@jamesp26 thanks for your response!

**Comment by jamesp26** [comment]
For anyone interested, we used the 'assumeRole' process for local development and testing in a dev environment. On production our Lambda's will be setup to run via our ARN natively.  

const createTemporaryAWSCredentials = async () => {
    const STS = new AWS.STS();
    const {
        Credentials: {
            AccessKeyId,
            SecretAccessKey,
            SessionToken,
        }
    } = await STS.assumeRole({
        RoleArn: '<--enter role arn here-->',
        RoleSessionName: '<--enter role session name here-->',
    }).promise();
    return {
        AccessKeyId,
        SecretAccessKey,
        SessionToken,
    };
};
