### ISSUE TITLE
Illegal block size from c#

### ISSUE THREAD

**Issue by esoler91** [amzn/selling-partner-api-docs#396]
Hello everyone.
I have developed the Submit a feed circuit but when I check the uploaded file the answer is: The uploaded document has an illegal block size.

I am developing the code from an ERP using C # and I have based on the following code: [https://stackoverflow.com/questions/64664197/how-to-encrypt-and-upload-data-using-selling-partner-api-in-amzon-using-net](https://stackoverflow.com/questions/64664197/how-to-encrypt-and-upload-data-using-selling-partner-api-in-amzon-using-net)

This is my code: 
[<img src="https://i.imgur.com/2qD1514.png">](https://i.imgur.com/2qD1514.png)

Anyone using C # to upload feeds? 
Thanks

**Comment by jason1004** [comment]
![image](https://user-images.githubusercontent.com/13719529/115149042-cbd0e100-a094-11eb-8323-0f7a82a2a14f.png)

**Comment by jason1004** [comment]
If the feeds api uploads an excel file, how to encrypt the data?

Using the EncryptStringToBytes_Aes method above, what you get is the result of doing the following：

            var content = File.ReadAllText(excel);
            var key = Convert.FromBase64String(createFeedDocResponse.Payload.EncryptionDetails.Key);
            var iv = Convert.FromBase64String(createFeedDocResponse.Payload.EncryptionDetails.InitializationVector);
            var encryptResult = EncryptStringToBytes_Aes(content, key, iv);

![image](https://user-images.githubusercontent.com/13719529/115153115-e613ba80-a0a6-11eb-9246-f228efcd4b2e.png)

**Comment by nightcoding2021** [comment]
Did you figure this out?  I keep getting "The uploaded document has an illegal block size." no matter what I try!
