### ISSUE TITLE
Get complete order information with one request

### ISSUE THREAD

**Issue by ravikas** [amzn/selling-partner-api-docs#399]
To get complete order infromation now i need to make these request:
/orders/v0/orders
foreach (var order in orders)
{
   /orders/v0/orders/{orderId}/orderItems
   /orders/v0/orders/{orderId}/address
   /orders/v0/orders/{orderId}/buyerInfo
}

it comes to making 3 extra requests for each order, it works but do not look very nice solution? Maybe there is a better way to accomplish this?

plus this constantly brings error "You exceeded your quota for the requested resource."

**Comment by gtaylor44** [comment]
@ravikas out of curiosity, are you able to get a Name, StreetAddress1, StreetAddress2 & StreetAddress3 out of the endpoint /orders/v0/orders/{orderId}/address?

**Comment by ravikas** [comment]
no., service returns blanks, returns only email., but email is also generated by amazon.., so far "address" and "buyerinfo" is useless.

**Comment by gtaylor44** [comment]
This is Amazon's new PII (Personally identifiable information) policies and may apply even after the draft state. 

"Personally Identifiable Information" ("PII") means information that can be used on its own or with other information to identify, contact, or locate an individual (e.g., Customer or Seller), or to identify an individual in context. This includes, but is not limited to, a Customer or Seller's name, address, e-mail address, phone number, gift message content, survey responses, payment details, purchases, cookies, digital fingerprint (e.g., browser, user device), IP Address, geo-location, or Internet-connected device product identifier.

For me this is a blocker. Amazon's support team is difficult to work with. Apparently you can get certain PII data but it must be discarded within 30 days.
