### ISSUE TITLE
Potential inconsistency: self authorise docs and Seller Central

### ISSUE THREAD

**Issue by p-prins** [amzn/selling-partner-api-docs#40]
**Question:**
Does creating a new refresh token through the Seller Central UI invalidate previously created tokens?

**Seller Central:**
![image](https://user-images.githubusercontent.com/67642137/95999625-5d396f00-0e36-11eb-9c59-b90cd0c73382.png)

**Docs:**
![image](https://user-images.githubusercontent.com/67642137/95999707-717d6c00-0e36-11eb-8c18-07504825cccf.png)

**Comment by rickdeee** [comment]
Fixed: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization. Thanks for pointing this out, @p-prins

**Comment by p-prins** [comment]
Perfect, thank you!
