### ISSUE TITLE
Modify IAM ARN or delete app?

### ISSUE THREAD

**Issue by emmendoza2794** [amzn/selling-partner-api-docs#400]
Hello friends, does anyone know how to modify the IAM ARN of an app or how to delete an app?
From the interface I don't see the option to delete the app and the IAM ARN is not modifiable, maybe someone knows how to do it?

Thank you very much, I stay tuned.

**Comment by ShivikaK** [comment]
Hello @emmendoza2794 

Thank you for raising this issue.

Currently there is no option to update/modify the IAM ARN of the application or delete the application via Developer Console page on Seller Central. We do accept such requests on a case by case basis and would recommend opening a support case with us if you have such an issue to further review it.

Please reach out to us via Support case for further assistance regarding this.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
