### ISSUE TITLE
Inventory API "Access to requested resource is denied"

### ISSUE THREAD

**Issue by mo86** [amzn/selling-partner-api-docs#401]
Hi, my request to https://sellingpartnerapi-eu.amazon.com/fba/inventory/v1/summaries results in "Access to requested resource is denied". All other Endpoints are working fine so it's nothing avout HOW I do the requests. In the app options I activated all endpoints.

I read somewhere else that the inventory API is not enabled in the European Marketplace. Can somebody confirm this? Thank you

**Comment by magik092** [comment]
Hi, I confirm that even the sandbox behavior returns 403 "Access to requested resource is denied" error (production returns same error).

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising the issue.

Currently this API is not enabled in EU and FE regions which is why you are receiving access denied error.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by mo86** [comment]
@ShivikaK  Thanks for your reply. So what can I do? I have no chance to use the "old" MWS-API because I just registered one week ago and with the new SP-API I can't get my stock amounts.

**Comment by jlevers** [comment]
@ShivikaK is there somewhere that we can see which APIs are/are not enabled in which regions? I'm running into the same error with the `getMarketplaceParticipations` call using the https://sellingpartnerapi-eu.amazon.com endpoint, and I'm wondering if it's because the Sellers API is not enabled in Europe.

**Comment by ericcj** [comment]
is it possible to get inventory data from the feeds api as a workaround or is that feed only available in north america too?

**Comment by jlevers** [comment]
@ericcj you should be able to retrieve inventory data from the [Reports API](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md) using one of [these report types](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#inventory-reports)

**Comment by kstar0101** [comment]
@ShivikaK
I'm getting inventory from japan.
But it's not working.
I would like to know if the inventory API works in Japan.

Error:
> [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

**Comment by MWessels62** [comment]
Hi @ShivikaK 
Two questions:

1. Do you have an ETA for when the Inventory API will be available in the EU region? 
2. If we have only just registered with Amazon can we still make use of the old MWS-API to use the ListInventorySupply API?

**Comment by ericcj** [comment]
still an issue
