### ISSUE TITLE
Getting Order Items Faster

### ISSUE THREAD

**Issue by mohamedfawzy96** [amzn/selling-partner-api-docs#403]
I would like to get all order items and in order to do that I have to go through each order and call an api to get its order items, is there a faster way to get the order items ? can I get it with the orders api all at once ?

**Comment by nodisk8800** [comment]
@mohamedfawzy96 

You can use Report API to get multiple orders and items at once.

**Comment by nodisk8800** [comment]
But,I suggest use Orders API to get orders.
If you have too much orders per day,then use Report API.

@mohamedfawzy96

**Comment by ykw090721** [comment]
@nodisk8800 What is the difference between calling orderApi and reportApi when pulling order data?

**Comment by nodisk8800** [comment]
@ykw090721 
没有什么不同,都是取订单的.
orderAPI 要一个一个下载,report API,可以一次下载一批订单,文本格式,下载后自己解析和保存.
在多数应用场景,orderAPI都能满足使用.
个别特殊情况,比较一天的订单数量超过API的频率上限,一整天都下载不完.此时就可以考虑使用reportAPI来下载.

**Comment by mohamedfawzy96** [comment]
@nodisk8800 okay will check it out, Thank you!
