### ISSUE TITLE
[BUG] Documentation GET /orders/v0/orders/{orderId}/orderItems

### ISSUE THREAD

**Issue by pnamroud** [amzn/selling-partner-api-docs#406]
Hello Team,
I believe there is an issue wither with the documentation, or the Orders API (getOrderItems).
I have been struggling to get all the information related to Taxes, Commission, shipping charges,... for Orders having status = Shipped', for no success.

It is either the Documentation is misleading, or their is certainly an issue with the API endpoint itself, not returning the data as documented.
I noticed your note below, but without any success...

Can you review and advise please ?

_**Note: When an order is in the Pending state (the order has been placed but payment has not been authorized), the getOrderItems operation does not return information about pricing, taxes, shipping charges, gift status or promotions for the order items in the order. After an order leaves the Pending state (this occurs when payment has been authorized) and enters the Unshipped, Partially Shipped, or Shipped state, the getOrderItems operation returns information about pricing, taxes, shipping charges, gift status and promotions for the order items in the order.**_

Thanks
PN

**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**

**URL of the content on GitHub**
Please provide the GitHub URL for the documentation where you see the bug.

**Description of what the documentation currently says**
Please describe the section/paragraph of the documentation where you see the bug.

**Description of what the documentation should say**
A clear and concise description of the guidance you expected to see in the documentation.

**Screenshots**

**Additional context**

**Comment by nodisk8800** [comment]
Your can call finances API to get all Commission about the orders.

**Comment by pnamroud** [comment]
Thanks for the feedback.
I tried by calling Finances API (/api/Finances/ListFinancialEventsByOrderId) as per your recommendation, and this is what I got:
{   "payload": {     "nextToken": null,     "financialEvents": {       "retrochargeEventList": [],       "rentalTransactionEventList": [],       "productAdsPaymentEventList": [],       "serviceFeeEventList": []     }   },   "hasError": false,   "message": null,   "statusCode": 200 }


That is why I am going back to find out wether the Get Order Items API is buggy or the the documentation is misleading....

Thanks again
PN

**Comment by nodisk8800** [comment]
If OrderStatus = Shipped,
I can get Taxes, Commission, shipping charges... success by  GetOrderItems in SPAPI or  ListOrderItems in MWS API.
And I call Finances in MWS API, they are also return.

If any problem in your seller account or your developer account ?

**Comment by abhi-112** [comment]
@pnamroud any resolution as of now??? as i am also getting the same error

**Comment by abhi-112** [comment]
@pnamroud so what am I needed to do to get the proper response??

**Comment by pnamroud** [comment]
@abhi-112 What you need to do is make sure the returning Json object is being built correctly in your code. At the time, when we were testing the one provided by Amazon docs, was missing objects and elements attributes.
Second, try the call to a production account, it should give better result.

Thanks and hope this helps
