### ISSUE TITLE
SPDC300 Error

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#408]
Hello,

I am getting this error while creating a SP application is seller central. My developer profile has already been approved. This is the error I am getting -

Something went wrongPlease try again at a later time If the problem persists, please contact Seller Support and provide them with the following information: SPDC300

I have already opened a case on Seller Central and the CASE ID is - 7990344371

Can someone please assist me with this ?

**Comment by ShivikaK** [comment]
Hello @hkncnr07 

Thank you for raising this issue and sharing the case ID. 

The case has been expedited for resolution and the Support Engineer has responded to the case with next steps. Please continue monitoring the case for follow-ups.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
