### ISSUE TITLE
[FEATURE] Documentation /api/Finances/ListFinancialEventsByOrderId NOT functionning

### ISSUE THREAD

**Issue by pnamroud** [amzn/selling-partner-api-docs#409]
Hello Team,
I tried calling Finances API (/api/Finances/ListFinancialEventsByOrderId) and this is what I got:

{ "payload": { "nextToken": null, "financialEvents": { "retrochargeEventList": [], "rentalTransactionEventList": [], "productAdsPaymentEventList": [], "serviceFeeEventList": [] } }, "hasError": false, "message": null, "statusCode": 200 }

Note, it works when we all the Sandbox, but not when we call it for PRoduction US marketplace or German MArketplace.

Thanks, ad looking forward to receive your recommendation

Pierre

**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the improvement**
A clear and concise description of the improvement you are proposing.

**URL of the content on GitHub**
Please provide the GitHub URL for the documentation content that could be improved.

**Description of what the documentation currently says**
Please describe the section/paragraph of the documentation where you see the bug.

**Description of what the documentation should say**
A clear and concise description of the guidance you propose to see in the documentation.

**Screenshots**

**Additional context**

**Comment by estebanangel** [comment]
Same problem here

**Comment by pnamroud** [comment]
@estebanangel 
The way we fixed it is  y manually adding the json models for this  API to our code.
Initially, we used the json model provided by the SP API team; however it was not up to date.
As soon as we fixed it and added the missing json objects, we got it working

Hope that points you to the correct path

Thanks
PN

**Comment by pprbhm** [comment]
Thanks @estebanangel  for doing Trial and Error and solving the problem. I will add that as one of the resolves and hopefully others having the same issue can be able to solve it by the method suggested by you or contacting Developer support team. I am closing the issue now.

**Comment by stefnats** [comment]
Hey @pnamroud i'm having a similar issue.

Are you refering to this PR?
https://github.com/amzn/selling-partner-api-models/pull/21

Or can you tell us what you exactly made when you `added the missing json objects`?

Thanks in advance!

**Comment by pnamroud** [comment]
@***@***.***>
Based on the models provided by Amazon SP-API team that we imported initially, it was missing a lots of json elements and arrays for the finance API (and other endpoints also); meaning it was not up-to-date.

The developer had to modify his C# code and add each missing object manually.
Once he did that, we started getting a good json result, similar to the one in the following screenshot, which you can use to fix your own json

Hope this helps

{
  "hasError": true,
  "message": "string",
  "statusCode": 0,
  "errors": [
    {
      "code": "string",
      "message": "string",
      "details": "string"
    }
  ],
  "payload": {
    "nextToken": "string",
    "financialEvents": {
      "retrochargeEventList": [
        {
          "retrochargeEventType": "string",
          "amazonOrderId": "string",
          "postedDate": "2021-04-09T13:26:02.667Z",
          "baseTax": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "shippingTax": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "marketplaceName": "string",
          "retrochargeTaxWithheldList": [
            {
              "taxCollectionModel": "string",
              "taxesWithheld": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ]
            }
          ]
        }
      ],
      "rentalTransactionEventList": [
        {
          "amazonOrderId": "string",
          "rentalEventType": "string",
          "extensionLength": 0,
          "postedDate": "2021-04-09T13:26:02.667Z",
          "rentalChargeList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "rentalFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "marketplaceName": "string",
          "rentalInitialValue": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "rentalReimbursement": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "rentalTaxWithheldList": [
            {
              "taxCollectionModel": "string",
              "taxesWithheld": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ]
            }
          ]
        }
      ],
      "productAdsPaymentEventList": [
        {
          "postedDate": "2021-04-09T13:26:02.667Z",
          "transactionType": "string",
          "invoiceId": "string",
          "baseValue": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxValue": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "transactionValue": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "serviceFeeEventList": [
        {
          "amazonOrderId": "string",
          "feeReason": "string",
          "feeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
           }
          ],
          "sellerSKU": "string",
          "fnSKU": "string",
          "feeDescription": "string",
          "asin": "string"
        }
      ],
      "shipmentEventList": [
        {
          "amazonOrderId": "string",
          "sellerOrderId": "string",
          "marketplaceName": "string",
          "orderChargeList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderChargeAdjustmentList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentFeeAdjustmentList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
         ],
          "orderFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderFeeAdjustmentList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "directPaymentList": [
            {
              "directPaymentType": "string",
              "directPaymentAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "postedDate": "2021-04-09T13:26:02.667Z",
          "shipmentItemList": [
            {
              "sellerSKU": "string",
              "orderItemId": "string",
              "orderAdjustmentItemId": "string",
              "quantityShipped": 0,
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemChargeAdjustmentList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeAdjustmentList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemTaxWithheldList": [
                {
                  "taxCollectionModel": "string",
                  "taxesWithheld": [
                    {
                      "chargeType": "string",
                      "chargeAmount": {
                        "currencyCode": "string",
                        "currencyAmount": 0
                      }
                    }
                  ]
                }
              ],
              "promotionList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "promotionAdjustmentList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                   "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "costOfPointsGranted": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "costOfPointsReturned": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentItemAdjustmentList": [
            {
              "sellerSKU": "string",
              "orderItemId": "string",
              "orderAdjustmentItemId": "string",
              "quantityShipped": 0,
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemChargeAdjustmentList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeAdjustmentList": [
                {
                 "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemTaxWithheldList": [
                {
                  "taxCollectionModel": "string",
                  "taxesWithheld": [
                    {
                      "chargeType": "string",
                      "chargeAmount": {
                        "currencyCode": "string",
                        "currencyAmount": 0
                      }
                    }
                  ]
                }
              ],
              "promotionList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "promotionAdjustmentList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "costOfPointsGranted": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "costOfPointsReturned": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ]
        }
      ],
      "refundEventList": [
        {
          "amazonOrderId": "string",
          "sellerOrderId": "string",
          "marketplaceName": "string",
          "orderChargeList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderChargeAdjustmentList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentFeeAdjustmentList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderFeeAdjustmentList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "directPaymentList": [
            {
              "directPaymentType": "string",
              "directPaymentAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "postedDate": "2021-04-09T13:26:02.668Z",
          "shipmentItemList": [
            {
              "sellerSKU": "string",
              "orderItemId": "string",
              "orderAdjustmentItemId": "string",
              "quantityShipped": 0,
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemChargeAdjustmentList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeAdjustmentList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemTaxWithheldList": [
                {
                  "taxCollectionModel": "string",
                  "taxesWithheld": [
                    {
                      "chargeType": "string",
                      "chargeAmount": {
                        "currencyCode": "string",
                        "currencyAmount": 0
                      }
                    }
                  ]
                }
              ],
              "promotionList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "promotionAdjustmentList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "costOfPointsGranted": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "costOfPointsReturned": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentItemAdjustmentList": [
            {
              "sellerSKU": "string",
              "orderItemId": "string",
              "orderAdjustmentItemId": "string",
              "quantityShipped": 0,
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemChargeAdjustmentList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeAdjustmentList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemTaxWithheldList": [
                {
                  "taxCollectionModel": "string",
                  "taxesWithheld": [
                    {
                      "chargeType": "string",
                      "chargeAmount": {
                        "currencyCode": "string",
                        "currencyAmount": 0
                      }
                    }
                  ]
                }
              ],
              "promotionList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "promotionAdjustmentList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "costOfPointsGranted": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "costOfPointsReturned": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ]
        }
      ],
      "guaranteeClaimEventList": [
        {
          "amazonOrderId": "string",
          "sellerOrderId": "string",
          "marketplaceName": "string",
          "orderChargeList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderChargeAdjustmentList": [
            {
              "chargeType": "string",
              "chargeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentFeeAdjustmentList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderFeeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "orderFeeAdjustmentList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "directPaymentList": [
            {
              "directPaymentType": "string",
              "directPaymentAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "postedDate": "2021-04-09T13:26:02.668Z",
          "shipmentItemList": [
            {
              "sellerSKU": "string",
              "orderItemId": "string",
              "orderAdjustmentItemId": "string",
              "quantityShipped": 0,
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemChargeAdjustmentList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeAdjustmentList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemTaxWithheldList": [
                {
                  "taxCollectionModel": "string",
                  "taxesWithheld": [
                    {
                      "chargeType": "string",
                      "chargeAmount": {
                        "currencyCode": "string",
                        "currencyAmount": 0
                      }
                    }
                  ]
                }
              ],
              "promotionList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "promotionAdjustmentList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "costOfPointsGranted": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "costOfPointsReturned": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "shipmentItemAdjustmentList": [
            {
              "sellerSKU": "string",
              "orderItemId": "string",
              "orderAdjustmentItemId": "string",
              "quantityShipped": 0,
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemChargeAdjustmentList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemFeeAdjustmentList": [
                {
                  "feeType": "string",
                  "feeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "itemTaxWithheldList": [
                {
                  "taxCollectionModel": "string",
                  "taxesWithheld": [
                    {
                      "chargeType": "string",
                      "chargeAmount": {
                        "currencyCode": "string",
                        "currencyAmount": 0
                      }
                    }
                  ]
                }
              ],
              "promotionList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "promotionAdjustmentList": [
                {
                  "promotionType": "string",
                  "promotionId": "string",
                  "promotionAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "costOfPointsGranted": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "costOfPointsReturned": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ]
        }
      ],
      "payWithAmazonEventList": [
        {
          "sellerOrderId": "string",
          "transactionPostedDate": "2021-04-09T13:26:02.668Z",
          "businessObjectType": "string",
          "salesChannel": "string",
          "charge": {
            "chargeType": "string",
            "chargeAmount": {
              "currencyCode": "string",
              "currencyAmount": 0
            }
          },
          "feeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ],
          "paymentAmountType": "string",
          "amountDescription": "string",
          "fulfillmentChannel": "string",
          "storeName": "string"
        }
      ],
      "serviceProviderCreditEventList": [
        {
          "providerTransactionType": "string",
          "sellerOrderId": "string",
          "marketplaceId": "string",
          "marketplaceCountryCode": "string",
          "sellerId": "string",
          "sellerStoreName": "string",
          "providerId": "string",
          "providerStoreName": "string",
          "transactionAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "transactionCreationDate": "2021-04-09T13:26:02.668Z"
        }
      ],
      "sellerDealPaymentEventList": [
        {
          "postedDate": "2021-04-09T13:26:02.668Z",
          "dealId": "string",
          "dealDescription": "string",
          "eventType": "string",
          "feeType": "string",
          "feeAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "totalAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "debtRecoveryEventList": [
        {
          "debtRecoveryType": "string",
          "recoveryAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "overPaymentCredit": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "debtRecoveryItemList": [
            {
              "recoveryAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "originalAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "groupBeginDate": "2021-04-09T13:26:02.668Z",
              "groupEndDate": "2021-04-09T13:26:02.668Z"
            }
          ],
          "chargeInstrumentList": [
            {
              "description": "string",
              "tail": "string",
              "amount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ]
        }
      ],
      "loanServicingEventList": [
        {
          "loanAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "sourceBusinessEventType": "string"
        }
      ],
      "adjustmentEventList": [
        {
          "adjustmentType": "string",
          "postedDate": "2021-04-09T13:26:02.668Z",
          "adjustmentAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "adjustmentItemList": [
            {
              "quantity": "string",
              "perUnitAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "totalAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              },
              "sellerSKU": "string",
              "fnSKU": "string",
              "productDescription": "string",
              "asin": "string"
            }
          ]
        }
      ],
      "safetReimbursementEventList": [
        {
          "postedDate": "2021-04-09T13:26:02.668Z",
          "safetClaimId": "string",
          "reimbursedAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "reasonCode": "string",
          "safetReimbursementItemList": [
            {
              "itemChargeList": [
                {
                  "chargeType": "string",
                  "chargeAmount": {
                    "currencyCode": "string",
                    "currencyAmount": 0
                  }
                }
              ],
              "productDescription": "string",
              "quantity": "string"
            }
          ]
        }
      ],
      "sellerReviewEnrollmentPaymentEventList": [
        {
          "postedDate": "2021-04-09T13:26:02.668Z",
          "enrollmentId": "string",
          "parentASIN": "string",
          "feeComponent": {
            "feeType": "string",
            "feeAmount": {
              "currencyCode": "string",
             "currencyAmount": 0
            }
          },
          "chargeComponent": {
            "chargeType": "string",
            "chargeAmount": {
              "currencyCode": "string",
              "currencyAmount": 0
            }
          },
          "totalAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "fbaLiquidationEventList": [
        {
          "postedDate": "2021-04-09T13:26:02.668Z",
          "originalRemovalOrderId": "string",
          "liquidationProceedsAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "liquidationFeeAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "couponPaymentEventList": [
        {
          "postedDate": "2021-04-09T13:26:02.668Z",
          "couponId": "string",
          "sellerCouponDescription": "string",
          "clipOrRedemptionCount": 0,
          "paymentEventId": "string",
          "feeComponent": {
            "feeType": "string",
            "feeAmount": {
              "currencyCode": "string",
              "currencyAmount": 0
            }
          },
         "chargeComponent": {
            "chargeType": "string",
            "chargeAmount": {
              "currencyCode": "string",
              "currencyAmount": 0
            }
          },
          "totalAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "imagingServicesFeeEventList": [
        {
          "imagingRequestBillingItemID": "string",
          "asin": "string",
          "postedDate": "2021-04-09T13:26:02.668Z",
          "feeList": [
            {
              "feeType": "string",
              "feeAmount": {
                "currencyCode": "string",
                "currencyAmount": 0
              }
            }
          ]
        }
      ],
      "networkComminglingTransactionEventList": [
        {
          "transactionType": "string",
          "postedDate": "2021-04-09T13:26:02.668Z",
          "netCoTransactionID": "string",
          "swapReason": "string",
          "asin": "string",
          "marketplaceId": "string",
          "taxExclusiveAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxAmount": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "affordabilityExpenseEventList": [
        {
          "amazonOrderId": "string",
          "postedDate": "2021-04-09T13:26:02.668Z",
          "marketplaceId": "string",
          "transactionType": "string",
          "baseExpense": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxTypeCGST": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxTypeSGST": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxTypeIGST": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "totalExpense": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ],
      "affordabilityExpenseReversalEventList": [
        {
          "amazonOrderId": "string",
          "postedDate": "2021-04-09T13:26:02.668Z",
          "marketplaceId": "string",
          "transactionType": "string",
          "baseExpense": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxTypeCGST": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxTypeSGST": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "taxTypeIGST": {
            "currencyCode": "string",
            "currencyAmount": 0
          },
          "totalExpense": {
            "currencyCode": "string",
            "currencyAmount": 0
          }
        }
      ]
    }
  }
}


________________________________
Please note our monitored support email ***@***.******@***.***>

Have a great day
P.S. Read our latest top (5) blogs:
How Integration can improve your supply chain management<https://www.edi2xml.com/blog/how-integration-can-improve-your-supply-chain-management/>
The Top 6 EDI Documents for Retail<https://www.edi2xml.com/blog/the-top-6-edi-documents-for-retail-suppliers/> Suppliers
What is EDI 855 Purchase Order Acknowledgment?<https://www.edi2xml.com/blog/what-is-edi-855-purchase-order-acknowledgment/>
EDI for transportation – EDI 214 Transportation Carrier Shipment Status Message<https://www.edi2xml.com/blog/edi-for-transportation-edi-214-transportation-carrier-shipment-status-message/>
Amazon Seller data automation and integration: Tips and Tricks<https://www.edi2xml.com/blog/amazon-seller-data-automation-and-integration-tips-and-tricks/>
Our Blog<https://www.edi2xml.com/blog/> was selected by Feedspot as one of the Top 10 EDI (Electronic Data Interchange) Blogs<https://blog.feedspot.com/electronic_data_interchange_blogs/> on the web.

Pierre Namroud (Msc. Eng.)



***@***.***D72D23.15E95F00]

Feel free to visit our blog and share its content <http://www.edi2xml.com/blog/>

  ***@***.***D72D23.15E95F00] <https://u3168881.ct.sendgrid.net/wf/click?upn=8LlbERTCqTShljT-2FrlLY2gEn4oqhEBlB5DQM4ZVQKTxuZGOjE9Ep3bpsEloxbzft3ge5oWrvFv-2BMXtJeSN2wq-2FIAnGPUXBqMVB3WykS6A4FsYqORfl0ptcXp-2FVyHFu4mmSIMBc0nIv8JN4NJhdzma1i4BGJrQWUmrFp-2B5tMg-2Ftoc4Ver9lLub42xSgXrumfA45Z7Ou1y-2FyzgJXoaN0Q4v4rwXDtW3uUKgJQQyXnTydXJSGPR5gfiwyVkLBNdu2fKCRI9o3I8X5GEG2zvXPgoFINtjCv78PpOSaf86pU5WkdcKWq4otCGenqlC4Q0drFVYUNLH5t-2FLqb7spwhbOpWrQ-3D-3D_t8mGnzu6DrfeL4DO4lZD3b7ppcIKBiPSSER8wrv4izzFZg-2FIk1FPwlRxEPRoxh-2FVS6JGziIfFV9U-2BdFdV5MRPYO9soFGT26FrbFL0HkAERVd2MBRLg7kV96jWHI7gRtLVM44omHwqts2Gq26YyA0-2BbvSTclqDnSBUNimYH8oJmAbK6O7cLon7G3B9-2F-2BqUauSl9wbhQURcAxBiT5WVGCAYhe9-2FaQ7Y-2BRLAJIbvmVZjFM-3D>   ***@***.***D72D23.15E95F00] <https://u3168881.ct.sendgrid.net/wf/click?upn=8LlbERTCqTShljT-2FrlLY2gEn4oqhEBlB5DQM4ZVQKTxuZGOjE9Ep3bpsEloxbzft3ge5oWrvFv-2BMXtJeSN2wq-2FIAnGPUXBqMVB3WykS6A4FsYqORfl0ptcXp-2FVyHFu4mmSIMBc0nIv8JN4NJhdzma1i4BGJrQWUmrFp-2B5tMg-2Ftr89upNjC4vt2d-2FBKpczvfeQG5M8U30bSaSO6drxvEe-2F6ow9c0kEPEVvZ7Bcrfj2mavLHMftGNmJPIFvSWc3hcNZErdgxbplqv8BR0RGynDtSQYPXOUfFtFFRdY-2FVgseQAXGipti0KpfnXxY-2FSctUKW_t8mGnzu6DrfeL4DO4lZD3b7ppcIKBiPSSER8wrv4izzFZg-2FIk1FPwlRxEPRoxh-2FVS6JGziIfFV9U-2BdFdV5MRPRCROPSKsGac0rE2asA2r5OceiuLUx9T4-2FZ2yvbVQHeP3JSj7gxBuNc4SZ9-2FnKw89LePrhGPqIdSxFXOLQvkK4iySkCCfIoYFrabTBbIMmXUx9SGs9-2BS8-2FE1sZSngs-2BuL91RwBjhATHoUjGuM8Qa5QU-3D>   ***@***.***D72D23.15E95F00] <https://u3168881.ct.sendgrid.net/wf/click?upn=a7xpjGjw-2BMRmjTLew6sej7E0MbFiEuw70R1mNyotB57mTpUmrL-2FokFLgaFO-2Bhc8aHPuRC1DwEgXTG6mVM-2FhD3A-3D-3D_t8mGnzu6DrfeL4DO4lZD3b7ppcIKBiPSSER8wrv4izzFZg-2FIk1FPwlRxEPRoxh-2FVS6JGziIfFV9U-2BdFdV5MRPX4AGU0-2BR6j0y4gjCksRkFHNVlkeqOaIu-2FclPKTA3UfqLqeYG9RNniGH0ZL-2BK0Tapul-2BlkPYoqOLsSx1fu6FG492usi-2F92LhWwWDsAN03N9rds4heD2jhSYAj-2FIsEqZTdsO-2BbQAm6j-2BAQOF9UIKDP3k-3D>




EDI2XML (by Namtek Consulting Services)
400, Curé-Labelle #304
Chomedey, Laval,
QC. H7V 2S7 <https://goo.gl/maps/4xKXg9yfXrt>
Tel: (450) 681-3009 Ext. 223<https://u3168881.ct.sendgrid.net/wf/click?upn=8LlbERTCqTShljT-2FrlLY2gEn4oqhEBlB5DQM4ZVQKTxuZGOjE9Ep3bpsEloxbzft3ge5oWrvFv-2BMXtJeSN2wq-2FIAnGPUXBqMVB3WykS6A4FsYqORfl0ptcXp-2FVyHFu4mmSIMBc0nIv8JN4NJhdzma-2B2fvIQGXYd2BkDxyovA-2F0iTtUCg9aFtA5WmGcwTID0sB0rO6lAabYmSaLfNEL38GjKHIjeqhRRutL0w5Yb5Cjw7rV8U09xtrOlpJmKT905xgHZLw31BynPA-2FKJyvHrtUQ-3D-3D_t8mGnzu6DrfeL4DO4lZD3b7ppcIKBiPSSER8wrv4izzFZg-2FIk1FPwlRxEPRoxh-2FVS6JGziIfFV9U-2BdFdV5MRPa8sy8UAY3SrelWM9WTxgeLRpbNtA0oCVFZplUu238vQDvo2d-2FE5gi7Tn8HrOXRopoXWs479h0UtBSlmDSLdqjLIeLV16gXnZpJIipMGp49EFchS47xd6YWIjRk-2FdEjVHZs95JBDNZCAtK2TPQgLPNk-3D>
***@***.******@***.***>
***@***.***D72D23.15E95F00]
