### ISSUE TITLE
OAuth changing market place

### ISSUE THREAD

**Issue by mohamedfawzy96** [amzn/selling-partner-api-docs#412]
So when I redirect the user to authorize using the https://sellercentral.amazon.com/apps/authorize/consent url. When the user changes the market place from the drop down the authorization page shows this error
![image](https://user-images.githubusercontent.com/16167016/108081956-d4e00a80-7071-11eb-967a-cd5fb4e63008.png)

What I realised is when the market place changes the consent url parameters gets overriden so the application_id is removed and the client id and secret

**Comment by nodisk8800** [comment]
Note. For sellers who sell in the Spain, UK, France, Germany, and Italy marketplaces, you can use the Seller Central URL for Europe when creating an OAuth authorization URI. Example: https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.0bf296b5-36a6-4942-a13e-EXAMPLEfcd28

**Comment by nodisk8800** [comment]
You will need an OAuth authorization URI for every marketplace where you want sellers to authorize your application. Simply use the appropriate Seller Central URL in each OAuth authorization URI that you need.

**Comment by mohamedfawzy96** [comment]
Okay thank you! but would be possible to select a specific market place for example germany ?

**Comment by nodisk8800** [comment]
@mohamedfawzy96 
Yes,you can.
But you also can OAuth any marketplace in same Region.
For example, at EU Region,contain marketplace UK/DE/FR/IT/ES/NL/SE...
you can OAuth one of any UK/DE/FR/IT/ES/NL/SE... marketplace.
The refreshtoken can used for all of EU Region(UK/DE/FR/IT/ES/NL/SE...)

**Comment by tspicer** [comment]
@nodisk8800 , does the OAuth support multi-marketplace sellers? I know this is more common in the EU? I assume yes, but wanted to confirm

**Comment by nodisk8800** [comment]
@tspicer
OAuth support multi-marketplace sellers in the same Region.
