### ISSUE TITLE
[BUG] reportType： GET_FLAT_FILE_OPEN_LISTINGS_DATA，The 'quantity'  field data in all  the generated report is 0 or empty

### ISSUE THREAD

**Issue by lzy6666666** [amzn/selling-partner-api-docs#414]
The field Quantity data in the generated report is 0 or is directly missing

**Comment by nodisk8800** [comment]
这个是不是应该算正常啊? 自己逻辑处理一下数量的问题

**Comment by lzy6666666** [comment]
> 这个是不是应该算正常啊？自己逻辑处理一下数量的问题

是报告中所有的sku都没有库存，店铺后台是有库存的

**Comment by nodisk8800** [comment]
是不是站点不对应啊?
库存在 UK,你却通过 DE 的MarketplaceID去下载

**Comment by lzy6666666** [comment]
> 是不是站点不对应啊？
> 库存在英国，你却通过DE的MarketplaceID去下载

我是美国站，用的是ATVPDKIKX0DER，你获取GET_FLAT_FILE_OPEN_LISTINGS_DATA这个报告是正常的吗？

**Comment by codingkondi** [comment]
> > 是不是站点不对应啊？
> > 库存在英国，你却通过DE的MarketplaceID去下载
> 
> 我是美国站，用的是ATVPDKIKX0DER，你获取GET_FLAT_FILE_OPEN_LISTINGS_DATA这个报告是正常的吗？

maybe the account seller setting relative config made the column be ignored.

**Comment by lzy6666666** [comment]
> > > 是不是站点不对应啊？
> > > 库存在英国，你却通过DE的MarketplaceID去下载
> > 
> > 
> > 我是美国站，用的是ATVPDKIKX0DER，你获取GET_FLAT_FILE_OPEN_LISTINGS_DATA这个报告是正常的吗？
> 
> 也许帐户卖方设置相对配置使该列被忽略。
I tested multiple stores and the results were the same


> > > 是不是站点不对应啊？
> > > 库存在英国，你却通过DE的MarketplaceID去下载
> > 
> > 
> > 我是美国站，用的是ATVPDKIKX0DER，你获取GET_FLAT_FILE_OPEN_LISTINGS_DATA这个报告是正常的吗？
> 
> maybe the account seller setting relative config made the column be ignored.

I tested multiple stores and the results were the same

**Comment by zhnc9** [comment]
it works fine in my side, you can test it in demo project, https://github.com/aws-samples/selling-partner-api-bootstrap

class cn.amazon.aws.rp.spapi.clients.api.ReportsApiIT

to verify it first.

Thanks.

**Comment by codingkondi** [comment]
> > > > 是不是站点不对应啊？
> > > > 库存在英国，你却通过DE的MarketplaceID去下载
> > > 
> > > 
> > > 我是美国站，用的是ATVPDKIKX0DER，你获取GET_FLAT_FILE_OPEN_LISTINGS_DATA这个报告是正常的吗？
> > 
> > 
> > 也许帐户卖方设置相对配置使该列被忽略。
> > I tested multiple stores and the results were the same
> 
> > > > 是不是站点不对应啊？
> > > > 库存在英国，你却通过DE的MarketplaceID去下载
> > > 
> > > 
> > > 我是美国站，用的是ATVPDKIKX0DER，你获取GET_FLAT_FILE_OPEN_LISTINGS_DATA这个报告是正常的吗？
> > 
> > 
> > maybe the account seller setting relative config made the column be ignored.
> 
> I tested multiple stores and the results were the same

maybe u could make sure that these seller account is FBA or not

**Comment by pprbhm** [comment]
Hello, We can assist you with more specific details if you would like to head over and create a [support case](https://developer.amazonservices.com/support) for Developer Support team.
