### ISSUE TITLE
Why Step 1 of SP-API is registering from seller central? What if 3rd party not able to apply seller account?

### ISSUE THREAD

**Issue by HalaLiu** [amzn/selling-partner-api-docs#415]
To whom it may concern,

If a 3rd party solution provider want to develop an APP for selling partners, like logistics company or financing institution, their credentials may not qualified to be a seller. Is there any other solutions?

Hala

**Comment by jbarradas980** [comment]
Have you found a solution?

**Comment by HalaLiu** [comment]
no, I think we should either provide a special seller account for these 3rd parties, or start SP-API from somewhere outside of seller central.

Hala

**Comment by jbarradas980** [comment]
Hi! 
I think the same, but I think it is because they want to have more control. 
I created a seller account and sent the corresponding documentation, but i have to fill out another form to register as a developer from the Seller Centerand wait for them to authorize me.
