### ISSUE TITLE
Uploading feed data error

### ISSUE THREAD

**Issue by GrelaM100** [amzn/selling-partner-api-docs#417]
Hi,
Currently I am facing problem with uploading feed data. First step works fine, I use createFeedDocument, then when I try to use url and encryptionDetails from response I get error: "The request signature we calculated does not match the signature you provided. Check your key and signing method.". When I am trying to calculate signature like in createFeedDocument call, I get another error telling me that I can use only one authorization method. Can someone help me? What can cause this error? Working C# code examples would also be helpful.

**Comment by nodisk8800** [comment]
@GrelaM100 
Upload document are not need to calculate the signature.
Because createFeedDocument return the url contain the signature.
You must upload the same ContentType file as createFeedDocument .

**Comment by CebulMaciej** [comment]
@nodisk8800 application/json is allowed?

**Comment by nodisk8800** [comment]
@CebulMaciej 

I think contentType="text/xml; charset=UTF-8"  is used a more lot.
FeedAPI need upload XML file.

**Comment by CebulMaciej** [comment]
@nodisk8800 could you send any working example of xml file?
