### ISSUE TITLE
[BUG]: oAuth flow authorization broken

### ISSUE THREAD

**Issue by tomhirschfeld** [amzn/selling-partner-api-docs#418]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**

during oAuth flow, the text "null" is present in the auth flow for the use authorizing the application where a name or some other identifier should be present

**Screenshots**

![image](https://user-images.githubusercontent.com/3522001/108410044-c877c100-71db-11eb-95b8-ee99b549b3a0.png)

**Comment by tomhirschfeld** [comment]
When looking at the network activity on the tab, I see the following 

post call to: 
```
https://sellercentral.amazon.com/apps/apis/cloudauth/oauth/applications/{id}/authInfo?application_stage=draft
```
returns
```
{"name":null,"id":"{id}","provider":{"id":"{id}","name":"ROI Brand Marketing"...
```

and it looks like the name should be populated here. Is this the issue? If so, what can i do to ensure the name is populated?

**Comment by ShivikaK** [comment]
Hello @tomhirschfeld 

Thank you for raising this issue.

This bug has been identified by the engineering team and we are working on providing a fix for this issue with high priority.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by tomhirschfeld** [comment]
any updates here?

 this is extremely high priority for us

**Comment by tomhirschfeld** [comment]
@ShivikaK pinging this ticket again, this is now blocking a client facing launch with us. Any ETA to fix?

**Comment by siddhartha-reckonsys** [comment]
@ShivikaK Shivika, do we have any update on this?

**Comment by jlevers** [comment]
This is also high priority for me -- a timeline estimate would be much appreciated.

**Comment by ShivikaK** [comment]
Hello everyone,

We are seeking to confirm an ETA with our engineering team regarding this issue and I will let you know once I have a timeline for the fix.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by tomhirschfeld** [comment]
@ShivikaK pinging here again, been about a day since last update

**Comment by ShivikaK** [comment]
Hello everyone,

The issue with oAuth workflow process has now been fixed and you should be able to proceed without any issues.

If you do see any error, please let us know and we will into it further.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by siddhartha-reckonsys** [comment]
@ShivikaK Shivika, i created a Hybrid app. But cannot save and continue in the App Listings page.

**Comment by ShivikaK** [comment]
Hello @siddhartha-reckonsys 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello everyone,

As the error reported here has been fixed, I am closing this issue.

Please open a new issue or support case with us for any other errors you encounter.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
