### ISSUE TITLE
OAuth authorization URIs for non-NA and non-EU marketplaces?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#419]
**Describe the improvement**

Seller Central URL for OAuth authorization aren't very clear.

By the docs, it sounds like every marketplace that is not part of "Spain, UK, France, Germany, and Italy" should be using NA URI.

Maybe that is intentional, but it is definitely confusing.

Because there are more countries in the EU. But there are also countries outside of EU and NA.

**URL of the content on GitHub**

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#oauth-authorization-uris

**Description of what the documentation currently says**

> Note. For sellers who sell in the Spain, UK, France, Germany, and Italy marketplaces, you can use the Seller Central URL for Europe when creating an OAuth authorization URI. Example: https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.0bf296b5-36a6-4942-a13e-EXAMPLEfcd28

**Description of what the documentation should say**

There should probably be a clear table, like for regions, for each marketplace and the OAuth link.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by nodisk8800** [comment]
没有问题,OAuth和API都可以正常工作.

**Comment by Syntaf** [comment]
I'm in the same boat as your @moltar, I don't quite understand what URLs we should be using for sellers outside of Europe and North America.

I found this link which at first seems to answer the question:

https://sellercentral.amazon.com/gp/help/help.html?itemID=G201062890&language=en_US

What's weird however is that these URLs don't match the documentation. For example The docs say to use `https://sellercentral-europe.amazon.com` but the link above specifies the European markets under `https://sellercentral.amazon.co.uk`. There's also far more regions listed compared to the documentation.

So how exactly do we build OAuth URLs for regions outside of Europe?

**Comment by zhanglaoye** [comment]
I have the same problem, I want to know how to authorize the Middle East and Australia, Singapore

**Comment by zhanglaoye** [comment]
According to the document, Japan, Australia, and Singapore belong to fe. After I authorize Japan, I will report an error Invalid Input when I visit Australia.

**Comment by AmichayMiara** [comment]
Same confusion
