### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by rodrigojob** [amzn/selling-partner-api-docs#42]
Have a lot simple erros in documentation, for example in https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-and-sign-your-request

Authorization: AWS4-HMAC-SHA25 Credential=AKIDEXAMPLE/20190430/us-east1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-accesstoken;xamz-date, Signature=5d672d79c15b13162d9279b0855cfba6789a8edb4c82c400e06b5924aEXAMPLE

AWS4-HMAC-SHA25 - correct is **AWS4-HMAC-SHA256**
x-amz-accesstoken - correct is **x-amz-access-token**
xamz-date - correct is **x-amz-date**
AKIDEXAMPLE : don't have explanation what is this value. Perhaps IAM Access Key?

In one line have 3 error ou 4.

I'm trying create the signature, but I am not trusting the information on the page. I lost 4 hours.

**Comment by seanevan** [comment]
@rodrigojob Thanks for reporting this, and I'm sorry you lost so much time due to these issues. We are working to correct this in our documentation.

**Comment by parvathm** [comment]
Thank you for reporting these typos. We have fixed them and updated the dev guide.

Thanks,
Parvathm
Amazon MWS Support.
