### ISSUE TITLE
Access to requested resource is denied - code Unauthorized - No details

### ISSUE THREAD

**Issue by SupersmartSA** [amzn/selling-partner-api-docs#420]
Hi, I have some difficult to connect API.
I have open a case on 6778278712 but at this day, no solution are get.

I make API in PERL with CURL query. 

I have make IAM user and rôle, link my application on seller central to ARN rôle like it's suggest.
AWS user rights :
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::[accountId]:role/SellerPartnerAPI"
        }
    ]
}
AWS role : arn:aws:iam::[accountId]:role/SellerPartnerAPI with Policy
AWS policy : 
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}
First step to get the Access token is ok with refresh token, application key and private parameters. I get the access token

Second step to make header it's OK, I had get some specifique error with the header before, but It's ok now. But I have an access denied. developer profil is ok and application have the the right selected

Here an exemple of query (It's the same result for all I have try)

CANONICAL_REQUEST : 
GET
/orders/v0/orders
MarketplaceIds=A13V1IB3VIYZZH&OrderStatuses=Unshipped
host:sellingpartnerapi-eu.amazon.com
user-agent:smartis/beta (Language=Perl; Host=loc.supersmart.com)
x-amz-access-token:Atza|[...]
x-amz-date:20210216T084319Z

host;user-agent;x-amz-access-token;x-amz-date
[CRYPTED VALUE]

STRING_TO_SIGN : 
AWS4-HMAC-SHA256
20210216T084319Z
20210216/eu-west-1/execute-api/aws4_request
[CRYPTED VALUE]

REQUEST :
url : https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?OrderStatuses=Unshipped&MarketplaceIds=A13V1IB3VIYZZH
HEADER : 
Authorization: AWS4-HMAC-SHA256 Credential=[AWS USER KEY]/20210216/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date, Signature=[CRYPTED VALUE]
host: sellingpartnerapi-eu.amazon.com
user-agent: smartis/beta (Language=Perl; Host=loc.supersmart.com)
x-amz-access-token: Atza|[...]
x-amz-date: 20210216T084319Z

RESPONSE 
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

I have see on forum something with a x-amz-security-token but I don't see how to get it. 
I have see too for temporary IAM token, to assumeRole by API, but call to sts doesn't work for me. 

Best for me is to make all call with CURL, anyone have an idea to be authorized ?

**Comment by pprbhm** [comment]
Hi,
Looks like the case-6778278712 has been resolved and the bug that was related to the case has been fixed. If you still have issues with your request we can help you on more case by case level if you would like to open a case[https://github.com/amzn/selling-partner-api-docs/issues/420](url)
