### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by GbalsaC** [amzn/selling-partner-api-docs#422]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
The Next token value, in it's natural response is not compatible with query URL string as it has + chars present, which become spaces in the query.

Explanation on how to use the NextToken value is necessary when it cannot be just plugged into the next query.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorders

**Description of what the documentation currently says**
It currently states "A string token returned in the response of your previous request." which is incorrect. 

**Description of what the documentation should say**
The Token value returned must be processed differently as it has values such as `+XKVmRZBY+oa` that become `%20XKVmRZBY%20oa` Where in reality, the url might need to be `%2BXKVmRZBY%2Boa` instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/5886517/108566917-d0635e00-72cc-11eb-9f6a-1d0cf15e36f7.png)

**Additional context**
None

**Comment by johnkw** [comment]
All query fields must always be URL-encoded. That's part of the HTTP standard. This is not an SP-API issue.

**Comment by wanghao0123** [comment]
nice, fix my problem

**Comment by parvathm** [comment]
Hi,

As stated above all query parameters should be url encoded and is given in the documentation. I am resolving this issue. Please feel free to open a support case if you need any further clarification.

Thanks,
Parvathm
Selling Partner API Developer Support.
