### ISSUE TITLE
[BUG] getPricing missing pricing data

### ISSUE THREAD

**Issue by darek292** [amzn/selling-partner-api-docs#423]
I've signed up and subscribed to the pricing role recently and I'm testing the API, the following call works as expected:

**GET /products/pricing/v0/competitivePrice** (it uses the same input as getPricing below) - it returns the competitive price with no issues.

Unfortunately this call is not working as expected:

**GET /products/pricing/v0/price**

```
let response = await sellingPartner.callAPI({
  operation:'getPricing',
  query:{
    MarketplaceId:'A1F83G8C2ARO7P',
    Asins: ['B00NH13S44'],
    ItemType: 'Asin'
  }
});
```

Returns

```
[{
  "status": "Success",
  "ASIN": "B00NH13S44",
  "Product": {
    "Identifiers": {
      "MarketplaceASIN": {
        "MarketplaceId": "A1F83G8C2ARO7P",
        "ASIN": "B00NH13S44"
      }
    }
  }
}]
```

This looks like it's missing pricing information? Initially I thought it would only be for my products, but I can call **GET /products/pricing/v0/items/{Asin}/offers** which then return all the offers and their pricing just fine, so that doesn't make sense to me. The sandbox also shows more data than what is actually coming back.

Am I missing something crucial here? I'm also seeing some things from the MWS API not available here, one such example is:

**GetLowestOfferListingsForSKU** which allows for 20 requests (10 items every sec restored) - In contrast, getListingOffers is somewhat close but only applies to one listing (you can only specify one ASIN and you need to specify ItemCondition).

Are there some undocumented APIs still in the work? I need to be able to return the lowest offer for multiple ASINs but it's proving to be difficult, I would love to have access to the MWS API in the interim but unfortunately as I'm a new dev it does not give me the option anywhere to sign up for it. 

@ShivikaK / @parvathm  could you provide some insight on this if possible please? I've been trying a lot of things with no success.

**Comment by daramony** [comment]
I got the same issue here, did you find any solution yet? Did you choose Data Access as "My organization sells on Amazon, and I only want to integrate to manage my own business only", what are your selected roles? Mine are "Product Listing,Pricing".

**Comment by darek292** [comment]
> I got the same issue here, did you find any solution yet? Did you choose Data Access as "My organization sells on Amazon, and I only want to integrate to manage my own business only", what are your selected roles? Mine are "Product Listing,Pricing".

Exactly what you selected for both options and roles, would this maybe why? I need to get an estimation of product data (prices) for automation purposes and if that's the case then I need to update my role.

**Comment by daramony** [comment]
Same to me, have you try changing your Data Access to other than manage your own business?

**Comment by darek292** [comment]
> Same to me, have you try changing your Data Access to other than manage your own business?

I have not, mainly because I am not intending to make an app for others, just primarily to manage own stock.

**Comment by mmalovichko** [comment]
Have got the same issue. I selected _Product Listing_ and _Pricing_ APIs and _My organization builds and offers publicly available applications_ option in my developer profile so shouldn't be Data Access issue
Please let me know if you find the reason

**Comment by daramony** [comment]
Great to know it was not because of the Data Access issue. 
No solution yet, I submitted a support ticket "https://sellercentral.amazon.com/gp/mws/contactus.html" but didn't get a solution from them yet but at least they responded asking for more detail. You should submit your case too,  so they can speed up to solve it.

**Comment by mmalovichko** [comment]
The problem for me turned out to be the wrong input. I was putting a Asins/Skus parameter value in the brackets, e.g. `Asins: ['B00NH13S44']`. As long as I removed them the price was returned correctly: `Asins: 'B00NH13S44'`

**Comment by darek292** [comment]
> The problem for me turned out to be the wrong input. I was putting a Asins/Skus parameter value in the brackets, e.g. `Asins: ['B00NH13S44']`. As long as I removed them the price was returned correctly: `Asins: 'B00NH13S44'`

Do you have a sample snippet? I tried both for **getPricing**, still returns 

```
[{
  "status": "Success",
  "ASIN": "B00NH13S44",
  "Product": {
    "Identifiers": {
      "MarketplaceASIN": {
        "MarketplaceId": "A1F83G8C2ARO7P",
        "ASIN": "B00NH13S44"
      }
    }
  }
}]
```

It should also be taking an array of ASINS, I think you might be using a different call?

**Comment by mmalovichko** [comment]
> > The problem for me turned out to be the wrong input. I was putting a Asins/Skus parameter value in the brackets, e.g. `Asins: ['B00NH13S44']`. As long as I removed them the price was returned correctly: `Asins: 'B00NH13S44'`
> 
> Do you have a sample snippet? I tried both for **getPricing**, still returns
> 
> ```
> [{
>   "status": "Success",
>   "ASIN": "B00NH13S44",
>   "Product": {
>     "Identifiers": {
>       "MarketplaceASIN": {
>         "MarketplaceId": "A1F83G8C2ARO7P",
>         "ASIN": "B00NH13S44"
>       }
>     }
>   }
> }]
> ```
> 
> It should also be taking an array of ASINS, I think you might be using a different call?

I'm sure it's the same call you are making, with exact same parameters, I'm using generated java SDK to sign the requests. Since you are not getting 401/400 code back the access token is probably correct. I noticed that it also returns empty result if I'm using the ASIN that doesn't belong to a seller that I have issued an access token for
![Screen Shot 2021-02-25 at 9 37 16 PM](https://user-images.githubusercontent.com/7721815/109247679-53475580-77b2-11eb-82ec-4c5138c472ad.png)

**Comment by darek292** [comment]
Okay that is interesting - so we can not access prices for other items except our own? It's a bit inconsistent as get CompetitivePrice and GetLowestOfferListingsForSKU does return for ANY ASIN (not just our own). We would like to know the lowest price for given products for trend purposes, etc. It is possible right now but it's rather cumbersome.

**Comment by quazardous** [comment]
I dont' know if it's related but I'm having a strange behaviour with [getpricing](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing) vs [getitemoffers](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getitemoffers).

getitemoffers is working perfectly but not getpricing !?

with `GET https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/price?Asins=2070584623&ItemType=ASIN&MarketplaceId=A13V1IB3VIYZZH`

I Get a 404
```json
{
      "code": "NotFound",
      "message": "The requested resource doesn\u0027t exist."
}
```
Any clue ?

And what does the 404 error mean ?

**Comment by rugved1991** [comment]
Hi @quazardous,

The Asins value in the request doesnt look correct. ASIN should be alphanumeric. Please make sure you are adding the correct ASIN value in the request and try again. Let me know if that works.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by quazardous** [comment]
> Hi @quazardous,
> 
> The Asins value in the request doesnt look correct. ASIN should be alphanumeric. Please make sure you are adding the correct ASIN value in the request and try again. Let me know if that works.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

thx for you quick answer 

I've tried with [B084DWG2VQ](https://www.amazon.fr/nouvel-echo-dot-4e-generation-enceinte-connectee-avec-alexa-anthracite/dp/B084DWG2VQ/ref=sr_1_1?_encoding=UTF8&c=ts&dchild=1&keywords=Univers+Hi-Fi&qid=1617816597&s=electronics&sr=1-1&ts_id=1455794031) and [2070584623](https://www.amazon.fr/Harry-Potter-Harry-l%C3%A9cole-sorciers/dp/2070584623/ref=sr_1_1?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1SESUCYWF5B7R&dchild=1&keywords=livre+harry+potter+broch%C3%A9&qid=1617816827&sprefix=livre+harry+%2Celectronics%2C232&sr=8-1) (for books the ASIN is historically the ISBN in my comprehension).

Anyway both ASINs trigger the same 404 response with getPricing but does work with getItemOffers.

And bad parameters should trigger a 400 response (?).

**Comment by rugved1991** [comment]
Hi @quazardous,

Any bad request would return 4XX errors. I noticed that you are adding ItemType value as 
"ASIN". You should use "Asin" instead. I was able to test it successfully on my end.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by quazardous** [comment]
@rugved1991 THX that's it, I can confirm it's working with `Asin` instead of `ASIN`. Sorry for the noise (IMO 404 is a bit misleading :) )

**Comment by gto2145** [comment]
Hello,

When we use "getPricing", we only receive information from our offers, not from the competition, is this normal?

Thanks for your help.

**Comment by littleylv** [comment]
Has anybody solved this problem?
I also receive no pricing data event the asin is our product

``` 
[payload] => Array
        (
            [0] => stdClass Object
                (
                    [status] => Success
                    [ASIN] => xxx
                    [Product] => stdClass Object
                        (
                            [Identifiers] => stdClass Object
                                (
                                    [MarketplaceASIN] => stdClass Object
                                        (
                                            [MarketplaceId] => ATVPDKIKX0DER
                                            [ASIN] => xxx
                                        )
                                )
                        )
                )
        )
```

**Comment by pardoxp** [comment]
Same issue here @littleylv, I'm not receiving the pricing data did you find a solution to solve this??

**Comment by littleylv** [comment]
@pardoxp It seems that `getPricing` api returns pricing data only when your Asin "has buyable offers"(which means it should show "Price: $xxxx" in the front product detail page in stead of "Currently unavailable.")

You can try calling `getPricing` api with two different kinds of asins ("Price: $xxxx" and "Currently unavailable.")

**Comment by Trimakas** [comment]
Anyone here have any luck in sending more than one `ASIN` or `Sku` ? I've tried with brackets, without brackets.. no luck

**Comment by harvetech** [comment]
Same issue. Unable to get the data for DE marketplace. For FR its working fine.
