### ISSUE TITLE
[FEATURE] Documentation - Notifications/CreateDestination - Grantless Operation

### ISSUE THREAD

**Issue by fernlop** [amzn/selling-partner-api-docs#424]
I'm trying to call the **createDestination** operation. 

The **createDestination** operation is a Grantless operation and i don't get how to authenticate this request correctly. 

The documentation for Grantless operations as seen here:
[Grantless operations](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#grantless-operations-1)
Is only describing when to use it, but not how. 

In the _Request a Login with Amazon access token_ part of the documentation there is an example for a grantless operation:
```
Example for calling a grantless operation:

POST /auth/o2/token HTTP/l.l
Host: api.amazon.com
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
grant_type=client_credentials
&scope=sellingpartnerapi::notifications
&client_id=foodev
&client_secret=Y76SDl2F
```
By this i assume, i just need to include grant_type, scope, client_id and client_secret as query params and should be good.

This results in the following error:
```
 "errors": [
    {
        "message": "Access to requested resource is denied.",
        "code": "MissingAuthenticationToken"
    }
]
```
When i include authorization (With signed authorization header) I receive the following error:
```
"errors": [
    {
        "message": "Access to requested resource is denied.",
        "code": "Unauthorized",
        "details": ""
    }
]
```

My request looks like this:
```
{
  service: 'execute-api',
  region: 'eu-west-1',
  method: 'POST',
  path: '/notifications/v1/destinations/?scope=sellingpartnerapi%3A%3Anotifications&client_id=amzn1.application-oa2-client.XXX&client_secret=XXX&grant_type=client_credentials',
  host: 'sellingpartnerapi-eu.amazon.com',
  headers: {
    'Content-Type': 'application/json',
    Host: 'sellingpartnerapi-eu.amazon.com',
    'Content-Length': 122,
    'X-Amz-Security-Token': 'FwoGZXIvYXdzEMz//////////XXX==',
    'X-Amz-Date': '20210221T184847Z',
    Authorization: 'AWS4-HMAC-SHA256 Credential=XXX/20210221/eu-west-1/execute-api/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=XXXX'       
  },
  body: '{"name":"AWS-EventBridge-Reports","resourceSpecification":{"eventBridge":{"region":"eu-west-1","accountId":XXXX}}}'
}
```

The documentation should explain this authentication process, so that users that are not using the Python or Java SDK can easily use this Method.

**Comment by weiliguo15634145** [comment]
Have you found the answer , I had the same problem.
