### ISSUE TITLE
REQUEST: AnyOfferChanged notification and IsBuyBoxWinner element

### ISSUE THREAD

**Issue by goodiebag45** [amzn/selling-partner-api-docs#427]
The AnyOfferChanged notification has exactly the same elements as the MWS counterpart, EXCEPT for IsBuyBoxWinner, which is missing.

It is part of the documentation, so is it on purpose it is left out or a mistake, and if so, can it be added to the AnyOfferChanged notification, so it is easier to convert MWS application to SP application ?

**Comment by tabertantrum** [comment]
This has been documented in issue #134 and to date we have not received a response from the Amazon team on it. Would you mind adding feedback to the original issue in hopes it can gain some traction?

**Comment by cgaugel** [comment]
+1

**Comment by cgaugel** [comment]
Any news here?

**Comment by ShivikaK** [comment]
Hello @goodiebag45 

Thank you for raising this issue.

We are currently investigating the issue reported here as well as in #134  with the engineering team and I will get back to you with an update accordingly.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by cgaugel** [comment]
Still no update. Great engeneering team

**Comment by ShivikaK** [comment]
Hello everyone,

The issue with IsBuyBoxWinner element in SP API has been identified and the engineering team is working on the fix.

I will let you know once I have an estimate on the timeline.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by cgaugel** [comment]
Oh, now I am happy. The engeneering team is working on it! WOW!

**Comment by ShivikaK** [comment]
Hello everyone,

The issue with IsBuyBoxWinner missing in SP API offers element has been resolved. 

Please let me know if you still observe any different behavior/result in SP API for the AnyOfferChanged notification. 

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello,

As the issue reported here has been fixed and no new errors have been reported, I will be closing this issue.

Please open a support case with us for any new API errors you encounter.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
