### ISSUE TITLE
Getting "Invalid request parameters" response in createFeed

### ISSUE THREAD

**Issue by vijayparmar09** [amzn/selling-partner-api-docs#428]
I am trying to create a feed. Authorization and everything is working fine I have checked. But create feed is giving InvalidInput in response. I created a feedDocument first and trying to create the feed. Please help with this.

Request: POST / https://sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/feeds
```
curl --location --request POST 'https://sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/feeds' \
--header 'x-amz-access-token: My Access Token' \
--header 'Accept: */*' \
--header 'X-Amz-Content-Sha256: beaead3198f7da1e70d03ab969765e0821b24fc913697e929e726aeaebf0eba3' \
--header 'X-Amz-Security-Token: My Security Token' \
--header 'X-Amz-Date: 20210222T120517Z' \
--header 'Authorization: AWS4-HMAC-SHA256 Credential=sdfdsafgfghfgxhfghxfghx/20210222/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=dfsdfsdfsdfsdfdfbcvbcbcvbcvbvcvdfgrgsdgsdfsdfsdfd' \
--header 'Content-Type: application/json' \
--data-raw '{   
    "feedType":"POST_FLAT_FILE_LISTINGS_DATA",
    "marketplaceIds":["**************"],
    "inputFeedDocumentId":"amzn1.*******.3.1156725d-sdf-gdf-gdf-gg-df.hgjhgjhgjh"   
}'
```

Response: 
```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid request parameters",
            "details": ""
        }
    ]
}
```

**Comment by fernlop** [comment]
Please provide the createFeedDocument and upload request and response. Also, did you encrypt the file correctly? 
Do other feed types work? I'm having problems with just some feed type, others work perfectly.

**Comment by avvarga** [comment]
Hello @vijayparmar09,

We will need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation.

Thanks,
Alejandro C
Selling Partner API Developer Support
