### ISSUE TITLE
Overlapping import name in Solicitiations API's Schema class

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#43]
After generating the Java code for the Solicitations API with Swagger, I got this error in `Schema.java`: `import io.swagger.v3.oas.annotations.media.Schema conflicts with a type defined in the same file`.

My solution was to rename the `Schema` class to `SolicitationsSchema`.

Steps to reproduce:

1. Generate the Solicitations API Java client code with
```bash
    java -jar path/to/swagger-codegen-cli.jar generate \
         -i selling-partner-api-models/models/solicitations-api-model/solicitations.json \
         -l java \
         -t selling-partner-api-models/clients/sellingpartner-api-aa-java/resources/swagger-codegen/templates \
         -o path/to/output/dir
```
2. Add `swagger-annotations` as a dependency to `build.gradle`:
`implementation group: 'io.swagger.core.v3', name: 'swagger-annotations', version: '2.1.5'`
3. Copy the `io.swagger.client.model` package to your SP API project: `cp -r path/to/output/dir/src/io path/to/project/src/main/java`
4. Run `./gradlew build`

I'm using the latest version of `amzn/selling-partner-api-models` `master` branch.

**Comment by jlevers** [comment]
My bad -- this issue was from using Swagger v3 instead of v2.1.13.

**Comment by charliecode** [comment]
Don't feel bad, you're not the only one who's gone through this. You can get some more context at issue #17 . After the hell I went through with swagger-codegen and the insane messiness of their docs etc, I did a ton of research and found what I feel is a much better solution. [OpenAPITools](https://openapi.tools) was [created out of Swagger by 40 of the main original contributors](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md) and seems to be making the most professional looking progress towards tooling for the specification. Their docs are way better and the direction seems more in line with the direction the OAS specification is moving. Being adopted not just by the community but by the software world in general. Here's a few good links. Hope this helps, in the event you're looking for a better solution.

[Repo](https://github.com/OpenAPITools/openapi-generator) 
[Generators / Docs](https://openapi-generator.tech/docs/generators/)

**Comment by jlevers** [comment]
Awesome, thank you -- that's super helpful!
