### ISSUE TITLE
GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT Different Formats

### ISSUE THREAD

**Issue by NetRushJacob** [amzn/selling-partner-api-docs#433]
We schedule and download the GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT report for multiple clients and we noticed today that we get different resulting reports for different clients.

Some reports come double quoted with a first column header of "Country"
Some reports come without double quoted with a first column header of 'Country'
Some reports come without double quoted with a first column header of 'Country/Region Code'

We request for both US and CA marketplaces, but the resulting format appear to be the same per marketplace, so it appears to be something with the actual seller account.

Not overly concerned about the double quotes as it makes little difference in our system, but the different headers makes this worth a clarification / question on what is going on with this report.

**Comment by parvathm** [comment]
Hi @NetRushJacob,

Thank you for the heads up. Can you please [open a support case](https://developer.amazonservices.com/support) with report id details which will help us in the investigation. 

Thanks,
Parvathm,
Selling Partner API developer support.

**Comment by NetRushJacob** [comment]
Hi @parvathm 
I have done so now; thanks!  Case ID 8034246241

**Comment by parvathm** [comment]
Closing this issue as it has been addressed in support case.

**Comment by NetRushJacob** [comment]
FYI for future searches:
The issues with CSV/Quoted vs TSV/Unquoted appears to be caused by scheduled reports (TSV/Unquoted) vs manual (IE from Seller Central) requests (CSV/Quoted). GetReports will return both scheduled and manual requests, but the files themselves appear to be different formats.
