### ISSUE TITLE
[BUG] Documentation putTransportContent->nonPartneredSmallParcelData,How to upload Carton size information？

### ISSUE THREAD

**Issue by lzy6666666** [amzn/selling-partner-api-docs#436]
NonPartneredSmallParcelData parameters and there is no size field，
And feeds "CartonContentsRequest. XSD" also have no

**Comment by shower1986** [comment]
找到上传尺寸和重量的接口了吗？

**Comment by tuxl** [comment]
我也在找这，大家找到方案了没

**Comment by shane186** [comment]
我也在找
看issue #389 里面有人用feed type：POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO
你们有用过这个feedtype吗？在官方文档没看到这个feedtype，excel模板不知道是什么样子。

**Comment by bxb100** [comment]
https://sellercentral.amazon.com/gp/help/help.html?itemID=G201967250&referral=AEGYJWO2CDBZW_A2ZE169I3JTRNH&

上面说必须要给, 不管是不是合作承运

**Comment by wonsky87** [comment]
不给装箱资料，亚马逊会发警告，然后说要暂停账号。
开了很多case去咨询找方案，他们也不给解决方案。
后面是用了自动化方案去解决

**Comment by lzy6666666** [comment]
> 不给装箱资料，会发警告。
> 开了很多case去咨询找方案，也没找到解决方案。
> 后面是用了自动化方案去解决
怎么个自动化，插件吗

**Comment by smartzhanghandsome** [comment]
大家最后都是怎么处理的？

**Comment by lzy6666666** [comment]
收到，谢谢!!!（自动回复）

**Comment by suofiya** [comment]
这个case大家都找到解决方案没？

**Comment by lzy6666666** [comment]
收到，谢谢!!!（自动回复）

**Comment by AisxLee** [comment]
> 不给装箱资料，会发警告。 开了很多case去咨询找方案，也没找到解决方案。 后面是用了自动化方案去解决

你说的自动化，不会是又搞了个爬虫处理的吧，成本有点高。。。

**Comment by AisxLee** [comment]
@lzy6666666 楼主光是回复“收到，谢谢”，问题最终解决了没？如果解决了，还请不吝分享一下解决方案，感谢楼主

**Comment by ccx0lw** [comment]
https://github.com/4379711/sellingpartner-api-fba-shipment-sdk

这个文档很详细，可以解决箱尺寸上传的问题。有模板。 我也是昨天才找到的

**Comment by lzy6666666** [comment]
收到，谢谢!!!（自动回复）

**Comment by pzming** [comment]
> https://github.com/4379711/sellingpartner-api-fba-shipment-sdk
> 
> 这个文档很详细，可以解决箱尺寸上传的问题。有模板。 我也是昨天才找到的

请问你们用这个方式上传成功了么

**Comment by lzy6666666** [comment]
收到，谢谢!!!（自动回复）
