### ISSUE TITLE
Feed response suddenly in Chinese? Why?

### ISSUE THREAD

**Issue by gtaylor44** [amzn/selling-partner-api-docs#437]
All of a sudden my feed responses are in Chinese. Is anybody seeing the same behaviour?

I can't see any header or parameter in the docs that can be used to set the language. I'm unable to parse Chinese and this has randomly happened. No recent deployments on my side, etc. Does anybody have any ideas?

![amazon_feed_response](https://user-images.githubusercontent.com/11572604/109002206-d191f200-76f5-11eb-9b3d-df497234dad4.jpg)

**Comment by wangjue666** [comment]
@gtaylor44 This is Japanese, Maybe you're pulling a feed from a Japanese site

**Comment by gtaylor44** [comment]
This is for the Australia marketplace (A39IBJ37TRP1C6). The selling partner URL for Australia is https://sellingpartnerapi-fe.amazon.com

I've been repeating the same feed many times before with this URL and had English spitting out each time... All of a sudden, it's in Japanese... hmm

Do you know if there is a header that can be set in the request to explicitly define the language?

**Comment by wangjue666** [comment]
Look at it this way, This should be spapi's bug, Maybe you both belong to site in the Far East, Then the machine node that causes the feed to be processed comes from Japan, hahah
Did you have such a problem with MWS before?

**Comment by gtaylor44** [comment]
"This should be spapi's bug"

No, I haven't seen this one before but in saying that, this is not the only bug i've found. I have raised several other issues with the Amazon support team in other areas but the team is not responding.

I've come to Github for this particular issue because I'm not getting anywhere with my other issues. 

I understand the API is new but I would like to see the Amazon developer & testing team up their game. Bugs aside, there is a really bad balance between security and usability with this API. It's obvious that the support team is inundated by developers asking how to sign their tokens, etc. This is probably why I'm hearing crickets with my open support cases.

**Comment by bxb100** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#marketplaceid-values

is that work?
