### ISSUE TITLE
Internal server error for getting SP API access token

### ISSUE THREAD

**Issue by swapnil106111** [amzn/selling-partner-api-docs#438]
Hello, 

I have created the app and it is in draft state. 
I am trying to get access token. For that I am passing client id, client secret and refresh token. Still I am getting Internal Server Error. 

Why I am getting this error?
If this error is because of draft state then when my app will get published/approved?

**Comment by vikingcodes** [comment]
Have you created consent using version=beta tag ?

https://sellercentral.amazon.com/apps/authorize/consent?application_id=[applicationId]&state=[State]&version=beta

**Comment by parvathm** [comment]
Hi @swapnil106111,

You should be able to get Access Token even when the application is in draft state. Can you please  [open a support case](https://developer.amazonservices.com/support) so we can address the issue correctly.

Thanks,
Parvathm
Selling Partner API developer support.

**Comment by parvathm** [comment]
Hi @swapnil106111,

I am resolving this issue. Please open a support case if you are still having issues getting access token.

Thanks,
Parvathm,
Selling Partner API Developer Support.
