### ISSUE TITLE
GetReport : ReportDocumentId is the same during one hour

### ISSUE THREAD

**Issue by logixio-jp** [amzn/selling-partner-api-docs#439]
Hi,

When I call GET /reports/2020-09-04/reports/{reportId}, I always get the same reportDocumentId in response, during one hour of requests.

Example : If I call /reports/2020-09-04/reports/50402018682, I get this response. ReportId is good (50402018682), and report document ID is :
amzn1.tortuga.3.96419c37-517a-4a55-8e72-fd12c482c6fa.T1LIO7VW9LC5MB

{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingEndTime":"2021-02-24T16:42:19+00:00","processingStatus":"DONE","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportDocumentId":"amzn1.tortuga.3.96419c37-517a-4a55-8e72-fd12c482c6fa.T1LIO7VW9LC5MB","reportId":"50402018682","dataEndTime":"2021-02-24T16:42:08+00:00","createdTime":"2021-02-24T16:42:08+00:00","processingStartTime":"2021-02-24T16:42:13+00:00","dataStartTime":"2021-02-24T16:42:08+00:00"}}

If I call /reports/2020-09-04/reports/50403018682, I get this response. ReportId is good (50403018682), and report document ID is :
amzn1.tortuga.3.96419c37-517a-4a55-8e72-fd12c482c6fa.T1LIO7VW9LC5MB

{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingEndTime":"2021-02-24T16:43:36+00:00","processingStatus":"DONE","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportDocumentId":"amzn1.tortuga.3.96419c37-517a-4a55-8e72-fd12c482c6fa.T1LIO7VW9LC5MB","reportId":"50403018682","dataEndTime":"2021-02-24T16:43:26+00:00","createdTime":"2021-02-24T16:43:26+00:00","processingStartTime":"2021-02-24T16:43:31+00:00","dataStartTime":"2021-02-24T16:43:26+00:00"}}

It looks like that the reportdocumentId is the same for one hour. Even if the reportId changes, when I call /reports/2020-09-04/reports/{reportId}, the reportDocumentId is the same for every request during one hour.

But weirdly, the createReport takes at least 7 seconds before getting the DONE status. So it looks that the report is generated, but it doesn't reflect on the ReportDocumentID. 

Please also note that when I finally get the new ReportDocumentId after one hour of GetReport request every 5 minutes, the report doen't take much time to generate... 7 seconds : 

{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingStatus":"IN_QUEUE","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}
**Le rapport n'est pas encore prêt, nouvelle tentative dans 1 sec.**
{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingStatus":"IN_QUEUE","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}
**Le rapport n'est pas encore prêt, nouvelle tentative dans 1 sec.**
{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingStatus":"IN_QUEUE","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}
**Le rapport n'est pas encore prêt, nouvelle tentative dans 1 sec.**
{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingStatus":"IN_PROGRESS","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","processingStartTime":"2021-02-24T19:02:35+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}
**Le rapport n'est pas encore prêt, nouvelle tentative dans 1 sec.**
{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingStatus":"IN_PROGRESS","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","processingStartTime":"2021-02-24T19:02:35+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}
**Le rapport n'est pas encore prêt, nouvelle tentative dans 1 sec.**
{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingStatus":"IN_PROGRESS","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","processingStartTime":"2021-02-24T19:02:35+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}
**Le rapport n'est pas encore prêt, nouvelle tentative dans 1 sec.**
{"payload":{"reportType":"GET_FLAT_FILE_OPEN_LISTINGS_DATA","processingEndTime":"2021-02-24T19:02:40+00:00","processingStatus":"DONE","marketplaceIds":["A2EUQ1WTGCTBG2"],"reportDocumentId":"amzn1.tortuga.3.816cd97d-c697-40ba-aceb-50752d0753f1.T3JJA76EMLSJYM","reportId":"50469018682","dataEndTime":"2021-02-24T19:02:29+00:00","createdTime":"2021-02-24T19:02:29+00:00","processingStartTime":"2021-02-24T19:02:35+00:00","dataStartTime":"2021-02-24T19:02:29+00:00"}}

Thanks

**Comment by johnkw** [comment]
Are you sure it's an hour? The documentation says some reports only change every 30 minutes, and some every 4 hours. This is documented on https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md although maybe it's wrong somewhere.
