### ISSUE TITLE
How to get my seller‘s listings？

### ISSUE THREAD

**Issue by BlinglingGirl** [amzn/selling-partner-api-docs#441]
catalog-items-api provides the query interface to query in the whole marketplace, but I want to get my seller's listing,how can i get?

**Comment by nodisk8800** [comment]
使用报告的API来下载

**Comment by fernlop** [comment]
Hello @BlinglingGirl ,
you need to generate a report for this, depending on your needs you can access all listings or just the active listings. 
Here is the related api and available report types:
[Reports API](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md)
[Inventory Report Types](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#inventory-reports)
