### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by mrkph** [amzn/selling-partner-api-docs#442]
I use xml to upload the product, but it keeps showing IN_PROGRESS for a whole day. I can only upload the product again after the status is automatically changed to CANCELLED. What is the reason?

**Comment by nodisk8800** [comment]
这样的问题,根本无法回答.
估计你的xml有问题.

**Comment by mrkph** [comment]
> 这样的问题，根本无法回答。
> 估计你的xml有问题。

你好，是这样的，我发现我一天只能上传十次左右的产品，后续的上传都是‘IN_PROGRESS’状态，而且无法手动取消，只有等它自动变成‘CANCELLED’状态后，我才能继续上传，但是我在那一天只有几次机会的上传中却可以上传成功，也没有报错。我是通过FeedsApi的方法上传的

**Comment by pprbhm** [comment]
Hi, To understand the problem in more details, Please contact Developer support via a [support case](https://developer.amazonservices.com/support).
