### ISSUE TITLE
[FEATURE] Documentation

### ISSUE THREAD

**Issue by ngLynx** [amzn/selling-partner-api-docs#443]
Where can I found the sellerCentral URL for all marketplace?
Document only list:
https://sellercentral.amazon.com
https://sellercentral-europe.amazon.com
in example. Where can I get the others? does https://sellercentral.amazon.com can be used for all north America marketplace?

**Comment by cgaugel** [comment]
https://sellercentral-na.amazon.com

**Comment by ngLynx** [comment]
what are the url for Asia and Middle East?
