### ISSUE TITLE
(Emergency)Developer ID is not associated with the application id - SP API

### ISSUE THREAD

**Issue by shower1986** [amzn/selling-partner-api-docs#444]
When I called getAuthorizationCode interface to get the code, there was an error。My question (**Case id: 7942162431**) has been submitted to the Amazon mws team for more than a month, but so far no customer service staff from the Amazon mws team has responded to me with specific solutions. **I'm very disappointed with the customer service staff on the Amazon mws team.**
Can there be a relevant person in charge here to answer my question? Thank you so much!
Below is the request data, returns the results and my application client that has been published for more than 10 days.

1.Request info:
{
    "auto": {
        "clientId": "amzn1.application-oa2-client.02f0xxxxxxxxxxxxxxxxxxxx81ae667e6",
        "clientSecret": "e75595ede00c1xxxxxxxxxxxxxxxxxx74c7d5",
        "accessKeyId": "AKIxxxxxxxxxxQQELI",
        "secretKey": "JuCHRTCxxxxxxxxxxxxxxxx0c/zTa6d",
        "roleArn": "arn:aws:iam::13685xxxx434:role/SellingPartnerAPIRole",
        "endpoint": "https://api.amazon.com/auth/o2/token",
        "region": "us-east-1",
        "endpointURL":"https://sellingpartnerapi-na.amazon.com",
        "withScopes":[
            "sellingpartnerapi::migration"
            ]
    },
   "sellingPartnerId":"A183xxxxxxxHMR1",
   "developerId":1347xxxxxxxx677,
   "mwsAuthToken":"amzn.mws.e4bxxxf9-0fec-1xxc-10xx9-94cxxxxxxxxxxdf5"    
}

2.Response info:
{
"errors": [
{
"code": "InvalidInput",
"message": "Developer ID 134xxxxx77 is not associated with the application id.",
"details": ""
}
]
}

3.My application client:
App name: HXXXXXXXXXXXXXL-SP-MWS
Status: Published(published for more than 10 days)
App ID: amzn1.sellerapps.app.7c54afxxxxxxxxxxxxxxxxc900e1
Client identifier: amzn1.application-oa2-client.02f00xxxxxxxxxxxxxxx7e6
Client secret: e75595ede00xxxxxxxxxxxxxxxxxxxxxxx674c7d5

**Comment by parvathm** [comment]
Hi @shower1986,

Sorry for the delay in response. This error is because your app id is not enabled to use authorizations API. It is enabled now. Please try and let us know if you still have any issues.

Thanks,
Parvathm,
Selling Partner Developer Support.

**Comment by parvathm** [comment]
Hi,

We are closing this issue. Please follow up on support case if you still have any issues.

Thanks,
Parvathm,
Selling Partner API Developer Support.
