### ISSUE TITLE
Unable to publish the App in the App Listings page

### ISSUE THREAD

**Issue by siddhartha-reckonsys** [amzn/selling-partner-api-docs#445]
We created a Hybrid App, but are unable to publish the App in the App Listings page.  The Save and Continue button in the App Information page is not submitting the information. There is no error as well. How do we proceed?

**Comment by siddhartha-reckonsys** [comment]
Hi,

Any help here, we are stuck on a major functionality here.

**Comment by saisanthoshdav** [comment]
Just confirming I am facing this issue as well, any help would be great.

**Comment by siddhartha-reckonsys** [comment]
No response yet.

**Comment by Bilal-Akram** [comment]
I am also facing same issue

**Comment by ShivikaK** [comment]
Hello @siddhartha-reckonsys 

Does the hybrid app include your oauth information in it? A SP API or Hybrid app requires oauth information i.e. Login and Redirect URI added to it before it can be submit to be published.

Please confirm this information for us.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by saisanthoshdav** [comment]
This might be different from what @siddhartha-reckonsys is experiencing but below is my situation -

**What I Want To Do**
To access and use SP APIs and MWS APIs. From what I read 'Hybrid Apps' seemed like the way to go.

**What Exists**
Registered as MWS developer around six months back and have a Developer ID

**What I Am Doing Now**
1) In Developer Central -
"+Add New App Client" (Only option)

![image](https://user-images.githubusercontent.com/10094226/110195762-a6ca3b00-7e65-11eb-95be-da6847000c76.png)

Only see MWS option (Should I be seeing SP API here ? If so, please let me know what I am missing to see this option. I can create a new thread if this is not relevant here).
I selected MWS and put in my Developer ID under Europe region

2) In the newly creted row, drop down to select "Edit Listing". Filled out the following
- Select the application client to list
- Listing name
- Select the language used to provide listing information:
- Product URL
- Support email
- Support phone
- Support URL
- Customer support languages
- Short description

Hit on Save And Continue.
No reaction.

**Comment by siddhartha-reckonsys** [comment]
> Hello @siddhartha-reckonsys
> 
> Does the hybrid app include your oauth information in it? A SP API or Hybrid app requires oauth information i.e. Login and Redirect URI added to it before it can be submit to be published.
> 
> Please confirm this information for us.
> 
> Thanks,
>  Shivika Khare 
> Selling Partner API Developer Support

Hi ShivikaK,

Yes, it does include the Login and Redirect URI.

**Comment by siddhartha-reckonsys** [comment]
> This might be different from what @siddhartha-reckonsys is experiencing but below is my situation -
> 
> **What I Want To Do**
> To access and use SP APIs and MWS APIs. From what I read 'Hybrid Apps' seemed like the way to go.
> 
> **What Exists**
> Registered as MWS developer around six months back and have a Developer ID
> 
> **What I Am Doing Now**
> 
> 1. In Developer Central -
>    "+Add New App Client" (Only option)
> 
> ![image](https://user-images.githubusercontent.com/10094226/110195762-a6ca3b00-7e65-11eb-95be-da6847000c76.png)
> 
> Only see MWS option (Should I be seeing SP API here ? If so, please let me know what I am missing to see this option. I can create a new thread if this is not relevant here).
> I selected MWS and put in my Developer ID under Europe region
> 
> 1. In the newly creted row, drop down to select "Edit Listing". Filled out the following
> 
> * Select the application client to list
> * Listing name
> * Select the language used to provide listing information:
> * Product URL
> * Support email
> * Support phone
> * Support URL
> * Customer support languages
> * Short description
> 
> Hit on Save And Continue.
> No reaction.

Hi @saisanthoshdav,

Yes, the API dropdown should include more two options, SP-API and MWS and SP-API.

**Comment by krithic15** [comment]
@saisanthoshdav Are you logged into the same account from which you submitted your MWS DRAF? If not, you should see a pop-up that asks you to update your Developer Profile. Once the profile is updated and SP API access is granted, you should be able to see SP API in 'API Type' dropdown.
[or] You could set up your hybrid app from the same account you submitted DRAF previously.

@siddhartha-reckonsys Could you open a support case to look into the issue further?

Best,
Krithi
Solutions Architect, SP API

**Comment by Bilal-Akram** [comment]
@krithic15 I am facing an issue on submitting my SP-API the form is complete but the save and continue button is not working. it's look like the button is disable.

**Comment by krithic15** [comment]
Hello @Bilal-Akram,

 I understand that you are unable to submit the Developer Profile form. Have you tried deleting cache and retrying [or] using a different browser? If these options don't help, please open a support case so that a member can look into your account.

Best,
Krithi
Solutions Architect, SP API

**Comment by Bilal-Akram** [comment]
@krithic15 
Yeah i have tried in different browsers but it didn't work. i will open a support case thanks

**Comment by UoooBarry** [comment]
Same issue

**Comment by iLoveSarabear** [comment]
SAME ISSUE

**Comment by sidrafarooq** [comment]
Hi,

Can you tell me what should be the OAuth Login URI and OAuth Redirect URI, bit confuse here
