### ISSUE TITLE
Why don't I see the fulfillment inventory API in MWS in the interface list

### ISSUE THREAD

**Issue by adamancyzhang** [amzn/selling-partner-api-docs#446]
**MWS Fulfillment Inventory API Document URL**
http://docs.developer.amazonservices.com/en_US/fba_inventory/FBAInventory_Overview.html

**Comment by krithic15** [comment]
Hello there,

If you are referring to the Fulfillment Inventory API in the SP API platform, please see FBA Inventory API: https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md#inventorysummary

Best,
Krithi,
Solutions Architect, SP API
