### ISSUE TITLE
400 Bad Request An unknown scope was requested

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-docs#448]
Hi! 

Following documentation I am trying to implement "Login with awazon" button. 
I am using JS SDK. I am getting error when requesting "profile" scope. 
```
   document.getElementById('LoginWithAmazon').onclick = function() {
          options = { scope:'profile', response_type: 'code' };
          options.scope_data = {
            'profile' : {'essential': false}
            };
          amazon.Login.authorize(options, function(response) {
            if ( response.error ) {
              alert('oauth error ' + response.error);
              return;
            }
            console.log(response)
```
Am I requesting wrong scope?             
I was looking for list of scopes for selling-partner-api, but found none. Can someone help me with such list and this error?

**Comment by pprbhm** [comment]
Hi, Scope specific requests can be handled by Developer support team by submitting a [support case](https://developer.amazonservices.com/support).
