### ISSUE TITLE
Request a Login with Amazon access token (PHP)

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#45]
Hello,
i'm trying to recover the access token (Step 1. Request a Login with Amazon access token) with curl, but the response is '{"error_description":"The authorization grant type is not supported by the authorization server","error":"unsupported_grant_type"}',  i have set grant_type to refresh_token, and i have set my refresh_token, i don't understand the error can you help me ?

the request in php: 
$cURL = curl_init('https://api.amazon.com');
$data = [
		'grant_type' => 'refresh_token',
		'refresh_token' => 'Atzr|...',
		'client_id' => '...',
		'client_secret' => '...'
		];
$headers[] = 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8';
$headers[] = 'Host: api.amazon.com';
curl_setopt($cURL, CURLOPT_HTTPHEADER, $headers);
curl_setopt($cURL, CURLOPT_URL, 'https://api.amazon.com/auth/o2/token');
curl_setopt($cURL, CURLOPT_POST, true);
curl_setopt($cURL, CURLOPT_POSTFIELDS, $data);
$response = curl_exec($cURL);

**Comment by tharrington** [comment]
@FexusZ Did you solve this issue?

**Comment by MST1122** [comment]
@tharrington @FexusZ  just change the header:

`Content-Type: application/x-www-form-urlencoded;charset=UTF-8`
to 
`Content-Type: application/json`

I figured it out after spending almost a week.
