### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by Albertocapobianco** [amzn/selling-partner-api-docs#451]
Hello everybody,
  I always get this error as many:

   "message": "Access to requested resource is denied.",
             "code": "Unauthorized",

I have followed the whole procedure several times, I have also tried to follow the guide twice and I have also tried some proposed solutions but I cannot go on.

I also opened a case: 6822632662

Any solution?

**Comment by Albertocapobianco** [comment]
Is there someone from technical support who would be able to help me, I have read that some moderators recommend opening a Case but instead of technicians the sales support is responding to me.

**Comment by parvathm** [comment]
Hi @Albertocapobianco,

Case id 6822632662 is in right queue now. you should get a reply in couple of days.

Thanks,
Parvathm,
Selling Partner API Developer support.

**Comment by Albertocapobianco** [comment]
Hi @parvathm 
Could you help me in any way? from the case they still do not answer me and the answers they gave me were not related to what I asked.

**Comment by LuigiRagone** [comment]
@Albertocapobianco Ciao Alberto, hai risolto? Ho il tuo stesso problema con l'utilizzo di SP-API.

**Comment by kumarparekh** [comment]
Hello,
Did anyone get any reply or was able to solve it themselves?
We have tried everything that was available to us through all the forums but no luck.
