### ISSUE TITLE
[Get Labels download PDF file in Japanese] Documentation

### ISSUE THREAD

**Issue by educatornum** [amzn/selling-partner-api-docs#452]
I wanna download the Japanese PDF file, but the pdf was only in English.

My marketplaceId is [**A1VC38T7YXB528**]

I have followed these steps.

**1.  Create Feed document
2. Create Feed with an XML file
3. Get Labels with PageType, LabelType, and PackageLabelsToPrint.**

I could download the pdf file but it's not Japanese.

**` Here is my downloaded PDF file in English`**
![Screen Shot 2021-02-24 at 16 52 38](https://user-images.githubusercontent.com/25072337/109441594-fcbf6d00-7a78-11eb-8677-25fa2dbefd9f.png)

**`  but I wanna the PDF file in Japanese.`**
![Screen Shot 2021-03-01 at 10 29 40](https://user-images.githubusercontent.com/25072337/109441666-342e1980-7a79-11eb-9761-02f3e0bf63ee.png)

How I can download the Japanese pdf file? 
Thanks!

**Comment by johnkw** [comment]
Are you sure it's supposed to be in Japanese? Maybe the fulfillment center wants it to be in English.

**Comment by educatornum** [comment]
I'm sure, Japan is a big marketplace for Amazon.

Before, The Marketplace Amazon web services was can download a PDF file in Japanese.  

Why The new Selling partner API couldn't download PDF in Japanese?

I don't know about it.

**Comment by johnkw** [comment]
Did you try shipping it in with the label in English though? The FC perhaps changed their policy? I'm curious either way, but this would be a good thing to ask Seller Support.
