### ISSUE TITLE
Uploading feed is success,but the feed not work in my market.

### ISSUE THREAD

**Issue by BlinglingGirl** [amzn/selling-partner-api-docs#454]
I need to change my sku's quantity.  so, I use the type `POST_INVENTORY_AVAILABILITY_DATA` of feed .My marketplace is the UK.
1. My XML file 
**MerchantIdentifier** : this is my Merchant's id
**SKU**: this is my SellerSKU
```<?xml version="1.0" ?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>ARI9W*****</MerchantIdentifier>
    </Header>
    <MessageType>Inventory</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <Inventory>
            <SKU>222</SKU> <!-- sellerSKU-->
            <Quantity>200</Quantity> 
        </Inventory>
    </Message>
</AmazonEnvelope>
```
2. create feedDocument
this is my request Body
```
{
"contentType":"text/tab-separated-values; charset=ISO_8859_1"
}
```
3. Upload the XML file

4. create feed used the Step2 returned feedDocument

5. Query the feed status through the interface of ```getFeedDocument```

Here is my feed query result.

```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>AESxxxxxxxx</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>50030xxxxx</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>1</MessagesProcessed>
				<MessagesSuccessful>1</MessagesSuccessful>
				<MessagesWithError>0</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>
```
This result seems to be successful, but I don't see the change of inventory quantity in the background of the business.

**Comment by tanaililing** [comment]
Hello, when I submitted the file in the third step, it returned a remote server error, 403 forbidden, what is the reason?

**Comment by tanaililing** [comment]
> I need to change my sku's quantity. so, I use the type `POST_INVENTORY_AVAILABILITY_DATA` of feed .My marketplace is the UK.
> 
> 1. My XML file
>    **MerchantIdentifier** : this is my Merchant's id
>    **SKU**: this is my SellerSKU
> 
> ```
> <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
>     <Header>
>         <DocumentVersion>1.01</DocumentVersion>
>         <MerchantIdentifier>ARI9W*****</MerchantIdentifier>
>     </Header>
>     <MessageType>Inventory</MessageType>
>     <Message>
>         <MessageID>1</MessageID>
>         <Inventory>
>             <SKU>222</SKU> 
>             <Quantity>200</Quantity> 
>         </Inventory>
>     </Message>
> </AmazonEnvelope>
> ```
> 
> 1. create feedDocument
>    this is my request Body
> 
> ```
> {
> "contentType":"text/tab-separated-values; charset=ISO_8859_1"
> }
> ```
> 
> 1. Upload the XML file
> 2. create feed used the Step2 returned feedDocument
> 3. Query the feed status through the interface of `getFeedDocument`
> 
> Here is my feed query result.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
> 	<Header>
> 		<DocumentVersion>1.02</DocumentVersion>
> 		<MerchantIdentifier>AESxxxxxxxx</MerchantIdentifier>
> 	</Header>
> 	<MessageType>ProcessingReport</MessageType>
> 	<Message>
> 		<MessageID>1</MessageID>
> 		<ProcessingReport>
> 			<DocumentTransactionID>50030xxxxx</DocumentTransactionID>
> 			<StatusCode>Complete</StatusCode>
> 			<ProcessingSummary>
> 				<MessagesProcessed>1</MessagesProcessed>
> 				<MessagesSuccessful>1</MessagesSuccessful>
> 				<MessagesWithError>0</MessagesWithError>
> 				<MessagesWithWarning>0</MessagesWithWarning>
> 			</ProcessingSummary>
> 		</ProcessingReport>
> 	</Message>
> </AmazonEnvelope>
> ```
> 
> This result seems to be successful, but I don't see the change of inventory quantity in the background of the business.

Hello, when I submitted the file in the third step, it returned a remote server error, 403 forbidden, what is the reason?

**Comment by tanaililing** [comment]
Have you solved this problem? How to solve it?
