### ISSUE TITLE
Mismatches between MWS and Selling API

### ISSUE THREAD

**Issue by AlexKraso** [amzn/selling-partner-api-docs#456]
there is a difference in columns between SP-API and MWS for the same report.
Issue summary:

the number of columns from the report is different between MWS and SP API.
There are no columns like "ship-address-1", "ship-address-2", "ship-address-3" and other.
Could you please specify a report from SP-API that has these columns (as it was in MWS)?
Issue details:
MWS report "_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_" (US marketplace)
Columns:
amazon-order-id
merchant-order-id
shipment-id
shipment-item-id
amazon-order-item-id
merchant-order-item-id
purchase-date
payments-date
shipment-date
reporting-date
buyer-email
buyer-name
buyer-phone-number
sku
product-name
quantity-shipped
currency
item-price
item-tax
shipping-price
shipping-tax
gift-wrap-price
gift-wrap-tax
ship-service-level
recipient-name
ship-address-1
ship-address-2
ship-address-3
ship-city
ship-state
ship-postal-code
ship-country
ship-phone-number
bill-address-1
bill-address-2
bill-address-3
bill-city
bill-state
bill-postal-code
bill-country
item-promotion-discount
ship-promotion-discount
carrier
tracking-number
estimated-arrival-date
fulfillment-center-id
fulfillment-channel
sales-channel
Selling Partner API report "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL" (US marketplace)
Columns:
amazon-order-id
merchant-order-id
shipment-id
shipment-item-id
amazon-order-item-id
merchant-order-item-id
purchase-date
payments-date
shipment-date
reporting-date
buyer-email
sku
product-name
quantity-shipped
currency
item-price
item-tax
shipping-price
shipping-tax
gift-wrap-price
gift-wrap-tax
ship-service-level
ship-city
ship-state
ship-postal-code
ship-country
item-promotion-discount
ship-promotion-discount
carrier
tracking-number
estimated-arrival-date
fulfillment-center-id
fulfillment-channel
sales-channel

**Comment by krithic15** [comment]
Hello there,

In SP API platform, the reportType enumerations have been split based on Role Based Access Control. To access PII in FBA reports, you can retrieve either GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING or ET_AMAZON_FULFILLED_SHIPMENTS_DATA_TAX based on your use-case.
For the list of report Types, please see https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#fulfillment-by-amazon-fba-reports

Best,
Krithi,
Solutions Architect, SP API
