### ISSUE TITLE
The required order-id field is missing from the file. To correct this error, download the template again and use the new copy...

### ISSUE THREAD

**Issue by bk757** [amzn/selling-partner-api-docs#457]
[Step 2. Encrypt and upload the feed data](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md#step-2-encrypt-and-upload-the-feed-data)

This step I had upload feed_data.xml success!   but the report result :
`string(616) "Feed Processing Summary:
        Number of records processed             0
        Number of records successful            0

original-record-number  order-id        order-item-id   error-code      error-type      error-message
0                       90012   Fatal   The required order-id field is missing from the file. To correct this error, download the template again and use the new copy, or insert the required field into your existing file.
0                       90061   Warning The <?xml version="1.0" encoding="UTF-8"?> field heading is invalid, so values in this field were ignored. To correct this error, download the template again and use the new copy, or fix the field heading in your existing file.
`

And this is my feed_data.xml content:
`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier><![CDATA[xx]]></MerchantIdentifier>
    </Header>
    <MessageType>OrderFulfillment</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <OperationType>Update</OperationType>
        <OrderFulfillment>
            <AmazonOrderId><![CDATA[yyy]]></AmazonOrderId>
            <FulfillmentDate><![CDATA[2021-02-02T10:40:00]]></FulfillmentDate>
            <FulfillmentData>
                <CarrierName><![CDATA[Yun Express]]></CarrierName>
                <ShippingMethod>Standard</ShippingMethod>
                <ShipperTrackingNumber><![CDATA[aa]]></ShipperTrackingNumber>
            </FulfillmentData>
            <Item>
                <AmazonOrderItemCode>bbbb</AmazonOrderItemCode>
                <Quantity>1</Quantity>
            </Item>
        </OrderFulfillment>
    </Message>
</AmazonEnvelope>`

I try it all day, but not get a solution! for help, thanks!

**Comment by mrkph** [comment]
I also encountered this error when updating the price of the product. Have you solved this problem?
