### ISSUE TITLE
Dynamic sandbox?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#459]
Hello,

Is the sandbox environment static or dynamic?

For example, can I generate a new report and get this report?

Thanks

**Comment by krithic15** [comment]
Hello there,

The sandbox environment in SP API platform is static today and can be used to retrieve a mocked response as stated in x-amazon-spds-sandbox-behaviors object of the API model when you send a request that includes the specified parameters.

For more information, https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox

Best,
Krithi
Solutions Architect, SP API

**Comment by arturll7** [comment]
@krithic15 thank you for the answer.

**Comment by SenQi-666** [comment]
> Hello there,
> 
> The sandbox environment in SP API platform is static today and can be used to retrieve a mocked response as stated in x-amazon-spds-sandbox-behaviors object of the API model when you send a request that includes the specified parameters.
> 
> For more information, https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox
> 
> Best,
> Krithi
> Solutions Architect, SP API

Excuse me, whether the sandbox returns a real response or a mocked response. I changed the endpoints and the request parameters are the same as x-amazon-spds-sandbox-behaviors, but the seller data is still returned.
