### ISSUE TITLE
Catalog Items API doesn't return Relationships section

### ISSUE THREAD

**Issue by bessonov87** [amzn/selling-partner-api-docs#46]
None of [Catalog Items API](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json) methods do not return Relationships section. This section was specified in the API documentation for those methods: getCatalogItem,listCatalogCategories,listCatalogItems.

At the same time, the MWS API returns it for the same ASIN, Relationships section contains information about variation and child/parent relation.

**Comment by shuaiys** [comment]
I also encountered this problem, have you solved it？

**Comment by sultanshakir** [comment]
@bessonov87 I am also hoping this is solved soon.

**Comment by ShivikaK** [comment]
Hello,

This issue has been reported to our team already and is being fixed.

We have another open github issue #257 regarding this. Please monitor that issue for any updates moving forward.

Thanks,
Shivika Khare
Selling Partner API Developer Support
