### ISSUE TITLE
Api and method to add a product to inventory?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#460]
Hello,

Which **API** and **METHOD**, should we use to **add product** to seller's **inventory**?

Can someone help me on this?

Thanks.

**Comment by vdanyliv** [comment]
@arturll7 feed api

**Comment by arturll7** [comment]
@vdanyliv thank you.

**Comment by MST1122** [comment]
@arturll7 I'm also working on Feed API for product creation. where can I contact you for discussion.
