### ISSUE TITLE
Now to get the complete order information, I need to make 5 requests. Is the orders API design really reasonable?

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#462]
To get complete order information now I need to make these request:
/orders/v0/orders
foreach (var order in orders)
{
/orders/v0/orders/{orderId}/orderItems
/orders/v0/orders/{orderId}/address to get the shipping address
/orders/v0/orders/{orderId}/buyerInfo to get the buyer information
/orders/v0/orders/{orderId}/orderItems/buyerInfo  to get the gift wrap price of the item
}

In order to fulfill the FBM order and get all types of prices of the orders, we need the shipping address and the email and gift wrap price,  we need to make 3 extra API requests for each order. Too many requests will bring more "request is throttled" problems. It doesn't look very nice solution, Is there a better way to accomplish this?

**Comment by intellifox-hq** [comment]
Hi @NancyLin 
All you have to do is wait the proper amount of seconds between each call for the same route.
Each route have their own throttling limits and if you respect them properly then everything will be a smooth ride.

Be careful of one thing: each route have a different time!

**Comment by NancyLin** [comment]
> Hi @NancyLin
> All you have to do is wait the proper amount of seconds between each call for the same route.
> Each route have their own throttling limits and if you respect them properly then everything will be a smooth ride.
> 
> Be careful of one thing: each route have a different time!

Yes, I wait the proper amount of seconds between each call for the same route. But I get complete order information now I need to make 5 requests and the MWS API just needs to make 2 requests. It takes longer to get complete order information. This is a terrible experience.

**Comment by intellifox-hq** [comment]
> Yes, I wait the proper amount of seconds between each call for the same route. But I get complete order information now I need to make 5 requests and the MWS API just needs to make 2 requests. It takes longer to get complete order information. This is a terrible experience.

Sorry but I don't find any issue there.
You can call them in parallel and compose your request with the available routes.

I don't agree that this is a "terrible experience":

```js
const get_order_details = async ({ access_token, market_place, order_id }) => {

  const [items, financial_events] = await Promise.all([
    get_order_detail({
      access_token, market_place, order_id,
      path: `/orders/v0/orders/${order_id}/orderItems`,
    }),
    get_order_detail({
      access_token, market_place, order_id,
      path: `/finances/v0/orders/${order_id}/financialEvents`,
    }),
  ])

  return {
    items, financial_events,
  }
}
```
(this is our production code code, using parallel calls to the API)

**Comment by fernlop** [comment]
I think the point is not, that you can't find a solution for throttling etc. But it's not best practice to have 5 API calls for something that was only one with MWS and any other platform, for example eBay supports this all in one request.

**Comment by NancyLin** [comment]
> > Yes, I wait the proper amount of seconds between each call for the same route. But I get complete order information now I need to make 5 requests and the MWS API just needs to make 2 requests. It takes longer to get complete order information. This is a terrible experience.
> 
> Sorry but I don't find any issue there.
> You can call them in parallel and compose your request with the available routes.
> 
> I don't agree that this is a "terrible experience":
> 
> ```js
> const get_order_details = async ({ access_token, market_place, order_id }) => {
> 
>   const [items, financial_events] = await Promise.all([
>     get_order_detail({
>       access_token, market_place, order_id,
>       path: `/orders/v0/orders/${order_id}/orderItems`,
>     }),
>     get_order_detail({
>       access_token, market_place, order_id,
>       path: `/finances/v0/orders/${order_id}/financialEvents`,
>     }),
>   ])
> 
>   return {
>     items, financial_events,
>   }
> }
> ```
> 
> (this is our production code code, using parallel calls to the API)

Can you use the financialEvents API to get the buyer's shipping address and email?  We need to ship according to the buyer's order. And we need the final amount for each amount type(such as ItemPrice, ItemTax, ShippingPrice, ShippingPrice, etc.), is that we have to calculate the final amount by ourselves from the financial event lists?

**Comment by BrockleyJohn** [comment]
Of course it's not insurmountable and some is due to roles etc but it's ridiculous that you have to make an individual follow up call per order to get the items and that there's not an option to return items with orders in the first place... especially as amazon orders with more than one item are as common as rocking horse droppings.
Maybe the lack of use case documentation is no coincidence.
