### ISSUE TITLE
LWA authorization code for a LWA refresh token

### ISSUE THREAD

**Issue by AlexMteam** [amzn/selling-partner-api-docs#466]
Hello, I had faced with problem on oAuth.
When I try to go throw [Step4](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-your-application-exchanges-the-lwa-authorization-code-for-a-lwa-refresh-token)
system return error {"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}.

I verified my credential all is ok.
Can you help me with this issue.
P.S. I tried to open support case on https://developer.amazonservices.com/support but they are sleeping.

**Comment by MST1122** [comment]
Hi @AlexMteam, LWA Authorization Code is valid for a limited time. you have to exchange it for LWA RefreshToken directly after acquiring it.

Let me know if this helped you.

**Comment by AlexMteam** [comment]
> Hi @AlexMteam, LWA Authorization Code is valid for a limited time. you have to exchange it for LWA RefreshToken directly after acquiring it.
> 
> Let me know if this helped you.

I sent request to LWA RefreshToken after  ~ 15-20 min.
Where did you find info about life cycle of LWA Authorization Code ?

**Comment by MST1122** [comment]
I didn't find it anywhere, I happen to face this similar issue and it worked for me if I exchange token within like 3-5 minutes.

**Comment by AlexMteam** [comment]
> I didn't find it anywhere, I happen to face this similar issue and it worked for me if I exchange token within like 3-5 minutes.

Tried another one, did not help me, run script after 30 sec did not help me.

**Comment by MST1122** [comment]
I'm using this package and also maintaining it. please take a look at it. It contains the all required functionality.

https://github.com/double-break/spapi-php

**Comment by AlexMteam** [comment]
Issue solved, looks like i missed some point on register, after several new register problem was solved.

**Comment by wmh49877** [comment]
> 问题解决了，看起来我错过了一些点注册后，几个新的注册问题得到解决。

hi,How did you solve this problem, I also encountered this problem

**Comment by AlexMteam** [comment]
> > 问题解决了，看起来我错过了一些点注册后，几个新的注册问题得到解决。
> 
> hi,How did you solve this problem, I also encountered this problem

This comment saved me, I hope u too.
https://stackoverflow.com/questions/64560163/access-to-requested-resource-is-denied-403-sp-api-amazon-c-sharp/66860192#66860192

**Comment by wmh49877** [comment]
> > > 问题解决了，看起来我错过了一些点注册后，几个新的注册问题得到解决。
> > 
> > 
> > hi,How did you solve this problem, I also encountered this problem
> 
> This comment saved me, I hope u too.
> https://stackoverflow.com/questions/64560163/access-to-requested-resource-is-denied-403-sp-api-amazon-c-sharp/66860192#66860192

Thanks, I also solved it. This is very useful @AlexMteam

**Comment by arthurchan1906** [comment]
I got spapi_oauth_code after step 4, but in step 5, the response is empty set, no access token

**Comment by arthurchan1906** [comment]
my application state is in draft status
