### ISSUE TITLE
Difference with MWS and Amazon SP-API (GetMatchingProductForId vs listCatalogItems)

### ISSUE THREAD

**Issue by mravoni** [amzn/selling-partner-api-docs#469]
Function GetMatchingProductForId in MWS can let you insert 5 id (EAN,UPS...) for each request. 
listCatalogItems (equivalent in SP-API) can let you insert 1 id for request.
 I don't think this is an upgrade because now to match the same 5 id it need at least 5 seconds.
There's another way to get the same response without waisting time?

**Comment by educatornum** [comment]
Hi Sir @mravoni

**Comment by chapmanjw** [comment]
The Catalog v0 `listCatalogItems` is a singular, non-batched operation. If your use-case cannot be served with the current API and rates, I would suggest contacting Developer Support: https://developer.amazonservices.com/support

**Comment by ulandj** [comment]
Hey guys, 
I have the same issue. In MWS I use `GetMatchingProductForId` to fetch 5 product details by SellerSKU in a single request. But using SP API I have to do 5 different requests. 
@mravoni Have you found a solution to this?
Thanks

**Comment by wangjue666** [comment]
I think the design of listcatalogitems API is unreasonable。It should be batch operated
