### ISSUE TITLE
Whos the clown 🤡 thats rolling out the MWS updates?

### ISSUE THREAD

**Issue by hollandjahleel** [amzn/selling-partner-api-docs#472]
🤡

**Comment by hollandjahleel** [comment]
@seanevan is it yourself that's rolling this out in such a poor way? If not could you point me to the person I need to talk to? Maybe @parvathm or @ShivikaK ?

**Comment by seanevan** [comment]
@hollandjahleel, you haven't provided any specifics in this issue, so we can't answer your question. I am closing this issue as a result. If you have an issue related to Selling Partner API, please feel free to open a new issue with the details.

Thanks,
Sean Evans
Manager, Support Engineering
