### ISSUE TITLE
Error creating a SP-API Application: SPDC300

### ISSUE THREAD

**Issue by GeoffTK** [amzn/selling-partner-api-docs#473]
Whenever I attempt to submit my application listing, I get the following error:

Something went wrong
Please try again at a later time If the problem persists, please contact Seller Support and provide them with the following information: SPDC300

I have had a support ticket opened for 3-4 days now and haven't received any help (ID 8067532491).  Hoping someone here can help me resolve this.

**Comment by GeoffTK** [comment]
I have seen @ShivikaK come to the rescue for a few others who have posted these issues before.

**Comment by ShivikaK** [comment]
Hello @GeoffTK 

Thank you for raising this issue.

The error regarding app submission has been reported to the engineering team for further investigation and you should have received an update on the support case as well. 

Please continue monitoring the case for updates and next steps.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
