### ISSUE TITLE
🤡

### ISSUE THREAD

**Issue by hollandjahleel** [amzn/selling-partner-api-docs#474]
Ref https://github.com/amzn/selling-partner-api-docs/issues/472 

The specifics of the question, just to clarify, was: Who do I speak to about the **poor rollout** of the MWS updates?

**Comment by fernlop** [comment]
Even though you are right, this is not the correct way to handle this, keep it professional here please. 
If you **really** want to do something about it and not just cry, try to find out who's responsible and try to contact them.

**Comment by hollandjahleel** [comment]
> Even though you are right, this is not the correct way to handle this, keep it professional here please.

I'm glad you agree, I will keep it how ever I wish! :)

> If you really want to do something about it and not just cry, try to find out who's responsible and try to contact them.

Precisely what I'm doing, I think you read the question I put and just didn't comprehend it.
