### ISSUE TITLE
The authorize endpoint asks for the MWS DeveloperID

### ISSUE THREAD

**Issue by fmaurobica** [amzn/selling-partner-api-docs#475]
Hello everyone,
I am having some problems trying to self-authorize my app with the new SP-API that Amazon provides.
The problem is similar to the one in ticket #288

This is my problem:
I have an app listed on the Amazon AppStore. 
The app ID is amzn1.sellerapps.app.e0bd6667-ab60-4747-843c-2d6974cf55c2
As written in the documentation (I am following the website workflow), I have to redirect the user's browser to this page, to let the user (in this case myself) authorize my app. The link I am using is the following:

https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.e0bd6667-ab60-4747-843c-2d6974cf55c2&state=15 

The page first asks me which marketplace I want to authorize, then a page shows up, asking me for an MWS DeveloperId.
From what I known, this DeveloperId is not needed for the new Sp API. So why it asks me for this data?
When I was in beta, the same page asks me for the permissions that I want to give to the app.
I already tried to open a ticket on Amazon Seller Center, but the operator asks me to check my MWS settings (MWS is deprecated so I want to use the new SP Apis).

Thank you for your support
Best regards

![image](https://user-images.githubusercontent.com/80271836/110343238-92846a80-802c-11eb-8f4e-2edd65f9ed8c.png)

**Comment by fmaurobica** [comment]
This is the same page, in English
![image](https://user-images.githubusercontent.com/80271836/110343966-50a7f400-802d-11eb-9049-9a94820a5bd1.png)

**Comment by krithic15** [comment]
Hello there,

The reason you are seeing the legacy MWS authorization flow[requesting for dev ID] is because your SP API app is still in draft state and not yet published. With a draft app, you can use the below auth uri with 'version=beta' parameter which will take you to the consent page and let you authorize your app in draft state. [mentioned under website oauth flow in Developer Gudie]
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.e0bd6667-ab60-4747-843c-2d6974cf55c2&state=15&version=beta

**Comment by fmaurobica** [comment]
Hello Krithi,
our SP API is already published (see the attachment).
Are there any other reasons why the authorization page proposes the legacy workflow?

Best regards
![image](https://user-images.githubusercontent.com/80271836/110910514-bb994980-8311-11eb-9aad-b3ffe327d2de.png)

**Comment by krithic15** [comment]
@fmaurobica Thank you for the additional details. I looked into your app configuration and see that it is published but the 'Enable Oauth' flag is unchecked which is required to switch to oauth flow after publishing. Can you please click on 'Edit App' and then choose 'enable Oauth' and go through the publish workflow again? That should resolve the issue.

Best,
Krithi,
Solutions Architect, SP API

**Comment by krithic15** [comment]
@fmaurobica Please let me know if you do not see the 'Enable Oauth' option under 'Edit App' as there was a recent update to enable this by default. I can have the team fix it for you.

Best,
Krithi,
Solutions Architect, SP API

**Comment by fmaurobica** [comment]
@krithic15 Thank you for your reply. I don't see an "Enable Oauth" button. When I click on "Edit app", this is what I see:
![image](https://user-images.githubusercontent.com/80271836/111121617-2d210400-856d-11eb-9867-b8e17568ff3f.png)

Besides the "Edit app", the other options in the menu are the following
![image](https://user-images.githubusercontent.com/80271836/111121720-50e44a00-856d-11eb-8b2b-fba0bf150030.png)

Best regards

**Comment by krithic15** [comment]
Hi @fmaurobica,

We have identified the issue and the team is actively working on the fix. I will update you as soon as the issue is fixed. Apologies for the inconvenience and thank you for your patience!

Best,
Krithi,
Solutions Architect, SP API

**Comment by fmaurobica** [comment]
Good morning @krithic15,
thank you for your reply. 
Do you have any news on this problem? I hope in a resolution before the month of April 2021 (https://github.com/amzn/selling-partner-api-docs/issues/489)

Best regards

**Comment by krithic15** [comment]
Hello @fmaurobica ,

We have fixed the issue. Can you please test it again and confirm?

Best,
Krithi,
Solutions Architect, SP API

**Comment by fmaurobica** [comment]
Hello @krithic15,
I confirm that now I am able to authorize my app using Oauth.

Best regards
