### ISSUE TITLE
Seller consents page not displayed (You do not have permissions to view this page)

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-docs#476]
I have Authorize Now button setup as documentation suggest. When seller press button, login into seller central he receive "You do not have permissions to view this page". No consent is displayed for him. What could be the reason for this? 
What are requirements for seller to be able to authorise access of application?

**Comment by krithic15** [comment]
Hello there,

Can you please have this seller confirm that their account is not blocked and is in an active status?
Also, please make sure the the user logging in to this seller account has the necessary permissions to access the consent page. For more information https://sellercentral.amazon.com/gp/help/help.html?itemID=G21861&language=en_US

If the seller is unsure, I would suggest that they open a support case to have their account looked into.

Best,
Krithi
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @tspicer,

You can refer to this documentation page which talks about each role and all the resources and reports you can get access to with it.
https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api

Best,
Rugved
Solutions Architect, SP API

**Comment by tspicer** [comment]
Hi @rugved1991 , those are the application roles, I was asking about the specific permissions in Seller Central. Users are asking for the mapping to the settings in User Permissions. See https://docs.openbridge.com/en/articles/5391780-amazon-selling-permissions
