### ISSUE TITLE
Website workflow Auth does not redirecting after permissions confirmation

### ISSUE THREAD

**Issue by GuillermoZAfiroCode** [amzn/selling-partner-api-docs#48]
When user click to authoritation button, amazon should redirect to redirect_uri saved in API configuration but it doesn't works for me

**Comment by charliecode** [comment]
Hello @GuillermoZAfiroCode. I may be able to be of assistance in pointing you in the right direction but you'll need to provide more details. Which authorization flow are you using? The "[Marketplace Appstore workflow](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#marketplace-appstore-workflow)" or the" [Website workflow](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#website-workflow)"? Sounds like you might be using the "Marketplace Appstore workflow". Regardless, it could be an issue with Amazon as they're having a lot of issues at the moment. It could also be something you over looked. In the event it's something you overlooked I may be able to spot it based off what I've learned so far.

**Comment by GuillermoZAfiroCode** [comment]
Hi @charliecode, thanks for you reply,
Im trying to using " Website workflow". I did all steps described in [developer guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md), but after log in and continue in amazon, it dont redirect to my url (redirect_url)

**Comment by charliecode** [comment]
I understand you perfectly. No need to apologize, your English is not bad at all and the important thing is that you're putting effort forth, that's more than most people can say.

You mentioned that "amazon should redirect to redirect_uri saved in API configuration", I think that's where your issue might be. Amazon actually redirects to the "OAuth Redirect URI" which is added when you do [Step 6. Register your application](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-6-register-your-application) under [Registering your Selling Partner API application](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application). This might be your issue.

**Comment by GuillermoZAfiroCode** [comment]
I followed the steps mentioned in Step 6 and I added information to this form (see image)

I thougth that after user login and accept, amazon must redirect to  "OAuth Redirect URI" field but  it stai in amazon page with white content

![image](https://user-images.githubusercontent.com/73171256/96621219-a727c680-1308-11eb-8b09-ddd66d0ec522.png)

Am I doing something wrong?

**Comment by charliecode** [comment]
When the seller clicks the "authorize" button in Step 0. [Set up your OAuth authorization URIs](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-0-set-up-your-oauth-authorization-uris) which "OAuth authorization URI" are you loading in the browser to redirect them to Seller Central? Is it like one of the ones in the examples under [Step 1. The seller initiates authorization from your website](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#Step-1-The-seller-initiates-authorization-from-your-website)? Like one of these -

For testing:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample&version=beta

For prod:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample

I would try using the example for testing and see if that works first, with the "&version=beta" added to the URL. When the redirect happens back to your website, it's supposed to redirect them back to your website with the "URI de redirección de OAuth" from your picture. So as long as you have everything filled out correctly and if you still can't get it working, it might be an issue with Amazon. I am having a related issue like this as well. I was directed to [create a case](url
![image](https://user-images.githubusercontent.com/22284644/96630750-50030100-12ca-11eb-8c00-f4616f615ce6.png)
), you may want to as well.

**Comment by GuillermoZAfiroCode** [comment]
Thank you!

I have created a case in amazon and they told me that it is an issue and the are working on it.
Hope they solve it as fast as possible :)

Thank for your hel @charliecode!

**Comment by ionafan2** [comment]
Hi @GuillermoZAfiroCode,
Do you have any updates on the case? 
Because I have the same issue, after seller Authorize my App it's not sending (redirecting) the user back to my website.
Thanks!

**Comment by GuillermoZAfiroCode** [comment]
Hi @ionafan2,

it seems language issue, I suppose that you are trying it in other language that not is English.
If you change the Amazon's language (in the footer of authorization page) it works fine.

I opened a case for this and few weeks after they solve that issue.

if you are not trying in spanish, maybe you must open another case describing the problem.

hope it helps you.

**Comment by moltar** [comment]
Same issue here. The console is also throwing the following error:

```
Uncaught TypeError: e is undefined
    buildUrl main.0648c4e81292709d8512.min.js:678
    handleRedirect main.0648c4e81292709d8512.min.js:4036
    s 1.b082f81cf7ca5fabfcf5.min.js:2
    h 1.b082f81cf7ca5fabfcf5.min.js:2
    b 1.b082f81cf7ca5fabfcf5.min.js:2
    b 1.b082f81cf7ca5fabfcf5.min.js:2
    ae 1.b082f81cf7ca5fabfcf5.min.js:2
    ie 1.b082f81cf7ca5fabfcf5.min.js:2
    se 1.b082f81cf7ca5fabfcf5.min.js:2
main.0648c4e81292709d8512.min.js:formatted:678
    buildUrl main.0648c4e81292709d8512.min.js:678
    handleRedirect main.0648c4e81292709d8512.min.js:4036
    <anonymous> self-hosted:1176
    s 1.b082f81cf7ca5fabfcf5.min.js:2
    h 1.b082f81cf7ca5fabfcf5.min.js:2
    b 1.b082f81cf7ca5fabfcf5.min.js:2
    b 1.b082f81cf7ca5fabfcf5.min.js:2
    ae 1.b082f81cf7ca5fabfcf5.min.js:2
    ie 1.b082f81cf7ca5fabfcf5.min.js:2
    se 1.b082f81cf7ca5fabfcf5.min.js:2
    he 1.b082f81cf7ca5fabfcf5.min.js:2
    M 1.b082f81cf7ca5fabfcf5.min.js:2
    q 1.b082f81cf7ca5fabfcf5.min.js:2
    Je 1.b082f81cf7ca5fabfcf5.min.js:2
    Xe 1.b082f81cf7ca5fabfcf5.min.js:2
    bind_applyFunctionN self-hosted:1374
    Xe self-hosted:1337
    unstable_runWithPriority 1.b082f81cf7ca5fabfcf5.min.js:2
    zi 1.b082f81cf7ca5fabfcf5.min.js:2
    N 1.b082f81cf7ca5fabfcf5.min.js:2
    Qe 1.b082f81cf7ca5fabfcf5.min.js:2
    bind_applyFunctionN self-hosted:1374
    Qe self-hosted:1337
    (Async: EventListener.handleEvent)
    Ye 1.b082f81cf7ca5fabfcf5.min.js:2
    $e 1.b082f81cf7ca5fabfcf5.min.js:2
    de 1.b082f81cf7ca5fabfcf5.min.js:2
    un 1.b082f81cf7ca5fabfcf5.min.js:2
    Ga 1.b082f81cf7ca5fabfcf5.min.js:2
    lu 1.b082f81cf7ca5fabfcf5.min.js:2
    cu 1.b082f81cf7ca5fabfcf5.min.js:2
    su 1.b082f81cf7ca5fabfcf5.min.js:2
    Zs 1.b082f81cf7ca5fabfcf5.min.js:2
    Zs self-hosted:1223
    Hi 1.b082f81cf7ca5fabfcf5.min.js:2
    unstable_runWithPriority 1.b082f81cf7ca5fabfcf5.min.js:2
    zi 1.b082f81cf7ca5fabfcf5.min.js:2
    Hi 1.b082f81cf7ca5fabfcf5.min.js:2
    Ki 1.b082f81cf7ca5fabfcf5.min.js:2
    Ys 1.b082f81cf7ca5fabfcf5.min.js:2
    enqueueSetState 1.b082f81cf7ca5fabfcf5.min.js:2
    setState 1.b082f81cf7ca5fabfcf5.min.js:2
    onStateChange 1.b082f81cf7ca5fabfcf5.min.js:2
    <anonymous> self-hosted:1176
    y 1.b082f81cf7ca5fabfcf5.min.js:2
    T 1.b082f81cf7ca5fabfcf5.min.js:2
    c 1.b082f81cf7ca5fabfcf5.min.js:2
    dispatch 1.b082f81cf7ca5fabfcf5.min.js:2
    __tryOrUnsub 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    notifyNext 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    notifyNext 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    notifyNext 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    notifyNext 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    subscribeToResult 1.b082f81cf7ca5fabfcf5.min.js:2
    _innerSub 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    s 1.b082f81cf7ca5fabfcf5.min.js:2
    (Async: EventHandlerNonNull)
    setupEvents 1.b082f81cf7ca5fabfcf5.min.js:2
    send 1.b082f81cf7ca5fabfcf5.min.js:2
    e 1.b082f81cf7ca5fabfcf5.min.js:2
    _subscribe 1.b082f81cf7ca5fabfcf5.min.js:2
    _trySubscribe 1.b082f81cf7ca5fabfcf5.min.js:2
    subscribe 1.b082f81cf7ca5fabfcf5.min.js:2
    call 1.b082f81cf7ca5fabfcf5.min.js:2
    subscribe 1.b082f81cf7ca5fabfcf5.min.js:2
    call 1.b082f81cf7ca5fabfcf5.min.js:2
    subscribe 1.b082f81cf7ca5fabfcf5.min.js:2
    subscribeToResult 1.b082f81cf7ca5fabfcf5.min.js:2
    _innerSub 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    _next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    next 1.b082f81cf7ca5fabfcf5.min.js:2
    c 1.b082f81cf7ca5fabfcf5.min.js:2
    updateProductDetails main.0648c4e81292709d8512.min.js:3846
    componentDidMount main.0648c4e81292709d8512.min.js:3776
    os 1.b082f81cf7ca5fabfcf5.min.js:2
    hu 1.b082f81cf7ca5fabfcf5.min.js:2
    hu self-hosted:1280
    unstable_runWithPriority 1.b082f81cf7ca5fabfcf5.min.js:2
    zi 1.b082f81cf7ca5fabfcf5.min.js:2
    pu 1.b082f81cf7ca5fabfcf5.min.js:2
    Zs 1.b082f81cf7ca5fabfcf5.min.js:2
    Zs self-hosted:1223
    Hi 1.b082f81cf7ca5fabfcf5.min.js:2
    unstable_runWithPriority 1.b082f81cf7ca5fabfcf5.min.js:2
```

Relevant code (minified, but prettified):

```js
    t.buildUrl = function (e, t) {
      void 0 === t && (t = {
      }),
      e.endsWith('?') && (e = e.replace('?', ''));
      var r = Object.keys(t).filter((function (e) {
        return null != t[e]
      })).map((function (e) {
        return t[e] ? encodeURIComponent(e) + '=' + encodeURIComponent(t[e]) : ''
      })).join('&');
      return r.length > 0 && (e.lastIndexOf('?') > 0 && e.lastIndexOf('&') < e.length - 1 ? e = e + '&' + r : e.lastIndexOf('?') > 0 && e.lastIndexOf('&') === e.length - 1 ? e += r : e = e + '?' + r),
      e
    }
```

**Comment by moltar** [comment]
Apparently the issue might be related to having the oauth login url filled out.

**Comment by pprbhm** [comment]
Hello, Please feel free to open a [support case](https://developer.amazonservices.com/support) with Developer support team to work on closely to troubleshoot the issue. We will have to recreate the issue and understand what causes this to happen. 
Thank you.
