### ISSUE TITLE
/catalog/v0/items endpoint returning other account product

### ISSUE THREAD

**Issue by madhupatel-hub** [amzn/selling-partner-api-docs#481]
My seller partner account has only 1 product.
But when I try to filter products by using /catalog/v0/items endpoint.
It will return me 10 products and it's not from my account. Please check this issue ASAP or let me know if I'm doing anything wrong. I have also attached the response JSON.
[response.txt](https://github.com/amzn/selling-partner-api-docs/files/6115102/response.txt)

My Query
https://sellingpartnerapi-eu.amazon.com/catalog/v0/items?MarketplaceId=A21TJRUUN4KGV&Query=n

I have one more question, how can I get all products from my account?
I can't find any endpoint for get all products. can you please provide the endpoint for it?
Thanks
Madhu Patel

**Comment by chapmanjw** [comment]
@madhupatel-hub The Catalog Items API is representative of the Amazon catalog (ASINs) data as display on Amazon retail websites. It does not cover listings (SKU) data.

**Comment by vikingcodes** [comment]
@madhupatel-hub "how can I get all products from my account?" Don't have any API which return all products from account. You need to use Report API with "Inventory report type.
