### ISSUE TITLE
Need clarification on get all item endpoint.

### ISSUE THREAD

**Issue by madhupatel-hub** [amzn/selling-partner-api-docs#482]
Team,
I can't find any endpoint where I can get my all product.
Do we have any endpoint for the same?
If yes please provide the endpoint detail.
if no please let me know how can I retrieve all products.
Thanks Again
Madhu Patel

**Comment by vdanyliv** [comment]
@madhupatel-hub  check reports-api

**Comment by madhupatel-hub** [comment]
Thanks for the quick response @vdanyliv I have tried with different reportTypes but not able to get all products.
can you please check the below details if I doing anything wrong?
My Query:
https://sellingpartnerapi-eu.amazon.com/reports/2020-09-04/reports?reportTypes=GET_MERCHANT_LISTINGS_ALL_DATA
My response
![Screenshot (123)](https://user-images.githubusercontent.com/59440968/110620518-19694c80-81bf-11eb-98b7-af45f07b3749.png)
Thanks Again!
Madhu Patel

**Comment by vdanyliv** [comment]
@madhupatel-hub read the docs carefully. There is a lot of steps that need to do to get report data.

**Comment by madhupatel-hub** [comment]
Thanks @vdanyliv it's working for me.

**Comment by coder771** [comment]
@vdanyliv @madhupatel-hub - can you please point me to the link where there are steps to get report data. I can see below but it doesn't have step as in what requests are needed for the flow like we have in feeds api

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md
