### ISSUE TITLE
SP-API Sandbox FBA createInboundShipment getting InternalServerError

### ISSUE THREAD

**Issue by RJEspera** [amzn/selling-partner-api-docs#486]
When posting a request to /fba/inbound/v0/shipments/{shipmentId}.  I'm getting InternalServerError, ("We encountered an internal error. Please try again").  There's no error detail, so I can't tell what the problem is.

I was able to acquire access token, and the signature matches.  There's no error there, but it's still unable to process the request. 
I'm passing the data to the body, which is done in client with this assignment:  var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(body, _settings.Value));

The body json string (which is the sample parameters in the fulfillmentInboundV0.json file included in the SDK) is as follows: "{\"InboundShipmentHeader\":{\"ShipmentName\":\"43545345\",\"ShipFromAddress\":{\"Name\":\"35435345\",\"AddressLine1\":\"123 any st\",\"DistrictOrCounty\":\"Washtenaw\",\"City\":\"Ann Arbor\",\"StateOrProvinceCode\":\"Test\",\"CountryCode\":\"US\",\"PostalCode\":\"48103\"},\"DestinationFulfillmentCenterId\":\"AEB2\",\"AreCasesRequired\":true,\"ShipmentStatus\":\"WORKING\",\"LabelPrepPreference\":\"SELLER_LABEL\",\"IntendedBoxContentsSource\":\"NONE\"},\"InboundShipmentItems\":[{\"ShipmentId\":\"345453\",\"SellerSKU\":\"34534545\",\"FulfillmentNetworkSKU\":\"43545345\",\"QuantityShipped\":0,\"QuantityReceived\":0,\"QuantityInCase\":0,\"ReleaseDate\":\"2021-03-31\",\"PrepDetailsList\":[{\"PrepInstruction\":\"Polybagging\",\"PrepOwner\":\"AMAZON\"}]}],\"MarketplaceId\":\"MarketplaceId\"}"

One thing I had to do to make the signature match is to ignore null on json serializer setting.

Please let me know what I could be missing.

**Comment by RJEspera** [comment]
I was able to resolve this.  The problem was the 'ReleaseDate' value I passed was the datetime when the test ran, but the Sandbox requires the value to be the same as the example.

I still would like to see 'detail' on the error.  Is there a plan on sending more useable message when this type of error occurs?  And also, is the response (or lack there of) be the same in production?

**Comment by johnkw** [comment]
The whole "sandbox" thing is rather useless in its current state. It should probably just be removed entirely to avoid confusion.
