### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by Luis-DdlFG** [amzn/selling-partner-api-docs#487]
I deeply apoligize if this is not the space to place this question but I believe this is related to documentation.

**Describe the bug**
I'm getting the following response from the API when calling GetOrders 

```
	{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
```

I'm a root user and as such I created

- IAM User
- IAM Policy
- IAM Role (attaching the User Name and Policy Name)
- AWS STS Token
- Attached the Policy to the User

As a root user I don't have access Seller Central -> Apps & Services -> Develop Apps, so the Admin user did register the application using the IAM ARN for the User.

(Is this correct? Or should I request access with my root user to Apps & Services and deploy  it myself?)

I then:

- Requested the access token using grant_type: refresh_token and the client ID and client secret of the deployed app
- Created the canonical request
- Calculated the signature
- Made the request

By looking at this issue: https://github.com/amzn/selling-partner-api-docs/issues/52

It mentions that we need to _assume the role that we used when adding an application_ How can we know when do we need to assume this role? Am I in a case of cross-account access because the Admin was the one who deployed the App?

**Comment by kevinhq** [comment]
We have exactly [same problem](https://github.com/amzn/selling-partner-api-docs/issues/509). Any update on this?

**Comment by Luis-DdlFG** [comment]
I think I moved beyond this problem by double checking Refresh token, cliend id and client secret.

Also checked that the Access Key ID.

In my case I'm using the client, not the role, to connect to the API.

Finally, I also attached the policy to the User

With that checked I'm not getting this error:

```
{
  "errors": [
    {
     "message": "Missing or invalid request parameters: [MarketplaceIds]",
     "code": "InvalidInput"
    }
  ]
}
```

**Comment by kevinhq** [comment]
Thanks for the response

> In my case I'm using the client, not the role, to connect to the API. Finally, I also attached the policy to the User

We've also attached the in line policy to the user, but our SP-API app is using the Role's ARN. 

Do you mean to change it using the User's ARN? 

Because when I tried to edit the app, that ARN field is disabled.

**Comment by Luis-DdlFG** [comment]
Yeap,

We have the option to decide wheter we use the User or Role ARN.

In my case it worked the following>

- Attach the policy to the User
- Register the application with the User ARN (In case you created one with the Role's ARN you can create a new application)
- Use the following fields from the new application registered: ClientID, ClientSecret and Refresh Token
- When calling the API also use the Access Key ID of the Client.

In my case I was mixing things up. I hope this helps, otherwise let me know if there is any other doubt.
