### ISSUE TITLE
Access to requested resource is denied.

### ISSUE THREAD

**Issue by emmendoza2794** [amzn/selling-partner-api-docs#488]
Hello friends, I have a problem accessing the resource GET /catalog/v0/items/  

I have already written to support but they have not given me a solution, I have everything fine because if I have access to other resources without problems, I already have all the permissions active but I continue to receive this problem.
I hope someone from support will take a look at my problem, the case number is 8073723611.
the error that I get is the following

```
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
      "code": "Unauthorized",
      "details": ""
    }
  ]
}
```

**Comment by krithic15** [comment]
Hello there,

I just reviewed your case and I am unable to check your app permissions as the case does not have your App ID details.
Can you confirm if your app has the Product Listing role associated with it? You can check by clicking on 'Edit App' next to your app on your Developer Central console and then checking the list of Roles you have chosen for your app.

[or] Please update the case with your App ID and I will have a support member look into it.

Best,
Krithi
Solutions Architect, SP API

**Comment by emmendoza2794** [comment]
Thank you very much for your prompt response, the application does not give me the option to edit, I think it is because the status is Submitted (Edit pending review).

![image](https://user-images.githubusercontent.com/24445416/110886993-8233f000-82b7-11eb-9fd8-f94dc3bda1f6.png)


But solve the problem by creating another app and now if I get a satisfactory answer.

Thank you very much.
