### ISSUE TITLE
Link to Authorization API User Guide

### ISSUE THREAD

**Issue by rick-ritts** [amzn/selling-partner-api-docs#49]
On this page:
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#hybrid-selling-partner-api-applications

In this section:
**Migrating authorization from Amazon Marketplace Web Service**
If a selling partner has authorized you to make calls to Amazon Marketplace Web Service on their behalf, you can use the Authorization API to migrate that authorization to a hybrid Selling Partner API application. This eliminates the need to request authorization from the selling partner again. For more information, see the _Authorization API User Guide_.

There is a reference to the '**Authorization API User Guide**'. Can you make this a link or let me know where this guide can be located? 

Thanks!

**Comment by charliecode** [comment]
Hello @rick-ritts. They're probably referring to the [selling-partner-api-models](https://github.com/amzn/selling-partner-api-models). With those models you can create a client library [using the models json file](https://github.com/amzn/selling-partner-api-models/tree/main/models) using a code generator like swagger-codegen or [openapi-generator](https://openapi-generator.tech/docs/generators), which I feel is a much better solution with far superior docs. You can also create docs using the same json file for each api. The [authorization api](https://github.com/amzn/selling-partner-api-models/tree/main/models/authorization-api-model) you mentioned is one them, which is used to do exactly what you're referring to.

**Comment by rugved1991** [comment]
Hi @rick-ritts,

Here is the link to the [Authorization Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md).

Thanks,
Rugved
Solutions Architect, SP API
