### ISSUE TITLE
 fbaInboundApi.createInboundShipment get error :$inputRoot.Message

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-docs#490]
class InboundShipmentRequest {
    inboundShipmentHeader: class InboundShipmentHeader {
        shipmentName: 43545345
        shipFromAddress: class Address {
            name: uan
            addressLine1: Room 1002，Unit C，Block127，Baixin Garden,
            Chunjiang Town, Xinbei District
            addressLine2: null
            districtOrCounty: null
            city: Changzhou
            stateOrProvinceCode: JS
            countryCode: CN
            postalCode: 213000
        }
        destinationFulfillmentCenterId: DCA6
        areCasesRequired: null
        shipmentStatus: WORKING
        labelPrepPreference: SELLER_LABEL
        intendedBoxContentsSource: NONE
    }
    inboundShipmentItems: class InboundShipmentItemList {
        [class InboundShipmentItem {
            shipmentId: FBA
            sellerSKU: HM789
            fulfillmentNetworkSKU: X00
            quantityShipped: 6
            quantityReceived: 0
            quantityInCase: 0
            releaseDate: 2021-03-31
            prepDetailsList: null
        }]
    }
    marketplaceId: ATV
}

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "$inputRoot.Message",
      "details": ""
    }
  ]
}

**Comment by waicraft** [comment]
Hello, have you gotten past this error? I have a ticket open with mws-level2 support since March 11th with no luck yet.
