### ISSUE TITLE
[BUG] Documentation / API Issue - deleteSubscriptionById for B2B_ANY_OFFER_CHANGED

### ISSUE THREAD

**Issue by tabertantrum** [amzn/selling-partner-api-docs#493]
**Describe the bug**
deleteSubscriptionById for B2B_ANY_OFFER_CHANGED fails with a grantless request
It is unclear if this is a documentation or API issue.
A support case has also been created (Case ID: 8094742471)

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md#deletesubscriptionbyid

**Description of what the documentation currently says**
Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. **The deleteSubscriptionById API is grantless.**

_(emphasis added)_

**Description of what the documentation should say**
Documentation should either identify the B2B_ANY_OFFER_CHANGED notificationType as requiring seller authorization, or this is a bug in the API.

**Comment by webinsect-rishabh** [comment]
is Notification API worked for you? can you please explain.
I am stuck at createDestination(). I am passing the correct parameter but always leaves with 403 error code.
