### ISSUE TITLE
Continued use of MWS API while experimenting with SP-API

### ISSUE THREAD

**Issue by samamorgan** [amzn/selling-partner-api-docs#494]
We would like to begin testing calls to the new SP-API, but our current MWS automations are business-critical. We're worried that if we go through the self-authorization process we may have to make changes to the current automations, or they may cease functioning altogether.

Is there any possibility that, if we go through the self-authorization process, our current calls to the MWS API, that makes calls using only AccessKey/SecretKey (not auth token), will no longer function?

**Comment by johnkw** [comment]
We're currently using MWS and SP-API. SP-API is incomplete, so there are still some things that can only be done with MWS.

**Comment by samamorgan** [comment]
@johnkw Thanks for jumping in!

I'm mostly wanting to ensure that if we start using this API, our current method of authorization with the MWS API won't be invalidated. I don't want to scramble to create an authorization token, etc, for MWS.

Did you have to make any changes to your pre-existing MWS authorization mechanism when you started using SP-API?

**Comment by krithic15** [comment]
Hello there,

You can continue to test and build SP APIs without having your MWS set up affected. The SP API oauth authorization workflow kicks in only after you publish your SP API application in AppStore after which you can use Authorization API to migrate MWS authorizations to SP API platform.

Best,
Krithi, 
Solutions Architect, SP API

**Comment by samamorgan** [comment]
@krithic15 Thanks for the clarity!

To reiterate, can we continue to use our MWS keys from SellerCentral (not tokens) to access MWS after we have self-authorized a SP-API application?

**Comment by krithic15** [comment]
@samamorgan Yes, you can continue to use your MWS Dev Keys to call MWS APIs [irrespective of SP API client usage] until  MWS deprecation for which we do not have an ETA yet.

Best,
Krithi,
Solutions Architect, SP API

**Comment by Tomer781** [comment]
> Hello there,
> 
> You can continue to test and build SP APIs without having your MWS set up affected. The SP API oauth authorization workflow kicks in only after you publish your SP API application in AppStore after which you can use Authorization API to migrate MWS authorizations to SP API platform.
> 
> Best,
> Krithi,
> Solutions Architect, SP API

@krithic15 Is the pre-existing MWS authorization mechanism will still work after publishing the hybrid sp api application? I understand that after the publish I can use the MWS authorizations to migrate to SP API platform, the question is about the MWS authorization mechanism itself.

**Comment by krithic15** [comment]
> > Hello there,
> > You can continue to test and build SP APIs without having your MWS set up affected. The SP API oauth authorization workflow kicks in only after you publish your SP API application in AppStore after which you can use Authorization API to migrate MWS authorizations to SP API platform.
> > Best,
> > Krithi,
> > Solutions Architect, SP API
> 
> @krithic15 @ShivikaK Is the pre-existing MWS authorization mechanism will still work after publishing the hybrid sp api application? I understand that after the publish I can use the MWS authorizations to migrate to SP API platform, the question is about the MWS authorization mechanism itself.

Hello @Tomer781,
Once the hybrid app is published, the authorization flow from AppStore will default to the new oauth authorization flow. If you have an existing MWS auth flow from your website, it will continue to work as it is until you make the switch on your end.

Best,
Krithi,
Solutions Architect, SP API

**Comment by Tomer781** [comment]
Thank you @krithic15 !
you succeeded to calm me down. I have some follow up question.

If I edit my published app and switch only the API type from MWS Application to SP API & MWS Application, should I wait for amazon reviewer approval or is it an immediate switch? If I should wait, for how long?
Another question, if I notice any problem, can I switch it back to MWS application? and if I can, is it immediate or should I wait for reviwe again? and for how long?
