### ISSUE TITLE
Access to requested resource is denied.

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#498]
Hi, I saw many posting about this error, and I also experiencing it. I am stucked ,Is there any update?I can confirm al my credentials are correct

**Comment by ianrussel** [comment]
`*Trying52.18.222.86: 443...*TCP_NODELAYset*Connectedtosellingpartnerapi-eu.amazon.com(*************)port443(#0)*ALPN,
offeringhttp/1.1*successfullysetcertificateverifylocations: *CAfile: /etc/ssl/certs/ca-certificates.crtCApath: /etc/ssl/certs*SSLconnectionusingTLSv1.2/ECDHE-RSA-AES128-*************ALPN,
serveracceptedtousehttp/1.1*Servercertificate: *subject: CN=sellingpartnerapi-eu.amazon.com*startdate: May200: 00: 002020GMT*expiredate: Jun212: 00: 002021GMT*subjectAltName: host"sellingpartnerapi-eu.amazon.com"matchedcert's"sellingpartnerapi-eu.amazon.com"*issuer: C=US;O=Amazon;OU=ServerCA1B;CN=Amazon*SSLcertificateverifyok.>GET/catalog/v0/items/B0002ZFTJA?MarketplaceId=************9HTTP/1.1Host: sellingpartnerapi-eu.amazon.comAccept: application/jsonContent-Type: application/jsonuser-agent: cs-php-sp-api-client/2.1x-amz-access-token: Atza|IwEBIDjrW5XqCWrGWsl_ypVUvkdwq*************************************************Arx-amz-date: 20210313T134132Zx-amz-security-token: ***********//////////******************************************************************************************************************************==Authorization: AWS4-HMAC-SHA256Credential=**********************************20210313/eu-west-1/execute-api/aws4_request,
SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token,
Signature=**********************************************************Markbundleasnotsupportingmultiuse<HTTP/1.1403Forbidden<Date: Sat,
13Mar202113: 41: 34GMT<Content-Type: application/json<Content-Length: 141<Connection: keep-alive<x-amzn-RequestId: *****************************************2<x-amzn-ErrorType: AccessDeniedException<x-amz-apigw-id: cIMaNE0ADoEF76w=<*Connection#0tohostsellingpartnerapi-eu.amazon.comleftintact"[403] Client error: `GET https:\/\/sellingpartnerapi-eu.amazon.com\/catalog\/v0\/items\/B0002ZFTJA?MarketplaceId=A1PA6795UKMFR9` resulted in a `403 Forbidden` response:\n{\n  \"errors\": [\n    {\n      \"message\": \"Access to requested resource is denied.\",\n     \"code\": \"Unauthorized\",\n     \"det (truncated...)\n"`

**Comment by ianrussel** [comment]
Hi @krithic15 , can you take a look in this? I will provide you privately  the credentials I used if you need it. I tried also the sandbox api, still same issue. I need to know what exactly the cause of the problem so I can relay it to my superior who created it in seller central. She's new to seller central and she's only the one who have allowed to have access. I am stuck for almost a week now. 


Regards,

Ian

**Comment by krithic15** [comment]
Hello @ianrussel,

Can you provide me with the App Id so that I can look into the configuration details and get back to you? The role you would need to access Catalog APIs is 'Product Listing'. For more information, please see https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md

Best,
Krithi,
Solutions Architect, SP API

**Comment by ianrussel** [comment]
Hi @krithic15 ,

Thank you for your reply. Here is the app id used 

`amzn1.sp.solution.b780a775-1a03-4ec2-8683-b4b731549b4b`


Regards,

Ian

**Comment by krithic15** [comment]
> Hi @krithic15 ,
> 
> Thank you for your reply. Here is the app id used
> 
> `amzn1.sp.solution.b780a775-1a03-4ec2-8683-b4b731549b4b`
> 
> Regards,
> 
> Ian

Hi Ian, the above app ID does not have the Product Listing role associated with it. Can you please click on 'Edit App' -> choose the Product Listing role and try calling the API again?

Best,
Krithi,
Solutions Architect, SP API

**Comment by ianrussel** [comment]
Hi @krithic15 ,

Thank you for you quick reply. I will relay this to  the person who has access the app. But I think this what we need to do to solve the 403 issue in catalog endpoints. This issue happens also in Orders, Fbainbound, product pricing etc. Do we need to add the  role related to each of the endpoint listed Selling partner api?

Regards,
Ian

**Comment by PrasunaPannati** [comment]
Hi,

I am also getting the same exception. my app id is amzn1.sellerapps.app.8ec066da-cf0c-4ceb-a246-ce42605c3d8f , Can you let me know what is wrong with sp api. This has stopped our migration.

Thanks
