### ISSUE TITLE
Athentication failed (401)

### ISSUE THREAD

**Issue by chesterSF** [amzn/selling-partner-api-docs#499]
HI,

I've been stuck on this error for 3 days and still couldn't figure it out. I went through the instructions 3x carefully. https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#authorizing-selling-partner-api-applications

I'm using https://github.com/saleweaver/python-amazon-sp-api to call Selling Partner API for simplicity. 
I keep getting this error:
sp_api.auth.exceptions.AuthorizationError: ('invalid_client', 'Client authentication failed', 401)

QUESTIONS
1. The keys and secrets I use, do they look right (I obfuscated but kept the format)?
2. I self-authorized the application and got the refresh token from the Seller Central dashboard. The app stayed in Draft state. Is that OK? https://github.com/amzn/selling-partner-api-docs/issues/66

============
import sp_api

marketpalce_id = 'ATVPDKIKX0DER'

app_id = 'amzn1.sp.solution.xxxxx-yyyy-zzzz-...'
refresh_token = 'Axxx....yyyy....'
lwa_client_id = 'amzn1.application-oa2-client.11113332322xxxxx....'
lwa_client_secret = 'a.......'

aws_access_key = 'AKIxxxxxx'
aws_secret_key = '1xxxxxx'
role_arn = 'arn:aws:iam::123....:role/SellingPartnerAPIRole'

credentials = dict(
refresh_token=refresh_token,
lwa_app_id=app_id,
lwa_client_secret=lwa_client_secret,

aws_secret_key=aws_secret_key,
aws_access_key=aws_access_key,
role_arn=role_arn,
)

from sp_api.api import Orders
from datetime import datetime, timedelta, timezone

res = Orders(credentials=credentials).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
print(res.payload) # json data

**Comment by ianrussel** [comment]
Hi, can you try the value of Client-ID ? So 
app_id=Client-ID value //amzn1.application-oa2-client.***************************

**Comment by chesterSF** [comment]
Bingo! That did the trick!
Thank you so much ianrussel.

**Comment by RutvijDave1801** [comment]
Still facing the same issue can you please paste a template of code of appid.Thanks!!

**Comment by Yumelhernandez** [comment]
Hey @chesterSF can you please share what you did to fix it. Some of us are still facing the same issue which is frustrating.

**Comment by bjquinn** [comment]
For anyone still struggling with this, I think the suggestion is that his "lwa_app_id" was wrong.  He used the ID that looked like "amzn1.sp.solution.xxxxx-yyyy-zzzz-...", which you get from the API Integration page in Vendor Central, under the app name.  But what you need is the "Client identifier" from viewing "LWA credentials" on that same page, and this looks like "amzn1.application-oa2-client.zzzzzzzzz".
