### ISSUE TITLE
Vendor and business reports API docs?

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-docs#5]
We are very familiar with the current MWS ecosystem. As such, we were interested in the net additions to the new API referenced in the announcement. 

Specifically, we were looking for information on the vendor and business report API additions. I could not locate any information on these. I'm hoping that this update will support providing the business reports (page views, clicks....) found in the Seller Central UI.

**Comment by edaik** [comment]
Hi there,

We will be posting additional documentation about the Vendor APIs targeting early next week. The current functionality covers Retail Procurement (PO and inbound shipment management) and Vendor Direct Fulfillment (drop ship). We will post an issue/announcement when we add it.

We have currently available an API that provides data on sellers' sales, including the granularity at the buyer type (B2C, B2B), fulfillment type (FBA, MFN), or ASIN/sku. [reference](https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md) 

We do not currently have the full data set available via business reports.

Thanks,
Evan

**Comment by tomhirschfeld** [comment]
@edaik we have a seller central account and are looking to integrate with vendors, but the docs make it seems like you need a vendor central account to integrate with vendors. How can we (using a seller central account) integrate with vendors using the SP API?
