### ISSUE TITLE
Internal Server Error when trying to create a report schedule in the sandbox

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#50]
I'm using the Java SDK, generated with Swagger 2.4.13. I'm able to successfully create new report schedules on the NA production endpoint (`https://sellingpartnerapi-na.amazon.com`), but when I try to do so on the sandbox endpoint (`https://sandbox.sellingpartnerapi-na.amazon.com`) I get a 500 Internal Server Error. Here's the method I'm using to create the report:

```java
public CreateReportScheduleResponse scheduleReport(String reportType) {
	CreateReportScheduleSpecification schedule = new CreateReportScheduleSpecification()
			.marketplaceIds(this.config.getSpapiMarketplaceIds())
			.period(CreateReportScheduleSpecification.PeriodEnum.P1D)
			.reportType(reportType);
	try {
		CreateReportScheduleResponse data = this.api.createReportSchedule(schedule);
		return data;
	} catch (ApiException e) {
		e.printStackTrace();
	}
	return null;
}
```

(I realize that there are references to instance methods/variables in the above code whose definitions I didn't include here, but I don't believe their definitions are relevant to this issue.)

If anyone could shed some light on what's going on here, I would really appreciate it. Thanks!

**Comment by rogersv** [comment]
Did you use the parameters that is defined in x- amazon-spds-sandbox-behaviors? I got the same error yesterday when I used incorrect parameters in the call. I think I got the problem in the endpoint for orders but it might be the same problem for other endpoints.

**Comment by jlevers** [comment]
Yep, that's exactly what the problem was. I hadn't read the seller documentation thoroughly enough...thanks!

**Comment by kingsun-he** [comment]
Actually, How to use createReportSchedule function? After I call this API, Can I download the report by "getReportDocument" Operation or download the report in Amazon Seller Center?
