### ISSUE TITLE
Destination is essential for subscription at Notification API? 

### ISSUE THREAD

**Issue by codingkondi** [amzn/selling-partner-api-docs#501]
why we have to subscribe to SQS or EventBridge via Destination ?
could we add SQS(arn) or EventBridge data while we create subscription for subscripting directly?
in my view, destination is a bridge between SP API(subscription) and AWS Service(SQS or EventBridge) for difference, right?

**Comment by webinsect-rishabh** [comment]
is Notification API worked for you? i am stuck at createDestination(). I am passing the correct parameter but always leaves with 403 error code.

**Comment by codingkondi** [comment]
> is Notification API worked for you? i am stuck at createDestination(). I am passing the correct parameter but always leaves with 403 error code.

u must use grantless token for this API

**Comment by stefnats** [comment]
@DanielLanger im not any official, but I think some things might change in the near future as this Api is fairly new.

**Comment by DanielLanger** [comment]
Makes sense @stefnats. I'm trying to wrap my head around how to properly use the notifications endpoint. We want to collect notifications on behalf of a customer and send them to our backend. So just trying to understand what the workflow/architecture would be
