### ISSUE TITLE
Question to the developer : POST /fba/inbound/v0/plans : createInboundShipmentPlan

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#503]
Hello,
I am using the createInboundShipmentPlan function to know where to send my products, but I wonder why during an error related to a product, you do not send us at the same time the products which do not have a problem ?

**Comment by kingsun-he** [comment]
I think you have to use loop to check the product one by one.

**Comment by johnkw** [comment]
All of the SKUs in the plan are returned by createInboundShipmentPlan when successful. When it fails you need to fix the issues and start over. There's seemingly no bug here - this should be closed.
