### ISSUE TITLE
Parent Seller SKU

### ISSUE THREAD

**Issue by estebanangel** [amzn/selling-partner-api-docs#505]
Hi, I'm trying to retrieve the Parent Seller SKU for any SKU. I found that it's possible to retrieve the Parent ASIN from the Relationships list in the getCatalogItems endpoint, but I haven't been able to find a place that returns the Parent SKU. Someone knows where can I find it?

Thanks

**Comment by johannesharmse** [comment]
We have the same requirement. Would like to know what the expected way is to retrieve this information.

**Comment by Syntaf** [comment]
@estebanangel Is the Parent ASIN an undocumented response key? According to the [docs](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json) there's no specification for a Parent ASIN in the relationships response.

There's a related discussion on the topic here as well: https://github.com/amzn/selling-partner-api-docs/issues/257

**Comment by estebanangel** [comment]
> @estebanangel Is the Parent ASIN an undocumented response key? According to the [docs](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json) there's no specification for a Parent ASIN in the relationships response.
> 
> I'm currently implementing against the spec above and am at a complete loss as to how to deduce relationships from the SP-API
> 
> There's a related discussion on the topic here as well: #257

Using the GET /catalog/v0/items you can get an object with a relationships list containing the parent asin for any item. My question is how to get the Parent SKU instead of the Parent ASIN, I haven't found anything on the docs, but there are applications out there that show the Parent SKU so it should be possible

**Comment by chapmanjw** [comment]
This is not _currently_ possible. The Catalog Item APIs are representative of the Amazon catalog (ASINs) as displayed on the retail websites. It does not cover listings (SKU) data.
