### ISSUE TITLE
Are rate limits for seller-authorized (not self-authorized) applications per-user or per-application?

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#507]
I haven't been able to find clear documentation on the behavior of endpoint rate limits when working with a non-self-authorized application. When a Seller authorizes a my SP API application either via the Marketplace Appstore or the website authorization flow, I (the developer) get a refresh token specific to that Seller's account.

Are API calls made using a specific Seller's refresh/access token limited based on the number of calls made with that Seller's refresh/access token, or based on the total number of calls made by the application as a whole? The former makes much more sense to me than the latter, but I don't see either option documented anywhere.

Thanks!

**Comment by stefnats** [comment]
Nothing official, but i'm pretty sure that limits are per-seller (merchant id / seller id). Per Application wouldn't make sense at all.

**Comment by UoooBarry** [comment]
[Described here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md)

> Will my application be throttled more often as I obtain more authorizations?
> 
> No. All usage plans are specific to application-Selling Partner pairs, so that your throughput grows naturally with your clients.

**Comment by jlevers** [comment]
Thank you -- I must have missed that.

**Comment by bxb100** [comment]
> [Described here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md)
> 
> > Will my application be throttled more often as I obtain more authorizations?
> > No. All usage plans are specific to application-Selling Partner pairs, so that your throughput grows naturally with your clients.

[update link](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md#will-my-application-be-throttled-more-often-as-i-obtain-more-authorizations)
