### ISSUE TITLE
Followed the doc, but we're still getting error: access to requested resource is denied 

### ISSUE THREAD

**Issue by kevinhq** [amzn/selling-partner-api-docs#509]
We follow all the details on the documentation, but we still get the `Access to requested resource is denied `

We have followed all suggestions on previous [closed thread](https://github.com/amzn/selling-partner-api-docs/issues/38), but none work for us.

Then, we tried to open a case with Amazon as suggested there, but Amazon just close our case because they said Amazon had deactivated our seller account.

So, do we need an active Amazon Seller account to access Selling-Partner API? Because we can access MWS API just fine.

If this helps, here's the details we get:

```
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=https://api.amazon.com/auth/o2/token response_code=200 return_code=ok total_time=1.19957
ETHON: performed EASY effective_url=https://sellingpartnerapi-na.amazon.com/authorization/v1/authorizationCode?sellingPartnerId=***&developerId=***&mwsAuthToken=amzn.mws.*** 
response_code=403 return_code=ok total_time=1.309088
AmzSpApi::ApiError: Error message: the server returns an error
HTTP status code: 403
Response headers: {"Date"=>"Wed, 17 Mar 2021 12:28:26 GMT", "Content-Type"=>"application/json", "Content-Length"=>"141", "Connection"=>"keep-alive", "x-amzn-RequestId"=>"4bc870c2-619b-474c-8a95-a0c441209dec", "x-amzn-ErrorType"=>"AccessDeniedException", "x-amz-apigw-id"=>"cVNcoF2moAMFpMQ="}
Response body: {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
````

FYI: We use the [self authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization) when getting the error.

It seems not an authorization problem but a permission with our AWS account (though we had double checked that we follow the documentation as it is)

**Comment by cgaugel** [comment]
Did you solved it @kevinhq ? Having the same problem..

**Comment by kevinhq** [comment]
@cgaugel - Not yet. We're still on progress setting up a new amazon seller account to get in touch with Amz support
