### ISSUE TITLE
MissingAuthenticationToken

### ISSUE THREAD

**Issue by Sorrow91** [amzn/selling-partner-api-docs#51]
Hey together,

I try to get my current orders with the SP-API, but I get this response:

`{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "MissingAuthenticationToken"
        }
    ]
}`

Request:
`GET /orders/v0/orders?MarketplaceIds=A1PA6795UKMFR9 HTTP/1.1
Host: sellingpartnerapi-eu.amazon.com
User-Agent: SellerAPI/1.0 (Language=Java/1.8.0.221; Platform=Windows/10)
Content-Type: application/json; charset=UTF-8
x-amz-access-token: Atza|IwEBIXXXX
x-amz-date: 20201021T101500Z`

I checked my token via `/auth/o2/tokeninfo?access_token`:

`GET /auth/o2/tokeninfo?access_token=Atza|IwEBIXXXX HTTP/1.1
Host: api.amazon.com
User-Agent: SellerAPI/1.0 (Language=Java/1.8.0.221; Platform=Windows/10)
Content-Type: application/json; charset=UTF-8`

and it seems to be valid:

Response:
`{
    "aud": "amzn1.application-oa2-client.cXXXX",
    "iss": "https://www.amazon.com",
    "exp": 741,
    "app_id": "amzn1.application.73b8dXXXX",
    "iat": 1603266055
}`

I double checked the tutorial [https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-create-an-aws-account](url)

Anything I made wrong here?

Kind regards

**Comment by balmca28** [comment]
Same Error For me  "message": "Access to requested resource is denied.",
     "code": "MissingAuthenticationToken"

Please Help me to resolve

**Comment by vikingcodes** [comment]
@Sorrow91 You using REST client or any language ? Share you code

**Comment by Trimakas** [comment]
STRUGGLING with this.. here is my code if anyone happens to come across this:

`
query = {
  sellingPartnerId: "A3K98O0XXX",
  developerId: "75319XXX",
  mwsAuthToken: "amzn.mws.XXXX-XX-66a1-614c-XXX",
  client_id: "amzn1.application-oa2-client.b28a79XXXXXXXXXX",
  client_secret: "a473e762d36XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
send = HTTParty.get("https://sellingpartnerapi-na.amazon.com/authorization/v1/authorizationCode", 
  query: query
)

`
