### ISSUE TITLE
429 QuotaExceeded on createReport call for GET_PRODUCT_EXCHANGE_DATA

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#512]
I'm making calls to the `createReport` endpoint, and most of them are going through as expected. But when I call `createReport` with report type `GET_PRODUCT_EXCHANGE_DATA`, I get a `429 QuotaExceeded` error. I'm pretty confident that this is a bug, because I'm not sure why I'd be permanently rate-limited on one report but able to create other types of reports just fine.

**Comment by rugved1991** [comment]
Hi @jlevers,

Can you please open a support case for further investigation? We would need the complete request and response along with headers which shows the 429 errors. We can troubleshoot the issue in detail on the support case.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by jlevers** [comment]
Just created a case related to this issue: #8181819961

**Comment by jlevers** [comment]
Just to resolve this for anyone with the same problem: I was told that the `GET_PRODUCT_EXCHANGE_DATA` report type was disabled for now (by Amazon), but that change was not reflected in the docs.
