### ISSUE TITLE
Java SDK Generation - Documentation Unclear

### ISSUE THREAD

**Issue by FA5I** [amzn/selling-partner-api-docs#514]
I am playing around with the java library (I know how the auth flow works etc and have made a minimal python SDK that can make calls). However, I want to get familiar with the Amazon Java Client SDK, and I just cannot seem to figure out based on the documentation what to do next.

1. I can successfully build and use the APIAA library detailed [here](package io.swagger.v3.oas.annotations.media does not exist) with my Maven project.
2. Now, I want to access the SellersAPI and all of the classes and methods therein. I manage to successfully generate the models, and place them in a folder called "JavaCL":

<img width="779" alt="Screenshot 2021-03-17 at 19 58 47" src="https://user-images.githubusercontent.com/56031768/111530439-31127900-875b-11eb-929a-595b19f24c77.png">

Within the model folder I have all of the models:

<img width="755" alt="Screenshot 2021-03-17 at 19 59 12" src="https://user-images.githubusercontent.com/56031768/111530491-3f609500-875b-11eb-88cc-e4ab9b2f2f29.png">

My Kotlin code (which is completely interoperable with Java) looks as follows:

```
import com.amazon.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import io.github.cdimascio.dotenv.dotenv
import com.amazon.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider
import com.amazon.SellingPartnerAPIAA.LWAAuthorizationCredentials;

val dotenv = dotenv();
val client_id = dotenv["client_id"]
val client_secret = dotenv["client_secret"]

fun main(args: Array<String>) {
    val awsAuthenticationCredentials = AWSAuthenticationCredentials.builder()
        .accessKeyId(dotenv["access_key_id"])
        .secretKey(dotenv["secret_access_key"])
        .region("us-east-1")
        .build()

    val awsAuthenticationCredentialsProvider = AWSAuthenticationCredentialsProvider.builder()
        .roleArn(dotenv["role_arn"])
        .roleSessionName("sp-api")
        .build()

    val lwaAuthorizationCredentials = LWAAuthorizationCredentials.builder()
        .clientId(dotenv["client_id"])
        .clientSecret(dotenv["client_secret"])
        .refreshToken(dotenv["lwa_refresh_token"])
        .endpoint("https://api.amazon.com/auth/o2/token")
        .build()

    val sellersApi: SellersApi = Builder()
        .awsAuthenticationCredentials(awsAuthenticationCredentials)
        .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
        .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
        .endpoint("https://sellingpartnerapi-na.amazon.com")
        .build()

}
```
As you can see below, in line 29 there is an unresolved reference (the APIAA stuff works fine). I do not understand why this is the case, since I have built the Jar as per the documentation, and also added it to my maven project as a dependency:

```
<dependency>
      <groupId>com.amazon.sellingpartnerapi</groupId>
      <artifactId>sellingpartnerapi-aa-java</artifactId>
      <version>1.0</version>
    </dependency>
```

Error:

<img width="944" alt="Screenshot 2021-03-17 at 20 03 09" src="https://user-images.githubusercontent.com/56031768/111530924-cd3c8000-875b-11eb-9a40-cf492d02df2f.png">

Can someone please help me out in trying to understand this? I would rather just use the Java SDK if it has all the endpoint calls and functions defined as per the open API schema.

**Comment by parvathm** [comment]
Hi @acse-fk4517,

Did you use Mustache templates while generating the Java client library? The Mustache templates that comes with Java AA library might not work with Open API generator. 

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by acse-fk4517** [comment]
Hi @parvathm ,

Yes I generate the SDK with the following flag:

`--template-dir clients/sellingpartner-api-aa-java/resources/swagger-codegen/templates`

Does that mean I need to generate generate a separate Moustache template to get this to work?

The authentication Java AA works with no errors. I assumed this would mean it is working correctly with the Open API generator. To get the AA working I just followed the steps in the docs. However when I try and call the Seller API, the classes are not being picked up.

**Comment by AshokRaja10** [comment]
Hi @parvathm,
I'm facing the exact same issue. I generated the SDK as mentioned in [Generating a Java SDK with LWA token exchange and authentication
](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication).

Then I copied the `swagger-codegen-cli.jar` and `sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar` into the library folder of my project. 

Now with regards to the generated SDK. I tried just copying the SDK folder(Sellers_JavaCL) into my project. Doing so, a lot of errors were displayed in the java files present within the SDK(Sellers_JavaCL). Attaching a few for your reference:

<img width="1038" alt="Screenshot 2021-05-05 at 2 15 22 PM" src="https://user-images.githubusercontent.com/13289422/117117171-dbe30300-adac-11eb-93e2-4508877b80b2.png">
<img width="740" alt="Screenshot 2021-05-05 at 2 16 13 PM" src="https://user-images.githubusercontent.com/13289422/117117202-e4d3d480-adac-11eb-993b-95244bf98fe6.png">
<img width="1082" alt="Screenshot 2021-05-05 at 2 18 10 PM" src="https://user-images.githubusercontent.com/13289422/117117212-e8675b80-adac-11eb-8a90-502760ea1888.png">

I'm clueless about how to incorporate the generated SDK into my Java project(Gradle is used for building the project). I hope this explains my problem. Please let me know if you need any additional information.

Hoping to hear from you soon.

Thanks & Regards,
Ashok
[Zoho Inventory](https://www.zoho.com/in/inventory/)

**Comment by AshokRaja10** [comment]
@FA5I, did you try installing the generated SDK as mentioned in the ReadMe.md file?

Mentioning below the Installation steps found in ReadMe.md present in the generated SDK:

## Installation

To install the API client library to your local Maven repository, simply execute:

```shell
mvn clean install
```

To deploy it to a remote Maven repository instead, configure the settings of the repository and execute:

```shell
mvn clean deploy
```

Refer to the [OSSRH Guide](http://central.sonatype.org/pages/ossrh-guide.html) for more information.

### Maven users

Add this dependency to your project's POM:

```xml
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-java-client</artifactId>
  <version>1.0.0</version>
  <scope>compile</scope>
</dependency>
```

### Gradle users

Add this dependency to your project's build file:

```groovy
compile "io.swagger:swagger-java-client:1.0.0"
```

### Others

At first generate the JAR by executing:

```shell
mvn clean package
```

Then manually install the following JARs:

* `target/swagger-java-client-1.0.0.jar`
* `target/lib/*.jar`

**Comment by FA5I** [comment]
Thanks @AshokRaja10 , I will take a look at this and implement the steps you have outlined!

**Comment by MaximeMarcaisBoxtal** [comment]
Hi!

I generated the Java SDK according to the doc ([https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication](Generating a Java SDK with LWA token exchange and authentication)). But my code doesn't compile when I try to use the SellersApi builder from [https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-an-instance-of-the-sellers-api-and-call-an-operation](Create an instance of the Sellers API and call an operation). Here is my code:

`AWSAuthenticationCredentials awsAuthenticationCredentials = AWSAuthenticationCredentials.builder()
    .accessKeyId("myAccessKeyId")
    .secretKey("mySecretId")
    .region("us-east-1")
    .build();

AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AWSAuthenticationCredentialsProvider.builder()
    .roleArn("myroleARN")
    .roleSessionName("myrolesessioname")
    .build();

LWAAuthorizationCredentials lwaAuthorizationCredentials = LWAAuthorizationCredentials.builder()
    .clientId("myClientId")
    .clientSecret("myClientSecret")
    .refreshToken("Aztr|...")
    .endpoint("https://api.amazon.com/auth/o2/token")
    .build();

SellersApi sellersApi = new SellersApi.Builder()
    .awsAuthenticationCredentials(awsAuthenticationCredentials)
    .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
    .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
    .endpoint("https://sellingpartnerapi-na.amazon.com")
    .build();`

What could I have missed?
Thanks for your help!

**Comment by litao1254** [comment]
The new API has no builder method, no awsauthenticationcredentials, lwaauthorizationcredentials, endpoint, lwaaccesstokencache, and so on

**Comment by davidecampello** [comment]
Same problem to me. It's not clear

**Comment by abdallahaymaan** [comment]
Same issue here, anyone figured out a possible solution?
