### ISSUE TITLE
Unable to continue on publish amaozon app

### ISSUE THREAD

**Issue by UoooBarry** [amzn/selling-partner-api-docs#521]
We are trying to publish the app on the app listing page so that we can use the production workflow(remove `version=beta`).
However, after we filled in the details for `App information`, we were unable to click the `save and continue button`. We have tried using **different browsers**, but the same thing happened.
![image](https://user-images.githubusercontent.com/37783883/111749304-8a4dea00-88cc-11eb-9341-8b0e3a840962.png)
We also opened a support case(id: #8112295971), but apparently, the customer service who reply us doesn't understand what we were asking. 
Can any one check this for me as soon as possible, please?

**Comment by UoooBarry** [comment]
@krithic15 May I have someone from the tech team, have a look at our support case, please?

**Comment by krithic15** [comment]
Hello @UoooBarry,

Apologies for the inconvenience. I have transferred your case to the concerned team and we are taking a look.

Best,
Krithi,
Solutions Architect, SP API

**Comment by iLoveSarabear** [comment]
Hey @krithic15, we're also having **the exact same problem** and no one has responded to our case. Can you take a look?

Case ID #8122623621

Thanks!

**Comment by krithic15** [comment]
> Hey @krithic15, we're also having **the exact same problem** and no one has responded to our case. Can you take a look?
> 
> Case ID #8122623621
> 
> Thanks!

Hello there, 

Can you please update the case with your app ID? I am forwarding your issue to the concerned team as well.

Best,
Krithi,
Solutions Architect, SP API

**Comment by mikhaill** [comment]
@krithic15 I'm running into the exact same issue trying to submit my app. Hoping this gets resolved soon.

**Comment by iLoveSarabear** [comment]
> > Hey @krithic15, we're also having **the exact same problem** and no one has responded to our case. Can you take a look?
> > Case ID #8122623621
> > Thanks!
> 
> Hello there,
> 
> Can you please update the case with your app ID? I am forwarding your issue to the concerned team as well.
> 
> Best,
> Krithi,
> Solutions Architect, SP API

I've updated the case with my app ID. Thanks.

**Comment by UoooBarry** [comment]
> Hello @UoooBarry,
> 
> Apologies for the inconvenience. I have transferred your case to the concerned team and we are taking a look. Can you please provide your app ID?
> 
> Best,
> Krithi,
> Solutions Architect, SP API

Sorry to reply late, my app id is amzn1.sp.solution.e54b980b-c1eb-4a72-974a-5a6db267132c

**Comment by krithic15** [comment]
Hello @UoooBarry and @iLoveSarabear @mikhaill  ,

Can you please click on the drop down under 'Select the language used to provide listing information' and re-select the language? This should fix the issue. We have identified the bug and working on a fix. Apologies for the inconvenience.

Best,
Krithi,
Solutions Architect, SP API

**Comment by mikhaill** [comment]
@krithic15 Thank you the update. I was able to successfully continue the process and submit the app. Looking forward to launching on the new SP API!
