### ISSUE TITLE
Invalidinput error code

### ISSUE THREAD

**Issue by PWAgony** [amzn/selling-partner-api-docs#522]
When calling the '/orders/V0/orders' interface, the first call is normal, and the second call has the NextToken parameter, with "errors":[
{
"message": null,
"code": "InvalidInput"
}
]
Error, what is the reason

**Comment by stefnats** [comment]
Can you post the request and the exact parameters that you're passing?

**Comment by PWAgony** [comment]
> Can you post the request and the exact parameters that you're passing?

![image](https://user-images.githubusercontent.com/11605913/111932652-d5e4db80-8af8-11eb-9d3b-fd8f621caa6b.png)

**Comment by stefnats** [comment]
Could you try to remove the `CreatedAfter`,`MarketplaceIds` and `OrderStatuses` parameter? As far as i know, `NextToken` has to be the only input.

**Comment by rugved1991** [comment]
Hi @PWAgony ,

Can you try encoding the NextToken with Base64 before adding it to the next request?
If the issues still persists, please open up a support case with the complete request and response along with headers for further troubleshooting.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by PWAgony** [comment]
> Hi @PWAgony ,
> 
> Can you try encoding the NextToken with Base64 before adding it to the next request?
> If the issues still persists, please open up a support case with the complete request and response along with headers for further troubleshooting.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API
Still not.
The system returns "message": "We could not decode your NextToken. Possible reasons include: a transmission error, improper quoting or a truncation problem.", I have tried a lot of requests that have not been processed correctly for NextToken. I hope you can tell me the How to deal with NextToken parameters

**Comment by PWAgony** [comment]
> Hi @PWAgony ,
> 
> Can you try encoding the NextToken with Base64 before adding it to the next request?
> If the issues still persists, please open up a support case with the complete request and response along with headers for further troubleshooting.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

Still not.
The system returns "message": "We could not decode your NextToken. Possible reasons include: a transmission error, improper quoting or a truncation problem.", I have tried a lot of requests that have not been processed correctly for NextToken. I hope you can tell me the How to deal with NextToken parameters

**Comment by PWAgony** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/227
Same problem here

**Comment by PWAgony** [comment]
> Could you try to remove the `CreatedAfter`,`MarketplaceIds` and `OrderStatuses` parameter? As far as i know, `NextToken` has to be the only input.

I tried, but I still couldn't.Can you help me determine the parameters of this page turning? What's wrong with my parameter.

**Comment by PWAgony** [comment]
> Hi @PWAgony ,
> 
> Can you try encoding the NextToken with Base64 before adding it to the next request?
> If the issues still persists, please open up a support case with the complete request and response along with headers for further troubleshooting.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

Can you help me determine what I need to pay attention to when using nextToken? Is there an example.

**Comment by stefnats** [comment]
> > Could you try to remove the `CreatedAfter`,`MarketplaceIds` and `OrderStatuses` parameter? As far as i know, `NextToken` has to be the only input.
> 
> I tried, but I still couldn't.Can you help me determine the parameters of this page turning? What's wrong with my parameter.

That seems odd. Is there a way for you to essentially show what was sent in the HTTP Request, like a really verbose log?
Please make sure to just send the only param `NextToken` - should be the same as in the previous request / page.

I can't give you the support as @rugved1991 for example can give you as i can't see the full request details and i don't have that much experience as an actual official Amazon Solutions Architect, so sorry for guessing ;)

**Comment by PWAgony** [comment]
> Hi @PWAgony ,
> 
> Can you try encoding the NextToken with Base64 before adding it to the next request?
> If the issues still persists, please open up a support case with the complete request and response along with headers for further troubleshooting.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

Found the problem. NextToken should be put in the header, not in the parameters as the document says. Please fix it in the document. Thank you

**Comment by PWAgony** [comment]
> > > 你可以尝试删除`CreatedAfter`，`MarketplaceIds`并且`OrderStatuses`参数？据我所知，`NextToken`必须是唯一的输入。
> > 
> > 
> > 我尝试过，但仍然无法完成。您能帮我确定此翻页参数吗？我的参数出了什么问题。
> 
> 好像很奇怪 有没有一种方法可以让您实质上显示HTTP请求中发送的内容，例如真正冗长的日志？
> 请确保只发送唯一的参数`NextToken`-应该与上一个请求/页面中的参数相同。
> 
> 我无法为您提供支持，例如@ rugved1991可以为您提供服务，因为我看不到完整的请求详细信息，而且我没有作为实际的官方Amazon Solutions Architect的丰富经验，非常抱歉；）



> > > Could you try to remove the `CreatedAfter`,`MarketplaceIds` and `OrderStatuses` parameter? As far as i know, `NextToken` has to be the only input.
> > 
> > 
> > I tried, but I still couldn't.Can you help me determine the parameters of this page turning? What's wrong with my parameter.
> 
> That seems odd. Is there a way for you to essentially show what was sent in the HTTP Request, like a really verbose log?
> Please make sure to just send the only param `NextToken` - should be the same as in the previous request / page.
> 
> I can't give you the support as @rugved1991 for example can give you as i can't see the full request details and i don't have that much experience as an actual official Amazon Solutions Architect, so sorry for guessing ;)

Found the problem. NextToken should be put in the header, not in the parameters as the document says. There is something wrong with the document. Thank you

**Comment by PWAgony** [comment]
> > > Could you try to remove the `CreatedAfter`,`MarketplaceIds` and `OrderStatuses` parameter? As far as i know, `NextToken` has to be the only input.
> > 
> > 
> > I tried, but I still couldn't.Can you help me determine the parameters of this page turning? What's wrong with my parameter.
> 
> That seems odd. Is there a way for you to essentially show what was sent in the HTTP Request, like a really verbose log?
> Please make sure to just send the only param `NextToken` - should be the same as in the previous request / page.
> 
> I can't give you the support as @rugved1991 for example can give you as i can't see the full request details and i don't have that much experience as an actual official Amazon Solutions Architect, so sorry for guessing ;)

Found the problem. NextToken should be put in the header, not in the parameters as the document says. There is something wrong with the document. Thank you

**Comment by stefnats** [comment]
@PWAgony this is pretty interesting. congrats on solving this
@rugved1991 can you confirm that `NextToken` should be sent in the header? Isn't this a fundamental flaw in the OpenAPI docs? Are you accepting PRs for that?

**Comment by PWAgony** [comment]
> @PWAgony this is pretty interesting. congrats on solving this
> @rugved1991 can you confirm that `NextToken` should be sent in the header? Isn't this a fundamental flaw in the OpenAPI docs? Are you accepting PRs for that?

I'm sure.

**Comment by fernlop** [comment]
For me it works with NextToken in the QueryParams but not in the header.. 
`/orders/v0/orders/?CreatedAfter=2021-02-01T00:00:00.000Z&CreatedBefore=2021-02-28T00:00:00.000Z&MarketplaceIds=A13V1IB3VIYZZH,A1805IZSGTT6HS,A1F83G8C2ARO7P,A1PA6795UKMFR9,A1RKKUPIHCS9HS,A2NODRKZP88ZB9,APJ6JRA9NG5V4&NextToken=2iqSofqEJZCaJqJYLDm0ZAmQazDrhw3CgJalwszeU.................`

I'm on the EU Servers.
