### ISSUE TITLE
C# GET /orders/v0/orders/***-****-***/address  The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by youcancallmeeverything** [amzn/selling-partner-api-docs#523]
SDK.OrdersV0ApiSDK.Client.ApiException:“Error calling GetOrderAddress: {
  "errors": [
    {
      "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/orders/v0/orders/***-*******-*******/address

accept:application/json
host:sellingpartnerapi-eu.amazon.com
x-amz-access-token:Atza|IwEBIIBHCoImjZPj1wbrjYCj6BPcRghiktlBL30K7DN7p5VYPezTsDw_9OJWu4Glho-CXMCUYcXV2blQZBZaCRYOb3tgKsjzXc-P5fOosHoy0AQ1l6GBlg1yG8Yc0QfcU2mBypM69IoqyBLYD_aGlKOyOCAAkVJZPJq0b29j2OI7DzsC9lkyaaDoMV8GhZPRthnVvvv3B9WDtfJ9qRnna0fhE8PR6BTUKBstssiOjmpTPC11zSFQdOTPF5Q_oBlr0h-trZfP0DNDhn8-pp0dkdoahe3-ctXntAdkPTn6GEKoHEcqfila3nEQI97Ve8WNWxoovzNJqLT3E1Hyim6YNjkduNL7
x-amz-date:20210319T063050Z

accept;host;x-amz-access-token;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20210319T063050Z
20210319/eu-west-1/execute-api/aws4_request
1dbdecdfa39fbb89e096ee6e5654378c08b2faefc71145bbebcfcea24e702862'
",
     "code": "InvalidSignature"
    }
  ]
}”

I use the same signature method and request get orders to return data normally. But when I asked for get order address, Ireturned this error

**Comment by youcancallmeeverything** [comment]
any way  ,I know what's going on

**Comment by youcancallmeeverything** [comment]
any way ,I know what's going on

**Comment by nicole1567** [comment]
what's the reason? I come into the same error

**Comment by youcancallmeeverything** [comment]
sorry ,my  english is not well. 
这是我找到的问题原因以及解决问题的办法




















At 2021-03-25 15:07:56, "nicole1567" ***@***.***> wrote:

what's the reason? I come into the same error

**Comment by wisdomleo** [comment]
same error on GET 'getReport'...

{
  "errors": [
    {
      "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/reports/2021-06-30/reports/51896...

accept:application/json
host:sellingpartnerapi-na.amazon.com
x-amz-access-token:Atza|IwEBIH...sgi
x-amz-date:20211117T065625Z
x-amz-security-token:FwoGZXIvYX...1qo=

accept;host;x-amz-access-token;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20211117T065625Z
20211117/us-east-1/execute-api/aws4_request
ee7c603bda80885d4a8ab9a7bc33414e43366d361d137619f169d4b7df0446c1'
",
     "code": "InvalidSignature"
    }
  ]
}
