### ISSUE TITLE
how to open report document file which is binary?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#524]
Hello,

I am using the ReportsApi::getReportDocument method to get report document details. I download the report with using URL parameter. The downloaded report file is binary.

For the next step, I know, I need to decrypt and uncompress (GZIP) the file. Because the file is binary, I cannot do these operations properly.

Can someone help me on this please?

Thanks.

**Comment by arturll7** [comment]
**SOLVED**.

I **first** **decrypted** file content then, **decompressed** it. After these steps, I reached the report document file content.

**Comment by nicole1567** [comment]
could you offer the codes ? I need a sample, thanks a lot!

**Comment by stefnats** [comment]
What do you mean with Stück on gzip compression? As for our work flow we download the file and then uncompress the downloaded data using the language's functions

**Comment by AshleyBurr** [comment]
@stefnats 

Hi there, sorry I should have updated this post. I was having issues with trying to decompress the response from Amazon (Feed Report Document). But I have worked it out now.
