### ISSUE TITLE
Create shipments - Invalid input

### ISSUE THREAD

**Issue by rusanpas** [amzn/selling-partner-api-docs#526]
I am trying to make a call to Merchanfullfillment - create shipment (POST /mfn/v0/shipments ), but it returns the error
```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}
```
I have tried in the sandbox and the call is successful. You can tell me that it may be wrong ...I think the json is correct.

This is what is being sent without personal data :
```
{
   "ShipmentRequestDetails":{
      "AmazonOrderId":"...",
      "ItemList":[
         {
            "OrderItemId":"3183...459",
            "Quantity":1
         }
      ],
      "ShipFromAddress":{
         "Name":"...",
         "AddressLine1":"..",
         "Email":"...",
         "City":"...",
         "PostalCode":"...",
         "CountryCode":"ES",
         "Phone":"..."
      },
      "PackageDimensions":{
         "Length":17.6,
         "Width":13.7,
         "Height":11.2,
         "Unit":"inches"
      },
      "Weight":{
         "Value":202.1,
         "Unit":"oz"
      },
      "ShippingServiceOptions":{
         "DeliveryExperience":"DeliveryConfirmationWithoutSignature",
         "CarrierWillPickup":false
      }
   },
   "ShippingServiceId":"SEUR_ES_MFN_24",
   "ShippingServiceOfferId":"....."
}
````

Case Id : #6880732102

Thanks

**Comment by rafaurl** [comment]
same problem here, same ShipmentRequestDetails works fine when calling /mfn/v0/eligibleShippingServices 
did you find a solution?

**Comment by rusanpas** [comment]
No, we are waiting response from Amazon.

mfn/v0/eligibleShippingServices is ok
POST /mfn/v0/shipments is not ok

With same request details and a with a valid shipping service id.

**Comment by rusanpas** [comment]
The failure continues, incidence is still open and nobody fixes anything.

**Comment by parvathm** [comment]
Hi @rusanpas,

Sorry of the delay. We are researching the issue, I will provide an update asap.

Thanks,
Parvathm,
Selling Partner Developer API Support.

**Comment by parvathm** [comment]
Hi all,

The code changes to fix the issue with CreateShipment invalid input is deployed.  Please try making the request now and let us know if you are still facing the same issue.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by rusanpas** [comment]
The failure continues... Internal failure message

**Comment by parvathm** [comment]
Hi @rusanpas ,

This looks like a different issue. Can you please provide the latest request id and time stamp for internal error in above mentioned case id 6880732102 for further investigation.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by rusanpas** [comment]
Hi

The error response
```
{
    "errors": [
        {
            "code": "InternalFailure",
            "message": "We encountered an internal error. Please try again.",
            "details": ""
        }
    ]
}
```

Request id :

with CarrierWillPickup: false : 9e662e2c-d1b1-4c96-a1f7-91fa172648e7
with CarrierWillPickup: true : be1833ce-eebe-48d1-b6f2-91a85f718456
with CarrierWillPickup: null : 27455a52-e7ab-4074-bf79-10cb0649a935


Same call, without ShippingServiceId and ShippingServiceOfferId, is ok in eligibleShippingServices...does that help you?

Thanks

**Comment by parvathm** [comment]
Hi @rusanpas,

Can you please use the request parameter as CarrierWillPickUp, looks like your request has wrong case CarrierWillPickup
See https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md#shippingserviceoptions

Please let us know if you still have any questions.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by poeily** [comment]
same problem here, 
did you find a solution?

**Comment by dsimon79** [comment]
Hi,

i have the same problem, but a different message in the error.
Does somebody know what the reason is? and how to solve the issue?
request body (AmazonOrderId, ShipFromAddress, OrderItemId and  ShippingServiceOfferId was modified by me, the request contains real data):
{
  "ShipmentRequestDetails": {
    "AmazonOrderId": "123-1234567-1234567",
    "ShipFromAddress": {
      "Name": "Example-Company GmbH & Co. KG",
      "AddressLine1": "Examplestreet 1",
      "Email": "info@Example-Company.com",
      "City": "Memmingen",
      "StateOrProvinceCode": "",
      "PostalCode": "87700",
      "CountryCode": "DE",
      "Phone": "(0 83 31) 123456"
    },
    "PackageDimensions": {
      "Unit": "centimeters",
      "Length": 18,
      "Width": 12,
      "Height": 8
    },
    "Weight": {
      "Unit": "g",
      "Value": 400
    },
    "ItemList": [
      {
        "OrderItemId": "12345678901234",
        "Quantity": 1
      }
    ],
    "ShippingServiceOptions": {
      "DeliveryExperience": "DeliveryConfirmationWithoutSignature",
      "CarrierWillPickUp": true
    }
  },
  "ShippingServiceId": "DPDDE_PTP_PRIME_DOM",
  "ShippingServiceOfferId": "<removed>"
}

response body:
errors: [
{
code: 'InvalidInput',
message: ' 40fda35b-d253-4cf8-9f2f-84eb6962ee7b',
details: ''
}
]

'x-amzn-requestid': 'b4452408-f46e-4bed-a2fa-c57d45be1e91'
'x-amz-date: 20211216T081158Z\r\n'

**Comment by fruch17** [comment]
> .

Hello, I have the same issue 
mfn/v0/eligibleShippingServices is working fine
POST /mfn/v0/shipments is not work 

Has anyone found the solution? please

**Comment by mtkumar82** [comment]
We are also facing same ierror in Amazon SP API, InvalidInput error, We are using nodejs, typeOrm, MongoDb  for same
our script was working fine few days before but than suddenly it stopped and than we migrated the script to new server and still same issue of Invalid Input, No other log returning in error return by Amazon, Anybody please help us to resolve this issue?

![image](https://github.com/amzn/selling-partner-api-docs/assets/1560517/3ea6a828-585d-44ae-8d2f-61ebdc280337)

**Comment by mianalise** [comment]
Hello @parvathm,
I am facing this issue for /mfn/v0/eligibleShippingServices.
I am getting this error ({ "code": "Unauthorized", "message": "Access to requested resource is denied.", "details": "" })
Can you tell me the solution for it.
I am getting orders with same access token and same settings
