### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by fmaurobica** [amzn/selling-partner-api-docs#528]
Hello everyone,
I don't know if this issue is related to https://github.com/amzn/selling-partner-api-docs/issues/475

This is my problem: I authorized, through Oauth, my app to download the list of orders from my selling profile.
The app id is amzn1.sellerapps.app.e0bd6667-ab60-4747-843c-2d6974cf55c2
I authorized the app for the Europe AWS region.
The request am calling is:
GET https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=APJ6JRA9NG5V4
<Request content is omitted because it contains sensible data>
The response contains this error: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details".

Then the response suggests the canonical string and the string-to-sign that I should use.
I can confirm that these values are exactly the ones suggested, and the signature algorithm is correct (i used the Java version provided on this page https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html).
Thus, the signature i calculate matches the one on this example https://docs.aws.amazon.com/it_it/general/latest/gr/sigv4-calculate-signature.html

Is there any other cause that could lead to this error? I am thinking about some missing permission that I haven't got to my app.

This is an actual request, without sensible data

GET https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=APJ6JRA9NG5V4
Authorization: AWS4-HMAC-SHA256 Credential=<AMAZON_AWS_ACCESS_KEY_ID>/20210323/eu-west-1/execute-api/aws4_request, SignedHeaders=accept;host;x-amz-access-token;x-amz-date, Signature=<Signature>
x-amz-access-token: <ACCESS_TOKEN>
Accept: application/json
x-amz-date: 20210323T160215Z
Host: sellingpartnerapi-eu.amazon.com

**Comment by fmaurobica** [comment]
I managed to reproduce the issue using the aws-java-sdk-signer maven library that Amazon provides.
This is the maven dependency
```xml
<dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-signer</artifactId>
        <version>1.11.927</version>
        <scope>test</scope>
</dependency>
```

This is the code

```java
Request<Void> request = new DefaultRequest<Void>("execute-api");
        request.setHttpMethod(HttpMethodName.GET);
        request.setEndpoint(URI.create("https://sellingpartnerapi-eu.amazon.com"));
        request.setResourcePath("/orders/v0/orders");

        AWSCredentials awsCredentials = new AWSCredentials() {
            @Override
            public String getAWSAccessKeyId() {
                return "<MyAccessKey>";
            }

            @Override
            public String getAWSSecretKey() {
                return "<MySecretKey>";
            }
        };

        AWS4Signer signer = new AWS4Signer();
        signer.setRegionName("eu-west-1");
        signer.setServiceName("execute-api");
        signer.sign(request, awsCredentials);

        HttpResponseHandler<SdkBaseException> httpResponseHandlerError = new HttpResponseHandler<SdkBaseException>() {
            @Override
            public SdkBaseException handle(HttpResponse httpResponse) throws Exception {
                System.err.println(IOUtils.toString(httpResponse.getContent()));
                return null;
            }

            @Override
            public boolean needsConnectionLeftOpen() {
                return false;
            }
        };

        HttpResponseHandler<String> httpResponseHandler = new HttpResponseHandler<String>() {
            @Override
            public String handle(HttpResponse httpResponse) throws Exception {
                System.out.println(IOUtils.toString(httpResponse.getContent()));
                return null;
            }

            @Override
            public boolean needsConnectionLeftOpen() {
                return false;
            }
        };
        Response<String> rsp = new AmazonHttpClient(new ClientConfiguration())
            .requestExecutionBuilder()
            .executionContext(new ExecutionContext(true))
            .request(request)
            .errorResponseHandler(httpResponseHandlerError)
            .execute(httpResponseHandler);
```

**Comment by WildBillKelso** [comment]
I had a similar issue.  Maybe try adding /vendor in your rest request?  Below works for me (North America) c#...

endpoint: "https://sellingpartnerapi-na.amazon.com";
IRestRequest request = new RestRequest("/vendor/orders/v1/purchaseOrders/<MyPoNum>", Method.GET);

**Comment by fmaurobica** [comment]
@WildBillKelso thank you for your comment.
For some reason, Amazon started to accept my signatures after I regenerate the IAM keys.
Hope this helps someone
