### ISSUE TITLE
(Emergency)How to send Carton Content information (dimensions, weights) feed for FBA Inbound shipments？

### ISSUE THREAD

**Issue by shower1986** [amzn/selling-partner-api-docs#529]
Has anyone been successful sending in box content information (dimensions, weights) using MWS for Non amazon-partnered carriers?I am aware we need to send in a feed POST_FBA_INBOUND_CARTON_CONTENTS but this feed has no mentions of dimensions, nor weight.

I tried to create an inbound shipment, and feed(FBA Inbound Shipment Carton Information Feed：_POST_FBA_INBOUND_CARTON_CONTENTS_, XSD is https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CartonContentsRequest.xsd) box content info (including number of boxes and units per box info, does not include box weight and box dimensions info, as i don't see these two fields) through API.When i finish creating this shipment and go back to Amazon Seller Central to check this shipment, i found the “3. Shipment packing” part is automatically checked by “Skip box information and apply manual processing fee”.
But why? as i mentioned i have feed the box content info. Is it that the info i feed through API is not enough?

My question (Case id: 8120069091) has been submitted to the Amazon mws team for more than 7 days, but so far no customer service staff from the Amazon mws team has responded to me with specific solutions.

**Comment by 4379711** [comment]
Did you solve this problem, I ran into the same problem.

**Comment by shower1986** [comment]
no

**Comment by johnkw** [comment]
Did you do 'IntendedBoxContentsSource' 'FEED'?  (See also bug #881 as it would be nice if this whole process was eliminated in favor of a simple API call.)

**Comment by bxb100** [comment]
may be non amazon partner carrier didn't need this info?

**Comment by bxb100** [comment]
Contact with amz supporter, they told me if I don't give this info will charge

**Comment by bxb100** [comment]
#436 somebody said can ignore

**Comment by bxb100** [comment]
@salric

**Comment by wonsky87** [comment]
I used to spend a lot of time looking for answers, and opened a case to consult the MWS team, but I got nothing.

**Comment by shower1986** [comment]
> Did you do 'IntendedBoxContentsSource' 'FEED'? (See also bug #881 as it would be nice if this whole process was eliminated in favor of a simple API call.)

https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md
The FeedType you mentioned is not in this URL.

Where did you see this Feedtype: IntendedBoxContentsSource? Can you share the URL with me?

**Comment by vasRK** [comment]
> > Did you do 'IntendedBoxContentsSource' 'FEED'? (See also bug #881 as it would be nice if this whole process was eliminated in favor of a simple API call.)
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md The FeedType you mentioned is not in this URL.
> 
> Where did you see this Feedtype: IntendedBoxContentsSource? Can you share the URL with me?

check this out

**Comment by HolyZeng** [comment]
Did you solve this problem, I ran into the same problem.

**Comment by azarus** [comment]
the xsd file is an xml schema file you need to generate an xml fille with carton contents according to the schema definitions.
Once filled you have to encrypt the xml document using `aes-256-cbc` algorithm the encryption key and Initialization vector is provided by the previous call and upload it the s3 url provided by the create document api call.
After you uploaded it to s3 call createFeed.

So steps to provide box contents information is basically this:
- createFeedDocument
- generateCartonContentsXML
- Encrypt XML
- Upload to S3
- createFeed

After that you have to put the transport details box weight, and box dimensions.
`putTransportDetails `then `confirmTransport`

**Comment by ericfragola** [comment]
@azarus we followed your steps and were able to get the box contents successfully uploaded 
But run into an Input error when trying PutTransportDetails - oddly it only happens when we select IsPartnered (both SP and LTL) 

Have you ran into the same thing ? 

[message:protected] => [400] Client error: `PUT https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments/FBA16HPLXL59/transport` resulted in a `400 Bad Request` response:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "$inputRoot.message",
      "details": ""
    }
  ] (truncated...)

We have an open case with amazon that's 6 weeks old and they still can't figure it out either

**Comment by azarus** [comment]
> @azarus we followed your steps and were able to get the box contents successfully uploaded But run into an Input error when trying PutTransportDetails - oddly it only happens when we select IsPartnered (both SP and LTL)
> 
> Have you ran into the same thing ?
> 
> [message:protected] => [400] Client error: `PUT https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments/FBA16HPLXL59/transport` resulted in a `400 Bad Request` response: { "errors": [ { "code": "InvalidInput", "message": "$inputRoot.message", "details": "" } ] (truncated...)
> 
> We have an open case with amazon that's 6 weeks old and they still can't figure it out either

Error states `InvalidInput` so you're providing Invalid Input. What is your input?

**Comment by ericfragola** [comment]
> Error states `InvalidInput` so you're providing Invalid Input. What is your input?

[0] => {"IsPartnered":true,"ShipmentType":"LTL","TransportDetails":{"PartneredLtlData":{"Contact":{"Name":"Susan McGregor","Phone":"4151234567","Email":"susan@mcgregor.com"},"BoxCount":"1","SellerFreightClass":"100","FreightReadyDate":"2021-12
-12","PalletList":{"Dimensions":{"Length":"48.0","Width":"40.0","height":"48.0","unit":"inches"},"IsStacked":false},"TotalWeight":{"Value":"200.0","Unit":"pounds"},"SellerDeclaredValue":{"CurrencyCode":"USD","Value":"69.00"}}}}
                            [1] => FBA16H8KY6RJ

I've also attached the full TXT document. 
[putTranferDetails (4).txt](https://github.com/amzn/selling-partner-api-docs/files/7695596/putTranferDetails.4.txt)

anything obvious sticking out? We've tried this before and after using the POST_FBA_INBOUND_CARTON_CONTENTS instructions you put

**Comment by taofeifanIT** [comment]
Did you solve this problem, I ran into the same problem.

**Comment by shower1986** [comment]
> Did you solve this problem, I ran into the same problem.

no!!!

**Comment by wonsky87** [comment]
> > Did you solve this problem, I ran into the same problem.
> 
> no!!!

I have solved this problem！

**Comment by A-BlackMoon** [comment]
> 

how??

**Comment by homebuildersh** [comment]
> > > Did you solve this problem, I ran into the same problem.
> > 
> > 
> > no!!!
> 
> I have solved this problem！

Can you PLEASE explain how you solved this problem? THANK YOU!!
