### ISSUE TITLE
Is there a quick start example for C# class library?

### ISSUE THREAD

**Issue by WXinFfly** [amzn/selling-partner-api-docs#53]
Hello, do you have a quick start example of C# class library?

**Comment by WXinFfly** [comment]
![image](https://user-images.githubusercontent.com/25562509/96819286-cf710b80-1455-11eb-8c10-c20db9e7b19f.png)



`{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "MissingAuthenticationToken"
        }
    ]
}`
The above is my attempt to use postman to request data, and I also gave this error

**Comment by charliecode** [comment]
Hello @WXinFfly . This appears to be a repeat of #38 and #52. I think if you check those two issues out you may find some jewels in regards to assuming the IAM Role via STS and adding the x-amz-security-token to the request (missing from documentation). @rogersv seems to have figured out the fix.

**Comment by israelproscai** [comment]
You need the headers in your request, (Authorization, X-Amz-Date, x-amz-access-token), remember that the requests have to be signed. use class (LWAAuthorizationSigner), check the example. 

(https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp)

**Comment by esalesplatform** [comment]
You need to sign your request with LWAAuthorizationSigner and also with AWSSigV4Signer

**Comment by BeeBee234** [comment]
Good Day,

This C# example code in https://github.com/amzn/selling-partner-api-models/issues/31 works for the following two calls if your credentials are all set up properly:

        var resource = $"/orders/v0/orders";
        IRestRequest restRequest = new RestRequest(resource, Method.GET);
        restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
        restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);

and

    var resource = $"/vendor/orders/v1/purchaseOrders";
    IRestRequest restRequest = new RestRequest(resource, Method.GET);
    restRequest.AddParameter("createdAfter", "2019-08-20", ParameterType.QueryString);
    restRequest.AddParameter("createdBefore", "2019-09-21", ParameterType.QueryString);

FYI, the C# SDK does not seem to be functional at this time (according to many other users as well).

Good luck and have a splendid evening,

Brian

**Comment by WXinFfly** [comment]
> Hello @WXinFfly . This appears to be a repeat of #38 and #52. I think if you check those two issues out you may find some jewels in regards to assuming the IAM Role via STS and adding the x-amz-security-token to the request (missing from documentation). @rogersv seems to have figured out the fix.

Thank you for your reply. I've solved it

**Comment by WXinFfly** [comment]
> You need the headers in your request, (Authorization, X-Amz-Date, x-amz-access-token), remember that the requests have to be signed. use class (LWAAuthorizationSigner), check the example.
> 
> (https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp)

Thank you for your reply. I've solved it

**Comment by WXinFfly** [comment]
> You need to sign your request with LWAAuthorizationSigner and also with AWSSigV4Signer

Thank you for your reply. I've solved it

**Comment by WXinFfly** [comment]
> Good Day,
> 
> This C# example code in [amzn/selling-partner-api-models#31](https://github.com/amzn/selling-partner-api-models/issues/31) works for the following two calls if your credentials are all set up properly:
> 
> ```
>     var resource = $"/orders/v0/orders";
>     IRestRequest restRequest = new RestRequest(resource, Method.GET);
>     restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
>     restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);
> ```
> 
> and
> 
> ```
> var resource = $"/vendor/orders/v1/purchaseOrders";
> IRestRequest restRequest = new RestRequest(resource, Method.GET);
> restRequest.AddParameter("createdAfter", "2019-08-20", ParameterType.QueryString);
> restRequest.AddParameter("createdBefore", "2019-09-21", ParameterType.QueryString);
> ```
> 
> FYI, the C# SDK does not seem to be functional at this time (according to many other users as well).
> 
> Good luck and have a splendid evening,
> 
> Brian

Thank you for your reply. I've solved it

**Comment by parvathm** [comment]
Hi,

Glad to hear that you are able to resolve the issue. Currently we don't have a quick start example of C# class library. If you are having issues with C# sample we need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation. 

Thanks,
parvathm
Selling Partner API Developer Support.

**Comment by abuzuhri** [comment]
Try to Use my library handle most of  requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by abuzuhri** [comment]
> Hello, do you have a quick start example of C# class library?

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by coder771** [comment]
> Hi,
> 
> Glad to hear that you are able to resolve the issue. Currently we don't have a quick start example of C# class library. If you are having issues with C# sample we need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation.
> 
> Thanks, parvathm Selling Partner API Developer Support.

How to add this c# class library in project?

**Comment by abuzuhri** [comment]
Library support nuget
