### ISSUE TITLE
Create Feed "Access to the resource is forbidden"

### ISSUE THREAD

**Issue by lionalex** [amzn/selling-partner-api-docs#530]
I would update a single order with a custom "MerchantOrderID".
So I follow this steps https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md
I create the document correctly and receive this data:
```
{
  payload =>  {
    encryptionDetails"] => {
      standard"] => "AES"
      initializationVector"] => "axxxxxxxxxxxx=="
      key => "/Ipxxxxxxxxxxxxxxxxxxxx="
    }
    feedDocumentId => "amzn1.tortuga.3.91cb6ab6-5142-48d3-8fc3-62ad0db268e9.XXXXXXXXX"
    url => "https://tortuga-prod-eu.s3-eu-west-1.amazonaws.com/%2FNinetyDays/amzn1.tortuga.3.91cb6ab6-5142-48d3-8fc3-62ad0db268e9.XXXXXXXXXX?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210324T112319Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=300&X-Amz-Credential=XXXXXXXXXXXXX%2F20210324%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Signature=axxxxxxxxxxxxxxxxxx"
  }
}
```

I encrypt and upload this XML to url string from previous call:
```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Header>
		<DocumentVersion>1.01</DocumentVersion>
		<MerchantIdentifier>APJ6JRA9NG5V4</MerchantIdentifier>
	</Header>
	<MessageType>OrderAcknowledgement</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<OrderAcknowledgement>
			<AmazonOrderID>171-XXXXXX-XXXXXX</AmazonOrderID>
			<MerchantOrderID>AA00001</MerchantOrderID>
			<StatusCode>Success</StatusCode>
		</OrderAcknowledgement>
	</Message>
</AmazonEnvelope>
```

Perfect. Now I should create the feed to https://sellingpartnerapi-na.amazon.com/feeds/2020-09-04/feeds with this  data
```
array(
  "feedType" => "POST_ORDER_ACKNOWLEDGEMENT_DATA",
  "inputFeedDocumentId" => amzn1.tortuga.3.91cb6ab6-5142-48d3-8fc3-62ad0db268e9.XXXXXXXXX,
  "marketplaceIds" => array(APJ6JRA9NG5V4),
  "feedOptions" => [
    "AmazonOrderID" => 171-XXXXXX-XXXXXX,
    "MerchantOrderID" => AA00001,
    "StatusCode" => "Success"
  ]
);
```

but I receive this error
```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}
```

Why? Where is the error?

**Comment by lockiie** [comment]
Any news about the error? I have this same error

**Comment by rugved1991** [comment]
Hi @lionalex,

The steps you are following are correct. Can you try removing the FeedOptions from the request and try again? FeedOptions is not required and is only applicable for certain feeds. The Order information should be present in the Feed you upload which will be used to process the Order Acknowledgement.

Can you also confirm if your application does have "Order Management" role associated with it? You would need this role to be able to use this Feed Type.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by lionalex** [comment]
I try to exclude FeedOptions from our request, but the errore is the same.
@rugved1991 how can I verify that our application has "Order Management" role? In IAM? Where?

Thanks

**Comment by rugved1991** [comment]
Hi @lionalex,

You can go to your application in seller central and click on "Edit App". You will be able to see all the roles associated with the application. Once you add the role, if not already present, you should reauthorize the seller before trying out the API.
If you are still facing the same issue, you would need to open up a support case with the request and response details for further investigation.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by lionalex** [comment]
In our roles list are only this choises
<img width="758" alt="Schermata 2021-04-06 alle 12 04 03" src="https://user-images.githubusercontent.com/4151825/113695517-39623200-96d1-11eb-9d0c-ada84de7e846.png">

should we have other voices?

**Comment by lionalex** [comment]
We have this options
<img width="686" alt="Schermata 2021-04-06 alle 12 19 37" src="https://user-images.githubusercontent.com/4151825/113696650-8db9e180-96d2-11eb-8b88-c7ce3feebb6a.png">

and have selected all
<img width="739" alt="Schermata 2021-04-06 alle 12 20 46" src="https://user-images.githubusercontent.com/4151825/113696669-93afc280-96d2-11eb-8648-f049e9055ad6.png">

**Comment by rugved1991** [comment]
Hi @lionalex,

Apologies for the confusion. The role name is "Inventory and Order Tracking". I see that you have added that to your application. Can you reauthorize the application and test again?
You should be able to submit the Feed with this new role. If you are still facing issues, please open up a support case and provide me the caseID.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by lionalex** [comment]
We open case id: 6918717042

Thanks

**Comment by lionalex** [comment]
Can you help us?

**Comment by rugved1991** [comment]
Hi @lionalex,

I have escalated the case and requested support team to investigate the issue. Please continue to monitor the case for updates.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by lionalex** [comment]
months have passed but we have'nt solution...amazon case is in stand by

**Comment by fatienza** [comment]
We have the same problem and "Inventory and Order Tracking" is checked.  My IDCase is ID7598995602
Status Code=Forbiden
"message\": \"Access to requested resource is denied.\",\n \"code\": \"Unauthorized\",\n \"details\": \"\"\n }\n ]\n}"

**Comment by albinsopaj** [comment]
> I would update a single order with a custom "MerchantOrderID". So I follow this steps https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md I create the document correctly and receive this data:
> 
> ```
> {
>   payload =>  {
>     encryptionDetails"] => {
>       standard"] => "AES"
>       initializationVector"] => "axxxxxxxxxxxx=="
>       key => "/Ipxxxxxxxxxxxxxxxxxxxx="
>     }
>     feedDocumentId => "amzn1.tortuga.3.91cb6ab6-5142-48d3-8fc3-62ad0db268e9.XXXXXXXXX"
>     url => "https://tortuga-prod-eu.s3-eu-west-1.amazonaws.com/%2FNinetyDays/amzn1.tortuga.3.91cb6ab6-5142-48d3-8fc3-62ad0db268e9.XXXXXXXXXX?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210324T112319Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=300&X-Amz-Credential=XXXXXXXXXXXXX%2F20210324%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Signature=axxxxxxxxxxxxxxxxxx"
>   }
> }
> ```
> 
> I encrypt and upload this XML to url string from previous call:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
> 	<Header>
> 		<DocumentVersion>1.01</DocumentVersion>
> 		<MerchantIdentifier>APJ6JRA9NG5V4</MerchantIdentifier>
> 	</Header>
> 	<MessageType>OrderAcknowledgement</MessageType>
> 	<Message>
> 		<MessageID>1</MessageID>
> 		<OrderAcknowledgement>
> 			<AmazonOrderID>171-XXXXXX-XXXXXX</AmazonOrderID>
> 			<MerchantOrderID>AA00001</MerchantOrderID>
> 			<StatusCode>Success</StatusCode>
> 		</OrderAcknowledgement>
> 	</Message>
> </AmazonEnvelope>
> ```
> 
> Perfect. Now I should create the feed to https://sellingpartnerapi-na.amazon.com/feeds/2020-09-04/feeds with this data
> 
> ```
> array(
>   "feedType" => "POST_ORDER_ACKNOWLEDGEMENT_DATA",
>   "inputFeedDocumentId" => amzn1.tortuga.3.91cb6ab6-5142-48d3-8fc3-62ad0db268e9.XXXXXXXXX,
>   "marketplaceIds" => array(APJ6JRA9NG5V4),
>   "feedOptions" => [
>     "AmazonOrderID" => 171-XXXXXX-XXXXXX,
>     "MerchantOrderID" => AA00001,
>     "StatusCode" => "Success"
>   ]
> );
> ```
> 
> but I receive this error
> 
> ```
> {
>   "errors": [
>     {
>       "code": "Unauthorized",
>       "message": "Access to the resource is forbidden",
>       "details": ""
>     }
>   ]
> }
> ```
> 
> Why? Where is the error?

Hi there. Would you please share with how did you manage to encrypt the file?

Thanks in advance
Kind regards
