### ISSUE TITLE
Is the selling_partner_id obtained during the authorization process unique in the world?

### ISSUE THREAD

**Issue by jason1004** [amzn/selling-partner-api-docs#531]
In the second step of authorization：

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#Step-3-Amazon-sends-you-the-authorization-information

![image](https://user-images.githubusercontent.com/13719529/112308798-814e8580-8cdd-11eb-96b1-9f07e214ed21.png)

**Comment by stefnats** [comment]
Hi @jason1004 
It's the Seller's ID with which you can identify him, something like A784JHJHFDSJ78 (i just made that up but it looks like this).

The Seller ID is unique to every seller. Does this answer your question? If not, could you please specify?

**Comment by rugved1991** [comment]
Hi @jason1004,

selling_partner_id received in the authorization is unique. @stefnats is right about it being Seller ID which is unique throughout the world.

Best,
Rugved
Solutions Architect, SP API

**Comment by xbaha** [comment]
Hello, Is the selling_partner_id unique to every market or to the region (the same  selling_partner_id for the markets in that region)?
hopefully, you can clarify that too.

regards.
