### ISSUE TITLE
MD9999 error when trying to authorize

### ISSUE THREAD

**Issue by prodij** [amzn/selling-partner-api-docs#533]
We have built the application to access Selling Partner API, and the application authorize and work as intended using our own Amazon seller accounts. 

However, when we try to authorize our clients, we get "MD9999" error displayed on Seller Central during our Authorization flow from our website. 
![Capture](https://user-images.githubusercontent.com/7538681/112384587-d671a380-8cab-11eb-875e-972a2fb0e091.JPG)

We've searched for this issue but nothing definitive, and the seller support is not giving us clear answers. 
Can someone please help us to figure out what "MD9999" error means and how to resolve it?

From what we found, some people were suggesting that we have to get our application published on the app store, but it's intended for a private group, so we cannot list there.

Help is appreciated. Thank you.

**Comment by rugved1991** [comment]
Hi @prodij,

Can you please confirm if you are using the OAuth URL with the "version=beta" parameter? If you do not want to publish your application on the Appstore, your app should be in the "Draft" status and should continue using beta parameter in the OAuth URL.
Can you also confirm if you have configured the application with HTTPS Login and Redirect URLs?

**Comment by stefnats** [comment]
Hey there,

i had a similar error. Can you make sure that you're not confusing the application id / client id? They look very similar.

**Comment by prodij** [comment]
Thanks your response!

@rugved1991 Yes, I pass "version=beta", have login and redirect setup.
Here is the link I am using:

https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.xxxxxxxxx-74e7-xxxxx-xxxxx-xxxxxxxxx&state=b255ce1440fb8cc1a836052c27a0eeb8&version=beta

We got it working on our own seller accounts but this MD9999 error occurs when we are trying to Authorize more of our client accounts. We ticketed customer support and got direct MWS team email, but they are not responding...

@stefnats Yes, we use application ID. you can see it in the link above. We got a few accounts working, so I am pretty certain that our code works..... just not on our client accounts.....
Thank you~

**Comment by estebanangel** [comment]
I'm having the same issue, error MD9999. In our case everything is working with the US store but when we try to connect the EU one we get the error after the login. Any ideas on this? a better error message could help

Thanks

**Comment by rugved1991** [comment]
Hi @prodij and @estebanangel,

Can you share the caseID for the support case? I can take a look at the app details and get back to you.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by prodij** [comment]
Hello @rugved1991 !
Thank you for responding... We were stuck at whom to contact to find out...
Our case ID was 8149055981

However, in that case, a support person told me below:
"To resolve this error, please write to our team at "mws-developer-performance@amazon.com". Our team functions independently and will get back to you directly at your registered email address."

I have sent 2 emails and it has been more than a week already and couldn't get a response.

Thank you for your assistance. It's much appreciated~!

**Comment by rugved1991** [comment]
Hi @prodij,

I checked the application configuration and I noticed that you do not have Login and Redirect URLs configured on your application. You are able to authorize your account through self-authorization. But for receiving authorization from the sellers, you will have to complete OAuth flow using the Login and Redirect URLs.
These should be HTTPS URLs. The sp_api_oauth_code will be received in the redirect_url after providing consent. You will have to use this code to exchange for refresh and access tokens. Please refer to [this](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#Step-3-Amazon-sends-you-the-authorization-information) section in developer guide for more information.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by estebanangel** [comment]
> Hi @prodij and @estebanangel,
> 
> Can you share the caseID for the support case? I can take a look at the app details and get back to you.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

Hi @rugved1991, here is our case id related to the problem ID8190891061. Thank you very much for your help

**Comment by prodij** [comment]
Hi @rugved1991 ,

I just checked the in edit app and we DO have the OAuth Login URI and OAuth Redirect URI with HTTPS URLs.
It was there since the beginning of the development and we were able to authorize 3 of our own accounts before it failed on our partner seller accounts. I am sending the screenshot below. Could you please check again?

![image](https://user-images.githubusercontent.com/7538681/113789102-61628d00-96f3-11eb-8485-fb6ce68448ba.png)

**Comment by prodij** [comment]
@rugved1991 We have 3 applications, the one in question has App ID ending in "33cf98375d60"
That application certainly has the URLs you've mentioned. 
Thank you.

**Comment by estebanangel** [comment]
@prodij @rugved1991 the solution in https://github.com/amzn/selling-partner-api-docs/issues/464 worked for us. we had a hybrid app (MWS + SP), but we were just using the SP endpoints so we removed the MWS check in the app config. We retested the authentication and it worked for our client

**Comment by rugved1991** [comment]
Hi @prodij,

Can you please reopen the case "8149055981"? Please let me know when it is reopened and I will escalate the case. If you are unable to reopen it, please open a new case and provide me the caseID.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by GenderAPI** [comment]
Hi @rugved1991 ;

we have the same issue.
our application is just uses SPA not MWS

and our application is live

i open a case with id : 8437800451

**Comment by nirmay** [comment]
Hi @rugved1991 

we have same issue. its already raised as support case (8383884761), but no luck.
We have a hybrid app, that works well for NA region authorizations. We are currently, trying to extend our app to EU region and facing this error.
Could you please look into it? Or suggest what we need to check.

Thanks
