### ISSUE TITLE
SP API Authorization javascript bug

### ISSUE THREAD

**Issue by gtaylor44** [amzn/selling-partner-api-docs#534]
Amazon has a javascript bug when consenting an application.

When the application "OAuth Login URI" is empty, clicking on "Confirm" button does nothing. A console error 'Cannot read property 'endsWith' of undefined' appears.

![amazon bug2](https://user-images.githubusercontent.com/11572604/112405954-31b29d00-8d63-11eb-86bd-7fcfddbe8c6e.jpg)

![amazon bug](https://user-images.githubusercontent.com/11572604/112405950-2eb7ac80-8d63-11eb-8b96-2639a0b28aac.jpg)

**Comment by parvathm** [comment]
Hi @gtaylor44,

Thank you for identifying the issue and providing more details. We were able to confirm the issue . I will update you once the issue is fixed.

Thanks,
Parvathm,
Selling Partner API Developer Support.
