### ISSUE TITLE
GET_REFERRAL_FEE_PREVIEW_REPORT

### ISSUE THREAD

**Issue by webinsect-rishabh** [amzn/selling-partner-api-docs#537]
I want to get REFERRAL_FEE_PREVIEW_REPORT but it always leave me with 403 error .
error details:-
"code": "Unauthorized",
"message": "Access to the resource is forbidden"

Earlier i tried to get GET_FLAT_FILE_OPEN_LISTINGS_DATA and GET_MERCHANT_LISTINGS_DATA reports and that worked for me. But REFERRAL_FEE_PREVIEW_REPORT is not working for me. 

Is there anyone with same issue or some one could help me to get rid of this.
Thanks in advance

**Comment by GeoffTK** [comment]
If you look at the role guide it seems to suggest that specific reports require different roles to create/get.  

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md
What roles does you application use?   

I just ran into a similar issue and requested more roles but won't know if it works until it is approved.

**Comment by webinsect-rishabh** [comment]
@GeoffTK Thanks for reply, I also requested for more role through developer registration which is not approved and i also clicked all the check boxes of roles in edit app option. 

I read the documentation of role earlier but the GET_REFERRAL_FEE_PREVIEW_REPORT is not mentioned under any role there.

**Comment by rugved1991** [comment]
Hi @webinsect-rishabh,

Can you please confirm if your application has access to "Finance and Accounting"? If you do not have this role added, please edit the app and add this role. You would need to reauthorize the application again after adding a new role.
If you are still facing the same issue, please open a support case with complete request and response along with headers for further troubleshooting. 

Best,
Rugved
Solutions Architect, SP API

**Comment by AmericanY** [comment]
@rugved1991 Hello, could you please check if i need to apply any Role here https://github.com/amzn/selling-partner-api-docs/issues/576 as am having same issue.

**Comment by webinsect-rishabh** [comment]
> Hi @webinsect-rishabh,
> 
> Can you please confirm if your application has access to "Finance and Accounting"? If you do not have this role added, please edit the app and add this role. You would need to reauthorize the application again after adding a new role.
> If you are still facing the same issue, please open a support case with complete request and response along with headers for further troubleshooting.
> 
> Best,
> Rugved
> Solutions Architect, SP API

@rugved1991 Thanks for reply. I tried the same, i already had "Finance and Accounting" access for the app. I also reauthorized the app & generated new refresh token and i used that token but issue still the same. Now i will contact to the support team.

**Comment by webinsect-rishabh** [comment]
> Can you please confirm if your application has access to "Finance and Accounting"? If you do not have this role added, please edit the app and add this role. You would need to reauthorize the application again after adding a new role.
> If you are still facing the same issue, please open a support case with complete request and response along with headers for further troubleshooting.
> 
> Best,
> Rugved
> Solutions Architect, SP API

@rugved1991 Thanks for reply, That worked for me. I added "Finance and Accounting" access earlier but did'nt reauthorized the application earlier. But after reauthorizing and generating the new refresh token it worked for me. It not worked instantly but after an hour it worked.
Thanks @rugved1991

**Comment by AmericanY** [comment]
@webinsect-rishabh that's for accessing the order reports API ? also could you please show me how did you add `Finance and Accounting`

**Comment by webinsect-rishabh** [comment]
@AmericanY This worked for me to GET_REFERRAL_FEE_PREVIEW_REPORT. 

To add `Finance and Accounting` -> Go to Develop Apps under "Apps & Services" in Seller Central. Here you can see your App. Then click on "Edit app". After clicking Edit App , you can see a Roles check box. Here you can click on the permission you need and save it. After adding any role you have to reauthorize the app by clicking on authorize button and generate new refresh token.

**Comment by rugved1991** [comment]
Hi @AmericanY,

If you do not see a particular role on your "Edit App" settings, you might not have requested this role in your developer profile. You will need to click on "Your Developer Profile" and request the necessary roles on your account. Once you have been approved to use the roles, you will be able to add them to your applications.
As mentioned by @webinsect-rishabh, you will have to reauthorize your application after you make any changes to your application settings.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by ellis** [comment]
@rugved1991 Many thanks for the helpful instructions - I was able to get the report working by following them.

Ideally, the report would not require the "Finance and Accounting" role.  The same data is available without that role through the productFees API.
