### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by adarmanto** [amzn/selling-partner-api-docs#539]
Hello, 

I am stuck with **Access to the requested resource is denied** error just like others and still no luck when tried to do as suggested from some of the thread e.g 
- [edit the APP access](https://github.com/amzn/selling-partner-api-docs/issues/498#issuecomment-803047953) 
- [using User ARN](https://github.com/amzn/selling-partner-api-docs/issues/487#issuecomment-801945688)

Basically, I have followed based on the doc to register SP-API [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application) without any problem on creating those steps.

Here are the APP ids:
- amzn1.sp.solution.080ef884-0efe-4e31-ad3a-1fdf8f964082 (User ARN)
- amzn1.sellerapps.app.3fa054e0-ef9c-4dc3-94c3-4ba5604c5569 (Role ARN)

Any help would be appreciated!

**Comment by stefnats** [comment]
Hi @adarmanto 
Did you use the User ARN or the Role ARN to register your application?
I had the same error message:
I used the User ARN (mistakenly) and used the STS Result to submit the token in the header of SP API Requests. If you used the User ARN to register your app, you must not use STS and simply omit the header.
If this doesn't help, could you please describe your request to the API a bit more? Like what headers are sent, which endpoint, which parameters, etc. Don't forget to obfuscate crucial parts.

**Comment by adarmanto** [comment]
Hi @stefnats 

Initially, I used Role ARN based on the doc but got that error message, and by checking from [similar issue ](https://github.com/amzn/selling-partner-api-docs/issues/487#issuecomment-801945688) I registered using User ARN to test, but still got the same error.

Here was the request using User ARN:

```
*   Trying 52.20.205.33:443...
* TCP_NODELAY set
* Connected to sellingpartnerapi-na.amazon.com (52.20.205.33) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=sellingpartnerapi-na.amazon.com
*  start date: May  2 00:00:00 2020 GMT
*  expire date: Jun  2 12:00:00 2021 GMT
*  subjectAltName: host "sellingpartnerapi-na.amazon.com" matched cert's "sellingpartnerapi-na.amazon.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /catalog/v0/items/B0788NWKVS?MarketplaceId=ATVPDKIKX0DER HTTP/1.1
Host: sellingpartnerapi-na.amazon.com
Accept: application/json
Content-Type: application/json
user-agent: cs-php-sp-api-client/2.1
x-amz-access-token: Atza|xxx
x-amz-date: 20210326T134325Z
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20210326/us-east-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date, Signature=xxx27ffcdbe65a8b57d9b7c7d37e9106d9f41f76287658fc14fee98518862c9f88e
``` 

FYI, I am using this [library](https://github.com/clousale/amazon-sp-api-php).

**Comment by adarmanto** [comment]
Ah-ha thanks @stefnats you are correct! I need to omit the STS Policy and attach the policy that has been created from [Step 3. Create an IAM policy](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-create-an-iam-policy) into IAM user's permissions directly if using User ARN.

Honestly, using the Role ARN from the doc is a bit complicated, just want to let others if want to use the User ARN instead by the following steps:
- [Step 1. Create an AWS account](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-create-an-aws-account)
- [Step 2. Create an IAM user](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-2-create-an-iam-user)
- [Step 3. Create an IAM policy](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-create-an-iam-policy)
- Step 4. Add the IAM policy to IAM user's permission
- Step 5. Register your application by using User ARN

**Comment by ianrussel** [comment]
@adarmanto did you resolve the issue ? I have similar problem too, but specific to catalog. I have success in other endpoints like /sellers

**Comment by adarmanto** [comment]
Yep @ianrussel, I tested it using `/catalog` endpoint successfully.

You might want to use the User ARN instead of Role ARN when registering your application as my suggested above, and ensure to check the Product Listing access:

![image](https://user-images.githubusercontent.com/26041956/112654183-b562ab80-8e81-11eb-904d-0eef9f9f89ea.png)

**Comment by ianrussel** [comment]
how about the other endpoints ?

**Comment by stefnats** [comment]
> Ah-ha thanks @stefnats you are correct! I need to omit the STS Policy and attach the policy that has been created from [Step 3. Create an IAM policy](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-create-an-iam-policy) into IAM user's permissions directly if using User ARN.
> 
> Honestly, using the Role ARN from the doc is a bit complicated, just want to let others if want to use the User ARN instead by the following steps:
> 
> * [Step 1. Create an AWS account](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-create-an-aws-account)
> * [Step 2. Create an IAM user](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-2-create-an-iam-user)
> * [Step 3. Create an IAM policy](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-create-an-iam-policy)
> * Step 4. Add the IAM policy to IAM user's permission
> * Step 5. Register your application by using User ARN

Glad that you could resolve this. I had this exact same issue originally.

**Comment by Nilanth** [comment]
@adarmanto I face this issue in all end points!

**Comment by tarekrahme** [comment]
Hey @ianrussel 
Trying to get orders too :((
Did you find a solution?
