### ISSUE TITLE
Why was the messaging API description removed?

### ISSUE THREAD

**Issue by dzhlobo** [amzn/selling-partner-api-docs#54]
I see that there was a messaging API and it was removed in https://github.com/amzn/selling-partner-api-docs/commit/6303ba8992d7aa773228e88296e4a4bca5d0df73.

Does it mean you no longer support it? Do you have plans to bring it back?

**Comment by fengmiq** [comment]
massaging-api and uploads-api can't work,return error: Access to requested resource is denied

**Comment by rugved1991** [comment]
The messaging and Uploads API are working as intended. Please let us know if you are running into any issues while implementing these APIs.
