### ISSUE TITLE
403(Access to requested resource is denied) when calling NotificationApi::createDestination

### ISSUE THREAD

**Issue by webinsect-rishabh** [amzn/selling-partner-api-docs#540]
i am working on NotificationApi. createDestination() always returns 403 Access to requested resource is denied. i am passing correct body parameter still can't get rid of this error.

@ShivikaK

**Comment by stefnats** [comment]
Hi @webinsect-rishabh could you please post the complete request?

**Comment by webinsect-rishabh** [comment]
@stefnats thanks for reply, yes i used User ARN to register my app. 

[resource_specification] => Array(
                                                        [sqs] => Array
                                                            (
                                                                [arn] => arn:aws:sqs:eu-west-1:MyAccountID:MyDestinationName
                                                            )
                                                
                                                    )

[name] => MyDestinationName

this is the body parameter i am passing in createDestination(),

Exception when calling NotificationsApi->createDestination: [403] Client error: `POST https://sellingpartnerapi-eu.amazon.com/notifications/v1/destinations` resulted in a `403 Forbidden` response:
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "det (truncated...)

And this is the error i get.

**Comment by webinsect-rishabh** [comment]
Earlier i worked on some reports_api and feeds api and that worked fine for me

**Comment by webinsect-rishabh** [comment]
> Hi @webinsect-rishabh could you please post the complete request and your workflow?
> Did you use User ARN or Role ARN to register your app? Do you use STS and pass the token to the SP API?

i used both User ARN and Role ARN registered Apps and i also used STS

**Comment by stefnats** [comment]
@webinsect-rishabh this seems to be a grantless operation (createDestination) - have you checked resources & guides on that?
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#grantless-operations-1

**Comment by ShivikaK** [comment]
Hello @webinsect-rishabh 

Thank you for raising this issue.

As mentioned above, create Destination is a grantless operation and it will require a grantless access token. 

Please refer to below documentation to request a grantless LWA access token for Notifications API -
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by webinsect-rishabh** [comment]
@ShivikaK & @stefnats Do i need extra permissions to my developer profile from amazon for this ?

**Comment by ShivikaK** [comment]
@webinsect-rishabh 

You do not need additional permissions to make requests for grantless operations but you may need permissions based on the Notification type to actually receive those notifications.

The main difference is the way the request is constructed for the grantless operation and the access token generated for the request.

Hope this helps address your question.

If you are receiving errors for your request for any grantless operation, please verify your access token generation step and if issue persists, please share the request details to investigate the issue further.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by chris-chen23** [comment]
Hi @webinsect-rishabh have you solved the problem yet ? I did everything according to the documentation. but it still returned 403 Access to requested resource is denied. How can I make a successful request createDestination()?
