### ISSUE TITLE
400 Error: Developer xxxxx does not have access to this application

### ISSUE THREAD

**Issue by GeoffTK** [amzn/selling-partner-api-docs#541]
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Developer ID xxxxxxxx is not associated with the application id.",
      "details": ""
    }
  ]
}
```

I receive the above error when attempting to make an API call to the Authorization API.  I have opened a support ticket (8136083331) that has yet to get any traction, so I was hoping maybe someone here could help.

I have the application set up with the IAM ARN pointing to a role.
First, I grab a grantless OAuth token with the `sellingpartnerapi::migration` scope.
I then set the  "x-amz-access-token" to the value of that oauth token.

Then, I assume that role as follows:
```
    val awsCredentialsProvider = STSAssumeRoleSessionCredentialsProvider.Builder(
            "arn:aws:iam::yyyyyyyyyy:role/SellerPartnerApi",
            "Seller-Partner-API-Client"
        )
            .withStsClient(
                AWSSecurityTokenServiceClientBuilder.standard()
                    .withRegion(REGION_NAME)
                    .withCredentials(AWSStaticCredentialsProvider(
                        BasicAWSCredentials(userAccessKey, userSecretKey)
                    )).build()
            )
            .build()
```

And I use that credential provider to sign the request I send.

```
        signer.sign(
            SignableSellerPartnerRequest(clientRequest, requestBodyStream),
            awsCredentialsProvider.credentials
        )
```

The error above seems confusing, as it seems like I am doing the whole flow right.... any ideas?

**Comment by GeoffTK** [comment]
I have seen @ShivikaK come to the rescue for a few others who have posted these issues before.

**Comment by ShivikaK** [comment]
Hello @GeoffTK 

Thank you for raising this issue.

Can you provide us with your application ID information? You can share the details via case as well and I will look into the issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @GeoffTK 

Your case has been updated with details regarding the issue. Please try to make a valid request after an hour or so and let me know on the case if error still persists.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by webinsect-rishabh** [comment]
hi @ShivikaK can you look on to my issue
[https://github.com/amzn/selling-partner-api-docs/issues/540](https://github.com/amzn/selling-partner-api-docs/issues/540)

**Comment by GeoffTK** [comment]
I can make API calls now!  I changed nothing on my end, and from the sounds of it someone over at Amazon flipped some kind of switch or something?  I have requested extra information on the support case in hopes that others who come across this issue may gain extra insight.

**Comment by GeoffTK** [comment]
Here is the extra info:
```
There is an internal flag that needs to be flipped to allow auth migration which means it only impacts Authorization API once the application is published.

But we are now working towards having this step added to our vetting process when an application is submitted to be listed in Appstore. That should help reduce such errors moving forward.

Hope that helps clarify the root cause.
```

So for anyone who is running into this issue in the future when trying to do MWS to SP-API migrations, open up a ticket and they will flip a switch.  It would be super useful to have the docs updated to let people know this needs to be done.

**Comment by ShivikaK** [comment]
Hello @GeoffTK 

As the issue reported here has been resolved, can we close this issue?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by copyboy** [comment]
@ShivikaK hi，I have the same problem, how do I contact you, I opened a case in the sellercentral but no one responded, my question ID 8190927951
