### ISSUE TITLE
Unauthorized & Access to requested resource is denied with no details. Is this due to Role settings?

### ISSUE THREAD

**Issue by rashearth** [amzn/selling-partner-api-docs#542]
Hi , I am using the selling partner-api to get the catalog information for each ASIN.

Here, i have done all the works written in this document, but still having these issues.
Please kindly let us know what is this cause, i have being working for 2 weeks finding the solution for this...

◆Problem:
All the work is done, but fetching the below content will output with errror.

Fetch content↓
'https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments/shipmentId1/preorder/confirm?MarketplaceId=ATVPDKIKX0DER&NeedByDate=2020-10-10'

Output↓
`
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
`

I have set all the permissiion guidelines, signatures done perfectly.

◆Hypothesis:
As i have checked through many of the similar issues in github, i think that somehow the application settings in the amazon seller central have ony 3 roles, and dont have any roles checking for catalog information. What did i do wrong? i also added Marketplace policy to the ARN user role, but nothing changed.

<img width="704" alt="スクリーンショット 2021-03-27 12 19 54" src="https://user-images.githubusercontent.com/26535295/112708701-f052f680-8ef6-11eb-9fe1-4d442628e274.png">
<img width="1035" alt="スクリーンショット 2021-03-27 12 19 37" src="https://user-images.githubusercontent.com/26535295/112708705-f3e67d80-8ef6-11eb-94c2-d102725715c4.png">

**Comment by Mitalee** [comment]
Had the same issue and the amazon team was gracious to help me out. 
1. Check that the IAM ARN in the draft app has the user ARN (instead of the role ARN).
2. In the IAM console, these steps are crucial - https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-create-an-iam-policy. The policy should be SellingPartnerAPI (You can create it as per the instructions or simply add it to the user from the list of policies.

Worked like a charm post these changes.

**Comment by stefnats** [comment]
@Mitalee and additionally, it has to be attached as a manged policy. That solved it for me.

**Comment by rashearth** [comment]
@Mitalee ,@stefnats

Thank you very much for the support,
But still having the same issues even I had re-tried the below progress with your comments worked.
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application

Output↓
`
{ "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }
`

I was wondering, is these permission the right one to fetch the marketplace
I also used this endpont too, but still same output
https://sellingpartnerapi-na.amazon.com/catalog/v0/categories?MarketplaceId=ATVPDKIKX0DER
Im totally confused on this error...

<img width="637" alt="スクリーンショット 2021-03-31 23 49 47" src="https://user-images.githubusercontent.com/26535295/113164118-c9d8e680-927b-11eb-9ea8-f4d27159729b.png">

**Comment by Mitalee** [comment]
Isn't catalogue part of Product Listing? Just assign all the roles to the draft app and try it out?

**Comment by rashearth** [comment]
Ya, actually i assinged all the 3 roles that is written, but have the similar error .

**Comment by stefnats** [comment]
Could you please post the details of your requests including all sent headers & params as well as the complete HTTP Result?

**Comment by diegocvazquez** [comment]
Hi there, I am strugling with this issue too.
Must be the application be approved by amazon before starting to use it?. 


I am able to get the tockens, but I cannot make any call, I am allways getting 
**{ "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }**

I have used the Rol ARN in one appliation and the user ARN in the second appliction to test but without results.

![image](https://user-images.githubusercontent.com/11884049/114024464-5f740780-9874-11eb-913b-3b552abdfd24.png)

Any help will be much appreciated!
rergards,
Diego
