### ISSUE TITLE
Method to get all categories in a marketplace?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#544]
Hello,

Does anyone know the method to get all categories in a marketplace with marketplace_id?

Thanks

**Comment by fernlop** [comment]
You have to use the Browse-Tree Report:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#browse-tree-report

**Comment by arturll7** [comment]
thank you @fernlop

**Comment by ouroboros25** [comment]
@fernlop  @arturll7  Can you show a request example how to get all categories in a marketplace with marketplace_id?
