### ISSUE TITLE
Error Code: MD9000 This Developer is not currently eligible for new authorizations

### ISSUE THREAD

**Issue by og77077** [amzn/selling-partner-api-docs#545]
I have submitted my app a couple of months ago and still haven't heard back from Amazon and as this process was new to me I didn't test the app in the draft state rather just submitted it for approval and they haven't replied to me with any updates even after months. 

Something went wrong
This Developer is not currently eligible for new authorizations.
App ID: amzn1.sellerapps.app.21aed38e-a640-4575-898e-00000000
Error Code: MD9000

I am getting the error MD9000 (with &version=beta) and MD1000 (without &version=beta). I have already submitted the app and cannot change the redirect URI. The status of my app is "Submitted". Can you please help me?

**Comment by og77077** [comment]
Hello? Anybody from the Amazon development team here? @ShivikaK

**Comment by ShivikaK** [comment]
Hello @og77077 

Thank you for raising this issue.

Can you share the correct App ID as this does not seem to be correct? I would encourage you to open a support case with us to further troubleshoot the issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by og77077** [comment]
@ShivikaK the App ID is amzn1.sellerapps.app.7e176a9b-1abe-43ff-919d-c9a7d45b7e9c

**Comment by og77077** [comment]
@ShivikaK I appreciate your response. Can you please help me?

**Comment by ShivikaK** [comment]
Hello @og77077 

The application submission has been cancelled so your app should be back in Draft stage.

You should be able to edit your app to modify redirect URI. Please let me know if you have any further concerns.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by og77077** [comment]
Thank you! @ShivikaK 
It would be awesome if you can record a loom video on how to set up our app is this page - https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md is very confusing.

**Comment by ShivikaK** [comment]
Hello @og77077 

Thank you for the suggestion, I will look into the possibility of providing a video recording for app registration process. 

In the meanwhile, if you have any further questions, I will be happy to address those for you.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by og77077** [comment]
Hello @ShivikaK 

I was able to test the app in the draft status and it is working. Can you please approve the app? I've already submitted it. The App ID is amzn1.sellerapps.app.7e176a9b-1abe-43ff-919d-c9a7d45b7e9c

Thank you so much, because of you I was able to test it.

**Comment by og77077** [comment]
@ShivikaK,

I accidentally submitted it with the incorrect OAuth URI - https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.7e176a9b-1abe-43ff-919d-c9a7d45b7e9c&version=beta

and I would like to change it to https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.7e176a9b-1abe-43ff-919d-c9a7d45b7e9c

Can you please update it? Thank you!

**Comment by og77077** [comment]
@evdeg @DKasto @seanevan @weitzhandler @manassolanki @parvathm @signontwodotoh @rickdeee @salric @jenilew 
Is anybody able to help me? We've been facing this problem for months now.

**Comment by ShivikaK** [comment]
Hello @og77077 

Your application submission has been cancelled and you should be able to see your app in Draft stage.

Additionally, we do not recommend using OAuth URI as the Login URL information in the application's OAuth section.

Login URI as name suggests is used to login into Developers website. So this should majorly be the developer website's login page URL

I will also recommend testing your Authorization workflow to verify that it is working as expected using the OAuth authorization URI prior to submitting the app to be published in the appstore. 

Please let me know if you still face any issues.

Thanks,
Shivika Khare
Selling Partner API Developer Support
