### ISSUE TITLE
Response Code 403, message='Forbidden' on every API call

### ISSUE THREAD

**Issue by vibhat** [amzn/selling-partner-api-docs#546]
I have been trying to use Amazon SP-API recently but I am getting 'Forbidden' message when trying to test APIs. Below example is from ProductPricingAPI.
I followed all the steps on Amazon Selling API Developer Guide, and successfully went through all of them. I also created an app under Seller Central > Apps & Services > Develop Apps. But I am still getting this error for the api call for java client:

Response{protocol=http/1.1, code=403, message=Forbidden, url=https://sellingpartnerapi-na.amazon.com/products/pricing/v0/price?MarketplaceId=ATVPDKIKX0DER&ItemType=Asin&Asins=9781338245752}
with following header - 
x-amzn-RequestId: c03ba865-0c46-474b-8cce-8e4eb2151e10
x-amzn-ErrorType: AccessDeniedException

Any help would be greatly appreciated in understanding the underlying problem.

**Comment by fernlop** [comment]
Please leave us your full request including all headers, otherwise I just can guess

**Comment by vibhat** [comment]
Hi @fernlop Below are my request and request header details as taken from the ApiClient.java - 

Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/products/pricing/v0/price?MarketplaceId=ATVPDKIKX0DER&ItemType=Asin&Asins=9781338245752, tag=Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/products/pricing/v0/price?MarketplaceId=ATVPDKIKX0DER&ItemType=Asin&Asins=9781338245752, tag=null}}

Request Headers - Accept: application/json
Content-Type: application/json
User-Agent: Swagger-Codegen/1.0.0/java
x-amz-access-token: Atza|IwEBIHTcehlWF65pPeKHze3*******
X-Amz-Security-Token: FwoGZXIvYXdzEEQaDCHn/Oq6C5B********
Host: sellingpartnerapi-na.amazon.com
X-Amz-Date: 20210330T180601Z
Authorization: AWS4-HMAC-SHA256 Credential=ASIA4*****/20210330/us-east-1/execute-api/aws4_request, SignedHeaders=accept;content-type;host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=84c410d9e1c*******

Let me know if this helps understand the issue.

**Comment by stefnats** [comment]
Some thoughts on that:

Headers like `X-Amz-Date` is not fully lower case. Please check if lower case your headers works
- access token looks like the refresh token?
- those are not ASINs, an ASIN is 10 alphanumeric characters

I'm currently on mobile, so I can't link. Please look into the developer guide on how to make calls. I hope this helps.

**Comment by vibhat** [comment]
Hi @stefnats Thanks for your response!
For X-Amz-Date, I am not explicitly setting anything, it seems to be added from APIClient and so am not sure if we can change it.
I am currently setting awsAuthenticationCredentials, lwaAuthorizationCredentials and awsAuthenticationCredentialsProvider to build the respective API object.

Regarding ASIN, I have also tried other APIs like CatalogApi -> listCatalogItems which takes ISBN as the parameter and am still getting the same response -
Response{protocol=http/1.1, code=403, message=Forbidden, url=https://sellingpartnerapi-na.amazon.com/catalog/v0/items?MarketplaceId=ATVPDKIKX0DER&ISBN=9781338245752}

**Comment by stefnats** [comment]
@vibhat thanks for the insights! Could you share how you set up the credentials and which values you have from what source? Are you using your User ARN for your app or the Role ARN?
If user: is the policy attached to it?

**Comment by vibhat** [comment]
@stefnats I have set up the authentication credentials following all the steps mentioned at - https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md
For awsAuthenticationCredentials, I am using AWS access key id and secret from IAM user step.
For lwaAuthorizationCredentials , using lwa client Id, client secret and refresh token.
For awsAuthenticationCredentialsProvider , using role ARN. I have also created and attached the policy for the user as mentioned in the guide.

**Comment by rugved1991** [comment]
Hi @vibhat,

Can you please confirm if you have configured an IAM Role or IAM User ARN on your application in Seller Central?
If you are using an IAM User ARN, you would need to add the IAM Policy to the IAM User directly.
If you are using IAM Role ARN, you would need to get temporary credentials for that IAM Role and then calculate the AWS SigV4 signature.
If you are still seeing the same issue, feel free to add more details.

Best,
Rugved
Solutions Architect, SP API

**Comment by vibhat** [comment]
@rugved1991 I have configured IAM user ARN on the application in seller central and have attached a policy (with inline policy type) to the same.
Please do let me know if any changes required in same.
Thanks,
Vibha

**Comment by rugved1991** [comment]
Hi @vibhat,

Thanks for confirming. Have you added the Execute API policy to the IAM User or STS Policy?
You should be adding [this policy](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-create-an-iam-policy) directly to the IAM User if you are configuring an IAM User on the app.

Best,
Rugved
Solutions Architect, SP API

**Comment by vibhat** [comment]
Hi @rugved1991 

Thanks for the response. I checked the configurations and have added a STS policy to the IAM user as mentioned in this link - https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-5-add-an-aws-security-token-service-policy-to-your-iam-user

I have created the managed policy for execute-api as well and is showing as an attached policy for the role ARN as mentioned at https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-an-iam-role

Do I need to attach the managed policy to the user ARN ?

**Comment by rugved1991** [comment]
Hi @vibhat,

Yes you need to attach the managed policy directly to the IAM User. Please refer to the "Important" note in [Step 6. Register your application](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-6-register-your-application) for more information.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by rogersv** [comment]
Hi @vibhat ,
It sounds like you mixed up the different approaches. You either choose to use the role ARN for your application OR the user ARN. 

For User ARN: 
* The user must have the permission for the execute-api. The documentation you refer to explains how to set it for a role not a user.
* skip the x-amz-security-token if you use this approach.

For role ARN:
* Make sure the application is registered with the role and not the user.
* assume the role to get a new key, secret and token. Use these values in the calls. So not use the original key, secret that was used for the user.

**Comment by vibhat** [comment]
Hi @rugved1991 @rogersv 
Thanks for clarifying the details of both the approaches.
I have updated the application in seller central and registered it with the IAM role and am now able to get a successful response when trying the catalogAPI.
Thanks a lot for your help in resolving the issue.
