### ISSUE TITLE
400 Bad Request when using NextToken on listFinancialEventsByOrderId

### ISSUE THREAD

**Issue by fernlop** [amzn/selling-partner-api-docs#547]
I'm trying to get the next page of financial events on the listFinancialEventsByOrderId _(path: /finances/v0/orders/{orderId}/financialEvents )_ method, but I receive a bad request error. 

What i try:

GET Request on:
`https://sellingpartnerapi-eu.amazon.com/finances/v0/financialEventGroups/{MyEventGroupId}/financialEvents?NextToken={NextToken}`

Response:
Data is empty, Code 400, Bad Request

When i try with a Token that is invalid (ANY String) i receive the following:
```
StatusCode: 200
data: { payload: {} }
```

Only with the **correct** NextToken i get the _Bad Request_ error.

This results in 2 problems:

- Can't get next page with NextToken
- No error message when using an invalid token, instead return empty payload

Can someone access the listFinancialEventsByOrderId with NextToken successfully? I would appreciate the feedback.

**Comment by stefnats** [comment]
Hey @fernlop i didn't try that, but it seems relative to issue #522 
It basically says that `NextToken` should be sent as header. Can you try that?

**Comment by fernlop** [comment]
@stefnats No doesn't work, if I put the NextToken only in the header it continues to give me the first page of results.

**Comment by fernlop** [comment]
UPDATE: 
NextToken doesn't work with **listFinancialEvents** eighter. 

ALSO INTERESTING:
When using the getOrders method, I can use the NextToken in the QueryParams and it works. Other users like in #522 can't use it. I'm on the EU servers, maybe there is some difference? 
For me it works with NextToken in the QueryParams but not in the header..
`/orders/v0/orders/?CreatedAfter=2021-02-01T00:00:00.000Z&CreatedBefore=2021-02-28T00:00:00.000Z&MarketplaceIds=A13V1IB3VIYZZH,A1805IZSGTT6HS,A1F83G8C2ARO7P,A1PA6795UKMFR9,A1RKKUPIHCS9HS,A2NODRKZP88ZB9,APJ6JRA9NG5V4&NextToken=2iqSofqEJZCaJqJYLDm0ZAmQazDrhw3CgJalwszeU.................`

**Comment by stefnats** [comment]
Hm that's interesting. Just out of curiosity, which library are you using for making that call?

**Comment by fernlop** [comment]
@stefnats I built my own SDK for NodeJS, requests look like this when using it:
```
const events = await amzSDK.request({
  region: "eu",
  type: "listFinancialEvents",
  queryParams: {
      PostedAfter: (new Date(fromDate)).toISOString(),
      PostedBefore: (new Date(toDate)).toISOString() 
  },
  accessToken: mwsAccountConfig.accessToken,
  iamUserAuth: auth,  
  bottleneckConfig: {
      ...auth.redisAuth
}
```
The SDK is currently private but I'm open for contributors :)

**Comment by cgaugel** [comment]
Same problem here. It was working some Weeks ago, now I am stuck here as well.. @parvathm fix this!

**Comment by fernlop** [comment]
@stefnats yes it gets URL encoded and it's already Base64 encoded. 
@cgaugel Did you open a case for this already? It's their basic excuse if they can't fix it quickly.

**Comment by fernlop** [comment]
@parvathm No I didn't create a ticket for this problem yet. Would this help organize the issues for you? 
Could you provide use a time window for this issue, maybe you already assigned it to a sprint :)

**Comment by parvathm** [comment]
Hi @fernlop,

Yes, if open a case and provide us request id, time stamp and any relevant data for which you are receiving error it helps us to identify the issue quickly and come up with ETA.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by cgaugel** [comment]
Still not fixed.

**Comment by ShivikaK** [comment]
Hello,

The code changes for this issue have been deployed. Can you please try making the request with NextToken and let us know if the issue is resolved?

Thanks,
Shivika Khare,
Selling Partner API Developer Support.
