### ISSUE TITLE
[BUG] CreateFeedAPI: Who can tell me what went wrong? 

### ISSUE THREAD

**Issue by joseacevedo-slab** [amzn/selling-partner-api-docs#548]
Here is my product information.
```
<?xml version="1.0" encoding="iso-8859-1"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>***</MerchantIdentifier>
    </Header>
    <MessageType>Product</MessageType>
    <PurgeAndReplace>false</PurgeAndReplace>
    <Message>
        <MessageID>1</MessageID>
        <OperationType>Update</OperationType>
        <Product>
            <SKU>JK20210330</SKU>
            <StandardProductID>
                <Type>UPC</Type>
                <Value>***</Value>
            </StandardProductID>
            <DescriptionData>
                <Title>Men's Glennaker Lake Rain Jacket</Title>
                <Brand>Columbia</Brand>
                <Description>Ua Pronto puffer jacket UA storm technology</Description>
                <BulletPoint>Imported</BulletPoint>
                <BulletPoint>Under armor storm technology repels water without sacrificing breathability</BulletPoint>
                <MSRP currency="GBP">500</MSRP>
                <Manufacturer>Columbia</Manufacturer>                
                <ItemType>COAT</ItemType>
            </DescriptionData>
            <ProductData>
                <Clothing>
                    <ClassificationData>
                        <ClothingType>Blazer</ClothingType>
                        <Department>boys</Department>
                        <TargetGender>male</TargetGender>
                    </ClassificationData>
                    <AgeRangeDescription>Adult</AgeRangeDescription>
                    <ApparelBodyType>big</ApparelBodyType>
                    <ApparelHeightType>tall</ApparelHeightType>
                    <ApparelSize>numeric_47</ApparelSize>
                    <ApparelSizeClass>numeric</ApparelSizeClass>
                    <ApparelSizeSystem>as8</ApparelSizeSystem>
                    <ApparelSizeTo>numeric_49</ApparelSizeTo>
                </Clothing>
            </ProductData>
        </Product>
    </Message>
</AmazonEnvelope>
```

This is the result of the submission:

**`The data you provided for [JK-2021-03-30] does not match the list of valid values.  Please select a valid value from the Data Definitions and resubmit.`**

**Comment by fernlop** [comment]
To which marketplace did you want to upload it?

**Comment by stefnats** [comment]
@amz maybe you could throw a more specific error here in the future. Just a suggestion :)

**Comment by joseacevedo-slab** [comment]
> To which marketplace did you want to upload it?

Hi, this is the marketplace id I'm using

A1F83G8C2ARO7P

**Comment by joseacevedo-slab** [comment]
> @amzn maybe you could throw a more specific error here in the future. Just a suggestion :) 

hi, thanks for the suggestion, i'm trying to be as specific as possible with the error i am getting, unfortunately the error does not describe exactly what may be happening, only the text i showed in the beginning appears :(

**Comment by stefnats** [comment]
@joseacevedo-slab oh no that was not directed to you. I just suggested Amazon SP API Team that they could look into throwing more specific errors. Sorry for the confusion!

**Comment by fernlop** [comment]
I have validated your XML against the Amazon schema and it should be correct for UK. 
The only thing I found is that `<MSRP currency="GBP">500</MSRP>` is the value without tax, maybe you have to add the `MSRPWithTax` too?
For your reference, you can find the schema here and check for mistakes:
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductClothing.xsd

**Comment by joseacevedo-slab** [comment]
> I have validated your XML against the Amazon schema and it should be correct for UK.
> The only thing I found is that `<MSRP currency="GBP">500</MSRP>` is the value without tax, maybe you have to add the `MSRPWithTax` too?
> For your reference, you can find the schema here and check for mistakes:
> https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd
> https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductClothing.xsd

I did the test by putting the MSRPWithTax and it keeps generating the error, I have already tried everything and it still does not work :/

**Comment by MST1122** [comment]
@joseacevedo-slab, where can I contact you? I need some help related to XML generation for product listing.
