### ISSUE TITLE
no orderTotal and itemPrice value in ordersV0Api.getOrder and ordersV0Api.getOrderItems

### ISSUE THREAD

**Issue by holly3k** [amzn/selling-partner-api-docs#554]
using self auth application to retrieve data, noticed orderTotal is empty in ordersV0Api.getOrder and itemPrice value is empty in ordersV0Api.getOrderItems

**Comment by stefnats** [comment]
Hey there,

that's unusual. Which library for making the calls are you using?
Do you have the chance on debugging the resulting JSON Object? I suspect that maybe the object returned might not be parsed 100% correct.

**Comment by fernlop** [comment]
Did you test this with multiple orders? I know there are some type of orders that indeed have an empty amount. For example Vine orders or MFN orders. Are you able to get all PII data for this order, like name and address?
Could you also confirm that you have all the necessary roles available in your developer profile? _( [YOUR_AMZ_REGION_URL]/developer/register )_

**Comment by gopkg-dev** [comment]
Hey there,

order status Pending orderTotal is empty.

**Comment by holly3k** [comment]
> 
> 
> Hey there,
> 
> order status Pending orderTotal is empty.
> this is normal.

all order status in SHIPPED, order type: AFN

**Comment by holly3k** [comment]
> 
> 
> Hey there,
> 
> that's unusual. Which library for making the calls are you using?
> Do you have the chance on debugging the resulting JSON Object? I suspect that maybe the object returned might not be parsed 100% correct.

java lib from the developer guide, generated code by swagger, no self-writing code in it

**Comment by holly3k** [comment]
> 
> 
> Hey there,
> 
> that's unusual. Which library for making the calls are you using?
> Do you have the chance on debugging the resulting JSON Object? I suspect that maybe the object returned might not be parsed 100% correct.

noticed that data return by postman has detail orderTotal but missing in JAVA client, i guess you are right, json client didn't parse it correctly
