### ISSUE TITLE
createFeedDocument Error, InvalidInput-contentType

### ISSUE THREAD

**Issue by cagataysayg** [amzn/selling-partner-api-docs#559]
Hi, when I tried to make a createFeedDocument call like that it response the error below.

{
  path: '/feeds/2020-09-04/documents',
  method: 'POST',
  host: 'sellingpartnerapi-fe.amazon.com',
  region: 'us-west-2',
  service: 'execute-api',
  headers: {
    'content-Type': 'text/tab-separated-values; charset=UTF-8',
    'User-Agent': 'MyAmazonApp/1.0 (Language=JavaScript;)',
    'x-amz-access-token': 'Atz**********************************************************************************************892********************************s',
    Host: 'sellingpartnerapi-fe.amazon.com',
    'X-Amz-Security-Token': '********************************G********************************+********************************',
    'X-Amz-Date': '20210404T142946Z',
    Authorization: 'AWS4-HMAC-SHA256 Credential=A********************************T, SignedHeaders=content-type;host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=********************************'
  }
}

And the response is:

"errors": [
                {
                    "code": "InvalidInput",
                    "message": "One or more required parameters missing",
                    "details": "contentType;"
                }
            ]

But when I send my request with that body: '{"contentType":"text/tab-separated-values; charset=UTF-8"}'
I never get response.

**Comment by moslemparve** [comment]
send this in body of request not in header
``{``
	``"contentType":"text/tab-separated-values; charset=UTF-8"``
``}``

**Comment by stefnats** [comment]
Hi @cagataysayg 

I have no problem here so far with the `swagger-codegen` generated Java client, so this has to be something with the client that you're using.
According to [the docs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2020-09-04.md#createfeeddocument) the only required parameter is `body` which basically just contains `contentType`, so something like this:

```json
{
  "body": {
    "contentType": "text/csv"
  }
}
``` 

In your request i haven't seen this post parameter anywhere, could you double-check please?
Also are you sure that the content type is `text/tab-separated-values` and not `text/csv`? I'm not sure either, just a guess, but worth a try.

**Comment by cagataysayg** [comment]
Actually I fixed the problem, the reason is the aws4 npm package. I just deleted all my builds and I used the amazon-sp-api npm package, it worked.
