### ISSUE TITLE
Self authorization dissonance between SP-API Docs and Developer Central

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-docs#56]
In the docs under [Self authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization-1) it states:

"**Important**: Click **Generate refresh token** just once to get your refresh token, and then save it for making calls to the Selling Partner API. If you click the **Generate refresh token** multiple times you will get a new refresh token each time, invalidating previous refresh tokens."

However, in Developer Central it says:

![Screen Shot 2020-10-21 at 11 41 55 AM](https://user-images.githubusercontent.com/22284644/96768261-83a95e00-1392-11eb-830e-9eaa5e11720a.png)

They contradict each other. Needs fixed. Bug.

**Comment by rodrigojob** [comment]
same that issue #40

**Comment by charliecode** [comment]
@rodrigojob Thank you. I looked to see whether it was already an issue but must have overlooked this. Will close now. Thanks again.

**Comment by rickdeee** [comment]
Fixed: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization. Thanks for pointing this out, @charliecode
