### ISSUE TITLE
POST_ORDER_FULFILLMENT_DATA error

### ISSUE THREAD

**Issue by L1nYong** [amzn/selling-partner-api-docs#561]
how to use POST_ORDER_FULFILLMENT_DATA to make order shipped,when I submit feeds then it always return 'We are unable to process the XML feed because one or more items are invalid. Please re-submit the feed'.Is there a problem with my xml format?
![image](https://user-images.githubusercontent.com/24206637/113718144-f0d16580-971e-11eb-845d-b832705d88e3.png)

**Comment by stefnats** [comment]
Hey @L1nYong  

Can you validate the XML against [this XSD](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd) (referenced from [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md#order-feeds)) and post the output?
