### ISSUE TITLE
Access denied!

### ISSUE THREAD

**Issue by AmericanY** [amzn/selling-partner-api-docs#565]
Hello,

What should i do in such case?

```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::xxx:user/mc.my.inventory is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxx:role/AmazonOrders
```

**Comment by stefnats** [comment]
Hey @AmericanY 
Could you please double-check this section (especially the IAM steps):
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application

I am suspecting that something with your user/policy/role in AWS is off and that your user is not allowed to perform the STS Call.

**Comment by AmericanY** [comment]
Solved.

**Comment by khanakia** [comment]
@AmericanY How did you solve the issue ?

**Comment by jiangdi0924** [comment]
+1

**Comment by khanakia** [comment]
@jiangdi0924 i solved the issue also i just followed the Amazon docs again and it worked fine. 👍
