### ISSUE TITLE
404 Error [BUG] Documentation

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#566]
This brings a 404 error

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application

Link found in this document
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/migration-guide/selling-partner-api-migration-guide.md#migration-process

**Comment by ShivikaK** [comment]
Hello @hrhearn7 

Thank you for raising this issue.

The documentation links for SP API Developer Guide were updated recently. Here is the correct link -
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application

I will notify our technical documentation team to correct the links in Migration Guide.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by hrhearn7** [comment]
Got it, thank you!
