### ISSUE TITLE
Account under review for 2 weeks - please help

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#567]
We are trying to develop for the new SP-API and currently use MWS, but our account went under review.  We are stuck.  It is affecting our current production and keeping us from making the account a Hybrid to move forward with authentication for the new SP_API.

Case# -8109560011

**Comment by rugved1991** [comment]
Hi @hrhearn7,

Thanks for sharing your case ID. There is an update on the support case you opened. Please review the case and respond back to it with additional information. 

Thanks,
Rugved
Solutions Architect, SP API
