### ISSUE TITLE
Who have Signature working for SP-API with PHP?

### ISSUE THREAD

**Issue by rodrigojob** [amzn/selling-partner-api-docs#57]
I tried create header signature, but don't work.
The aws-sdk-php generate header with "x-amz-security-token", not "x-amz-access-token", like necessary for this application, so , the header is invalid.
I use aws-sdk-php to access SQS.

**Comment by FexusZ** [comment]
I used curl and hash_hmac to get the signature with the tutorial : 
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

https://docs.aws.amazon.com/general/latest/gr/sigv4-create-string-to-sign.html

https://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html

https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html

**Comment by mkemper31** [comment]
You can manually calculate the signature per the documentation linked by @FexusZ. This is a commented snippet from my code for calculating the signature, assuming you've already got a valid string to sign, and the credential scope derived as per https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#credential-scope

```php
private function createSignature($secretKey) { // $secretKey is the AWS secret key from IAM user
	$stringToSign = $this->createStringToSign(); // Derived according to docs: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-string-to-sign.html
	$algorithm = 'sha256';
	$kSecret = "AWS4".$secretKey;
	$date = $this->credentials->date; // Date derived per amazon documentation eg. 20201020 for 20 Oct 2020
	$region = $this->credentials->region; // Region for request eg. us-east-1
	$service = $this->credentials->service; // Service eg. execute-api
	$terminationString = $this->credentials->terminationString; // Signature termination string eg. aws4_request
	$kDate = hash_hmac($algorithm, $date, $kSecret, true);
	$kRegion = hash_hmac($algorithm, $region, $kDate, true);
	$kService = hash_hmac($algorithm, $service, $kRegion, true);
	$kSigning = hash_hmac($algorithm, $terminationString, $kService, true);

	$signature = hash_hmac($algorithm, $stringToSign, $kSigning); // Without fourth parameter passed as true, returns lowercase hexits as called for by docs
	return trim($signature); // Trimming maybe not necessary here but can't hurt.
}
```

**Comment by chenlixin93** [comment]
I used  [signature_v4](https://github.com/chrismeller/awstools/blob/master/aws/signature/v4.php) to generate "x-amz-access-token", you need to use these files :
```
abstract.php
request.php
v4.php
```
I wrote a test file for it like : 
```php
<?php
require("./request.php");
require("./v4.php");

$v4 = new AWS_Signature_v4();
$v4->access_key('your_access_key');
$req = $v4->sign(new AWS_Request(), 'your_secret_key');
print_r($req);
```
but  I still got reponse : 
```json
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
```
this problem is same as : 
https://github.com/amzn/selling-partner-api-docs/issues/24
https://github.com/amzn/selling-partner-api-docs/issues/38

**Comment by rogersv** [comment]
You will need to hash the payload and add that hash to the header. Search for x-amz-content-sha256. That header will also be used in the signature.

**Comment by rogersv** [comment]
You need to hash the payload and add the hash to the header x-amz-content-sha256. The extra header should also be used in the signature.

**Comment by rodrigojob** [comment]
> ```
> $secretKey is the AWS secret key from IAM user
> ```

IAM user? Isn't  LWA?

**Comment by rodrigojob** [comment]
I found the error!. I was using wrong secret for sign.

**Comment by jainjayesh** [comment]
@rodrigojob Which secret we need to use? AWS_Access_Key or AWS_Secret_Key?

**Comment by rodrigojob** [comment]
So sorry , for delay. 
Both.

My error was  use LWA access_key.

**Comment by mba8487143** [comment]
@rodrigojob 
Hi 
I am using LWA Credentials and the signature was generated successfully, Now I am facing this error `The security token included in the request is invalid.
In headers I have passed x-amz-access-token,x-amz-date,host,content-type. Is there any other access token to be passed?
