### ISSUE TITLE
POST /reports/2021-06-30/reports,     Is this api url enabled?

### ISSUE THREAD

**Issue by foxfiring** [amzn/selling-partner-api-docs#570]
response: Access to requested resource is denied

**Comment by gopkg-dev** [comment]
me too

**Comment by jenilew** [comment]
Hello foxfiring and gopkg-dev, 

The new Reports API version 2021-06-30 is not currently enabled in production. The documentation has been provided as a preview; so you can see what the model will look like when we remove the client-side encryption requirement from Reports (and Feeds) this summer.  

This is explained in our Important Notice that we posted yesterday [https://github.com/amzn/selling-partner-api-docs/issues/563](https://github.com/amzn/selling-partner-api-docs/issues/563). 

Regards,
Jen L
Selling Partner API Developer Support

**Comment by jason1004** [comment]
> Hello foxfiring and gopkg-dev,
> 
> The new Reports API version 2021-06-30 is not currently enabled in production. The documentation has been provided as a preview; so you can see what the model will look like when we remove the client-side encryption requirement from Reports (and Feeds) this summer.
> 
> This is explained in our Important Notice that we posted yesterday #563.
> 
> Regards,
> Jen L
> Selling Partner API Developer Support

Is there a specific date for launching in the production environment？

**Comment by wmh49877** [comment]
@jenilew  hello the  feeds api version  2021-06-30 Can't it be used?  No matter how request  its     
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
