### ISSUE TITLE
C# SP-API Client 

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#571]
Is there a SP-API C# client & models similar to what was supplied for MWS ?

**Comment by stefnats** [comment]
@nrogers805 you need to generate it using `swagger-codegen` yourself. Refer to [this README](https://github.com/amzn/selling-partner-api-models/blob/main/clients/sellingpartner-api-aa-csharp/README.md).

**Comment by nrogers805** [comment]
Thanks stefnats

Now I am confused on how to actually use these  API's and hook the LWA with it all - are there any code snippets showing it all working together ?

**Comment by hrhearn7** [comment]
Look at Cafeasp - he pulled it together in .net c# - https://github.com/cafeasp/Selling-Partner-API

**Comment by hrhearn7** [comment]
He also made a video - https://www.youtube.com/watch?v=5clKZvJdPk8

**Comment by nrogers805** [comment]
Thanks hrhearn7 but that example is not using the API's generated by swagger - am I missing something here ?

**Comment by hrhearn7** [comment]
OK , Yes, this actually shows c# code with things tied together. You can step through and grab the JSON it that.  But, you are right, when I pulled into to swagger  - it did not tie in the auth piece as code examples.
