### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by AmericanY** [amzn/selling-partner-api-docs#573]
Hello,

Could you please clarify the rate limit for [Orders API](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md)

am calling the following EndPoint `orders/v0/orders/{}/buyerInfo`

![image](https://user-images.githubusercontent.com/27644047/113879149-866e0300-97ba-11eb-90b2-4890c5b9e113.png)

It's should be 1 request per second ? and what the meaning of `Burst 1` here? i don't understand it at all.

I've already tried to sleep 1 second between each request but i keep getting the following error.

```
You exceeded your quota for the requested resource.
```

but if i kept increment the sleep between requests. the API sometimes answer and sometimes not.

**Comment by AmericanY** [comment]
Hopefully someone can guide me here .

**Comment by AmericanY** [comment]
Even, how to increase my quota for orders API ? i feel lost within the documentation :s it's too complicated.

**Comment by stefnats** [comment]
@AmericanY What is your use-case?
Do you want to retrieve many orders at once?
Did you try one of the reports below?
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#order-reports

**Comment by AmericanY** [comment]
@stefnats Thanks for your response. i just were writing a new support ticket to include the full information while you replying me. i will close that one so we can follow up here https://github.com/amzn/selling-partner-api-docs/issues/576 . Thanks in advance for helping me out.
