### ISSUE TITLE
getPricing problem

### ISSUE THREAD

**Issue by gto2145** [amzn/selling-partner-api-docs#578]
we are exploring the opportunity to migrate from MWS API to the new SP API.

We were using getLowestOfferListingsForASIN (https://docs.developer.amazonservices.com/en_UK/products/Products_GetLowestOfferListingsForASIN.html) to fetch the offers of the market.

We are trying to do the same with getPricing (https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing).

The problem: we can only get data on our own offers.

Can you help us ? is it some scope/authorisation issue with the arn/role ?

**Comment by quazardous** [comment]
Hi @gto2145 I'm facing the same issue.

there is more discussion here https://github.com/amzn/selling-partner-api-docs/issues/423

hope someone can help

**Comment by stefnats** [comment]
Hey @quazardous i don't think this has anything to do with that.
Please find this document:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md

For `getPricing` it says:

> Returns pricing information for a seller's offer listings based on seller SKU or ASIN.

For `getItemOffers` it says

> Returns the lowest priced offers for a single item based on ASIN.

So i think the `getItemOffers` Call is what you want.

**Comment by quazardous** [comment]
> So i think the getItemOffers Call is what you want.

@stefnats but the throttle is definitively not what I want in comparison with MWS API. GetLowestOfferListingsForASIN had a far better throttle...

**Comment by stefnats** [comment]
@quazardous i agree completely! All operations of the Product Pricing API have the same throttles/rate limits and thus are really slow for many ASINs.

Maybe Amazon will provide improvements like
- multiple ASINs at once
- ReportType for the ReportsAPI

Are there any plans for that, Amazon?

**Comment by Jackpot00** [comment]
Hello,

we think to migrate to the new API, are you sure that "GetPricing" does not give information about the competitor's offers? 

Thanks

**Comment by quazardous** [comment]
@Jackpot00 that's it: no data on competitor's offers

**Comment by gto2145** [comment]
You can see the answer from seller support 

"Hello from Amazon Selling Partner Support,

I understand that you are receiving only your offers when GetPricing is used.

I'd like to let you know that this attribute would show only yours offers and not competitors pricing. This is normal.

Please let us know how we did."

Not very logic but what else.

**Comment by ToYonos** [comment]
Hi, the main issue is that GetLowestOfferListingsForASIN did not get an iso replacement call

**Comment by ToYonos** [comment]
Hi, the main issue is that `GetLowestOfferListingsForASIN` did not get an iso replacement call. `getPricing` should be this candidate (I thought so too) but as it only returns the seller's offer listings, it's totally worthless.

`getListingOffers` / `getItemOffers` are basically `GetLowestPricedOffersForSKU` / `GetLowestPricedOffersForASIN` with the same flaw (MyOffer tag is only present when SKU are used as input, cf #214). I don't understand the logic behind `getPricing`

**Comment by oliver3428402** [comment]
> Hey @quazardous i don't think this has anything to do with that. Please find this document: https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md
> 
> For `getPricing` it says:
> 
> > Returns pricing information for a seller's offer listings based on seller SKU or ASIN.
> 
> For `getItemOffers` it says
> 
> > Returns the lowest priced offers for a single item based on ASIN.
> 
> So i think the `getItemOffers` Call is what you want.

I tried the 'getItemOffers' call and got the following error:

 SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

Did anybody use this function with success in order to get info on a product which is not in your inventory?

**Comment by shemsheli** [comment]
Another problem with getItemOffers is that you must specify one condition. In GetLowestPricedOffersForASIN you can specify condition="Any".

**Comment by harvetech** [comment]
My application is based on getting competitors' offered pricing. So am I doomed already ? what are my other options if I just need the current offers on any ASIN?

**Comment by KhorneHoly** [comment]
> My application is based on getting competitors' offered pricing. So am I doomed already ? what are my other options if I just need the current offers on any ASIN?

I also would like to know that, since I'm also depended on the competitors prices.
