### ISSUE TITLE
Website based authorization process does not do the redirection

### ISSUE THREAD

**Issue by PWAgony** [amzn/selling-partner-api-docs#58]
I create the button with:

https://sellercentral.amazon.com/apps/authorize/consent?application_id=MY_APP_ID&state=MY_STATE&redirect_uri=https://MY_WEBSITE&version=beta

and after clicking it, the sellers goes through the process, they approve my app, they are shown the MWS token.

but they are not redirected to the url specifed in the redirect_uri
nor do i get a server hit on that url

When will this be fixed？

**Comment by charliecode** [comment]
Hello @PWAgony This sounds familiar to #48. If so then @GuillermoZAfiroCode [created a case](https://developer.amazonservices.com/support) with Seller Support and was told it's an issue which is being fixed.

**Comment by rugved1991** [comment]
Hi @PWAgony,

Are you still seeing this issue? Please let us know if you have created a support case to troubleshoot this issue further.
If this is no longer an issue, let us know so that we can close this thread.

Best,
Rugved
Solutions Architect, SP API
