### ISSUE TITLE
How to change the ARN from role to user in a hybrid published application

### ISSUE THREAD

**Issue by diegocvazquez** [amzn/selling-partner-api-docs#582]
Hello
Do anyone know if it is possible to change the ARN from a role to a user one in a hybrid published application.

Thanks!

**Comment by stefnats** [comment]
@diegocvazquez i asked that the support recently. They recommend to create a new application, because this cannot be changed - not even by the developer support.

**Comment by diegocvazquez** [comment]
> @diegocvazquez i asked that the support recently. They recommend to create a new application, because this cannot be changed - not even by the developer support.

Well these are horrible news the application is in production, and we have  hundred of sellers using it, also the application hast aproved PII information creating new application is not an option, I will have to make it work with the Role ARN. at the moment 0 success 2 day and not even able to make a call sucessfuly

Thanks for answering

**Comment by stefnats** [comment]
@diegocvazquez i feel your pain.
However, try to use an existing library that handles the STS `AssumeRole` Calls. Using a Role shouldn't be the end of the world.

**Comment by stefnats** [comment]
@diegocvazquez i feel your pain.
However, try to use an existing library that handles the STS `AssumeRole` Calls. Using a Role shouldn't be the end of the world.

**Comment by diegocvazquez** [comment]
> @diegocvazquez i feel your pain.
> However, try to use an existing library that handles the STS `AssumeRole` Calls. Using a Role shouldn't be the end of the world.

Not at all I am using this code, https://github.com/amzn/selling-partner-api-docs/issues/52 
but I am getting {"error_description":"Not authorized for requested operation","error":"unauthorized_client"}
when calling the signer for the lwaAuthCredentials any ideas?

Thanks!

**Comment by stefnats** [comment]
@diegocvazquez could you share some code? i assume you're using the java client?

**Comment by diegocvazquez** [comment]
> @diegocvazquez could you share some code? i assume you're using the java client?

Sure, c# 

//this is get the assumeRoletoken works ok
private static AssumeRoleResponse GetAssumeRoleTokenDetail()
        {
            // AWS IAM user data, NOT seller central dev data
            var accessKey = AppCred.Default.AccessKeyId; // get from users access key id from first step
            var secretKey = AppCred.Default.SecretKey; // get from users secret key from first step

            var credentials = new Amazon.Runtime.BasicAWSCredentials(accessKey, secretKey);
            var client = new AmazonSecurityTokenServiceClient(credentials);
            var assumeRoleRequest = new AssumeRoleRequest()
            {
                DurationSeconds = 3600,               
                RoleArn = "arn:aws:iam::my-role-arn",
                RoleSessionName = DateTime.Now.Ticks.ToString()
            };

            return client.AssumeRole(assumeRoleRequest);
        }

//this is a general function to call an endpoint
static void marketplaceParticipations()
        {

            var role = GetAssumeRoleTokenDetail();
            signatureHelper = new AuthHelper(
                 AppCred.Default.ClientId,
                 AppCred.Default.ClientSecret,
                 AppCred.Default.RefreshToken,
                 new Uri(AppCred.Default.Endpoint),                 
                 role.Credentials.AccessKeyId,
                 role.Credentials.SecretAccessKey,
                 AppCred.Default.Region
            ); 

            restClient = new RestClient(live_url_base);
            IRestRequest restRequest = new RestRequest("/sellers/v1/marketplaceParticipations", Method.GET);

            restRequest.AddHeader("x-amz-access-token", role.Credentials.SessionToken); 
            var request = signatureHelper.SignRequest(restRequest, restClient, content_form_urlencoded);

            try
            {
                var result = restClient.Execute(request);
                if (result.StatusCode == System.Net.HttpStatusCode.OK)
                {
                   ---------
                }
                  
            }
            catch (Exception e)
            {
                throw;
            }            
        }

the result:
{
  "errors": [
    {
      "message": "The security token included in the request is invalid.",
      "code": "InvalidInput"
    }
  ]
} 
looks like the generated token is wrong

**Comment by stefnats** [comment]
@diegocvazquez unfortunately, i'm not familiar with the C# Client.

Did you generate it with `swagger-codegen`? If not, do so, it seems like a proven method:
In Issue #571 there are a few comments on that.

**Comment by diegocvazquez** [comment]
> @diegocvazquez unfortunately, i'm not familiar with the C# Client.
> 
> Did you generate it with `swagger-codegen`? If not, do so, it seems like a proven method:
> In Issue #571 there are a few comments on that.

Actually I am using the code from thar issue. But there is something wrong with the token dont know what it is

**Comment by diegocvazquez** [comment]
I have generated the code with swagger-codgen this is the test

 private static AssumeRoleResponse GetAssumeRoleTokenDetail()
        {
            // AWS IAM user data, NOT seller central dev data
            var accessKey = "AKIARL........."; // get from users access key id from first step
            var secretKey = "fC9cmiRo7ZIBijF..."; // get from users secret key from first step

            var credentials = new Amazon.Runtime.BasicAWSCredentials(accessKey, secretKey);

            var client = new AmazonSecurityTokenServiceClient(credentials);

            var assumeRoleRequest = new AssumeRoleRequest()
            {
                DurationSeconds = 3600,               
                RoleArn = "arn:aws:iam::........",
                RoleSessionName = DateTime.Now.Ticks.ToString()
            };

            return client.AssumeRole(assumeRoleRequest);
        }


        static void connect()
        {
            var role = GetAssumeRoleTokenDetail();

            string resource = "/sellers/v1/marketplaceParticipations";
            IRestRequest restRequest = new RestRequest(resource, Method.GET);

            LWAAuthorizationCredentials lwaAuthorizationCredentials = new
           LWAAuthorizationCredentials
            {
                ClientId = "amzn1.applicat....",
                ClientSecret = "7baa991aa49....",
                RefreshToken = "Atzr|IwEBIEt4....",
                Endpoint = new Uri("https://api.amazon.com/auth/o2/token")
            };

            restRequest = new LWAAuthorizationSigner(lwaAuthorizationCredentials).Sign(restRequest);

            AWSAuthenticationCredentials awsAuthenticationCredentials = new AWSAuthenticationCredentials
            {
                AccessKeyId = role.Credentials.AccessKeyId,
                Region = "eu-west-1",
                SecretKey = role.Credentials.SecretAccessKey
                
            };
                        
            RestClient restClient = new RestClient("https://sellingpartnerapi-eu.amazon.com/");            
            restRequest = new AWSSigV4Signer(awsAuthenticationCredentials).Sign(restRequest, restClient.BaseUrl.Host);
            IRestResponse response = restClient.Execute(restRequest);       
        }

The results are 
{
  "errors": [
    {
      "message": "The security token included in the request is invalid.",
      "code": "InvalidInput"
    }
  ]
}
