### ISSUE TITLE
C# + Feeds! Does it work yet?

### ISSUE THREAD

**Issue by antonycartwright** [amzn/selling-partner-api-docs#583]
Hey everyone!

I had a client who wanted to use Feeds in November. After about 100hrs of research and dabbling, I found that it wasn't possible in C#.

I'm just wondering if it is now possible as it's been a few months.

In other words, has anyone got a feed to work in C#?

Thanks, Antony

**Comment by AsenBashaC** [comment]
I'm also facing the same issue any luck?

**Comment by antonycartwright** [comment]
> I'm also facing the same issue any luck?

None. I've never seen anything like this. I'm not sure why we can't use the old API until SPAPI is ready to go. This API is shocking!!!

**Comment by stefnats** [comment]
Hey there, i'm not a C# pro, but i've seen people using C# to access SP API successfully before.

Have you tried [this guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication)?

**Comment by antonycartwright** [comment]
> Hey there, i'm not a C# pro, but i've seen people using C# to access SP API successfully before.
> 
> Have you tried [this guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication)?

Hi!

That particular guide is the most useful document for this whole API, however, it's a very broad guide which only gets you set up. It has absolutely no mention of feeds or how to use them. Antony
