### ISSUE TITLE
Authorizing Selling Partner API applications Website workflow callbackurl

### ISSUE THREAD

**Issue by diegocvazquez** [amzn/selling-partner-api-docs#589]
Hello 
As far as I understand the only way to set up a callback url for the application authorization is in the application details in the seller central, is there a way to override the callback url for the website workflow? what about passing parameters on the callback url, our application is distributed in multiple servers, it woul be very usefull if the callback could be dinamic when generating the link for the authorization.

We seted up our current application working with MWS a hybrid in order to start the migration, at that point we could not set a callback url, now the application status is Current edit is pending approval, and I was told that I will have to wait 10 day, so basically I will not be able to set up a call back url for the next 10 days.

We have a huge application to migrate untill september and this situation is blocking us, self authorization is not an option because the seller account who owns the application does not have any products or orders.

Thanks for your help

**Comment by stefnats** [comment]
> We seted up our current application working with MWS a hybrid in order to start the migration, at that point we could not set a callback url, now the application status is Current edit is pending approval, and I was told that I will have to wait 10 day, so basically I will not be able to set up a call back url for the next 10 days.

Did you try adding `version=beta` to the auth URL?

For setting a custom redirect URL, i didn't succeed in doing that, maybe i am missing something too?

**Comment by diegocvazquez** [comment]
hi @stefnats 
Actually we didnt set up a value for the Callback url because we didnt know about the ten 10 day, the version=betta I think it is related to the Login URL basically when the workflow starts from amazon, is this right?

**Comment by diegocvazquez** [comment]
@stefnats 
I am still testing this with a new application that I created I will get back to you

**Comment by diegocvazquez** [comment]
Hi @stefnats, this is how far I got;
1. I am able to gernerate a link to start the website workflow.
2. seller follows the link, will send him to amazon, then the seller will authenticate and accept the terms and conditions for the app
3. Amazon will call the url set up as OAuth Login URI and send a authorization code with some other info
4. using th code I require a RefreshToken (the name is unfortunate I think) I will save this token
5. I can make calls on behalf of the seller that accepted the contidions in step 2

fell free to ask if you have any questions

**Comment by stefnats** [comment]
@diegocvazquez yup, exactly. i thought you were referencing to the `callback url` part - setting a custom `callback url` (that the user is redirected to after accepting) that is not the default URL that was saved in the developer central.

**Comment by diegocvazquez** [comment]
> @diegocvazquez yup, exactly. i thought you were referencing to the `callback url` part - setting a custom `callback url` (that the user is redirected to after accepting) that is not the default URL that was saved in the developer central.
> 
> EDIT: I think it was just solved [here](https://github.com/amzn/selling-partner-api-docs/issues/270#issuecomment-816885646)

Actually I was refering to have some kind of dynamic URL, I am using the state to embed the info I need.

I will close this ticket, thanks for your help again

**Comment by charliecode** [comment]
@stefnats You'll want to test that the Website Workflow OAuth endpoint actually accepts the redirect_uri as @rugved1991 indicated might be a possibility in #270. The reason being these are two different endpoints as is indicated in the docs and shown below.

Website workflow endpoint:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample&version=beta

Marketplace Appstore Workflow endpoint example:
https://amazon.com/apps/authorize/confirm/amzn1.sellerapps.app.2eca283f-9f5a-4d13-b16c-474EXAMPLE57?redirect_uri=https://d2yzyfnnpjylxu.cloudfront.net/landing.html&amazon_state=amazonstateexample&state=-37131022&version=beta

 I haven't gotten the opportunity to do so yet. If it works then only the docs will need updated as I indicated in #270. If it doesn't then Amazon will not only need to fix the docs but also the Website Workflow OAuth endpoint to handle the redirect_uri param. If you do verify it works please let me know as I won't be able to until next week.
