### ISSUE TITLE
C# RestSharp

### ISSUE THREAD

**Issue by jmawebtech** [amzn/selling-partner-api-docs#590]
Hi,

Is there a C# SDK that does not use RestSharp? 

https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp

If not, can I get some guidance? I want to use HTTPClient because the Swagger classes use HttpClient.

**Comment by abuzuhri** [comment]
> Hi,
> 
> Is there a C# SDK that does not use RestSharp?
> 
> https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp
> 
> If not, can I get some guidance? I want to use HTTPClient because the Swagger classes use HttpClient.

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by jmawebtech** [comment]
Please close

Sent via the Samsung Galaxy S10e, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
