### ISSUE TITLE
feed xml: Content is not allowed in trailing section

### ISSUE THREAD

**Issue by bluelveii** [amzn/selling-partner-api-docs#593]
I have successfully submitted XML data through feed API, but the feedback prompts "content is not allowed in training section". After testing and checking it many times, I'm sure there are no spaces or other symbols at the end of my XML file. How to solve this problem?

**Comment by cgaugel** [comment]
I had the same problem and switched to flat files, because Amazon wasn't able to tell me the symbol which is not allowed (there was no BOM or somehting like that in my XML). XML was valid at all.. Maybe it helps..

If you find a solution, please let me know..

**Comment by stefnats** [comment]
@bluelveii have you been able to validate against the XSD schema? usually that's what amazon does to validate the file, maybe that could help you?

**Comment by dannyatftecu** [comment]
I tried the following (with my own merch ID and SKU, of course), and MWS accepted with success (no error).  So I figured XML is formatted correctly.

With Selling Partner API, I get "Content is not allowed in trailing section." for the end line of file location:

```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
  <Header>
    <DocumentVersion>1.02</DocumentVersion>
    <MerchantIdentifier>my_merch_id</MerchantIdentifier>
  </Header>
  <MessageType>Product</MessageType>
  <PurgeAndReplace>false</PurgeAndReplace>
  <Message>
    <MessageID>1</MessageID>
    <OperationType>Update</OperationType>
    <Product>
      <SKU>my_test_sku</SKU>
      <ProductTaxCode>A_GEN_NOTAX</ProductTaxCode>
      <DescriptionData>
        <Title>Example Product Title</Title>
        <Brand>Example Product Brand</Brand>
        <Description>This is an example product description.</Description>
        <BulletPoint>Example Bullet Point 1</BulletPoint>
        <BulletPoint>Example Bullet Point 2</BulletPoint>
        <MSRP currency="USD">99.99</MSRP>
        <Manufacturer>Example Product Manufacturer</Manufacturer>
        <ItemType>example-item-type</ItemType>
      </DescriptionData>
      <ProductData>
        <Health>
          <ProductType>
            <HealthMisc>
			  <UnitCount unitOfMeasure="Count">1</UnitCount>
              <Ingredients>Example Ingredients</Ingredients>
              <Directions>Example Directions</Directions>
            </HealthMisc>
          </ProductType>
        </Health>
      </ProductData>
    </Product>
  </Message>
</AmazonEnvelope>
```

I used notedpad++ to create it as utf-8 and I checked using emacs in hex-mode as well HxD for any stray characters and didn't see any at the end of file.

**Comment by dannyatftecu** [comment]
Note that as suggested in #398 I tried both UTF-8 and iso-8859-1 (with the later, I tried iso-8859-1 only as well as starting with iso-8859-1 file and converted to UTF-8 before encrypting and uploading) formats and all 3 (UTF-8 -> encrypt -> upload; iso-8859-1 -> encrypt -> upload; iso-8859-1 -> convert to UTF-8 -> encrypt -> upload) generated the same error above....

**Comment by jeffstone30** [comment]
I was getting this message over and over again. Then, I was able to successfully process a product that had no <BulletPoint> tags in it. For me, I can't get any product with a <BulletPoint> tag to work....maybe Amazon is changing stuff here? Not sure but thought I'd share. Drop the <BulletPoint> tag from your feed and then see if it works.

**Comment by dannyatftecu** [comment]
@jeffstone30 I tried it (removing BulletPoint tags) but no luck.  I have 2 different xml's which submits OK via MWS but returns the errors above via selling partner API's.

**Comment by jeffstone30** [comment]
Yeah, I am actively trying to pass XML documents to Amazon and some are working and some are not....for no apparent reason. I just passed one product with bullet points and it worked. So, I started stripping down my XML to the bare minimum. Still can't figure out why one is working and the other is not. They are almost identical products minus the name and UPC code but one fails and one succeeds through the partner api. Very odd.

**Comment by aniruddhaad** [comment]
I  just found the same issue "Content is not allowed in trailing section." while uploading POST_PRODUCT_DATA xml file.
There is nothing really wrong with file. UTF-8 encoded (even manually encoded to UTF-8 and tried uploading it) . 
Someone should really look in to this!!

**Comment by canerkoroglu** [comment]
Hello i have found a solution please check  identifier of document : <?xml version="1.0" encoding="UTF-8"?> be carefull closing tag there should be a space between " and ? symbols like that <?xml version="1.0" encoding="UTF-8" ?> try this, it should work.

**Comment by canerkoroglu** [comment]
Hello i have found a solution please check identifier of document : 

invalid format
`<?xml version="1.0" encoding="UTF-8"?>`

be carefull closing tag there should be a space between " and ? symbols like that try this, it should work.

valid format
`<?xml version="1.0" encoding="UTF-8" ?>`

**Comment by aniruddhaad** [comment]
> Hello i have found a solution please check identifier of document :
> 
> invalid format
> `<?xml version="1.0" encoding="UTF-8"?>`
> 
> be carefull closing tag there should be a space between " and ? symbols like that try this, it should work.
> 
> valid format
> `<?xml version="1.0" encoding="UTF-8" ?>`

Just tried it -> <?xml version="1.0" encoding="utf-8" ?>
I am still getting the same error -
ResultMessageCode 5001
ResultDescription: XML Parsing Fatal Error at Line 27, Column 1: Content is not allowed in trailing section. Content is not allowed in trailing section.

**Comment by bhargavaaaa** [comment]
I have the same problem can't find solution for it.

**Comment by canerkoroglu** [comment]
> I have the same problem can't find solution for it, Is there not any solution for it? Cause I am generating xml file with PHP DOMDocument and also can't find any error in generated .xml file,
> 
> Although in SellingPartner APIs I am facing that issue, issue is not comes every time in every marketplace, it comes sometimes for same xml file sometimes, Is there any bug or issue from their side 🤔.

Did u try my solution?

Change header <?xml version="1.0" encoding="UTF-8" ?> instead of <?xml version="1.0" encoding="UTF-8"?> there is a space between " and ? symbols before the closing tag.

**Comment by bhargavaaaa** [comment]
> > I have the same problem can't find solution for it, Is there not any solution for it? Cause I am generating xml file with PHP DOMDocument and also can't find any error in generated .xml file,
> > Although in SellingPartner APIs I am facing that issue, issue is not comes every time in every marketplace, it comes sometimes for same xml file sometimes, Is there any bug or issue from their side 🤔.
> 
> Did u try my solution?
> 
> Change header `<?xml version="1.0" encoding="UTF-8" ?>` instead of `<?xml version="1.0" encoding="UTF-8"?>` there is a space between " and ? symbols before the closing tag.

Have tried that but its not working 🤔🤔.

**Comment by aniruddhaad** [comment]
I think the issue not the xml tag itself. it's something else.
I have this working fine with 
`<?xml version="1.0" encoding="utf-8" ?>`

**Comment by bhargavaaaa** [comment]
Its sometimes working and sometimes not working for the same file,
I have tried too many sometime it sends success and sometimes gives this trailing space error,
Not sure about what is the issue 🤔.

**Comment by aniruddhaad** [comment]
In the ASECryptoStream.php check if you have trimmed the body -

public static function encrypt(string $plainText, string $key, string $iv): string
    {
        //$plainText = static::getPaddedText($plainText);
        $plainText = trim(static::getPaddedText($plainText));
        return trim(openssl_encrypt($plainText, static::CIPHER, $key, OPENSSL_RAW_DATA, $iv));
    }
