### ISSUE TITLE
POST_FLAT_FILE_INVLOADER_DATA - 90011- The file's column headings are missing or invalid

### ISSUE THREAD

**Issue by shintaii** [amzn/selling-partner-api-docs#596]
I have created a .tsv file (flat file) programmitcly using python. When uploading that file, manually eveything works out fine and the file is processed. 

When sending the same file using the SP-API it fails with error:
```
Feed Processing Summary:
	Number of records processed		0
	Number of records successful		0

original-record-number	sku	error-code	error-type	error-message
0		90011	Fatal	The file's column headings are missing or invalid. To correct this error, download the template again and use that new copy, or insert the correct column headings as row two of your existing file.
```

File used:
`sku	product-id	product-id-type	price	minimum-seller-allowed-price	maximum-seller-allowed-price	item-condition	quantity	add-delete	will-ship-internationally	expedited-shipping	standard-plus	item-note	fulfillment-center-id
0889698521550	889698521550	4	40.95	40.95	40.95	11	0	a	4	N	Y		`

File is tab seperated and utf8 encoded.

**Comment by stefnats** [comment]
There seem to be no official template - many different versions out there.
I managed to find a version with many more headline columns. You can download it on this page:
https://sellercentral-europe.amazon.com/gp/help/help-popup.html/?itemID=200385480

This might not be very helpful for non-eu users, so try to find this in seller central:
Inventory -> Add Products via Upload -> Inventory Loader File -> Learn more link

I hope that helps!

**Comment by shintaii** [comment]
> There seem to be no official template - many different versions out there.
> I managed to find a version with many more headline columns. You can download it on this page:
> https://sellercentral-europe.amazon.com/gp/help/help-popup.html/?itemID=200385480
> 
> This might not be very helpful for non-eu users, so try to find this in seller central:
> Inventory -> Add Products via Upload -> Inventory Loader File -> Learn more link
> 
> I hope that helps!

Thanks! I have tried that already. All columns, some columns, 1 row, 1000 rows, no data, all dummy data, nothing seems to work. 

And when i get the created file and upload it manually, it works! But via SP-API it does not. My personal hunch is that during the document upload process something is 'changed' to the file. There can be no other explanation right? 

For example, i created some products manually on seller central, exported them using the inventory loader, uploaded it and it works. That exported file when send trough the SP-API does not work and gives error. 

The only thing different between SP-API and MWS is that during upload you now encrypt the file using AES. I think something goes wrong there. 

I'm now trying to bypass the encryption, or use different methods on encryption of the file to see if that works.

**Comment by rugved1991** [comment]
Hi @shintaii,

Can you please confirm if you are encrypting the feed using the encryption details provided by the SP API in createFeedDocument operation? You will need to use the "AES" encryption with the initializationVector and key provided in the response of createFeedDocument.
You can refer to the sample Java Encryption code provided in the [GitHub repository](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md#step-2-encrypt-and-upload-the-feed-data) for reference. 

Thanks,
Rugved
Solutions Architect, SP API
