### ISSUE TITLE
[BUG] Updating inventory quantities on Direcfulfillment inventory

### ISSUE THREAD

**Issue by GuillermoZAfiroCode** [amzn/selling-partner-api-docs#597]
I am trying to update inventory from vendor directfulfillment account. According with your documentation, you could update quantities using buyerProductIdentifier(ASIN) or vendorProductIdentifier(SKU).
When I try to update any product using the second option (using SKU), the request returns that have no products with that SKU but if I inform the ASIN in vendorProductIdentifier(SKU) it works fine.

Seems that always is searching products using ASIN independently that you inform ASIN or SKU field.
If I put buyerProductIdentifier field with ASIN, it works fine too so seems we have not way to update quantities using vendorProductIdentifier(SKU)

https://sellingpartnerapi-na.amazon.com/vendor/directFulfillment/inventory/v1/warehouses/{warehouseId}/items

![image](https://user-images.githubusercontent.com/73171256/114388651-43ce7100-9b94-11eb-9637-46a0d56595be.png)

**Comment by tecorraltd** [comment]
@GuillermoZAfiroCode where did you get the warehouseid from?

**Comment by coder771** [comment]
@tecorraltd did you find out where to get warehouseId from?
