### ISSUE TITLE
Issue getting orders with "created_after" date parameter

### ISSUE THREAD

**Issue by DydyDevelopper** [amzn/selling-partner-api-docs#598]
Dear support,
I am having un issue to get orders. The error is : 
Exception when calling OrdersApi->getOrders: [400] { "errors": [ { "code": "InvalidInput", "message": "timestamp must follow ISO8601", "details": "" } ] }

The problem is that my date is well formatted. Maybe it is an issue with the timezone ? I am from France.
I tried multiple format but for me correct one and not working is : 
2021-04-12T14:58:45+00:00
or 
2021-04-12T14:58:45+0000

Can you please help ?

Thanks
Regards
Dylan

**Comment by xbaha** [comment]
hi, try date without time.
i could not get the time working in ISO 8601 format, have you?

**Comment by vikingcodes** [comment]
Try this format

2020-04-15T12:00:00
