### ISSUE TITLE
SP-API Reports Generation Long Queue Times

### ISSUE THREAD

**Issue by tmello01** [amzn/selling-partner-api-docs#599]
Hello,

We are trying to generate data reports through the SP-API, but our report hashes are expiring before the report has even begun processing on the sp-api side. We cannot find a status dashboard and reports have previously worked fine. Is this an issue on Amazon's side? Or is there a new step we need for a report to go from IN_QUEUE to IN_PROGRESS?

**Comment by tmello01** [comment]
Update: We added a process to re-sign the request before checking the status, but we are still seeing 20 minute and counting queue times for reports for one month of data.

**Comment by rugved1991** [comment]
Hi @tmello01,

Can you please open a support case for this issue? The support team will be able to assist you in troubleshooting this issue further and provide an update. Please provide us with a caseID for tracking.

Please add the following details in the case:
1. Use Case
2. App ID
3. Merchant Token/Seller ID
4. Request and Response of API along with headers. (We would need request ID and timestamps found in response headers)

Thanks,
Rugved
Solutions Architect, SP API

**Comment by nirmay** [comment]
We are facing the same issue. A support request is already raised but no response yet.
has anyone been able to get past this issue? or atleast get any response from Amazon team.
