### ISSUE TITLE
Reports API - Usage Plans and Rate Limits

### ISSUE THREAD

**Issue by gregoks** [amzn/selling-partner-api-docs#6]
Hi,

I don't see anything regarding Usage Plans and Rate Limits for reports api. What are limits?

I cannot use the notifications for finished reports so I have to poll to check if report has finished running, it can cause throttling. 
Any plans adding dynamic usage plan to reports?

Thx,

Greg

**Comment by edaik** [comment]
Thanks Greg. We've identified this as a docs bug and will be updating the references/models soon.

**Comment by evdeg** [comment]
@gregoks Thanks again for bringing this issue up. The Usage Plans and Rate Limits for the Reports API have been updated in the API [reference](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md) and the [model](https://github.com/amzn/selling-partner-api-models/blob/main/models/reports-api-model/reports_2020-09-04.json) for the Reports API. Look at the section named "Usage Plan" under each operation. Please let us know if you have any other questions.
