### ISSUE TITLE
Report Apis  is giving  Unauthorized error. 

### ISSUE THREAD

**Issue by RonyFrancis** [amzn/selling-partner-api-docs#60]
I facing this issue. Report API is giving Unauthorised error.  Is anyone else facing this issue

request:

url: https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports
header:
    X-Amz-Date: 20201022T093416Z
    X-Amz-Access-Token: <Access token>
    Authorization: <auth creds>
    Accept: application/json
    Content-type: application/json
body: {
  "reportOptions": {},
  "reportType": "_GET_MERCHANT_LISTINGS_ALL_DATA_",
  "dataStartTime": "2019-12-10T20:11:24.000Z",
  "dataEndTime": "",
  "MarketplaceIds": [
    "A1PA6795UKMFR9",
    "ATVPDKIKX0DER"
  ]
}

reponse:
header: 
   X-Amzn-Requestid: c2e5bf7b-223e-4e1e-95d4-b36aef58fc94
   X-Amzn-Errortype: AccessDeniedException
   Content-type: application/json
   
body: {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by p-prins** [comment]
Related to #24 #38 #52 .

**Comment by rodrigojob** [comment]
Of course that you removed security info header of your post.
I'm triyng generate signature without success. With AWS SDK or not.
What language you are using?

**Comment by ShivikaK** [comment]
Hello @RonyFrancis 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
