### ISSUE TITLE
[BUG] /orders/v0/orders amazonOrderIds is a required parameter

### ISSUE THREAD

**Issue by dolphin-w** [amzn/selling-partner-api-docs#600]
`
//        amazonOrderIds.add("112-3731999-3925002");
//        amazonOrderIds.add("111-2451397-6921803");

        GetOrdersResponse response = ordersV0Api.getOrders(marketplaceIds, createdAfter,createdBefore, lastUpdatedAfter,
                lastUpdatedBefore, orderStatuses, fulfillmentChannels, paymentMethods, buyerEmail,
                sellerOrderId, maxResultsPerPage, null, null, null);
        OrdersList list = response.getPayload();
        System.out.println(response);

    public static String Stringiso(String data) {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime dt1 = LocalDateTime.parse(data, dateTimeFormatter);
        ZoneOffset offset = ZoneOffset.of("+08:00");
        OffsetDateTime date = OffsetDateTime.of(dt1, offset);
        DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        String datas = date.format(formatter2);
        return datas;
    }`
This is my code snippet.
If you don’t add the orderId parameter, it will ERROR BAD Request

**Comment by rugved1991** [comment]
Hi @dolphin-w,

The getOrders operation only has MarketplaceID as the required parameter. You will have to use either CreatedAfter, CreatedBefore, LastUpdatedAfter or LastUpdatedBefore parameter to fetch the orders. These are marked as optional as you can select which parameter to use in the request. But, it is important to call one of these params to successfully call the API.
Please try removing all other parameters except the marketplaceId and one of the timestamps.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by dolphin-w** [comment]
Thank you
