### ISSUE TITLE
authorizationCode API for the app in draft state

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#601]
Does **/authorization/v1/authorizationCode** API work if the app is in the draft state?

As I am getting this error

`[400] { "errors": [ { "code": "InvalidInput", "message": "A published application with the provided app-id not found", "details": "" } ] }`

**Comment by rugved1991** [comment]
Hi @Nilanth,

The Authorization API only works when the application is published on the Appstore. It is used to migrate your current MWS sellers to the new platform without them needing to reauthorize your app. The Authorization API is only applicable for a hybrid application. It is not to be used with a pure SP API app.

Thanks,
Rugved
Solutions Architect, SP API
