### ISSUE TITLE
GetOrderAddressResponse Does not include Buyers Name and Address !

### ISSUE THREAD

**Issue by mashhood1995** [amzn/selling-partner-api-docs#602]
I am trying to import orders from amazon to oracle Netsuite ERP using Orders API. When I request order shipping address, the response does not include  name and street address . After searching for answers i found out that it requires PII access . How can i get PII access for our seller account. We are using API for our own business only.
![Capture](https://user-images.githubusercontent.com/52625077/114557346-04328280-9c83-11eb-84ce-2bf613f9e0b4.PNG)

**Comment by rugved1991** [comment]
Hi @mashhood1995,

Can you please provide us the case ID for your developer registration? I will reach out to the team for an update.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by mashhood1995** [comment]
Hi @rugved1991 
Our developer registration case id # 7466871181 was approved on Oct 13, 2020. We created an app with app id # amzn1.sellerapps.app.2ac9bbe6-86f7-4b21-a725-3aa0f78e6811 .The Issue is that when we request order shipping address , we do not get buyers name, address and phone number information .
Thank you

**Comment by rugved1991** [comment]
Hi @mashhood1995,

Thanks for sharing your case ID and App ID. I was able to confirm that you had requested only "Inventory and Order Tracking" role in the DRAF form. BuyerName, Address are PII information and so you would need access to restricted role "Direct-To-Consumer Shipping" role on your account. Please re-edit your developer profile and request all roles that you would require on the account. You can then choose which roles to apply on the application. 
Please note that for restricted roles access, you would need to provide additional information about handling PII data securely.
I hope this information helps. Feel free to submit the DRAF again and monitor the case for updates.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by jchavest13** [comment]
Hi @mashhood1995, 

Upon review, I can confirm there is an update in your most recent Developer Registration case. Please carefully review it and update the requested information as instructed in the email sent through the case.

Regards,
Julian 
Developer Registration Specialist, SP-API

**Comment by mashhood1995** [comment]
Hi @jchavest13 
I have a question regarding this point mentioned in reply to our request on case 8249174521 . 
"1. Acceptable Use Policy - Do not use, offer, or promote external (non-Amazon) data services that vend Amazon data, including data retrieved from Amazon's public-facing websites.
• You confirmed to be retrieving Amazon Information from Oracle NetSuite ERP, which is a violation to our policy as you must not provide access to Amazon data to third parties with your Developer Credentials."

There are many third party applications like folio,celigo etc that import orders from Amazon Seller Central to Netsuite . Is using SP-API to create integration with ability to import orders from amazon seller to Netsuite not allowed ?
Thank you

**Comment by jchavest13** [comment]
Hi @mashhood1995,

Please disregard that question and make sure to address from question #2 to #9, as instructed in the email we previously sent you through case 8249174521. I think it could have been misinterpreted when reviewed. 

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by adarmanto** [comment]
Hello @jchavest13 

I had a similar issue for both endpoint APIs: `getOrderAddress` and `getOrderItemsBuyerInfo`, we have already reported a few weeks ago with case ID 816113245  and still not clearly responded :/ We have also been granted PII access already (Case ID: 5884230741).

Even we have tried by calling the [Tokens API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md) to get a Restricted Data Token (RDT) successfully, but the buyer name & address details are still missing, 

```
// GetOrderBuyerInfoResponse
{
    "payload": {
        "AmazonOrderId": "111-XXXXX-XXXXXX",
        "BuyerEmail": "XXXXXXX@marketplace.amazon.com"
    }
}

// GetOrderAddressResponse
{
    "payload": {
        "AmazonOrderId": "111-XXXX-XXXX",
        "ShippingAddress": {
            "Name": "",
            "City": "Sparrows Point",
            "County": "Balitmore",
            "StateOrRegion": "MD",
            "PostalCode": "21219",
            "CountryCode": "US"
        }
    }
}

```

Any help is much appreciated!

**Comment by jchavest13** [comment]
Hi @adarmanto,

Upon review, I could confirm indeed you were granted with PII access for roles requested through case 5884230741 in both MWS and SP-API. In addition, you have recently requested two additional Restricted SP-API access roles through case 8280973351. For the ones already approved, please connect with Developer Support team if you are having issues getting the information required, by using the link below:
https://sellercentral.amazon.com/gp/mws/contactus.html

Regarding the additional roles you requested, please accept our apologies for the delay getting back to you on your case 8280973351. You can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by paly76** [comment]
> Regarding the additional roles you requested, please accept our apologies for the delay getting back to you on your case 8280973351. You can rest assured that our team is working diligently to address your case as soon as possible.
> 
> Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

hi, do you resole it??
