### ISSUE TITLE
Problem registering SP-API

### ISSUE THREAD

**Issue by jesusvalle** [amzn/selling-partner-api-docs#603]
Hello,

In my team we were using until now MWS for seller account integrations in our system (we are registered as developer).

We are trying to register to use the new amazon SP-API, using the guide.

We have done all the steps, except step 6. We can’t find the way to register the application (the option in the tutorial doesn’t exist) and in developer console nothing appears, I attach a screenshot:

https://sellercentral.amazon.com/sellingpartner/developerconsole

Has anyone encountered this problem and can help us? Thank you very much

![developer console recorte](https://user-images.githubusercontent.com/23029374/114579005-bcf5c300-9c7d-11eb-8e54-a3eaa312d995.png)

**Comment by charliecode** [comment]
@jesusvalle Looks like you're in the Login with Amazon section not the Seller Central section with a registered Selling account. Also could be you're not in the root Seller Central account as you need to be to setup anything, all things which need to be fixed by Amazon so the developer experience is better and more fair for all involved.

**Comment by vikingcodes** [comment]
@jesusvalle You need to login "Seller Central" then need to create new app. Their is three types of apps.

1. MWS
2. Hybrid (MWS and SP-API)
3. SP-API

I suggest to create SP-API app. If you only want to use SP-API. 

If you still want to use MWS and SP-API API on same app then go with Hybrid.

FYI: from September 2021 amazon will not support MWS API.

**Comment by jesusvalle** [comment]
hello, thank you very much for your reply.

I am in seller central now with my root account, but in the apps & services section, I don't see any MWS option or for developing an app. Is it possible that I need to have a professional account for that option to appear?

Best regards and thanks again.

![image](https://user-images.githubusercontent.com/23029374/114663491-b5283400-9cfa-11eb-8d16-fa9ee897e747.png)

**Comment by charliecode** [comment]
@jesusvalle #429

**Comment by jesusvalle** [comment]
Thank you all. Finally it was a problem of not having the account with a pro plan.

Best regards.

**Comment by stefanosx** [comment]
Hello, how can we check if the seller central account is in pro plan or not?
