### ISSUE TITLE
Not getting data from listFinancialEvents prior to 2019-04-01

### ISSUE THREAD

**Issue by arontolentino** [amzn/selling-partner-api-docs#604]
My teams has been experiencing issues with retrieving any data from the `listFinancialEvents` operation prior to 2019-04-01. We're just getting arrays. Our account has financial data all the way to 2016. 

The 2019-04-01 is about 2 years from today. Does the `listFinancialEvents` have a new limit now of 2 years? or is this just a coincidence?

We also tried utilized `listFinancialEventsByOrderId` with an orderId that dated back to 2016 and it also returned a response full of empty arrays. 

Anyone else having this issue?

![Screenshot from 2021-04-13 15-50-22](https://user-images.githubusercontent.com/29000382/114612366-0d662400-9c70-11eb-85be-978f46c3d49d.png)

![Screenshot from 2021-04-13 15-50-45](https://user-images.githubusercontent.com/29000382/114612371-0e975100-9c70-11eb-8841-7a1b4d756d9b.png)

![Screenshot from 2021-04-13 16-44-29](https://user-images.githubusercontent.com/29000382/114618617-8cab2600-9c77-11eb-81fb-904fc75cdc81.png)

**Comment by cgaugel** [comment]
Any news?

**Comment by arontolentino** [comment]
@cgaugel It's definitely an odd situation but I haven't heard back from anyone. 

The MWS documentations states that you can't get financial events older than 18 months from the request date. However, with the current SP-API financial events endpoint, we're able to get up to 24 months of data. 

The documentation doesn't state anything at all regarding any limitations. It would be nice to get this information so we can plan accordingly.

**Comment by arontolentino** [comment]
Maybe @rugved1991 can shed some light on this?
