### ISSUE TITLE
Where to post c# model swagger-codegen issues

### ISSUE THREAD

**Issue by diegocvazquez** [amzn/selling-partner-api-docs#605]
Hello,

I am not sure where to post swagger-codegen issues, I am encountering a lot of problems in the json on generating a c# version of the models, f**or example missing visibility.mustache template, or some java BigDecimal type in the c# generated model, even not complying code**, is this the right place or should I post it in https://github.com/amzn/selling-partner-api-models.

Thanks for your advice

**Comment by rugved1991** [comment]
Hi @diegocvazquez,

Thanks for reaching out. You can use the issues page on the Swagger Models repository for issues with the swagger model or client libraries.

Thanks,
Rugved
Solutions Architect, SP API
