### ISSUE TITLE
Business Report Manage Quotes Report(RFQD_BULK_DOWNLOAD) return empty result

### ISSUE THREAD

**Issue by umairkhatri** [amzn/selling-partner-api-docs#606]
I am working with node.js and trying to get the result data from excel file, but it returns empty there is no data in file.
await this.createReport({
      reportType: 'GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL',
      startTime : createdAfter.toISOString(),
      endTime : createdBefore.toISOString(),
      marketplaceIds : [this.#marketPlace]
})
Provided all the desired parameters with specified date range of last week and month also from current date but no data? marketPlace is the correct marketPlaceId where seller account is registered.
Above code is creating the report, get report id, get document id of the report, download document and decrypt buffer to read the content but it returns empty data for only business reports?

Any solution?

**Comment by ianrussel** [comment]
Have you tried last 30 days ? Some reports can only get results past 30 days

**Comment by bigearIsSoNice** [comment]
I have the same problem. who can help pls ?

**Comment by vermouthsam** [comment]
I have the same problem. who can help pls ?
