### ISSUE TITLE
Connecting problem with SP-API

### ISSUE THREAD

**Issue by yasunori0120** [amzn/selling-partner-api-docs#608]
I wrote a Java code for connecting to "https://sellingpartnerapi-na.amazon.com" through SP-API.
 
Here is the code. Every time I run the code, I encounter an error saying:
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
What should I do with correcting the code? Any comments, suggestions, etc. would be greatly appreciated.
(Class SPAPI is written in "https://jesseevers.com/spapi-first-application/").

import com.amazon.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.amazon.SellingPartnerAPIAA.AWSSigV4Signer;
import com.amazon.SellingPartnerAPIAA.LWAAuthorizationSigner;
import com.squareup.okhttp.*;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.services.securitytoken.AWSSecurityTokenService;
import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder;
import com.amazonaws.services.securitytoken.model.AssumeRoleRequest;
import com.amazonaws.services.securitytoken.model.AssumeRoleResult;
import com.amazonaws.services.securitytoken.model.Credentials;

public class test3 {
	 
    public static void main(String[] args) {      
    	try {

         SPAPI spapi = new SPAPI();
         
         // Build a request
    	 String basePath = "https://sellingpartnerapi-na.amazon.com";  
    	 String localVarPath = "/orders/v0/orders";
    	 String url = basePath + localVarPath; 
        Request request =  new Request.Builder()
                .url(url)
                .addHeader("Content-Type", "application/json")
                .addHeader("user-agent", "My YouTube App 1.0 (Language=csharp;Platform=Windows/10)")
                .get()
                .build();

    	//Login with Amazon
        request = new LWAAuthorizationSigner(spapi.lwaAuthCreds).sign(request);
      
   	   //Get temporary session token   	 
        String SESSION_NAME = "assumeRoleTest";
        // Creating the STS client is part of your trusted code. It has
        // the security credentials you use to obtain temporary security credentials.
        AWSSecurityTokenService stsClient = AWSSecurityTokenServiceClientBuilder.standard()
                                                .withCredentials(new ProfileCredentialsProvider())
                                                .withRegion(spapi.config.getAwsRegion())
                                                .build();
        // Obtain credentials for the IAM role. Note that you cannot assume the role of an AWS root account;
        // Amazon S3 will deny access. You must use credentials for an IAM user or an IAM role.
        AssumeRoleRequest roleRequest = new AssumeRoleRequest()
                                                .withRoleArn(spapi.config.getAwsIAMARN())
                                                .withRoleSessionName(SESSION_NAME);
        AssumeRoleResult roleResponse = stsClient.assumeRole(roleRequest);
        Credentials sessionCredentials = roleResponse.getCredentials();
       
        request = request.newBuilder()
    			.addHeader("x-amz-security-token", sessionCredentials.getSessionToken())
    			.build();
        
    	//Amazon web service
         AWSAuthenticationCredentials awsAuthCreds2;
        awsAuthCreds2 = AWSAuthenticationCredentials.builder()
                .accessKeyId(sessionCredentials.getAccessKeyId())
                .secretKey(sessionCredentials.getSecretAccessKey())
                .region(spapi.config.getAwsRegion())
                .build();

        request =  new AWSSigV4Signer(awsAuthCreds2).sign(request);
 
        OkHttpClient client = new OkHttpClient();
    	Response resp = client.newCall(request).execute();   
    	
        System.out.println("HEADER -> " + resp.headers().toString() + " BODY -> "+ resp.body().string()); 

        } catch (Exception e) {
            System.err.println("Error : ");
            e.printStackTrace();
        }
}
}

**Comment by rugved1991** [comment]
Hi @yasunori0120,

Can you please confirm if you have assigned an IAM User ARN or IAM Role ARN on your application?

Thanks,
Rugved
Solutions Architect, SP API

**Comment by yasunori0120** [comment]
Thank you for your response. 

Yes, I assigned my IAM User ARN (arn:aws:iam:: ... ) and other necessary information (accessKeyId, secreKey, region for AWS, and authEndpoint, clientID, clientSecret, refreshToken, etc.) in my property setting file.
These information are read by the statement "SPAPI spapi = new SPAPI();".

Best Regards,
Yasunori

**Comment by rugved1991** [comment]
Hi @yasunori0120,

If you have added IAM User ARN in the application settings, then you will have to add the IAM Policy directly to the User. Please refer to the note below ["Step 6. Register your application"](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-6-register-your-application). 
You dont need to call AssumeRole operation if you have configured IAM User on your application directly.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by abuzuhri** [comment]
> I wrote a Java code for connecting to "https://sellingpartnerapi-na.amazon.com" through SP-API.
> 
> Here is the code. Every time I run the code, I encounter an error saying:
> "errors": [
> {
> "message": "Access to requested resource is denied.",
> "code": "Unauthorized",
> "details": ""
> }
> What should I do with correcting the code? Any comments, suggestions, etc. would be greatly appreciated.
> (Class SPAPI is written in "https://jesseevers.com/spapi-first-application/").
> 
> import com.amazon.SellingPartnerAPIAA.AWSAuthenticationCredentials;
> import com.amazon.SellingPartnerAPIAA.AWSSigV4Signer;
> import com.amazon.SellingPartnerAPIAA.LWAAuthorizationSigner;
> import com.squareup.okhttp.*;
> import com.amazonaws.auth.profile.ProfileCredentialsProvider;
> import com.amazonaws.services.securitytoken.AWSSecurityTokenService;
> import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder;
> import com.amazonaws.services.securitytoken.model.AssumeRoleRequest;
> import com.amazonaws.services.securitytoken.model.AssumeRoleResult;
> import com.amazonaws.services.securitytoken.model.Credentials;
> 
> public class test3 {
> 
> ```
> public static void main(String[] args) {      
> 	try {
> 
>      SPAPI spapi = new SPAPI();
>      
>      // Build a request
> 	 String basePath = "https://sellingpartnerapi-na.amazon.com";  
> 	 String localVarPath = "/orders/v0/orders";
> 	 String url = basePath + localVarPath; 
>     Request request =  new Request.Builder()
>             .url(url)
>             .addHeader("Content-Type", "application/json")
>             .addHeader("user-agent", "My YouTube App 1.0 (Language=csharp;Platform=Windows/10)")
>             .get()
>             .build();
> 
> 	//Login with Amazon
>     request = new LWAAuthorizationSigner(spapi.lwaAuthCreds).sign(request);
>   
>    //Get temporary session token   	 
>     String SESSION_NAME = "assumeRoleTest";
>     // Creating the STS client is part of your trusted code. It has
>     // the security credentials you use to obtain temporary security credentials.
>     AWSSecurityTokenService stsClient = AWSSecurityTokenServiceClientBuilder.standard()
>                                             .withCredentials(new ProfileCredentialsProvider())
>                                             .withRegion(spapi.config.getAwsRegion())
>                                             .build();
>     // Obtain credentials for the IAM role. Note that you cannot assume the role of an AWS root account;
>     // Amazon S3 will deny access. You must use credentials for an IAM user or an IAM role.
>     AssumeRoleRequest roleRequest = new AssumeRoleRequest()
>                                             .withRoleArn(spapi.config.getAwsIAMARN())
>                                             .withRoleSessionName(SESSION_NAME);
>     AssumeRoleResult roleResponse = stsClient.assumeRole(roleRequest);
>     Credentials sessionCredentials = roleResponse.getCredentials();
>    
>     request = request.newBuilder()
> 			.addHeader("x-amz-security-token", sessionCredentials.getSessionToken())
> 			.build();
>     
> 	//Amazon web service
>      AWSAuthenticationCredentials awsAuthCreds2;
>     awsAuthCreds2 = AWSAuthenticationCredentials.builder()
>             .accessKeyId(sessionCredentials.getAccessKeyId())
>             .secretKey(sessionCredentials.getSecretAccessKey())
>             .region(spapi.config.getAwsRegion())
>             .build();
> 
>     request =  new AWSSigV4Signer(awsAuthCreds2).sign(request);
> 
>     OkHttpClient client = new OkHttpClient();
> 	Response resp = client.newCall(request).execute();   
> 	
>     System.out.println("HEADER -> " + resp.headers().toString() + " BODY -> "+ resp.body().string()); 
> 
>     } catch (Exception e) {
>         System.err.println("Error : ");
>         e.printStackTrace();
>     }
> ```
> 
> }
> }

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by abuzuhri** [comment]
Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp
