### ISSUE TITLE
[BUG] mws_auth_token missing in OAuth Redirect URI - Hybrid App

### ISSUE THREAD

**Issue by rohit-forcesight** [amzn/selling-partner-api-docs#611]
I am trying to get seller authorization for both SP-APIs & MWS APIs.
I have created a hybrid application.

![image](https://user-images.githubusercontent.com/73869506/114995269-46460900-9ebb-11eb-9c3a-e9e4af50cbc2.png)

After the seller gives access to the app & when Amazon loads the OAuth Redirect URI into the browser (the first one specified when registered the application), it only adds the state, selling_partner_id, spapi_oauth_code query parameters. The mws_auth_token query parameters is missing.

The documentation says is adds state, selling_partner_id, spapi_oauth_code, mws_auth_token query parameters.
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-amazon-sends-you-the-authorization-information

Why the mws_auth_token query parameters is missing OAuth Redirect URI?

Thanks

**Comment by diegocvazquez** [comment]
@rohit-forcesight 
Hi there, is the seller authorizing the app the owner of the application?

**Comment by rohit-forcesight** [comment]
Hey @diegocvazquez 
No, the seller authorizing the app is not the owner of the application.

**Comment by diegocvazquez** [comment]
> Hey @diegocvazquez
> No, the seller authorizing the app is not the owner of the application.

@rohit-forcesight 
I couldn’t test this because I am using an application that only uses sp-api, as my hybrid app is still being approved, as soon I can test it I will get back to this thread.
Regards
