### ISSUE TITLE
[BUG] Documentation:  CreateFulfillmentOrderRequest doesn't respect marketplaceId

### ISSUE THREAD

**Issue by ericcj** [amzn/selling-partner-api-docs#613]
**Describe the bug**

CreateFulfillmentOrderRequest says you can optionally specify marketplaceId but it has no effect and believes all of my fulfillment orders for a sellerSku that is only present in amazon.ca are coming from the US.  it always returns the error "Value NotEligibleForExport for parameter Item is invalid" even though the address has 'countryCode' => 'CA', I'm specifying a marketplaceId A2EUQ1WTGCTBG2, and i'm specifying a sellerSku and fulfillmentNetworkSku that's only present in our amazon.ca inventory.  i was able to create an identical order from seller central itself without issue. 

**URL of the content on GitHub**

https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md#createfulfillmentorderrequest

**Comment by foxfiring** [comment]
I also encountered this problem on the European site. 
Seriously suspect that the parameter marketplaceId does not work

**Comment by henrybroeker** [comment]
I also have this issue. Creating an order from German Marketplace to German shipment address results in a message saying:
> This order cannot be fulfilled due to Brexit preventing cross-border fulfillment via EFN and Pan-European FBA

**Comment by sujing911** [comment]
this is simple issue,why amazon counldn't repair it

**Comment by henrybroeker** [comment]
I also contacted Amazon directly and informed about this, lets see if that helps

**Comment by ericcj** [comment]
The workaround for this is to provide the field shipFromCountryCode in the request

**Comment by ericcj** [comment]
actually shipFromCountryCode doesn't fix it for me

**Comment by henrybroeker** [comment]
I also tried the shipFromCountryCode field, had no effect for me. Still the old issue.

**Comment by ericcj** [comment]
still an issue
