### ISSUE TITLE
Getting Page Sales and Traffic reports using Reports API

### ISSUE THREAD

**Issue by yiweixia** [amzn/selling-partner-api-docs#614]
If I go to Seller Central, under Reports I can go:

Reports -> Business Reports -> By ASIN ->  Detail Page Sales and Traffic

which takes me to a page where I can download a CSV which details page views by ASIN. I can't seem to find a similar report using the SP API. Please correct me if I'm mistaken, but it seems like the reports offered by the Reports API don't line up with the reports shown on the Seller Central dashboard. 

I've checked a few of the inventory reports/performance reports, but those don't contain the info I'm looking for.

If these reports are currently available via the API, could we document the mapping of SC reports <-> API call better? 
 
If it's not, could you make them available?

**Comment by yiweixia** [comment]
@ShivikaK @rugved1991 Any idea if this is a planned feature? 

We'd like to offer an aggregated dashboard to the brands we work with, and having them manually download these reports from seller central and re-upload to our site for multiple ASINs is a painful process we want to avoid.

**Comment by bigearIsSoNice** [comment]
SP-API doent support  'the detail page sales and traffic report'  ?
SO BAD !

**Comment by tspicer** [comment]
The is a highly requested set of data for sellers and vendors. +1 for it to be added to the API

**Comment by RushaliChanneled** [comment]
Manually downloading these reports every time is not the ideal way. This data should be available via the API

**Comment by HuUncle** [comment]
I also need this report， but don't found right type

**Comment by HuUncle** [comment]
> If I go to Seller Central, under Reports I can go:
> 
> Reports -> Business Reports -> By ASIN -> Detail Page Sales and Traffic
> 
> which takes me to a page where I can download a CSV which details page views by ASIN. I can't seem to find a similar report using the SP API. Please correct me if I'm mistaken, but it seems like the reports offered by the Reports API don't line up with the reports shown on the Seller Central dashboard.
> 
> I've checked a few of the inventory reports/performance reports, but those don't contain the info I'm looking for.
> 
> If these reports are currently available via the API, could we document the mapping of SC reports <-> API call better?
> 
> If it's not, could you make them available?

Have you solved this problem ？

**Comment by PG408** [comment]
The is a highly requested,

**Comment by cccaimingjian** [comment]
+1

**Comment by steven-so** [comment]
@yiweixia @HuUncle 

Has anyone found a way to get this information from the sp-api? 

I'm trying to figure out a way to get sessions, units ordered, sales, and such, by sku for specific dates. Is there any way to do that from the SP-API, or an alternative good solution? Thank you.

**Comment by tspicer** [comment]
@steven-so , at the moment this is not available via the MWS or SP-API. Also, it is not clear exactly where this type of information, if it is released will land. For example, I have seen a trend where this type of business level reporting/metrics are showing up more on the Amazon Ads side of the house.  IMHO, I don't care if it is SP-API, Ads API or some other API but a different team at Amazon, it is important performance level data.

**Comment by steven-so** [comment]
@tspicer  Thanks for your reply. That is unfortunate.

**Comment by fractalakash** [comment]
@yiweixia Any updates whether we can download details sales and traffic data by ASIN via API ?

**Comment by ciocca-dev** [comment]
+1

**Comment by jimmy-ross-xapix** [comment]
+1

**Comment by JeromeXapix** [comment]
+1

**Comment by finnmeier23** [comment]
+1

**Comment by JacobFunnel** [comment]
+1

**Comment by phil-kramer** [comment]
+1

**Comment by Javadebi** [comment]
+1

**Comment by david-mcbacon** [comment]
+1

**Comment by yigal-mish** [comment]
+1

**Comment by cccaimingjian** [comment]
This report looks like coming soon, developer-docs website has "Sales and Traffic Business Report" already.
But I got an error "message": "Access to the resource is forbidden" when I try to get it.
Here is the docs link, if you can get this report , please let us know.
https://developer-docs.amazon.com/sp-api/docs/report-type-values#seller-retail-analytics-reports

**Comment by ShivikaK** [comment]
Hello @cccaimingjian 

Thank you for sharing this concern. The report type is under Brand Analytics role which is also now available for all developers. 

1. Please review your developer profile in Seller Central to select this role. 
2. Then Edit your app to add this role to your application and re-authorize the app. 

Once you complete the two steps, you should be able to make a successful request for this report.

If error persists, please open a support case with us to get additional assistance.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by stefnats** [comment]
Hi @ShivikaK
Thanks for the new report type.
Just want to say thanks for all the effort the Developers have put into this API. I have the feeling that in MWS times there was little effort to make the devs happier, but this turned around.
Yes, the API is a bit difficult to get into and not battlefield tested for years, but I feel like it's getting there.

**Comment by nassuf** [comment]
Hello @ShivikaK 
Thanks for informations !
I unfortunately cant found the "Brand Analytics" role in the europe seller central.

Is there anything to do to get this role ?

**Comment by ShivikaK** [comment]
Hello @nassuf 

Did you review your developer profile here?

1. In the Partner Network menu, click **Develop Apps**.
2. Click the **Your Developer Profile** link.
3. The Brand Analytics role needs to be selected in the profile and the profile needs to be saved.
4. Once the role is added to your profile, you can then edit the app and select the role for the app.
5. Make sure to re-authorize the app after saving the app changes.

Please let me know if issue persists.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by callumb123** [comment]
@ShivikaK 
How long does it normally take to get approval at each stage? 
I updated my developer profile to add the new Brand Analytics role around 11 days ago and haven't had any update (case ID: 7691521102).
I'm just aware if we wait weeks for this approval we might need to wait weeks again when we edit our app.

**Comment by tspicer** [comment]
hey @callumb123 , we just got approved and it took a few weeks. I assume they are backed up.

**Comment by ShotaTakahashiPro** [comment]
Hey guys!
Our developer profile got approved for the Brand Analytics role but the report returns empty data. Could you help me to figure out the issue? Thank you!

// Source Code
...
await sellingPartner.callAPI({
      operation:'createReport',
      body:{
        reportType:'GET_SALES_AND_TRAFFIC_REPORT',
        marketplaceIds:marketplace_ids,
        dataEndTime:'2022-03-31T00:00:00+00:00',
        dataStartTime:'2022-03-01T00:00:00+00:00',
        reportOptions: {dateGranularity:"MONTH", asinGranularity:"CHILD"}
      }
    });
...
let res_reports = await sellingPartner.callAPI({
      operation:'getReports',
      query:{
        reportTypes:'GET_SALES_AND_TRAFFIC_REPORT',
        MarketplaceIds:marketplace_ids,
        dataEndTime:'2022-03-31T00:00:00+00:00',
        dataStartTime:'2022-03-01T00:00:00+00:00',
        reportOptions: {dateGranularity:"MONTH", asinGranularity:"CHILD"}
      }
    });


// Console log
...
[{"reportType":"GET_SALES_AND_TRAFFIC_REPORT","processingEndTime":"2022-04-08T02:13:36+00:00","processingStatus":"DONE","marketplaceIds":["APJ6JRA9NG5V4"],"reportDocumentId":"amzn1.spdoc.1.3.2fb0e3ef-492f-48d4-8094-9f3630750364.T2NZQ8AYL0BMHH.44900","reportId":"177022019090","dataEndTime":"2022-03-31T00:00:00+00:00","createdTime":"2022-04-08T02:13:23+00:00","processingStartTime":"2022-04-08T02:13:27+00:00","dataStartTime":"2022-03-01T00:00:00+00:00"}]
...
[]

**Comment by shirushi-dev** [comment]
from Japan

  [403] {
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]

**Comment by kenyonduan** [comment]
@ShivikaK 

Hi ShivikaK

I saw this sentence in the [document](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api#frequently-asked-questions): _**Note: If you have a published hybrid SP-API application you must relist your application before reauthorization.**_ 

Does this mean that my application needs to be re-approved? and will I be able to access the Sp-API during the approval period?

**Comment by philmccarty** [comment]
I understand that users will need to re-authorize if they authorised the traditional way, but do they also need to re-authorize if this was a hybrid app that they migrated from?

**Comment by PG408** [comment]
> from Japan
> 
> [403] { "errors": [ { "code": "Unauthorized", "message": "Access to the resource is forbidden", "details": "" } ]

Have u solve this problem?

**Comment by shirushi-dev** [comment]
NO... 
I keep getting authentication errors.


> > from Japan
> > [403] { "errors": [ { "code": "Unauthorized", "message": "Access to the resource is forbidden", "details": "" } ]
> 
> Have u solve this problem? @shirushi-dev

**Comment by shirushi-dev** [comment]
@PG408 
NO...
I keep getting authentication errors.

**Comment by PG408** [comment]
We just solve this problem, you can add a new app, and use it call api, remember cleack the brand ✓ for your developer profile and app profile both.

From 减法
________________________________

**Comment by shirushi-dev** [comment]
@PG408 
I found the Brand Analysis section under "Edit App." 
Until now, it was not there.
I ✅ed it. Thanks. I will report back.

**Comment by mrvaita** [comment]
Hello, I have a question about getting Traffic reports. According to the documentation it should be possible to pass multiple marketplaceIds to the request specified as `< string > array` [REF](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference). However, submitting multiple marketplaceIds with struncture `[marketplaceId1, marketplaceId2, ...]` produces the following error:
```
"errors": [                                                                                                                                                                                         
    {                                                                                                                                                                                                 
      "code": "InvalidInput",                                                                                                                                                                         
      "message": "Report rejected for this client. Multiple marketplaces were provided for this report type that can only be applied to one marketplace at a time. Please retry with only one marketplace per request.",                                                                                                                                                                                    
      "details": ""                                                                                                                                                                                   
    }                                                                                                                                                                                                 
  ]
```
This is not mentioned in the reportType [description](https://developer-docs.amazon.com/sp-api/docs/report-type-values). Therefore, I would like to ask whether someone can someone  that it is not possible to submit requests for `GET_SALES_AND_TRAFFIC_REPORT` reports with multiple marketplaceIds.
Thank you very much in advance for your time and help.

**Comment by kingsun-he** [comment]
> We just solve this problem, you can add a new app, and use it call api, remember cleack the brand ✓ for your developer profile and app profile both. From 减法
> […](#)
> ________________________________ From: shirushi-dev ***@***.***> Sent: Tuesday, July 26, 2022 11:59:13 AM To: amzn/selling-partner-api-docs ***@***.***> Cc: PG408 ***@***.***>; Mention ***@***.***> Subject: Re: [amzn/selling-partner-api-docs] Getting Page Sales and Traffic reports using Reports API (#614) @PG408<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPG408&data=05%7C01%7C%7C3b8d519d00554611318408da6ebb345b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637944047553535017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sevdPz0CudLx8FR7DPO8QBbSNLD9j5jVjOr4ScaYuSU%3D&reserved=0> NO... I keep getting authentication errors. — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famzn%2Fselling-partner-api-docs%2Fissues%2F614%23issuecomment-1194969836&data=05%7C01%7C%7C3b8d519d00554611318408da6ebb345b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637944047553535017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t9ImIBUqUeo8Q8p3PN90nsu3TgT%2FpXf2NniV%2BLLDANw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE2FYCRB2FATVE5JCVBHGU3VV5PBDANCNFSM43CIXMCQ&data=05%7C01%7C%7C3b8d519d00554611318408da6ebb345b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637944047553535017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lj1lMilag3sMuPskE09dSsDGurS2DMcO2NYhVptaoJE%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

After half an hour  after I re-authorized, it works. We have to be patient.

**Comment by RestricePlanoax** [comment]
> Hello @cccaimingjian
> 
> Thank you for sharing this concern. The report type is under Brand Analytics role which is also now available for all developers.
> 
> 1. Please review your developer profile in Seller Central to select this role.
> 2. Then Edit your app to add this role to your application and re-authorize the app.
> 
> Once you complete the two steps, you should be able to make a successful request for this report.
> 
> If error persists, please open a support case with us to get additional assistance.
> 
> Thanks, Shivika Khare Selling Partner API Developer Support

@ShivikaK 

Hi @ShivikaK , I am unable to access seller central 
"GET_SALES_AND_TRAFFIC_REPORT" report , because of this error 

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Report type 44900 does not support account ID of type class com.amazon.partner.account.id.VendorGroupId.",
            "details": ""
        }
    ]
}

can you please help here, your help will be very very much appreciated.

**Comment by rugved1991** [comment]
Closing this thread as this report type is now publicly available to use. Please open a new issue using the templates if you have any other questions.

Best,
Rugved
Solutions Architect, SP API

**Comment by ElyeM** [comment]
> kenyonduan

@kenyonduan Have you found an answer to this?

Were you able to use SP-API after adding this role before it was re approved?
