### ISSUE TITLE
Understanding issue for restrictedDataToken for order reports

### ISSUE THREAD

**Issue by bjt1988** [amzn/selling-partner-api-docs#615]
as you say here:
https://github.com/amzn/selling-partner-api-docs/issues/563

specific order report types will need the RDT to get the report document.
actually i can receive for example the "PII DATA REPORT": GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING
without an extra RDT request.

is the case with the RDT after the 30.09.2021?

if yes i have a question how to use it.
actually the documentation of the RDT: 
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#restricted-operations
will not show me what i have to post to /tokens/2021-03-01/restrictedDataToken to receive an restrictedDataToken for an restricted Report Type.
if i request a report with the type: GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING after the 30.09.2021. what will happen? is the report reuqest working and the report will be processed and only for the document download i need the RDT?

**Comment by diegocvazquez** [comment]
@bjt1988 
Same question here, did you get any input on this?

thanks!

**Comment by bjt1988** [comment]
no, actually not. i am also still wait for a reply here. also with google i can not find any new informations.

**Comment by diegocvazquez** [comment]
@bjt1988 
> no, actually not. i am also still wait for a reply here. also with google i can not find any new informations.

Hi, tried to implement the RDT. I am using STS (role) but when make a call using the RDT in the x-amz-access-token I dont get any PII information, If I make the call using the LWA token in x-amz-access-token I get the PII information.

**Comment by bjt1988** [comment]
actually in my case i dont need the RDT request.
e.g. the report type: GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING is working without RDP before.
thats why i was writing "understanding issue".
i can not help you with the RDT request because i never did it.

in my case the amazon merchant give full rights for our sp-api app and our iamarn. after that we get access_token and refresh_token from https://api.amazon.com/auth/o2/token 
with this token actually we can request a report with PII Data e.g. GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING

but i think when i read this: https://github.com/amzn/selling-partner-api-docs/issues/563
this will also not work after 30.09.2021 and i also need an RDT request

**Comment by diegocvazquez** [comment]
@bjt1988 
I have created a case  https://github.com/amzn/selling-partner-api-docs/issues/671, I can also make a request without the RDT and works, the problem, is that I need to test it before it goes in production, I cannot imagine that we will all have to make a deploy on spetember 30th, we will see. 
Thanks for taking the time to answer

**Comment by AbePerl1** [comment]
Hello.
I am attempting to schedule a GET_ORDER_REPORT_DATA_INVOICING, but since it is in the restricted zone it requires an RDT.
For orders, I can perfectly fetch as Token, however on the reports it keep on throwing an error  {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid or unsupported document ID found",
      "details": ""
    }
  ]
}

The documentation does not show a proper sample on how to get or schedule the restricted reports
Any help is appreciated

**Comment by satishviswanathan** [comment]
Did anyone get it working. I'm also looking for the same.

**Comment by AbePerl1** [comment]
> Did anyone get it working. I'm also looking for the same.

Yes, no need to call RDT for order reports
