### ISSUE TITLE
[BUG] Migrating authorization from Amazon Marketplace Web Service Documentation - 404 Not Found

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#616]
I am trying to migrate my current MWS authorisations to the hybrid SP-API as documented here:
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-as-a-developer

However the link (in bold below) to the process gives a HTTP 404 not found

Migrating authorization from Amazon Marketplace Web Service
If a selling partner has authorized you to make calls to Amazon Marketplace Web Service on their behalf, you can use the Authorization API to migrate that authorization to a hybrid Selling Partner API application. This eliminates the need to request authorization from the selling partner again. For more information, **see the Authorization API Use Case Guide**.

**Comment by rugved1991** [comment]
Hi @nrogers805,

Thanks for bringing this to our attention. I have reached out to our documentation team to update the path of the link. Please refer to this [Authorization Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md) for more information. 

Thanks,
Rugved
Solutions Architect, SP API
