### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#617]
The README.nd at https://github.com/amzn/selling-partner-api-models

states:
This repository contains Swagger models for developers to use to create software to call Selling Partner APIs. Developers can use swagger codegen to generate client libraries from these models. Please refer to selling-partner-api-docs for additional documentation and read the **Selling Partner Api Developer Guide** for instructions to get started.

But the link in bold gives 404 Not Found

**Comment by rugved1991** [comment]
Hi @nrogers805,

Thanks for bringing this to our attention. I have reached out to the documentation team to update the link of the seller developer guide in the models repository.

Thanks,
Rugved
Solutions Architect, SP API
