### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#618]
SP-API Documentation missing

The README.nd at https://github.com/amzn/selling-partner-api-models

states:
The clients directory contains a Java library and a C# library with mustache templates for use with swagger-codegen to generate client libraries with authentication and authorization functionality included. The templates are located in resources/swagger-codegen.

However, the clients directory does not contain any templates and also does not have a directory resources/swagger-codegen

Where can I find these?

**Comment by jason1004** [comment]
https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates

**Comment by nrogers805** [comment]
> https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates

Thank you jason1004

Are there any more instructions on how to extract these? I tried a few swagger commands as shown for the json templates but not sure how to use these moustache templates

**Comment by abuzuhri** [comment]
> > https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates
> 
> Thank you jason1004
> 
> Are there any more instructions on how to extract these? I tried a few swagger commands as shown for the json templates but not sure how to use these moustache templates

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp
