### ISSUE TITLE
[BUG] /sales/v1/orderMetrics

### ISSUE THREAD

**Issue by dolphin-w** [amzn/selling-partner-api-docs#621]
response code. 500
```
        String interval = "2021-01-01T00:00:00-07:00--2021-04-04T00:00:00-07:00";
        String granularity = "Total";
        String granularityTimeZone = null;
        String buyerType = null;
        String fulfillmentNetwork = null;
        String firstDayOfWeek = null;
        String asin = null;
        String sku = null;
        GetOrderMetricsResponse response = salesApi.getOrderMetrics(marketplaceIds, interval, granularity, granularityTimeZone, buyerType, fulfillmentNetwork, firstDayOfWeek, asin, sku);
com.amazon.spapi.client.ApiException: Internal Server Error
	at com.amazon.spapi.client.ApiClient.handleResponse(ApiClient.java:955)
	at com.amazon.spapi.client.ApiClient.execute(ApiClient.java:869)
	at com.amazon.spapi.api.SalesApi.getOrderMetricsWithHttpInfo(SalesApi.java:188)
	at com.amazon.spapi.api.SalesApi.getOrderMetrics(SalesApi.java:166)
	at com.amazon.spapi.api.SalesApiTest.getOrderMetricsTest(SalesApiTest.java:90
```

**Comment by ianrussel** [comment]
Same issue here. Did you resolve it ?

**Comment by dolphin-w** [comment]
> 同样的问题在这里。您解决了吗？

no， now this is
`2021-01-01T00:00:00.000Z--2021-02-01T00:00:00.000Z
com.amazon.spapi.client.ApiException: Bad Request
400{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "{getOrderMetrics.arg3[0].id\u003dmust match \"(all|A[0-9A-Z]{1,20})\"}",
      "details": ""
    }
  ]
}`

**Comment by dolphin-w** [comment]
```
List<String> marketplaceIds = 
        Arrays.asList("A1RKKUPIHCS9HS","A1F83G8C2ARO7P","A13V1IB3VIYZZH","A1805IZSGTT6HS",
                "A1PA6795UKMFR9","APJ6JRA9NG5V4");
        String interval = "2021-01-01T00:00:00.000Z--2021-02-01T00:00:00.000Z";
        String granularity = "Total";
        String granularityTimeZone = null;
        String buyerType = null;
        String fulfillmentNetwork = null;
        String firstDayOfWeek = null;
        String asin = null;
        String sku = null;
        GetOrderMetricsResponse response = null;
        try {
            response = salesApi.getOrderMetrics(marketplaceIds, interval, granularity, granularityTimeZone, buyerType, fulfillmentNetwork, firstDayOfWeek, asin, sku);
            response.getPayload().get(0);
        } catch (ApiException e) {
            e.printStackTrace();
            System.out.println(e.getCode() +""+ e.getResponseBody()+""+ e.getResponseHeaders());
        }
com.amazon.spapi.client.ApiException: Bad Request
400{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "{getOrderMetrics.arg3[0].id\u003dmust match \"(all|A[0-9A-Z]{1,20})\"}",
      "details": ""
    }
  ]
}
```

**Comment by dolphin-w** [comment]
@rugved1991   Hello! Can this problem be solved?

**Comment by ianrussel** [comment]
Try 
 Arrays.asList("A1F83G8C2ARO7P");

The docs is confusing. It says marketplaceId accepts multiple as array. But it turns out it will only accept single value in an array

**Comment by jimmy-ross-xapix** [comment]
> Try
> Arrays.asList("A1F83G8C2ARO7P");
> 
> The docs is confusing. It says marketplaceId accepts multiple as array. But it turns out it will only accept single value in an array

i also noticed this problem with the Orders Endpoint: requesting with 1 marketplaceID works, but as soon as i add a 2nd to the array it doesnt. I raised this bug about it but didnt hear anything: https://github.com/amzn/selling-partner-api-docs/issues/756

The Sales > getordermetrics endpoint doesnt work for me at all, I just get an "invalid input" error message and summarized that here:  https://github.com/amzn/selling-partner-api-docs/issues/737

I was assuming it might not be available in Europe yet - have any of you been able to retrieve results from getOrderMetrics?


 {
      "body": {
        "errors": [
          {
            "message": "We encountered an internal error. Please try again.",
            "details": "",
            "code": "InternalFailure"
          }
        ]
      },

**Comment by ianrussel** [comment]
I think the interval date format is not accepted by amazon

**Comment by ianrussel** [comment]
Try this and see if it works

                 'buyerType' => 'All',
                 'granularity' => 'Total',
                 'interval' => '2021-05-03T22:00:00+00:00--2021-05-19T21:59:59+00:00',
                 'marketplaceIds' => 'A1PA6795UKMFR9',

**Comment by ianrussel** [comment]
` I was assuming it might not be available in Europe yet - have any of you been able to retrieve results from getOrderMetrics?` Yes I am able to get orders in Eu region

**Comment by jimmy-ross-xapix** [comment]
> I think the interval date format is not accepted by amazon

thanks so much for the tip, it works now :)

**Comment by dolphin-w** [comment]
Yes, I can get it by filling in a marketplace parameter,but not multiple marketplaces

**Comment by dolphin-w** [comment]
```
        List<String> marketplaceIds = Arrays.asList("A1RKKUPIHCS9HS","A1F83G8C2ARO7P","A13V1IB3VIYZZH","A1805IZSGTT6HS",
                "A1PA6795UKMFR9","APJ6JRA9NG5V4");
        String granularity = "Day";
        String granularityTimeZone = "UTC";
        String buyerType = null;
        String fulfillmentNetwork = null;
        String firstDayOfWeek = null;
        String asin = null;
        String sku = null;
        GetOrderMetricsResponse response = null;
        int count = 0;
        try {
            for (String s : marketplaceIds) {
                List<String> market = Arrays.asList(s);
                response = salesApi.getOrderMetrics(market, interval, granularity, granularityTimeZone, buyerType, fulfillmentNetwork, firstDayOfWeek, asin, sku);
                System.out.println(response.getPayload());
            }
        } catch (ApiException e) {
            e.printStackTrace();
            System.out.println(e.getCode() + "" + e.getMessage() + "");
        }

```
