### ISSUE TITLE
Invalid scope response when trying to migrate user using the AuthorisationApi

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#622]
Parameters sent:

{"grant_type":"client_credentials","refresh_token":null,"client_id":"amzn1.application-oa2-client.**","client_secret":"**","scope":"SCOPE_MIGRATION_API"}

Error Response
{"error_description":"The request has an invalid parameter : scope","error":"invalid_scope"}

Any ideas what I am doing wrong here ?

**Comment by rugved1991** [comment]
Hi @nrogers805,

Please make sure you are calling the Authorization API on a hybrid application which is published. Also, the scope value should be "sellingpartnerapi::migration" instead. The scope value you provided "SCOPE_MIGRATION_API" is used while using the Java Auth&Auth client library.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by nrogers805** [comment]
Hi @rugved1991 

The documentation should be clear then as this has wasted so much time

Thanks

**Comment by ezpinsky** [comment]
@jenilew this has also wasted a lot of time for me... Can you please make an internal ticket to add this to the API? API Docs should be global and not just directing us to the Java Library
