### ISSUE TITLE
@rajat-garg,  There are lots of questions here going unanswered.

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#624]
Hi @rajat-garg,

There are lots of questions here going unanswered.

We have been given until Sept 30th to get all of our apps SP-API compliant yet there are so many gaps in the API and the documentation and the c# components/SDK are lacking in process as well as documentation. 

How do we get full support for the this?

Thanks

**Comment by rajat-garg** [comment]
Hi @nrogers805 ,

Yes, I am also waiting for the replies. The documentation and support is not that promising. Don't know how we will get full support for this.
