### ISSUE TITLE
Website Workflow - Not Getting Response from Amazon

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#625]
How do I change the redirect url for the website workflow process as described here:

https://github.com/amzn/selling-partner-api-docs/issues?page=9&q=is%3Aissue+is%3Aopen

**Comment by rugved1991** [comment]
Hi @nrogers805,

Please refer to issue #270 for more information on redirect_url usage. If you have any other questions, feel free to reach out.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by nrogers805** [comment]
Hi @rugved1991 

I have tried the link mentioned in #270 but I am still not getting a redirection

Link used:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.34602ec6-8f08-4829-a96b-a99c9c5688e3&state=stateexample&version=beta&redirect_uri=https://app.sellertoolkit.co.uk/

Also, I cannot see any documentation that refers to the redirect_uri pameter

Thanks

**Comment by lily-PHP** [comment]
Hi @rugved1991

I also use the Website Workflow for authorizing my Selling Partner API applications and got the same problem. 
no matter how many times the seller click the 'Confirm' button or 'Cancel' button on the consent page, amazon never return to my redirect uri, and no error message showed, no success message showed, not any further action from that page. 
How can we fix this problem?

Hope you can help soon. 
Thanks, 
Lily

**Comment by AmichayMiara** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/534 help me to solve the issue with confirm button do nothing - just edit app and fill in the OAuth Login URI (I enter the redirect URI again, no docs about this field).

**Comment by rugved1991** [comment]
Hi @nrogers805 and @lily-PHP,

You will have to add the Redirect URLs on your application first using "Edit App" option. You can only use the redirect URLs that are configured on your application. 

Thanks, 
Rugved
Solutions Architect, SP API

**Comment by nrogers805** [comment]
Hi @rugved1991

We seem to be going around in circles here. 

How can I edit the application, its in review status and there does not seem to be a way of doing this.

This whole process is really cumbersome and not well thought out

Thanks

**Comment by rugved1991** [comment]
Hi @nrogers805,

Your application is currently under review in the app publish process. Once the app is published, you will be able to edit the application once again. Currently, you dont have any Login or Redirect URLs configured on your application. You wont be able to implement the OAuth flow as the application wont know where to redirect to.
You can still test the APIs with self-authorization. Once the app is published, feel free to edit the app again to add the URLs and then use the "version=beta" parameter in OAuth URL. 
You only need to publish the app when you want to list your app on the Appstore. 

Thanks,
Rugved
Solutions Architect, SP API

**Comment by magik092** [comment]
Hi @rugved1991,

We also have problem with redirect URL. In our hybrid SP & MWS API (app is Published) we fill OAuth Redirect URI but in Website workflow (even if we add redirect_url to URL), client isn't redirecting to our website - after last Seller Central authorization confirmation page he is redirecting to his authorization list page in SC.
Our appId=amzn1.sellerapps.app.a9ade8ec-4b5e-45e8-9ac2-75cb3e3f99ab

Thanks,
Lukas.

**Comment by mikmar-jj** [comment]
Any updates on this?
I'm a bit confused with the `redurect_uri` field mentioned [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-the-selling-partner-initiates-authorization-from-your-website). I need to pass custom redirect uri for each marketplace seller approves, but it only redirects to the one mentioned in app. So I'm not able to pass custom redirect uri? Am I getting this right? In help folks?
