### ISSUE TITLE
Get products list by query (listCatalogItems)

### ISSUE THREAD

**Issue by ouroboros25** [amzn/selling-partner-api-docs#626]
Hello,
I have a problem with listCatalogItems. It always returns an empty list with OK 200 status. 
   
   It's my request:  
       <img width="391" alt="Screenshot at Apr 19 17-39-13" src="https://user-images.githubusercontent.com/54668967/115267125-7d2d5080-a141-11eb-804c-930959ed179a.png">
       
       

   My response:
       
<img width="334" alt="Screenshot at Apr 19 19-05-25" src="https://user-images.githubusercontent.com/54668967/115267810-47d53280-a142-11eb-80db-98ea5347bb92.png">

Result is: status 200 and empty **items** array.     

The same function getCatalogItem($marketplace_id, $asin) works well and returns product data, so a connection with servers and settings are ok.
   <img width="451" alt="Screenshot at Apr 19 19-01-45" src="https://user-images.githubusercontent.com/54668967/115267318-b796ed80-a141-11eb-9460-5d2361c1bec1.png">
   
I use clousale/amazon-sp-api-php library for PHP. Here is my code:

  
    
`

        $accessToken = \ClouSale\AmazonSellingPartnerAPI\SellingPartnerOAuth::getAccessTokenFromRefreshToken(
            $options['refresh_token'],
            $options['client_id'],
            $options['client_secret']
        );
        $config = \ClouSale\AmazonSellingPartnerAPI\Configuration::getDefaultConfiguration();
        $config->setHost($options['endpoint']);
        $config->setAccessToken($accessToken);
        $config->setAccessKey($options['access_key']);
        $config->setSecretKey($options['secret_key']);
        $config->setRegion($options['region']);
        $apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\CatalogApi($config);

        $apiReportInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\ReportsApi($config);
        $marketplace_id = 'ATVPDKIKX0DER';

        $result =  $apiInstance->listCatalogItems($marketplace_id, "book");
        dd($result->getPayload());`
       
       

   Why I always get an empty array?  Help me please.

**Comment by tabertantrum** [comment]
@ouroboros25 I believe this issue is with your library.

I am receiving responses from the listCatalogItems endpoint with `MarketplaceId: ATVPDKIKX0DER` and `Query: "book"`.

**Comment by ouroboros25** [comment]
@tabertantrum  Hello! Thank you for your response. 
  Can you show your listCatalogItems code? Or request? It will help me to find a problem.

**Comment by ouroboros25** [comment]
@tabertantrum I also thought that problem is with the library, but the request seems correct, isn't it?

**Comment by tabertantrum** [comment]
@ouroboros25 the request seems correct to me. This is the query sent from our app:
`"/catalog/v0/items?MarketplaceId=ATVPDKIKX0DER&Query=book"`

And here's a snip of the response:
![Screen Shot 2021-04-20 at 9 16 34 AM](https://user-images.githubusercontent.com/21324669/115411469-1c415f00-a1b9-11eb-993d-43b312d3887b.png)
The first result in the response is for a downloadable movie: The Book of Eli

**Comment by ouroboros25** [comment]
@tabertantrum Thank you! I think I found a problem, it was a library issue. But I always get only 10 items in the payload array. Do you know how to change this limit? 
<img width="282" alt="Screenshot at Apr 21 11-58-39" src="https://user-images.githubusercontent.com/54668967/115526684-f7241d80-a298-11eb-9716-b0dc8866b77d.png">

**Comment by tabertantrum** [comment]
Documentation doesn't mention the response only returning the first 10 results, or whether that limit can be changed, which definitely should be updated in my opinion. There is also no method to request the next page of results, which one would expect in the response for a query request such as this.

@ShivikaK @parvathm the relevant section in this question is here:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#get-catalogv0items

**Comment by ouroboros25** [comment]
@tabertantrum So your API code also returns only 10 items? I didn't find a way how to get other items.

**Comment by chapmanjw** [comment]
Hello @ouroboros25 and @tabertantrum. The `v0` `listCatalogItems` operation was ported from the MWS Products API `ListMatchingProducts` operation. That operation has a max results size of 10. 

From http://docs.developer.amazonservices.com/en_US/products/Products_ListMatchingProducts.html:

`This operation returns a maximum of ten products and does not return non-buyable products.`

**Comment by aidensgithub** [comment]
> @tabertantrum Thank you! I think I found a problem, it was a library issue. But I always get only 10 items in the payload array. Do you know how to change this limit?
> <img alt="Screenshot at Apr 21 11-58-39" width="282" src="https://user-images.githubusercontent.com/54668967/115526684-f7241d80-a298-11eb-9716-b0dc8866b77d.png">

ouroboros25  Can you provide us with the solution that worked for this particular problem? Cos' I'm receiving empty payloads with status 200.

**Comment by chapmanjw** [comment]
@aidensgithub The 2020-12-01 version of the searchCatalogItems operation now returns more results than the previous listCatalogItems v0 operation did: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md.
