### ISSUE TITLE
No Response when requesting approval for PPI API Roles

### ISSUE THREAD

**Issue by ben-tdm** [amzn/selling-partner-api-docs#627]
We have requested access to the Direct-to-Consumer Shipping role in our SP-API Developer Profile but haven't heard anything in over a month. Our account is blocked for further development until we have a resolution. 

Who can we contact at Amazon to complete this review? Are cases currently being reviewed?

**Comment by ShivikaK** [comment]
Hello,

Thank you for raising this issue.

Please provide the Amazon Support case ID opened for this access request and I will look into expediting the case for resolution.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jchavest13** [comment]
Hi @ben-tdm,

Please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by ben-tdm** [comment]
Thank you! @jchavest13 @ShivikaK 

Support Case ID for requesting PPI APIs 8121873971

Case ID for our Developer Registration 7556094211

Do you need anything else?

**Comment by jchavest13** [comment]
Hi @ben-tdm ,

Your case is currently pending review. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by ben-tdm** [comment]
Thanks @jchavest13 but the case has been pending review for over a month. Can @ShivikaK expedite it?

**Comment by jchavest13** [comment]
Hi @ben-tdm ,

Upon review, I could confirm you provided the information requested through your ongoing Developer Registration case 8121873971 a couple of days ago. Please allow us sometime to evaluate your request and determine its outcome.

Regards,
Julian
Developer Registration Specialist, SP-API
