### ISSUE TITLE
Please check on our Developer Account being made into a Hybrid MWS/SP-API

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#628]
Can we get an update on our account being made a Hybrid (already using MWS)?  This is hindering development for the SP-API functionality.  Thank you!!!

Case#8109560011

**Comment by rugved1991** [comment]
Hi @hrhearn7,

Thanks for sharing the case ID. I have reached out to the team and they have informed me that they would review your response and get back to you on the support case. Please continue to monitor the support case for updates.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by hrhearn7** [comment]
Thank you for the quick response!

**Comment by hrhearn7** [comment]
Any updates on our account being approved as a Hybrid?  I am sorry to be a pest but we are wanting to go live with the FBA inbound API's by July (new process in several warehouses). And cannot move forward until we get past the authentication piece.

**Comment by jchavest13** [comment]
Hi @hrhearn7 ,

Your case is currently pending review. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
