### ISSUE TITLE
LWA For New Seller

### ISSUE THREAD

**Issue by jatinthapar1910** [amzn/selling-partner-api-docs#629]
I have a SaaS application using SP API and I want Amazon Sellers (my customers) to authorize their account to use the application. 
Going through documentation I saw a way for existing sellers to migrate to Seller Cloud but there is no documentation for new sellers. 

Please share the details for getting new sellers on onboard and preferably please share postman collection for this.

**Comment by rugved1991** [comment]
Hi @jatinthapar1910,

Please refer to the Seller Developer Guide for more information on authorization information. You can refer to the "[Website workflow](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#website-workflow)" section within the developer guide on how to receive OAuth tokens from the seller and call the new SP APIs.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by jatinthapar1910** [comment]
Hi @rugved1991 
I have been following the document with this https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.application-oa2-client.65ff80153a3a4ee38da39d1c165fcca9&version=beta and unfortunatelt this throws an error. 

https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.application-oa2-client.65ff80153a3a4ee38da39d1c165fcca9&version=beta
Something went wrong
Unable to find application.

Please contact Seller Support and provide them with the following information:

```
App ID: amzn1.application-oa2-client.65ff80153a3a4ee38da39d1c165fcca9
Error Code: MD1000
```

**Comment by rugved1991** [comment]
Hi @jatinthapar1910,

Thanks for sharing the OAuth URL. You are using clientID in the OAuth URL instead of Application ID. Please replace the application_id value with the app id. It should be in the following format:
"amzn1.sp.solution.some-value" or "amzn1.sellerapps.app.some-value".

Thanks,
Rugved
Solutions Architect, SP API

**Comment by jatinthapar1910** [comment]
This works for me.

**Comment by jatinthapar1910** [comment]
Thanks for looking into this.
