### ISSUE TITLE
Awesome SPAPI (Selling Partner API)

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#632]
Recently added helpful resources for SP-API. Hope it can help developers. 

https://github.com/vikingcodes/awesome-spapi

Request to all developer to add more resources. 

Thanks

**Comment by BoyOhu** [comment]
hi,
I have about SPAPI two questions  ：

If I register an application. SPA, on Amazon UK site, can sellers in other regions authorize this application?

Can I use the same aws account to get IAM ARN if I Create different SPA applications on different developer account ?

Looking forward to your reply
@vikingcodes

**Comment by vikingcodes** [comment]
If I register an application. SPA, on Amazon UK site, can sellers in other regions authorize this application?

Ans. Yes. One application can have different deveoper Ids. But **Access key ID** and "Secret access key" will be same for all regions. You just need to change endpoint and developer Id.

FYI: App depend on IAM credentials and IAM is global for all regions. 

Can I use the same aws account to get IAM ARN if I Create different SPA applications on different developer account ?
Ans. Not sure, But not suggested. You will make mesh.
