### ISSUE TITLE
[BUG] Vendor API Documentation

### ISSUE THREAD

**Issue by yiweixia** [amzn/selling-partner-api-docs#634]
The provided documentation only covers the seller side of the SPAPI, not the vendor side, and it seems like the vendor API is completely different. For example, for orders, the seller endpoint is `/orders/v0/orders`, but the vendor endpoint is `/vendor/orders/v1/purchaseOrders`. This isn't covered anywhere in the references section of the documentation. The only reason I was able to find the vendor orders endpoint was because it was used as an example in "SellingPartnerApiDeveloperGuideForVendors", which doesn't include any more vendor endpoints.

The references section should also include documentation for all the operations available to vendors.

**Comment by RoFuLo** [comment]
You can download the vendor documentation on the Vendor Central webpage, inside the "integration" menu.

![image](https://user-images.githubusercontent.com/1555912/115577920-1afd5880-a2c5-11eb-9c96-94b20ba64bf7.png)

**Comment by yiweixia** [comment]
Is there any way to access these docs without a Vendor Central account? We have a Seller Central account, and we can't create a Vendor Central account without an invite, and VC developer accounts don't exist. Asking one of our partners who integrate with our app to download the API for us periodically seems like such an unnecessary hurdle.

**Comment by tomhirschfeld** [comment]
@RoFuLo you can only see that documentation if you have a vendor central developer account, and none of our vendor partners have a developer account so we are blocked here. If you can compile the docs into either an HTML folder or a PDF file and send to me I will venmo/paypal/cashapp/mail you $50

**Comment by ShivikaK** [comment]
Hello @yiweixia 

Thank you for your interest in Vendor APIs.

We are finalizing features to enable third party developers to directly support developers and preparing documentation accordingly. We plan to post updates to our developer guide and API materials for Vendor use cases in the coming weeks.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by charliecode** [comment]
Looking forward to these updates for sure!
