### ISSUE TITLE
How to complete the third-party authorization of the website workflow 

### ISSUE THREAD

**Issue by wmh49877** [amzn/selling-partner-api-docs#635]
hello,I have completed steps 0 to 3, about[ Step 4: Your application exchanges the LWA authorization code for a LWA refresh token.](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#Step-4-Your-application-exchanges-the-LWA-authorization-code-for-a-LWA-refresh-token) 
I don’t understand what it means. 
After step 3 ,I got acesstoken through httprequest
```
         String url = "https://api.amazon.com/auth/o2/token";
         String param = "grant_type=authorization_code&code=" + fbParam.get("spapi_oauth_code") + "&redirect_uri=" +
                 REDIRECT_URL + "&client_id=" + getLwaClientId + "&client_secret=" + getLwaClientSecret;
         String result = HttpClientUtils.sendPostRequest(url, param);
```
But step 4 requires Add the Login with Amazon SDK for JavaScript, To exchange an LWA authorization code for an LWA refresh token.
I don't know what to do

**Comment by BoyOhu** [comment]
文档的意思：你可以两种方式获授权而已，
![image](https://user-images.githubusercontent.com/34674867/115662452-9288c180-a371-11eb-9759-b7b0c614b98f.png)，要么用他官方提供的sdk，要么自己通过授权码授权后获取，你现在的这种就是自己通过授权码已经授权了，你可以在卖家后台里的管理程序里看到已经授权了，那个程序刷新token的话参考这个：https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#connecting-to-the-selling-partner-api，把参数替换，就能获取refresh_token。

**Comment by wmh49877** [comment]
> 文档的意思：你可以两种方式获授权而已，
> ![image](https://user-images.githubusercontent.com/34674867/115662452-9288c180-a371-11eb-9759-b7b0c614b98f.png)，要么用他官方提供的sdk，要么自己通过授权码授权后获取，你现在的这种就是自己通过授权码已经授权了，你可以在卖家后台里的管理程序里看到已经授权了，那个程序刷新token的话参考这个：[https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#connecting-to-the-selling-partner-api，把参数替换，就能获取refresh_token。](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#connecting-to-the-selling-partner-api%EF%BC%8C%E6%8A%8A%E5%8F%82%E6%95%B0%E6%9B%BF%E6%8D%A2%EF%BC%8C%E5%B0%B1%E8%83%BD%E8%8E%B7%E5%8F%96refresh_token%E3%80%82)

感谢,我再研究一下 ,,文档把所有的都写一起了我就比较懵逼.

**Comment by BoyOhu** [comment]
是的，看文档也有的地方很懵，我现在都有一些疑问。真希望国内开发人员可以组件一个关于这方面得交流群。

**Comment by ianrussel** [comment]
I think its better to use language people mostly understand. If I write answer in hindu or arabic it will only helpful to people who know how to speak arabic or hindu. :)

**Comment by wmh49877** [comment]
> I think its better to use language people mostly understand. If I write answer in hindu or arabic it will only helpful to people who know how to speak arabic or hindu. :)

sorry BobOhu is mean  
Either use the SDK officially provided by him, or obtain it after authorization through the authorization code. What you have now is that you have been authorized through the authorization code. You can see that you have been authorized in the management program in the seller's backend, and the program refreshes. Refer to this for token: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#connecting-to-the-selling-partner -api, replace the parameters to get refresh_token. 


Even so, I still feel that the official documents are not detailed enough and confusing

**Comment by TKwheat** [comment]
Sorry, may I know how you solved it in the end?
