### ISSUE TITLE
Access to requested resource is denied when trying to subscribe to MFN_ORDER_STATUS_CHANGE

### ISSUE THREAD

**Issue by preoteasa** [amzn/selling-partner-api-docs#638]
When trying to subscribe to notification MFN_ORDER_STATUS_CHANGE I get the error:

{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}

Using the same credentials and SQS I can subscribe to notifications REPORT_PROCESSING_FINISHED and FBA_OUTBOUND_SHIPMENT_STATUS.

This error happens when using our EU selling account. I can subscribe to MFN_ORDER_STATUS_CHANGE using our US selling account. Any help would be highly appreciated.

**Comment by diegocvazquez** [comment]
@preoteasa 
Hi there, same issue here did you make any progrees in this issue?

**Comment by chrisptang** [comment]
The documentation says this notification is not publicly available.
> This notification type is invitation-only and not publicly available.

Hope this help.
Actually we are looking for this notification service in India too.
