### ISSUE TITLE
How to deal with a published app listing with a error IAM ARN.

### ISSUE THREAD

**Issue by vekincheng** [amzn/selling-partner-api-docs#640]
We have published a app listing before,but when we try to test the sa-api,we found that we have made a mistake with the IAM ARN.We used the user ARN,but the role ARN is the right one.But the IAM ARN can not be changed,so we need a way to fix this issue and continue the development.The only way is we need to publish another app listing?But how to deal with the one has been released?

**Comment by rugved1991** [comment]
Hi @vekincheng,

You can attach the "execute-api"  IAM policy directly to the IAM User. This would allow you to use IAM User credentials to calculate the AWS Signature and make calls to the API. You do not need to AssumeRole if you have configured an IAM User on your application.
Please refer to the "Important" section [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-application).

Thanks,
Rugved
Solutions Architect, SP API

**Comment by vekincheng** [comment]
@rugved1991 Thanks for your reply.I think it's a good way to fix this issue.And it works for self-authorizition,I will try other seller account after my app published.

**Comment by rugved1991** [comment]
Hi @vekincheng,

You can work with a few sellers by sharing the OAuth URL with "version=beta" parameter. You do not need to wait for app publish to test APIs with your sellers.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by vekincheng** [comment]
Hi @rugved1991 ,
Yes,you are right.We can get orders with other seller merchant.But it seems some method can not accessed like reports,Is that because the beta version?

Thanks & Regards.
Vekin
