### ISSUE TITLE
Orders Documentation

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#643]
Hi . Is there any way of just getting the total count for orders ? For total count I mean the sum of all orders . Currently the api returns only records with limit default to 100.

**Comment by PrashantMalaviya** [comment]
hello @ianrussel 
can you this type of error 
@@@@@@@@@@@@@@@@
403
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by ianrussel** [comment]
What endpoint ?

**Comment by PrashantMalaviya** [comment]
this is my code 


from aws_requests_auth.aws_auth import AWSRequestsAuth
import requests
import boto3
from time import sleep
header = {
"Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
}
d = {
"grant_type": "client_credentials",
"scope": "sellingpartnerapi::notifications",
"refresh_token": xxxx,
"client_id":xxxx,
"client_secret": xxxx,
}

response = requests.post("https://api.amazon.com/auth/o2/token", headers=header, data=d)
print(response.status_code)
data = response.json()
access_token = data['access_token']
print("access_token:-"access_token)
##############################################
sleep(2)
amw_client = boto3.client(
'sts',
aws_access_key_id=xxxx,
aws_secret_access_key=xxxx,
)

response = amw_client.assume_role(
RoleArn='xxxx',
RoleSessionName='SellingPartnerAPI'
)
AccessKeyId = response['Credentials']['AccessKeyId']
SecretAccessKey = response['Credentials']['SecretAccessKey']
SessionToken = response['Credentials']['SessionToken']
print("AccessKeyId:-",response['Credentials']['AccessKeyId'])
print("SecretAccessKey:-",response['Credentials']['SecretAccessKey'])
print("SessionToken:-",response['Credentials']['SessionToken'])
##############################################################################
sleep(2)
auth = AWSRequestsAuth(aws_access_key=AccessKeyId,
aws_secret_access_key=SecretAccessKey,
aws_token=SessionToken,
aws_host='sellingpartnerapi-eu.amazon.com',
aws_region='eu-west-1',
aws_service='execute-api')

endpoint = 'https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A21TJRUUN4KGV&CreatedAfter=2021-01-05'

headers = {'x-amz-access-token': access_token}

r = requests.get(endpoint, auth=auth, headers=headers)
print(r.status_code)
print(r.text)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
optput is :-
200
access_token:-xxxx

AccessKeyId:- xxxx
SecretAccessKey:- xxxx
SessionToken:- xxxx
403
{
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}

**Comment by ianrussel** [comment]
Hi @PrashantMalaviya , the first thing you investigate is to make sure your ARN should have the permissions, see screenshot. So for example if your Role has Selling Partner Insights unchecked, even if you are using the correct credentials, you will not be authorized to access the /orders endpoint, hence 403 access to requested resource is denied. If you have all those permission then the next to investigate is your credentials and code. Just let me know.
![insight](https://user-images.githubusercontent.com/4607692/115820686-f07ddd80-a433-11eb-8810-8309ac5d2560.png)

**Comment by PrashantMalaviya** [comment]
yes...all permissions are allow in ARN

**Comment by PrashantMalaviya** [comment]
but what is the "scope": "sellingpartnerapi::notifications" in orders ???
this error:-
{"error_description":"The request has an invalid parameter : scope","error":"invalid_scope"}

**Comment by webinsect-rishabh** [comment]
> but what is the "scope": "sellingpartnerapi::notifications" in orders ???
> this error:-
> {"error_description":"The request has an invalid parameter : scope","error":"invalid_scope"}

I think you are trying to call grantless operations. Use "Content-Type": "application/json" and you dont need to pass refresh token in grantless operations.

**Comment by PrashantMalaviya** [comment]
hello @webinsect-rishabh sir,
This type of request:-
header = {
    "Content-Type": "application/json",
}
d = {
    "grant_type": "client_credentials",
    "scope": "sellingpartnerapi::notifications",
    "client_id": "xxxxx",
    "client_secret": "xxxx",
}
response = requests.post("https://api.amazon.com/auth/o2/token", headers=header, data=d)
print(response.status_code)
print(response.text)
data = response.json()
access_token = data['access_token']
print(access_token)

but output:-
400
{"error_index":"KvdPQtKoUr5CAbnwMEsEwQAAAAAAAAABH_vpDJ_LMtoEBeCtluMB-d-kZcxTFmpyTk9bAX0h3vTmg3N8jGWWumQcDoJ5YNckl9tT2CldOGdz1bkFTdXTJoTK1QrWFKgygtLU-vjNBGkH21-sIsUp-kHtGhYjzOItqPhzI9JLDDuxSgbl2uBqRmPjAmzX8qimmf0bm14tSIU7mE9ePEzuoNvI1FPls09IXJdip-tgkFgaS5XXXz1t-A==",
"error_description":"Malformed request","error":"invalid_request"}
Traceback (most recent call last):
  File "awsdata.py", line 224, in <module>
    access_token = data['access_token']
KeyError: 'access_token'

**Comment by ShivikaK** [comment]
Hello @PrashantMalaviya 

The request created for generating access token is incorrect. You do not require to pass scope parameter for this access token and need to change grant_type to refresh_token. 

Currently your request setup is for generating a grantless token but Orders API does not require a grantless access token.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#grantless-operations-1

Please refer to below documentation for reference on how to make a request to get a LWA Access Token correctly-

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token

Additionally, the Content-Type in request for LWA access token is application/x-www-form-urlencoded but your actual request to Orders API endpoint should have it set to application/json.

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
hello @ShivikaK sir,
now What is now i send the postman Rquest ?????

GET https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A21TJRUUN4KGV&CreatedAfter=2021-01-05
403
700 ms
Network
Request Headers
x-amz-access-token: XXXXXX
Host: sellingpartnerapi-eu.amazon.com
X-Amz-Date: 20210424T042424Z
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXX/20210424/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date, Signature=XXXXXXX
User-Agent: PostmanRuntime/7.26.10
Accept: */*
Postman-Token: 4a5d2f3e-4a5b-4c82-85b2-071120da7fc3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Response Headers
Date: Sat, 24 Apr 2021 04:24:24 GMT
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
x-amzn-RequestId: 0431082f-7b0f-485a-a742-9d5c87297f57
x-amzn-ErrorType: AccessDeniedException
x-amz-apigw-id: eRWK1HgADoEFQIA=

**Comment by PrashantMalaviya** [comment]
hello @ShivikaK sir,
i try this but now output is ????
header = {
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
}
d = {
    "grant_type": "refresh_token",
    "refresh_token": XXXX ,
    "client_id": XXXXX,
    "client_secret": XXXXXX,
}

response = requests.post("https://api.amazon.com/auth/o2/token", headers=header, data=d)
print(response.status_code)
print(response.text)
data = response.json()
access_token = data['access_token']
print(access_token)
sleep(5)
auth = AWSRequestsAuth(aws_access_key=XXXXX,
aws_secret_access_key=XXXXX,
aws_host='sellingpartnerapi-eu.amazon.com',
aws_region='eu-west-1',
aws_service='execute-api')
endpoint = 'https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A21TJRUUN4KGV&CreatedAfter=2021-01-05'
headers = {'x-amz-access-token':data['access_token'] ,"Content-Type": "application/json" }
r = requests.get(endpoint, auth=auth, headers=headers)
print("==============data++++++++++++++++")
print(r.status_code)
print("+++++++++++++++++++++++++++")
print(r.text)
print("+++++++++++++++++++++++++++")
print(r.headers)


OUTPUT IS :_#########################
==============data++++++++++++++++
403
+++++++++++++++++++++++++++
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
+++++++++++++++++++++++++++
{'Date': 'Sat, 24 Apr 2021 05:34:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'x-amzn-RequestId': '06beec2d-1917-48b1-b8a6-33caccaa82e2', 'x-amzn-ErrorType': 'AccessDeniedException', 'x-amz-apigw-id': 'eRgYRE6-DoE
Fk9Q='}

**Comment by ianrussel** [comment]
@ShivikaK I open this ticket related to orders total count. `**Hi . Is there any way of just getting the total count for orders ? For total count I mean the sum of all orders . Currently the api returns only records with limit default t**o 100.`

**Comment by ShivikaK** [comment]
Hello @ianrussel 

Apologies for missing on the actual issue raised.

There is no API that returns the sum total of orders but you can refer the Order Reports and see if that helps your use case to get such data -

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#order-reports

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
> hello @ShivikaK sir,
> i try this but now output is ????
> header = {
> "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
> }
> d = {
> "grant_type": "refresh_token",
> "refresh_token": XXXX ,
> "client_id": XXXXX,
> "client_secret": XXXXXX,
> }
> 
> response = requests.post("https://api.amazon.com/auth/o2/token", headers=header, data=d)
> print(response.status_code)
> print(response.text)
> data = response.json()
> access_token = data['access_token']
> print(access_token)
> sleep(5)
> auth = AWSRequestsAuth(aws_access_key=XXXXX,
> aws_secret_access_key=XXXXX,
> aws_host='sellingpartnerapi-eu.amazon.com',
> aws_region='eu-west-1',
> aws_service='execute-api')
> endpoint = 'https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A21TJRUUN4KGV&CreatedAfter=2021-01-05'
> headers = {'x-amz-access-token':data['access_token'] ,"Content-Type": "application/json" }
> r = requests.get(endpoint, auth=auth, headers=headers)
> print("==============data++++++++++++++++")
> print(r.status_code)
> print("+++++++++++++++++++++++++++")
> print(r.text)
> print("+++++++++++++++++++++++++++")
> print(r.headers)
> 
> OUTPUT IS :_#########################
> ==============data++++++++++++++++
> 403
> +++++++++++++++++++++++++++
> {
> "errors": [
> {
> "message": "Access to requested resource is denied.",
> "code": "Unauthorized",
> "details": ""
> }
> ]
> }
> +++++++++++++++++++++++++++
> {'Date': 'Sat, 24 Apr 2021 05:34:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'x-amzn-RequestId': '06beec2d-1917-48b1-b8a6-33caccaa82e2', 'x-amzn-ErrorType': 'AccessDeniedException', 'x-amz-apigw-id': 'eRgYRE6-DoE
> Fk9Q='}

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ianrussel** [comment]
Hi @PrashantMalaviya sorry I need to close this issue .Please open another issue specific to your concerns and we will help you there
