### ISSUE TITLE
Amazon Pay status

### ISSUE THREAD

**Issue by thoemy** [amzn/selling-partner-api-docs#645]
Hi,

with MWS we are able to request Amazon Pay settlement reports with the `_GET_FLAT_FILE_OFFAMAZONPAYMENTS_SETTLEMENT_DATA_` report type. The only mention of Amazon Pay is in [reportType_string_array_values.md](https://github.com/amzn/selling-partner-api-docs/blob/548d815eb32c899aa4b7520c49baee008f3687e3/references/reports-api/reportType_string_array_values.md#amazon-pay-report). But it only mentions the sandbox report type. Is the other type missing from the documentation?

We tried the SP API with an Amazon Pay seller account and the authorization is successful. The app also appears under "Third-party developer and apps" but the `GetReports` API call fails with: Unauthorized: Access to requested resource is denied. Our hybrid App works fine with another seller that does not use Amazon Pay.

Should requesting Amazon Pay reports work?

**Comment by cajudosu** [comment]
We currently experience exactly the same issue. Any news on this?

**Comment by dingledorf** [comment]
Don't think it works at the moment, I contacted seller central support and the only thing they say is use MWS.
