### ISSUE TITLE
I can access ordersAPI GetOrders successfully but getting access denied for Order Reports

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#646]
Hi @rugved1991

I am getting a successful response from GetOrders but when calling CreatReport I get access denied.

Why would this be ?

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

Thanks

**Comment by ianrussel** [comment]
If your using reports_2021-06-30, its not yet available.Its only for preview

**Comment by nrogers805** [comment]
> If your using reports_2021-06-30, its not yet available.Its only for preview

Thanks @ianrussel 

Yes I am. 

So is it just basically if the date portion of the API is in the future then its not actually available, is that how it works?

Thanks

**Comment by ianrussel** [comment]
I think not. I forgot the link of the discussion by the Amazon architect, but basically the 2021-06-30 is not yet published in live because its not yet ready.

**Comment by rugved1991** [comment]
Hi @nrogers805,

The new version of the reports API is not yet available to use. It has been provided to understand the changes that would be made to the API. You will still use version "2020-09-04". Once the new reports API is available for use, we will remove the older version from the GitHub repository.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by ForrestWang** [comment]
do you have a place to list all production versions of APIs? how do we know the report 2021-06-30 is in preview until hits the error?

**Comment by rugved1991** [comment]
Hi @ForrestWang,

We do not have a list of production versions of APIs. The version with a future date is yet to be launched. We have provided these for your reference to understand what is to come in the new version. Once the new version is enabled, the previous version will be removed from the documentation. You would run into errors when the previous version is removed.

Thanks,
Rugved
Solutions Architect, SP API
