### ISSUE TITLE
"Authorize new developer" Error Code: MD9000 This Developer is not currently eligible for new authorizations.

### ISSUE THREAD

**Issue by tnortonfinibus** [amzn/selling-partner-api-docs#647]
We have a client that simply wants us to utilize this API to update their Inventory.  This is a custom app specifically for them that integrates their DB with their Amazon Seller stock.

Followed the docs and when the client goes to Apps & Services > Manage Your Apps > Authorize new developer, then enters our info they get the error:

**Error Code: MD9000 This Developer is not currently eligible for new authorizations.**

Developer ID: 301970451626

**Comment by jimmy-ross-xapix** [comment]
i get this too, i think we might have to add oauth login uri / redirect uri though im not sure what that needs to be

<img width="708" alt="Screenshot 2021-04-23 at 12 40 48" src="https://user-images.githubusercontent.com/62943550/115860049-41400700-a431-11eb-8435-db119df3eb2f.png">

**Comment by tnortonfinibus** [comment]
I have read from another post that they had to add OAuth Login as well.  However, I may be confused as I cannot seem to see the screen you sent in your screen shot @jimmy-ross-xapix 

I am not sure I am creating the app in the correct spot for this web app that will NOT be on the marketplace.

When I am in Amazon Developer I can go to Apps & Services and ADD NEW APP but there is only Android and Mobile Web?

**Comment by rugved1991** [comment]
Hi @tnortonfinibus,

Can you confirm if you are creating an application at this location:
Apps & Services -> Develop Apps
You can create new application by clicking on "Add new app client" and choosing "SP API" as API Type.
If you have already created an app, you can click on "Edit App" in front of the application. You will have to change the API Type settings to either "SP API" or "SP API and MWS" to be able to see the OAuth URL settings.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by tnortonfinibus** [comment]
Hi @rugved1991 thanks for the help thus far.

Where would I find the "Apps & Services -> Develop Apps" link?

- Seller Central (https://sellercentral.amazon.com/)?
- Developer Console (developer.amazon.com)?
- MWS (https://console.aws.amazon.com/)?

If it is Seller Central, only my client has access to that link and they just need my Developer ID they claim, hence the error in this thread.

**Comment by rugved1991** [comment]
Hi @tnortonfinibus,

You would find this option on the Seller Central Account. If you are developing an application for multiple sellers, you will have to create a seller central account for yourself. You will use this account to develop an application which will be used by multiple sellers through OAuth flow. 
Please refer to the [seller developer guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md) for more information on registering applications and connecting with SP API. 

@jimmy-ross-xapix you need to create HTTPS urls for login and redirect to handle the OAuth flow. The login url will be used by the application when a seller is not registered with your application. The redirect url will be used by the application to redirect the seller after providing consent. You will see the spapi_oauth_code and selling_partner_id in the redirect URL after the seller provides consent.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by tnortonfinibus** [comment]
Ok thanks again @rugved1991 .

So as I see it, we are developing this app for our client that only THEY will utilize.  

Does this make more sense for our client to set up their own Developer ID and gives us the credentials so we may connect to their store with this APP?

I just don't see the reason we need to keep paying for an Amazon Seller Account when we only have one client using this very specialized APP only for their Seller Account.  Am I way off here?

**Comment by etimmons** [comment]
Just a heads up, the user will also receive this error if they use a developer id from a different region for the region in which they are registering the app.  For example, using an app's North America developer id to register the app in the UK will give this error.

**Comment by mtkumar82** [comment]
> i get this too, i think we might have to add oauth login uri / redirect uri to the application though im not sure what that needs to be
> 
> <img alt="Screenshot 2021-04-23 at 12 40 48" width="708" src="https://user-images.githubusercontent.com/62943550/115860049-41400700-a431-11eb-8435-db119df3eb2f.png">

In my application, I am not geeting a way to add Login and redirect url , I am creating new application using developercentral account.
https://developercentral.amazon.com/

![image](https://github.com/amzn/selling-partner-api-docs/assets/1560517/7f255a95-d16a-4aa0-84a8-6943eb190afd)

there no way to add it, Also when I am creating application is in sandbox status, How I can put it live? Anybody please help me in this?
