### ISSUE TITLE
[BUG] /fba/inventory/v1/summaries not accessable

### ISSUE THREAD

**Issue by danielbebbernovacode** [amzn/selling-partner-api-docs#650]
Hello,

We are trying to access the API endpoint /fba/inventory/v1/summaries from EU in sandbox but only receiving "Unauthorized" as answer. Other API endpoints are working without any problem.

Error:
{
message: 'Access to requested resource is denied.',
code: 'Unauthorized',
details: ''
]
}

Are special permission needed for that endpoint or is there an other issue?

Best Regards,
Daniel

**Comment by rugved1991** [comment]
Hi @danielbebbernovacode,

The FBA Inventory API is currently only available for use in North America region. We will be releasing this API in Europe and Far East regions in 2021. Please refer to the [Overview](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md#overview) section of the API reference.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by danielbebbernovacode** [comment]
Hi Rugved,
Is there a more precise timeframe available than "2021"?

**Comment by viktorbahtev** [comment]
Hey @rugved1991, 

Any updates on this? Do you have a more precise date for releasing the Fba Inventory API for Europe and Far East regions?

With the MWS deprecation happening this September, it's really critical to provide an alternative for retrieving information about inventory programmatically.

**Comment by pbegle** [comment]
I am trying to access this endpoint in North America region and getting the same "Unauthorized" error that people in the EU are receiving. All other endpoints I have tried work fine. Can someone confirm this actually works in the NA region?

**Comment by viktorbahtev** [comment]
> I am trying to access this endpoint in North America region and getting the same "Unauthorized" error that people in the EU are receiving. All other endpoints I have tried work fine. Can someone confirm this actually works in the NA region?

Yes, it works in North America region.

**Comment by danielbebbernovacode** [comment]
Hi @rugved1991 ,
2021 is nearly gone. Will this endpoint be a christmas gift or will it never come to europe?

**Comment by danielbebbernovacode** [comment]
2021 is gone and we still have no access in europe ... can you provide any update here? Because it is getting annoying to get no feedback and the disclaimer still says 2021....

**Comment by chaochao181** [comment]
What's the matter with the data returned by my interface always being empty

**Comment by stefnats** [comment]
Daniel, I think the Api is now available in Europe region.

@chaochao181 what do you mean? Can you elaborate a bit more detailed?
