### ISSUE TITLE
Calling anyone with access to a vendor account/vendor docs

### ISSUE THREAD

**Issue by tomhirschfeld** [amzn/selling-partner-api-docs#652]
If you can send me a compilation of the documentation available to you, I will personally venmo/paypal/cashapp/mail you $50

we can only access vendor docs if we have a vendor account and we have a seller account, but we're integrating with vendors and cannot see the API docs.

**Comment by ShivikaK** [comment]
Hello @tomhirschfeld,

Thank you for your interest in Vendor APIs. 

We are finalizing features to enable third party developers to directly support developers and preparing documentation accordingly. We plan to post updates to our developer guide and API materials for Vendor use cases in the coming weeks.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by tomhirschfeld** [comment]
This is great!
We have 2 vendor customers onboarded and our offer still stands to anyone who can send me some docs for us set up some API calls to our vendor partners. 
Best,
Tom Hirschfeld

**Comment by ShivikaK** [comment]
Hello @tomhirschfeld

I can further assist with this request if you can open a support case with us and share the Case ID with me.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by tomhirschfeld** [comment]
@ShivikaK hi, the case number is here: CASE 8204944111 thanks for your help

**Comment by ShivikaK** [comment]
Hello @tomhirschfeld 

Your case has been responded with further details as requested.

Please let me know via the support case if you have any follow up questions.

Thanks,
Shivika Khare
Selling Partner API Developer Support
