### ISSUE TITLE
400 InvalidInput: getOrders with NextToken

### ISSUE THREAD

**Issue by milovvsam** [amzn/selling-partner-api-docs#653]
We were trying to access all orders from a seller and able to call getOrders successfully (Query: MarketplaceIds, CreatedAfter and CreatedBefore). 

We're having issues on calling getOrders (Query: NextToken). 
Amazon returns this error:{ "errors": [ { "message": null, "code": "InvalidInput" } ]}

How can we resolve this?

Below is the sample request.
------------------------
{
    method: "GET",
    url: "https://sellingpartnerapi-na.amazon.com/orders/v0/orders?NextToken=69B7Xsf/hO+aJqJYLDm0ZAmQazDrhw3CniO2hMIqkKP7jhTQ91co0MNI3HOI22PIxqXyQLkGMBs8VhF73Xgy+8ELbjnH8JQbWXnNulzBLcoO4unefPGnG3z38RTuGUmOInTAy+XKVmRZBY+oaVuyc8QON+K1yc/Yp0K4CZdazCD9VWV70XCFUvH21n5Dr9uif2GLmUGyr9UGnxD0RJmrryegoU0IPZxXANi6ocIEc7WEEaL6TUCRyjAvQebD16jJMBO/reDY2s8hGWNNu3VwFU0hrIUQcumU7YYXwRo+g8JiIXlRXylzxduZ3sLNMwtcnvdYBCPVhqJ9gIYEDcb3ThBga2VfNyoSEMX5JITS9AcgSC+G8iqGOpClSmSOEIdlJ1gGohf+5hNKw4h6m/JgRP1o1a5R+Vaq6JSfT6Z0kuhkm1TQSa1/0g==,
    headers: {
        Authorization: "AWS4-HMAC-SHA256 Credential=xxxxxx/20210422/us-east-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-date, Signature=xxxxxxx",
        host: "sellingpartnerapi-na.amazon.com",
        "user-agent": "Ixxxxxxx/1.0 (Language=JavaScript)",
        "x-amz-access-token": "xxxxxxx",
        "x-amz-date": "20210422T142748Z"
    }
}

**Comment by PrashantMalaviya** [comment]
hello @milovvsam 
i think NextToken is decode in algorithms=["HS256"] and this is the python code :- jwt.decode(NextToken,algorithms=["HS256"])

**Comment by ianrussel** [comment]
for me it works with `next_token`

**Comment by PrashantMalaviya** [comment]
hello sir,@ianrussel sir ,
can you check this...i have also same issues.....

my Python code :-
def getAdditionalOrders(req, next_token):
    # Custom timeout when Amazon throttles the request
    for i in [5, 10, 30, 60, 120]:
        try:
            print(next_token)
            response = req.list_order_items_by_next_token(next_token=next_token)
            # response = ordersObj.list_order_items_by_next_token(token=next_token)
            return response
        except mws.MWSError as e:
            if e.response.status_code == 503:
                time.sleep(i)
                continue
            else:
                raise e
orders = []
access_key =xxxxx
secret_key =xxxxx
seller_id = xxxx
IN = xxxxx
Token1 = xxxxx
ordersObj = mws.Orders(access_key, secret_key, seller_id,auth_token=Token1,region='IN')
next_token = None

response = ordersObj.list_orders(next_token=next_token,
                            marketplaceids=IN,
                            created_after="2021-04-27")

obj = xmltodict.parse(response.original)
print(obj)
orders.append(obj['ListOrdersResponse']['ListOrdersResult']['Orders']['Order'])
next_token = response.parsed.get('NextToken', None)

while next_token:
    response2 = getAdditionalOrders(ordersObj, next_token)
    obj = xmltodict.parse(response2.original)
    print(obj)
    orders.append(obj['ListOrdersByNextTokenResponse']['ListOrdersByNextTokenResult']['Orders']['Order'])
    next_token = response2.parsed.get('NextToken', None)


output in nextToken:-
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mws.amazonservices.in/Orders/2013-09-01?AWSAccessKeyId=xxxxxxx&Action=ListOrdersByNextToken&MWSAuthToken=xxxx&NextToken=QVj3mwNV2wyaJq
JYLDm0ZAmQazDrhw3C1eIqQwWD0wxUojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy%252B8ELbjnH8JQbeE6xVidIcK7LwG81KE%252Bhhrl02WZB7t3qInTAy%252BXKVmRZBY%252BoaVuyc8QON%252BK1yc%252FYrViWqudYlrvOi1q%252B3c3gNN%252BtQSagYJoGf2GLmUGyr9UGnxD0RJmrryegoU0IPZxXyrG8EnlsijKH6d7kmgnCHPNM
OKEEXK6DMBO%252FreDY2s%252BlLK7IMTJG%252BoWZaQSHenVJIIYkgmdzyCpNQzRAUqdu%252Fu9W9k%252Fg4x4611Ds5w1QtjVRzod%252F1ExQITOPK%252BZzoe2U0fiZM4OnSU9MnnkRTC8N3wUSRADguOJmsrFxdQMElQeTycdsaOKZ%252BptCkxguFlUBFMCsLoX8rUoTP9x12EjI4kpyhiJ3f7EyX4V3hBjzVIY%253D&SellerId=xxxx&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-04-28T13%3A24%3A27&Version=2013-09-01&Signature=xxxxxx

mws.mws.MWSError: <?xml version="1.0"?>
<ErrorResponse xmlns="https://mws.amazonservices.com/Orders/2013-09-01">
  <Error>
    <Type>Sender</Type>
    <Code>NextTokenCorrupted</Code>
    <Message>We could not decode your NextToken. Possible reasons include: a transmission error, improper quoting or a truncation problem.</Message>
  </Error>
  <RequestId>53787245-067b-47af-aa9f-3fab8847afe2</RequestId>
</ErrorResponse>

can you HELP ????

**Comment by grath90** [comment]
I have the same issue. I've supplied NextToken and Marketplace Ids in the query but get the same errors as posted above. I read in another issue to put the next token in the header but it just returns the same set of orders.

**Comment by soodankush** [comment]
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=MARKETPLACEIDS&NextToken=xfbimBkafg2aJqJYLDm0ZAmQazDrhw3CpJNTpcvpcS7mQLg8HUtIW1YJ60zM5T3FxqXyQLkGMBs8VhF73Xgy%2B2va6%2Ff3T54goAUSGAa%2F2JGL9hAYcb3iOGk2Pr9iWuKnInTAy%2BXKVmRZBY%2BoaVuyc9M9cTZROoa8CbugIqdDz6SxVLum7oXtpq8UoEvaMro9f2GLmUGyr9UGnxD0RJmrryegoU0IPZxXCsdszADKFUMRgvGhzNzKOHvH6fvcW0hIMBO%2FreDY2s%2BlLK7IMTJG%2BoWZaQSHenVJ7YYXwRo%2Bg8IXQS1AnoWDgduZ3sLNMwtccKDGq54NazUE8sptC7fMs3kYbz2aUPwM9kghxPKvMg%2FR0EW8hx%2FF6lPF1HQRJhsIXqZX%2Bmy2QqiBA1KyEG2j%2FOo4JBJr49sar1Q2QG6qwqhA7DO8amUIng%3D%3D


ENCODE THE NEXTTOKEN AND THEN PASS. YOU WILL GET THE RESULT
