### ISSUE TITLE
403 Forbidden  Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...) 

### ISSUE THREAD

**Issue by B1essedSou1** [amzn/selling-partner-api-docs#657]
Hello guys! im in very hard struggle with it about few weeks. I research all internet and cant fix that problem :( i was tried to send request as by following local guide and by using closuale repo.  But the verdict is the same all times...

All Apps in "Draft" status if its important..

[403] Client error: `GET https://sellingpartnerapi-eu.amazon.com/catalog/v0/items/B0002ZFTJA?MarketplaceId=ATVPDKIKX0DER` resulted in a `**403** **Forbidden**` response:
{
  "errors": [
    {
      "message": "**Access to requested resource is denied.**",
     "code": "**Unauthorized**",
     "det (truncated...)

I just give up and thinking to post that issue..
I was create few apps with same ARN's (user ARN, and Role ARN as was founded in internet)

now i provide a debug info from closuale package, please help :( ;

*   Trying 108.128.222.203...
* TCP_NODELAY set
* Connected to sellingpartnerapi-eu.amazon.com (108.128.222.203) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=sellingpartnerapi-eu.amazon.com
*  start date: Apr  4 00:00:00 2021 GMT
*  expire date: May  3 23:59:59 2022 GMT
*  subjectAltName: host "sellingpartnerapi-eu.amazon.com" matched cert's "sellingpartnerapi-eu.amazon.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /catalog/v0/items/B0002ZFTJA?MarketplaceId=ATVPDKIKX0DER HTTP/1.1
host: sellingpartnerapi-eu.amazon.com
Accept: application/json
Content-Type: application/json
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
x-amz-access-token: Atza|IwEBIMncUctcriiy*****************************9Hg1shadXX6Cf1g1Vb1hsKx8ne5e0ur6SLCd6k3OZEjK2NxLmZfEPYvvUms8HQnYq9es_nNUYs3c2__AH-Wiu7XaprVpc98T8bU5o9PcRMrcz7TZ3i-fB5ZQSIULL7wH6xzhy6GX0Nnhsx2_YvJrovOmqVvXyb84D5lcAr2IzDadMasi65jzK_LJLcxS9E1jhnvx3Tp2r_K833ucPQWVqcND4b-silm4tiZjgJAr_jyEGNosk5uDwzBIAzVBVNg5AEHdcZPAxD6zJT5b5JCtdNeWx4yNkrIqmjJu8
x-amz-date: 20210424T205838Z
x-amz-security-token: FwoGZXIvYXdzEJ7//////////wEa**********************************dZVoNmdKeFXTHn++57esbvkv34gB2FSqkvRJv+kQygfzZ7XuCjTXk7ZdFtZI/KO3AuUyZ0Xr5ina8vO/rgIJlBrPrYrtEI0uGaM7Qlu83RjuHf3LyeYoSUEXmYFofgetxovRlFRw0HOVO0IUaRvCXGd4EiLafFD1Zf41GZfTo8ODXXF8Ty0CJVO77ZBUl/wU36bGXXV2d7Gh7mxya3hZ/324xEECvaVQo/oyShAYyLV7ry9mY/hYjnYrENqcczsUcWJRy8ekP+7CoXWUGJisR5thy8Ce6nt+f/3Ulsg==
Authorization: AWS4-HMAC-SHA256 Credential=ASIA43SNT*********EH/20210424/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=17bb2aa1112**********b58510d1158066bcc98e59aed611b1bb4ec4c9d

< HTTP/1.1 403 Forbidden
< Date: Sat, 24 Apr 2021 20:58:38 GMT
< Content-Type: application/json
< Content-Length: 141
< Connection: keep-alive
< x-amzn-RequestId: c1752aad-b777-45b6-bed5-bb4******265
< x-amzn-ErrorType: AccessDeniedException
< x-amz-apigw-id: eTnz0HBvjoEFxEw=
< 
* Curl_http_done: called premature == 0
* Connection #0 to host sellingpartnerapi-eu.amazon.com left intact

**Comment by B1essedSou1** [comment]
Hey, can somebody help us? I think problem because of something wrong with User,Policies and Role(in case when we registered app with role). Anyway we did all by local guides. Thanks in advance!

**Comment by HelloLiuKaiJun** [comment]
I got the same error while I try to create report but OrderApi is just work fine.

**Comment by B1essedSou1** [comment]
> I got the same error while I try to create report but OrderApi is just work fine.

yeah! Some functions works correctly, but most of them bring errors...
