### ISSUE TITLE
Issue of publishing app to the marketplace app store

### ISSUE THREAD

**Issue by UoooBarry** [amzn/selling-partner-api-docs#658]
@rugved1991 @krithic15 
Hello, it has been a month since we submit the application to publish our app to the amazon marketplace app store. We received an email about our developer roles is not suitable for Amazon selling partner API. Then we requested the new role successfully. And we've been told `You now have global Marketplace access to SP-API based on the roles you requested`.
So we assume that our application to publish our app will be approved soon, however, as the weeks pass, we still not getting any update on it. Can you please check for us, and inform us of any issues? We really appreciate your help.
Thank you.

Our app id is: amzn1.sp.solution.e54b980b-c1eb-4a72-974a-5a6db267132c

**Comment by rugved1991** [comment]
Hi @UoooBarry,

Thanks for reaching out. I have reached out to the team for further investigation. I will update you when I have more information.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @UoooBarry,

I have an update from the team. They mentioned that in your developer profile you had submitted earlier, you mentioned you are a private developer. Private developer for us is someone who is building an application on seller central for their own account. If you are building an application to be used by multiple sellers, you should specify "public" developer.
Please edit your developer profile once again and then submit the application for publishing. Let me know the new case IDs for both developer profile and app publish. 

Thanks,
Rugved
Solutions Architect, SP API

**Comment by UoooBarry** [comment]
> Hi @UoooBarry,
> 
> I have an update from the team. They mentioned that in your developer profile you had submitted earlier, you mentioned you are a private developer. Private developer for us is someone who is building an application on seller central for their own account. If you are building an application to be used by multiple sellers, you should specify "public" developer.
> Please edit your developer profile once again and then submit the application for publishing. Let me know the new case IDs for both developer profile and app publish.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

Thanks for the reply. We confirmed our data access is now `My organization builds and offers publicly available applications` 
 and we resubmitted the application, the new case id is 8283805721.
Regards

**Comment by UoooBarry** [comment]
> Hi @UoooBarry,
> 
> I have an update from the team. They mentioned that in your developer profile you had submitted earlier, you mentioned you are a private developer. Private developer for us is someone who is building an application on seller central for their own account. If you are building an application to be used by multiple sellers, you should specify "public" developer.
> Please edit your developer profile once again and then submit the application for publishing. Let me know the new case IDs for both developer profile and app publish.
> 
> Thanks,
> Rugved
> Solutions Architect, SP API

Hello sir, 
Today we received a letter says that our developer account is a private account. But we double-checked our developer profile, and the profile states that 'My organization builds and offers publicly available applications'. Please check for us ASAP.
![image](https://user-images.githubusercontent.com/37783883/117236639-a77a5000-ae5b-11eb-9dc1-7259d9028d48.png)

**Comment by UoooBarry** [comment]
Hi @rugved1991 ,
Our app status was turned to 'ready for publishing', and no changes had been made after that. I wonder when the status will be 'published'? Or do I need to do anything for it?

Thanks
