### ISSUE TITLE
How to get product shipping price depends on the destination address?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#660]
Hello,

If I am not wrong, product-pricing api returns the product **listing price** and **shipping price**. I guess, **shipping price** here is in the **same country**.

But, I think, shipping price actually depends on the destination address.

For example, how can I get the **shipping price depending on the destination address** (another country)? For example, product's shipping price **US to Australia**?

Thank you.

**Comment by lyubo-slavilov** [comment]
@arturll7 did you find any solution to this problem?
