### ISSUE TITLE
[BUG] Amazon Order API wrong rate limit

### ISSUE THREAD

**Issue by xiaoyu-tamu** [amzn/selling-partner-api-docs#661]
**Describe the bug**
On Oct 8, 2020, @salric  changed the rate to 1 and burst to 1 for order related api. This is not correct, the rate for order related API is still 0.0055 and the burst is 20.

![image](https://user-images.githubusercontent.com/33362998/116017750-1529af00-a606-11eb-9843-f1646e30df8b.png)

**URL of the content on GitHub**
Please provide the GitHub URL for the documentation where you see the bug.

https://github.com/amzn/selling-partner-api-docs/commit/3a91724885b426075975e061297f4b951e1a1791#diff-33c0d1576f0f97731f884358fdf951fa76b2eaaf22e0a3ac2f4766a435e6b7a6

**Comment by callumb123** [comment]
This seems to be a common issue. The ListCatalogItems endpoint documentation also says you should be able to send 6 requests per second. However I have had it confirmed by support that this is not actually possible and in fact it is still using the old MWS rate limits which is 1 every 5 seconds

**Comment by ForrestWang** [comment]
same issue happened, I delayed the getOrderItems call by 2 seconds, but still get 429 error.
