### ISSUE TITLE
Document Helper For C# Missing

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#662]
Hi @rugved1991 

Where can I find the documents helper for c#. 

I see that its available for java here: https://github.com/amzn/selling-partner-api-models/tree/main/clients

Thanks

**Comment by rugved1991** [comment]
Hi @nrogers805,

We currently do not have helper code for Encryption Decryption in C#. Our team is working on developing the helper code in other languages but there is no ETA we can share yet. Meanwhile, you can leverage the developer community for help with C# code. I found a [similar issue](https://github.com/amzn/selling-partner-api-docs/issues/463#issuecomment-789609710) which references a C# code which worked for them.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by nrogers805** [comment]
Hi @rugved1991

Thanks but have now developed my own download & upload process  that works using HttpClient

Thanks
Norm
