### ISSUE TITLE
Is possible to get seller registered date in seller central? 

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#663]
Is possible to get the seller registered date in seller central or when the first order is placed or first listing created date in any API?

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
