### ISSUE TITLE
GET_FLAT_FILE_OPEN_LISTINGS_DATA Compression Algorithm

### ISSUE THREAD

**Issue by bwhaley-ece** [amzn/selling-partner-api-docs#664]
The ReportDocument for the GET_FLAT_FILE_OPEN_LISTINGS_DATA is showing CompressionAlgorithm = null.  However, the report appears to be gzip-compressed.  Thank you.

**Comment by bwhaley-ece** [comment]
I'm seeing similar behavior for the GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL report -- in some cases the report is compressed, but the CompressionAlgorithm in the ReportDocument is set to null.

**Comment by raja1621** [comment]
I'm also facing the CompressionAlgorithm is NULL for GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT, GET_FLAT_FILE_OPEN_LISTINGS_DATA, GET_MERCHANT_LISTINGS_ALL_DATA, GET_FLAT_FILE_OPEN_LISTINGS_DATA reports. Kindly let us know how to resolve it.

**Comment by johnkw** [comment]
If you haven't already, switch to the new https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#reportdocument API. It's working just fine. Weirdly enough I've never seen it return a compressed report. It's not even using HTTP compression over the wire, which is weird.

**Comment by johnkw** [comment]
Please close this in favor of the new #1287 which references the new API.
