### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by moveproduct** [amzn/selling-partner-api-docs#666]
I've been trying to get insight into case: 8164240151
https://sellercentral.amazon.com/cu/case-dashboard/view-case?caseID=8164240151

Can someone please look into it and respond?

Sorry, reaching out on github for it

**Comment by jchavest13** [comment]
Hi @moveproduct ,

Please accept our apologies for the delay getting back to you on your case. You can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
