### ISSUE TITLE
[BUG] getOrderBuyerInfo and getOrderAddress endpoints are not returning any data at my current scope access

### ISSUE THREAD

**Issue by petergzli** [amzn/selling-partner-api-docs#667]
I am referring to the customer buyer info https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorderbuyerinfo

It seems the sensitive buyer address line 1, address line 2, are not provided unless we are granted further private scope. However, I am unable to receive this scope is granted even after filing a request and waiting more than 2 weeks now. I have filed a request and my support ticket on seller central is 8184186041

@rugved1991

**Comment by rugved1991** [comment]
Hi @petergzli,

Thanks for reaching out. I can see there is an update on the support case. Please continue to monitor the support case for further updates. 
Looking forward to seeing you implement the SP APIs.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by petergzli** [comment]
Hi @rugved1991 actually it seems like a follow up question however, we are now back in the waiting period with 1.5 weeks in. Was wondering if there's a way to escalate the case as we are blocked on these customer shipping address data.

My case number is still: ID8184186041

With no responses by Amazon as of 1.5 weeks ago.

**Comment by jchavest13** [comment]
Hi @petergzli,

Please accept our apologies for the delay getting back to you on your case. You can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
