### ISSUE TITLE
Get a seller Id from Order ?

### ISSUE THREAD

**Issue by tswapnil** [amzn/selling-partner-api-docs#67]
Is there a way to get the seller Id from the Order (order Id) fetched using OrdersV0API ? 
Is there a way to get Orders for a seller Id ?

**Comment by seanevan** [comment]
Hi @tswapnil, you can filter Order results by the SellerOrderId, and can obtain the SellerSKU from the Orders API responses. The sellerId is not included in Orders responses. Your authorization with a particular seller allows you to call Orders, so I'm not sure I understand your second question, could you please elaborate?

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by tswapnil** [comment]
Hi @seanevan , I am not sure I understand the mechanism of fetching orders for a seller. Let's say I am authorized to fetch orders for multiple sellers. So, how should I be able to distinguish them ? I am also not sure how SellerOrderId can be used to box an order per seller ? Isn't SellerOrderId just another Order Id that doesn't necessarily identify a seller (from among multiple sellers ) ? 
   I have need to uniquely identify a seller if I have the Order Id or just get orders for a specific seller given a seller id . How can that be achieved ? 

Regards
Swapnil

**Comment by MrYing** [comment]
Hi @seanevan  ,I have a similar problem，I very much hope to get your advice。
I used the api: GET /orders/v0/orders/{orderId}/buyerInfo .
I cannot get user information。
I can only get these.
{"payload":{"AmazonOrderId":"XXXXX","BuyerEmail":"XXXXXX@marketplace.amazon.co.uk"}}
