### ISSUE TITLE
Restricted Data Token (RDT)  STS hybrid Application missing PII data

### ISSUE THREAD

**Issue by diegocvazquez** [amzn/selling-partner-api-docs#671]
Hello everyone, I am trying to implement Restricted Data Token (RDT) for consecutive to obtain order information like address and buyer info. I am following the guide;
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md
Our application is a Hybrid app using STS, so basically we add the AssumeRole token in the header “ x-amz-security-token” 
Basically I am able to obtain a RDT, but if I use the RDT instead of the LWA token  for the “x-amz-access-token” I am not getting any PII information, If I use the LWA I anm getting the PII information without any issues, the method I am using to test is /orders/v0/orders/{orderId}/address.

Is this working at the time or will be implemented later September 30th 2021? I am missing something?

@ShivikaK   I have created the case 6969713392, I saw some issues open about this subject like 
https://github.com/amzn/selling-partner-api-docs/issues/639
but not related with STS   & PII

Thanks for your response!

**Comment by ShivikaK** [comment]
Hello @diegocvazquez 

Thank you for raising this issue.

The case 6969713392 is currently being looked into by the Support team and will be updated with next steps and details.

Please continue monitoring the case for updates.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by diegocvazquez** [comment]
@ShivikaK 

Hi, 
Thanks for your support
