### ISSUE TITLE
Is there a way to use a test auth token while waiting on our account to be approved as a hybrid?

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#672]
We have been waiting a month a half to have our account approved as a hybrid.  We currently have MWS access.  Is there a way to move forward in our development with a test authentication? We have a WMS system and are going to use the FBA Inbound SP-API calls through out our application.  We are on development cycles and this development is in danger of  being pushed because we are waiting for our account to be made a hybrid. Today, our warehouses have to manually do these processes which take excessive labor.

Are there any suggestions?

**I am adding case number but you have already checked on it before**, so I am not asking for that here.  I just need a way to move forward in a test mode if possible.
ID8109560011

**Comment by diegocvazquez** [comment]
@hrhearn7 

Hi, what is the current status of your application?

**Comment by hrhearn7** [comment]
Open Case: Action Needed ByAmazon

**Comment by diegocvazquez** [comment]
@hrhearn7 

I mean in the sellercentral from the seller who owns the application

![image](https://user-images.githubusercontent.com/11884049/116291490-eee64980-a794-11eb-9a7a-2c1125e7a96f.png)

**Comment by hrhearn7** [comment]
The "develop apps" is not even an option.  We have been using MWS for FBM since 2019.  Our account went under review and they suspended everything.  We finally got the MWS back (was killing us in our production warehouses).  But I cannot see the developer drop down.  We are tying to integrate the FBA inbound api's (create plan, create order, update order, transport api's, etc) but cannot get past authentication.  I am thinking about making fake responses (in our QA environment) to just get it integrated into our system so when we finally get approval - we can move forward.

**Comment by jchavest13** [comment]
Hi @hrhearn7 ,

Please accept our apologies for the delay getting back to you on your case. You are already approved for the Unrestricted SP-API access roles you requested, we are only pending with the Restricted ones and you can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
