### ISSUE TITLE
Update Price API

### ISSUE THREAD

**Issue by moveproduct** [amzn/selling-partner-api-docs#673]
Does SPI provide any PUT/POST APIs to update price of a product?

**Comment by BrockleyJohn** [comment]
feeds

**Comment by mukulcap** [comment]
Can someone please give an example of feed data for updating price and inventory.

**Comment by chapmanjw** [comment]
The Listings APIs support PATCH operations where you can update individual attributes for a listing (such as pricing). See https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md#step-1-submit-listings-item-patch-request. 

For the structure and schema of the attributes data, you can retrieve JSON Schemas from the Product Type Definitions API: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md

**Comment by younkim** [comment]
@chapmanjw the `/attributes/purchasable_offer` patch seems to work, but this isn't doesn't seem to update the "offer" price shown from the get-listing-item's `offer.price` field, even with a valid `end_at` date. I've tried to patch `offer/price`, but it's not a recognized path. 

I'm not seeing any other SP API for updating regular price on products. Can you explain a bit about how to approach updating the actual selling pricing of a given product/item/listing?

**Comment by chapmanjw** [comment]
@younkim Apologies for the delayed response. If you are still seeing this issue, please contact developer support with specific sellers and SKUs that we can investigate.

**Comment by dialdhruv** [comment]
Is any way to update maximum retail price?

**Comment by chapmanjw** [comment]
> Is any way to update maximum retail price?

Yes, for the India marketplace, there is a `maximum_retail_price` struct under `purchasable_offer`. In previous tools, this was conflated with `list_price` (which is supposed to be MSRP, not MRP). In these newer tools (the APIs), these have been separated for clarity.

This would look something like this:

```
{
  "productType":"PRODUCT",
  "patches":[
    {
      "op":"replace",
      "path":"/attributes/purchasable_offer",
      "value":[
        {
          "marketplace_id": "A21TJRUUN4KGV",
          "currency": "INR",
          "our_price": [
            {
              "schedule": [
                {
                  "value_with_tax": 15.00
                }
              ]
            }
          ],
          "maximum_retail_price": [
            {
              "schedule": [
                {
                  "value_with_tax": 20.00
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
