### ISSUE TITLE
Orders API - getOrderItemsBuyerInfo response: BuyerCustomizedInfo.CustomizedURL is empty

### ISSUE THREAD

**Issue by betinawang** [amzn/selling-partner-api-docs#674]
When I try to get the customer's customized information, the returned field is empty
Has anyone encountered this situation?
Can help me?
This problem has been bothering me for many days

**Comment by betinawang** [comment]
HELP!!!!!!!!

**Comment by BrockleyJohn** [comment]
has the api role got pii permissions?

**Comment by betinawang** [comment]
> has the api role got pii permissions?

Yes I have passed the application

**Comment by betinawang** [comment]
i want to know how to contact Amazon SP-API customer service

**Comment by ShivikaK** [comment]
Hello @betinawang 

Thank you for raising this issue.

Please open a support case with us to further assist you with this issue using the following link - https://developer.amazonservices.com/support

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by salomonsanz** [comment]
same with me...

**Comment by thai101795** [comment]
i am sorry! 
Now, is there any solutions for the issue ?

**Comment by Chintan-Novus** [comment]
What role / permissions are required to get the BuyerCustomizedInfo in the API? 
All I get is a blank object for every customized order. I can see the customization details on the seller central dashboard but not on the sp-api `/orders/v0/orders/:orderId/orderItems/buyerInfo`

This is frustrating. @ShivikaK please need your help.
