### ISSUE TITLE
[BUG] a bug about the catalogItems_2020-12-01.json

### ISSUE THREAD

**Issue by CoolBoyXue** [amzn/selling-partner-api-docs#678]
hello sir , when I use the swagger-coden to auto generated from catalogItem_2020-12-01.json , my request send successfully , and I can only  get the data from class "summaries"   ,the class named"variations"、"vendorDetails"、"salesRanks"、“productTypes”、"images"  is null , the parameter I  write is actually correct , but the product 's image I have no idea to get ,somebody could tell me how to  do  to achieve this function?????

**Comment by chapmanjw** [comment]
Hello @CoolBoyXue, 

Can you provide an example of the request? 

By default, only `summaries` is provided. You can specify one or more `includedData` values to request the additional data.

**Comment by zmdhfjj** [comment]
Hi!
I have the same problems.
i can get the data 'productTypes', the data of "salesRanks" and "attributes" is null.
![1624246020](https://user-images.githubusercontent.com/37650213/122703270-bee29080-d283-11eb-88e5-477a4234eff7.jpg)
![1624246197(1)](https://user-images.githubusercontent.com/37650213/122703514-5b0c9780-d284-11eb-9b0f-c37ba66cc5e3.png)


> Hello @CoolBoyXue,
> 
> Can you provide an example of the request?
> 
> By default, only `summaries` is provided. You can specify one or more `includedData` values to request the additional data.

**Comment by chapmanjw** [comment]
@zmdhfjj Sorry for the delayed response. Can you create a support case with timestamps, requests, responses, and request ids (X-Amzn-RequestId header in the response)? From there, we can deep dive into what is happening on our end with your specific requests. https://sellercentral.amazon.com/gp/mws/contactus.html Thanks.
