### ISSUE TITLE
Uploading Feed 

### ISSUE THREAD

**Issue by Bagavath96** [amzn/selling-partner-api-docs#679]
package com.amazon.spapi.documents.Contoller;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.nio.charset.StandardCharsets;

import com.amazon.spapi.documents.UploadHelper;
import com.amazon.spapi.documents.UploadSpecification;
import com.amazon.spapi.documents.exception.CryptoException;
import com.amazon.spapi.documents.exception.HttpResponseException;
import com.amazon.spapi.documents.impl.AESCryptoStreamFactory;

public class upload {
	private final UploadHelper uploadHelper = new UploadHelper.Builder().build();
	
	private String data="<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
			+ "<AmazonEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"amzn-envelope.xsd\">\n"
			+ "    <Header>\n"
			+ "    <DocumentVersion>1.01</DocumentVersion>\n"
			+ "    <MerchantIdentifier>A********</MerchantIdentifier>\n"
			+ "    </Header>\n"
			+ "    <MessageType>Inventory</MessageType>\n"
			+ "    <Message>\n"
			+ "    <MessageID>1</MessageID>\n"
			+ "    <OperationType>Update</OperationType>\n"
			+ "    <Inventory>\n"
			+ "    <SKU>FMIBPKBLKON003017</SKU>\n"
			+ "    <Quantity>5</Quantity>\n"
			+ "    <FulfillmentLatency>7</FulfillmentLatency>\n"
			+ "    </Inventory>\n"
			+ "    </Message>\n"
			+ "    </AmazonEnvelope>\n"
			+ "";

	  // key, initializationVector, and url are returned by the createFeedDocument operation.
	  public void encryptAndUpload_fromString(String key, String initializationVector, String url) {
	    AESCryptoStreamFactory aesCryptoStreamFactory =
	      new AESCryptoStreamFactory.Builder(key, initializationVector)
	      .build();

	    // This contentType must be the same value that was provided to createFeedDocument.
	    String contentType = String.format("text/xml; charset=%s", StandardCharsets.UTF_8);

	    // The character set must be the same one that is specified in contentType.
	    try
	      (InputStream source = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8))) {
	        UploadSpecification uploadSpec =
	          new UploadSpecification.Builder(contentType, aesCryptoStreamFactory, source, url)
	          .build();

	        uploadHelper.upload(uploadSpec);
	      }
	    catch (CryptoException | HttpResponseException | IOException e) {
	      // Handle exception.
	    	
			System.out.print(e);

	    }
	  }

	  // key, initializationVector, and url are returned from createFeedDocument.
	  public void encryptAndUpload_fromPipedInputStream(String key, String initializationVector, String url) {
	    AESCryptoStreamFactory aesCryptoStreamFactory =
	      new AESCryptoStreamFactory.Builder(key, initializationVector)
	      .build();

	    // This contentType must be the same value that was provided to createFeedDocument.
	    String contentType = String.format("text/plain; charset=%s", StandardCharsets.UTF_8);

	    try
	      (PipedInputStream source = new PipedInputStream()) {
	        new Thread(
	          new Runnable() {
	          public void run() {
	            try
	              (PipedOutputStream feedContents = new PipedOutputStream(source)) {
	                // The character set must be the same one that is specified in contentType.
	                feedContents.write("my feed data\n".getBytes(StandardCharsets.UTF_8));
	                feedContents.write("more feed data".getBytes(StandardCharsets.UTF_8));
	              }
	            catch (IOException e) {
	              // Handle exception.
	            }
	          }
	        }).start();

	        UploadSpecification uploadSpec =
	          new UploadSpecification.Builder(contentType, aesCryptoStreamFactory, source, url)
	          .build();

	        uploadHelper.upload(uploadSpec);
	      }
	    catch (CryptoException | HttpResponseException | IOException e) {
	      // Handle exception.
			System.out.print(e);

	    }
	  }
	  
	  
	 
}

I have try to upload Inventory to Amazon with above code, the code is run but  response of the upload data is not showing

**Comment by MST1122** [comment]
@Bagavath96 are you also doing product listing with the feed?

**Comment by Bagavath96** [comment]
No, currently we are  try to upload inventory

**Comment by dovelover** [comment]
What's the format of uploading inventory using xml file?  T_T
This is the response I got after uploading the xml：
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>xxx</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>123</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>1</MessagesProcessed>
				<MessagesSuccessful>0</MessagesSuccessful>
				<MessagesWithError>2</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
			<Result>
				<MessageID>0</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>90215</ResultMessageCode>
				<ResultDescription>100% of the products in your file did not process successfully.</ResultDescription>
			</Result>
			<Result>
				<MessageID>1</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>99001</ResultMessageCode>
				<ResultDescription>A value is required for the "unit_count" field.</ResultDescription>
				<AdditionalInfo>
					<SKU>p_770038LB</SKU>
				</AdditionalInfo>
			</Result>
			<Result>
				<MessageID>1</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>99001</ResultMessageCode>
				<ResultDescription>A value is required for the "unit_count_type" field.</ResultDescription>
				<AdditionalInfo>
					<SKU>p_770038LB</SKU>
				</AdditionalInfo>
			</Result>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>`
