### ISSUE TITLE
GET_LEDGER_SUMMARY_VIEW_DATA is being generated for more than 24h

### ISSUE THREAD

**Issue by teb02** [amzn/selling-partner-api-docs#68]
**Update: the issue was fixed and then appeared again but with a bit another behaviour (check 3rd comment)**
GET_LEDGER_SUMMARY_VIEW_DATA was generated with default options and 60 days back start date. 
Report was created on 2020-10-24 18:54 UTC.
At the moment of 2020-10-25 24:00 UTC the report was still in progress status. So it was being generated for more than 24 hours.

It's probably stuck:

```
{
  "reportType": "GET_LEDGER_SUMMARY_VIEW_DATA"
  "processingStatus": "IN_PROGRESS"
  "marketplaceIds": array:6 [
    0 => "ATVPDKIKX0DER"
    1 => "A2EUQ1WTGCTBG2"
    2 => "A2ZV50J4W1RKNI"
    3 => "A1MQXOICRS2Z7M"
    4 => "A1AM78C64UM0Y8"
    5 => "A3H6HPSLHAK3XG"
  ]
  "reportId": "211807018559"
  "dataEndTime": "2020-10-23T18:52:48+00:00"
  "createdTime": "2020-10-24T18:54:34+00:00"
  "processingStartTime": "2020-10-24T18:54:40+00:00"
  "dataStartTime": "2020-08-25T18:52:48+00:00"
}
```

**Comment by teb02** [comment]
At the moment we see another issue with this report.

The report for 60 days returns empty data (just headers):

```{
  "reportType": "GET_LEDGER_SUMMARY_VIEW_DATA"
  "processingEndTime": "2020-10-27T11:54:30+00:00"
  "processingStatus": "DONE"
  "marketplaceIds": array:6 [
    0 => "ATVPDKIKX0DER"
    1 => "A2EUQ1WTGCTBG2"
    2 => "A2ZV50J4W1RKNI"
    3 => "A1MQXOICRS2Z7M"
    4 => "A1AM78C64UM0Y8"
    5 => "A3H6HPSLHAK3XG"
  ]
  "reportDocumentId": "amzn1.tortuga.3.5c334860-b8cf-47d5-b561-7fd1e478dfe7.T1AC82P36UWVQ9"
  "reportId": "213384018562"
  "dataEndTime": "2020-10-26T11:54:18+00:00"
  "createdTime": "2020-10-27T11:54:19+00:00"
  "processingStartTime": "2020-10-27T11:54:25+00:00"
  "dataStartTime": "2020-08-28T11:54:18+00:00"
}
```

The results just headers:
`Date	FNSKU	ASIN	MSKU	Title	Disposition	On Hand	FC Transfer	Receipts	Customer Shipments	Customer Returns	Vendor Returns	Warehouse Transfers	Found	Lost	Damaged	Disposed	Other Events	Location`

**Comment by teb02** [comment]
Now, the report is stuck under IN_QUEUE status:
```
{
  "reportType": "GET_LEDGER_SUMMARY_VIEW_DATA"
  "processingStatus": "IN_QUEUE"
  "marketplaceIds": array:6 [
    0 => "ATVPDKIKX0DER"
    1 => "A2EUQ1WTGCTBG2"
    2 => "A2ZV50J4W1RKNI"
    3 => "A1MQXOICRS2Z7M"
    4 => "A1AM78C64UM0Y8"
    5 => "A3H6HPSLHAK3XG"
  ]
  "reportId": "215085018565"
  "dataEndTime": "2020-10-29T15:59:22+00:00"
  __"createdTime": "2020-10-30T15:59:23+00:00"__
  "dataStartTime": "2020-10-25T15:59:22+00:00"
}
```
Pay attention to createdTime.
**And now it's 2020-10-30T21:30:23+00:00**

**Comment by teb02** [comment]
Closing the issue, looks like it started working :) Will reopen it if see any issues.

**Comment by webs-harsh-rana** [comment]
@teb02 IN_QUEUE Status is not working for me.

I get the following response every time I generate a report and get by report id.

"reportType": "GET_LEDGER_SUMMARY_VIEW_DATA",
    "dataStartTime": "2023-01-08T07:58:00+00:00",
    "dataEndTime": "2023-01-09T07:57:59+00:00",
    "createdTime": "2023-01-09T12:22:03+00:00",
    "processingStatus": "IN_QUEUE"
