### ISSUE TITLE
 Documents Helper  Report is not downloading 

### ISSUE THREAD

**Issue by Bagavath96** [amzn/selling-partner-api-docs#680]
package com.amazon.spapi.documents.Contoller;

import java.io.BufferedReader;
import java.io.IOException;

import com.amazon.spapi.documents.CompressionAlgorithm;
import com.amazon.spapi.documents.DownloadBundle;
import com.amazon.spapi.documents.DownloadHelper;
import com.amazon.spapi.documents.DownloadSpecification;
import com.amazon.spapi.documents.exception.CryptoException;
import com.amazon.spapi.documents.exception.HttpResponseException;
import com.amazon.spapi.documents.exception.MissingCharsetException;
import com.amazon.spapi.documents.impl.AESCryptoStreamFactory;

public class Download {
	 final DownloadHelper downloadHelper = new DownloadHelper.Builder().build();
	 
	    public void downloadAndDecrypt(String key, String initializationVector, String url, String compressionAlgorithm) {
	        AESCryptoStreamFactory aesCryptoStreamFactory =
	                new AESCryptoStreamFactory.Builder(key, initializationVector).build();
	 
	        DownloadSpecification downloadSpec = new DownloadSpecification.Builder(aesCryptoStreamFactory, url)
	                .withCompressionAlgorithm(CompressionAlgorithm.fromEquivalent(compressionAlgorithm))
	                .build();
	 
	        try (DownloadBundle downloadBundle = downloadHelper.download(downloadSpec)) {
	            // This example assumes that the downloaded document has a charset in the content type, e.g. 
	            // text/plain; charset=UTF-8
	            try (BufferedReader reader = downloadBundle.newBufferedReader()) {
	                String line;
	                do {
	                    line = reader.readLine();
	                    // Process the decrypted line.
	                } while (line != null);
	            }
	        } catch (CryptoException | HttpResponseException | IOException | MissingCharsetException e) {
	            // Handle exception here.
	        
	        }
	    }
}

I have Try to download report with help of Report API (https://sellingpartnerapi-eu.amazon.com/reports/2020-09-04/documents/DocumentID)
* After the response i have pass Key, IV,url,GZIP and Call the Below function to Download report  
dow.downloadAndDecrypt("ZFZkf8*****", "YT8*****","https://tortuga-prod-eu.s3-eu-west- ********", "GZIP");

The Download function is working but the file is not downloading kindly help us

**Comment by mingxin-yang** [comment]
You need to write line to file

**Comment by mingxin-yang** [comment]
@Bagavath96

**Comment by johnkw** [comment]
The pointless extra crypto is deprecated - switch over to https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#reportdocument and close this bug. @parvathm @jenilew
