### ISSUE TITLE
How to get past order details?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#684]
Hello,

I want to get the past **orders**. Do I need to use **orders api** or **reports api** (GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING or another report type) for this?

Could you help me for this?

Thanks

**Comment by nirmay** [comment]
Hi @arturll7,

I have found it is better to use report API, although the handshake is a bit involved to get historical orders.
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL report type provides necessary details on the order data.

Thanks

**Comment by arturll7** [comment]
Hi @nirmay,

Thank you very much for your answer. GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL report type is in the **order tracking reports**. In the reference, it says _"These order tracking reports are available in **North America (NA)** and **Europe (EU)**_."
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#order-tracking-reports

For far east marketplaces, do I need to use **Orders Api in order to get historical orders**? Do you have any idea for this?

Regards,

**Comment by ianrussel** [comment]
Take not also this reports api with reports type GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL will only return oders 30 days to current date. Where as of you use the orders api you can get all data starting from the beginning. In my situation, I can get all orders starting 2019 - up to now. But using reports API , I can only get the last 30 days

**Comment by arturll7** [comment]
hi @iamnsquared, I will use the Orders Api, thank you very much for your answer.
