### ISSUE TITLE
Set "redirect_uri" dynamically ? 

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#685]
As per this docs https://github.com/amzn/selling-partner-api-docs/blob/69a5a8662a6e44b8cbb4d8c04148e7e5ae89adc2/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

"A URI for redirecting the browser to your application. This must an OAuth Redirect URI that you specified when you registered your application. If you do not include the redirect_uri parameter, the default is the first OAuth Redirect URI that you specified when you registered your application."

We have windows and web application , we already defined **redirect_uri** when we created app.

But for windows app we need redirect uri to 127.0.0.1

So, we can capture authorization information on local machine.

**Comment by vikingcodes** [comment]
@ShivikaK @rugved1991 Please have a look into this issues

**Comment by charliecode** [comment]
@vikingcodes This is something I asked for at the very beginning but hasn't been implemented to date. In the long run it's really not necessary. I ended up closing out the original issue I created and instead added what could be done instead, which is honestly a much better practice anyways. Hopefully it can work for your use case too, I'm fairly certain it will. You can find it in the last comment @ #26.

**Comment by vikingcodes** [comment]
@charliecode Thanks
