### ISSUE TITLE
Is there a get method for /vendor/payments/v1/invoices

### ISSUE THREAD

**Issue by AlphanAksoyoglu** [amzn/selling-partner-api-docs#686]
The documentation specifies a POST method for /vendor/payments/v1/invoices,

There is no mention on how to GET the vendor invoices? 

Common sense tells me that this is supported but not documented in detail yet.

If a GET method is not implemented is there a way we can get the Vendor Central invoices through SP-API or MWS?

Thank you!

**Comment by ShivikaK** [comment]
Hello @AlphanAksoyoglu 

Thank you for raising this issue.

There is no operation to get the vendor invoices. The Vendor Payments API only supports allowing vendors to submit vendor invoices to request payment from Amazon for items shipped.

Vendors can verify the actual status of the original/updated version of the invoices via "Vendor Central > Payments > Invoices".

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/vendor-retail-procurement-apis-use-case-guide/vendor-retail-procurement-apis-use-case-guide.md#submit-invoices

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by AlphanAksoyoglu** [comment]
Hello @ShivikaK 

Thank you for your response. Is it planned to implement more GET methods in the future, regarding vendor reports? Accessing these reports are useful for Amazon Vendors to organize/analyse and bookkeep their financial statements?

Same goes for Date Range Reports (transaction itemized) in Seller Central. 

Thank you and all the best

-Alphan
