### ISSUE TITLE
Total count for orders

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#691]
Hi . Is there any way of just getting the total count for orders ? For total count I mean the sum of all orders . Currently the api returns only records with limit default  100.

Reports API is even not returning all orders, as it only limited to past 30 days.
Is it difficult or not possible to just add the total counts in /orders response ? For example

                {
                        "payload": {
                               "total_count_eversince": 2908988
                               "Orders": [
                                     ...........................
                               ]
                 
Or a simple endpoint `/orders/yourtotalorderseversince`

Thanks,

**Comment by hexrw** [comment]
I would also like to see a feature like this
