### ISSUE TITLE
Website workflow - Not redirected to callback

### ISSUE THREAD

**Issue by leoplct** [amzn/selling-partner-api-docs#695]
I have to initiate the Website workflow login for my MWS-SPAPI hybrid app. 

I have registred my application and added this OAuth Redirect URL
_https://www.example.com/en/sp_api/callback_
OAuth Login URI is blank
Btw, how can I add the localhost Redirect URI so that I can test locally?

Then the user goes to my website and click on this link
"https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=#{ENV['MWS_APP']}&redirect_uri=#{sp_auth_callback_url()}"

then it successfully approves the consent, but it's not redirected back to https://www.example.com/en/sp_api/callback

What am I missing?

**Comment by charliecode** [comment]
@leoplct You cannot add localhost directly as it's not allowed. You can however map a fake https url to your local host on you system and use that to test. I explain how to do this in the last comment at #26.

**Comment by leoplct** [comment]
Ok for localhost. I've added a public domain. Why is it redirected?

I see on Seller Central 
To complete authorization you must log in to MYwebsite and it redirects me to "Oauth login url" instead of "oauth redirect url"

**Comment by charliecode** [comment]
@leoplct Removing the version=beta will only work once your application is approved on the Marketplace Appstore and and therefore out of draft state. The login uri is not used during the website workflow, it's used for the Marketplace Appstore workflow to redirect a customer to your app when they find you on the Marketplace Appstore and click to signup from there.

**Comment by leoplct** [comment]
Ok, so why if I go to:
https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.XXXXX&redirect_uri=https://www.example.com/en/sp_api/callback

then i shows me 
https://sellercentral-europe.amazon.com/gp/mws/registration/registerSummary

instead of redirect me back to 

https://www.example.com/en/sp_api/callback (added as redirect URL in app registration page)

**Comment by charliecode** [comment]
@leoplct I'm not sure, don't know anything about your application, is it a hybrid application or a default implementation? I would try posting some pics of what's going on so others can help debug. If it's not a hybrid application then it could be a bug in which case you would need to open a support case.

**Comment by marconline** [comment]
You have to insert also the OAuth Login URL, otherwise there is a JS error in Amazon's page and you won't be redirected.
![app](https://user-images.githubusercontent.com/14978905/117034604-c534a180-ad03-11eb-9a0c-4e853d370c50.jpg)

**Comment by leoplct** [comment]
It's Hybrid. Oauth login URI it's present.

**Comment by marconline** [comment]
In the app registration setting you should put the ARN role.

**Comment by leoplct** [comment]
Good to know. I've opened a case to substitute it. 

So, for Amazon team the IAM ARN field should validate the presence of ":role" in the string.

**Comment by jimmy-ross-xapix** [comment]
> @leoplct Removing the version=beta will only work once your application is approved on the Marketplace Appstore and therefore out of draft state. The login uri is not used during the website workflow, it's used for the Marketplace Appstore workflow to redirect a customer to your app when they find you on the Marketplace Appstore and click to signup from there

hi, related to this - do you know if its ok to only proceed with the Website Workflow, or does the application always have to support the Marketplace Sign-Up flow too? Im building an application and would prefer to only support the Website Workflow but the documentation does not seem to explicitly state whether its ok to only support the Website Workflow and therefore not provide the login uri.

**Comment by charliecode** [comment]
Hello @jimmy-ross-xapix. In order for your website workflow to work in production, without the version=beta param, it must be out of draft state. In other words, it must be reviewed and approved by Amazon. Currently the only way that happens is by publishing to the Marketplace Appstore. The only other option would be a self authorization which is intended for your own account, not for an app which makes calls on behalf of other Selling Partners.

**Comment by jimmy-ross-xapix** [comment]
> Hello @jimmy-ross-xapix. In order for your website workflow to work in production, without the version=beta param, it must be out of draft state. In other words, it must be reviewed and approved by Amazon. Currently the only way that happens is by publishing to the Marketplace Appstore. The only other option would be a self authorization which is intended for your own account, not for an app which makes calls on behalf of other Selling Partners.

thanks for the reply. i was hoping to just have the Website Flow reviewed and approved by Amazon, not have to prepare and submit for both the Website flow and Marketplace Appstore flow. But i guess thats not possible then.

**Comment by charliecode** [comment]
@jimmy-ross-xapix I hear you, you're not alone in wishing for that functionality.

**Comment by chrisrueger** [comment]
Yes, we would also prefer to only support the Website Workflow (initiated from our webpage). 

To add to the conversation:
I can confirm that **both** the **OAuth Login URI** and the **OAuth Redirect URI** need to be populated. Otherwise the **Confirm**  button does not work and the page shows lots of javascript errors like this:

![image](https://user-images.githubusercontent.com/188422/119721426-6e863780-be6b-11eb-832a-3d69bd60f093.png)

The last error goes away after filling the OAuth Login URI too. 

Is there any hint, how to test the redirect with a localhost development environment? 
Does amazon recommend using services like https://ngrok.com/ or is there a different way?
