### ISSUE TITLE
error code ID: MD9000 inactive developer ID 

### ISSUE THREAD

**Issue by Sellcon** [amzn/selling-partner-api-docs#696]
Hello, 
I am register as a developer. My app has been approved and published, but my developer ID is inactive and third party sellers cannot authorize access for my app on their Seller Accounts. The error code ID: MD9000. Please if the developer team could advise.
This would be much appreciated.

**Comment by vikingcodes** [comment]
You using correct region or marketplaceId ?

@Sellcon Check following thread

https://github.com/amzn/selling-partner-api-docs/issues/647
https://github.com/amzn/selling-partner-api-docs/issues/545
https://github.com/amzn/selling-partner-api-docs/issues/342

**Comment by Sellcon** [comment]
Thanks, I see that I don't have oauth login uri and redirect uri. If my app has a published status is it possible to add oauth login uri / redirect uri ? What exactly does that mean? It is the https link to login to my app, isn't it?
Thanks

**Comment by Sellcon** [comment]
Thanks!
I added oauth login uri / redirect uri to the application. Please if the developer team could accept my app and unblock my developer ID for third party sellers. 
APP ID: amzn1.sellerapps.app.2958b63e-a98b-4031-a115-0d4890d11c1f
Thank you

**Comment by ShivikaK** [comment]
Hello @Sellcon 

Thank you for raising this issue.

Can you please open a support case with us and provide your developer ID information to investigate the issues you are facing?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Sellcon** [comment]
Hello, 

yes, I did it. I am waiting for an answer. If it's possible, please resolve this case as soon as possible.

Thank you

**Comment by Sellcon** [comment]
Hi!
My dev ID is active, thanks!

Then, I tried to download the data through the third party seller account and I have a problem- Access to Reports/ Finances is denied. 
Why? Do you have some idea?

I have included all boxes in the form for the developer application but now I don't have an access to the data by third party seller account.

Thanks

**Comment by Carlit-Auh** [comment]
@ShivikaK Hello i have the same problem, i open a issue #715, i don't undestand why is not working... 
I try everything... 

My developer ID : 863622224934
I try with a second Developer ID : 642422088485

My application ID : amzn1.sp.solution.aac3d3f6-2d6c-4d05-a803-a36cf9be2794

I just need to contact the amazon api to get orders and more information with a external API. 

I can't active my developer, can you help me ? 
Thank a lot

**Comment by ShivikaK** [comment]
> Hello,
> 
> could you answer here?

Hello @Sellcon 

I reviewed your case and Support is currently awaiting further information from you. Based on the screenshots provided in the case, it looks like you are making request to MWS Finances API.

Can you please provide requested details in the case for further investigation?

Thanks,
Shivika Khare
Selling Partner API Developer Support
