### ISSUE TITLE
getAuthorizationCode() for Auth MWS Token - MissingAuthenticationToken

### ISSUE THREAD

**Issue by leoplct** [amzn/selling-partner-api-docs#697]
I am following this guide to run SP-API using my existing MWS AUTH token: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md

When I run this code I get the error: **Access to requested resource is denied - MissingAuthenticationToken**. 
What am i missing? I just did step-by-step as suggested in the [doc](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md).

```
def self.get_authorization_code()
         selling_partner_id = 'A27XXXXXX'
        mws_auth_token     = 'amzn.mws.cXXXXX'
        endpoint           = "sellingpartnerapi-eu.amazon.com"
        url = "https://#{endpoint}/authorization/v1/authorizationCode"
        
        # Passing selling_partner_id, DeveloperId and MWS auth token as GET PARAMS
        return Faraday.get(url, {
            sellingPartnerId: selling_partner_id, 
            developerId: ENV['MWS_EU_DEVELOPER_ID'],
            mwsAuthToken: mws_auth_token
        })
end
```

**Comment by marconline** [comment]
Did you add the "X-Amz-Security-Token" header?
Check here: https://marco-tibaldeschi.medium.com/amazon-sp-api-auth-auth-demystified-ab3bc746729b

**Comment by leoplct** [comment]
I am generating the STS Token using

```
       client = Aws::STS::Client.new(
            region: aws_region,
            access_key_id: aws_access_key_id,
            secret_access_key: aws_secret_access_key
        )
        return client.assume_role(role_arn: sts_iam_role_arn, role_session_name: SecureRandom.uuid)
```

but I got 

`Aws::STS::Errors::AccessDenied (User: arn:aws:iam::123456789:user/selling-partner-api is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789:user/selling-partner-api)
`
if I got to AWS IAM console the policy for the user is 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::562177016314:role/SellingPartnerAPI"
        }
    ]
}
```

**Comment by leoplct** [comment]
Thank you very much for your guide but I still got a missing access_token.
I have checked all request headers and it looks ok.

**REQUEST** 

```
INFO -- request: GET https://sellingpartnerapi-eu.amazon.com/authorization/v1/authorizationCode?developerId=123456&mwsAuthToken=amzn.mws.XXXXX&sellingPartnerId=A27E0XXXXX
INFO -- request: host: "sellingpartnerapi-eu.amazon.com"
x-amz-date: "20210504T174042Z"
x-amz-security-token: "IQoJb3JpZ2luX2VjEHoaCWXXXX"
x-amz-content-sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4XXXXXXXX"
authorization: "AWS4-HMAC-SHA256 Credential=ASIAXXXXXXXX/20210504/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=0f251c3abca8a73a764671418d64a9291901086278b83574f6ea7f5a26982c30"
x-amz-access-token: "Atc|MQEBILWaaHz4CKGlzkSiMvrIqXXXXXXX"
user-agent: "App/1.0 (Language=Ruby)"
content-type: "application/json"
INFO -- response: Status 403
INFO -- response: date: "Tue, 04 May 2021 17:40:42 GMT"
content-type: "application/json"
content-length: "187"
connection: "keep-alive"
x-amzn-requestid: "2d51880c-6af3-4d93-9449-18e65b3e89e3"
x-amzn-errortype: "AccessDeniedException"
x-amz-apigw-id: "e0IMMGe-joEFsvA="
```


**Access token is missing in the request header.**

**Comment by ytcitsupport-jlin** [comment]
HI @leoplct 
Have you solved this issue?
I'm having the same problem as you.

**Comment by leoplct** [comment]
I haven't found a solution. Maybe because I have a wrong IAM ARN (user instead of role) in my app settings. I've asked support to change it, but they ask me to delete the production app. Which is crazy because we have live users and reviews.

**Comment by Mike-the-one** [comment]
Anyone got this working?

**Comment by marconline** [comment]
@Mike-the-one Yes, I did. Even if a perfectly working, PII-enabled MWS token is converted to a SP-API token which hasn't access to PII. :(
