### ISSUE TITLE
Vendor Central SP-API -  Carton labels for Retail Procurement?

### ISSUE THREAD

**Issue by gabeo671** [amzn/selling-partner-api-docs#698]
Is there a way to generate labels for Retail Procurement shipments or are they only available for Direct Fulfillment?

**Comment by ShivikaK** [comment]
Hello @gabeo671 

Thank you for raising this issue.

The shipment label generation via API is only available in Direct Fulfillment API. Retail API does not support this functionality.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by gabeo671** [comment]
Thanks Shivika.

**Comment by redtechflow** [comment]
Hi,

Are there any updates for Retail API ? If this does not support printing of Carton Label, then how do we print Carton Label via API?
