### ISSUE TITLE
Fetching order related informations issue.

### ISSUE THREAD

**Issue by dsokolowski** [amzn/selling-partner-api-docs#7]
Hi,

What is the best way to get payments and fulfillments informations related to a specified order? For example I see two endpoints dedicated to fulfillments for FBA and FBM stategies (fulfillment-outbound-api and merchant-fulfillment-api) but they do now allow me to fetch fulfillments filtered by either order or order line item. 

Also, which endpoint use to fetch payments informations for an order? Is this finances-api enpoint?

Please advice.

**Comment by evdeg** [comment]
Hi @dsokolowski, 

Thanks for your question. The best way to get payments information is with the [Selling Partner API for Finances](https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md). This is comparable to the [Finances API](http://docs.developer.amazonservices.com/en_US/finances/Finances_Overview.html) that is available in MWS today.

The best way to retrieve orders data is with the [Selling Partner API for Orders](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md). This is comparable to the MWS [Orders API](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_Overview.html).

In addition to these, you can also use the [Selling Partner API for Reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md) to retrieve data in bulk similar to the MWS [Reports API](http://docs.developer.amazonservices.com/en_US/reports/Reports_Overview.html). You can find all of the available reports and reportType values [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md). 

In particular, you may be interested in checking out the [order reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#order-reports) section and the [settlement reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#settlement-reports).

Please let us know if you have any other questions.

Regards,
Evan
