### ISSUE TITLE
[BUG] Headers are checked in case-sensitive way

### ISSUE THREAD

**Issue by marconline** [amzn/selling-partner-api-docs#700]
If I send a request specifying either "x-amz-access-token" or "x-amz-security-token" in different ways (e.g. X-Amz-Access-Token), those headers are ignored and an authorization error is generated. I don't know if this is related in some way to the Signature, but I guess the check should be case-insensitive.

**Comment by Jezza** [comment]
Weirdly, it doesn't seem to be _every_ endpoint.

I have an IAM user setup and I can use the `feeds/2020-09-04` API without issue.
But when I swap to the newer `feeds/2021-06-30` api, it spits out an authentication error.
