### ISSUE TITLE
Posted Date of ServiceFeeEvent

### ISSUE THREAD

**Issue by huaxuan** [amzn/selling-partner-api-docs#701]
Hello,
I know this is not the problem of SP-API, but I want to know do you have plan to improve it. 
Currently, for interface ListFinancialEvents, most event types have posted date field, so that I can get the exact time of these event. However, for ServiceFeeEvent, DebtRecoveryEvent and LoanSevicingEvent, there is not posted date in the response. 

Could you please provide the posted date information in the interface, like the transaction data we download for sellercentral?

Thank you.

Hope you can reply this problem.

**Comment by little-eyes** [comment]
I also encountered into this issue. I do need the PostedDate to associate with each item in the `ServiceFeeEvent`. Can we add it?
