### ISSUE TITLE
'createfulfillmentorder' in 'eu-west-1'...  marketplaceId  parameters don't work ？  [BUG] Documentation  

### ISSUE THREAD

**Issue by foxfiring** [amzn/selling-partner-api-docs#703]
ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\CreateFulfillmentOrderRequest::__set_state(array(
   'container' => 
  array (
    'marketplace_id' => 'A13V1IB3VIYZZH',
    'seller_fulfillment_order_id' => 'x29103854802',
    'displayable_order_id' => 'x29103854802',
    'displayable_order_date' => '2021-05-06T15:23:15Z',
    'displayable_order_comment' => 'message.......',
    'shipping_speed_category' => 'Standard',
    'delivery_window' => NULL,
.....................

i request   'marketplace_id' => 'A13V1IB3VIYZZH' **（FR）**,  but order created in **GB** ，and response 

'**This order cannot be fulfilled due to Brexit preventing cross-border fulfillment via EFN and Pan-European FBA starting December 28, 2020. To maintain your European sales, you will need to send products to fulfillment centers in the UK and the EU. See https://sellercentral-europe.amazon.com/gc/sell-online/brexit for more details**.'

**Comment by foxfiring** [comment]
@hyandell 
@rugved1991 
![image](https://user-images.githubusercontent.com/22993773/117272924-3a33e280-ae8e-11eb-8a0b-86aa2cd96579.png)
Does this parameter work?

**Comment by foxfiring** [comment]
repaired

**Comment by henrybroeker** [comment]
@foxfiring Did you fix this eventually? If yes, how? I have the same issue as it seems...

**Comment by sujing911** [comment]
@foxfiring did you repaired the problem? i have same issue

**Comment by sujing911** [comment]
@henrybroeker do you fix it?

**Comment by henrybroeker** [comment]
> @henrybroeker do you fix it?

@sujing911 I could not fix it until now. I reported this to Amazon and apparently I get this message because my primary/default marketplace is UK. But this cant be changed according to Amazon. Their advice was to create a new Account which of course has a big impact if you have a running business with everything set up. So this is not an option. The only hope is that this issue here gets enough attention so that Amazon will have a look at this on the API level.

**Comment by sujing911** [comment]
@henrybroeker It means if I won't create a new Account ,the issue couldnt repair.The api couldn't support now
