### ISSUE TITLE
Is customer ID / email available on getOrders endpoint?

### ISSUE THREAD

**Issue by cyrieu** [amzn/selling-partner-api-docs#705]
Hi all, we're building an Amazon application that helps sellers keep track of recurring purchases from the same customer - it seems like that data is available on the getOrderBuyerInfo endpoint, but the rate-limit of 1 per second means that if a seller has 900,000 orders, it would take 900,000 seconds (10.5 days) to get the customer IDs for all of them.

Is there a way to get this information faster?

**Comment by xbaha** [comment]
getOrderBuyerInfo returns null to me, is there a special authorization for this call?
