### ISSUE TITLE
SP-API Sandbox FBA PutTransportDetails getting 500 Internal Server Error

### ISSUE THREAD

**Issue by RJEspera** [amzn/selling-partner-api-docs#706]
Using the test parameters in the fulfillmentInboundV0.json file.  I'm getting a 500 Internal Server Error.  Is there a problem with the Sandbox on this particular endpoint?  It works on other endpoints like CreateInboundShipmentPlan, etc.  I noticed that this has the 'PUT' http verb as well.  Has anyone else experienced this problem?

"request": {
                  "parameters": {
                    "shipmentId": {
                      "value": "shipmentId1"
                    },
                    "body": {
                      "value": {
                        "IsPartnered": true,
                        "ShipmentType": "SP",
                        "TransportDetails": {
                          "PartneredSmallParcelData": {
                            "PackageList": [
                              {
                                "Dimensions": {
                                  "Length": 11,
                                  "Width": 11,
                                  "Height": 11,
                                  "Unit": "inches"
                                },
                                "Weight": {
                                  "Value": 11,
                                  "Unit": "pounds"
                                }
                              }
                            ],
                            "CarrierName": "string"
                          },
                          "NonPartneredSmallParcelData": {
                            "CarrierName": "USPS",
                            "PackageList": [
                              {
                                "TrackingId": "werwrwerwrwrer"
                              }
                            ]
                          },
                          "PartneredLtlData": {
                            "Contact": {
                              "Name": "Test1",
                              "Phone": "234-343-3434",
                              "Email": "abc@test.com",
                              "Fax": "234-343-3434"
                            },
                            "BoxCount": 1,
                            "SellerFreightClass": "50",
                            "FreightReadyDate": "2020-03-27",
                            "PalletList": [
                              {
                                "Dimensions": {
                                  "Length": 13,
                                  "Width": 13,
                                  "Height": 13,
                                  "Unit": "inches"
                                },
                                "Weight": {
                                  "Value": 13,
                                  "Unit": "pounds"
                                },
                                "IsStacked": true
                              }
                            ],
                            "TotalWeight": {
                              "Value": 13,
                              "Unit": "pounds"
                            },
                            "SellerDeclaredValue": {
                              "CurrencyCode": "USD",
                              "Value": 20
                            }
                          },
                          "NonPartneredLtlData": {
                            "CarrierName": "USPS",
                            "ProNumber": "3746274"
                          }
                        }
                      }
                    }
                  }
                },

**Comment by kingsun-he** [comment]
I met the same problem. But after I used the real host, not sandbox, It worked.

**Comment by bxb100** [comment]
same

**Comment by allenlin868** [comment]
> I met the same problem. But after I used the real host, not sandbox, It worked.

How did you solve it?I used the example parameter, which now returns the information 'Data is invalid. Please check'
