### ISSUE TITLE
listFinancialEventsByGroupId with postedAfter and postedBefore params

### ISSUE THREAD

**Issue by taskeenfatima** [amzn/selling-partner-api-docs#708]
With MWS Finances API it was possible to request financial events list with postedAfter and postedBefore params along with event group Id, but the selling partner API does not support these 3 together

The listFinancialEventsByGroupId request does not support postedAfter and postedBefore, which means we have to process all data associated to a group, every time from the day 1 till 15 or so days

While the listFinancialEvents response does not return event group id, so we cannot relate an event group to its events

Some prompt help will be highly appreciated

**Comment by marvs** [comment]
We also have the same issue causing us problems in migrating to SP-API.

**Comment by kk-wdt** [comment]
I suffer in this trouble too!
