### ISSUE TITLE
/vendor/orders/v1/purchaseOrders returns only the partyId for buyingParty, sellingParty, shipToParty and billToParty

### ISSUE THREAD

**Issue by darcome** [amzn/selling-partner-api-docs#709]
Good morning,

when I call the /vendor/orders/v1/purchaseOrders endpoint, the buyingParty, sellingParty, shipToParty and billToParty properties only contain the partyId and no address and no taxInfo.

What am I doing wrong? Is there some options I have to set?

Or, in any case, is there a way to get full party Info given its partyId?

Thanks in advance

**Comment by aaronb-cg** [comment]
I wanted to know this too, it's not made clear anywhere, however I _think_ that for the most part the party IDs refer to Amazon warehouses which can be looked up from this list:
https://selleressentials.com/amazon/amazon-fulfillment-center-locations/

**Comment by rugved1991** [comment]
Hi @darcome @aaronb-cg ,

The address and tax details are only returned for EU/IN region. For NA, you would only receive partyId in the response.
Please refer to the country specific business requirements section mentioned in the use case guide.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/vendor-retail-procurement-apis-use-case-guide/vendor-retail-procurement-apis-use-case-guide.md#country-specific-business-requirements


Thanks,
Rugved
Solutions Architect, SP API

**Comment by aaronb-cg** [comment]
Hi @rugved1991 ,

Thanks for your response but I'm afraid that does not answer the question.
The guide you have linked simply states:

> Ship to Party: (Europe) The assigned party ID for the ship to party

We need an address to stick on a box to ship to Amazon. How do we convert a Party ID to an actual address?
Are they, as I suspect, an Amazon Fulfillment Centre code?

**Comment by LazyCircles** [comment]
Hi,
I'm facing the same issue, is there anyway to retrive the shippment details for the given party ID? 
I could create an auxiliar table but that would not be a good solution...
Thank You

**Comment by ahlmackie** [comment]
+1 same issue. Would be good if the mods/anyone knows how to call/get the addresses using the partyId?

**Comment by scorpionbonus** [comment]
Hi everyone, i'm also in this "quest", to get the invoice information for the delivered orders. The tons of information are useless, because there is no conection, only try/result for hundreds of options.

However does anyone of you reached the "Holy grail" ??

I'm trying https://sellingpartnerapi-eu.amazon.com/vendor/directFulfillment/orders/v1/purchaseOrders it gives me allways 403 forbidden. Is this the correct path to get the invoice information?

**Comment by lw-andrewsmith** [comment]
Were looking at Vendor UK (eu-west-1) endpoints and have the same issue address is not returned meaning we can't tell the client where to ship it to.

**Comment by xudongding** [comment]
The same issue. Has this issue resolved?

**Comment by MktpStar** [comment]
same here
@xudongding have you found a solution? :)

**Comment by xudongding** [comment]
> same here @xudongding have you found a solution? :)

As a temporary solution, I imported the Amazon Fulfillment Center address list got from the amazon customer service team to the database. The returned party ID is always Amazon Fulfillment Center ID, such as YYZ3, PHX5. Then you can get the address from the database by party ID.

**Comment by MktpStar** [comment]
@xudongding Thanks Daniel, that's helpful.
how about invoicing? 
how do we get the Amazon company name and VAT ID from "PHX5"?

is this a correct assumption : "an order delivered to a warehouse in Spain has to be invoiced on the Amazon Spain entity" ?

**Comment by xudongding** [comment]
Hi @MktpStar ,
In my case, the ship to party ID, the bill to party ID and the buying party ID are the same, and there is no need to invoice.
I suggest you open a case to the Amazon customer service team for advise.

**Comment by MktpStar** [comment]
I did, but sadly they seem to not understand the problem at all.
if anyone has a solution , please do share.

**Comment by xudongding** [comment]
[Amazon_North_America_Fulfillment_Center_Address_List.csv](https://github.com/amzn/selling-partner-api-docs/files/9299175/Amazon_North_America_Fulfillment_Center_Address_List.csv)
This address list might be helpful.

**Comment by MktpStar** [comment]
that is very helpful.
is there a similar .csv for the EU fulfillment centers?

Thanks again!

**Comment by xudongding** [comment]
Just open a case on Amazon Vendor Central and ask for it.



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 10, 2022 18:57 PM
To: ***@***.***&gt;;
Cc: "Daniel ***@***.******@***.***&gt;;
Subject: Re: [amzn/selling-partner-api-docs] /vendor/orders/v1/purchaseOrdersreturns only the partyId for buyingParty, sellingParty, shipToParty andbillToParty (#709)




 
that is very helpful.
 is there a similar .csv for the EU fulfillment centers?
 
Thanks again!

**Comment by umarzahid028** [comment]
Hi everyone, 
if anyone found the solution, please let me know 
thanks

**Comment by MktpStar** [comment]
@umarzahid028 - there is only a solution: build your own database with Amazon parties, and when you process the orders you match the amazon warehouse code from the order with full details you already have in your database.
For invoices, any warehouse has a single VAT ID
