### ISSUE TITLE
Can the application not be published and used normally in the draft state?

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#711]
Our application only wants to be used by our own seller account, and does not want to be used by a third party, then can the application not be published and used in a draft state?

I've managed to successfully configure, on one of the Seller accounts (SELLER_1), the new SPApi integration.
I followed the Self Authorization workflow and I am now able to correctly authenticate and perform API calls on SELLER_1. 

I am now trying to use the same developer account and the same app to perform SPApi calls on a different SELLER_2, using the Authorization API. our OAuth Authorization URI has the flag version=beta as it is our draft application that is being authorized by the seller accounts.

Can I keep the app in a draft state without publishing it?

**Comment by vikingcodes** [comment]
@NancyLin On app draft state you can do self authorization and can call you own seller account information like own order, own reports.

But if you want call other seller's information like order, reports etc. then you need to publish you app and then seller need to authorize your app.

**Comment by NancyLin** [comment]
> @NancyLin On app draft state you can do self authorization and can call you own seller account information like own order, own reports.
> 
> But if you want call other seller's information like order, reports etc. then you need to publish you app and then seller need to authorize your app.
> 
> After then you can call other seller's information via SPAPI.

Can I always stay in the draft state and use the OAuth Authorization URI that has the flag version=beta, and our other seller can authorize our app.

We don't want the third part seller to authorize our app.

**Comment by nodisk8800** [comment]
Application in draft state can call any api,get any data,no any restrictions.
But it not list in the app marketplace.may be few seller know your application.

**Comment by NancyLin** [comment]
> Application in draft state can call any api,get any data,no any restrictions.
> But it not list in the app marketplace.may be few seller know your application.

We don't want to let other sellers know about our application. We just need our own seller to authorize our app. Can we always stay our application in a draft state? There should be no adverse effects, right? For example, the validity period of the authorization refresh token is very short.

**Comment by swaroopsaurav** [comment]
Hey @NancyLin,

Were you able to the pull the data for your clients while the application is in draft state? We are also considering the same but want to check if there are any API restrictions for draft applications?

**Comment by biancahuluban** [comment]
So this is the only solution for having one developer used for calling SP api operations for multiple seller accounts?

We want to do this too: to use the same developer id for multiple sellers but we don t want our app to be available in the marketplace.

Do you have Pii role assigned to develooer, I wonder if the restricted data is working too to be accessed via the so api op for multilple sellers.

**Comment by npiasecki** [comment]
Has anyone figured this out? We only have a handful of clients, and I'd rather not just anyone be able to install the app. Did you just leave it in Draft forever?

**Comment by npiasecki** [comment]
I ended up just going through the whole process and having it listed. There doesn't seem to be a direct equivalent of, say, Shopify's "public, but unlisted" app. It wasn't pleasant. 

Over at https://github.com/amzn/selling-partner-api-docs/issues/2064 someone suggests leaving it in Draft is fine *if* you don't have existing MWS authorizations to migrate over.

**Comment by moltar** [comment]
Does not appear to be fine.

One of my clients got the following notice: https://github.com/amzn/selling-partner-api-docs/issues/2038

**Comment by windrainw** [comment]
> I ended up just going through the whole process and having it listed. There doesn't seem to be a direct equivalent of, say, Shopify's "public, but unlisted" app. It wasn't pleasant.
> 
> Over at #2064 someone suggests leaving it in Draft is fine _if_ you don't have existing MWS authorizations to migrate over.

The doc https://developer-docs.amazon.com/sp-api/changelog/application-authorization-limits-and-listing-restrictions said draft status app can oauth 25 sellers, is that right? if I oauth 25 sellers , Does it cause store related punished?

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
