### ISSUE TITLE
Deprecation of "Other" from 7th May

### ISSUE THREAD

**Issue by tswapnil** [amzn/selling-partner-api-docs#712]
I received the following email - 
Dear Seller,

 

We are writing to inform you about an important change in the ship confirmation process for ‘Self Ship’ orders.

 

Effective 7th May 2021, you will no longer see “Other” as an option in the carrier list while ship confirming your Self Ship order in Seller Central. You will be required to use one of the integrated carrier to confirm and deliver Self Ship orders. This will be applicable across all ship confirmation methods– Single and Bulk order processing on ‘Manage Orders’ page, bulk confirmation using ‘Shipping Confirmation file upload’ and MWS API.

 

Following are the benefits of using integrated carriers:

 

a) customers can conveniently track their package status

b) reduced customer contacts

c) improved seller feedback ratings

d) faster order disbursement

e) Improved Valid Tracking Rate (VTR) of seller

 

Currently, Amazon integrated carriers for Self Ship orders include but are not limited to the following:

Blue Dart, Bombax, Delhivery, DHL, Dotzot, DTDC, FedEx, First Flight, India Post, Rivigo, SafeExpress, Ship Delight, Ship Economy, Shree Maruti Courier, Shree Tirupati Courier, Spoton, The Professional Couriers, Xpressbees Aramex, UPS, USPS, Yanwen, Yun Express, 4PX, ALLJOY, Cart2India, China Post, ICC Worldwide, Ship Global

 

If you choose to use any other carrier, please share the carrier name & other details in the form below

https://survey-az.tfaforms.net/2394

 

In case you are self delivering orders, you are required to follow the below steps:

(a)    Use the Amazon Delivery App to update pickup and delivery scans for all Self Ship orders

(b)   Use the ‘Buy Shipping’ option on the order details page to confirm orders

 

Please refer the Amazon Delivery App and Buy Shipping guide for more information here.

 

In case of any queries or feedback, please share it through this link à https://survey-az.tfaforms.net/2395

 

Thanks,

Seller Performance team

-----------------------------------------------------------------------
I currently use Feeds API to update Order Statuses . 
Would this change also impact our ability to provide "Others" carrier programmatically ? 
What are the alternatives available in SP-API that would allow us to continue process orders
via self-ship (We have a contract with a carrier who is not on the integrated carrier's list and so 
we would like to continue using their services )?  I have requested seller support to add them to the list but they do not have a time estimate for when would they be able to add them as integrated carrier . 
I am confused if this change impacts the SP-API as well ?

**Comment by tswapnil** [comment]
Thanks @nodisk8800 . Does this mean that "Others" is not being deprecated from CarrierCode enumeration list ?

**Comment by nodisk8800** [comment]
"Other" is  in the CarrierCode enumeration list .

**Comment by nodisk8800** [comment]
##################################################
    # Carrier Code element
    ##################################################
    
	-->
	<xsd:element name="CarrierCode">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="USPS"/>
				<xsd:enumeration value="UPS"/>
				<xsd:enumeration value="UPSMI"/>
				<xsd:enumeration value="FedEx"/>
				<xsd:enumeration value="DHL"/>
				<xsd:enumeration value="Fastway"/>
				<xsd:enumeration value="GLS"/>
				<xsd:enumeration value="GO!"/>
				<xsd:enumeration value="Hermes Logistik Gruppe"/>
				<xsd:enumeration value="Royal Mail"/>
				<xsd:enumeration value="Parcelforce"/>
				<xsd:enumeration value="City Link"/>
				<xsd:enumeration value="TNT"/>
				<xsd:enumeration value="Target"/>
				<xsd:enumeration value="SagawaExpress"/>
				<xsd:enumeration value="NipponExpress"/>
				<xsd:enumeration value="YamatoTransport"/>
				<xsd:enumeration value="DHL Global Mail"/>
				<xsd:enumeration value="UPS Mail Innovations"/>
				<xsd:enumeration value="FedEx SmartPost"/>
				<xsd:enumeration value="OSM"/>
				<xsd:enumeration value="OnTrac"/>
				<xsd:enumeration value="Streamlite"/>
				<xsd:enumeration value="Newgistics"/>
				<xsd:enumeration value="Canada Post"/>
				<xsd:enumeration value="Blue Package"/>
				<xsd:enumeration value="Chronopost"/>
				<xsd:enumeration value="Deutsche Post"/>
				<xsd:enumeration value="DPD"/>
				<xsd:enumeration value="La Poste"/>
				<xsd:enumeration value="Parcelnet"/>
				<xsd:enumeration value="Poste Italiane"/>
				<xsd:enumeration value="SDA"/>
				<xsd:enumeration value="Smartmail"/>
				<xsd:enumeration value="FEDEX_JP"/>
				<xsd:enumeration value="JP_EXPRESS"/>
				<xsd:enumeration value="NITTSU"/>
				<xsd:enumeration value="SAGAWA"/>
				<xsd:enumeration value="YAMATO"/>
				<xsd:enumeration value="BlueDart"/>
				<xsd:enumeration value="AFL/Fedex"/>
				<xsd:enumeration value="Aramex"/>
				<xsd:enumeration value="India Post"/>
				<xsd:enumeration value="Professional"/>
				<xsd:enumeration value="DTDC"/>
				<xsd:enumeration value="Overnite Express"/>
				<xsd:enumeration value="First Flight"/>
				<xsd:enumeration value="Delhivery"/>
				<xsd:enumeration value="Lasership"/>
				<xsd:enumeration value="Yodel"/>
				<xsd:enumeration value="Other"/>
				<xsd:enumeration value="Amazon Shipping"/>
				<xsd:enumeration value="Seur"/>
				<xsd:enumeration value="Correos"/>
				<xsd:enumeration value="MRW"/>
				<xsd:enumeration value="Endopack"/>
				<xsd:enumeration value="Chrono Express"/>
				<xsd:enumeration value="Nacex"/>
				<xsd:enumeration value="Otro"/>
				<xsd:enumeration value="Correios"/>
				<xsd:enumeration value="Toll Global Express"/>
				<xsd:enumeration value="China Post"/>
				<xsd:enumeration value="AUSSIE_POST"/>
				<xsd:enumeration value="EUB"/>
				<xsd:enumeration value="Australia Post"/>
				<xsd:enumeration value="Yun Express"/>
				<xsd:enumeration value="Fastway"/>
				<xsd:enumeration value="4PX"/>
				<xsd:enumeration value="YANWEN"/>
				<xsd:enumeration value="SF Express"/>
				<xsd:enumeration value="BRT"/>
				<xsd:enumeration value="AustraliaPost-Consignment"/>
                                <xsd:enumeration value="AustraliaPost-ArticleId"/>
                                <xsd:enumeration value="Sendle"/>
                                <xsd:enumeration value="CouriersPlease"/>
				<xsd:enumeration value="A-1"/>
				<xsd:enumeration value="AAA Cooper"/>
				<xsd:enumeration value="ABF"/>
				<xsd:enumeration value="ALLJOY"/>
				<xsd:enumeration value="Aras Kargo"/>
				<xsd:enumeration value="Arkas"/>
				<xsd:enumeration value="Arrow XL"/>
				<xsd:enumeration value="Asendia"/>
				<xsd:enumeration value="Asgard"/>
				<xsd:enumeration value="Assett"/>
				<xsd:enumeration value="AT POST"/>
				<xsd:enumeration value="ATS"/>
				<xsd:enumeration value="Balnak"/>
				<xsd:enumeration value="Beijing Quanfeng Express"/>
				<xsd:enumeration value="Best Buy"/>
				<xsd:enumeration value="Best Express"/>
				<xsd:enumeration value="BJS"/>
				<xsd:enumeration value="Bombax"/>
				<xsd:enumeration value="Cart2India"/>
				<xsd:enumeration value="CDC"/>
				<xsd:enumeration value="CELERITAS"/>
				<xsd:enumeration value="CEVA"/>
				<xsd:enumeration value="Ceva Lojistik"/>
				<xsd:enumeration value="Cititrans"/>
				<xsd:enumeration value="Coliposte"/>
				<xsd:enumeration value="Colissimo"/>
				<xsd:enumeration value="Conway"/>
				<xsd:enumeration value="Correos Express"/>
				<xsd:enumeration value="Couriers Please"/>
				<xsd:enumeration value="CTTExpress"/>
				<xsd:enumeration value="DB Schenker"/>
				<xsd:enumeration value="DHL eCommerce"/>
				<xsd:enumeration value="DHL Express"/>
				<xsd:enumeration value="DHL Freight"/>
				<xsd:enumeration value="DHL Home Delivery"/>
				<xsd:enumeration value="DHL Kargo"/>
				<xsd:enumeration value="DHL-Paket"/>
				<xsd:enumeration value="DHLPL"/>
				<xsd:enumeration value="Digital Delivery"/>
				<xsd:enumeration value="DirectLog"/>
				<xsd:enumeration value="Dotzot"/>
				<xsd:enumeration value="DSV"/>
				<xsd:enumeration value="DX Freight"/>
				<xsd:enumeration value="ECMS"/>
				<xsd:enumeration value="Ecom Express"/>
				<xsd:enumeration value="Emirates Post"/>
				<xsd:enumeration value="Energo"/>
				<xsd:enumeration value="Envialia"/>
				<xsd:enumeration value="Estafeta"/>
				<xsd:enumeration value="Estes"/>
				<xsd:enumeration value="Fedex Freight"/>
				<xsd:enumeration value="Fillo Kargo"/>
				<xsd:enumeration value="First Flight China"/>
				<xsd:enumeration value="First Mile"/>
				<xsd:enumeration value="Gati"/>
				<xsd:enumeration value="GEL Express"/>
				<xsd:enumeration value="geodis"/>
				<xsd:enumeration value="Geodis Calberson"/>
				<xsd:enumeration value="Geopost Kargo"/>
				<xsd:enumeration value="Hermes Einrichtungsservice"/>
				<xsd:enumeration value="Home Logistics"/>
				<xsd:enumeration value="Hongkong Post"/>
				<xsd:enumeration value="Horoz Lojistik"/>
				<xsd:enumeration value="HS code"/>
				<xsd:enumeration value="Hunter Logistics"/>
				<xsd:enumeration value="ICC Worldwide"/>
				<xsd:enumeration value="IDS Netzwerk"/>
				<xsd:enumeration value="InPost"/>
				<xsd:enumeration value="iParcel"/>
				<xsd:enumeration value="Japan Post"/>
				<xsd:enumeration value="JCEX"/>
				<xsd:enumeration value="Kargokar"/>
				<xsd:enumeration value="Kuehne+Nagel"/>
				<xsd:enumeration value="Landmark"/>
				<xsd:enumeration value="Metro Kargo"/>
				<xsd:enumeration value="MNG Kargo"/>
				<xsd:enumeration value="Narpost Kargo"/>
				<xsd:enumeration value="Nexive"/>
				<xsd:enumeration value="Ninjavan"/>
				<xsd:enumeration value="Old Dominion"/>
				<xsd:enumeration value="OneWorldExpress"/>
				<xsd:enumeration value="Panther"/>
				<xsd:enumeration value="Pilot"/>
				<xsd:enumeration value="Pilot Freight"/>
				<xsd:enumeration value="Polish Post"/>
				<xsd:enumeration value="Post NL"/>
				<xsd:enumeration value="PostNord"/>
				<xsd:enumeration value="PTT Kargo"/>
				<xsd:enumeration value="PUROLATOR"/>
				<xsd:enumeration value="QExpress"/>
				<xsd:enumeration value="Qxpress"/>
				<xsd:enumeration value="R+L"/>
				<xsd:enumeration value="Raben Group"/>
				<xsd:enumeration value="Rhenus"/>
				<xsd:enumeration value="Rieck"/>
				<xsd:enumeration value="Rivigo"/>
				<xsd:enumeration value="Roadrunner"/>
				<xsd:enumeration value="Safexpress"/>
				<xsd:enumeration value="Saia"/>
				<xsd:enumeration value="Seino"/>
				<xsd:enumeration value="SEINO TRANSPORTATION"/>
				<xsd:enumeration value="Selem Kargo"/>
				<xsd:enumeration value="Self Delivery"/>
				<xsd:enumeration value="SENDLE"/>
				<xsd:enumeration value="SFC"/>
				<xsd:enumeration value="Ship Delight"/>
				<xsd:enumeration value="Ship Global US"/>
				<xsd:enumeration value="ShipEconomy"/>
				<xsd:enumeration value="ShipGlobal"/>
				<xsd:enumeration value="Shree Maruti Courier"/>
				<xsd:enumeration value="Shree Tirupati Courier"/>
				<xsd:enumeration value="Shunfeng Express"/>
				<xsd:enumeration value="Singapore Post"/>
				<xsd:enumeration value="South Eastern Freight Lines"/>
				<xsd:enumeration value="Speedex"/>
				<xsd:enumeration value="Spoton"/>
				<xsd:enumeration value="StarTrack-ArticleID"/>
				<xsd:enumeration value="StarTrack-Consignment"/>
				<xsd:enumeration value="STO Express"/>
				<xsd:enumeration value="Tezel Lojistik"/>
				<xsd:enumeration value="The Professional Couriers"/>
				<xsd:enumeration value="TIPSA"/>
				<xsd:enumeration value="TNT Kargo"/>
				<xsd:enumeration value="TNTIT"/>
				<xsd:enumeration value="Total Express"/>
				<xsd:enumeration value="Trackon"/>
				<xsd:enumeration value="TransFolha"/>
				<xsd:enumeration value="Tuffnells"/>
				<xsd:enumeration value="UPS Freight"/>
				<xsd:enumeration value="Urban Express"/>
				<xsd:enumeration value="VIR"/>
				<xsd:enumeration value="VNLIN"/>
				<xsd:enumeration value="WanbExpress"/>
				<xsd:enumeration value="Watkins and Shepard"/>
				<xsd:enumeration value="Whizzard"/>
				<xsd:enumeration value="WINIT"/>
				<xsd:enumeration value="XDP"/>
				<xsd:enumeration value="XPO Freight"/>
				<xsd:enumeration value="Xpressbees"/>
				<xsd:enumeration value="YDH"/>
				<xsd:enumeration value="Yellow Freight"/>
				<xsd:enumeration value="YTO Express"/>
				<xsd:enumeration value="Yunda Express"/>
				<xsd:enumeration value="ZTO Express"/>
				<xsd:enumeration value="Tourline"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

**Comment by tswapnil** [comment]
Thanks @nodisk8800 . I am confused as to why did they send an email saying that all other carriers are being deprecated starting 7th May ?
