### ISSUE TITLE
SP API application client is not in drafted or published state not able to test API calls

### ISSUE THREAD

**Issue by thomasazz** [amzn/selling-partner-api-docs#714]
Followed all the steps stated in the documentation but not able to test or use SP API client. The application client condition is set to Eraser. While creating client Role ARN is used and its a hybrid application allowing both MWS and SP API. And also not able to find the option to delete the application client.

Application Client
![Amazon](https://user-images.githubusercontent.com/83658262/117568811-f33b2c80-b0db-11eb-9877-987dd7ce860e.png)

Registration Form
![Amazon2](https://user-images.githubusercontent.com/83658262/117568879-49a86b00-b0dc-11eb-9e3a-9a3f1f70a31c.png)

**Comment by nodisk8800** [comment]
drafted  state can call API and get the data.

**Comment by thomasazz** [comment]
@nodisk8800 condition is Eraser not Drafted that is may main concern, i did open a ticket with amazon support didn't get a reply yet.
