### ISSUE TITLE
SPDC300 Error

### ISSUE THREAD

**Issue by bdolan19** [amzn/selling-partner-api-docs#719]
Hi all,

I am getting an error code (SPDC300) while creating a SP application in seller central. My developer profile has already been approved. Here is the full error - 

Something went wrong. Please try again at a later time If the problem persists, please contact Seller Support and provide them with the following information: SPDC300.

I have already opened a case on Seller Central. Here is the Case ID - 8269846911

Any assistance would be greatly appreciated as we have been working on this for some time now and have not received a response from Seller Central.

**Comment by ShivikaK** [comment]
Hello @bdolan19 

Thank you for raising this issue.

Can you please share a screenshot showing the error? Is this error coming up when you try to create an application or list the application to be published in appstore?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by bdolan19** [comment]
> Hello @bdolan19
> 
> Thank you for raising this issue.
> 
> Can you please share a screenshot showing the error? Is this error coming up when you try to create an application or list the application to be published in appstore?
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

The error is coming up when we try to list the application to be published in the Appstore.

Attached is a screenshot of the error.
![Screenshot (2)](https://user-images.githubusercontent.com/83983235/117895544-8f0b9a80-b28c-11eb-86e6-1b282e23bfc5.png)
