### ISSUE TITLE
How can I get a list of the items I'm selling at Amazon mall

### ISSUE THREAD

**Issue by zhumo1998** [amzn/selling-partner-api-docs#720]
I want to get the list of all the products I'm selling through SP API, but I can't find the relevant interface in the API. Can someone tell me how to send the request? Thank you very much.

**Comment by nodisk8800** [comment]
这个也要问啊?自己看文档就好了.

**Comment by zhumo1998** [comment]
> 这个也要问啊？自己看文档就好了。

I've read the documents, but I don't find the interface to query the list of products I'm selling. Although I can retrieve the relevant product information through getcatalogitem or getinventorysummaries, the data is not what I'm selling.Can you help me?

**Comment by nodisk8800** [comment]
好好看一下 Report API,这里有你想要的数据.

**Comment by zhumo1998** [comment]
> 报告API，这里有你想要的数据。

 好的，谢谢 我区调用获取试试
