### ISSUE TITLE
Access to requested resource is denied. Unauthorized [BUG] Documentation

### ISSUE THREAD

**Issue by lantaoGitHub** [amzn/selling-partner-api-docs#723]
Hello
When I call the order interface, I return access to requested resource is denied。

The IAM policy I configured is ：
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "execute-api:Invoke",
      "Resource": "arn:aws:execute-api:*:*:*"
    }
  ]
}

Request parameters：
Sending request for https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2021-05-03T09:00:00&OrderStatuses=Pending&MarketplaceIds=A1PA6795UKMFR9&CreatedBefore=2021-05-01T09:00:00 
HEADERS 
host: sellingpartnerapi-eu.amazon.com
Authorization: AWS4-HMAC-SHA256 Credential=AKIAJ**********/20210511/eu-west-1/execute-api/aws4_request, SignedHeaders=accept;content-type;host;x-amz-access-token;x-amz-date, Signature=7f2c9836f09cce1c7dacfb30d3a0cc2a1c2ab1592b4b2d9fd7c8577c309ef322
x-amz-access-token: Atza|IwEBIBKhjqZT29gKBMFppHGVnzsYD3gnCYBl*****
content-type: application/json
x-amz-date: 20210511T094153Z
Accept: application/json

response： 
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
x-amzn-RequestId: c546b010-28a3-4b92-8795-ba3004fab834
x-amzn-ErrorType: AccessDeniedException
x-amz-apigw-id: fKGoAFQ0DoEFkdw=
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
What is the reason for this？

**Comment by lantaoGitHub** [comment]
@sellerjd  Hello, can you take a look

**Comment by nodisk8800** [comment]
对了,你的所有参数值 都要进行 encode.
特别是时间中有 T 有: 还有空格.

群里近期问这个访问不了的情况还是很多的.

**Comment by lantaoGitHub** [comment]
@nodisk8800 你好能加一下联系方式嘛，请教你写问题，感谢。

**Comment by lantaoGitHub** [comment]
> 对了,你的所有参数值 都要进行 encode.
> 特别是时间中有 T 有: 还有空格.
> 
> 群里近期问这个访问不了的情况还是很多的.

你好，我调用订单别的接口也是这样，能加一下联系方式嘛，请教一下问题。

**Comment by nodisk8800** [comment]
你自己搜一下QQ群,看看能不能找到我们....

**Comment by B1essedSou1** [comment]
hi sir! Are you solve problem? Because i am stuck so much too...

**Comment by lantaoGitHub** [comment]
> hi sir! Are you solve problem? Because i am stuck so much too...

我已经解决了，首先我是使用IAM USER 创建的开发者APP，然后 AMAZON 开发者在别的案例中说可以将以下配置配到用户上就可以了。

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "execute-api:Invoke",
      "Resource": "arn:aws:execute-api:*:*:*"
    }
  ]
}

**Comment by B1essedSou1** [comment]
HI! I was used new policy and result are same...your app registered by using User ARN? if yeah, then you dont create a role? i mean when you directly attach policy to user you finish setup AWS and go to amazon and create new app?
