### ISSUE TITLE
Orders Report No marketplace id

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#724]
Hi, when creating reports for orders with report type `GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL`, the marketplaceids are missing, its convenient if the marketplace id is also included in response. Or maybe I missed something ?

                {
                        "amazon-order-id": "352-4818523-776XX102",
                        "merchant-order-id": "307-4XX8524-70969TYY02",
                        "purchase-date": "2021-05-11T01:01:48+00:00",
                        "last-updated-date": "2021-05-11T01:55:45+00:00",
                        "order-status": "Pending",
                        "fulfillment-channel": "Amazon",
                        "sales-channel": "Amazon.de",
                        "order-channel": "",
                        "ship-service-level": "Expedited",
                        "product-name": "Impact "
                        "sku": "4Z-XYZ",
                        "asin": "BWERTRDCBSSDSDS",
                        "item-status": "Unshipped",
                        "quantity": "1",
                        "currency": "EUR",
                        "item-price": "16.95",
                        "item-tax": "",
                        "shipping-price": "",
                        "shipping-tax": "",
                        "gift-wrap-price": "",
                        "gift-wrap-tax": "",
                        "item-promotion-discount": "",
                        "ship-promotion-discount": "",
                        "ship-city": "KÃ¶ln",
                        "ship-state": "",
                        "ship-postal-code": "50935",
                        "ship-country": "DE",
                        "promotion-ids": "",
                        "is-business-order": "false",
                        "purchase-order-number": "",
                        "price-designation": "",
                        "is-sold-by-ab": "false"
               },

**Comment by ianrussel** [comment]
@ShivikaK can you take a look at this?, I am not sure if your api has inconsistent results or maybe I missed something. Creating an order report for specific marketplace(A1C3SOZRARQ6R3) with report type `GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL`  produce data when downloading it, But actually calling the orders endpoint with the said marketplace and same params(dates)  returns nothing? After some investigation, I confirm that the there's no data for that said marketplace.But the order reports says different.I can give you the reportId and documentreportid if you need it.I am using the orders report API just to get the total orders per marketplace results since orders api does not provide it . 

Please help.

Ian

**Comment by moltar** [comment]
@ianrussel have you solved this issue?

**Comment by nassuf** [comment]
Why is this issue closed and still not solved at all ?
marketplaceIds filter wont work and not marketplaceId is provided in the response !

**Comment by ronen-taktook** [comment]
yes Why is this issue closed?
