### ISSUE TITLE
Access to reports successful using credentials from SC but getting access denied when using migrated credentials

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#725]
Hi @rugved1991

I am able to request report GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL successfully using the seller credentials obtained form seller central.

But when I use the AuthorizationApi I get accessdenied error retuned from the report request.

Steps taken:
Call GetAuthorizationCodeAsync with mws credentails
Response = success

Swap for LWA token
Response = success

Call CreateReportAsync - with grant type = refresh token
Response = Invalid grant parameter
{"error_description":"The request has an invalid grant parameter : refresh_token","error":"invalid_grant"}

*** documentation does not specifically state that all future LWA getaccess codes should be grantless - is this the case ? *** 

So then tried as grantless:
Call CreateReportAsync - with grant type = grantless
Response = access denied
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by jlevers** [comment]
If I'm understanding correctly, when you requested grantless credentials, you gave a grant type of `grantless`? If I've got that right, the correct `grant_type` for grantless operations is actually `client_credentials`, not `grantless`...give that a try and see if you have any more luck :)

**Comment by nrogers805** [comment]
> If I'm understanding correctly, when you requested grantless credentials, you gave a grant type of `grantless`? If I've got that right, the correct `grant_type` for grantless operations is actually `client_credentials`, not `grantless`...give that a try and see if you have any more luck :)

No, I provided the correct scope of `client_credentials'

**Comment by jlevers** [comment]
My mistake, sorry about that!
