### ISSUE TITLE
CreateInboundShipmentPlan Amazon Global Logistics freight(AGL)[BUG] Documentation

### ISSUE THREAD

**Issue by chengpan9** [amzn/selling-partner-api-docs#729]
Question：
CreateInboundShipmentPlan，Can not set Amazon Global Logistics freigh(AGL)!

Attachment：
![image](https://user-images.githubusercontent.com/84064455/117932170-a7ce8b80-b332-11eb-8df1-5be0c574ae3b.png)

**Comment by evenchengithub** [comment]
I have the same problem
