### ISSUE TITLE
How use SP-API for php

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#73]
Hello,
I downloaded the php api via swagger, but I don't see any documentation, to know how to use it.
I saw that there was a configuration class, but the fields do not match the documentation.
someone has successfully used it ?

**Comment by charliecode** [comment]
@FexusZ Documentation on how to use the actual client which has been generated by swagger-codegen or [openapi-generator](https://openapi-generator.tech/docs/installation/) is going to be on a case by case basis depending on which generator you use. The generator author would have had to create a template just to explain that. I'm using typescript-node and I also do not have any generated docs. However, after looking over the generated code for an hour or so, I was able to figure out the flow and get things working. This is also what you'll probably need to do.

**Comment by cgaugel** [comment]
Any news here?
