### ISSUE TITLE
An Amazon seller account, the same ASIN in the same market, will it correspond to two FNSKUs?

### ISSUE THREAD

**Issue by jason1004** [amzn/selling-partner-api-docs#730]
We obtained the inventory report and found that there are two FNSKUs for the same ASIN.

An Amazon seller account, the same ASIN in the same market, will it correspond to two FNSKUs?

**Comment by keithbrink** [comment]
Yes, because you can have multiple listings for the same ASIN. For example, you could sell both New and Used conditions on an ASIN.
