### ISSUE TITLE
Error get orders filtering by date

### ISSUE THREAD

**Issue by k1ngdav1d** [amzn/selling-partner-api-docs#731]
When I request the list of orders and insert a date greater than the last order of the day made "CreatedBefore" on https://sellingpartnerapi-eu.amazon.com/orders/v0/orders, the system returns me "InvalidInput". Can I get the list of all the agendas for today, not yesterday? For example, if today is 2021-05-12 and I insert, in the filter, CreatedAfter = 2021-05-12T00: 00: 00Z and in CreatedBefore = 2021-05-12T23: 59: 59Z the request returns Bad Request.
This is normal? Hope it's a bug.

**Comment by ianrussel** [comment]
your createdbefore should not be more than you current Y-m-d H:i:s when you send the request. using php example

            $dateF = '2021-05-20'; //current day
            $dateT = '2021-05-20'; //current day
            $dateF = Carbon::parse("$from Europe/Berlin")->tz('UTC')->format('Y-m-d\TH:i:sP');
            $dateT = Carbon::parse("$to Europe/Berlin")->endOfDay()->tz('UTC')->format('Y-m-d\TH:i:sP');
 
Which will then translate the dates to


            2021-05-19 22:00:00 
            2021-05-20 21:59:59
