### ISSUE TITLE
listCatalogItems 403 Access to requested resource is denied

### ISSUE THREAD

**Issue by qq1356661768** [amzn/selling-partner-api-docs#736]
When I access the “catalog-items-api”, I execute the "listCatalogItems" operation,and the result returns 403 error“ Self authorization "is no problem, and then the application interface permissions are no problem. How to solve this problem?
sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]
![image](https://user-images.githubusercontent.com/57861916/118215809-e1270880-b4a4-11eb-8b67-e89138ff27f4.png)
![image](https://user-images.githubusercontent.com/57861916/118216095-6ca09980-b4a5-11eb-9668-388d3d739bee.png)
![image](https://user-images.githubusercontent.com/57861916/118216196-a07bbf00-b4a5-11eb-96f1-a912c85460f3.png)

**Comment by B1essedSou1** [comment]
So much issues about that last time...i am also in stuck because of "Unauthorized"...about 1 month :( support just answer "Please check guide, Please check some things" and etc...im totally sure from my end all ok.

**Comment by qq1356661768** [comment]
> So much issues about that last time...i am also in stuck because of "Unauthorized"...about 1 month :( support just answer "Please check guide, Please check some things" and etc...im totally sure from my end all ok.
I tried just now. It seems that the parameter "endpoint" is inconsistent.

**Comment by B1essedSou1** [comment]
sir, you see some ways to fix that? because i tried to get amazon account info by using access token and has error like "insufficient_scope" it means that i have no access to retreive this information, however in guide we can receive user info...i think problems with policies, roles and etc. AWS acc.

**Comment by nodisk8800** [comment]
其他的API调用是否正常?

**Comment by B1essedSou1** [comment]
> 其他的API调用是否正常?

no, nothing dont works

**Comment by nodisk8800** [comment]
我去年也遇到这个问题.
解决办法:
1,登录 https://console.aws.amazon.com/iam
2,使用以下json,添加一个 policy:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "execute-api:Invoke",
      "Resource": "arn:aws:execute-api:*:*:*"
    }
  ]
}

3,把这个新添加的 policy 加给你的 User. 这样这个IRN 才有权限访问SPAPI.

中文能看得明白吗?

**Comment by hamduc7** [comment]
I faced this same issue, @nodisk8800 will work if we assign permission for IAM user and use that IAM User in the app setting.
But Amazon does not allow we to update that value so I am still stuck

**Comment by dobariyarakesh** [comment]
@hamduc7 @nodisk8800 @B1essedSou1 I have created doc for step by step create AWS and Seller central detail and I have sample app for testing. Let me know if you required. 
I have completed 7 app for SP-API

**Comment by hamduc7** [comment]
@dobariyarakesh thank you very much. Can you share it?

**Comment by B1essedSou1** [comment]
> @hamduc7 @nodisk8800 @B1essedSou1 I have created doc for step by step create AWS and Seller central detail and I have sample app for testing. Let me know if you required.
> I have completed 7 app for SP-API

Good day sir! it will be awesome! Can you share it?

**Comment by dobariyarakesh** [comment]
@hamduc7 @B1essedSou1 https://join.skype.com/vgfIJuNFSRfL join me here

**Comment by ezerway** [comment]
Hi everyone,
Have any update for the issue.
I get the same error, now :(

**Comment by sim789** [comment]
Hi @ezerway join me here https://join.skype.com/vM5focrCvvnd

**Comment by ezerway** [comment]
Thank @sim789 .
The issue is solved ,cuz missing "Product Listing" option.
I tried re-check and re-authorize my app again, but api still doesn't work.
So i have to create new app.

**Comment by ClementeGao** [comment]
@dobariyarakesh can l join it ? can you share join link ?
