### ISSUE TITLE
[BUG] getOrderMetrics InternalFailure Error Messaging

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#737]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
Im trying to use the Sales > getOrderMetrics endpoint for a seller in the EU region, Spain Marketplace: A1RKKUPIHCS9HS. However I get a strange "InternalFailure" error message from Amazon saying "We encountered an internal error. Please try again."

**URL of the content on GitHub**
Please provide the GitHub URL for the documentation where you see the bug.
https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md#error-responses-and-schemas

**Description of what the documentation currently says**
The error overview doesnt mention this "InternalFailure" case im encountering 

**Description of what the documentation should say**
If there is a problem with the data I am submitting, Id expect it to send a relevant error message. But this is indicating that I should try again later and its a problem on Amazons side, so its not very helpful. 

**Screenshots**

**Additional context**

Im trying to use the Sales > getOrderMetrics endpoint for a seller in the EU region, Spain Marketplace: A1RKKUPIHCS9HS. 

But I keep encountering this error: 
```
    {
      "body": {
        "errors": [
          {
            "message": "We encountered an internal error. Please try again.",
            "details": "",
            "code": "InternalFailure"
          }
        ]
      },
```

**Some details on what we are sending in the request:** 

```
"request": {
    "sku": null,
    "firstDayOfWeek": null,
    "marketplaceIds": [
      "A1RKKUPIHCS9HS"
    ],
    "granularity": "Total",
    "interval": "2021-05-01T00:00-07:00--2021-05-10T00:00-07:00",
    "fulfillmentNetwork": null,
    "buyerType": null,
    "granularityTimeZone": null,
    "asin": null
  },
  "operation": "getOrderMetrics",
  "region": "eu",
```

I have also tried many variations: e.g. with US/Pacific as the timezone, different intervals, granularities etc but keep getting the same error message. 

The Finances and Catalog endpoints work fine for this seller account, so I dont think its an authentication issue. 

Thanks!

**Comment by ShivikaK** [comment]
Hello @jimmy-ross-xapix 

Thank you for raising this issue.

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Please provide request details including timestamp and request ID when you open a support case.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jimmy-ross-xapix** [comment]
@ShivikaK I got the answer from this thread: https://github.com/amzn/selling-partner-api-docs/issues/621#issuecomment-847686024

Apparently the date format requires the +00:00 to be added, then it worked: 

"2019-05-24T22:00:00**+00:00**--2021-05-24T21:59:59**+00:00**"
