### ISSUE TITLE
Individual sellers can not authorize our apps

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#738]
We stay the application in the draft state and use the OAuth Authorization URI that has the flag version=beta, and our other seller can authorize our app. But we have an Individual seller who can not authorize our apps to get the error message as follow:
"You're not permitted to take this action. You must be the primary user of a Professional selling account to take advantage of apps. If you are the primary user, you may upgrade your plan."

We are sure we are the primary user, but we do not want to upgrade our selling account plan.

How can the Individual seller authorize our app by website workflow?

**Comment by iLoveSarabear** [comment]
I am also having this problem. My account is already a professional selling account. I've created a case, but unfortunately the team I'm communicating with do not appear to understand.

Case ID: ID8354254721

**Comment by iLoveSarabear** [comment]
Hello, has there been any update on this issue? We're unable to use our App because the error states that we have to upgrade our plan.

Thanks,

**Comment by HelloLiuKaiJun** [comment]
> I am also having this problem. My account is already a professional selling account. I've created a case, but unfortunately the team I'm communicating with do not appear to understand.
> 
> Case ID: ID8354254721

same problem
