### ISSUE TITLE
Selling Partner API to retrieve the RMAs and Returns

### ISSUE THREAD

**Issue by sivasena-ks** [amzn/selling-partner-api-docs#739]
Hi Team,

I am looking for a way to retrieve the RMAs and Returns from a particular timestamp (Ex: After 2021-05-10T11:22:35+00:00) using Selling Partner API. I have gone through the API documentation available at https://github.com/amzn/selling-partner-api-docs. However, couldn't find any option to do so.

Is there a way to retrieve the RMAs and Returns from a particular timestamp using this API?

Any help/suggestion around this greatly appreciated.

Regards,
Sena

**Comment by ianrussel** [comment]
Maybe your looking at this reports https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#returns-reports

**Comment by sivasena-ks** [comment]
@ianrussel , Thank you for your response. Using reports API I can retrieve the returns for a specific date range.

This API returns an encrypted document. Do you know how to decrypt the file?

Regards,
Sena

**Comment by acardero** [comment]
@sivasena-ks You need to base64 decode both the IV and the key provided by Amazon on the response. Then using AES-256-CBC works just fine.
