### ISSUE TITLE
Retrieve report with reportId returns Access Denied

### ISSUE THREAD

**Issue by YanivC** [amzn/selling-partner-api-docs#740]
Hi,

I finally managed to get through lots of reading and was able to hit the new reports functionality and created a report. It signs and comes back fine but when I try to get the response (DONE, CANCELLED, etc...) Im getting:
"message": "Access to requested resource is denied.",
 "code": "Unauthorized"

Im using the same signing method as I used to create the report. Any help would be appreciated.

`RGReportRequestBodyModel requestBody = new RGReportRequestBodyModel()

RGAmazonRequestModel model = service.Client(requestBody);
AmazonService amazonService = new AmazonService(model);
amazonService.QueryString = "/" + report;  // "/reports/2020-09-04/reports/{reportId}
IRestRequest request = amazonService.GetAmazonSignedRequest();

//calling service that wraps this : IRestRequest request = new RestRequest(RestRequestUrl + QueryString, Method.POST);

RestClient restClient = service.SignedRestClient(model);
IRestResponse response = restClient.Execute(request);`

**Comment by nodisk8800** [comment]
Use Method.GET

**Comment by nodisk8800** [comment]
Login to you AWS Account, config the User Policy
