### ISSUE TITLE
getMyFeesEstimateForSKU error with SKU containing UTF-8 chars

### ISSUE THREAD

**Issue by amz-tools** [amzn/selling-partner-api-docs#742]
Some of our clients use german words as SKUs that include UTF-8 chars such as i.e. `Türrahmen`.

When trying to call the `getMyFeesEstimateForSKU` operation the SKU is part of the path:
`/products/fees/v0/listings/Türrahmen/feesEstimate`

The call itself works, however the result returns the following error:
```
{
  "payload": {
    "FeesEstimateResult": {
      "Status": "ClientError",
      "FeesEstimateIdentifier": {
        "MarketplaceId": "A1PA6795UKMFR9",
        "IdType": "SellerSKU",
        "SellerId": "<CUSTOMER_SELLER_ID>",
        "SellerInputIdentifier": "Türrahmen_de",
        "IsAmazonFulfilled": true,
        "IdValue": "T%C3%BCrrahmen",
        "PriceToEstimateFees": {
          "ListingPrice": {
            "CurrencyCode": "EUR",
            "Amount": 12.99
          }
        }
      },
      "Error": {
        "Type": "Sender",
        "Code": "InvalidParameterValue",
        "Message": "No ASIN found for SKU: T%C3%BCrrahmen. Please make sure the SKU is valid.",
        "Detail": []
      }
    }
  }
}
```

It looks like the `ü` inside the path gets url encoded and not decoded on the receiving end, which results in the SKU being not found as its now `T%C3%BCrrahmen` instead of `Türrahmen`.

Is somebody here who has run into the same issue? Is this a bug or is there a workaround I don't see yet?

Thanks for the help!

**Comment by nodisk8800** [comment]
try decode/encode the value

**Comment by amz-tools** [comment]
@nodisk8800 I already tried all possibilities of encoding the value. The problem seems to be on Amazons end, it seems as if the SKU is not decoded when its part of the path itself. It works fine for other calls where the SKU is part of the query or the body.

**Comment by ellis** [comment]
@amz-tools Yes, I ran into the same issue and never found a workaround.  Slashes in the SKU also cause a problem (see #467).

As an alternative data source, I had hoped we could use the report [GET_REFERRAL_FEE_PREVIEW_REPORT](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#inventory-reports), but it only includes the referral fee (as the name says) but no FBA fees.

We ended up using the `getMyFeesEstimateForASIN` method instead, until this is fixed.

**Comment by amz-tools** [comment]
@ellis Good to know we are not the only ones having the problem. We also apply `getMyFeesEstimateForASIN ` for the time being.

**Comment by diegocvazquez** [comment]
Hello, I am having the same issue calling /products/pricing/v0/price, if any sku is containing a UTF characters,  I will get an error Invalid Input. Do you guys have any updates on this ? 
I will create a case

**Comment by ellis** [comment]
@amz-tools and @diegocvazquez If you haven't already tried it again recently, it looks like this is working on my end now for both of the cases you mentioned.

For example, for a SKU with both spaces and umlauts, e.g. "Blaue Blüten", the following URL worked:

`https://sellingpartnerapi-eu.amazon.com/products/fees/v0/listings/Blaue%20Bl%C3%BCten/feesEstimate`

However, slashes in SKUs still aren't working yet:

**Comment by ellis** [comment]
@diegocvazquez Spaces are working just fine on my end, as long as you URL encode them like above, so that spaces become %20.  Have you tried that yet?

**Comment by diegocvazquez** [comment]
@ellis 
Hi, I am talking about 

GET /products/pricing/v0/price
Operation: getPricing

Description
Returns pricing information for a seller's offer listings based on seller SKU or ASIN.

docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing. If I call the method using skus with spaces I get and Invalid input error.

are you taking about he same endpoint?

thanks for your time

**Comment by ellis** [comment]
Hi @diegocvazquez you're right, I had only checked the `getMyFeesEstimateForSKU` method by mistake.  `getPricing` still fails with spaces in SKUs for me too.

**Comment by diegocvazquez** [comment]
Hi @ellis, yeah I will create a case, but I am able to use the asin version of the method, thanks for your help

**Comment by parvathm** [comment]
Hi,

Can you please share the case id for this issue?

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by diegocvazquez** [comment]
@parvathm 
If your question is directed to me, I have not created a case as I am using now the getMyFeesEstimateForASIN. I had not the time at the moment to wait for a response. I am not sure if this is working or not now.

Best regards,
Diego

**Comment by amz-tools** [comment]
We got this finally fixed in our JS SP client. Apparently there's no serverside issue, the trick is to double encode the parts of the api path when creating the canonical request, so i.e. `getMyFeesEstimateForSKU` with SKU `Türrahmen` becomes `/products/fees/v0/listings/T%25C3%25BCrrahmen/feesEstimate` for the canonical request.

**Comment by ellis** [comment]
@amz-tools Thanks for the workaround!  Isn't this still a bug, though?  Double-encoding is not a proper interface, and it then probably messes up other things that can only be encoded once, like spaces and slashes.  If you don't disagree, could you please re-open the issue?

**Comment by amz-tools** [comment]
@ellis Its actually correct as it is. The path itself is NOT double-encoded, only the canonical request that is used for the signature is double-encoded. And thats correct according to the docs for [creating a canonical request for Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html). It states:

> Each path segment must be URI-encoded twice

So I think we just missed that part and everything is working as it is supposed to be.
