### ISSUE TITLE
Orders Refund

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#743]
I would like to get the refund reports for orders by date range.I tried the `GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE` report type but always got status `Cancelled` so I cant get reportDocumentID for me to download report. Any idea ? I am certain have refunds when checking  it in actual sellers central dashboard

**Comment by nodisk8800** [comment]
do you set the  dataStartTime/dataEndTime ?

**Comment by ianrussel** [comment]
Yes. This is the reponse I got 

      `{
  "payload": {
    "marketplaceIds": [
      "A1F83G8C2ARO7P",
      "A1PA6795UKMFR9",
      "A13V1IB3VIYZZH",
      "AZMDEXL2RVFNN",
      "A38D8NSA03LJTC",
      "A1ZFFQZ3HTUKT9",
      "APJ6JRA9NG5V4",
      "A1RKKUPIHCS9HS",
      "A62U237T8HV6N",
      "AFQLKURYRPEL8",
      "A1805IZSGTT6HS",
      "A2NODRKZP88ZB9",
      "A1C3SOZRARQ6R3"
    ],
    "reportId": "23989701876293",
    "reportType": "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
    "dataStartTime": "2021-05-13T22:00:00+00:00",
    "dataEndTime": "2021-05-15T21:59:59+00:00",
    "createdTime": "2021-05-16T05:12:33+00:00",
    "processingStatus": "CANCELLED",
    "processingStartTime": "2021-05-16T05:12:38+00:00",
    "processingEndTime": "2021-05-16T05:12:44+00:00"
  }
}`

**Comment by ianrussel** [comment]
@ShivikaK any ideas ?

**Comment by stefnats** [comment]
@ianrussel i have to solution for the report problem, but you talked about `refund` reports.
This report shows the `customer returns`. If you want more detailed information about the transactions, you need to check the Finances API for `RefundEvent`s.

**Comment by ianrussel** [comment]
Hi @stefnats thanks for the response. Yes I think the `"GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE` report type is not for refunds. So I will try the Finance API for RefundEvents. But I think the aws team should still investigate why this report type always return `Cancelled` and maybe update their documentation
