### ISSUE TITLE
If I want to use the report API to get all the orders of the current seller, how should I choose "reporttype"

### ISSUE THREAD

**Issue by qq1356661768** [amzn/selling-partner-api-docs#745]
If I want to use the report API to get all the orders of the current seller, how should I choose "reporttype"
Can the report API get all the information about the seller's products? Which "report types" should I take？

I'm using "get_ order_ buyer_ Info", the error is reported:
[{'message': 'You exceeded your quota for the requested resource.', 'code': 'QuotaExceeded'}]
tp：
Why do you limit the speed of API so much? This can't be used normally, so I have to use one day to synchronize data?

**Comment by qq1356661768** [comment]
If I use the type “GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL”， I can only get the order data of the last 30 days. What's the solution?

**Comment by stefnats** [comment]
@qq1356661768 i think you need to make multiple requests. If you want to retrieve 12 months, you need to request 12 reports (each with their specific start/end date)

**Comment by qq1356661768** [comment]
> @ qq1356661768我认为您需要提出多个请求。如果要检索12个月，则需要请求12份报告（每个报告都有其特定的开始/结束日期）

However, once I call the report for more than 30 days, it has no data.

**Comment by qq1356661768** [comment]
> @qq1356661768 i think you need to make multiple requests. If you want to retrieve 12 months, you need to request 12 reports (each with their specific start/end date)

However, once I call the report for more than 30 days, it has no data.
![image](https://user-images.githubusercontent.com/57861916/118623575-f7adc680-b7fa-11eb-8309-ef3e6c7b0bdc.png)
![image](https://user-images.githubusercontent.com/57861916/118623606-fda3a780-b7fa-11eb-99d8-b14816b7471f.png)

**Comment by qq1356661768** [comment]
> @qq1356661768 i think you need to make multiple requests. If you want to retrieve 12 months, you need to request 12 reports (each with their specific start/end date)

Thank you. I just tried. Do as you say. OK.
