### ISSUE TITLE
how to check if a product is delivered to another country or not?

### ISSUE THREAD

**Issue by arturll7** [amzn/selling-partner-api-docs#746]
Hello,

Does anyone knows the way of "**how to check if a product is delivered to another country or not**"?

Thanks

**Comment by stefnats** [comment]
@arturll7 do you mean the shipping groups / shipping profiles? there is no way to retrieve the settings of a shipping profile / group, but it is possible to determine which shipping group is assigned to a specific SKU.

Or do you mean if a SKU is listed on a specific Marketplace? If so, you just need to request a stock report for that Marketplace.

**Comment by arturll7** [comment]
Hi @stefnats, thank you for your answer.
I want to check a specific ASIN. For example, I need to check a product sold on amazon.com can be delivered to Australia or another country? I need to make this checking with ASIN.
