### ISSUE TITLE
GET /catalog/2020-12-01/items/B06X9HW4MD is returning the wrong images for a specific ASIN

### ISSUE THREAD

**Issue by petergzli** [amzn/selling-partner-api-docs#748]
The images for GET /catalog/2020-12-01/items/B06X9HW4MD are incorrect

It seems to be only thing item. This item is in a group. The other colors are returning fine in the api but just this yellow one. The API images returning are the blue one.

<img width="898" alt="Screen Shot 2021-05-18 at 12 19 11 AM" src="https://user-images.githubusercontent.com/11988769/118589609-b2dc4e00-b76e-11eb-98bf-85c010d8d982.png">

**Comment by petergzli** [comment]
@parvathm @rugved1991 I'm not sure if I should file this bug here or on seller central as a support ticket.

**Comment by rugved1991** [comment]
Hi @petergzli,

Thanks for reaching out. Can you please open up a support ticket for this issue? Please provide the complete request and response along with headers in the case and the team will be able to investigate the issue further.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by petergzli** [comment]
Hi @rugved1991 thanks for the response. I had submitted the case ID 8370021361

However I have yet to receive a resolution and the support keeps asking me for the same information (the request/response along with headers) which I had included both in text and uploaded as a file 2 times already.

**Comment by rugved1991** [comment]
Hi @petergzli,

Thanks for bringing this to our attention. I have reached out to the backend team and provided them with the necessary details. We will update you once we have more information on this issue.
Thanks for your patience.

Best,
Rugved
Solutions Architect, SP API
