### ISSUE TITLE
GET_FBA_MYI_ALL_INVENTORY_DATA - your_price currency?

### ISSUE THREAD

**Issue by stefnats** [amzn/selling-partner-api-docs#749]
Hi,

in the Report with type `GET_FBA_MYI_ALL_INVENTORY_DATA` there is the column `your_price`.

If i have listed that SKU in multiple Marketplaces (let's say Amazon.de, Amazon.uk and Amazon.se) which listing/marketplace does it represent and thus which currency does the `your_price` column have?

**Comment by jiangdi0924** [comment]
It's really confusing when there are multiple sites that aren't differentiated by marketplace but rather merged together.  You solved this problem later @stefnats
