### ISSUE TITLE
getCompetitivePricing Rate (requests per second)

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#75]
On MWS API we have following rate limit.

Maximum request quota - 20 requests
Restore rate -	10 items every second
Hourly request quota - 36000 requests per hour

http://docs.developer.amazonservices.com/en_US/products/Products_GetCompetitivePricingForASIN.html

But SPAPI rate limit is very less

Rate (requests per second) - 1

https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getcompetitivepricing

Is this final rate limit ?

**Comment by GriceTurrble** [comment]
The rate limit on MWS equates to 36,000 items per hour.

If the APAPI rate limit is only per request, and each request may handle up to 20 items, that would be 72,000 items per hour. Sounds like an increase to me.

*Confirmation needed, though*.

**Comment by parvathm** [comment]
Hi,

Yes your understanding is correct. In SP API rate of 1 request per second that can contain maximum 20 ASIN's where as in MWS it is 1 request per second that can contain 10 items . so the rates in SP API are more than MWS rates. Hope this clarifies.

Thanks,
Parvathm
Amazon MWS Support.
