### ISSUE TITLE
mws_auth_token is missing in query params

### ISSUE THREAD

**Issue by Tomer781** [amzn/selling-partner-api-docs#750]
I'm following *Authorizing Selling Partner API applications* section, and implementing *Website workflow*, on step 4 I'm expecting a mws_auth_token and I don't get it, I only get this template:
https://myRedirectUri.com/?spapi_oauth_code=blablabla&state=test&selling_partner_id=blablabla
I'm using an OAuth authorization URI of draft hybrid application, and login using seller that is not the application owner.

**Comment by stefnats** [comment]
Just wanted to point out, this seems to be related to #734
