### ISSUE TITLE
_GET_XML_VAT_INVOICE_DATA_REPORT_ is about to be discarded. What's the new replacement

### ISSUE THREAD

**Issue by vic091** [amzn/selling-partner-api-docs#751]
_GET_XML_VAT_INVOICE_DATA_REPORT_ is about to be discarded. What's the new replacement

**Comment by stefnats** [comment]
According to https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#tax-reports
It may be `SC_VAT_TAX_REPORT` or `GET_VAT_TRANSACTION_DATA`
