### ISSUE TITLE
I used to apply for the basic role of PII, but now I want to apply for the permission of "restricted role". Can I still use the developed application normally during the application period?

### ISSUE THREAD

**Issue by qq1356661768** [amzn/selling-partner-api-docs#754]
I used to apply for the basic role of PII, but now I want to apply for the permission of "restricted role". Can I still use the developed application normally during the application period?

**Comment by ShivikaK** [comment]
Hello @qq1356661768 

Thank you for raising this issue.

You can use the same application developed and request for access to restricted role. Please re-submit the developer profile for access to restricted role. This will create a new case which will be reviewed based on the details provided to approve or deny the request.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md

Please let me know if you have further questions or if I misunderstood your question.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jchavest13** [comment]
Hi @qq1356661768,

Please follow @ShivikaK guidance provided above and feel free to re-open this issue if additional assistance is required or if your question was misunderstood.

Regards,
Julian
Developer Registration Specialist, SP-API
