### ISSUE TITLE
Issue with multiple MarketplaceIds in getorders?

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#756]
**Describe the bug**
Im sending getorder requests for a seller, active in France and Spain, and am getting the expected response when I include the MarketplaceId for Spain. Many orders are returned for a specific day. 
 
    "MarketplaceIds": [
      "A1RKKUPIHCS9HS"
    ]

BUT, when I add a 2nd MarketplaceIds for France, I no longer get any orders in the response. I also do not get any error messages, it seems the request is correct. 

    "MarketplaceIds": [
      "A1RKKUPIHCS9HS",
      "A13V1IB3VIYZZH"
    ]

The seller may not have had any orders on that day in France, but surely the MarketplaceIds should work in an OR fashion and still return the Spain orders? It seems that adding more IDs is filtering the results and nothing is returned because France had no orders?

Maybe Ive misunderstood something and I couldnt find anything in the documentation suggesting otheriwse - would be really grateful to hear from anyone who has encountered something similar. 

Thanks!

**Comment by JohnMirro** [comment]
This bug still exists
