### ISSUE TITLE
[BUG] SQS cannot receive the message notification of REPORT_PROCESSING_FINISHED

### ISSUE THREAD

**Issue by fengzidk** [amzn/selling-partner-api-docs#758]
I am trying to use Amazon SQS to receive REPORT_PROCESSING_FINISHED message notifications,

According to the guide:
> 1. create SQS,
> 2. Call the createDestination interface,
> 3. Call createSubscription and specify the notificationType as REPORT_PROCESSING_FINISHED,

**All operations get the correct result,**
But after I call createReport,And when processingStatus in getReport is DONE, there is no message in SQS

**What should I do to get notifications from SQS?**

**Comment by fengzidk** [comment]
It is worth mentioning that the messages I actively send to SQS can be pushed to the server correctly and can be consumed correctly

**Comment by stefnats** [comment]
Did you make sure that you [set the permissions correctly](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue)?

**Comment by fengzidk** [comment]
> 您是否确定[正确设置了权限](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#step-1-grant-selling-partner-api-permission-to-write-to-your-sqs-queue)？

Yes, I set the permissions according to the document
