### ISSUE TITLE
Some Orders appears to have no data when calling financial events by order id

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#759]
This seem another bug for this sellingpartner api. My goal is to get Financial events. Bu I noticed some of them return empty objects.

         finances/v0/orders/303-3828883-7xxxxxxxx/financialEvents

         {
            "payload": {
              "FinancialEvents": {
                "ShipmentEventList": [],
                "RefundEventList": [],
                "GuaranteeClaimEventList": [],
                "ChargebackEventList": [],
                "PayWithAmazonEventList": [],
                "ServiceProviderCreditEventList": [],
                "RetrochargeEventList": [],
                "RentalTransactionEventList": [],
                "ProductAdsPaymentEventList": [],
                "ServiceFeeEventList": [],
                "SellerDealPaymentEventList": [],
                "DebtRecoveryEventList": [],
                "LoanServicingEventList": [],
                "AdjustmentEventList": [],
                "SAFETReimbursementEventList": [],
                "SellerReviewEnrollmentPaymentEventList": [],
                "FBALiquidationEventList": [],
                "CouponPaymentEventList": [],
                "ImagingServicesFeeEventList": [],
                "NetworkComminglingTransactionEventList": [],
                "AffordabilityExpenseEventList": [],
                "AffordabilityExpenseReversalEventList": []
              }
            }
         }

calling same api with different orderid returns data

            {
        "payload": {
          "FinancialEvents": {
            "ShipmentEventList": [
              {
                "AmazonOrderId": "302-xxx3690-xxxxxx",
                "SellerOrderId": "302-xxx3690-xxxx",
                "MarketplaceName": "Amazon.de",
                "PostedDate": "2021-05-14T22:39:14+00:00",
                "ShipmentItemList": [
                  {
                    "SellerSKU": "4Z-xxxxx",
                    "OrderItemId": "2xxxx7168403",
                    "QuantityShipped": 2,
                    "ItemChargeList": [
                      {
                        "ChargeType": "Principal",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 33.9
                        }
                      },
                      {
                        "ChargeType": "Tax",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 0
                        }
                      },
                      {
                        "ChargeType": "GiftWrap",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 0
                        }
                      },
                      {
                        "ChargeType": "GiftWrapTax",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 0
                        }
                      },
                      {
                        "ChargeType": "ShippingCharge",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 3.99
                        }
                      },

And there are 5 more orderids that returns empty object, which I cant get enough information example charges(shpping etc)

And they are in same date range and marketplace. Any help @ShivikaK ?
And is there any other apis that can be used to get this information like the financial events api ?

**Comment by ianrussel** [comment]
Hi, it seems everyone in aws team is busy, I would like to ask where to report this bug for faster resolve? Currently in our app we need to show to the customer the charges like shipping for a specific order, but it turn out when calling the financial event api, some in formations on specific order are missing. In MWS its working good.

**Comment by ShivikaK** [comment]
Hello @ianrussel 

Thank you for raising this issue.

Can you please provide me with request IDs and timestamps for the requests returning empty objects in the response for further investigation?

A support case will be a better approach to investigating this further. So I will appreciate if you can open a support case with us and provide the requested information in it.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ianrussel** [comment]
Hi @ShivikaK ,

Thank you very much for your response

Here is the request informations
OrderId is `303-0141320-6135517`
 
                 v1/finances/v0/orders/303-0141320-6135517/financialEvents
                 {"Date":["Fri, 21 May 2021 22:55:46 GMT"],"Content-Type":["application\/json"],"Content-Length":["4241"],"Connection":["keep-alive"],"x-amzn-RequestId":["02cc99bc-be04-4876-937c-6ba21093ea78"],"x-amz-apigw-id":["fs4R4HdiDoEF-Ag="],"X-Amzn-Trace-Id":["Root=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]}  
                 {"payload":{"FinancialEvents":{"ShipmentEventList":[],"RefundEventList":[],"GuaranteeClaimEventList":[],"ChargebackEventList":[],"PayWithAmazonEventList":[],"ServiceProviderCreditEventList":[],"RetrochargeEventList":[],"RentalTransactionEventList":[],"PerformanceBondRefundEventList":[],"ProductAdsPaymentEventList":[],"ServiceFeeEventList":[],"SellerDealPaymentEventList":[],"DebtRecoveryEventList":[],"LoanServicingEventList":[],"AdjustmentEventList":[],"SAFETReimbursementEventList":[],"SellerReviewEnrollmentPaymentEventList":[],"FBALiquidationEventList":[],"CouponPaymentEventList":[],"ImagingServicesFeeEventList":[],"TaxWithholdingEventList":[],"NetworkComminglingTransactionEventList":[],"AffordabilityExpenseEventList":[],"AffordabilityExpenseReversalEventList":[],"RemovalShipmentAdjustmentEventList":[],"RemovalShipmentEventList":[]}}}  
![financeevent](https://user-images.githubusercontent.com/4607692/119206028-96247b00-bacc-11eb-88fd-17428dcb0359.png)


The status of this order id is shipped. See screenshot for response returned when calling the order api https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorder
![orders_gi](https://user-images.githubusercontent.com/4607692/119205906-3332e400-bacc-11eb-9230-aa6e92e03240.png)

                 
           
And There are lots of them. I am just showing the date for May 1 2021(out of 139) there are two orders which is empty when calling the financial events by order id

**Comment by ShivikaK** [comment]
Hello @ianrussel 

Thank you for providing the information.

I will investigate if there is an issue on my end and get back to you by next Monday at the earliest.

In the meanwhile, if you would like to open a support case with us, please do so and share the case ID with me.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ianrussel** [comment]
Hi Ms. @ShivikaK , do we have updates on this specific issue?

**Comment by ianrussel** [comment]
Its almost one month :(

**Comment by dsokolowski** [comment]
Hi, the same issue here. From time to time some orders appear having no financial events returned (empty arrays as in this issue description) even though they are paid and shipped.

**Comment by ianrussel** [comment]
I'm closing this issue. Amazon support already aware this issue and they fixed the specific order with missing financial events, though I am not sure if it also fixes other orders with missing financial events.

Thanks @ShivikaK for the help.

**Comment by dsokolowski** [comment]
@ShivikaK can you tell us whether your fix applies to all orders or just to what @ianrussel specified?

**Comment by ianrussel** [comment]
@dsokolowski I reopen this issue. This is really really annoying. Few weeks ago I only found few orders with empty financials events.Now they are hundreds of them!. I think it is growing everyday.How can we show accurate results to our customers ? :(

**Comment by newrobins** [comment]
Hi, Same this issue getting financial events. Please tell what I do to fix this and getting details?

**Comment by mwtaylor1983** [comment]
I'm also having the same issue, what is the fix for this?
