### ISSUE TITLE
Accessing the Sandbox

### ISSUE THREAD

**Issue by alex-lehan-bloom** [amzn/selling-partner-api-docs#76]
I'm using the SPAPI for the first time. I've been able to get an access_token from "https://api.amazon.com/auth/o2/token". 

I've added the access token to the "x-amz-access-token" header as the SPAPI doc says. However, I keep getting a 403 with the following message:

```javascript
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
      "code": "MissingAuthenticationToken"
    }
  ]
}
```

Does anyone know why this might be happening.

**Comment by charliecode** [comment]
Repeat #38 #52. Check those issues out for direction.
