### ISSUE TITLE
Missing XSD in documentation

### ISSUE THREAD

**Issue by tomhirschfeld** [amzn/selling-partner-api-docs#760]
Looking at this file: 
https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md

the "Flat File Inventory Loader Feed" type does not have an XSD. Can you please provide an XSD?

**Comment by chapmanjw** [comment]
Those feed types are not XML feeds with XSDs, rather they are spreadsheets. You can find more information on Seller Central help for how to use the "flat file" spreadsheet feed uploads, such as https://sellercentral.amazon.com/gp/help/202154120.
