### ISSUE TITLE
Please explain significance of Non-Amazon Marketplaces and Marketplace IDs

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#761]
The call to marketplace participation returned a marketplace with the ID of `A1ZFFQZ3HTUKT9`. This ID is not documented anywhere.

By Googling, I was able to find [this](https://github.com/caponica/AmazonMwsComplete/blob/7320c1ce2fd600b4de3961263c78e8bc51c7de7f/src/CaponicaAmazonMwsComplete/ClientPool/MwsClientPoolConfig.php#L219), which gives us a clue:

> Multi-channel fulfilment orders are linked to these "Non-Amazon" marketplaces

But what does that mean?

How should these marketplaces be handled?

Can you please include all of the possible IDs in the docs?

**Comment by jlevers** [comment]
I would appreciate some clarity around this as well. I'm running into issues where if I pull certain reports using only the marketplace IDs specified in the documentation, the report is missing a lot of data, but if I specify all marketplace IDs returned by `getMarketplaceParticipations` (some of which are not in the docs, as @moltar said above), I get all the expected data.

**Comment by moltar** [comment]
@jlevers That's interesting!

Could you post a specific example, please? I'll do some testing too.

**Comment by jlevers** [comment]
I think I was actually wrong about what I said above -- sorry for the confusion

**Comment by parvathm** [comment]
Hi @moltar,

Non Amazon marketplace id's returned in sellers API can be ignored. If you are having issues or any concerns with non Amazon marketplace id please let us know. 

Thanks,
Parvathm
Selling Partner API Developer Support.
