### ISSUE TITLE
PII - Restricted Access Request

### ISSUE THREAD

**Issue by bobsys-mfleischer** [amzn/selling-partner-api-docs#763]
Hello,

we opened a ticket for SP-API Developer on March 18 which is unfortunately still in review.
Is there any way to speed up the process ? We are interested in building solutions for the new Amazon AppStore in the medium term but without the PII it makes no sense for us.

CaseID: 6871048152

Regards

**Comment by ShivikaK** [comment]
Hello @bobsys-mfleischer 

Thank you for raising this issue.

Your case has been expedited and you should receive an update on the case by next week.

Please continue monitoring the case for further updates and next steps.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jchavest13** [comment]
Hi @bobsys-mfleischer,

Please accept our apologies for the delay getting back to you on your case. You can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
