### ISSUE TITLE
RDT with the Tokens API

### ISSUE THREAD

**Issue by msteinbock** [amzn/selling-partner-api-docs#764]
I recently got approval for PII restricted access. I set up the RDT based on the provided tutorial. 

I am trying to call the getOrderAddress operation from the Orders API. Prior to gaining restricted access, I was unable to get any address information. Now, with the restricted access, I am able to get the zip code, city, and state, however, I still don't receive the street address or the name. 

Am I doing something wrong with the RDT through the Tokens API or is there more access I need to request to get this information?

**Comment by milovvsam** [comment]
We're having the same issue. Were you able to resolve this?

**Comment by msteinbock** [comment]
> 
> 
> We're having the same issue. Were you able to resolve this?

Yes, it turns out that when you go from unrestricted access to restricted access you have to re-authorize the app and get a new LWA refresh token. Once I did that, then it worked.

Fair warning though, when you generate the LWA refresh token, it says that this will not disable old tokens. This is true, but if you make too many calls with different tokens, then it errors out and says you have "Too many active keys" (For instance, I had a production application running with the old refresh token while I developed a newer version with the new refresh token and both stopped working because too many calls were made using different tokens)

Hopefully this saves you many frustrating hours! :)

**Comment by krithic15** [comment]
> I am trying to call the getOrderAddress operation from the Orders API. Prior to gaining restricted access, I was unable to get any address information. Now, with the restricted access, I am able to get the zip code, city, and state, however, I still don't receive the street address or the name.
> 
> Am I doing something wrong with the RDT through the Tokens API or is there more access I need to request to get this information?

Hello @msteinbock,

Yes, you are correct. Your application would need a re-authorization due to the access change in this case so that the new token is associated with the correct permission.

However, regarding the "Too many active keys" error, this was caused due to an internal failure and we have fixed it. Please open a support case if you are still seeing this error.

Thank you,
Krithi
Solutions Architect II, Selling Partner APIs.
