### ISSUE TITLE
Access to requested resource is denied - 403

### ISSUE THREAD

**Issue by israelproscai** [amzn/selling-partner-api-docs#77]
I have a big problem with the integration with the C# SDK

**resource**:  https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders

**responsebody**
`{
    "errors": [
        {
            "message": "**Access to requested resource is denied**.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}`

**response headers**
x-amzn-ErrorType = AccessDeniedException

**Comment by rodrigojob** [comment]
Only you?
You need to see the list before oen a new issue.
#38

**Comment by ykl1993** [comment]
与Java SDK集成时也遇到了

**Comment by ykl1993** [comment]
> 与C＃SDK集成时遇到大问题
> 
> **资源**：[https](https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders) : [//sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders](https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders)
> 
> **反应体**
> `{ "errors": [ { "message": "**Access to requested resource is denied**.", "code": "Unauthorized", "details": "" } ] }`
> 
> **响应标头**
> x-amzn-ErrorType = AccessDeniedException



> 与C＃SDK集成时遇到大问题
> 
> **资源**：[https](https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders) : [//sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders](https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders)
> 
> **反应体**
> `{ "errors": [ { "message": "**Access to requested resource is denied**.", "code": "Unauthorized", "details": "" } ] }`
> 
> **响应标头**
> x-amzn-ErrorType = AccessDeniedException

It may be a problem with the newly added roleArn. I also reported this error, but I just removed the AWSAuthenticationCredentialsProvider class.

**Comment by chenlixin93** [comment]
The same error.
https://github.com/amzn/selling-partner-api-docs/issues/24#issuecomment-705697677

**Comment by weiliguo15634145** [comment]
解决了吗 , 我也遇到了同样的问题 .
