### ISSUE TITLE
Developer Profile is still under review 

### ISSUE THREAD

**Issue by AmazonAPI** [amzn/selling-partner-api-docs#771]
My developer profile is under review for over a week. Could you please advise?
Case ID 8349042171

**Comment by jchavest13** [comment]
Hi @AmazonAPI,

Please accept our apologies for the delay getting back to you on your case. You can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
