### ISSUE TITLE
Get all orders with shipping address

### ISSUE THREAD

**Issue by anton-pon** [amzn/selling-partner-api-docs#776]
In the old MWS "getOrders" api call, there was in the response a field for each order named "shippindAddress" which I could use to create my shipping labels.

In the new SP-API in the getOrders there is no such field. Instead I can get the shipping address via "/orders/v0/orders/{orderId}/address " for each order. But it seems that I should call this api for each order (>100) and the rate is set for 1 per request second.. So for 100 orders I will have to wait over 1.5 mins to get all addresses.
There is also no possibility to pass many orders in an array to this api...

Is there a possibility to get all order with shipping addresses ? Or to increase the request limit ?

**Comment by fernlop** [comment]
They changed it to just 0.0055 requests per second a few days ago!!! What is going on with them????

**Comment by EffectConnect** [comment]
Hey guys, we've noticed the 0.0055 rps limitation as well. This would mean it'll take us 5 hours to get address information for 100 orders (which are also on the 0.0055 rps limitation).
This is not workable in any stretch of the imagination. If a customer receives about 100 orders per hour, how are we going to get all these orders imported?

A limit of 0.55 requests per second would be sub-optimal, but understandable, seeing as we can make an order list request (with 100 orders) per 0.0055 seconds.
