### ISSUE TITLE
ISO 8601 problems

### ISSUE THREAD

**Issue by maranqz** [amzn/selling-partner-api-docs#779]
**Describe the bug**
For [getOrder](https://github.com/amzn/selling-partner-api-docs/blob/548d815eb32c899aa4b7520c49baee008f3687e3/references/orders-api/ordersV0.md#get-ordersv0orders), dates have ISO 8061. The [documentation](https://github.com/amzn/selling-partner-api-docs/blob/11d21d4931bb23c07c1cf84b77ce89c8a147ade3/references/vendor-direct-fulfillment-shipping-api/vendorDirectFulfillmentShippingV1.md#statusupdatedetails) said that  2020-07-16T23:00:00Z or 2020-07-16T23:00:00+01:00 are correct formats.

However, only the request with 2020-07-16T23:00:00Z gave a response, but 2020-07-16T23:00:00+01:00 gave an error.
Then, other ISO 8601 variations do not work too (2020-07-16T20:00:00+0100, 2020-07-16T20:00:00+01).

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "timestamp must follow ISO8601",
      "details": ""
    }
  ]
}
```

**Description of what the documentation should say**
ISO 8601 should be concreted or work in all variations of standard.

**Comment by ToYonos** [comment]
Same here
`GET https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2021-06-14T16%3A48%3A58.164%2B02%3A00&OrderStatuses=Shipped&MarketplaceIds=A13V1IB3VIYZZH`

2021-06-14T16:48:58.164+02:00 seems to fit the time offets though : https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

Does SPAPI only support  the special representation "Z" ?
