### ISSUE TITLE
Question: API endpoint to mark order as shipped easier way.

### ISSUE THREAD

**Issue by dsokolowski** [amzn/selling-partner-api-docs#78]
Hi,

My goal is to allow user to import amazon mfn orders in our app and ship them here manually using integration with various shipping carriers we already have. Once user processes shipment and gets label I want our system to mark amazon order as shipped (just change order status and store some shipment related informations like carrier, service, tracking id). I think API for merchant-fulfillment is not what I am looking for and I need to use API for feeds (Order Fulfillment Feed) but want to confirm it before I start adding support for feeds since this endpoint works a bit different way than other endpoints.

**Comment by charliecode** [comment]
Have you had a chance to read through the documentation provided for those endpoints yet? If not, [you can find the json files which can be used to generate documentation for a given API here](https://github.com/amzn/selling-partner-api-models/tree/main/models).

**Comment by dsokolowski** [comment]
Hi, thanks for the quick reply. Yes I had and what I have found is that I should use feeds api to do what I want to achieve. My question is not how to use feeds api to do this but if the feeds api is the best way to do this. Maybe there are other api endpoints I could use to do the same with one request since dealing with feeds endpoint requires more than one request.

**Comment by charliecode** [comment]
@dsokolowski I wish I could help more with the specifics of your question. The API is just newly launched and a lot of us are making our way around it also becoming familiar with it. Amazon is also fine tuning their docs so not everything is available yet, it's kind of a painful period until everything gets finished. In the event you were not away [there are a few guides which are more detailed](https://github.com/amzn/selling-partner-api-docs/tree/main/guides/use-case-guides) beyond the actual API docs. [One of them is for the feeds](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md). Hope this helps or someone else chimes in to help further.

**Comment by rugved1991** [comment]
Hi @dsokolowski,

You should be using Feeds API to upload information about the orders and shipment to Amazon. This is the recommended way which would allow you to upload information about the orders and shipments in bulk. The process to upload a feed contains multiple API calls but it allows you to perform bulk operation which avoids making frequent calls to the APIs.
For more information on how to implement feeds, feel free to refer to [Feeds Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md).

Thanks,
Rugved
Solutions Architect, SP API
