### ISSUE TITLE
How to pass required parameters in create report API?

### ISSUE THREAD

**Issue by anton-pon** [amzn/selling-partner-api-docs#781]
In the documentation is said, that the api POST /reports/2020-09-04/reports needs required parameters reportType and marketplaceID in the body
 body:{
            marketplaceIds: "A1PA6795UKMFR9",
            reportType:"GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING",
            CreatedAfter:"2021-05-25T12:37:36Z"
}
When I'm trying to create this body object, i receive the error message 
"UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object"

So i tried to put all this in a string but i am not sure if this is correct, because for me this looks very strange:
body:'{marketplaceIds: "A1PA6795UKMFR9", reportType:"GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING", CreatedAfter:"2021-05-25T12:37:36Z"}'

Can you tell me how I can pass the necessary parameters?

**Comment by ianrussel** [comment]
marketplaceIds should be array 
         
                marketplaceIds: ["A1PA6795UKMFR9"]

**Comment by dobariyarakesh** [comment]
@anton-pon marketplaceIds is array of string. let me know still facing issue.

**Comment by ionafan2** [comment]
Hi guys. 
Can you please tell me what I'm doing wrong here? 
![image](https://user-images.githubusercontent.com/807543/125851496-a892dea9-c540-45ff-ba12-ec2b2ed65cb0.png)

**Comment by ianrussel** [comment]
I think you need to pass the request body as json. So click Body tab, then add you request like 

       reportType: "reporttype"
      marketpalceIds: ["markeplaces1"."marketpalces2"]
      dataStartTime: "2021-03-31"
      dataEndTiem: "2021-05-01"
![Uploading sp.png…]()
