### ISSUE TITLE
when can release fba-inventory-api in the Europe and Far East regions.

### ISSUE THREAD

**Issue by yuql** [amzn/selling-partner-api-docs#783]
In document (https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md) Tell me The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network. Today this API is available only in the North America region. In 2021 we plan to release this API in the Europe and Far East regions.

I want to know the specific date ?

**Comment by jimmy-ross-xapix** [comment]
I would love to know this too - Im currently just assuming its not available when I get a 403 error

**Comment by ulandj** [comment]
Hi @krithic15 ,
do you know is there an ETA for this? Thanks

**Comment by cccaimingjian** [comment]
waiting +1

**Comment by JKrug1** [comment]
We are waiting too! The year 2021 is drawing to a close. Maybe it will be a Christmas present?

**Comment by emilianmanolache** [comment]
Hi! Any news on this? It's already 2022. Please, we desperately need this for a client's application.
Thank you!
