### ISSUE TITLE
Download the report "GET_MERCHANT_LISTINGS_ALL_DATA" only contain headers

### ISSUE THREAD

**Issue by dobariyarakesh** [amzn/selling-partner-api-docs#784]
Hello

I have tool that download the report "GET_MERCHANT_LISTINGS_ALL_DATA" and its working well till 21 May and after 21 May there is no exception in download report but in report csv only contain headers and there is no product listing details.

Can you check the issue and let me know what is the issue ?

Thanks

**Comment by Tech77** [comment]
Reports of this problem have been something of a trending topic over in the official Amazon Seller Forums over the last week; some are reporting success with specifying the MarketPlaceID in the call, and/or the "optional" MarketplaceIdList.Id.1.

**Comment by dobariyarakesh** [comment]
Yes that is work for me and also implemented. not sure why amazon suddenly modify his system without informing to the developer. 
If API parameter allow single marketplaceid why they are allow list of marketplaceid in the API call its must be single.
