### ISSUE TITLE
Application not published after 14 days

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#787]
Our application was approved May 12th and the email said it would be published within 10 days.  It has now been 14 days.

App ID - amzn1.sp.solution.5ba0226e-999f-4a49-8adf-bf8cd388bc6e

I also put a case in: 8388833091

**Comment by ShivikaK** [comment]
Hello @hrhearn7 

Your application has been successfully published. Can you confirm if you can see the app status as Published in Seller Central?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by hrhearn7** [comment]
I can - thank you!
