### ISSUE TITLE
Product returned from getPrice does not contain AttributeSets

### ISSUE THREAD

**Issue by leeningyap** [amzn/selling-partner-api-docs#788]
We are trying to migrate from the GetMatchingProductForId on the MWS Products endpoint. We use this to collect product information.

On SP API, when I call **getPrice**, the Product in the Price does not contain the AttributeSets.
However when I use **getCatalogItem** on the same SKU, the AttributeSets are indeed returned for the same product.
I'd like to use **getPrice** so that I'm able to specify more than one SKU at a time when gathering information

Am I missing anything here or will I need to getCatalogItem per product?

Thanks

**Comment by chapmanjw** [comment]
The `getPrice` and `getCatalogItem` v0 APIs were ported from the MWS Products API `GetMyPriceForASIN` and `GetMatchingProductForId` operations respectively. These were previously separate operations that happen to share an object model, but never returned both sets of data in the same request. This has carried forward with the ported APIs as well. 

The MWS Products API `GetMatchingProductForId` and v0 `getCatalogItem` operations are both being deprecated in the coming year, see https://github.com/amzn/selling-partner-api-docs/discussions/1041 for more details.

The 2020-12-01 (and subsequent iterations) of the Catalog Items APIs are the place to get ASIN data, see https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md for more details.

**Comment by cetetesoft** [comment]
Where is `getPrice`? I can't find that API anywhere. Do you mean `getPricing`? I'm looking for the equivalent of `GetMyPriceForASIN` (with buying price, regular price, fulfillment channel...).

**Comment by chapmanjw** [comment]
Yes, `getPricing` with the ASIN parameter populated is the equivalent of `GetMyPriceForASIN`: https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing
