### ISSUE TITLE
In feeds_2021-06-30.md  there is not  encryptionDetails in CreateFeedDocumentResponse.

### ISSUE THREAD

**Issue by xunbei100** [amzn/selling-partner-api-docs#789]
why CreateFeedDocumentResponse in feeds_2021-06-30.md don't have the CreateFeedDocumentResult and so don't have the CreateFeedDocumentResult.encryptionDetails"member field. 

Does it means that it's not need to encrypt the feed data any more when uploading a feed data before creating a feed.

**Comment by nodisk8800** [comment]
2021-06-30 版本的Reports/Feeds 都去掉了加密/解密.
主要是亚马逊觉得当前的数据和操作方式已满足安全的需要,可以不再使用加密/解密的方式,所以出了新版本,方便程序员开发.

**Comment by stefnats** [comment]
This is not unimportant. For all that do not speak chinese:

@nodisk8800 wrote:

>2021-06-30 version of Reports/Feeds are removed from encryption/decryption.
The main reason is that Amazon feels that the current data and operation methods have met the need for security and can no longer use the encryption/decryption method, so the new version was released to facilitate the development of programmers.

>I tested the 2021-06-30 version a while ago and found that it doesn't work yet.
I'm not sure if I have to wait until July 1st to use it.

**Comment by johnkw** [comment]
Similar to bug #363 - this has been deprecated entirely. The feeds_2020-09-04.md document should be updated to tell people in huge letters at the top to use the new version instead, and then this ticket should be closed. @parvathm ?
