### ISSUE TITLE
How to pass Authentication , Session token and STS temporary credentials in reports API Swagger client

### ISSUE THREAD

**Issue by arunkkram-tech** [amzn/selling-partner-api-docs#794]
Hi,

I am beginner to SP API.

I understood from GitHub that call to SP-API is done in 3 steps
1. Get Temporary keys from STS
2. Get Access token
3. Use keys and token from above to call SP-API 

I am able to retrieve STS temporary keys (from endpoint https://sts.eu-west-1.amazonaws.com)
and access token  (from endpoint https://api.amazon.com/auth/o2/token)

I used following swagger model to generate Python client to call  is  given below

_selling-partner-api-models/models/reports-api-model/reports_2020-09-04.json_

_However,   call to Reports API ( get_reports) response is given below

ERROR

Exception when calling ReportsApi->get_reports: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 27 May 2021 15:45:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '135', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'c378a237-8893-4e83-90a7-e4a5c5378244', 'x-amzn-ErrorType': 'MissingAuthenticationTokenException', 'x-amz-apigw-id': 'f_q6yHnuDoEFvQg='})
HTTP response body: {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "MissingAuthenticationToken"
    }
  ]
}_

I tried to modify following files , to pass authentication parameters , token and temporary keys 

**a. SWAGGER_CLIENT > configuration.py** 

**b. SWAGGER_CLIENT>api>reports_api.py** 

        ```
path_params = {}
        if 'report_id' in params:
            path_params['reportId'] = params['report_id']  # noqa: E501

        query_params = []
        header_params = {}

        temp_credentials = getstscreds()
        access_token = getaccesstoken()

        **header_params["x-amz-access-token"] = access_token["access_token"]
        header_params["X-Amz-Security-Token"] = temp_credentials["SessionToken"]**

        form_params = []
        local_var_files = {}
```

Pls guide me to pass authentication parameters , token and temporary keys in swagger client

**Comment by rugved1991** [comment]
Hi @arunkkram-tech,

Check out the new Selling Partner API on AWS QuickStart for a quick setup of SP APIs using Python Lambda. The IAM setup is automated so no need to worry about the setup. Just follow the instructions on the deployment guide of the QuickStart and you will be up and running in no time.

https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

Feel free to open issues or provide feedback on the issues page of the QuickStart.

Thanks,
Rugved
Solutions Architect, SP API.

**Comment by YChanHuang** [comment]
@rugved1991 I have the same issue and this [documentation ](https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities) tells that the STS is needed.

Could you confirm what does STS do?
