### ISSUE TITLE
fba/inventory/v1/summaries 403 error

### ISSUE THREAD

**Issue by defenderjim** [amzn/selling-partner-api-docs#795]
https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries

Anyone else having issues accessing this endpoint?

I am able to access other endpoints, no problem.
I checked that access was granted in Seller Central.

Header:
`Content-Type=application/json`

I am performing a GET to:
`https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?MarketplaceIds=ATVPDKIKX0DER&granularityType=Marketplace&granularityId=ATVPDKIKX0DER1`

With the response:
Access to requested resource is denied.
Unauthorized

**Comment by jimmy-ross-xapix** [comment]
i also cant access it despite having all roles enabled. I thought it might be because the store Im working on is in EU and the documentation indicates it will be released in EU at some point in "2021"...

But have not had confirmation on this either...

**Comment by defenderjim** [comment]
Docs do say EU not available yet.  Hopefully soon!  But I think the docs meant to say, "Not Available Anywhere"!  ;)

**Comment by defenderjim** [comment]
Working!  It turns out when you change permissions in Seller Central, you have to gen a new Refresh Token.
