### ISSUE TITLE
listCatalogItems 400  Bad Request

### ISSUE THREAD

**Issue by victor-haha** [amzn/selling-partner-api-docs#798]
Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/catalog/v0/items?MarketplaceId=ATVPDKIKX0DER, tag=Request{method=GET, url=https://sellingpartnerapi-na.amazon.com/catalog/v0/items?MarketplaceId=ATVPDKIKX0DER, tag=null}}

Give only the MarketplaceID parameter, which should be fine according to the documentation, but this error is returned

**Comment by chapmanjw** [comment]
The V0 ListCatalogItems API does not support queries without filter parameters provided. Either `query` or one of the identifier parameters needs to be provided: https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md

**Comment by chapmanjw** [comment]
Please also consider using the 2020-12-01 version instead: https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md. The V0 version will be deprecated next year: https://github.com/amzn/selling-partner-api-docs/discussions/1041.
