### ISSUE TITLE
VendorDirectFulfillmentOrdersV1 --> Forbidden: Access to requested resource is denied

### ISSUE THREAD

**Issue by evesoftware** [amzn/selling-partner-api-docs#80]
Followed the videoguide in API_TTH.mp4.

Attached SP-API policy directly to the IAM user, tested with the policy simulator, OK.

Application created (by amazon), client created and granted by myself  in sellingpartner/developerconsole (I have full rights in vendor central on the vendor data)

NOTE: at the time the app was registered there was no menu in vendorcentral to access the developer console and the button "register as developer" was missing.

The first test with postman WORKED!!! but i get an empty list in the response, while many orders are visible in vendor central.

using production endpoint:

<b>response.StatusDescription:</b>
<code>OK</code>
<b>response.Content:</b>
<code>{"payload":{"orders":[]}}</code>

same call using sandbox endpoint (and parameters as in the example):

<b>response.StatusDescription:</b>
<code>Internal Server Error</code>
<b>response.Content:</b>
<code>{
     "errors": [
   {
    "message": "We encountered an internal error. Please try again.",
    "code": "InternalFailure"
   }
 ]
}</code>

Opened a support case in vendorcentral (ID6342484702) on Sep 15, 2020 02:51 AM.

After a while appeared a new menu in vendorcentral and the button "register as developer" in the console.
When I registered the application there was no request for "registering as developer",   so I followed the link and succesfully created a SP-API Developer Profile.

After that, THE SAME POSTMAN CALL returns:  

<b>response.StatusDescription:</b>
<code>Forbidden</code>
<b>response.Content:</b>
<code>
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}</code>

same using the sandbox endpoint.

I tested another brand new client with the same results.

Added the new test results to the same support case on Oct 13, 2020 02:31 AM.

Here an extract of the c# client i am using, I haven't received any feedback from support yet so I admit I'm a little frustrated.
Any suggestions will be very welcome.

<code>

	public class DirectFulfillmentClient
    {
        private string userAgent;
        private string awsEndPoint;
        private LWAAuthorizationCredentials lwaCredentials;
        private AWSAuthenticationCredentials awsCredentials;

        public DirectFulfillmentClient(AWSAppConfig config) {
            userAgent = config.UserAgent;
            awsEndPoint = config.AWSEndPoint;

            lwaCredentials = new LWAAuthorizationCredentials()
            {
                ClientId = config.ClientId,
                ClientSecret = config.ClientSecret,
                Endpoint = new Uri(config.LWAEndPoint),
                RefreshToken = config.RefreshToken
            };                

            awsCredentials = new AWSAuthenticationCredentials()
            {
                AccessKeyId = config.AccessKeyId,
                SecretKey = config.SecretKey,
                Region = config.Region
            };
        }

        /// <param name="fromDate">Orders that became available after this time will be included in the result. Date range to search must not be more than 7 days.This field is expected to be in ISO-8601 date/time format, for example:2018-07-16T23:00:00Z/ 2018-07-16T23:00:00-05:00 /2018-07-16T23:00:00-08:00</param>
        /// <param name="toDate">Orders that became available before this time will be included in the result. Date range to search must not be more than 7 days.This field is expected to be in ISO-8601 date/time format, for example:2018-07-16T23:00:00Z/ 2018-07-16T23:00:00-05:00 /2018-07-16T23:00:00-08:00</param>
        /// <param name="includeDetails">Default value is true. If entered as 'true', this API will return list of orders with complete details. If entered as 'false' or not included in filter, then only purchase order numbers are returned.</param>
        /// <param name="shipFromPartyId">The vendor warehouseId from which the order will be fulfilled. If not specified the result will contain orders for all warehouses.</param>
        /// <param name="sortOrder">Sort ASC or DESC by order creation date.</param>
        /// <param name="limit">The limit to the number of records returned</param>
        /// <param name="nextToken">Used for pagination when there are more orders than the specified result size limit. The token value is returned in the previous API call.</param>
        public GetOrdersResponse GetOrders(DateTime fromDate, DateTime toDate, string includeDetails, string shipFromPartyId, string sortOrder, long? limit, string nextToken)
        {
            if (fromDate == null)
                throw new ArgumentNullException("fromDate");

            if (toDate == null)
                throw new ArgumentNullException("toDate");

            string resource = "/vendor/directFulfillment/orders/v1/purchaseOrders";

            RestClient client = new RestClient(this.awsEndPoint) { UserAgent = this.userAgent };
            IRestRequest request = new RestRequest(resource, Method.GET)
                .AddHeader("cache-control", "no-cache")
                .AddHeader("Content-Type", "application/x-www-form-urlencoded");

            request = new LWAAuthorizationSigner(this.lwaCredentials).Sign(request);

            request.AddParameter("createdAfter", fromDate.ToString("s", System.Globalization.CultureInfo.InvariantCulture), ParameterType.QueryString);
            request.AddParameter("createdBefore", toDate.ToString("s", System.Globalization.CultureInfo.InvariantCulture), ParameterType.QueryString);
            if (includeDetails != null)
                request.AddParameter("includeDetails", includeDetails, ParameterType.QueryString);
            if (shipFromPartyId != null)
                request.AddParameter("shipFromPartyId", shipFromPartyId, ParameterType.QueryString);
            if (sortOrder != null)
                request.AddParameter("sorted", sortOrder, ParameterType.QueryString);
            if (limit != null)
                request.AddParameter("limit", limit, ParameterType.QueryString);
            if (nextToken != null)
                request.AddParameter("nextToken", nextToken, ParameterType.QueryString);

            request = new AWSSigV4Signer(this.awsCredentials).Sign(request, client.BaseUrl.Host);

            IRestResponse response = client.Execute(request);

            foreach (var h in response.Headers) {
                Debug.Print(h.Name + " = " + h.Value);
            }
            Debug.Print(response.StatusCode.ToString());
            Debug.Print(response.StatusDescription);
            Debug.Print(response.Content);

            if (response.IsSuccessful)
            {
                var res = GetOrdersResponse.FromJson(response.Content);

                if (res != null)
                {
                    if (res.Errors != null)
                    {
                        foreach (var er in res.Errors)
                        {
                            Debug.Print(string.Format("Error: {0} - {1}", er.Code, er.Message));
                            if (!string.IsNullOrEmpty(er.Details)) Debug.Print(er.Details);
                        }
                    }
                    if (res.Payload?.Orders != null)
                    {
                        Debug.Print(string.Format("Orders count: {0}", res.Payload.Orders.Count));
                    }
                    return res;
                }
                else 
                {
                    throw new ApplicationException("GetOrders: The content cannot be deserialized");
                }
            }
            else 
            {
                var ermsg = new StringBuilder();

                ermsg.Append("GetOrders: ");
                ermsg.Append(response.StatusDescription);
                if (response.ErrorException != null)
                {
                    ermsg.Append(" (" + response.ErrorMessage + ")");
                }

                if (response.Content != null)
                {
                    ermsg.AppendLine("");
                    ermsg.Append(response.Content);
                }

                throw new ApplicationException(ermsg.ToString());
            }
        } }

</code>

**Comment by seanevan** [comment]
Hi @evesoftware, I will follow-up on your support case to ensure it gets prompt attention.

Best regards,
Sean Evans
Manager, Support Engineering

**Comment by zhanfjunjun** [comment]
@evesoftware Hello, have you solved this problem? I also encountered the same problem

**Comment by evesoftware** [comment]
@zhanfjunjun Unfortunately no

**Comment by evesoftware** [comment]
@seanevan and @zhanfjunjun, if it can help, after more than two months of opening the support case #6342484702 with no answers and after trying to figure out by myself what the problem is, I found that:
<b>if I make the exact same call</b> using 
<code>/vendor/orders/v1/purchaseOrders</code> 
instead of 
<code>/vendor/directFulfillment/orders/v1/purchaseOrders</code> 
<b>it is successful!!!</b>
<code>
STATUS: OK
{"payload":{"pagination":{"nextToken":"WyI4SVg2UklKQSIsIjhJWDZSSUpBIl0"},"orders":[{"purchaseOrderNumber":"8Z4SLMIC","purchaseOrderSt.....................</code>
obviously the content of the answer is only partially compatible with the definition in 
<code>DirectFulfillment_API_Vendor_Documents</code>
but I am actually seeing the orders I have been trying to access since September.
I believe this rules out signin problems or errors in the request, but now the question is: are Direct Fulfillment APIs active?
If so, why do I get "Unauthorized"? 
When creating the application I explicitly requested access to the Direct FulFillment API and the answer says (support case #6323106862):
<b>"Your application with access to Direct Fulfillment has been created successfully!"</b>
Also, after creating the profile, amazon in support case # 6414909022 says: 
<b>Your SP-API access request has been approved. You now have global marketplace access to SP-API based on your required roles.</b>

in fact, it seems that it is possible to access to some APIs but not to those defined in DFAPI_Reference_Guide.pdf, 
which are what we need.

I would very much appreciate if someone could identify the problem and tell me if I am doing something wrong or there is a need to intervene on the server side, since time is running out and I need to complete the application as quickly as possible.

Thank You!

**Comment by anxin3611** [comment]
Hello, have you solved this problem? Can you share with me how you solved it? Thank you.

**Comment by rugved1991** [comment]
Hi @anxin3611 and @evesoftware,

The Direct Fulfillment API requires access to "Direct-To-Consumer Shipping" role. If you have not requested this restricted role, you would need to fill out the developer registration again and provide additional information. 
If you are working with multiple vendors, you should be using your seller central account to create an application and using OAuth flow to receive authorization from vendors. Please refer to issue #222 for more information on how to authorize multiple vendors.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by tomhirschfeld** [comment]
@evesoftware  


We are blocked on a lack of vendor central documentation. You can only see that documentation if you have a vendor central developer account, and none of our vendor partners have a developer account so we are blocked here. If you can compile the docs into either an HTML folder or a PDF file and send to me I will venmo/paypal/cashapp/mail you $50.

**Comment by rugved1991** [comment]
Hi @tomhirschfeld,

Thanks for your patience. We have updated the GitHub repository with the Vendor APIs documentation. Please check out the references and swagger models in the following links:
https://github.com/amzn/selling-partner-api-docs/tree/main/references
https://github.com/amzn/selling-partner-api-models/tree/main/models

Thanks,
Rugved
Solutions Architect, SP API

**Comment by glukoid** [comment]
@rugved1991

could you please help me to understand what I am doing wrong with request to "/vendor/directFulfillment/orders/v1/purchaseOrders"

I am trying to create application for my own usage and what I am trying to receive is shipping information for my orders.
I do have Direct-to-Consumer Shipping permissions.

1. I got restrictedDataToken for both "/vendor/directFulfillment/shipping/v1/shippingLabels" and "/vendor/directFulfillment/orders/v1/purchaseOrders"
2. Signed with restricted token
3.Signed with STSKeys and SecurityToken
4. executed request to https://sellingpartnerapi-na.amazon.com for "/vendor/directFulfillment/orders/v1/purchaseOrders"
5. response:
"errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }

thx




OI

**Comment by pucsdian** [comment]
@glukoid 
hey can u tell me how did u get RDT 
i am getting error 
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}
request body :- 
{
	"restrictedResources": [
		{
			"method": "GET",
			"path": "/vendor/directFulfillment/orders/v1/purchaseOrders"
		}
	]
}

**Comment by rugved1991** [comment]
Hi @pucsdian @glukoid,

Can you please confirm if you are now able to make successful calls to the Vendor Direct Fulfillment API with RDT token? 
If you are still seeing an issue, please open a support case with the details and provide us the case ID.

Best,
Rugved
Solutions Architect, SP API

**Comment by pucsdian** [comment]
yes, it's working now

**Comment by rajat-garg** [comment]
@pucsdian , Can you please tell me which path you used for getting RDT for Vendor Direct Fulfillment APIs?

**Comment by pucsdian** [comment]
hey @rajat-garg 
my json look like for bulk purchase orders
`{
	"restrictedResources": [
		{
			"method": "GET",
			"path": "/vendor/directFulfillment/orders/v1/purchaseOrders/"
		}
	]
}`

and for single po
`{
	"restrictedResources": [
		{
			"method": "GET",
			"path": "/vendor/directFulfillment/orders/v1/purchaseOrders/{purchase_order_number}"
		}
	]
}`

Thanks ,
pucsdian

**Comment by summanbahadurVolo** [comment]
I am also having the same issue , error :
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Application do not have access to some or all requested resource",
            "details": ""
        }
    ]
}

i can get the token if i add "targetApplication": "amzn1.application-oa2-client.***"
but if i remove this optional field it gives above error:

request body:

{ "restrictedResources":
    [
        { "method": "GET" , "path": "/vendor/directFulfillment/orders/v1/purchaseOrders"}//,
               
    ]
}

**Comment by justicierogorek** [comment]
@summanbahadurVolo I have the same error. Did you solve it?

**Comment by summanbahadurVolo** [comment]
yeah , Check the refresh token that you are using. 
For me i was using refresh token for amazon seller central , got the token generated for Vendor Central that helped

**Comment by justicierogorek** [comment]
@summanbahadurVolo do you have the restrictive permissions in your developer profile (Direct-to-Consumer/Tax Invoicing/Tax Remittance)?? I don't know if they are necessary.
