### ISSUE TITLE
How to get the complete xsd list

### ISSUE THREAD

**Issue by wmh49877** [amzn/selling-partner-api-docs#800]
I upload products through feeds, but I can't write xml data,
I read [](url) https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf, 
but I can't get the complete xsd
Can someone tell me how to upload xml files through xsd?

**Comment by chapmanjw** [comment]
Category-Specific XSDs define the XML feeds for creating products and are available on Seller Central: https://sellercentral.amazon.com/gp/help/G200385010.
