### ISSUE TITLE
Why does the updateInboundShipment API not support adding new products to existing shipments?

### ISSUE THREAD

**Issue by jason1004** [amzn/selling-partner-api-docs#801]
API Response：

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": " Reason: Invalid attempt to add following new item(s) to shipment FBAXXXXXXXX: SELLERSKU.",
      "details": ""
    }
  ]
}

This can be done in MWS！

**Comment by kingsun-he** [comment]
I have the same question.

**Comment by hrhearn7** [comment]
I have the same question!  I was actually designing our system (based off of MWS documentation) in hopes to create a better ltl load by bringing shipments going to the same DC together where the plan gave diff shipmnetid for same dc.  Makes me wonder if you can call more than 200  sku's to get a plan.

**Comment by hrhearn7** [comment]
Another question - Why does this plan produce multiple shipment id’s when it is going to the same Amazon DC? and there are no special prep to be done?

Body sent -
{
“ShipFromAddress”: {
“Name”: “XXXXXX”,
“AddressLine1”: “XXXXX”,
“AddressLine2”: " ",
“City”: “XXXXX”,
“StateOrProvinceCode”: “NC”,
“CountryCode”: “US”,
“PostalCode”: “27265”
},
“ShipToCountryCode”: “US”,
“ShipToCountrySubdivisionCode”: null,
“LabelPrepPreference”: “SELLER_LABEL”,
“InboundShipmentPlanRequestItems”: [
{
“SellerSKU”: “HHBICERSGP41AST”,
“ASIN”: “B00GFUY0M8”,
“Condition”: “NewItem”,
“Quantity”: “20”,
“QuantityInCase”: “10”
},
{
“SellerSKU”: “HHBICMRC21BK”,
“ASIN”: “B00J2FJK32”,
“Condition”: “NewItem”,
“Quantity”: “20”,
“QuantityInCase”: “10”
}
]
}

Returned payload:

{
“payload”: {
“InboundShipmentPlans”: [
{
“ShipmentId”: “FBA166K4864M”,
“DestinationFulfillmentCenterId”: “CLT2”,
“ShipToAddress”: {
“Name”: “Amazon.com Services, Inc.”,
“AddressLine1”: “10240 Old Dowd Rd”,
“City”: “Charlotte”,
“StateOrProvinceCode”: “NC”,
“CountryCode”: “US”,
“PostalCode”: “28214-8082”
},
“LabelPrepType”: “SELLER_LABEL”,
“Items”: [
{
“SellerSKU”: “HHBICMRC21BK”,
“FulfillmentNetworkSKU”: “X002X4FHNR”,
“Quantity”: 20
}
],
“EstimatedBoxContentsFee”: {
“TotalUnits”: 20,
“FeePerUnit”: {
“CurrencyCode”: “USD”,
“Value”: 0.15
},
“TotalFee”: {
“CurrencyCode”: “USD”,
“Value”: 3
}
}
},
{
“ShipmentId”: “FBA166K19GSR”,
“DestinationFulfillmentCenterId”: “CLT2”,
“ShipToAddress”: {
“Name”: “Amazon.com Services, Inc.”,
“AddressLine1”: “10240 Old Dowd Rd”,
“City”: “Charlotte”,
“StateOrProvinceCode”: “NC”,
“CountryCode”: “US”,
“PostalCode”: “28214-8082”
},
“LabelPrepType”: “NO_LABEL”,
“Items”: [
{
“SellerSKU”: “HHBICERSGP41AST”,
“FulfillmentNetworkSKU”: “B00GFUY0M8”,
“Quantity”: 20
}
],
“EstimatedBoxContentsFee”: {
“TotalUnits”: 20,
“FeePerUnit”: {
“CurrencyCode”: “USD”,
“Value”: 0.15
},
“TotalFee”: {
“CurrencyCode”: “USD”,
“Value”: 3
}
}
}
]
}
}

**Comment by moishe1927** [comment]
having the same issue:

if a shipment plan returns items to sent to a fulfillment center that i alrady have an open shipment to it, how can i add the planned items to an existing shipment?

**Comment by AceGray** [comment]
有同样的问题；你们解决了吗？

**Comment by BDimaurizio** [comment]
I am also wondering this. Is it planned to be implemented in the future? It was a feature in the old deprecated API.

**Comment by homes2001** [comment]
I tried now the same request with the MWS API and the SP API and it works on first, but does not work on SP API. So this is definitely a problem with SP API.

**Comment by miraemor** [comment]
Is there any updates? Tried recently and it still fails to add new items to shipment

**Comment by kaipaysen** [comment]
At least the SP-API docs told us https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#updateinboundshipment "Adding new items is not supported.". How are we supposed to migrate our process (which usually involves > 200 SKUs per Shipment) to SP-API?

**Comment by giga666** [comment]
Same problem here. Amazon told me, that MWS-Worflow https://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_CreateShipment200Items.html
does not work for SP-API.

But Amazon also says: "June 2022: If you ship large shipments to fulfillment centers, you can now create shipments with up to 5000 boxes and 2000 SKUs"
https://sellercentral.amazon.de/gc/send-to-amazon

So how can I do this if "createInboundShipment" does not support more then 200 items and "updateInboundShipment" does not allow to add items?

**Comment by kaipaysen** [comment]
Amazon Support agreed it's not working with SP-API. They don't know if or when it will be fixed. If you can, stay with MWS.

**Comment by fr3shn3ss** [comment]
Everyone should create a support case with Amazon. We should push them to do it. 

I did and they acknowledge the issue.

**Comment by maulikb-emipro** [comment]
Please let me know if this is resolved or working for anyone.

**Comment by A-BlackMoon** [comment]
It is almost 2024 and MWS will be discontinued. Has this issue been resolved yet

**Comment by kpconnell** [comment]
Bump

**Comment by homes2001** [comment]
has anyone figured out how to send shipments with > 200 SKUs?

**Comment by MojoJake** [comment]
Anyone heard of any plans to restore this functionality? Not sure how they justify removing it...
