### ISSUE TITLE
How can i reuse the Access Token?

### ISSUE THREAD

**Issue by xbaha** [amzn/selling-partner-api-docs#802]
I successfully called "/orders/v0/orders/{orderId} Api after exchanging the refresh token with an Access Token,
but now if I want to call the API for a different order, do I have to request a new access token?
when I used the same access token, I got the signature error:
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method

The response worked by exchanging the refresh token with the access token.
```
restRequest.resource = $"/orders/v0/orders/" + orderId1;
restRequest = authHelper.SignWithAccessToken(restRequest, credentials.LWA_App_ClientId, credentials.LWA_App_ClientSecret, credentials.RefreshToken);
restRequest = authHelper.SignWithSTSKeysAndSecurityTokenn(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
IRestResponse response = client.Execute(restRequest);  //ok response
```

then I tried to add the access token for future API requests:
```
restRequest.resource = $"/orders/v0/orders/" + orderId2;
restRequest.AddParameter("x-amz-access-token","Atza|IwEBIMrmE...", ParameterType.QueryString);
restRequest = authHelper.SignWithSTSKeysAndSecurityTokenn(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
response = client.Execute(restRequest); //signature error
```

Please advise if we need to request for access token every time we change the parameters?

thank you.,

**Comment by nodisk8800** [comment]
Renew the request
