### ISSUE TITLE
Quotaexceed wait time

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#803]
What is the wait time to request again, if an API is Quotaexceeded?

**Comment by nodisk8800** [comment]
See the API document.
if 2 / second, you can Thread.sleet(2000)

**Comment by stefnats** [comment]
I think Rate Limit & QuotaExceeded might be different things.
Rate Limit as in "please wait some time and retry your call"
QuotaExceeded as in "you called too often, you can retry at a later time, tomorrow or so."
