### ISSUE TITLE
"Application do [sic] not have access to some or all requested resource" when creating RDT for getReportDocument

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#806]
I'm trying to create a restricted data token that will allow me to fetch a `GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING` report document, but when I request the RDT, I get this error:

```json
{
    "code": "InvalidInput",
    "message": "Application do not have access to some or all requested resource",
    "details": ""
} 
```
I've been approved for the `Direct-to-Consumer Shipping` role, so I should be able to access the report. My request to the `createRestrictedDataToken` endpoint looks like this:

```
POST https://sellingpartnerapi-na.amazon.com/tokens/2021-03-01/restrictedDataToken
x-amz-date: 20210530T221000Z
x-amz-access-token: Azta|.......
Content-Type: application/json
Host: sellingpartnerapi-na.amazon.com
Authorization: ......

{
    "restrictedResources": {
        "method": "GET",
        "path": "/reports/2020-09-04/documents/amzn1.spdoc....."
    }
}
```

I've also tried using the `2021-06-30` version of the `getReportDocument` endpoint, with the same result.

**Comment by glukoid** [comment]
hello

did you happen to solve this issue ? I am having same error on try to get RDT

**Comment by jlevers** [comment]
Unfortunately not -- if any of the Amazon developers could chime in on this, it would be much appreciated.

**Comment by jlevers** [comment]
I created a support case related to this problem: #8427320701

**Comment by rajbirverma** [comment]
Hello, any updates here? I am having same issue when trying ti get RDT.

**Comment by jlevers** [comment]
I still haven't heard anything -- @parvathm @ShivikaK could you please look into this? This is preventing one of my clients from getting the data they need for their business.

**Comment by jlevers** [comment]
I just figured this one out -- it was an error in my body payload. I was sending this:

```json
{
    "restrictedResources": {
        "method": "GET",
        "path": "/reports/2020-09-04/documents/amzn1.spdoc....."
    }
}
```
Instead of this:

```json
{
    "restrictedResources": [
        {
            "method": "GET",
            "path": "/reports/2020-09-04/documents/amzn1.spdoc....."
        }
    ]
}
```

Note that in the second snippet, `restrictedResources` is an _array of objects_ rather than a standalone object.
