### ISSUE TITLE
Help , how to receive messages from notifications api ?

### ISSUE THREAD

**Issue by HuUncle** [amzn/selling-partner-api-docs#807]
I configured it according to the document [notifications-api](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md) , step by step ，and I set  sqs this permissions ：
```
{
  "Version": "2008-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "__owner_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": ""
      },
      "Action": "SQS:*",
      "Resource": "
    },
    {
      "Sid": "__sender_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
      },
      "Action": "SQS:SendMessage",
      "Resource": ""
    },
    {
      "Sid": "__receiver_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": ""
      },
      "Action": [
        "SQS:ChangeMessageVisibility",
        "SQS:DeleteMessage",
        "SQS:ReceiveMessage"
      ],
      "Resource": ""
    }
  ]
}
```
but cannot receive message , so what should I do to get notifications from SQS?

**Comment by stefnats** [comment]
Can you post the response & requests from 

1. Creating the destination and
2. Creating the subscription?

**Comment by HuUncle** [comment]
@stefnats   yeah , I created the destination and subscription  ，and the response was successful

**Comment by HuUncle** [comment]
@stefnats 
create destination ：
![image](https://user-images.githubusercontent.com/19486270/120149543-73a50700-c21c-11eb-957e-415a7d7f9baf.png)
create subscription：
![image](https://user-images.githubusercontent.com/19486270/120149716-afd86780-c21c-11eb-8362-0db2d28570a9.png)

everything it seems like right ， but cannot receive message

**Comment by stefnats** [comment]
Hm seems nothing wrong.
Is you SQS Queue empty?
Sometimes it can take some time (minutes) that the sqs queue fills. 
What notification type did you subscribe to?

**Comment by HuUncle** [comment]
> Hm seems nothing wrong.
> Is you SQS Queue empty?
> Sometimes it can take some time (minutes) that the sqs queue fills.
> What notification type did you subscribe to?

I subscribed these type last Friday and so far it's empty.
+ ANY_OFFER_CHANGED
+ B2B_ANY_OFFER_CHANGED
+ FBA_OUTBOUND_SHIPMENT_STATUS
+ FEE_PROMOTION
+ FULFILLMENT_ORDER_STATUS

**Comment by stefnats** [comment]
Just guessing here, have you tried changing the price of a listing? That should trigger a notification if your listing is active (quantity > 0 and visible on the Amazon website)

**Comment by HuUncle** [comment]
> Just guessing here, have you tried changing the price of a listing? That should trigger a notification if your listing is active (quantity > 0 and visible on the Amazon website)
Thanks for you reply , I'll give it a try.

**Comment by HuUncle** [comment]
@stefnats  
Sorry to trouble you , could you tell me 
How to get orders in real time ? ( such as order created on amazon website )
Is subscribe `FULFILLMENT_ORDER_STATUS` type ?

**Comment by stefnats** [comment]
Getting orders in real time is not possible i think (i found no notification type for that)
Only solution would be to request reports for that in a frequent manner, but this is not real time.

**Comment by HuUncle** [comment]
> Getting orders in real time is not possible i think (i found no notification type for that)
> Only solution would be to request reports for that in a frequent manner, but this is not real time.

Thanks

**Comment by fullpipe** [comment]
@HuUncle hello. 

Have you started to receive FBA_OUTBOUND_SHIPMENT_STATUS messages to SQS?

I think I have similar problem. Subscription for FULFILLMENT_ORDER_STATUS works fine. But no messages for FBA_OUTBOUND_SHIPMENT_STATUS.

**Comment by HuUncle** [comment]
> @HuUncle hello.
> 
> Have you started to receive FBA_OUTBOUND_SHIPMENT_STATUS messages to SQS?
> 
> I think I have similar problem. Subscription for FULFILLMENT_ORDER_STATUS works fine. But no messages for FBA_OUTBOUND_SHIPMENT_STATUS.

No , It's not working until now . 
If you have any ideas , we can communicate together .

**Comment by HuUncle** [comment]
I think Amazon documents need to be improved .
Now, it's to simple

**Comment by ms-transalis** [comment]
> @HuUncle hello.
> 
> Have you started to receive FBA_OUTBOUND_SHIPMENT_STATUS messages to SQS?
> 
> I think I have similar problem. Subscription for FULFILLMENT_ORDER_STATUS works fine. But no messages for FBA_OUTBOUND_SHIPMENT_STATUS.

@fullpipe Did you get notifications to work? I'm unable to receive any FULFILLMENT_ORDER_STATUS to SQS.

**Comment by fullpipe** [comment]
@ms-transalis, hello
Nope. Nothing helps.
I have recreated everything from the start. Before that had enabled most of the permissions to the API client. And still do not receive FBA_OUTBOUND_SHIPMENT_STATUS. 

Maybe I misunderstood docs. I need order shipping information and status. 🤷‍♂️
