### ISSUE TITLE
createReport returns Signature error

### ISSUE THREAD

**Issue by xbaha** [amzn/selling-partner-api-docs#808]
I am testing the createReport API 
i have successfully used the authentication to get orders, so no issue with that, but for reports, I am getting Forbidden, with signature calculated does not match message, here is my request:

![reports3](https://user-images.githubusercontent.com/10267198/120244605-3f255f80-c29d-11eb-939c-b98b94845be8.png)

I am not sure where I made a mistake with this request.
I also tried the swagger API and got the same error, please help!
```
            var apiInstance = new ReportsApi();
           var body = new CreateReportSpecification(null, "GET_FLAT_FILE_OPEN_LISTINGS_DATA",null,null, new List<string> { "ATVPDKIKX0DER" });
            CreateReportResponse result = apiInstance.CreateReport(body);
```

**Comment by hongtao0770** [comment]
@xbaha 

Have you ever used this new version？/reports/2021-06-30/documents/{reportDocumentId}

**Comment by hongtao0770** [comment]
Hey @xbaha ！
![image](https://user-images.githubusercontent.com/33300443/131202518-8132b8b0-eb8a-4f08-b332-f41aa8a88ffe.png)

Do you know how to turn this stream into an easy to read file? such as EXECL.

Thanks you for your help.

**Comment by xbaha** [comment]
you can try using Extention csvhelper i guess

**Comment by hongtao0770** [comment]
@xbaha

How do you handle downloaded files?

**Comment by xbaha** [comment]
It depends on what do you want to do and what logic you are trying to achieve!

**Comment by laySpring** [comment]
@yizeku 你好，我也遇到这个问题，提取订单成功，但是创建报告的时候始终报错。我看说明是get模式不是post，同时代码改成和你一样的也无法成功提取到报表数据，请教一下你是怎么解决的？

**Comment by yizeku** [comment]
@laySpring 

请问是哪一步出问题？

**Comment by laySpring** [comment]
> 
尝试了更换各种参数，比如Method.Get/Post的切换，传递参数的方式，传递的参数类型， 基本上都是遇到Forbidden这个问题。
![image](https://user-images.githubusercontent.com/34540140/144006174-2216e96f-a247-43fa-810c-0f2bb9a4d4b3.png)

**Comment by laySpring** [comment]
@yizeku 
尝试了更换各种参数，比如Method.Get/Post的切换，传递参数的方式，传递的参数类型， 基本上都是遇到Forbidden这个问题。
![image](https://user-images.githubusercontent.com/34540140/144006174-2216e96f-a247-43fa-810c-0f2bb9a4d4b3.png)

**Comment by laySpring** [comment]
@yizeku  谢谢，我刚刚改的时候，给解决掉了。Method.POST + ParameterType.RequestBody 可以成功提取到reportId。
