### ISSUE TITLE
/fba/inbound/v0/plans (createInboundShipmentPlan) Sandbox and Production errors. StatusCode 500 InternalFailure

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-docs#81]
I believe there might be an issue with the /fba/inbound/v0/plans endpoint as **it isn't working for production or sandbox calls**. I'm successfully connected to the SP-API and able to make successful production calls to multiple endpoints. However with this one, although I have the body exactly as it shows in the docs, I keep getting statusCode 400 with the below format, not giving me any details about where the issue is.

`{
  "code": "InvalidInput",
  "message": "Invalid Input",
  "details": ""
}`

For the sandbox call, again everything is exactly as is required to make a sandbox call. I have made probably 15 calls at different times and everytime I get a statusCode 500 with the below format.

`{
  "message": "We encountered an internal error. Please try again.",
  "code": "InternalFailure"
}`

**Comment by charliecode** [comment]
In the event anyone else has this happen, this was actually a problem with the request library the generator for my language is using within it's templates. The request body was being serialized multiple times, before and after the aws4 signature. The way in which it happened allowed the aws4 signature to be correct and the request to go through, and yet the body was actually invalid once checked by the API. Weird but that's what it was. Keep an eye out if your generated library has interceptors and be careful what you do inside them because they may not play well with the actual request library. Especially within the body.

**Comment by johnkw** [comment]
Was this different from the bug #343 content-type issue?  That vague useless API error needs to be documented/fixed, and it would be good to consolidate in one new bug report what all the possible causes are.

**Comment by wbmgaye** [comment]
@charliecode what generator/language are you using, I'm running into issues with typescript/axios and wondering if that might be the same.
