### ISSUE TITLE
Which API can get all the complete SKU data!!!!!!!

### ISSUE THREAD

**Issue by victor-haha** [amzn/selling-partner-api-docs#811]

**Comment by vikingcodes** [comment]
@victor-haha  You should add description to more clear your problem.

But if you want all product listings details then you can use Report API and use Inventory Report Type to get all inventory from seller account.

**Comment by victor-haha** [comment]
> @victor-haha 您应该添加描述以更清楚您的问题。
> 
> 但是如果您想要所有产品列表的详细信息，那么您可以使用 Report API 并使用 Inventory Report Type 从卖家帐户获取所有库存。
Okay, thank you。

**Comment by victor-haha** [comment]
> @victor-haha You should add description to more clear your problem.
> 
> But if you want all product listings details then you can use Report API and use Inventory Report Type to get all inventory from seller account.
Okay, thank you
