### ISSUE TITLE
[BUG] 400 Bad Request when using NextToken on GetOrders

### ISSUE THREAD

**Issue by BasilAlhakami-SonaEnterprises** [amzn/selling-partner-api-docs#812]
I receive a 400 Bad Request response, when calling the /orders/v0/orders endpoint.
when I have the NextToken in the request I submitted a case# 8390283141

this thread: https://github.com/amzn/selling-partner-api-docs/issues/550 
 
is discussing the same issue but with https://github.com/amzn/selling-partner-api-docs/issues/550

the bug was resolved by @parvathm for the financialEventGroups API

I wonder if the same fix should apply to Orders

Thanks

**Comment by ShivikaK** [comment]
Hello @BasilAlhakami-SonaEnterprises 

Thank you for raising this issue and providing the case ID.

The case is being reviewed by the Support team and additional details will be provided via the case.

Please continue monitoring the case for further updates.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by RamprasadAkella** [comment]
@ShivikaK  Can you please let us know what's the latest update on this ? We are also seeing the same issue on our side.

**Comment by BasilAlhakami-SonaEnterprises** [comment]
@RamprasadAkella the problem was that the token has '/' in the string so including it in the url breaks it. you need to url encode the token and that worked for me

**Comment by fernadodemitropulos** [comment]
the problem still exists, this thread should not be closed

**Comment by flagile** [comment]
this problem for order api is still existing, could you pls have to fix? thank you very much @ShivikaK [ShivikaK(https://github.com/ShivikaK)

**Comment by matijaskorup1991** [comment]
this problem is still here, why is this closed?
