### ISSUE TITLE
Did'nt get Address or Buyer info after generating RDT (RestrictedDataToken)

### ISSUE THREAD

**Issue by webinsect-rishabh** [amzn/selling-partner-api-docs#814]
I generated RDT (RestrictedDataToken) to get details like buyer info and address of orders. But after getting RDT token i still getting only that much data which i was getting with normal access token. Do i require any other permissions in my developer profile ? Can anyone help me on this ?

**Comment by Jay670** [comment]
You probably need the PII access/roles enabled in order to fetch buyers info like name and complete address.

**Comment by NancyLin** [comment]
> I generated RDT (RestrictedDataToken) to get details like buyer info and address of orders. But after getting RDT token i still getting only that much data which i was getting with normal access token. Do i require any other permissions in my developer profile ? Can anyone help me on this ?

I also encountered the same situation, and my application still has” Direct-to-Consumer Shipping (Restricted)“,  "Tax Invoicing (Restricted)", "Tax Remittance (Restricted)" roles. But after getting the RDT token I still getting only that much data which I was getting with the normal access token.

**Comment by milovvsam** [comment]
FF. I have the same issue. DTC, TI, TX are enabled but no luck on getting the address info. Do we have an update on this?

**Comment by Jay670** [comment]
From What I know after getting the PII permission the refresh token needs to be regenerated in order to get required data.

**Comment by kevinvenclovas** [comment]
someone fixed this issue?
