### ISSUE TITLE
SKU and ASIN list for ALL PRODUCTS

### ISSUE THREAD

**Issue by Sellcon** [amzn/selling-partner-api-docs#815]
Hello,

could you tell me which endpoint give me a list of all product in inventory (active and inactive) with SKU and ASIN in one report. I used _GET_MERCHANT_LISTINGS_ALL_DATA_ but sometimes I have no data. 

Thanks

**Comment by Sellcon** [comment]
Please answer here.
Thanks

**Comment by Sellcon** [comment]
Please answer here.
Thanks

**Comment by shirushi-dev** [comment]
Please answer here.
Thanks

**Comment by hongtao0770** [comment]
Hi @Sellcon !

Have you solved this issues?
