### ISSUE TITLE
[BUG] getOrderMetrics data discrepancy with Seller Central Console

### ISSUE THREAD

**Issue by ferrants** [amzn/selling-partner-api-docs#820]
**Describe the bug**
We have heard from our customers that our metrics (Ordered Units, for example), as gathered from the /sales/v1/orderMetrics endpoint, not matching what is seen in the Seller Central console. Do we know of any reasons that these numbers would not match? I suspect the timezone is one reason. This is making it difficult for our customers to use our platform for seeing their Seller Central data.

What timezone does Seller Central use for each marketplace? We request based on UTC timezone currently, but if we know the timezone each Seller Central console uses, we can request with that `granularityTimeZone`

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md

**Description of what the documentation currently says**
> An IANA-compatible time zone for determining the day boundary. Required when specifying a granularity value greater than Hour. The granularityTimeZone value must align with the offset of the specified interval value. For example, if the interval value uses Z notation, then granularityTimeZone must be UTC. If the interval value uses an offset, then granularityTimeZone must be an IANA-compatible time zone that matches the offset. Example: US/Pacific to compute day boundaries, accounting for daylight time savings, for US/Pacific zone.

**Description of what the documentation should say**
It should include a link to the correct timezones for each marketplace

**Comment by xbaha** [comment]
if you are using the API i think it's the local timezone

**Comment by ferrants** [comment]
I'm wondering what timezone each seller central marketplace reports in, so I can ensure that the numbers I pull match Seller Central, because that's what my customers want to see.

This says that it's always PST:
https://sellercentral.amazon.com/forums/t/change-time-zone-in-seller-central/175200

This says that it's PST for North America or MET for Europe:
https://support.powermyanalytics.com/portal/en/kb/articles/why-do-the-sales-numbers-not-align-with-my-amazon-seller-central-reports

What about Japan? Brazil? It would be helpful to have this documented somewhere.

**Comment by ianrussel** [comment]
@ferrants , I got accurate results. For example My customer is from Berlin, what I did is to translate the interval according to customers timezone(example berlin). In frontend, I just leave the default timezone to localtimezone.

Im using php in backend, this is the snippet

                $dateF = Carbon::parse("$from Europe/Berlin")->tz('UTC')->format('Y-m-d\TH:i:sP');
                $dateT = Carbon::parse("$to Europe/Berlin")->endOfDay()->tz('UTC')->format('Y-m-d\TH:i:sP');
                $interval = json_encode($dateF) .'--'.json_encode($dateT);
                $marketplace_ids = $request->input("marketplace_ids") ?? ['A1PA6795UKMFR9']; // string[] | A list of marketplace identifiers. Example: ATVPDKIKX0DER indicates the US marketplace.
                $interval = str_replace('"',"",$interval);

**Comment by ferrants** [comment]
Thanks for the note, @ianrussel!

In North America, they need to be PST to match, not where the customer is. If the customer is an East coast customer, using EST won't work. Mexico and Canada also seem to report in PST. In Europe, they need to be MET, which is `Europe/Paris` as well as `Europe/Berlin`, so your timezone matches. Turkey is the next timezone over and I think they also report in MET, but am not certain. I'm wondering about Brazil, Japan, India and Australia, too. I am asking for the documentation (this is a documentation repo) to be updated to reflect this information as it is important for someone integrating to use the right timezone if they want the data to match, instead of just guessing which timezone to use.

**Comment by robcowie** [comment]
@ferrants Did you discover the marketplace time zones? I'm also looking for a definitive answer for the following Amazon marketplaces:

* China (China region)
* Singapore (Far East region)
* Sweden, Poland, Egypt, Turkey, Saudi Arabia (Europe region)

**Comment by ezpinsky** [comment]
We are still getting this issue where the data from the GetOrderMetrics API results does not line up with the Business reports Sales Data in Seller Central. @[jenilew](https://github.com/jenilew), @[jevoniuk](https://github.com/jevoniuk), please can you shed some light on why there is a difference? the Order Metrics total sales is consistently greater than what is displayed in seller central for the same date range. What is order metrics including that seller central business reports sales data is not including?

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
