### ISSUE TITLE
Hello, I applied for a new application submission, but it has not helped me review it for almost a year. Please help me review the application. Thank you! My CASEID: 7594068591

### ISSUE THREAD

**Issue by userbabu** [amzn/selling-partner-api-docs#823]
Hello, I applied for a new application submission, but it has not helped me review it for almost a year. Please help me review the application. Thank you!
My CASEID: 7594068591

**Comment by ShivikaK** [comment]
Hello @userbabu 

Thank you for raising this issue.

I will be reviewing the case and look into resolving this for you.

Please expect an update early next week regarding your case status and I apologize for inconvenience caused.

Thanks,
Shivika Khare
Selling Partner API Developer Support
