### ISSUE TITLE
Bad Request when using NextToken on GetOrders

### ISSUE THREAD

**Issue by debra140** [amzn/selling-partner-api-docs#824]
I recieve an 400 Bad Request response, when calling the orders/v0/orders/ endpoint with the GetOrders call. 

The request is submitted as described in the documentation. 

The first call to get the orders works and I get data back including the next token. An example of this call is: 

https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/?MarketplaceIds=A1F83G8C2ARO7P&CreatedAfter=2019-06-03T07:13:45.7945870Z&OrderStatuses=&MaxResultsPerPage=2&NextToken=

When I make the next call where I include the token I get a Bad Request.  An example of this call is:

https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/?NextToken=C6EMjFRxEoWaJqJYLDm0ZIfVkJJPpovRJNRItJpjf8cmQ+P8hHNbMxEkoIA3YVNUxqXyQLkGMBs8VhF73Xgy+5FhsH2erTQ4Z8nuGvBXu6B9HAMTdZwD9GBQE++3Oc2oInTAy+XKVmRZBY+oaVuyc9M9cTZROoa87U7aAFWzv/tJASkEew64xgTywOECQPb8f2GLmUGyr9UGnxD0RJmrryegoU0IPZxXSzM2tfYNfppc2qq8rxfcNbrfUUpZcv0kMBO/reDY2s+Z+SGWG8+LMp2zJWQvxBVrVhOjkSXLZOm7EbcPNB+bBxZByPo528ORVHr6/v7aqUGIfQDsbq7j2pnycMd/XRCQUk4tfrZ0HWw3b3HxcoCwMeimGJfgVBeDeXbnL7H8NOrHsJH6srKElY+rqSs7y2ixrToAsYN83sHgkdZPXhcRcE7Vz+MOIF3hcrUoMKDJjYA=

I have tried including the other paremeters in the call with next token and also leaving them out as there was a suggetsion that the URI being too long might cause a problem. 

I have also tried URL encoding the URI so the = at the end of the request is escaped. This still returns bad request

https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/?NextToken=C6EMjFRxEoWaJqJYLDm0ZIfVkJJPpovRJNRItJpjf8cmQ+P8hHNbMxEkoIA3YVNUxqXyQLkGMBs8VhF73Xgy+5FhsH2erTQ4Z8nuGvBXu6B9HAMTdZwD9GBQE++3Oc2oInTAy+XKVmRZBY+oaVuyc9M9cTZROoa87U7aAFWzv/tJASkEew64xgTywOECQPb8f2GLmUGyr9UGnxD0RJmrryegoU0IPZxXSzM2tfYNfppc2qq8rxfcNbrfUUpZcv0kMBO/reDY2s+Z+SGWG8+LMp2zJWQvxBVrVhOjkSXLZOm7EbcPNB+bBxZByPo528ORVHr6/v7aqUGIfQDsbq7j2pnycMd/XRCQUk4tfrZ0HWw3b3HxcoCwMeimGJfgVBeDeXbnL7H8NOrHsJH6srKElY+rqSs7y2ixrToAsYN83sHgkdZPXhcRcE7Vz+MOIF3hcrUoMKDJjYA==

**Comment by ianrussel** [comment]
You could try to marketplaceId query params

**Comment by ianrussel** [comment]
So remove everything except nexttoken and marketplaceid

**Comment by debra140** [comment]
Thanks for the reply Ian. I have tried the query with the MarketPlaceID and the NextToken. I still get the response of Bad Request. The detail on this is Invalid Query String. I have found a few other very recent posts about the same issue which is making me wonder if it's a problem on Amazon's side.

**Comment by ianrussel** [comment]
Hi @debra140 here is my example working request 

                      [2021-06-03 22:32:44] local.INFO: https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A1PA6795UKMFR9&MaxResultsPerPage=20&NextToken=6zB1c5BtraqaJqJYLDm0ZAmQazDrhw3CqLUJ468q3yBUojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy%2B5FhsH2erTQ4JRB7jWy%2FkD%2F2j7w2mEMp7fmDOU6fp6slInTAy%2BXKVmRZBY%2BoaVuyc8QON%2BK1yc%2FYHVR3r2Qyvvn9CHxngL2%2Fec3ZNvlcyxWjf2GLmUGyr9UGnxD0RJmrryegoU0IPZxXnriR3HVxB19K5D9uzvXtxajRkllfRVx4MBO%2FreDY2s9TeN2C3mXyRN4oJMGxzApKJt%2BBcHoDccW7EbcPNB%2BbB5CkgT8s%2BoRK11Ds5w1QtjVjIEqCKZbZkTOPK%2BZzoe2UxRL%2Bg8dAd%2BzlBRhejz0q6KqrA7K65cyJ27jd%2BeiqRxqnziS%2B3YzL5fUNxSHVfs00EsqGJJJsu8%2BPnp7zXB4uNDkpbblTM7beMDNT2aDUbPZjTnVM%2FHGQ%3D%3D

**Comment by luckylion000** [comment]
I am getting same error 400 when using NextToken.
Without NextToken, it's working fine.
@debra140 Did you manage to solve this problem?

**Comment by vasRK** [comment]
@luckylion000 

after getting first response, you should request with NextToken query param included

attach query param to first request url 

`url+ "&NextToken=" + encodeURIComponent(nextToken)`

NextToken value should be encode to work.  ` "....bTpudWxsfQ=="` equal sign in next token is giving issue without encodeURIComponent. I use NodeJs
