### ISSUE TITLE
Merging Items with different SHIPMENID going to the same DC to ONE SHIPMENID 

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#826]
Documentation needs to be updated with differences of old MWS and SP-api
For Inbound FBA - 
In older MWS - there was a way to merge items that were going to the same destination on to 1 shipmentid via updateinboundshipment.  You could first createinboundshipment for a shipmentid then add items from other PLANs going to same DC but diff shipmentid.  This does not seem possible with new SP_API ? 

Can you please documents these differences?  Old MWS - can merge shipmentid's together going to same DC but you cannot with SP-API.

Can you send requests with more than 200 lines?

We were trying to create better LTL/LT loads because transportation call is by **SHIPMENTID.**

**Comment by DavidRHid** [comment]
Did you figure this out?
