### ISSUE TITLE
Forbidden, ALMOST for all queries

### ISSUE THREAD

**Issue by B1essedSou1** [amzn/selling-partner-api-docs#827]
Hello guys. Please could you explain why some functions works correct,  and when i try to request most part of functions i catch Forbidden error? I did all strictly by reference instructions. 

If its important:
- Im using refresh token from self authorization. 
- App in draft status

**When i catch forbidden...for example:**
- _/catalog/v0/items_
- _/products/pricing/v0/competitivePrice_
- _/fba/inventory/v1/summaries_
- _and etc._

**When success response with payload:**
- _/orders/v0/orders/_
- _/reports/2020-09-04/reports/_

**Comment by shashank201091** [comment]
Try to create you app using user only and in your IAM user try this policy.
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*/*/*/*"
        }
    ]
}
