### ISSUE TITLE
AccessDeniedException

### ISSUE THREAD

**Issue by shashank201091** [amzn/selling-partner-api-docs#828]
I have been trying to connect to SP API for last 2 days, but after following the SP API documentation, I have been getting Access Denied Exception.
I followed other issues here regarding the same, but none of them seem to solve the issue.
My application is currently is draft status, I am able to retrieve the access token, not able to call any API.
As these rest end points, I am using POSTMAN to hit the URL's by using AWS Signature into the headers.
But still receiving the below error.
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
I tried associating role arn to an app as per documentation, which did not work.
Then going through issues, I tried associating role arn but that also did not work,
Even sandbox URL's having the same issue.
I am not sure what I am doing wrong.
Any help would be highly appreciated.
I have already raised a support case with Amazon wit case ID : **ID8420316981**

I have been seeing people suggesting assume role to include before calling the API.
Is there an rest end point to achieve that?

**Comment by B1essedSou1** [comment]
Hello sir. I was in stuck about 1.5 months..please try to call API from my issue. If orderv0 call will works, then your aws and app was setup correct. 
[My issue](https://github.com/amzn/selling-partner-api-docs/issues/827) 

If you will find solution, please keep me updated

**Comment by kprajith** [comment]
I am still facing similar issue but i was able to call assume role successfully. So providing the assume role details below.
**Postman details**: 
URL : https://sts.amazonaws.com?Version=2011-06-15&Action=AssumeRole&RoleSessionName=postmanSpApi&RoleArn={{RoleArn}} // replace RoleArn with your role example : arn:aws:iam::XXXXXXXXXXX:role/SellingPartnersDevRole

Authorization : select Aws signature and provide accesskey and secret. In place of service name provide sts.

Above setting should resolve your assume role issue.
**In java use below code**

       BasicAWSCredentials credentials = new BasicAWSCredentials(youraccessKey, yourSecretKey);

        AWSSecurityTokenServiceClient client = new AWSSecurityTokenServiceClient(credentials);

        AssumeRoleRequest request = new AssumeRoleRequest();
        request.setDurationSeconds(3600);
        request.setRoleArn("arn:aws:iam::XXXXXXXXXXX:role/SellingPartnersDevRole");
        request.setRoleSessionName("Test1234_43");
        AssumeRoleResult assumeRoleResponse = client.assumeRole(request);

**Comment by shashank201091** [comment]
> I am still facing similar issue but i was able to call assume role successfully. So providing the assume role details below.
> **Postman details**:
> URL : [https://sts.amazonaws.com?Version=2011-06-15&Action=AssumeRole&RoleSessionName=postmanSpApi&RoleArn={{RoleArn}}](https://sts.amazonaws.com?Version=2011-06-15&Action=AssumeRole&RoleSessionName=postmanSpApi&RoleArn=%7B%7BRoleArn%7D%7D) // replace RoleArn with your role example : arn:aws:iam::XXXXXXXXXXX:role/SellingPartnersDevRole
> 
> Authorization : select Aws signature and provide accesskey and secret. In place of service name provide "sts".
> 
> Above setting should resolve your assume role issue.
> **In java use below code**
> 
> ```
>    BasicAWSCredentials credentials = new BasicAWSCredentials(youraccessKey, yourSecretKey);
> 
>     AWSSecurityTokenServiceClient client = new AWSSecurityTokenServiceClient(credentials);
> 
>     AssumeRoleRequest request = new AssumeRoleRequest();
>     request.setDurationSeconds(3600);
>     request.setRoleArn("arn:aws:iam::XXXXXXXXXXX:role/SellingPartnersDevRole");
>     request.setRoleSessionName("Test1234_43");
>     AssumeRoleResult assumeRoleResponse = client.assumeRole(request);
> ```

Hi Kprajith,

Thanks to you, I am able to assume sts role, but still facing the same issue.

**Comment by B1essedSou1** [comment]
yeah.same

**Comment by kprajith** [comment]
@B1essedSou1 I am taking baby steps here. I was able to reach to step 3 of the feed documentation

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md#step-3-create-a-feed

I was getting AccessDeniedException for a while now. When I used old SP API url for same feed api it started working and i got response as expected. The actual URL I am suppose to use is "/feeds/2021-06-30/documents" but old url version "/feeds/2020-09-04/documents" is working for me. 

Try using old version of the URL you are trying to access.

Now I am getting below exception
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]
}

If someone knows whats I am doing wrong. Please help

**Comment by kprajith** [comment]
I am still facing issue with Feed API but Its for anyone who is looking for help working with SP APIs. I was able to figure marketplaceParticipations API.

below are the details of Postman.

GET : https://sandbox.sellingpartnerapi-eu.amazon.com/sellers/v1/marketplaceParticipations
Authorization screen : select AWS signature
provide accesskey and secret. 
enter AWS region, service name as "execute-api" and enter session token from assume role api response(Which is provided in previous comment).
in the header section, enter the key as "x-amz-access-token" and the value of access token from below postman call. 

Get Access token with below API

POST /auth/o2/token HTTP/1.1
Host: api.amazon.com
Content-Type: application/x-www-form-urlencoded


grant_type=refresh_token&refresh_token={{Refreshtoken from seller api app}}&client_id={{clientid from seller app}}&client_secret={{client secret from seller app}}

**Comment by kprajith** [comment]
All issues resolved. Thank you guys.

**Comment by B1essedSou1** [comment]
> All issues resolved. Thank you guys.

Awesome!Sir, could you share for us your solving? Because its hell 🥺

**Comment by kprajith** [comment]
@B1essedSou1 I have suffered due to poor SP API documentation. I am attaching postman collection I have made for SP API. It would be helpful for you. Import the postman environment file and replace values with your credentials and access key. Rest should work based on script. Please let me know if you need more help.

You might be facing issue because you are compiling the amazon code and completely depending on the compiled code. Try to write custom code based on attached postman collection. I am also attaching one of the Order apis for you which seems to be working and I am getting below response.

{
    "payload": {
        "CreatedBefore": "2021-06-09T20:09:10Z",
        "Orders": []
    }
}


[spapi.zip](https://github.com/amzn/selling-partner-api-docs/files/6626619/spapi.zip)

Good luck.

**Comment by B1essedSou1** [comment]
> @B1essedSou1 I have suffered due to poor SP API documentation. I am attaching postman collection I have made for SP API. It would be helpful for you. Import the postman environment file and replace values with your credentials and access key. Rest should work based on script. Please let me know if you need more help.
> 
> You might be facing issue because you are compiling the amazon code and completely depending on the compiled code. Try to write custom code based on attached postman collection. I am also attaching one of the Order apis for you which seems to be working and I am getting below response.
> 
> {
> "payload": {
> "CreatedBefore": "2021-06-09T20:09:10Z",
> "Orders": []
> }
> }
> 
> [spapi.zip](https://github.com/amzn/selling-partner-api-docs/files/6626619/spapi.zip)
> 
> Good luck.

Big human thanks! When i will able i check! Hope it will works for me. Have a good day)

**Comment by vossgrose** [comment]
> @B1essedSou1 I have suffered due to poor SP API documentation. I am attaching postman collection I have made for SP API. It would be helpful for you. Import the postman environment file and replace values with your credentials and access key. Rest should work based on script. Please let me know if you need more help.
> 
> You might be facing issue because you are compiling the amazon code and completely depending on the compiled code. Try to write custom code based on attached postman collection. I am also attaching one of the Order apis for you which seems to be working and I am getting below response.
> 
> { "payload": { "CreatedBefore": "2021-06-09T20:09:10Z", "Orders": [] } }
> 
> [spapi.zip](https://github.com/amzn/selling-partner-api-docs/files/6626619/spapi.zip)
> 
> Good luck.

Kprajith
When using your postman I'm still getting same issue: Access to requested resource is denied
Is there something that could be setup wrong in my account settings that I should double chekc ?
FYI:  I Noticed in your ApiCall you had the region hardcoded for the Authorization/Advanced instead of using the {{awsRegion}} var.

thanks for any help.
voss.

**Comment by vossgrose** [comment]
@B1essedSou1 
I'm still struggling with Sellers Api.
Do you do any side work/consulting ?
Need some help getting through issue and then have quite a bit of implementation work to start on.
Probably 4-6 weeks worth or work, but no real times lines.
thanks,
voss
voss_grose@hotmail.com
