### ISSUE TITLE
Forbidden - Only when creating a POST_FLAT_FILE_LISTINGS_DATA feed.

### ISSUE THREAD

**Issue by ifulfilment** [amzn/selling-partner-api-docs#83]
Hi,

Could you please advise regarding an issue I am having with submitting a POST_FLAT_FILE_LISTINGS_DATA feed?

The error I get back from the API when creating the listing feed via "/feeds/2020-09-04/feeds" is as follows:

Response Body: "Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature"
Response Code: 403

I have been able to connect to the API and perform many different actions including submitting price feeds ( POST_PRODUCT_PRICING_DATA ) and requesting listing report ( GET_MERCHANT_LISTINGS_ALL_DATA ) without issue.

Do I need to assign any additional permissions to be able to create listings?

Case Log: 7551028571

**Comment by 2445809596** [comment]
I have the same problem. Have you solved the problem?

**Comment by ShivikaK** [comment]
Hi @ifulfilment, 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance.

Thanks,
Shivika Khare
Selling Partner API Developer Support
