### ISSUE TITLE
More information on FBA Inbound documentation

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#833]
We are a large logistics company.  We are integrating the Fulfillment Inbound API's into our system.  This means we will be calling the Plan api, create order, update order and transport calls within the application for SEVERAL sellers.  The calls are seamless to the warehouse workers.

Now, where we are running into problems.....we are not finding out about certain restrictions until we have had our application published and are working with the API's with a real seller.  We designed the system based off of what we had in documentation from the SP-API (which is very little on using the api itself) and the MWS (which we found out we cannot use) 

One of our biggest issues is how do we handle a shipmentid when after picking - we have a 5%/6peice difference from the plan?  We will be building FTL/LTL and Parcels.  Remember, these warehouses will be housing many customers.  These LTL shipments are large.  We plan on verifying a case at a time (because of item prep) and labeling as we verify.  The correct shipmentid HAS to be on the label.  What do we do if we find that we have to adjust an item or items by 5%?  We have to cancel the order and create a new plan?  Which causes us to have to print new labels?  And the "NEW" plan can decide to send some items to a different DC?  This is disastrous for us.

Our second issue is the ability to combine shipmentid's that are from the same seller going to the same Amazon DC.  This is going to raise the cost of shipping to the seller if we cannot combine on the same ltl/ftl shipment.  

**Describe the improvement**
Please be clear that you cannot update an order ANYMORE with other plans going to the same Amazon DC.  MWS allowed this - but it needs to be explicit that this is not allowed anymore. This hurts us on shipping and combining shipmentid to create a better ltl/ftl shipment.

Can you do a call to the api for more than 200 lines?  This needs to be put in documentation because in MWS you could not (but you could combine shipmentid's).  Can you do this in SP-API?

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#inboundshipmentheader

**Description of what the documentation currently says**
Not enough information on how to resolve issues.  Especially for very large operations.

**Description of what the documentation should say**
I would like a better way to resolve a short pick other than having to create a new plan.

**Comment by bxb100** [comment]
diff seller parcels combine FTL/LTL? is that work?

**Comment by 8mpg** [comment]
We really would like the ability to combine shipments again. This is a huge help, money saver. It even will save Amazon money!
