### ISSUE TITLE
What are the valid values for Amazon Product Type?

### ISSUE THREAD

**Issue by LiuMicah** [amzn/selling-partner-api-docs#834]
Selling Partner API for Product Type Definitions

Api: GET /definitions/2020-09-01/productTypes

Param "keywords" Need To Use Amazon ProductType, But The Param "Sports" Response Is Null;

Please Talk Me What Product Type Valid?

**Comment by iamsr** [comment]
it's mentioned in the doc if you don't provide any keyword it will return all available lists of product types. Though the list is very small right now so it has no useful usecase yet.

**Comment by chapmanjw** [comment]
You can find more details on the Definitions API in the use case guide: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md

We are in the progress of migrating Amazon product type rules and data requirements, making them available in the Definitions API once available. Providing `null` (or omitting) for the `keywords` will return the full list for a given seller and marketplace.
