### ISSUE TITLE
Feature request: Exclude PII data from reports

### ISSUE THREAD

**Issue by adrianmiu** [amzn/selling-partner-api-docs#835]
Hello,

I have developed an app that requires the ability to generate VAT reports but the app DOES NOT need PII. 
Instead of returning FORBIDDEN when requesting the report why not exclude the PII from the response if the user/app/developer account does not have the rights to said data. Or why not add a parameter to exclude the PII data from the response/report and return the 403 response ONLY if the request doesn't match the limitations imposed by the account (ie: the parameter is missing for the requests made by accounts/apps that do not have access to PII)?

These limitations do not occur for the old MWS API and the claim is that the new SP-API is supposed to make everything better.

The internet is filled with questions from people wondering why they suddenly can't request certain reports without the issue being addressed by Amazon.

**Comment by marconline** [comment]
This would be a dream, even because some kind of reports are considered restricted and, then, you will need a RDT (so managng it is requested) in order to get everything working. Crazy as hell.

**Comment by adrianmiu** [comment]
Hello again. Is this idea being considered?

**Comment by adrianmiu** [comment]
Still interested in this feature. I mean people who got lucky to have registered with Amazon MWS can download VAT reports just fine but not for the new SP API.
