### ISSUE TITLE
All calls returning "Unauthorized" - "Access to requested resource is denied."

### ISSUE THREAD

**Issue by nightcoding2021** [amzn/selling-partner-api-docs#837]
Got past signing the request, but all calls to endpoints are then returning the below Unauthorized error.

It appears the API isn't granting access to the locale/selling account pair?  But how on earth to debug?  The locale has an active selling account with SP-API app created.

There is zero information in the response below, so now what?  Is everyone supposed to spend the rest of their days just guessing?

**{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}**

**Comment by kerbalwzy** [comment]
The same problam hanpped to me.

**Comment by kerbalwzy** [comment]
I have solved this problem. There is a problem with the IAM permission setting on AWS

**Comment by nightcoding2021** [comment]
I have followed configuration exactly as specified in the Developer's Guide.  Is that documentation incorrect?

I haven't done anything with STS endpoints.  I did follow the instructions in Developer's Guide only.  Are calls to STS endpoints also always required, not matter what is configured?

The error messages are a joke and provide very limited information what has triggered the problem.  I don't see that as a security benefit, because bad actors will know exactly why things are failing.

Some clearer guidance would be appreciated.  Further, I will comment the quality of the Developer's Guide is extremely poor both in writing and layout.  That said, it's likely easier for those already with a full understanding of the AWS architecture.

**Comment by byzosoftware** [comment]
Having the same issues. 

I exactly followed the instructions in the Developer's Guide when creating and configuring the IAM User.

What permission's need to be changed? Are the infos in the Developer's Guide wrong or incomplete?

@kerbalwzy How did you solve this exactly?

Anton

**Comment by nightcoding2021** [comment]
I opened a support ticket, here's what I received back just now.  Perhaps it'll fix the problem, but even if so, that really needs to be clearly stated in documentation.  The forum demonstrates the amount of everyone's development time being wasted.  Although again, I accept that those familiar with AWS will have found this process easier.

_Reviewing the call details I found that the you application was registered with the IAM role, however your request was submitted with IAM user (arn:aws:iam::[REDACTED]:user/SellingPartnerApiUser).

So please try to make a request and ensure you are using AWS credentials associated with your IAM role._

**Comment by B1essedSou1** [comment]
same error about 1.5 months spent. I was try so much ways to fix that but its not understandable still...if someone defeat that, please keep us updated!

**Comment by kerbalwzy** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/168#issuecomment-738612584

**Comment by jason1004** [comment]
I also encountered the same problem.

1. After both seller accounts are authorized to our APP, one can access the SP-API normally, and the other gets the response content:

HTTP/1.1 403 Forbidden
Date: Tue, 08 Jun 2021 01:08:08 GMT
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
x-amzn-RequestId: 551f1df0-9436-4cd2-815e-24b03903e74a
x-amzn-ErrorType: AccessDeniedException
x-amz-apigw-id: AlNm0EYxjoEFrgA=

{
   "errors": [
     {
       "message": "Access to requested resource is denied.",
      "code": "Unauthorized",
      "details": ""
     }
   ]
}

This can prove that our APP settings are correct


2. The SP-API prompt is too vague, making it difficult for developers to know where the problem is? It is suggested that the error message can be clear above!

**Comment by kerbalwzy** [comment]
If only a few interfaces show that they are not authorized, there are the following possibilities:

- The interface can only be used in a specified authorized region.
![image](https://user-images.githubusercontent.com/32036069/121117660-111abf00-c84b-11eb-9804-fc63f1a48f88.png)

- You need to access the API with PII permission, but the developer account you registered does not have.
- The authorized seller's shop has been closed

**Comment by aidensgithub** [comment]
> I also encountered the same problem.
> 
> 1. After both seller accounts are authorized to our APP, one can access the SP-API normally, and the other gets the response content:
> 
> HTTP/1.1 403 Forbidden
> Date: Tue, 08 Jun 2021 01:08:08 GMT
> Content-Type: application/json
> Content-Length: 141
> Connection: keep-alive
> x-amzn-RequestId: 551f1df0-9436-4cd2-815e-24b03903e74a
> x-amzn-ErrorType: AccessDeniedException
> x-amz-apigw-id: AlNm0EYxjoEFrgA=
> 
> {
> "errors": [
> {
> "message": "Access to requested resource is denied.",
> "code": "Unauthorized",
> "details": ""
> }
> ]
> }
> 
> This can prove that our APP settings are correct
> 
> 1. The SP-API prompt is too vague, making it difficult for developers to know where the problem is? It is suggested that the error message can be clear above!
> 
> I have opened a case in UK, the id is 7063323322

@jason1004 Have you resolved the issue? I've tried to add the STS Policy to my USER as suggested [here](https://github.com/amzn/selling-partner-api-docs/issues/168)
Still getting the same error: Forbidden, Unauthorized

**Comment by kerbalwzy** [comment]
@aidensgithub
In the case of using the first solution, you need to ensure that the app created with the IAM user's ARN instead of the IAM role's. 
You can consider using the IAM user's ARN to re create an new app and use it.

**Comment by JayChandler** [comment]
When your APP was created with a user ARN then you need to bind the Policy **AmazonAPIGatewayInvokeFullAccess** on the user and not on the ROLE! That worked for me

![image](https://user-images.githubusercontent.com/6359575/121552982-2e998580-ca11-11eb-8b7e-2472e7738478.png)

**Comment by nightcoding2021** [comment]
Thanks @JayChandler that appears to overcome the authentication/access problem.  Here is a step-by-step guide for everyone, I'm sure many will find this useful when setting up and integration. 

- In AWS IAM service dashboard, Go to your user, where that user ARN matches the one you created the App with in Seller Central
- Click the "Add permissions" button
- Search for the IAM policy name, which if named as per Developer's Guide is "SellingPartnerAPI".  See first screenshot, you are directly attaching a policy.
- Add to the user directly, your dashboard will now look like the second screenshot.

### Screenshot 1.
![image](https://user-images.githubusercontent.com/85417724/121566207-2fccb180-ca15-11eb-89df-8ecb61df3444.png)

### Screenshot 2.
![image](https://user-images.githubusercontent.com/85417724/121566089-10358900-ca15-11eb-9b52-dd52cb06ad51.png)

Now Amazon, please improve your Developer's Guide documentation!
Then... my initial API response, which I assume indicates success because I have a payload response (?).

{"payload":[]}

**Comment by JayChandler** [comment]
The simple reason this works i guess is due the fact when you create the app with a user ARN you are acting on the API as a USER and not as a ROLE. So when there is no permission on the user itself then it won't work. And i also guess the ROLE in that case is not taken into account, so putting the permission on the role is rather useless.

**Comment by dobariyarakesh** [comment]
HI @nightcoding2021 if you still facing the issue let me know I have created the document that are the mentions step by step generate the detail with screen short.

**Comment by haiderasad** [comment]
hi @JayChandler so to sum it up after following the amazons guide https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#about-this-guide  , then we just create a new app on the users ARN in seller central, then in AWS IAM user we go to permissions the attach SellingPartnerAPI policy we created and enable  AmazonAPIGatewayInvokeFullAccess  or are they the same policy?

**Comment by haiderasad** [comment]
hi @JayChandler @nightcoding2021  can you please explain solution in detail mate? i think I am missing something ,first of all I am trying sp API using python
createReportResponse = Reports(credentials=credentials).create_report(reportType=ReportType.GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING)
error is same that

"message": "Access to requested resource is denied.", "code": "Unauthorized", "details": ""

just to sum it up
1)follow amazon guide(including making IAM role)
2)create new app and add USER ARN not role ARN
3)Go to IAM user and
a)add permissions--->existing policy------>add policy made in amazon to user
b)add permissions--->existing policy------>add AmazonAPIGatewayInvokeFullAccess

am I missing something?please tell

**Comment by JayChandler** [comment]
@haiderasad Did you recreate the **refreshToken** in  the Application settings in the ui ? 

![Authorize App](https://user-images.githubusercontent.com/6359575/123794718-74948b80-d8e3-11eb-8db7-a11acbefda33.png)

**Comment by haiderasad** [comment]
> @haiderasad Did you recreate the **refreshToken** in the Application settings in the ui ?
> 
> ![Authorize App](https://user-images.githubusercontent.com/6359575/123794718-74948b80-d8e3-11eb-8db7-a11acbefda33.png)

Yes when creating new app(after configuring the iam user) i got the new token,

 do we use the same iam user or create a separate iam user apart from amazon guided?

**Comment by JayChandler** [comment]
@haiderasad I have created one IAM user and directly assigned *AmazonAPIGatewayInvokeFullAccess*. Then i have created the app using this user ARN. In the code ( java ) i also using user ARN not role ARN

**Comment by L1nYong** [comment]
> I also encountered the same problem.
> 
> 1. After both seller accounts are authorized to our APP, one can access the SP-API normally, and the other gets the response content:
> 
> HTTP/1.1 403 Forbidden
> Date: Tue, 08 Jun 2021 01:08:08 GMT
> Content-Type: application/json
> Content-Length: 141
> Connection: keep-alive
> x-amzn-RequestId: 551f1df0-9436-4cd2-815e-24b03903e74a
> x-amzn-ErrorType: AccessDeniedException
> x-amz-apigw-id: AlNm0EYxjoEFrgA=
> 
> {
> "errors": [
> {
> "message": "Access to requested resource is denied.",
> "code": "Unauthorized",
> "details": ""
> }
> ]
> }
> 
> This can prove that our APP settings are correct
> 
> 1. The SP-API prompt is too vague, making it difficult for developers to know where the problem is? It is suggested that the error message can be clear above!
> 
> I have opened a case in UK, the id is 7063323322

me to!Some accounts are OK, some are Unauthorized,I don't know how to resolve it.

**Comment by rugved1991** [comment]
Hi,

Check out the new Selling Partner API on AWS QuickStart for a quick setup of SP APIs using Python Lambda. The IAM setup is automated so no need to worry about the setup. Just follow the instructions on the deployment guide of the QuickStart and you will be up and running in no time.

https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

Feel free to open issues or provide feedback on the issues page of the QuickStart.

Thanks,
Rugved
Solutions Architect, SP API.

**Comment by SohailChohan143** [comment]
I Solved This issue by replacing my Grantless Token to LWA Token and it worked for me.
