### ISSUE TITLE
How to fetch all products offered by the seller?

### ISSUE THREAD

**Issue by dsokolowski** [amzn/selling-partner-api-docs#84]
My goal is to fetch all products and import them in our application. I found catalogs api endpoint so first question is if this is proper endpoint for me? Second question is what params to use to fetch all available items? I reviewed documentation and looks like I need to specify either idType param (SKU, ASIN...) or query. I think query parameter is what I need so now what to put there to fetch all available items?

**Comment by vikingcodes** [comment]
You want products offer by requesting seller or you want seller offers for specific product ?

Have a look into this API - 

https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md

getPricing - Returns pricing information for a seller's offer listings based on seller SKU or ASIN.

getCompetitivePricing - Returns competitive pricing information for a seller's offer listings based on seller SKU or ASIN.

I think these both API can provide you necessary information.

**Comment by dsokolowski** [comment]
I want to fetch list of all products that the seller offers in his webstore so I could import them in our application where user would manage their inventorie, prices etc.

**Comment by charliecode** [comment]
@dsokolowski A good place to get inventories is from the reports api. It get's pretty granular so I can't suggest a specific report as it will depend on what you want. But you can narrow it down by looking through the reports in the [Inventory Reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#inventory-reports) and the [Fulfillment by Amazon (FBA) reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#fulfillment-by-amazon-fba-reports) you'll want to scroll down a little until you see **FBA Inventory Reports**. For FBA inventory a couple good reports to start with are the "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA" and "GET_FBA_MYI_ALL_INVENTORY_DATA".

**Comment by dsokolowski** [comment]
Thank you, this is what I needed.
