### ISSUE TITLE
How can I use the interface to change the order status to the delivery status and upload the express number.

### ISSUE THREAD

**Issue by qq1356661768** [amzn/selling-partner-api-docs#840]
How can I use the interface to change the order status to the delivery status and upload the express number.

**Comment by stefnats** [comment]
I think you would need to use the feeds API to upload a feed:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md#order-feeds

I cannot tell you which exact feed. Maybe somebody else can help with this or you can find out from here.

**Comment by qq1356661768** [comment]
> I think you would need to use the feeds API to upload a feed:
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md#order-feeds
> 
> I cannot tell you which exact feed. Maybe somebody else can help with this or you can find out from here.

I looked at FeedType. The type is “POST_ORDER_FULFILLMENT_DATA”  may meet my requirements, but I don't know  “POST_ORDER_FULFILLMENT_DATA” this is what should be passed.

**Comment by qq1356661768** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md#createshipment
I  want to confirm whether the "createshipment" can realize the seller's delivery and modify the order to the delivery status.

**Comment by qq1356661768** [comment]
Why can't I generate XML from "OrderFulfillment.xsd" after downloading it. It has been reported that the file "amzn-base.xsd" is missing.

**Comment by bxb100** [comment]
> Why can't I generate XML from "OrderFulfillment.xsd" after downloading it. It has been reported that the file "amzn-base.xsd" is missing.

the file can download with this link
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd
