### ISSUE TITLE
[BUG] Documentation Invalid date-time field(s) [lastUpdatedAfter, createdAfter]

### ISSUE THREAD

**Issue by yswenli** [amzn/selling-partner-api-docs#841]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
/orders/v0/orders
CreatedAfter:2021-05-29T00%3a00%3a00Z

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "This is an invalid input",
      "details": "Invalid date-time field(s) [lastUpdatedAfter, createdAfter]."
    }
  ]
}

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md

**Description of what the documentation currently says**
A date used for selecting orders created after (or at) a specified time. Only orders placed after the specified time are returned. Either the CreatedAfter parameter or the LastUpdatedAfter parameter is required. Both cannot be empty. The date must be in ISO 8601 format.

**Description of what the documentation should say**
A clear and concise description of the guidance you expected to see in the documentation.

**Screenshots**

**Additional context**

**Comment by yswenli** [comment]
Type | Name | Description | Schema
-- | -- | -- | --
Query | CreatedAfteroptional | A date used for selecting orders created after (or at) a specified time. Only orders placed after the specified time are returned. Either the CreatedAfter parameter or the LastUpdatedAfter parameter is required. Both cannot be empty. The date must be in ISO 8601 format. | string

**Comment by yswenli** [comment]
Query usually requires URLEncode

**Comment by stefnats** [comment]
Could you please post the exact Request that you're sending?

**Comment by Jojosito** [comment]
Hello,

I am facing the same problem.

**Request**

GuzzleHttp\Psr7\Request Object 
( 
 [method:GuzzleHttp\Psr7\Request:private] => GET 
 [requestTarget:GuzzleHttp\Psr7\Request:private] => 
 [uri:GuzzleHttp\Psr7\Request:private] => GuzzleHttp\Psr7\Uri Object 
 ( 
 [scheme:GuzzleHttp\Psr7\Uri:private] => https 
 [userInfo:GuzzleHttp\Psr7\Uri:private] => 
 [host:GuzzleHttp\Psr7\Uri:private] => sellingpartnerapi-eu.amazon.com 
 [port:GuzzleHttp\Psr7\Uri:private] => 
 [path:GuzzleHttp\Psr7\Uri:private] => /orders/v0/orders 
 [query:GuzzleHttp\Psr7\Uri:private] => CreatedAfter=2021-05-26T14%3A38%3A52%2B0200&FulfillmentChannels=MFN&MarketplaceIds=A2VIGQ35RCS4UG%2CA1PA6795UKMFR9%2CA1RKKUPIHCS9HS%2CA13V1IB3VIYZZH%2CA1F83G8C2ARO7P%2CA21TJRUUN4KGV%2CAPJ6JRA9NG5V4%2CA1805IZSGTT6HS%2CA1C3SOZRARQ6R3%2CA2NODRKZP88ZB9%2CA33AVAJ2PDY3EV&Or
derStatuses=Unshipped%2CPartiallyShipped 
 [fragment:GuzzleHttp\Psr7\Uri:private] => 
 ) 
 
 [headers:GuzzleHttp\Psr7\Request:private] => Array 
 ( 
 [Accept] => Array 
 ( 
 [0] => application/json 
 ) 
 
 [Content-Type] => Array 
 ( 
 [0] => application/json 
 ) 
 
 [host] => Array 
 ( 
 [0] => sellingpartnerapi-eu.amazon.com 
 ) 
 
 [user-agent] => Array 
 ( 
 [0] => actindo-php-sp-api-client/2.1 
 ) 
 
 [x-amz-access-token] => Array 
 ( 
 [0] => ...
 ) 
 
 [x-amz-date] => Array 
 ( 
 [0] => 20210621T084730Z 
 ) 
 
 [x-amz-security-token] => Array 
 ( 
 [0] => ...
 ) 
 
 [Authorization] => Array 
 ( 
 [0] => AWS4-HMAC-SHA256 Credential=.../.../eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=...
 ) 
 
 ) 
 
 [headerNames:GuzzleHttp\Psr7\Request:private] => Array 
 ( 
 [accept] => Accept 
 [content-type] => Content-Type 
 [host] => host 
 [user-agent] => user-agent 
 [x-amz-access-token] => x-amz-access-token 
 [x-amz-date] => x-amz-date 
 [x-amz-security-token] => x-amz-security-token 
 [authorization] => Authorization 
 ) 
 
 [protocol:GuzzleHttp\Psr7\Request:private] => 1.1 
 [stream:GuzzleHttp\Psr7\Request:private] => 
) 


**Response**

{ 
 "errors": [ 
 { 
 "code": "InvalidInput", 
 "message": "This is an invalid input", 
 "details": "Invalid date-time field(s) [createdAfter]." 
 } 
 ] 
}

**Comment by ukben** [comment]
I had this also. 

This does **not** work: 
"2021-06-06T20:57:17+0000"  
which is the output of: `date(DATE_ISO8601, strtotime($p['time_from']))`

This does work: 
"2021-06-06T20:57:17+0000"
which is the output of: `date('Y-m-d\TH:i:s', strtotime($p['time_from']))`

Docs say ISO8601 so something isn't quite right.

**Comment by Jojosito** [comment]
I tried your suggestion:

CreatedAfter=2021-05-18T11%3A36%3A31%2B02%3A00&FulfillmentChannels=AFN&MarketplaceIds=A2VIGQ35RCS4UG%2CA1PA6795UKMFR9%2CA1RKKUPIHCS9HS%2CA13V1IB3VIYZZH%2CA1F83G8C2ARO7P%2CA21TJRUU
N4KGV%2CAPJ6JRA9NG5V4%2CA1805IZSGTT6HS%2CA1C3SOZRARQ6R3%2CA2NODRKZP88ZB9%2CA33AVAJ2PDY3EV&OrderStatuses=Unshipped%2CPartiallyShipped%2CShipped

However, I get the following response:
```
{                                                        
  "errors": [                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                 
      "code": "InvalidInput",                                                                                                                                                                                                         
      "message": "timestamp must follow ISO8601",                                                                                                                                                                                     
      "details": ""                                                                                                                                                                                                                   
    }                                                                                                                                                                                                                                 
  ]                                                                                                                                                                                                                                   
}
```

**Comment by ukben** [comment]
@Jojosito that's great. Yes it's UTC.
