### ISSUE TITLE
SP API 

### ISSUE THREAD

**Issue by bikramcv** [amzn/selling-partner-api-docs#842]
Hi, 

I am using SPI API  for order and buyer information.
To get these buyer information do we need the Amazon developer id for this or we get only by creating APP .
since I am not using MWS do we need for PII access for this .

In simple  what are the mandatory step for get order and buyer information via SP API

**Comment by stefnats** [comment]
I think for that you would have to contact developer support using the form on the developer website (for example for amazon us https://developer.amazonservices.com, just replace the tld accordingly)
