### ISSUE TITLE
Different throttling limits for different reports?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#843]
I can request `GET_SELLER_FEEDBACK_DATA` many times in a row and it is fine.

And seems like pretty much every time I request `GET_FLAT_FILE_PENDING_ORDERS_DATA` I get too many requests and `QuotaExceeded`.

Are there different throttling limits for different report types?

**Comment by valle-gp** [comment]
Hi moltar,

i have the same issue, have you resolve it?

**Comment by moltar** [comment]
@valle-gp Nope

**Comment by takeno-dev** [comment]
me toooooo!
