### ISSUE TITLE
What permission scopes are required for SC_VAT_TAX_REPORT?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#844]
I'm able to request many reports, but not `SC_VAT_TAX_REPORT`.

Getting `Unauthorized` error.

What scopes are required for this report?

**Comment by JayChandler** [comment]
Same here

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
