### ISSUE TITLE
Not receiving notifications for FULFILLMENT_ORDER_STATUS

### ISSUE THREAD

**Issue by ms-transalis** [amzn/selling-partner-api-docs#845]
I've created a subscription to FULFILLMENT_ORDER_STATUS using an SQS queue as the destination.
```
{
    "payload": {
        "subscriptionId": "d0d1ab46..............f",
        "destinationId": "ed306855.........",
        "payloadVersion": "1.0"
    }
}
```

However, I'm not receiving any notifications to the SQS queue. At first I was using a FIFO queue which I thought might be the problem, so I changed to a standard SQS queue but I'm still not getting any notifications.
I have received emails telling me that an order status has changed so I should be getting sent notifications?

**Comment by ms-transalis** [comment]
I've attached an IAM policy for the Amazon API too so that is not the issue.
```
{
      "Sid": "__sender_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
      },
      "Action": [
        "SQS:SendMessage",
        "SQS:GetQueueAttributes"
      ],
      "Resource": "arn:aws:sqs:eu-west-2:994133378593:seller-central-test-standard"
    }
```

**Comment by GenderAPI** [comment]
Hi did you solve the problem
if yes
can you share how?
can you share full Access Policy of the SQS?

**Comment by ms-transalis** [comment]
> Hi did you solve the problem
> if yes
> can you share how?
> can you share full Access Policy of the SQS?

Yes I solved this, I was originally using a FIFO SQS queue - but switched to using a standard SQS queue and it worked.

**Comment by GenderAPI** [comment]
@ms-transalis thank you very much i will try standart also

**Comment by GenderAPI** [comment]
Hi @ms-transalis 
yesterday i changed to Standart SQS.
and i give full access to Access Policy as below. But no result. i have always 15 Empty Receives :(

 `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1623913579556",
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}`

**Comment by ms-transalis** [comment]
> Hi @ms-transalis
> yesterday i changed to Standart SQS.
> and i give full access to Access Policy as below. But no result. i have always 15 Empty Receives :(
> 
> `{ "Version": "2012-10-17", "Statement": [ { "Sid": "Stmt1623913579556", "Effect": "Allow", "Action": "*", "Resource": "*" } ] }`

@GenderAPI You need to include the Amazon API principal:
```
"Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
}
```

Copy the policy I posted above but change the resource to your SQS queue ARN

**Comment by GenderAPI** [comment]
i did as bellow and waiting thanks for the help

`{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "__sender_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::..........:root"
      },
      "Action": [
        "SQS:SendMessage",
        "SQS:GetQueueAttributes"
      ],
      "Resource": "arn:aws:sqs:us-east-1:..........:SQS_Standart"
    }
  ]
}`

**Comment by GenderAPI** [comment]
@ms-transalis no solution :(
everthing works perfect in code side
i can create subscriptions

**Comment by GenderAPI** [comment]
woowww i set the principal with the id : 437568002678 and now it works.

i though that is was my root id 👍

**Comment by ms-transalis** [comment]
> woowww i set the principal with the id : 437568002678 and now it works.
> 
> i though that is was my root id 👍

@GenderAPI Cool, yes this is AMAZONS id - as you need to allow the Amazon API access to your SQS queue

**Comment by sunita1988** [comment]
HI i have created SQS with standard and also added policy 

{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "__sender_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::124327721787:root"
      },
      "Action": [
        "SQS:SendMessage",
        "SQS:GetQueueAttributes"
      ],
      "Resource": "arn:aws:sqs:us-east-1:124327721787:SQS_Standart"
    }
  ]
}

i can able to create a destination  

[resource] => Array
                        (
                            [sqs] => Array
                                (
                                    [arn] => arn:aws:sqs:eu-west-1:124327721787:notification
                                )

                            [eventBridge] => 
                        )

                    [destinationId] => 291d0c5a-8ad6-43d0-9cd1-1e12f8027bf0
                    [name] => order_status

but when i am going to create subscripton i am getting error access  denie can any one help in this .


this is the parameter i am using for create subscription

$notification_type = 'FULFILLMENT_ORDER_STATUS';
$subscription_body = '{
	"payloadVersion":"1.0",
    "destinationId": "4301ee2e-18a5-4c8a-b886-ff599db680a6"
  
}';

Thanks & Regards
