### ISSUE TITLE
How to get or create amazon_state?

### ISSUE THREAD

**Issue by polatdev** [amzn/selling-partner-api-docs#847]
Hi everyone,

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-2-the-selling-partner-consents-to-authorize-your-application

my questions is simple;

amazon_state how to create or get?

thx.

**Comment by alperozhan** [comment]
So there are 2 flows. First one is the one that you redirect people to Amazon for authorization. In this method, state is the field that you fill, and track. Such as you can enter your internal user id there in an encrypted way, and when they redirect back, you can tell which user it is. Or any other internal data you want to track.

The second flow is that when they redirect to your app from seller central. Which means they found you on Amazon's app store. In this method, amazon_state is filled with a value belongs to Amazon. You will have to send this back to Amazon as is while you are trying to retrieve the access tokens.
