### ISSUE TITLE
Not retrieving stock from inventory summary - /fba/inventory/v1/summaries

### ISSUE THREAD

**Issue by iLoveSarabear** [amzn/selling-partner-api-docs#849]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md

Hi, I'm setting the "details" parameter to true, but all I'm getting back is an empty array under [inventory_details].

How do we see how much stock is available for our inventory?

**Comment by iamsr** [comment]
is this api working for you? which region you are trying it for?
