### ISSUE TITLE
Selling Partner API for Fulfillment Outbound release

### ISSUE THREAD

**Issue by SellingPartnerAPI-team** [amzn/selling-partner-api-docs#85]
Hi all,

We have released a new version of the Selling Partner API for Fulfillment Outbound.

This API lets you create applications that help sellers fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. This API provides information on potential and existing fulfillment orders.

Version 2020-07-01 replaces v0 and provides three new features:

* Blank Box Shipping: the ability for sellers to specify delivery in non-Amazon branded boxes.
* A Per Unit Declared Value field: a new required field for shipping orders outside of the country of origin.
* Serial Numbers: the addition of serial numbers in the package tracking to enable sellers to track delivery of high-value items.

You can find the Selling Partner API for Fulfillment Outbound OpenAPI model at https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json. 

Check out the Selling Partner API for Fulfillment Outbound reference at https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md.

Best regards,

The Selling Partner API team

**Comment by charliecode** [comment]
Very nice! Thanks a ton guys for all of your hard work. We really appreciate it! Looking forward to looking into these new features.
