### ISSUE TITLE
MissingAuthenticationToken error when calling Seller Partner API

### ISSUE THREAD

**Issue by moveproduct** [amzn/selling-partner-api-docs#852]
we are getting MissingAuthenticationToken error for below api

1) https://sellingpartnerapi-na.amazon.com/authorization/v1/authorizationCode 
in the request parameter we are passing sellingPartnerId,developerId,mwsAuthToken

2) https://sellingpartnerapi-na.amazon.com/orders/v0/orders
here we are passing x-amz-access-token in header fetched from https://api.amazon.com/auth/o2/token call

{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "MissingAuthenticationToken"
        }
    ]
}

**Comment by jhullparkseed** [comment]
I have a similar issue though i pass via RestSharp and Json:

**Comment by skashish** [comment]
+1

**Comment by chetanshind** [comment]
Ideally if this is a MWS to SPAPI migration application and you have authorized the SPAPI Application to access with MWS credentials. 
Dont know what is the problem. Even I am not able to get this working.

**Comment by cxj** [comment]
I am seeing the same error, despite having an `x-amz-access-token` in my header just as [jhullparkseed](https://github.com/jhullparkseed) mentioned above.

I can only assume there is some _other_ error and Amazon's API is reporting the problem wrongly in the response.
