### ISSUE TITLE
How can I get the product URL if there is no product URL in the product data obtained by my interface?

### ISSUE THREAD

**Issue by qq1356661768** [amzn/selling-partner-api-docs#853]
How can I get the product URL if there is no product URL in the product data obtained by my interface?

I'm through "GET_FLAT_FILE_OPEN_LISTINGS_DATA”

Get SKU,

Then call "catalog"

"get_item" for details.

**Comment by 401009641** [comment]
Stitching asin by yourself

**Comment by daniel031699** [comment]
Has the problem been solved? I can't find the right API
