### ISSUE TITLE
[BUG] FulfillmentChannels on orders/v0/orders is documented incorrectly

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-docs#856]
The documentation indicates "FBA" or "SellerFulfilled", the correct values are "FBA" or "MFN".

**Comment by lw-andrewsmith** [comment]
Also The sandbox response shows SellerFulfilled and returns "SellerFulfilled" from the sandbox API, however the spec shows an enum of MFN.

Which is correct?

**Comment by coder771** [comment]
> Also The sandbox response shows SellerFulfilled and returns "SellerFulfilled" from the sandbox API, however the spec shows an enum of MFN.
> 
> Also is it FBA or AFN? ;)
> 
> Which is correct?

how about are you testing SP API. Sandbox is giving errors due to issues like above. Not sure how to get our QA Team to test it.
