### ISSUE TITLE
[BUG] PII are not returned even using RDT

### ISSUE THREAD

**Issue by marconline** [amzn/selling-partner-api-docs#858]
Hi, we are getting an incomplete response from the Order APIs. Please, consider that we tried both using a "normal" access token and a "restricted data" token, as described in your documentation here: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#restricted-operations.

Request has been sent as a GET to /orders/v0/orders/{orderId}/address endpoint.

The response provided by your service is like the following:
{"payload":{"AmazonOrderId":"{orderId}","ShippingAddress":{"StateOrRegion":"RM","PostalCode":"00197","City":"Roma","CountryCode":"IT","Name":""}}}

As you can see:
- name field is blank
- address field has not been passed (null)

Please also consider that the RDT was generated using an access token generated by converting an old MWS token to the new SP-API one.

Same effect with other restricted operations, like getOrderBuyerInfo
Developer Id:971580489273
Operation:getOrderAddress
MarketplaceId:IT
RequestId:8eea2033-956b-409b-83ef-ed6dc8d7b4f5
TimeStamp:2021-06-08T13:36:45Z

**Comment by marconline** [comment]
Please, consider that I opened this request **before** on your developer support and this is the reply that I received.
![image](https://user-images.githubusercontent.com/14978905/121488986-e8720100-c9d3-11eb-8721-47ed77f7506d.png)

After writing back that what they were asking **was already in my request** they answered this:
![image](https://user-images.githubusercontent.com/14978905/121489091-06d7fc80-c9d4-11eb-92d6-b4da8c445584.png)

Please, Amazon, if you want us to be ready **before September 2021**, you **must** provide us with dedicated support. These fake communications are a complete waste of time!!!

**Comment by glukoid** [comment]
I have the same issue.
Opened the 8444916261 incident about week ago and this was response from support team:

"Amazon Seller Support notes about the conversation:
We continue to research this issue and will update you as soon as any additional information is available. We apologize for the inconvenience this issue has caused."

let`s hope they will fix it soon enough.

**Comment by marconline** [comment]
They closed the ticket telling that in order to use MWS I must have a pro account (!!!).
Incredible. What a shame!

**Comment by greenxolutions** [comment]
Hi...

I had the same issue. So, I just tried to understand if it's my fault or if everyone has the same problem. Does it look like everyone has the same issue then why there are only a few complaints about it?

It based on Amazon's response, we just need to wait for them, right?

I developed in MWS years ago (2015) and everything works ok.

**Comment by 401009641** [comment]
Is this the code written by the Silicon Valley technologists? A bunch of questions

**Comment by marconline** [comment]
@greenxolutions : it seems that you have to wait. I'm wating since 2 months but still no access to PII. Have you been audited by Deloitte and Amazon? We had +3 months of paperworks and everything went fine. We are able to access PII with our MWS application since 2009 and right now we are blocked.

  @401009641 yes :(

**Comment by l-o-u-k-e** [comment]
Hi @marconline, I'm new to the SP-API and I'm developing a new Amazon connector project for the first time. I've no MWS background.
But I can confirm I can read PII data from the /orders/v0/orders/{orderId}/address endpoint.
It's quite strange, with or without using RDT in my requests I receive as follows:

`{
    "payload":
    {
        "AmazonOrderId": "XXX-XXXXXXX-XXXXXXX",
        "ShippingAddress":
        {
            "StateOrRegion": "FC",
            "AddressLine1": "Via Xxx Xxxxxx Xxxxx, 999",
            "Phone": "0547999999",
            "PostalCode": "47522",
            "City": "Cesena",
            "CountryCode": "IT",
            "Name": "Xxxxxxx Xxxxxxx"
        }
    }
}`

I've enabled all roles to my app, except "Tax Remittance Role" which I suppose I don't need it by design.

**Comment by glukoid** [comment]
@l-o-u-k-e: how did you define your AWS user roles ? did you do anything special ?
also it might work for one region and does not work for another.

for example with or without RDT I could not get addressLine1 and name of the customer.

Also, I know it is offline question, but maybe someone could help me to understand how I could receive shipping information (USPS tracking number) from the order ?

**Comment by marconline** [comment]
> Hi @marconline, I'm new to the SP-API and I'm developing a new Amazon connector project for the first time. I've no MWS background.
> But I can confirm I can read PII data from the /orders/v0/orders/{orderId}/address endpoint.
> It's quite strange, with or without using RDT in my requests I receive as follows:
> 
> `{ "payload": { "AmazonOrderId": "XXX-XXXXXXX-XXXXXXX", "ShippingAddress": { "StateOrRegion": "FC", "AddressLine1": "Via Xxx Xxxxxx Xxxxx, 999", "Phone": "0547999999", "PostalCode": "47522", "City": "Cesena", "CountryCode": "IT", "Name": "Xxxxxxx Xxxxxxx" } } }`
> 
> I've enabled all roles to my app, except "Tax Remittance Role" which I suppose I don't need it by design.

Hi @l-o-u-k-e (anzi ciao, visto che penso tu sia italiano!), thanks for your reply but I can confirm that the problem is probably in Amazon migrating an old MWS application to a new SP-API application. I can assure that:
1. with MWS I can totally get all the PII
2. I can succesfully convert the old MWS token to the new SP-API one
3. I can correctly call SP-API endpoints using the SP-API token
4. calling endpoints that asks for PII (like getOrderAddress) or generating a report that may contain PII results in an error. 
5. roles are correctly enabled on our (published) hybrid application. We only miss "Communication with buyers"

I got answer from SC help and they confirm is something on their side, but this is blocking as we cannot totally switch from MWS to SP-API. I hope they dig into this as soon as possible, since I think I'm not the only one in this situation.

Thanks
Marco

**Comment by l-o-u-k-e** [comment]
Hi @glukoid,
>>how did you define your AWS user roles ?
I followed step by step the [Selling Partner API Developer Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md). 1 to 5 steps, and the "Registering your application" paragraph.

>>for example with or without RDT I could not get addressLine1 and name of the customer.
Very strange, maybe there really are selective blocks from Amazon system.. who knows?!

>> how I could receive shipping information (USPS tracking number) from the order ?
I don't know, I'm sorry I've never had this need.

**Comment by l-o-u-k-e** [comment]
Ciao @marconline (si, sono romagnolo 😄 ),
let us know when Amazon support will solve your issue.

Because BTW I'm facing similar issue in querying GET_ORDER_REPORT_DATA_INVOICING or GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING which I can obtain but in which PII data such as customer name or VAT Code Or Fiscal Code are missing.

In fact it's been 1 month that I'm trying to read customers VAT Code, in different ways, but with no luck.
Since last week I'm in touch with an Amazon technical engineer that is helping me find a solution... we are working on it..

Did you accomplish this kind of PII data with SP-API?

**Comment by marconline** [comment]
@l-o-u-k-e well, at least you don't get an error while trying to get those reports. In that case I get an error, even if I try to schedule them. :(
No, I cannot get any PII with SP-API, while I can see everything with MWS.

Marco

**Comment by glukoid** [comment]
RDT and receiving of restricted information issues resolved for me.
the magic was to generate new refresh token after receiving PII permissions.

**Comment by marconline** [comment]
@glukoid I even tried that. Nothing different happens.

**Comment by abuzuhri** [comment]
> @glukoid I even tried that. Nothing different happens.

@marconline same problem with me , do you solve the problem ?

**Comment by paly76** [comment]
> @glukoid I even tried that. Nothing different happens.

hi,do you solve the problem ?

**Comment by marconline** [comment]
Hi everybody, finally I got this working. Check my latest article: https://marco-tibaldeschi.medium.com/amazon-sp-api-roles-demystified-6f53ee9dbeda

**Comment by J-W-Chan** [comment]
> 



> Hi everybody, finally I got this working. Check my latest article: https://marco-tibaldeschi.medium.com/amazon-sp-api-roles-demystified-6f53ee9dbeda

H,When I applied for PII permission, Amazon replied to my message. How should I solve it?

![image](https://user-images.githubusercontent.com/6493028/143220961-4d51d98e-d277-40bf-9437-11fa82f246ad.png)

**Comment by marconline** [comment]
Hi @J-W-Chan , unfortunately I guess you won't be able to solve it, as Amazon rejected your request.

**Comment by J-W-Chan** [comment]
> Hi @J-W-Chan , unfortunately I guess you won't be able to solve it, as Amazon rejected your request.

Why would Amazon reject my application? Can you advise me how to apply for PII permission?Thank you

**Comment by J-W-Chan** [comment]
> Hi @J-W-Chan , unfortunately I guess you won't be able to solve it, as Amazon rejected your request.

Why would Amazon reject my application? Can you advise me how to apply for PII permission?Thank you

**Comment by marconline** [comment]
Hi, unfortunately I don't know why they rejected it. I guess that this may be related to how you filled your developer profile. Amazon has very strict requirements on data management requirements.

**Comment by abuzuhri** [comment]
> > Hi @J-W-Chan , unfortunately I guess you won't be able to solve it, as Amazon rejected your request.
> 
> Why would Amazon reject my application? Can you advise me how to apply for PII permission?Thank you

Same here also they reject my application

**Comment by J-W-Chan** [comment]
> > > Hi @J-W-Chan , unfortunately I guess you won't be able to solve it, as Amazon rejected your request.
> > 
> > 
> > Why would Amazon reject my application? Can you advise me how to apply for PII permission?Thank you
> 
> Same here also they reject my application


What is the reason for their refusal?

**Comment by abuzuhri** [comment]
I think they try to avoid any problem 

> > > > Hi @J-W-Chan , unfortunately I guess you won't be able to solve it, as Amazon rejected your request.
> > > 
> > > 
> > > Why would Amazon reject my application? Can you advise me how to apply for PII permission?Thank you
> > 
> > 
> > Same here also they reject my application
> 
> What is the reason for their refusal?

I think they trying avoid any problem from seller abuse after GDBR
