### ISSUE TITLE
Error calling SearchCatalogItems for child products

### ISSUE THREAD

**Issue by PasswebPass** [amzn/selling-partner-api-docs#860]
Hello,
when I search for a child product using the searchCatalogItems call passing the EAN of the child product for example with this EAN on the Italy marketplace
Request
[
    {
        "Name": "keywords",
        "Value": "8068057337984"
    },
    {
        "Name": "marketplaceIds",
        "Value": "APJ6JRA9NG5V4"
    },
    {
        "Name": "includedData",
        "Value": "summaries, identifiers, productTypes, variations"
    }
]
I get this Response:
{
    "numberOfResults": 1,
    "pagination": {},
    "refinements": {
        "brands": [],
        "classifications": []
    },
    "items": [
        {
            "asin": "B07JX8BZ6P",
            "identifiers": [
                {
                    "marketplaceId": "APJ6JRA9NG5V4",
                    "identifiers": []
                }
            ],
            "productTypes": [
                {
                    "marketplaceId": "APJ6JRA9NG5V4",
                    "productType": "COAT"
                }
            ],
            "summaries": [
                {
                    "marketplaceId": "APJ6JRA9NG5V4",
                    "brandName": "Scotland",
                    "browseNode": "2420941031",
                    "colorName": "Nero",
                    "itemName": "Scotland Giacca da Moto, Milano, Uomo",
                    "manufacturer": "Scotland",
                    "sizeName": "M"
                }
            ],
            "variations": [
                {
                    "marketplaceId": "APJ6JRA9NG5V4",
                    "asins": [
                        "B00SB708QA",
                        "B00SB6ZZLO",
                        "B00SB6ZZKU",
                        "B00SB6ZZGO",
                        "B00SB6ZZI2",
                        "B00SB6ZT8I"
                    ],
                    "variationType": "PARENT"
                }
            ]
        }
    ]
}
The data of the parent product is obtained in response.
Instead with the call getCatalogItem with EAN parameters 8068057337984 I get the data of the child product
Response
{
    "payload": {
        "Items": [
            {
                "Identifiers": {
                    "MarketplaceASIN": {
                        "MarketplaceId": "APJ6JRA9NG5V4",
                        "ASIN": "B00SB6ZZKU"
                    }
                },
                "AttributeSets": [
                    {
                        "Binding": "Automobile",
                        "Brand": "Scotland",
                        "Color": "Nero",
                        "Department": "Unisex - Adulto",
                        "ItemDimensions": {
                            "Weight": {
                                "value": 2.425084882,
                                "Units": "pounds"
                            }
                        },
                        "Label": "Scotland",
                        "ListPrice": {
                            "Amount": 158.92,
                            "CurrencyCode": "EUR"
                        },
                        "Manufacturer": "Scotland",
                        "Model": "800003",
                        "PackageDimensions": {
                            "Height": {
                                "value": 5.511811018,
                                "Units": "inches"
                            },
                            "Length": {
                                "value": 30.708661386,
                                "Units": "inches"
                            },
                            "Width": {
                                "value": 20.472440924,
                                "Units": "inches"
                            },
                            "Weight": {
                                "value": 2.20462262,
                                "Units": "pounds"
                            }
                        },
                        "PackageQuantity": 1,
                        "PartNumber": "800003",
                        "ProductGroup": "Ricambi e accessori auto",
                        "ProductTypeName": "COAT",
                        "Publisher": "Scotland",
                        "ReleaseDate": "2019-09-24",
                        "Size": "50",
                        "SmallImage": {
                            "URL": "https://m.media-amazon.com/images/I/41-eTJxcbFL._SL75_.jpg",
                            "Height": {
                                "Units": "pixels",
                                "value": 75
                            },
                            "Width": {
                                "Units": "pixels",
                                "value": 63
                            }
                        },
                        "Studio": "Scotland",
                        "Title": "Scotland Giacca da Moto, Milano, Uomo, Nero, 50"
                    }

Why?

**Comment by chapmanjw** [comment]
@PasswebPass If I understand correctly, you are comparing searching the EAN of a child ASIN in the 2020-12-01 API keyword search vs. the id-based search in the v0 API? 

And that if you search new new API with the EAN, you are getting the parent ASIN instead of the expected child ASIN?

Assuming I understand correctly, sounds like you've found a bug. I will follow up with my team on how we can address this issue. Thanks for reporting!

**Comment by PasswebPass** [comment]
Hi, @chapmanjw, 
yes, that's exactly what you wrote.
By calling searchCatalogItems with the EAN, I get the data the parent ASIN instead of the expected child ASIN

**Comment by chapmanjw** [comment]
@PasswebPass Thanks for confirming. We've logged the issue with my team and we are identifying the right path to addressing the issue. I will post a reply here once we have a fix (not sure on timing yet as we don't yet have the solution figured out).

**Comment by midi-red** [comment]
@chapmanjw Do you have any updates for this bug fix? We are still receiving parent item given UPC/EAN belongs to a child asin. On a side node, why you do not have support for getCatalogItemByUPCorEAN like GET /catalog/2020-12-01/items/ean/{EAN} ?

**Comment by chapmanjw** [comment]
@midi-red We are, unfortunately, still working on a path forward for the child ASIN rollup behaviors. It's not a simple configuration option or change on our search indexes, etc., thus the larger effort/timeline to address. :-( 

For searching the catalog by product identifier, the intended design of the v2020-12-01 Catalog Items API was to behave similarly to the search functionality in Seller Central where you would use the ids as keywords. However, to aid in querying for multiple identifiers, we will be adding another query parameter to the search operation (like `identifiers`) that will accept a list of product identifiers. Stay tuned for updates on that.

**Comment by chapmanjw** [comment]
@midi-red and @PasswebPass Apologies for the delayed response. When searching the v2020-12-01 Catalog Items API or the newly released v2022-04-01 Catalog Items API for product identifiers include the actual ASIN matched, rather than the parent ASIN. Additionally, the v2022-04-01 version allows you to query explicitly for up-to 20 identifiers in a single request: https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference
