### ISSUE TITLE
Report is IN_PROGRESS more than 48h!!!

### ISSUE THREAD

**Issue by kerbalwzy** [amzn/selling-partner-api-docs#861]
I have a report. It has been in progress for more than 48 hours. I don't know how long it will take. Has anyone encountered the same situation? What's the longest waiting time?
![image](https://user-images.githubusercontent.com/32036069/121495837-8681bd80-ca0c-11eb-8fbc-0f4ae55c9c5c.png)

**Comment by stefnats** [comment]
We experienced this again - regularly.
You either need to cancel and re-submit that feed or contact seller support to cancel that. 

It's a common problem that nobody got its head around yet.

**Comment by kerbalwzy** [comment]
Can only cancel the report with IN_QUEUE...

**Comment by stefnats** [comment]
OK, got it. Could you contact developer support and keep me updated? Maybe this time, there is a long term solution.

**Comment by kerbalwzy** [comment]
![image](https://user-images.githubusercontent.com/32036069/121983580-21d7b180-cdc4-11eb-8876-d8900d5b4d82.png)
Finally, ...haha

**Comment by stefnats** [comment]
@kerbalwzy wow almost five days? 

has amazon said anything about this?
have you tried requesting the report again and was it similarly slow?
how big is the resulting report? it must be immensly big (>1GB) if it takes so long.
or was it cancelled?

**Comment by aidensgithub** [comment]
Hello @kerbalwzy !
Did you contact amazon to cancel IN_PROGRESS task for you, or there is a quicker solution?
Thanks!

**Comment by SouravPal95** [comment]
I had a similar situation. Developer support was of no help. @kerbalwzy. Could u please share how u solved this issue?

**Comment by unstory** [comment]
> I had a similar situation. Developer support was of no help. @kerbalwzy. Could u please share how u solved this issue?

I had a similar situation.Could u please share how u solved this issue? Thanks a lot!
