### ISSUE TITLE
createFeedDocument SP API [BUG] Documentation 

### ISSUE THREAD

**Issue by srsole** [amzn/selling-partner-api-docs#862]
I am trying to follow the guide [Feeds API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md)

The point is that I stay in step 1, when it says "**Step 1. Create a feed document**".
When  I try to create  "**createFeedDocument**" all my response, always gimeve "invalid input".

I know for sure that it is not an authentication problem.

I use C#, here I leave part of the code, an example of a request, with the corresponding response.

> Code C#

```
string url_api = "/feeds/2020-09-04/documents";
restClient = new RestClient(live_url_base); //https://sellingpartnerapi-eu.amazon.com
IRestRequest restRequest = new RestRequest(url_api , Method.POST);
restRequest.AddHeader("x-amz-access-token", txtAccessToken.Text);            
restRequest.AddParameter("contentType", "text/tab-separated-values;charset=UTF-8", "application/json",ParameterType.RequestBody ); 
var request = signatureHelper.SignRequest(restRequest, restClient, "application/json");
```

> Params in Request
```
 [0]: {x-amz-access-token=Atza|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
 [1]: {contentType=text/tab-separated-values;charset=UTF-8}
 [2]: {X-Amz-Date=20210610T124106Z}
 [3]: {host=sellingpartnerapi-eu.amazon.com}
 [4]: {Authorization=AWS4-HMAC-SHA256 Credential=xxxxxxxxx/20210610/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date, Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
 [5]: {Content-type=application/json}
 [6]: {user-agent=My App 1.0 (Language=csharp;Platform=Windows/10)}
```

> Response

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```

Thanks in advance

**Comment by rugved1991** [comment]
Hi @srsole,

The createFeedDocument operation is a POST call. You need to add the CreateFeedDocumentSpecification as body and not in parameters. Can you try adding the following in the body section of the request and test again?
{
  "contentType":"text/tab-separated-values; charset=UTF-8"
}

Thanks,
Rugved
Solutions Architect, SP API

**Comment by srsole** [comment]
Hello @rugved1991, thanks for your reply.
The parameter is added in body look in code 
`restRequest.AddParameter("contentType", "text/tab-separated-values;charset=UTF-8", "application/json",ParameterType.RequestBody ); ` <--here

We are using RestSharp as I think you already know.

If the body parameter were missing, the response would be "Missing required parameter contentType".

**Comment by rugved1991** [comment]
Hi @srsole,

Apologies, I missed the last part of the code line. The body looks good. In the headers, you are adding two contentType headers. You should only add "Content-Type=application/json" in the header. 
Please remove "contentType" header from the request.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by srsole** [comment]
Hi @rugved1991 thanks for reply
I try the same result. "Invalid input"

**Comment by srsole** [comment]
I give up, thanks.

**Comment by sim789** [comment]
@srsole dont give up. Let me know if you need help to resolve the issue. I will sure help you to resolve this issue.

**Comment by sumumumu** [comment]
> Hello @rugved1991, thanks for your reply.
> The parameter is added in body look in code
> `restRequest.AddParameter("contentType", "text/tab-separated-values;charset=UTF-8", "application/json",ParameterType.RequestBody ); ` <--here
> 
> We are using RestSharp as I think you already know.
> 
> If the body parameter were missing, the response would be "Missing required parameter contentType".

You should only add "Content-Type=application/json" in the header.
“contentType=text/tab-separated-values;charset=UTF-8 ” should be passed in the body in JSON.

`
            string resource = "/feeds/2020-09-04/documents";
            RestClient restClient = new RestClient(this.RegionUrl);
            IRestRequest restRequest = new RestRequest(resource, Method.POST);

            CreateFeedDocumentSpecification cfds = new CreateFeedDocumentSpecification
            {
                contentType = contentType
            };
            restRequest.AddJsonBody(cfds);

            restRequest.AddHeader("x-amz-access-token", GetAccessToken());
            restRequest = new AWSSigV4Signer(this.AWSAC)
                .Sign(restRequest, restClient.BaseUrl.Host);

            var resp = restClient.Execute(restRequest);
`

**Comment by yao657355700** [comment]
> @srsole不要放弃。如果您需要帮助来解决问题，请告诉我。我一定会帮助你解决这个问题。

I also encountered the same problem, is there a solution?

**Comment by satyacoder** [comment]
fixed it. header content type must be "application/json"
 and i using 
 restRequest.AddJsonBody({\"contentType\":\"text/tab-separated-values; charset=UTF-8\"});

**Comment by abuzuhri** [comment]
> I am trying to follow the guide [Feeds API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md)
> 
> The point is that I stay in step 1, when it says "**Step 1. Create a feed document**".
> When I try to create "**createFeedDocument**" all my response, always gimeve "invalid input".
> 
> I know for sure that it is not an authentication problem.
> 
> I use C#, here I leave part of the code, an example of a request, with the corresponding response.
> 
> > Code C#
> 
> ```
> string url_api = "/feeds/2020-09-04/documents";
> restClient = new RestClient(live_url_base); //https://sellingpartnerapi-eu.amazon.com
> IRestRequest restRequest = new RestRequest(url_api , Method.POST);
> restRequest.AddHeader("x-amz-access-token", txtAccessToken.Text);            
> restRequest.AddParameter("contentType", "text/tab-separated-values;charset=UTF-8", "application/json",ParameterType.RequestBody ); 
> var request = signatureHelper.SignRequest(restRequest, restClient, "application/json");
> ```
> 
> > Params in Request
> 
> ```
>  [0]: {x-amz-access-token=Atza|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
>  [1]: {contentType=text/tab-separated-values;charset=UTF-8}
>  [2]: {X-Amz-Date=20210610T124106Z}
>  [3]: {host=sellingpartnerapi-eu.amazon.com}
>  [4]: {Authorization=AWS4-HMAC-SHA256 Credential=xxxxxxxxx/20210610/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date, Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
>  [5]: {Content-type=application/json}
>  [6]: {user-agent=My App 1.0 (Language=csharp;Platform=Windows/10)}
> ```
> 
> > Response
> 
> ```
> {
>   "errors": [
>     {
>       "code": "InvalidInput",
>       "message": "Invalid Input",
>       "details": ""
>     }
>   ]
> }
> ```
> 
> Thanks in advance

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp
