### ISSUE TITLE
Can't find right Product Type for Listings API

### ISSUE THREAD

**Issue by yiweixia** [amzn/selling-partner-api-docs#864]
There was a release announcement for the Product Types and Listing APIs here: https://github.com/amzn/selling-partner-api-docs/issues/821, but the product type related stuff doesn't seem to be working. I tried calling the getDefinitionsProductType API (`GET /definitions/2020-09-01/productTypes/{productType}`), but it only returns a handful of product types: 

<details>

```
{
  "productTypes": [
    {
      "name": "AIR_MATTRESS",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BACKPACK",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BAG",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BEAN_BAG_CHAIR",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BED",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BED_FRAME",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BED_RAIL",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BENCH",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "BOTTLE_RACK",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "CABINET",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "CHAIR",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "COSMETIC_CASE",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "CRIB",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "DESK",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "DRESSER",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "DUFFEL_BAG",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "FURNITURE",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "HEADBOARD",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "LUGGAGE",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "MATTRESS",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "OTTOMAN",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "PRODUCT",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "SHELF",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "SOFA",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "STOOL_SEATING",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "SUITCASE",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "TABLE",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "WAIST_PACK",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    },
    {
      "name": "WALLET",
      "marketplaceIds": [
        "ATVPDKIKX0DER"
      ]
    }
  ]
}
```

</details>

Furthermore, the listings API requires a productType when updating attributes, and it rejects productTypes such as `PETSUPPLIES`, but it seems that the update works if I use `LUGGAGE`, even if the product isn't at all LUGGAGE related. 

Is the product types API ready for use? Does the product type actually do anything in listings API calls right now?

**Comment by sherlock270** [comment]
You can use [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#get-catalog2020-12-01itemsasin) with 'productTypes' in the includedData. It will give you the correct product type. However, not all product types have been migrated, those that haven't use the `PRODUCT` product type.

**Comment by chapmanjw** [comment]
More details for both the Listings and Definitions APIs can be found in the use case guides:

- https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md
- https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md

We are in the process of migrating the content and rules for Amazon product types, making them available in the Product Type Definitions API as the migration progresses. For product types not yet listed in the Product Type Definitions API, we do not support creating new products in the APIs at this time. However, we do support creating offers (i.e. listing with an existing ASIN) for most use-cases.

**Comment by SouravPal95** [comment]
I have been trying to use the feeds API to create product listings. However, any `productType` value I provided rendered a processing report with an error of invalid or unsupported product type. So I decided to use the search product definitions API endpoint for marketplace ID (`A21TJRUUN4KGV`) for India. It returned empty for `LUGGAGE` and every other keyword that I tried. Then I tried without any keyword and received PRODUCT as the only available type. Then on using it with requirements attribute `LISTING`, I received a processing report with error message that cannot use product type PRODUCT to create products which is an a problem because that is all I have available...could some one through a light on this issue? Is this related to the same migration related issue as stated above?

**Comment by chapmanjw** [comment]
Yes, we have migrated some product types for sellers (merchants) in the US and EU5 marketplaces. We have more broad coverage for vendors in other marketplaces, but have not yet migrated content in the IN marketplace. For marketplaces without migrated product types, we are currently limited to editing common attributes, such as price and inventory, but do not yet support creating new products without the migrated product types.

**Comment by yizeku** [comment]
@chapmanjw 

**PUT  https://sellingpartnerapi-na.amazon.com/listings/2020-09-01/items/A31EDVFF4K7C6L/050130?issueLocale=en_US&marketplaceIds=ATVPDKIKX0DER**

  {"sku":"050130","status":"INVALID","submissionId":"9b4211cf264345e289ceb1a8193798e3","issues":[{"code":"4000003","message":"The Amazon product type specified is invalid or not supported.","severity":"ERROR"}]}

How should this mistake be solved? Can you help me?

Thank you.

**Comment by uk-2** [comment]
@chapmanjw 

Hi 
We trying add a offer to ASIN but we keep getting 

Got: {\"sku\":\"cc_24\",\"status\":\"INVALID\",\"submissionId\":\"ac1eab4367b94cbabc14aecd4113a26f\",\"issues\":[{\"code\":\"4000003\",\"message\":\"The Amazon product type specified is invalid or not supported.\",\"severity\":\"ERROR\"}]


We are listing 24 packs of coco cola and we have looked up the product type using getcatalogitem which returned productType"=>"DRINK_FLAVORED"  but this still is not allowing us to list our offer ?

Thanks

**Comment by chapmanjw** [comment]
The list product types that have been migrated to the APIs is available by calling the search operation of the Product Type Definitions API: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md. Until the product type of an item is migrated to the APIs, you can use the `PRODUCT` product type to edit common attributes applicable to all items.

**Comment by shirushi-dev** [comment]
@chapmanjw 

"product_type" => "PRODUCT", 

but I get the following

    "issues": [
        {
            "code": "4000003",
            "message": "The Amazon product type specification is invalid or not supported."
            "severity": "ERROR"
        }
    ]

Therefore, the listing function is not available.

**Comment by shirushi-dev** [comment]
When will the product type be available?
We migrated from MWS API in a hurry, but it is inconvenient that we cannot realize product listing in SP-API. We should not have migrated.

**Comment by chapmanjw** [comment]
@shirushi-dev Migrating from MWS Feeds API to SP Feeds API would allow you to use the same document submissions (the XML feeds, etc.) that you were previously using (i.e. you are mostly changing which client you are using and which endpoint you are hitting, not the actual content you are submitting). 

Migrating to the SP Listings APIs is effectively the actual content you are submitting. For clients currently using XML product feeds whose use-cases are not yet fully covered by the SP Listings APIs, we recommend continuing to use the XML product feeds, but with the SP Feeds API at this time.

**Comment by ShaneOH** [comment]
@chapmanjw Any update on the level of parity support as of January 2023? We're looking to migrate from SP-API Feeds API to the Listings API as it seems to be a more modern stack, but we're fearful of that exact scenario you described, and whether there are any use cases not yet fully covered by the SP Listings APIs.
