### ISSUE TITLE
Invalid request parameters sending POST_INVENTORY_AVAILABILITY_DATA feed

### ISSUE THREAD

**Issue by rmp135** [amzn/selling-partner-api-docs#867]
On attempting to send a POST_INVENTORY_AVAILABILITY_DATA feed, all I'm receiving is "Invalid request parameters".

1. POST to /feeds/2020-09/documents with `{"contentType":"text/xml; charset=UTF-8"}`. Receive a feedDocumentId and encryption details.
2. PUT to the above feed document URL.
```xml
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
  <Header>
    <DocumentVersion>1.01</DocumentVersion>
  </Header>
  <MessageType>Inventory</MessageType>
  <Message>
    <MessageID>1</MessageID>
    <OperationType>Update</OperationType>
    <Inventory>
      <SKU>TESTPHONE1</SKU>
      <Quantity>1</Quantity>
    </Inventory>
  </Message>
</AmazonEnvelope>
```
This returns successfully. I've also attempted sending this encrypted and plain, both respond in the same way. 
3. POST to /feeds/2020-09-04/feeds with 
```json
{
    "feedType": "POST_INVENTORY_AVAILABILITY_DATA",
    "marketplaceIds": [
        "A1F83G8C2ARO7P"
    ],
    "inputFeedDocumentId": "{feedDocumentId}"
}
```
It's here that a 400 Bad Request is returned with the following.
```json
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid request parameters",
            "details": ""
        }
    ]
}
```

Does anyone have experience in updating quantity values? There's so few parameters here that I've no idea what could be going wrong.

**Comment by ShivikaK** [comment]
Hello @rmp135 

Thank you for raising the issue. 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by rmp135** [comment]
I've raised a support ticket (ID 7080708312) and this is the response I received.

"Please note that sellers who use XML are expected to create and troubleshoot their code. Seller Support is NOT trained to troubleshoot or create XML."

I raised it from within the seller central support page, is there somewhere else I should be raising API support issues?

**Comment by rmp135** [comment]
@ShivikaK I've just discovered I get the exact same error when attempting to create a "POST_ORDER_FULFILLMENT_DATA" feed. Is it because the app is in draft state that feeds do not work? Would you like me to create another support ticket?

**Comment by jlevers** [comment]
@rmp135 have you gotten any resolution here? I'm getting the same error for a number of feeds that were working fine a couple months ago.

**Comment by rmp135** [comment]
@jlevers No sorry, I haven't been able to get this working. In the same boat, this worked a few months back and I left it. Came back and the exact same code was returning this error. If you find a solution do let me know.

**Comment by rmp135** [comment]
@jlevers Any luck getting it to work? Was hoping the new feeds API would help but it's still returning same error.

**Comment by jlevers** [comment]
@rmp135 honestly not sure what I changed, but I believe it's working now...sorry, I know that's not very helpful :/

**Comment by rmp135** [comment]
@jlevers Glad you got it working but you were my only hope! Is you app in draft stage or live on the marketplace?

**Comment by jlevers** [comment]
Draft stage...does your report look like this?

```xml
<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="amzn-envelope.xsd"
>
  <Header>
    <DocumentVersion>1.02</DocumentVersion>
    <MerchantIdentifier>ASDF...</MerchantIdentifier>
  </Header>
  <MessageType>Inventory</MessageType>
  <Message>
    <MessageID>12345</MessageID>
    <SKU>ASDF1234</SKU>
    <Quantity>3</Quantity>
  </Message>
</AmazonEnvelope>
```

**Comment by rmp135** [comment]
Not exactly, the SKU and Quantity was wrapped in an Inventory tag. I've tried with your request and still no dice. I can send complete nonsense in that request and I get the same result, suggesting perhaps it's one of the other calls.

What does your POST to "/feeds/2020-09/documents" look like, just JSON with `{"contentType":"text/xml; charset=UTF-8"}`?

**Comment by jlevers** [comment]
My bad, you're right -- the SKU and Quantity tags are supposed to be in an inventory tag. I misread my code. I'll edit my post above to avoid confusing anyone else.

And yep, my request looks something like this:
```
POST /feeds/2020-09-04/documents

Content-Type: application/json
Host: sellingpartnerapi-na.amazon.com
User-Agent: SellingPartnerAPI/1.0 (Langugage=PHP)
x-amz-access-token: Azta|IWeB...
x-amz-date: 20210813T084123Z
Authorization: ....

{"contentType": "text/xml;charset=UTF-8"}
```

**Comment by AshokRaja10** [comment]
I'm trying to figure out how to upload the XML content to the URL obtained from createFeedDocument API.
It will be of much help if anyone could share the code snipped for the same.
Thanks in advance.
cc @rmp135 @jlevers

**Comment by rmp135** [comment]
After raising a support ticket, the Amazon engineers have fixed this issue for me, must have been something on the backend. If you're still having issues send them a support ticket and they should get it working for you as well. It took about 5 months to resolve so raise one as early as possible.

**Comment by ro0NL** [comment]
same issue for existing XML :(

> the Amazon engineers have fixed this issue for me, 

they should have fixed the error response as well :roll_eyes:
