### ISSUE TITLE
Not able to access authentication server

### ISSUE THREAD

**Issue by thunderbolt52** [amzn/selling-partner-api-docs#869]
On accessing auth server: **https://api.amazon.com/Oauth/o2/token** , i'm receiving maintainance error. May i know if there any change in URL Or how long the service will be down? Do we have any ETA?
![Website not available](https://user-images.githubusercontent.com/83335800/121687253-c4034b00-cadf-11eb-8029-bd467fed03b0.JPG)

**Comment by thunderbolt52** [comment]
Corrected the URI : https://api.amazon.com/auth/o2/token and received "500" internal server error.

**Comment by ezpinsky** [comment]
@thunderbolt52 Did you figure this out? What operation were you trying to do?

**Comment by thunderbolt52** [comment]
> @thunderbolt52 Did you figure this out? What operation were you trying to do?

Not yet.. Trying to get new access token using refresh token i have..but it is not working. Will you guide me how i can achieve this in sandbox as well as in production box?

**Comment by doverradio** [comment]
Hi I am facing this exact problem right now.  Any solution?

**Comment by thunderbolt52** [comment]
Yes buddy... You need to mention access token in auth header. Mention refresh token and others in body part. Check GitHub documentation.

**Comment by thunderbolt52** [comment]
Use refresh token and related params in request body.
