### ISSUE TITLE
Request signing with Python

### ISSUE THREAD

**Issue by jugi92** [amzn/selling-partner-api-docs#87]
While trying to connect to the new [Selling Partner API][1] for Amazon, I'm trying to use the following [AWS example][2] to sign my request properly:

```
import hashlib
import json
payload = {
    "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
    "dataStartTime": "2020-10-10T20:11:24.000Z",
    "marketplaceIds": [
        "A1PA6795UKMFR9"
    ]
}

payload_hash = hashlib.sha256(json.dumps(payload).encode('utf-8')).hexdigest()
```
returns the `payload_hash` of `942a2ee7d7dd8727860f6da72dd33c6620bc5af2633730bb7bd711745b16d30e` to me.
When I append this to the request as described and send it to the Sellingpartner API the response tells that the payload hash should have been `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`.

What am I doing wrong?

A full example of the code can be found in this [gist][3].
I also asked the same question on [Stackoverflow][4]

  [1]: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-and-sign-your-request
  [2]: https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html#sig-v4-examples-post
  [3]: https://gist.github.com/jugi92/bf0f5e7f52dbb52bfca73f0ffbff5e6a
  [4]: https://stackoverflow.com/questions/64622102/signing-aws-api-request-with-payload

**Comment by rogersv** [comment]
You forgot to add the header x-amz-content-sha256 see https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html.
That is why you got the e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 which is the hash for an empty string.

**Comment by jugi92** [comment]
Thanks for the hint @rogersv. I updated the linked gist above according to your suggestions. Unfortunately even with that I still get the reply saying it expected the hash of an empty string. It seems like the body of my request is not really considered.

**Comment by jugi92** [comment]
I figured out that deleting the content-length header created the problem that the body is not really used for the hash calculation on Amazons side.
