### ISSUE TITLE
What grants are required for /sales/v1/orderMetrics?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#872]
I'm getting `Unauthorized`, but it seems I should have enough grants available for this call.

Can we get a list of grants required for this?

**Comment by rugved1991** [comment]
Hi @moltar,

You can use "Sales Analytics" role to get access to this API. If you are unable to call the API even after adding the role and re-authorizing the application, please create a support case to troubleshoot the issue further. You can add the complete request and response along with headers in the support case to investigate further.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by moltar** [comment]
All of a sudden it started working today 🤷🏼
