### ISSUE TITLE
SP API Dev account & PII access approximate wait time 

### ISSUE THREAD

**Issue by kinjalnyc** [amzn/selling-partner-api-docs#873]
We applied 10 days ago for for our developer account with PII access. Our developers are on standby to start working and waiting for approval. Anyone one has idea of how long generally takes to get approved for developer account and PII access ? 

Thanks

**Comment by jchavest13** [comment]
Hi @kinjalnyc,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by kinjalnyc** [comment]
Hello Julian,

The case ID is 8417659571. Thank you for checking on it.

**Comment by PasswebPass** [comment]
Hello,
I am attacking this issue, as I too am waiting for approval to log in as a developer account and PII access.
My app is in Draft status.
The developers have finished migrating from MWS to SP-API, but as long as my app remains in Draft we cannot migrate Sellers from MWS to SP-API with Authorization API (getAuthorizationCode)
 
The case ID is 6900017342.
Sincerely

**Comment by jchavest13** [comment]
Hello everybody,

@kinjalnyc @PasswebPass - Please accept our apologies for the delay getting back to both of you on your cases. You can rest assured that our team is working diligently to address your cases as soon as possible. I've also raised an internal request to expedite the vetting of your cases.
Please ensure you monitor your Seller Central accounts for any pending case updates where your responses may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist

**Comment by karinamendonca29** [comment]
Hi,

I'm also awaiting a response on this : SP-API Developer Profile Update : Restricted Access Request
ID: 7071942002

The initial email said it would take 5 business days but it's been more than a week now!

**Comment by kinjalnyc** [comment]
@jchavest13  thank you, but we are still stuck would really appreciate help.
