### ISSUE TITLE
Response time to SP API migration case?

### ISSUE THREAD

**Issue by dsailer** [amzn/selling-partner-api-docs#875]
Can anyone comment on whether they are getting responses to the "Amazon MWS Migration to SP-API" case that Amazon opened for this migration? It is my understanding this is where we should be requesting support to any issues, but I've had a case open for four days now. Just wondering what kind of turn-around others are getting.

**Comment by jchavest13** [comment]
Hi @dsailer,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by dsailer** [comment]
you bet:

caseID=8190866971

**Comment by jchavest13** [comment]
Hi @dsailer,

I've created an internal request to expedite the response on your case with the team supporting migration cases. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
