### ISSUE TITLE
ResultMessageCode 5001 XML Parsing Fatal Error Content is not allowed in trailing section. Content is not allowed in trailing section

### ISSUE THREAD

**Issue by aniruddhaad** [amzn/selling-partner-api-docs#877]
**Describe the bug**
1. Create a product feed feedType "POST_PRODUCT_DATA"
2. create feed document id
3. upload feed 
4. create feed -> get feed id
5. getFeed using feed id
6.  if processingStatus is DONE then get Feed Document
7. then download Feed Processing Report

I always getting ResultMessageCode 5001  ResultDescription XML Parsing Fatal Error at Line 27, Column 1: Content is not allowed in trailing section. Content is not allowed in trailing section

Confirmed that file is utf-8 encoded. Same is mentioned in xml encoding declaration.
Tried setting DocumentVersion 1.01 and 1.02. No difference. Same error.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md

**Description of what the documentation currently says**
Step 6. Download and decrypt the feed processing report
You can download and decrypt the feed processing report using the information returned in the previous step.

**Description of what the documentation should say**
It should say the error codes and error messages to expect.   There is no error code documented. There is no feed specifciations.
The exact feed is working with MWS but not working with new API.

**Screenshots**
This is request file -
[amazon-product-request.txt](https://github.com/amzn/selling-partner-api-docs/files/6642811/amazon-product-request.txt)

This is the error response -
`<?xml version="1.0" encoding="UTF-8"?> <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd"> <Header> <DocumentVersion>1.02</DocumentVersion> <MerchantIdentifier>A3VBYO68OZ4LBR</MerchantIdentifier> </Header> <MessageType>ProcessingReport</MessageType> <Message> <MessageID>1</MessageID> <ProcessingReport> <DocumentTransactionID>194447018790</DocumentTransactionID> <StatusCode>Complete</StatusCode> <ProcessingSummary> <MessagesProcessed>0</MessagesProcessed> <MessagesSuccessful>0</MessagesSuccessful> <MessagesWithError>1</MessagesWithError> <MessagesWithWarning>0</MessagesWithWarning> </ProcessingSummary> <Result> <MessageID>0</MessageID> <ResultCode>Error</ResultCode> <ResultMessageCode>5001</ResultMessageCode> <ResultDescription>XML Parsing Fatal Error at Line 27, Column 1: Content is not allowed in trailing section. Content is not allowed in trailing section.</ResultDescription> </Result> </ProcessingReport> </Message> </AmazonEnvelope>`

**Comment by ZofD** [comment]
Hello

I checked your file and i see 26 lines, soo... there must be something wrong with encoding.

If you encode on your own, check or paste here your code - maybe on end of the file is null (that's what I had) or some other unsupported character.

**Comment by aniruddhaad** [comment]
I converted encoding to UTF-8 using notepad++ (it was already converted using php script using mb_convert but just to make sure.). 
Also opened file in editplus and used Hex Viewer to make sure there is nothing after last tag.
Also the same feed works with MWS without manually converting anything.  As this is working in production and same item was already live on amazon.
And moreover I opened XML file in VIM deleted last tag and typed it by hand again and saved it. 
However I am still getting the same error.

**Comment by aniruddhaad** [comment]
> Hello
> 
> I checked your file and i see 26 lines, soo... there must be something wrong with encoding.
> 
> If you encode on your own, check or paste here your code - maybe on end of the file is null (that's what I had) or some other unsupported character.

I converted encoding to UTF-8 using notepad++ (it was already converted using php script using mb_convert but just to make sure.).
Also opened file in editplus and used Hex Viewer to make sure there is nothing after last tag.
Also the same feed works with MWS without manually converting anything. As this is working in production and same item was already live on amazon.
And moreover I opened XML file in VIM deleted last tag and typed it by hand again and saved it.
However I am still getting the same error.

**Comment by ZofD** [comment]
In my case, the situation was similar and I wasted a lot of time on it. But I was looking in the wrong place. I discovered that the problem is with the encrypted version of the file you are sending to Amazon, not plain XML. There was a null value at the end of the file. I tried to find out what was wrong in my code, but that was a months ago and I don't remember what exactly was wrong, but probably it was in openssl_encrypt(). This link may be helpfull https://github.com/double-break/spapi-php/blob/master/src/Helper/Feeder.php

**Comment by aniruddhaad** [comment]
> In my case, the situation was similar and I wasted a lot of time on it. But I was looking in the wrong place. I discovered that the problem is with the encrypted version of the file you are sending to Amazon, not plain XML. There was a null value at the end of the file. I tried to find out what was wrong in my code, but that was a months ago and I don't remember what exactly was wrong, but probably it was in openssl_encrypt(). This link may be helpfull https://github.com/double-break/spapi-php/blob/master/src/Helper/Feeder.php

Thanks for the information.

Well, I am using https://github.com/double-break library only. So it must be latest & I should not have this problem in that case.
I should probably try to create a new issue on their library on github.

**Comment by aniruddhaad** [comment]
No progress on this. Still getting same error. Nothing really helped.

**Comment by aniruddhaad** [comment]
Finally I found the bug.
https://github.com/double-break/spapi-php/blob/master/src/ASECryptoStream.php
public static function encrypt(string $plainText, string $key, string $iv): string
replace line (line number 71) -
$plainText = static::getPaddedText($plainText);
with
$plainText = trim(static::getPaddedText($plainText));
and it started working!

**Comment by gala06195** [comment]
Hi, did you ever solved this, I have the same error https://stackoverflow.com/questions/77436186/laravel-xml-parsing-fatal-error-at-line-1-column-1-content-is-not-allowed-in

**Comment by aniruddhaad** [comment]
As I mentioned earlier you need to trim the spaces. If there are spaces then I think the signature doesn't match and request fails.
Try to trim your request XML.
