### ISSUE TITLE
[BUG] Order API responses are incomplete

### ISSUE THREAD

**Issue by joseph74a** [amzn/selling-partner-api-docs#879]
The Order API responses are incomplete!:

[https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md)

**OrderBuyerInfo**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderbuyerinfo](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderbuyerinfo)
![Cattura02](https://user-images.githubusercontent.com/31155146/121818262-56455380-cc86-11eb-8a8e-90c59a90c7e2.PNG)

**Address**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#address](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#address)
![Cattura03](https://user-images.githubusercontent.com/31155146/121818287-7ecd4d80-cc86-11eb-98a9-cc3050b1ca14.PNG)

**OrderItem**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderitem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderitem)
![Cattura01](https://user-images.githubusercontent.com/31155146/121818307-a58b8400-cc86-11eb-84d8-cd7ea38582cb.PNG)

**OrderItemBuyerInfo**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderitembuyerinfo](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#orderitembuyerinfo)
![Cattura04](https://user-images.githubusercontent.com/31155146/121818355-ff8c4980-cc86-11eb-8395-1224f301985a.PNG)

What is happening?

Thanks

**Comment by marconline** [comment]
Welcome to the incredible SP-API, where nothing is working and no support is provided.
The funny thing is that, at least we, have a working MWS application, with PII access allowed and we called SP-API Order endpoint with a normal access token and a RDT one, but nothing changes, same responses as yours.
And we are in the mid of June.

**Comment by parvathm** [comment]
Hi @joseph74a,

Can you please share your case id for this issue here , we will check your application id to see if it has right roles to provide PII data and also debug our logs to see if there is any issue on our side if you already have required roles. 

Thanks,
Parvathm,
Selling Partner API developer Support.

**Comment by joseph74a** [comment]
> Hi @joseph74a,
> 
> Can you please share your case id for this issue here , we will check your application id to see if it has right roles to provide PII data and also debug our logs to see if there is any issue on our side if you already have required roles.
> 
> Thanks,
> Parvathm,
> Selling Partner API developer Support.

Case ID: 7100916832
thanks

**Comment by ohabash** [comment]
I am also missing data... Are there any reasons why?

**Comment by marconline** [comment]
@ohabash that's a good question without any answer yet by Amazon.
