### ISSUE TITLE
Quering catalog item by SellerSKU or UPC doesn't work

### ISSUE THREAD

**Issue by teb02** [amzn/selling-partner-api-docs#88]
Let's say our UPC is "XXXX" (I hide it because I don't want to disclose UPC of our seller)

1. When I do:
GET sellingpartnerapi-eu.amazon.com/catalog/v0/items
MarketplaceId=A13V1IB3VIYZZH&**Query=XXXX**

We get the correct results, details of request:
x-amzn-RequestId: 2dd2bb28-5003-411a-b6e9-2e3da218fc3b
Date: Sun, 01 Nov 2020 16:00:58 GMT

2. When I do (same UPC):
GET sellingpartnerapi-eu.amazon.com/catalog/v0/items
MarketplaceId=A13V1IB3VIYZZH&**UPC=XXXX**

I get empty results, details of request:
x-amzn-RequestId: 309d5570-c21b-43be-bdbe-d624964d7cfc
Date: Sun, 01 Nov 2020 16:08:56 GMT

3. When I do request for real seller's SKU, I also get empty results:
GET sellingpartnerapi-eu.amazon.com/catalog/v0/items
MarketplaceId=A13V1IB3VIYZZH&**SellerSKU=YYYY**

x-amzn-RequestId: 311e53c8-eebc-48f0-b4e8-e10dae2ccfe2
Date: Sun, 01 Nov 2020 16:23:53 GMT

**Comment by parvathm** [comment]
Hi,

Thank you for the update. We are looking into this issue and provide an update asap.

Thanks,
Parvathm, 
Amazon MWS Support.

**Comment by vdanyliv** [comment]
@parvathm is there any news regarding this issue?

**Comment by parvathm** [comment]
> 
> 
> @parvathm is there any news regarding this issue?

Hi @vdanyliv ,

We have fixed the issue and deployed the changes. Can you please try now and open a support case with details if you are still receiving empty results.

Thanks,
Parvathm,
Selling Partner API Developer support.
