### ISSUE TITLE
Which path in RDT for createReport of type SC_VAT_TAX_REPORT

### ISSUE THREAD

**Issue by JayChandler** [amzn/selling-partner-api-docs#883]
It seems **SC_VAT_TAX_REPORT** is a restricted report. Which path to use for the restricted resource? I tried this

```
            var rdt = new CreateRestrictedDataTokenRequest();
            var restrictedResource = new RestrictedResource();
            restrictedResource.setMethod(RestrictedResource.MethodEnum.POST);
            restrictedResource.setPath("/reports/2021-06-30/reports");
            rdt.addRestrictedResourcesItem(restrictedResource);
            var token = tokensApi.createRestrictedDataToken(rdt);
```
but it ends up in an exception saying

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid or unsupported document ID found",
      "details": ""
    }
  ]
}
```

**Comment by iamtaojie** [comment]
@JayChandler Have you solved it ?  I have the same problem .

**Comment by JayChandler** [comment]
In order to call createReport you need need extended roles which need to be requested in your developer profile

![image](https://user-images.githubusercontent.com/6359575/122884428-720fc000-d33e-11eb-93e6-7eea361a10b5.png)

**Comment by DawidWawrzyniak** [comment]
Instead of:
` restrictedResource.setPath("/reports/2021-06-30/reports");`
try with:
` restrictedResource.setPath("/reports/{2020-09-04 or 2021-06-30}/documents/{reportDocumentId like amzn1.spdoc.1.3.d3277b35}");`
