### ISSUE TITLE
createReport- Access to requested resource is denied

### ISSUE THREAD

**Issue by JayChandler** [amzn/selling-partner-api-docs#884]
I want to create a report of type **SC_VAT_TAX_REPORT** but i am always getting 

```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}
```

I can make calls to other API successfullly so authorization is set up correctly. I have also checked all scopes on the application and recreated the refresh token. I am using API version **2020-09-04**

This is my code

```
 var createReportSpecification = new CreateReportSpecification();
            createReportSpecification.setDataStartTime(org.threeten.bp.OffsetDateTime
                .now()
                .minusDays(7));
            createReportSpecification.setDataEndTime(org.threeten.bp.OffsetDateTime
                .now()
                .minusDays(4));
            createReportSpecification.setReportType("SC_VAT_TAX_REPORT");
            createReportSpecification.setMarketplaceIds(List.of("A1PA6795UKMFR9"));

var reportResponse = reportsApi.createReport(createReportSpecification);
```

**Comment by JayChandler** [comment]
![RequiredRoles](https://user-images.githubusercontent.com/6359575/122178107-93783400-ce86-11eb-9fb5-28cbf884754d.png)

For all who are struggeling with the same problem. According to Amazon Support you need this extended role!

**Comment by zoborg** [comment]
Hey @JayChandler,

We are experiencing the same issue - I don't see those extra roles, had you applied for PII access too?

Regards
