### ISSUE TITLE
2020-12-01 and v0  what is the difference 

### ISSUE THREAD

**Issue by andanyoung** [amzn/selling-partner-api-docs#886]
2020-12-01 and v0 what is the difference ?
Give me a minute, Thinks !

**Comment by chapmanjw** [comment]
The 2020-12-01 version of the Catalog Item APIs are replacements for the corresponding V0 operations. It was recently announced that the V0 operations will be deprecated: #1041. Please consider the 2020-12-01 version for your use-cases. If there are specific data requirements preventing the 2020-12-01 version from fulfilling your use-cases, please contact us to discuss the use-case prior to the deprecation of V0: https://sellercentral.amazon.com/gp/mws/contactus.html. Thanks!
