### ISSUE TITLE
I can't find the UpdateReportAcknowledgements

### ISSUE THREAD

**Issue by iamtaojie** [amzn/selling-partner-api-docs#889]
Hi all,

I can't find the UpdateReportAcknowledgements in the sp-api !

Can you tell me how to change the Report Acknowledged like the UpdateReportAcknowledgements

Best regards,
T

**Comment by hcarsten** [comment]
so what was / is the solution here, how we can mark a report as processed or downloaded. What happens to reports that are created or scheduled but could not be downloaded in time ?

**Comment by getvicky83** [comment]
did u find any alternate solution for this?
