### ISSUE TITLE
Missing Access Token Error when Access Token Is Included in the Request

### ISSUE THREAD

**Issue by alex-lehan-bloom** [amzn/selling-partner-api-docs#89]
I'm attempting to access the Selling Partner API sandbox (https://sandbox.sellingpartnerapi-na.amazon.com) but keep getting a 403. Nothing is returned in the response body, but in one of the response headers it says:

```JavaScript
x-amzn-errortype | MissingAuthenticationTokenException

````
However, I don't understand this error since I have included the access token. At least, I believe I've included it correctly, as according to the documentation it says to include the access token inside of the x-amz-access-token header. 

Does anyone know why this would be happening?

**For more context:**

I am fairly confident my IAM User / Application setup is correct as I've been able to use the Refresh Token I get, when I Self-Authorize my application, to get an access_token from the LWA endpoint (https://api.amazon.com/auth/o2/token). (see #79).

Here is my request:

```JavaScript
  await fetch(
      "https://sandbox.sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries",
      {
        method: "GET",
        headers: {
          host: "sandbox.sellingpartnerapi-na.amazon.com",
          "x-amz-access-token": <access-token>,
          "x-amz-date": new Date().toISOString(),
          "user-agent": "Cross Border Bank/1.0 (Language=JavaScript)",
          Authorization: `AWS4-HMAC-SHA256 Credential=<iamuser-credential>/us-east-1/execute-api/aws4_request, SignedHeaders=${signedHeaders}, Signature=${signature}`,
        },
      }
    );
````

I've included the 4 signing steps I did based on this documentation:

https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

**Does anything look incorrect? And if not, can someone share their signing steps if it's not too much trouble?** 

```Javascript
 const access_token =
      "Atza|IwEXAMPLE";
    const date = "20201102T090000Z";
    // Signing Step 1
    const http = "GET";
    const uri = "/fba/inventory/v1/summaries";
    const queryString = "";
    const headers = `host:sandbox.sellingpartnerapi-na.amazon.com\nuser-agent:Cross Border Bank/1.0 (Language=JavaScript)\nx-amz-access-token:${access_token}\nx-amz-date:${date}`;
    const signedHeaders = "host;user-agent;x-amz-access-token;x-amz-date";
    const signedPayload = hash.sha256().update("").digest("hex");
    const canonicalRequest =
      http +
      "\n" +
      uri +
      "\n" +
      queryString +
      "\n" +
      headers +
      "\n" +
      signedHeaders +
      "\n" +
      signedPayload;
    const hashOfCanonicalRequest = hash
      .sha256()
      .update(canonicalRequest)
      .digest("hex");

    // Signing. Step 2.
    const algoDestination = "AWS4-HMAC-SHA256\n";
    const dateForSigning = `${date}\n`;
    const scope = "20201102/us-east-1/execute-api/aws4_request\n";
    const stringToSign =
      algoDestination + dateForSigning + scope + hashOfCanonicalRequest;

    // Signing. Step 3.
    const kSecret = "<secret-key-for-iam-user-creating-during-selling-partner-steps";

    const kDate = hash
      .sha256()
      .update("AWS4" + kSecret, "20201102")
      .digest("hex");
    const kRegion = hash.sha256().update(kDate, "us-east-1").digest("hex");
    const kService = hash.sha256().update(kRegion, "execute-api").digest("hex");
    const kSigning = hash
      .sha256()
      .update(kService, "aws4_request")
      .digest("hex");

    // Signing. Step 4.
    const signature = hash
      .sha256()
      .update(kSigning, stringToSign)
      .digest("hex");


```

**Comment by dsokolowski** [comment]
I had similar issue and it was because my http client did modify header keys like I put acccess-token and Access-Token was sent. According to some RFC header keys should be case-insensitive but apparently amazon did it other way.

**Comment by alex-lehan-bloom** [comment]
@dsokolowski , I think you're on to something here or at least it's something similiar. 

I'm using fetch in my http://localhost from a React app. I'm just doing this for testing, but perhaps this has to be moved to my backend. I noticed that on the first request, the x-amz-access-token is stripped from the request.

**Comment by charliecode** [comment]
@alex-lehan-bloom I'm going to assume you're using javascript or typescript since you mention React? If so, are you creating your own client code or are you using generated code from swagger-codegen or openapi-generator? Seems to me you're creating your own code. You're correct, I would not recommend handling any of this on your front end, especially since that would leave your refresh_token, accessKeyId and secretAccessKey open to the world. If you're open to using the backend and Typescript I would suggest using the [openapi-generator cli](https://openapi-generator.tech/docs/installation/) and use the [typescript-node generator](https://openapi-generator.tech/docs/generators/typescript-node). Once you have that setup I can point you in the right direction to get up and going as I already have a fully functional setup. This will take way less time than figuring out what you're currently doing wrong and all the access token logic and signing can be setup in a single function which can be connected into the interceptor of the already generated code. Lots of the heavy lifting will already be done, you won't need to worry about building out logic for the aws4 signature and you'll be loving life.

**Comment by alex-lehan-bloom** [comment]
@charliecode , you strike again! Amazing! 

I'll do just as you suggest. If I can avoid doing the signing logic myself, that would be too good to be true.

I have another task I need to complete, but I will be back on this hopefully early next week. I will report back as soon as I'm set up.

**Comment by ShivikaK** [comment]
Hi @alex-lehan-bloom , 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support
