### ISSUE TITLE
What scopes are required for FBA reports?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#890]
What permissions level (scopes) are required for these reports?

I am able to request many report types, but for some reason, all of the FBA ones produce the `Unauthorized` error:

```json
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to the resource is forbidden",
            "details": ""
        }
    ]
}
```

---

All of these reports fail:

```
GET_LEDGER_SUMMARY_VIEW_DATA
GET_LEDGER_DETAIL_VIEW_DATA
GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA
GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA
GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA
GET_RESERVED_INVENTORY_DATA
GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA
GET_FBA_STORAGE_FEE_CHARGES_DATA
```

---

We have the following scopes turned on and granted by the user:

- Finance and Accounting
- Selling Partner Insights
- Inventory and Order Tracking

Should this be enough?

**Comment by diogofacin** [comment]
@moltar I keep getting the same, any success on this issue?

**Comment by moltar** [comment]
Yes, you need to have "Amazon Fulfilment" scope enabled. Then you'll need to re-auth also (get a new token).

![Uploading screenshot-20210824T145206-95h2SpA1.png…]()
