### ISSUE TITLE
SP-API FulfillmentOutbound - createFulfillmentOrder - InvalidInput - Missing value for decimal type

### ISSUE THREAD

**Issue by nrojivadiyanetclues** [amzn/selling-partner-api-docs#891]
**I want help to find out issue.**

$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\FbaOutboundApi($config);

$QuantityObj = new \ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\Quantity();
$QuantityObj->offsetSet(null, 1);

$DecimalObj = new \ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\Decimal();
$DecimalObj->offsetSet(null, 19.98);

$MoneyObj = new \ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\Money(['currency_code' => 'USD', 'value' => $DecimalObj]);

$AddressObj = new \ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\Address(
    'name' => 'XYZ',
    'address_line1' => 'XYZ',
    'address_line2' => 'XYZ',
    'city' => 'XYZ',
    'state_or_region' => 'XYZ'
    'postal_code' => 'XYZ',
    'country_code' => 'US',
);

$ItemObj = new \ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\CreateFulfillmentOrderItem([
    'seller_sku' => 'XXX',
    'seller_fulfillment_order_item_id' => 'XXX',
    'quantity' => $QuantityObj,
    'per_unit_declared_value' => $MoneyObj,
]);

$FulfillmentOrder = [];
$FulfillmentOrder['seller_fulfillment_order_id'] = 'XXX';
$FulfillmentOrder['displayable_order_id'] = 'XXX';
$FulfillmentOrder['displayable_order_comment'] = 'Free Product';
$FulfillmentOrder['displayable_order_date'] = 'ISOString';
$FulfillmentOrder['destination_address'] = $AddressObj;
$FulfillmentOrder['items'] = $ItemObj;

$CreateFulfillmentOrderRequest = new \ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\CreateFulfillmentOrderRequest($FulfillmentOrder);
$CreateFulfillmentOrderRequest->setShippingSpeedCategory('Standard');

$createFulfillmentOrder = $apiInstance->createFulfillmentOrder($CreateFulfillmentOrderRequest);

**Comment by Sgroove** [comment]
I'm having the same issue here. Does anyone know how to fix this?

**Comment by DIGIWEBFR** [comment]
Hi,
I have a problem while using the API: CreateFulfillmentOrderRequest.

Example :

  $AddressObj = new Address();
        $AddressObj->setName('TITI');
        $AddressObj->setAddressLine1('Strettetet WWW');
        $AddressObj->setCity('GGG TTUTU');
        $AddressObj->setPostalCode('75000');
        $AddressObj->setStateOrRegion('PARIS');
        $AddressObj->setDistrictOrCounty('PARIS');
        $AddressObj->setCountryCode('FR');

        $oElt = new CreateFulfillmentOrderItem();
        $oElt->setSellerSku('20114456456');
        $oElt->setQuantity(1);
        $oElt->setSellerFulfillmentOrderItemId('20114456456-1');

        $CreateFulfillmentOrderRequest = new CreateFulfillmentOrderRequest();
        $CreateFulfillmentOrderRequest->setSellerFulfillmentOrderId('CDC0155416516465');
        $CreateFulfillmentOrderRequest->setDisplayableOrderId('CDC0155416516465');
        $CreateFulfillmentOrderRequest->setDisplayableOrderComment('Orders F');
        $CreateFulfillmentOrderRequest->setDisplayableOrderDate('2022-01-12T12:46:45.809Z');
        $CreateFulfillmentOrderRequest->setItems([$oElt]);
        $CreateFulfillmentOrderRequest->setDestinationAddress($AddressObj);

        $CreateFulfillmentOrderRequest->setShippingSpeedCategory('Standard');
        $CreateFulfillmentOrderRequest->setMarketplaceId('sdfqjsdnfjkqnsd);
 
        $apiInstance = $this->amazonInstanceApi();
        $createFulfillmentOrder = $apiInstance->createFulfillmentOrder($CreateFulfillmentOrderRequest);
        
        === BODY====
        
 ^ ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\CreateFulfillmentOrderRequest^ {#971
  #container: array:15 [
    "marketplace_id" => "XXXXX"
    "seller_fulfillment_order_id" => "CDC0155416516465"
    "displayable_order_id" => "CDC0155416516465"
    "displayable_order_date" => "2022-01-12T12:46:45.809Z"
    "displayable_order_comment" => "Orders F"
    "shipping_speed_category" => "Standard"
    "delivery_window" => null
    "destination_address" => ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\Address^ {#972
      #container: array:10 [
        "name" => "XXXX"
        "address_line1" => "XXXXX"
        "address_line2" => null
        "address_line3" => null
        "city" => "XXXX"
        "district_or_county" => "XXX"
        "state_or_region" => "XXX"
        "postal_code" => "75000"
        "country_code" => "FR"
        "phone" => null
      ]
    }
    "fulfillment_action" => null
    "fulfillment_policy" => null
    "cod_settings" => null
    "ship_from_country_code" => null
    "notification_emails" => null
    "feature_constraints" => null
    "items" => array:1 [
      0 => ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentOutbound\CreateFulfillmentOrderItem^ {#991
        #container: array:9 [
          "seller_sku" => "201120114221"
          "seller_fulfillment_order_item_id" => "201120114221-1"
          "quantity" => 1
          "gift_message" => null
          "displayable_comment" => null
          "fulfillment_network_sku" => null
          "per_unit_declared_value" => null
          "per_unit_price" => null
          "per_unit_tax" => null
        ]
      }
    ]
  ]
}


ERROR :
=>  [ERROR] [400] Client error: `POST
         https://sandbox.sellingpartnerapi-eu.amazon.com/fba/outbound/2020-07-01/fulfillmentOrders` resulted in a `400
         Bad Request` response:
[{"code":"InvalidInput","message":"Could not match input arguments"}]
