### ISSUE TITLE
CatalogItems have different parameters

### ISSUE THREAD

**Issue by deepaktech94** [amzn/selling-partner-api-docs#893]
Catalog Item API have two version 

- V0 
- 2020-12-01

But both version have different parameters ,rate and burst.

https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#listcatalogitems

https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#searchcatalogitems

Which version we need to consider ?

**Comment by chapmanjw** [comment]
It was recently announced that the V0 SearchCatalogItems operation will be deprecated: https://github.com/amzn/selling-partner-api-docs/discussions/1041. Please consider the 2020-12-01 version for your use-cases. If there are specific data requirements preventing the 2020-12-01 version from fulfilling your use-cases, please contact us to discuss the use-case prior to the deprecation of V0: https://sellercentral.amazon.com/gp/mws/contactus.html. Thanks!
