### ISSUE TITLE
Sandbox Mode: Access to requested resource is denied - Authorization Api

### ISSUE THREAD

**Issue by ytcitsupport-jlin** [amzn/selling-partner-api-docs#894]
I have test order and feeds endpoint of sandbox mode, 
But I was denied by authorization endpoint. 
Do I need more setting to try authorization api?

**Comment by srsole** [comment]
Believe it or not, Amazon, a gigantic international company, does not have a sandbox.
They offer you some static files with test responses. Come on, they are useless.
