### ISSUE TITLE
Is it possible to convert ASIN to UPC using sp-api?

### ISSUE THREAD

**Issue by DarkwaveMD** [amzn/selling-partner-api-docs#895]
As I remember such feature was available in MWS API

**Comment by chapmanjw** [comment]
The `getCatalogItem` operation with the `identifiers` requested in the `includedData` parameter will return the product identifiers for a given ASIN: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md
