### ISSUE TITLE
Not receiving notifications for FBA_OUTBOUND_SHIPMENT_STATUS

### ISSUE THREAD

**Issue by fullpipe** [amzn/selling-partner-api-docs#896]
I created Destination to SQS with destinationId 4a622372-****-****-****-*******
https://github.com/amzn/selling-partner-api-docs/blob/548d815eb32c899aa4b7520c49baee008f3687e3/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#step-1-create-a-destination

Then I create subscription to destinationId
https://github.com/amzn/selling-partner-api-docs/blob/548d815eb32c899aa4b7520c49baee008f3687e3/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#step-3-create-a-subscription
for notificationType FBA_OUTBOUND_SHIPMENT_STATUS
subscriptionId 281e0a54-****-****-****-*********

The problem is that I don't receive any FBA_OUTBOUND_SHIPMENT_STATUS messages.
We tried the same with FULFILLMENT_ORDER_STATUS type, everything is ok.

What I do wrong? Maybe we need to bump something permissions up?

**Comment by GenderAPI** [comment]
i have the same plroblem
i can create destination
i can create subscriptions to destination
for all nottification types

but i can not recive any messages

when i check the Monitors on AWS SQS fifo
Number Of Empty Receives always : 30

i do not understand i thing messages comes but they are empty?

**Comment by GenderAPI** [comment]
i fix it. mine was access pollicy
the problem may cause with your Access Policy
can you share your access policy

**Comment by fullpipe** [comment]
@GenderAPI glad to hear!
My Access Policy:
```json
{
  "Version": "2012-10-17",
  "Id": "Policy152237620",
  "Statement": [
    {
      "Sid": "Stmt162252273647",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
      },
      "Action": [
        "sqs:GetQueueAttributes",
        "sqs:SendMessage"
      ],
      "Resource": "arn:aws:sqs:us-west-2:***:****"
    },
    {
      "Sid": "Stmt161366956212313",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::****:root"
      },
      "Action": "sqs:*",
      "Resource": "arn:aws:sqs:us-west-2:***:****"
    }
  ]
}
```

**Comment by GenderAPI** [comment]
use below just change Your_SQS_ARN

{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "__sender_statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::437568002678:root"
      },
      "Action": [
        "SQS:SendMessage",
        "SQS:GetQueueAttributes"
      ],
      "Resource": "**Your_SQS_ARN**"
    }
  ]
}
