### ISSUE TITLE
I am sad.

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-docs#899]
I am sad. Why there lots of inconsistent data when using the SAPI -API? Example the orders. I already created a report in seller support but until now no response. Now Another inconsistent api response , the Shipping chargeback. I compare the same report in MWS , its not same.

**Comment by johnkw** [comment]
I am sad this github Issues list is so cluttered with tickets that are not actionable bug reports.

**Comment by joseph74a** [comment]
> I am sad this github Issues list is so cluttered with tickets that are not actionable bug reports.

This is a bug ... a real bug!: [https://github.com/amzn/selling-partner-api-docs/issues/879](url)

**Comment by johnkw** [comment]
Agreed that does look like a real bug.  You should post the full (redacted) HTTP request/response though to make it more obvious what's going on.

**Comment by PrashantMalaviya** [comment]
hello sir @ianrussel ,
can you see the #912 issue and any solution????

**Comment by gmathew127** [comment]
Same, we are not even able to get developer account after waiting for a month. So much pressure from our upper management on why we are waiting for a month now.

**Comment by jchavest13** [comment]
Hi @gmathew127,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by johnkw** [comment]
lol @ this being turned into a "Developer Registration" bug.

**Comment by jchavest13** [comment]
Hi @gmathew127,

Please referred to Issue #933 to follow up with your concern.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by johnkw** [comment]
As long as this github bug has degenerated into a bunch of random conversation, I'd like to make an actual request of Amazon:

Stop using github bugs to make announcements.  See for example @jenilew in bug #945 - this should not have been created as a bug.  Instead it should be a Github Announcement.  Github supports this feature natively.  Go to "Settings" on the /amzn/selling-partner-api-docs repository and scroll down to "Discussions" and click set up.

If you want, you can disable everything except for Announcements.

If you make announcements in the Announcements, then users can actually subscribe in github and get notifications of the announcements.
