### ISSUE TITLE
[BUG] Slow response and internal server error

### ISSUE THREAD

**Issue by GenderAPI** [amzn/selling-partner-api-docs#900]
Amazon API server response is very slow 
and i mostly get below error

{'errors': [{'message': 'We encountered an internal error. Please try again.', 'code': 'InternalFailure'}]}

is there any guys same error?

**Comment by etsourcing2** [comment]
We got API no response issue as well......

**Comment by arvin915** [comment]
We also encountered the same problem, get bellow error:
Response code: 500

{
  "errors": [
    {
      "message": "We encountered an internal error. Please try again.",
     "code": "InternalFailure"
    }
  ]
}

**Comment by GenderAPI** [comment]
is there any announcement from Amazon or from Amazon developers.

**Comment by moltar** [comment]
Same!!!

**Comment by foxfiring** [comment]
Same!!!

**Comment by smileLuckBoy** [comment]
找到组织了

**Comment by arvin915** [comment]
> Amazon API server response is very slow
> and i mostly get below error
> 
> {'errors': [{'message': 'We encountered an internal error. Please try again.', 'code': 'InternalFailure'}]}
> 
> is there any guys same error?

It seems to be back to normal.
