### ISSUE TITLE
[BUG] Authorization failed

### ISSUE THREAD

**Issue by fanmf** [amzn/selling-partner-api-docs#901]
The following error is displayed on the page when authorizing，and why the icon of the App in Marketplace Appstore is a lock?

You’re not permitted to take this action.

You must be the primary user of a Professional selling account to take advantage of apps. If you are the primary user, you may upgrade your plan. Click here to upgrade your plan

app id: amzn1.sp.solution.9cf9bdd6-ada1-4670-aedf-66e02c0b460c

**Comment by GenderAPI** [comment]
if you are the sub user of the account you need to get user permission from account owner

Tell your account owner to do as bellow

Settings->User Permissions->Performance->Marketplace Appstore (set it View&Edit)

**Comment by fanmf** [comment]
It's the primary account. authorizing other accounts has the same result. Is it related to the status of my app? Is it locked?

**Comment by GenderAPI** [comment]
i am sub user and i try to connect your application with success result. i think it is related with your seller account

**Comment by fanmf** [comment]
With this guide
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

Marketplace Appstore authorization workflow

- Step 1. The selling partner initiates authorization from the Marketplace Appstore
- Step 2. The selling partner consents to authorize your application
- Step 3. The selling partner signs into your website

in Step 3, when I connect the edited link, the following exception occurs

You’re not permitted to take this action.

You must be the primary user of a Professional selling account to take advantage of apps. If you are the primary user, you may upgrade your plan. Click here to upgrade your plan

**Comment by GenderAPI** [comment]
below link works good for me
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.9cf9bdd6-ada1-4670-aedf-66e02c0b460c


this is your application authorization link

**Comment by fanmf** [comment]
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.9cf9bdd6-ada1-4670-aedf-66e02c0b460c
this link is in Step 1. it is Ok.
but in Step 3. I need a link like 
https://sellercentral-japan.amazon.com/apps/authorize/confirm/amzn1.sp.solution.9cf9bdd6-ada1-4670-aedf-66e02c0b460c?redirect_uri=https%3A%2F%2Ferp.yidakj.net&state=XX&amazon_state=XXXX

The exception occurred in Step 3.

**Comment by fanmf** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-the-selling-partner-signs-into-your-website

Do the values of amazon_state and state need to be reversed？

**Comment by fanmf** [comment]
I see, my redirect_uri is inconsistent with the configuration.

**Comment by robinchen123** [comment]
It's better to add Marketplace Appstore permission explanation in Seller Central Help Center. 

Also it's better to add explanation about what permission in Seller central we need for SP API authorization.
