### ISSUE TITLE
I'm very confused

### ISSUE THREAD

**Issue by aluka8023** [amzn/selling-partner-api-docs#902]
I'm very confused why there is no structure description for the [putListingsItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md#putlistingsitem) request parameter, and I don't know what kind of data to pass

 parameter: [ListingsItemPutRequest.attributes](https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md#listingsitemputrequest)

**Comment by michaelbagrov** [comment]
@aluka8023 did you managed to find ListingsItemPutRequest.attributes structure documented somewhere?

**Comment by chapmanjw** [comment]
You can find more details on how to use the Listings Items APIs in the use case guide: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md.

The structure and data requirements for the attributes are provided by the Product Type Definitions API: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/product-type-definitions-api-use-case-guide/definitions-product-types-api-use-case-guide_2020-09-01.md

The Product Type Definitions API provides JSON Schemas describing the listings attributes data for a given Amazon product type.
