### ISSUE TITLE
[BUG] MD9999 error 500 Interval server error on /apps/apis/cloudauth/oauth/applications/

### ISSUE THREAD

**Issue by GenderAPI** [amzn/selling-partner-api-docs#903]
Hi Amazon developers;
Our application is live; and our OAuth Login URI  and OAuth Redirect URI filed correct and they are same URLS.
I have only SP-API, i am not using MSW
most of our customers can connect the application with success
but there are much customers have MD9999 (500 interval server) error
there is 500 error on your side with MD9999
you can see detailed reports below

![Captain A support team - SS](https://user-images.githubusercontent.com/38208531/122415246-6dd75180-cf90-11eb-8b9b-43c7876a1f7d.png)

**video on connecting**
https://user-images.githubusercontent.com/38208531/122422142-96157f00-cf95-11eb-9c4c-5574eaf71ed4.mp4

**Below is detailed Request and Response parameters (i delete cookies and other things if needed i can send it in case)**

Request URL: https://sellercentral.amazon.co.uk/apps/apis/cloudauth/oauth/applications/amzn1.sellerapps.app........./oauthAuthorize?application_stage=published&amazon_state=MTYyMzkzNjYxNDIwN1vvv70t77-9JO-_vVnvv70i77-9aBxW77-9Oe-_ve-_vWNB77-9Xe-_vTBo77-9EO-_vQQ1dm_vv70wBu-_vTlf77-977-977-90ZLvv706I1_vv70yfFzvv73vv70Q0rPvv73vv704RO-_vQbvv70b&redirect_url=https%3A%2F%2F..........co%2Fapp&devId=........&devName=......
    Request Method: GET
Status Code: 500
Remote Address: 23.214.109.179:443
Referrer Policy: strict-origin-when-cross-origin
cache-control: no-cache, no-store, must-revalidate
content-encoding: gzip
content-type: text/html;charset=UTF-8
date: Thu, 17 Jun 2021 13:31:19 GMT
expires: 0
permissions-policy: interest-cohort=()
pragma: no-cache
server: Server
vary: accept-encoding,Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent
x-amz-rid: ............
x-content-type-options: nosniff
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-ua-compatible: IE=edge
x-xss-protection: 1
x-xss-protection: 1;
:authority: sellercentral.amazon.co.uk
:method: GET
    :path: /apps/apis/cloudauth/oauth/applications/amzn1.sellerapps.app................/oauthAuthorize?application_stage=published&amazon_state=MTYyMzkzNjYxNDIwN1vvv70t77-9JO-_vVnvv70i77-9aBxW77-9Oe-_ve-_vWNB77-9Xe-_vTBo77-9EO-_vQQ1dm_vv70wBu-_vTlf77-977-977-90ZLvv706I1_vv70yfFzvv73vv70Q0rPvv73vv704RO-_vQbvv70b&redirect_url=https%3A%2F%2F.........co%2Fapp&devId=.......&devName=......
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
content-type: application/json;charset=UTF-8
cookie: cookies deleted for the security
referer: https://sellercentral.amazon.co.uk/apps/authorize/confirm/amzn1.sellerapps.app..........?redirect_uri=https%3A%2F%2F........co%2Fapp&state=NjBiZWFjMDRhNWIxNjUwMzJhNjI2YzkyLWV1cm9wZQ%3D%3D&amazon_state=MTYyMzkzNjYxNDIwN1vvv70t77-9JO-_vVnvv70i77-9aBxW77-9Oe-_ve-_vWNB77-9Xe-_vTBo77-9EO-_vQQ1dm_vv70wBu-_vTlf77-977-977-90ZLvv706I1_vv70yfFzvv73vv70Q0rPvv73vv704RO-_vQbvv70b
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
x-requested-with: XMLHttpRequest
application_stage: published
amazon_state: MTYyMzkzNjYxNDIwN1vvv70t77-9JO-_vVnvv70i77-9aBxW77-9Oe-_ve-_vWNB77-9Xe-_vTBo77-9EO-_vQQ1dm_vv70wBu-_vTlf77-977-977-90ZLvv706I1_vv70yfFzvv73vv70Q0rPvv73vv704RO-_vQbvv70b
redirect_url: https%3A%2F%2F........co%2Fapp
devId: ..........
devName: ........

@rugved1991 
@parvathm

**Comment by ShivikaK** [comment]
Hello @GenderAPI 

Thank you for raising this issue.

Can you please provide me the OAuth authorization URL constructed to authorize the application so that we can investigate the issue further?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by GenderAPI** [comment]
Hi @ShivikaK ;
our authorization link is;
https://sellercentral.amazon.co.uk/apps/authorize/consent?application_id=amzn1.sellerapps.app.a164cd4d-6c5d-4b97-8c1d-b6b52b2e9a09&state=NjBkMTZlZjAwYTU2YTMyMzQzMTMwMTcyLWV1cm9wZQ==

and after accept all permissions the redirect url is;

https://sellercentral.amazon.co.uk/apps/apis/cloudauth/oauth/applications/amzn1.sellerapps.app.a164cd4d-6c5d-4b97-8c1d-b6b52b2e9a09/oauthAuthorize?application_stage=published&amazon_state=MTYyMzkzNjYxNDIwN1vvv70t77-9JO-_vVnvv70i77-9aBxW77-9Oe-_ve-_vWNB77-9Xe-_vTBo77-9EO-_vQQ1dm_vv70wBu-_vTlf77-977-977-90ZLvv706I1_vv70yfFzvv73vv70Q0rPvv73vv704RO-_vQbvv70b&redirect_url=https%3A%2F%2Fcaptaina.co%2Fapp&devId=575331142443&devName=CaptainA
