### ISSUE TITLE
[BUG] feeds feedType : POST_PRODUCT_DATA, XML OperationType: PartialUpdate has a bug

### ISSUE THREAD

**Issue by CKTara** [amzn/selling-partner-api-docs#907]
feed xml :
`<?xml version="1.0" encoding="UTF-8"?>
        <AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <Header>
                <DocumentVersion>1.01</DocumentVersion>
                <MerchantIdentifier>SuntekStore</MerchantIdentifier>
            </Header>
            <MessageType>Product</MessageType>
            <PurgeAndReplace>false</PurgeAndReplace>
                <Message>
                    <MessageID>1</MessageID>
                    <OperationType>PartialUpdate</OperationType>
                    <Product>
                        <SKU>5305566659787329</SKU>
                                <NumberOfItems>1</NumberOfItems>
                        <DescriptionData>
                            <Title><![CDATA[女性男性ギフト用スタンドホルダーバングルディスプレイオーガナイザーを見る - シルバーロッド]]></Title><Description><![CDATA[<p><b>説明:</b></p><p> - 個人用の時計スタンドホルダーまたは小売店のディスプレイカウンタートップ。<br> - 頑丈で安定した大理石、革製の時計ホルダークッション、シルバー/ゴールデンメタルのサポートロッド、革新的で高貴な贅沢、目を引く。<br> - あらゆるスタイルやブランドの時計にフィットする最も豪華な時計スタンドは、ジュエリーブレスレットやバングルの展示にも使用できます。<br> - 時計やジュエリーを使用しないときにテーブルに置いたままにするのではなく、整理して保管するためのエレで安全な場所。<br> - 住宅用または商業用。あなたのボーイフレンド、夫、父への素晴らしい贈り物。</p><p><b>仕様:</b></p><p> - 素材：大理石、金属、革</p><p><b>サイズチャート:</b></p><p>製品サイズ：10x10x16 cm /3.9x3.9x6.3インチ<br>テーブル枕：9.4x6.2x3.2 cm /3.7x2.4x1.3インチ</p><p><b>パッケージに含まれるもの:</b></p><p>1ピース大理石時計スタンド</p>]]></Description>
                            <BulletPoint><![CDATA[あらゆるスタイルやブランドの時計にフィットする最も豪華な時計スタンドは、ジュエリーブレスレットやバングルの展示にも使用できます。]]></BulletPoint>
                            <BulletPoint><![CDATA[住宅用または商業用。あなたのボーイフレンド、夫、父への素晴らしい贈り物。]]></BulletPoint>
                            <BulletPoint><![CDATA[個人用の時計スタンドホルダーまたは小売店のディスプレイカウンタートップ。]]></BulletPoint>
                            <BulletPoint><![CDATA[時計やジュエリーを使用しないときにテーブルに置いたままにするのではなく、整理して保管するためのエレで安全な場所。]]></BulletPoint>
                            <BulletPoint><![CDATA[頑丈で安定した大理石、革製の時計ホルダークッション、シルバー/ゴールデンメタルのサポートロッド、革新的で高貴な贅沢、目を引く。]]></BulletPoint>
                            <Manufacturer></Manufacturer>
                            <MfrPartNumber>05b8f3bdddc069191966581240633eaf</MfrPartNumber>
                            <SearchTerms><![CDATA[時計スタンドディスプレイ ジュエリーブレスレット用時計ホルダーディス 革と大理石の時計スタンドオーガナイザーホルダー イヤリングバングルショーケースディスプレイカウン]]></SearchTerms>
                            <TargetAudience>ユニセックス</TargetAudience>
                            <RecommendedBrowseNode>2504083051</RecommendedBrowseNode>
                       <IsExpirationDatedProduct><![CDATA[false]]></IsExpirationDatedProduct> 
			</DescriptionData>
                <ProductData>
                    <Jewelry><ProductType>
              		<FashionOther>
              			<VariationData>
                             <Parentage>child</Parentage> </VariationData>
                    </FashionOther>
                 </ProductType>
                    </Jewelry>
                </ProductData>
                                <IsHeatSensitive>0</IsHeatSensitive>
                    </Product>
                </Message>
        </AmazonEnvelope>`

return result xml : 
`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>A1BF6B6BPRBL60</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>54097018796</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>1</MessagesProcessed>
				<MessagesSuccessful>0</MessagesSuccessful>
				<MessagesWithError>1</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
			<Result>
				<MessageID>1</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>8560</ResultMessageCode>
				<ResultDescription>SKU 5305566659787329、 指定のない属性 brand。 SKU 5305566659787329はどのASINとも一致しません。新しいASINを作成する場合は、次の属性が必要になります: brand。 Feed ID: 0。 詳しくは、 http://sellercentral.amazon.co.jp/gp/errorcode/8560 を参照してください。</ResultDescription>
				<AdditionalInfo>
					<SKU>5305566659787329</SKU>
				</AdditionalInfo>
			</Result>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>`

PartialUpdate should allow brand to be empty

**Comment by CKTara** [comment]
No problem

**Comment by naocan12345** [comment]
I also have this problem, how did you solve it?
