### ISSUE TITLE
[FEATURE] Documentation FEED API Confusing

### ISSUE THREAD

**Issue by jhullparkseed** [amzn/selling-partner-api-docs#908]
I've had a confusing time trying to understand the new SPAPI. feeds API We currently are using the MWS which uses the Amazon envelope feed API to send our data up for specific feeds.

I've not found any good guides, tutorials, or examples on how to a fee process using the new selling partners API So what I'm asking is twofold, 1 a basic understanding are the steps required to send a feed to Amazon using the new rest API and two, can I use the objects in the Amazon envelope as part of the body.

What little I've been able to garner is that it looks like the steps involved are:

1 – Create a FeedDocument where the body is what? No good example
I understand this returns a document ID in the payload along with encryption stuff so I then
2 – Encrypt using what type of encryption?
3 – Then I perform a CreateFeed but when I look at the body specifications, when do I send up the data?

Name	Description	Schema
feedType
required	The feed type.	string
marketplaceIds
required	A list of identifiers for marketplaces that you want the feed to be applied to.	< string > array
inputFeedDocumentId
required	The document identifier returned by the createFeedDocument operation. Upload the feed document contents before calling the createFeed operation.	string
feedOptions
optional	Additional options to control the feed. These vary by feed type.	FeedOptions

4 - then decrypt the response.

What or when do I upload the feed document contents when I don’t see any parameter or API method to do that.

This is VERY confusing.

I've send a request to the developer support, but this should be made much more clear in the documentation.  You have no clear steps, you have a phrase "Upload the feed document before calling createfeed with no clear indication how that is done.  MWS did this in one call and while I may need to do multiple steps...

at the very least tell me specifically what they are and by the way, this link no longer exists:

 https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md#step-2-encrypt-and-upload-the-feed-data

**Comment by loshengf01** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide-2020-09-04.md

**Comment by vaidas-lungis** [comment]
But there is already exists [feeds_2021-06-30.json](https://github.com/amzn/selling-partner-api-models/blob/7c7d355dab8c4c490880ec0e527d20b813760022/models/feeds-api-model/feeds_2021-06-30.json) at [models/feeds-api-model](https://github.com/amzn/selling-partner-api-models/tree/7c7d355dab8c4c490880ec0e527d20b813760022/models/feeds-api-model) and specs does not have any encryption details :/ compared to the 2020-09-04 edition. Kinda confused right now.

**Comment by abuzuhri** [comment]
> I've had a confusing time trying to understand the new SPAPI. feeds API We currently are using the MWS which uses the Amazon envelope feed API to send our data up for specific feeds.
> 
> I've not found any good guides, tutorials, or examples on how to a fee process using the new selling partners API So what I'm asking is twofold, 1 a basic understanding are the steps required to send a feed to Amazon using the new rest API and two, can I use the objects in the Amazon envelope as part of the body.
> 
> What little I've been able to garner is that it looks like the steps involved are:
> 
> 1 – Create a FeedDocument where the body is what? No good example
> I understand this returns a document ID in the payload along with encryption stuff so I then
> 2 – Encrypt using what type of encryption?
> 3 – Then I perform a CreateFeed but when I look at the body specifications, when do I send up the data?
> 
> Name Description Schema
> feedType
> required The feed type. string
> marketplaceIds
> required A list of identifiers for marketplaces that you want the feed to be applied to. < string > array
> inputFeedDocumentId
> required The document identifier returned by the createFeedDocument operation. Upload the feed document contents before calling the createFeed operation. string
> feedOptions
> optional Additional options to control the feed. These vary by feed type. FeedOptions
> 
> 4 - then decrypt the response.
> 
> What or when do I upload the feed document contents when I don’t see any parameter or API method to do that.
> 
> This is VERY confusing.
> 
> I've send a request to the developer support, but this should be made much more clear in the documentation. You have no clear steps, you have a phrase "Upload the feed document before calling createfeed with no clear indication how that is done. MWS did this in one call and while I may need to do multiple steps...
> 
> at the very least tell me specifically what they are and by the way, this link no longer exists:
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md#step-2-encrypt-and-upload-the-feed-data

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by johnkw** [comment]
This ticket should be closed in favor of the new feeds API.
