### ISSUE TITLE
[BUG] GET_AFN_INVENTORY_DATA_BY_COUNTRY is available in US, CA, but not MX

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#911]
**Describe the bug**

Docs state:

> This report is only available to FBA sellers in Europe (EU).

In actuality it is available in US, CA, but not MX

**URL of the content on GitHub**

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#fulfillment-by-amazon-fba-reports

**Description of what the documentation currently says**

`GET_AFN_INVENTORY_DATA_BY_COUNTRY`

> This report is only available to FBA sellers in Europe (EU).

**Description of what the documentation should say**

Should list all marketplaces where this report is available.

**Screenshots**

![screenshot-20210619T201403-EaoPSdmT](https://user-images.githubusercontent.com/491247/122643613-e843d500-d13a-11eb-87d8-052313d57b20.png)

**Additional context**

I was able to retrieve this data personally for US and CA, but not MX.

For MX an error is thrown:

```
"errors": [
          {
            "code": "InvalidInput",
            "message": "Report rejected for this client. Some of the marketplaces are not allowed for this Report",
            "details": ""
          }
        ]
```

**Comment by moltar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by phstc** [comment]
@moltar did you get any progress on this? I'm getting the same issue for MX.
