### ISSUE TITLE
I got [Access to requested resource is denied] when I use getCatalogItem to get information from US

### ISSUE THREAD

**Issue by getstar** [amzn/selling-partner-api-docs#914]
I can get information from Japan(A1VC38T7YXB528) by getCatalogItem.
I can't get information from US(ATVPDKIKX0DER) by getCatalogItem.

But I got the email in which it said 
`Thank you for completing your Amazon Selling Partner API (SP-API) Developer Profile.
Your request for access to SP-API has been APPROVED.
You now have global Marketplace access to SP-API based on the roles you requested.
`

Does the "global Marketplace access" mean I can get information from US ?
thanks

**Comment by ShivikaK** [comment]
Hello @getstar 

Thank you for raising the issue.

To be able to have access to US account, you will need to authorize your application for the particular seller account based out in US. A SP API application is global in nature, but it still needs to be authorized by the sellers to get access to seller data via APIs.

Thanks,
Shivika Khare
Selling Partner API Developer Support
