### ISSUE TITLE
How do I get The variation theme's attributes

### ISSUE THREAD

**Issue by aluka8023** [amzn/selling-partner-api-docs#915]
When using the [product-type-definitions-api/getdefinitionsproducttype](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-type-definitions-api/definitionsProductTypes_2020-09-01.md#getdefinitionsproducttype) API to obtain the product type definitions, there is no theme's attributes under the variation theme in the variations section

response data：

```json
...
"variations":{
	"title":"Variations",
	"description":"Variations that product will use",
	"propertyNames":[
		"parentage_level",
		"variation_theme"
	]
}
...
```

schema data:

```json
...
"properties": {
    "name": {
        "title": "Variation Theme Name",
        "description": "Specify the variation theme that the product will use. The theme's attributes must be populated for all items in the grouping.",
        "editable": true,
        "hidden": false,
        "examples": [
          "Size/Color"
        ],
        "type": "string",
    }
}
...       
```

Mentioned above "The theme's attributes must be populated for all items in the grouping", but how do I get The theme's attributes？

**Comment by chapmanjw** [comment]
Are you asking how to get the valid values for `variation_theme` or something else?

**Comment by Emizy** [comment]
Sorry to jump on this trend

We have been trying to upload product using the listing feed endpoint ,After using get product type definitions which return a product schema(/definitions/2020-09-01/productTypes/{product_type}/} in which we use to to construct the attributes parameter in the request body but each time its always {'code': 'InvalidInput', 'message': 'Request has missing or invalid parameters and cannot be parsed.', 'details': ''}]


Supplied Product Request body

payload = {
    "productType": "PRODUCT",
    "requirements": "LISTING",
    "attributes": {
        "brand": [
            {"value": "Sony", "marketplace_id": "A2NODRKZP88ZB9", "language_tag": "sv_SE"}
        ],
        "bullet_point": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "Breathable leather lining"
            },
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "Breathable leather lining 2"
            },
        ],
        "color": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "Cranberry"
            }
        ],
        "country_of_origin": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "Sweden"
            }
        ],
        "item_name": [
            {
                "language_tag": "sv_SE",
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "Adidas Blue Sneakers"
            }
        ],
        "product_description": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "language_tag": "sv_SE",
                "value": "This summer, boots by Jette made from high quality suede leather are real gems. "
                         "They visually highlight the craftsmanship and fine leather braid positioned at the top of the shaft"
            }
        ],
        "recommended_browse_nodes": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "Diet Bars"
            }
        ],
        "supplier_declared_dg_hz_regulation": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "GHS"
            }
        ],
        "merchant_suggested_asin": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "B007KQBXN0"
            }
        ],
        "externally_assigned_product_identifier": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "type": "UPC",
                "value": "714532191586"
            }
        ],
        "skip_offer": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "True"
            }
        ],
        "fulfillment_availability": [{
            "fulfillment_channel_code": "AMAZON_NA",
            "is_inventory_available": "True",
            "lead_time_to_ship_max_days": "5",
            "quantity": "152",
            "restock_date": "5/5/20",
        }],
        "condition_type": [
            {
                "marketplace_id": "A2NODRKZP88ZB9",
                "value": "New"
            }
        ],
    }
}

request format
 response = self.aws.send_request(endpoint=self.endpoint,
                                             path=f'/listings/2020-09-01/items/{seller_partner_id}/{sku}/?marketplaceIds={marketplace_ids}&issueLocale={issue_locale}',
                                             method='PUT',
                                             host=self.host,
                                             region=self.region,
                                             body=json.dumps({'body': payload}))

Any help or correction on how to go about this

**Comment by chapmanjw** [comment]
@Emizy When I paste your payload into https://jsonformatter.org/, I get JSON parsing errors (some extra commas, extra quotes, etc.). The 400 BAD_REQUEST you are receiving is likely due to the invalid JSON format.
