### ISSUE TITLE
Is it feasible to get order buyer name by SP API ?

### ISSUE THREAD

**Issue by aaalison** [amzn/selling-partner-api-docs#916]
I want to get "Seller Central (US marketplace) > Order details (FBA order) > Ship to > Buyer name" by SP API.
![image](https://user-images.githubusercontent.com/86222908/122721516-586d6a80-d2a3-11eb-8b79-2eba03934e2b.png)

I found "OrderBuyerInfo > BuyerName" and "OrderAddress > Shipping Address > Name" in SP API documentation.
![image](https://user-images.githubusercontent.com/86222908/122721643-7d61dd80-d2a3-11eb-91a5-3cbfe7e04bb6.png)
![image](https://user-images.githubusercontent.com/86222908/122721704-910d4400-d2a3-11eb-8d83-4e24c2154374.png)

I noticed Amazon stricten customer privacy policy and I read issues saying SP API does not return above info.

So, 1. Is it feasible to get above info by SP API?
2. Do I need "Direct-to-Consumer Shipping" role to get above info?
3. Is there any other special conditions required?
![image](https://user-images.githubusercontent.com/86222908/122722823-c0708080-d2a4-11eb-83db-09f2b0c520a4.png)

**Comment by kingsun-he** [comment]
Hi aaalison， Do you get the "shipping name" successfully at last?

**Comment by stefnats** [comment]
You need access to PII and you need to contact developer support to achieve that.

**Comment by aaalison** [comment]
> Hi aaalison， Do you get the "shipping name" successfully at last?

Nope, can't get

> You need access to PII and you need to contact developer support to achieve that.

Yes I think so
