### ISSUE TITLE
SP-API Developer Profile Update: Awaiting action from Amazon

### ISSUE THREAD

**Issue by karinamendonca29** [amzn/selling-partner-api-docs#919]
Hi,

I'm awaiting a response on this : SP-API Developer Profile Update : Restricted Access Request
ID: 7071942002

The initial email said it would take 5 business days but it's been more than a week now!

**Comment by jchavest13** [comment]
Hi @karinamendonca29,

Please accept our apologies for the delay getting back to you on your case, I've created an internal request to expedite its vetting. You can rest assured that our team is working diligently to address your case as soon as possible.

Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API
