### ISSUE TITLE
Which API seller can use for getting all buyer questions e.g. items, price, returns or service requests?  

### ISSUE THREAD

**Issue by sibendu** [amzn/selling-partner-api-docs#92]
Hi
Which API can be used by a seller for getting all buyer questions and messages - general (like items, price) and pertaining to an order (e.g. returns, service requests etc)? 
Is there a single API for this? 
Regards.

**Comment by rugved1991** [comment]
Hi @sibendu,

Thanks for your feedback! We have relayed it to our product team for consideration.
