### ISSUE TITLE
FEED API - Access to requested resource is denied.

### ISSUE THREAD

**Issue by jhullparkseed** [amzn/selling-partner-api-docs#921]
I have gone through all the steps to gain access to using the SPAPIs and I have been able to **successfully** pull orders using the API for orders.

I am now trying to  process the order Acknowledgement using the SPAPI Feeds model and I get this response:

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

I confirmed I am using the ***same*** access keys/tokens etc, the request gets signed, I called the same APIClient that worked for Orders so why would I get this message?  Do I need to create another role or policy?

I am not sure the content type for the CreateDocument Call but I cannot see how that would give me access denied.

**Comment by homer-zhang** [comment]
@jhullparkseed  I get the same error message .
badly I even can't get the purchase orders.
I have done all the steps in the document.
but it still not work.
Could you share your way to pull orders?
thanks for a lot.

**Comment by jhullparkseed** [comment]
If you are using c# you need to use the swagger models and [convert them to c#  classes](https://swagger.io/tools/swagger-codegen/) and the [api access solution for c#](https://github.com/amzn/selling-partner-api-models/blob/main/clients/sellingpartner-api-aa-csharp/SellingPartnerAPIAuthAndAuthCSharp.sln).

Once you get swagger downloaded and set up, here is an example of converting a model (json) to c# project:

java -jar C:\SwaggerToCL\swagger-codegen-cli.jar generate -i C:\SwaggerToCL\feeds_2021-06-30.json -l csharp -o C:\SwaggerToCL\Feeds_sharp

In the APIClient class in the swagger project add these lines in PrepareRequest:

```
            request = (RestRequest)SignWithAccessToken(request, credentials.LWA_App_ClientId, credentials.LWA_App_ClientSecret, credentials.RefreshToken);

           request = (RestRequest)SignWithSTSKeysAndSecurityTokenn(request,RestClient.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
```
and this at the bottom filling in your own credentials:

        ```
private static IRestRequest SignWithAccessToken(IRestRequest restRequest, string clientId, string clientSecret, string refreshToken)
        {
            var lwaAuthorizationCredentials = new LWAAuthorizationCredentials
            {
                ClientId = clientId,
                ClientSecret = clientSecret,
                Endpoint = new Uri("https://api.amazon.com/auth/o2/token"),
                RefreshToken = refreshToken,
            };

            return new LWAAuthorizationSigner(lwaAuthorizationCredentials).Sign(restRequest);
        }

        private static IRestRequest SignWithSTSKeysAndSecurityTokenn(IRestRequest restRequest, string host, string roleARN, string accessKey, string secretKey)
        {
            AssumeRoleResponse response1 = null;
            using (var STSClient = new AmazonSecurityTokenServiceClient(accessKey, secretKey, RegionEndpoint.USEast1))
            {
                var req = new AssumeRoleRequest()
                {
                    RoleArn = roleARN,
                    DurationSeconds = 950, //put anything you want here
                    RoleSessionName = Guid.NewGuid().ToString()
                };

                response1 = STSClient.AssumeRoleAsync(req, new CancellationToken()).Result;
            }

            //auth step 3
            var awsAuthenticationCredentials = new AWSAuthenticationCredentials
            {
                AccessKeyId = response1.Credentials.AccessKeyId,
                SecretKey = response1.Credentials.SecretAccessKey,
                Region = "us-east-1"
            };

            restRequest.AddHeader("x-amz-security-token", response1.Credentials.SessionToken);

            return new AWSSigV4Signer(awsAuthenticationCredentials).Sign(restRequest, host);
        }

        public class SellerAPICredentials
        {
            /// <summary>
            /// todo Add values to config file
            /// </summary>
            public string BasePath = "https://sellingpartnerapi-na.amazon.com";
            public string LWA_App_ClientId = ""; //amzn...
            public string LWA_App_ClientSecret = "";
            public string RefreshToken = ""; //Atzr...
            public string AWSSecret = "";
            public string AWSKey = "";
            public string RoleARN = "arn:aws:iam::999887759094:role/SellingPartnerRole"; //arn...
        }
```
This was the culmination of days on research and learning and I still have issues, but I did get ORDER apis working.
