### ISSUE TITLE
Migrate MWS application to the new SP-API - not able to get RDT

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-docs#922]
I am in the process of converting my existing MWS app to a hybrid App.

I have completed the website auth flow and appstore auth flow.

I have followed the docs and set the app as hybrid app in my developer console.  Status is `Current edit is in draft`.  My application is a public seller application, the MWS app was already published.  My existing MWS app has access to PII data (for direct fulfillment access).

`Direct-to-Consumer Shipping` is selected in my app setting.

I am able to call `getMarketplaceParticipations` from `SellersApi`, against to my own seller account, and with a self authorized refresh token.

However, I am not able to get the Restricted Data Token (RDT).  I followed the steps here:

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-an-rdt-and-call-restricted-operations

and the code here:

https://github.com/amzn/selling-partner-api-models/commit/63a55cee11ca54caf8242884027a863860abaaf2

The response I am getting is:

```json
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}

```

This is the resource path I am trying to access:

```
/orders/v0/orders/?maxResultsPerPage=100&marketplaceIds=ATVPDKIKX0DER&createdAfter=2021-06-04T04:37:39Z&fulfillmentChannels=MFN
```

Did I miss anything?

Or, I have to have my application published in order to access the above resource?

BTW,  I am not able to get the refresh token from mws auth token, this is normal for apps in draft status?

**Comment by ShivikaK** [comment]
Hello @Mike-the-one 

Thank you for raising the issue.

Based on details provided, you are requesting RDT for getOrders operation in Orders API.

Below are the restricted operations in Orders API that require RDT -

Orders API:

    getOrderBuyerInfo

    getOrderAddress

    getOrderItemsBuyerInfo

getOrders operation does not require RDT. If you are instead requesting RDT for Direct Fulfillment Orders API then the path provided is incorrect.

Please confirm your use case for RDT and I can assist further with the issue.

Also with respect to not getting refresh token from mws auth token, if you are using Authorizations API, then the error is expected as the API can only be used after the hybrid application has been published to appstore.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Mike-the-one** [comment]
@ShivikaK Thank you so much for your fast reply.  I will try to request RDT for these three actions.
For getOrders call, my first try was to use the `OrdersV0Api`, but it returned null:

![image](https://user-images.githubusercontent.com/37592183/122842054-90d46f00-d2ca-11eb-897b-6792287dc8e6.png)

the `createdAfter` date is Jun 4,  and I have orders between Jun 4 and today.

Thanks

**Comment by Mike-the-one** [comment]
@ShivikaK Just an update, I am able to get RDT for these three resources:

```sh
getOrderBuyerInfo
getOrderAddress
getOrderItemsBuyerInfo
```

So I need help on `getOrders` call from `OrdersV0Api`.

This is how I call it

```java
GetOrdersResponse getOrdersResponse = api.getOrders(Collections.singletonList("ATVPDKIKX0DER"),
                "2021-06-04T04:37:39Z", null, null, null, null, Collections.singletonList("MFN"), null, null, null,
                Integer.valueOf(100), null, null, null, null, null, null);
```

The result is in the previous comment.  The `orders` object is null.

As for publishing hybrid application, once published, my customers can either authorize my app via my site or via app store, and since I will receive mws auth token, so I can keep using MWS apis, until I completely convert my app to use SP-API?

After Sept 30, will you require all app owners to change the app type from hybrid app to SP-API only?

thanks

**Comment by jhullparkseed** [comment]
If I can jump on this thread.  I  am working on integration program that uses ORDER apis to pull down order information to go into our ERP system then would use FEED apis (createFeedDocument, createFeed etc) to acknowledge orders as well as do inventory, pricing, and shipping updates.

While I was able to get working the ORDERS api (GetOrder, GetBuyer etc) using the c# SDK for access (sets up LWA/AWS signing) along with the Model's API Client, When I tried using the same access for FEED, I keep getting:

      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""

I then read that PPI APIs (like Address) will require RDT and when I attempted to put together an API call to getRestrictedAccessToken I got the same error above.  There is no clear documentation on how to implement this in c#, but I have all the credentials from AWS to sign calls, what else do I need?

**Comment by Mike-the-one** [comment]
@ShivikaK Could you please take a look?  I am stuck :-(

**Comment by ShivikaK** [comment]
Hello @Mike-the-one 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

If a support case has already been logged with us, please share the case ID and I can review the same.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Mike-the-one** [comment]
Hi, @ShivikaK Thank you so much.  The case id is 8190894151.

Thank you so much.

**Comment by abuzuhri** [comment]
> I am in the process of converting my existing MWS app to a hybrid App.
> 
> I have completed the website auth flow and appstore auth flow.
> 
> I have followed the docs and set the app as hybrid app in my developer console. Status is `Current edit is in draft`. My application is a public seller application, the MWS app was already published. My existing MWS app has access to PII data (for direct fulfillment access).
> 
> `Direct-to-Consumer Shipping` is selected in my app setting.
> 
> I am able to call `getMarketplaceParticipations` from `SellersApi`, against to my own seller account, and with a self authorized refresh token.
> 
> However, I am not able to get the Restricted Data Token (RDT). I followed the steps here:
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-an-rdt-and-call-restricted-operations
> 
> and the code here:
> 
> [amzn/selling-partner-api-models@63a55ce](https://github.com/amzn/selling-partner-api-models/commit/63a55cee11ca54caf8242884027a863860abaaf2)
> 
> The response I am getting is:
> 
> ```json
> {
>   "errors": [
>     {
>       "code": "InvalidInput",
>       "message": "Application do not have access to some or all requested resource",
>       "details": ""
>     }
>   ]
> }
> ```
> 
> This is the resource path I am trying to access:
> 
> ```
> /orders/v0/orders/?maxResultsPerPage=100&marketplaceIds=ATVPDKIKX0DER&createdAfter=2021-06-04T04:37:39Z&fulfillmentChannels=MFN
> ```
> 
> Did I miss anything?
> 
> Or, I have to have my application published in order to access the above resource?
> 
> BTW, I am not able to get the refresh token from mws auth token, this is normal for apps in draft status?

Try to Use my library handle most of requirement https://github.com/abuzuhri/Amazon-SP-API-CSharp

**Comment by abuzuhri** [comment]
> Hi, @ShivikaK Thank you so much.  The case id is 8190894151.
> 
> 
> 
> Thank you so much.

Same problem here but I think to access this resource you need to have permission first in your developer account to access PII .
