### ISSUE TITLE
403 on all Reports API operations

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-docs#925]
I'm the maintainer of a [PHP wrapper library](https://github.com/jlevers/selling-partner-api) for the SP API. I'm trying to update the library to use the latest versions of the API models.

For some reason, when I upgraded to the `2021-06-30` version of the Reports API, I started getting `403 Unauthorized` on every single Reports API endpoint, even when using credentials that had been working before I upgraded. I know that an RDT is required to access `getReportDocument`, but even `getReports` and `createReport` are giving me a 403.

Could anyone shed some light on what might be going on here? I'm able to make calls to other endpoints exactly as I could before (for instance, `getMarketplaceParticipations` is working fine), but none of the Reports API calls are working.

**Comment by sleipi** [comment]
Hi @jlevers 

We are facing the same issue during our SPAPI Integration. 
The Feedback from Amazons SPAPI Team was that the `2021-06-30` version of the Reports API is not yet production ready, thus it is not yet available.

best

**Comment by jlevers** [comment]
Thanks @sleipi, that's very good to know.

If someone from Amazon could give a timeline on when the new version of the Reports API might be ready, that would be much appreciated.

**Comment by avvarga** [comment]
Hi @jlevers,

The current target date for the release of the new version (2021-06-30) of the Feeds API and the Reports API is 06/30/2021. 

Thanks,
Alejandro C
Selling Partner API Developer Support

**Comment by kpconnell** [comment]
> Hi @jlevers
> 
> We are facing the same issue during our SPAPI Integration.
> The Feedback from Amazons SPAPI Team was that the `2021-06-30` version of the Reports API is not yet production ready, thus it is not yet available.
> 
> best

How exactly did you get in touch with the SPAPI team?

**Comment by ianrussel** [comment]
@kpconnell  you can create ticket in Seller support

**Comment by jlevers** [comment]
@avvarga I'm still getting a 403 here. Was the Reports API deployed yesterday as planned?

**Comment by parvathm** [comment]
Hi @jlevers,

Sorry for providing incorrect date and for any inconvenience that might have caused.  
Current release date is July 14th. We will make an announcement on Github when it is released. 

Thanks,
parvathm,
Selling Partner API Developer Support.

**Comment by vaidas-lungis** [comment]
Also related https://github.com/amzn/selling-partner-api-docs/issues/998
