### ISSUE TITLE
reports content Incorrect characters

### ISSUE THREAD

**Issue by yuql** [amzn/selling-partner-api-docs#927]
I downloaded a report（TYPE：GET_MERCHANT_LISTINGS_ALL_DATA）use sp-api，the api response header tell me the document charset is  cp1252，I try to convert it to UTF-8 and save to my database（mysql） ，but the document content always show me the  Incorrect characters 。
example：℃ will be show ?

My used function is ：mb_convert_encoding($string, 'UTF-8','cp1252');
How Can I correct convert it to UTF-8 ？

**Comment by chris-chen23** [comment]
I had the same problem. Did you solve it? I want to ask for help

**Comment by aibirriaga** [comment]
Same issue here, in what encoding is the response given?

**Comment by yutveg** [comment]
Still having this issue. Can't seem to transcode it into UTF-8 successfully. Is it actually CP1252?
