### ISSUE TITLE
[BUG] Cannot get "getOrderBuyerInfo > BuyerName" & "getOrderAddress > ShippingAddress > Name"

### ISSUE THREAD

**Issue by aaalison** [amzn/selling-partner-api-docs#928]
According to SP-API order documentation,

1. "getOrderBuyerInfo" will return "BuyerName"
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorderbuyerinfo

But it did not return, I got error "Undefined index: BuyerName"
![image](https://user-images.githubusercontent.com/86222908/122875627-186fbb80-d367-11eb-9a21-251ed215e6aa.png)
![image](https://user-images.githubusercontent.com/86222908/122875664-21f92380-d367-11eb-9485-a21c4eb75102.png)

2. "getOrderAddress" will return "ShippingAddress" with "Name"
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorderaddress

But it returned blank name
![image](https://user-images.githubusercontent.com/86222908/122875694-2c1b2200-d367-11eb-8967-4a2e6d66fe1c.png)
![image](https://user-images.githubusercontent.com/86222908/122875719-350bf380-d367-11eb-9d55-ce7313152bb9.png)

Operation: getOrderBuyerInfo, getOrderAddress
MarketplaceId: ATVPDKIKX0DER

**Comment by Mike-the-one** [comment]
The is the returned data for buyerInfo:

```json
{
  "payload": {
    "AmazonOrderId": "111-1111111-1111111",
    "BuyerEmail": "1234567@marketplace.amazon.com",
    "BuyerName": "John Doe"
  }
}
```

and address
```json
{
  "payload": {
    "AmazonOrderId": "111-1111111-1111111",
    "ShippingAddress": {
      "StateOrRegion": "AA",
      "AddressLine1": "address line 1",
      "Phone": "123-123123123",
      "PostalCode": "1234567",
      "City": "Cityname",
      "CountryCode": "US",
      "AddressType": "Residential",
      "Name": "John Doe"
    }
  }
}
```

try to remove `response` from your code.

**Comment by aaalison** [comment]
> The is the returned data for buyerInfo:
> 
> ```json
> {
>   "payload": {
>     "AmazonOrderId": "111-1111111-1111111",
>     "BuyerEmail": "1234567@marketplace.amazon.com",
>     "BuyerName": "John Doe"
>   }
> }
> ```
> 
> and address
> 
> ```json
> {
>   "payload": {
>     "AmazonOrderId": "111-1111111-1111111",
>     "ShippingAddress": {
>       "StateOrRegion": "AA",
>       "AddressLine1": "address line 1",
>       "Phone": "123-123123123",
>       "PostalCode": "1234567",
>       "City": "Cityname",
>       "CountryCode": "US",
>       "AddressType": "Residential",
>       "Name": "John Doe"
>     }
>   }
> }
> ```
> 
> Maybe you can printout the json body and take a look

Thank you! Would you know if access to PII is required to get the two data?

**Comment by fazal26** [comment]
getting the same issue.
