### ISSUE TITLE
How to fetch all message by the seller?

### ISSUE THREAD

**Issue by nickname-sb** [amzn/selling-partner-api-docs#93]
My goal is to get all unread messages for unified management, but the existing api can only be obtained by the order number.

**Comment by vikingcodes** [comment]
Can you share your User Case ?

**Comment by nickname-sb** [comment]
I am calling this message-api and it returns an error: {
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
};

This api can only query emails through amazonOrderId, my goal is to get all eligible emails by time or email status.

**Comment by nickname-sb** [comment]
Is there currently a filter condition such as time or status to get all eligible emails?

**Comment by nickname-sb** [comment]
I am calling this message-api(https://github.com/amzn/selling-partner-api-docs/blob/main/references/messaging-api/messaging.md) and it returns an error: {
"errors": [
{
"code": "InternalFailure",
"message": "We encountered an internal error. Please try again.",
"details": ""
}
]
};

**Comment by rogersv** [comment]
Did you call the sandbox endpoint or the production endpoint?

**Comment by nickname-sb** [comment]
I am calling the api of the production endpoint.

**Comment by nickname-sb** [comment]
My problem has been solved.

**Comment by hsmw408** [comment]
> My goal is to get all unread messages for unified management, but the existing api can only be obtained by the order number.


I have the same need, have you solved it?

**Comment by hsmw408** [comment]
> My goal is to get all unread messages for unified management, but the existing api can only be obtained by the order number.

@christopy-dev  I have the same need, have you solved it?

**Comment by christopy-dev** [comment]
> > My goal is to get all unread messages for unified management, but the existing api can only be obtained by the order number.
> 
> @christopy-dev I have the same need, have you solved it?

No

**Comment by bilbey** [comment]
We need to fetch all messages after a certain time. It is very inefficient to query messages for all orders periodically.

**Comment by yizeku** [comment]
@bilbey 

How to get the message corresponding to the order? I didn't find it in the document?

**Comment by yizeku** [comment]
@bilbey Do you know what API should be used to get messages sent by users?
