### ISSUE TITLE
Error returned on POST /fba/inbound/v0/shipments/{shipmentId}/transport/estimate - not documented

### ISSUE THREAD

**Issue by hrhearn7** [amzn/selling-partner-api-docs#930]
What does the error code mean when calling POST /fba/inbound/v0/shipments/{shipmentId}/transport/estimate.  It is not in documentation - 

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "FTXGatewayService.estimateLtlShipment returned error code: 412",
      "details": ""
    }
  ]
}

**Comment by gaurav-webs** [comment]
@hrhearn7 

I am also facing the same issue. but didn't find any possible solution.

@parvathm 

What this error means, can you please update?

**Comment by gaurav-webs** [comment]
@hrhearn7 

As i review my shipment in the seller center, when I am getting this `"FTXGatewayService.estimateLtlShipment returned error code: 412"` error at that time in my seller center in the **4. Shipping charges** section I am getting `"Unable to calculate shipping cost, please try again later"` this error something like this

![screenshot-sellercentral amazon com-2021 07 22-16_28_10](https://user-images.githubusercontent.com/78719205/126644810-e79c7713-9a81-4120-9e41-5a2359b6d5d2.jpg)

But after 3-3:30 hours that error remove from seller center and I am successfully run the `estiamteTransport` API.

You can wait for few hours if not able to run the API.

**Comment by defenderjim** [comment]
@hrhearn7 
@gaurav-webs 
I am having problems getting this endpoint working.  Did either of you have any success?
