### ISSUE TITLE
Report GET_REFERRAL_FEE_PREVIEW_REPORT gets cancelled

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#931]
Please explain the algorithm for obtaining this report (`GET_REFERRAL_FEE_PREVIEW_REPORT`).

When I manually request it, it always gets `CANCELLED`.

This is what the docs say:

> Tab-delimited flat file that contains the seller's open listings as well as the price and estimated referral fees for each SKU.
> 
> Note: The information in this report may be up to 24 hours old. Please do not request a report more than once per 24 hour period.
> 
> Can be requested.

**Comment by moltar** [comment]
I contacted SP API support thru the case log functionality and got the following useless response that is not even related to SP API:

> I understand you have a question regarding Referral Fee Preview Report. Kindly allow me to assist you further.
> 
> The Referral Fee Preview Report shows the estimated referral fee amount for each of your current listings on Amazon. The referral fee shown in the report is based on your current listed item price and does not account for shipping or gift wrap charges applied at the time of purchase. Additional selling fees, including variable closing fees, may apply when your item is sold.
> 
> The information contained in this report may be up to 72 hours old. The report can only be requested once per 24 hours.
> 
> To request an inventory report, follow these steps:
> 
> 1. Go to Inventory and select Inventory Reports.
> 2. Select the report type from the drop-down menu (in your case, select Referral Fee Preview Report). See the list of report types below.
> 3. Click the Request Report button.
> Reports generally take 15 to 45 minutes to generate. You can return to this page later to access your completed report.
> 4. Under Check Report Status & Download, when the report status is "Ready", click the Download button.
> 5. Save the file to your local computer in text (tab delimited, *.txt) format.
> 6. Open the report in a spreadsheet or database program, such as Microsoft Excel or Microsoft Access.

---

I then asked the same question again, got another useless response, which just states what is already in the docs. But not even SP API, this references MWS, when my question was about SP API.

> I understand you are not able to get the Referral Fee Preview Report.
> 
> Please search for "`_GET_REFERRAL_FEE_PREVIEW_REPORT_`" and click on "RequestReport" to find the steps to request a report in the below mentioned link.
> https://docs.developer.amazonservices.com/en_US/reports/Reports_ReportType.html#ReportTypeCategories__ListingsReports
> 
> You can find links to the documentation for the various API sections of Amazon Marketplace Web Service (Amazon MWS) here:
> https://developer.amazonservices.com/
> 
> The web page for each Amazon MWS API section has a link to the documentation for that API section. Each web page also has a link to the Amazon MWS Developer Guide, which provides information that applies to all Amazon MWS API sections.

---

I then asked again, and got the following response:

> I have reviewed your account and understand you're concerned about how to obtain a Referral Fee Preview Report.
> 
> While I know you are disappointed with the outcome of this matter, I’ve confirmed that the [INFORMATION/RESPONSE] you received from our team on [6/24/2021] is correct and we are unable to address this decision any further.
> 
> I apologize for any inconvenience and appreciate your understanding.

---

So there is no answer and this is still not solved.

**Comment by gopkg-dev** [comment]
Once every 24 hours, the request will not be cancelled.
That's what I did.

**Comment by ellis** [comment]
Note that, as an alternative, you could consider using the [productFees](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-fees-api/productFeesV0.md) endpoint to get this information.

CONs:
- you'll need to call it for each ASIN or SKU individually.
- its buggy, so you can't use it yet for SKUs with certain characters, like slashes (see #467) and umlauts (see #742).

PROs:
-   You get a lot more information.

**Comment by hexrw** [comment]
I can confirm this issue still exits after almost 3 years
