### ISSUE TITLE
How long it takes to get developer account ?! Waiting for a month now

### ISSUE THREAD

**Issue by gmathew127** [amzn/selling-partner-api-docs#933]
We are just twiddling thumbs as of now. No idea how long Amazon is going to take to approve us , how are we supposed to meet 30th September deadline if we cant even begin the development work, resolve all the issues and go live ?

**Comment by jchavest13** [comment]
Hi @gmathew127,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by S4T-TP** [comment]
Hello @jchavest13,

we have a similar problem.
According to the Developer-Guide, our application is required to become a "Hybrid Selling Partner API applications".
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#hybrid-selling-partner-api-applications

Unfortunately, at the Developer Central we can only select the API type “MWS” when we edit our existing application.
We assume that it should be possible to select another API type for a hybrid-application.

We have already opened a case in European seller central (6916088232) but so far, we have not received an answer.
We are really stuck and cannot continue the migration process. Can you please take a look at our case?

Best Regards
S4T

**Comment by jchavest13** [comment]
Hi @S4T-TP,

Upon review, looks like there is an update on your case. Feel free to check it out at your earliest convenience for more information.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by S4T-TP** [comment]
Hello @jchavest13 ,

You were right, our open case was accepted yesterday and we can now select the correct API type.
Thank you very much for your quick answer.

Best regards
S4T

**Comment by jchavest13** [comment]
Hi @gmathew127,

Please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by Maciej-Surowiec** [comment]
Hi Julian @jchavest13 
Could You please help us to resolve our issue we still struggle with MWS registration our Case number is: 7030881652
Could You please help us to get through the registration ?

**Comment by jchavest13** [comment]
Hi @Maciej-Surowiec,

Upon review, looks like your case was resolved on 06/23/2021. Please feel free to check the communications sent through the case for more information.

Regards,
Julian
Developer Registration Specialist, SP-API
