### ISSUE TITLE
[FEATURE] Documentation Generating AMZNCC number

### ISSUE THREAD

**Issue by MayuBen1027** [amzn/selling-partner-api-docs#937]
For the SubmitShipmentConfirmations it says that for generating Amazon UCC labels to pass the type AMZNCC. But I can't find anywhere on how to generate this number. Since the API currently doesn't support label generation for Item Procurement I want to generate the labels myself and then do a shipment confirmation that has the data in it.

**Comment by jdmontes** [comment]
Hi @MayuBen1027, did you find a solution? I would appreciate your comments!
