### ISSUE TITLE
[BUG] Removal Shipment Detail report used marketplaceIds always canceled 

### ISSUE THREAD

**Issue by lijinghui** [amzn/selling-partner-api-docs#938]
**Describe the bug**

In the SP-API the Removal Shipment Detail report cannot be used marketplaceIds as parameters.The Amazon will canceled you report request. The type is GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA
I tried to use MWS requests without marketplaceIds and same date range it will success. And I tried to use MWS requests with  marketplaceIds  then Amazon also canceled  my  requests  .MWS marketplaceIds is a optional parameters . But sp-api is a required parameters ,how can i use sp-api to request Removal Shipment Detail report ?

Please be aware that although there are no procedural errors, the requested report is invalid and cancelled. This has a serious impact on data acquisition.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#createreport

![20210625143926](https://user-images.githubusercontent.com/13672644/123381394-42bdb500-d5c3-11eb-9ddf-a2a134d15872.jpg)
![20210624195601](https://user-images.githubusercontent.com/13672644/123381396-44877880-d5c3-11eb-910d-571f54b6d1d1.jpg)

**Comment by anthonychoy** [comment]
is there an update on this bug? thanks
