### ISSUE TITLE
SP-API Developer Profile Update : Restricted Access Request

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#942]
Hi,
I applied to access "Direct-to-Consumer Delivery" at 21 June and a case with the number 8488857661 has been created automatically but still we didnt get a reply from Amazon.
It is really urgent for us and developers to solve it in short time.
Can you please review our case and approve that?
Thank you

**Comment by jchavest13** [comment]
Hi @hkncnr07,

Please accept our apologies for the delay getting back to you on your case. You can rest assured that our team is working diligently to address your case as soon as possible.
Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by hkncnr07** [comment]
Dear @jchavest13,

Thanks for reply. Still my case not solved and I didnt get any answer from my case.
Can you please review it?

Thank you

**Comment by hkncnr07** [comment]
> Hi @hkncnr07,
> 
> Please accept our apologies for the delay getting back to you on your case. You can rest assured that our team is working diligently to address your case as soon as possible.
> Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.
> 
> Regards,
> Julian
> Developer Registration Specialist, SP-API

Dear @jchavest13 

We have sent new requirements 1 week ago but still waiting for reply from Amazon.
Can you please help us to expedite that?
It is very important for our developer team and company.

Thanks
