### ISSUE TITLE
[BUG] To get a complete order we need to requires 5 API requests, after these 20 you will have to wait 3 minutes for every new request. It’s too terrible. Can Amazon explain why they put these restrictions and disassemble an order into so many interfaces?

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#948]
To get a complete order we need to requires 5 API requests
getOrders
getOrderBuyerInfo
getOrderAddress
getOrderItems
getOrderItemsBuyerInfo

Its 0.0055 requests per second, so if you divide 1 by 0.0055 you get 180 seconds per request, which is 3 minutes. Well, you have 20 burst, but after these 20 you will have to wait 3 minutes for every new request. 

It’s too terrible. Can Amazon explain why they put these restrictions and disassemble an order into so many interfaces?

**Comment by lijinghui** [comment]
In my tests, it was a 0.0055 second interval. So I used this code to hibernate, but it was inefficient and frustrating.
```
  String limit = headers.get("x-amzn-RateLimit-Limit");
  double limitDb = Double.parseDouble(limit);
  double ceil = Math.ceil(1 / limitDb / burst);
```

**Comment by userbabu** [comment]
I think you have misunderstood. You can take a closer look at the description of the traffic limit in the document

**Comment by NetRushJacob** [comment]
@NancyLin are you sure each of these calls are on the same quota? My understanding is that each of these 5 have their own, individual quotas.

Also note that the Orders API is the first to be a dynamic quota, so as your order count increases, so does the quota.

Totally agree with you on the separation, though. Although I can understand it as it makes it easier to implement considering the likely reason: PII. getOrder and getOrderItems do not contain any PII and, therefore, will not need any extra authorization. The others all contain PII.

**Comment by SiMu-EVA** [comment]
> 在我的测试中，这是一个0.0055秒的间隔。所以我用这个代码来休眠，但它效率低下且令人沮丧。
> 
> ```
>   String limit = headers.get("x-amzn-RateLimit-Limit");
>   double limitDb = Double.parseDouble(limit);
>   double ceil = Math.ceil(1 / limitDb / burst);
> ```

xd,怎么可能0.0055s的间隔，按你的意思它能1s恢复180个？我1s/个，在120个后，就报429

**Comment by SiMu-EVA** [comment]
> 

大佬，对不起，我还是无法理解。
如果我limitDb=0.0167,
那么ceil=Math.ceil(1/0.0167/20)=3，那么ceil代表的意思是什么呢？是每3s回复一个么？

**Comment by SiMu-EVA** [comment]
> > > > > 在我的测试中，这是一个0.0055秒的间隔。所以我用这个代码来休眠，但它效率低下且令人沮丧。
> > > > > ```
> > > > >   String limit = headers.get("x-amzn-RateLimit-Limit");
> > > > >   double limitDb = Double.parseDouble(limit);
> > > > >   double ceil = Math.ceil(1 / limitDb / burst);
> > > > > ```
> > > > 
> > > > 
> > > > xd,怎么可能0.0055s的间隔，按你的意思它能1s恢复180个？我1s/个，在120个后，就报429
> > > 
> > > 
> > > 你理解错了，我不知道你是怎么算的180个， Math.ceil(1 / limitDb / burst)的 burst 是文档里面接口定义的并发数。由于亚马逊给的是动态限速，在21年的黑五里面订单接口达到了0.002XX的间隔。用这个方式算是否需要休眠是可以的。休眠时间过短是可以直接忽略的。
> > 
> > 
> > 大佬，对不起，我还是无法理解。 如果我limitDb=0.0167, 那么ceil=Math.ceil(1/0.0167/20)=3，那么ceil代表的意思是什么呢？是每3s回复一个么？
> 
> 你的例子确实是 3秒恢复一个。 x-amzn-RateLimit-Limit 因为单位是每秒，所以导致出现0.00XXX的时候让人很迷惑。 你可以去看看Nginx的限流，我个人感觉这个限流和Nginx十分类似。

大佬，谢谢你，我正在测试你的方法，但我想知道你从哪知道用”Math.ceil“来计算的？

**Comment by SiMu-EVA** [comment]
> > ”Math.ceil
> 
> 这个只是java一个转型的系统函数，没什么特殊的。

我知道Math.ceil，我的疑问是为什么要用”Math.ceil“计算，我没看到文档有说
