### ISSUE TITLE
What is the structure of "< string > array" ? It's available ?

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#95]
I tried several methods which ask for a "<string> array" field, but each time I have to put a simple "<string>".

Example for getLabels in  <a href="https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getlabels">Fulfillment Inbound</a>.

I can't do : 
/fba/inbound/v0/shipments/{shipmentId}/labels?shipmentId=shipmentId&PageType=PageType&LabelType=LabelType&PackageLabelsToPrint[]=PackageLabelsToPrint&PackageLabelsToPrint[]=PackageLabelsToPrint2

But i can do : 
 /fba/inbound/v0/shipments/{shipmentId}/labels?shipmentId=shipmentId&PageType=PageType&LabelType=LabelType&PackageLabelsToPrint=PackageLabelsToPrint

Same thing when the MarketplaceId require an "< string > array", the "< string > array" not work but the simple "string" work..

is this normal ? The "< string > array" is not yet available? Or is there a specific way?

**Comment by rogersv** [comment]
The values are seperated by a `,`. For example `?type=id1,id2,id3`. At least that is that case for MarketplaceIds in the /orders/ endpoint.

**Comment by charliecode** [comment]
@FexusZ Did you ever get past issue #94 with the pageSize error?

**Comment by FexusZ** [comment]
Don't now why the comment was delete but the response to my ask is : PackageLabelsToPrint=PackageLabelsToPrint,PackageLabelsToPrint2...,PackageLabelsToPrintN.

**Comment by cpietsch82** [comment]
Hi there,

to use a string of labels to print doesn't work for me as well. 

I've got the following error response: 
"Provided SellerCartonIds are not valid: [[cartonId1, cartonId2, ...]]" for Sshipment: [FBAXYZ...]"

The cartonIds are exactly the same like in the upload feed.

Any ideas? Thanks in advance!

**Comment by Kevin-qs** [comment]
< string > array, How to pass by get?

**Comment by khanakia** [comment]
Same question
