### ISSUE TITLE
Amazon does not reply to Restricted Access requests

### ISSUE THREAD

**Issue by fmaurobica** [amzn/selling-partner-api-docs#950]
Good morning,

on April 02 I opened a new issue on Amazon seller central because I requested Amazon access to the PII for our application. 
Today is June 28, and Amazon has not yet replied to my request, neither positive nor negative.
The ticket ID is 6908148442.
Is it fair to keep a customer on hold for three months, without a reply? I did try many times to solicit the ticket. It is really frustrating to wait all this time, lose customers, and meanwhile, I am paying the amazon subscription as a developer.
Even when we had a problem with the SP-API, Amazon did not reply to our ticket on Seller Central; Instead, I got support here on Github (and the problem was on Amazon's side).
Is this normal? Can anyone here help us to speed up the request?

Thank you

**Comment by chadwixk** [comment]
Unfortunately so. See #846 and #955

**Comment by jchavest13** [comment]
Hi @fmaurobica,

Please accept our apologies for the delay getting back to you.

Upon review, looks like your Developer Registration case 6908148442 was resolved on 07/19/2021. You can check its resolution email for more information about the outcome.

Regards,
Julian
Developer Registration Specialist, SP-API
