### ISSUE TITLE
Error Code: MD9000 - "Authorize new developer"

### ISSUE THREAD

**Issue by Yoh7** [amzn/selling-partner-api-docs#951]
I have a client that simply wants us to utilize this API to update their Inventory. 
This is a custom app specifically for them that integrates their DB with their Amazon Seller stock.

Followed the docs and when the client goes to Apps & Services > Manage Your Apps > Authorize new developer, then enters our info they get the error:

Error Code : MD9000

Developer ID: 489766047078 (French)
Seller token : A3GKKMDSTPO9EO (LaMarge, french too)

**Comment by GenderAPI** [comment]
i have the same error and there are many cases for this and there is no response and no solution for it

https://github.com/amzn/selling-partner-api-docs/issues/903

@ShivikaK @rugved1991 @parvathm
