### ISSUE TITLE
Any realistic time line documentation for developer account approval ? 

### ISSUE THREAD

**Issue by kinjalnyc** [amzn/selling-partner-api-docs#952]
While I appreciate the vetting process, is there any real timeline documentation on how long we should be waiting for our developer account approval ? So far we have been waiting for 1 month. It would be great to get rough idea. If its going to take a lot longer we would give up on developing solution on our own and move on with a third party as our upper management is really pushing development team at this point. We really hope Amazon documents this for ease of developers consuming API.

Our case # is 8417659571

**Comment by DawidWawrzyniak** [comment]
Respond and ask what was missing in your request.
I made two requests (Vendor and Seller Center) and both were rejected the first time.

**Comment by kinjalnyc** [comment]
@DawidWawrzyniak We got following response, what was reason for your rejection ?

We have completed our assessment and have determined that you do not meet the requirements for Restricted SP-API. To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon.

No changes have been made to your SP-API access at this time.

**Comment by purplefish-it** [comment]
The realistic timeline from my experience with this is.... Never.  Even when you jump through all the hoops and provide evidence that you will adhere to all their requests, you will get denied without explanation.  I imagine there's a lot of MWS users who will have to stop selling on Amazon when those APIs are retired.
