### ISSUE TITLE
The Cancel button has been added to the consent page. Resolving this issue.

### ISSUE THREAD

**Issue by bikramsinghpb** [amzn/selling-partner-api-docs#954]
The Cancel button has been added to the consent page. Resolving this issue.

_Originally posted by @rugved1991 in https://github.com/amzn/selling-partner-api-docs/issues/29#issuecomment-823601980_

We are able to view the Cancel Button on consent page. But there is no operation perform on clicking this.  And Also I am not able to find the option to set CancelRedirectURI while registering the app. Could you please let us know how we can exit after clicking the Cancel button on cancel page

**Comment by ShivikaK** [comment]
Hello @bikramsinghpb 

Thank you for confirming that issue has been resolved for you.

I am closing out this issue as requested.

Thanks,
Shivika Khare
Selling Partner API Developer Support
