### ISSUE TITLE
Amazon Rejected Restricted Access Request

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#955]
We have a developer account and after we try to use Orders Api we recognized that we couldnt get full buyer address information and we requested restricted access of api.
Today our case was replied and Amazon rejected our request. The answer is below:

"Hello,

Thank you for your response.

We have completed our assessment and have determined that you do not meet the requirements for Restricted SP-API. To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon.

No changes have been made to your SP-API access at this time."

What is that mean? There are too many applications and many of them same specifications. We have written our specific different specifications but we got that answer. What can we do? We need that access and our project needs that access becase we have a warehouse integration with carriers.

Thank you

**Comment by gmathew127** [comment]
We got same response, we gave up and decided to go with third party solution provider and integrated their api in to our system. It's really sad Amazon treats developer this way, all applications kind of provide same order sync,pick, pack and ship, dashboard, forecasting and inventory functionality, so do they want us to invent something new ?

**Comment by chadwixk** [comment]
@gmathew127 would you mind sharing which provider you used...we are in the same boat :(

@hkncnr07 we just got this BS response as well. Our response:

```
Hello, I don't understand this response in stating that apps must be materially different from existing applications. 

- This undermines the whole concept of free market competition that is what continually drives apps to be better. 

- we do believe we offer unique advantages compared to other solutions. How did you evaluate our solution compared to the thousands of apps your already have in your app store?

- You currently have multiple apps in your app store that are not materially different, eg. Shipping Easy and Shippo are essentially very similar to each other...why did you approve both?

Can you please provide some clarification?

Thank you.
```
This seem anti-competitive and potentially illegal...and hypocritical.

@jchavest13 Can you shed any light onto this type of response or he rationale behind it.

**Comment by gmathew127** [comment]
Moving on with orderdesk, dealing with amazon's policies and its buggy painful api is not worth our time and effort.

**Comment by fernlop** [comment]
@jchavest13 
Anything new here? 
They reject my request since march without a real reason. 
An its not just potentially illegal, it is illegal. The German cartel office already decided that Amazon has to grant sellers access and have a really good reason if they deny the access. I believe you can see it the same way with developers.

I gave them a last chance (Case ID 6900535322) to review my request and if they still deny without a real reason I will report them and take legal actions. 

It's very disappointing that we are at this point, but I think I can speak for all of us that Amazon is critical for our business.

**Comment by hkncnr07** [comment]
@jchavest13 
My request was also denied 2 days ago again and there is no explanation as to why it was denied.
Our software company has been trying to get this authorization for 6 months and we have fulfilled all the items in the Amazon policies and sent everything requested from us.
There is no other solution other than making repeated requests. There is no one to get information over the phone.
Unfortunately, our company has been victimized by Amazon in this regard.

**Comment by WWangYu** [comment]
> @jchavest13 Anything new here? They reject my request since march without a real reason. An its not just potentially illegal, it is illegal. The German cartel office already decided that Amazon has to grant sellers access and have a really good reason if they deny the access. I believe you can see it the same way with developers.
> 
> I gave them a last chance (Case ID 6900535322) to review my request and if they still deny without a real reason I will report them and take legal actions.
> 
> It's very disappointing that we are at this point, but I think I can speak for all of us that Amazon is critical for our business.


Did you finally get permission? We have the same problem now

**Comment by miketimeturner** [comment]
> @jchavest13 My request was also denied 2 days ago again and there is no explanation as to why it was denied. Our software company has been trying to get this authorization for 6 months and we have fulfilled all the items in the Amazon policies and sent everything requested from us. There is no other solution other than making repeated requests. There is no one to get information over the phone. Unfortunately, our company has been victimized by Amazon in this regard.



> @jchavest13 My request was also denied 2 days ago again and there is no explanation as to why it was denied. Our software company has been trying to get this authorization for 6 months and we have fulfilled all the items in the Amazon policies and sent everything requested from us. There is no other solution other than making repeated requests. There is no one to get information over the phone. Unfortunately, our company has been victimized by Amazon in this regard.

Im curious too, did you get permission? if not what did you do? thanks

**Comment by aikidou9876** [comment]
こんにちは。
私は日本で同じく申請を行っておりますが、状況は同じです。
現在、この申請について許可を得られた申請は存在しないのではないのでしょうか？
申請却下によるフィードバックが存在しないため、改善する事ができません。

**Comment by Storeship** [comment]
We have also had 3 applications rejected although we already use their previous data.
Personally I think they are monopolising and stopping 3PL companies like Storeship shipping goods for our Amazon customers giving Amazon once again a monopoly and shipping etc.
Our app is unique to us and so in no way is anticompetitive, we just want to fulfil our customer's Amazon orders and it's what our customers want.

**Comment by benpatel** [comment]
We have our application denied 2 time already, we do not even want public data all we want is data for our orders, it is a private application, I already get customer data through 3rd part app, but i do not want to use them i want shipping to be handled by our own app. i am not sure what to explain any more.

**Comment by hussain3134** [comment]
Has anyone here got their application approved yet? @hkncnr07 @gmathew127 @chadwixk @fernlop @WWangYu @miketimeturner @aikidou9876 @Storeship @benpatel ?

**Comment by hkncnr07** [comment]
Hi,

Unfortunately, our application has not been approved yet.

**Comment by Storeship** [comment]
My last application was received with a response saying they would not consider my application anymore???
I since requested again and application has been ignored.
Email text below:

_

_As previously mentioned, we have determined that you will not be given access to Restricted SP-API roles based on your application. Your SP-API access remains unchanged at this time.

We evaluate all Public Developer applications that request Restricted SP-API access, for a variety of technical and business criteria including, but not limited to, launch readiness, services offered that can be viewed on a public facing website, and supported geographies.

Please note that this decision is final and we may not respond to further inquiries about this.

Thank you for selling with Amazon._

_

**Comment by stratokako** [comment]
> orderdesk

Can you tell me the app you are using? Thanks.

**Comment by Storeship** [comment]
Wanting to build my own app, cant start until I get the api keys

**Comment by jaimezac27** [comment]
@stratokako @gmathew127 i have the same problem for months. What app are you using? Thanks
