### ISSUE TITLE
[FEATURE] Get increment merchant listing data report should be supported

### ISSUE THREAD

**Issue by wolgy** [amzn/selling-partner-api-docs#957]
**Describe the improvement**
I found that it always returns the whole data while trying to get a report by GET_MERCHANT_LISTINGS_DATA.
I've tried createReport with dataStartTime and dataEndTime ,but time seems not worked.So as createReportSchedule.

I think that it is not necessary to return all listings in every report.

It would make some trouble when the dataset is huge.

All we need is just the listings whitch changed during the time range provided.

I sincerely hope that there is a way to achive this.Thanks

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md

**Comment by stefnats** [comment]
I agree that this would make sense but as far as i know is not supported. I'm curious what Amazon has to say to this.

It sounds like you're having trouble with huge CSV files, therefore you should overthink the way you parse those files.
Maybe you could chunk those (say, read 1000 lines, process them, read the next 1000 lines etc.)

**Comment by wolgy** [comment]
> I agree that this would make sense but as far as i know is not supported. I'm curious what Amazon has to say to this.
> 
> It sounds like you're having trouble with huge CSV files, therefore you should overthink the way you parse those files.
> Maybe you could chunk those (say, read 1000 lines, process them, read the next 1000 lines etc.)

It could be some other troubles,such as plenty of unnecessary workflow processes and API calls.

And thanks for the suggestion.
