### ISSUE TITLE
I'm going crazy,  Access to requested resource is denied

### ISSUE THREAD

**Issue by userbabu** [amzn/selling-partner-api-docs#958]
I'm going crazy, we have checked all the information, and all the authorization information has been filled in (what would I think my information is correct? Because I modify any of the parameters and cause other errors, such as parameter errors, etc.) so I The submitted information is correct, and the seller account has been authorized, but it still shows Access to requested resource is denied

The returned information is: {"message": "Access to requested resource is denied.", "code": "Unauthorized"}
Submitted interface: https://sandbox.sellingpartnerapi-na.amazon.com/sellers/v1/marketplaceParticipations

**Comment by userbabu** [comment]
After hard work, finally solved. Thanks to Amazon

**Comment by phpandrew** [comment]
> After hard work, finally solved. Thanks to Amazon

What did you do to solve this issue?

**Comment by ajayak** [comment]
@userbabu how did you manage to fix this? I followed the docs and now I'm stuck with this error
