### ISSUE TITLE
[FEATURE] Can a Hybrid SP-API app get RDTs for existing sellers without needing to re-authorize.

### ISSUE THREAD

**Issue by turnerror** [amzn/selling-partner-api-docs#961]
I have a question that isn't explicitly clear to me from the documentation.

Say you are an existing MWS application looking to convert to a hybrid SP-API application as you use some of the endpoints which will be deprecated and made restricted. And this MWS application already has a lot of sellers who provided MWS Auth Tokens in order to act on their behalf. We can use the Authorization API to automatically get the new LWA Access/Refresh Tokens and not require our clients to reauthenticate.

However, with the introduction of RDTs (Restricted Data Tokens), my question is, will we be able to get RDTs as well for these existing sellers without needing to have them re-authorize us to access this now restricted information?

Thank you for your time and I am sorry if I missed if this was stated somewhere on the docs... I've already spent quite a while trying to find the answer to this.

**Comment by norbertmwk** [comment]
@turnerror you can use [Authorization API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/authorization-api-use-case-guide/authorization-api-use-case-guide-v1.md) to exchange existing MWS tokens into SP API LWA Code (which later you exchange for SP API Access token). 
This operation does not invalid or change existing MWS Token.
