### ISSUE TITLE
About Fulfillment Inbound API

### ISSUE THREAD

**Issue by 854350999** [amzn/selling-partner-api-docs#963]
I am trying to call the ```Fulfillment Inbound API```. When I call ```getShipments``` in it, after I specify the ```MarketplaceId(A1RKKUPIHCS9HS)``` of a ```certain country(ES)```, he still returns me the data of the entire region(EU). I think this MarketplaceId does not work in this ```interface```.

**Comment by 854350999** [comment]
By the way, can I know which country the inbound shipments of a certain shipmentId belong to? Through which interface? 


Best regards!

**Comment by houyingkun** [comment]
Got the same problem and need help.
