### ISSUE TITLE
 Python implementation using the SP-API wrapper.

### ISSUE THREAD

**Issue by haiderasad** [amzn/selling-partner-api-docs#968]
Hey i am trying to call spapi from my python script, following procedures have been implemented but no success

1)Amazon guide on github
2)Creating a new app with USER ARN not the role ARN    -nosuccess
    -then attaching the SellerApi policy to the User in AWS -nosuccess
    -then removing the STS policy from user  -nosuccess
    -add the AMAZONAPIGATEWAYINVOKEFULLACCESS from permissions to the user -nosuccess

AWS and SP API Setup

1. User set up in AWS with the following policies attached:

STS Policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sts:GetSessionToken",
                "sts:DecodeAuthorizationMessage",
                "sts:GetAccessKeyInfo",
                "sts:GetCallerIdentity",
                "sts:GetServiceBearerToken"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": [
                "arn:aws:iam::390828649157:user/*",
                "arn:aws:iam::390828649157:role/*"
            ]
        }
    ]
}

SellingPartnerAPI Policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:::*"
        }
    ]
}

AmazonAPIGatewayAdministrator

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "apigateway:*"
            ],
            "Resource": "arn:aws:apigateway:::/"
        }
    ]
}

AmazonAPIGatewayInvokeFullAccess

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "execute-api:Invoke",
                "execute-api:ManageConnections"
            ],
            "Resource": "arn:aws:execute-api:::*"
        }
    ]
}

I have created an app in developer central using my user IAM ARM. 

I am using the following code

```
`from sp_api.api import Orders
from sp_api.api import Reports
from sp_api.api import Feeds
import datetime
from datetime import timedelta
from datetime import datetime
from sp_api.api import Orders
from sp_api.api import Reports
from sp_api.api import Feeds
from sp_api.base.reportTypes import ReportType

credentials=dict(
        refresh_token='abc',
        lwa_app_id='amzn1.sp.solution.abc',
        lwa_client_secret='dsfsf',
        aws_secret_key='abc',
        aws_access_key='abc',
        role_arn='arn:aws:iam::1234566..:user/',
    )

createReportResponse = Reports(credentials=credentials).create_report(reportType=ReportType.GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING)
`
```

 and receiving the following error:

`AuthorizationError: ('invalid_client', 'Client authentication failed', 401)`

**Comment by stefnats** [comment]
I think this is the wrong place to ask, please consider asking in the repo for the python wrapper.
This seems kind of related and leads to the conclusion that User ARN is not supported:

https://github.com/saleweaver/python-amazon-sp-api/issues/74

**Comment by rugved1991** [comment]
Hi @haiderasad,

Check out the new Selling Partner API on AWS QuickStart for a quick setup of SP APIs using Python Lambda.
https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

Feel free to open issues or provide feedback on the issues page of the QuickStart.

Thanks,
Rugved
Solutions Architect, SP API.
