### ISSUE TITLE
Europe - Unauthorized

### ISSUE THREAD

**Issue by aspence07** [amzn/selling-partner-api-docs#972]
I am able to successfully make calls to the US SPAPI endpoint.

I'm trying to accomplish the same for the EU / UK.

I'm getting the same 'Unauthorized' response that many other people here have reported.

A few questions:

1. On the EU Seller Central site, on the Developer Central page, should I re-use the same Developer ID that my company uses for the US? Or should there be a separate Developer ID for the EU?

2. Can I re-use the same AWS IAM and Role ARN credentials for the EU?

3. Is this the correct Auth URL for the EU? :          https://api.amazon.com/auth/o2/token

**Comment by aspence07** [comment]
I figured out in another thread that the sub-API I was trying to call, the FBA Inventory API, is not implemented for Europe yet:

https://github.com/amzn/selling-partner-api-docs/issues/650

To potentially save other people the pain I went through, I'll answer my own questions from above:

1. same dev ID
2. yes
3. yes

**Comment by xbaha** [comment]
Thank you for answering your questions, saves me time, but I want to confirm back on 1, how do you use the same developer ID that exists on the US market in EU market???
