### ISSUE TITLE
 Access to the resource is forbidden

### ISSUE THREAD

**Issue by LuisRosasGaspar** [amzn/selling-partner-api-docs#974]
Hi folks,
I started to have this issue when requesting reports to the API, yesterday was working fine, and today i'm having issues, i did confirm that my accesKey and secretKey are updated and my refresh token is also working, i can get new access token for reports but when i try to request a new report i keep getting this message.
{'errors': [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]}
Thanks

**Comment by parvathm** [comment]
Hi @LuisRosasGaspar ,

We are have added few FAQs [here](https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs) that might help troubleshooting your issue. If you did not find anything that is relevant to your issue please open a [support case ](https://sellercentral.amazon.com/gp/mws/contactus.html?) with request id and time stamp details and provide us the case id.

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by teddy-codes** [comment]
Make sure that you are assuming the role #52.

This was a problem that I had recently.
