### ISSUE TITLE
Why has this application been under review?

### ISSUE THREAD

**Issue by WXinFfly** [amzn/selling-partner-api-docs#978]
Hello @ShivikaK 
      My app ID is amzn1.sellerapps.app.01bd19b4-07f6-47bd-97bc-c6d937760fd2. Why has this application been under review? I saw a case in the store backstage, and no one responded to me. what should I do?

**Comment by ezpinsky** [comment]
Keep replying to the case once a day asking for an update on it. Unless you bother them about responding to you they will take their time to respond.

**Comment by ShivikaK** [comment]
Hello @WXinFfly 

Thank you for raising this issue.

Can you please share the case ID created for application review?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jchavest13** [comment]
Hi @WXinFfly,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by WXinFfly** [comment]
> Hi @WXinFfly,
> 
> Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?
> 
> Regards,
> Julian
> Developer Registration Specialist, SP-API
Hi @jchavest13 

case Id is 8419384021

**Comment by WXinFfly** [comment]
> 你好@WXinFfly
> 
> 感谢您提出此问题。
> 
> 您能分享为申请审查创建的案例ID吗？
> 
> 谢谢，
> 希维卡·卡
> 雷销售合作伙伴API开发人员支持

case Id is 8419384021

> Hello @WXinFfly
> 
> Thank you for raising this issue.
> 
> Can you please share the case ID created for application review?
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Hi @ShivikaK 

case Id is 8419384021

**Comment by WXinFfly** [comment]
> Hello @WXinFfly
> 
> Thank you for raising this issue.
> 
> Can you please share the case ID created for application review?
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support
Hi @ShivikaK 
case Id is 8419384021

**Comment by WXinFfly** [comment]
Hi @ShivikaK 
Is there a problem with the case ID 8419384021? No one can help me deal with the problem

**Comment by jchavest13** [comment]
Hi @WXinFfly,

I have created an internal request to the team working with the Appstore, so they expedite your case review. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by metaprice** [comment]
Hello @jchavest13 ,

could you please have a look at case id: 7670038762 ?

We are waiting for our Application Approval to start with our business.

Thank you
