### ISSUE TITLE
How to publish products on Amazon with SP-API?

### ISSUE THREAD

**Issue by roger-sanchez117** [amzn/selling-partner-api-docs#98]
Hi!

I am new to the consumption of this type of API's and I need to publish products for sale on Amazon.

What API should I consume?
What is the process that I should follow?

I thank you very much in advance for your help and comments.

**Comment by charliecode** [comment]
Hello @roger-sanchez117. I would encourage you to [read over the developer guide really well](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md) as the SP-API takes a good amount of forethought and effort. If you're wondering which API to use in a given situation [the references](https://github.com/amzn/selling-partner-api-docs/tree/main/references) are a great place to dive into as they explain every API in detail. There are also some [use case guides](https://github.com/amzn/selling-partner-api-docs/tree/main/guides/use-case-guides) for certain aspects of the API which go into further detail. Really the [main readme](https://github.com/amzn/selling-partner-api-docs) is a great place to start as it also explains and gives direction on how to create your languages client based off [the OpenAPI specification models](https://github.com/amzn/selling-partner-api-models/tree/main/models) as well.
