### ISSUE TITLE
Token duration is 25 minutes error in /finances/v0/financialEvents 

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#981]
Getting below error in **/finances/v0/financialEvents** API, When requesting with Next Token. Can anyone explain what happens here? 

```
"error":[
{
"code":"InvalidInput",
"message":"Token is not valid, token duration is 25 minutes.",
"details":""
}
];
```

**Comment by cgaugel** [comment]
The NextToken is only valid for 25 minutes. Here are a lot of BUGs regarding this problem but they don't care

**Comment by stefnats** [comment]
Hey @Nilanth have you tried setting a smaller PostedBefore/PostedAfter range? This could help that restriction.

**Comment by liyouzhuo** [comment]
The same for me

**Comment by ruslan-khomiak** [comment]
I have the same

**Comment by Javadebi** [comment]
> Getting below error in **/finances/v0/financialEvents** API, When requesting with Next Token. Can anyone explain what happens here?
> 
> ```
> "error":[
> {
> "code":"InvalidInput",
> "message":"Token is not valid, token duration is 25 minutes.",
> "details":""
> }
> ];
> ```

did you fix the issue?

**Comment by JsonSong89** [comment]
wt~ 
now the error is 
`Token is not valid, token duration is 3 minutes.`
