### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by mrkph** [amzn/selling-partner-api-docs#983]
I use reports-api and the following report is returned

class GetReportResponse {
    payload: class Report {
        marketplaceIds: [ATVPDKIKX0DER]
        reportId: 54652018811
        reportType: GET_SELLER_FEEDBACK_DATA
        dataStartTime: 2021-07-03T03:48:08Z
        dataEndTime: 2021-07-03T03:48:08Z
        reportScheduleId: null
        createdTime: 2021-07-03T03:48:08Z
        processingStatus: IN_PROGRESS
        processingStartTime: 2021-07-03T03:48:14Z
        processingEndTime: null
        reportDocumentId: null
    }
    errors: null
}

io.swagger.client.ApiException: Missing the required parameter 'reportDocumentId' when calling getReportDocument(Async)

What is the reason？

**Comment by csx-java** [comment]
Excuse me, do you have this problem？
![image](https://user-images.githubusercontent.com/31872268/124342541-32c35800-dbf7-11eb-957d-2cbd516a3356.png)

**Comment by dobariyarakesh** [comment]
@csx-java You setup your ReportApi endpoint wrong. I already implemented report API in java spring boot let me know if you need.

@mrkph There is use case for report Make sure you follow the steps

**Comment by stefnats** [comment]
@mrkph you seem to try downloading a report that is not finished yet (`processingStatus: IN_PROGRESS`), thus the `reportDocumentId` is still `null`. You have to wait until the status is `DONE` - you will receive the document id that you can use to call the `getReportDocument` endpoint.
