### ISSUE TITLE
[BUG] GET_FLAT_FILE_OPEN_LISTINGS_DATA Inventory Report quantity not available 

### ISSUE THREAD

**Issue by dobariyarakesh** [amzn/selling-partner-api-docs#986]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
GET_FLAT_FILE_OPEN_LISTINGS_DATA Inventory Report quantity not available 

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#inventory-reports

**Description of what the documentation currently says**
Tab-delimited flat file open listings report that contains a summary of the seller's product listings with the price and quantity for each SKU. For Marketplace and Seller Central sellers.

**Description of what the documentation should say**

**Screenshots**
![image](https://user-images.githubusercontent.com/84843030/124401408-0880b000-dd47-11eb-90e7-d290e5fa2ea6.png)

**Additional context**

**Comment by dobariyarakesh** [comment]
Also seller account is FBA.

**Comment by stefnats** [comment]
This reportType does not return FBA Quantities. You need to request ReportType = `GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA` to retrieve fba / afn quantities.

**Comment by dobariyarakesh** [comment]
@stefnats Thanks for the reply but currently I am using GET_AFN_INVENTORY_DATA and able to get the AFN inventory.

**Comment by stefnats** [comment]
Yes, that's also a possibility!
