### ISSUE TITLE
CustomError: Access to requested resource is denied. Code: 'Unauthorized' 

### ISSUE THREAD

**Issue by huybui-hubt** [amzn/selling-partner-api-docs#987]
Hi forks,
I'm getting error above when  try to get orders with sandbox mode after completing registration successfully.

Application ID: amzn1.sellerapps.app.e2cc381c-ee0b-4309-8d8a-6b6fce08cb75
Request ID: 'cba25144-063d-4e73-bc8e-6d6bdbcef70d'
Request Date: 1625460588000
API operation: 'getOrders'
Error response received: 
```
CustomError: Access to requested resource is denied.
    at SellingPartner.callAPI (<PATH>/node_modules/amazon-sp-api/lib/SellingPartner.js:572:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async <PATH>/index.js:76:24 {
  code: 'Unauthorized',
  details: '',
  type: 'error'
}
```

```
try {
        const result = await client.callAPI({
            operation: "getOrders",
            endpoint: "orders",
            query: {
                CreatedAfter: "TEST_CASE_200",
                MarketplaceIds: "ATVPDKIKX0DER",
            },
        });
        console.log(result);
    } catch (error) {
        console.log(error);
    }
```

**Comment by EnriqueF97** [comment]
Have the same error, but on reports. I think there are like 5 possts of the same issue without a clear solution.

**Comment by teddy-codes** [comment]
If you have created the iam role and linked that role to your user, you have to be sure to assume that role prior to actually calling the api. This will give you a security token that you provide in the header as well as credentials that you use to sign the request instead of your user credentials.

**Comment by huybui-hubt** [comment]
@teddy-codes I'm using @aws-sdk/client-sts for Node.js and try to assumeRole and i got response with Credentials but when i using this Credentials Amazon return invalid token error
