### ISSUE TITLE
Report error     /feeds/2021-06-30/documents   

### ISSUE THREAD

**Issue by yao657355700** [amzn/selling-partner-api-docs#998]
POST
/feeds/2021-06-30/documents

content-type:application/x-www-form-urlencoded; charset=utf-8
host:sellingpartnerapi-eu.amazon.com
user-agent:My (Language=PHP/7.1.16;)
x-amz-date:20210707T095648Z

content-type;host;user-agent;x-amz-date
1fc8d63a192e5485606a3c7241233f568b29d2011c33526cb8502570075694d2

text ： {"body":{"contentType":"text\/tab-separated-values;charset=UTF-8"}}

Error：
"errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]

**Comment by ShivikaK** [comment]
Hello @yao657355700 

Thank you for raising this issue.

The new Feeds and Reports API endpoint is not yet live. Please use the existing endpoint for the API requests.

We will be providing the new updated timeline soon.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by yao657355700** [comment]
> Hello @yao657355700
> 
> Thank you for raising this issue.
> 
> The new Feeds and Reports API endpoint is not yet live. Please use the existing endpoint for the API requests.
> 
> We will be providing the new updated timeline soon.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

**Comment by yao657355700** [comment]
我换成这个  /feeds/2020-09-04/documents
现在一直报错这个：
 "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
