### ISSUE TITLE
Can i get other seller's price by SP-API

### ISSUE THREAD

**Issue by PG408** [amzn/selling-partner-api-docs#999]
As the title said.

**Comment by johnkw** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md

**Comment by PG408** [comment]
> https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md

thank you a lot, I find it

**Comment by johnkw** [comment]
Please close this ticket.
